aptos-labs/aptos-core

aptos-move/e2e-move-tests/src/aggregator.rs, aptos-move/e2e-move-tests/src/aggregator_v2.rs, aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/sources/aggregator_v2_test.move, aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs, aptos-move/e2e-tests/src/executor.rs
Previously we were only doing transactions from single account, so if they were executed speculatively, they would fail on SEQUENCE_NUMBER_TOO_NEW. modifying to use different account for each transaction, so all can happen in parallel.
adding all modes that currently work
=> Improve agg v2 e2e tests

.github/workflows/docker-build-test.yaml
When we are debugging a PR, we mostly want only the forge e2e test to run, so this PR introduces a new GH PR label to run just that test and defer the compat and framework upgrade tests.
=> [gha] label to trigger forge e2e perf test only

Cargo.lock, aptos-node/src/state_sync.rs, config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/error.rs, state-sync/data-streaming-service/Cargo.toml, state-sync/data-streaming-service/src/data_notification.rs, state-sync/data-streaming-service/src/data_stream.rs, state-sync/data-streaming-service/src/metrics.rs, state-sync/data-streaming-service/src/stream_engine.rs, state-sync/data-streaming-service/src/streaming_service.rs, state-sync/data-streaming-service/src/tests/data_stream.rs, state-sync/data-streaming-service/src/tests/streaming_service.rs
This PR updates the data streaming service in state sync to support early termination of lagging subscription streams. This is useful for subscription streams that cause peers to lag behind the rest of the chain (e.g., if the network channel used by the stream is slow or faulty, or if the peer serving the subscription stream is actively malicious). In these cases, the data streaming service will monitor the lag of a subscription stream and terminate the stream prematurely, iff: (i) the stream is lagging for too long; and (ii) the lag has increased since the last check (indicating that the lag is getting worse and the stream is falling behind).
Note: to avoid being overly aggressive, we don't terminate subscriptions streams that lag temporarily, exhibit a "bounded" lag (that doesn't get …
=> [Data Streaming Service] Support early termination in lagging subscription streams.

aptos-move/aptos-aggregator/src/aggregator_v1_extension.rs, aptos-move/aptos-aggregator/src/delta_change_set.rs, aptos-move/aptos-aggregator/src/resolver.rs, aptos-move/aptos-aggregator/src/tests/types.rs, aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/output.rs, aptos-move/aptos-vm-types/src/resolver.rs, aptos-move/aptos-vm-types/src/tests/test_change_set.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/move_vm_ext/resolver.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/aptos-vm/src/storage_adapter/executor_view_base.rs, aptos-move/block-executor/src/errors.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/view.rs, aptos-move/framework/src/natives/aggregator_natives/aggregator.rs, aptos-move/framework/src/natives/aggregator_natives/aggregator_factory.rs, aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs, aptos-move/framework/src/natives/aggregator_natives/context.rs
DelayedFields is an optimization within BlockExecutor.
For resolvers that are not coming from BlockExecutor, they wouldn't know how to handle it - how to do the exchanges or materialize the output. And so add additional function within the TDelayedFieldView - is_delayed_field_optimization_capable - that will tell native code whether it can use delayed fields, or should directly execute operations on move values.
=> [agg_v2] Use aggregator v2 fallback when resolver is not "delayed field capable"

crates/aptos-rest-client/src/client_builder.rs, crates/aptos/CHANGELOG.md, crates/aptos/src/common/types.rs
This is required as we gradually migrate to use the API gateway.
Note: When rejected, the error message isn't very helpful:
```
"Error": "API error: HTTP error 401 Unauthorized: error decoding response body: EOF while parsing a value at line 1 column 0"
```
I'm not sure right now if this comes from the CLI or the API gateway.
```
$ cargo run -p aptos -- account list --account 0x6a124da893602cf136d600832a7e8946e1f489ad9a8128b9a71b11da456d6630 --url https://api.mainnet.aptoslabs.com
{
"Error": "API error: HTTP error 401 Unauthorized: error decoding response body: EOF while parsing a value at line 1 column 0"
}
```
```
$ cargo run -p aptos -- account list --account 0x6a124da893602cf136d600832a7e8946e1f489ad9a8128b9a71b11da456d6630 --url https://api.mainnet.aptoslabs.com --node-api-key <key> …
```
=> [CLI] Add support for setting an API key

developer-docs-site/docs/sdks/rust-sdk.md
The guidance for the Rust SDK today doesn't actually work out of the box, you need to set tokio_unstable. This PR updates the docs accordingly.
Docs.
=> [Docs] Update SDK usage docs

aptos-move/framework/aptos-token-objects/sources/token.move, developer-docs-site/docs/standards/digital-asset.md
The docs refer to create_from_account but this function is deprecated, so I make them refer to create instead.
Additionally, create_from_account is marked as deprecated but nothing says what to use instead. I add a comment explaining what to do.
As you can see my editor also obliterates trailing spaces, hopefully that's alright. We should probably make the linter do that anyway.
👀
=> Refer to create rather than create_from_account for token v2

api/src/accept_type.rs, api/src/accounts.rs, api/src/basic.rs, api/src/blocks.rs, api/src/context.rs, api/src/events.rs, api/src/index.rs, api/src/state.rs, api/src/transactions.rs, api/src/view_function.rs
This PR makes it that the API handlers use spawn_blocking for any synchronous segments of the inner handler code.
Alternatives that don't really work:
- Make the handlers sync: Poem requires that the handlers be async. Beyond that, some functions are actually properly async, e.g. the submit transaction function, in which the underlying component (mempool) exposes an async interface.
- Macro magic: This would just macro-ify what I'm doing somewhat by hand here. It could work but the downside is you can't do it for the properly async handlers (bc you'd end up calling async functions inside a sync function) and it also puts more stuff inside the spawned task than necessary (e.g. some of the checks for fail points / whether the output style is enabled / some verification stuff).
Fortunately …
=> [Node API] Use spawn_blocking for synchronous work

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/framework/aptos-framework/doc/delegation_pool.md, aptos-move/framework/aptos-framework/doc/staking_contract.md, aptos-move/framework/aptos-framework/doc/vesting.md, aptos-move/framework/aptos-framework/sources/delegation_pool.move, aptos-move/framework/aptos-framework/sources/staking_contract.move, aptos-move/framework/aptos-framework/sources/staking_contract.spec.move, aptos-move/framework/aptos-framework/sources/vesting.move, aptos-move/framework/aptos-framework/sources/vesting.spec.move, aptos-move/framework/aptos-framework/tests/delegation_pool_integration_tests.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, types/src/on_chain_config/aptos_features.rs
This PR allows the operator to set the beneficiary address. This PR implements the AIP-51: https://github.com/aptos-foundation/AIPs/pull/252
=> [Stake] Allow to set the beneficiary for operator

aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
(recreated from https://github.com/aptos-labs/aptos-core/pull/9972, as that got mistakenly closed)
Implements Fungible Asset part of [AIP-43](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-43.md), which increases throughput of minting/burning operations, by using aggregators to concurrently track total supply.
=> Update fungible assets to use Aggregators for concurrent minting/burning

aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/collection.move, aptos-move/framework/aptos-token-objects/sources/token.move, types/src/on_chain_config/aptos_features.rs
(recreated from https://github.com/aptos-labs/aptos-core/pull/9971, as that got mistakenly closed)
Implements Token V2 part of [AIP-43](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-43.md), which increases throughput of minting/burning operations, by using aggregators to concurrently track total supply.
=> Modify TokenV2 to add concurrent way of minting tokens using AggregatorV2

.github/workflows/copy-images-to-dockerhub-release.yaml, docker/release-images.mjs
So we can have a separate indexer GRPC release process. This decouples the versioning of the node and indexer.
This PR introduces the concept of "release groups" within the release-images.mjs tool, which groups together images that are released together.
* aptos-node: validator (incl. validator-testing), faucet, tools
* aptos-indexer-grpc: indexer-grpc
Add a new dry-run mode, and test from there.
Release with aptos network tag. This releases `aptos-node` 
```
$ IMAGE_TAG_PREFIX=devnet AWS_ACCOUNT_ID=bla GCP_DOCKER_ARTIFACT_REPO_US=bla GCP_DOCKER_ARTIFACT_REPO=bla GIT_SHA=bla ./docker/release-images.mjs --wait-for-image-seconds=3600 --dry-run
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 386ms
$ command -v crane
/opt/homebrew/bin/crane
INFO: dry run: true …
```
=> [docker] release aptos-node and aptos-indexer-grpc separately

Cargo.lock, crates/aptos-admin-service/Cargo.toml, crates/aptos/src/node/local_testnet/docker.rs
We were relying on deps without gating them by target OS.
I also fix a warning that only happens on Windows.
Built on Windows successfully. CI for the rest.
=> Fix aptos-admin-service build on Windows

crates/aptos-genesis/src/config.rs, crates/aptos/src/genesis/mod.rs, terraform/helm/genesis/templates/genesis.yaml, terraform/helm/genesis/values.yaml, testsuite/forge-cli/src/main.rs
This PR enables setting on-chain consensus config in Forge tests as part of the genesis config.
Test in Forge
=> [forge] Ability to set onchain config in tests

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-emitter-lib/src/lib.rs, crates/transaction-emitter-lib/src/wrappers.rs, crates/transaction-emitter/src/main.rs, ecosystem/node-checker/src/checker/tps.rs
Account creation is a pretty expensive part of the emitter, so allow reuse. Note, the seed allows re-creation of all private keys of the test accounts, so must be kept safe (e.g., in gcloud secrets).
Also create an exclusive `create-accounts` mode for separating out account creation and thus making it easier to exactly specify the gas to use in each step.
Run `% cargo run -p aptos-transaction-emitter --release -- create-accounts -t https://fullnode.testnet.aptoslabs.com --coin-source-key ${APT_KEY} --chain-id testnet --count 1 --max-gas-per-txn 1009` and check output via explorer.
=> [txn emitter] allow reuse of accounts using seed, also add a mode to exclusively create accounts

crates/aptos-logger/src/aptos_logger.rs, crates/aptos-logger/src/event.rs
Avoid printing too much.
Unit test.
=> [aptos-logger] truncate long log messages and field values

Cargo.lock, Cargo.toml, state-sync/storage-service/server/Cargo.toml, state-sync/storage-service/server/src/handler.rs, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/metrics.rs, state-sync/storage-service/server/src/moderator.rs, state-sync/storage-service/server/src/optimistic_fetch.rs, state-sync/storage-service/server/src/subscription.rs, state-sync/storage-service/server/src/tests/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/request_moderator.rs, state-sync/storage-service/server/src/tests/subscription.rs, state-sync/storage-service/server/src/utils.rs
This PR makes several small improvements to the storage service, each in their own commits:
1. Add additional latency metrics to request handling.
2. Replace `RwLock<HashMap<T>>` with `DashMap<T>` in the request moderator.
3. Replace `LRUCache` with a more efficient concurrent cache (to avoid a single `Mutex`).
=> [Storage Service] Small improvements to storage service.

.github/workflows/windows-build.yaml
Our time is valuable, finding changes that broke the Windows CLI build after the fact requires much more time than just preventing it in the first place. Let's just run the Windows CLI build on every PR.
Once this looks good for a while I'll make it land blocking.
CI
=> [CLI] Run Windows build CI on every PR and on main

aptos-move/framework/aptos-framework/doc/coin.md, aptos-move/framework/aptos-framework/doc/managed_coin.md, aptos-move/framework/aptos-framework/doc/optional_aggregator.md, aptos-move/framework/aptos-framework/doc/stake.md, aptos-move/framework/aptos-framework/doc/timestamp.md, aptos-move/framework/aptos-framework/doc/transaction_fee.md, aptos-move/framework/aptos-framework/doc/transaction_validation.md, aptos-move/framework/aptos-framework/doc/util.md, aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.spec.move, aptos-move/framework/aptos-framework/sources/coin.spec.move, aptos-move/framework/aptos-framework/sources/managed_coin.spec.move, aptos-move/framework/aptos-framework/sources/stake.spec.move, aptos-move/framework/aptos-framework/sources/timestamp.spec.move, aptos-move/framework/aptos-framework/sources/transaction_fee.spec.move, aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move, aptos-move/framework/aptos-framework/sources/util.spec.move
1. Add concrete `aborts_if` clauses in the `mint` function in `coin`. Update the specification for all the functions that call `coin::mint`.
2. Add functional specification for the `mint` function in `managed_coin` to ensure that minted coins are deposited to the provided destination address.
3. Add functional specification for the `register` function in `managed_coin` to ensure that the registered account exists after the function call.
4. Add requirement for the `address_from_bytes` function in `util` to ensure that address input bytes are exactly 32 bytes long. This is an abstract specification and the soundness of this abstraction depends on the native function. If length of address input bytes is not 32, the deserialization will fail. See …
=> [spec] specify functions in framework modules

aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, types/src/on_chain_config/aptos_features.rs
Correct the feature number for `LIMIT_MAX_IDENTIFIER_LENGTH` to be consistent to that of the `main` branch
=> Correct the feature number for `LIMIT_MAX_IDENTIFIER_LENGTH`

Cargo.lock, crates/aptos-drop-helper/src/lib.rs, storage/scratchpad/Cargo.toml, storage/scratchpad/src/sparse_merkle/mod.rs, storage/scratchpad/src/sparse_merkle/node.rs, storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs, storage/scratchpad/src/sparse_merkle/test_utils/proptest_helpers.rs, storage/scratchpad/src/sparse_merkle/updater.rs
hen a old SMT drops late (many descendants droped early), a long chain
of `Inner`s drop sequantially in the current implementation. This Makes that
concurrent.
=> drop smt in parallel

Cargo.lock, crates/aptos-drop-helper/Cargo.toml, crates/aptos-drop-helper/src/async_concurrent_dropper.rs, crates/aptos-drop-helper/src/async_drop_queue.rs, crates/aptos-drop-helper/src/lib.rs, execution/executor-types/src/in_memory_state_calculator.rs, execution/executor/src/components/block_tree/mod.rs, execution/executor/src/components/in_memory_state_calculator_v2.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/state_store/buffered_state.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_merkle_batch_committer.rs, storage/aptosdb/src/state_store/state_snapshot_committer.rs, storage/aptosdb/src/test_helper.rs, storage/scratchpad/Cargo.toml, storage/scratchpad/src/lib.rs, storage/scratchpad/src/sparse_merkle/ancestors.rs, storage/scratchpad/src/sparse_merkle/mod.rs, storage/storage-interface/src/cached_state_view.rs, storage/storage-interface/src/lib.rs, storage/storage-interface/src/state_delta.rs
Now that ledger update is a seperate stage, the oldest ancester is held                                                                                                                                  from multiple threads, which can result in it not being freed when the                                                                                                                                   pipeline is busy.    
On certain machines where we used to observe high memory usage, it's now good.
Local benchmark runs didn't observe regression.
Unit tests.
=>  FrozenSmt not holding oldest ancester 

.github/workflows/docker-build-test.yaml, docker/compose/indexer-grpc/data-service-config.yaml, testsuite/indexer_grpc_local.py
From the logs of a failed run (from https://github.com/aptos-labs/aptos-core/actions/runs/6642204051/job/18047211693?pr=10602) I saw this:
```
indexer-grpc-indexer-grpc-data-service-1 | Caused by:
indexer-grpc-indexer-grpc-data-service-1 |     disable_auth_check is not set but whitelisted_auth_tokens is empty
indexer-grpc-indexer-grpc-data-service-1 | Error: Config did not pass validation
```
The script was also using the wrong proto path.
After fixing those the test passes.
See that it passes in CI.
=> Add indexer-grpc test back unbroken

Cargo.lock, third_party/move/move-vm/runtime/Cargo.toml, third_party/move/move-vm/runtime/src/data_cache.rs, third_party/move/move-vm/runtime/src/loader/mod.rs, third_party/move/move-vm/runtime/src/loader/type_loader.rs, third_party/move/move-vm/types/Cargo.toml, third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
Use back btreemap to replace hashmap due to potential non-determinism concern. Also use bit vector to replace the inefficient Vec<bool>
We should run a replay on this.
=> [move-vm] Remove hashmap

ecosystem/indexer-grpc/indexer-grpc-data-access/src/in_memory_storage/storage.rs
^ 
Tested locally and it passed. Root cause is the other thread is not yielding in time, which delays the update operation. Extend the waiting time to allow more time for yielding.
=> [tests] fix the flaky tests for indexer grpc.

Cargo.lock, Cargo.toml, aptos-node/src/lib.rs, aptos-node/src/services.rs, consensus/src/consensus_provider.rs, consensus/src/lib.rs, consensus/src/quorum_store/mod.rs, consensus/src/quorum_store/quorum_store_db.rs, consensus/src/quorum_store/types.rs, crates/aptos-admin-service/Cargo.toml, crates/aptos-admin-service/src/server/consensus/mod.rs, crates/aptos-admin-service/src/server/mod.rs, crates/aptos-admin-service/src/server/utils.rs
Added 3 endpoints:
`/debug/consensus/consensusdb`: dump everything in consensus db.
`/debug/consensus/quorumstoredb`: dump all quorum store batchs, also a query param `digest` is supported for dumping a single batch.
`/debug/consensus/block`: dump all blocks in consensus, also a query param `block_id` is supported for dumping a single block.
Manually tested on a local test node.
=> [AdminService] Add several debug APIs to dump consensus data.

.github/workflows/copy-images-to-dockerhub-release.yaml, .github/workflows/docker-build-test.yaml
Similar to aptos-node, for grpc images:
* release network-specific images when `aptos-indexer-grpc-{devnet,testnet,mainnet}` branch is cut. These images are no longer released on `{devnet,testnet,mainnet}` branch cut
* release versioned X.Y.Z images when `aptos-indexer-grpc-vX.Y.Z` git tag is created
CI
=> [gha] release network-specific grpc images

aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/collection.move, aptos-move/framework/aptos-token-objects/sources/token.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
e2e indexer tests failed because CONCURRENT_ASSETS flag was made default and so enabled for testing (not for release)
redo the identical PR (https://github.com/aptos-labs/aptos-core/pull/10632), without making CONCURRENT_ASSETS default
=> re-revert  Modify TokenV2 to add concurrent way of minting tokens using AggregarorV2

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/errors.rs, third_party/move/move-vm/runtime/src/data_cache.rs
Previously we (over)used STORAGE_ERROR for speculation failures, and so we needed to ignore all STORAGE_ERRORs
We created special errors - SPECULATIVE_EXECUTION_ABORT_ERROR, to disambiguate from other STORAGE_ERRORs, and stopped ignoring STORAGE_ERRORs
Unfortunately get_resource_bytes_with_metadata_and_layout wraps the inner error, and the caller cannot distinguish, and just throws STORAGE_ERROR instead, making STORAGE_ERROR still being created for speculative errors, causing alert to fire.
Reverting to ignore STORAGE_ERRORs for now, but we need to propagate inner errors better in get_resource_bytes_with_metadata_and_layout longterm
=> Continue ignoring STORAGE_ERROR until full cleanup

crates/aptos-drop-helper/src/async_concurrent_dropper.rs, crates/aptos-drop-helper/src/lib.rs, crates/aptos-drop-helper/src/metrics.rs, storage/aptosdb/src/state_store/mod.rs, storage/scratchpad/src/sparse_merkle/ancestors.rs, storage/scratchpad/src/sparse_merkle/dropper.rs, storage/scratchpad/src/sparse_merkle/mod.rs, storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs, storage/scratchpad/src/sparse_merkle/test_utils/proptest_helpers.rs
Making these changes based on the following observations:
1. it's a dead lock harzard to put nested drops onto a bounded concurrency pool
2. in the current mechanism, trees are actually dropped sequentially, because every ref on the chain are held
3. the back pressure being on the committing side is wrong -- more blocks will lock the current base, making it impossible to be really dropped.
In this change:
1. drop the root asynchronously in a different pool (instead of children Inner's). Inner will be blazing fast to drop, and there's no deadlock.
2. back pressure is on the execution side (when trying to ref the base). the committing side is free to move forweard and switch to a newer base as soon as possible.
Unit tests
Artificially increase SubTree drop latency and observe back pressure …
=> AsyncConcurrentDropper: use dedicated pool

ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs, ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs, ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs
Previously, all images were being converted to JPEGs. As a result, any pixels containing alpha are changed into black pixels. This fixes that issue by only converting images to JPEGs if they don't have any pixels containing alpha. 
Tested locally with PNGs containing transparency.
=> [NFT Metadata Crawler] Fix transparency bug

Cargo.lock, Cargo.toml, aptos-node/Cargo.toml, aptos-node/src/lib.rs, crates/aptos-admin-service/Cargo.toml, crates/aptos-admin-service/src/server/mod.rs, crates/aptos-admin-service/src/server/thread_dump.rs, docker/builder/builder.Dockerfile, scripts/dev_setup.sh
Add `/threadz` endpoint to dump stack trace for all threads.
Default libunwind doesn't work well due to a compatibility issue with lld, using libdw instead.
=> [AdminService] Support thread dump.

.github/workflows/coverage.yaml
Update trigger condition to listen for label change in github pull_request event.  Disable the trigger on push event. 
- Coverage job is not triggered in CI without label 
- Coverage job is triggered in CI with label
=> [gha] update code coverage trigger

third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs, third_party/move/move-compiler-v2/src/lib.rs, third_party/move/move-compiler-v2/src/pipeline/mod.rs, third_party/move/move-compiler-v2/src/pipeline/visibility_checker.rs, third_party/move/move-compiler-v2/tests/checking/typing/constant_internal.exp, third_party/move/move-compiler-v2/tests/testsuite.rs, third_party/move/move-compiler-v2/tests/visibility-checker/call_friend_only.exp, third_party/move/move-compiler-v2/tests/visibility-checker/call_friend_only.move, third_party/move/move-compiler-v2/tests/visibility-checker/call_private_function.exp, third_party/move/move-compiler-v2/tests/visibility-checker/call_private_function.move, third_party/move/move-compiler-v2/tests/visibility-checker/constant_use_across_mod.exp, third_party/move/move-compiler-v2/tests/visibility-checker/constant_use_across_mod.move, third_party/move/move-compiler-v2/tests/visibility-checker/main_call_visibility_friend.exp, third_party/move/move-compiler-v2/tests/visibility-checker/main_call_visibility_friend.move, third_party/move/move-compiler-v2/tests/visibility-checker/module_call_visibility_friend.move, third_party/move/move-compiler-v2/tests/visibility-checker/module_call_visibility_friend_invalid.exp, third_party/move/move-compiler-v2/tests/visibility-checker/module_call_visibility_friend_invalid.move, third_party/move/move-model/src/ast.rs, third_party/move/move-model/src/builder/exp_builder.rs, third_party/move/move-model/src/builder/model_builder.rs, third_party/move/move-model/src/builder/module_builder.rs, third_party/move/move-model/src/lib.rs, third_party/move/move-model/src/model.rs
Compiler v2 now checks that function calls and const uses respect visibility rules.
We now do the following checks:
* Private functions cannot be called outside the module
* Public friend functions cannot be be called from non-friend modules.
* Constants can only be used directly within the module.
We perform all the function visibility checks as a pass on the stackless bytecode. However, it is too late to do the constant visibility check at this point, as constants have been converted to their values by then, so this is done at an earlier stage (expression builder when building the move model). @brmataptos : inlining implementation could affect this check - something to keep in mind when that implementation rolls in.
* Various checks on validity of a friend declaration.
* Fixing …
=> Visibility Analysis for compiler v2

aptos-move/aptos-aggregator/src/delta_change_set.rs, aptos-move/aptos-aggregator/src/resolver.rs, aptos-move/aptos-aggregator/src/tests/types.rs, aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/output.rs, aptos-move/aptos-vm-types/src/resolver.rs, aptos-move/aptos-vm-types/src/tests/utils.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/view.rs, aptos-move/framework/src/natives/aggregator_natives/context.rs, aptos-move/mvhashmap/src/types.rs, aptos-move/mvhashmap/src/unit_tests/proptest_types.rs, types/src/transaction/mod.rs, types/src/write_set.rs
Previously, for resources that have aggregators, if only aggregator is modified, they were not being charged, even though they do show up in the transaction output.
So we move figuring out which read-set keys need exchanges from materialization to VMChangeSet creation, so it can be charged appropriately.
e2e aggregator unit tests.
In follow-up, that handles PayloadWriteSet::Direct appropriately, will add comparison tests between aggregators enabled and disabled.
=> [agg_v2] Proper gas charging for writing to resources with aggregators

ecosystem/nft-metadata-crawler-parser/src/utils/uri_parser.rs
Most submitted IPFS asset URIs that use a public gateway are in this format: 
- `https://public.gateway.com/ipfs/<cid>/<path>`
- e.g. https://dweb.link/ipfs/bafybeifdkldssgfrlt4iukpniuq24fugpw53crt5jkchmo3wjypocwzi7y/101
When visited, the previous URI will redirect to this format:
- `https://<cid>.ipfs.public.gateway.com/<path>`
- e.g. https://bafybeifdkldssgfrlt4iukpniuq24fugpw53crt5jkchmo3wjypocwzi7y.ipfs.dweb.link/101
These changes add coverage to the URI Parser for the redirected version and increase the success rate for the parser. 
Added said case to unit tests for URI Parser.
=> [NFT Metadata Crawler] Increase URI Parser coverage for redirected IPFS public gateway URIs

Cargo.lock, config/src/config/execution_config.rs, config/src/config/mod.rs, config/src/config/transaction_filter_type.rs, consensus/Cargo.toml, consensus/src/consensus_provider.rs, consensus/src/epoch_manager.rs, consensus/src/lib.rs, consensus/src/state_computer.rs, consensus/src/transaction_filter/mod.rs
A filter that can be used to allow or deny transactions from being executed. It contains a set
of rules that are evaluated one by one in the order of declaration. If a rule matches, the transaction is either allowed or
denied depending on the rule. If no rule matches, the transaction is allowed. For example a rules might look like this:
```
rules:
- Allow:
Sender: f8871acf2c827d40e23b71f6ff2b9accef8dbb17709b88bd9eb95e6bb748c25a
- Allow:
ModuleAddress: "0000000000000000000000000000000000000000000000000000000000000001"
- Allow:
EntryFunction:
- "0000000000000000000000000000000000000000000000000000000000000001"
- test
- check
- Allow:
EntryFunction:
- "0000000000000000000000000000000000000000000000000000000000000001"
- test
- new
- Deny: All
```
This filter allows transactions from the …
=> [Execution] Add support for configurable transaction filtering

config/src/config/network_config.rs, testsuite/forge-cli/src/main.rs
Tests show that overriding the socket options for send and recv buffer actually hurts performance (even with default linux kernel settings). Logically, this rolls back #4649 but keeping the configs and code around in case this or other socket options are revisited.
New results:
* `net_bench_two_region_env`: 800 KB/s -> 4 MB/s
* `pfn_performance_with_realistic_env`: 4K -> 6K TPS
=> [1.8 cherry pick] [Networking] set TCP buffer overrides to None by default (#10176)

consensus/src/liveness/leader_reputation.rs, consensus/src/liveness/leader_reputation_test.rs, storage/aptosdb/src/db_options.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/schema/block_index/mod.rs, storage/aptosdb/src/schema/block_index/test.rs, storage/aptosdb/src/schema/mod.rs, storage/storage-interface/src/lib.rs
First step to make block as first class concept at storage layer.
- Add a block index CF to store block_height -> version mapping.
- Add an api to return latest NewblockEvents, and change leader reputation to use the new API so it doesn't depend on event indices.
=> [Storage] Add block index support for leader reputation.

Cargo.lock, crates/aptos/Cargo.toml, crates/aptos/src/node/local_testnet/indexer_api.rs
No particular reason for the version bumps, just trying to get the latest and greatest.
Previously I was using the name of the Docker context to figure out if the Docker engine was Docker Desktop or not. Turns out this is not reliable, so I'm using a different field now. 
Works on Mac, if CI passes that means it works on Linux and Windows too.
=> Update version for processor and Hasura console, improve detection of Docker environment

aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/output.rs, aptos-move/aptos-vm-types/src/resource_group_adapter.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs, aptos-move/block-executor/src/errors.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-move-tests/src/aggregator_v2.rs, aptos-move/e2e-move-tests/src/tests/resource_groups.rs, aptos-move/e2e-testsuite/src/tests/genesis.rs, types/src/on_chain_config/aptos_features.rs
We tried using fallback to sequential with dynamic change set capable disabled, but we cannot make that have identical gas charges. 
So cleaning up that code. 
Instead we are going to support PayloadWriteSet only if it is alone in a block.
CI, genesis tests, they were failing before fallback was added.
=> [agg_v2] Cleanup unsuccessful fallback logic

aptos-move/move-examples/cli_args/entry_function_arguments.json, aptos-move/move-examples/cli_args/script_function_arguments.json, aptos-move/move-examples/cli_args/scripts/set_vals.move, aptos-move/move-examples/cli_args/sources/cli_args.move, developer-docs-site/docs/move/move-on-aptos/cli.md
Added missing examples about CLI arguments, such as `hex` and `string`
=> [Doc] Added missing examples for CLI Args

testsuite/forge-cli/src/main.rs
We have been consistently hitting these marks for awhile, so we need to update to avoid silent regressions. Even these are pretty conservative, for now erring on the side of loose thresholds to prevent flakiness.
=> [forge] increase TPS thresholds for realistic_env_max_load_test

crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/wrappers.rs
When using txn emitter on a test network (which has root account), we already have mint_to_root flag to not require user to fund root account manually
enable it for txn emitter, and make it not fail if root account has too much resources to make minting overflow
forge tests use mint_to_root to test the non-failing behavior.
=> set mint to root for txn emitter

Cargo.lock, testsuite/fuzzer/.cargo/config.toml, testsuite/fuzzer/fuzz/Cargo.toml, testsuite/fuzzer/fuzz/fuzz_targets/move/aptosvm_publish_and_run.rs, testsuite/fuzzer/google-oss-fuzz/build.sh, testsuite/fuzzer/repro.sh, testsuite/fuzzer/test-fuzzers.sh, third_party/move/move-binary-format/Cargo.toml, third_party/move/move-binary-format/src/file_format.rs, third_party/move/move-bytecode-verifier/fuzz/Cargo.toml, third_party/move/move-core/types/Cargo.toml, third_party/move/move-core/types/src/language_storage.rs
Adds new AptosVM fuzzer
Features:
* Fuzzing transactions through AptosVM eliminates false positives. (e.g. argument types are properly checked)
* Possible to reach aptos-specific features and adapter code
* Supports multi-module/multi-package fuzzcases
* invariant violations are caught as panics, except for known false positives
* Supports executions with both, entry functions and `CompiledScript`
* `Corpus::Keep`s for various errors can be modified to make libfuzzer not store specific fuzzcases.
Drawbacks:
* More dependencies for the fuzzer, slower compilation
* large input space means harder to mutate inputs
* `./test-fuzzer.sh` passes
=> [Fuzzing] Add AptosVM fuzzer

crates/aptos/CHANGELOG.md, crates/aptos/src/node/local_testnet/docker.rs, crates/aptos/src/node/local_testnet/indexer_api.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/postgres.rs
I finally figured out a way to run the containers such that I don't need to detect the Docker environment (Docker Desktop or not) and change the invocation accordingly. This should make it much more reliable.
Tested manually on MacOS, Linux, Windows (WSL) with this command:
```
```
I also confirmed that running the local testnet from inside a container (with the tools image) still works.
Windows (NT) doesn't seem to be working, but the release version of the CLI is also not working, even without `--with-indexer-api`, so I suspect it has to do with my machine rather than the CLI. Still investigating.
All the failing CI seems unrelated, it has been broken for a while it turns out.
=> [CLI] Make inter container networking more reliable in local testnet

api/doc/spec.json, api/doc/spec.yaml, api/src/context.rs, api/src/transactions.rs, storage/aptosdb/src/lib.rs
1. remove get_account_state: Simulation and get_account_txns API don't rely on the state kv index
2. always write to the state KV index
3. get around that get_block_timestamp breaks with event indices missing
unit tests and local fullnode simulation calls
=> RestAPI: remove get_account_state

.github/workflows/cli-release.yaml, crates/aptos/README.md, developer-docs-site/docs/tools/aptos-cli/install-cli/download-cli-binaries.md, developer-docs-site/docs/tools/aptos-cli/install-cli/index.md
We've learned in the last few months that brew isn't as magic as I thought and every time we release a CLI, someone actually creates a PR to bump the version in homebrew-core manually. This means sometimes it can take a while.
To make this process faster, this PR adds a step to the CLI release that submits that version bump PR automatically.
This PR was opened thanks to the new job added here: https://github.com/Homebrew/homebrew-core/pull/153591.
=> Automatically create PR to bump homebrew version of CLI, don't build MacOS binary

aptos-move/e2e-move-tests/Cargo.toml, aptos-move/e2e-move-tests/proptest-regressions/tests/aggregator.txt, aptos-move/e2e-move-tests/src/aggregator_v2.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/aggregator.rs, aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs, aptos-move/e2e-tests/src/executor.rs
- cleaning up of execution mode - use parallel was confusing - as it was running both sequential and parallel. adding three modes - SequentialOnly, ParallelOnly and BothComparison
- adding ability to execute and check a set of transactions with a given BlockSplit. For tests when block boundary matters (i.e. testing path of reading from storage), ability to vary this easily (via test_case or proptest is useful). provided example from aggregator v1 test.
=> MoveHarness improvements - execution mode and block splitting

crates/transaction-emitter-lib/src/emitter/account_minter.rs
when account-minter-seed is used, the source account is reused as well
testing on previewnet
=> txn-emitter: query source account seq num

crates/aptos/src/move_tool/mod.rs, third_party/move/tools/move-cli/src/base/test.rs
This PR enables the option `--compiler-version` for the command `aptos move test`.
run `aptos move test --compiler-version=v2`
=> [CLI][move-unit-test] Enable compiler-version for aptos move test

third_party/move/move-model/bytecode/src/stackless_bytecode.rs
Stackless bytecode `Operation` variants belonging to the programming and to the verification language were intermixed. This PR reorders them into two separate groups for better documentation.
=> [compiler v2] Reorganize bytecode Operation for better documentation

testsuite/forge/src/backend/local/node.rs, testsuite/smoke-test/Cargo.toml, testsuite/smoke-test/src/genesis.rs
This PR updates the genesis write-set smoke test to: (i) ensure that the config optimizer doesn't block the recovery flow after a genesis write-set transaction is applied to the network and the node restarts; and (ii) verify that the config optimizer does indeed run.
The PR also makes several small readability refactors and comment updates, but nothing should logically change.
=> [Smoke Tests] Clean up the genesis flow test.

config/src/config/secure_backend_config.rs, testsuite/forge/src/backend/local/node.rs, testsuite/forge/src/interface/swarm.rs, testsuite/smoke-test/src/state_sync.rs
Note: this PR is built on: https://github.com/aptos-labs/aptos-core/pull/10763
This PR adds a set of smoke tests to ensure that validator nodes are able to participate in consensus after syncing. This property was temporarily broken for fast syncing validators, so we want to ensure it doesn't happen again.
1. Some small cleanups to the state sync smoke tests. Nothing should change logically -- I've just moved some things around and grouped some logic into functions.
2. Add 4 smoke tests to ensure that validators can participate in consensus after having their DB's wiped and synced. These tests check this property for: (i) fast syncing with epoch changes; (ii) fast syncing without epoch changes; (iii) default syncing with epoch changes; and (iv) default …
=> [Smoke Test] Add smoke tests to ensure validators can participate in consensus after syncing

aptos-move/vm-genesis/src/lib.rs
This PR enables `LIMIT_MAX_IDENTIFIER_LENGTH` in devnet by default.
=> Enables `LIMIT_MAX_IDENTIFIER_LENGTH` in devnet by default

consensus/consensus-types/src/common.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/direct_mempool_quorum_store.rs, consensus/src/quorum_store/tests/batch_generator_test.rs, consensus/src/quorum_store/utils.rs, mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs, mempool/src/shared_mempool/tasks.rs, mempool/src/shared_mempool/types.rs, mempool/src/tests/common.rs, mempool/src/tests/core_mempool_test.rs, mempool/src/tests/mocks.rs, mempool/src/tests/multi_node_test.rs, mempool/src/tests/test_framework.rs
In forge `realistic_network_tuned_for_throughput` it was found that:
* Calling pull takes > 25 ms.
* In an edge case where the pull returns 0 new txns, this could cause livelock because the pull call would be called every 25 ms.
Resolved by:
* Optimizing the pull; now on the same workload the pull takes ~8 ms.
* Instead of using a hashmap, use a sorted vector + binary search for the excluded txns
* And only re-sort the vector when batches in progress is updated (instead of every pull)
* Checking the time taken to pull, and pulling less frequently if the pull takes > 12.5 ms.
Existing tests, ran `realistic_network_tuned_for_throughput` as ad-hoc job and observed results.
=> [quorum store][mempool] optimize pulling txns for when many txns are in progress

config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/tests/priority.rs, state-sync/aptos-data-client/src/tests/utils.rs, state-sync/aptos-data-client/src/utils.rs
This PR makes two modifications to state sync (each in their own commit):
1. Disable subscription syncing by default. For now, it makes sense to utilize optimistic fetching until we've fully stress tested the subscription syncing flows.
2. Improve the peer selection logic for optimistic fetches:
- Currently, we're simply [choosing](https://github.com/aptos-labs/aptos-core/pull/10552) the peer with the lowest distance from the validator set and peer ping latency. While this is optimal for the happy path, it will struggle in the unhappy path (e.g., if the chosen peer is lagging, faulty or malicious).
- To help combat this, we introduce some randomization into the selection logic and instead choose the peer weighted by distance and latency. Note: this is a temporary solution. Eventually, …
=> [State Sync] Disable subscription sync and optimize optimistic fetching

.github/workflows/coverage-move-only.yaml
This PR adds a new CI job `Test Coverage For Move`, which runs `cargo llvm-cov` on move packages only whenever any changes happen in the directory in `third_party/move`. 
Tested by editing a file in the move folder to see whether the job is triggered.
=> [gha] Add a CI job to run llvm-cov for move tests only

consensus/src/liveness/leader_reputation.rs
In https://github.com/aptos-labs/aptos-core/pull/9919 I made the `Display` impl of `AccountAddress` AIP-40 compliant so new users of `AccountAddress` would get compliant behavior by default. In that PR I endeavored to make sure everything that already used `AccountAddress` kept the old behavior. It seems like I missed a spot.
This PR switches the labelling here to use `to_hex` instead of `to_string`. `to_hex` behaves how `to_string` worked before #9919.
CI
=> [Consensus] Label metrics with address in `to_hex` format

consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_state_sync.rs, consensus/src/dag/observability/logging.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/dag/tests/integration_tests.rs
This PR rewrites the DAG state sync mode to making catching up more effective
- It now processes incoming network messages. Fetch and Node messages are ignored. CertifiedNodeMessages are buffered. Also, if we get a CertifiedNodeMsg with 2*window higher round than the current synching target, then we abort the current sync and sync to this new CertifiedNodeMsg.
- If sync is unsuccessful, we keep using the current DAG store and order rule.
- If sync is successful, we rebootstrap all the components including a new DAG store reading from latest storage.
=> [dag] state sync mode rewrite

aptos-move/aptos-vm-types/src/resource_group_adapter.rs, aptos-move/block-executor/src/captured_reads.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs, aptos-move/mvhashmap/src/types.rs, aptos-move/mvhashmap/src/unit_tests/mod.rs, aptos-move/mvhashmap/src/unit_tests/proptest_types.rs, aptos-move/mvhashmap/src/unsync_map.rs, aptos-move/mvhashmap/src/versioned_data.rs, aptos-move/mvhashmap/src/versioned_group_data.rs
If we call resource_exists/get_metadata, we pass None layout, and that gets stored in storage - which is incorrect.
added unit tests to test those, and they were failing.
Adding ValueWithLayout to distinguish whether Layout was known or unknown, and used it for resources. to modify resource groups as well.
Additionally - consolidated logic between sequential and parallel via ResourceState
unit tests that were added.
=> Distinguish between RawFromStorage and Exchanged in view.rs for resources

consensus/src/dag/dag_driver.rs, consensus/src/dag/tests/dag_driver_tests.rs, crates/reliable-broadcast/src/lib.rs
This PR makes fixes some RB bugs.
- It handles any error returned by the remote. Otherwise, sometimes, the loop will exit and execute the `unreachable!` path.
- Abort reliable broadcast handle on DagDriver drop. Otherwise, it will orphan the reliable broadcast task and it will keep trying to broadcast its node.
=> [dag][rb][bugfix] handle error result on rb and drop RB handle properly

aptos-node/src/lib.rs, config/src/config/state_sync_config.rs
This PR:
- Reduces the max state sync pipeline depth from 500 to 50 (to mitigate the OOMing nodes).
- Update validators to use execution mode for syncing (seems like they struggle with networking much more than VFNs).
- Keep VFNs using output syncing (we need the extra CPU for the REST API).
=> [State Sync] Reduce pipeline depth and use execution for validators.

consensus/consensus-types/src/common.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/direct_mempool_quorum_store.rs, consensus/src/quorum_store/tests/batch_generator_test.rs, consensus/src/quorum_store/utils.rs, mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs, mempool/src/shared_mempool/types.rs, mempool/src/tests/common.rs, mempool/src/tests/core_mempool_test.rs, mempool/src/tests/mocks.rs, mempool/src/tests/multi_node_test.rs, mempool/src/tests/test_framework.rs
cherry pick #10744 
In forge `realistic_network_tuned_for_throughput` it was found that:
* Calling pull takes > 25 ms.
* In an edge case where the pull returns 0 new txns, this could cause livelock because the pull call would be called every 25 ms.
Resolved by:
* Optimizing the pull; now on the same workload the pull takes ~8 ms.
* Instead of using a hashmap, use a sorted vector + binary search for the excluded txns
* And only re-sort the vector when batches in progress is updated (instead of every pull)
* Checking the time taken to pull, and pulling less frequently if the pull takes > 12.5 ms.
Existing tests, ran `realistic_network_tuned_for_throughput` as ad-hoc job and observed results.
=> [cherry-pick devnet][quorum store][mempool] optimize pulling txns for when many txns are in progress (#10744)

third_party/move/documentation/coding_guidelines.md
The file `./third_party/move/documentation/coding_guidelines.md` already contains useful guidelines for coding. This PR adds guidelines for code review.
=> [doc] Adding PR guidelines

.github/actions/rust-setup/action.yaml, Cargo.lock, Cargo.toml, api/Cargo.toml, api/doc/spec.json, api/doc/spec.yaml, api/src/view_function.rs, api/types/src/convert.rs, api/types/src/lib.rs, api/types/src/mime_types.rs, api/types/src/view.rs, crates/aptos-bcs-utils/Cargo.toml, crates/aptos-bcs-utils/src/lib.rs, crates/aptos-rest-client/src/lib.rs, testsuite/smoke-test/src/rest_api.rs
This should let users provide any BCS encoded input into the view function. This cleaner interface will make it easier for things like options and other complex inputs.
This is part of a discovery on making changes to the SDK interfacing.  The view functions work differently than transaction submission since they only accept JSON inputs, which make the API a huge mess to work with via the SDK
I added a special function to ensure that outputs were encoded only once in BCS and are easy to decode rather than being wrapped twice.
I added a smoke test to ensure that the encoding is right.
=> [api] Add BCS inputs for View Functions

.github/actions/rust-setup/action.yaml
This reverts commit 82cb76c5ce066f4fc8928569cf989c6c5ab535e7.
Turns out prover needed javascript
=> Revert "[github CI] Remove Javascript from Rust CI"

third_party/move/move-compiler/src/diagnostics/mod.rs, third_party/move/tools/move-cli/src/base/test.rs
Move unit tests continue to run in the presence of compiler warnings, but the warnings are shown.
Existing tests &
```
MOVE_COMPILER_WARN_OF_DEPRECATION_USE=1 WARN_OF_DEPRECATION_USE_IN_APTOS_LIBS=1 cargo test -p aptos-framework --test move_unit_test -- --skip prover
```
=> [Bug] Fix issue 10468

third_party/move/move-compiler-v2/tests/bytecode-generator/inline_specs.exp, third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_inference.exp, third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_inference.move, third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_inference_bitvector.exp, third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_inference_bitvector.move, third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_inference_vector.exp, third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_inference_vector.move, third_party/move/move-compiler-v2/tests/checking/typing/constant_unsupported_exps.exp, third_party/move/move-model/src/ast.rs, third_party/move/move-model/src/builder/exp_builder.rs, third_party/move/move-model/src/builder/module_builder.rs
This closes #10885 and closes #10875 and closes #10874. The fix is a bit more involved as thought because the way how inlined spec blocks are type checked needed to be changed:
- Inlined spec blocks _cannot_ be checked as they appear in the code, since they are not supposed to influence type inference, and since they are designed to work in their own inference context.
- Rather the entire function body needs to be checked first, and then subsequently the spec blocks, each with the context of locals in which they are defined, at a point where the types of the locals have been inferred.
This PR implements this new scheme by collecting spec blocks and only at the end of a function body, post-processes them.
Adds the test from the bug report.
=> [compiler v2] Fixing bug in spec block analysis

third_party/move/evm/move-to-yul/src/functions.rs, third_party/move/move-model/bytecode/src/dataflow_analysis.rs, third_party/move/move-model/bytecode/src/stackless_control_flow_graph.rs
rename StacklessControlFlowGraph::is_dummmy() to is_dummy()
This is just a fix for typo in a function name.
=> rename StacklessControlFlowGraph::is_dummmy() to is_dummy()

Cargo.lock, aptos-move/block-executor/Cargo.toml, aptos-move/block-executor/src/executor.rs
We observed the drop is pretty expensive, doing this in the executor thread can potentially block execution. Use the async dropper instead so that drop can happen in a lower priority thread. 
Existing UTs
=> Use async dropper to drop block executor data

testsuite/forge/src/backend/local/swarm.rs, testsuite/forge/src/interface/node.rs, testsuite/forge/src/interface/swarm.rs, testsuite/smoke-test/src/genesis.rs, testsuite/smoke-test/src/state_sync.rs, testsuite/smoke-test/src/test_utils.rs
This PR adds a new smoke test to verify that fullnodes are also able to bypass a network halt using the same flow as the validators (i.e., manually apply a genesis writeset transaction to the DB to bypass the halt and continue syncing).
Once this lands, I'll work on updating state sync to be able to bypass network halts using only a trusted waypoint, but this test is important because it helps to verify that we always have a manual "working" solution.
=> [Smoke Tests] Add smoke tests for manual fullnode writesets.

state-sync/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-driver/src/error.rs, state-sync/state-sync-driver/src/tests/bootstrapper.rs, state-sync/state-sync-driver/src/tests/utils.rs
Note: most of this PR is just new unit tests.
This PR makes two small modifications to the state sync driver (each in their own commit):
1. Wrap an `info!` log in `sample!` to prevent the log from spamming the output when nodes are unable to identify data in the network.
2. Remove an unnecessary advertised version check. If the local epoch end is higher than the advertised epoch end, and we've verified our waypoint, we should just mark bootstrapping as complete. This prevents us from blocking in the bootstrapping phase if we're ahead of all our peers.
- We also add several simple tests for this logic.
=> [State Sync Driver] Remove unnecessary advertised version check and add tests

third_party/move/move-compiler/src/typing/core.rs, third_party/move/move-compiler/src/typing/expand.rs, third_party/move/move-compiler/tests/move_check/typing/eq_invalid.exp, third_party/move/move-compiler/tests/move_check/typing/exp_list_nested.exp, third_party/move/move-compiler/tests/move_check/typing/exp_list_resource_drop.exp, third_party/move/move-compiler/tests/move_check/typing/ignore_inferred_resource.exp, third_party/move/move-compiler/tests/move_check/typing/invalid_type_acquire.exp, third_party/move/move-compiler/tests/move_check/typing/neq_invalid.exp, third_party/move/move-compiler/tests/move_check/typing/number_literal_too_large.exp, third_party/move/move-compiler/tests/move_check/typing/recursive_local.exp, third_party/move/move-compiler/tests/move_check/typing/uninferred_type_call.exp, third_party/move/move-compiler/tests/move_check/typing/uninferred_type_pack.exp, third_party/move/move-compiler/tests/move_check/typing/uninferred_type_unpack_assign.exp, third_party/move/move-compiler/tests/move_check/typing/uninferred_type_unpack_bind.exp, third_party/move/move-compiler/tests/move_check/typing/uninferred_type_unpack_decl.exp
This improves the compiler error messages when type inference fails by
- removing duplicated error messages for the same uninferred type variable ([uninferred_type_unpack_assign.exp](https://github.com/aptos-labs/aptos-core/compare/main...fEst1ck:aptos-core:better-compiler-err-msg#diff-f1676ba2459a1234f8bb7314ec79fee1ad79868ceace16149c2f5557c1204e3e)).
- telling why we cannot infer; e.g., which generic needs to be provided.
Existing tests of compiler v1.
=> [compiler v1] Better compiler error messages (#9222)

third_party/move/move-compiler/src/diagnostics/mod.rs
If `RUST_BACKTRACE` is set in environment, then add a backtrace to move-compiler diagnostics of severity "Bug".
If `MOVE_COMPILER_DEBUG` is also set, then add a backtrace to every move-compiler diagnostic for debugging.
Manual tests.
=> Add backtrace to compiler errors for debugging

developer-docs-site/docs/tutorials/first-coin.md
Fix typo in a Your First Coin example for python, instead of `your-coin` python module should be named as it is defined in `examples` directory: `your_coin.py`.
=> Update first-coin guide

developer-docs-site/docs/tutorials/first-transaction.md
Replace `~` home related paths for `cd` command with relative to current directory. The user can execute the first command in the guide (`git clone https://github.com/aptos-labs/aptos-core.git`) from any directory, which will result in an error if this directory is not a home directory when the user will try to execute `cd` command, for example for Rust SDK `cd ~/aptos-core/sdk`.
=> Update first-transaction guide with relative cd paths

developer-docs-site/docusaurus.config.js
Search was completely broken, due to API key being rotated and not updated within Docusaurus config. 
Test search functionality with updated key.
=> [docs] Update Algolia key

aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs, aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
- forgot to have a limit on create_snapshot
- forgot to charge length in create_snapshot
- used incorrect gas param for concat call
Since these were never released, we can make these breaking changes
=> [easy] Fix string length agg v2 native charges

Cargo.lock, Cargo.toml, config/src/config/admin_service_config.rs, crates/aptos-admin-service/Cargo.toml, crates/aptos-admin-service/src/server/mod.rs
Allow authentication through query parameter `passcode`.
Manually tested on local net.
=> [AdminService] Implement a naive passcode authentication.

aptos-move/vm-genesis/src/lib.rs
This enables `OPERATOR_BENEFICIARY_CHANGE` in the devnet to release (v1.8.4).
=> Enables `OPERATOR_BENEFICIARY_CHANGE` in devnet by default

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/framework/aptos-framework/doc/delegation_pool.md, aptos-move/framework/aptos-framework/doc/staking_contract.md, aptos-move/framework/aptos-framework/doc/vesting.md, aptos-move/framework/aptos-framework/sources/delegation_pool.move, aptos-move/framework/aptos-framework/sources/staking_contract.move, aptos-move/framework/aptos-framework/sources/staking_contract.spec.move, aptos-move/framework/aptos-framework/sources/vesting.move, aptos-move/framework/aptos-framework/sources/vesting.spec.move, aptos-move/framework/aptos-framework/tests/delegation_pool_integration_tests.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
This PR cherry-picks:
* [Stake] Allow to set the beneficiary for operator: https://github.com/aptos-labs/aptos-core/pull/10455
* Enables `OPERATOR_BENEFICIARY_CHANGE` in devnet by default  https://github.com/aptos-labs/aptos-core/pull/11029
This PR also cherry-picks the following PR to enable `LIMIT_MAX_IDENTIFIER_LENGTH`. This was missing in the v1.8.0 branch cut, so we enabled it manually in the devnet at that time.
* https://github.com/aptos-labs/aptos-core/pull/10861
=> [Cherry pick] Allow to set the beneficiary for operator

Cargo.lock, Cargo.toml, crates/aptos/src/node/mod.rs
Rationale described here: https://aptos-org.slack.com/archives/C067LJNM2NL.
See that the API works when running a local testnet:
```
cargo run -p aptos -- node run-local-testnet --force-restart --assume-yes
```
Fortunately it seems like this doesn't change the OpenAPI spec at all.
CI from this point on.
For the specific issue, see https://aptos-org.slack.com/archives/C067LJNM2NL/p1700668794918089.
=> [API] Upgrade Poem from 1.3.55 to 1.3.59

third_party/move/move-model/src/ty.rs
Fixing confusing documentation that function types only appear in specs, which was likely true at some point before, but is no longer true.
NA.
=> Fixing documentation for function types.

third_party/move/move-compiler-v2/tests/checking/typing/lambda.exp, third_party/move/move-compiler-v2/tests/checking/typing/subtype_args.exp, third_party/move/move-compiler-v2/tests/checking/typing/subtype_args.move, third_party/move/move-compiler-v2/tests/checking/typing/subtype_args_invalid.exp, third_party/move/move-compiler-v2/tests/checking/typing/subtype_args_invalid.move, third_party/move/move-model/src/ty.rs
Type inference wasn't considering variance and contra-variance in function type checking.
Closes #10913.
=> [compiler v2] Fix bug in mutability conversion and higher-order functions

Cargo.lock, testsuite/forge-cli/Cargo.toml, testsuite/forge-cli/src/main.rs
This lazy was using a private field, it should be using the oncecell directly.
Ran rust lint locally, worked properly.  CI should ensure compatibility
=> [forge-cli] Fix Lazy to be the right lazy

crates/aptos/src/test/mod.rs
Display exists already in path, so no reason to use AsDisplay
Build should work
=> [test] Remove usage of private AsDisplay

Cargo.lock, Cargo.toml, api/src/accept_type.rs, api/src/accounts.rs, api/src/basic.rs, api/src/blocks.rs, api/src/context.rs, api/src/events.rs, api/src/index.rs, api/src/state.rs, api/src/transactions.rs, api/src/view_function.rs, aptos-node/Cargo.toml, crates/aptos/src/node/mod.rs
This PR cherry picks the following two commits into aptos-release-v1.8:
- 8f56310fae4e1ad9d262b33e05dbcd5393f0e67c (https://github.com/aptos-labs/aptos-core/pull/10643)
- aba6f6f4433d1f29986ec2c190e8c50628748f1a (https://github.com/aptos-labs/aptos-core/pull/11050)
Rationale: https://aptos-org.slack.com/archives/C067LJNM2NL/p1700671856025839?thread_ts=1700671630.035739&cid=C067LJNM2NL.
=> Cherry pick 8f56310fae4e1ad9d262b33e05dbcd5393f0e67c and aba6f6f4433d1f29986ec2c190e8c50628748f1a into 1.8

docker/builder/README.md, docker/builder/build-indexer.sh, docker/builder/build-tools.sh, docker/builder/builder.Dockerfile, docker/builder/docker-bake-rust-all.hcl, docker/builder/indexer-grpc.Dockerfile, docker/builder/nft-metadata-crawler.Dockerfile
Separate build target for indexer (grpc) and related images. This is to unstrip them, since other CLIs are stripped in the `tools` builder.
CI builds image on this PR
=> [docker] separate build target for grpc

third_party/move/move-compiler/src/parser/lexer.rs, third_party/move/move-compiler/tests/move_check/parser/not_doc_comment.move
When parsing a move file containing `/**/`, the parser panics. This was first reported by @CapCap in the move eng channel.
This PR contains a fix, and a simplified test case that showcases the panic without this fix.
Added a test case to demonstrate the fix.
=> Fixing a panic when parsing /**/

aptos-move/framework/aptos-framework/sources/multisig_account.move, aptos-move/framework/aptos-stdlib/doc/math_fixed.md, aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381_algebra.move, aptos-move/framework/aptos-stdlib/sources/math_fixed.move
Constant folding and vector[...] are not supported by the new compiler yet. For convenience of testing on the framework code, non-supported operations are replaced by supported ones. Will put them back once they are supported in the new compiler.
=> Remove constants not supported by V2 for testing

Cargo.lock, aptos-node/src/lib.rs, config/Cargo.toml, config/src/config/node_config.rs
This PR logs the node config in multiple separate `info!` level logs, instead of a single `info!` call (which is truncated -- because the config is too large).
Manual verification. The logs now look as follows:
```
2023-11-21T13:37:10.051845Z [main] INFO config/src/config/node_config.rs:88 Using full_node_networks config: [{"max_connection_delay_ms":60000,"connection_backoff_base":2,"connectivity_check_interval_ms":5000,"network_channel_size":1024,"max_concurrent_network_reqs":100,"discovery_method":"onchain","discovery_methods":[],"identity":{"type":"from_config","key":"0xe81faac74fea2b3264038e3fe18b1a95d87d948c2d092b4365b704cc7ce79770","peer_id":"e596594ffc659d80515ad648ae59b318f1841c4d11a6a62d5b91550a3e6b6a5d"},"listen_address":"/ip4/127.0.0.1/tcp/6180","mutual_authentication":false,"ne …
```
=> [Node Config] Log each config individually.

aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381_algebra.move
This warning causes the tests to fail.
Before:
```
$ aptos move test
warning[W01004]: invalid documentation comment
┌─ /Users/dport/a/core/aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381_algebra.move:773:5
│
773 │     /// The maximum number of `G1` elements that can be created in a transaction,
│     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Documentation comment cannot be matched to a language item
warning[W01004]: invalid documentation comment
┌─ /Users/dport/a/core/aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381_algebra.move:774:5
│
774 │     /// calculated by the current memory limit (1MB) and the in-mem G1 representation size (144 bytes per element).
│     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> Fix compilation warning in bls12381_algebra.move

aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move
This provides an easy way to check if a feature is enabled.
I see we have no other view functions in move-stdlib. Asking here if that's intentional.
Move tests:
```
cd aptos-move/framework/move-stdlib
```
Run a local testnet:
```
cargo run -p aptos -- node run-local-testnet --force-restart --assume-yes
```
Call the view function:
```
$ aptos move view --function-id 0x1::features::is_enabled --args u64:41 --url http://127.0.0.1:8080/v1
{
"Result": [
false
]
}
$ aptos move view --function-id 0x1::features::is_enabled --args u64:28 --url http://127.0.0.1:8080/v1
{
"Result": [
true
]
}
```
=> Make is_enabled in features.move a view function

Cargo.lock, aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs, third_party/move/move-vm/runtime/Cargo.toml, third_party/move/move-vm/runtime/src/interpreter.rs, third_party/move/move-vm/runtime/src/loader/mod.rs, third_party/move/move-vm/runtime/src/loader/modules.rs, third_party/move/move-vm/runtime/src/loader/type_loader.rs, third_party/move/move-vm/runtime/src/session.rs, third_party/move/move-vm/types/Cargo.toml, third_party/move/move-vm/types/src/loaded_data/runtime_types.rs, third_party/move/move-vm/types/src/values/values_impl.rs
Improve the performance of the loader by:
1. Use index for struct identifiers instead of Arc.
2. Use `Arc` instead of `Box` to make cloning `Type` trivial.
Ran the performance benchmark on the p2p workflow and observed getting the performance regression back from the new loader
=> [move-vm] A few perf optimizations for the loader

testsuite/forge-cli/src/main.rs
Some of the node configurations for the forge test `run-forge-realistic-network-tuned-for-throughput` appear to be incorrect and are causing transient failures in the stable (nightly) run. These were leftovers from `previewnet` tests. This PR fixes the inconsistencies. 😄 
=> [Forge Stable] Fix inconsistencies in node configs.

storage/backup/backup-cli/src/coordinators/replay_verify.rs, storage/db-tool/src/replay_verify.rs, testsuite/replay_verify.py, testsuite/replay_verify_run_local.py
The problem is the 2nd retry was the same process with old cache or lock on DB. Now, do the retry outside and can still leverage the resumable replay without redundant work。
using old versioned node cache will cause all non-exe thread panic and stuck forever.
also the lock on ledger db cannot be dropped even when the AptosDb goes out of scope in the 2nd iteration. 
https://github.com/aptos-labs/aptos-core/actions/runs/6937303262
=> [storage] fix the replay-verify stuck

.github/workflows/ts-sdk-e2e-tests.yaml
Because this check usese pull request target trigger the concurrency was actually incorrect and causing jobs to get randomly canceled
Test Plan: there is unfortunately not really a great way to test pull_request_target because it runs off the main branch on the workflow
=> [gha] Set concurrency correctly on ts sdk check

developer-docs-site/docs/move/book/functions.md, developer-docs-site/scripts/additional_dict.txt
Updating move book documentation for inline functions and lambda expressions, fixing an error in the example code, adding an explicit list of current restrictions.
Generated documentation with `pnpm` locally and proof read the result.
=> Updating inline function documentation in the move book.

developer-docs-site/docs/move/book/abilities.md, developer-docs-site/docs/move/book/abort-and-assert.md, developer-docs-site/docs/move/book/functions.md, developer-docs-site/docs/move/book/integers.md, developer-docs-site/docs/move/book/structs-and-resources.md, developer-docs-site/docs/move/book/tuples.md, developer-docs-site/docs/move/book/unit-testing.md
For files in developer-docs-site/docs/move/book/:
1. abilities.md - Replaced n with c_n.
2. abort-and-assert.md - Added "of" in sentence.
3. functions.md - Fixed example where function names can't start with underscore. Made various sentences read better.
4. integers.md - Replaced "oe" with "or".
5. structs-and-resources.md - The "d" returned is actually already d*d. Renamed "d" to "dist_squared_value". Replaced d*d with dist_squared_value.
6. tuples.md - Improved sentence readability.100000
7. unit-testing.md - Current default max instructions in aptos 2.3.1 is 100000 from "aptos move test -h".
Fixed several documentation errors in several `.md` files.
I changed the `.md` files and after running:
```
./scripts/rust_lint.s
```
I got these errors:
```
error: use of `or_insert_with` to …
```
=> Fixed several documentation errors

state-sync/state-sync-driver/src/tests/storage_synchronizer.rs, testsuite/forge-cli/src/main.rs
This PR makes two small test only changes:
1. `realistic_network_tuned_for_throughput_test` is now using big machines and running at a higher TPS, so we need to bump the catch up time for slow nodes.
2. Use a timeout to prevent some failed tests from hanging.
=> [Forge] Bump catchup time for `realistic_network_tuned_for_throughput_test`

consensus/src/experimental/buffer_manager.rs, consensus/src/experimental/decoupled_execution_utils.rs, consensus/src/experimental/pipeline_phase.rs, consensus/src/experimental/tests/execution_phase_tests.rs, consensus/src/experimental/tests/signing_phase_tests.rs
We observe that in some cases, processing through all requests can take very long when we have to request for missing batches that are already garbage collected. This commit adds a flag to drop those pending requests.
=> [buffer manager] use reset flag for faster reset

developer-docs-site/docs/apis/aptos-labs-developer-portal.md, developer-docs-site/docs/indexer/api/example-queries.md, developer-docs-site/docs/indexer/api/index.md, developer-docs-site/docs/indexer/api/labs-hosted.md, developer-docs-site/docs/indexer/api/self-hosted.md, developer-docs-site/docs/indexer/api/usage-guide.md, developer-docs-site/docs/indexer/custom-processors/e2e-tutorial.md, developer-docs-site/docs/indexer/custom-processors/index.md, developer-docs-site/docs/indexer/custom-processors/parsing-txns.md, developer-docs-site/docs/indexer/indexer-landing.md, developer-docs-site/docs/indexer/txn-stream/index.md, developer-docs-site/docs/indexer/txn-stream/labs-hosted.md, developer-docs-site/docs/indexer/txn-stream/local-development.md, developer-docs-site/docs/indexer/txn-stream/self-hosted.md, developer-docs-site/scripts/additional_dict.txt, developer-docs-site/src/components/_dev_portal_beta_notice.mdx, developer-docs-site/src/components/_indexer_beta_notice.mdx
This PR adds an admonition to each of the new indexer pages informing users that the new stack is in beta.
I remove redundant titles where appropriate as part of this.
Note: My original intent was to do something more lightweight by adding a beta badge above the title but I couldn't get it working. See https://github.com/facebook/docusaurus/issues/9588.
Docs.
=> [docs] Add beta admonition to indexer pages

crates/aptos/CHANGELOG.md, crates/aptos/src/common/types.rs
It's not ready for outside use, and users are confused and try to use it when things don't work for them in V1, which leads to more confusion because they definitely don't work in V2.
=> [cli] Hide V2 Compiler

consensus/consensus-types/src/block.rs, consensus/consensus-types/src/executed_block.rs, consensus/src/block_preparer.rs, consensus/src/block_storage/block_store.rs, consensus/src/dag/adapter.rs, consensus/src/execution_pipeline.rs, consensus/src/experimental/execution_schedule_phase.rs, consensus/src/experimental/ordering_state_computer.rs, consensus/src/experimental/tests/execution_phase_tests.rs, consensus/src/experimental/tests/test_utils.rs, consensus/src/lib.rs, consensus/src/rand/rand_gen/block_queue.rs, consensus/src/state_computer.rs, consensus/src/state_computer_tests.rs, consensus/src/state_replication.rs, consensus/src/test_utils/mock_state_computer.rs
We observed in previewnet that for large block and higher conflict, the shuffling is pretty expensive takes around 150 ms. This PR moves the transaction fetching, dedup, shuffling to the block preparation phase and also avoids redoing all the above operations in the commit phase by storing the input transaction in the executed block. 
Ran Forge.
=> [Execution] Move the transaction shuffling and dedup to the block preparation phase

testsuite/forge-cli/src/main.rs
Max load test is already tuned for max TPS, so the system metrics threshold check is not needed - and can be flaky as the CPU usage increases as a result of various optimizations. 
As a next step, will tune this test to test 30k previewnet setup. 
Run test.
=> [Forge] Remove system metrics threashold check for max load test

aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/output.rs, aptos-move/aptos-vm-types/src/tests/test_output.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/e2e-tests/src/executor.rs, experimental/execution/ptx-executor/src/finalizer.rs
Extracted from block gas limit PR, for easier review - this is necessary there to be able to understand conflicts in sequential and parallel execution in the same way.
Also it is cleaner to have all materialization at the same place - in executor.rs
=> Move AggV1 materialize from transaction execution to block executor materialization

consensus/consensus-types/src/executed_block.rs, consensus/src/block_storage/block_store.rs, consensus/src/experimental/ordering_state_computer.rs, consensus/src/liveness/proposal_generator.rs, consensus/src/payload_client/user/quorum_store_client.rs, testsuite/smoke-test/src/aptos_cli/validator.rs
* Fix pipeline backpressure to exclude treating committed block as pending
For pipeline backpressure we were looking at latency between ordered and committed block.
But committed block is not in the pipeline any more, and next block after it could've
been created significantly later (and so got into the pipeline significantly later).
Second it is better to take actual time block is in the pipeline, than  use ordered timestamp.
if it took us 1s to order oldest_not_committed_block, but 100ms to order
currently ordered block, we don’t want to backpressure if it
is 1.5s passed the oldest_not_committed_block - because it was really only 500ms in the pipeline
=> Fix pipeline backpressure to exclude treating committed block as pending

.github/workflows/ts-sdk-e2e-tests.yaml
fix the concurrency rule to avoid concurrent PRs cancelling each others jobs
=> fix cancellation of ts-sdk tests workflow

third_party/move/move-compiler-v2/src/inliner.rs, third_party/move/move-compiler-v2/tests/checking/inlining/lambda_param.exp, third_party/move/move-compiler-v2/tests/checking/inlining/lambda_param.move, third_party/move/move-compiler-v2/tests/checking/inlining/private_call.exp, third_party/move/move-compiler-v2/tests/checking/inlining/private_call_2.exp, third_party/move/move-compiler-v2/tests/checking/inlining/private_call_3.exp, third_party/move/move-model/src/ast.rs, third_party/move/move-model/src/model.rs
Add 'inlined from' annotations to locations in diagnostics about code that has been inlined in move-compiler-v2
- Add an `Option<Box<Loc>>` field `inlined_from_loc` to struct `Loc` in move-model/src/model.rs, modify diagnostics to show it if present.
- Use it in move-compiler-v2/src/inliner.rs to augment code with information about where it was inlined.
- Existing test cases private_call.move, private_call_2.move, and private_call_3.move show improved information in this case.
- Other test cases show lack of disruption.
Bug #10848
=> Add 'inlined from' annotations to locations in diagnostics about code that has been inlined

testsuite/forge-cli/src/main.rs
CPU metrics check is not needed and flaky for max throughput tests. Removing it. 
Will run Forge.
=> [Forge] Remove system metrics check for max throughput test

aptos-move/framework/aptos-framework/sources/object.spec.move, aptos-move/framework/aptos-token-objects/sources/aptos_token.move
Looks like some imports weren't cleaned up when the feature flags were removed.  These show up whenever you compile against main with the compiler.
=> [framework] Remove move warnings from framework

testsuite/forge-cli/src/main.rs
The test should use the `default_for_genesis` version of consensus config (similar to the execution config).
Currently `OnChainConsensusConfig` is primarily used as `default_is_missing`.
=> fix consensus config for realistic_env_max_load_test

consensus/src/liveness/unequivocal_proposer_election.rs
Error message doesn't make sense as the leader mismatch might happen if peer history is not available.
Unit tests
=> Remove error message in proposer election

third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs, third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs, third_party/move/move-compiler-v2/tests/reference-safety/return_borrowed.move, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_field_combo.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_field_combo_invalid.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_field_field.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_field_full.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_field_full_invalid.exp, third_party/move/move-model/bytecode/src/dataflow_analysis.rs
Closes #11221.
When a temporary goes out of scope, nodes related to that temporary are removed from the graph, provided they are not borrowed. This process recursively continues, visiting nodes representing other temporaries, cleaning up large parts of the graph. There was a significant bug in this cleanup, namely ignoring whether a node and a related temporary are also referenced from the outside. This is for example the case if the temporary is used later in the program. It appears this bug only hits if different control flows contribute to the graph, as is in the test case `return_borrowed.move`.
Notice the better error messages in other .exp files come from that previously parts of the graph have been removed. Its the same errors, only with more secondary info from the corrected …
=> [compiler-v2] Fixes a bug in borrow graph shrinking

Cargo.lock, aptos-move/e2e-tests/Cargo.toml, aptos-move/e2e-tests/src/loader/mod.rs, aptos-move/e2e-tests/src/loader/module_generator.rs, aptos-move/e2e-testsuite/src/tests/loader.rs
Refactored the loader proptest to allow generating random packages and mutate them during execution. This would give us a stress test on loader's behavior over module republishing.
Updated an ran the tests. Make sure they passed.
=> [move-vm] Create a stress test suite for module upgrades

third_party/move/move-compiler/src/parser/lexer.rs, third_party/move/move-compiler/src/parser/syntax.rs, third_party/move/move-compiler/tests/move_check/control_flow/for_user.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/break_continue_for_loop.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/break_continue_for_loop.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_empty.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_empty.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_counter.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_counter.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_empty.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_empty.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_empty_range.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_empty_range.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_increment_iter.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_increment_iter.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_non_terminating.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_non_terminating.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_type_mismatch.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_type_mismatch.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/nested_for_loops.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/nested_for_loops.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/nested_for_while_loops.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/nested_for_while_loops.move
Add support to parse for loops of the form `for (iter in lower_bound..upper_bound) { loop_body }` by transforming it into a corresponding while loop.
Refer to tests in `move-compiler/transactional-tests/tests/control_flow/`
=> implement for loops

ecosystem/typescript/aptos-client/CHANGELOG.md, ecosystem/typescript/aptos-client/package.json, ecosystem/typescript/aptos-client/pnpm-lock.yaml
Main driver is to update Axios in the aptos-client, but I've updated the rest accordingly anyways for now.  Will not deploy a new version of the Typescript SDK until Aptos Client is updated.
CI tests.  Will need to test directly with TS SDK v2 / possibly should move it to that repository.
=> [typescript] Update Aptos Client axios, and other typescript deps

third_party/move/move-compiler-v2/src/bytecode_generator.rs, third_party/move/move-compiler-v2/transactional-tests/tests/constants/folding_vector.exp, third_party/move/move-compiler-v2/transactional-tests/tests/constants/folding_vector.move, third_party/move/move-model/src/ty.rs
This PR fixes the bug that the compiler V2 does not correctly handle the type of vector constants when generating the stackless bytecode. A new test is added to the test case `folding_vector` to validate the fix.
=> [Compiler-v2] Fix a bug related to vector constants

Cargo.lock, third_party/move/move-compiler-v2/src/inliner.rs, third_party/move/move-compiler-v2/transactional-tests/Cargo.toml, third_party/move/move-compiler-v2/transactional-tests/tests/tests.rs
Tweak V2 transactional tests to not compile V1 and run comparisons if `MOVE_TEST_DEBUG` is enabled, making debugging easier..
Run tests with and without `MOVE_TEST_DEBUG=1`.
=> Turn off v1 comparison in v2 transactional tests if MOVE_TEST_DEBUG is enabled 

config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/poller.rs, state-sync/data-streaming-service/src/data_stream.rs, state-sync/data-streaming-service/src/metrics.rs, state-sync/data-streaming-service/src/tests/data_stream.rs
This PR updates the data streaming service to continue pre-fetching, even when head of line blocked.
Previously, the pre-fetcher would stop when there were `max_concurrent_requests` in the queue (even if only the first request was blocked/processing and the rest were already complete). To prevent head of line blocking from slowing synchronization down, the pre-fetcher now maintains two windows: (i) `max_concurrent_requests` -- the max in-flight requests (at any one time); and (ii) `max_pending_requests` -- the max pending requests (at any one time) in the pre-fetcher queue (this is required to bound memory use). Now, the pre-fetcher is able to continue pre-fetching up to a larger number of requests when head of line blocked.
1. Fix the request latency …
=> [Data Streaming Service] Continue to pre-fetch even when head of line blocked.

Cargo.lock, api/src/context.rs, aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/src/captured_reads.rs, aptos-move/block-executor/src/counters.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/lib.rs, aptos-move/block-executor/src/limit_processor.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/types.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-tests/src/executor.rs, crates/aptos-genesis/src/test_utils.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/pipeline.rs, execution/executor-benchmark/src/transaction_executor.rs, testsuite/single_node_performance.py, types/src/block_executor/config.rs, types/src/on_chain_config/execution_config.rs, types/src/test_helpers/transaction_test_helpers.rs
throughput changes based on whether there are conflicts between transactions (and they need to be executed sequentially), or if they are parallel. But the gas charged stays constant, as gas charging is independent for each transaction.
In order to limit to the total amount of time block can be executing, we introduce conflict-aware block gas limit - where we multiply gas used for individual transactions with the coefficient of how many of the recent 8 transaction it had conflicts with (including self, which we assume it had conflict with - to have the number in the [1, 8] range)
=> Improved block gas limit - output size limit, conflict aware, io/compute multipliers

aptos-move/block-executor/src/limit_processor.rs
seems like squash didn't squash my last update to the PR
remove unnecessary println
=> remove accidental println

aptos-move/aptos-abstract-gas-usage/src/algebra.rs, aptos-move/aptos-debugger/src/aptos_debugger.rs, aptos-move/aptos-gas-meter/src/algebra.rs, aptos-move/aptos-gas-meter/src/meter.rs, aptos-move/aptos-gas-meter/src/traits.rs, aptos-move/aptos-vm-types/src/storage/change_set_configs.rs, aptos-move/aptos-vm-types/src/storage/io_pricing.rs, aptos-move/aptos-vm-types/src/storage/mod.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/gas.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/vm-genesis/src/lib.rs, aptos-move/writeset-transaction-generator/src/writeset_builder.rs
1. Split the pricing configs (`StoragePricing`) and change set limit configs (`ChangeSetConfigs`) to their own files.
2. Rename `StoragePricing` to `IoPricing`, in preparation to introduce `space_pricing`
=> trivial: split out StoragePricing

config/src/config/state_sync_config.rs, network/framework/src/application/storage.rs, network/framework/src/transport/mod.rs, state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/lib.rs, state-sync/aptos-data-client/src/priority.rs, state-sync/aptos-data-client/src/tests/priority.rs, state-sync/aptos-data-client/src/utils.rs
Note: there should be no logic changes in this PR.
This PR introduces new priority categories for peers in the Aptos Data Client. We'll use these categories in the next PR (to implement multi-fetch), but for now the logic should not change. The peer poller still only cares about peers that are high-priority or not.
1. Add the new priority categories (and tests).
2. Move the latency configs into their own sub-config (to prevent the config from growing too large).
New and existing unit tests. Note: some tests have been moved from the `utils.rs` file to `priority.rs`.
=> [Aptos Data Client] Introduce priority categories.

aptos-move/aptos-abstract-gas-usage/src/algebra.rs, aptos-move/aptos-gas-meter/src/algebra.rs, aptos-move/aptos-gas-meter/src/meter.rs, aptos-move/aptos-gas-meter/src/traits.rs, aptos-move/aptos-gas-profiling/src/profiler.rs, aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs, aptos-move/aptos-memory-usage-tracker/src/lib.rs, aptos-move/aptos-vm-types/src/abstract_write_op.rs, aptos-move/aptos-vm-types/src/storage/io_pricing.rs, aptos-move/aptos-vm-types/src/storage/mod.rs, aptos-move/aptos-vm-types/src/storage/space_pricing.rs, types/src/write_set.rs
Refactor and consolidate storage fee charging logic to DiskSpacePricing. Prepare to inroduce different charging scheme.
=> DiskSpacePricing

.github/workflows/docker-build-test.yaml, .github/workflows/faucet-tests-prod.yaml, .github/workflows/indexer-grpc-integration-tests.yaml, .github/workflows/rust-client-tests.yaml, .github/workflows/ts-sdk-e2e-tests.yaml
This PR reverts this [commit](https://github.com/aptos-labs/aptos-core/pull/10352/commits/cd683c9f099bdf2ebcc2d17c0be36305f1ab6668) from #10352 that adds a condition to `permission-check` jobs to bypass it if the user is a dependabot. I think we don't need this check actually and we just need to enable auto-merge on the PR so it gets the proper write permissions to run the workflow. The side-effect is that we are now building images on every PR automatically without any labels.
Will merge this and check next time dependabot creates a PR.
=> [gha] revert permission-check if condition

third_party/move/move-compiler-v2/transactional-tests/tests/inlining/objects.exp, third_party/move/move-compiler-v2/transactional-tests/tests/inlining/phantoms.exp, third_party/move/move-compiler-v2/transactional-tests/tests/inlining/phantoms.move, third_party/move/move-model/src/builder/exp_builder.rs, third_party/move/move-model/src/builder/module_builder.rs
Closes #11092. In fact abilities are correctly propagated to file format. However, a phantom type parameter was not. This lead to the bytecode verification error `UNSAFE_RET_UNUSED_VALUES_WITHOUT_DROP`  in `objects.move` which is now fixed.
=> [compiler-v2] Fixing a bug with propagation of phantom type parameters

Cargo.lock, aptos-move/e2e-move-tests/Cargo.toml, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/lib.rs, aptos-move/e2e-move-tests/src/tests/attributes.rs, aptos-move/e2e-move-tests/src/tests/code_publishing.rs, aptos-move/e2e-move-tests/src/tests/common.rs, aptos-move/e2e-move-tests/src/tests/generate_upgrade_script.rs, aptos-move/e2e-move-tests/src/tests/metadata.rs, aptos-move/e2e-move-tests/src/tests/mint_nft.rs, aptos-move/e2e-move-tests/src/tests/nft_dao.rs, aptos-move/e2e-move-tests/src/tests/scripts.rs, aptos-move/e2e-move-tests/src/tests/simple_defi.rs
This PR uses the environment variable `ENABLE_V2` to control whether to use compiler v2 for tests in `e2e-move-tests`.
=> [e2e-move-tests] Enable compiler v2 in e2e-move-tests

config/src/config/config_optimizer.rs, config/src/config/indexer_grpc_config.rs
When env is available, it overrides the yaml. Otherwise everything else works as intended.
enable_verbose_logging: true in yaml, no env
enable_verbose_logging: true in yaml, env set to false
enable_verbose_logging: false in yaml or missing, env set to false or missing
=> [indexer grpc] Create env var to toggle logging 

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json, api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json, aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs, aptos-move/aptos-vm-types/src/storage/io_pricing.rs, aptos-move/aptos-vm-types/src/storage/mod.rs, aptos-move/aptos-vm-types/src/storage/space_pricing.rs, aptos-move/aptos-vm/src/gas.rs, aptos-move/e2e-move-tests/src/tests/per_category_gas_limits.data/out_of_gas_while_charging_storage_fee.exp, aptos-move/e2e-move-tests/src/tests/per_category_gas_limits.data/storage_limit_reached_by_new_bytes.exp, aptos-move/e2e-move-tests/src/tests/per_category_gas_limits.rs, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__borrow_after_move.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__change_after_move.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__move_from_across_blocks.exp, aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs, aptos-move/framework/table-natives/src/lib.rs
1. read bytes charged in 4k steps
2. remove per write op free quota
=> Io Gas adjustments

Cargo.lock, api/Cargo.toml, api/src/context.rs, api/src/metrics.rs, api/src/runtime.rs, api/src/transactions.rs, config/src/config/api_config.rs
The metrics give direct observability of what gas estimations are actually being returned.
Calling it periodically helps understand the gas estimation even in environments (forge, previewnet) where the estimation is not called.
Run forge, observe the metrics.
=> [Gas estimate][metrics] Add metrics for gas estimation, and call it periodically

config/src/config/quorum_store_config.rs, consensus/src/network.rs, consensus/src/network_interface.rs, consensus/src/quorum_store/batch_requester.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/quorum_store_builder.rs, consensus/src/quorum_store/tests/batch_requester_test.rs, consensus/src/quorum_store/tests/mod.rs, consensus/src/quorum_store/types.rs, consensus/src/quorum_store/utils.rs, consensus/src/test_utils/mock_quorum_store_sender.rs, testsuite/generate-format/src/consensus.rs, testsuite/generate-format/tests/staged/consensus.yaml
Batches that are not available locally are requested for execution.
Previously, batch requests for locally unavailable batches were just ignored. The sender would have to wait to timeout. The worst case was when the batch was actually expired, as all retries would have to timeout.
In this PR, a negative acknowledgement is a response when the batch is unavailable. In addition, the current ledger info is given in the response. The sender checks if the batch is expired for the current ledger info, and short circuits further retries when this is the case. The validator will fail execution (and eventually go to state sync).
Added unit tests. Hoping to get a forge-based repro and show the improved behavior.
=> [Quorum Store] batch request changed to short circuit on expired

config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/error.rs, state-sync/aptos-data-client/src/logging.rs, state-sync/aptos-data-client/src/metrics.rs, state-sync/aptos-data-client/src/poller.rs, state-sync/aptos-data-client/src/priority.rs, state-sync/aptos-data-client/src/tests/advertise.rs, state-sync/aptos-data-client/src/tests/compression.rs, state-sync/aptos-data-client/src/tests/mock.rs, state-sync/aptos-data-client/src/tests/mod.rs, state-sync/aptos-data-client/src/tests/multi_fetch.rs, state-sync/aptos-data-client/src/tests/peers.rs, state-sync/aptos-data-client/src/tests/poller.rs, state-sync/aptos-data-client/src/tests/priority.rs, state-sync/aptos-data-client/src/tests/utils.rs, state-sync/aptos-data-client/src/tests/weighted_selection.rs, state-sync/aptos-data-client/src/utils.rs
Note: 90% of this PR is unit test changes (in the second and third commits).
This PR introduces multi-fetch support to the data client. More specifically, whenever a data client request is created by the data streaming service, the data client will send the request to multiple peers simultaneously and use the first response. This is helpful to guard against unreliable peers, transient network errors and RPC timeouts, hopefully making things more reliable in practice.
The minimum and maximum number of peers to select for each request is configurable and depends on the number of potential peers that can service the request (as well as the request type). We've currently set the default minimum to `2` and the default maximum to `5`, respectively. If we have less than the minimum number of …
=> [Aptos Data Client] Add multi-fetch support.

mempool/src/tests/multi_node_test.rs, state-sync/storage-service/server/src/tests/epoch_ending.rs, state-sync/storage-service/server/src/tests/state_values.rs, state-sync/storage-service/server/src/tests/transaction_outputs.rs, state-sync/storage-service/server/src/tests/transactions.rs, state-sync/storage-service/server/src/tests/transactions_or_outputs.rs, state-sync/storage-service/server/src/tests/utils.rs, storage/backup/backup-cli/src/backup_types/transaction/analysis.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, types/src/contract_event.rs
It is innefficient to be serializing to bytes (and allocating that memory), 
when we only care about the length of the serialized value.
Let's see if this improves performance a bit, I think we use it to charge txn_size, among other places
=> Use bcs::serialized_size(..) instead of bcs::to_bytes(..).len()

ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/lib.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs, ecosystem/indexer-grpc/indexer-grpc-file-store/src/lib.rs
Old yaml's that don't have the `enable_verbose_logging` flag set will not work. This PR sets default for the flag if it's not set. 
1. Test without `enable_verbose_logging` flag
2. Test set `enable_verbose_logging` to true
3. Test set `enable_verbose_logging` to false 
[Humio](https://cloud.us.humio.com/k8s/search?live=false&query=k8s.namespace%20%3D%20%22indexer-grpc-devnet%22%0A%7C%20rename(%5B%5Bdata.service_type%2C%20fields.service_type%5D%2C%20%5Bdata.step%2C%20fields.step%5D%5D)%20%2F%2F%20Rename%20the%20fields%20in%20fullnode%0A%7C%20in(fields.service_type%2C%20values%3D%5B%22data_service%22%2C%20%22cache_worker%22%2C%20%22file_worker%22%2C%20%22indexer_fullnode%22%5D)%0A%7C%20fields.step%20%3D%20*%0A%7C%20format(format%3D%22service%3D%25s%2C%20step%3D%25s%22%2C%20field%3D%5Bfields. …
=> [indexer grpc] Default enable_verbose_logging flag to false in rust config

third_party/move/move-compiler-v2/tests/checking/inlining/bug_11112.exp, third_party/move/move-compiler-v2/tests/checking/inlining/bug_11112.move, third_party/move/move-compiler-v2/transactional-tests/tests/inlining/bug_11112.exp, third_party/move/move-compiler-v2/transactional-tests/tests/inlining/bug_11112.move, third_party/move/move-compiler/src/command_line/compiler.rs, third_party/move/move-compiler/src/inlining/translate.rs, third_party/move/move-compiler/tests/move_check/inlining/bug_11112.move, third_party/move/move-compiler/transactional-tests/tests/inlining/bug_11112.exp, third_party/move/move-compiler/transactional-tests/tests/inlining/bug_11112.move
Fix move-compiler-transactional-tests to also inline functions from pre-compiled-library.
- Added a new test bug_11112.move showing the problem in both v1 and v2 (because it also compares with v1 output).
- Provided `pre_compiled_lib` to inlining pass in move-compiler (V1) for transactional tests, and also collect inline
functions from that library in inlining pass.  This could probably be made more efficient, but as V1 is on its way out,
that'll do for now.
Fixes Issue #11264 
The new test illustrated the problem, now shows it is fixed.
This change only affects move-compiler-transactional-tests (and move-compiler-v2-transactional-tests due to its
output comparison with V1), so running all transactional tests should be sufficient.
=> Fix move-compiler-transactional-tests to also inline functions from pre-compiled-library. (#11264)

config/src/config/indexer_grpc_config.rs, ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs, ecosystem/indexer-grpc/indexer-grpc-fullnode/src/localnet_data_service.rs, ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs, ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs
1. rename var to enable_expensive_logging
2. gate the expensive parts of logging
1. test with enable_expensive_logging not set or set to false. Step 1 shouldn't show up in metrics 
2. test with enable_expensive_logging = true. Step 1 should show up in metrics
=> [indexer grpc] Gate only the expensive part of the logging 

consensus/src/block_storage/block_store.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/transaction_generator.rs
for very low TPS workloads, I noticed that execution throughput was lower than overall, because we were counting initialization (which is around 18 TPS for ~0.1s)
=> Exclude initialization steps from benchmark measurements

consensus/src/counters.rs
This will allow proper `histogram_quantile` when needed.
=> [metrics] add custom histogram buckets for block trace

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/cluster.rs, crates/transaction-emitter-lib/src/instance.rs, ecosystem/node-checker/src/checker/tps.rs
Option to use an API key for the txn-emitter's underlying REST client, so we can route traffic through the API gateway
Run the txn emitter with the new `--node-api-key` argument, after creating a new API key
```
cargo run -p aptos-transaction-emitter --release -- emit-tx -t https://fullnode.devnet.aptoslabs.com --coin-source-key ${DEVNET_APT_KEY} --chain-id ${CHAIN_ID} ...--node-api-key <MY_KEY>
```
=> [txn-emitter] option to use an api key

aptos-move/aptos-gas-schedule/mass_mod.py, aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs, aptos-move/aptos-gas-schedule/src/gas_schedule/instr.rs
This introduces a python script that can be used to mass-modify the gas schedule entries that are embedded in the Rust source files. It is meant to serve as a temporary solution until we come up with a more appropriate format for storing 
the gas schedule.
Notice that I've also included some formatting changes in the PR. These are generated by running the script with an id function. Making these formatting changes now will make it easier for us to spot changes in subsequent gas adjustment PRs.
=> [gas] add script for mass-modifying the gas schedule

third_party/move/move-compiler-v2/src/bytecode_generator.rs, third_party/move/move-compiler-v2/tests/checking/inlining/bug_11112.exp, third_party/move/move-compiler-v2/tests/checking/inlining/bug_9717.exp, third_party/move/move-compiler-v2/tests/checking/inlining/bug_9717_looponly.exp, third_party/move/move-compiler-v2/tests/live-var/bug_9717_looponly.exp, third_party/move/move-compiler-v2/tests/live-var/inferred_copy.exp, third_party/move/move-compiler-v2/tests/live-var/mut_inline.exp, third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp, third_party/move/move-compiler-v2/tests/live-var/mut_ref.move, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_mutual_borrows_invalid.exp, third_party/move/move-compiler-v2/transactional-tests/tests/control_flow/sorter.exp, third_party/move/move-compiler-v2/transactional-tests/tests/evaluation_order/side_effecting_args.exp, third_party/move/move-compiler-v2/transactional-tests/tests/evaluation_order/side_effecting_args.move
Closes https://github.com/aptos-labs/aptos-core/issues/11276.
In order to enforce left-to-right evaluation of arguments to a function, we had introduced saving each arg evaluation (in order) in a temporary. While there was some optimization to reduce the number of temporaries, it still was too many to break one of the framework code.
In this PR, we further reduce the number of temporaries, by not creating them when all args to a function are guaranteed to not mutate locals (i.e., side-effect free). Our analysis here is fairly simple, as we expect copy propagation (in the future) to eliminate many of the unnecessary temps.
I have added a new test, which among other things, showcases that we cannot just scan for blocks to detect side-effects: move functions can also be side-effecting.
I …
=> Reducing the number of temporaries generated

consensus/src/quorum_store/tests/utils.rs, consensus/src/quorum_store/utils.rs
Batches are pulled using round robin on authors (and by order of gas within the same author). This additionally sorts the pulled batches based on gas.
Add unit test.
=> [Quorum Store] before returning block, sort by batch gas

testsuite/forge-cli/src/main.rs
The default was changed. Future changes should be more apparent now.
Ran ad-hoc forge run
=> [forge] Update realistic_network_tuned_for_throughput_test to use latest onchain execution config

Cargo.lock, consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_state_sync.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/types.rs, consensus/src/epoch_manager.rs, consensus/src/pipeline/buffer_manager.rs, consensus/src/pipeline/commit_reliable_broadcast.rs, consensus/src/pipeline/decoupled_execution_utils.rs, consensus/src/pipeline/tests/buffer_manager_tests.rs, consensus/src/rand/rand_gen/rand_manager.rs, consensus/src/rand/rand_gen/reliable_broadcast_state.rs, crates/reliable-broadcast/Cargo.toml, crates/reliable-broadcast/src/lib.rs, crates/reliable-broadcast/src/tests.rs
This PR modifies ReliableBroadcast to process RPC responses concurrently using the `concurrent_map`ping function introduced in #11290. To support concurrency, `BroadcastStatus` trait had to support `Sync + Send + Clone`, so this PR also changes all instances of BroadcastStatus to satisfy the new bounds.
=> [rb] support concurrent message verification

testsuite/forge-cli/src/main.rs
These update thresholds based on the impact of the gas schedule and block limit changes. 
latencies are much more uniform and predictable (we can probably lower them further, I was a big conservative). on the other hand - throughput for NFT minting is lower, because it was overloading before.
=> Update workload sweep forge thresholds

aptos-move/aptos-release-builder/data/release.yaml
This PR resets the `release.yaml` for the v1.9 release and adds the steps for AIP-50 and AIP-52
CI test
=> Update release.yaml for the v1.9 release

third_party/move/move-vm/runtime/src/data_cache.rs, third_party/move/move-vm/runtime/src/interpreter.rs, third_party/move/move-vm/runtime/src/loader/function.rs, third_party/move/move-vm/runtime/src/loader/mod.rs, third_party/move/move-vm/runtime/src/loader/modules.rs, third_party/move/move-vm/runtime/src/loader/script.rs, third_party/move/move-vm/runtime/src/move_vm.rs, third_party/move/move-vm/runtime/src/native_functions.rs, third_party/move/move-vm/runtime/src/runtime.rs, third_party/move/move-vm/runtime/src/session.rs
The idea is the session should pass in which loader cache to use. The default API remains the same but created a new API for passing a custom module cache instead. This would make MoveVM itself stateless if such API is used.
Rebased on the testing PR #11126
=> [move_vm] Split out module cache from loader

state-sync/aptos-data-client/src/latency_monitor.rs, state-sync/aptos-data-client/src/metrics.rs
This PR adds a new metric to the latency monitor in state sync that tracks the block timestamp lag in seconds (i.e., the difference between the current time and the timestamp of the highest synced block).
=> [Latency Monitor] Add simple metric for block timestamp lag.

Cargo.lock, api/Cargo.toml, api/src/tests/accounts_test.rs, api/src/tests/transaction_vector_test.rs, api/src/tests/view_function.rs, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/framework/cached-packages/src/aptos_stdlib.rs, sdk/src/transaction_builder.rs
This is a cherry pick from #11274 which brings us closer to removing `ModuleBundle`
execution path from Aptos VM. 
1. Removes the dependencies on the deprecated transaction type from `api` tests.
2. Adds new code publishing approach instead.
=> [cleanup] Remove API dependency on ModuleBundle in tests

consensus/src/dag/adapter.rs, consensus/src/dag/order_rule.rs
Uses the new storage API to get block events and fixes the commit event evaluation length.
=> use new api to get block event

execution/executor-benchmark/src/block_preparation.rs
Since the change https://github.com/aptos-labs/aptos-core/pull/11287 we want to add state checkpoint only after the txns are executed. Hence do not append it to input txns list.
This should not matter because StateCheckpoint txn is no-op in executor benchmark.
=> [Executor_benchmark] Do not append state checkpoint txn to the block

third_party/move/tools/move-bytecode-utils/src/module_cache.rs
Removed dead code from bytecode utils. Cherry pick from #11177. Needed to minimize usages of `GetModule` trait and fix error propagation in resolvers.
=> [move][trivial] Remove unused module cache

third_party/move/move-compiler-v2/tests/checking/typing/eq.exp, third_party/move/move-compiler-v2/tests/checking/typing/eq_inline.exp, third_party/move/move-compiler-v2/tests/checking/typing/eq_inline.move, third_party/move/move-compiler-v2/tests/checking/typing/eq_invalid.exp, third_party/move/move-compiler-v2/tests/checking/typing/mutable_eq_and_neq.exp, third_party/move/move-compiler-v2/tests/checking/typing/neq.exp, third_party/move/move-compiler-v2/tests/checking/typing/neq_invalid.exp, third_party/move/move-model/src/builder/exp_builder.rs
Close #11337 by dropping reference only when building a model for specifications. 
Note that the current solution will bring a new issue when handling equality on variance. I will file an issue once this is landed.
A new test `third_party/move/move-compiler-v2/tests/checking/typing/eq_inline.move` is added to validate the fix.
=> [Compiler-v2] Fix 11337

consensus/consensus-types/src/proof_of_store.rs, consensus/src/logging.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/proof_coordinator.rs, consensus/src/quorum_store/quorum_store_coordinator.rs, mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs
In particular, these improvements are important for blocks that reach gas limit. Without the improvements, txns did not get added to new batches until the existing batch expires.
- Immediately remove from batches in progress on commit (before expiry)
- Add commit notification for proof coordinator to remove in progress proofs
In addition, added more observability to the process of txns getting re-pulled into new batches.
- Add metrics for number of times txn is pulled in mempool, and some structured logs for proof coordinator
Forge stable tests
=> [Quorum Store] improve commit notification logic

third_party/move/move-compiler-v2/src/inliner.rs
Close #11422 by instantiating param type when rewrite a temp.
1) Existing tests still pass. 
2) Manually validate that the ICE disappears when following the instruction in #11422.
=> [Compiler-v2] Fix 11422

docker/compose/indexer-grpc/docker-compose.yaml, docker/compose/indexer-grpc/file-store-config.yaml, ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/lib.rs, ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/main.rs, ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs, ecosystem/indexer-grpc/indexer-grpc-file-store/src/lib.rs, ecosystem/indexer-grpc/indexer-grpc-file-store/src/main.rs, ecosystem/indexer-grpc/indexer-grpc-file-store/src/processor.rs, ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs, ecosystem/indexer-grpc/indexer-grpc-server-framework/src/lib.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs
To avoid a deadlock between cache worker and filestore, we should just have filestore update all the config, both in the metadata file and in the cache. Cache worker would no longer touch config such as chain_id and file_store_metadata_version
Note, this is breaking as we now need chain_id in the filestore yaml. Followups are
1. internally, we need chain id automation in deployment
2. also we need the chain id automation for localnet
3. externally, we may ship it with grpc release?
Initial upload of metadata.json fails, but verify it's eventually created. 
```
│ {"timestamp":"2023-12-19T22:53:33.275282Z","level":"ERROR","fields":{"message":"[File worker] Failed to update file store metadata. Retrying.","batch_start_version":0,"service_type":"file_worker"},"filename":"ecosystem/index │
```
=> [grpc] fix deadlock

aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs
(which runs exhaustive proptests)
=> fix e2e move test - disable stresstest mode

consensus/consensus-types/src/proof_of_store.rs, consensus/src/logging.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/proof_coordinator.rs, consensus/src/quorum_store/quorum_store_coordinator.rs, mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs
In particular, these improvements are important for blocks that reach gas limit. Without the improvements, txns did not get added to new batches until the existing batch expires.
- Immediately remove from batches in progress on commit (before expiry)
- Add commit notification for proof coordinator to remove in progress proofs
In addition, added more observability to the process of txns getting re-pulled into new batches.
- Add metrics for number of times txn is pulled in mempool, and some structured logs for proof coordinator
Forge stable tests
=> [Cherry-pick] [Quorum Store] improve commit notification logic (#11444)

third_party/move/move-compiler-v2/src/inliner.rs, third_party/move/move-model/src/ast.rs, third_party/move/move-model/src/builder/exp_builder.rs, third_party/move/move-model/src/builder/module_builder.rs, third_party/move/move-model/src/spec_translator.rs, third_party/move/move-prover/bytecode-pipeline/src/data_invariant_instrumentation.rs, third_party/move/move-prover/bytecode-pipeline/src/mono_analysis.rs, third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs
Clean up Move-Model AST visitors and exp_rewriter interfaces
- don't abuse `Result(Exp, Exp)` in ExpRewriter interfaces, since it's confusing (which one is changed?)
- OTOH, return `Option<()>` from the implementation of `ExpData::visit..` so we can use `None` to more convenient short-cutting with `?`.   Client visitor functions return `bool`, with `true` to continue, and `false` to exit early by short-cutting.
- While we're at it, rename `move_model::ast::ExpData::uses_memory` to `uses_no_memory` to match its semantics (fixing #10725).
=> [compiler] Clean up Move-Model AST visitors and exp_rewriter interfaces

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/gas.rs, aptos-move/e2e-move-tests/src/tests/fee_payer.rs
Test if the account resource exists before attempting to create the account resource. This solves potential devx issues around gas fees and also prevents potential errors when the account exists but sequence number 0 isn't expensive enough.
updated one of the tests to explicitly test for this condition.
=> [movevm] more validation for sponsored transaction

third_party/move/move-compiler-v2/src/bytecode_generator.rs, third_party/move/move-compiler-v2/tests/ability-checker/ability_violation.exp, third_party/move/move-compiler-v2/tests/ability-checker/ability_violation.move, third_party/move/move-compiler-v2/tests/bytecode-generator/global_invalid.exp, third_party/move/move-compiler-v2/tests/bytecode-generator/global_invalid.move, third_party/move/move-compiler-v2/tests/v1.matched, third_party/move/move-compiler-v2/tests/v1.unmatched, third_party/move/move-compiler/tests/move_check/typing/global_invalid.exp, third_party/move/move-compiler/tests/move_check/typing/global_invalid.move
For the global memory operation: `exists`, `move_from`, `move_to`, `borrow_global` and `borrow_global_mut`, the compiler requires that the type parameter must be converted into a concrete struct type during generation of stackless bytecode. Otherwise, it will panic with the message `panicked at 'expected Type::Struct, found: ...`, as mentioned in #11377. 
This PR changes this behavior by generating a compiler error instead of panicking.
Close #11377.
1) Added a new test `global_invalid.move` to validate the result. The same test case is also added to the V1 compiler.
2) Updated the test case `ability_violation.move`.
=> [Compiler-v2] Generate a compiler error for global memory operation with incorrect type parameter

Cargo.lock, crates/aptos-compression/Cargo.toml, crates/aptos-compression/src/client.rs, crates/aptos-compression/src/lib.rs, crates/aptos-compression/src/metrics.rs, crates/aptos-compression/src/tests.rs, mempool/src/tests/common.rs, network/framework/src/counters.rs, network/framework/src/protocols/wire/handshake/v1/mod.rs, state-sync/storage-service/types/src/responses.rs
This PR offers several small cleanups and metrics improvements to the `aptos-compression` crate (each in their own commit):
1. Move the compression client to a separate file. This prevents us from having to expose the metrics file globally.
2. Add a new error type so that we can differentiate between compression and decompression errors. 
3. Several small code cleanups and metric improvements. This includes: (i) adding metrics for sent and received messages (not just sent messages, as is being tracked today); (ii) better histogram buckets for tracking serialization and compression; and (iii) better metrics for tracking compression and decompression errors.
=> [Aptos Compression] Small cleanups and metrics improvements

aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs, aptos-move/aptos-transactional-test-harness/src/lib.rs, aptos-move/aptos-transactional-test-harness/tests/tests.rs, aptos-move/aptos-transactional-test-harness/tests/v2-tests/smoke_test.exp, aptos-move/aptos-transactional-test-harness/tests/v2-tests/smoke_test.move, third_party/move/testing-infra/transactional-test-runner/src/framework.rs
This just sets the framework up so we can test v2 code. It doesn't yet configure comparison testing which we may do later
=> [compiler-v2] Enable aptos transactional tests for debugging

third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs, third_party/move/move-compiler-v2/transactional-tests/tests/misc/approx_the_same.exp, third_party/move/move-compiler-v2/transactional-tests/tests/misc/approx_the_same.move
The function_generator uses liveness checks to determine whether to copy or move values onto the stack. This check worked wrong for an instruction like `y := OP x,x`. Since `x` is not alive after the instruction, `x` will be moved twice onto the stack, leading to MOVELOC_UNAVAILABLE error.
=> [compiler-v2] Fixes an issues in file format gen if temp is used twice

testsuite/forge-cli/src/main.rs
The tests are pretty close to the threshold and many recent runs failed due to this. Relaxing for release sanity over the holidays.
=> [Forge] Relax workload sweep ordered_to_commit: 1.5 -> 2.0

third_party/move/move-compiler/src/parser/syntax.rs, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_upper_bound.exp, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_loop_upper_bound.move, third_party/move/move-compiler/transactional-tests/tests/control_flow/for_type_mismatch.exp
In order to ensure that for loops are consistent with Rust semantics, as well as for efficiency, the upper_bound should be evaluated only once.
Refer to test `control_flow/for_loop_upper_bound.move`
=> Fix for loop upper bound bug

third_party/move/move-compiler-v2/tests/bytecode-generator/spec_construct.exp, third_party/move/move-compiler-v2/tests/checking/typing/nested_post_process.exp, third_party/move/move-compiler-v2/tests/checking/typing/nested_post_process.move, third_party/move/move-compiler-v2/tests/file-format-generator/with_spec.exp, third_party/move/move-model/src/ast.rs, third_party/move/move-model/src/builder/exp_builder.rs
During building of expressions, placeholders are used for expressions which can't be decided because of incomplete type inference. At the end when inference is complete, a post processing phase is run to replace those placeholders. This uses the expression rewriter, but that one doesn't descend on rewrite steps.
This adds a new `RewrittenAndDescend` variant to rewrite functions which instructs the rewriter to descend on rewritten exps. Fortunately, this is cleanly possible because we not longer use `Result` as a return value.
Adds one test case which exposed this behavior from `simple_map` in the aptos stdlib.
=> [compiler-v2] Fixes an issue in post-processing of exp_builder

.github/workflows/check-protos.yaml, protos/README.md, protos/typescript/src/aptos/indexer/v1/raw_data.ts, protos/typescript/src/aptos/internal/fullnode/v1/fullnode_data.ts, protos/typescript/src/aptos/remote_executor/v1/network_msg.ts
The CI is failing because in CI it generates the code and there are changes. I suspect this isn't a case of failing to check in updated code but of the tool versions changing. To address that, I pin the buf and protoc versions we use in CI.
See that the check protos CI passes now.
=> [protos] Regenerate TS code, pin tool versions in CI

state-sync/storage-service/server/src/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/optimistic_fetch.rs
This PR updates the optimistic fetch handler to better tolerate optimistic fetch requests that have been updated between: (i) when we first check to see if the request can be handled (i.e., we have the data to service the request); and (ii) when the request is finally handled (i.e., we fetch the data to send to the peer). It's possible that between these two times, a peer updates the optimistic fetch request with a higher known version. In this case, we want to avoid sending the old data to the peer and handle the new optimistic fetch request only when new data is ready.
Note: this race is rare and it does not cause any issues (except logging an error). But, this PR fixes the issue by ensuring that we only handle the request if it hasn't been updated since we last checked.
New and …
=> [State Sync] Update the optimistic fetch handler to handle check-to-use race.

Cargo.lock, Cargo.toml, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml, crates/aptos/src/node/local_testnet/hasura_metadata.json, crates/aptos/src/node/local_testnet/indexer_api.rs
This PR updates the CLI to use the latest processor code / Hasura metadata.
I make some changes to the deps to match the deps changes just landed in aptos-indexer-processors: https://github.com/aptos-labs/aptos-indexer-processors/pull/225. The changes to num-bigint look fine: https://github.com/rust-num/num-bigint/blob/master/RELEASES.md. If I take another crack it I might find that some of the version bumps here are unnecessary, but it's good to stay on top of these anyway. We'll see how the tests go.
```
cargo run -p aptos -- node run-local-testnet --with-indexer-api --force-restart --assume-yes
```
See that the local testnet comes up and the indexer API works, including with the web UI.
Run the TS SDK v2 tests against the local testnet:
```
pnpm test
```
```
Test Suites: 41 passed, 41 …
```
=> [CLI] Upgrade processors code used in local testnet

execution/executor-benchmark/src/ledger_update_stage.rs, execution/executor-benchmark/src/main.rs, execution/executor-benchmark/src/pipeline.rs, execution/executor-benchmark/src/transaction_executor.rs, execution/executor-types/src/state_checkpoint_output.rs
When transaction fails in executor benchmark, (with allow flags false), we only had output information, but no information about the transaction
So moving the checking logic to a place where we do have both, so we can give more useful info.
Also adding checks on no-retries.
=> [executor benchmark] more details on transaction failures

.cargo/config.toml, Cargo.lock, Cargo.toml, devtools/aptos-cargo-cli/Cargo.toml, devtools/aptos-cargo-cli/src/bin/cargo-x.rs, devtools/aptos-cargo-cli/src/cargo.rs, devtools/aptos-cargo-cli/src/common.rs, devtools/aptos-cargo-cli/src/lib.rs, devtools/aptos-cargo-cli/src/main.rs
Reopening #9463 as a new PR because the other one won't reopen.
This PR (re)introduces the target-determinator based cargo command wrapper from the diem project, albeit in a simplified and very opinionated way. The implementation details diverge from the original implementation and is tailored to the everyday use-case at Aptos. It uses the `determinator` [crate](https://docs.rs/determinator/latest/determinator/index.html), which was originally used in diem repo, to identify potentially affected packages between local changes and remote. 
As v0, the features are very limited:
- Only identifies changed packages with respect to local origin/main ref. It won't work for other branch such as release branches yet.
- Does not yet allow excluding certain packages such as smoke-tests if they are …
=> [devtools] (Re)Introducing target determinator cargo CLI

Cargo.lock, Cargo.toml
This PR bumps `mini-moka` to `0.10.3` (in response to this known issue with `0.10.2`:  https://github.com/moka-rs/mini-moka/issues/21)
=> [Cargo] Bump mini-moka to 0.10.3

aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/collection.move, aptos-move/framework/aptos-token-objects/sources/token.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move
cannot re-use function that accesses aggregators
also made it throughout that concurrent assets require aggregator api as well.
tested nft minting unit test, with making FeatureFlag::AGGREGATOR_V2_API disabled
=> fix nft minting

aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/collection.move, aptos-move/framework/aptos-token-objects/sources/token.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move
cannot re-use function that accesses aggregators
also made it throughout that concurrent assets require aggregator api as well.
tested nft minting unit test, with making FeatureFlag::AGGREGATOR_V2_API disabled
=> [cherry-pick of #11586] fix nft minting

aptos-move/aptos-debugger/Cargo.toml, aptos-move/aptos-debugger/src/aptos_debugger.rs, aptos-move/aptos-debugger/src/bin/remote-gas-profiler.rs
This adds a new binary `remote-gas-profiler` to the `aptos-debugger` crate. The tool allows you to generate a gas profiling report for a committed transaction.
Here's an example command:
```
cargo run -p aptos-move-debugger --bin remote-gas-profiler -- --version 721512672
rest https://testnet.aptoslabs.com/v1
```
=> [aptos-debugger] introduce remote-gas-profiler binary

aptos-move/aptos-gas-schedule/src/ver.rs
Quick search through the repo seems no feature is gated on 13 yet so it should be safe to update to 12 as it should be.
This was a miss from this PR https://github.com/aptos-labs/aptos-core/commit/1f0ba321d3680b3df888c0d2ee061e48ee88923c
=> Update lastest gas version

aptos-move/framework/aptos-framework/doc/delegation_pool.md, aptos-move/framework/aptos-framework/sources/delegation_pool.move
- Updated it to accurately use `operator_commission_percentage(pool_address)` instead of the field `pool.operator_commission_percentage` directly
=> Fix the view function `delegation_pool::get_add_stake_fee`

aptos-move/framework/aptos-framework/doc/delegation_pool.md, aptos-move/framework/aptos-framework/sources/delegation_pool.move
Cherry-picks https://github.com/aptos-labs/aptos-core/pull/11608
- Updated it to accurately use `operator_commission_percentage(pool_address)` instead of the field `pool.operator_commission_percentage` directly
=> [cherry-pick] Fix the view function `delegation_pool::get_add_stake_fee` (#11608)

api/openapi-spec-generator/src/fake_context.rs, api/test-context/src/test_context.rs, aptos-node/src/state_sync.rs, config/src/config/state_sync_config.rs, crates/aptos-rest-client/src/lib.rs, mempool/src/shared_mempool/coordinator.rs, mempool/src/tests/mocks.rs, mempool/src/tests/node.rs, mempool/src/tests/shared_mempool_test.rs, mempool/src/tests/test_framework.rs, state-sync/inter-component/mempool-notifications/src/lib.rs, state-sync/state-sync-driver/src/driver_factory.rs, state-sync/state-sync-driver/src/metrics.rs, state-sync/state-sync-driver/src/notification_handlers.rs, state-sync/state-sync-driver/src/storage_synchronizer.rs, state-sync/state-sync-driver/src/tests/driver.rs, state-sync/state-sync-driver/src/tests/driver_factory.rs, state-sync/state-sync-driver/src/tests/storage_synchronizer.rs, state-sync/state-sync-driver/src/tests/utils.rs
This PR makes several modifications to the way in which state sync handles post-processing of committed transactions, (e.g., notifying mempool, the storage service and the event subscription service). Specifically:
1. Instead of handling post-processing in the same task as the commit operation, we add a dedicated task to do it. The benefit of this is that is reduces the commit time in the state sync pipeline. Adding the new task updates the pipeline from `execute/apply -> update -> commit` to `execute/apply -> update -> commit -> commit post-process`.  The e2e performance tests show a ~10% reduction in commit time.
2. When notifying mempool of the committed transactions, we no longer wait for an `ack`. The ack is redundant (i.e., if we fail to receive an ack, we log an error and do …
=> [State Sync] Move commit post-processor to dedicated task

api/src/runtime.rs
I see no reason why we should restrict the headers we accept in our CORS policy, it has only caused us grief in the past. As far as I can tell the only reason you can configure this in CORS is for auth purposes, which is irrelevant for the node API.
Run local testnet on a machine behind a reverse proxy with a URL using https:
```
```
Run explorer from https://github.com/aptos-labs/explorer/pull/661 where the mainnet URL is hacked to that new URL. See that it works using a local testnet from this PR.
=> [API] Allow all headers in CORS policy

Cargo.lock, config/src/config/state_sync_config.rs, state-sync/data-streaming-service/Cargo.toml, state-sync/data-streaming-service/src/data_stream.rs, state-sync/data-streaming-service/src/streaming_service.rs, state-sync/data-streaming-service/src/tests/data_stream.rs
This PR adds a stream update notifier to the data streaming service. Whenever a data response is now received, the stream update notifier will be used to notify the data streaming service to process the response immediately (as opposed to waiting for each loop iteration at `50ms` apart). This helps to reduce the time between when a data response is received, and state sync is able to process it (this reduction is evident in the experiments).
The PR offers two commits:
1. Add a simple stream update notifier to the data streaming service (including several unit tests). Note: we still keep the existing (periodic) progress checks for redundancy. We can consider removing these in the future, but I'd prefer to leave them as-is (for now).
2. Spawn a dedicated task for data summary refreshes, so …
=> [Data Streaming Service] Add stream update notifier.

crates/aptos-crypto-derive/src/lib.rs, crates/aptos-crypto/src/unit_tests/cryptohasher.rs
In the output, currently 
```
let name = aptos_crypto::_serde_name::trace_name::<Baz<()>>()
let name = aptos_crypto::_serde_name::trace_name::<()>> ()
```
To fix this, we add a `,` after the `()` for the generics. This handles both single generics, as well as multiple.
Compilation works (and added test case)
=> [crypto] Fix CryptoHasher with multiple generics

aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-framework/doc/aptos_account.md, aptos-move/framework/aptos-framework/doc/coin.md, aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/aptos_account.move, aptos-move/framework/aptos-framework/sources/coin.move, aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/framework/aptos-framework/sources/object.move, crates/aptos-rosetta/src/types/objects.rs, crates/indexer/src/models/transactions.rs, execution/executor-test-helpers/src/integration_test_impl.rs
step 1 of #10529 
leave other modules for grabs.
ut
=> [event v2] double emitting in account, coin, fungible asset and object and migrate move-examples

aptos-move/framework/aptos-framework/doc/genesis.md, aptos-move/framework/aptos-framework/doc/overview.md, aptos-move/framework/aptos-framework/doc/reconfiguration.md, aptos-move/framework/aptos-framework/doc/reconfiguration_state.md, aptos-move/framework/aptos-framework/doc/reconfiguration_with_dkg.md, aptos-move/framework/aptos-framework/doc/stake.md, aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/framework/aptos-framework/sources/reconfiguration.move, aptos-move/framework/aptos-framework/sources/reconfiguration_state.move, aptos-move/framework/aptos-framework/sources/reconfiguration_with_dkg.move, aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/aptos-framework/sources/stake.spec.move
1. Define `0x1::reconfiguration_state::State` to store `reconfig_start_time`.
1. Update `stake::update_stake_pool()` to use `reconfig_start_time` instead of the current time when checking if `pending_inactive` should be released. This is to avoid potentially large gap between DKG stakes and new epoch stakes.
1. Refactor `stake::update_stake_pool()` to `stake::update_stake_pool(commit: bool): u64` to enable read-only mode and return new stake.
1. `stake::on_new_epoch()` refactored to `stake::update_validator_set_on_new_epoch(commit: bool): ValidatorSet` to enable read-only mode and return new validator set.
See [here](https://github.com/aptos-labs/aptos-core/pull/11458#issue-2051522444)
existing UTs
=> stake.move refactoring

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs, aptos-move/aptos-release-builder/data/release.yaml, aptos-move/e2e-move-tests/src/tests/smart_data_structures.data/sources/test.move, aptos-move/e2e-move-tests/src/tests/storage_refund.rs
in support of [AIP](https://github.com/aptos-foundation/AIPs/blob/49e3883bf80f16c91e8e995769f5b6e2b0077a92/aips/reduce_largest_accepted_transactions.md), with more explanations there.
New values come to approximatelly 90ms for execution limit, and 100ms for io limit.
=> Reduce max_execution_gas / max_io_gas on v1.8

aptos-move/e2e-move-tests/src/lib.rs, aptos-move/framework/tests/move_unit_test.rs, third_party/move/move-command-line-common/src/testing.rs, third_party/move/move-compiler-v2/src/lib.rs, third_party/move/tools/move-package/src/compilation/compiled_package.rs, third_party/move/tools/move-package/src/lib.rs, third_party/move/tools/move-package/tests/test_runner.rs
Honor MOVE_COMPILER_V2 (was ENABLE_V2) environment variable whenever 'aptos build' is used.  Also decrease V2 bytecode dumping a bit (was with --debug or MOVE_COMPILER_DEBUG, now also need dump-bytecode flag to be selected, to make debugging a bit more mangeable).  Also use standard method to read ENABLE_V2, so that "true" or "1" are acceptable values.
Also pass attributes through correctly to move-compiler-v2.
Shouldn't affect anything in the default case.  Manually tests show more existing bugs.
https://github.com/aptos-labs/aptos-core/issues/11573
and https://github.com/aptos-labs/aptos-core/issues/11575.
Seems to also fix https://github.com/aptos-labs/aptos-core/issues/11638.
=> add MOVE_COMPILER_V2 flag for all aptos compile, also reduce dump logging a bit (only if both debug and dump_bytecode flags are selected)

third_party/move/move-compiler-v2/tests/checking/specs/update_field_err.exp, third_party/move/move-compiler-v2/tests/checking/specs/update_field_err.move, third_party/move/move-compiler-v2/tests/checking/specs/update_field_ok.exp, third_party/move/move-compiler-v2/tests/checking/specs/update_field_ok.move, third_party/move/move-model/src/builder/exp_builder.rs
`update_field(x, f, val): X` is a built-in function in the prover where `x` is an instance of struct `X` , `f` is a field of `X` and `val` is a value that has the same type with `f`. It will return a new instance of `X` where all other fields keep the value of `x` and the field `f` takes the value `val`.
Currently, the function `translate_update_field` contains a constraint check for the field `f`, which is problematic because the expected type of `f` in this constraint is X instead of the type of `f`. 
This PR closes #11532 by fixing the expected type for the field.
1) Manually check DPN test passes (this will be added to unit test soon);
2) Add two new tests to tests/checking/specs;
3) Existing tests still pass.
=> [Prover][Move-Model] fix #11532

third_party/move/move-model/bytecode/src/livevar_analysis.rs, third_party/move/move-prover/tests/sources/functional/table_option.move
This PR closes #11534 by excluding the case of OpaqueCallBegin and OpaqueCallEnd from a code optimization in live var analysis for the prover. See added comments in the code for more information.
Added a new test case to validate the fix.
=> [Prover] fix #11534

api/src/runtime.rs
Internal context: https://aptos-org.slack.com/archives/C041CLG018F/p1705420540475269.
=> Cherry pick 3ab2c1761ebdbb2a7e2e8c8ff0a24e813289f70f into aptos-release-v1.9

.gitignore
Prevents accidental commits of compiler artifacts to the repo. 
Related to, but doesn't completely fix https://github.com/aptos-labs/aptos-core/issues/11636
Commits after compilation should not include artifacts, except for the pre-existing test directory.
=> Update .gitignore to not include .bytecode and .dot files

api/src/transactions.rs, api/src/view_function.rs, config/src/config/api_config.rs, config/src/config/transaction_filter_type.rs
This is one short term solution to the overall problem of nodes being overwhelmed by computationally expensive functions to the point where they can't even state sync.
Start local testnet:
```
```
Stop it, add `0x1::coin::balance` to the config in the blocklist:
```
view_filter:
blocklist:
- address: "0x1"
module: "coin"
function_name: "balance"
```
Start local testnet again:
```
cargo run -p aptos -- node run-local-testnet --with-indexer-api
```
Try to call view function from the explorer, get this response:
```
Error: {"message":"Function 0000000000000000000000000000000000000000000000000000000000000001::coin::balance is not allowed","error_code":"invalid_input","vm_error_code":null}
```
Other …
=> [API] Add filter support for view and simulate

CONTRIBUTING.md, crates/aptos/README.md, crates/aptos/homebrew/README.md
Updated links for the cli-tools and developer-docs. 
Markdown doc link fixes, in case if needed to test, just click on the old and new links. 😄
=> [docs] update links in markdown

state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/interface.rs, state-sync/data-streaming-service/src/data_notification.rs, state-sync/data-streaming-service/src/data_stream.rs, state-sync/data-streaming-service/src/metrics.rs, state-sync/data-streaming-service/src/stream_engine.rs, state-sync/data-streaming-service/src/tests/data_stream.rs, state-sync/data-streaming-service/src/tests/utils.rs, state-sync/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-driver/src/continuous_syncer.rs, state-sync/state-sync-driver/src/metrics.rs, state-sync/state-sync-driver/src/storage_synchronizer.rs, state-sync/state-sync-driver/src/tests/bootstrapper.rs, state-sync/state-sync-driver/src/tests/continuous_syncer.rs, state-sync/state-sync-driver/src/tests/mocks.rs, state-sync/state-sync-driver/src/tests/storage_synchronizer.rs, state-sync/state-sync-driver/src/utils.rs
This PR adds additional metrics to track end-to-end pipeline latencies in state sync (i.e., how long a data chunk takes from the moment it is received until it moves through the entire pipeline). 
1. Add a `new` method to `ResponseContext` (as a well as `creation_time`).
2. Add a `new` method to `DataNotification` (as a well as `creation_time`).
3. Add a metric to track the latency between a data chunk is received, and when it's sent along the data stream.
4. Add a metric to track the latencies of a data notification along the state-sync pipeline.
5. Small cleanups to the storage synchronizer (nothing should really change here).
=> [State Sync] Introduce metrics to track end-to-end pipeline latencies.

crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-generator-lib/src/account_generator.rs, crates/transaction-generator-lib/src/accounts_pool_wrapper.rs, crates/transaction-generator-lib/src/batch_transfer.rs, crates/transaction-generator-lib/src/call_custom_modules.rs, crates/transaction-generator-lib/src/entry_points.rs, crates/transaction-generator-lib/src/lib.rs, crates/transaction-generator-lib/src/p2p_transaction_generator.rs, crates/transaction-generator-lib/src/workflow_delegator.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, execution/executor-benchmark/src/transaction_generator.rs
More sophisticated smart contracts require moving users through a set of states, i.e. registering, joining, playing, collecting winnings.
These changes enable that:
- split out the publishing from creating generator - as we want to publish a single module, and use it for multiple transactions
- create a workflow based on pools, so that you can go to next transaction after all users have move to that stage.
Usage shown in https://github.com/aptos-labs/aptos-core/pull/11384
=> TransactionGenerator Workflow 

third_party/move/move-compiler-v2/tests/checking/friends/friend_decl_out_of_account_addr.exp, third_party/move/move-compiler-v2/tests/checking/friends/friend_decl_out_of_account_addr.move, third_party/move/move-compiler-v2/tests/checking/friends/friend_decl_self.exp, third_party/move/move-compiler-v2/tests/checking/friends/friend_decl_self.move, third_party/move/move-compiler-v2/tests/checking/friends/friend_decl_self_with_use.exp, third_party/move/move-compiler-v2/tests/checking/friends/friend_decl_self_with_use.move, third_party/move/move-compiler-v2/tests/checking/friends/friend_decl_unbound_module.exp, third_party/move/move-compiler-v2/tests/checking/friends/friend_decl_unbound_module.move, third_party/move/move-compiler-v2/tests/checking/friends/friend_different_addresses.exp, third_party/move/move-compiler-v2/tests/checking/friends/friend_different_addresses.move, third_party/move/move-model/src/lib.rs
This PR adds some missing checks in compiler v2 when it comes to friend declarations.
As per the move book (https://aptos.dev/move/book/friends#friend-declaration-rules), the following rules are applied when checking for correctly formed friend declarations:
- no self friend decls (check implemented in this PR, and in naming phase in v1)
- friending unbound module (checked in expansion phase already)
- friends should be within the same address (check implemented in this PR, and in naming phase in v1)
- no cyclic dependencies (checked in expansion phase already)
- duplicate friends (checked in expansion phase already)
- Ported relevant tests from compiler v1
- Added a couple of new ones
- Remaining tests remain as is, without changes
=> [compiler-v2] Invalid friend declaration warnings

.github/actions/move-tests-compiler-v2/action.yaml, .github/workflows/coverage-move-only.yaml, .github/workflows/move-test-compiler-v2.yaml
This PR:
1) adds a CI action to run aptos-framework and e2e-move-tests using Compiler V2;
2) adds aptos-framework as the target when running coverage test for move.
=> Add move tests for compiler V2 to CI

CODEOWNERS, crates/aptos-dkg/Cargo.toml
Removing a profile causing the warning: `profiles for the non root package will be ignored, specify profiles at the workspace root` when building the crate `aptos-dkg`. Also updating code owners on @alinush's request. 
N/A
=> [minor] Removing profile causing build warnings

aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/limit_processor.rs, aptos-move/block-executor/src/txn_last_input_output.rs, execution/executor-benchmark/src/lib.rs, types/src/block_executor/config.rs, types/src/on_chain_config/execution_config.rs
Start computing the accumulated block gas fee normally until you find a module publishing txn. Then recompute the accumulated block gas fee by setting conflict_multiplier == conflict_penalty_window for all preceeding txns, and continue accumulating with the same conflict_multiplier for subsequent txns in the block subsequent txns as well
=> Compute correct accumulated effective block gas fees with module publishing txn(s) in the block

docker/builder/build-node.sh, testsuite/forge-cli/src/main.rs
I noticed after adding the unstrip forge binary that failpoints is failing on main because forge doesnt define the failpoints feature
Then I realized that really only aptos node needs these special features so only build features with aptos node for now
=> [docker] Fix build-node for failpoints on push

api/goldens/aptos_api__tests__transactions_test__test_simulation_filter_allow_sender.json, api/goldens/aptos_api__tests__transactions_test__test_simulation_filter_deny.json, api/goldens/aptos_api__tests__view_function__test_view_allowlist.json, api/goldens/aptos_api__tests__view_function__test_view_blocklist.json, api/src/tests/transactions_test.rs, api/src/tests/view_function.rs
Before we roll out the feature to prod we should have tests confirming the filtering works and that it doesn't regress. This PR adds those tests.
Related to https://github.com/aptos-labs/aptos-core/pull/11666 and https://github.com/aptos-labs/aptos-core/pull/11714.
```
cargo test -p aptos-api
```
=> [API] Add tests for view function and txn simulation filters

consensus/src/pipeline/buffer_manager.rs, consensus/src/pipeline/commit_reliable_broadcast.rs, testsuite/generate-format/tests/staged/consensus.yaml
add CommitMessage::Nack to reply to ::Vote and ::Decision that don't get ::Ack
The real win is that the server doesn't leave RPCs hanging to timeout. Timeout error counters and log messages will be less spammy.
existing tests
=> add CommitMessage::Nack

CODEOWNERS, crates/aptos-dkg/benches/pvss.rs, crates/aptos-dkg/benches/weighted_vuf.rs, crates/aptos-dkg/src/pvss/test_utils.rs, crates/aptos-dkg/src/pvss/weighted/weighted_config.rs, crates/aptos-dkg/src/weighted_vuf/bls/mod.rs, crates/aptos-dkg/src/weighted_vuf/pinkas/mod.rs, crates/aptos-dkg/tests/dkg.rs, crates/aptos-dkg/tests/pvss.rs, crates/aptos-dkg/tests/weighted_vuf.rs
Some bureaucratic fixes to our benchmarking infrastructure.
Plus, fixed the BLS WVUF `verify_share` implementation to use the [BDN18] multisig verification, since we need to ensure individual shares are correct, not just their aggregation. Otherwise, an adversary can tweak two shares $(\sigma_1, \sigma_2)$ into $(\sigma_1 + \delta, \sigma_2 - \delta)$ and break the correctness of aggregation later on.
=> aptos-dkg extra benchmarking

ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
We should use spawn_blocking for CPU bound work: https://aptos-org.slack.com/archives/C04PF1X2UKY/p1706554218137959.
CI.
=> [Indexer] Use spawn_blocking for converting txns in stream coordinator

Cargo.lock, Cargo.toml
Our `tokio` dependencies are almost ~1.5 years behind the latest version (16+ months to be exact...). This PR brings us to the latest 😄 
=> [Cargo] Update tokio to the latest version.

api/src/transactions.rs, api/src/view_function.rs, config/src/config/api_config.rs, config/src/config/transaction_filter_type.rs
Context: https://aptos-org.slack.com/archives/C06BBLE5AHK.
=> Cherry pick bc4b3fcd449f3376f9e891245d9fb31e11016c13 into aptos-release-v1.9

Cargo.lock, api/Cargo.toml, api/src/context.rs, api/src/metrics.rs, api/src/runtime.rs, api/src/transactions.rs, api/src/view_function.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/e2e-move-tests/src/aptos_governance.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/constructor_args.rs, aptos-move/e2e-move-tests/src/tests/fungible_asset.rs, aptos-move/e2e-tests/src/executor.rs, config/src/config/api_config.rs, types/src/transaction/mod.rs
On PFNs, periodically (every minute) log the top-9 gas-using view functions and simulate transactions. This gives observability to the PFNs usage.
Utilizes a small cache that is reset every minute. Alternatively, such high-cardinality data would not work with prometheus.
Requires minimal changes to propagate gas usage.
Deploy PFN locally, observe log messages.
=> [cherry-pick] [API] [PFNs] improve observability of view function and simulate usage #11696

testsuite/single_node_performance.py
mostly first calibration for newly added workloads, and some small modifications
big change was for account-generation native, but that is month old - same as the coin-transfer todo (it just wasn't updated at that time as that runs only on continuous)
=> Recalibrate single_node_performance

.github/workflows/workflow-run-execution-performance.yaml
They're unreliable and causing spurious failures.
=> [GHA] Remove jobs `sequential-execution-performance` and `parallel-execution-performance`

third_party/move/move-compiler-v2/tests/checking/inlining/private_call_3.exp, third_party/move/move-compiler-v2/tests/checking/typing/bad_type_argument_arity_const.exp, third_party/move/move-compiler-v2/tests/checking/typing/constant_invalid_base_type.exp, third_party/move/move-compiler-v2/tests/checking/typing/constant_non_base_type.exp, third_party/move/move-compiler-v2/tests/folding/bad_type_argument_arity_const.exp, third_party/move/move-compiler-v2/tests/folding/constants_blocks.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/return_borrowed_local_invalid.exp, third_party/move/move-model/src/model.rs
Improve ordering of Errors/Warnings shown to user by comparing more than one Label/location when there are multiple locations in two diagnostics.
Fixes https://github.com/aptos-labs/aptos-core/issues/10935
Testing on existing move-compiler-v2 tests shows a change in 7 cases, manually checked they are an improvement.
=> Improve Diagnostic ordering further for multiple diagnostics with some of the same labels

aptos-move/aptos-aggregator/src/types.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/src/errors.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/txn_last_input_output.rs
- Disentangle abort and module r/w handling
- Perform halt centrally outside of the loop, forward errors
- Convert resource group errors to code invariant errors, create resource group serialization errors for bcs failure allowing specific sequential fallback handling in a coming PR or commit (e.g. skipping the transaction after alert)
- Change Result and Error type redefinitions to avoid ugly and confusing nomenclature.
Tests pass.
=> [Executor] Refactor errors, prepare for resource group bcs fallback

third_party/move/documentation/examples/diem-framework/move-packages/DPN/sources/DiemSystem.move, third_party/move/documentation/examples/diem-framework/move-packages/core/sources/configs/DiemSystem.move, third_party/move/documentation/examples/diem-framework/move-packages/experimental/sources/MultiToken.move, third_party/move/documentation/examples/diem-framework/move-packages/experimental/sources/MultiTokenBalance.move, third_party/move/move-compiler-v2/tests/checking/specs/len_ok.exp, third_party/move/move-compiler-v2/tests/checking/specs/len_ok.move, third_party/move/move-compiler-v2/tests/checking/specs/len_same_fun_name_err.exp, third_party/move/move-compiler-v2/tests/checking/specs/len_same_fun_name_err.move, third_party/move/move-compiler/tests/move_check/typing/len_err.exp, third_party/move/move-compiler/tests/move_check/typing/len_err.move, third_party/move/move-model/src/builder/exp_builder.rs
This PR closes #11737 by returning none in `translate_fun_call_special_cases` in the spec mode when the function call is a built-in function such that no type checking will be performed between the function and a local variable with the same name.
2) Add three unit tests to show the behavior of name conflict in different cases and validate the fix;
3) Compilation of DPN will not show the error in #11737.
=> [Compiler-v2] Fix type checking issue due to name conflicts between built-in functions and local variables

ecosystem/nft-metadata-crawler-parser/migrations/2024-01-31-221845_add_not_parsable_column/down.sql, ecosystem/nft-metadata-crawler-parser/migrations/2024-01-31-221845_add_not_parsable_column/up.sql, ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris.rs, ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris_query.rs, ecosystem/nft-metadata-crawler-parser/src/schema.rs, ecosystem/nft-metadata-crawler-parser/src/utils/counters.rs, ecosystem/nft-metadata-crawler-parser/src/utils/database.rs, ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Many submitted tokens do not have proper JSON or image NFT metadata URIs. This column flags that so that they are not reprocessed and lets us have more accurate metrics regarding the success rate of the parser. 
Tested locally + existing unit tests
=> [NFT Metadata Crawler] Add column to mark URIs to not be parsed

third_party/move/move-compiler-v2/tests/checking/inlining/lambda_cast.exp, third_party/move/move-compiler-v2/tests/checking/inlining/lambda_cast.move, third_party/move/move-compiler-v2/tests/checking/inlining/lambda_cast_err.exp, third_party/move/move-compiler-v2/tests/checking/inlining/lambda_cast_err.move, third_party/move/move-compiler-v2/tests/checking/specs/len_ok.exp, third_party/move/move-model/src/builder/exp_builder.rs
This PR closes #11810 by adding number type constraint to the expression type if it is not fully instantiated.
Added two test cases to validate the fix.
=> [Compiler-V2] add constraints when type checking the cast operation

aptos-move/framework/move-stdlib/doc/vector.md, aptos-move/framework/move-stdlib/sources/vector.move, aptos-move/framework/move-stdlib/tests/vector_tests.move
Adding the `range` and `slice` functions inside the `vector` module. 
- The `range` function generates a sequence of `u64` integers from a specified start to an end (exclusive), incremented by a given step.
- These are unsigned integers, therefore we don't need to handle negative number cases.
- The `slice` function takes a reference vector, specified start to an end (exclusive) and returns a new vector with the copied values from `start` to `end` index.
To run tests
1.  `cd` into directory `aptos-core/aptos-move/framework/move-stdlib`
2. run `aptos move test --filter test_range`
3. run `aptos move test --filter test_slice`
1. Happy case
4. Edge case where `start` and `end` are equal - (Should return empty vector)
5. Edge case where `end` is greater than `start`  - (Should return empty …
=> Add range, slice function in vector module

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/e2e-move-tests/src/tests/randomness_test_and_abort.rs, aptos-move/e2e-move-tests/src/tests/randomness_unsafe_public.data/pack/Move.toml, aptos-move/e2e-move-tests/src/tests/randomness_unsafe_public.data/pack/scripts/script.move, aptos-move/e2e-move-tests/src/tests/randomness_unsafe_public.data/pack/sources/some_randapp.move, aptos-move/e2e-move-tests/src/tests/randomness_unsafe_public_entry.data/pack/Move.toml, aptos-move/e2e-move-tests/src/tests/randomness_unsafe_public_entry.data/pack/scripts/script.move, aptos-move/e2e-move-tests/src/tests/randomness_unsafe_public_entry.data/pack/sources/some_randapp.move, aptos-move/framework/aptos-framework/doc/randomness.md, aptos-move/framework/aptos-framework/sources/randomness.move, aptos-move/framework/aptos-framework/sources/randomness.spec.move, aptos-move/framework/src/natives/randomness.rs, aptos-move/framework/src/natives/transaction_context.rs, aptos-move/move-examples/lottery/sources/lottery_insecure.move, aptos-move/move-examples/lottery/sources/lottery_secure.move, aptos-move/move-examples/raffle/sources/raffle.move, third_party/move/move-vm/runtime/src/session.rs
Test-and-abort attacks are described in [AIP-41](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-41.md#test-and-abort-attacks)
**Note:** Using similar tricks as in this [old chain ID PR](https://github.com/aptos-labs/aptos-core/pull/5288)
=> Address test-and-abort attacks in the randomness module (and some clean up)

third_party/move/move-compiler-v2/src/logging.rs
A module path for log filters has the form `crate::mod1::mod2`, but `:` was also used as a file separator, as in `MVC_LOG=info:test.log`. Replaced this with `MVC_LOG=info@test.log`. Also the string is now split on `@` from the right, so if there are multiple of those chars, we only take the last segment as file name.
=> [compiler v2] Fixing log specification file separator char

aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/tests/test_change_set.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-testsuite/src/tests/genesis.rs
Direct WriteSetPayload modifies state directly, without knowing if there are resource groups or aggregators inside. 
No transactions can be executed correctly, within same BlockSTM context, after it. So allow it to be in the block, and expect it to end the block if successfully executed.
=> [agg_v2] Allow Direct WriteSetPayload, only if it ends the block

ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator/gcs.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator/local.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator/mod.rs
Previously, fetching from GCS cold storage was single-threaded; this increases the thread count, which in turn increases max backfill TPS
To reduce gaps due to network blips, this also adds internal retries to the `FileStoreOperator`
(also adds `spawn_blocking` whenever we do cpu bound transformations on the data, because why not)
Tested in cdb-testnet, devnet
=> Parallel fetching for GCS 

types/src/dkg/real_dkg/mod.rs, types/src/dkg/real_dkg/rounding/mod.rs, types/src/dkg/real_dkg/rounding/tests.rs
Input validator_stakes, secrecy_threshold and recontruct_threshold, output validator_weights and reconstruct_threshold_in_stake_ratio.
Alert if the validator_weights is too large or reconstruct_threshold_in_stake_ratio > recontruct_threshold.
=> [Randomness] refactor rounding

terraform/helm/genesis/templates/genesis.yaml, terraform/helm/genesis/values.yaml
#11842 removed consensus config and execution config so they were not applied to forge
Ran ad-hoc forge test that overrides execution config and observed it is overridden: https://github.com/aptos-labs/aptos-core/actions/runs/7788659630
=> [forge] revert genesis to pre-#11842

.pre-commit-config.yaml, config/src/config/dag_consensus_config.rs, consensus/src/dag/adapter.rs, consensus/src/dag/anchor_election/leader_reputation_adapter.rs, consensus/src/dag/anchor_election/mod.rs, consensus/src/dag/anchor_election/round_robin.rs, consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/health/backoff.rs, consensus/src/dag/health/chain_health.rs, consensus/src/dag/health/mod.rs, consensus/src/dag/health/pipeline_health.rs, consensus/src/dag/mod.rs, consensus/src/dag/order_rule.rs, consensus/src/dag/round_state.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/order_rule_tests.rs, consensus/src/liveness/leader_reputation.rs, types/src/on_chain_config/consensus_config.rs, types/src/on_chain_config/mod.rs
- Refactors Chain health backoff by decoupling it from LeaderReputationAdapter.
- Adds PipelineBackpressure mechanism
- Organizes both chain health and pipeline backpressure into a health module
- Adds on chain configs for leader reputation adapter.
=> [dag] refactor/improve dag health monitoring

config/src/config/consensus_config.rs, config/src/config/quorum_store_config.rs, consensus/src/epoch_manager.rs, consensus/src/round_manager.rs, consensus/src/round_manager_test.rs, testsuite/forge-cli/src/main.rs, testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs, testsuite/smoke-test/src/rest_api.rs
With the improvements in VM load time, it's no longer necessary to have a very large block size for throughput. In fact, with the block gas limits, a large block size can be bad, because it leads to frequent block cuts.
With targeting a smaller block size, there's no more reason to have a separate quorum store enabled size. So combined into a single block size and simplified the logic.
Run e2e perf test.
=> [consensus] reduce block size to 2500, simplify logic by removing quorum store overrides

Cargo.lock, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/Cargo.toml, aptos-move/block-executor/src/errors.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/bencher.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/scheduler.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/unit_tests/mod.rs
Fix the issues stemming from https://github.com/aptos-labs/aptos-core/pull/11832 and beyond.
Previously, the errors were set during sequential commit preparation of the transactions. That allowed to set the first error encountered, as well as making sure errors were processed before non-error conditions for halting the scheduler / parallel execution (e.g. block gas limit, but also skip rest, or just having executed everything). However, even that logic was a bit flowed, since module publishing fallback can be observed non-deterministically (in terms of which transaction observes it), and also one of the motivations for above refactoring was to make error flows uniform, as some errors (such as delayed fields code invariants) can occur during execution (i.e. not in commit).
New design:
- …
=> [Block Executor] Fix halting logic

aptos-move/vm-genesis/src/lib.rs
Enable concurrent Token V2 structs from AIP-43.
We can do this now, that indexer change has landed. (which was blocking it)
(they will all be sequential until aggregator flag itself is enabled,
but this allows for new codepath to be executed and tested, and replay-verify to test aggregators)
=> Enable CONCURRENT_TOKEN_V2 flag

aptos-move/framework/aptos-framework/doc/state_storage.md, aptos-move/framework/aptos-framework/sources/state_storage.move
=> [Framework] Fix typo in state storage module

aptos-move/framework/aptos-stdlib/doc/math128.md, aptos-move/framework/aptos-stdlib/doc/math64.md, aptos-move/framework/aptos-stdlib/sources/math128.move, aptos-move/framework/aptos-stdlib/sources/math64.move
@davidiw @movekevin @junkil-park 
Add to the `u64` and `u128` math libraries an implementation of Euclid's algorithm for computing the greatest common divisor, along with tests
=> Add GCD algorithm to math library

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-emitter-lib/src/wrappers.rs
Various improvements as follows 
1. Add option to specify number of accounts to create - please note that the transactions per account argument is still supported and the code ensures that you specify only one of them. 
2. Add option to skip minting and funding of new accounts - this is needed to resume transaction emitter after a failure.
```
cargo run -p aptos-transaction-emitter --release -- emit-tx -t https://fullnode.devnet.aptoslabs.com -t https://fullnode.devnet.aptoslabs.com -t https://fullnode.devnet.aptoslabs.com -t https://fullnode.devnet.aptoslabs.com -t https://fullnode.devnet.aptoslabs.com -t https://fullnode.devnet.aptoslabs.com --mint-key ${DEVNET_MINT_KEY} --chain-id ${CHAIN_ID} --duration 60 --txn-expiration-time-secs 60  --mempool-backlog=1000 --expected-max-txns 300000 …
```
=> [Txn Emitter] Various improvements to the transaction emitter

aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/unit_tests/mod.rs
Thanks to @danielxiangzl for finding a status overwrite issue during commit.
It used to be for Abort, but now abort short-circuits and would not be an issue. However, if might already be a SkipRest.
Moved the checks earlier for status invariants, and made sure it errors out if status isn't recorded, warn wouldn't do much because some later operations would anyway assert. So this way we can utilize the new fallback flow if somehow there is an issue with the status.
I'm not sure if it's also worth doing that before the first delayed fields check.
=> [Block Executor] Fix committed status checks / skip rest

aptos-move/block-executor/src/errors.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/mvhashmap/src/unsync_map.rs
- If block execution runs into bcs serialization issue, run sequential execution that pre-serializes and skips txns that have an error.
- New test to check the fallback logic, re-using existing mock executor infrastructure.
Used to fix error propagation / halting issue, but now rebased on https://github.com/aptos-labs/aptos-core/pull/11899
=> [Block Executor] implement group serialization fallback, test

Cargo.lock, consensus/src/dag/adapter.rs, consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_fetcher.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_state_sync.rs, consensus/src/dag/dag_store.rs, consensus/src/dag/health/chain_health.rs, consensus/src/dag/order_rule.rs, consensus/src/dag/rb_handler.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/tests/fetcher_test.rs, consensus/src/dag/tests/order_rule_tests.rs, consensus/src/dag/tests/rb_handler_tests.rs
- Separated in-memory component of Dag store from persistence.
- `PersistentDagStore` handles both persistence and maintains the in-memory DAG store.
=> [dag] concurrent dag store

consensus/src/dag/rb_handler.rs
This PR enables the DAG RB handler to calculate and save node signatures concurrently.
=> [dag] support parallel rb voting

aptos-move/aptos-vm/src/zkid_validation.rs, aptos-move/framework/aptos-framework/doc/genesis.md, aptos-move/framework/aptos-framework/doc/zkid.md, aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/framework/aptos-framework/sources/zkid.move, aptos-move/vm-genesis/src/lib.rs, testsuite/generate-format/tests/staged/api.yaml, testsuite/generate-format/tests/staged/aptos.yaml, testsuite/generate-format/tests/staged/consensus.yaml, testsuite/smoke-test/src/zkid.rs, types/src/bn254_circom.rs, types/src/jwks/mod.rs, types/src/move_utils/as_move_value.rs, types/src/on_chain_config/mod.rs, types/src/transaction/authenticator.rs, types/src/zkid.rs
=> Properly handle `exp_horizon` + zkid.move VK & Configuration initialization in Rust

Cargo.lock, Cargo.toml, consensus/Cargo.toml, consensus/src/dag/anchor_election/leader_reputation_adapter.rs, consensus/src/dag/dag_driver.rs, crates/aptos-collections/Cargo.toml, crates/aptos-collections/src/bounded_vec_deque.rs, crates/aptos-collections/src/lib.rs
=> [dag] broadcast nodes within window till all validators ack

consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_store.rs, consensus/src/dag/order_rule.rs, consensus/src/dag/rb_handler.rs, consensus/src/dag/tests/helpers.rs, consensus/src/dag/tests/rb_handler_tests.rs, consensus/src/dag/types.rs, types/src/validator_verifier.rs
Instead of counting votes each time, this PR adds caching functionality for votes.
Also, checks for epoch when handling a RB node.
Fixed existing tests.
=> [dag] cache votes without re-counting

Cargo.lock, ecosystem/nft-metadata-crawler-parser/Cargo.toml, ecosystem/nft-metadata-crawler-parser/migrations/2024-02-08-013147_add_last_transaction_version/down.sql, ecosystem/nft-metadata-crawler-parser/migrations/2024-02-08-013147_add_last_transaction_version/up.sql, ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris.rs, ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris_query.rs, ecosystem/nft-metadata-crawler-parser/src/schema.rs, ecosystem/nft-metadata-crawler-parser/src/utils/database.rs, ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Found a bug where the wrong image is being shown due to overwriting images with the same `token_data_id`. These changes make the file names the SHA256 hash of their corresponding URI instead of its corresponding `token_data_id`. 
Works locally + unit tests
=> [NFT Metadata Crawler] SHA256 file names + last_transaction_version migration

aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/account.spec.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
This makes it explicit that were rotating an authentication key and eliminates the need for generating the complex proof the existing rotation method requires. This is viable because this is a private entry function that only a transaction can call into that is no scripts or other functions can call into.
=> [framework] introduce private entry function for auth key rotation

crates/transaction-emitter-lib/src/wrappers.rs
Create accounts doesn't take a separate init_max_gas_per_txn, so assign it to max_gas_per_txn.
Run command locally. In future, we need an integration test that keeps this from breaking.
=> [txn emitter] one liner to fix create-accounts command

consensus/src/network.rs, consensus/src/quorum_store/quorum_store_builder.rs
Enable BatchResponseV2 which was introduced in #11162, but not enabled then for backwards compatibility.
Do not add to 1.9 branch before deployment.
=> [Quorom Store] enable BatchResponseV2

.github/actions/rust-setup/action.yaml
Add an optional cache key for rust cache
In some cases (like where we build the binary on a different base os in the same job) this automatic job based cache key is not specific enough so we need to further differentiate it.
Test Plan: PR checks dont die
=> [gha] Add additional optional cache key

aptos-move/aptos-vm/src/zkid_validation.rs, testsuite/smoke-test/src/zkid.rs
This fixes the JWT that was being used in the smoke test with a new one.  The old one expired causes the test to fail without a code change.  This new one will expire in 8 months.  There is a TODO to be able to generate the JWT for the test so that the expiry doesn't have to be hardcoded in.
JWT generated via https://token.dev/
=> Fix zkid smoke tests

testsuite/forge-cli/src/main.rs
We are consistently getting more than 6500 TPS on land blocking. Hence increasing the threshold. 
Forge
=> [Forge] Increase land blocking threshold

consensus/src/block_preparer.rs, consensus/src/lib.rs, consensus/src/transaction_shuffler/fairness/conflict_key/entry_fun.rs, consensus/src/transaction_shuffler/fairness/conflict_key/entry_fun_module.rs, consensus/src/transaction_shuffler/fairness/conflict_key/mod.rs, consensus/src/transaction_shuffler/fairness/conflict_key/test_utils.rs, consensus/src/transaction_shuffler/fairness/conflict_key/txn_sender.rs, consensus/src/transaction_shuffler/fairness/conflict_zone.rs, consensus/src/transaction_shuffler/fairness/mod.rs, consensus/src/transaction_shuffler/fairness/pending_zone.rs, consensus/src/transaction_shuffler/fairness/selection_tracker.rs, consensus/src/transaction_shuffler/fairness/tests/manual.rs, consensus/src/transaction_shuffler/fairness/tests/mod.rs, consensus/src/transaction_shuffler/fairness/tests/proptests.rs, consensus/src/transaction_shuffler/mod.rs, consensus/src/transaction_shuffler/sender_aware.rs, testsuite/forge-cli/src/main.rs, types/src/on_chain_config/execution_config.rs
FairnessShuffler that tries to spread out (delay) transactions from dominant modules in a block.  
See inline documents and tests.
Unittests
=> FairnessShuffler

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/aptos-vm/src/sharded_block_executor/global_executor.rs, aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs, aptos-move/block-executor/src/errors.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/executor_utilities.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/bencher.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/mvhashmap/src/unsync_map.rs, aptos-node/src/utils.rs, config/src/config/execution_config.rs, testsuite/smoke-test/src/execution.rs, testsuite/smoke-test/src/lib.rs, types/src/block_executor/config.rs
- make executor resilient to aggregator exceptions. where possible, skip transactions that are failing
- cleanup errors across parallel and sequential execution
- and discard_failed_blocks
=> [agg_v2] executor exceptions propagation

consensus/consensus-types/src/proof_of_store.rs, consensus/src/epoch_manager.rs, consensus/src/logging.rs, consensus/src/quorum_store/batch_coordinator.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/proof_coordinator.rs, consensus/src/quorum_store/quorum_store_builder.rs, consensus/src/quorum_store/tests/batch_generator_test.rs, consensus/src/quorum_store/tests/batch_store_test.rs, consensus/src/round_manager.rs
Occasionally, the metrics show batches not getting quorum, in forge and testnet.
1. There are false positives (didn't actually expire, only in the metrics), due to batches getting late votes, after they have been committed. This is resolved by caching the committed batches until expiration time; only really really late votes would cause false positives.
2. There are proofs that actually expire without getting quorum. These are written too late into the QS DB; if the entry does not exist in the DB, the vote is discarded, and in some cases more than 33% of votes are actually discarded. This is resolved by writing to the DB in batch_generator, before broadcasting the Batch.
In addition the counters for counting proof votes are cleaned up, so the votes/stake are counted on expire time (as …
=> [Quorum Store] improvements to prevent some batches not getting quorum

consensus/safety-rules/src/safety_rules.rs, consensus/src/counters.rs, consensus/src/epoch_manager.rs, consensus/src/liveness/leader_reputation.rs, state-sync/storage-service/server/src/handler.rs
=> clean error log lines

Cargo.lock, Cargo.toml, api/types/src/convert.rs, ecosystem/indexer-grpc/indexer-grpc-table-info/Cargo.toml, ecosystem/indexer-grpc/indexer-grpc-table-info/src/backup_restore/fs_ops.rs, ecosystem/indexer-grpc/indexer-grpc-table-info/src/backup_restore/gcs.rs, ecosystem/indexer-grpc/indexer-grpc-table-info/src/backup_restore/mod.rs, ecosystem/indexer-grpc/indexer-grpc-table-info/src/lib.rs
1. add gcs operator utils
**[1/4] separate indexer async v2 db from aptosdb : https://github.com/aptos-labs/aptos-core/pull/11799
[2/4] add gcs operational utils to set up for backup and restore to gcs: https://github.com/aptos-labs/aptos-core/pull/11793
[3/4] add epoch based backup logic: https://github.com/aptos-labs/aptos-core/pull/11794
[4/4] add db snapshot restore logic: https://github.com/aptos-labs/aptos-core/pull/11795**
https://www.notion.so/aptoslabs/Internal-Indexer-Deprecation-Next-Steps-824d5af7f16a4ff3aeccc4a4edee2763?pvs=4
1. Migrating internal indexer off of aptos db critical path, move it into its own standalone runtime service.
7. Still provide the table info mapping to both API and indexer services.
8. improve table info parsing performance to unblock indexer perf …
=> [table info][2/4] add utils for table info backup and restore and redesign the db read

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-vm-types/src/resolver.rs, aptos-move/aptos-vm-types/src/resource_group_adapter.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-move-tests/src/aggregator_v2.rs, aptos-move/e2e-move-tests/src/resource_groups.rs, aptos-move/e2e-move-tests/src/tests/aggregator_v2_events.rs, aptos-move/e2e-move-tests/src/tests/aggregator_v2_runtime_checks.rs, aptos-move/e2e-move-tests/src/tests/resource_groups.rs, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
old name was stale, when charging was what was different, but we changed the logic to keep backward compatible charging, and only affect VmChangeSet split
=> [simple] rename RG split in VmChangeSet flag

docker/builder/docker-bake-rust-all.hcl
=> Update Docker images

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json, api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json, aptos-move/aptos-gas-calibration/samples_ir/vector/vec-generic.mvir, aptos-move/aptos-gas-meter/src/meter.rs, aptos-move/aptos-gas-profiling/src/aggregate.rs, aptos-move/aptos-gas-profiling/src/erased.rs, aptos-move/aptos-gas-profiling/src/flamegraph.rs, aptos-move/aptos-gas-profiling/src/log.rs, aptos-move/aptos-gas-profiling/src/profiler.rs, aptos-move/aptos-gas-schedule/src/gas_schedule/instr.rs, aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs, aptos-move/aptos-memory-usage-tracker/src/lib.rs, aptos-move/aptos-vm-profiling/move/subst_ty/node_size_16.mvir, aptos-move/aptos-vm-profiling/move/subst_ty/node_size_8.mvir, aptos-move/e2e-move-tests/src/tests/smart_data_structures.rs, aptos-move/e2e-move-tests/src/tests/storage_refund.rs, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account.exp, testsuite/single_node_performance.py, third_party/move/move-binary-format/src/file_format.rs, third_party/move/move-core/types/src/gas_algebra.rs, third_party/move/move-vm/runtime/src/interpreter.rs, third_party/move/move-vm/runtime/src/loader/mod.rs, third_party/move/move-vm/test-utils/src/gas_schedule.rs, third_party/move/move-vm/types/src/gas.rs, third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
This cherry picks a few VM changes we have been working on recently.
=> Cherry-pick VM changes

Cargo.lock, crates/aptos/Cargo.toml, crates/aptos/src/node/local_testnet/processors.rs
* This is to fix the CI issue that newer transaction types are not recognized by indexer. We introduce safe handling in a recent processor. Thus upgrading can solve the issue.
=> [CI][indexer] fix the e2e localnet.

.github/workflows/docker-build-test.yaml, aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs, aptos-move/aptos-gas-schedule/src/ver.rs
Also be conservative and leave legacy parameters in >14 versions for
now. Need to clean up after REFUNDABLE_BYTES feature is actually enabled
on all networks.
also change compat test base on PRs to the `testnet` tag
=> bump latest gas feature version to 14

.github/actions/general-lints/action.yaml, .github/actions/python-lint-tests/action.yaml, .github/actions/rust-lints/action.yaml, .github/actions/rust-setup/action.yaml, .github/actions/rust-smoke-tests/action.yaml, .github/actions/rust-unit-tests/action.yaml, .github/workflows/lint-test.yaml
* actions/checkout@v4 doesn't behave well if both a workflow and an invoked action checkout the source code on top of each other.
* update pin for tj-actions/changed-files
Commit and see if it breaks anything.
=> [GHA] Upgrade lint-test.yaml and the dependent actions to checkout@v4

aptos-move/aptos-release-builder/data/proposals/aip_67_initialization.move, aptos-move/aptos-release-builder/data/proposals/start_jwk_consensus_for_google.move, aptos-move/aptos-release-builder/data/release.yaml
=> start jwk consensus for google

aptos-move/block-executor/src/errors.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/txn_last_input_output.rs
- when FatalVMError happens, we have those logs, it doesn't get wrapped into delayed materialization code invariant error
- do not alert on FatalVMError - if it is invariant - it is already alerted, if it is node issue (i.e. old binary so VM_STARTUP_FAILURE) alert is too aggressive
=> FatalVMError shouldn't create "Delayed materialization code invariant"

.github/workflows/docker-build-test.yaml, aptos-move/aptos-release-builder/data/release.yaml
- Provide a valid URL for discussion, which resolves the framework_upgrade CI test failure
- Bump up the base commit to 1.9.5 for the compat test and framework_upgrade test
=> Resolved the `framework_upgrade` CI test failure

third_party/move/move-compiler-v2/src/experiments.rs, third_party/move/move-compiler-v2/src/lib.rs, third_party/move/move-compiler-v2/src/pipeline/mod.rs, third_party/move/move-compiler-v2/src/pipeline/split_critical_edges_processor.rs, third_party/move/move-compiler-v2/tests/testsuite.rs, third_party/move/move-model/bytecode/src/stackless_bytecode.rs
Implements a compiler pass that eliminates critical edges by splitting them with empty blocks, making it easier for later passes to add code along control flow graph edges. 
After critical edges are eliminated, to add a new code block between `BB0` and `BB1`:
- If the edge `BB0 -> BB1` is a conditional jump, prepend the new block to `BB1`. This is because `BB0` has multiple successors so `BB1` cannot have multiple predecessors.
- Otherwise append the new block to `BB0`, since unconditional jumps have only one successor.
The pass can be turned on with the experiment flag `"split-critical-edges"`.
There is currently no way to directly test for this pass, since the bytecode generator doesn't seem to create any critical edges. (I've tested it personally where I modified the bytecode generator …
=> [Compiler V2] Critical edge elimination

config/src/config/consensus_config.rs
The block output limit is no longer hit with p2p txns.
Forge `realistic_env_max_load` TPS improves.
=> [consensus configs] reduce sending block size from 2500 to 1900

Cargo.lock, crates/aptos-admin-service/src/server/mod.rs, crates/aptos-admin-service/src/server/profiling.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs, ecosystem/indexer-grpc/indexer-grpc-server-framework/Cargo.toml, ecosystem/indexer-grpc/indexer-grpc-server-framework/src/lib.rs
host:port/profilez will start returning cpu profiling result.
Current use duration = 10s, frequency = 99Hz, format = flamegraph, will try to make it configurable in the future.
=> [Indexer-grpc] Add profiling support.

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json, api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json, aptos-move/framework/aptos-framework/doc/block.md, aptos-move/framework/aptos-framework/doc/randomness.md, aptos-move/framework/aptos-framework/sources/block.move, aptos-move/framework/aptos-framework/sources/randomness.move, testsuite/smoke-test/src/randomness/disable_feature_0.rs, testsuite/smoke-test/src/randomness/disable_feature_1.rs, testsuite/smoke-test/src/randomness/mod.rs
... so applications have no seed to consume and then abort (instead of reusing the previous seed, which is worse).
=> clean up randomness seed in block metadata when feature is disabled

aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/account.spec.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
because the auth key isn't verified, the OriginatingAddress table can be manipulated with false entries, therefore eliminate the ability for the unverified auth key rotations from manipulating it.
=> [move] rotate_authentication_key_call should not modify OriginatingAddress

config/src/config/state_sync_config.rs, state-sync/data-streaming-service/src/data_notification.rs, state-sync/data-streaming-service/src/data_stream.rs, state-sync/data-streaming-service/src/dynamic_prefetching.rs, state-sync/data-streaming-service/src/lib.rs, state-sync/data-streaming-service/src/metrics.rs, state-sync/data-streaming-service/src/tests/data_stream.rs, state-sync/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-driver/src/storage_synchronizer.rs, state-sync/state-sync-driver/src/tests/mocks.rs, state-sync/state-sync-driver/src/tests/storage_synchronizer.rs
Note: > 80% of this PR is just unit test changes/additions.
This PR adds dynamic prefetching support to the data streaming service. Instead of having a static (config-defined) maximum number of in-flight requests, we now dynamically increase/decrease the maximum based on successful RPC responses and timeouts, i.e., for each successful response we increase the value (e.g., +1), for each timeout we decrease the value (e.g., -3), and when we see a timeout, freeze the increases for some time (e.g., 30 secs), to regain stability.
The feature is config gated, and the experiments show significant improvements for `mainnet` PFNs running in GCP, e.g., a `40%` improvement in fast syncing time when combined with latency aware peer dialing (already landed).
1. Add …
=> [Data Streaming Service] Add support for dynamic prefetching

consensus/src/block_storage/sync_manager.rs, consensus/src/epoch_manager.rs, consensus/src/network.rs, consensus/src/quorum_store/batch_coordinator.rs, consensus/src/recovery_manager.rs, consensus/src/round_manager.rs, consensus/src/round_manager_fuzzing.rs, consensus/src/round_manager_test.rs, testsuite/forge-cli/src/main.rs
In order to reduce latency in the round manager, use Arc pointers for NetworkSender to reduce the latency of cloning the NetworkSender.
Evaluate the latency of this change by running forge test with 100 nodes on this PR and compare the stats with the main branch.
The results can be compared here:
Forge test on this branch: https://github.com/aptos-labs/aptos-core/actions/runs/7965930582
Forge test on main branch: https://github.com/aptos-labs/aptos-core/actions/runs/7965951082
=> Reduce latency of cloning network sender using Arc pointers

aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/object_code_deployment.rs, aptos-move/framework/aptos-framework/doc/object_code_deployment.md, aptos-move/framework/aptos-framework/sources/object_code_deployment.move, aptos-move/framework/cached-packages/src/aptos_stdlib.rs, aptos-move/framework/src/natives/object_code_deployment.rs
backward incompatible change, to be included before current code is deployed  to testnet
main change is in the API in the object_code_deployment.move:
- since holding ExtendRef is internal implementation, renaming to ManagingRefs (similarly to naming in managed_fungible_asset.move)
- changing argument of upgrade to be Object<PackageRegistry> to align with freeze, and to not expose internal ManagingRefs object.
=> ObjectCodeDeployment API cleanup update

aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/object_code_deployment.rs, aptos-move/framework/aptos-framework/doc/object_code_deployment.md, aptos-move/framework/aptos-framework/sources/object_code_deployment.move, aptos-move/framework/cached-packages/src/aptos_stdlib.rs, aptos-move/framework/src/natives/object_code_deployment.rs
=> [cp #12133] ObjectCodeDeployment API cleanup update

aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/object_code_deployment.rs, aptos-move/framework/aptos-framework/doc/object_code_deployment.md, aptos-move/framework/aptos-framework/sources/object_code_deployment.move, aptos-move/framework/cached-packages/src/aptos_stdlib.rs, aptos-move/framework/src/natives/object_code_deployment.rs
=> ObjectCodeDeployment API cleanup update (#12133)

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/framework/aptos-framework/sources/object.spec.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
This PR enables the max object nesting check
=> Enable the max object nesting check

aptos-move/framework/aptos-framework/sources/account.move
Resolved the following warning for unused variable in `account.move` unit tests
```
warning[W09003]: unused assignment
┌─ /Users/jpark/Work/aptos-labs/aptos-core/aptos-move/framework/aptos-framework/sources/account.move:1349:13
│
1349 │         let new_addr = from_bcs::to_address(new_auth_key);
│             ^^^^^^^^ Unused assignment or binding for local 'new_addr'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_new_addr')
```
=> [Framework] Resolved the warning for unused variable

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml, crates/aptos/src/node/local_testnet/hasura_metadata.json, crates/aptos/src/node/local_testnet/processors.rs
This PR updates the aptos-indexer-processors dep. I see a few weeks back the dep was updated and the object processor was made available but unusable in the local testnet. This PR fixes that and enables it.
Ran local testnet, saw that objects table exists, processor is processing, etc. Let's see how the TS SDK tests go.
=> [CLI] Update aptos-indexer-processors dep to d5dc7a00, enable objects processor

.github/actions/run-faucet-tests/action.yaml, crates/aptos-faucet/core/src/server/run.rs, crates/aptos-faucet/integration-tests/main.py, crates/aptos/e2e/main.py
Improve platform handling in the faucet and CLI e2e tests so you don't have to worry about the docker platform env vars.
Beyond that, I fixed the faucet CI in two ways:
- The tests for confirming that the faucet works with the existing devnet / testnet were broken due to code changing, but I suppose the tests were disabled so the bad change landed. [Broken run](https://github.com/aptos-labs/aptos-core/actions/runs/8000725904/job/21851191929?pr=12161).
- The breakage came from 72f04e09def0f6ed796a00a83b1b52fa31a5e860 so the tests have been broken for a hot minute. Only the tests were broken.
- The tests for confirming that upstream changes don't break compatibility with the existing faucet were broken due to syntax error in the CI that I think I messed up ages ago.
I changed …
=> [E2E] Improve platform handling, fix faucet tests

consensus/src/state_computer.rs
This PR unifies the different Mutex fields in ExecutionProxy by moving them to a Inner struct wrapped with a RwLock. This should prevent any potential accidental lock reordering deadlocks in state computer.
=> [consensus] unify different locks in state_computer

consensus/src/counters.rs, consensus/src/round_manager.rs
=> metrics + logs of proposed vtxn count & size

config/src/config/consensus_config.rs, config/src/config/quorum_store_config.rs
As the recent block size change means txns are removed at max at a slower rate (previously, a portion of these txns were block cut).
e2e perf test for QsPosToProposal reduction: ~0.4s -> ~0.2s
=> [quorum store] reduce QS backpressure txn limit to 12K

consensus/src/dag/adapter.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_fetcher.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_store.rs, consensus/src/dag/order_rule.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/network.rs, testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs, testsuite/smoke-test/src/consensus/dag/dag_fault_tolerance.rs, testsuite/smoke-test/src/consensus/dag/mod.rs, testsuite/smoke-test/src/consensus/mod.rs
This PR copies the existing consensus smoke tests and adapts it to DAG consensus. It also includes two fixes identified from running the tests.
- Any fetch was fetching from the lowest incomplete round, but that is not realistic as validators fail to propose and rounds can be incomplete. Using the lowest incomplete round as the start round for fetch resulted in fetching >30 (3*window) rounds and failing because thats the GC limit. However, we only need to fetch the last 10 (window) rounds as that's the window we order.
- When a validator processes a certified node after its missing parents have been fetched, all the nodes in the fetched rounds should be processed to ensure prompt ordering. Otherwise the ordering can be arbitrarily delayed until a round that mis-matches the parity of last …
=> [dag] Smoke tests and related fixes

consensus/src/consensus_provider.rs, consensus/src/dag/tests/integration_tests.rs, consensus/src/epoch_manager.rs, consensus/src/network.rs, consensus/src/network_tests.rs, consensus/src/pipeline/execution_client.rs, consensus/src/pipeline/tests/buffer_manager_tests.rs, consensus/src/round_manager_fuzzing.rs, consensus/src/round_manager_test.rs, consensus/src/twins/twins_node.rs, crates/channel/src/lib.rs, network/framework/src/protocols/wire/messaging/v1/test.rs
Since the messages are from self, no need for this to be bounded. Having a bounded channel runs into the risk of blocking the round manager thread when the channel is full. 
UTs
=> [Consensus] Use unbounded channel for self messages

ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
This fixes a bug which allowed for unbounded number of fetcher tasks to spawn, causing data service to OOM. The bug only happens when processor ending_version (transactions_count) is set. 
1. Deploy to devnet
2. Run backfill processor with ending_version set
3. See that processor receives txn's and data service ingress isn't crazy high
=> Fix max fetcher tasks

types/src/block_metadata_ext.rs, types/src/on_chain_config/aptos_features.rs, types/src/on_chain_config/consensus_config.rs, types/src/on_chain_config/mod.rs
=> types update from randomnet 3

types/src/on_chain_config/execution_config.rs
This extends block size increase by 1/3, so up to 2500.
=> Increase block limits (gas/output) to match concurrency level increases

types/src/on_chain_config/execution_config.rs
This extends block size increase by 1/3, so up to 2500.
=> [cp v1.10] Increase block limits (gas/output) to match concurrency level increases (#12207)

config/src/config/consensus_config.rs, consensus/src/dag/adapter.rs, consensus/src/dag/dag_driver.rs, testsuite/forge-cli/src/main.rs, testsuite/forge-cli/src/suites/dag.rs, testsuite/forge-cli/src/suites/mod.rs, testsuite/testcases/src/dag_onchain_enable_test.rs, types/src/on_chain_config/consensus_config.rs
=> [forge] dag land blocking-style and stable tests

Cargo.lock, aptos-node/Cargo.toml, aptos-node/src/utils.rs, config/src/config/execution_config.rs
Since we have upgraded our default machine spec, we need to bump up the concurrency level to utilize the additional cores. 32 concurrency level worked the best from our previewnet load test.
Forge
=> [Execution] Increase the default concurrency to 32

types/src/on_chain_config/execution_config.rs
- forgot to update block output limit for concurrency increase
- make fairness reordering less aggressive to start with
=> update execution config

Cargo.lock, aptos-node/Cargo.toml, aptos-node/src/utils.rs, config/src/config/execution_config.rs
Since we have upgraded our default machine spec, we need to bump up the concurrency level to utilize the additional cores. 32 concurrency level worked the best from our previewnet load test.
Forge
=> [Execution] Increase the default concurrency to 32 

consensus/src/quorum_store/batch_store.rs
This shaves off ~10ms per round for max load test during prefetch, as the local batch reads also require reading from DB. (Impact should be larger when sending from more VFNs)
=> [quorum store] do local batch fetch also async, so prefetch is not slow

testsuite/forge-cli/src/main.rs, testsuite/forge/src/backend/k8s/swarm.rs
=> Reverting forge changes

config/src/config/state_sync_config.rs
This PR makes a few small tweaks to the state sync configs for previewnet to help reduce network pressure for nodes with bad networks. Specifically, we reduce the max chunk sizes, the max number of multi-fetch requests, and the min prefetching value.
=> [State Sync] Reduce network pressure for nodes with bad networks.

consensus/consensus-types/src/common.rs, consensus/src/counters.rs, consensus/src/round_manager.rs
For blocks with many batches, using par_iter significantly improves proposal processing time.
The counters were used to find this issue in prep for previewnet.
Observe counters changed in forge. Existing forge tests.
=> [consensus] verify proposals in parallel, add counters

api/src/context.rs, storage/aptosdb/src/db/include/aptosdb_internal.rs, storage/aptosdb/src/db/include/aptosdb_reader.rs, storage/aptosdb/src/db/mod.rs, storage/aptosdb/src/fake_aptosdb.rs, storage/aptosdb/src/ledger_db/event_db.rs, storage/aptosdb/src/ledger_db/ledger_metadata_db.rs, storage/aptosdb/src/schema/block_by_version/mod.rs, storage/aptosdb/src/schema/block_info/mod.rs, storage/storage-interface/src/lib.rs, types/src/block_info.rs, types/src/contract_event.rs
utilize the block indices for block timestamp fetching
avoid double logging api calls
instead, emit metrics only on the outmost call
=> [previewnet] [cherry pick] remove more cases of dependency on the event index (use the block indices instead) #12245

api/src/context.rs, storage/aptosdb/src/db/include/aptosdb_internal.rs, storage/aptosdb/src/db/include/aptosdb_reader.rs, storage/aptosdb/src/db/mod.rs, storage/aptosdb/src/fake_aptosdb.rs, storage/aptosdb/src/ledger_db/event_db.rs, storage/aptosdb/src/ledger_db/ledger_metadata_db.rs, storage/aptosdb/src/schema/block_by_version/mod.rs, storage/aptosdb/src/schema/block_info/mod.rs, storage/storage-interface/src/lib.rs, types/src/block_info.rs, types/src/contract_event.rs
When sharded DB is enabled, a lot of warning are printed because we are still querying the event indices in a few places. This is to remove those cases.
=> remove more cases of dependency on the event index (use the block indices instead)

config/src/config/consensus_config.rs
For now, let's avoid backpressure as it adds more noise.
=> [previewnet] higher limits pipeline backpressure

consensus/src/pipeline/buffer_manager.rs
We send out the epoch change notification before spawning the commit task, so there's race condition that epoch manager shuts down the buffer manager before the request created and we lose the final commit task.
=> [consensus] fix the race condition with the order of operations

ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris.rs, ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris_query.rs, ecosystem/nft-metadata-crawler-parser/src/utils/database.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Previously set the duplicate CDN URIs in the model but didn't write the models to DB
Also cleaned up some code
Works locally (different asset_uri, same raw_image_uri, copy over cdn_image_uri)
=> [NFT Metadata Crawler] Fix not committing duplicate images and animations

third_party/move/move-compiler-v2/tests/checking/typing/main_return_type_not_unit.exp, third_party/move/move-compiler-v2/tests/checking/typing/main_return_type_not_unit.move, third_party/move/move-compiler-v2/tests/v1.matched, third_party/move/move-compiler-v2/tests/v1.unmatched, third_party/move/move-model/src/builder/module_builder.rs
This PR closes #12077 by adding a check on the return type of functions defined in a script.
2) port the test `main_return_type_not_unit.move` from V1 to V2.
=> [Compiler-v2] Fix issue 12077

aptos-move/framework/aptos-framework/sources/multisig_account.move, aptos-move/framework/aptos-token-objects/sources/collection.move, aptos-move/framework/tests/move_unit_test.rs, aptos-move/move-examples/tests/move_unit_tests.rs, crates/aptos/src/move_tool/mod.rs, third_party/move/extensions/move-table-extension/tests/move_unit_tests.rs, third_party/move/move-stdlib/tests/move_unit_test.rs, third_party/move/tools/move-cli/src/base/test.rs, third_party/move/tools/move-cli/src/lib.rs, third_party/move/tools/move-cli/src/main.rs, third_party/move/tools/move-unit-test/src/cargo_runner.rs, third_party/move/tools/move-unit-test/src/lib.rs, third_party/move/tools/move-unit-test/src/main.rs, third_party/move/tools/move-unit-test/src/test_runner.rs, third_party/move/tools/move-unit-test/tests/move_unit_test_testsuite.rs, types/src/on_chain_config/aptos_features.rs
Make move unit tests have ability to initialize with genesis state. 
Use that state to pass Feature flags
Let me know if any changes in third-party are problematic, and we can either try to minimize, or copy some of the testing code to our repo directly. All changes there are fully generic, and don't make any Aptos-specific assumptions.
all move unit tests.
=> Move unit tests should use default Feature flags

ecosystem/nft-metadata-crawler-parser/src/config.rs
Addressing this error
Code copied from processors repo
Locally
=> [NFT Metadata Crawler] Remove null bytes

Cargo.lock, config/src/config/identity_config.rs, consensus/src/consensus_provider.rs, consensus/src/epoch_manager.rs, consensus/src/pipeline/errors.rs, consensus/src/pipeline/execution_client.rs, consensus/src/test_utils/mock_execution_client.rs, consensus/src/twins/twins_node.rs, dkg/Cargo.toml, dkg/src/agg_trx_producer.rs, dkg/src/counters.rs, dkg/src/dkg_manager/mod.rs, dkg/src/dkg_manager/tests.rs, dkg/src/epoch_manager.rs, dkg/src/lib.rs, dkg/src/transcript_aggregation/mod.rs, dkg/src/transcript_aggregation/tests.rs, dkg/src/types.rs
=> randomness #6: dkg manager update from randomnet

aptos-move/framework/aptos-framework/doc/genesis.md, aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/vm-genesis/src/lib.rs
- call `jwks::initialize` from rust (instead of in Move).
- stop using an initial OIDC provider list so we don't DDOS (current list is invalid anyway)
=> update jwk initialization in genesis

third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs, third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs, third_party/move/move-compiler-v2/tests/ability-transform/copy_ability_tuple.exp, third_party/move/move-compiler-v2/tests/ability-transform/copy_ability_tuple.move, third_party/move/move-compiler-v2/tests/copy-propagation/dead_assignment_2.exp
This PR closes #12255 by adding a check for whether a variable is alive after a given program point, consider that this variable may be just introduced at this point. So a variable is alive if (a) it is in the after set of livevar (b) it is not in the instrs.dests() of the current instructions.
1) existing tests pass
2) add a test `copy_ability_tuple.move`
=> [Compiler-v2] Fix issue 12255

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml
Integrating https://github.com/aptos-labs/aptos-indexer-processors/pull/290.
Internal context: https://aptos-org.slack.com/archives/C03N83P7QUC/p1709258737987549.
```
```
```
pnpm test:indexer
```
=> [CLI] Upgrade processor dep to d44b2d209f57872ac593299c34751a5531b51352

config/src/config/state_sync_config.rs
This PR updates the configs for state sync so that node's will use fast syncing by default in previewnet.
=> [State Sync] Use fast sync by default.

keyless/pepper/service/src/jwk.rs
=> use async sleep in pepper

crates/channel/src/aptos_channel.rs, testsuite/forge-cli/src/main.rs
The consensus queues are recreated per epoch. Without resetting the counters, the metrics show as increasing number of "stuck" messages, which are simply messages that were in the queue during the epoch change (and hence were not dequeued or dropped).
=> [preview] [aptos channel] always reset counters on new channel

aptos-move/framework/aptos-framework/doc/dkg.md, aptos-move/framework/aptos-framework/sources/dkg.move, aptos-move/vm-genesis/src/lib.rs, consensus/src/dag/dag_fetcher.rs, consensus/src/epoch_manager.rs, consensus/src/rand/rand_gen/rand_manager.rs, consensus/src/rand/rand_gen/rand_store.rs, consensus/src/rand/rand_gen/types.rs, dkg/src/dkg_manager/mod.rs, dkg/src/dkg_manager/tests.rs, dkg/src/transcript_aggregation/tests.rs, testsuite/smoke-test/src/randomness/failure_indicator_block_dkg.rs, testsuite/smoke-test/src/randomness/failure_indicator_block_randomness.rs, testsuite/smoke-test/src/randomness/mod.rs, types/src/dkg/dummy_dkg/tests.rs, types/src/dkg/mod.rs
=> on-chain resources to indicate dkg/randomness failure injection

aptos-move/aptos-vm/src/aptos_vm.rs, types/src/proptest_types.rs, types/src/transaction/mod.rs
Remove the detail error info from transaction status which is the upstream from the execution status used in transaction info. 
To rollout the feature,
1. test turning on the feature in testnet once 1.11 upgrade finishes.
2. aim to turn the feature on in 1.12 branch once we see all the validators are on the version >= 1.11
TODO:
add transaction auxiliary data backup and restore. 
replay verify https://github.com/aptos-labs/aptos-core/actions/runs/8103822653
=> [storage] [2/3] remove error detail from txn info

scripts/git-checks.sh
In git-checks.sh, exclude whitespace checks for .exp files, which are program-generated and can have any syntax.
Tested locally with various previous commits involving extra whitespaces.  Verified that .exp files are excluded, but others are not.
#12356
=> exclude .exp files from whitespace checks in scripts/git-checks.sh

aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/sources/create_signer.move, aptos-move/framework/aptos-framework/sources/fungible_asset.move
@igor-aptos @georgemitenkov @lightmark 
#11183 enables voluntary upgrading of a fungible asset store to use a concurrent balance, via `fungible_asset::upgrade_store_to_concurrent`. However, `fungible_asset::upgrade_store_to_concurrent` requires an `ExtendRef` and thus cannot be used in the general case, because `fungible_asset::create_store` does not by default store an `ExtendRef` anywhere (https://github.com/aptos-labs/aptos-core/pull/11183#discussion_r1510032495).
Importantly, the `primary_fungible_store` module has no way of provisioning an `ExtendRef`, which means that the current iteration of #11183 blocks all of a user's existing primary fungible asset stores (essentially all assets held in their wallet) from upgrading to concurrent balances when the features roll out on mainnet: …
=> [Framework] Add on-the-fly fungible store concurrency upgrade to general case

Cargo.lock, consensus/consensus-types/Cargo.toml, consensus/consensus-types/src/common.rs
Follow-up to #11830 . These need to be filtered, to avoid pulling repeatedly.
=> [quorum store] filter also txn limited batches

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml, crates/aptos/src/lib.rs, crates/aptos/src/move_tool/bytecode.rs, crates/aptos/src/update/aptos.rs, crates/aptos/src/update/helpers.rs, crates/aptos/src/update/mod.rs, crates/aptos/src/update/revela.rs, crates/aptos/src/update/tool.rs
We are adding support for decompilation to the CLI: https://github.com/aptos-labs/aptos-core/pull/12354. The decompilation requires a separate binary called Revela to operate. We decided that it would be simplest if the CLI itself supported installing the binary it needs, rather than baking this into our release process. This PR evolves the `aptos update` command to support Revela.
As you can see in the test plan, because we instal Revela to a predictable, specific location, the decompile tool can run immediately after we download Revela without having to set the PATH or reload the shell configuration or anything.
The correctness of this behavior relies on:
- The folks who built Revela use a consistent tagging scheme (e.g. like they do now, `v1.0.0`).
- The Revela folks ensuring that …
=> [CLI] Add support for self-downloading Revela

Cargo.lock, consensus/consensus-types/Cargo.toml, consensus/consensus-types/src/common.rs
Follow-up to #11830 . These need to be filtered, to avoid pulling repeatedly.
=> [cherry-pick] [quorum store] filter also txn limited batches (#12369)

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/cluster.rs, ecosystem/node-checker/src/checker/tps.rs
If the `--chain-id` is not provided to the transaction-emitter, attempt to derive it from the given targets. This helps in some cases where the chain_id of the chain under test changes, and we do not want to change the transaction-emitter setup.
Unit tests, and running transaction-emitter without specifying the chain_id
=> [txn-emitter] derive chain_id if not provided

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/sources/multisig_account.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, types/src/on_chain_config/aptos_features.rs
- introduced and enforced `MAX_PENDING_TRANSACTIONS`
- added entry functions for batch voting
- added entry functions for batch executing rejected transactions
This PR resolves https://github.com/aptos-labs/aptos-core/issues/8411.
=> [multisig v2] Enhanced multisig v2 with batch operations and the max pending txn limit

aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/scheduler.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/block-executor/src/view.rs
- allow halting Executing status when waking up a dependency
- add panic/fallback error handling to scheduler invariants
- new unit tests for halting, errors
=> [Block Executor] Halt executing, utilize PanicError, clean-up

aptos-move/aptos-vm-types/src/abstract_write_op.rs, aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/tests/test_change_set.rs, aptos-move/aptos-vm/src/move_vm_ext/session/respawned_session.rs, aptos-move/aptos-vm/src/move_vm_ext/session/view_with_change_set.rs, aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
Respowned session had two issues:
- incorrect view was being passed (one without resource group handling for split flag)
- size was set to 0, which breaks code afterwards
e2e tests didn't catch this, because epilogue is always the same - no matter what user transaction executes.
Unit test provided by Aaron.
=> Fix RG handling in respawned session

crates/aptos/src/update/revela.rs
Fast follow from #12362.
```
cargo build -p aptos
```
```
~/a/core/target/debug/aptos update revela
```
```
Checking target-arch... aarch64-apple-darwin
Checking current version... v1.0.0-rc3
Looking for tag: v1.0.0
revela release status:
* New exe release: "revela-aarch64-apple-darwin"
* New exe download url: "https://api.github.com/repos/verichains/revela/releases/assets/155171154"
* Installing to: /Users/dport/.local/bin
The new release will be downloaded/extracted and the existing binary will be replaced.
Do you want to continue? [Y/n] y
Downloading...
Extracting archive... Moving binary file to /Users/dport/.local/bin... Done
{
"Result": "Successfully updated Revela from v1.0.0-rc3 to v1.0.0"
}
```
=> Update target Revela version to 1.0.0

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml, crates/aptos/src/update/revela.rs
If the user doesn't already have the default install directory, it would previously fail. Now we make the directory. This is how the Python install script does it.
First delete the default install dir, e.g. for linux `~/.local/bin`.
Before:
```
$ cargo run -p aptos -- update revela
{
"Error": "Unexpected error: Failed to build self-update configuration: ConfigError: `bin_install_dir` must be a directory"
}
```
After:
```
Checking target-arch... aarch64-apple-darwin
Checking current version... v0.0.0
Looking for tag: v1.0.0
revela release status:
* New exe release: "revela-aarch64-apple-darwin"
* New exe download url: "https://api.github.com/repos/verichains/revela/releases/assets/155171154"
* Installing to: /Users/dport/.local/bin
The new release will be downloaded/extracted and the …
```
=> Make install dir if not present in aptos update revela

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
Forgot to bump the feature versions for these parameters when we decided to make dependency gas version 15. This get them fixed.
=> [easy][gas] fix gas feature version for parameters (main)

docker/builder/docker-bake-rust-all.hcl
Docker builds are now running with local cacheing, so pushing cache images to GAR is no longer useful.
=> Remove Docker layer cacheing

aptos-move/aptos-vm-types/src/abstract_write_op.rs, aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/tests/test_change_set.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
Respowned session had two issues:
- incorrect view was being passed (one without resource group handling for split flag)
- size was set to 0, which breaks code afterwards
e2e tests didn't catch this, because epilogue is always the same - no matter what user transaction executes.
Unit test provided by Aaron.
=> [CP to 1.10] Fix RG handling in respawned session (#12372)

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
Forgot to bump the feature versions for these parameters when we decided to make dependency gas version 15. This get them fixed.
=> [easy][gas] fix gas feature version for parameters (1.10)

third_party/move/move-compiler-v2/src/pipeline/ability_processor.rs, third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs, third_party/move/move-compiler-v2/tests/ability-check/explicit_move.move, third_party/move/move-compiler-v2/tests/ability-check/inferred_copy.move, third_party/move/move-compiler-v2/tests/ability-check/unused_para_no_drop.exp, third_party/move/move-compiler-v2/tests/ability-check/unused_para_no_drop.move, third_party/move/move-compiler-v2/tests/ability-transform/mutate_return.exp, third_party/move/move-compiler-v2/tests/live-var/mut_ref.exp, third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/access_control/dynamic.exp
This PR closes #12309 by adding a check to the ability processor that if 1) an unused parameter is of generic type or a struct or a vector of struct; 2) the struct/generic type has no drop ability and 3) the function does not always abort, an error will be generated.
Added a new test `unused_para_no_drop` to validate the fix
=> [Compiler-v2] Fix issue 12309

.github/workflows/aptos-node-release.yaml, .github/workflows/docker-update-images.yaml
Update `create-pull-request` action due to a breaking change in the Github API: https://github.com/peter-evans/create-pull-request/releases/tag/v6.0.1
See the patch notes
=> [gha] update broken create-pull-request action

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-emitter-lib/src/wrappers.rs, crates/transaction-generator-lib/src/call_custom_modules.rs, crates/transaction-generator-lib/src/entry_points.rs, crates/transaction-generator-lib/src/lib.rs, crates/transaction-generator-lib/src/workflow_delegator.rs, execution/executor-benchmark/src/lib.rs, testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs, testsuite/smoke-test/src/txn_emitter.rs
Make computation of needed funds more precise:
- accounting for min balance needed
- accounting for difference between actual loadtest traffic and minting
- check if accounts exist, and then use transfer gas costs, otherwise account creation gas costs for minting
- init_max_gas_per_txn now refers to non-account creation initialization - i.e. module publishing. I.e. if we need to publish one module, we don't need to require larger balances and gas consumption for the whole acount minting stage
- make all consumption from root (i.e. module publishing) require approval - so that we don't consume unexpected amounts
- make more things optional and have sane defaults. init multiplier is 2x (enough to get to second bucket), transfer/creating gas needed is provided, expected-gas-per-txn defaults …
=> improved txn emitter fund accounting

docker/release-images.mjs, testsuite/forge.py
Replace references to the old `aptos-internal` repository with the multi-region repo.
See if the Forge tests run correctly.
=> Switch to multi-region Docker repository

third_party/move/move-core/types/src/vm_status.rs
As far as I understand, INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE is thrown when accounts balance is not enough for the max_gas specified in the transaction. but current description is not conveying that, so trying to clarify it.
Is https://aptos.dev/reference/error-codes/ showing directly what is written here, or is there a separate change needed for that?
=> Fix INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE description

third_party/move/move-compiler-v2/src/bytecode_generator.rs, third_party/move/move-compiler-v2/tests/file-format-generator/pack_unpack_ref.exp, third_party/move/move-compiler-v2/tests/file-format-generator/pack_unpack_ref.move, third_party/move/move-compiler-v2/transactional-tests/tests/misc/pack_unpack_ref.exp, third_party/move/move-compiler-v2/transactional-tests/tests/misc/pack_unpack_ref.move
This PR closes #12198 by generating the borrow_field instruction for each field when unpacking a reference to a struct.
Added one unit test and one transactional test to validate the fix.
=> [Compiler-v2] Fix issue 12198

aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/sources/multisig_account.move
To simplify the Multisig v2 transaction execution workflow and minimize the required number of transactions, this implemented implicit voting as follows:
* Count it as an implicit approval upon transaction execution
* Count it as an implicit rejection upon "rejection execution"
This resolves https://github.com/aptos-labs/aptos-core/issues/11011.
=> [Multisig V2] Implemented the implicit voting for multisig transaction execution and rejection

Cargo.toml
Change the debuginfo settings to `line-tables-only`. This should reduce the size of our build artifacts and binaries without breaking backtraces.
After building all packages to run unit tests, the size of the `target` directory went from 255GB -> 188GB.
I also tested builing a nextest archive for running unit tests
`cargo nextest archive --cargo-profile ci --locked --workspace --exclude aptos-testcases --exclude smoke-test --archive-file nextest-archive.tar.zst`. With this change the archive file went from 39GB -> 11GB
- CI
- Add a test that panics and check that backtraces still contain function names and line numbers
```
alanluong@ubuntu:/Users/alanluong/vm/aptos-core$ RUST_BACKTRACE=full cargo test -p aptos-node --profile ci
warning: unused imports: `DKGTranscriptMetadata`, …
```
=> set debug to line-tables-only

aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/scheduler.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/block-executor/src/view.rs
A follow-up for recent changes to clean up some things in the scheduler and executor.
=> [Block Executor] Follow up fix-ups

crates/aptos/CHANGELOG.md, crates/aptos/src/node/local_testnet/postgres.rs, crates/aptos/src/node/local_testnet/processors.rs
The local testnet sometimes fails to start because the number of connections is greater than the max the DB allows. This PR configures the postgres container to have a higher max connections count.
While here I upgrade the minor version of postgres.
```
```
The local testnet comes up happily.
See also:
```
postgres=> SHOW max_connections;
250
```
I ran the TS SDK v2 tests and they all passed.
N/A
=> [CLI] Increase max_connections for postgres in local testnet

aptos-move/aptos-release-builder/src/components/feature_flags.rs, types/src/on_chain_config/aptos_features.rs
Fix the feature flag for the multisig v2 enhancement (`MULTISIG_V2_ENHANCEMENT`)
`TransactionContextExtension` is the next feature to come. It didn't land yet.
=> [Multisig V2] Fix the feature flag for MULTISIG_V2_ENHANCEMENT

terraform/fullnode/aws/kubernetes.tf, terraform/fullnode/aws/variables.tf, terraform/helm/genesis/templates/genesis.yaml, terraform/helm/genesis/values.yaml, terraform/modules/resources/instance.tf
Sync Terraform & Helm changes
* set default disk size for the `fullnode` chart to 2.5TBi
* add a toggle to the `genesis` chart to disable running automatically (thus avoiding to potentially overwrite an already existing genesis)
* Add `c2-standard-60` to the list of approved instance types
=> Sync Terraform & Helm

ecosystem/python/sdk/CHANGELOG.md, ecosystem/python/sdk/aptos_sdk/async_client.py, ecosystem/python/sdk/aptos_sdk/type_tag.py, ecosystem/python/sdk/examples/common.py, ecosystem/python/sdk/examples/your_coin.py, ecosystem/python/sdk/pyproject.toml
* Add submit and wait
* Improve table data retrieval code (aesthetics)
* Add support for view functions via bcs
* Demo transfer of non apt
Some example code that verified it.
None
=> [python] updates to sdk

consensus/src/state_computer.rs, consensus/src/state_computer_tests.rs, consensus/src/txn_notifier.rs
In testing we saw:
Failed to notify mempool of rejected txnsMempoolError { inner: Expected compute_status length and actual compute_status length mismatch! user_txns len: 1, expected compute_status len: 2, compute_status len: 3, has_reconfiguration: false }
appearing because vtxns have changed size of the prefix before user transactions.
txn notifier doesn't need full result, only statuses of user transactions, so simplifying the API. that also removes one clone.
test via smoke test
=> Fix txn notifier failure due to vtxns

consensus/src/quorum_store/batch_generator.rs
We were not constraining on the sender side, even though we check on the receiver side. It's an oversight. We hadn't run into this previously because the backpressure configs meant we never tried to pull more than the sender/receiver side limit.
Existing tests
=> [quorum store] constrain txn pull size to sender_max_total_txns

CODEOWNERS, Cargo.lock, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/keyless_validation.rs, aptos-move/e2e-move-tests/src/tests/keyless_feature_gating.rs, crates/aptos-crypto/src/secp256r1_ecdsa/secp256r1_ecdsa_sigs.rs, testsuite/generate-format/tests/staged/api.yaml, testsuite/generate-format/tests/staged/aptos.yaml, testsuite/generate-format/tests/staged/consensus.yaml, types/src/keyless/mod.rs, types/src/on_chain_config/aptos_features.rs, types/src/transaction/authenticator.rs
Two changes:
1. **Fixing feature gating:** We did not allow for the ZKless mode to be enabled while the ZK mode is disabled. This is now fixed.
2. **Match the JWK's `alg` field with the JWT header's `alg` field**: For completeness, this should be done.
3. **Fix an oversight in our `EphemeralPublicKey` deserialization override**
Decided **not** to implement extra size limits of keyless public keys and signatures, since the TXN size limits suffice. The code would have been ugly & confusing, since there are size limits dispersed in too many places.
-  For the ZK path:
+ `KeylessPublicKey` will not be fixed-size because the IDC field is `Vec<u8>`
+ `KeylessSignature::ZeroKnowledgeSig` has all of its fields constant-sized or size-checked (e.g., the max size of the `String` fields is checked …
=> [keyless] update feature gating & match alg field

api/doc/spec.json, api/doc/spec.yaml, api/test-context/src/test_context.rs, api/types/src/transaction.rs, ecosystem/typescript/sdk/src/generated/index.ts, ecosystem/typescript/sdk/src/generated/models/MultisigTransactionPayload.ts, ecosystem/typescript/sdk/src/generated/models/MultisigTransactionPayload_EntryFunctionPayload.ts
- Currently, simulating Multisig payloads fails with the following error message:
```
{
"Error": "API error: Unknown error error decoding response body: invalid value: map, expected map with a single key at line 1 column 5701"
}
```
- This is caused by the incorrect serialization of the `MultisigTransactionPayload` type.
- For the correct (de)serialization, this PR adds the serde attribute (tag = "type") to the enum type `MultisigTransactionPayload`
This PR resolves https://github.com/aptos-labs/aptos-core/issues/12469,
and partially for https://github.com/aptos-labs/aptos-core/issues/8304.
tested on the localnet
=> [Multisig V2][API] Fix the API error for Multisig V2

third_party/move/move-compiler-v2/src/lib.rs, third_party/move/move-compiler-v2/tests/no-simplifier/constant_folding_ristretto.exp, third_party/move/move-compiler-v2/tests/no-simplifier/constant_folding_ristretto.move, third_party/move/move-compiler-v2/tests/simplifier/constant_folding_ristretto.exp, third_party/move/move-compiler-v2/tests/simplifier/constant_folding_ristretto.move, third_party/move/move-compiler-v2/tests/testsuite.rs, third_party/move/move-compiler-v2/transactional-tests/tests/simplifier/constant_folding_ristretto.exp, third_party/move/move-compiler-v2/transactional-tests/tests/simplifier/constant_folding_ristretto.move, third_party/move/move-compiler/transactional-tests/tests/simplifier/constant_folding_ristretto.exp, third_party/move/move-compiler/transactional-tests/tests/simplifier/constant_folding_ristretto.move, third_party/move/move-model/src/ast.rs, third_party/move/move-model/src/constant_folder.rs, third_party/move/move-model/src/symbol.rs
Fixes issue #12516 by using ast::Value equivalence
(newly exposed through function `Value::equivalent()`),
rather than struct
equality, when constant-folding equality operations.
(`Value::ByteArray(..)` and `Value::AddressArray(..)` values can
each also be represented by `Value::Vector(..)` instead).
This fixes a failure that shows up in `0x1::ristretto:255`
test case `test_scalar_from_canonical_bytes`.
Fixes #12516.
V2 compiler
Included thorough unit test for new function `Value::equivalent`,
and a targeted test case `constant_folding_ristretto.move` for
comparison with V1 and V2 without simplification.
Existing V2 CI tests should show the original problem is fixed.
Consider redundancy and ambiguity of the AST representation, perhaps there are more cases.
=> use ast::Value equivalence, not enum equality, to do constant folding of constants

aptos-move/aptos-e2e-comparison-testing/src/execution.rs, aptos-move/aptos-vm/src/aptos_vm.rs
Reduce the unnecessary transaction metadata instantiation
This PR resolves https://github.com/aptos-labs/aptos-core/issues/12546
=> [Aptos VM] Reduce some unnecessary transaction metadata instantiation

config/src/config/consensus_config.rs, consensus/src/epoch_manager.rs, consensus/src/round_manager.rs, consensus/src/round_manager_fuzzing.rs, consensus/src/round_manager_test.rs
Move the broadcast vote flag to consensus local config.
=> [consensus] move flag to local config

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml
This fixes an issue reported by @gregnazario where `aptos update revela` doesn't work if `/tmp` is on a different filesystem.
The relevant function in the self_update crate is here: https://github.com/banool/self_update/blob/8306158ad0fd5b9d4766a3c6bf967e7ef0ea5c4b/src/update.rs#L345.
See also https://stackoverflow.com/q/78175299/3846032.
Before:
```
Checking target-arch... aarch64-apple-darwin
Checking current version... v0.0.0
Looking for tag: v1.0.0
revela release status:
* New exe release: "revela-aarch64-apple-darwin"
* New exe download url: "https://api.github.com/repos/verichains/revela/releases/assets/155171154"
* Installing to: /Volumes/storage
The new release will be downloaded/extracted and the existing binary will be replaced.
Do you want to continue? [Y/n] y
Downloading... …
```
=> [CLI] Use updated self_update that supports cross-fs renames

testsuite/forge/src/backend/k8s/fullnode.rs
Fix an issue where Forge PFNs weren't able to start up because of a missing genesis.blob. There were some changes I made to the Volumes and VolumeMounts in #12524 that are also needed for PFNs
Ran Forge for `pfn_const_tps_with_realistic_env`
https://github.com/aptos-labs/aptos-core/actions/runs/8332018633/job/22802583531
=> add writable volume for the genesis.blob for Forge PFNs

crates/aptos-rosetta/src/types/objects.rs
=> fix vtxn todo in rosetta

consensus/src/quorum_store/batch_generator.rs
We were not constraining on the sender side, even though we check on the receiver side. It's an oversight. We hadn't run into this previously because the backpressure configs meant we never tried to pull more than the sender/receiver side limit.
=> [cp 1.10][quorum store] constrain txn pull size to sender_max_total_txns (#12532)

.github/workflows/test-copy-images-to-dockerhub.yaml, Cargo.lock, aptos-node/Cargo.toml, docker/__tests__/release-images.test.js, docker/release-images.mjs, docker/test.sh, package.json, pnpm-lock.yaml
We currently dont check that the tag and the aptos-node cargo.toml version match
This ensures that before publish we have to check the tag and version match only for release images
Test Plan: wrote unittests and added a testing workflow
made the script possibel to unittest
Also ran a workflow against a wrong tag https://github.com/aptos-labs/aptos-core/actions/runs/7619251294
When the job fails it will also include the error in the job summary using the github actions core summary api
And test with a positive test case
https://github.com/aptos-labs/aptos-core/actions/runs/7619506814/job/20752691898
I cancelled it but it would work (but i dont want to publish 0.0.1 :P)
=> [docker] Check that version matches tag before publishing release images

aptos-move/aptos-aggregator/src/types.rs, aptos-move/block-executor/src/counters.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/view.rs, aptos-move/mvhashmap/src/lib.rs, aptos-move/mvhashmap/src/unsync_map.rs, aptos-move/mvhashmap/src/versioned_data.rs, aptos-move/mvhashmap/src/versioned_delayed_fields.rs, aptos-move/mvhashmap/src/versioned_group_data.rs, aptos-move/mvhashmap/src/versioned_modules.rs, crates/aptos-metrics-core/src/avg_counter.rs, crates/aptos-metrics-core/src/lib.rs
run forge tests, and looked at the counters
=> Add a few counters for BlockSTM size

consensus/src/pipeline/buffer_manager.rs
=> [cherrypick] avoid getting BlockNotFound error on epoch boundary

consensus/src/round_manager.rs
If the node has too many buffered proposals, and its current round is not consecutive from the first one, it needs to fetch the gaps. However those blocks may already be garbage collected and it needs to waste the rpc time to discard it. If new blocks are created faster than the speed it discards stale proposals, the node can be stuck in an infinite loop until next epoch.
=> [consensus] bail buffered out of date proposals faster

third_party/move/move-compiler-v2/src/bytecode_generator.rs, third_party/move/move-compiler-v2/tests/checking/typing/assign_unpack_references.exp, third_party/move/move-compiler-v2/tests/checking/typing/bind_unpack_references.exp, third_party/move/move-compiler-v2/tests/checking/typing/decl_unpack_references.exp, third_party/move/move-compiler-v2/tests/simplifier-elimination/assign_unpack_references.exp, third_party/move/move-compiler-v2/transactional-tests/tests/misc/assign_unpack_references.exp, third_party/move/move-compiler-v2/transactional-tests/tests/misc/assign_unpack_references.move, third_party/move/move-model/src/builder/exp_builder.rs
This PR fixes the bug revealed in the test case`/simplifier-elimination/assign_unpack_references.move` by 1) changing the type of nodeId generated for the Unpack operation; 2) fixing a bug in the bytecode_generator to recursively handle struct pattern when the unpack target is reference.
The fix can be validated by the output change in existing tests. Also added a transactional test `assign_unpack_references`.
=> [Compiler-v2] Fix bug in assign_unpack_references

api/doc/spec.json, api/doc/spec.yaml, api/goldens/aptos_api__tests__transactions_test__test_wait_pending_transaction_by_hash.json, api/goldens/aptos_api__tests__transactions_test__test_wait_transaction_by_hash_not_found.json, api/goldens/aptos_api__tests__transactions_test__test_wait_transaction_by_invalid_hash.json, api/src/context.rs, api/src/metrics.rs, api/src/tests/transactions_test.rs, api/src/transactions.rs, config/src/config/api_config.rs
The motivation is to reduce e2e latencies by learning of committed responses immediately. Currently, it is up to the client to poll /transactions/by_hash and there is overhead on the poll intervals and the RTT of the poll.
There is concern around holding large numbers of connections for an extended time -- to alleviate this we put a limit on active long polls, and simply return immediately when that limit is reached. The API does not give guarantees about how long the long poll will wait.
Added unit tests. Deployed locally and in previewnet and tested long poll behavior.
=> [api] add a long poll API /transactions/wait_by_hash/:txn_hash

third_party/move/move-compiler-v2/tests/testsuite.rs
`check_and_rewrite_pipeline` already adds `cyclic_instantiation_checker::check_cyclic_instantiations` to the env pipeline, so no need to add it again.
=> [compiler-v2] Removing duplicate call to cyclic instantiation checker in tests

aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/scheduler.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/block-executor/src/view.rs
straight up cherry pick of the following PRs from main:
https://github.com/aptos-labs/aptos-core/pull/12230
https://github.com/aptos-labs/aptos-core/pull/12468
=> [cherry-pick v1.10] BlockSTM error propagation and handling

third_party/move/move-core/types/src/vm_status.rs
=> update TOO_MANY_DELAYED_FIELDS error code

crates/aptos/CHANGELOG.md, crates/aptos/src/common/types.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/test/mod.rs
It was erroneously renamed to --value
```
cargo build -p aptos;
./target/debug/aptos move publish --override-size-check
```
=> [cli] Fix override size check flag

CODEOWNERS, Cargo.lock, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/keyless_validation.rs, aptos-move/e2e-move-tests/src/tests/keyless_feature_gating.rs, aptos-move/vm-genesis/src/lib.rs, crates/aptos-crypto/src/secp256r1_ecdsa/secp256r1_ecdsa_sigs.rs, testsuite/generate-format/tests/staged/api.yaml, testsuite/generate-format/tests/staged/aptos.yaml, testsuite/generate-format/tests/staged/consensus.yaml, types/src/keyless/bn254_circom.rs, types/src/keyless/mod.rs, types/src/keyless/openid_sig.rs, types/src/on_chain_config/aptos_features.rs, types/src/transaction/authenticator.rs
This PR cherry picks two changes:
1. https://github.com/aptos-labs/aptos-core/pull/12476 (except for the devnet-only Google OIDC provider; Google is set as the default provider for *all* networks during genesis in v1.10)
2. https://github.com/aptos-labs/aptos-core/pull/12521
See original PRs.
See original PRs.
=> cherry pick keyless into v1.10.1

aptos-move/aptos-aggregator/src/types.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/block-executor/src/counters.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-move-tests/src/aggregator_v2.rs, aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs, aptos-move/framework/src/natives/event.rs, aptos-move/framework/table-natives/src/lib.rs, aptos-move/mvhashmap/src/lib.rs, aptos-move/mvhashmap/src/unsync_map.rs, aptos-move/mvhashmap/src/versioned_data.rs, aptos-move/mvhashmap/src/versioned_delayed_fields.rs, aptos-move/mvhashmap/src/versioned_group_data.rs, aptos-move/mvhashmap/src/versioned_modules.rs, crates/aptos-metrics-core/src/avg_counter.rs, crates/aptos-metrics-core/src/lib.rs, third_party/move/move-core/types/src/vm_status.rs, third_party/move/move-vm/types/src/value_serde.rs
Combined three memory related changes into this cherry-pick : #12580, #12583, #12581
=> [cp 1.10] Memory improvements/limits for DelayedFields (#12580, #12583, #12581)

api/types/src/address.rs, aptos-move/aptos-gas-schedule/src/ver.rs, aptos-move/aptos-vm-types/src/output.rs, aptos-move/e2e-tests/src/loader/mod.rs, aptos-move/framework/src/natives/cryptography/ristretto255.rs, consensus/src/consensusdb/schema/dag/mod.rs, crates/aptos-crypto/src/traits.rs, crates/aptos-dkg/src/algebra/lagrange.rs, crates/aptos-dkg/src/utils/mod.rs, crates/aptos-ledger/src/lib.rs, crates/aptos/src/common/types.rs, crates/channel/src/lib.rs, execution/block-partitioner/src/pre_partition/connected_component/mod.rs, execution/block-partitioner/src/pre_partition/uniform_partitioner/mod.rs, network/benchmark/src/lib.rs, storage/storage-interface/src/errors.rs, storage/storage-interface/src/lib.rs, third_party/move/move-compiler-v2/src/experiments.rs, third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs, third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs, third_party/move/move-core/types/src/account_address.rs, third_party/move/move-core/types/src/identifier.rs, third_party/move/move-model/bytecode/abstract_domain_derive/src/lib.rs, types/src/keyless/groth16_sig.rs, types/src/keyless/mod.rs, types/src/keyless/openid_sig.rs
Cleans up rust doc warnings, so doc build is clean.
However, there's a ton of unused warnings in different parts of the codebase as well.
Documentation only change
Documentation only change
=> [doc] Fix documentation warnings for rustdoc

consensus/src/quorum_store/batch_coordinator.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/quorum_store_builder.rs, consensus/src/quorum_store/tests/proof_manager_test.rs, consensus/src/quorum_store/tests/utils.rs, consensus/src/quorum_store/utils.rs
I've reset changes related to proof manager and batch coordinator from https://github.com/aptos-labs/aptos-core/pull/12579. This is to reduce the number of changes we make in v1.10.1 release.
=> Reset proof manager and batch coordinator without inline payload changes

Cargo.lock, Cargo.toml, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml, crates/aptos/src/node/local_testnet/processors.rs
This update required more than just bumping the rev, a few things changed:
- To ensure we don't onboard the libpq dep, we set `default-features = false`. See more here: https://github.com/aptos-labs/aptos-indexer-processors/pull/325.
- In the new version of the library `run_pending_migrations` takes in a generic DB object. To support this, `run_migrations` was updated to use `AsyncConnectionWrapper` since async connection itself doesn't impl the relevant traits. This required some changes to how we run migrations on our side.
- There is a new processor, TransactionMetadataProcessor. We add support for it here and enable it by default.
- Some processors (those with lookups) now take additional configuration.
- Some deps were updated in aptos-indexer-processors, we make necessary updates in …
=> [CLI] Update processor dependency

aptos-move/move-examples/move-tutorial/README.md
These docs are linked to from aptos.dev (Specifically from https://aptos.dev/move/move-on-aptos clicking the 3rd link called "The Move Tutorial"), but this tutorial contained many dead links because the docs moved out of this repo, but this tutorial still was using relative links.
This updates the page to point the documentation site, which should allow us to forward these links to the proper place even post-migrating the docs.
* Replaced all `../../../ ... /docs` with `https://aptos.dev/`
* Replaced any changed lines that now point to the docs website so they didn't have `.md` in the filepath.
I clicked all the links in preview mode, and they now work / go to the similar page they were referring to before.
Make sure to click all the links and verify they make sense.
=> Fix dead links for Aptos Move Tutorial

.github/actions/move-tests-compiler-v2/action.yaml
This PR brings back the test `test_smart_data_structures_gas` for testing the compiler V2.
=> [compiler-v2] Add test_smart_data_structures_gas back to test Compiler v2

aptos-move/e2e-move-tests/src/tests/stake.data/enable_rewards_rate_decrease/sources/main.move, aptos-move/e2e-move-tests/src/tests/transaction_fee.data/disable_collection/sources/main.move, aptos-move/e2e-move-tests/src/tests/transaction_fee.data/enable_collection/sources/main.move, aptos-move/e2e-move-tests/src/tests/transaction_fee.data/remove_validator/sources/main.move, aptos-move/e2e-move-tests/src/tests/transaction_fee.data/upgrade_burn_percentage/sources/main.move, aptos-move/e2e-move-tests/src/tests/vote.data/enable_partial_governance_voting/sources/main.move, testsuite/smoke-test/src/aptos_cli/validator.rs, testsuite/smoke-test/src/consensus/dag/dag_fault_tolerance.rs, testsuite/smoke-test/src/rosetta.rs, types/src/on_chain_config/randomness_config.rs
Enable randomness by default, but disable it for a few tests which may alter validator set, or expect immediate reconfigs.
=> enable randomness in genesis

network/builder/src/builder.rs
Simplify discovery setup.
Merge `if Let` into `match` that was happening anyway.
Move lines of code out of overfull `NetworkBuilder::create()`
_(things found along the way to network2)_
Existing unit tests. Lint.
Code is more readable.
=> refactor discovery setup

Cargo.lock, config/src/config/state_sync_config.rs, network/framework/src/protocols/network/mod.rs, network/framework/src/protocols/rpc/error.rs, peer-monitoring-service/client/src/metrics.rs, state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/tests/advertise.rs, state-sync/aptos-data-client/src/tests/compression.rs, state-sync/aptos-data-client/src/tests/peers.rs, state-sync/aptos-data-client/src/tests/utils.rs, state-sync/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-driver/src/continuous_syncer.rs, state-sync/state-sync-driver/src/notification_handlers.rs, state-sync/storage-service/server/Cargo.toml, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/optimistic_fetch.rs, state-sync/storage-service/server/src/subscription.rs, state-sync/storage-service/server/src/tests/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/subscription.rs
This PR offers several small metrics and performance improvements to the networking and state sync code. It also cleans up the use of an `unbounded_executor` in the storage service (this is no longer needed now that we [bound](https://github.com/aptos-labs/aptos-core/blob/6a2fee68cce24e6bf0b8e64bf23dfb545df35bfb/crates/aptos-runtimes/src/lib.rs#L27) our tokio runtimes).
1. Small metrics and performance improvements to networking and state sync.
2. Remove `unbounded_executor` in the storage service.
3. Update the affected unit tests.
=> [State Sync] Small metrics and performance improvements.

config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/tests/advertise.rs, state-sync/data-streaming-service/src/data_stream.rs, state-sync/data-streaming-service/src/stream_engine.rs, state-sync/data-streaming-service/src/tests/client_requests.rs, state-sync/data-streaming-service/src/tests/data_stream.rs, state-sync/data-streaming-service/src/tests/missing_data.rs, state-sync/data-streaming-service/src/tests/mod.rs, state-sync/data-streaming-service/src/tests/stream_engine.rs
Note: (i) most of this PR is just updating/adding tests; and (ii) this PR is built on https://github.com/aptos-labs/aptos-core/pull/12481.
This PR adds a configurable maximum number of in-flight subscription requests to the data streaming service. This is required to bound the number of subscription requests that can be sent at any one time. The default is `9` (at ~3 blocks per second, this means we can prefetch ~3 seconds of data). Before this, the maximum was determined by the dynamic prefetching value, which is suboptimal in practice. A constant configurable number seems to perform more steadily.
1. Add the new maximum config value.
2. Add/update the unit tests.
=> [State Sync] Add max in-flight subscription requests

third_party/move/extensions/async/move-async-vm/tests/testsuite.rs, third_party/move/move-compiler-v2/tests/testsuite.rs, third_party/move/move-compiler-v2/transactional-tests/tests/tests.rs, third_party/move/move-model/bytecode/tests/testsuite.rs, third_party/move/move-model/tests/testsuite.rs, third_party/move/move-prover/bytecode-pipeline/tests/testsuite.rs, third_party/move/move-prover/move-abigen/tests/testsuite.rs, third_party/move/move-prover/move-docgen/tests/testsuite.rs, third_party/move/move-prover/tests/testsuite.rs
Fix #12657 by adding `$` to the end of regexps like `".*\.move"` trying to match test input files,
so that backup files such as `foo.move~` and `foo.move.bak`are not matched as well.
Run locally in messy environment with backup files.  Happy path will be tested in CI.
Not a lot of complexity here.
=> Fix regexp for test file iteration to skip backup files

third_party/move/move-compiler-v2/src/options.rs
Add a test case for `Options` to verify that the `RefCell` is cloned
correctly.  Since there is a lof of conflicting info on the web it
seemed worth double-checking.
This confirms that Issue #12655 was not a bug.  (Already closed).
Run locally.
Confirm that the test shows the map underlying the `experiment_cache`
is cloned when the `Options` object is cloned.
=> add a test to show that ref_cell is cloned correctly

aptos-move/aptos-vm/src/errors.rs
This commit fixes the incorrect category in converting a prologue error code for Multisig V2. As a result, the VM can return the correct `StatusCode` and generate the proper error message for the client.
When trying to execute a non-existing Multisig V2 transaction, the error message was/is as follows:
Before this fix
```
{
"Error": "API error: API error Error(VmError): Invalid transaction: Type: InvariantViolation Code: UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION"
}
```
After this fix
```
{
"Error": "API error: API error Error(VmError): Invalid transaction: Type: Validation Code: MULTISIG_TRANSACTION_NOT_FOUND"
}
```
This PR resolves https://github.com/aptos-labs/aptos-core/issues/12667.
=> [Multisig V2] Fix the incorrect category of a prologue error code

storage/scratchpad/src/sparse_merkle/mod.rs, storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
The whole BranchTracker / family lock thing was designed so that we can
get_oldest_ancestor() on any SMT to get to the "root smt".
No longer needed since https://github.com/aptos-labs/aptos-core/pull/10665 where we let FrozenSmt hold the smt at the latest
persisted version via `SmtAncestors.get_youngest()`, instead of the absolutely oldest
in mem version, which can result in memory bloating because of now we
have more than one threads that holds ancestor smts. (see https://github.com/aptos-labs/aptos-core/pull/10665 for
details)
Existing unit tests
This should be straightforward refactor. See that all change were relevant to removal of already `allow(dead_code)` code.
- [N/A] I have made corresponding changes to the documentation
=> [smt] remove BranchTracker

.pre-commit-config.yaml
This PR updates the pre-commit CI/CD checks to use the `aptos-labs` fork of `pre-commit-hooks`, here: https://github.com/aptos-labs/pre-commit-hooks. Until we can fully migrate away from using pre-commit checks, maintaining a fork seems safer 😄 
Manual verification and existing test infrastructure and CI/CD flows.
=> [Pre-commit] Fork pre-commit-hook dependency.

aptos-move/move-examples/README.md
These Move examples are referenced several times in the docs, but the README doesn't explain how to use them. The docs are also very sparse in describing *how* to actually use these examples (even though they show example input / output for running a specific command relating to the example). 
This PR adds the little bit of missing in-between context so users can know where to run the commands like `aptos move compile` to actually get them working as the docs say they will. 
Additionally this PR links out to the Aptos CLI docs as they're necessary to work with these examples, and it puts the intimidating warning at the end of the steps to avoid discouraging developers from even trying to use the examples. 
Inspection
- I moved the warning lower, but still in the primary section. 
- The …
=> Update Move examples README.md to explain usage

aptos-move/aptos-debugger/src/aptos_debugger.rs, aptos-move/aptos-debugger/src/bcs_txn_decoder.rs, aptos-move/aptos-debugger/src/execute_past_transactions.rs, aptos-move/aptos-debugger/src/execute_pending_block.rs, testsuite/smoke-test/src/aptos/mint_transfer.rs
When there are infrequent race conditions, it is useful to re-execute same block multiple times
=> add --repeat-execution-times to aptos-debugger move command

aptos-move/framework/aptos-framework/doc/gas_schedule.md, aptos-move/framework/aptos-framework/sources/configs/gas_schedule.move, aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
fix the gas update function in the new randomness framework: it's supposed to verify the gas version as the deprecated `gas_sechedule::set_gas_schedule()` does.
UT
=> check gas version in `gas_schedule::set_for_next_epoch`

aptos-move/aptos-release-builder/data/proposals/start_jwk_consensus_for_google.move
... so JWK consensus starts immediately. Otherwise we would need to wait for 2 hours (until the next epoch).
Manually tested on testnet.
=> tweak google jwk governance script for 1.10

.github/actions/file-change-determinator/action.yaml, .github/workflows/move-test-compiler-v2.yaml
This PR updates the move compiler v2 GHA jobs to only run on each PR when necessary. When a PR doesn't modify relevant code to trigger the job, the job "passes trivially" (skipping the compiler v2 tests).
Manual verification and existing test infrastructure. Here is a run where the tests were skipped: https://github.com/aptos-labs/aptos-core/actions/runs/8459568568
=> [CI/CD] Only run the move compiler v2 tests when neccessary.

crates/aptos/src/update/revela.rs
macos x86_64 will report an error when installing revela Self-updating is not supported on your OS (macos-x86_64 ) right now, please download the binary manually
=> [Cli-Update]: Fix  update revela err on macos x86_64

.github/workflows/lint-test.yaml, scripts/cargo_build_aptos_cached_packages.sh, scripts/rust_lint.sh
This PR removes the step to build the cached packages from `rust_lint.sh` and migrates it to a separate script, to be invoked separately. This has the benefit that it: (i) reduces the lint script time (the lint script is run much more frequently); and (ii) only invokes the cached package build when required (most folks don't need to run this alongside the linter).
=> [CI/CD] Split up rust lint and cached packages scripts.

.github/workflows/check-protos.yaml, .github/workflows/lint-test.yaml, .github/workflows/windows-build.yaml
This PR:
1. Delays the: (i) windows CLI GHA job; and (ii) the check protos job, to only run on each PR when an appropriate event occurs. This includes: (i) when auto-merge is enabled; or (ii) when the correct label is added to the PR. This should help reduce the number of unnecessary/redundant runs of the job on each PR.
2. Fixes a missing step in `rust-build-cached-packages`.
=> [CI/CD] Delay windows CLI and protos test until appropriate event.

Cargo.lock, aptos-move/aptos-gas-schedule-updator/src/lib.rs, aptos-move/aptos-gas-schedule-updator/tests/gen_tests.rs, aptos-move/aptos-release-builder/Cargo.toml, aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/mod.rs
This allows the gas feature version to be overridden when building a release, which is needed when you don't want to bump it on-chain.
=> [release-builder] allow gas feature version to be overridden

third_party/move/move-compiler-v2/tests/checking/inlining/test_12670.exp, third_party/move/move-compiler-v2/tests/checking/inlining/test_12670.move
This PR closes #12670 by adding a test for lambda parameter inference to v2.
Added a new test and validated the output
=> [Compiler-v2] Add a test case for issue 12670

aptos-move/aptos-aggregator/src/delta_change_set.rs, aptos-move/aptos-aggregator/src/resolver.rs, aptos-move/aptos-aggregator/src/tests/types.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/move_vm_ext/session/mod.rs, aptos-move/aptos-vm/src/move_vm_ext/session/view_with_change_set.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/block-executor/src/view.rs, aptos-move/framework/src/natives/aggregator_natives/context.rs
When execution is halted (i.e. due to module publish or other reasons), get_resource_state_value_metadata will return speculative error.
We shouldn't transform that into a code panic - as it is not.
This is alternative implementation to the #12676
error propagation
=> [delayed materialization] Fix propagating errors through

aptos-move/aptos-gas-meter/src/meter.rs, aptos-move/aptos-gas-meter/src/traits.rs, aptos-move/aptos-gas-profiling/src/aggregate.rs, aptos-move/aptos-gas-profiling/src/erased.rs, aptos-move/aptos-gas-profiling/src/flamegraph.rs, aptos-move/aptos-gas-profiling/src/log.rs, aptos-move/aptos-gas-profiling/src/profiler.rs, aptos-move/aptos-gas-profiling/src/render.rs, aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs, aptos-move/aptos-gas-schedule/src/ver.rs, aptos-move/aptos-memory-usage-tracker/src/lib.rs, aptos-move/aptos-vm-types/src/storage/io_pricing.rs, aptos-move/aptos-vm/src/aptos_vm.rs
We used not to charge io gas for writing the transaction itself and events at all. Although we do charge execution gas in proportion to the sizes of both of them (intrinsic gas for the transaction and in write_event_to_store native funciton), it feels proper to charge for the writes in charge_change_set -- might benefit calibration accuracy. 
Notice that we used to charge storage fee for those sizes and that was removed due to https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-65.md
Also note, new gas parameters introduced are set to 0 for now. This should be a no op.
- [] Move/Aptos Virtual Machine
planning to test in unit test with the gas profiler
probably need gas re-calibration
the numbers for the per txn byte and per event byte write gas.
=> ability to charge io gas for writing the transaction itself and emitted events

crates/channel/src/aptos_channel.rs
The consensus queues are recreated per epoch. Without resetting the counters, the "Round manager pending messages" show as increasing number of "stuck" messages, which are simply messages that were in the queue during the epoch change (and hence were not dequeued or dropped).
Deployed to previewnet and saw round manager pending messages are no longer stuck
=> [aptos channel] always reset counters on new channel

mempool/src/core_mempool/index.rs, mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs
The commit-minus-parked is to be used for alerts in place of regular commits. Previously a handful of txns that are held in parking lot can skew higher percentiles.
Run forge, create a dashboard.
=> [mempool] track commit-minus-parked time, as well as parked time

.config/nextest.toml
I had a recent unit test failure running for over 4 hours in GHA test. Set `nextest` to timeout after 10 minutes.
I have this in another branch and things pass within this timout. 30s and 90s were not enough (but we should push towards that and make slow tests faster)
Anyone know why `nextest` 'period' should be shorter but timeout after several of them? (instead of this config which is a long period and timeout after 1 of it)
=> set 10 minute timeout for nextest

third_party/move/move-compiler-v2/tests/checking/typing/assign_wrong_arity.exp, third_party/move/move-compiler-v2/tests/checking/typing/assign_wrong_type.exp, third_party/move/move-compiler-v2/tests/checking/typing/bind_wrong_arity.exp, third_party/move/move-compiler-v2/tests/checking/typing/bind_wrong_type.exp, third_party/move/move-compiler-v2/tests/checking/typing/declare_wrong_arity.exp, third_party/move/move-compiler-v2/tests/checking/typing/eq_invalid.exp, third_party/move/move-compiler-v2/tests/checking/typing/lambda.exp, third_party/move/move-compiler-v2/tests/checking/typing/loop_body_invalid.exp, third_party/move/move-compiler-v2/tests/checking/typing/loop_result_type_invalid.exp, third_party/move/move-compiler-v2/tests/checking/typing/neq_invalid.exp, third_party/move/move-compiler-v2/tests/checking/typing/pack_unit.exp, third_party/move/move-compiler-v2/tests/checking/typing/pack_unit.move, third_party/move/move-compiler-v2/tests/checking/typing/vector_with_non_base_type.exp, third_party/move/move-compiler-v2/tests/checking/typing/vector_with_non_base_type_inferred.exp, third_party/move/move-compiler-v2/tests/checking/typing/while_body_invalid.exp, third_party/move/move-compiler-v2/tests/v1.matched, third_party/move/move-compiler-v2/tests/v1.unmatched, third_party/move/move-model/src/ty.rs
This PR closes #12764 by treating unit as tuple in type constraints. 
Note that the error message in the test `third_party/move/move-compiler-v2/tests/checking/typing/lambda.move` and `third_party/move/move-compiler-v2/tests/checking/typing/while_body_invalid.exp` is less clearer after this fix, which should be fixed.
1) existing tests;
2) migrate the test `pack_unit` from V1
=> [Compiler-v2] Treat unit as tuple in type constraints

.github/actions/docker-setup/action.yaml, .github/workflows/cargo-metadata-upload.yaml, .github/workflows/copy-images-to-dockerhub.yaml, .github/workflows/docker-update-images.yaml, .github/workflows/workflow-run-forge.yaml, .github/workflows/workflow-run-replay-verify.yaml
Also upgrade actions/checkout to v4.
The previous versions of the actions use Nodejs 16, which is deprecated.
Check that workflows run successfully.
=> [GH] Update version of GCloud actions

aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/sources/collection.move
Add additional fields in `Collection` mutation events for indexing needs. Follow up from PR: https://github.com/aptos-labs/aptos-core/pull/12737
1. Changing the collection name
- Emit the collection object address, as well as the old and new values
2. Changing the collection max supply
- Emit the old max supply too
=> Add collection address, old and new values to collection mutation events

crates/aptos-logger/src/aptos_logger.rs
Change logger to always send json formatted logs to the telemetry service
`cargo test`
=> always send json formatted logs to the telemetry service

aptos-move/vm-genesis/src/lib.rs, aptos-node/src/lib.rs, crates/aptos-genesis/src/config.rs, crates/aptos/src/genesis/mod.rs, terraform/helm/genesis/templates/genesis.yaml, types/src/on_chain_config/jwk_consensus_config.rs
Add a `JWKConsensusConfigOverride` to `GenesisInfo`, to allow control JWK initialization in smoke tests/localnet.
n.a.
=> parameterize jwk consensus config in genesis

protos/buf.ts.gen.yaml, protos/scripts/install_deps.sh
This properly pins the tooling so the generated code doesn't drift unintentionally.
I ran the generator myself and nothing changed. CI will confirm.
=> Properly pin buf proto gen tools for TS

ecosystem/indexer-grpc/indexer-grpc-data-service/src/metrics.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs
As we introduce the concept of applications to API Gateway, we no longer rate limit by email but by application. The metrics from data service should align with that. Rather than "keying" by email + key name, we now key by application ID (which we call an `identifier`). This is a uuid4.
I will only land this when we're ready to land https://github.com/aptos-labs/api-gateway/pull/109 and its children.
I looked at the following dashboards and can see that the request_token, api_key_name, and email labels are not used for any queries:
- https://aptoslabs.grafana.net/d/fa76529f-4cfe-49bb-8d03-97e9e898f32b/indexer-grpc-debug?orgId=1&refresh=5s
- https://aptoslabs.grafana.net/d/b409aee0-50ba-4530-ba28-7326d868afee/indexer-grpc-sla-dashboard?orgId=1&refresh=5s
- …
=> [Data Service] Push metrics parameterized by identifier, not API key name + email

aptos-node/src/utils.rs, config/src/config/config_optimizer.rs, config/src/config/execution_config.rs, state-sync/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-driver/src/tests/bootstrapper.rs, state-sync/state-sync-driver/src/tests/utils.rs, types/src/epoch_state.rs
This PR extends support for non-genesis waypoints in two ways (each offered in their own commit):
1. Add a config optimizer for the `ExecutionConfig` so that if a node operator specifies a non-genesis waypoint in the node base config, the genesis waypoint will be automatically injected into the execution config (this is required by storage).
2. Add additional unit tests for state sync around waypoint verification and mismatches.
New and existing unit tests.
=> [Waypoint] Support non-genesis waypoints in the node configs.

.github/workflows/forge-stable.yaml, testsuite/forge.py
Use one Forge namespace for each branch. If multiple Forge stable tests are run for a branch the earlier runs should be preempted
Ran the continuous forge stable workflow manually https://github.com/aptos-labs/aptos-core/actions/runs/8428066515
=> use one forge namespace for each branch

testsuite/forge-cli/src/main.rs, testsuite/forge-cli/src/suites/dag.rs
This PR updates the forge tests `changing_working_quorum_test()` and `changing_working_quorum_test_high_load()` to allow error logs. These tests were incorrectly marked as to not allow errors, and are thus failing in our forge stable runs.
=> [Forge stable] Allow errors on failing forge tests.

.github/actions/rust-targeted-unit-tests/action.yaml, .github/actions/rust-unit-tests/action.yaml, .github/workflows/lint-test.yaml, devtools/aptos-cargo-cli/src/cargo.rs, devtools/aptos-cargo-cli/src/common.rs, devtools/aptos-cargo-cli/src/lib.rs
This PR offers several improvements to CI/CD when running the rust unit tests on Github PRs:
1. Only run all rust unit tests when an appropriate event occurs (e.g., auto-merge is enabled or the `CICD:run-all-unit-tests` label is applied).
- This will help to reduce the amount of wasted compute due to unnecessary runs.
1. Introduce a targeted rust unit tests job for PRs that only runs relevant rust unit tests. This builds on the existing `aptos-cargo-cli` and leverages target determination to decide which tests to run (i.e., based on changed files and the point at which the code forked off of the `main` branch in `aptos-core`).
- This should reduce unit test time and provide developers with faster feedback, as it avoids running unnecessary rust unit tests.
1. Add several new commands to …
=> [CI/CD] Add targeted unit test job and delay all unit tests.

third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs, third_party/move/move-compiler-v2/tests/reference-safety/function_ref.exp, third_party/move/move-compiler-v2/tests/reference-safety/function_ref.move, third_party/move/move-compiler-v2/tests/reference-safety/function_ref.no-opt.exp, third_party/move/move-compiler-v2/tests/reference-safety/function_ref_err.exp, third_party/move/move-compiler-v2/tests/reference-safety/function_ref_err.move, third_party/move/move-compiler-v2/tests/reference-safety/function_ref_err.no-opt.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_transfer_borrows.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_transfer_borrows.move, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_transfer_borrows.no-opt.exp
This PR makes a slight change on the relation between input and output references for a function call: if an output reference is mutable, it is a child of all input mutable references.
Close #12828 
1) Existing test cases. Note that the output of `call_transfer_borrows` is updated
2) Added a new test case `function_ref`.
=> [Compiler-v2] borrow analysis for function call

.github/actions/rust-targeted-unit-tests/action.yaml, .github/workflows/windows-build.yaml, devtools/aptos-cargo-cli/src/cargo.rs, devtools/aptos-cargo-cli/src/lib.rs
This PR updates the CLI test and build job in Windows to use target determination. This should help to reduce unnecessary CI/CD compute times by skipping the job if irrelevant changes are detected (currently, the entire job takes around ~20 minutes to run).
To achieve this, the PR adds a new command (`cargo x targeted-cli-tests`) to the `aptos-cargo-cli` which will test and build the Aptos CLI iff relevant rust changes are detected. If no relevant changes are detected the command returns early, e.g.:
```
% cargo x targeted-cli-tests -vv
[2024-04-10T18:10:23Z INFO  aptos_cargo_cli::common] Identified the merge base: "d7c50d7d4928e510e23710784325fa94e3392c9e"
Skipping CLI tests as the CLI package was not affected!
```
The PR also makes some small cleanups along the way with regards to the …
=> [CI/CD] Adopt targeted CLI windows build test.

config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/metrics.rs, state-sync/aptos-data-client/src/peer_states.rs, state-sync/aptos-data-client/src/tests/peers.rs
This PR makes three small changes to the Aptos Data Client (each in their own commit):
1. Add metrics to track the number of ignored peers.
2. Add a config flag to enable/disable ignoring peers. The default is true (as it is today).
3. Reduce the maximum number of multi-fetch requests from 5 to 3. Under high-load, the additional multi-fetches increase CPU usage unnecessarily.
=> [Aptos Data Client] Add metrics for ignored peers.

aptos-node/src/storage.rs, execution/executor/src/chunk_executor.rs, execution/executor/src/components/chunk_output.rs, execution/executor/src/tests/chunk_executor_tests.rs, storage/aptosdb/src/db/fake_aptosdb.rs, storage/aptosdb/src/db/include/aptosdb_internal.rs, storage/aptosdb/src/db/include/aptosdb_testonly.rs, storage/aptosdb/src/db/mod.rs, storage/aptosdb/src/db/test_helper.rs, storage/aptosdb/src/lib.rs, testsuite/forge-cli/src/main.rs
This PR fixes the consensus-only feature.
- It updates the FakeAptosDB implementation to mirror the recent refactorings of the original AptosDB.
- It bypasses the transaction proof verification during state sync chunk update stage. This was reintroduced after recent refactoring.
- Updates forge test to always execute transactions during state sync.
=> Refactor and fix consensus-only-perf-test feature

testsuite/performance_benchmark.sh
single_node_performance.py uses the value from environment variable instead of the command line arguments. Setting environment variables needs to be placed in front of the command
=> Fix environment variable setup in benchmark script

api/src/accept_type.rs
Addresses the issue described in #7855 
By first matching on JSON, rather than BCS, the default accept type will be JSON which the UI can display. To test that this works, you can: 
1) Go to https://fullnode.testnet.aptoslabs.com/v1/spec#/operations/view
2) Send this payload:
```
{
"function": "0x1::timestamp::now_seconds",
"type_arguments": [],
"arguments": []
}
```
3) You will see `200 "No supported response body returned". `
4) Run local testnet on this branch (`cargo run -p aptos -- node run-local-testnet --faucet-port 8081 --force-restart --assume-yes`)
5) Go to http://127.0.0.1:8080/v1/spec#/operations/view
6) The same payload will now return `200 ["correct timestamp"]. `
This also works for the other endpoints i.e. `https://fullnode.testnet.aptoslabs.com/v1/spec#/operations/get_acco …
=> [api] default to json accept type

aptos-node/src/lib.rs, aptos-node/src/tests.rs, crates/aptos/src/node/local_testnet/node.rs
Introduces a `performance` mode for `test` where you need a single node network that can run a fair bit of load. On my macbook, this was ~5K TPS.
`cargo run -p aptos-node --release -- --test --performance`
Then run txn emitter:
`cargo run -p aptos-transaction-emitter --release -- emit-tx -t http://localhost:8080 --mint-file <path to mint.key from above command> --chain-id 4 --duration 120 --txn-expiration-time-secs 60 --mempool-backlog=22000 --expected-max-txns 1200000 --init-gas-price-multiplier=1 --max-transactions-per-account 5 --transaction-type coin-transfer`
=> [aptos-node] add --performance mode for --test

third_party/move/move-compiler-v2/src/experiments.rs, third_party/move/move-compiler-v2/src/lib.rs, third_party/move/move-compiler-v2/src/struct_params_checker.rs, third_party/move/move-compiler-v2/src/unused_params_checker.rs, third_party/move/move-compiler-v2/tests/checking/access_specifiers/access_ok.move, third_party/move/move-compiler-v2/tests/checking/naming/duplicate_type_parameter_function.exp, third_party/move/move-compiler-v2/tests/checking/naming/duplicate_type_parameter_struct.exp, third_party/move/move-compiler-v2/tests/checking/naming/unused_type_parameter_struct.exp, third_party/move/move-compiler-v2/tests/checking/naming/unused_type_parameter_struct.move, third_party/move/move-compiler-v2/tests/checking/naming/unused_type_parameter_struct_invalid_fields.exp, third_party/move/move-compiler-v2/tests/checking/naming/unused_type_parameter_struct_invalid_fields.move, third_party/move/move-model/src/builder/exp_builder.rs, third_party/move/move-prover/src/lib.rs
- Implement a checker for unused parameters in struct definitions, as an environment pipeline
- Improve the error messages for duplicate type parameters for functions and structs, by adding the location of the duplication.
Fixed #11709
Existing tests and `checking/naming/unused_type_parameter_struct.move`
=> [Compiler-V2] Unused type parameter checking

state-sync/aptos-data-client/src/tests/peers.rs
This PR disables a flaky test in the Aptos Data Client. At some point, I'll return to debug it, but for now, let's move it off the critical path.
=> [Aptos Data Client] Ignore flaky test.

.pre-commit-config.yaml, devtools/assets/license_header_utf8.txt, devtools/assets/shared_license_header.txt, devtools/assets/shared_license_header_utf8.txt, devtools/assets/third_party_license_header.txt, devtools/assets/third_party_license_header_2.txt, protos/rust/src/pb/aptos.bigquery_schema.transaction.v1.rs, protos/rust/src/pb/aptos.bigquery_schema.transaction.v1.serde.rs, protos/rust/src/pb/aptos.indexer.v1.rs, protos/rust/src/pb/aptos.indexer.v1.serde.rs, protos/rust/src/pb/aptos.indexer.v1.tonic.rs, protos/rust/src/pb/aptos.internal.fullnode.v1.rs, protos/rust/src/pb/aptos.internal.fullnode.v1.serde.rs, protos/rust/src/pb/aptos.internal.fullnode.v1.tonic.rs, protos/rust/src/pb/aptos.remote_executor.v1.rs, protos/rust/src/pb/aptos.remote_executor.v1.serde.rs, protos/rust/src/pb/aptos.remote_executor.v1.tonic.rs, protos/rust/src/pb/aptos.transaction.v1.rs, protos/rust/src/pb/aptos.transaction.v1.serde.rs, protos/rust/src/pb/aptos.util.timestamp.rs, protos/rust/src/pb/aptos.util.timestamp.serde.rs, protos/rust/src/pb/mod.rs, third_party/move/move-model/bytecode/abstract_domain_derive/tests/test.rs, third_party/move/move-vm/types/src/delayed_values/error.rs
Add multiple allowed license files to pre-commit script, tolerating
existing UTF8-encoded (c) symbols but adding ASCII-only notices if
missing.  Update 3 .rs files that were missing Copyright notices.
Add a section for third_party license notices.
This enables #12687, which will have a  race with other code changes.
Local testing.
=> Prepare for ASCII copyrights by using multiple license files in pre-commit script

aptos-move/aptos-release-builder/src/main.rs, aptos-move/move-examples/large_packages/large_package_example/sources/five.move, crates/aptos-faucet/DEV.md, crates/aptos-faucet/README.md, crates/aptos-faucet/configs/testing_redis_minter_local.yaml, crates/aptos-faucet/core/src/server/run.rs, crates/aptos-faucet/integration-tests/README.md, crates/aptos-faucet/integration-tests/local_testnet.py, crates/aptos-faucet/integration-tests/main.py, crates/aptos/CHANGELOG.md, crates/aptos/e2e/cases/init.py, crates/aptos/e2e/local_testnet.py, crates/aptos/e2e/main.py, crates/aptos/e2e/test_helpers.py, crates/aptos/src/main.rs, crates/aptos/src/node/local_testnet/docker.rs, crates/aptos/src/node/local_testnet/faucet.rs, crates/aptos/src/node/local_testnet/indexer_api.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/node.rs, crates/aptos/src/node/local_testnet/postgres.rs, crates/aptos/src/node/local_testnet/processors.rs, crates/aptos/src/node/local_testnet/ready_server.rs, crates/aptos/src/node/mod.rs, docker/compose/indexer-grpc/README.md, ecosystem/indexer-grpc/indexer-grpc-integration-tests/src/tests/fullnode_tests.rs, ecosystem/typescript/sdk/examples/typescript/call_aptos_cli.ts, ecosystem/typescript/sdk/scripts/publish_ans_contract.ts, ecosystem/typescript/sdk/src/tests/e2e/fungible_asset_client.test.ts
"Local testnet" is a consistently confusing name because many users assume it has something to do with the production testnet. "Localnet" is much clearer.
`run-local-testnet` will continue to work so it doesn't break anything, but we'll refer to `run-localnet` and call it a localnet (or in a long form a "local development environment", which is what the docs do) moving forward.
For now we still use `run-local-testnet` when actually invoking the CLI.
```
cargo run -p aptos -- node run-localnet -h
cargo run -p aptos -- node run-local-testnet -h
```
Just thoughts on the naming.
=> Rename run-local-testnet to run-localnet, keep alias for old name

Cargo.lock, aptos-move/aptos-debugger/src/aptos_debugger.rs, aptos-move/aptos-vm/src/aptos_vm.rs, crates/aptos/Cargo.toml, crates/aptos/src/common/local_simulation.rs, crates/aptos/src/common/mod.rs, crates/aptos/src/common/types.rs, crates/aptos/src/common/utils.rs, crates/aptos/src/move_tool/mod.rs, ecosystem/indexer-grpc/indexer-grpc-in-memory-cache-benchmark/Cargo.toml
This is a major enhancement to the CLI's ability to perform various kinds of local simulations.
These commands now get the following new options:
- `--local`: simulates the transaction locally as opposed to sending it to the fullnode
- `--benchmark`: benchmarks the transaction locally
```
Usage: aptos move replay [OPTIONS] --network <NETWORK> --txn-id <TXN_ID>
Options:
--network <NETWORK>
The network to replay on.
Possible values: mainnet, testnet, <REST_ENDPOINT_URL>
--txn-id <TXN_ID>
The id of the transaction to replay. Also being referred to as "version" in some contexts
--benchmark
If this option is set, benchmark the transaction and report the running time(s)
--profile-gas
If this option is set, profile the transaction and generate a detailed report of its gas usage
--skip-comparison …
```
=> [CLI] introduce local simulation, benchmarking and replay

Cargo.lock, Cargo.toml, tools/calc-dep-sizes/Cargo.toml, tools/calc-dep-sizes/src/main.rs
This introduces a script that reads all move modules (.mv files) in a directory recursively and computes the dependency size for each module. The results will be saved to a .csv file.
=> [move] script for calculating dependency sizes

dkg/src/counters.rs, dkg/src/dkg_manager/mod.rs, testsuite/smoke-test/src/aptos_cli/validator.rs, types/src/dkg/mod.rs, types/src/dkg/real_dkg/mod.rs, types/src/dkg/real_dkg/rounding/mod.rs, types/src/dkg/real_dkg/rounding/tests.rs
- Add rounding metrics.
- Use a back-up rounding mechanism when the default search returns no result.
The back-up mechanism:
- guarantees privacy and liveness.
- requires total weight to be ~3n where n is the number of validators.
UTs
=> dkg rounding updates

.github/actions/file-change-determinator/action.yaml, .github/actions/move-tests-compiler-v2/action.yaml, .github/workflows/move-test-compiler-v2.yaml, Cargo.lock, Cargo.toml, devtools/aptos-cargo-cli/Cargo.toml, devtools/aptos-cargo-cli/src/common.rs, devtools/aptos-cargo-cli/src/lib.rs
This PR updates the compiler v2 tests to use target determination. This should help to reduce unnecessary CI/CD compute times by skipping the job if irrelevant changes are detected.
To achieve this, the PR adds a new command (`cargo x targeted-compiler-v2-tests`) to the `aptos-cargo-cli` which will run the compiler v2 tests iff relevant changes are detected. Relevant changes are defined as changes that either: (i) touch the list of file paths we care about; or (ii) impact the `e2e-move-tests` and `aptos-framework` rust packages.
The PR offers two commits:
1. Update the CLI to offer the new targeted compiler v2 tests. Including simple unit tests.
2. Remove reliance on the old (buggy) target determination system.
=> [CI/CD] Add support for targeted compiler v2 tests

testsuite/forge/src/backend/k8s/helm-values/aptos-node-default-values.yaml
Remove the debug override for forge debug logs
This is to cut down the log volume, debug logs around 30% of forge logs (which is the current top contributor to log volume)
Test Plan: check logs from the PR job
=> [forge] Decrease log level to info

.github/workflows/coverage-move-only.yaml, .github/workflows/coverage.yaml
This PR updates the code coverage GHA jobs not to fail if the codecov upload step fails. This can happen for various reasons (and the current set of failures still needs to be debugged). Unblocking this for now.
=> [Coverage] Don't fail job on codecov upload failure

aptos-move/move-examples/raffle/Move.toml, aptos-move/move-examples/raffle/scripts/test_and_abort_attack_defeated.move, aptos-move/move-examples/raffle/sources/raffle.move, aptos-move/move-examples/raffle/sources/raffle_test.move
This is to replace the `raffle` example on the `randomnet` branch, as the syntax has changed, and devnet should be developed on rather than `randomnet` for randomness.
Compiled and ran locally
This copies the existing one on randomnet, and adds the annotation for randomness
=> [move-examples] Add raffle example that supports the latest syntax

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
This tunes the gas costs and limits for dependencies.
=> [gas] tune dependency gas

third_party/move/move-compiler-v2/src/cyclic_instantiation_checker.rs, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/recursive_type_instantiation.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/complex_1.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/mutually_recursive_three_args_type_con_non_generic_types_ok.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/mutually_recursive_three_args_type_con_shifting.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/mutually_recursive_two_args_swapping_type_con.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/mutually_recursive_type_con.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/nested_types_1.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/nested_types_2.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/recursive_infinite_type_terminates.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/recursive_one_arg_type_con.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/recursive_two_args_swapping_type_con.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/two_loops.exp, third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-typing/infinite_instantiations_invalid.exp
For error messages like "f calls g at loc", the loc is previously the location of f, the caller, but it better be the location of g, the callee. See the updated test outputs for examples.
Fixes #12903.
=> [Compiler-V2] [Bugfix] Improve cyclic instantiation checker error messages

Cargo.lock, mempool/Cargo.toml, mempool/src/shared_mempool/tasks.rs
Transaction validation is happening in serial today, which hurts the latency when validation is expensive for a certain type of transaction. This should help alleviate the issue. 
Test with Forge. Average transaction processing latency goes down from 15 ms (https://aptoslabs.grafana.net/goto/3nJ9oVfIg?orgId=1) to 7 ms after this change (https://aptoslabs.grafana.net/goto/3nJ9oVfIg?orgId=1)
=> [Mempool] Transaction validation in parallel

crates/aptos-dkg/src/pvss/das/unweighted_protocol.rs, crates/aptos-dkg/src/pvss/das/weighted_protocol.rs, crates/aptos-dkg/src/pvss/fiat_shamir.rs
Derive linear combination coefficients from Fiat-Shamir result.
Existing UTs
n/a
=> deterministic pvss verify

config/src/config/consensus_config.rs, consensus/src/pipeline/buffer_manager.rs, consensus/src/pipeline/decoupled_execution_utils.rs, consensus/src/pipeline/execution_client.rs, consensus/src/pipeline/tests/buffer_manager_tests.rs
Add broacast_commit_votes flag in ConsensusConfig to enable or disable the broadcast of commit votes in buffer_manager.
=> Add broadcast_commit_votes flag to ConsensusConfig

storage/schemadb/src/lib.rs, storage/schemadb/tests/db.rs
as titled. if we had this, reverting from 1.11 to 1.10 binary wouldn't have been a problem.
unit test
=> schemadb: ignore unrecognized CF on opening

aptos-move/framework/aptos-framework/doc/overview.md, aptos-move/framework/aptos-framework/doc/randomness_config_seqnum.md, aptos-move/framework/aptos-framework/doc/reconfiguration_with_dkg.md, aptos-move/framework/aptos-framework/sources/configs/config_buffer.move, aptos-move/framework/aptos-framework/sources/configs/randomness_config_seqnum.move, aptos-move/framework/aptos-framework/sources/reconfiguration_with_dkg.move, aptos-move/vm-genesis/src/lib.rs, aptos-node/src/lib.rs, config/src/config/node_config.rs, consensus/src/epoch_manager.rs, consensus/src/rand/rand_gen/rand_manager.rs, crates/aptos/src/test/mod.rs, dkg/src/epoch_manager.rs, dkg/src/lib.rs, testsuite/smoke-test/src/randomness/mod.rs, testsuite/smoke-test/src/randomness/randomness_stall_recovery.rs, types/src/on_chain_config/mod.rs, types/src/on_chain_config/randomness_config.rs
Adding:
- a local config to disable randomness at a chain halt caused by randomness generation failure,
- an on-chain config to re-enable randomness after the recovery.
new smoke test.
=> config to disable randomness in a chain halt

aptos-move/framework/aptos-stdlib/doc/smart_table.md, aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move, aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move
@gregnazario @lightmark @vgao1996 
Presently, trying to get all keys for a sufficiently large simple table will error out due to execution gas errors.
Add a pagination function to get keys in a smart table, for indexing smart tables either across successive transactions or through chained view function calls. Also add a wrapper to the pagination function that gets all keys.
Affected functions tested to 100% coverage, but Move source coverage feature in the CLI might erroneously print red: so use `aptos move coverage bytecode --module smart_table` to verify bytecode coverage.
=> [Framework] Add smart table keys lookup with pagination, tests

keyless/circuit-data/templates/helpers/misc.circom
Description of bug is here:
https://www.notion.so/aptoslabs/JWTFieldCheck-does-not-properly-constrain-field_len-which-can-cause-the-circuit-to-accept-field-val-9943c152e7274f35a1669a6cb416c7bf?pvs=4
=> Modify JWTFieldCheck to enforce field_len >= name_len + value_len + 1

.github/workflows/forge-stable.yaml, testsuite/forge-cli/src/main.rs, testsuite/forge/src/interface/swarm.rs, testsuite/testcases/src/compatibility_test.rs, testsuite/testcases/src/framework_upgrade.rs
Previously we wanted to test compatibility and test framework upgrades separately
As a part of the new release schedule (more regular / frequent / backwards compatible upgrades) we need to test compatibility throughout the upgrade process
So it no longer makes sense to have two tests, keep the previous compat test for local testing, but use only the framework upgrade test for k8s testing.
Test Plan: framework upgrade on the PR passes
=> [forge] Merge compat and framework test in k8s forge

testsuite/forge/src/backend/k8s/helm-values/aptos-node-default-values.yaml
Fix forward for https://github.com/aptos-labs/aptos-core/pull/12917.
The `rust_log` helm value sets the `RUST_LOG` env var. Setting just `hyper=off` actually overwrites the default log level. Thus we need to set it to `info`
Forge logs from the PR. The logs must include those from the validators/fullnodes from the Forge test's k8s namespace, as well as the test runner
The config
=> [forge] fix info logs for validators and fullnodes

storage/aptosdb/src/state_kv_db.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/utils/truncation_helper.rs
1. between batches, the progress should be updated after the deletions on shards.
2. in a single batch, the record is possible to equal "current_version"
eyeing. it's rare except in Zhoujun's bulk testing. will observe if this fixes his seeing truncation failure.
=> fix state kv truncate

aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/e2e-benchmark/src/main.rs, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/framework/aptos-framework/sources/object.spec.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/framework/src/natives/object.rs, aptos-move/framework/src/natives/transaction_context.rs, testsuite/single_node_performance.py, types/src/on_chain_config/aptos_features.rs, types/src/transaction/authenticator.rs
Computing address for primary_fungible_asset store is expensive, and repeated multiple times. (especially if we start using fungible assets for gas charging)
This optimizes that computation by moving it to rust, and by caching it within a transaction (so computation in prologue gets saved for epilogue)
performance on Coin => FA migration
=> Use native implementation to optimize object derived address computation

types/src/state_store/state_key.rs
`## Description
This is to completely remove StateKey::access_path()
tests
=> trivial: test state key hashes for different AccessPath flavors

aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs, aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs, aptos-move/aptos-gas-schedule/src/ver.rs
=> Add gas vesion list, and fix gas version for derived object id native function

.github/workflows/coverage.yaml
Ongoing effort in fixing tests coverage on codecov, some tests hit a stack overflow trying to bump the stack size to 4 times the current size.
https://github.com/aptos-labs/aptos-core/pull/13013
- [ X] Bug fix
- [ X] Tests
- [X ] Developer Infrastructure
Running CI/CD on this PR.
N.A.
- [X ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [X ] I tested both happy and unhappy path of the functionality
- [ X] I have made corresponding changes to the documentation
=> Increase stack for test from 8 to 32 MB

api/types/src/convert.rs, consensus/src/rand/rand_gen/rand_manager.rs, consensus/src/round_manager.rs, crates/reliable-broadcast/src/lib.rs
This (opinionated) PR reduces the log frequencies of the ~15 most spammy logs in `aptos-node`. In most cases, we reduce the logs from `info` level logs to `debug` logs (so that they can be dropped in various environments, e.g., `forge`). This seems superior to using `sample` because it still allows developers who care about these logs to read/process all of them when `debug` logs are enabled.
Note: if there's any changes in this PR you disagree with, please let us know so that we can discuss it 😄 This PR is a starting point.
=> [Logging] Reduce noisy logs.

Cargo.lock, mempool/Cargo.toml, mempool/src/shared_mempool/runtime.rs, vm-validator/Cargo.toml, vm-validator/src/vm_validator.rs
https://github.com/aptos-labs/aptos-core/pull/12940 introduced transaction validation to be done in parallel, however, the VM is not threadsafe. This change introduces a pool of VMs so that we can avoid race conditions in the VM. 
Existing UTs and Forge.
=> [Mempool] Use a pool of VMs for transaction validation

aptos-move/aptos-release-builder/data/release.yaml
Based on my simulation **3739 gas units** are needed for execution of framework upgrade with #13040 and #13027 .
Bumping the execution gas limit.
```
{"execution_gas_units":"3739","io_gas_units":"161","storage_fee_octas":"46320","storage_fee_refund_octas":"0","total_charge_gas_units":"4363"}
```
=> higher execution gas limit

.github/workflows/forge-stable.yaml
We made a change to make sure there is only one forge stable running by using the same namespace depending on the branch name, however we forgot the other half of that change
Currently this means all forge stable runs collide with each other, but are not cancelled at workflow level leading to them racing and cancelling each other
This change ensures the entire workflow is cancelled in favor of the other job.
Test Plan: runs on PR
=> [gha] Fix forge stable concurrency

.github/actions/framework-upgrade-determinator/action.yaml, .github/workflows/docker-build-test.yaml, devtools/aptos-cargo-cli/src/lib.rs
This PR updates the framework upgrade test to use target determination. This should help to reduce unnecessary CI/CD runs by skipping the job if irrelevant changes are detected.
To achieve this, the PR adds a new command (`cargo x targeted-framework-upgrade-tests`) to the `aptos-cargo-cli`. The command will output if relevant changes are detected and the framework upgrade test should be performed. For example:
```
% cargo x targeted-framework-upgrade-tests
Framework upgrade test required: true
```
We define "relevant changes" for running the framework upgrade test as: (i) touching the list of file paths we care about (as provided by @runtian-zhou); or (ii) affecting the `aptos-framework` or `aptos-release-builder` rust packages.
Note:
- If target determination finds that the framework …
=> [CI/CD] Add simple target determination for framework upgrade test.

third_party/move/move-compiler-v2/src/unused_params_checker.rs, third_party/move/move-prover/src/lib.rs
Fixes #13093 by not checking for structures generated from ghost variables.
=> [Compiler-V2] [Bugfix] Fix bug in unused parameter checker

third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs, third_party/move/move-compiler-v2/tests/reference-safety/write_ref_dest.exp, third_party/move/move-compiler-v2/tests/reference-safety/write_ref_dest.move, third_party/move/move-compiler-v2/tests/reference-safety/write_ref_dest.no-opt.exp, third_party/move/move-compiler-v2/tests/reference-safety/write_ref_dest_err.exp, third_party/move/move-compiler-v2/tests/reference-safety/write_ref_dest_err.move, third_party/move/move-compiler-v2/tests/reference-safety/write_ref_dest_err.no-opt.exp, third_party/move/move-compiler-v2/transactional-tests/tests/misc/write_ref_dest.exp, third_party/move/move-compiler-v2/transactional-tests/tests/misc/write_ref_dest.move
Previously, as long as the temp is borrowed, it cannot be written. This PR relaxes the condition that if all borrowing temps are not alive after the statement, it can be written.
close #12888 
Existing test cases and newly added test cases
Whether this change can be applied to all checks on local writes.
=> [Compiler-v2] Relax check on whether a local can be written

Cargo.lock, Cargo.toml, api/types/src/wrappers.rs, aptos-move/aptos-vm-types/src/storage/io_pricing.rs, aptos-move/e2e-move-tests/src/tests/access_path_test.rs, storage/aptosdb/src/schema/stale_state_value_index/mod.rs, storage/aptosdb/src/schema/state_value/mod.rs, storage/aptosdb/src/schema/state_value_index/mod.rs, testsuite/generate-format/Cargo.toml, types/Cargo.toml, types/benches/state_key.rs, types/src/state_store/state_key/inner.rs, types/src/state_store/state_key/mod.rs, types/src/state_store/state_key/prefix.rs, types/src/state_store/state_key/registry.rs
1. StateKey is an Arc, so super cheap to clone.
1. StateKeyRegistry to cache actual state key instances. 
1. `StateKey::resource()` etc. tries to fetch a cached entry from the registry rather than constructing a new instance.
results:
1. single-node-performance has a 6% -ish TPS gain on average
2. inserting existing (cached) keys to a new set is 10x -ish faster as observed in a Criterion benchmark introduced in the same PR, which is the purpose of this in the first place.
3. didn't observe any significant gain in a cluster setting.
txn | ws | vm? | block size | expected | Baseline | with Registry | pct
-- | -- | -- | -- | -- | -- | -- | --
warmup | 1 | VM | 10000 | 0 | 10771.8 | 11225.7 | 4.21%
no-op | 1 | VM | 10000 | 22200 | 20552.3 | 22046.7 | 7.27%
no-op | 1000 | VM | 10000 | 11500 | …
=> StateKeyRegistry

aptos-move/aptos-gas-profiling/templates/index.html
Fixes broken HTML in the gas profiler reports
Just an HTML change according to the missing tags
look at the HTML
=> [gas] Fix broken HTML in gas profiler

aptos-move/aptos-gas-meter/src/meter.rs, aptos-move/aptos-gas-schedule/src/lib.rs, aptos-move/aptos-gas-schedule/src/ver.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/keyless_validation.rs
The previous implementation was incompatible with what got deployed to testnet. This gets it fixed.
=> [vm] fix gas feature gating for keyless transactions

crates/aptos/src/common/types.rs
Remove `hide = true` from the option `compiler-version` and `language-version` for the Aptos CLI.
=> [cli][trivial] Change compiler option in CLI

Cargo.lock, storage/schemadb/src/iterator.rs, storage/schemadb/src/lib.rs, storage/storage-interface/Cargo.toml, storage/storage-interface/src/errors.rs
as requested in https://github.com/aptos-labs/aptos-core/issues/12451
build
=> trivial: storage-interface not depend on rocksdb::Error

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml
Version bump ahead of release. Please note that this PR will not be merged in until all the release-blocking PRs land on main (which should be fairly soon). Please do not auto-merge.
n/a
Is the version bump acceptable or do we bump it to 4.0.0? There was an unreleased breaking change that I am not sure whether it qualifies to move up major version (or if the minor version bump suffices).
=> [cli] Bump to 3.3.0

storage/aptosdb/src/state_kv_db.rs, storage/aptosdb/src/state_merkle_db.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/utils/truncation_helper.rs
Fix that state tree / kv truncator do duplicated work when db sharding is not enabled.
forge test fullnode_reboot_stress_test were broken since last fix (where state kv db truncation is always attempted), this fixes that.
=> [INC-600] fix state db truncation when db-sharding is not enabled.

.github/actions/test-target-determinator/action.yaml, .github/workflows/docker-build-test.yaml, .github/workflows/execution-performance.yaml, .github/workflows/workflow-run-execution-performance.yaml, devtools/aptos-cargo-cli/src/lib.rs
This PR updates the execution performance test to use target determination. This should help to reduce unnecessary CI/CD runs by skipping the job if irrelevant changes are detected.
To achieve this, the PR adds a new command (`cargo x targeted-execution-performance-tests`) to the `aptos-cargo-cli`. The command will output if relevant changes are detected and the execution performance test should be performed. For example:
```
% cargo x targeted-execution-performance-tests
Execution performance test required: true
```
We define "relevant changes" for running the test as: (i) touching the list of file paths we care about (see the PR); or (ii) affecting the `aptos-executor-benchmark` or `aptos-move-e2e-benchmark` rust packages.
Note:
- Target determination for the execution performance tests …
=> [CI/CD] Add target determination for execution performance tests.

crates/transaction-emitter-lib/src/emitter/stats.rs, crates/transaction-emitter-lib/src/emitter/submission_worker.rs, ecosystem/node-checker/src/checker/tps.rs, sdk/src/types.rs, testsuite/forge/src/report.rs, testsuite/forge/src/success_criteria.rs
and some helpful comments
In a 30 second sample, rounding to int can be 3-4% off. Use float64.
unit tests, forge tests
Variable meaning comments are accurate
=> TxnStatsRate fields as f64

third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs, third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs
This PR fixes #13201 by attaching the type information to cons_to_idx to make sure different ConstantPoolIndex will be generated when there are multiple constants which have the same value but different types. For instance in the following code, both KEYS and VALUES are empty vectors but one is of type `vector<vector<u8>>` and the other is of type `vector<u64>`.
```
module 0x42::m {
use std::bcs;
use std::string::{Self};
use std::vector;
const KEYS: vector<vector<u8>> = vector[];
const VALUES: vector<u64> = vector[];
public entry fun init(
) {
let _ = vector::map(KEYS, |key|{ string::utf8(key)});
let _ = vector::map(VALUES, |v|{ bcs::to_bytes<u64>(&v)});
}
}
```
PR #13205 already added test cases. Only need to make sure existing tests still pass. 
Some changes in #13205  are reverted. …
=> [compiler-v2] Add type information to cons_to_idx

aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/framework/aptos-framework/sources/object.spec.move
Make it so that objects can be made immovable via the constructor ref. Even if other entities have access to the constructor ref.
Add the functionality to fungible asset to make immovable stores by default for assets that opt into the behavior.
Also offer a root_owner function to determine the deepest node that owns a nested object.
See https://github.com/aptos-foundation/AIPs/pull/414
Lots of unit tests
There's really not that much code...
=> [framework] implement immovable objects

aptos-move/framework/aptos-framework/doc/dispatchable_fungible_asset.md, aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/doc/primary_fungible_store.md, aptos-move/framework/aptos-framework/doc/staking_config.md, aptos-move/framework/aptos-framework/doc/storage_gas.md, aptos-move/framework/aptos-framework/sources/configs/staking_config.spec.move, aptos-move/framework/aptos-framework/sources/dispatchable_fungible_asset.move, aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/framework/aptos-framework/sources/primary_fungible_store.move, aptos-move/framework/aptos-framework/sources/storage_gas.spec.move, aptos-move/framework/aptos-framework/tests/deflation_token_tests.move, aptos-move/framework/aptos-framework/tests/simple_dispatchable_token.move, aptos-move/framework/aptos-framework/tests/simple_dispatchable_token_fa_tests.move, aptos-move/framework/aptos-framework/tests/simple_dispatchable_token_pfs_tests.move, third_party/move/move-compiler-v2/src/plan_builder.rs, third_party/move/move-compiler/src/unit_test/mod.rs, third_party/move/move-compiler/src/unit_test/plan_builder.rs, third_party/move/move-vm/runtime/src/data_cache.rs, third_party/move/move-vm/runtime/src/interpreter.rs, third_party/move/tools/move-cli/tests/sandbox_tests/multi_module_publish/args.exp, third_party/move/tools/move-unit-test/src/test_runner.rs, third_party/move/tools/move-unit-test/tests/test_sources/missing_data.exp, third_party/move/tools/move-unit-test/tests/test_sources/non_exsistent_native.exp, third_party/move/tools/move-unit-test/tests/test_sources/out_of_gas.exp
Fixes a bunch of issues:
1. Updated move-unit-test to include full error msg on test failure so we can see the detailed error msg.
2. Fix error msg when the module that contains the hook function doesn't exist.
3. Fix error msg when invoking FS api on assets with hook registered.
4. Fix PFS mint to invoke withdraw_internal.
5. Fix transfer api in dispatchable api to check for the frozen bit.
Added tests for each affected cases.
N/A
=> [framework] A few minor fix for dispatchable token 

aptos-move/framework/aptos-framework/doc/delegation_pool.md, aptos-move/framework/aptos-framework/sources/delegation_pool.move
The specs of delegating voting power (VP) from a delegation pool state that the pending voter of a delegator becomes effective next lockup cycle. However, due to some missing logic in `update_and_borrow_mut_delegator_vote_delegation` of `delegation_pool.move`, the pending voter of a delegator may take effect immediately without waiting for the current lockup cycle to end.
`VoteDelegation.last_locked_until_secs` is the timestamp when `VoteDelegation.pending_voter` takes effect. Currently, `last_locked_until_secs` is not updated to be the end timestamp of the current lockup cycle on the delegation pool. It is correctly initialized and, consequently, everything works as expected during the first lockup cycle when `VoteDelegation` has been created, but remains immutable and outdated …
=> [delegated voting] hotfix pending voter applying instantly on delegation pools

Cargo.lock, aptos-move/e2e-tests/Cargo.toml, aptos-move/e2e-tests/src/executor.rs, testsuite/fuzzer/fuzz/Cargo.toml, testsuite/fuzzer/fuzz/fuzz_targets/move/aptosvm_publish_and_run.rs
* Updated the fuzzer to use official publish flow for deploying module
* Additional improvements which improve performance by a good margin at an expense of small patch to `FakeExecutor`
* Verify the modules with production config to reject bad modules quicker
N/A
The patch to `FakeExecutor` and it's feature gating.
=> [Fuzzing] Do publish with official flow

.github/workflows/workflow-run-replay-verify.yaml, testsuite/replay_verify.py
=> [replay-verify] rebalance the ranges

consensus/consensus-types/src/proof_of_store.rs, consensus/src/logging.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/proof_coordinator.rs, testsuite/forge-cli/src/main.rs
The motivation is our metrics show failed quorums when there are late votes, even if the quorum was in fact reached before the late votes. There were subtle bugs in metrics when inline batches are used (before getting quorum) and/or batches with the same digests (either remotely or locally) are created.
Thinking a bit more, there's no reason to use digest in proof coordinator, so changing to use the batch info instead. This means we no longer have to disambiguate between batches that are possibly created with the same digests (either remotely or locally). This simplifies the code significantly while dealing with the above issues.
Ran forge stable workload sweep test, which has gas cut
=> [quorum store] better handling of proofs in proof coordinator

storage/jellyfish-merkle/src/lib.rs, storage/jellyfish-merkle/src/node_type/mod.rs, storage/jellyfish-merkle/src/node_type/node_type_test.rs, storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs, storage/scratchpad/src/sparse_merkle/test_utils/naive_smt.rs, storage/scratchpad/src/sparse_merkle/updater.rs, types/src/proof/definition.rs, types/src/proof/unit_tests/proof_test.rs
Our implementation outputs the new order natually without the need for
reversing.
Lucky that we didn't expose the state proof to outside of the node
The range proof unfortunately is already exposed, so not gonna be
changed.
unit tests updated.
checked code as far as I can, and I don't think the proof is exposed anywhere, including db backups.
=> reverse state proof siblings

aptos-move/aptos-release-builder/src/components/consensus_config.rs, aptos-move/aptos-release-builder/src/components/execution_config.rs, aptos-move/aptos-release-builder/src/components/gas.rs, aptos-move/aptos-release-builder/src/utils.rs, aptos-move/framework/src/release_bundle.rs
Currently it takes an excruciatingly long time to generate the governance proposals for releases. This is because we generate all blobs as `vector<u8>`, and compiler v1 presumably runs some non-linear algorithms on these vectors.
This changes all `vector<u8>` to hex strings, greatly reducing compilation time (before: 13 minutes, after: 26 seconds, release mode).
=> [release-builder] reduce compilation time by generating blobs as hex strings as opposed to vectors

storage/jellyfish-merkle/src/lib.rs
Original thought was in these rare cases we just waste a constructed Child to make the code simply, however it wasn't considered that there's a panic on hash_cache miss. I think the panic is valuable assertion so this is fixing it by some extra code.
locally tested by running the replay tool.
unit test coverage was not able to catch this because deletion is not tested enough. Gonna update proptest separately though, to fix forward quickly.
=> Fix hash_cache miss when leaf is brought up on sibling deletion

aptos-move/e2e-benchmark/src/main.rs, storage/scratchpad/src/sparse_merkle/mod.rs, storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs, storage/storage-interface/src/async_proof_fetcher.rs, storage/storage-interface/src/cached_state_view.rs, types/src/proof/definition.rs
In the presence of deletion, a leaf node on the SMT can be lifted, so
the hash value won't be matching that in the DB.
Examining more, it's obvious that in such cases proof fetching is not
needed in the first place.
updated unit tests.
replay-verify.
it's unfortunate unit tests don't have much coverage for state deletion -- a tech debt I'm gonna fix as a follow up.
=> Fix SMT proof fetching for lifted leaf

aptos-move/aptos-release-builder/data/keyless.yaml
Adds governance proposal to enable keyless accounts ([AIP-61](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-61.md)) in v1.12.
Thoroughly, in other keyless PRs.
Review the .yaml file, since I am no expert on it.
=> governance proposal to enable privacy-preserving keyless accounts

aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs, aptos-move/aptos-gas-schedule/src/ver.rs
These gas params were reverted for 1.12 and should now target 1.13 (gas feature version 18).
=> [gas] fix gas feature version for function info and dispatchable token gas params

.github/workflows/docker-build-test.yaml, .github/workflows/forge-stable.yaml, aptos-move/aptos-release-builder/data/release.yaml
This PR reset `release.yaml` for the v1.13 release
=> Update release.yaml and the forge test base node hash for the v1.13 release

Cargo.lock, consensus/src/dag/tests/integration_tests.rs, consensus/src/network.rs, consensus/src/network_tests.rs, consensus/src/round_manager_test.rs, consensus/src/twins/twins_node.rs, mempool/src/shared_mempool/coordinator.rs, mempool/src/tests/mocks.rs, mempool/src/tests/node.rs, mempool/src/tests/test_framework.rs, network/benchmark/src/lib.rs, network/builder/src/builder.rs, network/builder/src/dummy.rs, network/framework/Cargo.toml, network/framework/src/application/storage.rs, network/framework/src/application/tests.rs, network/framework/src/connectivity_manager/mod.rs, network/framework/src/connectivity_manager/test.rs, network/framework/src/peer_manager/builder.rs, network/framework/src/peer_manager/conn_notifs_channel.rs, network/framework/src/peer_manager/mod.rs, network/framework/src/peer_manager/tests.rs, network/framework/src/peer_manager/types.rs, network/framework/src/protocols/health_checker/interface.rs, network/framework/src/protocols/health_checker/mod.rs, network/framework/src/protocols/health_checker/test.rs, network/framework/src/protocols/network/mod.rs, network/framework/src/testutils/test_node.rs, peer-monitoring-service/server/src/tests.rs, state-sync/storage-service/server/src/tests/mock.rs
This reverts commit f5de7609d50860e42b4b2dcd72e968cd6c57071e.
=> [cherrypick][1.12] Revert "Event simplification conn subs (#12730)"

Cargo.lock, consensus/src/dag/tests/integration_tests.rs, consensus/src/network.rs, consensus/src/network_tests.rs, consensus/src/round_manager_test.rs, consensus/src/twins/twins_node.rs, mempool/src/shared_mempool/coordinator.rs, mempool/src/tests/mocks.rs, mempool/src/tests/node.rs, mempool/src/tests/test_framework.rs, network/benchmark/src/lib.rs, network/builder/src/builder.rs, network/builder/src/dummy.rs, network/framework/Cargo.toml, network/framework/src/application/storage.rs, network/framework/src/application/tests.rs, network/framework/src/connectivity_manager/mod.rs, network/framework/src/connectivity_manager/test.rs, network/framework/src/peer_manager/builder.rs, network/framework/src/peer_manager/conn_notifs_channel.rs, network/framework/src/peer_manager/mod.rs, network/framework/src/peer_manager/tests.rs, network/framework/src/peer_manager/types.rs, network/framework/src/protocols/health_checker/interface.rs, network/framework/src/protocols/health_checker/mod.rs, network/framework/src/protocols/health_checker/test.rs, network/framework/src/protocols/network/mod.rs, network/framework/src/testutils/test_node.rs, peer-monitoring-service/server/src/tests.rs, state-sync/storage-service/server/src/tests/mock.rs
This reverts commit f5de7609d50860e42b4b2dcd72e968cd6c57071e.
=> [cherrypick][1.13] Revert "Event simplification conn subs (#12730)"

Cargo.lock, aptos-move/aptos-transactional-test-harness/Cargo.toml, aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/bad_parameter.exp, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/bad_parameter.move, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/diamond_clicker.exp, aptos-move/aptos-transactional-test-harness/tests/tests.rs, aptos-move/aptos-transactional-test-harness/tests/v2-tests/bad_parameter.exp, aptos-move/aptos-transactional-test-harness/tests/v2-tests/bad_parameter.move, aptos-move/framework/src/extended_checks.rs, third_party/move/move-compiler/src/shared/mod.rs, third_party/move/testing-infra/transactional-test-runner/src/framework.rs, third_party/move/testing-infra/transactional-test-runner/src/vm_test_harness.rs
Run `extended_checks` as part of the `aptos-transactional-test-harness`.
Fixes #13297.
To run `extended_checks` we need a model (`GlobalEnv`) to be generated
by compilation.  For Compiler V2 this is pretty straightforward, as we
just have to enable the `"attach-compiled-module"` experiment.  For
Compiler V1, the compilation entry point currently used by the test
framework doesn't generate a model as part of compilation, and reusing
the process used in `BuiltPackage::build()` (defined in
`aptos-move/framework/src/build_package.rs`) is overly complex.
So instead, we follow the process that was used in
`CompiledPackage::build_all()` (defined in
`third_party/move/tools/move-package/src/compilation/compiled_package.rs`)
to build a model under compiler V1, needed for ABIs or Docgen with …
=> add extended_checks to aptos-transactional-test-harness

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml
This bumps the CLI version to 3.3.1, so that we can make another CLI release to fix local simulation and gas profiling.
Manually ran replay command
```
cargo run -p aptos -- move replay --network testnet --txn-id 1199201215
```
N/A
=> [cli] bump version to 3.3.1

testsuite/forge-cli/src/main.rs
The haproxy test runs in a completely different network topology (effectively all close to each other). It doesn't seem to make sense to have detailed thresholds in this environment, and to spend time investigating threshold violations.
Run forge.
=> [forge] remove latency breakdown thresholds from haproxy test

Cargo.lock, crates/aptos-debugger/Cargo.toml, crates/aptos-debugger/src/main.rs, storage/aptosdb/Cargo.toml, storage/aptosdb/src/db_debugger/common/mod.rs, storage/aptosdb/src/db_debugger/mod.rs, storage/aptosdb/src/db_debugger/state_kv/get_value.rs, storage/aptosdb/src/db_debugger/state_kv/mod.rs, storage/aptosdb/src/db_debugger/state_kv/scan_snapshot.rs, storage/aptosdb/src/db_debugger/state_tree/get_leaf.rs, storage/aptosdb/src/db_debugger/state_tree/get_path.rs, storage/aptosdb/src/db_debugger/state_tree/mod.rs
get-leaf to return leaf info for given snapshot version and leaf index
get-value to query the kv table by key
scan-snapshot to go through a state snapshot
manual runs
=> db-debugger: new commands

storage/schemadb/src/iterator.rs
Meaning, do not advance underlying raw iter early
Sometimes the second advance on the state value CF is exetremely costly
due to deletions by the pruner.
Fixed issue where point-getting a state value can be extremely slow if the value gets historically updated a lot and stayed untouched within the ledger pruning window.
unit tests
=> schemadb: make iterator lazy

config/src/config/quorum_store_config.rs
Make the max constraint in quorum store backpressure larger.
Forge stable tests look fine: https://github.com/aptos-labs/aptos-core/actions/runs/9178126508
=> [quorum store] increase max per-validator TPS constraint from 2K to 4K

third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs, third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/factor_invalid_2.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/factor_invalid_2.move, third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/factor_invalid_2.no-opt.exp
Fixes #12781
This also refactors and simplifies the releasing of references before write operations. I initially thought this was the problem but it wasn't, anyway the refactoring simplifies the code a bit.
New baseline test
=> [compiler v2] Emulating some unexpected v1 borrow behavior

ecosystem/indexer-grpc/indexer-grpc-server-framework/src/lib.rs
This will change emitted logs from:
`{ .... fields: { foo: "bar", bla: "baz" } }`
to
`{ foo: "bar", bla: "baz" }`
i.e. it will put all "fields" emitted into the root of the json object. We do more or less the same in api-gateway and kind of the rest of aptos-core which makes querying emitted logs a bit easier/intuitive as you don't need to prefix every single query field with `fields.` when querying.
If we have any humio dashboards that use `fields.` in their query, they probably need adjustment.
=> flatten json log fields in indexer logs.

config/src/config/quorum_store_config.rs
Make the max constraint in quorum store backpressure larger.
=> [cherry-pick][1.12] [quorum store] increase max per-validator TPS constraint from 2K to 4K (#13362)

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
There have been 2 performance improvements to keyless TXN verification times:
1. Caching the deserialized VK in the VM (https://github.com/aptos-labs/aptos-core/pull/12975), which lowered the time from 5ms to 3.10 ms
2. Faster Poseidon hashing (https://github.com/aptos-labs/aptos-core/pull/13050), which lowered the gas from 3.10ms to 1.66ms
Overall, this is a ~3x reduction in gas costs and should be reflected in how we charge for keyless TXNs.
It has not. @vgao1996 do we need to bump up gas versions?
1. Do we need to bump up gas version?
2. Do we need feature gating?
=> Lower gas for keyless TXNs by 3x in transaction.rs

ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/in_memory_cache.rs
For the data service, Instead of returning an error when not specifying a starting version, we just start from the latest transaction (live mode). We get the latest version from the in-memory cache. 
Data is live!
=> [Indexer gRPC] Data Service Live Mode

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs, aptos-move/aptos-release-builder/data/keyless.yaml
Cherry-picking https://github.com/aptos-labs/aptos-core/pull/13397 onto v1.12.
=> Cherry pick lower gas for keyless TXNs by 3x in transaction.rs (#13397)

config/src/config/quorum_store_config.rs
Make the max constraint in quorum store backpressure larger.
=> [cherry-pick][1.13] [quorum store] increase max per-validator TPS constraint from 2K to 4K (#13362)

aptos-move/move-examples/raffle/sources/raffle.move, aptos-move/move-examples/tests/move_unit_tests.rs
The `raffle` example for [AIP-41](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-41.md) used `smart_vector::borrow(&v, i)` when selecting the winner. The problem is this function has variable gas cost based on `i`, which creates an undergasing attack vector that can bias the distribution of winners..
This PR fixes it by switching to `vector`.
```
cd aptos-move/move-examples
cargo test -- raffle --nocapture
```
Are there any other attack vectors?
=> update raffle example to fix undergasing

Cargo.lock, Cargo.toml, crates/aptos-jwk-consensus/Cargo.toml, crates/aptos-jwk-consensus/src/jwk_manager/mod.rs, crates/aptos-jwk-consensus/src/jwk_observer.rs, crates/jwk-utils/Cargo.toml, crates/jwk-utils/src/lib.rs, keyless/pepper/service/src/main.rs, testsuite/smoke-test/src/aptos_cli/validator.rs, testsuite/smoke-test/src/jwks/dummy_provider/mod.rs, testsuite/smoke-test/src/jwks/jwk_consensus_basic.rs, testsuite/smoke-test/src/jwks/jwk_consensus_per_issuer.rs, testsuite/smoke-test/src/jwks/jwk_consensus_provider_change_mind.rs
- Pull some shared JWK logic out into a crate and make it a dependency of pepper service and jwk-consensus.
- Start fetching apple jwks in pepper service.
=> jwk updates

aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/bad_parameter.exp, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/bad_parameter.v2_exp, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/randomness_safety.v2_exp, aptos-move/aptos-transactional-test-harness/tests/v2-tests/bad_parameter.exp, aptos-move/framework/src/extended_checks.rs
Clean up error messages about `#[view]` function parameters.
See #13242 for old error messages.
New test output looks like:
```
error: `#[view]` function must return values
┌─ /var/folders/hx/_s_6fyh529bgmvl6z4m8m9fm0000gn/T/.tmpTfNXod/sources/m.move:4:17
│
4 │             fun view(_value: u64) { }
│                 ^^^^
test tests::attributes::test_view_attribute_on_non_view - should panic ... ok
test tests::attributes::test_view_attribute ... ok
BUILDING Package
error: type `&mut signer` is not supported as a transaction parameter type
┌─ /var/folders/hx/_s_6fyh529bgmvl6z4m8m9fm0000gn/T/.tmpFo5Hs8/sources/m.move:4:22
│
4 │             fun view(_:&mut signer,value: u64): u64 { value }
│                      ^
test tests::aggregator_v2_events::test_events_with_snapshots_not_emitted_on_abor …
```
=> Fix #13242 by cleaning up error messages about `#[view]` function parameters

docker/builder/tools.Dockerfile
The backup tool has switched from the deprecated `gsutil` CLI to `gcloud storage`.
=> Install Google Cloud SDK in the tools image

ecosystem/indexer-grpc/indexer-grpc-data-service/src/metrics.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs
In https://github.com/aptos-labs/aptos-core/pull/12547 I migrated the data service metrics to use identifier. Well, it turns out it's handy to have email and friends, so this PR adds back a header for email! It also adds things like the application name.
Run data service:
```
cargo run -p aptos-indexer-grpc-data-service -- -c /tmp/config.yaml
```
With this config:
```
health_check_port: 8184
server_config:
file_store_config:
file_store_type: "LocalFileStore"
local_file_store_path: /tmp/localfilestore
redis_read_replica_address: redis://127.0.0.1:10001
enable_cache_compression: true
whitelisted_auth_tokens: []
disable_auth_check: true
data_service_grpc_non_tls_config:
data_service_grpc_listen_address: 0.0.0.0:50051
```
Connect with the relevant headers set:
```
docker run …
```
=> [data service] Include email and application name in metrics

Cargo.lock, consensus/consensus-types/Cargo.toml, consensus/consensus-types/src/pipeline/commit_decision.rs, consensus/consensus-types/src/sync_info.rs, consensus/src/block_storage/block_store.rs, consensus/src/block_storage/block_store_test.rs, consensus/src/block_storage/sync_manager.rs, consensus/src/round_manager.rs, testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs
Cherry-pick a fix for an issue that a malicious node can use ordered cert as commit cert to panic other validators because we assert if the execution result is different from the cert (ordered cert has dummy values)
=> [consensus] add missing checks for commit cert

aptos-move/aptos-aggregator/src/delayed_field_extension.rs, aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs, aptos-move/aptos-gas-schedule/src/ver.rs, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/e2e-move-tests/proptest-regressions/tests/aggregator_v2.txt, aptos-move/e2e-move-tests/src/aggregator_v2.rs, aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/sources/aggregator_v2_test.move, aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs, aptos-move/framework/aptos-framework/doc/aggregator_v2.md, aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.move, aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.spec.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs, types/src/on_chain_config/aptos_features.rs
We can have an efficient aggregator_v2::is_at_least call (and is cheaper than equivalent try_sub() + add() calls), which can then be used to check for minimal balance, or other things.
we don't need really is_at_most(value), as that is really equivalent to !is_at_least(value + 1).
Adding also constructors with value, for now just as move utility, we can see if we want to make them a single native call (instead of currently two). but creation of aggregators is much less frequent, so should be fine.
=> Add aggregator_v2::is_at_least API

docker/builder/tools.Dockerfile
The backup tool has switched from the deprecated `gsutil` CLI to `gcloud storage`.
=> Cherry pick Install Google Cloud CLI in the tools image

aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move
The feature flag `max_object_nesting_check` was used to fix a bug safely. Now that it has been enabled on the testnet and the mainnet successfully, this PR cleans it up to save gas at runtime.
It's a straight-forward change.
=> [Framework] Clean up the feature flag `max_object_nesting_check`

.github/workflows/coverage-move-only.yaml, .github/workflows/coverage.yaml
Local tests + tests on this PR
N/A
=> (fix) Reorder the parameters and adapt them to Nextest.

crates/aptos/e2e/main.py
These tests are too flaky due to this reconfiguration + simulation problem ([here](https://github.com/aptos-labs/aptos-core/actions/runs/9280793012/job/25564873884) is an instance of it happening, look for `Move abort in 0x1::stake: ERECONFIGURATION_IN_PROGRESS(0x30014): Validator set change temporarily disabled because of in-progress reconfiguration`). Theoretically https://github.com/aptos-labs/aptos-core/pull/13389 is able to fix it if applied properly (e.g. waiting for reconfiguration in all the necessary places) but unfortunately CLI is understaffed and no one has time to investigate this properly. So let's just disable the staking tests.
See CI. All tests pass, and quickly.
N/A
=> [CLI][E2E] Disable staking tests

Cargo.lock, mempool/Cargo.toml, mempool/src/shared_mempool/tasks.rs
The validation of transaction itself is pretty expensive, so its okay to split the parallel iterator up to size 1. The overhead of splitting should not outweigh the actual work done in this case.
=> [Mempool] Tune validation parallelism

third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs, third_party/move/move-compiler-v2/tests/reference-safety/call_access_invalid.exp, third_party/move/move-compiler-v2/tests/reference-safety/call_access_invalid.move, third_party/move/move-compiler-v2/tests/reference-safety/call_access_invalid.no-opt.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_acquires_invalid.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_acquires_invalid.no-opt.exp, third_party/move/move-compiler-v2/tests/testsuite.rs, third_party/move/move-model/src/ast.rs
Closes #13146
Adds a check that a global resource is not borrowed when it is declared in the access specifier list of a function.
This implements the full semantics of Move 2.0 access specifiers. However, if the 2.0 language is not enabled, access specifiers other then `acquires` will be rejected by the context checker, and for that special case the behavior is equivalent.
In order to test the extended access specifier semantics, we need to disable the existing acquires checker, which is not yet implemented for general access specifiers.
Existing failing test now works plus new tests
=> [compiler-v2] Add access specifier check to reference safety

aptos-move/framework/aptos-framework/doc/aptos_governance.md, aptos-move/framework/aptos-framework/sources/aptos_governance.move, aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
This PR adds batch voting functionalities for Aptos governance so voters can vote with multiple stake pools in a single transaction.
Unit tests
=> feat: Batch Vote Func

aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move
This prevents original owner from reclaiming the "burnt" object after transfer_with_ref takes effect
Unit tests
=> Cherrypick PR#13495 into v1.13

aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move
This prevents original owner from reclaiming the "burnt" object after transfer_with_ref takes effect
Unit tests
=> Cherrypick PR#13495 into v1.14

aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move
This prevents original owner from reclaiming the "burnt" object after transfer_with_ref takes effect
Unit tests
=> [Aptos Framework][Object] Update transfer_with_ref to remove tombstone if present

aptos-move/framework/src/extended_checks.rs
To allow Move developers to indicate to formatting tools that they should skip formatting a particular piece of code, we are adding the `#[fmt::skip]` attribute to the known list of attributes.
=> [minor] Adding `fmt::skip` attribute to the known list of attributes

Cargo.lock, testsuite/forge/src/backend/k8s/chaos.rs, testsuite/forge/src/backend/k8s/chaos/netem.yaml, testsuite/forge/src/backend/k8s/helm-values/aptos-node-default-values.yaml, testsuite/forge/src/backend/k8s/node.rs, testsuite/forge/src/backend/local/node.rs, testsuite/forge/src/interface/node.rs, testsuite/testcases/src/multi_region_network_test.rs, testsuite/testcases/src/network_bandwidth_test.rs, testsuite/testcases/src/network_loss_test.rs, testsuite/testcases/src/network_partition_test.rs, testsuite/testcases/src/three_region_simulation_test.rs
It turns out, network chaos is only applied based on the source and destination pod IPs, however, we use k8s services in Forge cluster, which resolve to service IPs that are different from pod IPs. In order to support them, this PR extends the targets to include the service IPs. To do so, it leverages the `externalTargets` field which can either be domains or IP address and populates them with the service domains of the stateful sets. 
`externalTargets` are only supported with `to` direction, so it splits the chaos with `both` direction into two each with `to` direction.
Also, fixes a bug where we applied the RTT delay in each direction instead of dividing it.
On Forge
=> [forge] fix chaos-mesh injection direction

api/src/tests/transactions_test.rs, api/src/transactions.rs, types/src/transaction/mod.rs
we try to get the detail error from VM status directly, the detail error in txn output may be lost after feature turned on
Added new test cover simulation API detail error info
=> Fix the simulation API not showing detail error info

third_party/move/move-examples/experimental/defi/Move.toml, third_party/move/move-examples/experimental/defi/README.md, third_party/move/move-examples/experimental/defi/sources/reserve.move, third_party/move/move-examples/experimental/defi/sources/uniswap.move
- Created two DeFi examples, revamping the previous rounding error examples
- One is a simple dex pool based on Uniswap V1
- Another is a simple reserve-backed currency system
- Defined the safety properties for the examples, and proved them with Move Prover
=> [Prover] Added DeFi examples

crates/aptos/src/node/analyze/analyze_validators.rs, crates/aptos/src/node/mod.rs
`cargo run -p aptos -- node analyze-validator-performance --analyze-mode max-tps `
=> Add max-tps option to aptos node analyze-validator-performance cli

aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.move, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/framework/aptos-framework/sources/transaction_context.move, aptos-move/framework/aptos-framework/tests/simple_dispatchable_token_fa_tests.move, aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/collection.move, aptos-move/framework/aptos-token-objects/sources/token.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/move-examples/rewards_pool/sources/tests/test_helpers.move, aptos-move/move-examples/token_objects/guild/sources/guild.move
Those two features will not be reverted.
If there is any issue with the aggregators, feature that controls the fallback will be used, but API will still work.
This simplifies the complicated nested if conditions in collection.move and token.move
=> Cleanup after aggregator_v2_api and concurrent token features

aptos-move/framework/aptos-framework/doc/keyless_account.md, aptos-move/framework/aptos-framework/sources/keyless_account.move
=> skip bn254 verification in vk update in main

aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/token.move
Add collection creator assertion prior to token creation.
Unit tests for all token creation functions taking in the `Object<Collection>` have been verified that assertions throw.
=> Assert collection creator prior to token creation

consensus/consensus-types/src/wrapped_ledger_info.rs
=> trivial: fix build warning when fuzzing feature is not enabled

docker/builder/tools.Dockerfile
pigz compresses much faster than gzip and the format is compatible.
=> install pigz in tools image

third_party/move/move-compiler-v2/tests/checking/naming/warning_dependency.exp, third_party/move/move-compiler-v2/tests/checking/naming/warning_dependency.move, third_party/move/move-model/src/model.rs
This PR closes #13193 by printing out a diagnosis only when it is from a primary module or it is an error.
2) Added a new test `warning_dependency` of which the exp file does not contain warnings from the module it depends.
The logic added to filter out diagnoses which are not an error and not raised from primary modules.
=> [Compiler-v2] Generate compiler warnings for primary modules only

crates/aptos-crypto/src/secp256r1_ecdsa/secp256r1_ecdsa_sigs.rs, crates/aptos-crypto/src/unit_tests/secp256r1_ecdsa_test.rs
The function `check_s_lt_order_half` is intended to ensure that the value of S in an ECDSA signature is less than the order of the Secp256r1 curve divided by 2 to eliminate signature malleability. However, there's a boundary condition issue in the function's return logic.
At the end of the function, the return value is set to false when `S == ORDER_HALF`. This decision seems incorrect. To eliminate ECDSA signature malleability, S is required to be less than `n/2`, where n is the curve order. Since the curve's order is a prime number and cannot be divided by 2 evenly, `ORDER_HALF` effectively represents the `floor(n/2)`. Therefore, `ORDER_HALF` should be considered a valid S value, and its corresponding invalid S would be `ORDER_HALF + 1`. This boundary value consideration aligns with the …
=> fix:Correct ECDSA signature malleability handling

ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs, ecosystem/indexer-grpc/indexer-grpc-in-memory-cache-benchmark/src/main.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/in_memory_cache.rs
We want to be able to tune the value of the in memory cache for data service. This PR adds support for that.
For now, just see that the existing tests pass:
```
cd ecosystem/indexer-grpc/indexer-grpc-utils/
cargo test
```
Make sure I'm not missing any spot we might need to change.
=> [data service] Add support for configuring in memory cache size

aptos-move/aptos-release-builder/data/coin_to_fa_migration.yaml, aptos-move/aptos-release-builder/data/proposals/create_apt_mapping.move
=> [testnet] migration proposal

crates/aptos-metrics-core/src/lib.rs, storage/backup/backup-service/src/handlers/utils.rs
Looks like hyper::body::Sender::send_data() waits for the ack in place without buffering, that could be the reason why our backup speed is so dependent on network latency.  Upgrading hyper is non-trivial (warp depends on the old version), so I did some manual buffering. 
Doubles the throughput.
Existing unit tests (commenting out flush_buffer(), for example, does fail the tests)
patched testnet pfn0
=> backup service send in batch

aptos-move/aptos-vm/src/aptos_vm.rs
get_resource already returns PartialVMError, with appropriate exception - whether speculative error, storage error, etc.
not all of those are invariant violations. 
I forgot is this the way to convert PartialVMError to VMError (via `finish()`), or should I use `into()` or something else?
Failures here should never happen on transactions to be committed on-chain (and replay verify should confirm that), so change in logic here is fine.
There are speculative transactions (that will later be invalidated) where this might fail, and fix here avoids error logs, and allows BlockSTM to handle them correctly.
=> Propagate resolver errors, instead of transforming into invariant error

.github/workflows/forge-stable.yaml, .github/workflows/forge-unstable.yaml
=> [forge] move haproxy test to unstable

Cargo.lock, consensus/consensus-types/src/wrapped_ledger_info.rs, storage/backup/backup-cli/Cargo.toml, storage/backup/backup-cli/src/backup_types/state_snapshot/backup.rs, storage/backup/backup-cli/src/metrics/backup.rs
in the StateSnapshotBackupController, make receiving data from the server and uploading files to cloud storage pipelined.
performance is only slightly up because this is not currently the bottleneck.
unit and integration tests.
manually deployed on testnet.
=> db-backup: state snapshot backup pipelined

crates/aptos-genesis/src/test_utils.rs, execution/executor-benchmark/src/db_generator.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, types/src/on_chain_config/aptos_features.rs
While running exe benchmark, adds instrumentation to override 'on-chain' config.
A unit test in [aptos-core/types/src/on_chain_config/aptos_features.rs](https://github.com/aptos-labs/aptos-core/blob/8ddb8453d44e1d0f56e6fd61cee785e705b0f229/types/src/on_chain_config/aptos_features.rs#L83)
and
cargo run --profile performance -p aptos-executor-benchmark -- --generate-then-execute run-executor --enable-feature CODE_DEPENDENCY_CHECK MULTI_ED25519_PK_VALIDATE_V2_NATIVES --disable-feature CODE_DEPENDENCY_CHECK --data-dir ~/workspace/db_dirs/db/ --checkpoint-dir ~/workspace/db_dirs/chk --blocks 50 --main-signer-accounts 100001
=> [Executor Benchmark] Instrumentation to override 'on-chain' config (#13378)

config/src/config/mempool_config.rs, mempool/src/core_mempool/index.rs, mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/shared_mempool/network.rs, mempool/src/tests/core_mempool_test.rs, mempool/src/tests/shared_mempool_test.rs, testsuite/forge-cli/src/main.rs
This reduces the number of duplicate transactions due to PFN duplication. In most cases, the upstream VFN will have already seen the txn via the primary VFN's quorum store batch.
Ran PFN performance and see ~1K TPS reduction in duplicates (to < 100 TPS)
Added unit test.
=> [mempool] add a delay when broadcasting txns to failover nodes

consensus/src/round_manager.rs
We've seen `VerifyError { inner: Vote Round should be higher than SyncInfo }` in forge tests. This happens when a validator receives votes and order votes for a round before getting proposal for the round. In this case, the validator has processed the ordered cert before receiving proposal for the round. 
In a regular case, QC for round r is inserted before inserting Ordered cert for round r. But in the above case, it's possible that we call `RoundManager::new_ordered_cert` on round r even before the QC for round r is inserted. In such a case, the `RoundManager::new_ordered_cert` will first insert the QC for round r. But we are not calling the `process_certificates` to increment the round number after this operation. When the validator later gets proposal for round r, the validator will …
=> Fix the VerifyError in forge tests

consensus/src/block_preparer.rs, consensus/src/pipeline/buffer_manager.rs, testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs
Today when execution returns error e.g. CouldNotGetData, the whole pipeline has much worse performance by falling back to schedule block one by one and each schedule is delayed for 100ms.
This commit changes the reschedule for the whole suffix.
=> [pipeline] better retry for execution error

.github/workflows/docker-build-test.yaml
The workflow is currently using `targetCacheId` which resolves to "pr-\<number\>", leading to the reuse of the Kubernetes namespace if it was left from a previous run, and that fails the test.
=> Use BRANCH_HASH for Docker build Forge namespaces

.github/workflows/docker-build-test.yaml
Reverts aptos-labs/aptos-core#13660
=> Revert "Use BRANCH_HASH for Docker build Forge namespaces"

Cargo.lock, api/src/context.rs, aptos-move/aptos-release-builder/Cargo.toml, aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/gas.rs, aptos-move/aptos-release-builder/src/components/mod.rs, aptos-move/aptos-release-builder/src/main.rs, aptos-move/aptos-release-builder/src/validate.rs, aptos-move/aptos-vm/src/gas.rs, aptos-move/e2e-move-tests/Cargo.toml, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/gas.rs, aptos-move/framework/aptos-framework/doc/gas_schedule.md, aptos-move/framework/aptos-framework/sources/configs/gas_schedule.move, aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.spec.move, testsuite/smoke-test/src/rosetta.rs, testsuite/smoke-test/src/upgrade.rs, types/src/on_chain_config/gas_schedule.rs, types/src/on_chain_config/mod.rs
This introduces some major improvements to the gas schedule upgrade process
- New `gas_schedule::set_for_next_epoch_check_hash` interface to help establish a known base for upgrades, preventing unintended changes.
- New release builder command `generate-gas-schedule` to create a snapshot of the gas schedule based on the values defined in Rust, stored to a json file.
- Consolidated the various gas related release entries (`DefaultGas`, `DefaultGasWithOverride` etc.) into a single one named `Gas` for clarity.
- This has two fields: `old` and `new'. Valid values are `<url to remote gas schedule file>`, `<path to local gas schedule file>` or `current` (using the Rust-defined values).
- `new` is required but `old` is optional. It however not recommended you skip `old` for a real release. It's …
=> [gas] generate delta when upgrading the gas schedule

aptos-move/framework/aptos-framework/doc/primary_fungible_store.md, aptos-move/framework/aptos-framework/sources/primary_fungible_store.move, aptos-move/move-examples/fungible_asset/stablecoin/sources/usdk.move
Add public inline functions for the existing view functions in the module. This enables calls to pfs in deposit/withdraw hooks and avoids circular dependencies. 
Change `assert_not_denylisted` to use PFS `priamary_store_exists_inlined`. 
user calls `pfs::withdraw` -> withdraw hook -> `assert_not_denylisted` -> `pfs::primary_store exists_inlined`
Unit Tests
=> stablecoin deposit/withdraw hook fix

api/src/tests/multisig_transactions_test.rs, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/errors.rs, aptos-move/aptos-vm/src/transaction_validation.rs, aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/sources/multisig_account.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/framework/move-stdlib/sources/configs/features.spec.move, third_party/move/move-core/types/src/vm_status.rs, types/src/on_chain_config/aptos_features.rs
This PR update the `validate_multisig_transaction ` function, so that the multisig transaction fails if the provided payload does not match to the onchain payload. This fixes https://github.com/aptos-labs/aptos-core/issues/12929.
Tested on the localnet
Added API tests
=> [Multisig V2] Aborts the multisig transaction if the provided payload does not match the payload stored onchain

testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs
Previously we only take rounds into considerations and tests can become flaky when the epoch advances and we don't see rounds increase. for example if it advances from (1, 10) to (2, 8), it actually makes progress of at least 8 rounds but the check would fail with 0 rounds.
=> [smoke-test] better success criteria

testsuite/smoke-test/src/genesis.rs, testsuite/smoke-test/src/randomness/randomness_stall_recovery.rs
Current fault in `process_ready_blocks()` sometimes won't work: it's possible that the 1st faulty validator gets stuck starting block `i` while the other 3 unaffected validators moved forward with seed in `B`, in which case the 1st validator will later not able to commit block `i`.
n/a
It's a test.
n/a
=> fix randomness_stall_recovery flakiness

api/goldens/aptos_api__tests__secp256k1_ecdsa__test_multi_secp256k1_ecdsa.json, api/goldens/aptos_api__tests__secp256k1_ecdsa__test_secp256k1_ecdsa.json, api/src/tests/secp256k1_ecdsa.rs, api/src/transactions.rs, api/types/src/convert.rs, api/types/src/transaction.rs, ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs, types/src/transaction/mod.rs
Poem's display functionality is a bit limiting and doesn't seem to handle printing enums effectively, so one needs to leverage a wrapping struct to effectively display a type and value field.
This PR introduces just that.
This means that anyone parsing single or multi key sender json output will be broken, of course, the data was largely useless to begin with.
Other aspects remain untouched so this is a minimally breaking changes PR.
Check the embedded golden files.
Singlekey:
```
{
"public_key": {
"value": "0x049b8327d929a0e45285c04d19c9fffbee065c266b701972922d807228120e43f34ad68ac77f6ec0205fe39f7c5b6055dad973a03464a3a743302de0feaf6ec6d9",
"type": "secp256k1_ecdsa"
},
"signature": {
"value": "0x357a77abdb3ef4a01aea1e8d0cb932606655bcf66e6726d2cefbfd904d57703b0bf38eb19bc3da1e3e9f6929db0d480 …
```
=> [api] print SingleSender signature / key variants

testsuite/forge/src/test_utils/consensus_utils.rs
Right now if we have
All at epochs: [3, 3, 3, 3], from [3, 2, 3, 2]
All at rounds: [9, 9, 9, 9], from [1, 10, 1, 10]
it'll report 0 epochs and 0 round, because it uses current max epoch/round - previous max epoch/round, which is 3 - 3, 9 - 10.
this commit updates it to look at maximum of (epoch, round) and compare, in this case (3, 9) - (3, 1) = (0, 8)
=> [smoke-test] further enhance progress metrics

Cargo.lock, consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_network_test.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/network.rs, consensus/src/network_interface.rs, consensus/src/pipeline/buffer_manager.rs, consensus/src/pipeline/commit_reliable_broadcast.rs, consensus/src/rand/rand_gen/rand_manager.rs, crates/aptos-jwk-consensus/src/epoch_manager.rs, crates/aptos-jwk-consensus/src/network.rs, crates/aptos-jwk-consensus/src/network_interface.rs, crates/aptos-jwk-consensus/src/update_certifier.rs, crates/reliable-broadcast/Cargo.toml, crates/reliable-broadcast/src/lib.rs, crates/reliable-broadcast/src/tests.rs, dkg/src/agg_trx_producer.rs, dkg/src/epoch_manager.rs, dkg/src/network.rs, dkg/src/network_interface.rs, network/framework/src/application/interface.rs, network/framework/src/application/tests.rs, network/framework/src/protocols/network/mod.rs
This PR separates RPC sending from serialization by introducing two methods on `NetworkClient`: `send_rpc_raw` and `to_bytes`. The intent is to prevent serialization `N` times for Reliable Broadcast. Reliable Broadcast uses this to serialize once and send to many peers.
`send_rpc_raw` takes in Bytes as an argument instead of an actual message.
`to_bytes` takes in a message struct and returns Bytes. It serializes based on Peer Protocol.
`send_rpc_to_self` takes in the message struct, because self messages don't have to be serialized.
=> [network][reliable-broadcast] separate RPC sending from serialization for efficiency

Cargo.lock, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_network_test.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/network.rs, consensus/src/network_interface.rs, consensus/src/pipeline/commit_reliable_broadcast.rs, crates/aptos-jwk-consensus/src/network.rs, crates/aptos-jwk-consensus/src/network_interface.rs, crates/reliable-broadcast/src/lib.rs, crates/reliable-broadcast/src/tests.rs, dkg/src/network.rs, dkg/src/network_interface.rs, mempool/src/shared_mempool/priority.rs, network/framework/src/application/interface.rs, network/framework/src/application/metadata.rs, network/framework/src/application/storage.rs, network/framework/src/counters.rs, peer-monitoring-service/client/src/tests/utils.rs, peer-monitoring-service/server/src/lib.rs, state-sync/aptos-data-client/src/tests/utils.rs, state-sync/aptos-data-client/src/utils.rs
It seems beneficial to prioritize sending messages to distant peers first during a broadcast.
This PR introduces a method to `PeersAndMetadata` to sort peers by latency. 
- NetworkClient uses this sorting for `send_to_many` calls. 
- RBNetworkSender trait exposes a method to sort peers by latency for Reliable Broadcast RPCs.
- Removes cloning for `PeerMonitoringMetadata` in `PeerMetadata`, because the clone is expensive about 9 microseconds per clone with 100 validators.
=> [consensus] send to distant peers first on broadcast

.cargo/config.toml, Cargo.lock, Cargo.toml, ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs, ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/in_memory_cache.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs
As titled. Current deflate compression is slow and old. New compression is > 5x faster. This did require a fork of Tonic, for which I will submit a PR upstream.
=> [GRPC] Enable data service ZSTD and update crate that uses old tonic

consensus/safety-rules/src/safety_rules.rs
Add a check to verify epoch in order vote safety rules.
=> Check epoch in verify_order_vote_proposal

.github/actionlint.yaml, .github/workflows/cli-e2e-tests.yaml, .github/workflows/coverage-move-only.yaml, .github/workflows/coverage.yaml, .github/workflows/docker-build-rosetta.yaml, .github/workflows/faucet-tests-main.yaml, .github/workflows/faucet-tests-prod.yaml, .github/workflows/find-packages-with-undeclared-feature-dependencies.yaml, .github/workflows/indexer-grpc-integration-tests.yaml, .github/workflows/keyless-circuit-daily-test.yaml, .github/workflows/lint-test.yaml, .github/workflows/move-test-compiler-v2.yaml, .github/workflows/node-api-compatibility-tests.yaml, .github/workflows/prover-daily-test.yaml, .github/workflows/run-gas-calibration.yaml, .github/workflows/rust-client-tests.yaml, .github/workflows/ts-sdk-e2e-tests.yaml
This switches high-perf-docker (c2-standard-60) to roughly equivalent runs-on.com runners. Specifically AWS machines of the c7 family (runs-on has some heuristics to pick the cheapest spot instance in the c7 family that satisfies the CPU requirement of 64 CPUs).
Ran several tests a bunch of times. Compared performance to baseline PR (https://github.com/aptos-labs/aptos-core/pull/13698 ). Performance is roughly similar, usually a bit faster (5-15%), few times a bit slower (less than 5%).
Re spot preemption: Haven't seen a single spot preemption so far (added a log-based chart here https://aptoslabs.grafana.net/d/cb066e70-b378-4de7-aadb-79b43386e664/gha-self-hosted-runners?orgId=1&from=now-30d&to=now ).
Note: Some of the checks below are failing but to the best of my ability they are just …
=> switch high-perf-docker to runs-on.com runners

storage/aptosdb/src/backup/backup_handler.rs, storage/aptosdb/src/metrics.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/backup/backup-cli/src/backup_types/epoch_ending/tests.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/backup.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs, storage/backup/backup-cli/src/backup_types/tests.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, storage/backup/backup-cli/src/metrics/backup.rs, storage/backup/backup-cli/src/utils/backup_service_client.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/backup/backup-cli/src/utils/read_record_bytes.rs, storage/backup/backup-service/src/handlers/mod.rs, storage/backup/backup-service/src/handlers/utils.rs
Get state snapshot chunks in parallel, from the client side.
This keeps the server simple and low overhead (memory for buffering the chunks, for e.g.) while adding some concurrency to the snapshot taking process. The drawback is the server doesn't control the concurrency, it's not a big deal considering the backup service is deemed local only. 
With this testnet snapshot finishes within 2 hours.
unit tests.
deploying to testnet backup pfn.
=> db-backup: get state snapshot chunks in concurrency

scripts/dev_setup.sh
Update Node.js from version 18 to 20. The previous version is no longer available in the upstream Ubuntu repository.
=> dev_setup.sh: update Node.js version

testsuite/smoke-test/src/keyless.rs
Fix keyless test flakiness by explicitly specifying max gas.
n/a
n/a
n/a
=> fix keyless test flakiness

third_party/move/move-compiler/src/expansion/translate.rs, third_party/move/move-compiler/tests/move_check/expansion/assign_non_simple_name.exp, third_party/move/move-compiler/tests/move_check/expansion/use_nested_self_as_invalid.exp, third_party/move/move-compiler/tests/move_check/expansion/use_struct_overlap_with_module.exp
This makes the interpretation of `Foo::Bar` as enum variant dependent on that Move 2 is enabled, allowing older legacy code which uses captilized module names to succeed as long as used for the v1 language only.
Against Diem prover tests
=> [move-2] Fix CI breaking change in variant names in prover

Cargo.lock, devtools/aptos-cargo-cli/Cargo.toml, devtools/aptos-cargo-cli/src/common.rs, devtools/aptos-cargo-cli/src/lib.rs
This PR makes several small improvements to the target determinator logic in CI/CD. Specifically:
1. It improves the error message returned when metadata for an old commit (i.e., an old merge-base) cannot be fetched. In these cases, folks should simply rebase.
1. It adds a simple check to ensure that the merge-base is no greater than 7 days old. If so, the determinator will return an error telling folks to rebase.
1. It updates the target-determinator cargo options to include dev-dependencies. This helps to ensure that test-only crates are correctly handled (i.e., test-only crates will be marked as tainted if any of their dev-dependencies change). This should help to address a few edge-cases we've seen.
Existing test infrastructure and manual verification.
=> [Target Determinator] Small improvements to determinator logic.

crates/aptos/CHANGELOG.md, crates/aptos/src/account/balance.rs, crates/aptos/src/account/mod.rs
I did some user research, and realized `aptos account list --query balance` isn't exactly the easiest to find.  Instead it is now `aptos account balance`, with coin support.  Fungible asset can be added in the future.
Tested on devnet
```bash
./target/debug/aptos account balance --account 0xa550c18
{
"Result": [
{
"asset_type": "coin",
"coin_type": "0x1::aptos_coin::AptosCoin",
"balance": 18445820919974317715
}
]
}
```
=> [cli] Add balance command to make it easier to lookup balances

.github/workflows/docker-build-test.yaml, .github/workflows/forge-stable.yaml
=> bump forge version for 1.15 branch cut

Cargo.lock, Cargo.toml, ecosystem/indexer-grpc/transaction-filter/.gitattributes, ecosystem/indexer-grpc/transaction-filter/Cargo.toml, ecosystem/indexer-grpc/transaction-filter/README.md, ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_00008bc1d5adcf862d3967c1410001fb_705101000.pb.lz4, ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_0013c194ec4fdbfb8db7306170aac083_445907000.pb.lz4, ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_f3d880d9700c70d71fefe71aa9218aa9_301616000.pb.lz4, ecosystem/indexer-grpc/transaction-filter/src/boolean_transaction_filter.rs, ecosystem/indexer-grpc/transaction-filter/src/errors.rs, ecosystem/indexer-grpc/transaction-filter/src/filters/event.rs, ecosystem/indexer-grpc/transaction-filter/src/filters/mod.rs, ecosystem/indexer-grpc/transaction-filter/src/filters/move_module.rs, ecosystem/indexer-grpc/transaction-filter/src/filters/transaction_root.rs, ecosystem/indexer-grpc/transaction-filter/src/filters/user_transaction.rs, ecosystem/indexer-grpc/transaction-filter/src/lib.rs, ecosystem/indexer-grpc/transaction-filter/src/test_lib/mod.rs, ecosystem/indexer-grpc/transaction-filter/src/traits.rs
an MVP version of the transaction filtering crate, to performantly filter out API streams of transactions
This PR: https://github.com/aptos-labs/aptos-indexer-processors/pull/398 but in aptos-core as otherwise there are dependency issues
On a random 3mb proto of 1000txns during taptos, running the "everything" filter (looped) gives:
```
BENCH: Took 13.225167ms for 1000000 transactions (13ns each)
```
Random 10mb proto from April 25th with "everything" filter:
```
BENCH: Took 21.815375ms for 1000000 transactions (21ns each)
```
Graffio 100mb proto ("everything" filter, but with `or`): 
```
BENCH: Took 31.559333ms for 1000000 transactions (31ns each)
```
More advanced feature complete version here: https://github.com/aptos-labs/aptos-indexer-processors/pull/392
=> [GRPC] Simple Transaction Filtering

Cargo.lock, ecosystem/indexer-grpc/indexer-grpc-data-service/Cargo.toml, ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/metrics.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
There are two types of transaction filtering we will support in the future:
1. Per stream configuration: The downstream declares what txns they want to receive.
2. Global configuration: At the data service level we refuse to include full txns for all streams.
This PR implements the second of these, using @CapCap's work here:
~https://github.com/aptos-labs/aptos-indexer-processors/pull/398~ https://github.com/aptos-labs/aptos-core/pull/13715.
Rather than not sending txns at all if they match the blocklist filters, we just omit the writesets and events (and payload + signature, like we did with `sender_addresses_to_ignore`). Not sending the txns entirely would cause issues with processors, which today assume that they will receive all txns.
The txn filtering stuff is a superset of the …
=> [Data Service] Implement simple upstream transaction filtering

aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/bug_bbb75fa.v2_exp, third_party/move/evm/move-to-yul/src/functions.rs, third_party/move/move-compiler-v2/src/bytecode_generator.rs, third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs, third_party/move/move-compiler-v2/tests/ability-check/v1-signer/read_ref_transitive.exp, third_party/move/move-compiler-v2/tests/ability-check/v1-typing/assign_pop_resource.exp, third_party/move/move-compiler-v2/tests/ability-check/v1-typing/bind_pop_resource.exp, third_party/move/move-compiler-v2/tests/ability-transform/by_reference.exp, third_party/move/move-compiler-v2/tests/bytecode-generator/matching_ability_err.exp, third_party/move/move-compiler-v2/tests/bytecode-generator/matching_ability_err.move, third_party/move/move-compiler-v2/tests/bytecode-generator/matching_coverage_err.exp, third_party/move/move-compiler-v2/tests/bytecode-generator/matching_coverage_err.move, third_party/move/move-compiler-v2/tests/bytecode-generator/matching_ok.exp, third_party/move/move-compiler-v2/tests/bytecode-generator/matching_ok.move, third_party/move/move-compiler-v2/tests/bytecode-generator/wildcard6.exp, third_party/move/move-compiler-v2/tests/bytecode-generator/wildcard7.exp, third_party/move/move-compiler-v2/tests/bytecode-generator/wildcard8.exp, third_party/move/move-compiler-v2/tests/checking/variants/variants_ok.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/imm_borrow_on_mut_invalid.exp, third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/imm_borrow_on_mut_invalid.no-opt.exp, third_party/move/move-model/bytecode/src/stackless_bytecode.rs, third_party/move/move-model/src/ast.rs, third_party/move/move-model/src/model.rs, third_party/move/move-model/src/ty.rs, third_party/move/move-model/src/well_known.rs, third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
This implements the Move 2 `match` expression on stackless bytecode level. The PR consists of the following parts:
1. *Extending the Bytecode*
There are a few new bytecode operations:
```
dest := TestVariant(struct_id, variant, src)
dest := PackVariant(struct_id, variant, srcs)
dests := UnpackVariant(struct_id, variant, src)
dest := BorrowFieldVariant(struct_id, variant, field, src)
```
The `TestVariant` and `BorrowFieldVariant` operations  expect references to the variant struct. The `UnpackVariant` and `BorrowFieldVariant` operations abort if the `src` value is not a value of the given variant.
Notably, there are no new control flow operations, and the remaining part of the stackless bytecode framework should operate without changes. This may change in the future if we introduce a new …
=> [compiler-v2] Pattern matching for struct variants (aka enum types)

crates/aptos-genesis/src/builder.rs, storage/aptosdb/src/db_debugger/state_kv/scan_snapshot.rs, storage/aptosdb/src/db_debugger/truncate/mod.rs, storage/aptosdb/src/db_options.rs, storage/aptosdb/src/pruner/state_kv_pruner/state_kv_metadata_pruner.rs, storage/aptosdb/src/pruner/state_kv_pruner/state_kv_shard_pruner.rs, storage/aptosdb/src/pruner/state_merkle_pruner/test.rs, storage/aptosdb/src/rocksdb_property_reporter.rs, storage/aptosdb/src/schema/mod.rs, storage/aptosdb/src/state_kv_db.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/utils/iterators.rs, storage/aptosdb/src/utils/truncation_helper.rs, testsuite/replay_verify.py, testsuite/single_node_performance.py
StateValueIndex is removed from writing in this PR. 
backup and restore shouldn't be impacted 
https://github.com/aptos-labs/aptos-core/blob/populate_new_state_kv_schema/storage/aptosdb/src/state_store/mod.rs#L1049 
backup uses jmt get keys and then use state key to state store to get state value 
Existing test and spot check generated DBs
replay-verify with sharding mode on and no error except timeout
https://github.com/aptos-labs/aptos-core/actions/runs/9585888369
=> [sharded][3] use state value with key hash

aptos-node/src/consensus.rs, aptos-node/src/lib.rs, config/src/config/consensus_observer_config.rs, consensus/src/consensus_observer/logging.rs, consensus/src/consensus_observer/network_client.rs, consensus/src/consensus_observer/observer.rs, consensus/src/consensus_observer/publisher.rs, consensus/src/consensus_provider.rs, consensus/src/payload_manager.rs, consensus/src/pipeline/buffer_manager.rs, network/framework/src/application/interface.rs, network/framework/src/protocols/network/mod.rs, network/framework/src/protocols/wire/handshake/v1/mod.rs
This PR makes several changes to the network message flow for consensus observer. Specifically, it offers the following commits:
1. Add network compression to the direct send CO messages.
2. Add support for in-order message serialization for CO publisher. This helps to ensure that messages are not sent out-of-order (even if some take longer to serialize/compress than others).
3. Add support for explicitly unsubscribing from peers. We now send an unsubscribe request asynchronously when terminating a subscription.
=> [Consensus Observer] Improve message serialization ordering.

third_party/move/move-compiler-v2/tests/checking/typing/dummy_field.exp, third_party/move/move-compiler-v2/tests/checking/typing/dummy_field.move, third_party/move/move-compiler-v2/tests/checking/typing/dummy_field_err.exp, third_party/move/move-compiler-v2/tests/checking/typing/dummy_field_err.move, third_party/move/move-model/src/builder/exp_builder.rs, third_party/move/move-model/src/builder/model_builder.rs, third_party/move/move-model/src/builder/module_builder.rs
This PR adds a new bool field `is_empty_struct` to `StructEntry` to indicate whether the struct does not have any fields. With this field, 
- if a user defines a struct with the field `dummy_field`, packing and unpacking without any fields will raise an error;
- accessing `dummy_field` from an empty struct will raise an error.
close #13594 
2) Add a new test `dummy_field.move`. 
Whether the added logic will break how struct fields are generally checked.
=> [Compiler-v2] Check `dummy_field` in a struct

config/src/config/consensus_observer_config.rs, consensus/src/consensus_observer/error.rs, consensus/src/consensus_observer/metrics.rs, consensus/src/consensus_observer/network_client.rs, consensus/src/consensus_observer/network_events.rs, consensus/src/consensus_observer/network_message.rs, consensus/src/consensus_observer/observer.rs, consensus/src/consensus_observer/publisher.rs, consensus/src/consensus_observer/subscription.rs
This PR makes several small improvements to the consensus observer. Specifically, it offers the following commits:
1. Downgrade non-critical `info` logs to `debug`.
1. Add more metrics for subscription logic and errors.
1. Fix a race condition between the commit callback and the state sync process.
1. Remove several unnecessary `unwrap` calls.
1. Add more publisher metrics and clean up metric names.
1. Exclude the active subscribers from the potential peers list. This should help reduce the likelihood of subscription cycles (i.e., A subscribes to B, and B subscribes to A). Note, however, that even if a cycle occurs, the nodes will select new peers after being unable to make progress for a while.
1. Add simple tests for the consensus publisher.
=> [Consensus Observer] Feature improvements, bug fixes and new metrics/logs.

Cargo.lock, Cargo.toml, third_party/move/move-binary-format/Cargo.toml, third_party/move/move-binary-format/src/file_format.rs, third_party/move/move-bytecode-spec/Cargo.toml, third_party/move/move-bytecode-spec/src/lib.rs, third_party/move/move-bytecode-spec/tests/tests.rs, third_party/move/move-vm/runtime/src/interpreter.rs
This introduces a procedural macro `bytecode_spec` that allows us to add inline specifications to the Move bytecode instructions defined in Rust:
```rust
#[bytecode_spec]
pub enum Bytecode {
#[group = "stack_and_local"]
#[description = "Pop and discard the value at the top of the stack. The value on the stack must be an copyable type."]
#[semantics = "stack >> _"]
#[paranoid_post = r#"
ty_stack >> ty
assert ty has drop
"#]
Pop,
..
}
```
The macro will generate a `pub fn spec() -> Vec<BTreeMap<String, String>>`, which can be used to extract the specification defined using the the attributes. 
```json
[
{
"description": "Pop and discard the value at the top of the stack. The value on the stack must be an copyable type.",
"group": "stack_and_local",
"name": "pop",
"paranoid_post": "ty_stack …
```
=> [move] introduce bytecode specification

consensus/src/consensus_observer/observer.rs
This PR adds retries for sending `unsubscribe` messages to consensus observer when a previous message hasn't been processed correctly. This should help to fix some flaking smoke tests.
=> [Consensus Observer] Add unsubscribe retries to avoid flakes.

consensus/src/quorum_store/utils.rs
=> Calculate cur_txns in pull proofs method accurately

crates/aptos-crypto/src/secp256r1_ecdsa/secp256r1_ecdsa_sigs.rs, crates/aptos-crypto/src/unit_tests/secp256r1_ecdsa_test.rs
Reverting this change due to lack of feature gating, for now.
N/A.
N/A.
=> Revert "fix:Correct ECDSA signature malleability handling (#13544)"

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/keyless_validation.rs
Before this PR, if the VK was **unset**:
1. When ZK mode was _disabled_, our code would  return `TransactionStatus::Discard(StatusCode::INVALID_SIGNATURE)` when verifying keyless TXNs. 
- This is incorrect/unecessary, since the (lack of a) VK is irrelevant when  ZK mode is _disabled_. 
- More importantly, if the TXN had only ZK**less** signatures, this would incorrectly discard it!
3. When ZK mode was _enabled_ , our code would return `TransactionStatus::Discard(StatusCode::INVALID_SIGNATURE)`. This is incorrect when the TXN contains **only** ZK**less** signatures that are all valid.
After this PR, if the VK is **unset**:
1. When ZK mode is _disabled_,
a. If the TXN has one or more keyless ZK signatures, it returns `TransactionStatus::Discard(StatusCode::FEATURE_UNDER_GATING)`
b. …
=> move VK check into feature gating

aptos-move/block-executor/src/executor.rs
For small blocks, decrease the number of threads from concurrency level to the half block size,
mitigates overhead from thread initialization
=> reduce number of threads for small blocks

.github/workflows/forge-stable.yaml
`forge-stable.yaml` supports testing on a schedule multiple branches. Today we're only using it for the `main` branch though.
To support this, we need to uniquely identify each schedule/cron for each branch in the `determine-test-branch` step. This was missed in https://github.com/aptos-labs/aptos-core/commit/2bc9910c1821265c8e8708ffbc565e607995efd3, and results in `Unknown schedule`
CI on schedule
=> [gha] fix forge-stable main branch cadence check

.github/workflows/replay-verify.yaml
Only run test-replay for PRs with the `CICD:test-replay` label
* Make sure test-replay doesn't run for this PR
* Add the `CICD:test-replay` label
* Check if test-replay workflow runs
=> only run test-replay for PRs with label

consensus/src/pipeline/tests/buffer_manager_tests.rs, consensus/src/round_manager_test.rs, testsuite/smoke-test/src/consensus/consensusdb_recovery.rs
This PR disables several super flaky consensus tests. These are backing up CI/CD quite a bit.
```
aptos-consensus round_manager::round_manager_test::forking_retrieval_test
aptos-consensus pipeline::tests::buffer_manager_tests::buffer_manager_sync_test
smoke-test consensus::consensusdb_recovery::test_consensusdb_recovery
```
=> [Consensus] Ignore flaky tests.

Cargo.lock, aptos-move/aptos-debugger/Cargo.toml, aptos-move/aptos-debugger/src/aptos_debugger.rs, aptos-move/aptos-debugger/src/bcs_txn_decoder.rs, aptos-move/aptos-debugger/src/common.rs, aptos-move/aptos-debugger/src/execute_past_transactions.rs, aptos-move/aptos-debugger/src/execute_pending_block.rs, aptos-move/aptos-transaction-benchmarks/Cargo.toml, aptos-move/aptos-transaction-benchmarks/src/transaction_bench_state.rs, aptos-move/aptos-transaction-benchmarks/src/transactions.rs, aptos-move/aptos-validator-interface/src/lib.rs, aptos-move/aptos-vm-logging/src/log_schema.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/limit_processor.rs, aptos-move/e2e-tests/src/executor.rs, testsuite/smoke-test/src/aptos/mint_transfer.rs, types/src/state_store/mod.rs, types/src/transaction/mod.rs
being able to use:
--use-same-block-boundaries --concurrency-level=1 --concurrency-level=4 --concurrency-level=8 --concurrency-leve
l=16 --concurrency-level=32 --concurrency-level=48
and compare speeds as well.
=> Add speed comparison flags to remote debugger 

.github/actionlint.yaml, .github/workflows/cli-e2e-tests.yaml, .github/workflows/coverage-move-only.yaml, .github/workflows/coverage.yaml, .github/workflows/docker-build-rosetta.yaml, .github/workflows/faucet-tests-main.yaml, .github/workflows/faucet-tests-prod.yaml, .github/workflows/find-packages-with-undeclared-feature-dependencies.yaml, .github/workflows/indexer-grpc-integration-tests.yaml, .github/workflows/keyless-circuit-daily-test.yaml, .github/workflows/lint-test.yaml, .github/workflows/move-test-compiler-v2.yaml, .github/workflows/node-api-compatibility-tests.yaml, .github/workflows/prover-daily-test.yaml, .github/workflows/run-gas-calibration.yaml, .github/workflows/rust-client-tests.yaml, .github/workflows/ts-sdk-e2e-tests.yaml
Reintroducing runs-on runners as high-perf-docker replacement again. This is after flakyness issues that were observed last time have been resolved.
This time using AWS custom AMI build by @ibalajiarun .
=> Attempt #2: switch high-perf-docker to runs-on.com runners

aptos-move/aptos-release-builder/data/coin_to_fa_migration.yaml, aptos-move/aptos-release-builder/data/proposals/create_apt_mapping.move
=> FA migration proposal to release v1.14

third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs, third_party/move/move-compiler-v2/tests/checking/typing/v1-examples/multi_pool_money_market_token.exp, third_party/move/move-compiler-v2/tests/checking/typing/v1-examples/multi_pool_money_market_token.move, third_party/move/move-compiler-v2/tests/checking/typing/v1-examples/simple_money_market_token.exp, third_party/move/move-compiler-v2/tests/checking/typing/v1-examples/simple_money_market_token.move, third_party/move/move-compiler-v2/tests/v1.matched, third_party/move/move-compiler-v2/tests/v1.unmatched, third_party/move/move-compiler-v2/tools/testdiff/src/main.rs, third_party/move/move-model/src/builder/model_builder.rs, third_party/move/move-model/src/builder/module_builder.rs, third_party/move/move-model/src/model.rs
This PR closes #13758 by setting field_information as Native instead of Declared when the field count is 0 (which means it is a native struct).
2) migrate two tests from V1.
Since `dummy_field` is inserted for user defined empty structs during compilation, if the field count is 0, the struct is native. Need to guarantee that this reasoning is correct.
=> [Compiler-v2] Fix native struct

scripts/dev_setup.sh
Dotnet install step in `dev_setup.sh` will occasionally fail due to server returning 500 when fetching the install script: https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install
```
+ wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
--2024-07-01 15:49:39--  https://dot.net/v1/dotnet-install.sh
Resolving dot.net (dot.net)... 20.76.201.171, 20.112.250.133, 20.236.44.162, ...
Connecting to dot.net (dot.net)|20.76.201.171|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh [following]
--2024-07-01 15:49:39--  https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
Resolving dotnet.microsoft.com …
```
=> [dev_setup] retry flaky dotnet install

execution/executor-benchmark/src/ledger_update_stage.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/pipeline.rs, testsuite/single_node_performance.py
fix DETAILED=1 flag in single_node_performance.py (which runs across different concurrency levels)
and for that fix --skip-commit flag in the executor benchmark
run 
NUMBER_OF_EXECUTION_THREADS=32 DETAILED=1 FLOW=CONTINUOUS SKIP_MOVE_E2E=1 NUM_INIT_ACCOUNTS=10000 ./testsuite/single_node_performance.py
=> fix flag to compare concurrency levels in single node performance benchmark

consensus/src/quorum_store/utils.rs
Cherrypicking the commit from `main` branch to simplify the proof queue data structure.
=> Simplify proof queue data structure

api/src/basic.rs
Refactor the `/-/healthy` endpoint to use more explicit variable names, and a clearer error message.
=> Make healtch check failure clearer.

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/cluster.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-emitter-lib/src/wrappers.rs, sdk/src/transaction_builder.rs
Create generic bulk_create_accounts, that anyone can use, without having EmitterJobRequest params object.
(we use this later for creating worker accounts)
with end-to-end bulk submit script
=> Txn emitter changes for it to be used for bulk emitter script

ecosystem/indexer-grpc/indexer-grpc-utils/src/config.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator/gcs.rs
This allows a single GCS bucket to be shared by multiple instances of indexer GRPC (file store operator), each using a different subdirectory/namespace. With this, we can enable many ephemeral indexer GRPC service stacks running at a time, sharing a bucket. This is for Forge-like testing of indexer. Subdirectories can be pruned using bucket lifecycle policies, or backed up if needed
A new optional config `gcs_file_store_bucket_sub_dir` enables this functionality. Otherwise, no-op
Deploy ephemeral indexer stacks e2e
=> [indexer-grpc] filestore can use subdirectories

testsuite/forge-cli/src/main.rs, testsuite/forge/src/runner.rs
Long running Forge tests need larger disks for performance reasons (larger disks perform higher / have higher IOPS) as well as have the potential to fill the disk. For realistic env tests only (first), if it's a long running test, give it 1TiB
Trigger with adhoc forge run and observe disk size. As long as we're providing the helm values correctly in the Forge Test Runner, the helm chart is already tested and should create the spec required to get a larger disk
Test run: https://github.com/aptos-labs/aptos-core/actions/runs/9783196286/job/27011224899
Disks took a few min to provision, so we might need to increase the pod readiness timeout if this gets too long (e.g. for large scale tests)
PVCs show 1000Gi
`main.rs` in Forge that creates the NodeResourceOverride
=> [forge] long running tests get more storage

aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/framework/aptos-framework/tests/native_disaptch_token_tests.move, aptos-move/framework/aptos-framework/tests/native_dispatch_token.move, aptos-move/framework/src/natives/function_info.rs, third_party/move/move-vm/runtime/src/config.rs, third_party/move/move-vm/runtime/src/interpreter.rs, third_party/move/move-vm/runtime/src/loader/function.rs, types/src/on_chain_config/aptos_features.rs, types/src/vm/configs.rs
Disallowing dispatching on custom native function. This wouldn't raist a correctness issue but it's just not user friendly when user attempted so for now as the VM will raise error at an unexpected location.
Added a test to make sure such function gets rejected properly.
Make sure the gas version is set properly.
=> [aptos-framework] disallow dispatching on custom native

testsuite/forge-cli/src/main.rs
With the introduction of `max_sending_block_unique_txns` in #13906 (+ previous PRs) the forge test for max throughput needs to override this value.
=> [forge] fix the max throughput test, after changes to the consensus config

devtools/aptos-cargo-cli/src/common.rs
This PR updates the merge base check so that it doesn't block the release branch. A better fix is required, but this should unblock the failing check for now.
=> [CI/CD] Unblock merge base check for release branch.

storage/aptosdb/src/state_merkle_db.rs, storage/aptosdb/src/state_restore/mod.rs, storage/jellyfish-merkle/src/restore/mod.rs
=> [Storage] For fast sync / restore, we don't commit nodes from multiple shards in parallel.

consensus/src/block_storage/sync_manager.rs, consensus/src/network_tests.rs, consensus/src/round_manager_test.rs
=> [cherry-pick][1.16][consensus] fix edge case of block retrieval

.github/workflows/lint-test.yaml, aptos-move/aptos-abstract-gas-usage/Cargo.toml, aptos-move/aptos-gas-calibration/Cargo.toml, aptos-move/aptos-vm-benchmarks/Cargo.toml, crates/aptos-dkg/Cargo.toml, deny.toml, ecosystem/indexer-grpc/indexer-grpc-integration-tests/Cargo.toml, testsuite/fuzzer/Cargo.toml, third_party/move/move-model/bytecode/abstract_domain_derive/Cargo.toml
Internal context: https://aptos-org.slack.com/archives/C03K45JU90C/p1720451868050819.
CI is expected to fail until @grao1991 lands his PR. See thread in summary for more context. Once that is done, see that the new CI passes.
Update: CI passes now that that PR has been landed. Let's land.
Confirm that deny.toml is configured appropriately.
=> Use cargo deny to prevent onboarding certain crates

.github/workflows/lint-test.yaml
This PR is a cherry-pick of https://github.com/aptos-labs/aptos-core/pull/13943 (into the 1.16 release branch).
=> [CI/CD] Run all unit tests on release branch PRs.

aptos-move/framework/aptos-framework/doc/coin.md, aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/sources/coin.move, aptos-move/framework/aptos-framework/sources/fungible_asset.move
Coin has unlimited supply, so does FA.
=> [fix] make the max supply unlimited

config/src/config/mempool_config.rs, config/src/config/quorum_store_config.rs, testsuite/forge-cli/src/main.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/src/load_vs_perf_benchmark.rs, testsuite/testcases/src/two_traffics_test.rs
=> Re-apply qs backpressure increase with buffer latency increase

Cargo.lock, third_party/move/move-compiler-v2/transactional-tests/Cargo.toml, third_party/move/testing-infra/transactional-test-runner/Cargo.toml
Previously, to fix the case of testing VM output sometimes appearing
in `move-compiler-v2-transactional-tests` and sometimes not, PR #13492
added a dependence on `aptos-vm` with `debugging` feature.  This
introduced unnecessary dependency builds when working in third-party.
This PR fixes that.
CI tests should do it.
=> fix aptos-vm dependence in third-party/.../transactional-tests

consensus/src/consensus_observer/error.rs, consensus/src/consensus_observer/mod.rs, consensus/src/consensus_observer/observer.rs, consensus/src/consensus_observer/payload_store.rs, consensus/src/consensus_observer/pending_blocks.rs, consensus/src/payload_manager.rs, state-sync/state-sync-driver/src/driver.rs
This PR makes several small refactors and improvements to consensus observer. Specifically, it offers the following commits:
1. Refactor the block payload store to a separate file, add a simple struct wrapper and several unit tests.
1. Refactor the pending ordered blocks to a separate file, add a simple struct wrapper and several unit tests.
1. Add simple message verification for commit messages. Here, we verify the commit ledger info using the current epoch state. If the ledger info is for a future epoch, we pass it to state sync and rely on state sync to verify the epoch change and syncing process.
=> [Consensus Observer] Small refactors and basic commit verification.

crates/aptos/src/common/local_simulation.rs
This fixes a small bug in the banchmarking code. I forgot to sort the list of measurements taken.
Manual testing
=> [easy][cli] fix sorting bug in benchmarking code

aptos-move/aptos-vm/src/aptos_vm.rs, third_party/move/move-vm/runtime/src/loader/mod.rs, third_party/move/move-vm/runtime/src/session.rs
Previously, we used `check_dependencies_and_charge_gas_non_recursive_optional` which lived inside loader/MoveVM. This is not great for the new code cache because:
1. Newly published modules (not yet verified!) were deserialized and cached inside the session (transaction data cache), which is clearly not the place for it.
2. The main goal was to charge for existent modules, but this was done via `allow_loading_to_fail` flags, and was not really needed: AptosVM has full information about which modules exist and which do not.
In this PR, `check_dependencies_and_charge_gas_non_recursive_optional` is removed, and the gas charging is moved to AptosVM. There is no caching of deserialization because we can fetch size from the state view directly. This also aligns with new code cache design where …
=> [aptos-vm] Remove charging gas for module bundle from loader

consensus/src/network_tests.rs, consensus/src/round_manager_test.rs
This PR adds a unit test for block retrieval timeout bug fix PR #13864.
=> [consensus] unit test for block retrieval timeout

consensus/safety-rules/src/safety_rules.rs, consensus/src/pipeline/tests/signing_phase_tests.rs
Fix the InvalidOrderedLedgerInfo error that we observed in testnet. 
When doing fast forward sync, we pull the latest blocks and quorum certs from peers and store them in storage. 
We then compute the root ordered cert and root commit cert from storage and start the consensus from there.
But given that we are not storing the ordered cert obtained from order votes in storage, as a hack, we set root ordered cert to commit certificate. This means, the root ordered cert will not have a dummy execution_state_id in this case. When a block is being executed with this ordered cert, the safety rule for signing commit vote fails, which checks that the ordered cert should have dummy execution_state_id. This PR fixes the issue by bypassing the check when the ordered cert matches with commit vote's …
=> Fix the InvalidOrderedLedgerInfo error

Cargo.lock, Cargo.toml, api/Cargo.toml, api/doc/CHANGELOG.md, api/doc/spec.html, api/doc/spec.json, api/doc/spec.yaml, api/openapi-spec-generator/src/main.rs, api/src/accept_type.rs, api/src/bcs_payload.rs, api/src/check_size.rs, api/src/lib.rs, api/src/log.rs, api/src/runtime.rs, api/src/spec.rs, api/src/transactions.rs, api/types/src/transaction.rs, crates/aptos-faucet/core/src/endpoints/captcha.rs, crates/aptos-openapi/Cargo.toml, crates/aptos-openapi/src/helpers.rs, testsuite/smoke-test/src/rosetta.rs
In this PR I upgrade us from poem 1.x.x and poem-openapi 2.x.x to poem 3.x.x and poem-openapi 5.x.x. Besides it being good in general to stay up to date, we want to upgrade specifically to get the latest opentelemetry features so we can benefit from distributed tracing throughout the API stack. There have been other instances where being pinned to a specific version caused us issues.
The new Poem traits had issues with `Box<UserTransaction>` in transaction, so I just unboxed it. I can't see why it needs to be in a Box and the original commit (https://github.com/aptos-labs/aptos-core/commit/3ecd8e927a35ead89f528f035c0c6397ffb8d80b) doesn't explain it. Perhaps there used to be some recursive type that we had to break.
Besides that, fortunately there wasn't much to change with our types or …
=> Upgrade to poem 3.x.x and poem-openapi 5.x.x

aptos-move/aptos-release-builder/data/release.yaml
This uses the newly introduced new / old gas option to ensure that the gas schedule is upgrading explicitly from the prior version to the new version
Test Plan: framework upgrade forge test runs in the PR triggered by the label
=> [RFC] Update gas schedule with new diff for 1.16

.github/workflows/workflow-run-docker-rust-build.yaml, docker/builder/builder.Dockerfile
This PR migrates the docker build workflow to use runs-on runners. This setup is quite different from our experimental-docker setup in that it uses S3 caches instead of attached volumes. Essentially, there is a step that archives the `/var/lib/docker` folder and caches it. To workaround using the `cache` action on a privileged directory, a step first tars the directory with `sudo` privileges and then invokes the cache action. Similar, on download, it downloads the tar and untars it.
=> [gha][docker] migrate to runs-on runners

Cargo.lock, Cargo.toml, ecosystem/nft-metadata-crawler-parser/Cargo.toml, ecosystem/nft-metadata-crawler-parser/src/asset_uploader.rs, ecosystem/nft-metadata-crawler-parser/src/config.rs, ecosystem/nft-metadata-crawler-parser/src/lib.rs, ecosystem/nft-metadata-crawler-parser/src/main.rs, ecosystem/nft-metadata-crawler-parser/src/parser.rs, ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
The asset uploader is a simple service for the TMP that uploads token assets to cloudflare images and saves the mapping in postgres. These changes include logic for the asset uploader, moving the NFT metadata crawler from warp -> axum, and refactoring the config. 
Deployed to staging + tested locally + unit tests
`asset_uploader.rs` and the config diffs
=> [NFT Metadata Crawler] Asset Uploader

consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/counters.rs
=> Improve QS backpressure counter

consensus/src/liveness/leader_reputation.rs, storage/storage-interface/src/lib.rs
Lazy init db result on first call to leader reputation. Otherwise there was a corner case where it would not start updating until one block after genesis. (This is the reason smoke test `client::test_basic_fault_tolerance` was flaky.)
Ran `client::test_basic_fault_tolerance` multiple times
* Haven't seen it fail.
* Added verbose logs (since removed) to confirm that the block event sliding window now starts at length 1 (genesis) instead of length 0 (which is a bug, since genesis should be there)
This should only affect the corner case of a fresh chain. Experts should double check.
=> [consensus] leader election: lazy init cached db results

Cargo.lock, consensus/Cargo.toml, consensus/src/transaction_shuffler/mod.rs, consensus/src/transaction_shuffler/use_case_aware/delayed_queue.rs, consensus/src/transaction_shuffler/use_case_aware/iterator.rs, consensus/src/transaction_shuffler/use_case_aware/mod.rs, consensus/src/transaction_shuffler/use_case_aware/tests/manual.rs, consensus/src/transaction_shuffler/use_case_aware/tests/mod.rs, consensus/src/transaction_shuffler/use_case_aware/tests/proptests.rs, consensus/src/transaction_shuffler/use_case_aware/types.rs, consensus/src/transaction_shuffler/use_case_aware/utils.rs, testsuite/forge-cli/src/suites/dag.rs, testsuite/smoke-test/src/aptos_cli/validator.rs, types/src/on_chain_config/execution_config.rs
Full description:
https://github.com/aptos-foundation/AIPs/pull/477/files
This shuffler delays txns according to both contract address spread factor and sender spread factor. 
unit tests and forge tests
=> UseCaseAwareShuffler

.github/workflows/workflow-run-docker-rust-build.yaml
Using `capacity-optimized` spot instances to limit preemptions.
=> [gha][docker] use capacity optimized spot runners

.dockerignore, crates/aptos-build-info/build.rs, docker/builder/forge.Dockerfile, testsuite/testcases/src/framework_upgrade.rs
Add and test any proposal release yaml in the data dir of release builder
Test Plan: Build / runs on PR with label
Also a child PR with a new yaml should show running and executing that yaml
https://github.com/aptos-labs/aptos-core/pull/14025
=> [forge] Framework upgrade test all proposals

aptos-move/aptos-vm-types/src/environment.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs, third_party/move/move-vm/integration-tests/src/tests/instantiation_tests.rs, third_party/move/move-vm/runtime/src/config.rs, third_party/move/move-vm/runtime/src/interpreter.rs, third_party/move/move-vm/runtime/src/loader/mod.rs, third_party/move/move-vm/transactional-tests/tests/recursion/runtime_type_deeply_nested.exp, third_party/move/move-vm/types/src/loaded_data/runtime_types.rs, types/src/on_chain_config/aptos_features.rs
The feature to limit VM type sizes has been enabled, so this PR removes the legacy type builder implementation.
=> [move] Remove legacy type builder

experimental/storage/layered-map/src/lib.rs, experimental/storage/layered-map/src/node.rs, experimental/storage/layered-map/src/tests.rs
The interface used to understand `None` as deletions (None as tombstones) and when trying to get a key, the result is the same if the key is not found or the value is None. The behavior confused the call site, I'd rather let the call site deal with the tombstones "manually.
unit test
=> LayeredMap: carries Value instead of Option<Value>

crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/submission_worker.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs
We were checking whether worker accounts exist, and using transfer vs account creation gas for init method. But we were internally also funding seed accounts with the same max gas specified - and they could be missing.
Changing so that seed and worker accounts are created at the same place, and as a single stream of accounts (so that changing different params is unlikely to require account creation, to safe funds)
Additionally, drastically reducing number of accounts (and with it amount of funds/connections) needed for --target-tps. We were reusing accounts after expiration+240s, but that buffer is way too large. Defaulting to 2*expiration + 5. With default expiration of 60s, that reduces number of accounts by 60% (multiplier down from 300 to 125), but also if your test expects low …
=> [txn-emitter] Fix check whether seed accounts exist, and reduce num accounts needed for --target-tps

consensus/src/quorum_store/batch_requester.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/tests/batch_requester_test.rs, consensus/src/quorum_store/types.rs
In an event when the `PayloadManager::prefetch_payload_data` is invoked before a batch is received locally, the batch requester starts sending RPCs to retrieve the batch from remote peers. However, it is very possible the batch arrives from the author as soon as the prefetch happens, but the payload manager still waits for the batch requester to fetch. 
To prevent this, this PR proposes a subscription mechanism where the batch requester will subscribe to the batch store persist flow and listen to the batch being added from the Direct Send message. This will short circuit the batch requester and use this value to satisfy the PayloadManager.
=> [quorum-store] subscribe to batches from DirectSend flow in batch requester

testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs
Adds a timeout to `generate_traffic` call to non quorum store node in the `test_swarm_with_bad_non_qs_node` smoke test. The test was flaky because the bad node crashes and dies but the transaction emitter keeps trying for 600 seconds before giving up.
=> [smoke-test][qs] add generate_traffic timeout to bad node

third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_empty_block.exp, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_empty_block.move, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_fun_1.exp, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_fun_1.move, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_fun_2.exp, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_fun_2.move, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_fun_3.exp, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_fun_3.move, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_var.exp, third_party/move/move-compiler-v2/tests/checking/variants/variants_allow_match_var.move, third_party/move/move-compiler-v2/tests/checking/variants/variants_parse_err4.exp, third_party/move/move-compiler/src/parser/syntax.rs
Fixes #14038.
The introduction of the `match (exp) { .. }` expression accidentally disabled the `match` name to be used for functions or variables. This PR adds context sensitivity to the parser to distinguish, for example, `match(x, y)` (a function call) from `match (e) { .. }`. As we are using a LL(2) parser, this is achieved by factoring out the common prefix. There is no function call `match(e) {` possible, so we know it is a match expression once we see `{`.
Added a number of test cases to the Move 2 testsuite. The parsers for language v1 and v2 are the same, so this also covers use cases for compiler v1 and compiler v2/language version v1.
=> [move-2] Allow variables and functions be called `match` in Move-2

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml
Release needed to fix a breaking bug effecting both v1/v2 compilers.
=> [cli] Bump to 3.5.1

.github/actions/rust-unit-tests/action.yaml, .github/workflows/lint-test.yaml
Remove buildkite test collector since this isn't being used anymore
Will run the unit test workflow for this PR
=> remove buildkite integration

.github/workflows/windows-build.yaml, scripts/windows_dev_setup.ps1
I was seeing that downloading the WinGet installer was just hanging. For whatever reason, Invoke-WebRequest struggled with the large WinGet installer package. Using Start-BitsTransfer fixes it. It doesn't know how to follow redirects so I resolve those myself, it seems like the actual URLs are sensible (like not ephemeral).
I also fixed some broken flags, e.g. typos for `--accept-source-agreements`.
See Windows CLI build run. Note that the actual CLI build will fail until this lands: https://github.com/aptos-labs/aptos-core/pull/14067. The point of this PR is just to fix the setup phase.
N/A
=> Fix downloads in Windows setup script

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml, crates/aptos/src/node/local_testnet/processors.rs
Previous: https://github.com/aptos-labs/aptos-core/pull/14068
The previous processor dependency broke the CLI build on Windows. This PR updates the dependency to fix that. This updates the dependency such that the v1 processors have been deleted. I update the CLI code accordingly.
This time I applied the `CICD:run-windows-tests` label, see that the Windows build CI passes.
N/A
=> Update processor dep for localnet to fix Windows CLI build

config/src/config/consensus_observer_config.rs, consensus/consensus-types/src/common.rs, consensus/src/consensus_observer/network_message.rs, consensus/src/consensus_observer/observer.rs, consensus/src/consensus_observer/ordered_blocks.rs, consensus/src/consensus_observer/payload_store.rs, consensus/src/consensus_observer/pending_blocks.rs, consensus/src/consensus_observer/publisher.rs, consensus/src/payload_manager.rs, consensus/src/pipeline/execution_client.rs, consensus/src/test_utils/mock_execution_client.rs
Note: most of this code is new unit tests.
This PR makes several improvements to consensus observer. Specifically, it offers the following commits:
1. Add a `reset()` method to the execution client trait. This method is already provided internally by `sync_to` and we want to expose it so that we can call it directly whenever consensus observer needs to reset execution state (e.g., on subscription changes).
1. Update consensus observer to reset the execution pipeline and all pending block state when switching subscriptions. This shouldn't be strictly necessary, but it seems like a safe fallback.
1. Update consensus observer to perform message verification for block payloads. Specifically, we: (i) verify the payload batch digests (i.e., to make sure all transactions are valid and in the …
=> [Consensus Observer] Add block payload verification.

consensus/src/consensus_observer/metrics.rs, consensus/src/consensus_observer/network_message.rs, consensus/src/consensus_observer/observer.rs, consensus/src/consensus_observer/ordered_blocks.rs, consensus/src/consensus_observer/payload_store.rs, consensus/src/consensus_observer/publisher.rs, consensus/src/payload_manager.rs
Note: this PR builds on https://github.com/aptos-labs/aptos-core/pull/14027
This PR offers several simplifications and cleanups to consensus observer. Specifically, it offers the following commits:
1. Enable `info` logging of message types. We should probably have these for a while (to aid debugging).
2. Clean up the ordered block store and remove the need for supporting unverified blocks. Now that all payloads must be verified before ordering, the ordered block store will always verify blocks before processing. Also, we rename a few structs and methods for clarity.
3. Move final payload verification out of the payload manager and into the payload store. This is now possible that we've simplified the ordered block logic.
4. Refactor block transaction payload messages.
New and existing …
=> [Consensus Observer] Simplify and clean up logic.

aptos-move/e2e-move-tests/src/tests/object_code_deployment.data/pack_immutable_deps/Move.toml, aptos-move/e2e-move-tests/src/tests/object_code_deployment.data/pack_immutable_deps/sources/test_immutable_deps.move, aptos-move/e2e-move-tests/src/tests/object_code_deployment.data/pack_mutable_deps/Move.toml, aptos-move/e2e-move-tests/src/tests/object_code_deployment.data/pack_mutable_deps/sources/test_mutable_deps.move, aptos-move/e2e-move-tests/src/tests/object_code_deployment.rs, aptos-move/framework/aptos-framework/doc/code.md, aptos-move/framework/aptos-framework/sources/code.move
- [ x ] Bug fix
- [ x ] Aptos Framework
E2E tests
=> [Framework] Add dependencies check for code object freezing
