config/src/config/consensus_config.rs
consensus/src/block_storage/block_store_test.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/counters.rs
consensus/src/round_manager.rs

[cherry-pick] aggressive backpressure changes (#11345 and #11550)

---

config/src/config/execution_config.rs

update additional vm checks

---

aptos-move/aptos-release-builder/data/release.yaml

to match change in #11472 and #11548

block limits in release.yaml for 1.9

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Making a release to pick up new local testnet and Move changes.
CI.

[CLI] Bump version to 2.4.0

---

consensus/src/quorum_store/proof_coordinator.rs

Since #11444 proof coordinator removes batches on commit, rather than only expire. The counter however was not added to the commit path until now.

[Quorum Store] fix counters

---

consensus/src/quorum_store/proof_coordinator.rs

[cherry-pick] [Quorum Store] fix counters

---

aptos-move/framework/aptos-framework/doc/multisig_account.md
aptos-move/framework/aptos-framework/sources/multisig_account.spec.move

- Fixed some minor issues with the requirements of the multisig_account module
- Replaced `Property` with `Requirement`
- Added a dummy `spec module` block for the correct document generation

[Spec] Fixed some minor issues with the requirements of the multisig_account module

---

aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/block.md
aptos-move/framework/aptos-framework/doc/managed_coin.md
aptos-move/framework/aptos-framework/doc/staking_config.md
aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/doc/storage_gas.md
aptos-move/framework/aptos-framework/doc/voting.md
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/block.spec.move
aptos-move/framework/aptos-framework/sources/configs/staking_config.spec.move
aptos-move/framework/aptos-framework/sources/managed_coin.spec.move
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
aptos-move/framework/aptos-framework/sources/storage_gas.spec.move
aptos-move/framework/aptos-framework/sources/voting.spec.move

Nits to refine documentation for prover article.

[documentation] small fixes

---

consensus/src/block_storage/block_store_test.rs
consensus/src/block_storage/sync_manager.rs

Add min gap to fallback to statesync

---

storage/aptosdb/src/backup/backup_handler.rs
storage/aptosdb/src/backup/restore_handler.rs
storage/aptosdb/src/backup/restore_utils.rs
storage/aptosdb/src/db/include/aptosdb_reader.rs
storage/aptosdb/src/db/include/aptosdb_writer.rs
storage/aptosdb/src/db/mod.rs
storage/aptosdb/src/db_debugger/examine/print_db_versions.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/ledger_db/mod.rs
storage/aptosdb/src/ledger_db/transaction_db.rs
storage/aptosdb/src/ledger_db/transaction_db_test.rs
storage/aptosdb/src/pruner/ledger_pruner/mod.rs
storage/aptosdb/src/pruner/ledger_pruner/transaction_pruner.rs
storage/aptosdb/src/rocksdb_property_reporter.rs
storage/aptosdb/src/transaction_store/mod.rs
storage/aptosdb/src/transaction_store/test.rs
storage/aptosdb/src/utils/truncation_helper.rs
types/src/transaction/mod.rs

Move functions that are not going to be deprecated after sharding to the TransactionDb struct, and add unit tests.

[Storage] Add TransactionDb as a submodule of LedgerDb.

---

aptos-move/aptos-gas-schedule/src/ver.rs

[cherry-pick] Update lastest gas version (#11614)

---

aptos-node/src/storage.rs
aptos-node/src/tests.rs
config/src/config/execution_config.rs

add a storage genesis waypoint config to decouple from node base waypoint config
updated unit test

[storage] add storage genesis waypoint

---

crates/aptos/src/move_tool/mod.rs

Correct cli name `VerifyPackage`

---

execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/pipeline.rs

[executor benchmark] consolidate output evaluation stats

---

crates/aptos/src/node/local_testnet/node.rs

This lets you run two local testnets with different sets of services. Useful in certain circumstances described in the thread below.
See https://aptos-org.slack.com/archives/C04PF1X2UKY/p1704482631166169.

[CLI] Add a secret flag to disable the node in a local testnet

---

CODEOWNERS

Update aptos-vm code owners

---

consensus/consensus-types/src/block.rs
consensus/consensus-types/src/executed_block.rs
consensus/src/block_storage/block_store.rs
consensus/src/epoch_manager.rs
consensus/src/execution_pipeline.rs
consensus/src/pipeline/execution_schedule_phase.rs
consensus/src/pipeline/ordering_state_computer.rs
consensus/src/state_computer.rs
consensus/src/state_computer_tests.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_state_computer.rs
types/src/block_metadata_ext.rs
types/src/proptest_types.rs
types/src/transaction/mod.rs

When randomness feature is enabled, execute `BlockMetadataExt` flow.

state computer working with block metadata ext

---

ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Move URI blacklist to the config so that it can be edited without having to redeploy. 
Tested locally, works fine

[NFT Metadata Crawler] Add URI blacklist to config

---

storage/aptosdb/src/backup/backup_handler.rs
storage/aptosdb/src/backup/restore_handler.rs
storage/aptosdb/src/backup/restore_utils.rs
storage/aptosdb/src/db/include/aptosdb_internal.rs
storage/aptosdb/src/db/include/aptosdb_reader.rs
storage/aptosdb/src/db/include/aptosdb_writer.rs
storage/aptosdb/src/db/mod.rs
storage/aptosdb/src/db_debugger/examine/print_db_versions.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/get_restore_handler.rs
storage/aptosdb/src/ledger_db/mod.rs
storage/aptosdb/src/ledger_db/write_set_db.rs
storage/aptosdb/src/ledger_db/write_set_db_test.rs
storage/aptosdb/src/pruner/ledger_pruner/mod.rs
storage/aptosdb/src/pruner/ledger_pruner/write_set_pruner.rs
storage/aptosdb/src/rocksdb_property_reporter.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/transaction_store/mod.rs
storage/aptosdb/src/transaction_store/test.rs
storage/aptosdb/src/utils/truncation_helper.rs

[Storage] Add WriteSetDb as a submodule of LedgerDb.

---

protos/typescript/src/aptos/bigquery_schema/v1/transaction.ts
protos/typescript/src/aptos/indexer/v1/raw_data.ts
protos/typescript/src/aptos/internal/fullnode/v1/fullnode_data.ts
protos/typescript/src/aptos/transaction/v1/transaction.ts
protos/typescript/src/aptos/util/timestamp/timestamp.ts

* Re-gen the TS proto code from main. This is to fix the CI issue. 
script generated code

update the typescript proto gen.

---

protos/typescript/CHANGELOG.md
protos/typescript/CONTRIBUTING.md
protos/typescript/package.json
protos/typescript/src/aptos/bigquery_schema/v1/transaction.ts
protos/typescript/src/aptos/indexer/v1/raw_data.ts
protos/typescript/src/aptos/internal/fullnode/v1/fullnode_data.ts
protos/typescript/src/aptos/transaction/v1/transaction.ts
protos/typescript/src/aptos/util/timestamp/timestamp.ts

Seems like the code is out of sync with what the generator returns, even though the tool versions are pinned. Not sure how it happened but it shouldn't happen again.
I tested the new TS package, works fine.

Update generated proto code for TS

---

.github/workflows/docker-build-test.yaml
docker/builder/build-node.sh
docker/builder/build-tools.sh
docker/builder/forge.Dockerfile

Unfortunately stripping removes our ability to get stack traces
However in the future we want to add some stripped images (perhaps fullnode image)
And figure out a way to distribute the symbols or symbolicate separately
Test Plan: tools image on the PR is a reasonable size (below 10GB)

[forge] Unstrip forge

---

storage/aptosdb/src/metrics.rs
storage/aptosdb/src/rocksdb_property_reporter.rs

[Storage] Split rocksdb metrics for db shards into separate metrics.

---

crates/transaction-emitter-lib/src/emitter/mod.rs

[simple] Fix emitter when client is a load balancer across multiple servers

---

aptos-node/src/lib.rs
aptos-node/src/services.rs
config/src/config/identity_config.rs
consensus/src/consensus_provider.rs
consensus/src/epoch_manager.rs

dk fetch fix

---

Cargo.lock
dkg/Cargo.toml
dkg/src/dkg_manager/mod.rs
testsuite/smoke-test/src/randomness/validator_restart_during_dkg.rs

test: restart validators during dkg

---

ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs
ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs
ecosystem/nft-metadata-crawler-parser/src/utils/uri_parser.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Add more options for image quality to config and pinata auth for IPFS requests. 
Tested locally + existing unit tests

[NFT Metadata Crawler] Enable better quality from configs + add IPFS gateway auth

---

.github/workflows/copy-images-to-dockerhub-release.yaml
.github/workflows/docker-build-test.yaml

Publish images from randomnet branch

---

aptos-move/aptos-release-builder/src/components/feature_flags.rs
types/src/on_chain_config/aptos_features.rs

reserve a feature flag to enable new txn output

Add feature flag for removing detailed error from hash calcution

---

ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/localnet_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs

* Do not panic if clients disconnect.

[indexer] If the channel is closed, don't panic.

---

ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs

Remove extraneous log

---

aptos-move/aptos-vm/src/validator_txns/dkg.rs
aptos-move/aptos-vm/src/validator_txns/mod.rs
consensus/src/block_storage/tracing.rs
consensus/src/counters.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/tests/rb_handler_tests.rs
consensus/src/epoch_manager.rs
consensus/src/liveness/proposal_generator.rs
consensus/src/logging.rs
consensus/src/round_manager.rs
consensus/src/round_manager_fuzzing.rs
consensus/src/round_manager_test.rs
dkg/src/agg_trx_producer.rs
dkg/src/epoch_manager.rs
types/src/on_chain_config/aptos_features.rs
types/src/on_chain_config/consensus_config.rs
types/src/validator_txn.rs

Check if vtxn feature is enabled for DKG and randomness besides checking DKG.
Check if DKG feature is enabled in consensus besides checking vtxn.

[Randomness][Fix] check feature flags

---

aptos-move/framework/aptos-framework/sources/randomness.move

[Randomness] fix permutation

---

aptos-move/aptos-vm/src/natives.rs
aptos-move/framework/aptos-framework/doc/randomness.md
aptos-move/framework/aptos-framework/sources/randomness.move
aptos-move/move-examples/lottery/Move.toml
aptos-move/move-examples/lottery/README.md
aptos-move/move-examples/lottery/sources/lottery_common.move
aptos-move/move-examples/lottery/sources/lottery_insecure.move
aptos-move/move-examples/lottery/sources/lottery_secure.move
aptos-move/move-examples/lottery/sources/lottery_test.move
aptos-move/move-examples/raffle/Move.toml
aptos-move/move-examples/raffle/README.md
aptos-move/move-examples/raffle/scripts/test_and_abort_attack_defeated.move
aptos-move/move-examples/raffle/sources/raffle.move
aptos-move/move-examples/raffle/sources/raffle_test.move
aptos-move/move-examples/tests/move_unit_tests.rs
consensus/src/epoch_manager.rs
types/src/on_chain_config/aptos_features.rs

1. Updates the randomness API to include more functions.
2. Gives two example of randapps: a raffle and a lottery.
- The lottery example contains both a secure variant and an insecure one (susceptible to undergasing)

[move] extra randomness APIs + raffle and lottery examples

---

ecosystem/nft-metadata-crawler-parser/migrations/2024-01-31-221845_add_not_parsable_column/down.sql
ecosystem/nft-metadata-crawler-parser/migrations/2024-01-31-221845_add_not_parsable_column/up.sql

Add if exists and if not exists to migration so they don't fail. 
Tested locally

[NFT Metadata Crawler] Add IF EXISTS to migration

---

ecosystem/indexer-grpc/indexer-grpc-data-access/src/gcs.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs

Removes some clones, and fixes typos
existing tests

[GRPC] Nits + Clone reduction

---

aptos-move/framework/aptos-framework/doc/config_buffer.md
aptos-move/framework/aptos-framework/doc/dkg.md
aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/doc/jwks.md
aptos-move/framework/aptos-framework/doc/randomness.md
aptos-move/framework/aptos-framework/doc/reconfiguration_state.md
aptos-move/framework/aptos-framework/sources/configs/config_buffer.move
aptos-move/framework/aptos-framework/sources/dkg.move
aptos-move/framework/aptos-framework/sources/genesis.move
aptos-move/framework/aptos-framework/sources/jwks.move
aptos-move/framework/aptos-framework/sources/randomness.move
aptos-move/framework/aptos-framework/sources/reconfiguration_state.move

So the new resources can be initialized by governance.

initialize visibility fix

---

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
aptos-move/aptos-gas-schedule/src/ver.rs

double txn size limit

---

testsuite/fuzzer/fuzz/fuzz_targets/move/aptosvm_publish_and_run.rs

* Add support for signing fuzzcase transactions with different types of authenticators which allows fuzzer to cover signature verification code better.
* Other changes to improve invariant violation handling. 
`./fuzz.sh run move_aptosvm_publish_and_run` works

Authenticator fuzzer

---

ecosystem/nft-metadata-crawler-parser/src/config.rs
ecosystem/nft-metadata-crawler-parser/src/lib.rs
ecosystem/nft-metadata-crawler-parser/src/main.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Moves the config to its own module (in its own file) so that the code is cleaner. No logic is changed here! 
Tested locally + unit tests

[NFT Metadata Crawler] Refactor config to its own module

---

types/src/dkg/real_dkg/mod.rs
types/src/dkg/real_dkg/rounding/mod.rs
types/src/dkg/real_dkg/rounding/tests.rs

This reverts commit 1364c7676c8db44d67a1e6b0d52f0aba8e5b0063.

Revert "refactor (#11904)"

---

types/src/dkg/real_dkg/mod.rs
types/src/dkg/real_dkg/rounding/mod.rs
types/src/dkg/real_dkg/rounding/tests.rs

Input validator_stakes, secrecy_threshold and recontruct_threshold, output validator_weights and reconstruct_threshold_in_stake_ratio.
Alert if the validator_weights is too large.
Existing unit test.

[Randomness] rounding refactor

---

ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris.rs
ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Change retry logic to utilize `do_not_parse` and other retry fields
Works locally + unit tests

[NFT Metadata Crawler] Change dedupe + retry logic

---

crates/transaction-emitter-lib/src/args.rs
crates/transaction-emitter-lib/src/cluster.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/wrappers.rs
crates/transaction-generator-lib/src/bounded_batch_wrapper.rs
crates/transaction-generator-lib/src/lib.rs
crates/transaction-generator-lib/src/reduced_batch_wrapper.rs
crates/transaction-generator-lib/src/workflow_delegator.rs

- don't fail if only stale seq_num are received from rest endpoint
- workflow:
- make delay_between_stages_s configurable
- make init_max_gas_per_txn cli argument
- ReducedBatchWrapperTransactionGeneratorCreator utility, useful for tournament

[simple] Transaction generator improvements

---

Cargo.lock
config/src/config/dag_consensus_config.rs
consensus/src/dag/adapter.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/errors.rs
consensus/src/dag/health/backoff.rs
consensus/src/dag/health/pipeline_health.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/tests/rb_handler_tests.rs

Introduce ability to stop voting on RB  nodes, if pipeline latency is too long.

[dag] stop voting based on pipeline latency

---

ecosystem/nft-metadata-crawler-parser/migrations/2024-01-31-221845_add_not_parsable_column/up.sql

[NFT Metadata Crawler] Fix faulty migration

---

aptos-move/aptos-aggregator/src/delayed_field_extension.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/move_vm_ext/session.rs
aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
aptos-move/block-executor/src/proptest_types/types.rs

removing leftover TODOs that seem already addressed.

[agg_v2] First pass over TODOs

---

crates/transaction-generator-lib/src/publishing/module_simple.rs
execution/executor-benchmark/src/lib.rs
testsuite/single_node_performance.py

and count speculative aborts during a run.

add aggregator test to continuous single node performance

---

aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
aptos-move/vm-genesis/src/lib.rs
testsuite/single_node_performance.py

[agg_v2] Enable AggV2/RG feature in genesis (i.e. for devnet)

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/node/local_testnet/processors.rs

Update indexer version to latest version to fix TS SDK tests that are currently failing.

Update indexer version to latest version

---

ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator/local.rs

[Fix] Only create parent dir when it doesn't exist.

---

crates/aptos-dkg/tests/secret_sharing_config.rs

Needed a test case that prints information about the subsets of validators we expect to aggregate signatures from.

[randomness] print average/best/worst-case aggregation subset information

---

crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/emitter/mod.rs

fix transaction emitter balance requirements

---

aptos-move/aptos-aggregator/src/types.rs
aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm-types/src/output.rs
aptos-move/aptos-vm-types/src/resource_group_adapter.rs
aptos-move/aptos-vm-types/src/tests/test_change_set.rs
aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/errors.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
aptos-move/block-executor/src/captured_reads.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/task.rs
aptos-move/block-executor/src/txn_last_input_output.rs
aptos-move/block-executor/src/view.rs
aptos-move/mvhashmap/src/versioned_delayed_fields.rs
third_party/move/move-core/types/src/vm_status.rs
types/src/delayed_fields.rs

Making the error code more universal - DELAYED_MATERIALIZATION_CODE_INVARIANT_ERROR - i.e. anything with regards to BlockSTM, that we might want to fall back to sequential to resolve.

[agg_v2] cleaning up TODOs part 2

---

config/src/config/dag_consensus_config.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_handler.rs
consensus/src/dag/dag_network.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/round_state.rs
consensus/src/dag/tests/dag_driver_tests.rs
consensus/src/dag/tests/fetcher_test.rs
consensus/src/dag/tests/integration_tests.rs
consensus/src/dag/tests/order_rule_tests.rs
consensus/src/dag/tests/rb_handler_tests.rs
consensus/src/test_utils/mock_payload_manager.rs

This PR changes the dag NetworkHandler to process messages in parallel, to improve performance and avoid sequential bottlenecks including storage write latencies.

[dag] parallel message handler implementation

---

aptos-move/framework/aptos-framework/doc/stake.md
aptos-move/framework/aptos-framework/sources/stake.move

fix next_validator_consensus_infos bug

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs
aptos-move/block-executor/src/executor.rs
aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/e2e-move-tests/src/resource_groups.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs
aptos-move/e2e-tests/src/executor.rs
types/src/block_executor/config.rs

[agg_v2] e2e test with module publish

---

execution/executor-test-helpers/src/integration_test_impl.rs
execution/executor/tests/storage_integration_test.rs
storage/aptosdb/src/db/include/aptosdb_internal.rs
storage/aptosdb/src/db/mod.rs
storage/indexer/src/db_v2.rs
storage/indexer/src/lib.rs
storage/storage-interface/src/state_view.rs
types/src/transaction/mod.rs

Add some proof verification in storage integration test

---

Cargo.lock
Cargo.toml
crates/aptos-dkg/Cargo.toml
crates/aptos-dkg/benches/crypto.rs
crates/aptos-dkg/benches/weighted_vuf.rs
crates/aptos-dkg/src/utils/mod.rs
crates/aptos-dkg/src/utils/parallel_multi_pairing.rs
crates/aptos-dkg/src/weighted_vuf/bls/mod.rs
crates/aptos-dkg/src/weighted_vuf/pinkas/mod.rs
crates/aptos-dkg/src/weighted_vuf/traits.rs
crates/aptos-dkg/tests/crypto.rs
crates/aptos-dkg/tests/weighted_vuf.rs

The Pinkas WVUF derivation includes three phases that must be computed serially.
1. Lagrange coefficients
2. Several G1 multiexp
3. One multipairing
In this PR, we parallelize phases 2 and 3.
Phase 1 can be parallelized as well (to some extent), if need be.

Parallelize WVUF derivation

---

aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move

Fix a spec bug which leads to the recent prover test failure.

[Spec][Trivial] Fix a bug in the spec

---

aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/sources/events_with_aggregators.move
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2_events.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2_runtime_checks.rs
aptos-move/e2e-move-tests/src/tests/mod.rs
aptos-move/framework/src/natives/event.rs

- Added tests for event V1 and event V2 generation with aggregator snapshots. 
- Events V1 now also can use snapshots.

[aggregator] tests for events and improve event v1 handling

---

Cargo.lock
testsuite/single_node_performance.py
third_party/move/move-vm/runtime/Cargo.toml
third_party/move/move-vm/runtime/src/loader/mod.rs

Cache modules that have already been verified to avoid calling bytecode verifier.
TBD

[move-vm] Cache verified modules

---

testsuite/fuzzer/fuzz.sh
testsuite/fuzzer/fuzz/fuzz_targets/move/aptosvm_publish_and_run.rs

This PR:
- fixes a false positive generated by the `move_aptosvm_publish_and_run` fuzzer
- fixes minor bugs in `fuzz.sh`
the `move_aptosvm_publish_and_run` fuzzer is tested not to crash with [this testcase](https://oss-fuzz.com/download/f7b87485-e62d-4247-a1b8-b31b5dfe4141?testcase_id=6366721847918592).

[fuzzing] fixes oss-fuzz FP and fuzz.sh

---

consensus/src/transaction_shuffler/fairness/mod.rs

wrong time complexity analysis

trivial doc fix

---

crates/aptos-jwk-consensus/src/counters.rs
crates/aptos-jwk-consensus/src/jwk_observer.rs

jwk observation counters

---

consensus/src/dag/dag_handler.rs
consensus/src/dag/tests/types_test.rs
consensus/src/dag/types.rs
consensus/src/epoch_manager.rs
consensus/src/network.rs
consensus/src/pipeline/commit_reliable_broadcast.rs
consensus/src/rand/rand_gen/network_messages.rs

This PR implements epoch check before processing any incoming RPC request.

[consensus] check rpc epoch in epoch_manager

---

aptos-move/aptos-gas-schedule/src/gas_schedule/instr.rs

fix gas version (13 is deprecated/cannot be used)

---

aptos-move/aptos-gas-meter/src/meter.rs

This fixes an incorrect version in the feature-gating of type creation.

[gas] fix feature-gating of type creation

---

consensus/src/quorum_store/batch_store.rs
consensus/src/round_manager.rs

remove spurious error lines

---

aptos-move/framework/aptos-framework/doc/account.md
aptos-move/framework/aptos-framework/doc/aptos_account.md
aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/doc/fungible_asset.md
aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/sources/account.move
aptos-move/framework/aptos-framework/sources/aptos_account.move
aptos-move/framework/aptos-framework/sources/coin.move
aptos-move/framework/aptos-framework/sources/fungible_asset.move
aptos-move/framework/aptos-framework/sources/object.move
crates/aptos-rosetta/src/types/objects.rs
crates/indexer/src/models/transactions.rs
execution/executor-test-helpers/src/integration_test_impl.rs

This reverts commit c7375b86ff492862f49ee56e994fed9c8af71709.

Revert "[event_v2] migrate account, coin, object (#10532)"

---

consensus/src/quorum_store/batch_store.rs
consensus/src/round_manager.rs

[cp #12137] remove spurious error lines

---

aptos-move/framework/aptos-framework/doc/account.md
aptos-move/framework/aptos-framework/sources/account.move
aptos-move/framework/aptos-framework/sources/account.spec.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs

cherry pick [move] rotate_authentication_key_call should not modify OriginatingAddress (#12108)

---

aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/sources/object.move
aptos-move/framework/aptos-framework/sources/object.spec.move
aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move
aptos-move/vm-genesis/src/lib.rs
types/src/on_chain_config/aptos_features.rs

This PR cherry picks the PR (#12129) to enable the max object nesting check
unit tests
framework upgrade test

[cherry-pick] Enable the max object nesting check (#12129)

---

config/src/config/state_sync_config.rs

Copy-pasta from forge optimize_state_sync_for_throughput
Ask Josh :)

[previewnet] state sync configs

---

aptos-move/framework/aptos-token-objects/doc/collection.md
aptos-move/framework/aptos-token-objects/doc/token.md
aptos-move/framework/aptos-token-objects/sources/collection.move
aptos-move/framework/aptos-token-objects/sources/token.move

TokenV2 - add owner to burn event (Burn event)

---

config/src/config/consensus_config.rs
config/src/config/quorum_store_config.rs

[preview] config fixes

---

aptos-move/framework/aptos-token-objects/doc/collection.md
aptos-move/framework/aptos-token-objects/doc/token.md
aptos-move/framework/aptos-token-objects/sources/collection.move
aptos-move/framework/aptos-token-objects/sources/token.move

* TokenV2 - add owner to burn event (BurnEventV2)
* review comments
* adding unit tests

[cp v1.10] TokenV2 - add owner to burn event (Burn event) (#12145)

---

ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs

Cherry pick https://github.com/aptos-labs/aptos-core/pull/12193

Hotfix to indexer grpc 1.3

---

aptos-move/aptos-release-builder/data/release.yaml
testsuite/forge-cli/src/main.rs

Update.release.yaml to enable `max_object_nesting_check`
framework upgrade test

Update.release.yaml to enable `max_object_nesting_check`

---

aptos-move/aptos-release-builder/data/release.yaml
types/src/on_chain_config/execution_config.rs

* forgot to update block output limit for concurrency increase
* make fairness reordering less aggressive to start with
* update release.yaml

[cp 1.10] update execution config (#12216)

---

ecosystem/nft-metadata-crawler-parser/migrations/2024-01-31-221845_add_not_parsable_column/down.sql
ecosystem/nft-metadata-crawler-parser/migrations/2024-01-31-221845_add_not_parsable_column/up.sql
ecosystem/nft-metadata-crawler-parser/migrations/2024-02-08-013147_add_last_transaction_version/down.sql
ecosystem/nft-metadata-crawler-parser/migrations/2024-02-08-013147_add_last_transaction_version/up.sql
ecosystem/nft-metadata-crawler-parser/src/config.rs
ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris.rs
ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Also update migrations so they don't break
Works locally

[NFT Metadata Crawler] Set retry count to 0 if image succeed + do_not_parse when blacklist

---

config/src/config/dag_consensus_config.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_state_sync.rs
consensus/src/dag/errors.rs
consensus/src/dag/tests/dag_state_sync_tests.rs
consensus/src/dag/types.rs
crates/aptos-bitvec/src/lib.rs
testsuite/smoke-test/src/consensus/dag/dag_fault_tolerance.rs

Dedup concurrent fetch requests and fetch concurrently.

[dag] concurrent dag fetcher

---

consensus/src/consensusdb/consensusdb_test.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_handler.rs
consensus/src/dag/dag_state_sync.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/tests/dag_driver_tests.rs
consensus/src/dag/tests/helpers.rs
consensus/src/dag/tests/order_rule_tests.rs
consensus/src/dag/tests/rb_handler_tests.rs

[dag] address fetch ordering conditions

---

.github/workflows/copy-images-to-dockerhub-release.yaml
.github/workflows/docker-build-test.yaml

Build and release preview-networking

[gha] add preview-networking

---

aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/sources/aggregator_v2_test.move
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs

add deletion/recreation to agg_v2 e2e test

---

aptos-move/aptos-release-builder/src/components/mod.rs
aptos-move/vm-genesis/src/lib.rs
testsuite/smoke-test/src/upgrade.rs
types/src/on_chain_config/aptos_features.rs

consolidate default features into a single list

---

aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2_events.rs

Address changes from #12012. Tests compare events in a nicer fashion, and all transaction outputs are compared for both sequantial/parallel and enabled/disabled flags.

[aggregator] Improve event testing

---

storage/aptosdb/src/db_options.rs
storage/aptosdb/src/rocksdb_property_reporter.rs

[storage] reduce the number of cf reporting metrics

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Bumping prior to making a release.
👀

[CLI] Bump version to 2.5.0

---

aptos-move/aptos-vm-types/src/storage/mod.rs
aptos-move/e2e-move-tests/src/tests/fee_payer.rs
aptos-move/e2e-tests/src/executor.rs

it's hard to maintain (already stale)
existing tests

remove StorageGasParameters::unlimited()

---

testsuite/forge-cli/src/main.rs

Add more variety to Forge workload-mix test

---

aptos-move/aptos-vm-types/src/storage/mod.rs

StorageGasParameters::latest() for usage in tests

---

config/src/config/identity_config.rs
consensus/src/consensus_provider.rs
consensus/src/epoch_manager.rs
consensus/src/pipeline/errors.rs
consensus/src/pipeline/execution_client.rs
consensus/src/test_utils/mock_execution_client.rs
consensus/src/twins/twins_node.rs

randomness #5: consensus update from randomnet

---

Cargo.lock
aptos-move/aptos-vm/src/keyless_validation.rs
testsuite/generate-format/src/lib.rs
testsuite/generate-format/tests/staged/api.yaml
testsuite/generate-format/tests/staged/aptos.yaml
testsuite/generate-format/tests/staged/consensus.yaml
testsuite/smoke-test/Cargo.toml
testsuite/smoke-test/src/keyless.rs
types/src/keyless/bn254_circom.rs
types/src/keyless/circuit_testcases.rs
types/src/keyless/groth16_sig.rs
types/src/keyless/mod.rs
types/src/keyless/openid_sig.rs
types/src/keyless/test_utils.rs
types/src/keyless/tests.rs
types/src/on_chain_config/aptos_features.rs

Cherry pick https://github.com/aptos-labs/aptos-core/pull/12287.

last keyless authenticator changes

---

aptos-move/aptos-vm-types/src/storage/mod.rs
aptos-move/aptos-vm-types/src/storage/space_pricing.rs
aptos-move/e2e-move-tests/src/tests/fee_payer.rs
aptos-move/e2e-tests/src/executor.rs

1. make it use latest logic, easier to maintain going forward
2. use latest() instead of unlimited() when proper
existing unittests

fix StorageGasParameters::unlimited()

---

aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move

fix CONCURRENT_FUNGIBLE_ASSETS feature id

---

consensus/src/counters.rs
consensus/src/round_manager.rs

cherry pick vtxn proposal metrics to 1.10

---

aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move

cherry pick feature id fix to 1.10

---

ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs

[Cherry pick] Fix max fetcher tasks

---

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json
api/src/tests/state_test.rs
aptos-move/framework/aptos-framework/doc/block.md
aptos-move/framework/aptos-framework/sources/block.move
aptos-move/framework/aptos-framework/sources/block.spec.move
consensus/src/counters.rs
consensus/src/dag/adapter.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/storage.rs
consensus/src/dag/tests/dag_driver_tests.rs
consensus/src/dag/tests/dag_test.rs
consensus/src/dag/tests/integration_tests.rs
types/src/on_chain_config/commit_history.rs
types/src/on_chain_config/mod.rs

[dag] use resource instead of events for commit history

---

aptos-node/src/tests.rs

Just fix by commenting out for now.
cargo build --all-targets

[preview] fix build

---

consensus/consensus-types/src/common.rs
testsuite/forge-cli/src/main.rs

Only do parallel verify if cache miss, reduce the min_len 4 -> 2.

[preview] proof cache improvement

---

crates/aptos-dkg/src/utils/mod.rs
crates/aptos-dkg/src/utils/parallel_multi_pairing.rs

[dkg] remove unsafe code

---

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
aptos-move/aptos-gas-schedule/src/ver.rs

gas schedule for dag init

---

Cargo.lock
config/src/config/state_sync_config.rs
network/framework/src/protocols/network/mod.rs
network/framework/src/protocols/rpc/error.rs
peer-monitoring-service/client/src/metrics.rs
state-sync/aptos-data-client/src/client.rs
state-sync/aptos-data-client/src/tests/advertise.rs
state-sync/aptos-data-client/src/tests/compression.rs
state-sync/aptos-data-client/src/tests/peers.rs
state-sync/aptos-data-client/src/tests/utils.rs
state-sync/data-streaming-service/src/data_stream.rs
state-sync/data-streaming-service/src/stream_engine.rs
state-sync/state-sync-driver/src/bootstrapper.rs
state-sync/state-sync-driver/src/continuous_syncer.rs
state-sync/state-sync-driver/src/notification_handlers.rs
state-sync/storage-service/server/Cargo.toml
state-sync/storage-service/server/src/lib.rs
state-sync/storage-service/server/src/optimistic_fetch.rs
state-sync/storage-service/server/src/subscription.rs
state-sync/storage-service/server/src/tests/optimistic_fetch.rs
state-sync/storage-service/server/src/tests/subscription.rs

This PR tunes and enables subscription syncing (for test purposes).

[Previewnet] Enable subscription syncing.

---

consensus/consensus-types/src/common.rs

Already doing the same in the InQuorumStore variant, missed the InQuorumStoreWithLimit variant. Landing now to make things consistent.

[Quorum Store] add parallel verification to InQuorumStoreWithLimit variant

---

aptos-node/src/lib.rs
aptos-node/src/tests.rs

This PR fixes a small unit test.
Local verification.

[Aptos Node] Fix config merge test.

---

crates/transaction-generator-lib/src/workflow_delegator.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/pipeline.rs
execution/executor-benchmark/src/transaction_generator.rs
testsuite/single_node_performance.py

and end executor benchmark after multiple consecutive empty blocks
Needed for Econia/Tournament/etc

Add stages into executor benchmark output

---

third_party/move/move-compiler-v2/tests/checking/access_specifiers/access_err.exp
third_party/move/move-compiler-v2/tests/checking/control_flow/for_loop_empty_novar.exp
third_party/move/move-compiler-v2/tests/checking/naming/standalone_mname.exp
third_party/move/move-compiler-v2/tests/checking/naming/unbound_module_name.exp
third_party/move/move-compiler-v2/tests/checking/specs/conditions_err.exp
third_party/move/move-compiler-v2/tests/checking/specs/expressions_err.exp
third_party/move/move-compiler-v2/tests/checking/specs/lets_err.exp
third_party/move/move-compiler-v2/tests/checking/specs/schemas_err.exp
third_party/move/move-compiler-v2/tests/checking/specs/use_erroneous_schema.exp
third_party/move/move-compiler-v2/tests/checking/typing/bad_type_argument_arity_struct_unpack.exp
third_party/move/move-compiler-v2/tests/checking/typing/lambda.exp
third_party/move/move-compiler-v2/tests/checking/typing/shadowing_invalid_scope.exp
third_party/move/move-compiler-v2/tests/checking/typing/v1-commands/no_let_outside_if.exp
third_party/move/move-compiler-v2/tests/checking/typing/v1-commands/unpack_extra_binding.exp
third_party/move/move-compiler-v2/tests/checking/typing/v1-commands/unpack_missing_binding.exp
third_party/move/move-compiler-v2/tests/folding/constants_simple.exp
third_party/move/move-model/src/builder/exp_builder.rs
third_party/move/move-model/tests/sources/conditions_err.exp
third_party/move/move-model/tests/sources/expressions_err.exp
third_party/move/move-model/tests/sources/lets_err.exp
third_party/move/move-model/tests/sources/schemas_err.exp
third_party/move/move-model/tests/sources/use_erroneous_schema.exp

This PR closes #12121 by printing the name without qualifier.
Error messages are changed.

[Compiler-v2] Fix issue 12121

---

config/src/config/dag_consensus_config.rs
consensus/src/dag/anchor_election/leader_reputation_adapter.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_handler.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/observability/counters.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/tests/dag_test.rs
crates/aptos-metrics-core/src/op_counters.rs

[dag] Bootstrap latency fixes and additional counters

---

crates/transaction-generator-lib/src/args.rs
testsuite/forge-cli/src/main.rs
testsuite/single_node_performance.py
testsuite/testcases/src/load_vs_perf_benchmark.rs

Create graceful workload sweep benchmark for measuring latency predictability

---

aptos-move/aptos-release-builder/data/example-release-with-randomness-framework/output/0-features.move
aptos-move/aptos-release-builder/data/example-release-with-randomness-framework/output/1-consensus-config.move
aptos-move/aptos-release-builder/data/example-release-with-randomness-framework/output/2-execution-config.move
aptos-move/aptos-release-builder/data/example-release-with-randomness-framework/output/3-version.move
aptos-move/aptos-release-builder/data/example-release-with-randomness-framework/output/4-oidc-provider-ops.move
aptos-move/aptos-release-builder/data/example-release-with-randomness-framework/output/5-gas-schedule.move
aptos-move/aptos-release-builder/data/example-release-with-randomness-framework/release.yaml
aptos-move/aptos-release-builder/src/components/consensus_config.rs
aptos-move/aptos-release-builder/src/components/execution_config.rs
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-release-builder/src/components/gas.rs
aptos-move/aptos-release-builder/src/components/mod.rs
aptos-move/aptos-release-builder/src/components/oidc_providers.rs
aptos-move/aptos-release-builder/src/components/version.rs

release builder update for randomness framework

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/move_vm_ext/mod.rs
aptos-move/aptos-vm/src/move_vm_ext/session/mod.rs
aptos-move/aptos-vm/src/move_vm_ext/session/respawned_session.rs
aptos-move/aptos-vm/src/move_vm_ext/session/session_id.rs
aptos-move/aptos-vm/src/move_vm_ext/session/view_with_change_set.rs

In preparation to introduce things like PrologueSession, UserSession, EpilogueSession.

A few cleanups around execute_user_transaction_impl

---

config/src/config/dag_consensus_config.rs
consensus/src/dag/anchor_election/leader_reputation_adapter.rs
consensus/src/dag/anchor_election/mod.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/rb_handler.rs

[preview][dag] order rule latency fixes and monitors

---

consensus/src/dag/dag_store.rs

[dag] fix dag store new tokio runtime bug

---

aptos-move/e2e-move-tests/src/harness.rs
aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/gas_schedule.md
aptos-move/framework/aptos-framework/sources/configs/gas_schedule.move

also disable gas update function

---

types/src/jwks/jwk/mod.rs
types/src/jwks/jwk/tests.rs

Some unwraps exploitable by malicious OIDC providers to halt the chain.

avoid some unwraps in jwk consensus

---

api/src/metrics.rs
api/src/transactions.rs
config/src/config/api_config.rs

[preview] [api] add a long poll API /transactions/wait_by_hash/:txn_hash

---

aptos-move/e2e-benchmark/src/main.rs
testsuite/single_node_performance.py

initial VM bench recalibration and minor single node recalibration

---

crates/transaction-generator-lib/src/args.rs
crates/transaction-generator-lib/src/entry_points.rs
crates/transaction-generator-lib/src/publishing/module_simple.rs
testsuite/single_node_performance.py

Add fee payer workload to transaction generator

---

Cargo.lock
Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs

I need to do this in multiple steps to avoid breaking processors in another repo.

[Indexer-grpc] Accept zstd as the compression encoding.

---

docker/builder/docker-bake-rust-all.hcl
testsuite/forge.py

bfeb0a8252a2089676d98107de508a7e9678fc52
49354812f75b6a9e7832b031df45ac626e33c9dc
from main

[preview] cherry-pick docker forge improvements

---

config/src/config/state_sync_config.rs

This PR disable subscription syncing by default.

[State Sync] Disable subscription syncing.

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

[CLI] Bump to 3.0.2 for release

---

Cargo.lock
Cargo.toml
aptos-move/aptos-vm/Cargo.toml
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/move_vm_ext/session/mod.rs
aptos-move/aptos-vm/src/move_vm_ext/session/respawned_session.rs
aptos-move/aptos-vm/src/move_vm_ext/session/session_id.rs
aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/abort_hook.rs
aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/epilogue.rs
aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/mod.rs
aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/prologue.rs
aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/user.rs
aptos-move/aptos-vm/src/testing.rs
aptos-move/e2e-move-tests/src/tests/fee_payer.rs

in preparation for introducing gas locking in the prologue.
full replay https://github.com/aptos-labs/aptos-core/actions/runs/8237114675

Persist progloue side effects

---

network/framework/src/connectivity_manager/mod.rs

This PR updates the networking code to determine the outbound connection limit based on network type.

[Network] Determine the outbound connection limit based on network type

---

aptos-move/framework/aptos-framework/doc/block.md
aptos-move/framework/aptos-framework/doc/reconfiguration_with_dkg.md
aptos-move/framework/aptos-framework/sources/block.move
aptos-move/framework/aptos-framework/sources/reconfiguration_with_dkg.move
aptos-move/framework/src/natives/debug.rs
types/src/contract_event.rs

Remove some debug stuff merged in by accident.

revert debug code

---

aptos-move/aptos-release-builder/data/release.yaml

From testing, fairness showed negative interaction with block gas limit, leaving it for next release, after a fix.
deployed to testnet already

disable fairness for v1.10

---

ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs

This change adds server-side filtering, which ignores the events/changes/payload/signatures for specified sender addresses. 
Unit tests added.

add server-side filtering.

---

ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs

tested in scratchnet and it looks good. 
[full.txt](https://github.com/aptos-labs/aptos-core/files/14595198/full.txt)
[trimmed.txt](https://github.com/aptos-labs/aptos-core/files/14595201/trimmed.txt)

fix the broken config.

---

consensus/src/liveness/leader_reputation.rs

- add more debug details for the first error line, to understand when it happens better
- when max_version is unset (when result is empty), don't log additional error line for not being able to find it.
existing tests, just adds logs

Leader reputation error logs

---

consensus/src/epoch_manager.rs
consensus/src/pipeline/execution_client.rs
consensus/src/rand/rand_gen/rand_manager.rs

fix randomness bootstrap

---

aptos-move/aptos-release-builder/data/proposals/enable_randomness.move
aptos-move/aptos-release-builder/data/proposals/jwk_consensus_config_migration.move
aptos-move/aptos-release-builder/data/proposals/randomness_framework_initialization.move
aptos-move/aptos-release-builder/data/proposals/start_jwk_consensus_for_google.move
aptos-move/aptos-release-builder/data/release.yaml
aptos-move/framework/aptos-framework/doc/dkg.md
aptos-move/framework/aptos-framework/doc/randomness_config.md
aptos-move/framework/aptos-framework/sources/configs/config_buffer.move
aptos-move/framework/aptos-framework/sources/configs/randomness_config.move
aptos-move/framework/aptos-framework/sources/dkg.move
aptos-move/framework/aptos-framework/sources/dkg.spec.move
aptos-move/framework/aptos-framework/sources/randomness.move
aptos-move/framework/aptos-framework/sources/randomness.spec.move
consensus/src/epoch_manager.rs
types/src/jwks/mod.rs
types/src/on_chain_config/jwk_consensus_config.rs

update release yaml for randomness framework

---

consensus/src/pipeline/buffer_manager.rs

Demote from error!() QuorumStore CouldNotGetData

---

mempool/src/core_mempool/transaction.rs

with some loadtests we were seeing it reaching 255

increase width of mempool retry counter per transaciton

---

consensus/src/pipeline/buffer_manager.rs

avoid getting BlockNotFound error on epoch boundary

---

aptos-move/aptos-release-builder/data/release.yaml

Reverting this as we don't plan to provision mainnet for higher throughput for now.

[Revert] AIP 74 - revert increasing block gas limit

---

consensus/src/epoch_manager.rs
consensus/src/liveness/leader_reputation.rs
consensus/src/pipeline/buffer_manager.rs

Cherry-picks of:
* Demote from error!() QuorumStore CouldNotGetData #12522 
* Leader reputation error logs #12509 
*  demote network issue with epoch proofs to warn message #12548

[cp 1.10] error logs cleanup cherry-picks (#12522, #12509, #12548)

---

mempool/src/core_mempool/transaction.rs

with some loadtests we were seeing it reaching 255

[cp 1.10] increase width of mempool retry counter per transaciton (#12538)

---

crates/aptos-rosetta/src/types/objects.rs

Fixes a missing transaction type in Rosetta which would make the Rosetta process panic
Tested on testnet with live data

[cherry-pick] fix vtxn todo in rosetta (#12569)

---

consensus/src/epoch_manager.rs

demote network issue with epoch proofs to warn message

---

aptos-move/aptos-vm/src/move_vm_ext/session/mod.rs
aptos-move/block-executor/src/view.rs
aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs
aptos-move/framework/src/natives/event.rs
aptos-move/framework/table-natives/src/lib.rs
third_party/move/move-core/types/src/vm_status.rs
third_party/move/move-vm/types/src/value_serde.rs

temporarily, until gas charges for aggregator loading are implemented, limit number of aggregators per resource
e2e workload tests

Limit number of DelayedFields (aggregators) per resource

---

consensus/src/pipeline/buffer_manager.rs
consensus/src/round_manager.rs

[cherry-pick] bail buffered out of date proposals faster

---

consensus/src/state_computer.rs
consensus/src/state_computer_tests.rs
consensus/src/txn_notifier.rs

cherry-picking https://github.com/aptos-labs/aptos-core/pull/12512

vtxn mempool fix for 1.10

---

types/src/jwks/jwk/mod.rs
types/src/jwks/jwk/tests.rs

cherry-picking https://github.com/aptos-labs/aptos-core/pull/12432

jwk serde fix for 1.10

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Version bump ahead of release.
N/A
N/A

[CLI] Bump to 3.1.0

---

Cargo.lock
keyless/pepper/service/Cargo.toml
keyless/pepper/service/src/jwk.rs
keyless/pepper/service/src/lib.rs
keyless/pepper/service/src/main.rs
keyless/pepper/service/src/metrics.rs
keyless/pepper/service/src/vuf_keys.rs

- metric: seconds/count of a pepper request handling by pepper scheme (currently only v0) and result (ok/err).
- metric: seconds/count of jwk fetches by issuer and result (ok/err) 
- Avoid logging the entire JWT.

pepper v0 proper logs and metrics

---

.github/actions/move-tests-compiler-v2/action.yaml

Remove 3 retries from the CI job to save more resource.

[CI][Compiler-v2] remove retry from compiler v2 test

---

.github/workflows/move-test-compiler-v2.yaml

Update workflow_dispatch so that it will be run against all PRs

[CI] Update move-test-compiler-v2.yaml

---

aptos-move/block-executor/src/scheduler.rs
aptos-move/e2e-move-tests/src/tests/nft_dao.rs
consensus/safety-rules/src/thread.rs

chore: fix typos

---

aptos-move/aptos-gas-profiling/src/profiler.rs
aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs

This tunes the gas costs and limits for dependencies.

[gas] tune dependency gas and limits for 1.10

---

config/src/config/consensus_config.rs
consensus/src/liveness/proposal_generator.rs

enable block limit after reordering and support the same for Chain health

---

testsuite/forge-cli/src/main.rs

Test run: https://github.com/aptos-labs/aptos-core/actions/runs/8456079404

tweak max_round_gap for changing_working_quorum_test

---

aptos-move/aptos-release-builder/data/release.yaml

merge AIP-43 and aggregator API enabling

---

Cargo.lock
aptos-move/e2e-benchmark/Cargo.toml
aptos-move/e2e-benchmark/src/main.rs
crates/aptos-logger/src/counters.rs
crates/aptos-logger/src/lib.rs
crates/aptos-logger/src/macros.rs
execution/executor-benchmark/src/lib.rs
testsuite/forge/src/interface/prometheus_metrics.rs
testsuite/forge/src/success_criteria.rs

Track error logs lines in a counter and assert as success criteria

---

.github/actions/rust-unit-tests/action.yaml

Make the test result upload using `buildkite-test-collector`. If there are issues with redirecting the test output this will print an error message instead of failing the workflow
CI

make buildkite-test-collector best effort

---

aptos-node/src/lib.rs
config/src/config/consensus_config.rs
consensus/src/payload_client/mixed.rs
consensus/src/pipeline/execution_client.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/reliable_broadcast_state.rs
consensus/src/rand/rand_gen/types.rs
dkg/src/epoch_manager.rs
dkg/src/lib.rs
testsuite/forge-cli/src/main.rs

[rand] add reliable broadcast config and override in test

---

.github/workflows/docker-build-test.yaml

Updating the image tag in workflows.

Update image tag in workflows

---

execution/executor-benchmark/src/main.rs
testsuite/single_node_performance.py

Add --skip-paranoid-checks and SKIP_MOVE_E2E=1 to executor benchmark

---

.github/workflows/prover-daily-test.yaml
aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/consensus_config.md
aptos-move/framework/aptos-framework/doc/execution_config.md
aptos-move/framework/aptos-framework/doc/gas_schedule.md
aptos-move/framework/aptos-framework/doc/jwk_consensus_config.md
aptos-move/framework/aptos-framework/doc/randomness.md
aptos-move/framework/aptos-framework/doc/randomness_config.md
aptos-move/framework/aptos-framework/doc/reconfiguration_with_dkg.md
aptos-move/framework/aptos-framework/doc/stake.md
aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/doc/storage_gas.md
aptos-move/framework/aptos-framework/doc/version.md
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/configs/consensus_config.spec.move
aptos-move/framework/aptos-framework/sources/configs/execution_config.spec.move
aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
aptos-move/framework/aptos-framework/sources/configs/jwk_consensus_config.spec.move
aptos-move/framework/aptos-framework/sources/configs/randomness_config.spec.move
aptos-move/framework/aptos-framework/sources/configs/version.spec.move
aptos-move/framework/aptos-framework/sources/randomness.move
aptos-move/framework/aptos-framework/sources/randomness.spec.move
aptos-move/framework/aptos-framework/sources/reconfiguration_with_dkg.spec.move
aptos-move/framework/aptos-framework/sources/stake.spec.move
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
aptos-move/framework/aptos-framework/sources/storage_gas.spec.move

This PR fixes the daily prover test failure and adds invariants on ValidatorSet and StakePool
Both CI and daily test pass

[Spec] Add invariants on ValidatorSet and StakePool

---

consensus/consensus-types/src/common.rs

Change Payload.len() and Payload.empty() to indicate actual payload size instead of max_txns_to_execute

---

.gitignore
aptos-move/aptos-gas-profiling/src/erased.rs
aptos-move/aptos-gas-profiling/src/flamegraph.rs
aptos-move/aptos-gas-profiling/src/report.rs
aptos-move/aptos-gas-profiling/templates/index.html

group ledger writes:
report write io gas for transaction itself and events:
running txns from the cli with `--profile-gas` (with events and transaction write gas hacked on)

beautifying gas profiler report

---

api/src/log.rs
api/src/runtime.rs

Update all the API endpoints with proper methods.

[api] specify method for all endpoints

---

aptos-move/e2e-benchmark/src/main.rs
consensus/src/epoch_manager.rs
dkg/src/dkg_manager/mod.rs
testsuite/forge/src/interface/prometheus_metrics.rs
testsuite/forge/src/success_criteria.rs

[forge][success_criteria] Fix forge check for error!() logs

---

crates/transaction-emitter-lib/src/args.rs
crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/emitter/local_account_generator.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/wrappers.rs
crates/transaction-generator-lib/src/lib.rs
sdk/src/types.rs

Changes to support pluggable account type. The actual implementation of keyless accounts is still TBD as a follow up.

[Emitter] Changes to support pluggable account type for keyless support 

---

testsuite/single_node_performance.py

https://tinyurl.com/perf1233
check out link
check out link

single-node-performance: update expected tps

---

.github/workflows/indexer-grpc-in-memory-cache-benchmark.yaml
Cargo.lock
Cargo.toml
docker/builder/build-indexer.sh
docker/builder/indexer-grpc.Dockerfile
ecosystem/indexer-grpc/indexer-grpc-in-memory-cache-benchmark/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-in-memory-cache-benchmark/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/in_memory_cache.rs

* Add benchmarks for in-memory cache.
Locally tested.

[indexer grpc] in-memory cache benchmarks.

---

README.md

Link: [https://aptos.dev/category/environment](https://aptos.dev/category/environment) is outdated 
Should: [https://aptos.dev/guides/system-integrators-guide](https://aptos.dev/guides/system-integrators-guide)

[Readme] Update outdated link

---

aptos-move/aptos-aggregator/src/delta_math.rs
third_party/move/documentation/coding_guidelines.md
third_party/move/tools/move-package/src/resolution/resolution_graph.rs

chore: fix some typos

---

api/src/response.rs
aptos-move/aptos-sdk-builder/src/rust.rs
aptos-move/aptos-sdk-builder/tests/generation.rs
aptos-move/aptos-vm/src/sharded_block_executor/cross_shard_state_view.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-move-tests/src/tests/string_args.rs
aptos-move/e2e-tests/src/account.rs
aptos-move/move-examples/mint_nft/2-Using-Resource-Account/sources/create_nft_with_resource_account.move
aptos-move/move-examples/veiled_coin/doc/veiled_coin.md
aptos-move/move-examples/veiled_coin/sources/veiled_coin.move
aptos-node/src/tests.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
storage/aptosdb/src/db/fake_aptosdb.rs

fix some comments

---

aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/doc/governance_proposal.md
aptos-move/framework/aptos-framework/doc/multisig_account.md
aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
aptos-move/framework/aptos-framework/doc/storage_gas.md
aptos-move/framework/aptos-framework/doc/transaction_fee.md
aptos-move/framework/aptos-framework/doc/transaction_validation.md
aptos-move/framework/aptos-framework/doc/vesting.md
third_party/move/move-prover/move-docgen/src/docgen.rs

Close #12870.
Updated doc files
Whether the contents of the doc comments for high-level requirement docs are in the generated documents

[doc-gen] Fix a bug in doc gen

---

.github/workflows/keyless-circuit-daily-test.yaml
keyless/circuit-data/install-deps.sh
keyless/circuit-tests/src/base64.rs
keyless/common/src/input_processing/witness_gen.rs

circuit pr update

---

consensus/src/rand/rand_gen/aug_data_store.rs
consensus/src/rand/rand_gen/network_messages.rs

double-verify epoch in aug data store

---

consensus/src/epoch_manager.rs
consensus/src/pipeline/execution_client.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/storage/db.rs
consensus/src/test_utils/mock_execution_client.rs
storage/schemadb/src/iterator.rs

[rand] cherry-pick fixes from previewnet

---

Cargo.lock
Cargo.toml
crates/aptos-drop-helper/src/async_concurrent_dropper.rs
experimental/storage/layered-map/Cargo.toml
experimental/storage/layered-map/src/dropper.rs
experimental/storage/layered-map/src/lib.rs
experimental/storage/layered-map/src/metrics.rs
experimental/storage/layered-map/src/node.rs
experimental/storage/layered-map/src/ref.rs
experimental/storage/layered-map/src/tests.rs

A multi-versional mapping data structure much like the in memory sparse merkle tree but doesn't do the hashing on nodes.
This is useful for implementing the per-block speculative LRU cache / Active State coming up.
proptest

[experimental] LayeredMap which views a sequence of MapLayers

---

consensus/src/rand/rand_gen/aug_data_store.rs
consensus/src/rand/rand_gen/rand_manager.rs

[rand] delay processing incoming blocks until self certified data available

---

aptos-move/aptos-release-builder/data/release.yaml

Before 1.11 framework upgrade, we should use the `DefaulGasWithOverrideOld` entry.

1.11 release yaml fix

---

testsuite/smoke-test/src/aptos_cli/validator.rs
types/src/dkg/real_dkg/rounding/mod.rs
types/src/dkg/real_dkg/rounding/tests.rs

rounding update more

---

.github/workflows/coverage-move-only.yaml
.github/workflows/coverage.yaml

GitHub workflow
https://github.com/aptos-labs/aptos-core/actions/runs/8741798017/job/23988636329?pr=12933

Add auth token for code coverage

---

Cargo.lock
Cargo.toml
crates/aptos-admin-service/Cargo.toml
crates/aptos-admin-service/src/server/consensus/mod.rs
crates/aptos-admin-service/src/server/mod.rs
crates/aptos-system-utils/Cargo.toml
crates/aptos-system-utils/src/lib.rs
crates/aptos-system-utils/src/profiling.rs
crates/aptos-system-utils/src/thread_dump.rs
crates/aptos-system-utils/src/utils.rs
ecosystem/indexer-grpc/indexer-grpc-server-framework/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-server-framework/src/lib.rs

[AdminService] Move some code to a separate crate.

---

aptos-move/aptos-release-builder/data/release.yaml

Cherry-picking https://github.com/aptos-labs/aptos-core/commit/cc63d74efd65f4722a72b15ad1f9af535c1ca4f6

fix release yaml

---

consensus/src/rand/rand_gen/types.rs

should handle invalid author properly.

fix share verify panic

---

Cargo.lock
api/types/src/convert.rs
aptos-node/Cargo.toml
third_party/move/tools/move-resource-viewer/src/fat_type.rs
third_party/move/tools/move-resource-viewer/src/lib.rs
third_party/move/tools/move-resource-viewer/src/limit.rs
third_party/move/tools/move-resource-viewer/src/resolver.rs

Cherrypick #12969

---

crates/validator-transaction-pool/src/lib.rs

so epoch can change even when proposal delay is high.
local smoke test
n/a

pull vtxn at least once

---

storage/aptosdb/src/db_options.rs
storage/aptosdb/src/schema/mod.rs

adding new CF to v1.10
1. relying on existing test
2. local test starting node with db containing txn_aux CF.

[storage fix] add transaction aux cf to 1.10

---

keyless/circuit-data/templates/tests/bigint/big_less_than_test.circom
keyless/circuit-tests/src/bigint.rs
keyless/circuit-tests/src/lib.rs
keyless/common/src/input_processing/circuit_input_signals.rs

circuit big_less_than tests

---

consensus/consensus-types/src/randomness.rs
consensus/src/rand/rand_gen/block_queue.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/reliable_broadcast_state.rs
consensus/src/rand/rand_gen/test_utils.rs
consensus/src/rand/rand_gen/types.rs
consensus/src/round_manager.rs
testsuite/generate-format/tests/staged/api.yaml
testsuite/generate-format/tests/staged/aptos.yaml
testsuite/generate-format/tests/staged/consensus.yaml
testsuite/smoke-test/src/randomness/mod.rs
types/src/randomness.rs

#12968 but also update `BlockMetadataExt`

rand type clean-up ver. B

---

scripts/windows_dev_setup.ps1

Updates Windows dependencies
CI
Look at the CI

[dev setup] Update windows install script

---

aptos-move/aptos-release-builder/data/release.yaml
aptos-move/aptos-release-builder/src/components/randomness_config.rs
aptos-move/framework/aptos-framework/doc/randomness_config.md
aptos-move/framework/aptos-framework/sources/configs/randomness_config.move
types/src/on_chain_config/randomness_config.rs

fast path release entry

---

aptos-move/framework/aptos-framework/doc/randomness.md
aptos-move/framework/aptos-framework/doc/stake.md
aptos-move/framework/aptos-framework/doc/vesting.md
aptos-move/framework/aptos-framework/doc/voting.md
aptos-move/framework/aptos-framework/sources/randomness.spec.move
aptos-move/framework/aptos-framework/sources/stake.spec.move
aptos-move/framework/aptos-framework/sources/vesting.spec.move
aptos-move/framework/aptos-framework/sources/voting.spec.move

Rewrote the spec in the vesting module that causes a warning
This resolves https://github.com/aptos-labs/aptos-core/issues/12879.
There are some flaky timeout issues going on, which are unrelated to this PR. This PR adds some `verify_duration_estimate` to suppress the flaky timeout errors.

[Spec] Fixed the spec in the vesting module that causes a warning

---

.github/workflows/coverage.yaml

Currently we are observing stack overflow issue when executing the coverage test: https://github.com/aptos-labs/aptos-core/actions/runs/8808837182/job/24178627220 
This PR adds the environment variable to the yaml file to resolve the issue.

[CI][Coverage] Set env var RUST_MIN_STACK to coverage test

---

execution/executor-benchmark/src/lib.rs
execution/executor/src/components/chunk_output.rs
execution/executor/src/metrics.rs
types/src/transaction/authenticator.rs

[simple] Add counters for authenticators used

---

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
aptos-move/aptos-gas-schedule/src/ver.rs

Enabling io gas for transaction itself and events, implemented here https://github.com/aptos-labs/aptos-core/pull/12770
the impact on commonly used txns are minimal:
Transfer | 7 | 7 | 0.0%
-- | -- | -- | --
2ndTransfer | 7 | 7 | 0.0%
CreateAccount | 993 | 993 | 0.0%
CreateTransfer | 995 | 995 | 0.0%
MintTokenV2 | 633 | 633 | 0.0%
MutateTokenV2 | 8 | 8 | 0.0%
MintLargeTokenV2 | 1452 | 1452 | 0.0%
MutateLargeTokenV2 | 11 | 12 | $${ \color{red} 9.1 \\% }$$
CreateStakePool | 2350 | 2350 | 0.0%
RotateConsensusKey | 66 | 66 | 0.0%
JoinValidator100 | 53 | 53 | 0.0%
AddStake | 15 | 15 | 0.0%
UnlockStake | 40 | 40 | 0.0%
WithdrawStake | 10 | 10 | 0.0%
LeaveValidatorSet100 | 12 | 12 | 0.0%
CreateCollection | 962 | 962 | 0.0%
CreateTokenFirstTime | 1489 | 1489 | 0.0%
MintTokenV1 | 8 | 8 | 0.0% …

enable write io gas for transaction and events

---

aptos-move/framework/aptos-framework/sources/aptos_coin.move
aptos-move/framework/aptos-framework/tests/aptos_coin_tests.move

[framework] refactor aptos_coin to separate out tests

---

keyless/circuit-data/templates/helpers/arrays.circom

Bug description [here](https://www.notion.so/aptoslabs/Same-problem-for-other-templates-in-arrays-circom-TODO-better-description-11b19366aa9b45ee978ac6a5cc9f3b7d?pvs=4).

Modify LeftArraySelector and RightArraySelector to support index == len

---

.github/workflows/forge-stable.yaml

Forge stable, in case of failure always needs to run
Test Pla: job runs on PR

[gha] Fix conditional scheduling in forge stable

---

third_party/move/move-compiler-v2/src/experiments.rs
third_party/move/move-compiler-v2/src/file_format_generator/mod.rs
third_party/move/move-compiler-v2/src/lib.rs
third_party/move/move-compiler-v2/tests/testsuite.rs
third_party/move/tools/move-package/src/compilation/compiled_package.rs

Currently, V2 compiler uses the model generated by V1 for the extended_check. This PR adds the logic to attach compiled module to the move model generated by V2 so that it can be used for the extended check.
close #12914
Existing tests still pass. 
The following flamegraphs are generated by running "aptos move compile --compiler-version=v2" from the folder `aptos-move/framework/aptos-framework`
flamegraph before change:
flamegraph after change:
Execution time before change: 1.2s.
Execution time after change: 0.7s.
The logic to attach the compiled module to move model when generating the bytecode.

Use model generated by V2 in extended_check

---

aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__borrow_after_move.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__change_after_move.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__move_from_across_blocks.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_bad_sig_function_dep.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_code_unverifiable.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_nested_type_argument_module_does_not_exist.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_non_existing_function_dep.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_none_existing_module_dep.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_type_argument_module_does_not_exist.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_arbitrary_script_execution.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_script_dependency_fails_verification.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_script_transitive_dependency_fails_verification.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_type_tag_dependency_fails_verification.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_type_tag_transitive_dependency_fails_verification.exp
types/src/state_store/state_key.rs

prepare to change the internals of StateKey
unit test

Make StateKey debug output leaner, hiding the internal details.

---

keyless/circuit-data/.gitignore
keyless/circuit-data/install-keys-for-testing-prover-service.sh
keyless/circuit-data/templates/update_ctags.sh

Shell scripts for testing/tag generation

---

aptos-move/aptos-release-builder/data/release.yaml

Corrected the gas feature version for the step 1

Update release.yaml for v1.11

---

.github/workflows/docker-build-test.yaml

fix compat base

---

.github/workflows/forge-stable.yaml

extra base image fix

---

aptos-move/framework/aptos-framework/doc/delegation_pool.md
aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
aptos-move/framework/aptos-framework/sources/delegation_pool.move
aptos-move/framework/aptos-framework/sources/object.move
aptos-move/framework/aptos-framework/sources/primary_fungible_store.move

[event] hotfix of event migration

---

keyless/circuit-data/templates/helpers/hashtofield.circom
keyless/circuit-tests/src/hash_to_field.rs
keyless/circuit-tests/src/lib.rs

initial `hash_bytes_to_field_with_len` tests and `TestCircuitHandle` constructors from direct circom src

---

crates/aptos-crypto/src/poseidon_bn254.rs
keyless/circuit-tests/src/hash_to_field.rs

hash to field tests remaining

---

Cargo.lock
mempool/Cargo.toml
mempool/src/shared_mempool/runtime.rs
vm-validator/Cargo.toml
vm-validator/src/vm_validator.rs

Cherry-pick of https://github.com/aptos-labs/aptos-core/pull/13091

[Mempool] Use a pool of VMs for transaction validation (#13091)

---

storage/aptosdb/src/utils/truncation_helper.rs

should consider the edge case where current_version == traget_version while there is data written ahead of the progress

fix kv truncate further

---

crates/aptos/homebrew/README.md

Update homebrew README.md

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Updates changelog and preps release for today.
CI
This is just a changelog update for the release

[cli] Release 3.2.0

---

keyless/circuit-data/templates/helpers/misc.circom
keyless/circuit-data/templates/tests/misc/email_verified_check_test.circom
keyless/circuit-tests/src/misc.rs

Add EmailVerifiedCheck test

---

keyless/circuit-tests/src/misc.rs

Sample Frs from whole range instead of just from u64 range

---

README.md

- Update outdated links
https://twitter.com/Aptos
outdated

[readme] Update outdated links

---

aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/doc/vesting.md
aptos-move/framework/aptos-framework/sources/coin.move
aptos-move/framework/aptos-framework/sources/vesting.spec.move

[coin migration] deterministic address of paired FA metadata object

---

third_party/move/move-vm/runtime/src/interpreter.rs

[move-vm]Fix error reporting

---

third_party/move/move-vm/runtime/src/interpreter.rs

Fix the error reporting logic on new frame creation.
Use replay to re-execute the txn.
N/A

[move-vm] Fix error reporting

---

Cargo.lock
crates/aptos-rest-client/src/lib.rs
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml
crates/aptos/src/account/multisig_account.rs
crates/aptos/src/common/types.rs
crates/aptos/src/governance/delegation_pool.rs
crates/aptos/src/governance/mod.rs

This unlocks a larger set of possible inputs, and makes the experience seamless similar to entry functions
Manual testing for Aptos names options.

[cli] Switch view functions to use BCS for arguments

---

aptos-node/src/lib.rs
aptos-node/src/network.rs
aptos-node/src/services.rs
aptos-node/src/state_sync.rs
config/src/config/mod.rs
config/src/config/node_config.rs
config/src/config/observer_config.rs
config/src/config/state_sync_config.rs
consensus/consensus-types/src/pipelined_block.rs
consensus/src/consensus_observer/mod.rs
consensus/src/consensus_observer/network.rs
consensus/src/consensus_observer/observer.rs
consensus/src/consensus_observer/publisher.rs
consensus/src/consensus_provider.rs
consensus/src/epoch_manager.rs
consensus/src/lib.rs
consensus/src/payload_manager.rs
consensus/src/pipeline/buffer_manager.rs
consensus/src/pipeline/decoupled_execution_utils.rs
consensus/src/pipeline/execution_client.rs
consensus/src/pipeline/tests/buffer_manager_tests.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/state_computer.rs
consensus/src/twins/twins_node.rs
network/framework/src/protocols/wire/handshake/v1/mod.rs
state-sync/state-sync-driver/src/driver.rs
testsuite/generate-format/tests/staged/network.yaml

[observer] initial commit

---

api/src/transactions.rs

This is a quick fix for making simulation with with fungible assets as gas.  Uses the view function instead of the resource lookup for gas.
This could add some performance hit, which I have not measured, and we may want to look at just two resource lookups instead.
CI or bust

[api] Fix simulation API for fungible assets as gas

---

config/src/config/quorum_store_config.rs
consensus/src/quorum_store/batch_coordinator.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/quorum_store/tests/batch_generator_test.rs
testsuite/forge-cli/src/main.rs
testsuite/testcases/src/public_fullnode_performance.rs

We filter txns seen from a remote batch for a short time (~500ms). This reduces duplicate txns created in an adversarial client/PFN scenario -- when transactions are duplicated to all VFNs.
Builds on #13007
Added the new forge test pfn_spam_duplicates and observed performance

[quorum store] filter txns seen in remote batches on batch creation

---

aptos-move/move-examples/large_packages/large_package_example/sources/six.move
third_party/move/move-bytecode-verifier/transactional-tests/tests/stack_usage_verifier/multiple_return_values_extra_value.mvir
third_party/move/move-prover/lab/README.md

Add the missing single quota mark in words

Add the missing single quota mark in words

---

consensus/src/quorum_store/batch_generator.rs

Accidentally landed #13019 with local changes not committed.
All CICD tests

[quorum store] fix last commit in #13019

---

aptos-move/e2e-move-tests/src/tests/metadata.rs
aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
aptos-move/framework/src/module_metadata.rs

Cherry-pick the metadata fix PR #13236 onto main

[compiler-v2] Cherry-pick #13236 onto main

---

crates/aptos/src/update/aptos.rs
crates/aptos/src/update/mod.rs
crates/aptos/src/update/revela.rs

Adds the ability to check your version, without updating.
Resolves https://github.com/aptos-labs/aptos-core/issues/13266
Manually tested
Setting to 3.3.0
```bash
./target/debug/aptos update aptos --check
{
"Result": "Already up to date (3.3.0)"
}
```
Setting to 3.0.0
```bash
./target/debug/aptos update aptos --check
{
"Result": "Update is available (3.3.0)"
}
```
...

[cli] Add update --check for checking version of the latest

---

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account.exp
aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/sources/aptos_account.move
aptos-move/framework/aptos-framework/sources/coin.move
aptos-move/framework/aptos-framework/sources/multisig_account.move
aptos-move/framework/aptos-framework/sources/resource_account.move
aptos-move/framework/aptos-framework/sources/stake.move
aptos-move/move-examples/dao/nft_dao/sources/nft_dao.move
aptos-move/move-examples/defi/sources/locked_coins.move
aptos-move/move-examples/drand/sources/lottery_test.move
aptos-move/move-examples/resource_account/sources/simple_defi.move
aptos-move/move-examples/shared_account/sources/shared_account.move

We ever allow creation of `CoinStore<0x1::string::String>`. We have to fix this.

Disallow creation of CoinStore<NOT_COIN_TYPE> and also migration of it

---

testsuite/single_node_performance.py

calibration seems off, failing workflows
single-node-performance test

tune single-node-performance expected_tps

---

api/src/transactions.rs
aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/borrow_in_loop.exp
aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/diamond_clicker.exp
aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-move-tests/src/tests/code_publishing.rs
aptos-move/e2e-move-tests/src/tests/fee_payer.rs
aptos-move/e2e-move-tests/src/tests/vm.rs
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_bad_sig_function_dep.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_code_unverifiable.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_nested_type_argument_module_does_not_exist.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_non_existing_function_dep.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_none_existing_module_dep.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_type_argument_module_does_not_exist.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_arbitrary_script_execution.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_script_dependency_fails_verification.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_script_transitive_dependency_fails_verification.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_type_tag_dependency_fails_verification.exp
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_type_tag_transitive_dependency_fails_verification.exp
aptos-move/e2e-tests/src/executor.rs
storage/aptosdb/src/db/include/aptosdb_reader.rs
testsuite/single_node_performance.py
types/src/on_chain_config/aptos_features.rs
types/src/proof/definition.rs
types/src/transaction/mod.rs

for v1.12 testnet release
Before the feature is on
transaction https://explorer.aptoslabs.com/txn/1319701?network=devnet
Move abort in 0x1::from_bcs: EINVALID_UTF8(0x10001): UTF8 check failed in conversion from bytes to string  [with detail error]
Run governance proposal to enable the feature https://explorer.aptoslabs.com/txn/1325739?network=devnet
We still have the error details as expected. Devnet is also running healthy https://explorer.aptoslabs.com/txn/1327821?network=devnet

[storage] turn on feature flag for remove_detailed_error_from_hash

---

types/src/dkg/real_dkg/rounding/tests.rs

fix flaky rounding tests

---

storage/aptosdb/src/db/fake_aptosdb.rs
storage/aptosdb/src/db/include/aptosdb_reader.rs
storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/jellyfish-merkle/src/lib.rs
storage/jellyfish-merkle/src/node_type/mod.rs
storage/scratchpad/src/sparse_merkle/mod.rs
storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
storage/scratchpad/src/sparse_merkle/updater.rs
storage/storage-interface/src/async_proof_fetcher.rs
storage/storage-interface/src/cached_state_view.rs
storage/storage-interface/src/lib.rs
storage/storage-interface/src/mock.rs
types/src/proof/definition.rs

During execution, much of the proof is known info already on the in-mem
SMT. This changes it so that only the unknown parts of the proofs are
requested, saving much duplicated hashing required to calculate the
internal (binary SMT) nodes compressed out by the JMT node.
This command (on 100M items DB) sees ~8% TPS improvement (24500 -> 26500):
```
cargo run -p aptos-executor-benchmark --profile performance -- --generate-then-execute --transactions-per-sender 1 --block-size 10000 --enable-storage-sharding --enable-state-pruner --enable-ledger-pruner --enable-epoch-snapshot-pruner --ledger-pruning-batch-size 10000 --state-prune-window 3000000 --epoch-snapshot-prune-window 3000000 --ledger-prune-window 3000000 --execution-threads 48 run-executor --data-dir /home/msmouse/work/data/temp/100M …
```

partial state proofs

---

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json
aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account.exp
aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/sources/genesis.move
crates/transaction-emitter-lib/src/emitter/mod.rs
testsuite/single_node_performance.py

devnet should have it enabled by default.
extracting from not-yet-reviewed https://github.com/aptos-labs/aptos-core/pull/13194

enable APT coin <-> FA mapping in genesis

---

aptos-move/aptos-release-builder/data/enable-randomness.yaml
aptos-move/aptos-release-builder/data/proposals/enable_randomness_api_v0.move

enable randomness

---

.github/workflows/docker-build-test.yaml
.github/workflows/forge-stable.yaml
aptos-move/aptos-release-builder/data/release.yaml

update version for main

---

consensus/consensus-types/src/pipeline/commit_decision.rs
consensus/consensus-types/src/sync_info.rs
storage/schemadb/src/iterator.rs

cherry-pick https://github.com/aptos-labs/aptos-core/pull/13341

[cherry-pick][1.13] schemadb: make iterator lazy #13341

---

consensus/consensus-types/src/sync_info.rs
consensus/src/pipeline/execution_client.rs

https://github.com/aptos-labs/aptos-core/pull/13341 updated after cherry-pick https://github.com/aptos-labs/aptos-core/pull/13351 landed

[cherry-pick][1.13] fix #13341 cherry-pick

---

consensus/consensus-types/src/pipeline/commit_decision.rs
consensus/src/pipeline/execution_client.rs
storage/schemadb/src/iterator.rs

cherry-pick https://github.com/aptos-labs/aptos-core/pull/13341

[cherry-pick][1.12] schemadb: make iterator lazy #13341

---

aptos-move/aptos-release-builder/data/keyless.yaml
aptos-move/aptos-release-builder/data/proposals/keyless_initialization.move

- Initialize VK and Configuration before feature flag flip.
- Fix `execution_mode` in yaml.

augment keyless release

---

Cargo.lock
consensus/src/dag/tests/integration_tests.rs
consensus/src/network.rs
consensus/src/network_tests.rs
consensus/src/round_manager_test.rs
consensus/src/twins/twins_node.rs
mempool/src/shared_mempool/coordinator.rs
mempool/src/tests/mocks.rs
mempool/src/tests/node.rs
mempool/src/tests/test_framework.rs
network/benchmark/src/lib.rs
network/builder/src/builder.rs
network/builder/src/dummy.rs
network/framework/Cargo.toml
network/framework/src/application/storage.rs
network/framework/src/application/tests.rs
network/framework/src/connectivity_manager/mod.rs
network/framework/src/connectivity_manager/test.rs
network/framework/src/peer_manager/builder.rs
network/framework/src/peer_manager/conn_notifs_channel.rs
network/framework/src/peer_manager/mod.rs
network/framework/src/peer_manager/tests.rs
network/framework/src/peer_manager/types.rs
network/framework/src/protocols/health_checker/interface.rs
network/framework/src/protocols/health_checker/mod.rs
network/framework/src/protocols/health_checker/test.rs
network/framework/src/protocols/network/mod.rs
network/framework/src/testutils/test_node.rs
peer-monitoring-service/server/src/tests.rs
state-sync/storage-service/server/src/tests/mock.rs

This reverts commit f5de7609d50860e42b4b2dcd72e968cd6c57071e.

Revert "Event simplification conn subs (#12730)"

---

third_party/move/move-vm/integration-tests/Cargo.toml

Close #13345 by adding `features = ["testing"]` to the dependency `move-binary-format` specified in `Cargo.toml` of `third_party/move-vm/integration-tests`.
All tests pass when running `cargo test -p move-vm-integration-tests --lib`.

[Compiler-v2][trivial] Add `features = ["testing"]` to `move-binary-format` for third_party/move-vm/integration-tests

---

consensus/src/network.rs
consensus/src/payload_client/mixed.rs
consensus/src/quorum_store/types.rs

when not all features are enabled, warnings are given.

clean up compile warnings

---

aptos-move/framework/aptos-token/doc/token_transfers.md
aptos-move/framework/aptos-token/sources/token_transfers.move

fix v1.13 release. Making it compatible with v1.12

[fix] make v1.13 compatible with v1.12

---

aptos-move/framework/aptos-token/doc/token_transfers.md
aptos-move/framework/aptos-token/sources/token_transfers.move

This file was overlooked in the previous release with wrong attribute. Now it cannot be removed because it's on testnet already.

[cherry-pick] Quick fix v1.13 to add back #[event]

---

aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/bad_parameter.exp
aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/randomness_safety.exp
aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/randomness_safety.move
aptos-move/aptos-transactional-test-harness/tests/v2-tests/bad_parameter.exp
aptos-move/e2e-move-tests/src/tests/randomness.data/pack/sources/test.move
aptos-move/framework/aptos-framework/doc/randomness.md
aptos-move/framework/aptos-framework/sources/randomness.spec.move
aptos-move/framework/src/extended_checks.rs
aptos-move/move-examples/on_chain_dice/sources/dice.move
crates/aptos/CHANGELOG.md
third_party/move/move-compiler/src/parser/syntax.rs

This adds checks to the extended checker for safe usage of randomness.
- Public functions which directly or indirectly call into the `randomness` module are flagged as an error. Exempted functions are those which have the `#[lint_allow_unsafe_randomness]` attribute or which are in the framework at address 0x1.
- Private or friend entry functions which do not have the `#[randomness]` attribute are flagged as an error.
We do not need to check dynamic dispatch here since only public functions are allowed to be registered for dispatch, and those are already checked via above logic.
Added Aptos transactional tests
Consistency of the checks.

[extended checker] Add checks for safe randomness usage

---

aptos-move/move-examples/large_packages/large_package_example/sources/five.move
ecosystem/typescript/sdk/SPEC.md
ecosystem/typescript/sdk/src/indexer/codegen.yml
ecosystem/typescript/sdk/src/providers/indexer.ts
ecosystem/typescript/sdk/src/utils/api-endpoints.ts

Supersedes https://github.com/aptos-labs/aptos-core/pull/12231.
CI
If I missed any spots.

Use indexer API via API Gateway throughout codebase

---

consensus/src/block_storage/block_store.rs
consensus/src/block_storage/mod.rs
consensus/src/block_storage/pending_blocks.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/counters.rs
consensus/src/epoch_manager.rs
consensus/src/pipeline/commit_reliable_broadcast.rs
consensus/src/recovery_manager.rs
consensus/src/round_manager.rs
consensus/src/round_manager_fuzzing.rs
consensus/src/round_manager_test.rs
consensus/src/test_utils/mod.rs
crates/reliable-broadcast/src/lib.rs

[consensus] shortcut the block retrieval with local buffer

---

aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
third_party/move/move-bytecode-verifier/transactional-tests/tests/reference_safety/call_function_with_many_acquires.v2_exp
third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/signer_write_ref.v2_exp
third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/type_error_after_branch.v2_exp
third_party/move/move-model/src/builder/exp_builder.rs

This PR fixes https://github.com/aptos-labs/aptos-core/issues/13250 by using iteration to handle Seq(exp) in the function `translate_seq_recursively`.
Note that this PR basically tries to resolve the same issue that the PR #13436 but uses a different approach. Not sure which ways to go.
Existing tests pass and the test third_party/move/move-bytecode-verifier/transactional-tests/tests/reference_safety/call_function_with_many_acquires does not overflow with MOVE_COMPILER_V2 set to true.
Also tested by the following script:
```
for value in false true; do 
UB=1 MOVE_COMPILER_V2=$value cargo test \
-p "aptos-transactional-test-harness" \
-p "bytecode-verifier-transactional-tests" \
-p "move-async-vm" \
-p "move-cli" \
-p "move-model" \
-p "move-package" \
-p "move-prover-bytecode-pipeline" \ …
```

[Compiler-v2] handle the case Seq(exp) iteratively in translate_seq_recursively

---

api/types/src/convert.rs
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
storage/aptosdb/src/db/include/aptosdb_reader.rs
types/src/proof/definition.rs
types/src/transaction/mod.rs

Remove the incorrect injection of error detail

---

third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs
third_party/move/move-compiler-v2/tests/ability-transform/borrowed_from_one_path.exp
third_party/move/move-compiler-v2/tests/ability-transform/by_reference.exp
third_party/move/move-compiler-v2/tests/ability-transform/copy_ability_tuple.exp
third_party/move/move-compiler-v2/tests/ability-transform/dead_but_borrowed.exp
third_party/move/move-compiler-v2/tests/ability-transform/destroy_after_call.exp
third_party/move/move-compiler-v2/tests/ability-transform/drop_after_loop.exp
third_party/move/move-compiler-v2/tests/ability-transform/foreach_mut_expanded.exp
third_party/move/move-compiler-v2/tests/ability-transform/mutate_return.exp
third_party/move/move-compiler-v2/tests/ability-transform/mutate_vector.exp
third_party/move/move-compiler-v2/tests/abort-analysis/drop_on_abort.exp
third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/mutable_borrow_invalid.exp
third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/mutable_borrow_invalid.no-opt.exp
third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/mutable_borrow_invalid_2.exp
third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/mutable_borrow_invalid_2.move
third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/mutable_borrow_invalid_2.no-opt.exp
third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_field_combo.exp
third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/borrow_field_combo.no-opt.exp

Fixes #12904
A weak borrow results from branching like `let r = if (cond) &mut r.f else &mut r.g`. The resulting reference `r` can be derived from either of the two borrows. The borrow safety check until now did not correctly deal with weak borrows when constructing hyper edges. This PR fixes the issue by grouping edges which target the same node into one hyper edge.
The 1st commit is only a change in annotation output, the 2nd is the relevant one for the change.
Some more new errors are produced in baseline output which haven't been flagged before, but those appear reasonable.
Existing test, isolated failing case into new test

[compiler-v2] Fixes bug in reference safety regards weak borrow relations

---

aptos-move/aptos-release-builder/data/enable-randomness.yaml

Enable randomness without gas deposit and undergasing attack prevention.

randomness proposal update

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml
crates/aptos/src/node/local_testnet/hasura_metadata.json
crates/aptos/src/node/local_testnet/processors.rs

* update the localnet dependencies.
* Metadata can be found here: https://github.com/aptos-labs/aptos-indexer-processors/blob/main/hasura-api/metadata-json/unified.json
Run some queries and it looks good
example

update the localnet dependencies.

---

aptos-move/e2e-move-tests/src/tests/randomness_test_and_abort.rs
types/src/on_chain_config/randomness_api_v0_config.rs

For randomness txns, disable gas deposit by default, since there's currently no good way to prevent undergasing attacks.
n/a

update rnd api v0 config for genesis

---

Cargo.lock
Cargo.toml

rust-rocksdb 0.2.1 -> 0.2.2, among other things, now we have add_compact_on_deletion_collector_factory()
build
- [] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc

update rocksdb dependency

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Bump CLI version to 3.4.0 for release

---

aptos-move/framework/aptos-framework/doc/keyless_account.md
aptos-move/framework/aptos-framework/sources/keyless_account.move

skip vk verification

---

aptos-move/framework/aptos-framework/doc/staking_config.md
aptos-move/framework/aptos-framework/sources/configs/staking_config.move
aptos-move/framework/aptos-framework/sources/configs/staking_config.spec.move

This PR adds a view function for getting the current stake reward rate

[Framework] Add a view function for getting the current staking reward rate

---

.github/ISSUE_TEMPLATE/config.yml
CODEOWNERS

Update issue template to have dev discussions links, cleanup CODEOWNERS

---

aptos-move/framework/aptos-framework/doc/keyless_account.md
aptos-move/framework/aptos-framework/sources/keyless_account.move

skip bn254 verification in vk update in 1.14

---

aptos-move/framework/aptos-framework/doc/keyless_account.md
aptos-move/framework/aptos-framework/sources/keyless_account.move

skip bn254 verification in vk update in 1.13

---

aptos-move/aptos-release-builder/data/enable_dispatchable_fungible_asset.yaml

Add yaml for enabling AIP-73

---

aptos-move/framework/aptos-token-objects/doc/token.md
aptos-move/framework/aptos-token-objects/sources/token.move

Cherry pick for PR: https://github.com/aptos-labs/aptos-core/pull/13550
- Add collection creator assertion prior to token creation.

Assert collection creator prior to token creation

---

aptos-move/aptos-vm/src/aptos_vm.rs

[Link to PR](https://github.com/aptos-labs/aptos-core/pull/13441)

Cherry-pick keyless txn simulation fix in v1.13 

---

testsuite/forge-cli/src/main.rs

[forge] reduce haproxy mempool backlog

---

aptos-move/framework/aptos-framework/doc/fungible_asset.md
aptos-move/framework/aptos-framework/sources/fungible_asset.move

Add getter for icon uri and project uri in FA

---

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs

This lowers the gas schedule fee of keyless transactions to 32_000_000 to be more in line with the latest performance benchmarks comparing keyless to ed25519 for p2p txns.

Lower the gas cost of Keyless txns to 32_000_000

---

types/src/on_chain_config/consensus_config.rs

Enable order vote feature at genesis

Enable order vote feature at genesis

---

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs

[Original PR](https://github.com/aptos-labs/aptos-core/pull/13574)

Cherrypick Keyless gas schedule change to 32_000_000 in v1.13

---

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs

[Original PR](https://github.com/aptos-labs/aptos-core/pull/13574)

 Cherrypick Keyless gas schedule change to 32_000_000 in v1.14

---

testsuite/forge-cli/src/main.rs
testsuite/forge/src/backend/k8s/prometheus.rs
testsuite/forge/src/success_criteria.rs

Fix forge stable and some recalibration

---

Cargo.lock
crates/aptos-telemetry-service/src/clients/mod.rs
crates/aptos-telemetry-service/src/lib.rs

[telemetry-svc] optional bearer token for metrics client

---

storage/backup/backup-cli/src/metadata/cache.rs

It's possible to hit a download error while the compactor is deleting old files. It's safe to ignore because either the metadata is in a newer file or the program will complain later if there's gaps in the backups.
build

backup-cli: ignore metadata file download failure

---

crates/aptos-drop-helper/src/lib.rs
experimental/storage/layered-map/src/lib.rs
experimental/storage/layered-map/src/tests.rs
storage/scratchpad/src/sparse_merkle/mod.rs
storage/scratchpad/src/sparse_merkle/node.rs
storage/scratchpad/src/sparse_merkle/test_utils/proptest_helpers.rs
storage/scratchpad/src/sparse_merkle/updater.rs

So that we don't need to `impl Value` for things contained in the map.
build

[experimental] LayeredMap: refine trait requirements

---

aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/sources/object.move

[framework] Rename ENOT_MOVABLE to EOBJECT_NOT_TRANSFERRABLE

---

.github/workflows/windows-build.yaml
scripts/windows_dev_setup.ps1

This PR fixes the windows builder such that it installs the developer tools before building the Aptos CLI. It appears the script was modified  in #7607 to take in an command line argument to install either the tools or move prover, however the builder script was never modified. Therefore, we never installed the developer tools via the script and just used system installed ones. Recently [Github](https://github.com/actions/runner-images/commit/a615999e85d5b3f3853c691cd59fcfe89f0495ae) updated the base image which changed the default installed tools on the builder and that broke the Rust CLI builds.

[gha] upgrade and fix windows builder

---

.github/workflows/windows-build.yaml

[gha][fix] fix windows build workflow

---

api/types/src/convert.rs
storage/aptosdb/src/db/aptosdb_test.rs
storage/aptosdb/src/db/include/aptosdb_reader.rs
storage/aptosdb/src/ledger_db/transaction_auxiliary_data_db.rs
storage/storage-interface/src/lib.rs

we see warning of API errors due to the API returns error if it doesn't exist
https://aptoslabs.grafana.net/d/storage/storage-details?orgId=1&var-Datasource=fHo-R604z&var-metrics_source=All&var-chain_name=testnet&var-cluster=All&var-namespace=All&var-kubernetes_pod_name=All&var-role=All&var-cf_name=All&var-api_name=All&var-timer_name=All&var-db_name=All&var-rocksdb_property_name=All&viewPanel=3468

[storage] return none if non exist

---

api/types/src/convert.rs
storage/aptosdb/src/db/aptosdb_test.rs
storage/aptosdb/src/db/include/aptosdb_reader.rs
storage/aptosdb/src/ledger_db/transaction_auxiliary_data_db.rs
storage/storage-interface/src/lib.rs

Cherry pick 1387de8265a7b0feefc91621e030a2e6a732371b

---

consensus/src/payload_manager.rs

Remove duplicate prefetching

---

api/src/tests/multisig_transactions_test.rs
aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/sources/coin.move

We haven't turned on the feature but yesterday @rtso really wants coin events v2 to get rid of `phantom` type in the name for indexing. I agree this is a legit asking.

[event v2] refactor coin events requested by indexer team

---

Cargo.lock
storage/backup/backup-service/Cargo.toml
storage/backup/backup-service/src/handlers/bytes_sender.rs
storage/backup/backup-service/src/handlers/mod.rs
storage/backup/backup-service/src/handlers/utils.rs

New BytesSender makes all interfaces synchronous so the sender loop can be moved to another thread (`spawn_blocking()`)
This enables easier parallelization in the synchronous world as well (https://github.com/aptos-labs/aptos-core/pull/13653)
tests and deployed on testnet -- performs the same as before.

New BytesSender that does the sync - async world adaption

---

.github/workflows/replay-verify.yaml

https://github.com/aptos-labs/aptos-core/actions/runs/9552833781

[replay] reduce the frequency

---

.github/workflows/replay-verify.yaml

Cherry pick replay-verify change

---

aptos-node/src/network.rs
consensus/src/dag/tests/integration_tests.rs
consensus/src/network_tests.rs
consensus/src/round_manager_test.rs
consensus/src/twins/twins_node.rs
mempool/src/tests/mocks.rs
mempool/src/tests/node.rs
mempool/src/tests/test_framework.rs
network/builder/src/builder.rs
network/builder/src/dummy.rs
network/framework/src/application/tests.rs
network/framework/src/protocols/health_checker/test.rs
network/framework/src/protocols/network/mod.rs
peer-monitoring-service/server/src/tests.rs
state-sync/storage-service/server/src/tests/mock.rs

[network] make parallel deserialization in-order

---

.github/actionlint.yaml
.github/workflows/cli-e2e-tests.yaml
.github/workflows/coverage-move-only.yaml
.github/workflows/coverage.yaml
.github/workflows/docker-build-rosetta.yaml
.github/workflows/faucet-tests-main.yaml
.github/workflows/faucet-tests-prod.yaml
.github/workflows/find-packages-with-undeclared-feature-dependencies.yaml
.github/workflows/indexer-grpc-integration-tests.yaml
.github/workflows/keyless-circuit-daily-test.yaml
.github/workflows/lint-test.yaml
.github/workflows/move-test-compiler-v2.yaml
.github/workflows/node-api-compatibility-tests.yaml
.github/workflows/prover-daily-test.yaml
.github/workflows/run-gas-calibration.yaml
.github/workflows/rust-client-tests.yaml
.github/workflows/ts-sdk-e2e-tests.yaml

Reverts aptos-labs/aptos-core#13658
until we understand source of flakyness https://aptos-org.slack.com/archives/C03PKBQM2RY/p1718735296062229

Revert "switch high-perf-docker to runs-on.com runners"

---

scripts/dev_setup.sh

The script appears to have been un-deprecated.

Use official nodesource repository setup script

---

consensus/src/pipeline/tests/buffer_manager_tests.rs

Fixes the buffer_manager_test to compare all blocks instead of last block in pipelined block. This ensures that block are compared even if the buffer manager outputs multiple blocks at once.

[consensus][buffer_manager_test] compare all ordered blocks

---

aptos-move/aptos-release-builder/data/enable_order_votes.yaml

Add the yaml to enable order votes.

Add release.yaml to enable order votes

---

keyless/common/src/input_processing/bits.rs

fix doc error

---

aptos-move/aptos-release-builder/data/enable_aggregator_is_at_least.yaml
aptos-move/aptos-release-builder/data/enable_concurrent_fungible_balance.yaml
aptos-move/aptos-release-builder/data/enable_native_object_derived_address.yaml

Fix feature names for 1.14 release in release yaml

---

Cargo.lock
Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/metrics.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/transaction-filter/.gitattributes
ecosystem/indexer-grpc/transaction-filter/Cargo.toml
ecosystem/indexer-grpc/transaction-filter/README.md
ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_00008bc1d5adcf862d3967c1410001fb_705101000.pb.lz4
ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_0013c194ec4fdbfb8db7306170aac083_445907000.pb.lz4
ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_f3d880d9700c70d71fefe71aa9218aa9_301616000.pb.lz4
ecosystem/indexer-grpc/transaction-filter/src/boolean_transaction_filter.rs
ecosystem/indexer-grpc/transaction-filter/src/errors.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/event.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/mod.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/move_module.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/transaction_root.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/user_transaction.rs
ecosystem/indexer-grpc/transaction-filter/src/lib.rs
ecosystem/indexer-grpc/transaction-filter/src/test_lib/mod.rs
ecosystem/indexer-grpc/transaction-filter/src/traits.rs

Cherry-pick upstream data service filtering commits to 1.6 branch.

Add upstream filtering to grpc 1.6

---

Cargo.lock
Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/metrics.rs
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/metrics.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/metrics.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/counters.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs
ecosystem/indexer-grpc/transaction-filter/.gitattributes
ecosystem/indexer-grpc/transaction-filter/Cargo.toml
ecosystem/indexer-grpc/transaction-filter/README.md
ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_00008bc1d5adcf862d3967c1410001fb_705101000.pb.lz4
ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_0013c194ec4fdbfb8db7306170aac083_445907000.pb.lz4
ecosystem/indexer-grpc/transaction-filter/fixtures/compressed_files_lz4_f3d880d9700c70d71fefe71aa9218aa9_301616000.pb.lz4
ecosystem/indexer-grpc/transaction-filter/src/boolean_transaction_filter.rs
ecosystem/indexer-grpc/transaction-filter/src/errors.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/event.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/mod.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/move_module.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/transaction_root.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/user_transaction.rs
ecosystem/indexer-grpc/transaction-filter/src/lib.rs
ecosystem/indexer-grpc/transaction-filter/src/test_lib/mod.rs
ecosystem/indexer-grpc/transaction-filter/src/traits.rs

Add upstream filtering to grpc 1.5

---

network/framework/src/counters.rs
network/framework/src/peer/mod.rs
network/framework/src/protocols/health_checker/mod.rs
network/framework/src/protocols/rpc/mod.rs

[cherry-pick] unblock health check and make peer actor more robust

---

.github/workflows/forge-stable.yaml
.github/workflows/replay-verify.yaml

Nightly CI run on main after this lands
This PR makes `forge-stable` match the cadence of `replay-verify`: Sun, Tues, Thurs at 22:00 UTC. This allows us to have release candidate Mon, Wed, Fri, and also ensures that both of these nightly tests only test the same RC

[forge] stable 3 times a week

---

.github/workflows/forge-stable.yaml
.github/workflows/replay-verify.yaml

Cherry-picked PR, tested on `main` https://github.com/aptos-labs/aptos-core/pull/13787

[forge] stable 3 times a week (#13787)

---

.github/runs-on.yaml

[gha][runs-on] add AMI image config

---

.github/runs-on.yml

[gha][runs-on] update AMI id

---

api/goldens/aptos_api__tests__transactions_test__test_simulation_failure_with_detail_error.json
api/goldens/aptos_api__tests__transactions_test__test_simulation_failure_with_move_abort_error_rendering.json
api/src/tests/transactions_test.rs
api/src/transactions.rs
types/src/transaction/mod.rs

1. Add golden file to simulation API detail error
2. the feature gate 
3. this also fix an issue in rendering abort error. after execution, the execution status only contains location and code. The info is injected later. In this PR, I also add this injection. More discussion see https://aptos-org.slack.com/archives/C045G5Q0V8W/p1719353100654589. The error code is not rendered.

Fix abort error rendering, add feature gate and golden test

---

aptos-move/e2e-move-tests/src/tests/access_path_test.rs
aptos-move/e2e-tests/src/executor.rs
types/src/on_chain_config/aptos_features.rs

This PR actually enables type size limits, switching from the legacy to the new bounded implementation. Once the feature is fully rolled out, the feature flag can be removed completely.

[move] Enable type size limit

---

api/goldens/aptos_api__tests__transactions_test__test_simulation_failure_with_detail_error.json
api/goldens/aptos_api__tests__transactions_test__test_simulation_failure_with_move_abort_error_rendering.json
api/src/tests/transactions_test.rs
api/src/transactions.rs
types/src/transaction/mod.rs

cherry-pick 56ca46302b934b0bb0384c1034b6c62685d82b3f

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/transaction_metadata.rs
aptos-move/aptos-vm/src/transaction_validation.rs
aptos-move/e2e-benchmark/src/main.rs
aptos-move/framework/aptos-framework/doc/transaction_validation.md
aptos-move/framework/aptos-framework/sources/transaction_validation.move
aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
testsuite/smoke-test/src/randomness/entry_func_attrs.rs

Required_deposit is not enabled, and we don't plan to enable it, so this pr cleans it up. Defense of undergasing attack is still under discussions.

[rand] cleanup unused api v1

---

.github/runs-on.yml

[runson] update AMI with rustup fix

---

mempool/src/core_mempool/mempool.rs

Calculating skipped txns in mempool accurately

Calculating skipped txns in mempool accurately

---

consensus/src/pipeline/tests/buffer_manager_tests.rs

[consensus][buffer_manager_test][bugfix] count batches properly

---

aptos-move/aptos-release-builder/data/enable_limit_vm_type_size.yaml

[testnet] Add proposal for VM type size limiting

---

consensus/src/block_storage/sync_manager.rs

[consensus] fix edge case of block retrieval

---

ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/user_transaction.rs

* Fix entry function filtering
* Comments
Cherry pick https://github.com/aptos-labs/aptos-core/pull/13867

Fix entry function filtering (#13867)

---

consensus/src/quorum_store/utils.rs

Simplify proof queue data structure

Simplify proof queue data structure

---

.github/workflows/docker-build-test.yaml
.github/workflows/forge-stable.yaml

bump forge version for 1.16

---

aptos-move/aptos-gas-schedule/src/ver.rs
aptos-move/aptos-vm-types/src/environment.rs
aptos-move/aptos-vm/src/move_vm_ext/vm.rs
third_party/move/move-vm/runtime/src/config.rs
third_party/move/move-vm/runtime/src/loader/mod.rs
types/src/vm/configs.rs

Type tag construction

---

crates/aptos/CHANGELOG.md
crates/aptos/src/common/init.rs
crates/aptos/src/common/types.rs
crates/aptos/src/common/utils.rs

Adds network to config, and adds explorer links to the output
On initialize account:
```
./target/debug/aptos init --profile my-new-account
Configuring for profile my-new-account
Enter your private key as a hex literal (0x...) [Current: None | No input: Generate new key (or keep one if present)]
No key given, generating key...
Account 0x86d447d67bb6f336fd98c0590bd90e7cc0a5b996473aaa6e89cdc6d0b6f3b9c9 doesn't exist, creating it and funding it with 100000000 Octas
Account 0x86d447d67bb6f336fd98c0590bd90e7cc0a5b996473aaa6e89cdc6d0b6f3b9c9 funded successfully
---
Aptos CLI is now set up for account 0x86d447d67bb6f336fd98c0590bd90e7cc0a5b996473aaa6e89cdc6d0b6f3b9c9 as profile …
```

Improve cli from UX feedback

---

aptos-move/framework/src/natives/cryptography/algebra/serialization.rs

The `into_affine` operation in `crypto_algebra::serialize` API should be pre-charged.
Local manual testing.
n/a

charge into_affine

---

testsuite/module_verify.py
testsuite/replay_verify.py
testsuite/verify_core/common.py

Update testnet ranges to exclude tapos transactions
Will run replay-verify manually https://github.com/aptos-labs/aptos-core/actions/runs/9714483252

update testnet ranges for replay-verify

---

crates/aptos/CHANGELOG.md
crates/aptos/src/move_tool/mod.rs
crates/aptos/src/test/mod.rs

- Fixes a description of the aptos move tool
- Adds aliases for a couple commands
- Adds templates for aptos move init
Manually tested

[cli] Various usability improvements

---

consensus/src/block_storage/block_store.rs
consensus/src/counters.rs
consensus/src/quorum_store/batch_coordinator.rs
consensus/src/quorum_store/counters.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/tests/utils.rs
consensus/src/quorum_store/types.rs
consensus/src/quorum_store/utils.rs

Revert proof queue changes (#13878), (#13703)

[1.16] Revert proof queue changes (#13878), (#13703)

---

aptos-move/framework/src/natives/cryptography/algebra/serialization.rs

cherry-picking #13893 from v1.16 branch

charge `into_affine` operation

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Bump the CLI version to 3.5.0 ahead of release.
N/A
N/A

Release CLI version 3.5.0

---

crates/aptos-telemetry-service/src/clients/mod.rs
crates/aptos-telemetry-service/src/peer_location.rs
crates/aptos-telemetry-service/src/prometheus_push_metrics.rs

Update the query used for peer location labels. The old query was missing some countries
```
cargo test -F bigquery_integration_tests -p aptos-telemetry-service --lib
```

update query used for peer location labels

---

consensus/src/rand/rand_gen/rand_manager.rs

addtl context https://aptos-org.slack.com/archives/C06TH3DH7SB/p1720511608091559

downgrade noisy on-chain randomness logs to trace level

---

ecosystem/indexer-grpc/indexer-grpc-utils/src/in_memory_cache.rs

[Indexer-grpc] Allow in mem cache to return more txns (500 -> 5000).

---

testsuite/single_node_performance.py

Also support easier recalibration with just pasting the results.

Use 32 threads in single node performance benchmark

---

config/src/config/consensus_config.rs
consensus/consensus-types/src/common.rs
consensus/consensus-types/src/request_response.rs
consensus/src/block_preparer.rs
consensus/src/consensus_observer/network_message.rs
consensus/src/consensus_observer/observer.rs
consensus/src/counters.rs
consensus/src/liveness/proposal_generator.rs
consensus/src/payload_manager.rs
consensus/src/quorum_store/direct_mempool_quorum_store.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/tests/proof_manager_test.rs
consensus/src/quorum_store/utils.rs

Proposer block size counters and usize->u64 for protocol message

---

mempool/src/core_mempool/index.rs
testsuite/forge-cli/src/main.rs

Mempool prioritizes transactions based on insertion time instead of expiration time.

Mempool prioritizes transactions based on insertion time instead of expiration time.

---

.backportrc.json
.github/workflows/backport-to-release-branches.yaml

This PR introduces a workflow to create backport/cherry-pick to release branch PRs automatically. To cherry-pick, a PR should be labeled with the version of the branch `v1.16` for `aptos-release-v1.16`, `v1.15` for `aptos-release-v1.15`, so on. The label matching is done on regex, so as long as the branch exists and the label exists, the workflow should work without modifications for all future branches. 
The catch is that this workflow can only create cherry-pick PR once the original PR is merged. I think this is okay, because we want to limit drift between two PRs so as soon as we merge to main, we have enough confidence to be accepted to release branch as well. 
The author is, however, responsible for resolving any merge conflicts before merging.
Tested this on the cicd-playground …

[gha] workflow for automatic backport PRs

---

Cargo.lock
consensus/src/quorum_store/proof_coordinator.rs
consensus/src/quorum_store/utils.rs
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml
crates/aptos/src/node/local_testnet/hasura_metadata.json
crates/aptos/src/node/local_testnet/indexer_api.rs
crates/aptos/src/node/local_testnet/processors.rs
crates/aptos/src/node/mod.rs
crates/indexer/src/models/coin_models/coin_activities.rs
crates/indexer/src/runtime.rs
crates/indexer/src/util.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs

Periodic update of the indexer API in the localnet. As part of this, I upgrade the Hasura image and switch us to use the CE image so the UI doesn't show all the enterprise features / upgrade prompts.
I had to upgrade some crates (chrono, uuid, bitflags) as part of this, since those crates have been upgraded in aptos-indexer-processors (some crates transitively depend on the different dep declarations so the versions need to have overlapping acceptable ranges). Where it made sense I actioned the deprecation warnings from chrono rather than silenced them.
```
cargo run -p aptos -- node run-localnet --force-restart --with-indexer-api --assume-yes
```
I ran the TS SDK v2 tests against it and they all passed:
```
APTOS_NODE_API_URL=http://127.0.0.1:8080/v1 …
```

Update indexer API deps in CLI to d954cf4eef9ceabdd941b2e08923fff83984b591, use CE Hasura image

---

aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/doc/fungible_asset.md
aptos-move/framework/aptos-framework/sources/coin.move
aptos-move/framework/aptos-framework/sources/fungible_asset.move

cherry-pick https://github.com/aptos-labs/aptos-core/pull/13913

[fix] make the max supply unlimited

---

.backportrc.json
.github/workflows/backport-to-release-branches.yaml

[gha] harden backport workflow and assign PRs

---

docker/compose/aptos-node/haproxy-fullnode.cfg
docker/compose/aptos-node/haproxy.cfg

This PR updates the HAProxy config file of docker compose to match the latest version (i.e., here: https://github.com/aptos-labs/internal-ops/blob/main/terraform/lib/helm/aptos-node/files/haproxy.cfg).
Note: the HAProxy config file and terraform config will be updated manually (once internal-ops is copied across with this PR: https://github.com/aptos-labs/internal-ops/pull/3726).

[HAproxy] Update the config file.

---

crates/aptos/src/move_tool/mod.rs

This PR closes #13972.
Manual test

[CLI][trivial] Add support of language version selection to `aptos move test`

---

Cargo.lock
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/keyless_validation.rs
aptos-move/aptos-vm/src/move_vm_ext/resolver.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/view.rs
aptos-move/mvhashmap/src/types.rs
aptos-move/mvhashmap/src/unsync_map.rs
third_party/move/extensions/async/move-async-vm/src/async_vm.rs
third_party/move/extensions/async/move-async-vm/tests/testsuite.rs
third_party/move/move-core/types/src/lib.rs
third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
third_party/move/move-vm/runtime/src/data_cache.rs
third_party/move/move-vm/runtime/src/move_vm.rs
third_party/move/move-vm/runtime/src/session.rs
third_party/move/move-vm/test-utils/src/lib.rs
third_party/move/move-vm/test-utils/src/storage.rs
third_party/move/move-vm/types/Cargo.toml
third_party/move/move-vm/types/src/lib.rs
third_party/move/move-vm/types/src/resolver.rs
third_party/move/testing-infra/test-generation/Cargo.toml
third_party/move/testing-infra/test-generation/src/lib.rs
third_party/move/testing-infra/transactional-test-runner/src/vm_test_harness.rs
types/src/executable.rs

Small changes picked from larger module storage PR to speed up reviewing and help landing things faster. In particular:
- Adapt `ModulePath` trait to use boolean + have a new method to construct a state key from address + module name. We need the last one because we want to implement module storage traits directly over Block-STM, so that we do not even need adapter.
- Remove `DeltaStorage` which was used for weird testing patterns, as we should not be publishing modules like that.
- Move `MoveResolver`s to VM types because 1) we can directly use concrete error type instead of an associated type, 2) only VM uses these traits and they also logically belong to the VM. Also, methods from `MoveResolver` are removed so that `ResourceResolver` and `ModuleResolver` are clearly separated.
Goals: …

[move] Minor cherrypicks for code storage

---

config/src/config/mempool_config.rs
config/src/config/quorum_store_config.rs
testsuite/forge-cli/src/main.rs
testsuite/testcases/src/lib.rs
testsuite/testcases/src/load_vs_perf_benchmark.rs
testsuite/testcases/src/two_traffics_test.rs

* [quorum store] reduce backpressure significantly for more TPS (#13558)
As Quorum Store batches are bucketed, and we are looking to increase block limits, now is the time to reduce Quorum Store backpressure.
We now allow 36K transactions outstanding. At 12K TPS, this is approximately 3 seconds worth of batches.
For forge tests, a lot of the queuing shifts from mempool to POS-to-Proposal, so the limits need to be adjusted accordingly.
* increase buffer for expiration in batch creation
* adding buffers on inner traffic as well
---------

[cherry-pick] Re-apply qs backpressure increase with buffer latency increase (#13961)

---

aptos-move/aptos-release-builder/data/enable_bn254.yaml

Release yaml to enable BN254 algebra in Move.

bn254 yaml

---

crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/emitter/submission_worker.rs
testsuite/forge-cli/src/main.rs

Using all clients when fetching latency - to not have huge latency if one/few clients are slow
Increasing resource usage for max load test.

Try fix forge stable

---

consensus/src/block_storage/block_store.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/pipeline/execution_client.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/test_utils/mock_execution_client.rs

The current variable names for highest committed/ordered were inconsistent

[consensus] some trivial code cleanup

---

consensus/src/round_manager.rs

Reduces the size of vote logs.

[consensus] reduce size of vote logs

---

.github/workflows/adhoc-forge.yaml

This should only run when the file itself is changed on PR
Test Plan:
PR test passes

[gha] Scope the PR run of adhoc forge to changes to the file itself

---

buildtools/packer/aws-ubuntu.pkr.hcl
buildtools/packer/user_data.sh

Packer config for custom AMI for runs-on workflows.

[runson] custom image packer script

---

aptos-move/framework/aptos-framework/doc/randomness.md
aptos-move/framework/aptos-framework/sources/randomness.move

Miscellaneous randomness.move fixes.
Local manual testing.
n/a

randomness.move update

---

aptos-move/aptos-release-builder/data/randomness-module-misc-fix.yaml

release yaml for a framework patch

v116 framework patch yaml

---

aptos-move/framework/aptos-framework/doc/aggregator_v2.md
aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.spec.move

This PR mocks up the new native functions of aggregator_v2.

[Prover][Spec] mock up the new native functions of aggregator_v2

---

aptos-move/e2e-move-tests/src/tests/object_code_deployment.data/pack_immutable_deps/Move.toml
aptos-move/e2e-move-tests/src/tests/object_code_deployment.data/pack_immutable_deps/sources/test_immutable_deps.move
aptos-move/e2e-move-tests/src/tests/object_code_deployment.data/pack_mutable_deps/Move.toml
aptos-move/e2e-move-tests/src/tests/object_code_deployment.data/pack_mutable_deps/sources/test_mutable_deps.move
aptos-move/e2e-move-tests/src/tests/object_code_deployment.rs
aptos-move/framework/aptos-framework/doc/code.md
aptos-move/framework/aptos-framework/sources/code.move

This PR cherry picks https://github.com/aptos-labs/aptos-core/pull/14064.

[Framework] Add dependencies check for code object freezing (#14064)

---

testsuite/forge/src/backend/k8s/fullnode.rs

Ad hoc forge: https://github.com/aptos-labs/aptos-core/actions/runs/10064091917/job/27820301908

[forge][bugfix] fix fullnode container spec

---

consensus/src/consensus_observer/network_message.rs
consensus/src/payload_manager.rs

[qs] OptQuorumStorePayload: consensus observer integration

---

Cargo.lock
crates/aptos-rosetta/Cargo.toml
crates/aptos-rosetta/src/lib.rs
crates/aptos-rosetta/src/main.rs
testsuite/smoke-test/src/rosetta.rs

These fields were used nowhere as part of some of the rush up to mainnet as a temporary fix that got removed.  This just cleans it up and removes it, and associated dependencies.

[rosetta] Remove unused input fields

---

mempool/src/shared_mempool/use_case_history.rs

Two options were equal in the test, so it was random which one was picked

[trivial] fix usecase test

---

aptos-move/aptos-release-builder/data/coin_to_fa_migration.yaml
aptos-move/aptos-release-builder/data/proposals/create_apt_mapping.move

This PR redo the coin -> fa migration again on v1.16 which failed on v1.14

enable fa migration proposal again

---

execution/executor-benchmark/src/lib.rs
execution/executor/src/tests/chunk_executor_tests.rs
execution/executor/src/tests/mod.rs
execution/executor/tests/internal_indexer_test.rs
peer-monitoring-service/server/src/tests.rs
state-sync/aptos-data-client/src/latency_monitor.rs
state-sync/state-sync-driver/src/tests/bootstrapper.rs
state-sync/state-sync-driver/src/tests/continuous_syncer.rs
state-sync/state-sync-driver/src/tests/mocks.rs
state-sync/state-sync-driver/src/utils.rs
state-sync/storage-service/server/src/tests/mock.rs
storage/aptosdb/src/backup/restore_handler.rs
storage/aptosdb/src/db/fake_aptosdb.rs
storage/aptosdb/src/db/include/aptosdb_internal.rs
storage/aptosdb/src/db/include/aptosdb_reader.rs
storage/aptosdb/src/db/include/aptosdb_writer.rs
storage/aptosdb/src/db_debugger/state_kv/get_value.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/fast_sync_storage_wrapper.rs
storage/aptosdb/src/ledger_db/ledger_metadata_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/backup/backup-cli/src/backup_types/tests.rs
storage/backup/backup-cli/src/backup_types/transaction/tests.rs
storage/indexer/src/db_indexer.rs
storage/storage-interface/src/lib.rs

Currently in many places we doin't distinguish an empty DB and DB read errors, which is problematic.
unit tests

refactor get_synced_version() to return an Option

---

.github/runs-on.yml

Add a custom image that uses a wildcard to select the latest matching image. I'm going to be iterating on the custom image so I'll be pushing new images often.
[runs-on only reads this from `main`](https://runs-on.com/features/configuration/) so I'm not able to update the runs-on image from my own branch.

[runs-on] add definition for latest image

---

config/src/config/consensus_config.rs
consensus/src/consensus_provider.rs

Increased bounded executor tasks to 16.

Increased bounded executor tasks

---

.github/runs-on.yml

Add an owner for the runs-on image. Looks like we need the owner when specifying using the image name https://runs-on.com/features/byoi
Will test on this branch after merging

add owner for runs-on image

---

crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/emitter/submission_worker.rs

[forge][txn emitter] Revert emitter latency check from multiple nodes

---

config/src/config/quorum_store_config.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/proof_manager.rs

Pull from mempool more frequently

Pull from mempool more frequently

---

crates/transaction-generator-lib/src/call_custom_modules.rs

[transaction-generator] better printing of error messages when publishing modules

---

config/src/config/consensus_config.rs
config/src/config/quorum_store_config.rs

increasing block limit for concurrency level increase

---

api/src/accounts.rs
api/src/tests/accounts_test.rs
api/src/tests/transactions_test.rs
api/src/transactions.rs
types/src/indexer/indexer_db_reader.rs

[Fix] Use correct version for API, fix tests.

---

storage/aptosdb/src/db/include/aptosdb_writer.rs
storage/aptosdb/src/db/mod.rs
storage/aptosdb/src/db_options.rs
storage/aptosdb/src/ledger_db/transaction_accumulator_db.rs
storage/aptosdb/src/schema/mod.rs
storage/aptosdb/src/schema/transaction_accumulator_root_hash/mod.rs
storage/aptosdb/src/schema/transaction_accumulator_root_hash/test.rs
storage/aptosdb/src/utils/truncation_helper.rs

[Storage] Store transaction accumulator root hash at each version directly in the database.

---

.github/workflows/forge-stable.yaml
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/emitter/stats.rs
crates/transaction-generator-lib/src/args.rs
crates/transaction-generator-lib/src/call_custom_modules.rs
testsuite/forge-cli/src/main.rs
testsuite/forge.py
testsuite/forge/src/success_criteria.rs
testsuite/testcases/src/lib.rs
testsuite/testcases/src/load_vs_perf_benchmark.rs
testsuite/testcases/src/two_traffics_test.rs

Add graceful overload forge tests - workload sweep and parallelism non-starvation test

---

config/src/config/state_sync_config.rs
testsuite/forge-cli/src/main.rs

This PR increases the default state sync chunk sizes.

[State Sync] Increase chunk sizes.

---

.github/runs-on.yml
buildtools/packer/aws-ubuntu.pkr.hcl
scripts/dev_setup.sh

Install additional dependencies in our runs-on image. These are needed by our Rust unit tests and Move compiler tests
Check if workflows for this PR are successful

update deps installed in runs-on image

---

consensus/src/block_storage/block_store.rs
consensus/src/block_storage/mod.rs
consensus/src/epoch_manager.rs
consensus/src/network.rs
consensus/src/payload_client/mod.rs
consensus/src/quorum_store/quorum_store_db.rs
consensus/src/quorum_store/tests/batch_requester_test.rs
consensus/src/quorum_store/utils.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_quorum_store_sender.rs
consensus/src/test_utils/mock_state_computer.rs

Many devs have missed these warnings, and it properly deletes or moves code to test only code.

[consensus] Remove all the warnings

---

storage/aptosdb/src/state_kv_db.rs

[Storage] Fix the state kv db shard commit metric.

---

third_party/move/move-vm/runtime/src/access_control.rs
third_party/move/move-vm/runtime/src/debug.rs
third_party/move/move-vm/runtime/src/interpreter.rs
third_party/move/move-vm/runtime/src/loader/function.rs
third_party/move/move-vm/runtime/src/loader/mod.rs
third_party/move/move-vm/runtime/src/loader/modules.rs
third_party/move/move-vm/runtime/src/loader/script.rs
third_party/move/move-vm/runtime/src/native_functions.rs
third_party/move/move-vm/runtime/src/runtime.rs
third_party/move/move-vm/runtime/src/session.rs
third_party/move/move-vm/runtime/src/tracing.rs

Replaced the `Function` struct in `interpreter.rs` and its friends with a `LoadedFunction` struct to better encapsulate function-related information and accommodate further enhancements (e.g., loader V2).
- Updated the `AccessControlState`, `DebugContext`, `Interpreter`, and other core components to use `LoadedFunction` instead of `Function`.
- Updated function calls, type checks, and error messages to reflect the new `LoadedFunction` structure.
- Refactored the `Loader` and `ModuleStorageAdapter` to incorporate the `LoadedFunction` changes for resolving and caching functions, making code somewhat cleaner.
- Refactored the `Resolver` to simply fetch scope from `LoadedFunction`.
The `LoadedFunction` struct provides a more flexible and robust representation of functions, ensuring we have …

[move] Change interpreter to use loaded func and improve scoping

---

consensus/consensus-types/src/pipelined_block.rs
consensus/src/counters.rs
consensus/src/pipeline/buffer_manager.rs

Fix execution summary being set twice, due to execution retry

---

mempool/src/core_mempool/mempool.rs
mempool/src/core_mempool/transaction_store.rs
mempool/src/counters.rs

Add counter for sender bucket frequencies in mempool

---

config/src/config/consensus_config.rs
testsuite/forge-cli/src/main.rs

Add more context to consensus config sanitizer output

---

mempool/src/core_mempool/mempool.rs
mempool/src/counters.rs

Add consensus pulled per txn counter along with bucket information

Add consensus pulled per txn counter along with bucket information

---

Cargo.lock
Cargo.toml
crates/aptos-crypto/src/hash.rs
crates/aptos-metrics-core/src/lib.rs
experimental/storage/hexy/Cargo.toml
experimental/storage/hexy/benches/sort_dedup.rs
experimental/storage/hexy/src/hashing.rs
experimental/storage/hexy/src/in_mem/base.rs
experimental/storage/hexy/src/in_mem/mod.rs
experimental/storage/hexy/src/in_mem/overlay.rs
experimental/storage/hexy/src/in_mem/view.rs
experimental/storage/hexy/src/lib.rs
experimental/storage/hexy/src/metrics.rs
experimental/storage/hexy/src/tests/mod.rs
experimental/storage/hexy/src/utils.rs
experimental/storage/layered-map/src/metrics.rs

There's the Base, the overlay, and the view -- think of them as the StateDB, the SparseMerkleTree, and the FrozenSparseMerkleTree.
This implements the updates, but not the logic of merging "committed" layers to the base (that comes next).
unit test

[experimental] hexary in-mem merkle tree

---

.github/workflows/adhoc-forge.yaml
.github/workflows/workflow-run-forge.yaml

Adds the ability to override number of validators and vfns for a given forge test. This should allow running any forge test with different network size easier without modifying code.

[gha] adhoc forge - num validator/vfn options

---

storage/indexer/src/db_indexer.rs

[Fix] Fix internal indexer progress.

---

third_party/move/move-compiler/src/parser/syntax.rs

chore(doc): amend the grammar rules docs

---

consensus/src/round_manager.rs

Removing a warning log for order votes

Removing a warning log for order votes

---

.github/workflows/docker-build-test.yaml
.github/workflows/forge-stable.yaml

update forge version for 1.17 branch cut

---

crates/aptos-telemetry-service/src/prometheus_push_metrics.rs

Put the location labels behind a feature flag so we can we can enable/disable this without changing code
CI

[telemetry-service] add feature flag for location labels

---

experimental/storage/layered-map/src/iterator.rs
experimental/storage/layered-map/src/lib.rs
experimental/storage/layered-map/src/map.rs
experimental/storage/layered-map/src/node.rs
experimental/storage/layered-map/src/tests.rs

ability to traverse the LayeredMap
unit test

[experimental] LayeredMap::iter()

---

testsuite/performance_benchmark.sh
testsuite/single_node_performance.py

Recalibrate for FA, and check for node validation

---

Cargo.lock
experimental/storage/hexy/Cargo.toml
experimental/storage/hexy/src/in_mem/base.rs
experimental/storage/hexy/src/in_mem/overlay.rs
experimental/storage/hexy/src/tests/mod.rs
experimental/storage/layered-map/src/layer.rs

(unsafe code) merge HexyOverlay into HexyBase.
The view needs to be exclusive of the bottom layer content for efficiency, but it seems a larger refactor. Will defer to a later PR.
unit test

HexyBase::merge(overlay)

---

consensus/src/rand/rand_gen/rand_manager.rs
mempool/src/shared_mempool/tasks.rs

downgrade some error logs

---

storage/aptosdb/src/db/include/aptosdb_reader.rs

[Fix] Avoid reading event beyond the synced version.

---

consensus/src/rand/rand_gen/rand_manager.rs

[Log] downgrade error to warn

---

aptos-move/aptos-release-builder/data/release.yaml

Release yaml for 1.18

---

consensus/src/quorum_store/batch_proof_queue.rs
testsuite/forge-cli/src/main.rs

A set of commits to address issues from the latest forge stable run. 
https://github.com/aptos-labs/aptos-core/actions/runs/10444079164

Fix Forge Stable

---

consensus/src/rand/rand_gen/rand_manager.rs

unsuccessful `add_certified_aug_data` should be an error.
n/a
n/a

rand manager log level update

---

crates/aptos-crypto/src/hash.rs
crates/aptos-crypto/src/unit_tests/hash_test.rs

trivial: ability rand::random::<HashValue>()

---

ecosystem/typescript/aptos-client/CHANGELOG.md
ecosystem/typescript/aptos-client/package.json

Bump aptos-cli version to 0.1.1

---

crates/aptos-metrics-core/src/lib.rs
execution/executor/src/block_executor.rs
execution/executor/src/chunk_executor.rs
execution/executor/src/metrics.rs
storage/aptosdb/src/db/include/aptosdb_internal.rs
storage/aptosdb/src/metrics.rs

In the case of a dead lock in the executor this gauge should show a constant 1.
building

log call concurrency of db and executor APIs

---

consensus/src/block_preparer.rs
consensus/src/block_storage/tracing.rs
consensus/src/counters.rs
consensus/src/execution_pipeline.rs
consensus/src/state_computer.rs
execution/executor/src/components/apply_chunk_output.rs

Add metrics to measure waiting times in execution pipeline

Add metrics for waiting times in execution pipeline

---

testsuite/forge/src/backend/k8s/swarm.rs

Fixes that drop() panics when called in async context.
unsuccessful forge run

trivial: K8sSwarm::drop not panic

---

experimental/storage/hexy/Cargo.toml
experimental/storage/hexy/benches/update.rs
experimental/storage/layered-map/Cargo.toml
experimental/storage/layered-map/benches/maps.rs

Add benchmarks for LayeredMap and Hexy

---

aptos-move/move-examples/README.md

Update README of move-examples

---

experimental/storage/layered-map/src/map/mod.rs
experimental/storage/layered-map/src/map/new_layer_impl.rs

trivial refacor: seperate LayeredMap::new_layer() code out

---

crates/transaction-emitter-lib/src/emitter/stats.rs
testsuite/forge-cli/src/main.rs
testsuite/forge/src/success_criteria.rs

to mitigate what appears to be discrepancy between machine raw performances.
forge run

[forge] add P70 latency stat

---

aptos-move/aptos-vm/src/gas.rs

Existing tests
This is just a small typo...

[vm][gas] fix typo in log message: min to max

---

consensus/src/pipeline/commit_reliable_broadcast.rs

Metrics for measuring verify time for commit votes and decision

Metrics for measuring verify time for commit votes and decision

---

testsuite/forge-cli/src/main.rs
testsuite/forge/src/runner.rs

Enable storage sharding in forge.

---

consensus/src/quorum_store/proof_manager.rs

Validators are spending between 50 to 130ms in computing remaining txns as per our [forge test](https://grafana.aptoslabs.com/goto/met0vYqSR?orgId=1). Reducing the frequency of this computation.

Reduce frequency of counting remaining txns

---

aptos-move/aptos-vm/src/errors.rs

propagate speculative error in prologue and epilogue

---

consensus/consensus-types/src/pipeline/commit_decision.rs
consensus/src/pipeline/buffer_item.rs
consensus/src/pipeline/buffer_manager.rs

deal with the edge case where buffer manager receives a LI before the round is accepted into the buffer (due to backpressure)
forge run

BufferManager::pending_commit_proofs

---

testsuite/forge-cli/src/main.rs
testsuite/forge/src/runner.rs

Reverts aptos-labs/aptos-core#14484

Revert "Enable storage sharding in forge."

---

Cargo.lock
aptos-move/block-executor/src/modules_and_scripts.rs
aptos-move/block-executor/src/proptest_types/tests.rs
aptos-move/mvhashmap/src/lib.rs
aptos-move/mvhashmap/src/versioned_code_storage.rs
aptos-move/mvhashmap/src/versioned_module_storage.rs
third_party/move/extensions/async/move-async-vm/Cargo.toml
third_party/move/move-vm/integration-tests/src/tests/bad_entry_point_tests.rs
third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
third_party/move/move-vm/runtime/Cargo.toml
third_party/move/move-vm/runtime/src/data_cache.rs
third_party/move/move-vm/runtime/src/interpreter.rs
third_party/move/move-vm/runtime/src/lib.rs
third_party/move/move-vm/runtime/src/loader/mod.rs
third_party/move/move-vm/runtime/src/move_vm.rs
third_party/move/move-vm/runtime/src/storage/dummy.rs
third_party/move/move-vm/runtime/src/storage/environment.rs
third_party/move/move-vm/runtime/src/storage/implementations/unsync_code_storage.rs
third_party/move/move-vm/runtime/src/storage/implementations/unsync_module_storage.rs
third_party/move/move-vm/runtime/src/storage/mod.rs
third_party/move/move-vm/runtime/src/storage/struct_name_index_map.rs
third_party/move/move-vm/runtime/src/storage/verified_module_cache.rs
third_party/move/move-vm/types/src/loaded_data/runtime_access_specifier.rs
types/src/vm/modules.rs

- Changed `UnsyncModuleStorage` to use a better way of traversing modules. Now the flow is almost 1:1 to whatever Block-STM is using, so it should be possible to abstract any duplication here later I hope.
- Added a few methods to `RuntimeEnvironment` to deduplicate module deserialization, paranoid checks, etc.
- Hashes are now stored together with module storage entries, so that we can cache the verification like in V1 loader. This gives a significant performance boost, as it allows cross-block caching, and skip concurrent verifications (that can be improved I guess). The verification cache is also re-used for module publishing. If the hash is the same, we can skip re-verification even if the module is republished (ideally, in the future, we can skip adding this blob completely).
- …

[loader-v2] Addressing some loader TODOs and performance issues

---

ecosystem/indexer-grpc/indexer-transaction-generator/README.md

This change is to add a readme for transaction generator.

[indexer] README for indexer testing framework

---

testsuite/forge-cli/src/main.rs
testsuite/forge/src/interface/prometheus_metrics.rs

calibrate forge

---

config/src/config/indexer_grpc_config.rs

To enable indexer we must set `table_info_service_mode: IndexingOnly` now
Ran a node with these configs set, which will be used for Forge default
```
storage:
enable_indexer: false
indexer_grpc:
enabled: true
address: 0.0.0.0:50051
processor_task_count: 32
processor_batch_size: 100
output_batch_size: 100
indexer_table_info:
table_info_service_mode: IndexingOnly
parser_task_count: 10
parser_batch_size: 100
```
The config sanitizer

[config] indexer grpc sanitizer prompts table_info_service_mode

---

Cargo.lock
crates/aptos/src/account/fund.rs
crates/aptos/src/common/types.rs
crates/aptos/src/node/local_testnet/mod.rs
crates/aptos/src/node/local_testnet/node.rs

This change is to update the node to allow indexer transaction generator to interact local 
node easily. 
* Note this change doesn't have any user-facing impact and is considered safe. It'll be covered by follow-up PRs.

Change to facilitate indexer localnode access. 

---

.github/workflows/docker-build-test.yaml
.github/workflows/forge-stable.yaml

Update base image for forge tests to v1.19.1

---

aptos-move/framework/aptos-framework/tests/compiler-v2-doc/fungible_asset.md
third_party/move/move-compiler-v2/tests/file-format-generator/index_then_field_select.exp
third_party/move/move-compiler-v2/tests/file-format-generator/index_then_field_select.move
third_party/move/move-compiler-v2/tests/file-format-generator/index_then_field_select.opt.exp
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/index.exp
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/index.move
third_party/move/move-model/src/builder/exp_builder.rs

This PR 
1) fixes bug in index notation for vector types to handle mutable reference to index notation of a vector with field selection: 
```
struct Coin(u64);
fun foo(x: vector<Coin>, index: u64) {
let p = &mut x[index].0;
...
}
```
2) supports `v[...]` when v is a reference to vector:
```
fun inc_vec_new(x: &mut vector<u256>, index: u64) {
x[index] = x[index] + 1;
}
```
Close #14608
2) Add one unit test and revise the transactional test for index notation.
Whether there are other missing cases.

[Compiler-v2] Fix bugs in index notation for vector type

---

Cargo.lock
Cargo.toml
ecosystem/indexer-grpc/indexer-transaction-generator/Cargo.toml
ecosystem/indexer-grpc/indexer-transaction-generator/README.md
ecosystem/indexer-grpc/indexer-transaction-generator/src/config.rs
ecosystem/indexer-grpc/indexer-transaction-generator/src/config_template.yaml
ecosystem/indexer-grpc/indexer-transaction-generator/src/lib.rs
ecosystem/indexer-grpc/indexer-transaction-generator/src/main.rs
ecosystem/indexer-grpc/indexer-transaction-generator/src/transaction_importer.rs

This adds the transaction importer with a centralized config. 
Unit tests and tested locally, looks good.
* example command `cargo run -- --config example.yaml --output-folder /tmp/`
* example.yaml
```
import_config:
testnet_config:
transaction_stream_endpoint: https://grpc.testnet.aptoslabs.com:443
api_key: YOUR_KEY_HERE
versions_to_import:
123: testnet_v1.json
```
* Imported transaction
```
{
"timestamp": {
"seconds": "1662686686",
"nanos": 406842000
},
"version": "123",
"info": {
"hash": "bclHbIzLfXln8ZYDTwnOcFVQ7ESU4gfbcMyOrh2m+f0=",
"stateChangeHash": "r7bhT+R9hQ/Qpzlbz7mX/6z0cV4PiVzBYsIY5KdWS8Y=",
"eventRootHash": "QUNDVU1VTEFUT1JfUExBQ0VIT0xERVJfSEFTSAAAAAA=",
"stateCheckpointHash": "zR+cbdQA2SeI6NyH/gvyb4/YP9ujVRGRaqaBd472PoI=",
"vmStatus": "Executed …
```

[EI-520] Create centralized config and transaction importer.

---

testsuite/smoke-test/src/keyless.rs
types/src/keyless/test_utils.rs

n/a
n/a
function `fedrate_keyless_scenario`.

smoke test for fed keyless

---

consensus/src/round_manager.rs
consensus/src/round_manager_test.rs
crates/reliable-broadcast/src/lib.rs
execution/executor/src/components/chunk_output.rs
network/framework/src/application/interface.rs
network/framework/src/peer/mod.rs
network/framework/src/protocols/rpc/mod.rs
state-sync/storage-service/server/src/handler.rs

cleanup warn logs

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

CLI Release 4.2.0
Adds the latest VM and compiler changes, and latest localnet updates.

[cli] Release 4.2.0

---

api/src/accounts.rs
api/src/context.rs
api/src/events.rs
api/src/index.rs
api/src/transactions.rs
api/types/src/ledger_info.rs

Use internal indexer latest version as latest ledger info

---

consensus/consensus-types/src/wrapped_ledger_info.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/counters.rs
consensus/src/pending_order_votes.rs
consensus/src/round_manager.rs

Sync up QC in order vote message

Sync up QC in order vote message

---

third_party/move/move-compiler-v2/tests/checking/variants/variants_empty.exp
third_party/move/move-compiler-v2/tests/checking/variants/variants_empty.move
third_party/move/move-model/src/builder/module_builder.rs

[compiler-v2] Disallow empty enum types

---

third_party/move/tools/move-resource-viewer/src/lib.rs

This gives me 50% tps improvement on indexer FN for the vector-picture30k benchmark.

Remove an unnecessary clone.

---

crates/aptos/src/move_tool/bytecode.rs

fix `aptos move disassemble` help message

---

aptos-move/aptos-gas-schedule/src/ver.rs
aptos-move/aptos-release-builder/data/release.yaml

release yaml for v1.19

---

.github/workflows/docker-build-test.yaml
.github/workflows/forge-stable.yaml
aptos-move/aptos-gas-schedule/src/ver.rs

- Bump Forge base image hash
- Bump gas version to 1.21

update forge version and gas version for release 1.21

---

Cargo.lock
Cargo.toml
crates/aptos-metrics-core/src/const_metric.rs
crates/aptos/Cargo.toml
crates/aptos/src/node/local_testnet/hasura_metadata.json
crates/aptos/src/node/local_testnet/processors.rs

* Use a new processor dependency that supports long  signature.
* Also we updated the hasura metadata in this change. 
* Note: per this PR https://github.com/aptos-labs/aptos-indexer-processors/pull/500, transition metadata is only used during migration; considering localnet starts from scratch, we don't need it.
Locally tested and looks good

Fix the localnet processor dependency.

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Patches the indexer processors for 4.2.0
@larry-aptos tested in previous PR #14682

[cli] Release 4.2.1

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Locally tested and it looks good.

Fix the spamming log in CLI.

---

.github/workflows/replay-verify.yaml

mainnet: max-versions-per-range: 1M -> 0.8M,
testnet: max-versions-per-range: 1.8M -> 2M
6 more jobs (30-ish machines running for slightly shorter though), 30min less total time.
https://github.com/aptos-labs/aptos-core/actions/runs/11002942898
https://github.com/aptos-labs/aptos-core/actions/runs/11000410306
test runs, see summary

Tune replay granularity for speed

---

types/src/keyless/mod.rs
types/src/keyless/openid_sig.rs

[cherry-pick] timeless hotfix (#275)

---

types/src/keyless/mod.rs
types/src/keyless/openid_sig.rs

[cherry-pick][1.19] timeless hotfix (#275)

---

execution/executor-types/src/parsed_transaction_output.rs
execution/executor/src/components/apply_chunk_output.rs
testsuite/single_node_performance.py

Too much memcpy'ing because we zip and unzip the transactions and transaction_outyputs vectors.
executor-benchmark 
seeing 40-50ms (per second) in execute_block latency with local runs.
On the PR, single node performance job sees potential improvement as well. See the second commit for calibration numbers.

[perf] optimize sort_transactions_with_state_checkpoint

---

.github/runs-on.yml

Added new runs on image for testing, included gcloud sdk and kubectl.

adding new runs on image for testing, included gcloud sdk and kubectl

---

keyless/pepper/service/src/jwk.rs

This adds pattern matching and JWK fetch support for cognito tokens in the pepper service.
Tested manually

Add Cognito support to the pepper service

---

.github/workflows/cargo-metadata-upload.yaml

Fix this: https://github.com/aptos-labs/aptos-core/commit/4f413cdc178ae3f21a52a8bfc63092f3e6241d6a#r147270353
GHA will trigger cargo metadata upload job on this PR based on the path
It ran here: https://github.com/aptos-labs/aptos-core/actions/runs/11063457885?pr=14772
See the test plan

[gha] fix cargo metadata syntax error

---

consensus/src/consensus_observer/network/observer_message.rs

This PR updates consensus observer (CO) to skip the verification of expired QS batches when verifying block payload messages and digests.
This is required because the QS payload manager filters these transactions out when returning all transactions for a given block, see:
https://github.com/aptos-labs/aptos-core/blob/b015ee41dfa89ae4fc95e4264aad1ada61ee310b/consensus/src/payload_manager.rs#L147

[Consensus Observer] Skip expired batches from verification.

---

scripts/dev_setup.sh
testsuite/smoke-test/Cargo.toml

This PR pins the `cargo-machete` version installed by `dev_setup.sh`

[Dev Setup] Pin cargo-machete version

---

execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/transaction_committer.rs
execution/executor/src/block_executor.rs
execution/executor/src/chunk_executor.rs
execution/executor/src/components/apply_chunk_output.rs
execution/executor/src/components/chunk_commit_queue.rs
execution/executor/src/components/chunk_output.rs
execution/executor/src/components/in_memory_state_calculator_v2.rs
execution/executor/src/components/mod.rs
execution/executor/src/components/transaction_chunk.rs
execution/executor/src/metrics.rs
types/src/proof/definition.rs

Removes duplicated code.
Existing coverage.

refactor: combine execute and apply chunk paths

---

Cargo.lock
storage/indexer/Cargo.toml
storage/indexer/src/db_indexer.rs
storage/indexer/src/lib.rs
storage/indexer/src/metrics.rs

Before gas version 3, the create op was modified to modification op.This leads to internal indexer missing these keys.
* Existing tests
* latency to be measured on devnet

Write statekey for both modification and creation

---

.github/workflows/docker-build-test.yaml
.github/workflows/docker-indexer-grpc-test.yaml
.github/workflows/indexer-grpc-integration-tests.yaml

Reverts aptos-labs/aptos-core#14823
The PR broke land-blocking tests on main: https://github.com/aptos-labs/aptos-core/actions/runs/11151838164

Revert "[gha] remove unused indexer tests"

---

Cargo.lock
config/src/config/consensus_config.rs
consensus/Cargo.toml
consensus/consensus-types/src/pipeline_execution_result.rs
consensus/consensus-types/src/pipelined_block.rs
consensus/consensus-types/src/quorum_cert.rs
consensus/consensus-types/src/wrapped_ledger_info.rs
consensus/safety-rules/src/safety_rules.rs
consensus/src/consensus_observer/observer/consensus_observer.rs
consensus/src/counters.rs
consensus/src/execution_pipeline.rs
consensus/src/pipeline/execution_schedule_phase.rs
consensus/src/pipeline/pre_execution_phase.rs
consensus/src/round_manager.rs
consensus/src/state_computer.rs
consensus/src/state_replication.rs
execution/executor-types/src/lib.rs
execution/executor/src/block_executor.rs
testsuite/forge-cli/src/main.rs
testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs
types/src/on_chain_config/execution_config.rs

[test] haunter + fast proposal

---

aptos-move/aptos-release-builder/data/release.yaml

v1.20 release yaml

---

execution/executor-types/src/ledger_update_output.rs
execution/executor/src/chunk_executor.rs
execution/executor/src/components/chunk_commit_queue.rs
execution/executor/src/components/chunk_output.rs
execution/executor/src/components/chunk_result_verifier.rs
execution/executor/src/components/mod.rs
execution/executor/src/components/transaction_chunk.rs
execution/executor/src/tests/mod.rs

prepare for simplifying TransactionReplayer impl
equivalency before and after the refactor

introduce ChunkResultVerifier

---

execution/executor-types/src/ledger_update_output.rs
execution/executor-types/src/lib.rs
execution/executor/src/chunk_executor.rs
execution/executor/src/components/chunk_commit_queue.rs
execution/executor/src/components/chunk_result_verifier.rs
execution/executor/src/components/executed_chunk.rs
execution/executor/src/tests/mod.rs
storage/backup/backup-cli/src/backup_types/transaction/restore.rs

1. enqueue multiple chunks for a single replay() call (renamed to enqueue_chunks) and call ledger_udpate separately from the call site.
2. remove ExecutedChunk::combine.
manual replay-verify run

simplify TransactionReplayer::replay implementation

---

storage/aptosdb/src/state_store/state_store_test.rs

We cannot handle only 2 state cases. No frozen nodes be written to the shards.

Fix flaky test

---

aptos-move/aptos-release-builder/data/release.yaml

cargo run --profile performance -p aptos-release-builder -- generate-proposals --release-config aptos-move/aptos-release-builder/data/release.yaml --output-dir output --simulate testnet
```
RemoteFile(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/aptos-labs/aptos-networks/main/gas/v1.21.1.json", query: None, fragment: None })
RemoteFile(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/aptos-labs/aptos-networks/main/gas/v1.20.0.json", query: None, fragment: None })
INCLUDING DEPENDENCY …
```

release yaml for v1.21.0

---

Cargo.lock
Cargo.toml
docker/builder/build-indexer.sh
docker/builder/indexer-grpc.Dockerfile
ecosystem/indexer-grpc/indexer-grpc-file-checker/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-file-checker/README.md
ecosystem/indexer-grpc/indexer-grpc-file-checker/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-file-checker/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-file-checker/src/processor.rs

This change adds a job that compares the file in existing gcs and the file in sharding db gcs bucket. The goal is to make sure that the sharding db migration is data safe for indexer stack.
* Next step is deployment + alerts on the counter.
Locally tested and looks good.

[indexer] Create a file checker for sharding migration

---

consensus/consensus-types/src/pipelined_block.rs

don't serialize PipelinedBlock::state_compute_result

---

aptos-move/aptos-gas-schedule/src/ver.rs

[Gas] bump gas version for 1.22

---

testsuite/forge/src/backend/k8s_deployer/deployer.rs
testsuite/forge/src/interface/prometheus_metrics.rs

Few issues found from the canary of https://github.com/aptos-labs/aptos-core/pull/14924
* Processor SDK metrics query needs to result in a single series. So take the `max` rather than `max by (bla)`
* Deployer should always pull the latest image. It defaults to `IfNotPresent`, which means new deployer profiles will not get picked up
Canary on this PR, which is possible since there are no workflow changes. Use the new `forge_indexer_sdk` profile
* run: https://github.com/aptos-labs/aptos-core/actions/runs/11390164207
* dash: https://grafana.aptoslabs.com/d/fdr6l9zgfzncwf/indexer-testing-overview-ephemeral-forge?orgId=1&from=1729188386352&to=1729188951058&var-namespace=forge-runner-1729188140
* SDK processors being used, meaning the profile was invoked correctly!

[forge] fix processor sdk integration

---

crates/aptos-drop-helper/src/async_concurrent_dropper.rs

Set the gauge on .dec() as well, so it's useful for detecting dead locks.
forge

DropHelper: fix num_tasks gauge

---

.gitignore
ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_mainnet_txns/999929475_coin_and_fa_transfers.json
ecosystem/indexer-grpc/indexer-transaction-generator/example.yaml
ecosystem/indexer-grpc/indexer-transaction-generator/example_tests/imported_transactions.yaml

Adds test transaction that includes coin and fungible asset transfers.

Add fungible asset test transaction

---

crates/aptos-push-metrics/src/lib.rs

this is to migrate to groundcover
tried with local benchmark run

Update auth header for push metrics

---

testsuite/fuzzer/fuzz.sh

While using the script, @GotenJBZ and I noticed some issues. Apparently, some paths were wrong in my commit but correct locally, so I'm fixing those to align with my working local copy.
N/A
N/A

Fix small issues in paths of fuzz.sh

---

Cargo.lock
consensus/src/quorum_store/batch_store.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/utils/truncation_helper.rs
testsuite/smoke-test/Cargo.toml
testsuite/smoke-test/src/storage.rs

[Fix][Storage] Truncate state merkle db at start so it doesn't go beyond the overall commit progress.

---

storage/aptosdb/src/versioned_node_cache.rs

Cherrypick https://github.com/aptos-labs/aptos-core/pull/15068

[v1.22] move maybe_evict_cache() off default rayon pool

---

consensus/src/epoch_manager.rs

downgrade validator not in set error to warn

---

aptos-move/e2e-move-tests/src/aggregator.rs
aptos-move/e2e-move-tests/src/tests/aggregator.rs
aptos-move/framework/aptos-framework/doc/aggregator_factory.md
aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/doc/optional_aggregator.md
aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.move
aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.spec.move
aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.move
aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.spec.move
aptos-move/framework/aptos-framework/sources/coin.move
aptos-move/framework/aptos-framework/sources/coin.spec.move
aptos-move/framework/aptos-framework/sources/genesis.move
aptos-move/framework/aptos-framework/tests/aggregator_tests.move
execution/executor/tests/internal_indexer_test.rs

* only allowing AggregatorV1 to be created with limit == u64::MAX
* only allowing optional_aggregator to be created within genesis (for coin APT total supply). removing upgrade / switch

AggregatorV1 - leave only genesis instance with no limit

---

aptos-move/framework/aptos-framework/doc/aptos_account.md
aptos-move/framework/aptos-framework/sources/aptos_account.move
aptos-move/framework/aptos-framework/sources/aptos_account.spec.move

add 3 functions as the counterparts of their coin versions.

[aptos_account] add transfer FA functions

---

aptos-move/aptos-gas-schedule/src/ver.rs

Bump up gas version for v1.23

---

Cargo.lock
aptos-move/aptos-release-builder/Cargo.toml
aptos-move/aptos-release-builder/src/validate.rs
crates/aptos/src/governance/mod.rs
types/src/account_config/events/mod.rs

fix the bug that event cannot be found as v2.

fix aptos_goverance::CreateProposal event recognition

---

ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_mainnet_txns/145959468_account_transaction.json
ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml

Add account_transaction transaction

---

Cargo.lock
aptos-move/aptos-release-builder/Cargo.toml
aptos-move/aptos-release-builder/src/validate.rs
crates/aptos/src/governance/mod.rs
types/src/account_config/events/mod.rs

cherry-pick
[fix aptos_goverance::CreateProposal event recognition (](https://github.com/aptos-labs/aptos-core/commit/2df2cf4836115a3a88746e7c53209cdf63542cf4)https://github.com/aptos-labs/aptos-core/pull/15143[)](https://github.com/aptos-labs/aptos-core/commit/2df2cf4836115a3a88746e7c53209cdf63542cf4)

[cp] fix aptos_goverance::CreateProposal event recognition

---

.github/workflows/module-verify.yaml

We have a new Mainnet S3 backup bucket.

Update Mainnet DB backup S3 bucket

---

.github/workflows/workflow-run-forge.yaml

[forge] Turn off junit until fixed

---

CODEOWNERS

Make `ecosystem-infra` the owner of protos. This can make sure the changes can be handled correctly downstream.  
n/a

Include the ecosysystem-infra team as the proto owner.

---

third_party/move/move-binary-format/src/file_format.rs
third_party/move/move-binary-format/src/lib.rs
third_party/move/move-binary-format/src/views.rs

While looking at @wrwg's closure PR, found this beauty. I think we can remove it, especially considering the TODOs left in the code.

[move] Remove SignatureTokenKind

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Making a release.
Just a version bump.
N/A

Bump CLI version to 4.4.0

---

execution/executor-types/src/state_compute_result.rs
storage/aptosdb/src/db/include/aptosdb_testonly.rs
storage/aptosdb/src/db/include/aptosdb_writer.rs
types/src/proptest_types.rs

this resulted in last state checkpoint of every chunk being persisted to db and persisted synchronously on the critical path, except the epoch endings.
epoch ending tree nodes are ephemeral, so after deploying the fix we can wait it out for fast sync to work again.
added ensuring in db code, without the fix all tests with epoch changes would fail

fix chunk_to_commit.is_reconfig

---

testsuite/smoke-test/src/fullnode.rs

smoke test flaky due to failing to get enough mem. reduce one validator to save mem
local test passed

remove one validator in test

---

aptos-move/framework/aptos-framework/doc/function_info.md
aptos-move/framework/aptos-framework/sources/function_info.spec.move

This PR adds the specification for the `function_info` module, addressing the Move Prover internal error related to the undefined native function.

[Spec] Prover specification of the function_info module

---

aptos-move/aptos-release-builder/data/release.yaml

Release yaml for v1.23.0 framework release

---

storage/aptosdb/src/db/test_helper.rs
types/src/proptest_types.rs

test data is not realistic enough and test logic needs update after reconfigs being introduced to the test data in
https://github.com/aptos-labs/aptos-core/pull/15226
flaky test fixed

fix flaky test_save_blocks

---

config/src/config/quorum_store_config.rs
consensus/src/counters.rs
consensus/src/epoch_manager.rs
consensus/src/liveness/proposal_status_tracker.rs

Metrics and logs for proposal status tracker. Also, moves `opt_qs_minimum_batch_age_usecs` to config.

[optqs] proposal status tracker metrics/logs

---

consensus/consensus-types/src/pipelined_block.rs
consensus/src/block_storage/block_tree.rs
consensus/src/counters.rs
consensus/src/pipeline/mod.rs
consensus/src/pipeline/pipeline_builder.rs

This PR introduces a new pipeline framework that's based on shared futures, aimed to provide more expressiveness and flexibility and replace the existing buffer manager & execution pipeline etc.

[pipeline] introduce new pipeline framework

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/e2e-move-tests/src/tests/mod.rs
aptos-move/e2e-move-tests/src/tests/upgrade_compatibility.rs
third_party/move/move-binary-format/src/compatibility.rs
third_party/move/move-binary-format/src/compatibility_legacy.rs
third_party/move/testing-infra/transactional-test-runner/src/vm_test_harness.rs
types/src/on_chain_config/timed_features.rs

* [compat-check] Fixes and tests for friends (#280)
* [compat-check] Fixes and tests for friends
* add tests
* add feature flag
* Add comments and cleanups
* Rename, add tests, update timestamp
* fixup! Rename, add tests, update timestamp
---------
* Update timestamp
---------

Cherrypick #280 (#282)

---

ecosystem/indexer-grpc/indexer-transaction-generator/src/config.rs

support  devnet import

---

Cargo.lock
ecosystem/nft-metadata-crawler/Cargo.toml
ecosystem/nft-metadata-crawler/migrations/2024-10-02-062003_add_asset_uploader_requests_table/up.sql
ecosystem/nft-metadata-crawler/src/asset_uploader/api/get_status.rs
ecosystem/nft-metadata-crawler/src/asset_uploader/api/mod.rs
ecosystem/nft-metadata-crawler/src/asset_uploader/api/upload_batch.rs
ecosystem/nft-metadata-crawler/src/asset_uploader/throttler/mod.rs
ecosystem/nft-metadata-crawler/src/models/asset_uploader_request_statuses.rs
ecosystem/nft-metadata-crawler/src/models/asset_uploader_request_statuses_query.rs
ecosystem/nft-metadata-crawler/src/schema.rs

[NFT Metadata Crawler] Use idempotency key + application id pattern for asset uploader

---

.github/workflows/forge-unstable.yaml

Add SDK processors to Forge unstable

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Release 4.5.0 to support AIP-80

[cli] Release 4.5.0

---

docker/builder/builder.Dockerfile

Update builder.Dockerfile for Move2

---

execution/executor/src/types/in_memory_state_calculator_v2.rs
storage/aptosdb/src/db/test_helper.rs
storage/aptosdb/src/state_store/mod.rs

The assumption has been that all things being written to must be read from the state view. However the current code doesn't ensure this assumption.

panic on state cache miss

---

crates/transaction-emitter-lib/src/emitter/local_account_generator.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/wrappers.rs
crates/transaction-emitter/src/diag.rs
testsuite/smoke-test/src/txn_emitter.rs
testsuite/testcases/src/lib.rs

keyless exebench patch

---

crates/aptos/CHANGELOG.md

We updated the version but never made a release, let's include the items we're just about to release in the changelog.
N/A
N/A

[CLI] Update CHANGELOG to include items for 4.5.0 release

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/e2e-move-tests/src/tests/mod.rs
aptos-move/e2e-move-tests/src/tests/upgrade_compatibility.rs
third_party/move/move-binary-format/src/compatibility.rs
third_party/move/move-binary-format/src/compatibility_legacy.rs
third_party/move/testing-infra/transactional-test-runner/src/vm_test_harness.rs
types/src/on_chain_config/timed_features.rs

Cherrypick #280 (#282) (#15258)

---

Cargo.lock
crates/aptos-drop-helper/Cargo.toml
crates/aptos-drop-helper/src/async_concurrent_dropper.rs
crates/aptos-drop-helper/src/lib.rs

cherry-pick https://github.com/aptos-labs/aptos-core/pull/15322 to v1.24 release branch

[cp 1.24] fix deadlock on nested DropHelper

---

consensus/src/transaction_shuffler/use_case_aware/mod.rs
crates/aptos-rest-client/src/lib.rs
testsuite/forge/src/interface/aptos.rs
testsuite/smoke-test/src/storage.rs

as titled. see comments inline.

fix flaky test_db_restart

---

config/src/config/consensus_observer_config.rs
consensus/src/consensus_observer/common/error.rs
consensus/src/consensus_observer/observer/fallback_manager.rs

This PR cherry-picks https://github.com/aptos-labs/aptos-core/pull/15320 into `v1.24`.

[Consensus Observer] Add sync lag based fallback.

---

terraform/helm/aptos-node/files/configs/fullnode-base.yaml
terraform/helm/aptos-node/files/configs/validator-base.yaml

update helm node sharding config

---

aptos-move/e2e-benchmark/src/main.rs

recalibrate move e2e benchmark

---

aptos-move/aptos-release-builder/src/simulate.rs

When simulating gov. proposals, it is often useful to see detailed fee statement instead of just the total gas used. This PR prints that information.
Here is a sample output of a gov. proposal simulation after this PR:
```
Executing governance scripts...
0-gas-schedule.move
Fee statement: FeeStatement {
total_charge_gas_units: 229,
execution_gas_units: 39,
io_gas_units: 57,
storage_fee_octas: 13360,
storage_fee_refund_octas: 0,
}
Success
1-move-stdlib.move
Fee statement: FeeStatement {
total_charge_gas_units: 1161,
execution_gas_units: 77,
io_gas_units: 105,
storage_fee_octas: 97880,
storage_fee_refund_octas: 0,
}
Success
2-aptos-stdlib.move
Fee statement: FeeStatement {
total_charge_gas_units: 1670,
execution_gas_units: 1498,
io_gas_units: 123,
storage_fee_octas: 4960, …
```

Print detailed fee statement for gov proposal simulation

---

consensus/src/state_computer.rs

this is to cherry-pick https://github.com/aptos-labs/aptos-core/pull/15361 to v1.23

[cp 1.23] Move payload_manager.notify_commit() to after commit

---

types/src/validator_verifier.rs

This PR adds an extra verification step in optimistic_verify to check that the author of the vote is in the validator list.

Verify validator in optimistic_verify function

---

consensus/src/block_storage/block_store.rs
consensus/src/block_storage/block_store_test.rs
consensus/src/block_storage/execution_pool_test.rs
consensus/src/liveness/proposal_generator_test.rs
consensus/src/test_utils/mod.rs

This PR includes a set of unit tests and test utilities for the execution window changes covered in [`brian/exec-window-base`](https://github.com/aptos-labs/aptos-core/pull/14076)

[execution-pool] Initialize execution_pool_test.rs

---

consensus/src/block_storage/sync_manager.rs

This reverts commit af0b0557d17e9d9dc5a697cfc28c5405686131ab.

Revert "[consensus] trigger sync based on remote LI timestamp"

---

Cargo.lock
Cargo.toml
testsuite/forge/src/config.rs

[pipeline] enable on forge

---

ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_devnet_txns/78753811_coin_transfer_with_v2_events.json
ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_devnet_txns/78753831_token_v1_mint_transfer_with_v2_events.json
ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_devnet_txns/78753832_token_v2_mint_transfer_with_v2_events.json

add 3 txn for indexer integration test.

add 3 devnet txn with module events migrated

---

aptos-move/aptos-release-builder/data/release.yaml

This PR updates the release yaml for the v1.24.0 framework release (on the `aptos-release-v1.24` branch).

[Release] Update release.yaml for v1.24.0 framework release.

---

aptos-move/aptos-release-builder/data/enable-loader-v2.yaml

Proposal to enable V2 loader on testnet ([AIP-107](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-107.md)).

[release] Proposal to enable V2 loader

---

consensus/src/counters.rs
consensus/src/lib.rs
consensus/src/pipeline/pipeline_builder.rs

[Pipeline] add counters

---

aptos-move/aptos-release-builder/data/release.yaml

This PR updates the old gas version for the mainnet release.

[Aptos Release Builder] Update old gas version for mainnet release.

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Version bump for CLI release.
N/A, see CI.
N/A

[CLI] Bump version to 5.0.0

---

testsuite/forge/src/config.rs

[forge] enable pipeline

---

aptos-move/block-executor/src/code_cache_global_manager.rs

Addressing loader V2 todo: adding more test cases for module manager cache flushing conditions.
N/A
Ensure all corner cases are covered.

[loader-v2] More tests for global manager

---

scripts/dev_setup.sh

- Fix cargo nextest version (#15608)

[CP] Fix cargo nextest version #15608

---

aptos-move/aptos-gas-schedule/src/ver.rs

Bump gas for 1.25

---

testsuite/forge-cli/src/suites/land_blocking.rs
testsuite/forge/src/config.rs

[forge] exclude new pipeline for compat test

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/common/types.rs
crates/aptos/src/config/mod.rs

Resolves https://github.com/aptos-labs/aptos-core/issues/14492

Add extra files to gitignore

---

api/doc/spec.json
api/doc/spec.yaml
api/types/src/transaction.rs
crates/indexer/src/models/signatures.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs

[api] Allow JSON no account signature in simulation

---

Cargo.lock
Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-manager/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-manager/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-manager/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-manager/src/main.rs

[Indexer-Grpc-V2] Create two new folders for new binaries.

---

aptos-move/e2e-benchmark/data/calibration_values.tsv
aptos-move/e2e-benchmark/src/main.rs
testsuite/single_node_performance_values.tsv

fix calibration for a few tests from recent change

---

ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_devnet_txns/19922017_token_v1_offer_claim.json

token v1 offer claim test txn

---

testsuite/forge-cli/src/suites/realistic_environment.rs

to reduce noise on forge stable runs

relax forge thresholds

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

[cli] update cli version to 6.0.0

---

ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs

This is to fix grpcurl broken with new tonic reflection release.
ref: https://github.com/hyperium/tonic/issues/1786
also grpcurl seems using alphav1. 
New processor at HEAD.
grpcurl
Tested with old processors, looks good

[indexer grpc] Fix the service reflection.

---

Cargo.lock
Cargo.toml
aptos-move/aptos-workspace-server/Cargo.toml
crates/aptos-localnet/Cargo.toml
crates/aptos-localnet/src/processors.rs
crates/aptos-metrics-core/src/const_metric.rs
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Context https://aptos-org.slack.com/archives/C03MN5F7WUV/p1736824414357779.
dport: Since first adding the processor dependency, we now depend on it in a few different places. The drift can introduce version conflicts and incompatible types, even from within the processor crate itself. In this PR I lift all those dependency declarations up to the workspace level Cargo.toml.

update indexer processors hash

---

Cargo.lock
Cargo.toml
api/src/runtime.rs
api/src/tests/index_test.rs
config/src/config/api_config.rs

Add support for gzipped responses to the fullnode API
`cargo test --package aptos-api --lib -- tests::index_test::test_compression_middleware --exact --show-output`
```
*  Executing task: cargo test --package aptos-api --lib -- tests::index_test::test_compression_middleware --exact --show-output 
Finished `test` profile [unoptimized + debuginfo] target(s) in 47.12s
Running unittests src/lib.rs (target/debug/deps/aptos_api-2b44963f83c2c3b4)
running 1 test
test tests::index_test::test_compression_middleware ... ok
successes:
---- tests::index_test::test_compression_middleware stdout ----
resp: Response { status: 200, version: HTTP/1.1, headers: {"content-type": "application/json; charset=utf-8", "content-encoding": "gzip", "date": "Thu, 09 Jan 2025 17:18:56 GMT"}, body: …
```

Upgrade poem and enable compression middleware

---

aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/sources/coin.move

partially revert https://github.com/aptos-labs/aptos-core/pull/15269
to ban deposit into exchange account in FA format 
will revert once we start migration.

[fa] add back migration_flag for exchanges

---

crates/aptos-localnet/src/hasura_metadata.json
crates/aptos/CHANGELOG.md

Forgot to update on https://github.com/aptos-labs/aptos-core/pull/15732

Update hasura metadata

---

testsuite/forge/src/config.rs

forge: enable optqs

---

aptos-move/aptos-release-builder/data/release.yaml
aptos-move/aptos-release-builder/src/simulate.rs

release yaml for 1.26 to testnet

---

Cargo.lock
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/connection_manager.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/live_data_service/data_client.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/live_data_service/data_manager.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/live_data_service/fetch_manager.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/live_data_service/in_memory_cache.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/live_data_service/mod.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/service.rs

[Indexer-Grpc-V2] Add LiveDataService.

---

testsuite/replay-verify/archive_disk_utils.py
testsuite/replay-verify/main.py

Replay verify failed due to disk size doesn't match
recently, the mainnet disk is increased to 10Ti. update the disk size for replay verify as well. 
local tested

update the mainnet disk size to 10Ti

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Bump CLI to 6.0.3

---

aptos-move/move-examples/defi/sources/locked_coins.move

All the tests in this file are broken in main.
@perryjrandall why?

[move-examples] fix locked_coins

---

aptos-move/framework/aptos-framework/doc/account_abstraction.md
aptos-move/framework/aptos-framework/doc/staking_config.md
aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
sdk/src/transaction_builder.rs
testsuite/smoke-test/src/permissioned_delegation.rs

1. make all functions to remove/add AA authentication function private entry to reduces security risks.
2. Change some implementation
3. fix comments
4. fix tests.
ut

[AA] fix visibility issues

---

.github/workflows/replay-verify.yaml
.github/workflows/workflow-run-replay-verify-on-archive.yaml

Fix replay-verify workflows on multiple triggers:
- schedule - touch the file so it executes under the last editor's user permissions, which is used for GCP workload identity federation
- workflow_dispatch - increase the fetch depth so we can crawl the git history of the triggering branch 
workflow dispatch using this workflow source branch: https://github.com/aptos-labs/aptos-core/actions/runs/13142750915
- images not built for this branch yet
- so we have to crawl backwards to find images to use, which requires a deep enough fetch depth
Workflow

[gha] fix replay-verify on all triggering conditions

---

Cargo.lock
experimental/storage/layered-map/Cargo.toml
experimental/storage/layered-map/benches/maps.rs

Caching makes running selective benchmarks faster.
Added benches that uses rocksdb as a map (indeed 1-2 orders of magnitude slower than any in memory map) -- the cache should work.

LayeredMap: lazy and cached bench input data

---

aptos-node/src/utils.rs
crates/aptos/src/update/prover_dependencies.rs

[cli] Fix Windows build

---

aptos-move/aptos-vm-environment/src/environment.rs

[aptos-vm] Fix a typo in environment

---

ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/generated_transactions.rs
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_testnet_txns/6616059810_account_abstraction_authenticator.json
ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml

add aa testnet txn to fixtures

---

api/doc/spec.json
api/doc/spec.yaml
api/src/accounts.rs

Fix doc for get_account_balance
I tested a few different asset types through UI

fix account_balance doc

---

aptos-move/aptos-release-builder/data/release.yaml

release yaml for 1.27 to testnet

---

execution/executor-types/src/lib.rs
storage/aptosdb/src/db/test_helper.rs
storage/aptosdb/src/state_merkle_db.rs
storage/scratchpad/benches/sparse_merkle.rs
storage/scratchpad/src/sparse_merkle/mod.rs
storage/scratchpad/src/sparse_merkle/node.rs
storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
storage/scratchpad/src/sparse_merkle/test_utils/naive_smt.rs
storage/scratchpad/src/sparse_merkle/test_utils/proof_reader.rs
storage/scratchpad/src/sparse_merkle/test_utils/proptest_helpers.rs
storage/scratchpad/src/sparse_merkle/updater.rs
storage/scratchpad/src/sparse_merkle/utils.rs
storage/storage-interface/src/state_store/state_summary.rs
storage/storage-interface/src/state_store/versioned_state_value.rs
types/src/proof/mod.rs
types/src/state_store/state_key/tests.rs

Since recent introduction of the `State` and `LedgerState` structures, the SMT no longer doubles as the speculative state.
updated tests

SparseMerkleTree not carry value

---

terraform/aptos-node/gcp/kubernetes.tf
terraform/aptos-node/gcp/variables.tf

Sync Terraform & Helm

---

Cargo.lock
crates/node-resource-metrics/Cargo.toml
crates/node-resource-metrics/src/collectors/linux_collectors.rs

Collect these metrics on Linux.
local run
``` bash
$ curl localhost:9101/metrics -s | grep rlimit
node_linux_disk_rlimit_nofile_hard 999999
node_linux_disk_rlimit_nofile_soft 999999
```

Emit counters for RLIMIT_NOFILE

---

aptos-node/src/lib.rs
aptos-node/src/utils.rs
config/src/config/storage_config.rs

People has concern about panicking mainnet nodes.
local run

ensure_max_open_files not panic for mainnet

---

consensus/consensus-types/src/common.rs

[optqs] verify batch author belongs to epoch

---

.github/workflows/cli-release.yaml
.github/workflows/windows-build.yaml

Global can be run without admin permissions, but system requires admin permissions.  There's really no logical difference except that it is tied only to one user.

[windows-cli] Switch to using --global instead of --system

---

Cargo.lock
Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-manager/src/data_manager.rs
ecosystem/indexer-grpc/indexer-grpc-manager/src/grpc_manager.rs
ecosystem/indexer-grpc/indexer-grpc-manager/src/metadata_manager.rs
ecosystem/indexer-grpc/indexer-grpc-manager/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-server-framework/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-server-framework/src/lib.rs

- Track file store version on non-master instance.
- Pick FN based on the requested data.
- Propagate master address if known.
- Remove disconnected data service.
- Make sure the stored stream_info is always available.  
- Support passing config through env variables using figment.

[Indexer-Grpc-V2] Implement some TODOs in GrpcManager.

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

[cli] Release 6.2.0

---

consensus/src/block_storage/sync_manager.rs
consensus/src/network.rs
consensus/src/network_tests.rs

To be enabled after #14076 is deployed.

[execution window] Enable sending V2 block retrieval request with target round

---

experimental/storage/hexy/src/in_mem/base.rs
experimental/storage/hexy/src/in_mem/view.rs

Original unsafe code forcibly mutates immutable cells without using UnsafeCell to inform the reading side.
Added documentation to reason about safety.

HexyBase: use UnsafeCell and atomic::fence

---

crates/aptos-faucet/metrics-server/src/gather_metrics.rs
crates/aptos-inspection-service/src/server/utils.rs
storage/aptosdb/src/metrics.rs
storage/aptosdb/src/rocksdb_property_reporter.rs

Splitting them is just to avoid a warning and doesn't reduce number of
metrics.
Enlarging the warning threshold instead.
curl local node
``` bash
10:45 $ curl localhost:9101/metrics -s | grep rocksdb_shard                                                                                                                                   
aptos_rocksdb_shard_properties{cf_name="jellyfish_merkle_node",property_name="aptos_rocksdb_actual-delayed-write-rate",shard_id="0"} 0
aptos_rocksdb_shard_properties{cf_name="jellyfish_merkle_node",property_name="aptos_rocksdb_actual-delayed-write-rate",shard_id="1"} 0
aptos_rocksdb_shard_properties{cf_name="jellyfish_merkle_node",property_name="aptos_rocksdb_actual-delayed-write-rate",shard_id="10"} 0 …
```

consolidate per shard RocksDB properties

---

crates/aptos/src/node/local_testnet/mod.rs

This flag has been used here and there by the community, we might as well make it visible.
N/A

[localnet] Unhide --bind-to

---

api/src/accounts.rs
api/src/state.rs
api/src/tests/converter_test.rs
api/src/view_function.rs
api/types/src/convert.rs
api/types/src/move_types.rs
api/types/src/transaction.rs
api/types/src/wrappers.rs
crates/aptos/src/common/types.rs

JSON API parsing had an inconsistent input argument error description, which is now fixed and documented.
Additionally, removes some excess clones that are not necessary for type conversion.
See CI

[api] Cleanup JSON API parsing

---

storage/backup/backup-cli/src/coordinators/backup.rs

If compaction failed during the .meta file removal phase, the next run will find the expired files missing. Safe to ignore.

backup-compactor: Ignore failure in backing up .meta file

---

api/src/tests/function_value_test.rs

[move][api] Turning of api test which started failing on CI

---

.github/workflows/module-verify.yaml

Make it 120 minutes by default and turn it into a customizable input.

Increase default timeout for module-verify

---

.github/workflows/module-verify.yaml

Let the default 720 be used for the moment.

Hack to fix default timeout

---

storage/db-tool/src/replay_on_archive.rs
testsuite/replay-verify/main.py

1. make range end_version inclusive.
2. replay-on-archive returns gracefully if range and db range doesn't overlap. (because the scheduler doesn't know actual db range)
manual run

replay-verify: improve range allocation

---

testsuite/replay-verify/main.py

We used to quit successfully as long as no TransactionInfo mismatch was found.
manual run

replay-verify: fail the workflow if any task fails

---

testsuite/replay-verify/main.py

replay-verify: fix a log line

---

aptos-move/aptos-vm/src/aptos_vm.rs
third_party/move/move-vm/runtime/src/interpreter.rs
third_party/move/move-vm/runtime/src/lib.rs
third_party/move/move-vm/runtime/src/loader/mod.rs
third_party/move/move-vm/runtime/src/session.rs
third_party/move/move-vm/runtime/src/storage/dependencies_gas_charging.rs
third_party/move/move-vm/runtime/src/storage/loader.rs
third_party/move/move-vm/runtime/src/storage/mod.rs

Move gas charging for dependencies outside of loader/session into its own file. Using V2 loader only. Refactored charging gas for function values type args.

[4/n] Move gas charging for dependcies out of loader

---

storage/aptosdb/src/db_debugger/examine/print_db_versions.rs

dbtool examine cmd prints all db metadata entries

---

third_party/move/move-vm/runtime/src/data_cache.rs
third_party/move/move-vm/runtime/src/interpreter.rs
third_party/move/move-vm/runtime/src/loader/mod.rs
third_party/move/move-vm/runtime/src/native_functions.rs
third_party/move/move-vm/runtime/src/runtime.rs
third_party/move/move-vm/runtime/src/runtime_type_checks.rs
third_party/move/move-vm/runtime/src/session.rs
third_party/move/move-vm/runtime/src/storage/ty_layout_converter.rs
third_party/move/move-vm/runtime/src/storage/ty_tag_converter.rs
third_party/move/move-vm/types/src/loaded_data/runtime_types.rs

- Added config to interpreter (no need to use loader to pass configs)
- Removed `Loader::V1` occurrences there and in resolver
- Resolver now fully relies on module storage
- Layout conversion uses module storage only
- Moved pseudo gas context to type tag converter & cache

[6/n] Interpreter and resolver refactor for V2 loader

---

aptos-move/framework/aptos-framework/doc/account_abstraction.md
aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
aptos-move/framework/aptos-framework/tests/account_abstraction_tests.move

1. refactor add authentication function.
2. add a test case returning an invalid signer.
ut

[AA] refactor and add test

---

consensus/src/block_storage/block_store.rs

[consensus] update ordered root before sending blocks down the pipeline

---

consensus/consensus-types/src/pipelined_block.rs
consensus/src/block_storage/block_store_test.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/pipeline/buffer_manager.rs
consensus/src/pipeline/pipeline_builder.rs
third_party/move/move-binary-format/src/errors.rs

[precommit] make precommit more robust

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/framework/aptos-framework/doc/account_abstraction.md
aptos-move/framework/aptos-framework/doc/auth_data.md
aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
aptos-move/framework/aptos-framework/sources/account/auth_data.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
execution/executor/tests/internal_indexer_test.rs
sdk/src/types.rs
testsuite/generate-format/src/api.rs
testsuite/generate-format/src/aptos.rs
testsuite/generate-format/src/consensus.rs
testsuite/generate-format/tests/staged/api.yaml
testsuite/generate-format/tests/staged/aptos.yaml
testsuite/generate-format/tests/staged/consensus.yaml
types/src/transaction/authenticator.rs
types/src/transaction/mod.rs

[CP for 1.28 of #16128] Rename to derivable account abstraction

---

aptos-move/aptos-release-builder/data/release.yaml

for v1.28.0 framework release
simulation

add release.yaml for v1.28.0

---

ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs

Do not modify the expiration timestamp.

---

ecosystem/indexer-grpc/transaction-filter/src/filters/move_module.rs
ecosystem/indexer-grpc/transaction-filter/src/filters/user_transaction.rs
ecosystem/indexer-grpc/transaction-filter/src/lib.rs
ecosystem/indexer-grpc/transaction-filter/src/utils.rs

Indexer gRPC does not standardize addresses, and the transaction filter itself should be able to accept addresses of all formats. These changes memoize a standardized version (Display Format from [AIP-40](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-40.md#display-format)) of the address to use for comparison. 
Previously, `standardize_address()` was implemented using the `format!()` macro; however, we reimplement it to use direct string manipulation for optimal performance. 
Unit tests
The reimplemented `matches()` and `standardize_address()`

[Transaction Filter] Compare standardized addresses

---

ecosystem/indexer-grpc/indexer-grpc-table-info/src/internal_indexer_db_service.rs

Minor fix for indexer test

---

config/src/config/storage_config.rs

change default ledger prune window 150M -> 100M
could save a few hundred GBs of disk space.
rollout on testnet first and observe

default ledger prune window: 100m

---

config/src/config/storage_config.rs

This reverts commit 1521375b927943145d45882e31ce247399c100f8 to reapply https://github.com/aptos-labs/aptos-core/pull/16221

Reapply "default ledger prune window: 100m (#16217) (#16221)"

---

.github/actions/wait-images-ci/action.yaml
.github/workflows/forge-continuous-land-blocking-test.yaml
docker/__tests__/release-images.test.js
docker/image-helpers.js
docker/release-images.mjs
docker/wait-images-ci.mjs

This PR introduces a new script `wait-images-ci.mjs` that waits for all images that are relevant for CI (Forge, replay-verify, etc). Most of this functionality has been factored out of the existing `release-images.mjs` script
Existing tests
```
docker/__tests__/release-images.test.js
```
Run dry run locally
```
IMAGE_TAG_PREFIX=devnet AWS_ACCOUNT_ID=bla GCP_DOCKER_ARTIFACT_REPO=us-docker.pkg.dev/aptos-registry/docker GIT_SHA=$(git fetch && git rev-parse origin/main) ./docker/release-images.mjs --wait-for-image-seconds=3600 --dry-run
```
Wait images
```
GCP_DOCKER_ARTIFACT_REPO=us-docker.pkg.dev/aptos-registry/docker GIT_SHA=$(git fetch && git rev-parse origin/main) ./docker/wait-images-ci.mjs --wait-for-image-seconds=3600
```
Also see next stacked PR for GHA test plan
The new scripts

[docker] wait-images separate from release-images

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Bump cli to 7.1.0

---

api/doc/spec.yaml

[api] Update YAML API Spec

---

aptos-move/framework/aptos-framework/doc/fungible_asset.md
aptos-move/framework/aptos-framework/sources/fungible_asset.move

revoke_permission's signature is wrong

Temporarily disable fungible_asset::revoke_permission (still gated on testnet)

---

execution/executor-benchmark/src/lib.rs
testsuite/smoke-test/src/fullnode.rs

cleanup debug println

---

config/src/config/consensus_config.rs
consensus/src/block_storage/block_store_test.rs
consensus/src/block_storage/sync_manager.rs
testsuite/forge/src/config.rs

[pipeline] revert sync gap changes and disable pre-commit for now

---

execution/executor/src/block_executor/block_tree/mod.rs
execution/executor/src/block_executor/mod.rs
execution/executor/src/chunk_executor/chunk_commit_queue.rs
execution/executor/src/db_bootstrapper/mod.rs
execution/executor/src/types/partial_state_compute_result.rs

give upper level a chance to recover
as titled
compile

PartialStateComputeResult: propagate errors about unset fields

---

crates/aptos/e2e/cases/account.py
crates/aptos/e2e/main.py
crates/aptos/e2e/test_helpers.py
crates/aptos/src/common/init.rs

CLI funds accounts when using aptos account init with localnet after stateless account change.

[aptos] refactor aptos account init

---

third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16363.exp
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16363.move
third_party/move/move-model/src/model.rs

This PR sets lambda lifter to be run against all modules instead of target modules to match behavior in bytecode generator which generates stackless bytecode for functions that are in non-target modules but used by functions in the target modules.
close #16363 
1) existing tests;
2) a new test case.
Whether we want to run lambda lifter on all modules?

[compiler-v2][trivial] run lambda lifter for target modules and their transitive closures

---

config/src/config/storage_config.rs
storage/aptosdb/src/db/include/aptosdb_internal.rs
storage/aptosdb/src/db_debugger/mod.rs
storage/aptosdb/src/db_debugger/watch/mod.rs
storage/aptosdb/src/db_debugger/watch/opened.rs
storage/aptosdb/src/db_options.rs

tool to open a db and keep running, useful when playing with db default configs.
Also, trigger pruners on db open, so they start working before any commit.
played locally

db debugger: "watched opened" cmd

---

config/src/config/storage_config.rs
storage/aptosdb/src/db_options.rs

cherry-pick https://github.com/aptos-labs/aptos-core/pull/16392

[cp][1.29] set CompactOnDeletion table property collector

---

aptos-move/framework/aptos-framework/doc/aggregator_v2.md
aptos-move/framework/aptos-framework/doc/fungible_asset.md
aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.move
aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.spec.move
aptos-move/framework/aptos-framework/sources/fungible_asset.move

[trivial] Update aggregator_v2 to use self param for move2 call-style

---

mempool/src/core_mempool/index.rs
mempool/src/core_mempool/mempool.rs
mempool/src/core_mempool/transaction.rs
mempool/src/core_mempool/transaction_store.rs
mempool/src/tests/common.rs
mempool/src/tests/core_mempool_test.rs
mempool/src/tests/test_framework.rs

refactor: remove SequenceInfo, as the account sequence number is unnecessary: it was never read after insert

[mempool] refactor: remove SequenceInfo

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Fixes bug in localnet / devnet where CLI thinks an account is already created & funded.  Now it just checks for funding.

[cli] Release 7.3.0

---

.github/workflows/cli-release.yaml
scripts/cli/build_cli_release.sh

[cli] Allow skipping version checks for testing purposes

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/transaction_validation.rs
types/src/on_chain_config/aptos_features.rs

`TRANSACTION_SIMULATION_ENHANCEMENT` feature flag is enabled about 6 months ago. Cleaning up the transaction validation logic that was only invoked before this feature flag was enabled.

Cleanup TRANSACTION_SIMULATION_ENHANCEMENT feature flag

---

.github/workflows/docker-build-test.yaml
.github/workflows/forge-continuous-land-blocking-test.yaml
testsuite/testcases/src/compatibility_test.rs

Reverting the temporary change to understand flakiness.

Forge compat reduce restart wait time from 300s to 20s

---

aptos-move/aptos-gas-schedule/src/ver.rs

Bump gas version for v1.29

---

api/src/transactions.rs
api/types/src/convert.rs

Minor refactor in API convert methods

---

config/src/config/storage_config.rs
storage/aptosdb/src/db_options.rs
testsuite/forge/src/backend/k8s_deployer/constants.rs

cherry-pick https://github.com/aptos-labs/aptos-core/pull/16392

[cp][1.28] set CompactOnDeletion table property collector

---

Cargo.lock
aptos-move/aptos-gas-meter/src/traits.rs
aptos-move/aptos-gas-profiling/Cargo.toml
aptos-move/aptos-gas-profiling/src/profiler.rs
aptos-move/aptos-vm-types/src/abstract_write_op.rs
aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/session_change_sets.rs

[gas] fix prev_materialized_size for in place delayed field change

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/transaction_validation.rs
types/src/on_chain_config/aptos_features.rs

This reverts commit e7ad67cfaa13127d41be7eb3b889e62efa7a2bf9.

Revert "Cleanup TRANSACTION_SIMULATION_ENHANCEMENT feature flag (#16412)"

---

config/src/config/consensus_config.rs
config/src/config/consensus_observer_config.rs
consensus/consensus-types/src/pipelined_block.rs
consensus/consensus-types/src/wrapped_ledger_info.rs
consensus/src/block_storage/block_store.rs
consensus/src/block_storage/block_tree.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/consensus_observer/observer/active_state.rs
consensus/src/consensus_observer/observer/consensus_observer.rs
consensus/src/pipeline/execution_client.rs
consensus/src/pipeline/execution_schedule_phase.rs
consensus/src/pipeline/pipeline_builder.rs
consensus/src/state_computer.rs
consensus/src/state_computer_tests.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_execution_client.rs
consensus/src/test_utils/mock_state_computer.rs
testsuite/forge/src/config.rs

[pipeline] pre_commit

---

api/src/accounts.rs
api/src/context.rs
api/src/response.rs
api/src/tests/accounts_test.rs

we need this to see consistent behavior between api and code onchain.

[stateless_account] add feature gating to account api

---

aptos-move/framework/aptos-framework/doc/config_buffer.md
aptos-move/framework/aptos-framework/doc/consensus_config.md
aptos-move/framework/aptos-framework/doc/execution_config.md
aptos-move/framework/aptos-framework/doc/gas_schedule.md
aptos-move/framework/aptos-framework/doc/jwk_consensus_config.md
aptos-move/framework/aptos-framework/doc/jwks.md
aptos-move/framework/aptos-framework/doc/keyless_account.md
aptos-move/framework/aptos-framework/doc/randomness_api_v0_config.md
aptos-move/framework/aptos-framework/doc/randomness_config.md
aptos-move/framework/aptos-framework/doc/randomness_config_seqnum.md
aptos-move/framework/aptos-framework/doc/version.md
aptos-move/framework/aptos-framework/sources/configs/config_buffer.move
aptos-move/framework/aptos-framework/sources/configs/config_buffer.spec.move
aptos-move/framework/aptos-framework/sources/configs/consensus_config.move
aptos-move/framework/aptos-framework/sources/configs/execution_config.move
aptos-move/framework/aptos-framework/sources/configs/gas_schedule.move
aptos-move/framework/aptos-framework/sources/configs/jwk_consensus_config.move
aptos-move/framework/aptos-framework/sources/configs/randomness_api_v0_config.move
aptos-move/framework/aptos-framework/sources/configs/randomness_config.move
aptos-move/framework/aptos-framework/sources/configs/randomness_config_seqnum.move
aptos-move/framework/aptos-framework/sources/configs/version.move
aptos-move/framework/aptos-framework/sources/jwks.move
aptos-move/framework/aptos-framework/sources/keyless_account.move

Add config_buffer::extract_v2() and deprecate config_buffer::extract() which has incorrect visibility.
Existing UT.
n/a

config_buffer fix

---

crates/transaction-emitter-lib/src/emitter/account_minter.rs

we check if accounts exist or not, to decide if we need gas for transfer or creation
we check for end accounts and minter accounts, but not secondary source - causing issue when that's the only one that doesn't exist

fix txn-emitter - check secondary source account existance

---

.github/actions/python-setup/action.yaml

Update Poetry action and add parameter to allow gradually upgrading Poetry.

Update version pin on snok/install-poetry

---

api/src/accounts.rs

remove two println lines pushed in by accident.

delete println for debug

---

crates/aptos-rest-client/src/lib.rs

used to assume json format error however the gateway returns plain text errors.
``` bash
$ RUST_LOG=error cargo run -p aptos-debugger move execute-past-transactions --begin-version 2664750000 --limit 10000 --rest-endpoint http://api.mainnet.aptoslabs.com/v1 --skip-result --concurrency-level 8
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.49s
Running `target/debug/aptos-debugger move execute-past-transactions --begin-version 2664750000 --limit 10000 --rest-endpoint 'http://api.mainnet.aptoslabs.com/v1' --skip-result --concurrency-level 8`
Error: Unknown error Per anonymous IP rate limit exceeded. Limit: 50000 compute units per 300 seconds window. This means you have hit your per IP compute unit limit. If you are using a dapp, it means the dapp you are using is not using …
```

rest-client prints text error

---

third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/closures_in_enums.exp
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/closures_in_enums.move
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/extensive_capturing.exp
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/extensive_capturing.move
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/more_nested.exp
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/more_nested.move

Adding some tests for closures.

[compiler-v2] Some closure tests

---

crates/transaction-generator-lib/src/publishing/prebuild_packages.rs
crates/transaction-generator-lib/src/publishing/publish_util.rs

Allow it to pass BuildOptions, and when publishing code - use the latest version of binary_format_version when needed.
tested by using function values in separate project using txn-generator-lib

Allow txn-generator-lib to use new language features

---

aptos-move/block-executor/src/limit_processor.rs
aptos-move/block-executor/src/types.rs
aptos-move/replay-benchmark/src/execution.rs
execution/executor-benchmark/src/lib.rs

Add some info for debugging conflicts, and commented out code to enable.

Add info for debugging conflicts

---

storage/schemadb/src/lib.rs

context: replay-on-archive opens db in readonly mode and a new column family in the code but not in the DB (from production snapshots) doesn't open. 
replay-verify
https://github.com/aptos-labs/aptos-core/actions/runs/14846789904

DB: tolerate missing cfs when open read-only

---

ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/live_data_service/data_manager.rs
ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/metrics.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/counters.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs

[Indexer-Grpc-V2] Latency metrics.

---

aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
aptos-move/framework/aptos-experimental/doc/test_function_values.md
aptos-move/framework/aptos-experimental/sources/test_function_values.move

Fix transactional tests when aptos-experimental uses some new FV features

---

consensus/src/consensus_observer/observer/consensus_observer.rs

[observer] fix if let scope for mutex

---

storage/aptosdb/src/state_store/hot_state.rs
storage/aptosdb/src/state_store/persisted_state.rs
storage/aptosdb/src/state_store/tests/speculative_state_workflow.rs

On maiinnet we observe the hot state when full (1 million items):
1. taking about 300MB memory
2. evicted item is about 12 hours old
3. hit rate can drop to lower than 95%
Enlarging it to 4 million items, and hard capped at 4GB in size. Also, allow items as large as 10KB, up from 4KB.

Enlarge HotState

---

consensus/src/pipeline/buffer_manager.rs

Pending persisting blocks are popped from the buffer so reset can't see them. Previously it relies on ongoing tasks to count them but after pipeline the block can have in-fly futures that need explicit abort. For example persiting phase accepts reset and drops all blocks and finishes reset but those blocks can have running futures that will keep running.

[pipeline] abort pending persisting blocks properly

---

aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/market/market_types.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/clearinghouse_test.move

Update the clearinghouse APIs to support recent changes.

[Experimental][Orderbook] Update the clearinghouse APIs

---

api/src/context.rs
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/e2e-move-tests/src/tests/events.data/pack/Move.toml
aptos-move/e2e-move-tests/src/tests/events.data/pack/sources/test_module.move
aptos-move/e2e-move-tests/src/tests/events.rs
aptos-move/e2e-move-tests/src/tests/mod.rs
aptos-move/framework/aptos-framework/doc/event.md
aptos-move/framework/aptos-framework/sources/event.move
aptos-move/framework/src/natives/event.rs
aptos-move/replay-benchmark/Cargo.toml
aptos-move/replay-benchmark/src/diff.rs
consensus/src/liveness/leader_reputation_test.rs
crates/aptos-rosetta/src/test/mod.rs
execution/executor-benchmark/src/native/native_vm.rs
execution/executor-benchmark/src/native/parallel_uncoordinated_block_executor.rs
execution/executor/src/tests/mock_vm/mod.rs
execution/executor/tests/db_bootstrapper_test.rs
state-sync/inter-component/consensus-notifications/src/lib.rs
state-sync/inter-component/event-notifications/src/tests.rs
state-sync/state-sync-driver/src/tests/utils.rs
storage/aptosdb/src/event_store/test.rs
storage/aptosdb/src/ledger_db/ledger_metadata_db_test.rs
storage/indexer/src/event_v2_translator.rs
types/src/contract_event.rs
types/src/move_utils/move_event_v1.rs
types/src/move_utils/move_event_v2.rs
types/src/proof/unit_tests/proof_test.rs
types/src/proptest_types.rs
types/src/unit_tests/contract_event_test.rs

Allows to cache event size at construction time.
New unit tests.
N/A

[vm] Enhance events construction

---

aptos-move/e2e-benchmark/src/main.rs
aptos-move/e2e-move-tests/src/tests/gas.rs
aptos-move/framework/src/chunked_publish.rs
crates/aptos/src/common/types.rs
crates/transaction-generator-lib/src/call_custom_modules.rs
crates/transaction-generator-lib/src/publish_modules.rs
crates/transaction-generator-lib/src/publishing/publish_util.rs

Use chunking support in txn generator lib to allow txn generator lib to work with modules that exceed 64kb.

Use chunking in txn generator lib

---

api/src/context.rs
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/e2e-move-tests/src/tests/events.data/pack/Move.toml
aptos-move/e2e-move-tests/src/tests/events.data/pack/sources/test_module.move
aptos-move/e2e-move-tests/src/tests/events.rs
aptos-move/e2e-move-tests/src/tests/mod.rs
aptos-move/framework/aptos-framework/doc/event.md
aptos-move/framework/aptos-framework/sources/event.move
aptos-move/framework/src/natives/event.rs
aptos-move/replay-benchmark/Cargo.toml
aptos-move/replay-benchmark/src/diff.rs
consensus/src/liveness/leader_reputation_test.rs
crates/aptos-rosetta/src/test/mod.rs
execution/executor-benchmark/src/native/native_vm.rs
execution/executor-benchmark/src/native/parallel_uncoordinated_block_executor.rs
execution/executor/src/tests/mock_vm/mod.rs
execution/executor/tests/db_bootstrapper_test.rs
state-sync/inter-component/consensus-notifications/src/lib.rs
state-sync/inter-component/event-notifications/src/tests.rs
state-sync/state-sync-driver/src/tests/utils.rs
storage/aptosdb/src/event_store/test.rs
storage/aptosdb/src/ledger_db/ledger_metadata_db_test.rs
storage/indexer/src/event_v2_translator.rs
types/src/contract_event.rs
types/src/move_utils/move_event_v1.rs
types/src/move_utils/move_event_v2.rs
types/src/proof/unit_tests/proof_test.rs
types/src/proptest_types.rs
types/src/unit_tests/contract_event_test.rs

Allows to cache event size at construction time.
New unit tests.
N/A

[vm] Enhance event construction

---

aptos-move/aptos-gas-schedule/src/ver.rs

Bump gas version to V1_31

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/doc/market_types.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/market/market_types.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/clearinghouse_test.move

This simplify order matching significantly.. it is upto the clearinghouse to figure out the settlement size and cancel the order is applicable.

[Experimantal][Orderbook] Clean up clearinghouse APIs and remove max_settlement_size API

---

third_party/move/move-vm/runtime/src/interpreter.rs
third_party/move/move-vm/transactional-tests/tests/display/print_values.exp
third_party/move/move-vm/transactional-tests/tests/display/print_values.move
third_party/move/move-vm/types/src/values/values_impl.rs

When `Container`, `Locals`, `ContainerRef` values are displayed, raw address is printed. This is useless information and also error prone due to non-determinism.

[vm] Remove raw address display

---

testsuite/forge/src/success_criteria.rs

This PR changes the forge success criteria checker to return all assertion failures instead of returning the first assertion failure. This should help to see all errors together instead of one at a time.

[forge] print all errors together on test failure

---

docker/compose/aptos-node/docker-compose-fullnode.yaml
docker/compose/aptos-node/docker-compose-src.yaml
docker/compose/aptos-node/docker-compose.yaml

Remove obsolete `version` field.

Remove obsolete version field from Docker compose files

---

Cargo.lock
Cargo.toml
crates/aptos-localnet/src/hasura_metadata.json
crates/aptos-localnet/src/processors.rs
crates/aptos/src/node/local_testnet/processors.rs

Adds it to the processor set and updates the hasura schema.
The versions for the indexer sdk and processor crates are updated as well.
Tested locally

Add the account restoration processor to local net

---

aptos-move/framework/aptos-experimental/doc/active_order_book.md
aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/doc/order_book.md
aptos-move/framework/aptos-experimental/doc/order_book_types.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/order_book/active_order_book.move
aptos-move/framework/aptos-experimental/sources/trading/order_book/order_book.move
aptos-move/framework/aptos-experimental/sources/trading/order_book/order_book_types.move

Add API to decrease the size of the order without changing its priority

[Experimental][Orderbook] Add API to decrease the size of the order without changing its priority

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/doc/order_book.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/order_book/order_book.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/clearinghouse_test.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/market_test_utils.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/market_tests.move

Self trade should generally be rejected - adding a configuration knob for users to tune its behavior as needed.

[Experimental][Orderbook] Add support for rejecting self-trade

---

scripts/dev_setup.sh

To fix other CI issues. 
Prev: https://github.com/aptos-labs/aptos-core/pull/16680

Pin cargo-sort version in dev_setup.sh

---

Cargo.lock
execution/executor-benchmark/Cargo.toml
execution/executor-benchmark/src/ledger_update_stage.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/measurements.rs
execution/executor-benchmark/src/pipeline.rs
execution/executor-benchmark/src/transaction_executor.rs

reviving old @vusirikala 's PR on to print out summary of events of transactions (across stages), so users can easily verify if things are executed correctly, and frequency of different actions.

executor benchmark improvements - summary of events

---

consensus/Cargo.toml
consensus/src/dag/rb_handler.rs
consensus/src/round_manager.rs
consensus/src/round_manager_test.rs
consensus/src/test_utils/mock_payload_manager.rs
dkg/Cargo.toml
dkg/src/transcript_aggregation/mod.rs
dkg/src/transcript_aggregation/tests.rs
testsuite/smoke-test/src/validator_txns.rs
types/src/dkg/dummy_dkg/mod.rs
types/src/dkg/mod.rs
types/src/dkg/real_dkg/mod.rs
types/src/validator_txn.rs
types/src/validator_verifier.rs

Cherry-picking a fix: invalid DKG transcripts should be rejected.
new UT and smoke tests.

[cherry-picking] dkg fixes

---

aptos-move/framework/aptos-framework/doc/ethereum_derivable_account.md
aptos-move/framework/aptos-framework/sources/account/common_account_abstractions/ethereum_derivable_account.move
testsuite/smoke-test/src/account_abstraction.rs

cherrypicking https://github.com/aptos-labs/aptos-core/commit/a03a6181ef312889d9b56ceecccfad34ccb401fb to v1.30 - it needs to go to testnet, and release is being delayed

Cherry pick Ethereum DAA fix

---

ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs

[IndexerFN] Update the timestamp conversion to avoid overflow.

---

ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/connection_manager.rs

[Indexer-Grpc-V2] Break after maximal retries.

---

aptos-move/framework/aptos-framework/doc/account_abstraction.md
aptos-move/framework/aptos-framework/sources/account/account_abstraction.move

The `account_abstraction::initialize` function is being called during genesis, which is what enables us to register auth functions.
Since this function is a private entry function, it can’t be called from a script directly.
So changing it to be public

Change `account_abstraction::initialize` to public entry function

---

aptos-move/framework/aptos-framework/doc/big_ordered_map.md
aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.move

- make new() work for variable-sized types, by trying to be "smart", and setting things up so that values of up to 5KB can be inserted. For bigger values, you want to use one of the other constructors to configure it yourself.

BigOrderedMap improvement: allow new() for variable-sized types 

---

crates/aptos-rosetta/src/types/move_types.rs
crates/aptos-rosetta/src/types/objects.rs

This adds module events for parsing in rosetta

[rosetta] Add module events for parsing

---

.gitignore
crates/aptos-faucet/ts-client/.npmignore
ecosystem/node-checker/ts-client/.npmignore

Follow best practices from https://github.com/google-github-actions/auth?tab=readme-ov-file#prerequisites. The dockerignore ignores everything by default so didn't add there

[gitignore] gha auth

---

third_party/move/move-model/src/ty.rs
third_party/move/move-prover/boogie-backend/src/boogie_helpers.rs
third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
third_party/move/move-prover/boogie-backend/src/lib.rs
third_party/move/move-prover/boogie-backend/src/spec_translator.rs
third_party/move/move-prover/bytecode-pipeline/src/number_operation.rs
third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs
third_party/move/move-prover/bytecode-pipeline/src/options.rs
third_party/move/move-prover/src/cli.rs
third_party/move/move-prover/tests/sources/functional/bitset.move
third_party/move/move-prover/tests/sources/functional/bitwise_error_1.exp
third_party/move/move-prover/tests/sources/functional/bitwise_error_1.move
third_party/move/move-prover/tests/sources/functional/bitwise_error_2.exp
third_party/move/move-prover/tests/sources/functional/bitwise_error_2.move

This PR refactors the code for bitwise operation analysis:
1) generates better error messages for bv analysis to avoid boogie-level errors;
2) improves heuristics to handle more cases where automatic type conversion from general integer types to bv types is required;
3) removes the flag `ban-int-2-bv` and related code, since it is not exposed to Aptos CLI anyway.
4) removes unnecessary code for better readability.
Existing test cases and new test cases to show error messages.
Newly introduced error messages

[Prover] code refactor for bitwise operation analysis

---

.github/workflows/bump-release-version.yaml

Updates Cargo.lock along with Cargo.toml

Fix release version workflow

---

aptos-move/framework/aptos-framework/doc/fungible_asset.md
aptos-move/framework/aptos-framework/sources/fungible_asset.move

Graceful when concurrent FA disabled

---

ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/generated_transactions.rs
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2277018899_tradeport_v2_accept_token_delist_same_token_data_id.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2296098846_tradeport_v2_accept_token_delist2.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2296149225_tradeport_v2_accept_token_delist.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2298838662_tradeport_v2_fill_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2313248448_wapal_fill_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2381742315_wapal_cancel_listing.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2381810159_wapal_cancel_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2382219668_wapal_fill_collection_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2382221134_wapal_fill_listing.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2382251863_wapal_place_listing.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2382313982_wapal_place_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2382373209_wapal_place_collection_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2382373978_wapal_cancel_collection_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2386021136_tradeport_v2_fill_collection_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2386133936_tradeport_v2_place_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2386142672_tradeport_v2_cancel_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2386455218_tradeport_v2_fill_listing.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2386716658_tradeport_v2_cancel_listing.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2386809975_tradeport_v2_place_listing.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2386889884_tradeport_v2_cancel_collection_offer.json
ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2386891051_tradeport_v2_place_collection_offer.json
ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml

add test txns for nft aggregator

add nft testing txns

---

execution/executor/src/workflow/do_get_execution_output.rs

There could be a BlockEpilogue txn after all retry transactions.

[Priority Fee] Rewrite the logic to handle retry and discard transactions.

---

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json
api/test-context/src/test_context.rs
aptos-move/aptos-transaction-simulation/src/state_store.rs
aptos-move/block-executor/src/executor.rs
testsuite/smoke-test/src/execution.rs
types/src/block_executor/config.rs

[CP] Check add_block_limit_outcome_onchain flag since AIP-88 is not enabled.

---

aptos-move/aptos-release-builder/data/enable_block_epilogue.yaml

Enable aip-88.

---

consensus/consensus-types/src/block.rs
consensus/consensus-types/src/common.rs
consensus/consensus-types/src/payload.rs
consensus/src/counters.rs
consensus/src/quorum_store/counters.rs

Existing counters on QS batches are broken. Fixing it and adding more counters on QS proof, inline batch, and opt batch.

[counters] adding/fixing batch counters

---

storage/aptosdb/src/db/include/aptosdb_internal.rs
storage/aptosdb/src/db/include/aptosdb_reader.rs
storage/aptosdb/src/db/include/aptosdb_writer.rs

[Storage] Format code under db/include.

---

storage/aptosdb/src/db/include/aptosdb_writer.rs
storage/aptosdb/src/db/test_helper.rs
storage/aptosdb/src/db_options.rs
storage/aptosdb/src/ledger_db/mod.rs
storage/aptosdb/src/ledger_db/persisted_auxiliary_info_db.rs
storage/aptosdb/src/ledger_db/persisted_auxiliary_info_db_test.rs
storage/aptosdb/src/pruner/ledger_pruner/mod.rs
storage/aptosdb/src/pruner/ledger_pruner/persisted_auxiliary_info_pruner.rs
storage/aptosdb/src/schema/db_metadata/mod.rs
storage/aptosdb/src/schema/mod.rs
storage/aptosdb/src/schema/persisted_auxiliary_info/mod.rs
storage/aptosdb/src/schema/persisted_auxiliary_info/test.rs
storage/storage-interface/src/errors.rs
types/src/transaction/mod.rs

Also add a V1 variant for PersistedAuxiliaryInfo.

[Storage] Store persisted auxiliary info.

---

storage/aptosdb/src/ledger_db/persisted_auxiliary_info_db.rs
storage/aptosdb/src/ledger_db/persisted_auxiliary_info_db_test.rs

[Storage] Fix calculation and add tests.

---

third_party/move/move-binary-format/src/check_bounds.rs
third_party/move/move-binary-format/src/file_format.rs
third_party/move/move-bytecode-verifier/src/check_duplication.rs
third_party/move/move-bytecode-verifier/src/stack_usage_verifier.rs

Mainly, this PR fixes one of the TODOs in the open cover bug for closures (I have added a comment to draw attention to it).
There are some other minor comments/typo fixes/naming changes, etc.

[vm][bytecode-verifier][trivial] Use captured count

---

aptos-move/aptos-vm-logging/src/lib.rs
aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/txn_last_input_output.rs
aptos-move/block-executor/src/unit_tests/mod.rs
aptos-move/mvhashmap/src/versioned_delayed_fields.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/native/aptos_vm_uncoordinated.rs
execution/executor-benchmark/src/native/native_transaction.rs
execution/executor-benchmark/src/native/native_vm.rs
execution/executor-benchmark/src/native/parallel_uncoordinated_block_executor.rs
execution/executor/src/tests/mock_vm/mod.rs
execution/executor/src/workflow/do_get_execution_output.rs

[Priority Fee] Call VM to execute BlockEpilogue txn.

---

aptos-move/framework/aptos-framework/doc/block.md
aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/doc/stake.md
aptos-move/framework/aptos-framework/sources/block.move
aptos-move/framework/aptos-framework/sources/genesis.move
aptos-move/framework/aptos-framework/sources/stake.move
execution/executor/tests/internal_indexer_test.rs

[Priority Fee] Implement contract for storing and distributing fee.

---

third_party/move/tools/move-resource-viewer/src/lib.rs

Using `bail!` instead of `todo!`.

[API] Removing TODO for fat types

---

aptos-move/block-executor/src/executor.rs

The materialize_txn_commit is happening in parallel. The previous code is not detecting the finalization of execution correctly before moving to BlockEpilogue generation.

[Priority Fee] Fix the condition to trigger BlockEpilogue txn generation in parallel execution.

---

consensus/src/block_preparer.rs
crates/aptos-transaction-filters/src/block_transaction_filter.rs
crates/aptos-transaction-filters/src/tests/block_transaction_filter.rs
crates/aptos-transaction-filters/src/tests/block_transaction_filter_config.rs
crates/aptos-transaction-filters/src/tests/utils.rs

Note: this PR is built on: https://github.com/aptos-labs/aptos-core/pull/16911
This PR adds a block author filter to the `BlockTransactionFilter`, including new unit and integration tests.

[API] Extend filtering support.

---

config/src/config/consensus_config.rs
config/src/config/quorum_store_config.rs
testsuite/forge-cli/src/suites/realistic_environment.rs
testsuite/forge/src/config.rs

Landing blocking forge perf tuning for opt proposal.

[consensus] Opt Proposal Perf Tuning

---

aptos-move/aptos-vm/src/aptos_vm.rs
third_party/move/move-core/types/src/vm_status.rs
types/src/proptest_types.rs
types/src/transaction/mod.rs

Adding a feature gate for propagating error status when depth is reached. Before, this error was just an execution failure.

[vm] Depth checks error feature-gating

---

crates/transaction-generator-lib/src/call_custom_modules.rs
crates/transaction-generator-lib/src/publishing/publish_util.rs

[trivial] multi-package publish for txn generator

---

testsuite/forge-cli/src/suites/realistic_environment.rs

Increase mempool to block creation threshold further in forge

---

third_party/move/move-bytecode-verifier/src/limits.rs
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/very_large_1.exp
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/very_large_1.move
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/very_large_2.exp
third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/very_large_2.move

Fixes a missing increment for function type limit.
Added new tests.

[vm] [bytecode-verifier] Function type limit fix

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/market_test_utils.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/market_tests.move

[Orderbook] Fix the remaining size when taker order is cancelled

---

aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/market/market_types.move

[trivial] add missing market methods 

---

Cargo.lock
aptos-move/block-executor/Cargo.toml
aptos-move/block-executor/src/executor.rs
aptos-move/framework/aptos-framework/doc/stake.md
aptos-move/framework/aptos-framework/sources/stake.move
aptos-move/framework/aptos-framework/sources/stake.spec.move
aptos-move/mvhashmap/src/lib.rs
aptos-move/mvhashmap/src/versioned_data.rs
aptos-move/mvhashmap/src/versioned_delayed_fields.rs
aptos-move/mvhashmap/src/versioned_group_data.rs
testsuite/smoke-test/Cargo.toml
testsuite/smoke-test/src/lib.rs
testsuite/smoke-test/src/priority_fee.rs

[Priority Fee] Fix some issues in parallel execution and add some tests.

---

third_party/move/tools/move-resource-viewer/src/lib.rs

Addressing TODO for function values to convert tags to fat types.
Closes #16975

[api] Addressing function value todos

---

storage/aptosdb/src/db_debugger/examine/mod.rs
storage/aptosdb/src/db_debugger/examine/print_raw_data_by_version.rs
storage/aptosdb/src/db_debugger/state_kv/get_value.rs

[Storage] Add a tool for printing raw ledger db content.

---

third_party/move/move-vm/runtime/src/config.rs

The default was already increased to 512 in https://github.com/aptos-labs/aptos-core/blob/8d7664ff9f375a69232502ee846d399c0eb59a40/aptos-move/aptos-vm-environment/src/prod_configs.rs#L141 but this was missed.

Increase max layout default size from 256 to 512

---

consensus/consensus-types/src/pipelined_block.rs
consensus/src/pipeline/buffer_manager.rs
consensus/src/pipeline/pipeline_builder.rs
execution/executor/src/block_executor/mod.rs

[pipeline] properly wait for spawn_blocking futures

---

aptos-move/aptos-release-builder/data/release.yaml

```bash
cargo run -p aptos-release-builder -- \
generate-proposals \
--release-config aptos-move/aptos-release-builder/data/release.yaml \
--output-dir output \
--simulate testnet
```
```bash
Creating and funding sender account.. done
Executing governance scripts...
0-gas-schedule.move
Fee statement: FeeStatement {
total_charge_gas_units: 174,
execution_gas_units: 46,
io_gas_units: 57,
storage_fee_octas: 7160,
storage_fee_refund_octas: 0,
}
Success
1-move-stdlib.move
Fee statement: FeeStatement {
total_charge_gas_units: 426,
execution_gas_units: 88,
io_gas_units: 125,
storage_fee_octas: 21320,
storage_fee_refund_octas: 0,
}
Success
2-aptos-stdlib.move
Fee statement: FeeStatement {
total_charge_gas_units: 475,
execution_gas_units: 331,
io_gas_units: 145,
storage_fee_octas: 0, …
```

Testnet framework release v1.33.0 rc

---

storage/aptosdb/src/backup/backup_handler.rs
storage/backup/backup-cli/src/backup_types/transaction/backup.rs
storage/backup/backup-cli/src/backup_types/transaction/manifest.rs
storage/backup/backup-cli/src/backup_types/transaction/restore.rs
storage/backup/backup-cli/src/utils/backup_service_client.rs
storage/db-tool/src/replay_on_archive.rs

[Storage] Support PersistedAuxiliaryInfo in backup/restore.

---

ecosystem/indexer-grpc/indexer-grpc-table-info/src/table_info_service.rs

[Indexer] Do not panic when failed to parse table info.

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move

[Orderbook] Add trigger condition to the event

---

storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs
storage/aptosdb/src/pruner/state_merkle_pruner/state_merkle_metadata_pruner.rs
storage/aptosdb/src/pruner/state_merkle_pruner/state_merkle_shard_pruner.rs

For cross epoch nodes, there is likely no corresponding root at the same version.

[Storage] Fix cross epoch merkle pruner.

---

protos/README.md

Add plantuml diagram for signatures

add plantuml diagram for signatures

---

testsuite/forge-cli/src/main.rs
testsuite/forge-cli/src/suites/ungrouped.rs

A basic single cluster test without any network emulation, useful for reproducing devnet style environment.

[forge] single cluster test

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Releases the latest version of the CLI, removing sharding from localnet

[cli] Release CLI version 7.7.0

---

aptos-move/framework/aptos-experimental/doc/order_book.md
aptos-move/framework/aptos-experimental/doc/order_book_types.md
aptos-move/framework/aptos-experimental/doc/pending_order_book_index.md
aptos-move/framework/aptos-experimental/sources/trading/order_book/order_book.move
aptos-move/framework/aptos-experimental/sources/trading/order_book/order_book_types.move
aptos-move/framework/aptos-experimental/sources/trading/order_book/pending_order_book_index.move

Changing this as a generic trigger condition allows supporting more flexible order type such as stop limit and stop market orders.

[Orderbook] Make the trigger condition more generic

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/market_test_utils.move

[OrderBook] return max matches

---

consensus/src/pipeline/pipeline_builder.rs
storage/indexer/src/db_v2.rs

This PR reduces the `info!` log volume of 3 separate, high-frequency logs.

[Logs] Reduce info! log volume.

---

storage/aptosdb/src/db_debugger/examine/print_db_versions.rs
storage/aptosdb/src/ledger_db/mod.rs
storage/aptosdb/src/pruner/ledger_pruner/persisted_auxiliary_info_pruner.rs

[Storage] Fix a bug in pruner, and print more information in debugger.

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move

[Orderbook] Fix the size delta in events in case of order cancellation

---

storage/aptosdb/src/pruner/state_merkle_pruner/state_merkle_pruner_manager.rs
storage/aptosdb/src/state_merkle_db.rs

[Storage] Write epoch ending pruner progress to right key.

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/doc/market_types.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/market/market_types.move

[Orderbook] Add Order ack event type

---

.github/actions/wait-images-ci/action.yaml
.github/workflows/docker-build-test.yaml
.github/workflows/replay-verify-mainnet.yaml
.github/workflows/replay-verify-testnet.yaml
.github/workflows/workflow-run-docker-rust-build.yaml
.github/workflows/workflow-run-replay-verify-on-archive.yaml
docker/image-helpers.js
docker/wait-images-ci.mjs

Reverts aptos-labs/aptos-core#17270

Revert "[ci] build images automatically if not present"

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/market_test_utils.move

[Orderbook] Fix size delta in case of placing a maker order

---

config/src/config/config_optimizer.rs
config/src/config/storage_config.rs

[AIP-97] Print clear error message if the AIP is not enabled.

---

.github/workflows/workflow-run-docker-rust-build.yaml

Wait for image to be built if the lock exists. The step will fail at the end of 20 minutes assuming image is still building and/or the job failed to build the image. 
Run parallel builds targeting changes in this build: 
- First to trigger build process: https://github.com/aptos-labs/aptos-core/actions/runs/17113279285/job/48539150749?pr=17362
- Second to wait for image to produce (skips build process): https://github.com/aptos-labs/aptos-core/actions/runs/17113312333/job/48539245751

[ci] wait for image to be built after lock check

---

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs

Bumping `max_total_dependency_size`

bump max_total_dependency_size

---

aptos-move/aptos-gas-schedule/src/ver.rs

Bump gas version for release 1.35.

---

third_party/move/move-vm/runtime/src/storage/module_storage.rs

This PR fixes a missing `use`. The function `visit_dependencies_and_skip_verification()` is gated by `#[cfg(fuzzing)]` so this didn't affect normal compilation & testing.
The error message was:
```
error[E0433]: failed to resolve: use of undeclared type `Location`
--> ...../third_party/move/move-vm/runtime/src/storage/module_storage.rs:532:27
|
532 |     .map_err(|e| e.finish(Location::Undefined))?;
|                           ^^^^^^^^ use of undeclared type `Location`
```
All transactional tests still pass.
Building with the `fuzzing` feature won't cause the above error anymore.

[fuzzer] add missing use under #[cfg(fuzzing)]

---

execution/executor-benchmark/src/measurements.rs

[trivial] provide benchmark stats accessors to the caller

---

aptos-move/aptos-release-builder/data/release.yaml

 Framework release for 1.34

---

third_party/move/tools/move-resource-viewer/src/fat_type.rs

`fat_type::from_runtime_layout`, which is used to compute the FatType from captured arguments, did not work correctly for function values.

[move resource viewer] Fixes a bug with closures captured by closures

---

crates/transaction-generator-lib/src/call_custom_modules.rs
crates/transaction-generator-lib/src/lib.rs
crates/transaction-generator-lib/src/workflow_delegator.rs
crates/transaction-workloads-lib/src/args.rs
execution/executor-benchmark/src/lib.rs

allow benchmark to be deterministic

---

aptos-move/framework/aptos-framework/doc/big_ordered_map.md
aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.move

[simple] Optimize is_empty BigOrderedMap function

---

aptos-move/framework/aptos-experimental/doc/market.md
aptos-move/framework/aptos-experimental/sources/trading/market/market.move

[Orderbook] Fix market order with trigger condition

---

.github/actions/get-latest-docker-image-tag/action.yml

Fix for https://github.com/aptos-labs/aptos-core/commit/e083c4671b9271655cd67de804633e4503764be2
Syntax check and lint

[fix][gha] add retry to get-latest-docker-image-tag

---

aptos-move/aptos-gas-profiling/src/aggregate.rs
aptos-move/aptos-gas-profiling/src/erased.rs
aptos-move/aptos-gas-profiling/src/report.rs
aptos-move/aptos-gas-profiling/templates/index.html

[gas profiler] add method-based tables to gas-profile

---

aptos-move/aptos-gas-profiling/src/render.rs

[gas profiler] fix table rendered

---

third_party/move/move-vm/types/src/values/values_impl.rs

When getting variant tag, we do not need to borrow container - it is sufficient to extract tag directly as `u16`.
On `read-enum-variants` workload, a 15% perf improvement is observed (running with 32 threads, 10K txns per block each txn reads 4096 variants, c3d instance).
```bash                                                                                  
--------------------------------------------------------------------------------------------------------
read-enum-variants [bs=10000]18062.31 [17980.95, 18158.79]         20819.54 [20606.13, 20916.40]         
Median speed-up by workload ( ÷ ):
read-enum-variants [bs=10000] 1.15×
```

[vm] Get enum tags without borrowing containers

---

api/src/tests/move/pack_rand/Move.toml
api/src/tests/move/pack_rand/sources/counter.move
api/src/tests/simulation_test.rs
aptos-move/aptos-vm/src/aptos_vm.rs

The test fails without the patch and now it passes

[simulation] patch randomness seed

---

aptos-move/mvhashmap/src/versioned_delayed_fields.rs

[Block Executor] Fix estimate invariant for epilogue re-execution

---

consensus/src/block_storage/block_store.rs
consensus/src/block_storage/block_tree.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/recovery_manager.rs

[zaptos] abort pending tasks in block store

---

aptos-move/framework/aptos-experimental/doc/order_operations.md
aptos-move/framework/aptos-experimental/sources/trading/market/order_operations.move

Changes to cancel API to support TWAPs better

---

aptos-move/framework/aptos-experimental/doc/market_bulk_order.md
aptos-move/framework/aptos-experimental/doc/market_types.md
aptos-move/framework/aptos-experimental/doc/order_book.md
aptos-move/framework/aptos-experimental/doc/order_operations.md
aptos-move/framework/aptos-experimental/doc/order_placement.md
aptos-move/framework/aptos-experimental/doc/single_order_book.md
aptos-move/framework/aptos-experimental/sources/trading/market/market_bulk_order.move
aptos-move/framework/aptos-experimental/sources/trading/market/market_types.move
aptos-move/framework/aptos-experimental/sources/trading/market/order_operations.move
aptos-move/framework/aptos-experimental/sources/trading/market/order_placement.move
aptos-move/framework/aptos-experimental/sources/trading/order_book/order_book.move
aptos-move/framework/aptos-experimental/sources/trading/order_book/single_order_book.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/clearinghouse_test.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/market_test_utils.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/market_tests_common.move

Ability to return generic templated values from clearinghouse APIs

---

testsuite/forge.py
testsuite/test_framework/cluster.py

- Do a simpler GKE cluster list  operation. And print the results to stdout for inspection
- Added a special case for FORGE_RUNNER_DURATION_SECS=0, so the forge wrapper just aborts after running through all the pre-forge checks such as cluster selection. useful to iterate fast
- Add a simple retry for GKE cluster list, since it seems  flaky
workflow_dispatch
```
gh workflow run adhoc-forge.yaml --ref 09-25-_forge_add_debug_for_cluster_list -F GIT_SHA=09-25-_forge_add_debug_for_cluster_list -F IMAGE_TAG=024efa00f4e96d670de0d1ea671aefdc89acf53e -F FORGE_RUNNER_DURATION_SECS=0 -F FORGE_NUM_VALIDATORS=1 -F FORGE_NUM_VALIDATOR_FULLNODES=1
```

[forge] add debug for cluster list

---

execution/executor-benchmark/src/measurements.rs

fix json table for executor benchmark

---

docker/builder/tools.Dockerfile

We need the source to generate the txn payload. Followup to #17690 
CI. Also build and run release builder in a docker container

[docker] add release-builder to tools image incl source

---

testsuite/forge-cli/src/suites/realistic_environment.rs

[forge] memory threshold again

---

testsuite/replay-verify/archive_disk_utils.py

[replay-verify] bump disk to 15Ti

---

testsuite/replay-verify/main.py

[replay-verify] increase pvc ttl

---

aptos-move/framework/aptos-experimental/doc/market_clearinghouse_order_info.md
aptos-move/framework/aptos-experimental/doc/market_types.md
aptos-move/framework/aptos-experimental/doc/order_operations.md
aptos-move/framework/aptos-experimental/doc/order_placement.md
aptos-move/framework/aptos-experimental/doc/overview.md
aptos-move/framework/aptos-experimental/sources/trading/market/market_clearinghouse_order_info.move
aptos-move/framework/aptos-experimental/sources/trading/market/market_types.move
aptos-move/framework/aptos-experimental/sources/trading/market/order_operations.move
aptos-move/framework/aptos-experimental/sources/trading/market/order_placement.move
aptos-move/framework/aptos-experimental/sources/trading/tests/market/clearinghouse_test.move

[Orderbook] Clearinghouse API Cleanup

---

storage/db-tool/src/backup_maintenance.rs

[Storage][Tool] Add a command to print backup metadata.

---

testsuite/replay-verify/main.py

Increase both pvc and workers per pvc to shorten replay time.

[replay-verify] increase worker count
