- config/src/config/consensus_observer_config.rs
- consensus/src/consensus_observer/observer.rs
- consensus/src/consensus_provider.rs
- testsuite/smoke-test/src/randomness/randomness_stall_recovery.rs
This PR updates consensus observer to pass the `randomness_stall_recovery` smoke test. To do so, we: (i) update the smoke test to add the `randomness_override_seq_num` override; and (ii) update consensus observer to use the override when constructing `OnChainRandomnessConfig`.
Note: I'll remove the enablement of consensus observer before this lands. It's simply so that I can test the smoke test 😄 
> [Consensus Observer] Fix randomness_stall_recovery smoke test.

- docker/compose/aptos-node/docker-compose-fullnode.yaml
- docker/compose/aptos-node/docker-compose-src.yaml
- docker/compose/aptos-node/docker-compose.yaml
- docker/compose/aptos-node/haproxy-fullnode.cfg
- docker/compose/aptos-node/haproxy.cfg
1. Update haproxy version for docker compose deployment method
2. Change user from nobody to haproxy, nobody causes an error on `haproxy:3.0.2`. If it's `haproxytech/haproxy-debian:3.0.2` it will work, but the latest Helm charts use `haproxy:3.0.2`.
3. Fix the metrics port, the current config was incorrectly changed to make aptos-node share a metrics port with haproxy. Metrics are randomly shuffled by aptos-node or haproxy for each request. 
It was incorrectly changed in the following commit
https://github.com/aptos-labs/aptos-core/commit/84ab6fa7a4060d21e6cb31eeadbb58da1cb88da9#diff-e14828a9d40dad356c6aa567c7e8fe99c86d368226a8cf348e172d0998f90053L169
> Haproxy update and fix

- aptos-move/framework/aptos-framework/doc/randomness.md
- aptos-move/framework/aptos-framework/sources/randomness.move
> V117 randomness module update

- config/src/config/mempool_config.rs
- consensus/src/transaction_shuffler/use_case_aware/delayed_queue.rs
- consensus/src/transaction_shuffler/use_case_aware/iterator.rs
- consensus/src/transaction_shuffler/use_case_aware/mod.rs
- consensus/src/transaction_shuffler/use_case_aware/tests/mod.rs
- consensus/src/transaction_shuffler/use_case_aware/types.rs
- mempool/src/core_mempool/mempool.rs
- mempool/src/counters.rs
- mempool/src/shared_mempool/coordinator.rs
- mempool/src/shared_mempool/mod.rs
- mempool/src/shared_mempool/tasks.rs
- mempool/src/shared_mempool/types.rs
- mempool/src/shared_mempool/use_case_history.rs
- state-sync/inter-component/mempool-notifications/src/lib.rs
- state-sync/state-sync-driver/src/tests/utils.rs
- types/src/transaction/mod.rs
- types/src/transaction/use_case.rs
Track frequency of usecases in recent blocks (or during state sync - recent batches), and then report latency counters separately for top usecases, as well as framework and others (i.e. scripts)
We can then use this for monitoring, and gas estimation and more
> e2e counters split out by top usecases

- config/src/config/consensus_config.rs
- config/src/config/quorum_store_config.rs
- consensus/consensus-types/src/common.rs
- consensus/consensus-types/src/pipelined_block.rs
- consensus/src/block_storage/block_store.rs
- consensus/src/block_storage/mod.rs
- consensus/src/counters.rs
- consensus/src/dag/bootstrap.rs
- consensus/src/dag/health/chain_health.rs
- consensus/src/dag/health/pipeline_health.rs
- consensus/src/epoch_manager.rs
- consensus/src/execution_pipeline.rs
- consensus/src/liveness/proposal_generator.rs
- consensus/src/pipeline/execution_schedule_phase.rs
- consensus/src/state_computer.rs
- consensus/src/test_utils/mock_state_computer.rs
- execution/executor-types/src/lib.rs
- testsuite/forge-cli/src/main.rs
We can have gas miscalibration for various reasons, leading to a block taking longer than intended 300ms even after block gas limit has been applied. 
And so here we make sure on consensus side to gracefully handle it.
We track execution speed of historical blocks, and their sizes - and compute what block size should've been such that it lasted 300ms. We then take p50 of previous 10 blocks - and use that as the block limit for the next block.
Once we have improved re-ordering and execution pool, we can additionally use reordering_ovarpacking_factor to create larger blocks - but only execute wanted number of transactions.
Currently execution stage is the bottleneck almost always, and so this PR only touches that. But practically - we can do the same for each stage, to make sure to reduce …
> Execution speed backpressure to handle consistent gas miscalibration

- devtools/aptos-cargo-cli/src/common.rs
This PR updates the target determinator to ignore out-of-date merge base errors on the 1.17 release branch. It's the same fix as this: https://github.com/aptos-labs/aptos-core/pull/13939.
Going forward, I'll try to figure out how to avoid this problem so we don't run into it again...
> [Target Determinator] Ignore the merge base out-of-date error.

- Cargo.lock
- crates/aptos-rosetta/Cargo.toml
- crates/aptos-rosetta/src/account.rs
- crates/aptos-rosetta/src/block.rs
- crates/aptos-rosetta/src/common.rs
- crates/aptos-rosetta/src/construction.rs
- crates/aptos-rosetta/src/error.rs
- crates/aptos-rosetta/src/lib.rs
- crates/aptos-rosetta/src/main.rs
- crates/aptos-rosetta/src/network.rs
- crates/aptos-rosetta/src/types/identifiers.rs
- crates/aptos-rosetta/src/types/misc.rs
- crates/aptos-rosetta/src/types/move_types.rs
- crates/aptos-rosetta/src/types/objects.rs
- crates/aptos-rosetta/src/types/requests.rs
- testsuite/smoke-test/src/rosetta.rs
Adds documentation for the Rosetta codebase around remaining design decisions.
Builds on top of https://github.com/aptos-labs/aptos-core/pull/14104
> [Rosetta] Document design decisions and remaining code

- api/types/src/convert.rs
- api/types/src/move_types.rs
- aptos-move/aptos-release-builder/data/release.yaml
- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/aptos-resource-viewer/src/lib.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/e2e-move-tests/src/tests/script_with_object_param.data/pack/Move.toml
- aptos-move/e2e-move-tests/src/tests/script_with_object_param.data/pack/sources/test.move
- aptos-move/e2e-move-tests/src/tests/scripts.rs
- testsuite/generate-format/tests/staged/api.yaml
- testsuite/generate-format/tests/staged/aptos.yaml
- testsuite/generate-format/tests/staged/consensus.yaml
- third_party/move/move-core/types/src/transaction_argument.rs
- third_party/move/tools/move-resource-viewer/src/lib.rs
- types/src/on_chain_config/aptos_features.rs
Script argument need to be updated so we can pass more complex arguments as we did for entry point functions.
Test implemented
- Compatibility: will this be a backward compatible change?
- Security: will this code cause new attack surfaces?
> [aptos-vm] Allowing raw bytes for script argument

- Cargo.lock
- Cargo.toml
- keyless/pepper/common/Cargo.toml
- keyless/pepper/common/src/account_recovery_db.rs
- keyless/pepper/common/src/aud_db.rs
- keyless/pepper/common/src/lib.rs
- keyless/pepper/example-client-rust/Cargo.toml
- keyless/pepper/example-client-rust/src/main.rs
- keyless/pepper/readme.md
- keyless/pepper/service/Cargo.toml
- keyless/pepper/service/src/account_db.rs
- keyless/pepper/service/src/lib.rs
- keyless/pepper/service/src/main.rs
- Pepper service will save the account derivation preimages into an "account recovery DB", which is later to be used by the keyless account recovery service.
- Make HTTP request handling functions async (in order to adopt firestore async rust APIs).
Local manual test suite as specified in `keyless/pepper/readme.md`.
The DB schema `AccountRecoveryDbEntry`.
> account recovery db

- consensus/consensus-types/src/block.rs
- consensus/consensus-types/src/common.rs
- consensus/consensus-types/src/lib.rs
- consensus/consensus-types/src/payload.rs
- consensus/consensus-types/src/proof_of_store.rs
- consensus/src/consensus_observer/network_message.rs
- consensus/src/payload_manager.rs
- consensus/src/quorum_store/batch_requester.rs
- consensus/src/quorum_store/batch_store.rs
- consensus/src/quorum_store/quorum_store_builder.rs
- consensus/src/quorum_store/tests/batch_requester_test.rs
- consensus/src/quorum_store/tests/proof_coordinator_test.rs
- consensus/src/util/db_tool.rs
- testsuite/generate-format/src/consensus.rs
- testsuite/generate-format/tests/staged/consensus.yaml
- Introduces `OptQuorumStore` variant to `Payload` enum to support Optimistic QS batches in consensus. 
- Introduces `OptQuorumStorePayload` enum as value for the `Payload::OptQuorumStore` variant. The enum helps in future extensibility.
- Introduces a generic `CachedDataPointer<T: TDataInfo>` struct as a replacement to `ProofWithData`. The generic struct can hold both Proofs and BatchInfos for Optimistic batches. `TDataInfo` is a trait to support common operations across proofs and batches.
- Introduces `PayloadExecutionLimit` enum to support extensible way to specify execution limits for QuorumStore batches.
- Adds support for the new Payload variant to PayloadManager.
> [consensus][qs] Introduce OptQuorumStorePayload Payload

- consensus/src/consensus_observer/network_message.rs
- consensus/src/consensus_observer/payload_store.rs
This PR adds several simple unit tests to consensus observer. Specifically, it offers the following commits:
1. Clean up the display implementation.
2. Add simple unit tests for network message verification.
3. Add a missing unit test for the block payload store.
Nothing should logically change.
> [Consensus Observer] Add simple unit tests.

- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/verifier/event_validation.rs
- aptos-move/e2e-move-tests/src/tests/metadata.rs
- aptos-move/framework/src/module_metadata.rs
- types/src/on_chain_config/aptos_features.rs
This PR adds a check in the VM when running bytecode generated by an unstable compiler or containing unstable language feature on mainnet
Added an e2e move test
1. logic of checking in the VM;
2. coverage in e2e move tests.
> [Compiler-v2][VM] add metadata check for script

- testsuite/forge-cli/src/main.rs
This PR removes the P90 assertion from realistic_env_max_load to help unblock forge.
> [Forge] Remove P90 assertion to unblock realistic_env_max_load.

- consensus/src/block_storage/block_store.rs
- consensus/src/counters.rs
- consensus/src/dag/tests/helpers.rs
- consensus/src/payload_manager.rs
- consensus/src/round_manager.rs
- testsuite/forge-cli/src/main.rs
This PR adds support for processing proposals with OptQuorumStorePayload in consensus. Round manager ensures that the data corresponding to optimistic batches exist before signing the proposal. Otherwise, the proposal is enqueued until QS acknowledges data availability. 
Naively, this PR checks if optimistic batches are available locally and proceeds processing the proposal if so. If not, it wait until QS fetches both optimistic batches and **proof batches**.
> [consensus][qs] support OptQuorumStorePayload in consensus

- testsuite/forge-cli/src/main.rs
This PR increases the state sync chunk sizes for the `realistic_env_max_load_test` forge tests. This seems to prevent storage from becoming bottlenecked and slowing down VFNs in the relevant tests.
> [Forge] Avoid commit bottleneck in forge.

- testsuite/forge-cli/src/main.rs
This PR bumps the PFN const TPS forge stable latency criteria. The TPS was increased by this [PR](https://github.com/aptos-labs/aptos-core/commit/681a54de09d0843288fe2fb02be4de5480624200) (from 100 -> 5k), but the latency criteria was not updated. Thus, the job is failing for forge stable.
> [Forge] Increase PFN const TPS limits.

- api/src/accounts.rs
- api/types/src/convert.rs
- api/types/src/move_types.rs
- aptos-move/aptos-release-builder/src/components/mod.rs
- aptos-move/aptos-resource-viewer/src/lib.rs
- aptos-move/framework/src/natives/string_utils.rs
- testsuite/fuzzer/fuzz/fuzz_targets/move/utils.rs
- third_party/move/move-core/types/src/value.rs
- third_party/move/move-model/bytecode/src/stackless_bytecode_generator.rs
- third_party/move/move-model/src/model.rs
- third_party/move/move-vm/types/src/delayed_values/derived_string_snapshot.rs
- third_party/move/move-vm/types/src/values/mod.rs
- third_party/move/move-vm/types/src/values/serialization_tests.rs
- third_party/move/move-vm/types/src/values/values_impl.rs
- third_party/move/tools/move-resource-viewer/src/fat_type.rs
- third_party/move/tools/move-resource-viewer/src/lib.rs
This adapts more functionality around enums/struct variants for move value representation:
- `MoveStructLayout::WithVariants` is a new decorated representation for variant types, and `MoveStruct::WithVariant` is the matching decorated value representation. Code has been adapted to deal with those decorated versions
- Unfortunately, we do not only have serializers/deserializers in `value.rs` (which where already implemented for variants) but also `value_impl.rs`. It is unclear what of this code is used where, so implemented now the serialization logic a 2nd time in `value_impl.rs` with support of custom serializers.
- Adapted yet another redundant type representation to support variants, `FatType` in resource viewer. Extended `AnnotatedMoveValue` to carry an optional field for variant …
> [move-2] Decorated values and resource viewer for enum types

- mempool/src/core_mempool/mempool.rs
Missunderstood which mempool counter is for what - switching usecase counter to give e2e breakdown, only for non-parked txns.
> [trivial] switch usecase counter to measure e2e

- Cargo.lock
- aptos-move/aptos-gas-profiling/src/aggregate.rs
- aptos-move/e2e-move-tests/Cargo.toml
- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-move-tests/src/tests/gas.rs
> Gas profiling of EntryPoints from transaction generator

- keyless/pepper/common/src/account_recovery_db.rs
- keyless/pepper/example-client-rust/src/main.rs
- keyless/pepper/service/src/lib.rs
- In addition to last request time, now also track first request time and number of requests.
- Also avoid updating account recovery DB when it's a V0signature request.
Local manual testing.
See comments in function `update_account_recovery_db` about the transaction details.
> account recovery db, more counters

- Cargo.lock
- Cargo.toml
- docker/builder/build-indexer.sh
- docker/builder/indexer-grpc.Dockerfile
- ecosystem/indexer-grpc/indexer-grpc-file-store-backfiller/Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-file-store-backfiller/README.md
- ecosystem/indexer-grpc/indexer-grpc-file-store-backfiller/src/lib.rs
- ecosystem/indexer-grpc/indexer-grpc-file-store-backfiller/src/main.rs
- ecosystem/indexer-grpc/indexer-grpc-file-store-backfiller/src/processor.rs
Create a file store backfiller. This consumes data from an archive fullnode.
Tested in testnet and mainnet; looks good.
> [indexer] File store backfiller

- aptos-move/e2e-benchmark/src/main.rs
- testsuite/single_node_performance.py
- third_party/move/move-binary-format/src/file_format_common.rs
- third_party/move/move-core/types/src/value.rs
- third_party/move/move-vm/types/src/values/serialization_tests.rs
- third_party/move/move-vm/types/src/values/values_impl.rs
After using Rust macro expand to analyze how serde deals with Rust enums, updating the Move serializers to align with this. Uses now serde's `serialize_unit_variant`, `serialize_newtype_variant`, and `serialize_tuple_variant` and the matching counterparts for deserialization.
Onne obstacle here until now was the need to pass `&static str` variant names to the serializers. However, those names are not used by bcs serialization logic, which uses variant tags instead, they are only required by serde for other formats. This is a solved by having a static cache which constructs those strings via box leaking as `"0"`, `"1"`, etc.
Closes #14159.
There are multiple new tests, including roundtrip serialization Rust <-> Move in `serialization_tests`. Also verified manually that the generated …
> [move 2] Synchronize Move and Rust enum serialization

- consensus/src/counters.rs
- consensus/src/liveness/proposal_generator.rs
- consensus/src/liveness/proposal_generator_test.rs
- consensus/src/liveness/round_state.rs
- consensus/src/round_manager.rs
- consensus/src/round_manager_fuzzing.rs
This PR moves proposal generation to its own task so it does not block the round manager event loop. Proposal generation is heavy and blocking involving time sleeps. Moving it to an async task will allow RoundManager event loop to continue to process other events while proposal is generated. 
In addition, also removes the leader timeout step before the proposal. This is no longer needed because we now broadcast the votes to all nodes.
> [consensus] async proposal generation

- testsuite/fuzzer/.cargo/config.toml
Moved linker to `gold` with tuning flags to try to save memory. If this does not work, I need to work off files to reduce size.
Needs to be tested on Google infra.
N/A
> [tentative] Move fuzzer to gold linker

- .github/actions/move-tests-compiler-v2/action.yaml
- .github/actions/rust-doc-tests/action.yaml
- .github/actions/rust-lints/action.yaml
- .github/actions/rust-smoke-tests/action.yaml
- .github/actions/rust-targeted-unit-tests/action.yaml
- .github/actions/rust-unit-tests/action.yaml
- .github/workflows/lint-test.yaml
Remove the rust-setup and `cargo install nextest` steps from the lint-test workflows. These are now included in the custom image used by the runs-on runners
See the workflow runs for this PR
> remove dev_setup from lint-test workflow

- devtools/aptos-cargo-cli/src/common.rs
This PR increases the merge base date check for the 1.18 release branch. This check will be updated on `main` to avoid impacting release branches.
> [CI/CD] Increase merge base check for v1.18 release branch.

- consensus/src/counters.rs
- consensus/src/execution_pipeline.rs
- consensus/src/pipeline/buffer_manager.rs
> [consensus] Downgrade error!() from channel closing in pipeline execution

- .github/actions/rust-check-merge-base/action.yaml
- .github/actions/rust-targeted-unit-tests/action.yaml
- .github/workflows/lint-test.yaml
- devtools/aptos-cargo-cli/src/common.rs
- devtools/aptos-cargo-cli/src/lib.rs
This PR makes several small improvements to the target determinator. Specifically:
1. We add a new "check merge base" CI/CD job that will ensure the merge base for PRs is up-to-date (within 7 days). Although we already have this check, the new job will only run on PRs to the `main` branch, so it should help us avoid the issue we're currently seeing with release branches (i.e. the need for these fixes: https://github.com/aptos-labs/aptos-core/pull/14120).
1. We improve the cargo metadata error handling during the target determination process. If cargo metadata cannot be fetched remotely (e.g., from GCS), we instead compute it locally by checking out a temporary clone of the `aptos-core` repository at the merge base and computing the metadata. This should help to avoid issues with remote …
> [Target Determinator] Small improvements to metadata and merge base checks.

- third_party/move/move-compiler-v2/src/bytecode_generator.rs
- third_party/move/move-compiler-v2/tests/bytecode-generator/matching_ok.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/matching_ok.move
- third_party/move/move-compiler-v2/tests/checking/positional_fields/common_access.exp
- third_party/move/move-compiler-v2/tests/checking/positional_fields/invalid_common_access.exp
- third_party/move/move-compiler-v2/tests/checking/positional_fields/invalid_common_access.move
- third_party/move/move-compiler-v2/tests/checking/variants/variants_check_err.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_check_err.move
- third_party/move/move-compiler-v2/tests/checking/variants/variants_ok.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_ok.move
- third_party/move/move-compiler-v2/tests/file-format-generator/struct_variants.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/struct_variants.move
- third_party/move/move-compiler-v2/tests/file-format-generator/struct_variants.opt.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_field_select_different_offsets.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_field_select_different_offsets.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_field_select_different_offsets.no-optimize.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_field_select_different_offsets.optimize-no-simplify.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_field_select_different_offsets.optimize.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/tests.rs
- third_party/move/move-model/src/ast.rs
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/builder/model_builder.rs
- third_party/move/move-model/src/builder/module_builder.rs
- third_party/move/move-model/src/model.rs
- third_party/move/move-model/src/ty.rs
- third_party/move/move-prover/boogie-backend/src/spec_translator.rs
This circles back to the frontend and completes the intended enum implementation as it is now supported by the VM.
- Let the checker allow selecting fields which are not present in all variants.
- Adds a new expression operation `SelectVariants` to represent selecting a field from a variant.
- Implements `SelectVariants` in the bytecode generator to generate a sequence of tests if selecting fields at different positions of variants.
- Removes the now obsolete common_field property. Also, each variant field now has a unique FieldId in contrast to before where common fields shared the same id.
This is tested in various stages of the compiler including transactional tests.
> [compiler-v2] Complete implementation of enum field selection

- third_party/move/move-compiler-v2/src/pipeline/reference_safety_processor.rs
- third_party/move/move-compiler-v2/tests/reference-safety/bug_13973_branch_cond_borrowed.exp
- third_party/move/move-compiler-v2/tests/reference-safety/bug_13973_branch_cond_borrowed.move
- third_party/move/move-compiler-v2/tests/reference-safety/bug_13973_branch_cond_borrowed.no-opt.exp
- third_party/move/move-compiler-v2/tests/testsuite.rs
Fixes #13973.
New test from the bug
> [move-compiler-v2] Restrict usage of mutably borrowed locals in branch conditions

- third_party/move/move-compiler-v2/src/bytecode_generator.rs
- third_party/move/move-compiler-v2/tests/ability-check/v1-typing/pack_constraint_not_satisfied.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/matching_ok.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/matching_ok.move
- third_party/move/move-compiler-v2/tests/checking/error_context/assign.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_err.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_err.move
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_ok.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_ok.move
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_parse_err1.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_parse_err1.move
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_parse_err2.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_parse_err2.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_variant_test.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_variant_test.move
- third_party/move/move-compiler/src/expansion/ast.rs
- third_party/move/move-compiler/src/expansion/dependency_ordering.rs
- third_party/move/move-compiler/src/expansion/translate.rs
- third_party/move/move-compiler/src/naming/translate.rs
- third_party/move/move-compiler/src/parser/ast.rs
- third_party/move/move-compiler/src/parser/syntax.rs
- third_party/move/move-model/src/ast.rs
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/ty.rs
- third_party/move/move-prover/boogie-backend/src/spec_translator.rs
This adds the last missing feature to enums, namely the variant test `x is Foo::Variant`.
- Extends the parser and expansion phase
- Extends checker, introducing a new Exp `Operation::TestVariants`
- Extends the bytecode generator to map this down to the (existing) TestVariant opcode
Tests have been added for the various stages of the pipeline
> [compiler-v2] Implements `x is Foo::Variant` feature

- consensus/src/counters.rs
- execution/executor/src/components/chunk_output.rs
As this can be a common reason and not really a cause for concern in terms of transaction failures themselves.
> [metrics] add a failure reason in counters for expired transactions

- crates/aptos/src/node/analyze/analyze_validators.rs
- crates/aptos/src/node/mod.rs
- testsuite/forge-cli/src/main.rs
- testsuite/forge-cli/src/suites/dag.rs
- testsuite/forge/src/success_criteria.rs
- testsuite/testcases/tests/forge-local-performance.rs
`analyze-validator-performance --analyze-mode network-health-over-time` cli command gives health statistics of the network over time. Adding gap analysis to it as well, as an useful metric if there are any issues or not
`cargo run -p aptos -- node analyze-validator-performance --analyze-mode network-health-over-time --url https://fullnode.mainnet.aptoslabs.com/ --start-epoch=-12`
returns
```
Max non-epoch-change gaps: 2 rounds at version 1039252739 (avg 0.00), 3.44s no progress at version 1039252739 (avg 0.22s).
Max epoch-change gaps: 0 rounds at version 0 (avg 0.00), 3.92s no progress at version 1038729529 (avg 2.76s).
```
> Add chain gap/pause analysis from onchain data to CLI 

- aptos-move/framework/aptos-framework/doc/aptos_account.md
- aptos-move/framework/aptos-framework/sources/aptos_account.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- crates/transaction-generator-lib/src/args.rs
- crates/transaction-generator-lib/src/lib.rs
- crates/transaction-generator-lib/src/p2p_transaction_generator.rs
- execution/executor-benchmark/src/lib.rs
- testsuite/single_node_performance.py
- testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs
- testsuite/smoke-test/src/rest_api.rs
Enabling FA for APT in regression benchmarks, so we can track and catch any regressions in the FA framework.
Also added storage_fee to reports.
> Enable FA for APT for regression single node benchmark

- Cargo.lock
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
Updated `aptos` crate version from `3.5.1` to `4.0.0` to include recent breaking changes with a new native function not being found.
> [cli] Bump to 4.0.0

- crates/aptos-dkg/benches/crypto.rs
- crates/aptos-dkg/benches/pvss.rs
- crates/aptos-dkg/benches/weighted_vuf.rs
- crates/aptos-dkg/src/pvss/das/unweighted_protocol.rs
- crates/aptos-dkg/src/pvss/low_degree_test.rs
- crates/aptos-dkg/src/pvss/test_utils.rs
- crates/aptos-dkg/src/pvss/weighted/weighted_config.rs
- crates/aptos-dkg/src/weighted_vuf/bls/mod.rs
This PR adds more benchmarks in our `aptos-dkg` crate, which were added as I was working on our SBC'24 presentation of the randomness crypto. These benchmarks should've been there to begin with though.
It has not.
@danielxiangzl, is the change to the `WeightedConfig` struct problematic? Does that end up being serialized? AFAICT, it does not. Trying to figure this out by removing the (de)serialization derives...
> [crypto] added more aptos-dkg benchmarks

- third_party/move/move-compiler-v2/tests/ability-check/bug_14189.exp
- third_party/move/move-compiler-v2/tests/ability-check/bug_14189.move
- third_party/move/move-compiler-v2/tests/ability-check/bug_14227.exp
- third_party/move/move-compiler-v2/tests/ability-check/bug_14227.move
- third_party/move/move-compiler-v2/tests/reference-safety/immu_borrow_bug.exp
- third_party/move/move-compiler-v2/tests/reference-safety/immu_borrow_bug.move
- third_party/move/move-compiler-v2/tests/reference-safety/immu_borrow_bug.no-opt.exp
Two test cases from #14189 and #14227 and one test case generating the error `cannot immutably borrow since mutable references exist`
> [Compiler-v2] test cases for MOVELOC_UNAVAILABLE_ERROR and borrow analysis

- aptos-node/src/consensus.rs
- aptos-node/src/lib.rs
- consensus/src/consensus_observer/mod.rs
- consensus/src/consensus_observer/network_handler.rs
- consensus/src/consensus_observer/observer.rs
- consensus/src/consensus_observer/publisher.rs
- consensus/src/consensus_provider.rs
Note: this PR is just a refactor. Nothing should really change.
This PR adds a dedicated network handler to the consensus observer. The network handler is a simple component that processes incoming consensus observer messages and forwards them to the observer, or publisher, depending on the destination. 
This is cleaner than the current approach, which makes the observer forward messages to the publisher. In some cases (e.g., validators), only the publisher is running, so we still need to create a "dummy observer" to perform message forwarding. Now, with the network handler, we can avoid this.
1. Add a simple network handler.
2. Add simple unit tests to check the network client and handler.
> [Consensus Observer] Add simple network handler.

- consensus/src/rand/rand_gen/rand_manager.rs
Invalid aug data doesn't have to be error-level.
n/a
n/a
> aug error log level update

- third_party/move/move-model/src/builder/module_builder.rs
- third_party/move/move-prover/bytecode-pipeline/src/data_invariant_instrumentation.rs
- third_party/move/move-prover/tests/sources/functional/invariants.exp
- third_party/move/move-prover/tests/sources/functional/invariants.move
- third_party/move/move-prover/tests/sources/functional/invariants.v2_exp
- third_party/move/move-prover/tests/sources/functional/invariants_positional.exp
- third_party/move/move-prover/tests/sources/functional/invariants_positional.move
- third_party/move/move-prover/tests/sources/functional/invariants_positional.v2_exp
This PR allows users to use the receiver style `self` in struct invariants when the language version is at least 2.0. For instance, for the struct below:
```
module 0x42::TestInvariants {
struct PositionalStruct(u64, u64) has key, copy, drop;
}
```
We can write the invariant as below:
```
spec PositionalStruct {
invariant self.0 > 10;
invariant self.1 < 10;
}
```
Note that if a struct has a field called `self`:
```
struct StructSelf has key, copy, drop {
self: u64
}
```
We need to use `self.self` to access the field instead of directly using `self`:
```
spec StructSelf {
invariant self.self > 10;
}
```
Existing tests pass and new tests.
> [prover] Add support of using receiver style `self` in struct invariants

- experimental/storage/hexy/src/in_mem/overlay.rs
- experimental/storage/hexy/src/tests/mod.rs
- experimental/storage/layered-map/src/iterator.rs
- experimental/storage/layered-map/src/layer.rs
- experimental/storage/layered-map/src/map.rs
- experimental/storage/layered-map/src/node.rs
- experimental/storage/layered-map/src/tests.rs
A view represents the content of a left-exclusive, right-exclusive range of layers, so that the batches we merge into the HexyBase won't have overlaps.
unit tests
> [experimental] LayeredMap: base-exclusive

- third_party/move/move-compiler-v2/src/pipeline/unused_assignment_checker.rs
- third_party/move/move-compiler-v2/tests/unused-assignment/bug-13880.move
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/op_with_side_effect_14.operator-eval-lang-2.exp
- third_party/move/move-model/src/model.rs
Fixes https://github.com/aptos-labs/aptos-core/issues/13880 by skip checking instructions expanded from inline function calls.
Existing tests and `third_party/move/move-compiler-v2/tests/unused-assignment/bug-13880.move` (new)
> [Bugfix] [Compiler-V2] Fix spurious warnings on inline functions from unused assignment checking

- aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/diamond_clicker.v2_exp
- aptos-move/framework/aptos-stdlib/tests/compiler-v2-doc/math128.md
- aptos-move/framework/aptos-stdlib/tests/compiler-v2-doc/math64.md
- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs
- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/reducible_pairs.rs
- third_party/move/move-compiler-v2/tests/file-format-generator/has_script.opt.exp
- third_party/move/move-compiler-v2/tests/variable-coalescing/branch_assigns_then_moves_then_assigns.exp
- third_party/move/move-compiler-v2/tests/variable-coalescing/branch_assigns_then_moves_then_assigns.opt.exp
- third_party/move/move-compiler-v2/tests/variable-coalescing/bug_12068.exp
- third_party/move/move-compiler-v2/tests/variable-coalescing/bug_12068.opt.exp
- third_party/move/tools/move-cli/tests/build_tests/disassemble_script/args.v2_exp
In this PR, we add a new peephole optimization on the file format bytecode: instances of pairs (`LdTrue`, `BrFalse`) and (`LdFalse`, `BrTrue`) are both removed. This was originally suggested by @brianrmurphy during a code review.
Note that these new peephole optimizations can change basic blocks by merging then, and we have found instances where redoing peephole optimizations on the new basic blocks can reduce code (see changed exp files). Therefore, we rerun basic block optimizations every time the number of basic blocks change.
Existing tests, all updated exp files were validated to produce better (or equal) code.
Changes to rust files.
> [compiler-v2] Basic block merging peephole optimization

- config/src/config/state_sync_config.rs
- mempool/src/shared_mempool/network.rs
- network/framework/src/transport/mod.rs
- state-sync/data-streaming-service/src/data_stream.rs
- state-sync/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-driver/src/tests/bootstrapper.rs
This PR makes several small tweaks and logging improvements to node infra related components. The commits are as follows:
1. Increase the supported fast sync lag and improve the error message.
1. Downgrade the noise handshake network error logs.
1. Increase the maximum chunk size for state sync from 6MB -> 8MB (we want to favor output syncing slightly more, given that latency aware peer dialing is working).
1. Reduce/remove some unnecessary logs.
> [Node Infra] Small tweaks and logging improvements.

- config/src/config/mempool_config.rs
Enable include_ready_time_in_broadcast flag for VFNs
> Enable include_ready_time_in_broadcast flag for VFNs

- third_party/move/move-compiler-v2/tests/checking/receiver/dont_warn_unused_self.exp
- third_party/move/move-compiler-v2/tests/checking/receiver/dont_warn_unused_self.move
- third_party/move/move-compiler/src/hlir/ast.rs
- third_party/move/move-compiler/src/hlir/translate.rs
- third_party/move/move-compiler/tests/move_check/locals/dont_warn_unused_self.exp
- third_party/move/move-compiler/tests/move_check/locals/dont_warn_unused_self.move
This omits the warning for unused self parameters in the v1 compiler, in case we run it on v2 code.
v2 does already omit the warning.
Fixes #14361
Added test cases for both v1 and v2.
> [compiler-v1] Omit warning for unused `self` parameter

- consensus/consensus-types/src/common.rs
- consensus/consensus-types/src/payload.rs
- consensus/consensus-types/src/proof_of_store.rs
- consensus/src/payload_manager.rs
- consensus/src/round_manager.rs
- execution/executor-types/src/error.rs
`PayloadManager::get_transactions` is neither cancellation safe nor allows concurrency. It's however needed to support OptQuorumStore.  Concurrency is necessary because if we receive duplicate proposals and both have to wait for the payload.
Instead of storing the oneshot receivers in `Option<DataStatus>` and `take`ing them out to release the mutex, a shared future is introduced that polls the oneshot receivers. With a shared future, any caller of `get_transaction` will await on the same future even when called concurrently. The shared future returns an error if any of the oneshot results in error. In this case, the request is re-submitted and the future is re-initialized.
> [consensus] cancellation safety in payload manager

- testsuite/forge-cli/src/main.rs
Bumping thresholds for realistic_env_load_sweep and realistic_env_max_load_large tests.
> [forge] bump thresholds for failing stable tests

- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/framework/aptos-token-objects/doc/collection.md
- aptos-move/framework/aptos-token-objects/doc/token.md
- aptos-move/framework/aptos-token-objects/sources/collection.move
- aptos-move/framework/aptos-token-objects/sources/token.move
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.move
- types/src/on_chain_config/aptos_features.rs
Cherry pick of https://github.com/aptos-labs/aptos-core/pull/14307
> Separate out collection creator and owner permissions (#14307)

- testsuite/forge-cli/src/main.rs
It seems that using default syncing mode passes the working quorum test. 
https://github.com/aptos-labs/aptos-core/actions/runs/10517320138
> [forge] use default syncing mode for working quorum test

- third_party/move/tools/move-package/src/compilation/compiled_package.rs
This PR is makes the `make_source_and_deps_for_compiler` function public so it can by the external `move-mutator` tool located in the [eiger/move-spec-testing](https://github.com/eigerco/move-spec-testing) repo.
N/A - no new functionality has been added.
Simple API visibility change.
One can observe here how it is used in the external repository:
https://github.com/eigerco/move-spec-testing/blob/703d6a75deae02e9080b678ebd102c0d34926f33/third_party/move/tools/move-mutator/src/compiler.rs#L155
The above solution locally references `move-package`, but in the next iteration of the tool, `move-package` and all other `aptos-core` files will be removed from that repository, so such an option won't be available.
> [move-package]: make `make_source_and_deps_for_compiler` public

- consensus/src/quorum_store/batch_proof_queue.rs
`pull_internal` is returning the `!full`, but it is expected to return `full` to indicate when the block was fully packed with proofs. This fixes it.
> [qs][fix] return full status in ProofBatchQueue::pull_internal

- third_party/move/tools/move-unit-test/src/test_runner.rs
This PR closes #14401 by setting the bytecode version to the version of the compiled module during serialization.
Manually testing by executing the command `aptos move test --compiler-version=v2 --language-version=2` against a move project that uses enum and has unit tests
1) whether it is the correct place to set the bytecode version;
2) whether the correct version is set.
> [Compiler-v2][trivial] set bytecode version during serialization of module in move unit test 

- third_party/move/move-compiler-v2/tests/checking/unused/unused_enum.exp
- third_party/move/move-compiler-v2/tests/checking/unused/unused_enum.move
- third_party/move/move-compiler/src/expansion/dependency_ordering.rs
This PR closes #14400 by adding the case for enum type when analyzing dependency.
FIxes #14400.
Existing tests pass.
Added a new test.
> [compiler-v2] add usage check for enum in expansion phase

- config/src/config/consensus_config.rs
Reduce pipeline or higher workloads.
> Reduce pipeline backpressure

- .github/workflows/workflow-run-forge.yaml
- testsuite/fixtures/forge-test-runner-template.fixture
- testsuite/forge-cli/src/main.rs
- testsuite/forge-test-runner-template.yaml
- testsuite/forge.py
- testsuite/forge/src/runner.rs
- testsuite/forge_test.py
Allow retention of all Forge logs with the new `FORGE_RETAIN_DEBUG_LOGS` env var. This sets some new helm values and adds the `aptos.dev/min-log-level-to-retain` pod annotation to the validator nodes during a Forge run
- Ran the adhoc Forge workflow, see #14275
> add option to retain all forge logs

- .github/workflows/adhoc-forge.yaml
- .github/workflows/workflow-run-forge.yaml
- testsuite/forge-cli/src/main.rs
- testsuite/forge-test-runner-template.yaml
- testsuite/forge.py
- testsuite/forge/src/runner.rs
Update the ad-hoc Forge workflow with an input to retain all Forge logs
- Ran the adhoc Forge workflow
- `helm get values aptos-node -n forge-runner-1724090704`
- Check that the new values are in the helm values
```
podAnnotations:
aptos.dev/log-levels: warn,info,error
```
> Add option to retain all logs for adhoc forge workflow

- .github/workflows/adhoc-forge.yaml
This workflow should point to `main` instead of my own branch. Follow up to #14275
> point adhoc forge workflow to main branch

- third_party/move/move-compiler-v2/tests/checking-lang-v1/direct_visibility.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v1/direct_visibility.move
- third_party/move/move-compiler-v2/tests/checking/visibility-checker/direct_visibility.exp
- third_party/move/move-compiler-v2/tests/checking/visibility-checker/direct_visibility.move
- third_party/move/move-compiler-v2/tests/checking/visibility-checker/direct_visibility_err.exp
- third_party/move/move-compiler-v2/tests/checking/visibility-checker/direct_visibility_err.move
- third_party/move/move-compiler-v2/tests/checking/visibility-checker/direct_visibility_err2.exp
- third_party/move/move-compiler-v2/tests/checking/visibility-checker/direct_visibility_err2.move
- third_party/move/move-compiler-v2/tests/checking/visibility-checker/direct_visibility_err3.exp
- third_party/move/move-compiler-v2/tests/checking/visibility-checker/direct_visibility_err3.move
- third_party/move/move-compiler/src/parser/syntax.rs
The syntax `public(friend) fun` and `public(package) fun` is unnecessary verbose. Taken over from Rust, perhaps in Rust `pub(crate) fn` is OK, but Move does add to much noise.
This PR suggests to introduce the syntax `package fun` and `friend fun`. Those read naturally and are also in this in other languages. (E.g. C#).
New tests
> [compiler-v2] More concise visibility declarations

- third_party/move/move-compiler-v2/tests/ability-check/v1-typing/pack_constraint_not_satisfied.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/matching_refutable_err.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/matching_refutable_err.move
- third_party/move/move-compiler-v2/tests/checking/indexing/examples_book.exp
- third_party/move/move-compiler-v2/tests/checking/indexing/examples_book.move
- third_party/move/move-compiler-v2/tests/checking/specs/structs_err.exp
- third_party/move/move-compiler-v2/tests/checking/typing/bad_type_argument_arity_struct_unpack.exp
- third_party/move/move-compiler-v2/tests/checking/typing/native_structs_pack_unpack.exp
- third_party/move/move-compiler-v2/tests/checking/typing/pack_invalid_argument.exp
- third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_pack_invalid.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_check_err.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_constants.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_constants.move
- third_party/move/move-compiler-v2/tests/checking/variants/variants_inference.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_inference.move
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/tests/sources/structs_err.exp
Those fixes resulted from testing various scenarios for the Move book
- Ensured that simple variant names are inferred for pack and not just unpack. This makes scenarios like `let c: Color = Blue` work.
- Ensured that 0-ary constructors can be used as `Blue` and not need `Blue()` or `Blue{}`. Fixes #14365
A few test cases also now produce better error messages because types are earlier specialized.
> [compiler-v2] Some fixes to enum variant type checking

- third_party/move/move-binary-format/src/deserializer.rs
Accept any known bytecode version in CLI aptos move disassemble.
Fixes #14374
Manual testing.
How concise, how elegant the code fix!
But how clumsy the testing...
> [move-compiler-v2] fix aptos move disassemble CLI to accept all known bytecode versions

- execution/executor-types/src/lib.rs
- state-sync/state-sync-driver/src/metrics.rs
- state-sync/state-sync-driver/src/storage_synchronizer.rs
This PR adds metrics and logs to better track pipeline channel backpressure in the storage synchronizer. Specifically, when a channel gets full, we log the backpressure and track the backpressure in a gauge. This should help us better identify blockages in the pipeline 😄 
> [State Sync] Add metrics and logs for pipeline backpressure.

- third_party/move/move-compiler-v2/src/env_pipeline/model_ast_lints.rs
- third_party/move/move-compiler-v2/src/env_pipeline/model_ast_lints/needless_bool.rs
- third_party/move/move-compiler-v2/src/env_pipeline/model_ast_lints/simpler_numeric_expression.rs
- third_party/move/move-compiler-v2/src/lint_common.rs
- third_party/move/move-compiler-v2/tests/lints/model_ast_lints/needless_bool_warn.exp
- third_party/move/move-compiler-v2/tests/lints/model_ast_lints/needless_bool_warn.move
- third_party/move/move-compiler-v2/tests/lints/model_ast_lints/simpler_numeric_expression_warn.exp
- third_party/move/move-compiler-v2/tests/lints/model_ast_lints/simpler_numeric_expression_warn.move
This PR implements two model-AST lint checks, both inspired from similar rust clippy checks.
We identify code of the form `if (cond) true else false`, and suggest that they can be replaced by just `cond` (similarly, `!cond`, if the the branches were flipped).
We identify various cases of numeric operations that can be replaced with simpler expressions, which can make code simpler to read.
The following cases are checked and simplifications suggested (here, `x` stands for an arbitrary expression, `=>` stands for "can be simplified to"):
* `x & 0`, `x * 0`, `0 & x`, `0 * x`, `0 << x`, `0 >> x`, `x % 1` => `0`
* `x | 0`, `x ^ 0`, `x >> 0`, `x << 0`, `x + 0`, `x - 0`, `x / 1`, `x * 1`, `0 | x`, `0 ^ x`, `0 + x`, `1 * x` => `x`
- Existing tests pass
- New tests have been added to demonstrate …
> [compiler-v2][lint] Needless boolean and Simpler numerical expressions lints

- Cargo.lock
- aptos-move/aptos-e2e-comparison-testing/Cargo.toml
- aptos-move/aptos-e2e-comparison-testing/src/execution.rs
- aptos-move/framework/src/built_package.rs
In a couple of places (that I could discover), we seem to use hard-coded literals for setting bytecode versions, while we have consts defined for them.
Using these consts instead of hard-coded literals will help with discoverability (e.g., you can show all references on a constant and see where it is used and whether that usage needs version upgrade).
> [compiler-v2][trivial] Changing hardcoded bytecode versions with their corresponding defined consts

- third_party/move/scripts/compare_num_instructions.py
The script used to compare number of instructions in two builds of the project, builds disassembler in release mode, but uses disassembler in debug mode. It used to work for me because I had not done a `cargo clean`.
We now build and use the release mode disassembler binary for this script.
Manual
> [bug-fix][trivial] Use the built release binary instead of debug

- consensus/src/pipeline/buffer_manager.rs
- consensus/src/pipeline/decoupled_execution_utils.rs
- consensus/src/pipeline/execution_client.rs
- consensus/src/pipeline/tests/buffer_manager_tests.rs
When we disable pre-commit via local config, also disable buffer manager -- so that consensus behaves more like pre-pre-commit era.
manual forge run
> enable_pre_commit config also guards buffer manager back pressure

- third_party/move/move-compiler-v2/tests/bytecode-generator/bug_14471_receiver_inference.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/bug_14471_receiver_inference.move
- third_party/move/move-model/src/builder/exp_builder.rs
The receiver argument type needs to be specialized in `post_process_receiver_call`.
Fixes #14471
Fixes #14030
Added a test case
> [compiler-v2] Fix a bug in receiver type inference

- Cargo.lock
- aptos-move/e2e-move-tests/src/tests/metadata.rs
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
- third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs
- third_party/move/move-compiler-v2/src/options.rs
- third_party/move/move-compiler-v2/tests/checking-lang-v1/acquires_list_generic.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v1/assert_one_arg.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v1/conditional_global_operations.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v1/receiver_calls.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v1/v1-typing/invalid_type_acquire.exp
- third_party/move/move-model/src/metadata.rs
- third_party/move/move-prover/src/cli.rs
- third_party/move/move-prover/src/lib.rs
- third_party/move/tools/move-package/src/compilation/compiled_package.rs
- third_party/move/tools/move-package/src/compilation/model_builder.rs
Prepare for CLI release 4.1. This makes compiler v2 stable and adds a few new tools.
Manually tested that `--move-2` is not producing a warning about unstable compiler or language.
> [cli] Preparing release 4.1.0

- terraform/helm/aptos-node/templates/fullnode.yaml
- terraform/helm/aptos-node/templates/validator.yaml
Sync helm chart changes. Added support for pod annotations to the helm charts
Created a values file for testing and ran
`helm template . --values test`
> sync helm chart changes for log level annotations

- Cargo.lock
- config/src/config/consensus_observer_config.rs
- consensus/Cargo.toml
- consensus/src/consensus_observer/observer/active_state.rs
- consensus/src/consensus_observer/observer/subscription.rs
- consensus/src/consensus_observer/observer/subscription_manager.rs
- consensus/src/consensus_observer/publisher/consensus_publisher.rs
- consensus/src/payload_manager.rs
- consensus/src/pipeline/buffer_manager.rs
- state-sync/inter-component/consensus-notifications/src/lib.rs
- state-sync/state-sync-driver/src/driver.rs
- state-sync/state-sync-driver/src/metrics.rs
- state-sync/state-sync-driver/src/notification_handlers.rs
- testsuite/smoke-test/src/consensus_observer.rs
- testsuite/smoke-test/src/full_nodes.rs
- testsuite/smoke-test/src/state_sync_utils.rs
- testsuite/smoke-test/src/utils.rs
- types/src/on_chain_config/consensus_config.rs
This PR makes several small improvements to consensus observer (each in their own commit):
1. Make `publish_message()` non-blocking. This helps to ensure that consensus is never blocked by a failure to publish a message.
1. Add more simple smoke tests for consensus observer, including: (i) disabling quorum store; and (ii) disconnecting a validator and VFN.
1. Update consensus observer peer selection to ignore peers that don't support consensus observer. This is done by checking which network protocol IDs are supported at the connection level.
1. Add a simple PFN smoke test for consensus observer.
1. Improve the subscription optimality check logic to only execute if: (i) peers have changed since the last check; or (ii) enough time has elapsed to force a refresh.
1. Small renames and …
> [Consensus Observer] Further improvements and tests.

- consensus/src/quorum_store/counters.rs
- consensus/src/quorum_store/network_listener.rs
- consensus/src/quorum_store/proof_coordinator.rs
- consensus/src/quorum_store/proof_manager.rs
- consensus/src/quorum_store/quorum_store_coordinator.rs
Sometimes in our load tests, some validators' proof queue size is increasing uncontrollably. These validators don't seem to be receiving commit notifications. Added some counters to check what messages quorum store is receiving.
> Add counters in quorum store to track received messages

- experimental/storage/layered-map/benches/maps.rs
- experimental/storage/layered-map/src/flatten_perfect_tree.rs
- experimental/storage/layered-map/src/iterator.rs
- experimental/storage/layered-map/src/layer.rs
- experimental/storage/layered-map/src/lib.rs
- experimental/storage/layered-map/src/map/mod.rs
- experimental/storage/layered-map/src/map/new_layer_impl.rs
- experimental/storage/layered-map/src/node.rs
- experimental/storage/layered-map/src/utils.rs
Compress the top of the critbit tree by using a newly introduced FlattenedPerfectTree, which omits the internal nodes.
<details>
<summary>
Due to the complexity of the code, update is slower.
</summary>
```
insert_in_batches/layered_map_1_batches_of_10k_updates
time:   [1.6578 ms 1.6878 ms 1.7120 ms]
thrpt:  [5.9814 Melem/s 6.0671 Melem/s 6.1768 Melem/s]
change:
time:   [+14.571% +18.106% +21.934%] (p = 0.00 < 0.05)
thrpt:  [-17.988% -15.331% -12.718%]
Performance has regressed.
insert_in_batches/layered_map_8_batches_of_10k_updates
time:   [21.700 ms 21.854 ms 22.016 ms]
thrpt:  [3.7210 Melem/s 3.7485 Melem/s 3.7752 Melem/s]
change:
time:   [-2.5688% -1.7149% -0.9398%] (p = 0.00 < 0.05)
thrpt:  [+0.9487% +1.7449% +2.6365%]
Change within noise threshold. …
```
> optimize LayeredMap::get()

- Cargo.lock
- aptos-move/aptos-release-builder/src/components/consensus_config.rs
- aptos-move/aptos-release-builder/src/components/execution_config.rs
- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/aptos-release-builder/src/components/framework.rs
- aptos-move/aptos-release-builder/src/components/gas.rs
- aptos-move/aptos-release-builder/src/components/jwk_consensus_config.rs
- aptos-move/aptos-release-builder/src/components/mod.rs
- aptos-move/aptos-release-builder/src/components/oidc_providers.rs
- aptos-move/aptos-release-builder/src/components/randomness_config.rs
- aptos-move/aptos-release-builder/src/components/transaction_fee.rs
- aptos-move/aptos-release-builder/src/components/version.rs
- aptos-move/aptos-release-builder/src/utils.rs
- aptos-move/framework/src/release_bundle.rs
- crates/aptos/src/governance/mod.rs
- testsuite/smoke-test/src/upgrade.rs
Currently, the release builder represents the next execution hash as a raw byte array. This byte array is essentially an untagged union with 3 types of values:
1. A hash value
2. The empty array, meaning that we are not in multi-step mode
3. Byte representation of the string `"vector::empty<u8>()"`, meaning that we are in multi-step mode, but does not have a next execution hash (last step of the proposal)
This representation is extremely confusing and error-prone, resulting in a bug in the custom governance script generator that causes (3) to be treated as a regular hash value and emitted to the script, leading to a few incidents we've seen in the past.
This gets the issue fixed by switching it to a strongly typed representation. 
Manually tested
> [release builder] fix handling of next execution hash

- aptos-move/aptos-vm-types/src/module_and_script_storage/module_storage.rs
- aptos-move/aptos-vm-types/src/module_and_script_storage/state_view_adapter.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/user.rs
- aptos-move/aptos-vm/src/move_vm_ext/vm.rs
- aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
Two changes:
1. Beautiful hack thanks to @zekun000 to support init module without index struct name cache flushing.
2. Added API for `AptosModuleStorage` to query state value metadata.
Note: tests 2will come when things are connected e2e. 
Kept them as a separate PR for simplicity. This way it is easier to address all `TODO(loader_v2)`s...
> [aptos-vm] init_module & state value metadata for V2 loader

- aptos-move/aptos-gas-meter/src/traits.rs
- aptos-move/aptos-gas-profiling/src/profiler.rs
- aptos-move/aptos-vm-types/src/change_set.rs
- aptos-move/aptos-vm-types/src/module_and_script_storage/module_storage.rs
- aptos-move/aptos-vm-types/src/module_and_script_storage/state_view_adapter.rs
- aptos-move/aptos-vm-types/src/module_write_set.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/session_change_sets.rs
This PR connects previous size calculation for write ops with new module storage interfaces. The fact that we need to pass `&impl AptosModuleStorage` even if there are no modules is ugly, but we can live with this for now :)
> [aptos-vm] Fixed previous size calculation for modules

- third_party/move/move-vm/runtime/Cargo.toml
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/storage/environment.rs
- third_party/move/move-vm/runtime/src/storage/struct_name_index_map.rs
- third_party/move/move-vm/types/src/loaded_data/runtime_access_specifier.rs
This PR addresses loader todo for struct name index map. Previously, it was buggy if used concurrently, and in one of the earlier PR I fixed by cloning out the struct name all the times.
Here, I added a few tests to check the map across multiple threads. In particular, we must enforce the invariant that if multiple threads try to cache a new name, only one succeeds and the index is unique!
To avoid bugs in the future, I changed the APIs and the internals (we store arced struct name) so that the lock is always released when any struct name index map function returns. Using a mapped guard is error prone, because it can cause a deadlock. In most of the cases, we need to clone the struct name anyway, and if we don't, using an arc is safer at not such a big overhead I think.
I tried multiple …
> [move] Improve & test struct index map

- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/modules_and_scripts.rs
- aptos-move/mvhashmap/Cargo.toml
- aptos-move/mvhashmap/src/lib.rs
- aptos-move/mvhashmap/src/scripts.rs
- aptos-move/mvhashmap/src/unsync_map.rs
- aptos-move/mvhashmap/src/versioned_code_storage.rs
- third_party/move/move-vm/runtime/src/data_cache.rs
- third_party/move/move-vm/runtime/src/lib.rs
- third_party/move/move-vm/runtime/src/storage/code_storage.rs
- third_party/move/move-vm/runtime/src/storage/environment.rs
- third_party/move/move-vm/runtime/src/storage/implementations/unsync_code_storage.rs
This completes Block-STM integration for the code cache by adding an implementation to deserialize/verify and cache scripts. Right now, we opt for a very basic policy of:
```
any module published ==> flush the script cache
```
We can revisit this in later PRs, but for now it suffices to get things running. Correctness is guaranteed because we publish at commit time, and so if there is a txn with a script that used older versions of code, it will be invalidated since there will be at least a single module dependency that gets loaded and is invalidated.
Other:
- This PR also fixed a bug in sponsored account creation introduced by one of the earlier PRs where `is_none()` got replaced by `is_some()`.
For tests, see the PR stacked on top.
> [block-stm] Integrate script caches

- third_party/move/move-compiler-v2/src/env_pipeline/model_ast_lints.rs
- third_party/move/move-compiler-v2/src/env_pipeline/model_ast_lints/needless_ref_in_field_access.rs
- third_party/move/move-compiler-v2/src/lint_common.rs
- third_party/move/move-compiler-v2/tests/lints/model_ast_lints/needless_ref_in_field_access_warn.exp
- third_party/move/move-compiler-v2/tests/lints/model_ast_lints/needless_ref_in_field_access_warn.move
Adds a new lint check to catch needless reference during field access, e.g.,
* `(&s).f` can be simplified to `s.f`.
* `(&mut s).f = 42;` can be simplified to `s.f = 42;`.
* Added tests to showcase the lint rule working
* Existing tests all pass as is
* Ran on the aptos-framework, but did not find any violations of this lint.
> [compiler-v2][lint] Needless reference in field access

- .github/workflows/lint-test.yaml
- third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
- third_party/move/move-prover/boogie-backend/src/spec_translator.rs
- third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs
- third_party/move/move-prover/tests/sources/functional/bv_aborts.exp
- third_party/move/move-prover/tests/sources/functional/bv_aborts.move
- third_party/move/move-prover/tests/sources/functional/bv_aborts.v2_exp
This PR closes #14459 by adding support of expression with bv operation in the abort_if condition.
Added a new test.
> [Prover] Bitwise operation in aborts_if condition

- storage/aptosdb/src/ledger_db/mod.rs
- storage/aptosdb/src/state_kv_db.rs
- storage/aptosdb/src/state_merkle_db.rs
- storage/schemadb/src/lib.rs
- storage/schemadb/tests/db.rs
DB::open_readonly used not to accept cfds, resulting in different options being used compared to a normal open. This is particularly an issue where the prefix_extractor being missed for the KV DBs.
unittests and local runs
> fix that DB::open_readonly not using the same cf options

- mempool/src/core_mempool/transaction_store.rs
- mempool/src/counters.rs
- mempool/src/shared_mempool/tasks.rs
- mempool/src/tests/common.rs
- mempool/src/tests/core_mempool_test.rs
- mempool/src/tests/integration_tests.rs
- mempool/src/tests/test_framework.rs
To better handle large transactions
> [mempool] improve parking lot eviction

- .github/runs-on.yml
Bump the runs-on AMI to the latest image. Our build deps were updated in #14487
> bump runs-on image to latest version

- aptos-move/e2e-move-tests/src/aggregator_v2.rs
- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-move-tests/src/tests/fungible_asset.rs
- aptos-move/e2e-tests/src/account.rs
- aptos-move/e2e-tests/src/account_universe.rs
- aptos-move/e2e-tests/src/account_universe/create_account.rs
- aptos-move/e2e-tests/src/executor.rs
- types/src/account_config/resources/fungible_asset_metadata.rs
- types/src/account_config/resources/fungible_store.rs
- types/src/account_config/resources/mod.rs
- types/src/account_config/resources/object.rs
Add an unit test that fails before the fix (#14512) of propagation of prologue speculation.
When speculatively executing transaction, calls to view (i.e. storage) can return speculative errors if BlockSTM is aware transaction will need to be re-executed. BlockSTM then sees these errors and marks for re-execution accordingly.
But, if that happens in prologue or epilogue, we were transforming these errors into UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION, and so BlockSTM didn't know it should re-execute them.
Prologue and epilogue are very limited, and only existing way to trigger it there is by having concurrent fungible balance created and used in the same block, but in a way that there are expensive transactions before both - so that rolling commit couldn't pass over the first one. That is …
> Add unit test for prologue speculation

- .github/actions/rust-unit-tests/action.yaml
- .github/workflows/lint-test.yaml
Ingest test metrics from nextest and upload to trunk.io (for main unittest runs)
Test Plan: running on PR, step should upload results and not fail the job either way
> [testing] Report unit test results to trunk.io

- third_party/move/move-compiler-v2/src/experiments.rs
- third_party/move/move-compiler-v2/tests/file-format-generator/borrow.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_13952_stack_balance.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_13952_stack_balance_regression.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/const.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/has_script.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/if_else.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/loop.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/operators.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/struct_variants.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/unpack_generic_struct.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/vector.exp
- third_party/move/move-compiler-v2/tests/testsuite.rs
- third_party/move/move-prover/tests/sources/functional/choice.v2_exp
- third_party/move/move-prover/tests/sources/functional/enum.v2_exp
- third_party/move/move-prover/tests/sources/functional/enum_abort.v2_exp
- third_party/move/move-prover/tests/sources/functional/enum_generic.v2_exp
- third_party/move/move-prover/tests/sources/functional/enum_positional.v2_exp
- third_party/move/move-prover/tests/sources/functional/enum_self.v2_exp
- third_party/move/move-prover/tests/sources/functional/fixed_point_arithm.v2_exp
- third_party/move/move-prover/tests/sources/functional/invariants.v2_exp
- third_party/move/move-prover/tests/sources/functional/is_txn_signer.v2_exp
- third_party/move/move-prover/tests/sources/functional/mut_ref.v2_exp
- third_party/move/move-prover/tests/sources/functional/references.v2_exp
- third_party/move/move-prover/tests/sources/functional/strong_edges.v2_exp
In this PR, we make "flush writes optimization" a default optimization (derives from the `OPTIMIZE` experiment), after having successfully run the compare testing with it being on.
In addition, I am turning off the experiment `OPTIMIZE_WAITING_FOR_COMPARE_TESTS` in all those test configs where `OPTIMIZE` was turned off, as the expectation in those test configs is that no optimizations are run.
Existing tests, with baseline updates that were reviewed and considered okay.
> [compiler-v2] Make flush writes optimization a default optimization

- consensus/src/liveness/proposal_generator.rs
- consensus/src/pipeline/buffer_manager.rs
- consensus/src/round_manager.rs
- types/src/transaction/use_case.rs
When we enabled info logs for a bit, "Receive commit vote" was most frequent, by an order of magnitude. Changing it to debug. 
changing useful log line from proposal_generator from info to warn, so it is logged. We need to decide if we want to cleanup info's, so we can keep them all, or if we need to upgrade to warn logs that are most useful...
> Remove most noisy info log

- consensus/src/round_manager.rs
- crates/reliable-broadcast/src/lib.rs
- network/framework/src/protocols/health_checker/mod.rs
Use {:#} from https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations, to keep all reasons, but no stack trace, as they are generally not useful here.
> [simple] remove backtrace from common warn logs

- config/src/config/consensus_observer_config.rs
- consensus/src/consensus_observer/common/error.rs
- consensus/src/consensus_observer/common/metrics.rs
- consensus/src/consensus_observer/network/observer_client.rs
- consensus/src/consensus_observer/network/observer_message.rs
- consensus/src/consensus_observer/observer/active_state.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
- consensus/src/consensus_observer/observer/ordered_blocks.rs
- consensus/src/consensus_observer/observer/payload_store.rs
- consensus/src/consensus_observer/observer/pending_blocks.rs
- consensus/src/consensus_observer/observer/subscription.rs
- consensus/src/consensus_observer/observer/subscription_manager.rs
- consensus/src/consensus_observer/publisher/consensus_publisher.rs
- consensus/src/payload_manager.rs
Note: most of this PR is adding/updating unit tests.
This PR adds support to consensus observer (CO) for subscribing to multiple subscription streams (instead of just a single stream). To achieve this, the PR offers the following commits:
1. Wrap the block and payload stores in locks (e.g., Mutex's), so they can be thread safe.
1. Update CO to handle duplicate commit messages.
1. Update CO to handle duplicate block payload messages.
1. Update CO to handle duplicate ordered block messages.
1. Small renames and refactors.
1. Update CO to create and maintain multiple subscription streams.
- Note: most of the code is in this commit, and a majority of the changes are simply adding/updating unit tests.
The next step is to parallelize subscription creation (so that it doesn't block the CO …
> [Consensus Observer] Support multiple observer subscriptions.

- consensus/src/consensus_observer/observer/mod.rs
- consensus/src/consensus_observer/observer/subscription.rs
- consensus/src/consensus_observer/observer/subscription_manager.rs
- consensus/src/consensus_observer/observer/subscription_utils.rs
- consensus/src/consensus_observer/publisher/consensus_publisher.rs
Note:
- Most of this PR is unit tests.
- This PR is based on https://github.com/aptos-labs/aptos-core/pull/14566
This PR makes subscription creation asynchronous, instead of blocking the consensus observer thread. The PR offers the following commits:
1. Make subscription creation asynchronous by spawning a dedicated thread. Most of this commit is just moving subscription logic into a new file so that the tasks can be spawned asynchronously.
1. Move the subscription health check to `subscription.rs` and update the tests.
1. Update the tests for the subscription manager.
1. Update the tests for the subscription utilities file.
> [Consensus Observer] Make subscription creation asynchronous.

- aptos-move/framework/src/module_metadata.rs
- third_party/move/move-binary-format/src/check_bounds.rs
- third_party/move/move-binary-format/src/check_complexity.rs
- third_party/move/move-binary-format/src/proptest_types/types.rs
- third_party/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/mod.rs
- third_party/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/variant_name_test.rs
- third_party/move/move-bytecode-verifier/src/check_duplication.rs
- third_party/move/move-bytecode-verifier/src/limits.rs
- third_party/move/move-bytecode-verifier/src/signature_v2.rs
- third_party/move/move-bytecode-verifier/src/verifier.rs
Contains a number of fixes to the implementation of enum types in the VM
New test added, existing test caught new checks and need to be adapted
> [move-vm] Fixes to enum type implementation

- consensus/src/consensus_observer/observer/active_state.rs
- consensus/src/network.rs
This PR downgrades several consensus observer (CO) error logs to warnings:
1. `Failed to read on-chain randomness config seq num!`: Looks like this is expected (e.g., [consensus will just use the default](https://github.com/aptos-labs/aptos-core/blob/793eeb7273c25543a15ebd94de4db37335f0d8b2/consensus/src/epoch_manager.rs#L1100) and not log anything if it can't read it) so we can do the same.
2. `Error delivering a self msg`: CO doesn't [register to receive self-sent messages](https://github.com/aptos-labs/aptos-core/blob/4fbb77ebb9ebd2025893c8a158cb0cd5699464c4/consensus/src/consensus_provider.rs#L143), so we should downgrade the failed send.
- I'm not sure we want to alert on failed self sends anyway. Consensus should already be resilient to that (@zekun000 to confirm? 😄). If not, we'll …
> [Consensus Observer] Downgrade unnecessary error logs.

- aptos-move/aptos-release-builder/data/federated_keyless.yaml
Adds the governance proposal to enable federated keyless accounts.
It has not.
That the YAML is correct & the feature flag name is good.
> add governance proposal to enable federated keyless accounts

- api/src/context.rs
- config/src/config/gas_estimation_config.rs
- types/src/on_chain_config/execution_config.rs
AIP-68 implements spreading out of potentially conflicting transactions within a block. Consequence is that workload from single module doesn't increase gas prices for unrelated modules. 
Updating gas estimation logic to not treat block as full if majority of block is from a single contract.
will run workload sweep forge test and check gas estimation.
change to block_min_inclusion_price
> Update gas estimation changes for UseCaseAware block reordering (AIP-68)

- aptos-move/framework/aptos-framework/doc/account.md
- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/doc/jwks.md
- aptos-move/framework/aptos-framework/doc/multisig_account.md
- aptos-move/framework/aptos-framework/doc/stake.md
- aptos-move/framework/aptos-framework/doc/staking_contract.md
- aptos-move/framework/aptos-framework/doc/vesting.md
- aptos-move/framework/aptos-framework/doc/voting.md
- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/aptos-framework/sources/coin.move
- aptos-move/framework/aptos-framework/sources/jwks.move
- aptos-move/framework/aptos-framework/sources/multisig_account.move
- aptos-move/framework/aptos-framework/sources/stake.move
- aptos-move/framework/aptos-framework/sources/staking_contract.move
- aptos-move/framework/aptos-framework/sources/vesting.move
- aptos-move/framework/aptos-framework/sources/voting.move
In this PR, we fix `move lint` violations in the aptos framework for the lint rule introduced here: https://github.com/aptos-labs/aptos-core/pull/14651
In essence, any `&mut` and `borrow_global_mut` that do not need to be mutable, and can be replaced by `&` and `borrow_global` respectively, are found and suggested by the new lint checker. This PR is a result of applying those suggestions.
Existing aptos framework tests were run using both compiler v1 and v2.
Any change that does not preserve the intended semantics of the original code.
> [aptos-framework] Fix needless mutable references and borrows

- .github/actions/move-prover-setup/action.yaml
- .github/actions/rust-setup/action.yaml
- .github/workflows/windows-build.yaml
The old version relies on a deprecated version of Node.js
> Update pin on the Swatinem/rust-cache GH action

- types/src/state_store/state_key/registry.rs
If before Entry::drop() calls Registry::maybe_remove, the weak ref under the same key1 and key2 is replaced, Entry::drop can be called recursively resulting in a deadlock. The crux is we try to see if the entry has been replaced by trying to upgrading it to a strong ref, and it possible that the upgrade is successful and the result becomes a only ref to the new entry.
This tries to fix it by determining the same thing by seeing if Weak::strong_count() is 0 instead of upgrading the weak ref.
eyes of hackers
> Fix potential deadlock in state_key::Entry::drop

- api/types/src/convert.rs
- testsuite/smoke-test/src/indexer.rs
We don't have table info on non-indexer FN. When implementing the internal indexer for storage sharding, we accidentally change the logic to return an Error rather than Ok(None) when internal indexer is enabled but the table info indexer is not enabled. The PR fix the behavior to return Ok(None).
> [Fix] Return None instead of error if table info is not available on the node.

- .github/actions/rust-setup/action.yaml
I put in the if- condition to speed up iteration on PRs, and it looks like when the condition is not hit, rust-cache is not happy with it. Removing to unbreak main.
```
Error:
aptos-labs/aptos-core/main/.github/actions/rust-setup/action.yaml: The
scalar style 'SingleQuoted' on line 23 and column 11 is not valid with
the tag '!startsWith(github.ref,'
Error: System.ArgumentException: Unexpected type '' encountered while
reading 'action manifest root'. The type 'MappingToken' was expected.
at
GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken
value, String objectDescription)
at
GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext
executionContext, String manifestFile)
Error: Failed to load …
```
> resolve rust-setup error

- third_party/move/move-model/bytecode/Cargo.toml
- third_party/move/move-model/bytecode/src/fat_loop.rs
- third_party/move/move-model/bytecode/src/lib.rs
- third_party/move/move-prover/bytecode-pipeline/src/loop_analysis.rs
The prover actually has a full-fledged loop analysis for stackless bytecode for loop invariant instrumentation and unrolling. This loop analysis is a major part of the logic for decompilation. This PR pulls out this functionality in a new general purpose module, `fat_loop`. Its mostly a refactoring of existing code.
Existing prover tests
> [compiler-v2][decompiler] Pulling fat-loop algorithm out of the prover

- api/src/context.rs
- crates/aptos/src/node/local_testnet/node.rs
- storage/indexer/src/indexer_reader.rs
- types/src/indexer/indexer_db_reader.rs
This is to fix the issue from the config combination of (sharding, internal index, table info). 
Tested major 3 path and looks good. 
tested locally and it looks good.
3 cases:
* no table info or sharding
```
api:
enabled: true
address: 127.0.0.1:8084
```
* table info without sharding
```
indexer_table_info:
parser_task_count: 10
parser_batch_size: 100
table_info_service_mode: IndexingOnly
indexer_grpc:
enabled: true
address: 0.0.0.0:50051
processor_task_count: 10
processor_batch_size: 100
output_batch_size: 100
```
* table info with sharding
```
indexer_db_config:
enable_event: true
enable_statekeys: true
enable_transaction: true
storage:
rocksdb_configs:
enable_storage_sharding: true
indexer_table_info:
parser_task_count: 10
parser_batch_size: 100
table_info_service_mode: IndexingOnly …
```
> [Fix] Fix indexer FN and localnet.

- Cargo.lock
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
^ 
This is to fix the broken indexer at localnet.  
This was tested in change: https://github.com/aptos-labs/aptos-core/pull/14727
> Release CLI 4.2.3.

- crates/aptos/src/move_tool/mod.rs
Ensure that the following functions are publicly visible so they can be used from the [`move-mutation-test`](https://github.com/eigerco/move-spec-testing) tool.
- `aptos::move_tool::aptos_debug_natives::aptos_debug_natives()`
- `aptos::move_tool::experiments_from_opt_level()`
> [aptos-cli]: update move-tool visibility

- types/src/keyless/mod.rs
- types/src/keyless/openid_sig.rs
> timeless hotfix (#275)

- consensus/src/state_computer.rs
this commit guarantees the garbage collection order of mempool -> quorum store -> block store.
> [mempool] move the qs callback to be after mempool

- third_party/move/move-compiler-v2/tests/checking-lang-v1/v1-typing/refer_other_constants.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v1/v1-typing/refer_other_constants.move
- third_party/move/move-compiler-v2/tests/checking/typing/constant_all_valid_types.exp
- third_party/move/move-compiler-v2/tests/checking/typing/constant_all_valid_types.move
- third_party/move/move-compiler-v2/tests/checking/typing/constant_duplicate.exp
- third_party/move/move-compiler-v2/tests/checking/typing/constant_duplicate.move
- third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp
- third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.move
- third_party/move/move-compiler/src/expansion/ast.rs
- third_party/move/move-compiler/tests/move_check/typing/constant_duplicate.exp
- third_party/move/move-compiler/tests/move_check/typing/constant_duplicate.move
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/builder/module_builder.rs
- third_party/move/move-model/src/constant_folder.rs
This PR
1) adds checks to only allow referring other constants in constant definition when the language version is at least 2.0.
2) rejects recursive definition of constants.
close #14648
1) Update existing test cases;
2) Add a new test to `checking-lang-v1`
> [Compiler-v2] Check recursive definition for constants

- config/src/config/consensus_observer_config.rs
This PR disables consensus observer (CO) for VFNs (by default).
> [Consensus Observer] Disable CO for VFNs.

- Cargo.lock
- api/src/context.rs
- api/test-context/src/test_context.rs
- aptos-node/src/lib.rs
- aptos-node/src/services.rs
- aptos-node/src/storage.rs
- crates/aptos-faucet/core/Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-table-info/src/internal_indexer_db_service.rs
- ecosystem/indexer-grpc/indexer-grpc-table-info/src/runtime.rs
- storage/aptosdb/Cargo.toml
- storage/aptosdb/src/db/include/aptosdb_internal.rs
- storage/aptosdb/src/db/include/aptosdb_writer.rs
- storage/aptosdb/src/db/mod.rs
- storage/aptosdb/src/fast_sync_storage_wrapper.rs
- storage/indexer/src/db_indexer.rs
- testsuite/smoke-test/Cargo.toml
- third_party/move/move-vm/runtime/Cargo.toml
1. replace with sleep with waiting for update message
2. only return block boundary versions at min(storage_version, internal indexer version)
local test with devnet fullNode
updated existing unit tests
> replace sleep with notification from aptosdb

- crates/aptos/CHANGELOG.md
- crates/aptos/src/move_tool/fmt.rs
This PR includes move files inside `tests` and `examples` as the format target when executing `aptos move fmt`.
Close #14776
Manual test
> [movefmt][trivial] format move files in the `tests` and `examples` folder

- aptos-move/aptos-release-builder/src/components/framework.rs
This fixes a bug in the release builder that results in the framework upgrade scripts being generated in reverse order.
> [release builder] fix framework upgrade ordering (1.20)

- aptos-move/aptos-release-builder/src/components/framework.rs
This fixes a bug in the release builder that results in the framework upgrade scripts being generated in reverse order.
> [release builder] fix framework upgrade ordering (main)

- .github/workflows/adhoc-forge.yaml
workflow_call expects a bool, but passing around workflow_dispatch inputs implicitly converts it to a string. Convert it back to a bool with `== 'true'`
Otherwise, it gets this error
trigger on PR
Also run adhoc forge on this branch: https://github.com/aptos-labs/aptos-core/actions/runs/11130143854
> [gha] fix FORGE_ENABLE_INDEXER and other adhoc bools

- third_party/move/move-binary-format/src/check_bounds.rs
- third_party/move/move-bytecode-verifier/src/check_duplication.rs
Fixed ordering of bounds checking, remove obsolete debug print.
> [move-vm] Fix a bug in order of bounds checking

- api/src/tests/multisig_transactions_test.rs
- api/test-context/src/test_context.rs
- aptos-move/framework/README.md
- aptos-move/framework/aptos-framework/doc/multisig_account.md
- aptos-move/framework/aptos-framework/sources/multisig_account.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- sdk/src/transaction_builder.rs
Introduce private entry functions for creating multisig account. This eliminates the need for generating the complex proof the existing `create_with_existing_account` functions require.
This proposal mirrors changes implemented in commits https://github.com/aptos-labs/aptos-core/commit/fdc041f37e4cb17d2c7f4bb2e0ad784a3f007614 https://github.com/aptos-labs/aptos-core/commit/d771cec3c4638a9a5d50120765f921e47feea83f, where a private entry function was introduced for account key rotation with a similar purpose.
AIP proposal: https://github.com/aptos-foundation/AIPs/pull/496
Added unit tests
The implementation itself is straightforward, please see the AIP for the rationale of this change.
> [framework] introduce private entry function for creating multisig account

- third_party/move/move-binary-format/src/check_bounds.rs
Add a check to bounds_checker for empty variant field handle lists
> [move-vm] Check for empty field variant list

- state-sync/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-driver/src/utils.rs
This PR removes unnecessary `clone()` calls for the storage synchronizer.
> [State Sync] Remove clone() calls for storage synchronizer.

- config/src/config/consensus_observer_config.rs
- config/src/config/state_sync_config.rs
- testsuite/testcases/src/fullnode_reboot_stress_test.rs
This PR offers several small improvements (each in their own commit):
1. Improve the `FullNodeRebootStressTest` by preventing node reboots from happening too close to the end of the test.
1. Disable consensus observer on VFNs (by default). VFNs are still opt-in, and will be turned on once a few improvements are made.
1. Bump the max message size for state sync (from 8MB to 10MB). This should help favour output syncing a little more.
> [Misc] Small improvements to forge, consensus observer and state sync.

- consensus/consensus-types/src/sync_info.rs
- consensus/consensus-types/src/wrapped_ledger_info.rs
> [consensus] cleanup verbose logs

- consensus/src/counters.rs
- consensus/src/payload_manager.rs
Counters to track the local availability of batches when a proposal is received.
> [consensus] batch availability counters for InlineHybrid payload

- consensus/src/payload_manager.rs
Calculates missing batches properly.
> [consensus] fix batch availability counters

- ecosystem/indexer-grpc/indexer-test-transactions/build.rs
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/scripted_transactions/simple_user_script1.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/scripted_transactions/simple_user_script2.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/scripted_transactions/simple_user_script3.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/scripted_transactions/simple_user_script4.json
- ecosystem/indexer-grpc/indexer-test-transactions/src/lib.rs
- ecosystem/indexer-grpc/indexer-transaction-generator/example.yaml
This is to update folder name to be consistent with processor repo
- [X ] Other (indexer-test-transactions)
- [ X] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I identified and added all stakeholders and component owners affected by this change as reviewers
> update the folder name to be consistent

- Cargo.lock
- Cargo.toml
- api/src/runtime.rs
- api/test-context/src/test_context.rs
- aptos-move/aptos-workspace-server/Cargo.toml
- aptos-move/aptos-workspace-server/src/main.rs
- aptos-node/src/lib.rs
- aptos-node/src/services.rs
- crates/aptos-faucet/core/src/server/run.rs
- crates/aptos/src/node/local_testnet/mod.rs
- ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs
This is the initial implementation of Aptos Workspace Server, a new binary that is capable of spawning a fully self-contained local network, powering [Aptos Workspace, our new integration testing framework](https://github.com/aptos-labs/workspace/).
As a side effect, this introduces alternative entrypoints to both the node and the faucet to allow them to report the ports used via oneshot channels. This makes it possible to bind the services to random ports, allowing multiple instances of the workspace server to be spawned simultaneously, which is a necessity for integration tests.
> [aptos-workspace] initial workspace server implementation

- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/k8s_deployer/deployer.rs
Change the retry logic for waiting on the deployer jobs to finish to fail fast if the job fails. Use `again::RetryPolicy` rather than `aptos_retrier` to be more flexible on which errors are retryable and which are fatal. We will still wait for upwards of 10min. 
We saw in some runs that even after the job fails, forge still waits for the full time: https://github.com/aptos-labs/aptos-core/actions/runs/11151237022/job/30995462775
CI
The retry logic and assumptions
> [forge] fail fast deployer if job failed

- consensus/src/quorum_store/batch_generator.rs
- consensus/src/quorum_store/batch_store.rs
In previous commit https://github.com/aptos-labs/aptos-core/pull/14757, we move timestamp update to async callback to ensure the consistency between mempool, qs and consensus. However it introduces the race of timestamp can be updated by sync_to first then async callback and violates the assertion.
> [qs] tolerate block timestamp being updated asynchronously

- api/doc/spec.json
- api/doc/spec.yaml
- api/types/src/convert.rs
- api/types/src/transaction.rs
- types/src/block_metadata_ext.rs
- types/src/transaction/mod.rs
(Validator txn had the same problem, fixed in #13718 .)
Txn API currently doesn't return anything to help distinguish between the following BlockMetadata txn variants (depending on the status of randomness feature and randomness seed availability).
- (A) `BlockMetadataExt::V1 { seed: Some(...) }`, used when the feature is enabled and the seed is available.
- (B) `BlockMetadataExt::V1 { seed: None }`, used when the feature is enabled but the seed is unavailable.
- (C) `BlockMetadataExt::V0`, never used.
- (D) `BlockMetadata`, used when the randomness feature is disabled.
This change adds distinguishing fields to the txn API return values. Hopefully this doesn't break anyone since we are only adding fields.
NOTE: no change to indexer, **assuming the variant info should still be ignored**. …
> block metadata txn api update

- Cargo.lock
- aptos-move/aptos-vm-types/src/resource_group_adapter.rs
- aptos-move/aptos-vm/src/block_executor/mod.rs
- aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
- aptos-move/block-executor/src/captured_reads.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/executor_utilities.rs
- aptos-move/block-executor/src/proptest_types/baseline.rs
- aptos-move/block-executor/src/proptest_types/types.rs
- aptos-move/block-executor/src/task.rs
- aptos-move/block-executor/src/txn_last_input_output.rs
- aptos-move/block-executor/src/unit_tests/mod.rs
- aptos-move/block-executor/src/view.rs
- aptos-move/mvhashmap/Cargo.toml
- aptos-move/mvhashmap/src/lib.rs
- aptos-move/mvhashmap/src/types.rs
- aptos-move/mvhashmap/src/unit_tests/mod.rs
- aptos-move/mvhashmap/src/unit_tests/proptest_types.rs
- aptos-move/mvhashmap/src/unsync_map.rs
- aptos-move/mvhashmap/src/versioned_data.rs
- aptos-move/mvhashmap/src/versioned_delayed_fields.rs
- aptos-move/mvhashmap/src/versioned_group_data.rs
- aptos-move/mvhashmap/src/versioned_modules.rs
(1) Make resource group size reads faster, and validations (faster but also) less prone to speculative failure by recording the group size from outputs instead of collecting the sizes of latest versions of all tags in the group. Simplify the logic for reading size from estimate by associating to the whole group as opposed to individual entries. Add runtime checks and tests that compare the actual serialized size to the record at the end.
Most likely, collect was implemented when migrating resource groups to block executor before group size would become a part of the output. But with size in output, there is no need to collect.
Tests are stronger because they re-do the logic for computing final group size based on the changes, and test it in the end vs ground truth (actual serialized …
> Resource Groups: don't recompute size, test serialized size, parallel finalization

- consensus/src/epoch_manager.rs
> log level downgrade

- aptos-move/framework/src/built_package.rs
This fixes a mishandling of scripts in dependency packages, which caused metadata extraction to panic.
> [built-package] fix panic caused by script in dependency

- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/prometheus_metrics.rs
- testsuite/forge/src/interface/swarm.rs
- testsuite/forge/src/success_criteria.rs
- testsuite/testcases/src/lib.rs
- testsuite/testcases/src/load_vs_perf_benchmark.rs
Adds some latency-based success criteria to Forge runs with the indexer.
Also start to add a new class of `indexer_*` test suites
CI. Also run it ad-hoc many times. Use this to calibrate some of the latency criteria: https://github.com/aptos-labs/aptos-core/actions/runs/11185219106 (see the run history on GHA)
1. [run1](https://grafana.aptoslabs.com/d/fdr6l9zgfzncwf/indexer-testing-overview-ephemeral-forge?from=1728067246000&to=1728068660000&var-Datasource=fHo-R604z&var-BigQuery=axNEitxVz&var-metrics_source=All&var-chain_name=forge-0&var-cluster=All&var-namespace=forge-runner-1728067241&var-kubernetes_pod_name=All&orgId=1)
2. [run2](https://grafana.aptoslabs.com/d/fdr6l9zgfzncwf/indexer-testing-overview-ephemeral-forge?from=1728070813000&to=1728071720000&var-Datasource=fHo-R604z&var-BigQue …
> [forge] indexer SuccessCriteria and new test

- Cargo.lock
- storage/aptosdb/src/db/test_helper.rs
- storage/aptosdb/src/pruner/state_merkle_pruner/test.rs
- storage/aptosdb/src/state_merkle_db.rs
- storage/aptosdb/src/state_store/state_store_test.rs
When restoring sharded db is in progress, we may haven't write the root node of the sharded JMT when being interrupted.
we still want to get the rightmost child in this case to continue restoring.
> Get right most child

- aptos-move/aptos-workspace-server/src/main.rs
This fixes a config issue preventing the node's indexer grpc service from starting. 
We had the same issue with the CLI's Localnet implementation and it was fixed by https://github.com/aptos-labs/aptos-core/pull/14727.
A subsequent PR will add proper tests to ensure the binary always succeed to start.
> [simple][aptos-workspace-server] fix config issue preventing indexer grpc from starting

- .github/workflows/execution-performance.yaml
- .github/workflows/workflow-run-execution-performance.yaml
- testsuite/forge_test.py
- testsuite/single_node_performance.py
Recalibrate for RG change
Update limits to be based on min_ratio / max_ratio of many runs update module working set to 100
> [single node perf] Recalibrate and improve regression perf test

- consensus/src/counters.rs
- consensus/src/execution_pipeline.rs
- consensus/src/state_computer.rs
- consensus/src/state_computer_tests.rs
- execution/executor-types/src/lib.rs
separate state sync notifications to pre-commit and commit, so that state sync always receives notification even if consensus switches with pre-committed-but-not-committed blocks.
> separate state sync notifications to pre-commit and commit

- ecosystem/indexer-grpc/indexer-grpc-table-info/src/backup_restore/fs_ops.rs
- ecosystem/indexer-grpc/indexer-grpc-table-info/src/backup_restore/gcs.rs
- ecosystem/indexer-grpc/indexer-grpc-table-info/src/table_info_service.rs
* Adds more logging for debuggability
* Fix the tar file  creation issue:
* Before: compression streams into tmp tar file under the same folder
* After: compression is done in memory and file creation in one shot.
* This fixed the problem that if tar tmp file exists, it'll create a circle: it tries to compress the tar file itself...
deployed and looks good
> Add more logging and fix the table info tar file creation.

- .github/workflows/forge-unstable.yaml
Some small fixes to forge unstable
* trigger condition
* use double brackets in inline bash
workflow dispatch. also the cron schedule once it's landed
> [forge] fixs incl unstable trigger conditions

- Cargo.lock
- execution/executor-types/Cargo.toml
- execution/executor-types/src/lib.rs
- execution/executor/src/block_executor.rs
- execution/executor/src/chunk_executor.rs
- execution/executor/src/components/apply_chunk_output.rs
- execution/executor/src/components/block_tree/block_output.rs
- execution/executor/src/components/block_tree/mod.rs
- execution/executor/src/components/block_tree/test.rs
- execution/executor/src/components/chunk_commit_queue.rs
- execution/executor/src/components/chunk_output.rs
- execution/executor/src/components/executed_chunk.rs
- execution/executor/src/components/mod.rs
- execution/executor/src/db_bootstrapper.rs
- execution/executor/src/tests/mod.rs
- storage/backup/backup-cli/src/backup_types/transaction/restore.rs
The concept of ExecutionOutput is in fact internal to the BlockTree.
The ExecutedChunk is a (unnecessary) helper structure that's local to the executor algorithms.
> trivial: move a few data structures off executor-types

- third_party/move/move-prover/boogie-backend/src/spec_translator.rs
- third_party/move/move-prover/tests/sources/functional/verify_vector.move
This PR allows use of `vector[...]` in specifications by:
1) converting `vector[]` into `$EmptyVec` when the vector is empty;
2) converting `vector[]` into `MakeVec1`, `MakeVec2`, `MakeVec3` and `MakeVec4`  when the vector has 1, 2, 3 and 4 elements;
3) converting `vector[x1, x2...]` into `ConcatVec(MakeVec1(x1), ConcatVec(...))` when the vector has more than 4 elements.
close #14790
New test cases with `vector[...]` used in the spec.
> [Prover][trivial] Add support of operation `vector[]` to spec

- Cargo.lock
- crates/aptos-api-tester/src/tests/coin_transfer.rs
- crates/aptos-api-tester/src/utils.rs
- crates/aptos-faucet/core/src/funder/transfer.rs
- crates/aptos-faucet/core/src/server/run.rs
- crates/aptos-rest-client/src/lib.rs
- crates/aptos/src/common/types.rs
- crates/transaction-emitter-lib/src/cluster.rs
- crates/transaction-emitter-lib/src/emitter/account_minter.rs
- crates/transaction-emitter-lib/src/emitter/local_account_generator.rs
- crates/transaction-emitter-lib/src/emitter/mod.rs
- crates/transaction-emitter-lib/src/emitter/submission_worker.rs
- crates/transaction-emitter-lib/src/emitter/transaction_executor.rs
- sdk/src/coin_client.rs
- testsuite/forge-cli/src/main.rs
- testsuite/smoke-test/src/aptos/mint_transfer.rs
- testsuite/smoke-test/src/fullnode.rs
- testsuite/smoke-test/src/rosetta.rs
- testsuite/smoke-test/src/utils.rs
> [txn-emitter][simple] Reduce flakiness in txn emitter

- keyless/pepper/service/src/lib.rs
- keyless/pepper/service/src/tests.rs
- types/src/keyless/circuit_testcases.rs
- types/src/keyless/mod.rs
- types/src/keyless/test_utils.rs
Too large iat is not handled properly in pepper service.
UT.
n/a
> handle max_exp_data_secs overflow in pepper

- .github/workflows/copy-images-to-dockerhub.yaml
Use runs-on for release images workflow
Added a dry_run input for the workflow then ran the workflow for testing https://github.com/aptos-labs/aptos-core/actions/runs/11260314466
> use runs-on runner for release images workflow

- third_party/move/move-compiler-v2/src/bytecode_generator.rs
- third_party/move/move-compiler-v2/tests/bytecode-generator/loop_labels.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/loop_labels.move
- third_party/move/move-compiler-v2/tests/checking-lang-v1/loop_labels.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v1/loop_labels.move
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_check_err.exp
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_check_err.move
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_check_ok.exp
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_check_ok.move
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_parse_err1.exp
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_parse_err1.move
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_parse_err2.exp
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_parse_err2.move
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_parse_err3.exp
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_parse_err3.move
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_parse_err4.exp
- third_party/move/move-compiler-v2/tests/checking/control_flow/loop_labels_parse_err4.move
- third_party/move/move-compiler-v2/tests/testsuite.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/loop_labels.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/loop_labels.move
- third_party/move/move-compiler/src/expansion/ast.rs
- third_party/move/move-compiler/src/expansion/dependency_ordering.rs
- third_party/move/move-compiler/src/expansion/translate.rs
- third_party/move/move-compiler/src/naming/translate.rs
- third_party/move/move-compiler/src/parser/ast.rs
- third_party/move/move-compiler/src/parser/lexer.rs
- third_party/move/move-compiler/src/parser/syntax.rs
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/lib.rs
Besides the user being able to describe complex algorithms more efficiently, loop labels are required to express aribtrary reducible control flow graphs in the AST language, and create parity of the AST with the bytecode level for this kind of code (which is also what can be generated from Move).
New baseline tests in checking, v1-checking, bytecode generation, and a transactional test.
> [compiler-v2] Add loop labels to the language

- RUST_SECURE_CODING.md
Updated the incorrect domain reference from create.io to crates.io in the “Rustup” section. This ensures the correct Rust package management site is referenced for security considerations.
> Fix Incorrect Domain Reference in RUST_SECURE_CODING.md

- testsuite/fuzzer/fuzz.sh
Our long-lasting issue with OSS-Fuzz builds could be at an end without too many sacrifices. The idea is to build fuzzers one at a time instead of lowering Rust job cores. This trick will use all the cores to build dependencies, but during the linking phase, we have only one fuzzer (this is where we had issues with OOM). The next fuzzer to be built will benefit from already built dependencies of the previous one.
We can re-evaluate decommissioned fuzzer for improvements and re-enable them if everything works smoothly.
N/A
N/A
> Slightly change build process to prevent OOM

- consensus/src/state_computer.rs
- consensus/src/state_computer_tests.rs
- state-sync/inter-component/consensus-notifications/src/lib.rs
- state-sync/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-driver/src/driver.rs
- state-sync/state-sync-driver/src/driver_factory.rs
- state-sync/state-sync-driver/src/metrics.rs
- state-sync/state-sync-driver/src/notification_handlers.rs
- state-sync/state-sync-driver/src/tests/continuous_syncer.rs
This PR adds basic `sync_for_duration()` support to state sync, allowing callers to block while state sync synchronizes the node for the specified duration. This will be required by consensus observer (CO), to implement a smarter fallback mechanism on failures to stay up-to-date. Integration with CO will happen in the next PR.
1. Add a `sync_for_duration()` function to the consensus notifier.
1. Update state sync to handle the `sync_for_duration()` request.
2. Make `sync_for_duration()` return the latest synced ledger info on handover.
New and existing test infrastructure. More will be added upon integration with CO.
> [State Sync] Add sync_for_duration() mode.

- third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs
- third_party/move/move-compiler-v2/tests/checking/specs/move_function_in_spec_ok.exp
- third_party/move/move-prover/boogie-backend/src/lib.rs
- third_party/move/move-prover/boogie-backend/src/prelude/prelude.bpl
- third_party/move/move-prover/boogie-backend/src/spec_translator.rs
- third_party/move/move-prover/tests/sources/functional/abort_in_fun.move
- third_party/move/move-prover/tests/sources/functional/loops_with_memory_ops.exp
- third_party/move/move-prover/tests/sources/functional/loops_with_memory_ops.v2_exp
- third_party/move/move-prover/tests/sources/functional/spec_fun_imperative_expression_err.exp
- third_party/move/move-prover/tests/sources/functional/spec_fun_imperative_expression_err.move
- third_party/move/move-prover/tests/sources/functional/spec_fun_imperative_expression_err.v2_exp
Currently, when rewriting a Move expression into a spec expression, abort will be rewritten into empty `()` expression. Later when generating boogie, the error `Tuple not yet supported` will be raised. This PR introduces uninterpreted functions to the Boogie native for each type generated in the program and `abort` operation is translated into calling the corresponding function based on its type. 
close #14793
2) Add a new test case to the prover test.
> [Prover] add support of abort in spec function

- Cargo.lock
- config/src/config/consensus_config.rs
- consensus/Cargo.toml
- consensus/src/counters.rs
- consensus/src/round_manager.rs
- consensus/src/round_manager_test.rs
- Enables the RoundTimeoutMsg on main. The last release should have all the handling logic, so it can be turned on for next release cut.
- Adds counters to track the round timeout reason and if timeout due to OptQS (still disabled) missing payload, then track the missing authors.
> [consensus] enable round timeout message

- config/src/config/consensus_observer_config.rs
- consensus/src/block_storage/sync_manager.rs
- consensus/src/consensus_observer/common/error.rs
- consensus/src/consensus_observer/common/metrics.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
- consensus/src/consensus_observer/observer/fallback_manager.rs
- consensus/src/consensus_observer/observer/mod.rs
- consensus/src/consensus_observer/observer/ordered_blocks.rs
- consensus/src/consensus_observer/observer/payload_store.rs
- consensus/src/consensus_observer/observer/state_sync_manager.rs
- consensus/src/consensus_observer/observer/subscription.rs
- consensus/src/consensus_observer/observer/subscription_manager.rs
- consensus/src/consensus_provider.rs
- consensus/src/dag/dag_state_sync.rs
- consensus/src/epoch_manager.rs
- consensus/src/pipeline/execution_client.rs
- consensus/src/state_computer.rs
- consensus/src/state_computer_tests.rs
- consensus/src/state_replication.rs
- consensus/src/test_utils/mock_execution_client.rs
- consensus/src/test_utils/mock_state_computer.rs
- state-sync/inter-component/event-notifications/src/lib.rs
- state-sync/state-sync-driver/src/driver.rs
This PR adds a "state sync fallback" mode to consensus observer (CO). If CO does not make progress for some time (e.g., no increase in synced version for 30 seconds), it will fallback to state sync for a while (e.g., 10 minutes). After which, CO will regain control and attempt to make progress.
1. Rename `sync_to()` to `sync_to_target()`
1. Add the state sync fallback mode to CO. For this, we introduce two new components to help manage state sync interaction: (i) the state sync manager; and (ii) the observer fallback manager.
1. Enable CO for all validators and VFNs (by default).
New and existing test infrastructure, including manual verification, e.g., see https://github.com/aptos-labs/aptos-core/pull/14960.
> [Consensus Observer] Add state sync fallback mode.

- docker/compose/aptos-node/fullnode.yaml
- docker/compose/aptos-node/validator.yaml
> Update yaml to enable new storage format by default.

- crates/aptos-rosetta/src/main.rs
Removes poorly formatted currencies, with a warning on startup of Rosetta.
> [rosetta] Remove supported currencies with an empty symbol

- .github/workflows/copy-images-to-dockerhub.yaml
- docker/release-images.mjs
Don't set `dry_run` in the environment variables. This was getting set to the string `'false'` which is a truthy value and results in dry run mode being enabled
Ran the workflow manually:
https://github.com/aptos-labs/aptos-core/actions/runs/11378206947
> remove dry_run env flag

- testsuite/fuzzer/fuzz/Cargo.toml
Workaround since `cargo fuzz list` return all the bins in the cargo toml.
N/A
N/A
> Comment out disabled fuzzers to prevent them from appearing in the list

- third_party/move/move-compiler-v2/tests/checking/receiver/bad_receiver.exp
- third_party/move/move-compiler-v2/tests/checking/receiver/bad_receiver.move
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/builder/model_builder.rs
- third_party/move/move-model/src/ty.rs
When displaying a "receiver function" type in the presence of errors,
a type variable may be shown by showing the receiver function type,
which includes the type variable itself.  We break the recursion by
introducing an `opt_self_var` field in `TypeDisplayContext` which
is used to recognize the type variable and display "Self" instead
of recursing.
Fixes #14913 
Added a reduced test based on Igor's finding.
If we allow more recursive types/constraint in the future then we
may want a more general mechanism.  I think we should punt for now,
but others may disagree.
> [compiler-v2] Avoid infinite recursion showing types with receiver functions in presence of errors

- third_party/move/move-compiler-v2/src/env_pipeline/inliner.rs
- third_party/move/move-compiler-v2/tests/checking-lang-v1/underscore.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v1/underscore.move
- third_party/move/move-compiler-v2/tests/checking/naming/underscore.exp
- third_party/move/move-compiler-v2/tests/checking/naming/underscore.move
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore.move
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore.operator-eval-lang-1.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore.operator-eval-lang-2.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore_v1.move
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore_v1.operator-eval-lang-1.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore_v1.operator-eval-lang-2.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore_v2.move
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore_v2.operator-eval-lang-1.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/operator_eval/underscore_v2.operator-eval-lang-2.exp
- third_party/move/move-compiler/tests/move_check/naming/underscore.exp
- third_party/move/move-compiler/tests/move_check/naming/underscore.move
- third_party/move/move-compiler/transactional-tests/tests/parser/underscore.exp
- third_party/move/move-compiler/transactional-tests/tests/parser/underscore.move
- third_party/move/move-compiler/transactional-tests/tests/parser/underscore_v1.exp
- third_party/move/move-compiler/transactional-tests/tests/parser/underscore_v1.move
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/builder/module_builder.rs
In Move Language 2.0+, treat a function parameter named "_" as a wildcard value-sink, not a variable.
This is needed if we want to use `_` in closure construction.
Fixes #14949.
Added more tests of underscore parameter and local vars.  Use the same
tests for V1 and compiler-v2 with Lang V1 and Lang V2.
- One or multiple params named _
- use of value of _
- Passing actual of wrong type to _ parameter
- Inline functions with same
Added duplicate transactional tests that comment out lines causing
compile-time errors (separately for V1 and V2) to demonstrate that
other transactions actually run correctly.
Did I miss any places where Parameters might be processed?
> [move-compiler-v2] Don't treat underscore parameters as variables in Move Lang V2+

- .github/workflows/forge-stable.yaml
- .github/workflows/forge-unstable.yaml
Forge stable and unstable today have `always()` conditions on the jobs, making them impossible to cancel outside of invoking from the GH API. Add a step summary that points folks to tooling to cancel via API
> [forge] add a message to the summary on how to cancel a job

- third_party/move/move-compiler-v2/tests/checking/abilities/bug_14490_field_abilities.exp
- third_party/move/move-compiler-v2/tests/checking/abilities/bug_14490_field_abilities.move
- third_party/move/move-compiler-v2/tests/checking/positional_fields/named_tuple_ability_decl_ok.exp
- third_party/move/move-compiler-v2/tests/checking/positional_fields/named_tuple_ability_decl_ok.move
- third_party/move/move-model/src/ty.rs
Closes #14490
Move has some unusual semantics for ability checking of type parameters
- In most contexts, a type parameter is assumed to have all abilities during checking. Then when the parameter is instantiated, checking takes place.
- However, there is one exemption, namely when a type parameter is used to instantiate another type parameter which has an abilitie constraint, as in `f<T:drop>`. If we instantiate `f<R>` then `R` needs to be checked for `drop`.
This PR solves this by adding a field `type_param_exempted` to `HasAbilities(abilities, type_param_exempted)` to the ability constraint.
New baseline test, existing tests
> [compiler-v2] Revise ability checking for type parameters

- consensus/src/state_computer.rs
- execution/executor-types/src/ledger_update_output.rs
- execution/executor-types/src/parsed_transaction_output.rs
- execution/executor-types/src/state_compute_result.rs
- execution/executor/src/block_executor.rs
- execution/executor/src/chunk_executor.rs
- execution/executor/src/components/apply_chunk_output.rs
- execution/executor/src/components/do_ledger_update.rs
- execution/executor/src/components/executed_chunk.rs
- execution/executor/src/components/mod.rs
- execution/executor/src/db_bootstrapper.rs
- execution/executor/src/fuzzing.rs
- storage/aptosdb/src/db/include/aptosdb_testonly.rs
- storage/aptosdb/src/db/include/aptosdb_writer.rs
- storage/aptosdb/src/db/mod.rs
- storage/aptosdb/src/db/test_helper.rs
- storage/aptosdb/src/fast_sync_storage_wrapper.rs
- storage/aptosdb/src/ledger_db/transaction_db.rs
- storage/aptosdb/src/ledger_db/transaction_db_test.rs
- storage/aptosdb/src/ledger_db/write_set_db.rs
- storage/aptosdb/src/ledger_db/write_set_db_test.rs
- storage/aptosdb/src/pruner/state_merkle_pruner/test.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/aptosdb/src/state_store/state_store_test.rs
- storage/storage-interface/src/chunk_to_commit.rs
- storage/storage-interface/src/lib.rs
- types/src/proptest_types.rs
1. avoid unnecessary packing and unpacking, it's desirable because I'm
gonna make the PartialStateComputeResult consist of multiple
immutable stage outputs.
2. extract DoLedgerUpdate algorithm
> avoid TransactionToCommit

- testsuite/forge/src/backend/k8s/helm-values/aptos-node-default-values.yaml
Fix default arguments for the `aptos-node` Helm chart when initialized by Forge.
Previously changed in https://github.com/aptos-labs/aptos-core/pull/14547.
> Fix Forge default arguments to the aptos-node Helm chart

- Cargo.lock
- ecosystem/nft-metadata-crawler/Cargo.toml
- ecosystem/nft-metadata-crawler/migrations/2024-10-02-062003_add_asset_uploader_requests_table/up.sql
- ecosystem/nft-metadata-crawler/src/asset_uploader/api/get_status.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/api/mod.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/mod.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/throttler/config.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/throttler/mod.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/worker/mod.rs
- ecosystem/nft-metadata-crawler/src/config.rs
- ecosystem/nft-metadata-crawler/src/models/asset_uploader_request_statuses.rs
- ecosystem/nft-metadata-crawler/src/models/asset_uploader_request_statuses_query.rs
- ecosystem/nft-metadata-crawler/src/schema.rs
Implementation of the Asset Uploader Throttler.
Design: https://www.notion.so/aptoslabs/WIP-Asset-Uploader-cb33138051324d1fa03115ef1b55ed0b
`src/asset_uploader/throttler/mod.rs`
> [NFT Metadata Crawler] Asset Uploader Throttler

- Cargo.lock
- Cargo.toml
- ecosystem/nft-metadata-crawler/Cargo.toml
- ecosystem/nft-metadata-crawler/migrations/2024-10-02-062003_add_asset_uploader_requests_table/down.sql
- ecosystem/nft-metadata-crawler/migrations/2024-10-02-062003_add_asset_uploader_requests_table/up.sql
- ecosystem/nft-metadata-crawler/src/asset_uploader/api/get_status.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/api/mod.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/api/upload_batch.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/mod.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/throttler/config.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/throttler/mod.rs
- ecosystem/nft-metadata-crawler/src/asset_uploader/worker/mod.rs
- ecosystem/nft-metadata-crawler/src/config.rs
- ecosystem/nft-metadata-crawler/src/models/asset_uploader_request_statuses.rs
- ecosystem/nft-metadata-crawler/src/models/asset_uploader_request_statuses_query.rs
- ecosystem/nft-metadata-crawler/src/models/mod.rs
- ecosystem/nft-metadata-crawler/src/schema.rs
Implementation of the Asset Uploader API. 
Design: https://www.notion.so/aptoslabs/WIP-Asset-Uploader-cb33138051324d1fa03115ef1b55ed0b
> [NFT Metadata Crawler] Asset Uploader API

- Cargo.lock
- third_party/move/move-compiler-v2/src/experiments.rs
- third_party/move/move-compiler-v2/src/lib.rs
This PR enables the control flow graph simplification as a default optimization.
Existing tests && comparison testing.
> [Compiler V2] Turn on CFG simplification as default optimization

- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
After seeing many repositories where people have uploaded their private keys via config.yaml, this should prevent it on two levels:
1. No more build artifacts, and private keys in move projects
2. No more saving .aptos/config.yaml files.
New move repos add it automatically if it doesn't exist.
.aptos/ folders only add it if it doesn't exist.
Tested manually with each individually, they prevent them from being saved.
> [cli] Add .gitignore in new move folders and in .aptos folder

- testsuite/forge-cli/src/suites/realistic_environment.rs
This PR bumps the latency threshold for the `realistic_env_load_sweep_test()` by 100ms. We're seeing a threshold failure in forge stable, e.g.,:
```
Test Failed: Failed latency check, for ["P90 latency for 10 is 0.9s and exceeds limit of 0.9s"]
```
> [Forge] Bump latency threshold for realistic_env_load_sweep test.

- consensus/consensus-types/src/proof_of_store.rs
- consensus/src/consensus_observer/network/observer_message.rs
- consensus/src/consensus_observer/observer/payload_store.rs
This PR parallelizes message verification steps in consensus observer. Specifically, payload signature verification and payload digest verification. This should save about ~20ms in consensus observer lag for `realistic_env_max_load` (e.g., see: https://github.com/aptos-labs/aptos-core/pull/15002)
> [Consensus Observer] Parallelize message processing logic.

- config/src/config/consensus_observer_config.rs
- consensus/src/consensus_observer/observer/fallback_manager.rs
This PR adds a grace period to consensus observer (CO) that prevents CO from entering fallback mode until the grace period is over. This helps to prevent fallback from occurring when a network first starts (e.g., forge).
> [Consensus Observer] Add startup period before fallback.

- aptos-move/framework/src/built_package.rs
- crates/aptos/CHANGELOG.md
- crates/aptos/src/common/types.rs
- testsuite/single_node_performance.py
- third_party/move/move-compiler/src/parser/syntax.rs
- third_party/move/move-compiler/src/shared/mod.rs
- third_party/move/move-model/src/metadata.rs
- third_party/move/move-prover/tests/testsuite.rs
- Updating CHANGELOG
- Marking Move 2.1 stable and the default
> [cli 4.2.4] Preparing for CLI release

- testsuite/single_node_performance.py
> [single node benchmark] recalibrate and make thresholds depend on number samples present

- crates/aptos/CHANGELOG.md
- crates/aptos/src/move_tool/fmt.rs
- crates/aptos/src/move_tool/mod.rs
Makes error handling come out of stderr instead of relying on panics.
> [cli] Replace unwraps with better error handling

- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/runner.rs
Set `enable_storage_sharding` and `enable_event` to be true
Will run adhoc forge
https://github.com/aptos-labs/aptos-core/actions/runs/11488481527
> hardcode enable_storage_sharding

- Cargo.lock
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
- crates/aptos/src/common/types.rs
- third_party/move/move-prover/move-docgen/tests/testsuite.rs
Bumping version of cli to fix a bug with move-2 flag
> [cli] Bumping to 4.2.6 to fix in issue with `--move-2` flag

- storage/aptosdb/src/versioned_node_cache.rs
This can potentially block the pre_commit_ledger thread while it's holding the buffered_state lock. Before we reduce the scope of that lock, I'm moving this part off the defualt pool so that even if the default pool gets busy (or worse, there are tasks on the threads of the pool trying to lock the buffered_state) this part doesn't get affected.
> move maybe_evict_cache() off default rayon pool

- aptos-move/framework/src/chunked_publish.rs
- aptos-move/move-examples/large_packages/sources/large_packages.move
- Removed Option type in large_packages.move, initially introduced to handle both code deployment and upgrade in a single interface. Separate functions now exist for each operation.
- Deployed the new version of large_packages.move as an immutable package under address `0x0e1ca3011bdd07246d4d16d909dbb2d6953a86c4735d5acf5865d962c630cce7`, both on testnet and mainnet.
- Updated Move module address in chunked_publish.rs to the latest version.
run [large_package_publishing](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/e2e-move-tests/src/tests/large_package_publishing.rs) e2e test
> Update large packages module

- state-sync/state-sync-driver/src/driver.rs
- state-sync/state-sync-driver/src/metrics.rs
- state-sync/state-sync-driver/src/storage_synchronizer.rs
- state-sync/state-sync-driver/src/utils.rs
This PR updates the synced version and synced epoch metrics. We now track these metrics in two ways: (i) by reading the values directly from storage; and (ii) by incrementally summing up all processed transactions and epochs. 
The first metric will be used as the "official" metric, and the second as a sanity check to ensure that there are no gaps in transaction and/or epoch processing (e.g., consensus dropping notifications meant for state sync).
> [State Sync] Update synced version and synced epoch metrics.

- storage/aptosdb/src/db_debugger/mod.rs
- storage/aptosdb/src/db_debugger/validation.rs
one time tool, save in case we may want to use
> add validation for internal indexer data

- consensus/consensus-types/src/common.rs
- consensus/consensus-types/src/payload.rs
- consensus/src/epoch_manager.rs
- consensus/src/liveness/proposal_status_tracker.rs
- consensus/src/quorum_store/batch_coordinator.rs
- consensus/src/quorum_store/batch_proof_queue.rs
- consensus/src/quorum_store/counters.rs
- consensus/src/quorum_store/mod.rs
- consensus/src/quorum_store/network_listener.rs
- consensus/src/quorum_store/proof_coordinator.rs
- consensus/src/quorum_store/proof_manager.rs
- consensus/src/quorum_store/quorum_store_builder.rs
- consensus/src/quorum_store/quorum_store_coordinator.rs
- consensus/src/quorum_store/tests/proof_coordinator_test.rs
- consensus/src/quorum_store/tracing.rs
- consensus/src/quorum_store/utils.rs
- consensus/src/round_manager.rs
This PR fixes a config bug and adds metrics for OptQS and QS batch tracing.
- Fixes `minimum_batch_age_usecs` to 10 milliseconds. It was set to 50 secs instead of 50ms.
- Adjusts unique transactions when pulling optQS based on the number of proofs pulled. 
- BatchCoordinator: assign batches to coordinator in round-robin instead of using author-based index.
- Fixes a metrics call issue where late votes were never counted at all.
- Trace batch from sender to receiver and back to form a PoS. Also observe time for every 10% increment in accumulated voting power.
> [optqs] add new metrics, batch tracing, and bug fixes

- .github/workflows/docker-build-test.yaml
- .github/workflows/forge-stable.yaml
- .github/workflows/workflow-run-forge.yaml
- Cargo.lock
- Cargo.toml
- testsuite/fixtures/testFormatJunitXml.fixture
- testsuite/fixtures/testMain.fixture
- testsuite/forge-cli/Cargo.toml
- testsuite/forge-cli/src/main.rs
- testsuite/forge-test-runner-template.yaml
- testsuite/forge.py
- testsuite/forge/Cargo.toml
- testsuite/forge/src/config.rs
- testsuite/forge/src/interface/test.rs
- testsuite/forge/src/lib.rs
- testsuite/forge/src/observer/junit.rs
- testsuite/forge/src/observer/mod.rs
- testsuite/forge/src/result.rs
- testsuite/forge/src/runner.rs
- testsuite/forge_test.py
- testsuite/testcases/src/lib.rs
Add junit support for forge
This will allow us to onboard forge onto trunk flaky test detection
Also make suite choice more clean
Test Plan: running on a subsequent PR (due to pull request target) 
https://github.com/aptos-labs/aptos-core/pull/15042/checks
also running on this PR (to ensure behavior doesnt change without flag)
> [forge] Add junit support

- aptos-move/e2e-benchmark/src/main.rs
want to have clean baseline, for the changes coming on top (for move 2 compiler). I don't see any changes in last 90 days, so this is probably not perfectly calibrated to start with, or some very old perf change.
> recalibrate move e2e tests

- execution/executor/tests/internal_indexer_test.rs
When changing something in the framework, that changes genesis (even new stdlib module), this test fails cryptically:
```
thread 'test_db_indexer_data' panicked at execution/executor/tests/internal_indexer_test.rs:196:5:
assertion `left == right` failed
left: 151
right: 152
```
Changing it so that:
- error message is clearer
- fixing it is clearer (instead of just changing number - you modify the key that your PR changes)
unit tested on PRs changing genesis
> improve internal_indexer_test.rs and error it gives

- aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs
- aptos-move/framework/src/natives/randomness.rs
Charge a few extra cents for the randomness call, so it's less fragile against future intrinsic gas changes.
TODO
n/a
> randomness native gas

- aptos-move/aptos-vm/Cargo.toml
- aptos-move/framework/src/built_package.rs
- third_party/move/tools/move-package/src/compilation/compiled_package.rs
Fixed #14311. This PR continues the partial fix from @jasonxh https://github.com/aptos-labs/aptos-core/pull/14340 by
- extending `OnDiskPackage`
- fix the way package metadata is extracted from the bytecode dependency in the original pr
The original issue is caused by `CompiledPackage` missing information for bytecode dependencies, which propagates to `PackageMetadata` when constructing transaction payloads.
This is manually tested on the #14311
> [Bugfix] Fix broken bytecode dependency

- Cargo.lock
- Cargo.toml
- aptos-move/aptos-vm/Cargo.toml
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
- third_party/move/move-vm/metrics/Cargo.toml
- third_party/move/move-vm/metrics/src/lib.rs
- third_party/move/move-vm/runtime/Cargo.toml
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/loader/modules.rs
- third_party/move/move-vm/runtime/src/runtime.rs
Some basic counters that address #14348. Note that some metrics should not be collected via this timer, e.g., interpreter loop so that there is no perf degradation. Hence, added only in a few interesting places (e.g., module loading cache misses, resource loading cache misses, total execution times for user transaction with basic break downs).
> [move-vm][aptos-vm] Basic execution counters

- aptos-move/e2e-move-tests/src/tests/large_package_publishing.rs
- aptos-move/framework/src/chunked_publish.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/test/mod.rs
- Added a new `--large-packages-module-address` command option for Move package publishing:
- `aptos move publish`
- `aptos move deploy-object`
- `aptos move upgrade-object`
- `aptos move create-object-and-publish-package`
- `aptos move upgrade-object-package`
- `aptos move clear-staging-area`
- This option will be used alongside the `--chunked-publish` flag. If provided, the specified large packages module address will be used.
- Note that the CLI does not verify if the module actually exists at the given address; it will simply abort if an incorrect address is supplied.
- The default address will be used if no address is provided.
- This feature allows users to utilize the chunked publishing in the localnet testing environment by manually deploying the …
> [cli] Make large packages module address configurable

- Cargo.lock
- aptos-move/e2e-move-tests/src/tests/large_package_publishing.rs
- aptos-move/framework/src/chunked_publish.rs
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/test/mod.rs
Fixes parsing of large packages override address
This works now with localnet when deploying locally.  It didn't work with address aliases / missing 0x before.
Now:
```bash
../../../target/cli/aptos move publish --profile local2 --named-addresses hello_blockchain=local2 --chunked-publish --large-packages-module-address local
BUILDING Examples
package size 1718 bytes
Publishing package in chunked mode will submit 1 transactions for staging and publishing code.
Transaction 1 of 1
Do you want to submit a transaction for a range of [8700 - 13000] Octas at a gas unit price of 100 Octas? [yes/no] >
y
Transaction submitted: …
```
> [cli] Release 4.3.0 & Chunked publish override

- Cargo.lock
- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/aptos-vm/src/move_vm_ext/session/mod.rs
- aptos-move/aptos-vm/src/transaction_metadata.rs
- aptos-move/e2e-move-tests/src/tests/transaction_context.data/pack/sources/transaction_context_test.move
- aptos-move/e2e-move-tests/src/tests/transaction_context.rs
- aptos-move/framework/aptos-framework/doc/randomness.md
- aptos-move/framework/aptos-framework/doc/transaction_context.md
- aptos-move/framework/aptos-framework/sources/object.move
- aptos-move/framework/aptos-framework/sources/randomness.move
- aptos-move/framework/aptos-framework/sources/transaction_context.move
- aptos-move/framework/aptos-framework/sources/transaction_context.spec.move
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.move
- aptos-move/framework/src/natives/transaction_context.rs
- types/src/on_chain_config/aptos_features.rs
- types/src/transaction/user_transaction_context.rs
Revert #13659 (Add a transaction context function to get the raw transaction hash)
It turns out that we need more discussion on the requirement of `raw_transaction_hash`.
> Revert #13659 (Add a transaction context function to get the raw transaction hash)

- .github/workflows/forge-stable.yaml
Refactor Forge Stable workflow to achieve the following:
- Make parallelism configurable. One job at a time is too limited in critical situations.
- Add ability to run single test (GH doesn't support multiple choice, so we get single choice) or entire workflow.
- Add new tests easily because the tests are defined as a JSON blob
The above is accomplished by dynamically generating a matrix strategy based on inputs before dispatching the forge jobs.
> [gha] Refactor Forge Stable to run individual tests

- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_mainnet_txns/155112189_default_table_items.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_mainnet_txns/1845035942_default_current_table_items.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_mainnet_txns/513424821_default_block_metadata_transactions.json
- ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml
Generate new transactions for the default_processor diff tests from mainnet.
> Add Txns for Default Processor

- crates/aptos/CHANGELOG.md
- crates/aptos/src/common/types.rs
Fixed https://github.com/aptos-labs/aptos-core/issues/15131
Run `cargo run -p aptos -- move compile --help` and check the output.
> [Bugfix] [Cli] Fix typo

- aptos-move/framework/move-stdlib/sources/bit_vector.move
- aptos-move/framework/tests/gate_v2_features.rs
We add tests for compiling framework code using compiler v1, so that no v2 features are accidentally used in the framework until mainnet has upgraded to use language v2.
Check out [26d691f](https://github.com/aptos-labs/aptos-core/pull/15146/commits/26d691fabe61c9477bfc0605a4738b3422eea4c6) where some v2 features are used in the framework, and the tests should fail.
> [Framework] Gate V2 Features in Framework until V2 Features Allowed on Mainnet

- storage/aptosdb/src/db/include/aptosdb_writer.rs
- storage/aptosdb/src/db/test_helper.rs
- storage/aptosdb/src/pruner/state_merkle_pruner/test.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/aptosdb/src/state_store/state_store_test.rs
write only at chunk boundaries and the latest checkpoint (used to be enabled with sharding but it's actually orthognal)
> Stop writing down usage at all versions

- ecosystem/indexer-grpc/indexer-grpc-table-info/src/internal_indexer_db_service.rs
during restore, we also need to enable the transaction and event to make sure the progress is tracked
> fix internal indexer progress tracking during restore

- consensus/src/counters.rs
- consensus/src/round_manager.rs
Record the failed author as label in the `AGGREGATED_ROUND_TIMEOUT_REASON` metric, so we can identify which author failed for what reason.
> [consensus] record timeout author with reason in metrics

- third_party/move/tools/move-cli/src/base/test.rs
During move test --coverage, a huge .trace file is generated, but is
then processed to generate a more compact coverage map which should
contain all neededed data.  We now delete the .trace file after
successful generation of the coverage map.
Fixes #15054 .
Ran manually on a few cases.  Made sure that `aptos move coverage ...` features work without .trace file.
?
> cleanup trace file after coverage map is generated successfully

- .github/workflows/forge-stable.yaml
- Fix parallelism param bug that prevented the workflow from running on schedule trigger
- If a test doesn't need failpoints or performance image, no need to check for it and use a older image.
- Set concurrency level for dispatch trigger based on git SHA so it doesn't interfere with multiple workflow runs on same ref.
> [forge] forge stable bug fixes

- types/src/transaction/mod.rs
We should log auxiliary data when there is a transaction output mismatch to be able to see error messages in case those got removed.
> [replay] Add error messages from aux data

- Cargo.lock
- Cargo.toml
- ecosystem/indexer-grpc/indexer-test-transactions/src/lib.rs
- third_party/move/move-compiler-v2/tests/checking/typing/loop_result_type.exp
- third_party/move/move-model/bytecode/Cargo.toml
- third_party/move/move-model/bytecode/ast-generator-tests/tests/abort_example.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/abort_example.move
- third_party/move/move-model/bytecode/ast-generator-tests/tests/bit_vector_loop_example.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/bit_vector_loop_example.move
- third_party/move/move-model/bytecode/ast-generator-tests/tests/conditionals.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/conditionals.move
- third_party/move/move-model/bytecode/ast-generator-tests/tests/loops.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/loops.move
- third_party/move/move-model/bytecode/ast-generator-tests/tests/match.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/testsuite.rs
- third_party/move/move-model/bytecode/src/astifier.rs
- third_party/move/move-model/src/ast.rs
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/exp_builder.rs
- third_party/move/move-model/src/sourcifier.rs
- third_party/move/tools/move-decompiler/src/lib.rs
- third_party/move/tools/move-decompiler/tests/bit_vector.exp
- third_party/move/tools/move-decompiler/tests/bit_vector.move
- third_party/move/tools/move-decompiler/tests/fixed_point32.exp
- third_party/move/tools/move-decompiler/tests/option.exp
- third_party/move/tools/move-decompiler/tests/simple_map.exp
- third_party/move/tools/move-decompiler/tests/string.exp
- third_party/move/tools/move-decompiler/tests/vector.exp
This PR implements some major improvements to the astifier:
- Finally (I think) cracked the way how to do correct topological sorting and managing nested blocks. More complicated examples now produce more reasonable results.
- Rewrote AST transformations for if-then-else and loops.
- Fixed issues with the fixpoint analysis on the AST
- Did some minor fixes in the sourcifier
The generated source is still not correct in some cases, but much better then before.
Baseline tests
> Astifier fixes

- third_party/move/move-compiler-v2/tests/checking/variants/bug_15073.exp
- third_party/move/move-compiler-v2/tests/checking/variants/bug_15073.move
- third_party/move/move-compiler/src/expansion/translate.rs
This PR closes #15073 by generating an error instead of using `expect` when `bind_list` fails during handling `match` statements.
2) added a new test.
> [Compiler-v2][trivial] fix error handling for `match` in expansion phase

- aptos-move/framework/aptos-framework/doc/aggregator.md
- aptos-move/framework/aptos-framework/sources/aggregator/aggregator.spec.move
- aptos-move/framework/src/aptos-natives.bpl
- crates/aptos/CHANGELOG.md
- crates/aptos/src/update/movefmt.rs
This PR
1) closes #15135 by adding intrinsic implementation of `limit` method for `aggregator`
2) updates installation of movefmt from 1.0.5 to 1.0.6.
1) existing tests pass with no warning;
2) manual CLI test
> [trivial] Add intrinsic for limit for aggregator and update movefmt version

- third_party/move/move-compiler-v2/src/lib.rs
- third_party/move/move-model/bytecode/ast-generator-tests/tests/abort_example.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/bit_vector_loop_example.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/conditionals.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/loops.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/match.exp
- third_party/move/move-model/bytecode/src/fat_loop.rs
- third_party/move/move-model/bytecode/src/stackless_bytecode.rs
- third_party/move/move-prover/tests/sources/functional/aborts_if.v2_exp
- third_party/move/move-prover/tests/sources/functional/bug_15044.move
- third_party/move/move-prover/tests/sources/functional/bv_aborts.v2_exp
- third_party/move/move-prover/tests/sources/functional/choice.v2_exp
- third_party/move/move-prover/tests/sources/functional/emits.v2_exp
- third_party/move/move-prover/tests/sources/functional/enum_abort.v2_exp
- third_party/move/move-prover/tests/sources/functional/global_invariants.v2_exp
- third_party/move/move-prover/tests/sources/functional/is_txn_signer.v2_exp
- third_party/move/move-prover/tests/sources/functional/loop_unroll.v2_exp
- third_party/move/move-prover/tests/sources/functional/loops.v2_exp
- third_party/move/move-prover/tests/sources/functional/loops_with_memory_ops.v2_exp
- third_party/move/move-prover/tests/sources/functional/macro_verification.v2_exp
- third_party/move/move-prover/tests/sources/functional/script_incorrect.v2_exp
- third_party/move/tools/move-decompiler/tests/fixed_point32.exp
- third_party/move/tools/move-decompiler/tests/option.exp
- third_party/move/tools/move-decompiler/tests/simple_map.exp
- third_party/move/tools/move-decompiler/tests/string.exp
Currently, loop analysis [collects](https://github.com/aptos-labs/aptos-core/blob/3b23a90154809474c905d8e90c6bd0d4b8f7ef0f/third_party/move/move-model/bytecode/src/fat_loop.rs#L447) bytecode for unrolling loops and returns a vector of basic blocks, which will be directly flatten later. This implementation will lead to incorrect boogie code if a block in the vector falls through to its successor in the original CFG but the next element in the vector is actually not its successor. The bug leads to verification failure shown in #15044 when CFG simplification is turned on. This PR fixes the issue by inserting the explicit jump instruction.
Close #15044 
2) a new test;
The code change will only influence bounded verification with `unroll` pragma. Need to make sure this …
> [Prover] Fix bug in loop unrolling

- testsuite/forge-cli/src/suites/realistic_environment.rs
As TPS has improved, increase the TPS of the graceful overload test to more properly test overload. (The current "overload" could almost be reached at peak TPS.)
Run the test, see TPS -- it now shows overload
https://github.com/aptos-labs/aptos-core/actions/runs/11636241940
> [forge] increase load of graceful overload

- aptos-move/aptos-workspace-server/src/main.rs
This refactors the existing `aptos-workspace-server` implementation to make use of shared futures. This shift of paradigm will give us great flexibility and scalability when it comes to managing complex service startup sequences, paving the road for supporting the indexer components.
Manually tested. Automated tests will be set up later as planned
The use of shared futures
> [aptos-workspace-server] service-startup using shared futures

- third_party/move/move-compiler-v2/src/env_pipeline/inliner.rs
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/builder/module_builder.rs
Feature gating for #14962 from Move 2.0 to Move 2.1
Existing tests
Check whether all places are covered: #14962
> [Compiler-v2] feature gating for semantic change of `_` to Move 2.1

- aptos-move/framework/aptos-framework/doc/account.md
- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/aptos-framework/sources/account.spec.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
@banool @gregnazario
Closes #13517
AIP: https://github.com/aptos-foundation/AIPs/issues/487
There are currently several issues with the `OriginatingAddress` table (which is
supposed to be a one-to-one lookup table) that render the mapping unsafe in
practice:
1. Per #13517, `rotate_authentication_key_call` does not update the
`OriginatingAddress` table for an "unproven" key rotation without a
`RotationProofChallenge` (resolved in this PR with new
`set_originating_address` private entry function).
1. During an operation that attempts to map an authentication key (which has
already been mapped) to a different originating address, the inner function
`update_auth_key_and_originating_address_table` overwrites the initial
mapping, rather than aborting. This oversight can lead to account loss if …
> [Framework] Safe onchain key rotation address mapping for standard accounts

- consensus/consensus-types/src/payload.rs
- consensus/src/consensus_observer/network/observer_message.rs
Fixes verification of OptQuorumStore payloads in Consensus Observer.
[Verified with test run](https://grafana.aptoslabs.com/d/overview/overview?orgId=1&var-Datasource=fHo-R604z&var-BigQuery=axNEitxVz&var-namespace=forge-e2e-pr-15158&var-metrics_source=$__all&var-chain_name=forge-0&from=2024-11-05T19:22:16.841Z&to=2024-11-05T19:30:16.091Z&var-cluster=$__all&var-kubernetes_pod_name=$__all)
> [optqs][co] Implement optQS payload validation in CO

- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_mainnet_txns/578318306_objects_write_resource.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/scripted_transactions/simple_user_script1.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/scripted_transactions/simple_user_script2.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/scripted_transactions/simple_user_script3.json
- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/scripted_transactions/simple_user_script4.json
- ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml
> Add objects test txns

- .github/actions/rust-smoke-tests/action.yaml
v3 has been deprecated and will brown out (be failed on purpose by Github) soon.
> Switch to update-artifact v4

- crates/aptos/src/move_tool/mod.rs
- third_party/move/tools/move-package/src/source_package/std_lib.rs
This migrates the aptos-cli to use dependencies from the newly-setup aptos-framework repo. Specifically, this updates the `move init` command and the `--override-std` option.
> aptos-framework repo migration: aptos-cli [2/n]

- .github/workflows/cli-release.yaml
- scripts/cli/build_cli_release.sh
This should prevent us from releasing poorly setup versions.  Note, I didn't fix Windows, but the whole flow will stop if the linux builds break.
1. This ensures a version isn't double uploaded
2. This ensures the inputted tag matches the crate version
Tested locally
1. Already existing version:
```
sh scripts/cli/build_cli_release.sh Mac 4.2.6
4.2.6 already released
```
2. New version (when changing the cargo version):
```
sh scripts/cli/build_cli_release.sh Mac 6.0.0
Building release 6.0.0 of aptos-cli for Darwin-Mac on arm64
Compiling move-core-types v0.0.4 (/opt/git/aptos-core/third_party/move/move-core/types)
Compiling aptos-build-info v0.1.0 (/opt/git/aptos-core/crates/aptos-build-info)
...
```
3. Version mismatch
```
sh scripts/cli/build_cli_release.sh Mac 7.0.0
Wanted to release …
```
> [cli] Update CLI release script to check for versions

- crates/aptos/CHANGELOG.md
- crates/aptos/src/node/local_testnet/postgres.rs
When using `--use-host-postgres`, it can sometimes be helpful to specify a different address for the postgres instance rather than `127.0.0.1`. This PR adds the `--host-postgres-host` flag to let you do that.
```
cargo run -p aptos -- node run-localnet --use-host-postgres --host-postgres-host 1.2.3.4 --with-indexer-api
```
I confirmed that if you use a host where a DB is running the localnet comes up, and otherwise does not.
N/A
> Add --host-postgres-host flag to CLI for localnet

- consensus/src/consensus_observer/common/metrics.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
- consensus/src/consensus_observer/observer/pending_blocks.rs
- consensus/src/consensus_observer/observer/subscription_utils.rs
This PR makes two small changes to consensus observer (CO):
1. Adds simple metrics to track how long message processing takes, i.e., once a message is received by CO, we track how long it takes for it be processed, including message verification. We also take into account ordered block messages being placed into the pending block store before they are processed.
1. Fixes the ordering of parameters passed to `sort_peers_for_subscriptions` and adds some simple tests. Note: the incorrect ordering doesn't impact the behaviour as both sets of peers are "ignored" equally.
New and existing test infrastructure. You can also see the new metrics [here](https://grafana.aptoslabs.com/d/ddphlx0p7mxvka/consensus-observer?from=2024-11-06T15:49:28.378Z&to=2024-11-06T15:57:35.000Z&var-Datasource=fHo-R604z& …
> [Consensus Observer] Add message processing latency metrics.

- aptos-move/framework/README-MIRROR-REPO.md
This adds a README for the mirror repo (https://github.com/aptos-labs/aptos-framework).
> [framework] add README for the mirror repo

- .github/workflows/fullnode-fast-devnet-main.yaml
- .github/workflows/fullnode-fast-devnet-stable.yaml
This PR adds 2 new fullnode sync jobs to verify fast sync in `devnet`:
1. Fast sync using the `main` branch
2. Fast sync using the `devnet` branch
This should help us catch any potential issues with fast sync earlier (without needing to wait for testnet).
> [Fullnode Sync] Add jobs to verify fast sync in devnet.

- api/test-context/src/test_context.rs
- aptos-move/aptos-vm/src/counters.rs
- aptos-move/block-executor/src/counters.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/e2e-benchmark/src/main.rs
- consensus/Cargo.toml
- consensus/src/consensus_provider.rs
- consensus/src/execution_pipeline.rs
- ecosystem/indexer-grpc/indexer-test-transactions/src/lib.rs
- execution/executor-benchmark/src/block_preparation.rs
- execution/executor-benchmark/src/db_generator.rs
- execution/executor-benchmark/src/lib.rs
- execution/executor-benchmark/src/main.rs
- execution/executor-benchmark/src/native/mod.rs
- execution/executor-benchmark/src/native/native_config.rs
- execution/executor-benchmark/src/native_executor.rs
- execution/executor-benchmark/src/pipeline.rs
- execution/executor-benchmark/src/transaction_committer.rs
- execution/executor-benchmark/src/transaction_executor.rs
- execution/executor-test-helpers/src/integration_test_impl.rs
- execution/executor/src/block_executor/mod.rs
- execution/executor/src/fuzzing.rs
- execution/executor/src/metrics.rs
- execution/executor/src/tests/mock_vm/mod.rs
- execution/executor/tests/db_bootstrapper_test.rs
- experimental/execution/ptx-executor/src/lib.rs
- testsuite/single_node_performance.py
* Separately reporting signature_verification and ledger_update stages.
* changing "block execution time" from being VM_EXECUTE_BLOCK counter to BLOCK_EXECUTOR_EXECUTE_BLOCK - as it is counting BlockSTM + VM, instead of just VM. adding BLOCK_EXECUTOR_INNER_EXECUTE_BLOCK when needed better granularity.
* Changed so that AptosVM is decoupled from BlockSTM. I.e. AptosVM doesn't implement TransactionBlockExecutor any more, but there is new AptosVMBlockExecutor. That allows for creating NativeVMBlockExecutor in a following PR. Allowing TransactionBlockExecutor to have state if needed, with having new() and &self argument.
* fixed split_stages to split all pipeline stages, and for initial delay to only create transacitons, but not start the pipline (i.e. verification) beforehand. 
Followup PR …
> Executor benchmark revamps

- ecosystem/indexer-grpc/indexer-test-transactions/src/lib.rs
we were using a scripted txn for the test, but since this is submitted to localnet, we might get different txn_version for thist xn when it's resubmitted. 
In this change, we replaced with imported txn, whose txn_version will never change. 
test passed
> fix transaction test failure

- aptos-move/aptos-vm-types/src/abstract_write_op.rs
- aptos-move/aptos-vm-types/src/change_set.rs
- aptos-move/aptos-vm-types/src/module_write_set.rs
- aptos-move/aptos-vm-types/src/tests/test_change_set.rs
- aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
- aptos-move/e2e-move-tests/src/tests/storage_refund.rs
- crates/aptos-rosetta/src/test/mod.rs
- ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
- testsuite/generate-format/src/api.rs
- testsuite/generate-format/src/aptos.rs
- testsuite/generate-format/src/consensus.rs
- types/src/state_store/state_value.rs
- types/src/transaction/change_set.rs
- types/src/transaction/mod.rs
- types/src/write_set.rs
WrietOp carries StataValue so that in many cases (that I'm gonna introduce) we can use refs to StateValue directly out of the transaction outputs without constructing them. 
Removed the cached hashvalue field on StateValue otherwise there's a slight performance regression (now it's a slight improvement, it looks like). Also, now that we have introduced setters to the fields, it's safer not to cache the hash. 
We only need the hashes when we update the trees and if necessary I will explicitly cache them. 
> WriteOp carries StateValue

- devtools/aptos-cargo-cli/src/common.rs
This PR updates the target determinator to take into account JSON and YAML files. If any of these files change, the closest rust package is marked as affected. This should be good enough to catch any edge cases we've encountered (e.g., around the indexer GRPC tests).
Existing test infrastructure and manual verification. I changed a JSON file locally and verified that the closest package was marked as affected, e.g.,:
```
Running `target/debug/aptos-cargo-cli affected-packages -vvv`
[2024-11-08T00:34:48Z INFO  aptos_cargo_cli::common] Identified the merge base: "7df77b85d4894c7355cb306abeecca5a4ded2d44"
[2024-11-08T00:34:48Z DEBUG aptos_cargo_cli::common] Attempting to read metadata from local file: ".../aptos-core/target/aptos-x-tool/metadata-7df77b85d4894c7355cb306abeecca5a4ded2d44.json" …
```
> [Target Determination] Track JSON and YAML files.

- network/framework/src/application/interface.rs
- network/framework/src/connectivity_manager/mod.rs
- network/framework/src/connectivity_manager/test.rs
- network/framework/src/counters.rs
- network/framework/src/lib.rs
- network/framework/src/peer/mod.rs
- network/framework/src/peer/test.rs
- network/framework/src/peer_manager/mod.rs
- network/framework/src/peer_manager/senders.rs
- network/framework/src/peer_manager/tests.rs
- network/framework/src/peer_manager/types.rs
- network/framework/src/protocols/health_checker/interface.rs
- network/framework/src/protocols/health_checker/mod.rs
- network/framework/src/protocols/health_checker/test.rs
- network/framework/src/protocols/network/mod.rs
This PR adds two simple metrics to the network code, tracking: (i) the number of peer dials; and (ii) the number of peer disconnects (including disconnect reason). I've also gone through and updated the various disconnect reasons so that it is easier to reason about.
Existing test infrastructure and manual verification, i.e., I hacked the code so that it would force network health check disconnects. You can see the run [here](https://grafana.aptoslabs.com/d/overview/overview?orgId=1&refresh=10s&var-Datasource=VictoriaMetrics%20Global%20%28Non-mainnet%29&var-BigQuery=Google%20BigQuery&var-namespace=forge-e2e-pr-15174&var-metrics_source=All&var-chain_name=forge-0&from=1730759704000&to=1730760451000), and the network metrics [showing](https://grafana.aptoslabs.com/d/network/network?from=2024- …
> [Network] Add metrics for connection operations.

- aptos-move/aptos-vm/README.md
Fixes #14606. We had some really ugly/old docs for AptosVM, quickly updated.
> [docs] Update AptosVM readme

- crates/aptos-rosetta/src/account.rs
This cleans up and ensures that Rosetta only returns either the base account balances, the staking balances, or the delegated staking balances.  It will never return all three at the same time.
Tested against existing accounts on mainnet with a local version.  Prior version would return the account's balance and stake together, when requesting stake.
Now it only returns the balance
```bash
curl -s -X POST http://localhost:8082/account/balance -H 'Content-Type: application/json' -d '{ "network_identifier": { "blockchain": "aptos", "network": "mainnet" }, "account_identifier": { "address": "75d9ef170a1e8c4215084da639d626d75dfd8a6405e91928261160ed66aa748e", "sub_account": {"address":"stake" }}, "metadata": {} }' | jq
{
"index": 249813200,
"hash": "mainnet-249813200"
}, …
```
> [rosetta] Fix staking balances

- ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
- storage/indexer/src/indexer_reader.rs
- types/src/indexer/indexer_db_reader.rs
In this PR, fullnode will serve data based on the ledger and table info versions. With this change, the API result would be consistent since ledger db and table info are consistent for requested version. 
* Tested in forge and looks good: processing is tightly bounded by fullnode version.
> [indexer grpc] Improve the read consistency for fullnode GRPC. 

- Cargo.lock
- storage/aptosdb/Cargo.toml
- storage/aptosdb/src/backup/restore_utils.rs
- storage/aptosdb/src/backup/test.rs
- storage/aptosdb/src/db/aptosdb_test.rs
- storage/aptosdb/src/db/fake_aptosdb.rs
- storage/aptosdb/src/db/include/aptosdb_reader.rs
- storage/aptosdb/src/db/include/aptosdb_testonly.rs
- storage/aptosdb/src/db/include/aptosdb_writer.rs
- storage/aptosdb/src/db/mod.rs
- storage/aptosdb/src/db/test_helper.rs
- storage/aptosdb/src/db_debugger/truncate/mod.rs
- storage/aptosdb/src/ledger_db/ledger_metadata_db.rs
- storage/aptosdb/src/state_store/buffered_state.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/backup/backup-cli/src/utils/test_utils.rs
- storage/storage-interface/src/state_delta.rs
Move the part which need to be read out, so that the read path is not blocked by buffered state back pressure or sync commits.
Also the pre commited version is now in the same lock of the latest state, eliminating some edge cases.
> Stop locking BufferedState for read

- config/src/config/consensus_config.rs
Both forge realistic env and mainnet get around 5 blocks/s so a target of 200 ms seems reasonable. Reducing the target should help latency at higher loads.
Forge tests, in particular realistic_env_fairness_workload_sweep
> Execution backpressure: reduce target 250 -> 200ms

- testsuite/forge/src/backend/k8s/node.rs
Increase the startup timeout for nodes during Forge tests. Pods sometimes take longer to startup when they get rescheduled to a different node and attach a pvc. Also added a separate check for pod status that could help us distinguish between infra errors vs other issues
https://github.com/aptos-labs/aptos-core/actions/runs/11750653293
> increase forge node startup timeout

- aptos-move/aptos-gas-schedule/src/gas_schedule/move_stdlib.rs
- aptos-move/aptos-native-interface/src/context.rs
- aptos-move/framework/move-stdlib/src/natives/cmp.rs
- aptos-move/framework/move-stdlib/src/natives/mod.rs
- third_party/move/move-vm/types/src/values/values_impl.rs
Implement generic comparison operator for any move type. 
This enables writing generic methods that require comparison - for example binary_search on a vector.
Since move doesn't have signed integers, comparison return value is not intuitive (increased by 1 from usual -1, 0, 1), and so is wrapped into Ordering struct - so users don't need to think about it (with move 2, calling those will be pretty intuitive)
Provided unit tests
> [move] Implement generic comparison method in move cmp::compare

- Cargo.lock
- aptos-move/aptos-gas-schedule/src/gas_schedule/move_stdlib.rs
- aptos-move/aptos-gas-schedule/src/ver.rs
- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/aptos-vm-environment/src/natives.rs
- aptos-move/framework/move-stdlib/Cargo.toml
- aptos-move/framework/move-stdlib/doc/vector.md
- aptos-move/framework/move-stdlib/sources/vector.move
- aptos-move/framework/move-stdlib/src/natives/mod.rs
- aptos-move/framework/move-stdlib/src/natives/vector.rs
- aptos-move/framework/move-stdlib/tests/vector_tests.move
- third_party/move/move-vm/types/src/values/values_impl.rs
- types/src/on_chain_config/aptos_features.rs
Memcopy (i.e. `ptr::copy_nonoverlapping` inside of `Vec`) is extremely efficient, and using Vec operations that use it directly is significantly faster (orders of magnitude on bigger vectors) than issuing operations in move.
Operations on `vector` that can be speed-up: `insert`, `remove`, `append`, `split_off`.
To keep amount of native functions short, instead of having native for each of those, providing one more general native function: `vector::move_range`, which is enough to support all 4 of the above, in addition to other uses. 
Internally, we shortcircuit a few special cases, for faster speed.
Full performance evaluation is in the follow-up PR: #14862
> [move-stdlib] Add vector::move_range native function

- aptos-move/block-executor/src/code_cache.rs
- aptos-move/block-executor/src/executor.rs
- third_party/move/move-vm/runtime/src/storage/environment.rs
- third_party/move/move-vm/runtime/src/storage/implementations/unsync_module_storage.rs
Before, when deserializing bytes into compiled module, runtime environment also returned size and hash. These were not needed because module cache has an "extension" just for that.
> [loader-v2] Remove extra hash calculation from runtime environment

- Cargo.lock
- aptos-move/aptos-gas-schedule/src/gas_schedule/move_stdlib.rs
- aptos-move/e2e-move-tests/src/tests/transaction_context.data/pack/sources/transaction_context_test.move
- aptos-move/framework/move-stdlib/Cargo.toml
- aptos-move/framework/move-stdlib/doc/bcs.md
- aptos-move/framework/move-stdlib/sources/bcs.move
- aptos-move/framework/move-stdlib/src/natives/bcs.rs
- aptos-move/framework/move-stdlib/tests/bcs_tests.move
- third_party/move/move-vm/types/src/value_serde.rs
- types/src/on_chain_config/aptos_features.rs
It is sometimes useful to know if type has constants serialized size, and for example perform some optimization based on it. 
provided unit tests
> [move-stdlib] Implement bcs::constant_serialized_size<T>(): Option<u64>

- config/src/config/consensus_config.rs
- config/src/config/consensus_observer_config.rs
- consensus/consensus-types/src/pipelined_block.rs
- consensus/src/block_storage/block_store.rs
- consensus/src/block_storage/block_tree.rs
- consensus/src/consensus_observer/observer/active_state.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
- consensus/src/consensus_observer/observer/ordered_blocks.rs
- consensus/src/epoch_manager.rs
- consensus/src/pipeline/buffer_manager.rs
- consensus/src/pipeline/execution_client.rs
- consensus/src/pipeline/execution_schedule_phase.rs
- consensus/src/pipeline/mod.rs
- consensus/src/pipeline/persisting_phase.rs
- consensus/src/pipeline/pipeline_builder.rs
- consensus/src/pipeline/signing_phase.rs
- consensus/src/pipeline/tests/signing_phase_tests.rs
- consensus/src/round_manager_fuzzing.rs
- consensus/src/round_manager_test.rs
- consensus/src/state_computer.rs
- consensus/src/test_utils/mock_execution_client.rs
- consensus/src/test_utils/mod.rs
- consensus/src/twins/twins_node.rs
This pr integrates the pipeline framework from https://github.com/aptos-labs/aptos-core/pull/15145 to existing code, and use a local config to gate it.
> [pipeline] integration

- aptos-move/aptos-gas-schedule/src/gas_schedule/move_stdlib.rs
- aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/mem.move
- aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib_incompat/sources/mem.move
- aptos-move/framework/move-stdlib/doc/mem.md
- aptos-move/framework/move-stdlib/doc/overview.md
- aptos-move/framework/move-stdlib/doc/vector.md
- aptos-move/framework/move-stdlib/sources/mem.move
- aptos-move/framework/move-stdlib/sources/vector.move
- aptos-move/framework/move-stdlib/src/natives/mem.rs
- aptos-move/framework/move-stdlib/src/natives/mod.rs
- aptos-move/framework/move-stdlib/tests/mem_tests.move
- execution/executor/tests/internal_indexer_test.rs
- third_party/move/move-vm/types/src/values/value_tests.rs
- third_party/move/move-vm/types/src/values/values_impl.rs
If we have a field that contains non-copyable type, it is impossible to change it, and get the old value back. 
Adding two methods:
* native mem::swap, that implements swap of contents of two mutable references
* mem::replace, as a simple wrapper based on mem::swap 
provided unit tests
> [move][stdlib] Implement mem::swap native move call

- crates/aptos/src/common/types.rs
After this change: https://github.com/aptos-labs/aptos-core/pull/14876, version 7 was the default bytecode version emitted by compiler v2, but the CLI doc in `aptos move compile --help` said otherwise.
This PR fixes the CLI doc.
Existing tests and manual.
> [cli] Correct the help doc displayed for bytecode version

- .github/actions/move-tests-compiler-v2/action.yaml
This PR adds execution of the script `move_pr.sh -2` to CI. 
close #13750 
1) need to check updated docs and exp files;
2) whether the script execution is flaky.
> [Compiler-v2] run `move_pr.sh -2` in CI

- Cargo.lock
- consensus/src/lib.rs
- consensus/src/transaction_shuffler/mod.rs
- consensus/src/transaction_shuffler/use_case_aware/mod.rs
- testsuite/fuzzer/fuzz.sh
- testsuite/fuzzer/fuzz/Cargo.toml
- testsuite/fuzzer/fuzz/fuzz_targets/use_case_aware_shuffler.rs
Adds a fuzzer for use case aware shuffler.
`./fuzz.sh run use_case_aware_shuffler` works
Is it okay to change the module and struct visibility or should I gate it for `"fuzzer"` feature as well?
> [Fuzzing] Add use case aware shuffler fuzzer

- .github/actions/buildx-setup/action.yml
- docker/builder/docker-bake-rust-all.hcl
Apparently, [according to this blog](https://depot.dev/blog/building-images-gzip-vs-zstd), using zstd compression can provide better compression/decompression times for docker image, speeding up both image build times and container start times. 
Also, upgrades the docker setup action to use latest version of docker.
> [docker] use zstd compression and upgrade action

- .config/nextest.toml
This PR increases the `threads-required` nextest [configuration](https://nexte.st/docs/configuration/threads-required/) to reduce the number of rust unit tests running in parallel for CI/CD. We've recently seen cases where simple tests (e.g., without locks, multi-threading, tokio, etc.) have hit the time out (despite usually completing in 1-2 seconds).
From some quick experimentation, it appears that the tests are just not being given enough time to actually run by the OS (i.e., resources are saturated, so the tests do not complete before the test runner terminates them). By reducing the concurrency, we're hoping to see these timeouts disappear. 
Existing test infrastructure and (some) manual verification (i.e., I did a few manual rust unit test runs and couldn't reproduce the timeouts).
> [CI] Increase `threads-required` to reduce saturation.

- RELEASE.md
- RUST_CODING_STYLE.md
- aptos-move/framework/aptos-stdlib/doc/from_bcs.md
- ecosystem/indexer-grpc/release_notes.md
- terraform/helm/aptos-node/README.md.gotmpl
**Description**
This pull request addresses several spelling and grammatical issues across the codebase. These changes help improve code clarity and reduce the likelihood of confusion for contributors and users. Specifically, the following corrections were made:
"stablized" → "stabilized"
"xclippy" → "clippy"
"offerred" → "offered"
"respone" → "response"
"valdiator" → "validator"
These fixes were primarily applied in variable names, comments, and documentation.
No new dependencies were introduced as part of these changes.
**How Has This Been Tested?**
The changes do not affect functionality but improve code readability. As a result, no new tests were needed.
All existing unit and integration tests were run to ensure the correctness of the system.
**Key Areas to Review**
**Which Components …
> fix: typos in documentation files

- aptos-move/framework/aptos-framework/doc/stake.md
- aptos-move/framework/aptos-framework/sources/stake.move
More actionable error message when a txn is aborted due to in-progress async reconfig.
n/a
n/a
> reconfig in progress errmsg

- aptos-move/vm-genesis/src/lib.rs
- crates/aptos-genesis/src/builder.rs
- crates/aptos-genesis/src/config.rs
- crates/aptos-genesis/src/lib.rs
- crates/aptos-genesis/src/mainnet.rs
- crates/aptos/src/genesis/mod.rs
- crates/transaction-emitter-lib/src/emitter/local_account_generator.rs
- crates/transaction-emitter-lib/src/emitter/mod.rs
- crates/transaction-emitter-lib/src/wrappers.rs
- crates/transaction-emitter/src/diag.rs
- execution/executor-benchmark/src/account_generator.rs
- execution/executor-benchmark/src/db_generator.rs
- execution/executor-benchmark/src/lib.rs
- execution/executor-benchmark/src/main.rs
- execution/executor-benchmark/src/transaction_generator.rs
- sdk/Cargo.toml
- sdk/src/types.rs
- testsuite/smoke-test/src/keyless.rs
- testsuite/smoke-test/src/txn_emitter.rs
- testsuite/testcases/src/lib.rs
- types/src/jwks/patch/mod.rs
- types/src/jwks/rsa/insecure_test_jwk.json
- types/src/keyless/bn254_circom.rs
- types/src/keyless/circuit_constants.rs
- types/src/keyless/circuit_testcases.rs
- types/src/keyless/configuration.rs
- types/src/keyless/mod.rs
- types/src/keyless/test_utils.rs
- Add new genesis parameter `initial_jwks`.
- Add new genesis parameter `keyless_groth16_vk_override`.
- Add new `executor-benchmark` parameter `--use-keyless-accounts` for enabling **keyless mode**: all local accounts will be keyless accounts instead of Ed25519 accounts.
- Introduced to bench keyless latency/TPS.
- If `executor-benchmark` runs in **keyless mode**, also run genesis with groth16 keys from simulation.
Bench example.
```
/// step 1, create DB
cargo run -p aptos-executor-benchmark -- \
--enable-storage-sharding \
--block-executor-type aptos-vm-with-block-stm \
--use-keyless-accounts \ #NEW!
create-db --data-dir /tmp/db2 --num-accounts 100
/// step 2, actual bench
cargo run -p aptos-executor-benchmark -- \
--block-size 100 \
--enable-storage-sharding \
--block-executor-type …
```
> exebench for keyless

- Cargo.lock
- aptos-move/aptos-release-builder/Cargo.toml
- aptos-move/aptos-release-builder/src/main.rs
- aptos-move/aptos-release-builder/src/simulate.rs
This enhances the governance proposal simulation tool by adding the following features:
1. Gas usage display
2. Option to generate gas profiling reports (enabled with the `--profile-gas` flag)
Without `--profile-gas`
```
Executing governance scripts...
0-gas-schedule.move
Gas used: 215
Success
1-move-stdlib.move
Gas used: 471
Success
2-aptos-stdlib.move
Gas used: 1669
Success
3-aptos-framework.move
Gas used: 4393
Success
4-aptos-token.move
Gas used: 144
Success
5-aptos-token-objects.move
Gas used: 151
Success
All scripts succeeded!
All proposals succeeded!
```
With `profile-gas`
```
Executing governance scripts...
0-gas-schedule.move
Gas report saved to output/sources/TBD/proposal_1_upgrade_framework/gas-profiling/0-gas-schedule
Gas used: 215
Success
1-move-stdlib.move
Gas report saved to …
```
> [release builder] gov proposal simulation: show gas usage + add gas profiling support

- crates/aptos/CHANGELOG.md
- crates/aptos/src/move_tool/bytecode.rs
This PR adds option `--print-metadata-only` to `aptos move decompile` and `aptos move disassemble` to print out the metadata attached to the bytecode.
Here is an example output:
```
Metadata: {
"aptos_metadata": {
"error_map": {
"0": {
"code_name": "ED25519_SCHEME",
"code_description": "Scheme identifier for Ed25519 signatures used to derive authentication keys for Ed25519 public keys."
},
"1": {
"code_name": "EACCOUNT_ALREADY_EXISTS",
"code_description": "Account already exists"
},
"2": {
"code_name": "EACCOUNT_DOES_NOT_EXIST",
"code_description": "Account does not exist"
},
"3": {
"code_name": "ESEQUENCE_NUMBER_TOO_BIG",
"code_description": "Sequence number exceeds the maximum value for a u64"
},
"4": {
"code_name": "EMALFORMED_AUTHENTICATION_KEY",
"code_description": "The provided …
```
> [CLI] add option to `aptos move decompile` and `aptos move disassemble` to  print out metadata attached to the bytecode

- aptos-move/e2e-move-tests/src/lib.rs
- third_party/move/move-model/src/metadata.rs
- third_party/move/scripts/move_pr.sh
Add `MOVE_LANGUAGE_V2=true` for compiler v2 integration tests to allow V2 language features to be implemented in aptos-framework
existing tests
> [CI][Compiler-v2] add `MOVE_LANGUAGE_V2=true` to move_pr.sh

- consensus/src/quorum_store/batch_proof_queue.rs
> [qs] remove assertion on timestamp

- third_party/move/move-compiler-v2/src/plan_builder.rs
- third_party/move/move-compiler-v2/tests/unit_test/test/other_failures_invalid_location.exp
- third_party/move/move-compiler-v2/tests/unit_test/test/other_failures_invalid_location.move
This PR closes #14635 by fixing how `location` is parsed in the attribute for move unit tests.
> [Compiler-v2] Fix parsing of `location` in plan_builder of compiler v2

- Cargo.lock
- crates/aptos-drop-helper/Cargo.toml
- crates/aptos-drop-helper/src/async_concurrent_dropper.rs
- crates/aptos-drop-helper/src/lib.rs
When droping is slow and `DropHelper`s are nested, `AsyncConcurrentDropper::schedule_drop()` can deadlock on `self.num_tasks_tracker.inc();`
added unit test, verified failing before fix
> fix deadlock on nested DropHelper

- Cargo.lock
- crates/aptos-drop-helper/Cargo.toml
- crates/aptos-drop-helper/src/async_concurrent_dropper.rs
- crates/aptos-drop-helper/src/lib.rs
- third_party/move/testing-infra/transactional-test-runner/src/vm_test_harness.rs
cherry-pick https://github.com/aptos-labs/aptos-core/pull/15322 to v1.23 release branch
> [cp 1.23] fix deadlock on nested DropHelper

- config/src/config/consensus_observer_config.rs
- consensus/src/consensus_observer/common/error.rs
- consensus/src/consensus_observer/observer/fallback_manager.rs
This PR adds a simple fallback mechanism to consensus observer (CO) such that if the node starts to experience sync lag (i.e., fall behind), it'll fallback to state sync.
With this change, we now have two ways to fallback to state sync: (i) if no progress is made for some time (e.g., >10 seconds); or (ii) if the node is lagging behind the head of the chain (e.g., >15 seconds). In the future, we may make these limits more aggressive, but let's start here.
> [Consensus Observer] Add simple sync lag fallback

- aptos-move/block-executor/src/code_cache_global_manager.rs
- third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/storage/loader.rs
- third_party/move/move-vm/transactional-tests/tests/entry_points/script_too_few_type_args_inner.exp
- third_party/move/move-vm/transactional-tests/tests/entry_points/script_too_few_type_args_inner.v2_exp
- third_party/move/move-vm/transactional-tests/tests/entry_points/script_too_many_type_args_inner.exp
- third_party/move/move-vm/transactional-tests/tests/entry_points/script_too_many_type_args_inner.v2_exp
- third_party/move/move-vm/types/src/code/errors.rs
Addressing loader's TODOs:
- Switching from undefined to script location
- Keeping error remapping because the status code exists on-chain. It is probably fine t keep it as is.
- Removed useless TODO for alerts on concurrent manager uses.
- Changed `errors.rs` TODO  into a note, as it is not a P0/P1/P2 to fix.
Existing tests
> [loader-v2] Addressing simple loader V2 TODOs

- .github/actions/buildx-setup/action.yml
Reverts the buildx actions upgrade introduces in #15228. For the docker cache reuse to work properly, builder name should remain the same for all instantiations.
> revert buildx action version

- aptos-move/framework/aptos-framework/doc/function_info.md
- aptos-move/framework/aptos-framework/sources/function_info.move
The `new_function_info` used to be a `public(friend)` and this put lots of constraint on the builder.
N/A
We added the constraint previously because we thought it would be a safer constraint to only allow owner of the module to create function pointer value that points to the functions in a module. 
However, this is only creating developer burden and is not helping our safety at all because one can easily get around the constraint by wrapping the function call (this is safe because the called function has to be public anyway to create a function pointer) in a new module and publish this module under an address that they own.
> make create function info public

- consensus/src/pipeline/pipeline_builder.rs
- consensus/src/state_computer.rs
This prevents QS from GCing batches before they are actually committed.
> Move payload_manager.notify_commit to after commit

- config/src/config/consensus_config.rs
Reverts #15220 until execution pool is out.
> revert back backpressure change until execution pool

- consensus/src/block_storage/sync_manager.rs
- consensus/src/quorum_store/batch_store.rs
- consensus/src/quorum_store/quorum_store_builder.rs
- consensus/src/quorum_store/tests/batch_store_test.rs
- testsuite/forge-cli/src/suites/realistic_environment.rs
- In Quorum store, we garbage collect batches 60 seconds after they are expired based on block timestamp, to help slow peers fetch batches and execute without falling back to state sync.
- In consensus, peers will state sync if their local committed block timestamp is behind 30s from the remote committed block timestamp.
> [consensus] sync improvements to help slow nodes sync better

- config/src/config/consensus_config.rs
> [1.23] Temporarily loosen backpressures, until module loading improvement speeds up blocks

- aptos-move/framework/aptos-token-objects/doc/collection.md
- aptos-move/framework/aptos-token-objects/sources/collection.move
In `aptos-token-objects::collection`, the `set_description` and `set_uri` functions replace the data with the new value before emitting the event. This causes the Mutation V2 event to incorrectly emit the new value as the old value.
This update fixes the code to ensure the correct data is emitted.
Resolve https://github.com/aptos-labs/aptos-core/issues/15373.
> Fix Emitted Data for `aptos-token-objects::collection::Mutation` V2 Event

- crates/aptos/CHANGELOG.md
- crates/aptos/src/move_tool/mod.rs
For future Buildspace usage, we need to be able to provide an API key for the replay job to avoid server rate limiting.
For more context:
- https://www.notion.so/aptoslabs/Buildspace-Design-1278b846eb728055bf61e15c48a9b209?pvs=4#12e8b846eb728042af53f2e25f6719ed
- https://aptos-org.slack.com/archives/C06F3NBT1RP/p1731950102620299
- https://aptos-org.slack.com/archives/C05EJFD3E3S/p1732042568948249?thread_ts=1732040752.508009&cid=C05EJFD3E3S
```
cargo run --bin aptos move replay --help
--network <NETWORK>
The network to replay on.
Possible values: mainnet, testnet, <REST_ENDPOINT_URL>
--txn-id <TXN_ID>
The id of the transaction to replay. Also being referred to as "version" in some contexts
--benchmark
If this option is set, benchmark the transaction and report the running time(s) …
```
> Add a `--node-api-key` flag to the `aptos move replay` command to enable querying the full node using an API key

- third_party/move/move-compiler-v2/tests/eager-pushes/move_stdlib_reduced.exp
- third_party/move/move-compiler-v2/tests/eager-pushes/move_stdlib_reduced.move
Adds a test case to support the description in the issue: https://github.com/aptos-labs/aptos-core/issues/15339.
This test case was reduced from a function (`vector::reverse_append`) in move stdlib.
Test added.
> [compiler-v2] Test case reduced from move-stdlib showing opportunity for optimization

- aptos-move/aptos-vm-environment/src/environment.rs
- crates/aptos/src/node/mod.rs
- types/src/on_chain_config/mod.rs
- types/src/on_chain_config/timed_features.rs
Previously, timed feature flags activation time used millis as the unit, `last_reconfiguration_time` used micros as the unit, and these two were compared to see if timed feature flag was enabled (which was always true for any date on which blockchain has been around).
1. This PR fixes the above issue.
2. We also always enable `DisableInvariantViolationCheckInSwapLoc` (keeping the same semantics as before, but applying a minor fix).
3. We remove the replay override for `EntryCompatibility` (as there are transactions on mainnet before this feature was activated that fail the corresponding check).
- Existing tests
- Will be running replay-verify
- Added some new tests
> Fix units in timed feature flags

- third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs
- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs
- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/inefficient_loads.rs
- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/optimizers.rs
- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/reducible_pairs.rs
- third_party/move/move-compiler-v2/tests/reference-safety/v1-borrow-tests/writeref_borrow_invalid.old.exp
- third_party/move/move-ir-compiler/move-bytecode-source-map/src/source_map.rs
- third_party/move/move-prover/tests/sources/functional/aborts_if.v2_exp
- third_party/move/move-prover/tests/sources/functional/aborts_if_with_code.v2_exp
- third_party/move/move-prover/tests/sources/functional/bv_aborts.v2_exp
- third_party/move/move-prover/tests/sources/functional/choice.v2_exp
- third_party/move/move-prover/tests/sources/functional/emits.v2_exp
- third_party/move/move-prover/tests/sources/functional/enum.v2_exp
- third_party/move/move-prover/tests/sources/functional/enum_abort.v2_exp
- third_party/move/move-prover/tests/sources/functional/loop_unroll.v2_exp
- third_party/move/move-prover/tests/sources/functional/mono.v2_exp
- third_party/move/move-prover/tests/sources/functional/schema_exp.v2_exp
- third_party/move/move-prover/tests/sources/functional/verify_custom_table.v2_exp
- third_party/move/move-prover/tests/sources/functional/verify_table.v2_exp
- third_party/move/tools/move-unit-test/tests/test_sources/abort_location.exp
- third_party/move/tools/move-unit-test/tests/test_sources/abort_location.move
- third_party/move/tools/move-unit-test/tests/test_sources/abort_location.v2_exp
- third_party/move/tools/move-unit-test/tests/test_sources/native_signer_creation.v2_exp
- third_party/move/tools/move-unit-test/tests/test_sources/proposal_test.v2_exp
Fixes #14167.
Peephole optimization changes the original file format bytecode after it is generated from stackless bytecode. Source mapping is computed when the original file format bytecode is created, so the source mapping is incorrect after peephole optimization changes the file format bytecode.
This resulted in several downstream issues, including move test, prover, coverage, etc.
This PR contains the fix by having the peephole optimization maintain a mapping to the original offsets and propagating them, and updating the source map accordingly after the optimization.
- Existing tests
- Added another test reported by a user
- Manually tested the user's report before and after the fix (details below).
When we ran `aptos move test --move-2` for the following program:
```
module …
```
> Fixing source map locations when peephole optimizations are applied.

- aptos-move/framework/aptos-token/doc/token_event_store.md
- aptos-move/framework/aptos-token/sources/token_event_store.move
Corrected `CollectionMaxiumMutate` to `CollectionMaximumMutate` in `token_event_store.move`
> Fix the type in V2 event name:  Change `CollectionMaxiumMutate` to `CollectionMaximumMutate`

- mempool/src/shared_mempool/tasks.rs
- mempool/src/thread_pool.rs
- storage/storage-interface/src/state_store/sharded_state_updates.rs
We started to do this par_iter in the global pool instead of the "exe pool" here:
https://github.com/aptos-labs/aptos-core/pull/15184#discussion_r1861207119
and it triggered a deadlock like what we saw repeatedly before:
https://github.com/aptos-labs/aptos-core/pull/15068
To fix it and safe guard it, I am doing these two things in this PR:
1. move the mempool validation to its dedicated pool -- it's not ideal to wait on a lock in the global pool
2. move the par_iter back to the "exe pool"
it's not ideal that any rayon pool is involved in the "current_state" lock whose critical section was meant to be small. Won't be a issue any more once I change the representation of the state delta from hashmaps to layeredmaps.
> fix deadlock between the mempool and the db

- Cargo.lock
- consensus/Cargo.toml
- consensus/safety-rules/src/persistent_safety_storage.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
- consensus/src/epoch_manager.rs
- consensus/src/pipeline/execution_client.rs
- consensus/src/quorum_store/quorum_store_builder.rs
- consensus/src/test_utils/mock_execution_client.rs
consensus key rotation was updated in #13926 .
QS should have been updated accordingly.
existing tests.
n/a
> update qs key loading

- aptos-move/e2e-move-tests/src/tests/large_package_publishing.rs
- aptos-move/framework/src/chunked_publish.rs
- crates/aptos/CHANGELOG.md
- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/test/mod.rs
Updated the chunked publish mode in the CLI to include an option for configuring the chunk size.
This gives more flexibility since the chunked publish mode utilizes nearly the maximum payload size permitted for a single transaction. This change helps to handle failures when gas charges are updated.
* Added a new `chunk_size` option to `ChunkedPublishOption`
* Updated `MAX_CHUNK_SIZE_IN_BYTES` to be of type `&str` with a value of `55000`
* e2e-move-test
* manually building & testing the CLI
> [cli] Make chunk size configurable for chunked publish

- Cargo.lock
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
Bump CLI version to 4.6.0
* Add `--node-api-key` flag to `aptos move replay` to allow for querying the fullnode with an API key.
* Add `--chunk-size` flag to allow configuring chunk size for chunked publish mode.
* Lower the default chunk size for chunked publish mode (`CHUNK_SIZE_IN_BYTES`) from 60,000 to 55,000.
n/a
> [cli] Bump to 4.6.0

- ecosystem/nft-metadata-crawler/src/asset_uploader/throttler/mod.rs
> [NFT Metadata Crawler] Fix asset uploader throttler

- aptos-move/framework/aptos-framework/sources/account.move
This PR removes an unused line from the unit test `test_events` in the `account` module (`aptos-move/framework/aptos-framework/sources/account.move`):
`let eventhandle = &borrow_global<Account>(addr).coin_register_events;`
To generate the warning, create a module and bring the `account` module into scope. For example:
```
module 0x9000::test {
use aptos_framework::account;
}
```
now use `aptos move test`, the following warning could be seen:
```
warning[W09003]: unused assignment
┌─ /home/levi0804/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework/sources/account.move:1538:13
│
1538 │         let eventhandle = &borrow_global<Account>(addr).coin_register_events;
│             ^^^^^^^^^^^ Unused assignment or binding for local 'eventhandle'. …
```
> Resolve compiler warning by removing unused line

- execution/executor/src/block_executor/block_tree/mod.rs
- execution/executor/src/block_executor/block_tree/test.rs
- execution/executor/src/chunk_executor/chunk_commit_queue.rs
- execution/executor/src/db_bootstrapper/mod.rs
- execution/executor/src/tests/mod.rs
- execution/executor/src/workflow/mod.rs
- peer-monitoring-service/server/src/tests.rs
- state-sync/state-sync-driver/src/tests/mocks.rs
- state-sync/storage-service/server/src/tests/mock.rs
- storage/aptosdb/src/db/aptosdb_test.rs
- storage/aptosdb/src/db/fake_aptosdb.rs
- storage/aptosdb/src/db/include/aptosdb_reader.rs
- storage/aptosdb/src/db/mod.rs
- storage/backup/backup-cli/src/utils/test_utils.rs
- storage/db-tool/src/bootstrap.rs
- storage/storage-interface/src/ledger_summary.rs
- storage/storage-interface/src/lib.rs
> trivial: rename ExecutedTrees -> LedgerSummary

- api/src/transactions.rs
- api/types/src/move_types.rs
Updating serialization constant in the API
Existing tests
> Updating serialization constant in the API

- aptos-move/aptos-release-builder/data/collection-owner.yaml
As part of [AIP 95 collections permissions update](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-95.md), enable feature Collection Owner. This enables users to create collections as the collection owner. 
New functions added and tested.
> Enable Collection Owner feature

- consensus/consensus-types/src/pipelined_block.rs
- consensus/src/pipeline/execution_schedule_phase.rs
- consensus/src/pipeline/persisting_phase.rs
- consensus/src/pipeline/pipeline_builder.rs
The use case we have here is probably more suitable for a shared future with oneshot channel than a broadcast channel.
Broadcast channel has a property of dropping values if exceeds the capacity and receiver will see a RecvError::Lagged error. Using oneshot channel we can do exact once send easily and use shared future to share the result to multiple subscribers.
> [pipeline] switch from broadcast channel to shared future

- .github/workflows/provision-replay-verify-archive-disks.yaml
- .github/workflows/replay-verify-on-archive.yaml
- .github/workflows/workflow-run-replay-verify-archive-storage-provision.yaml
- .github/workflows/workflow-run-replay-verify-on-archive.yaml
- testsuite/replay-verify/main.py
> remove the branch ref to default to github.ref

- testsuite/replay-verify/archive_disk_utils.py
- testsuite/replay-verify/main.py
1. use single region snapshot
2. remove repair disk after use
run `python archive_disk_utils.py --network mainnet`
snapshot here are updated to single region https://console.cloud.google.com/compute/snapshots?inv=1&invt=AbjKqg&project=aptos-devinfra-0
> reduce cost

- aptos-move/script-composer/src/builder.rs
- aptos-move/script-composer/src/tests/mod.rs
- aptos-move/script-composer/src/tests/test_modules/sources/test.move
Fixes two issues for the script composer:
1. The current code handled call convention incorrectly. The returned values are stored in the reverse order.
2. Infer the operation type for copyable and droppable values, so that caller wouldn't need to distinguish between copy and move for those primitive values.
Added three test cases:
1. Created a function to return two values and make sure it can be stored properly.
2. Created a transaction that invokes a function that returned a copyable and droppable value, and use the destructor twice. This can be built properly (positive case)
3. Created a transaction that invokes a function that returned a droppable but not copyable value, and use the destructor twice. Builder will complain on this case (negative case)
Whether we tested the two features …
> [script-composer] Add infer functionality, fix multiple return values

- consensus/src/quorum_store/batch_store.rs
- consensus/src/quorum_store/quorum_store_builder.rs
- consensus/src/quorum_store/tests/batch_proof_queue_test.rs
- consensus/src/quorum_store/tests/batch_store_test.rs
- [qs] Use expiration buffer to cleanup during bootstrap
Fix a bug from https://github.com/aptos-labs/aptos-core/pull/15364 where the batches were not cleanup respecting the expiration buffer during bootstrap.
- [qs] async gc old epoch batches from batch store
With https://github.com/aptos-labs/aptos-core/pull/15364, doubling cache duration in batch store means bootstrap time during epoch changes is now doubled because all the batches now need to be read from storage. To avoid this, this PR introduces a separate path for epoch changes vs restarts. During epoch change, the old batches from storage are deleted asynchronously. At restarts, the batches are still cleaned up synchronously.
- [qs] monitor! create batch store
> [qs] batch store bootstrap perf improvements

- testsuite/forge-cli/src/suites/realistic_environment.rs
- testsuite/forge/src/config.rs
Increasing memory thresholds to accommodate #15364
> [forge] update memory thresholds for Forge stable

- ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_mainnet_txns/1806220919_object_untransferable.json
- ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml
> untransferable test txn

- ecosystem/indexer-grpc/indexer-test-transactions/build.rs
add devnet repo to generate_transactions.rs
> add devnet test txns

- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/sources/coin.move
- aptos-move/framework/aptos-framework/sources/coin.spec.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.spec.move
1. Will not create PFS when register account. Deposit will create that automatically.
2. Get rid of unnecessary `MigrationFlag`.
ut
> [FA] get rid of migration flag

- storage/aptosdb/src/db_debugger/validation.rs
- storage/aptosdb/src/db_options.rs
- storage/aptosdb/src/ledger_db/mod.rs
- storage/aptosdb/src/state_kv_db.rs
- storage/aptosdb/src/state_merkle_db.rs
> [Storage] Open db in parallel when storage sharding is enabled.

- .github/workflows/provision-replay-verify-archive-disks.yaml
- .github/workflows/replay-verify-on-archive.yaml
- .github/workflows/workflow-run-replay-verify-on-archive.yaml
- testsuite/replay-verify/archive_disk_utils.py
- testsuite/replay-verify/main.py
- testsuite/replay-verify/poetry.lock
- testsuite/replay-verify/pyproject.toml
- testsuite/replay-verify/xfs-disk-repair.yaml
1. switch to night to run main replay verify and provision. 
2. add validation for end range in case user enter a range that we cannot replay
3. use correct argument for image tag
local tested
> update schedule and add input checking for replay-verify on archive

- crates/aptos/CHANGELOG.md
- crates/aptos/src/common/types.rs
When defining `deserialize_with`, if the field is missing, it will throw an error. By adding a default we are able to default it to `Option::None`
Any edge cases with invalid or missing fields
> [cli] Fix private key field being required

- crates/aptos-inspection-service/src/server/index.rs
- crates/aptos-inspection-service/src/server/metrics.rs
- crates/aptos-inspection-service/src/server/mod.rs
- state-sync/state-sync-driver/src/driver.rs
- state-sync/state-sync-driver/src/metrics.rs
This PR adds a simple consensus health check endpoint to the node inspection service. Specifically, the new endpoint `/consensus_health_check` will return a 200 status code iff the node is currently executing consensus.
To achieve this, I added a new metric gauge that is set iff consensus is executing on the validator node. The inspection service simply fetches the value of this gauge. The gauge can be seen [here](https://grafana.aptoslabs.com/d/ddphlx0p7mxvka/consensus-observer?from=2024-12-05T19:41:59.000Z&to=2024-12-05T19:54:13.000Z&var-Datasource=fHo-R604z&var-BigQuery=axNEitxVz&var-metrics_source=$__all&var-chain_name=forge-0&var-cluster=$__all&var-namespace=forge-e2e-pr-15512&var-kubernetes_pod_name=$__all&var-interval=$__auto&var-role=$__all&var-Filters=&viewPanel=panel-226). …
> [Inspection Service] Add simple consensus health check endpoint.

- Cargo.lock
- Cargo.toml
- crates/aptos-faucet/configs/testing_redis.yaml
- crates/aptos-faucet/configs/testing_redis_minter_local.yaml
- crates/aptos-faucet/core/Cargo.toml
- crates/aptos-faucet/core/src/bypasser/auth_token.rs
- crates/aptos-faucet/core/src/checkers/auth_token.rs
- crates/aptos-faucet/core/src/checkers/memory_ratelimit.rs
- crates/aptos-faucet/core/src/checkers/redis_ratelimit.rs
- crates/aptos-faucet/core/src/endpoints/errors.rs
- crates/aptos-faucet/core/src/endpoints/fund.rs
- crates/aptos-faucet/core/src/firebase_jwt.rs
- crates/aptos-faucet/core/src/lib.rs
- crates/aptos-faucet/core/src/server/run.rs
- crates/aptos-faucet/integration-tests/main.py
This PR supports configuring the Redis ratelimiter to ratelimit by either IP or JWT.
I asked @geekflyer to transfer the firebase-token fork to aptos-labs, I'll use that once it's done.
Run a localnet:
```
aptos node run-localnet --no-faucet
```
Run Redis:
```
redis-server
```
Run the faucet:
```
cargo run -p aptos-faucet-service -- run -c ~/faucet.yaml
```
The config looks like this:
```
---
server_config:
api_path_base: ""
listen_port: 8092
metrics_server_config: {}
bypasser_configs:
- type: "AuthToken"
file: "/tmp/bypass-auth-tokens.txt"
checker_configs:
- type: "RedisRatelimit"
database_address: localhost
max_requests_per_day: 5
ratelimit_key_provider_config:
type: "Jwt"
identity_platform_gcp_project: <redacted>
funder_config:
type: "MintFunder"
node_url: "http://127.0.0.1:8080" …
```
> [Faucet] Support ratelimiting on Firebase JWT

- testsuite/forge-test-runner-template.yaml
- testsuite/forge/src/backend/k8s/helm-values/aptos-node-default-values.yaml
Add annotation to prevent the runner itself, as well as the validator and validator fullnode pods from being evicted by the cluster autoscaler.
Make sure the Forge tests pass, and check the GHA logs that the added annotation is being used.
> Forge: mark pods as non-evictable

- aptos-move/e2e-move-tests/src/tests/vote.data/enable_partial_governance_voting/sources/main.move
- aptos-move/e2e-move-tests/src/tests/vote.rs
- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- types/src/on_chain_config/aptos_features.rs
The feature flag `partial_governance_voting` has been successfully enabled on both the testnet and mainnet. However, it is not part of the default feature set for devnet.
Including this feature in the default feature set causes many Move unit tests to fail, as they were not written to accommodate the feature. The affected unit tests have been updated accordingly.
Partially resolves https://github.com/aptos-labs/aptos-core/issues/15305.
Move unit tests
Unit test updates
> Enable partial_governance_voting

- aptos-move/framework/aptos-framework/sources/delegation_pool.move
- types/src/on_chain_config/aptos_features.rs
The feature flag `delegation_pool_partial_governance_voting` has been successfully enabled on both the testnet and mainnet. However, it is not part of the default feature set for devnet.
Including this feature in the default feature set causes many Move unit tests to fail, as they were not written to accommodate the feature. The affected unit tests have been updated accordingly, and a new test case has been added to test the behavior of the feature enabled.
Partially resolves https://github.com/aptos-labs/aptos-core/issues/15305.
Move Unit Test
> Enable delegation_pool_partial_governance_voting by default

- consensus/consensus-types/src/pipelined_block.rs
- consensus/src/block_storage/block_store.rs
- consensus/src/counters.rs
- consensus/src/lib.rs
- consensus/src/pipeline/pipeline_builder.rs
> [pipeline] fixes and counters

- crates/aptos/CHANGELOG.md
- crates/aptos/src/move_tool/bytecode.rs
Since the bytecode version default is v7, Revela cannot be used at all anymore. This PR attempts to downgrade to v6 before calling Revela, if possible. This allows to continue to work with Revela until the new decompiler is available.
Manually
> [decompiler] Downgrade to bytecode v6 for Revela

- aptos-move/framework/aptos-framework/doc/object.md
- aptos-move/framework/aptos-framework/sources/object.move
ensure `ObjectCore` exists before short-circuit
> ensure ObjectCore exists before short-circuit

- Cargo.lock
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
Bump CLI to 5.1.0.
We will run the workflow after all the fixes/features are in `main` (some of those PRs are still waiting for approvals).
> [cli] Bump to 5.1.0

- scripts/dev_setup.sh
Not able to release CLI: https://github.com/aptos-labs/aptos-core/actions/runs/12335989799, because the current rust version 1.78.0 is not supported by the nextest version installed.
> Fix cargo nextest version

- third_party/move/move-model/src/model.rs
- third_party/move/move-prover/boogie-backend/src/spec_translator.rs
- third_party/move/move-prover/bytecode-pipeline/src/verification_analysis.rs
- third_party/move/move-prover/bytecode-pipeline/src/verification_analysis_v2.rs
- third_party/move/move-prover/tests/sources/functional/type_reflection.move
- third_party/move/tools/move-cli/src/base/prove.rs
When calling a generic function in a specification expression which transitively uses type reflection, the function call type instantiation wasn't correctly treated for the type info parameters. The refined test generates this situation and failed before but passes now.
Removes the boogie compilation error in #15605, but after this the example in this bug times out, even though the package does not contain any specs. I verified that all verification conditions belong to functions in this package, but this does not change this. Should be fixed in subsequent PR before closing the bug.
New test variant
> [move-prover] Fix a bug in treatment of type reflection in spec funs

- .github/workflows/forge-stable.yaml
Updates the forge-stable workflow schedule to run Monday through Friday at 22:00 UTC instead of only running on Sunday, Tuesday, and Thursday.
This change only modifies the GitHub Actions workflow schedule configuration. The functionality of the forge tests remains unchanged.
I will schedule from this PR to ensure that the cron spec is valid
The cron expression syntax: `0 22 * * 1-5` represents:
- Minutes: 0
- Hour: 22 (UTC)
- Day of month: *
- Month: *
- Day of week: 1-5 (Monday through Friday)
> [forge] Run forge nightly on weekdays

- crates/transaction-emitter-lib/src/emitter/submission_worker.rs
> Fix txn-emitter precission of worker sleeping

- aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
Reverts aptos-labs/aptos-core#15352
We don't need this anymore because of Vineeth's effort for optimization
> Revert "Bumping up the max transaction execution gas limit for gov proposals"

- aptos-move/framework/aptos-stdlib/doc/big_vector.md
- aptos-move/framework/move-stdlib/doc/vector.md
- aptos-move/framework/move-stdlib/sources/mem.move
- aptos-move/framework/move-stdlib/sources/vector.move
- third_party/move/move-model/src/lib.rs
> Optimizing vector::replace and compiler-v2 vector depenency fix 

- protos/scripts/install_deps.sh
The check protos CI is broken right now because of this error:
```
error: failed to compile `protoc-gen-prost-crate v0.3.1`, intermediate artifacts can be found at `/tmp/cargo-installm2VsXb`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
rustc 1.78.0 is not supported by the following package:
home@0.5.11 requires rustc 1.81
```
Locking the deps and the version fixes this. We were only locking the version.
See that CI passes now: https://github.com/aptos-labs/aptos-core/actions/runs/12418518578/job/34671883427?pr=15638.
> Lock Rust deps for checking protos

- devtools/aptos-cargo-cli/src/lib.rs
Temporarily disables framework upgrade tests except for the release builder by commenting out most of the relevant file paths. This change reduces the scope of when framework upgrade tests are triggered.
The change is configuration-only and affects test triggering logic. The remaining enabled path for `aptos-move/aptos-release-builder` continues to function as expected.
- Verify that disabling these test paths aligns with current framework upgrade test issues
- Confirm that release builder tests remain properly triggered
- Consider if this should be a temporary or permanent change
> [forge] Disable framework upgrade tests except for release builder

- devtools/aptos-cargo-cli/src/lib.rs
This PR disables the framework upgrade tests due to failures that need to be debugged. Going forward, all PRs will skip the test and mark it as successful.
> [Devtools] Disable framework upgrade test

- third_party/move/move-compiler-v2/src/env_pipeline/ast_simplifier.rs
- third_party/move/move-compiler-v2/src/env_pipeline/inliner.rs
- third_party/move/move-compiler-v2/src/lib.rs
- third_party/move/move-compiler-v2/src/logging.rs
Output using the `debug!` logging facility should not stay permanent in the code, or at leastr be protected by an additional guard, unless it is useful to work with end users. The default output of `debug!` should overall be useful for users to help understand their problems and avoid complex internal data structures.
This updates some code in the compiler to follow this guideline, as well as refines the docs for logging to reflect this.
This came apparent when trying to use `aptos move prove -v debug` -- the output printed lots of stuff which is probably only relevant for internal debugging.
Existing tests
> [compiler-v2] Make `-v debug` output more concise

- devtools/aptos-cargo-cli/src/common.rs
This PR updates the comment for the merge-base commit delay. This is simply just to bump the latest commit on main.
> [Devtools] Update comment for merge-base commit delays.

- third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs
- third_party/move/move-model/src/builder/model_builder.rs
- third_party/move/move-model/src/model.rs
Fixes https://github.com/aptos-labs/aptos-core/issues/15618.
The transformation of `public(packge)` to `public(friend)` currently is only done for modules in the current package, but not the dependencies. This becomes an issue when the generated bytecode of dependencies is used, say in the case unit tests.
We fix this by also doing the transformation to the dependency modules. For dependencies, we cannot perform the transformation properly, as there is no way tell if two non-primary target modules are in the same package (see https://github.com/aptos-labs/aptos-core/issues/13745). So we may friend modules outside the current package. If a dependency contains `public(packge)` visibility violation, say  package A contains calls function in package B that calls a `public(package)` function …
> [Bugfix][Compiler-V2] Fix `public(package)` causing unit test errors

- aptos-move/framework/aptos-framework/doc/aptos_account.md
- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/doc/dispatchable_fungible_asset.md
- aptos-move/framework/aptos-framework/doc/fungible_asset.md
- aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
- aptos-move/framework/aptos-framework/doc/transaction_fee.md
- aptos-move/framework/aptos-framework/sources/aptos_account.move
- aptos-move/framework/aptos-framework/sources/aptos_account.spec.move
- aptos-move/framework/aptos-framework/sources/coin.move
- aptos-move/framework/aptos-framework/sources/dispatchable_fungible_asset.move
- aptos-move/framework/aptos-framework/sources/fungible_asset.move
- aptos-move/framework/aptos-framework/sources/primary_fungible_store.move
- aptos-move/framework/aptos-framework/sources/transaction_fee.move
- execution/executor-benchmark/src/native/native_vm.rs
- execution/executor-benchmark/src/native/parallel_uncoordinated_block_executor.rs
We don't emit event when burn APT coin, neither should APT FA.
Now each txn burn gas fee from APT FA, we see a withdraw event for this.
We first remove this event to facilitate the exchanges to recognize deposit.
simple refactoring.
> [FA] remove withdraw event when burn

- aptos-move/aptos-gas-schedule/bump_ver.py
This adds a python script that can be used to bump LATEST_GAS_FEATURE_VERSION. It will also create the next gas feature version entry if it does not exist.
Sample output (after running the script 3 times):
```
diff --git a/aptos-move/aptos-gas-schedule/src/ver.rs b/aptos-move/aptos-gas-schedule/src/ver.rs
index 2c5ec6d504..31924b94a4 100644
--- a/aptos-move/aptos-gas-schedule/src/ver.rs
+++ b/aptos-move/aptos-gas-schedule/src/ver.rs
@@ -69,7 +69,7 @@
///       global operations.
/// - V1
///   - TBA
-pub const LATEST_GAS_FEATURE_VERSION: u64 = gas_feature_versions::RELEASE_V1_22;
+pub const LATEST_GAS_FEATURE_VERSION: u64 = gas_feature_versions::RELEASE_V1_25;
pub mod gas_feature_versions {
pub const RELEASE_V1_8: u64 = 11;
@@ -89,4 +89,5 @@ pub mod gas_feature_versions {
pub const …
```
> [gas schedule] add script to bump gas feature version

- Cargo.lock
- aptos-move/aptos-workspace-server/Cargo.toml
- aptos-move/aptos-workspace-server/src/common.rs
- aptos-move/aptos-workspace-server/src/lib.rs
- aptos-move/aptos-workspace-server/src/main.rs
- aptos-move/aptos-workspace-server/src/services/docker_common.rs
- aptos-move/aptos-workspace-server/src/services/faucet.rs
- aptos-move/aptos-workspace-server/src/services/indexer_api.rs
- aptos-move/aptos-workspace-server/src/services/postgres.rs
- aptos-move/aptos-workspace-server/src/services/processors.rs
- crates/aptos/src/lib.rs
- crates/aptos/src/workspace/mod.rs
This PR implements several fixes and improvements to `aptos-workspace-server`:
- **Shared Docker Network**: 
- Instead of creating a new Docker network for each instance, we now use a shared network (aptos-workspace). 
- This helps avoid hitting Docker's default network limit (30 networks per host).
- **Error Propagation Fixes**: 
- Fixed issues with error propagation so we can know why services actually fail
- **Automatic Docker Image Pulling**: 
- Docker images are now automatically pulled if they do not already exist locally.
- **Shared Docker Client Initialization**:
- All docker operations now await a single shared future to initialize the Docker client, rather than creating separate instances.
- **Timeout**:
- Automatically initiates the shutdown sequence when a timeout is reached. …
> [aptos-workspace-server] various fixes and improvements

- Cargo.lock
- aptos-move/aptos-vm-environment/Cargo.toml
- aptos-move/aptos-vm-environment/src/environment.rs
- types/src/on_chain_config/mod.rs
Addresses another loader todo: equality tests for environment. When config changes, environment should be different. Note that gas hook, signer injection and delayed field enablement is not part of the comparison on purpose: the first 2 are used outside of block execution (2nd is deprecated actually), and 3rd is used for block executor only.
N/A
Ensure corner cases are covered
> [loader-v2] Additional environment tests

- .github/workflows/forge-stable.yaml
- testsuite/forge-cli/src/suites/realistic_environment.rs
- testsuite/forge-cli/src/suites/ungrouped.rs
> Add documentation to forge-stable test suite

- crates/aptos-rosetta/src/common.rs
- crates/aptos-rosetta/src/lib.rs
Adds USDC to default coins supported by Rosetta
Check that USDC testnet and USDC mainnet addresses are correct
> [rosetta] Add USDC

- storage/README.md
> Update the doc on internal indexer config

- aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/cmp.move
- aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib_incompat/sources/cmp.move
- aptos-move/framework/move-stdlib/doc/cmp.md
- aptos-move/framework/move-stdlib/doc/overview.md
- aptos-move/framework/move-stdlib/sources/cmp.move
- aptos-move/framework/move-stdlib/tests/bcs_tests.move
- execution/executor/tests/internal_indexer_test.rs
Separated out move part of the cmp::compare native call (first part is in the #14714), as it requires enums, and can only land after enums are enabled.
> [move] Implement generic comparison method in move - move part (cmp::compare)

- third_party/copy.bara.sky
This PR sets correct URLs, branches to sync `third-party/move` with `move-on-aptos`.
Created a PR in `move-on-aptos` with recent changes: https://github.com/move-language/move-on-aptos/pull/3
> [move] Change copybara to sync with move-on-aptos

- Cargo.lock
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/gas.rs
- aptos-move/aptos-vm/src/keyless_validation.rs
- aptos-move/aptos-vm/src/lib.rs
- aptos-move/aptos-vm/src/transaction_validation.rs
- aptos-move/block-executor/src/code_cache.rs
- third_party/move/move-vm/types/src/code/cache/module_cache.rs
- third_party/move/move-vm/types/src/code/errors.rs
- vm-validator/Cargo.toml
- vm-validator/src/mocks/mock_vm_validator.rs
- vm-validator/src/vm_validator.rs
This PR re-implements module caching logic for VM validator (mempool validation running prologues) to make it work correctly with module publishing and account abstraction (AA). Before, module cache was only updated on full reset (that is, epoch change), which means that:
- If new version of the code is published, the old one is still used until epoch change.
- If a new module is published that is also used by the prologue, it it not found until epoch change.
The later is a problem for AA because it is possible for the user to publish a module with some validation logic and custom prologue, and then use it within the same epoch (as a result, "module not found error" is returned). 
**Changes:**
VM validator now owns the*versioned* code cache explicitly. On every module read from the cache, …
> [validator] Changing module cache for VM validator

- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/storage/environment.rs
- third_party/move/move-vm/runtime/src/storage/mod.rs
- third_party/move/move-vm/runtime/src/storage/ty_tag_cache.rs
- third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
This PR moves type tag cache out of the other type cache because it is conceptually different: type tags can be cached speculatively, same as indexed struct names. As a result:
1. Type tag cache is implemented with tests and added to `RuntimeEnvironment`.
2. V2 loader uses a new `TypeTagBuilder` API to encapsulate conversions from types to tags. Under the hood, it uses a pseudo gas meter. Tests
3. V1 loader still uses the old path, so the code is versioned.
- Tests for type tag cache.
- Tests for tag metering.
> [move] Move out tag cache (safe speculation)

- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/sources/coin.move
The original event didn't have the coin type which made it very hard for indexing.  This replaces it.
> [framework] Replace coin store deletion event with coin type

- api/Makefile
- scripts/dev_setup.sh
- scripts/windows_dev_setup.ps1
Remove `schemathesis` from the fullnode API and dev_setup.sh. It doesn't look like we're using this. Also cleaned up some targets for api v0 from the Makefile
`make test`
> Remove `schemathesis` and clean up api `Makefile`

- aptos-move/framework/aptos-framework/doc/overview.md
- aptos-move/framework/aptos-framework/doc/permissioned_signer.md
- aptos-move/framework/aptos-framework/sources/create_signer.move
- aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.move
- aptos-move/framework/aptos-framework/sources/permissioned_signer.move
- aptos-move/framework/aptos-framework/sources/permissioned_signer.spec.move
- aptos-move/framework/aptos-framework/tests/compiler-v2-doc/permissioned_signer.md
- aptos-move/framework/aptos-framework/tests/permissioned_signer_tests.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- execution/executor/tests/internal_indexer_test.rs
Implemented aptos framework code for the permissioned signer.
Implemented tests to cover the entire lifecycle of a permission handle.
Whether the api is safe to use.
> create permissioned signer example

- aptos-move/framework/aptos-framework/doc/overview.md
- aptos-move/framework/aptos-framework/doc/permissioned_signer.md
- aptos-move/framework/aptos-framework/sources/create_signer.move
- aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.move
- aptos-move/framework/aptos-framework/sources/permissioned_signer.move
- aptos-move/framework/aptos-framework/sources/permissioned_signer.spec.move
- aptos-move/framework/aptos-framework/tests/compiler-v2-doc/permissioned_signer.md
- aptos-move/framework/aptos-framework/tests/permissioned_signer_tests.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- aptos-move/framework/src/natives/permissioned_signer.rs
- execution/executor/tests/internal_indexer_test.rs
Clone of #14469 due to rebase error
Implemented aptos framework code for the permissioned signer.
Implemented tests to cover the entire lifecycle of a permission handle.
Whether the api is safe to use.
> add permissioned signer move code

- aptos-move/e2e-move-tests/src/tests/move_feature_gating.rs
- aptos-move/framework/aptos-framework/doc/account.md
- aptos-move/framework/aptos-framework/doc/big_ordered_map.md
- aptos-move/framework/aptos-framework/doc/multisig_account.md
- aptos-move/framework/aptos-framework/doc/ordered_map.md
- aptos-move/framework/aptos-framework/doc/resource_account.md
- aptos-move/framework/aptos-framework/doc/staking_contract.md
- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/aptos-framework/sources/account.spec.move
- aptos-move/framework/aptos-framework/sources/multisig_account.spec.move
- aptos-move/framework/aptos-framework/sources/resource_account.spec.move
- aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
Adds permission checks to account operations in the Aptos Framework to restrict key rotation and signer capability management. This introduces a new `AccountPermission` type and associated functions to control access to privileged account operations.
Key changes:
- Added `check_signer_permission` function to verify permissions
- Added `grant_permission` function to authorize signers
- Added permission checks to all account rotation and capability management functions
- Introduced new error code `ENO_ACCOUNT_PERMISSION`
TBA
- Permission check implementation in `check_signer_permission`
- Integration of permission checks across account operations
- Error handling for unauthorized operations
- Permission granting mechanism in `grant_permission`
> Add permission check to account

- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/framework/aptos-framework/doc/permissioned_signer.md
- aptos-move/framework/aptos-framework/sources/permissioned_signer.move
- aptos-move/framework/aptos-framework/tests/permissioned_signer_tests.move
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.move
- aptos-move/framework/src/natives/permissioned_signer.rs
- types/src/on_chain_config/aptos_features.rs
Adds support for permissioned signer functionality in the Aptos framework by introducing a new feature flag `PERMISSIONED_SIGNER`. This change enables controlled access to signer capabilities through permission checks. The implementation includes feature flag assertions in the permissioned signer module to ensure the feature is enabled before use.
The feature flag implementation follows established patterns used for other feature flags in the system. Testing is enforced through the existing feature flag testing infrastructure.
- Feature flag integration in `permissioned_signer.move`
- New permission checks added to `signer_from_permissioned_handle` and `signer_from_storable_permissioned_handle`
- Feature flag constant definition and helper functions in `features.move`
> Feature gate permissioned signer

- aptos-move/framework/aptos-framework/doc/object.md
- aptos-move/framework/aptos-framework/doc/permissioned_signer.md
- aptos-move/framework/aptos-framework/sources/object.move
- aptos-move/framework/aptos-framework/sources/permissioned_signer.move
Allowed transfer ref to grant permission to the permissioned signer.
Test added 
Whether the granting logic is safe.
> Create object with permissioned signer

- aptos-move/e2e-move-tests/README.md
- aptos-move/e2e-move-tests/src/tests/keyless_feature_gating.rs
- aptos-move/vm-genesis/src/lib.rs
- crates/aptos-genesis/src/builder.rs
- crates/aptos-genesis/src/lib.rs
- crates/aptos-genesis/src/mainnet.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/genesis/mod.rs
- execution/executor-benchmark/src/db_generator.rs
- keyless/pepper/service/src/lib.rs
- testsuite/smoke-test/src/keyless.rs
- types/src/keyless/bn254_circom.rs
- types/src/keyless/circuit_constants.rs
- types/src/keyless/mod.rs
- types/src/keyless/test_utils.rs
- types/src/keyless/tests.rs
The genesis VK for Aptos Keyless is either set manually via `GenesisConfiguration` or defaults to the `DEVNET_VERIFICATION_KEY` value hardcoded in our Rust code.
However, this default value is no longer useful[^huh], because when we update the devnet VK in production, a devnet redeployment would later overwrite this update and revert us back to the default VK.
This, in turn, would lock developers outside of their devnet accounts. As result, we'd have to manually run a governance proposal to update the devnet VK after every devnet release.
Therefore, to ensure VK updates persist on devnet, we need to refine our devnet deployment process to fetch the latest VK from somewhere (TBD) and deploy with that in the `GenesisConfiguration`.
+ @perryjrandall suggested to update the devnet release …
> no more default devnet VK; it should now be set manually via governance during (re)deployment

- consensus/src/pipeline/buffer_manager.rs
- consensus/src/pipeline/decoupled_execution_utils.rs
- consensus/src/pipeline/persisting_phase.rs
> [buffer manager] move epoch notification to after commit

- aptos-move/e2e-move-tests/src/tests/move_feature_gating.rs
- aptos-move/framework/aptos-framework/doc/big_ordered_map.md
- aptos-move/framework/aptos-framework/doc/object.md
- aptos-move/framework/aptos-framework/doc/ordered_map.md
- aptos-move/framework/aptos-framework/doc/permissioned_signer.md
- aptos-move/framework/aptos-framework/sources/object.move
- aptos-move/framework/aptos-framework/sources/object.spec.move
- aptos-move/framework/aptos-framework/sources/permissioned_signer.move
- testsuite/single_node_performance_values.tsv
Adds permissioned signer support for object transfers and token/collection mutations in the Aptos Framework. This change introduces new permission types and validation checks to ensure only authorized signers can perform transfers and mutations on objects, tokens and collections.
Added new test cases in object.move and aptos_token.move to verify permissioned signer functionality for transfers and mutations. 
- New permission types added: TransferPermission, TokenUpdatePermission, CollectionUpdatePermission
- Permission validation checks in transfer and mutation operations
- Integration with existing permissioned_signer module
- Authorization and revocation flows for token/collection mutations
> [object] Add permissioned checks to object

- Cargo.lock
- ecosystem/indexer-grpc/indexer-grpc-manager/Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-manager/src/config.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/grpc_manager.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/lib.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/service.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/test.rs
> [Indexer-Grpc-V2] Add GrpcManagerService.

- aptos-move/framework/aptos-framework/doc/account.md
- aptos-move/framework/aptos-framework/doc/multisig_account.md
- aptos-move/framework/aptos-framework/doc/resource_account.md
- aptos-move/framework/aptos-framework/doc/staking_contract.md
- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/aptos-framework/sources/account.spec.move
- aptos-move/framework/aptos-framework/sources/multisig_account.spec.move
- aptos-move/framework/aptos-framework/sources/resource_account.spec.move
- aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
> Add permission checks to account

- third_party/move/move-vm/runtime/src/frame_type_cache.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- types/src/on_chain_config/aptos_features.rs
Just setting default for the call tree and instruction caches to true.
> Enable call frame tree cache and instruction caches

- aptos-move/framework/aptos-framework/doc/aptos_account.md
- aptos-move/framework/aptos-framework/doc/aptos_coin.md
- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/doc/dispatchable_fungible_asset.md
- aptos-move/framework/aptos-framework/doc/fungible_asset.md
- aptos-move/framework/aptos-framework/doc/managed_coin.md
- aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
- aptos-move/framework/aptos-framework/doc/stake.md
- aptos-move/framework/aptos-framework/sources/aptos_account.move
- aptos-move/framework/aptos-framework/sources/aptos_coin.spec.move
- aptos-move/framework/aptos-framework/sources/coin.move
- aptos-move/framework/aptos-framework/sources/coin.spec.move
- aptos-move/framework/aptos-framework/sources/dispatchable_fungible_asset.move
- aptos-move/framework/aptos-framework/sources/fungible_asset.move
- aptos-move/framework/aptos-framework/sources/managed_coin.move
- aptos-move/framework/aptos-framework/sources/managed_coin.spec.move
- aptos-move/framework/aptos-framework/sources/primary_fungible_store.move
- aptos-move/framework/aptos-framework/sources/stake.spec.move
Implemented permissions for FA transfer.
- Work with current Coin that already migrated to FA as well.
- Implemented a new api `deposit_with_signer` so that permissions can be added to the signer back again.
Added test cases. In particular, tested the entire migration path of Coin and FA.
Make sure FA permission works well throughout the entire migration path of FA.
> add permissions for fungible assets operation

- aptos-move/framework/aptos-framework/doc/aptos_governance.md
- aptos-move/framework/aptos-framework/doc/code.md
- aptos-move/framework/aptos-framework/doc/create_signer.md
- aptos-move/framework/aptos-framework/doc/delegation_pool.md
- aptos-move/framework/aptos-framework/doc/object_code_deployment.md
- aptos-move/framework/aptos-framework/doc/resource_account.md
- aptos-move/framework/aptos-framework/doc/stake.md
- aptos-move/framework/aptos-framework/doc/staking_proxy.md
- aptos-move/framework/aptos-framework/doc/vesting.md
- aptos-move/framework/aptos-framework/doc/voting.md
- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
- aptos-move/framework/aptos-framework/sources/code.move
- aptos-move/framework/aptos-framework/sources/code.spec.move
- aptos-move/framework/aptos-framework/sources/create_signer.spec.move
- aptos-move/framework/aptos-framework/sources/delegation_pool.move
- aptos-move/framework/aptos-framework/sources/object_code_deployment.move
- aptos-move/framework/aptos-framework/sources/resource_account.spec.move
- aptos-move/framework/aptos-framework/sources/stake.move
- aptos-move/framework/aptos-framework/sources/stake.spec.move
- aptos-move/framework/aptos-framework/sources/staking_proxy.move
- aptos-move/framework/aptos-framework/sources/staking_proxy.spec.move
- aptos-move/framework/aptos-framework/sources/vesting.move
- aptos-move/framework/aptos-framework/sources/vesting.spec.move
- aptos-move/framework/aptos-framework/sources/voting.move
- aptos-move/framework/aptos-framework/sources/voting.spec.move
- aptos-move/framework/aptos-framework/tests/compiler-v2-doc/object_code_deployment.md
Implement checks for all framework related privilege operations.
Added relevant tests.
Whether there's any priviledged operation need to be gated.
> permission for framework

- ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2200077591_account_restoration_single_ed25519.json
- ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2200077800_account_restoration_rotated_to_multi_key.json
- ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2200077877_account_restoration_rotated_to_single_secp256k1.json
- ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml
Generate new transactions for the new account_restoration_processor diff tests from mainnet.
- version `2200077591`: User txn with `ed25519` single-key authenticator
- version `2200077877`: User txn with `secp256k1` single-key authenticator, after rotation (rotated from `secp256k1` single-key)
- version `2200077800`: User txn with 2-of-3 multi-key authenticator, after rotation (rotated from `ed25519` single-key)
> Add Txns for AccountRestoration Indexer Processor Tests

- Cargo.lock
- aptos-move/aptos-release-builder/data/example.yaml
- aptos-move/aptos-release-builder/data/release.yaml
- testsuite/smoke-test/Cargo.toml
- testsuite/smoke-test/src/upgrade.rs
> fix bytecode version for upgrade test

- aptos-move/framework/src/built_package.rs
- third_party/move/move-compiler-v2/src/lib.rs
With this PR, `aptos move lint` returns exit code 0 on success and 1 if there are any warnings or errors.
This was a feature request by @banool for ease of use in CI/scripts.
Manually tested on a projects that (a) produce warnings and (b) do not produce warnings, and verified we have expected behavior.
> [lint] Make `aptos move lint` return non-zero exit code on warnings and errors

- third_party/move/tools/move-linter/src/stackless_bytecode_lints/needless_mutable_reference.rs
- third_party/move/tools/move-linter/tests/stackless_bytecode_lints/needless_mutable_reference_warn.move
In the following code (taken from a real world example), the linter warned about needless mutable reference:
`fun foo(_x: &mut u64) {}`
With this PR, we omit such warnings for variables that begin with `_`.
Added a new test.
> [lint] Don't lint needless mut reference on _ignored variables

- Cargo.lock
- api/Cargo.toml
- api/doc/spec.json
- api/doc/spec.yaml
- api/src/accounts.rs
- api/src/tests/accounts_test.rs
- api/types/src/account.rs
- api/types/src/derives.rs
- api/types/src/lib.rs
- sdk/Cargo.toml
- sdk/src/types.rs
create endpoint `/accounts/{ADDRESS}/balance/{TYPE_TAG | ADDRESS}` to return the total balance of migrated coin or pure FA.
> [api] balance api

- aptos-move/framework/aptos-framework/doc/transaction_validation.md
- aptos-move/framework/aptos-framework/sources/transaction_validation.move
- aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
- testsuite/smoke-test/src/lib.rs
- testsuite/smoke-test/src/permissioned_delegation.rs
> [gas] permission

- aptos-move/e2e-benchmark/data/calibration_values.tsv
- aptos-move/framework/aptos-framework/Prover.toml
- aptos-move/framework/src/prover.rs
- aptos-move/framework/tests/move_prover_tests.rs
- third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
- third_party/move/move-prover/boogie-backend/src/options.rs
- third_party/move/move-prover/lab/src/benchmark.rs
- third_party/move/move-prover/src/lib.rs
- third_party/move/move-prover/tests/sources/functional/bitwise_features.exp
Boogie is using exhaustive amounts of memory if run as part of proving aptos-framework (100GB+), which makes CI and local testing fail randomly. This PR introduces a new `--shards` option which splits the Boogie job into multiple shards, if specified. Also re-animates the use of `Prover.toml` in a package directory allowing to set such options.
Existing tests
> [move-prover] Sharding feature + re-animate Prover.toml

- ecosystem/indexer-grpc/indexer-grpc-utils/src/compression_util.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator_v2/common.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator_v2/file_store_operator.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator_v2/file_store_reader.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator_v2/gcs.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator_v2/local.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator_v2/mod.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs
> [Indexer-Grpc-V2] Add FileStoreOperatorV2.

- aptos-move/aptos-gas-schedule/src/ver.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- third_party/move/move-core/types/src/language_storage.rs
- third_party/move/move-vm/runtime/src/session.rs
> [aptos-vm] Refactor type tag processing

- consensus/src/block_preparer.rs
Basically, `get_transactions` is not cancellation safe, so it cannot be polled in a select statement.
> qs: undo using block votes to fetch batches

- Cargo.lock
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/config.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/connection_manager.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/historical_data_service.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/lib.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/service.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/test.rs
> [Indexer-Grpc-V2] Add HistoricalDataService.

- ecosystem/indexer-grpc/indexer-grpc-manager/Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-manager/src/config.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/file_store_uploader.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/grpc_manager.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/lib.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/test.rs
> [Indexer-Grpc-V2] Add FileStoreUploader.

- .github/workflows/indexer-protos-sdk-update.yaml
- scripts/indexer_proto_update_status_poll.sh
Fix the workflow that doesn't catch the downstream workflow breakage. Now processor linter issue will break aptos-core CI!
> Add workflow that monitors the downstream test result.

- storage/aptosdb/src/ledger_db/ledger_metadata_db.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/aptosdb/src/utils/truncation_helper.rs
- testsuite/smoke-test/src/storage.rs
in case of a partial commit on a unsharded state db, two things were wrong:
1. when we see a partial version, we need to look at the previous version before jumping the the epoch boundary (we forgot to subtract 1 from the version)
2. the ledger meta db were not passed in as intended (instead, we passed the state merkle meta db)
incomplete / faulty fix previously https://github.com/aptos-labs/aptos-core/pull/15089
The test_db_restart smoke test does catch this sometimes but it's not easy to trigger. I bumped the number of restarts on that test.
> Fix state merkle truncate

- scripts/indexer_proto_update_status_poll.sh
Fix the polling script.
Tested and looks good.
> Fixed the workflow to release protos.

- aptos-move/aptos-workspace-server/src/common.rs
- aptos-move/aptos-workspace-server/src/lib.rs
- aptos-move/aptos-workspace-server/src/services/docker_common.rs
- aptos-move/aptos-workspace-server/src/services/faucet.rs
- aptos-move/aptos-workspace-server/src/services/indexer_api.rs
- aptos-move/aptos-workspace-server/src/services/node.rs
- aptos-move/aptos-workspace-server/src/services/postgres.rs
- aptos-move/aptos-workspace-server/src/services/processors.rs
This introduces two custom macros to be used within `aptos-workspace-server`, which allow errors to be ignored when writing to `stdout` & `stderr`.
This is to ensure `aptos-workspace-server` can complete its graceful shutdown sequence when being used as a child process.
- When spawned as a child process, its `stdout` and `stderr` get piped.
- When the parent (TS-frontend) exits, the pipes will close. The default macros (`println`, `eprintln`) will panic when writing to a closed pipe.
> [aptos-workspace-server] ignore errors when writing to stdout & stderr

- Cargo.lock
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
This bumps the CLI version to 6.0.2 so we can release a fixed version that can be used by aptos workspace.
> Bump cli version to 6.0.2

- third_party/move/move-core/types/src/value.rs
- third_party/move/move-vm/runtime/src/data_cache.rs
- third_party/move/move-vm/runtime/src/lib.rs
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/runtime.rs
- third_party/move/move-vm/runtime/src/session.rs
- third_party/move/move-vm/runtime/src/storage/environment.rs
- third_party/move/move-vm/runtime/src/storage/mod.rs
- third_party/move/move-vm/runtime/src/storage/ty_layout_converter.rs
- third_party/move/move-vm/runtime/src/storage/ty_tag_converter.rs
[PR 3/n vm closures]
Type conversions from runtime types to `MoveTypeLayout` and `TypeTag` currently are associated with the `Loader` type. However, they are needed for the `FunctionValueExtension` trait which needs to be constructed in contexts where no loader but only `ModuleStorage` exists.
This PR moves the conversion functions into a new trait `TypeConverter`. The trait is then implemented two times, once based on `ModuleStorage` only and once based on the existing `Loader`, for downwards compatibility.
Refactoring only, existing tests
> [move-cm][closures] Refactor: Move type conversions out of `Loader` into a trait

- Cargo.lock
- aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
- third_party/move/move-vm/integration-tests/Cargo.toml
- third_party/move/move-vm/integration-tests/src/tests/module_storage_tests.rs
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/loader/modules.rs
- third_party/move/move-vm/runtime/src/loader/script.rs
- third_party/move/move-vm/runtime/src/loader/type_loader.rs
- third_party/move/move-vm/runtime/src/session.rs
- third_party/move/move-vm/runtime/src/storage/environment.rs
- third_party/move/move-vm/runtime/src/storage/mod.rs
- third_party/move/move-vm/runtime/src/storage/ty_cache.rs
- third_party/move/move-vm/runtime/src/storage/ty_layout_converter.rs
- third_party/move/move-vm/runtime/src/storage/ty_tag_converter.rs
- third_party/move/move-vm/types/Cargo.toml
- third_party/move/move-vm/types/src/code/errors.rs
- third_party/move/move-vm/types/src/loaded_data/mod.rs
- third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
- third_party/move/move-vm/types/src/loaded_data/struct_name_indexing.rs
For transaction argument validation, we check if the struct type name matches the allowed constructor. Previously, we were loading modules to check that, which is unnecessary because we can get the name from the struct re-indexing map. This PR changes the check to this.
Double-check the behaviour is the same.
> [aptos-vm][move] Avoid module loads when getting the struct name

- aptos-move/framework/aptos-framework/doc/permissioned_signer.md
- aptos-move/framework/aptos-framework/sources/permissioned_signer.spec.move
This PR reduces memory usage of verification of framework to less than 30GB by making `check_permission_exists` opaque.
Existing tests
> [spec] use opaque in the spec of check_permission_exists

- devtools/aptos-cargo-cli/src/lib.rs
Removes a temporary fix that was disabling the framework upgrade test. This change re-enables the test by removing the code that was forcing `relevant_changes_detected` to `false`.
The framework upgrade test will now run normally when relevant changes are detected, validating the intended behavior.
- Verify that removing this temporary fix doesn't reintroduce the original issues that led to disabling the test
- Confirm that the framework upgrade test executes correctly when changes are detected
> [devtools] Enable the framework upgrade test again

- consensus/consensus-types/src/block_retrieval.rs
- consensus/src/block_storage/sync_manager.rs
- consensus/src/epoch_manager.rs
- consensus/src/network.rs
- consensus/src/network_interface.rs
- consensus/src/network_tests.rs
- consensus/src/round_manager_test.rs
- testsuite/generate-format/src/consensus.rs
- testsuite/generate-format/tests/staged/consensus.yaml
Deprecates the `BlockRetrievalRequest` struct in favor of a `BlockRetrievalRequest` enum. This is needed as execution pool plans to make `BlockRetrievalRequest`s that include epoch and round information instead of `target_block_id`.
The plan is to phase this in three releases. The first release will introduce the new `BlockRetrievalRequest` enum and all corresponding structs / logic that use it. The second release will deprecate the `BlockRetrievalRequestV1` struct and all related structs / logic.
> [!IMPORTANT]  
> Some TODOs around deprecation are already marked in the code. Additional TODO in future PRs:
> - [ ] `process_block_retrieval_v2` to be implemented in a future PR cc @bchocho @hariria 
> - [ ] Once the new `BlockRetrievalRequest` enum is in the mainnet release, …
> [execution-pool] BlockRetrievalRequest struct -> enum

- third_party/move/move-vm/runtime/Cargo.toml
Fix compile error when running `cargo test` on `move-vm-runtime`.
> Fix compile error

- api/src/tests/simulation_test.rs
- aptos-move/framework/aptos-framework/doc/transaction_validation.md
- aptos-move/framework/aptos-framework/sources/transaction_validation.move
There is an `if` clause that got deleted by mistake.
api test does not catch this because AA feature is enabled inside default features, when it is enabled the prologue was run with a different/new move function that does not have this bug. Whereas the old one run when AA is disabled has.
remove AA from default features, then
test_bcs_simulate_fee_payer_transaction_without_gas_fee_check failed with `UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION`
after the fix this test passes.
> [hotfix] fix the fee payer txn simulation error

- aptos-move/aptos-gas-schedule/src/ver.rs
- aptos-move/aptos-release-builder/data/release.yaml
- aptos-move/aptos-release-builder/src/components/mod.rs
and update release.yaml template closer to what is used in the release, and add more details on release folder issues.
> Bump gas version on main

- consensus/src/consensus_observer/network/observer_message.rs
- consensus/src/payload_manager.rs
These are the consensus observer message-side changes needed to support blocks having a block gas limit override. Once these messages are deployed, they can be used.
Existing unit tests.
Serde compatibility. Any structs that are currently used in messages should not be changed in place.
> [consensus observer] add new BlockTransactionPayload variants to prepare for block gas limit override on blocks

- Cargo.lock
- Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/config.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/historical_data_service.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/lib.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/live_data_service/mod.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/status_page.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-manager/src/config.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/data_manager.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/grpc_manager.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/lib.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/metadata_manager.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/status_page.rs
- ecosystem/indexer-grpc/indexer-grpc-server-framework/src/lib.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/Cargo.toml
- ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/status_page/html.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/status_page/mod.rs
> [Indexer-Grpc-V2] Add status pages for DataService and GrpcManager.

- aptos-move/block-executor/src/view.rs
When there is a storage error, propagate it up with alert, but do not set incorrect use to avoid fallback to sequential and scary invariant violation logs.
> [block-stm] Do not set incorrect use on storage errors

- aptos-move/framework/aptos-framework/doc/big_ordered_map.md
- aptos-move/framework/aptos-framework/doc/ordered_map.md
- aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.move
- aptos-move/framework/aptos-framework/sources/datastructures/ordered_map.move
- aptos-move/framework/aptos-stdlib/doc/smart_table.md
- aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move
making traversal APIs complete and public
adding ordering-based utilities, without iterator functionality
> [framework] Adding utilities to OrderedMap / BigOrderedMap

- aptos-move/script-composer/src/builder.rs
- aptos-move/script-composer/src/tests/mod.rs
Improve script composer logic:
1. Fixed deduplication problem with importing multiple generic calls.
2. Cache the module loaded results into a thread local, hopefully this would allow for a faster re-loading process.
3. Rename the wasm bindgen to camel case to align with TS apis.
Added test case for the bug fix. Caching logic would be captured by the native CI.
N/A
> Improve script composer

- aptos-move/framework/aptos-framework/doc/account_abstraction.md
- aptos-move/framework/aptos-framework/doc/staking_config.md
- aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- sdk/src/transaction_builder.rs
- testsuite/smoke-test/src/permissioned_delegation.rs
cherry pick https://github.com/aptos-labs/aptos-core/pull/15858
> [cherry-pick][AA] fix visibility issues

- consensus/src/round_manager_test.rs
- testsuite/forge-cli/src/suites/dag.rs
- testsuite/smoke-test/src/aptos_cli/validator.rs
- testsuite/smoke-test/src/consensus/dag/dag_fault_tolerance.rs
- testsuite/smoke-test/src/consensus_observer.rs
- testsuite/smoke-test/src/state_sync.rs
- testsuite/testcases/src/dag_onchain_enable_test.rs
- types/src/on_chain_config/consensus_config.rs
- types/src/on_chain_config/mod.rs
A new `OnChainConsensusConfig` variant that includes a `window_size` for execution pool.
Note: `window_size` is be `Option<u64>` in the OnChainConfig, but will be converted to `Option<usize>` once it's deserialized and handled in memory
> [exec-pool] OnChainConsensusConfig V4

- testsuite/smoke-test/src/permissioned_delegation.rs
The original test is confusing in terms of the key to delegate.
> [smoke-test] solidify permissioned delegation test

- .github/workflows/forge-unstable.yaml
Stop running forge unstable on schedule. Previously this was used to bake and calibrate forge tests that include the indexer stack and measure its e2e latency. Save some costs and get signal elsewhere, esp since we have many data points now.
Removes a workflow that's been failing. We should have enough data points now to calibrate unstable tests
> [gha] stop testing forge unstable on schedule

- consensus/src/consensus_observer/common/metrics.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
This small PR makes tiny improvements to the message metrics for consensus observer. Specifically, we: (i) add a new counter to track invalid messages; and (ii) refactor some of the logic into shared methods.
> [Consensus Observer] Small improvements to message metrics.

- Cargo.lock
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
Bump the CLI to 6.1.0
I will run the release workflow after https://github.com/aptos-labs/aptos-core/pull/15888 gets merged to `main`.
> [cli] Bump to 6.1.0

- .github/workflows/cli-release.yaml
There seems to be some intermittent dependency conflict that only occurs on the ARM machines.  Need more to debug.
> [cli] Disable macOS ARM build

- aptos-move/framework/src/built_package.rs
- crates/aptos/e2e/cases/move.py
- crates/aptos/src/move_tool/lint.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/test/mod.rs
- third_party/move/tools/move-package/src/lib.rs
Fixes https://github.com/aptos-labs/aptos-core/issues/13279
I have added a python test which checks that compilation hasn't been invoked with the `--fetch-deps-only` flag.
I had to split `BuiltPackage::build_with_external_checks()` to be able to run a part of it separately. 
@vgao1996
> [CLI] Add `--fetch-deps-only` option to the `aptos move compile` to skip compilation

- aptos-move/move-examples/tests/move_unit_tests.rs
- third_party/move/tools/move-package/src/source_package/std_lib.rs
The move examples in `aptos-move/move-examples/` are expected to be used as a template by users. As such, we want to keep the `Move.toml` references within these projects to refer to `https://github.com/aptos-labs/aptos-framework.git` (as a best practice).
However, we use these examples for testing (the compiler, the framework usage, etc). By pointing to `https://github.com/aptos-labs/aptos-framework.git`, these tests can fail on framework upgrade (an external event). Instead, we want these tests to use the local framework.
In this PR, we add a new std override, so that these tests use the local framework, but the `Move.toml` files in the `aptos-move/move-examples/` can continue to point to `https://github.com/aptos-labs/aptos-framework.git`.
- Existing tests
> [move-examples] Override framework used in testing of move examples

- Cargo.lock
- aptos-move/aptos-workspace-server/src/lib.rs
- crates/aptos/CHANGELOG.md
- crates/aptos/Cargo.toml
This adds to `aptos-workspace-server` the ability to listen for a `stop` command from `stdin` so to allow external programs to conveniently trigger a graceful shutdown. This is especially needed on Windows, where it is not possible to send a SIGINT to just a child process.
This also bumps the CLI version to 6.1.1.
> [aptos-workspace-server] add ability to listen for a stop command + bump aptos CLI version to 6.1.1

- .github/actions/fullnode-sync/fullnode_sync.py
This PR adds a storage config to the fullnode sync jobs to avoid checking for ulimits. This check was recently introduced by https://github.com/aptos-labs/aptos-core/pull/15875, but it's not a hard requirement for our tests. Right now the tests are failing with:
```
Identified node type (PublicFullnode) and chain ID (Some(mainnet)) from node config!
thread 'main' panicked at aptos-node/src/utils.rs:121:17:
Failed raising RLIMIT_NOFILE soft limit to 100000. Error: Operation not permitted (os error 1)
```
Existing test infratructure.
> [Fullnode Sync] Fix the fullnode sync job ulimit check.

- .github/workflows/indexer-processor-testing.yaml
- ecosystem/indexer-grpc/indexer-transaction-generator/README.md
- ecosystem/indexer-grpc/indexer-transaction-generator/src/config.rs
Added configurable flags to control transaction processing behavior in the indexer transaction generator. Two new command-line options have been introduced:
- `mode`: (Optional) Specify the mode of operation for the indexer. Possible values are `import` and `script`. Default is `import`.
These flag provide more granular control over the transaction generation process, allowing users to selectively enable or disable specific functionality as needed.
default run to just import txns
```
cargo run -- --testing-folder ./imported_transactions --output-folder ../indexer-test-transactions/src 
```
this will generate txns from scripts
```
cargo run -- --testing-folder ./imported_transactions --output-folder ../indexer-test-transactions/src --mode=script
```
Note that `generated_transactions.rs` …
> update test txn generator flags

- Cargo.lock
- aptos-move/replay-benchmark/Cargo.toml
- aptos-move/replay-benchmark/README.md
- aptos-move/replay-benchmark/src/commands/initialize.rs
- aptos-move/replay-benchmark/src/overrides.rs
- types/src/transaction/mod.rs
This PR adds support for package overriding: one can specify `--override-packages P1 P2 P3` and replay historical transactions with new code (e.g., framework). This allows to check performance (`benchmark` option) or gas usage (`diff` option).
Note: one needs to be careful overriding packages which add new package dependencies. For example, it is possible that stdlib adds a module, which is used in framework code. For override, one needs to provide both packages.
> [benchmark] Add option for package overrides

- aptos-move/replay-benchmark/README.md
- aptos-move/replay-benchmark/src/commands/benchmark.rs
Adds a flag to disable paranoid mode for benchmarking. This way we can measure performance with and without on historical workloads.
> [benchmark] Make paranoid mode configurable

- consensus/src/execution_pipeline.rs
- consensus/src/network.rs
Temporarily adding `#[allow(dead_code)]` for fields and variants that are not being consumed yet. The code on `main` passes as-is on `scripts/rust-lint.sh`, this is just to remove some warnings.
For context, we’re deprecating the `BlockRetrievalRequest` struct in favor of an enum. And it needs to be phased over two releases. The `BlockRetrieval` variant here in the `IncomingRpcRequest` enum consumes this new `BlockRetrievalRequest` enum and isn’t being constructed yet (that’s why you’re seeing that message). The shuffler field is going to be used soon in https://github.com/aptos-labs/aptos-core/pull/14584/files.
> [exec-pool] Add allow dead code for IncomingRpcRequest and ExecuteBlock

- docker/builder/build-indexer.sh
- docker/builder/indexer-grpc.Dockerfile
Added support for two new indexer binaries: `aptos-indexer-grpc-data-service-v2` and `aptos-indexer-grpc-manager` to the build and Docker configuration. These binaries are now included in both the build process and the final Docker image.
- Verified successful build of new binaries through Docker build process
- Confirmed proper binary placement in Docker image
- Validated Docker image functionality with new components
- Build script modifications to include new binaries
- Docker file updates for proper binary copying
- Binary naming consistency across build and Docker configurations
> build indexer grpc-v2 binaries

- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/well_known.rs
This PR fixes a bug in the compiler so that index notation can be used in the vector module.
close #15959 
2) manually compilation of move-stdlib after using index notation in the vector module.
> [Compiler] Allow index notation in vector module

- third_party/move/move-compiler-v2/src/bytecode_generator.rs
- third_party/move/move-compiler-v2/tests/bytecode-generator/matching_coverage_err.exp
- third_party/move/move-compiler-v2/tests/checking/dotdot/dotdot_valid.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/dotdot/nested.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/bug-14296.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/match_cover.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/match_cover.move
Fixes #14296.
Makes a couple of changes in the enum exhaustive match checker:
- When joining two shapes (see `try_join`), we have to unify `n` pairs of sub-shapes. Previously, we stopped if a single sub-shape pair was successful in unification. Now, we unify all `n` pairs of sub-shapes if possible.
- When specializing a list of shapes given a new shape (see `join_value_shape`), we stopped after doing this successfully on one of the shapes. Now, we go through the entire list of shapes and try specializing each one based on the new shape.
Currently on `main`, compiling:
```
module 0xc0ffee::n {
enum A has drop {
V1 { a: P, b: Q, c: R},
}
enum P has drop {
P1,
P2,
}
enum Q has drop {
Q1,
Q2,
}
enum R has drop {
R1,
R2,
}
public fun test(a: A) {
match (a) {
A::V1 { a: P::P1, b: _, c: _ } => …
```
> [compiler-v2] Fix enum match not exhaustive

- third_party/move/move-binary-format/src/file_format.rs
- third_party/move/move-core/types/src/function.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/loader/function.rs
- third_party/move/move-vm/runtime/src/loader/modules.rs
- third_party/move/move-vm/runtime/src/runtime_type_checks.rs
- third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
[PR 5/n vm closures]
This closes the loop, putting the pieces together to implement the closure logic in the interpreter loop.
They are some paranoid checks still missing which are marked in the code.
Testing postponed until e2e tests are possible
> [move-vm][closures] Interpreter

- consensus/consensus-types/src/common.rs
> [optqs] fix len_for_execution

- config/src/config/consensus_config.rs
- consensus/consensus-types/src/pipelined_block.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
- consensus/src/counters.rs
- consensus/src/epoch_manager.rs
- consensus/src/execution_pipeline.rs
- consensus/src/pipeline/buffer_manager.rs
- consensus/src/pipeline/decoupled_execution_utils.rs
- consensus/src/pipeline/execution_client.rs
- consensus/src/pipeline/pipeline_builder.rs
- consensus/src/pipeline/tests/buffer_manager_tests.rs
- consensus/src/test_utils/mock_execution_client.rs
- testsuite/forge-cli/src/suites/realistic_environment.rs
- testsuite/forge/src/config.rs
- tolerate the case when the parent block's future gets garbage collected (i.e. at epoch boundary)
- move pipeline creation to be exclusive with sync (either target or fallback)
> [pipeline] fix observer

- third_party/move/move-model/src/builder/module_builder.rs
- third_party/move/move-prover/tests/sources/functional/bug_15969.exp
- third_party/move/move-prover/tests/sources/functional/bug_15969.move
This PR fixes the bug in exp_builder to allow using receiver-style call in spec functions. 
Close #15969 
1) existing tests;
2) add a new test.
> [compiler-v2][trivial] Allow receiver call for spec fun

- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/framework/aptos-framework/doc/account_abstraction.md
- aptos-move/framework/aptos-framework/doc/auth_data.md
- aptos-move/framework/aptos-framework/doc/common_domain_aa_auths.md
- aptos-move/framework/aptos-framework/doc/domain_account_abstraction_ed25519_hex.md
- aptos-move/framework/aptos-framework/doc/transaction_validation.md
- aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
- aptos-move/framework/aptos-framework/sources/account/auth_data.move
- aptos-move/framework/aptos-framework/sources/transaction_validation.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.move
- aptos-move/vm-genesis/src/lib.rs
- execution/executor/tests/internal_indexer_test.rs
- sdk/src/types.rs
- testsuite/generate-format/src/api.rs
- testsuite/generate-format/src/aptos.rs
- testsuite/generate-format/src/consensus.rs
- testsuite/generate-format/tests/staged/api.yaml
- testsuite/generate-format/tests/staged/aptos.yaml
- testsuite/generate-format/tests/staged/consensus.yaml
- types/src/on_chain_config/aptos_features.rs
- types/src/transaction/authenticator.rs
- types/src/transaction/mod.rs
Current AA requires registration for each account, and user has to have private key for an address to be able to do so.
This change allows for AA to be per domain - for example for Solana we need "ed25519_hex", and domain-separated addresses to automatically accept it.
> AccountAbstraction that works per domain

- aptos-move/e2e-benchmark/data/calibration_values.tsv
- testsuite/single_node_performance_values.tsv
- third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs
- third_party/move/move-compiler-v2/src/lib.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy_local.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy_local.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy_nested.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy_nested.move
- third_party/move/move-core/types/src/language_storage.rs
- third_party/move/move-model/src/model.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/lib.rs
- third_party/move/move-vm/runtime/src/loader/function.rs
- third_party/move/move-vm/runtime/src/reentrancy_checker.rs
This implements a new reentrancy checker that supports both the rules of existing native dispatch (fungible assets et. al) as the ones for function value dispatch. The rules for the lattter are described in [AIP-112](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-112.md#reentrancy-check), and are more liberal than for native dispatch: with funtion value dispatch, one can reenter a module, but resources defined in such a module are unaccessible. With native dispatch, reentrancy is already blocked when an attempt is made to enter a module the 2nd time.
The existing reentrancy check is pulled out from the interpreter into a new module `reentrancy_checker.rs` which handles both rule sets by processing when functions are entered/exited and whether by static call/dynamic dispatch. …
> [move-vm][closures] New reentrancy checker

- .github/workflows/cli-release.yaml
- crates/aptos/CHANGELOG.md
- crates/aptos/src/update/aptos.rs
Removes 20.04 from release, since it's blocking CLI release
> [cli] Remove Ubuntu 20.04 from release

- testsuite/replay-verify/main.py
replay-verify end versions are currently manually set in gcs and we are not actually updating it. 
This makes the scheduler get it from our fullnode rest api.
manual run
https://github.com/aptos-labs/aptos-core/actions/runs/13662325606/job/38196109893
> get end version from api

- api/Cargo.toml
- api/src/tests/function_value_test.rs
- api/src/tests/mod.rs
- api/test-context/src/test_context.rs
- api/types/src/move_types.rs
- aptos-move/aptos-resource-viewer/src/lib.rs
- aptos-move/framework/src/built_package.rs
- aptos-move/move-examples/function_values/calculator/Move.toml
- aptos-move/move-examples/function_values/calculator/sources/calculator.move
- ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs
- storage/indexer/src/db_v2.rs
- storage/indexer/src/lib.rs
- third_party/move/move-compiler-v2/src/bytecode_generator.rs
- third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs
- third_party/move/move-compiler-v2/src/experiments.rs
- third_party/move/move-compiler-v2/src/lib.rs
- third_party/move/move-compiler-v2/tests/testsuite.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/tests.rs
- third_party/move/move-core/types/src/account_address.rs
- third_party/move/move-model/src/metadata.rs
- third_party/move/tools/move-resource-viewer/src/fat_type.rs
- third_party/move/tools/move-resource-viewer/src/lib.rs
This connects closure values to the REST API:
- Supports `aptos move compiler/... --language 2.2` to access function values
- Supports closures and function types in AnnotatedMoveValue
- Supports closures and function types in APIs MoveType/MoveValue
- Adds the move-examples/function_value/calculator and builds an API e2e test on top of it.
- Also verified manually with CLI.
e2e API test
> [api][closures] Support Closures in the REST API

- third_party/move/move-vm/runtime/src/loader/function.rs
- third_party/move/move-vm/runtime/src/storage/module_storage.rs
- third_party/move/move-vm/types/src/values/function_values_impl.rs
- third_party/move/move-vm/types/src/values/serialization_tests.rs
The version will allow us to evolve the format how closures are represented in storage.
> [move-vm][closures] Add a version field to closure serialization data

- ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/generated_transactions.rs
- ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_testnet_txns/6643353707_fa_transfer_events_v2.json
- ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_testnet_txns/6643353877_fa_transfer_2.json
- ecosystem/indexer-grpc/indexer-transaction-generator/README.md
- ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml
- ecosystem/indexer-grpc/indexer-transaction-generator/src/config.rs
Also adds network arg (testnet / mainnet)
> [Indexer] Adds new transactions for testing

- api/src/tests/function_value_test.rs
- third_party/move/move-core/types/src/function.rs
- third_party/move/move-vm/runtime/src/storage/module_storage.rs
- third_party/move/move-vm/types/src/values/function_values_impl.rs
- third_party/move/move-vm/types/src/values/serialization_tests.rs
After adding version number to closure BCS, API test started to fail on main. Apparently those tests aren't triggered by changes in the VM. To my surprise, the serialization format in `move-core/types/value.rs` must match the one used in `move-vm/types/values_impl.rs`, a dependency which isn't documented anywhere and appears strange. In any case, the data in the DB put via values_impl.rs there, must be recognizable by the `MoveValue` serializers. This PR fixes this and re-enables the failing test.
Renabled failing test
> [move-vm][closures] Fix failing api test

- aptos-move/e2e-move-tests/src/lib.rs
- aptos-move/e2e-move-tests/src/tests/metadata.rs
- crates/aptos/CHANGELOG.md
- crates/aptos/src/common/types.rs
- crates/aptos/src/governance/mod.rs
- crates/aptos/src/move_tool/mod.rs
- third_party/move/move-command-line-common/src/env.rs
- third_party/move/move-compiler-v2/src/lib.rs
- third_party/move/move-compiler-v2/tests/testsuite.rs
- third_party/move/move-model/src/metadata.rs
- third_party/move/tools/move-cli/src/base/test.rs
- third_party/move/tools/move-package/src/compilation/build_plan.rs
- third_party/move/tools/move-package/src/compilation/compiled_package.rs
- third_party/move/tools/move-package/src/compilation/model_builder.rs
- third_party/move/tools/move-unit-test/src/lib.rs
In this PR, we remove compiler v1 from the CLI.
Notes:
1. Once this PR merges, we will tag with `compiler-v1-alive` or similar, as after this PR, compiler v1 will not be available through the CLI and certain APIs.
2. The next CLI release after this PR gets merged should bump up the main version (i.e., `7.0.0`).
3. Aptos end-to-end comparison testing will not work because compiling with v1 will bail. I have discussed this with @rahxephon89.
- Existing tests.
- Certain tests (in e2e-move-tests) have been modified to reflect not being able to call into compiler v1.
Any general concerns about the manner of removal.
> [compiler-v2] Remove compiler v1 from the CLI

- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- types/src/on_chain_config/aptos_features.rs
Make V2 loader default. This breaks some historical transactions, as described here: https://docs.google.com/spreadsheets/d/16IVAe72g3Rcf3LqMKaj80a0Isa8ma3SaJFMVzOtVOfI/edit?usp=sharing. Note that since this doc was created there can be a few more differences.
TODO: cannot add txns to skip to the replay easily, will update this soon.
Note: the actual loader V1 removal comes in the next PR.
Replay run: (TBA)
> [2/n] Make loader V2 default

- aptos-move/aptos-vm-types/src/module_and_script_storage/state_view_adapter.rs
- third_party/move/move-vm/runtime/src/data_cache.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/native_functions.rs
- third_party/move/move-vm/runtime/src/session.rs
- third_party/move/move-vm/runtime/src/storage/depth_formula_calculator.rs
- third_party/move/move-vm/runtime/src/storage/implementations/unsync_code_storage.rs
- third_party/move/move-vm/runtime/src/storage/implementations/unsync_module_storage.rs
- third_party/move/move-vm/runtime/src/storage/mod.rs
- third_party/move/move-vm/runtime/src/storage/module_storage.rs
- third_party/move/move-vm/runtime/src/storage/publishing.rs
Move depth formula checks from loader to a separate type / file, use V2 loader only. Change type tag construction to V2 only and move it out of loader.
> [3/n] Move depth formulas and type tags out of loader

- third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/const_vec.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/const_vec.move
- third_party/move/move-model/bytecode/src/stackless_bytecode.rs
When we compile the following code:
```move
module 0xc0ffee::m {
public fun test1(): u8 {
let a = vector[0u8, 128u8];
a[0]
}
public fun test2(): u8 {
let b = x"0080";
b[0]
}
}
```
We get the following bytecode verification error due to a compiler bug.
```
Error: compilation errors:
bug: bytecode verification failed with unexpected status code `DUPLICATE_ELEMENT`. This is a compiler bug, consider reporting it.
Error message: none
┌─ TEMPFILE:2:1
│  
2 │ ╭ module 0xc0ffee::m {
3 │ │     public fun test1(): u8 {
4 │ │         let a = vector[0u8, 128u8];
5 │ │         a[0]
· │
10 │ │     }
11 │ │ }
│ ╰─^
```
In this PR, we fix this bug. Specifically, we use a canonical representation to check if a const has already been added to the const pool during code generation.
Added new test to …
> [compiler-v2] Fix bytecode verification error by canonicalizing constants

- aptos-move/aptos-vm-types/src/module_and_script_storage/state_view_adapter.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- third_party/move/move-vm/runtime/src/loader/function.rs
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/runtime.rs
- third_party/move/move-vm/runtime/src/session.rs
- third_party/move/move-vm/runtime/src/storage/code_storage.rs
- third_party/move/move-vm/runtime/src/storage/implementations/unsync_code_storage.rs
- third_party/move/move-vm/runtime/src/storage/loader.rs
Move `load_script` to `CodeStorage` as a default member. Switch to V2 flow and remove V1 loader usage for script loading.
> [5/n] Move script loading to trait and switch to V2

- aptos-move/framework/aptos-framework/doc/fungible_asset.md
- aptos-move/framework/aptos-framework/sources/fungible_asset.move
We need this event similar to CoinStoreDeletion for parsing a txn that withdraw FA and delete the store.
W/o this event, the there is no way to know the fa asset type from withdraw event.
> [FA] Add an event when FA store is deleted

- storage/db-tool/src/replay_on_archive.rs
The db-restore tooling didn't guarantee the StateStorageUsage is written down at epoch endings.
local run
> replay-verify: ignore hash mismatch at the begining of a chunk

- aptos-move/aptos-vm-types/src/module_and_script_storage/module_storage.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/user.rs
- aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
- aptos-move/e2e-tests/src/executor.rs
- third_party/move/move-vm/integration-tests/src/tests/instantiation_tests.rs
- third_party/move/move-vm/integration-tests/src/tests/loader_tests.rs
- third_party/move/move-vm/integration-tests/src/tests/native_tests.rs
- third_party/move/move-vm/runtime/src/lib.rs
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/loader/modules.rs
- third_party/move/move-vm/runtime/src/session.rs
- third_party/move/move-vm/runtime/src/storage/implementations/unsync_code_storage.rs
- third_party/move/move-vm/runtime/src/storage/implementations/unsync_module_storage.rs
- third_party/move/move-vm/runtime/src/storage/module_storage.rs
- third_party/move/move-vm/runtime/src/storage/publishing.rs
Moves loading of instantiated functions to V2 loader trait (module storages). This completes API transitions and V1 loader can be fully removed (next PR).
> [9/n] Move function loading to module storages

- consensus/src/consensus_observer/common/metrics.rs
- consensus/src/consensus_observer/network/observer_message.rs
- consensus/src/consensus_observer/observer/active_state.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
This PR adds basic boilerplate code to consensus observer. It offers the following commits:
1. Add the execution pool window size to the active state. This is read from the on-chain configs and will be populated in a separate PR.
2. Add a new consensus observer message (ordered block with window), and boilerplate to process the message.
In the next PR, I'll work on actually processing the ordered block with window message.
Existing test infrastructure. Nothing has really changed here.
> [Consensus Observer] Add boilerplate for block with window messages.

- Cargo.lock
- aptos-move/aptos-vm-environment/src/prod_configs.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/keyless_validation.rs
- aptos-move/block-executor/Cargo.toml
- aptos-move/block-executor/src/code_cache_global_manager.rs
- aptos-move/block-executor/src/errors.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/limit_processor.rs
- aptos-move/block-executor/src/proptest_types/tests.rs
- aptos-move/block-executor/src/txn_last_input_output.rs
- aptos-move/block-executor/src/view.rs
- aptos-move/vm-genesis/src/lib.rs
- third_party/move/move-vm/runtime/src/config.rs
- third_party/move/move-vm/runtime/src/storage/module_storage.rs
- types/src/on_chain_config/aptos_features.rs
This PR removes `use_loader_v2` from VM config. Cleaned up few places where it was used - mostly block executor. Removed fallback for module publishes handling as this is no longer used.
> [12/n] Remove use_loader_v2 config, refactor block executor to use V2

- aptos-move/aptos-release-builder/src/simulate.rs
- aptos-move/aptos-vm/src/data_cache.rs
- aptos-move/aptos-vm/src/move_vm_ext/resolver.rs
- third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
- third_party/move/move-vm/runtime/src/data_cache.rs
- third_party/move/move-vm/runtime/src/move_vm.rs
- third_party/move/move-vm/test-utils/src/storage.rs
- third_party/move/move-vm/types/src/resolver.rs
Modules are fetched from V2 loader (`ModuleStorage`, to be renamed), and `ModuleResolver` is removed because it is no longer used in V2.
> [13/n] Remove ModuleResolver as obsolete

- aptos-move/framework/src/built_package.rs
- crates/aptos/CHANGELOG.md
- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/coverage.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/update/movefmt.rs
- third_party/move/move-compiler-v2/src/experiments.rs
Closes #13198.
This PR adds a new user provided option to the compiler: `--fail-on-warning`.
When running, e.g., `aptos move compile --fail-on-warning`, if there are one or more warnings produced by the compiler, then the compilation fails.
Note: [minor] we also update the move formatter target version to the latest available formatter version.
- Existing tests.
- Manually tested the CLI option.
> [compiler-v2] Fail on warnings option

- aptos-move/framework/src/built_package.rs
- crates/aptos/CHANGELOG.md
- crates/aptos/src/common/types.rs
- crates/aptos/src/governance/mod.rs
- crates/aptos/src/move_tool/coverage.rs
- crates/aptos/src/move_tool/lint.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/move_tool/show.rs
- crates/aptos/src/test/mod.rs
- ecosystem/indexer-grpc/indexer-transaction-generator/src/script_transaction_generator.rs
We now run extended checks by default on test code. Users can disable these checks with `--skip-checks-on-test-code` option.
Closes #10335.
Also, we rename `MovePackageDir` -> `MovePackageOptions`.
> [compiler-v2] Check test code by default

- devtools/aptos-cargo-cli/src/lib.rs
There was a [change](https://github.com/nextest-rs/nextest/discussions/1646) recently made to nextest which results in an error if no tests are run. This is currently problematic for us as the target determinator may attempt to run tests on packages that don't have any unit tests. 
To prevent this, we add a `--no-tests=warn` flag to nextest in the target determinator. If no tests are run, the command will pass and a warning will be printed.
> [CI/CD] Add --no-tests flag to avoid failures on no tests.

- aptos-move/framework/src/docgen.rs
- aptos-node/src/utils.rs
- third_party/move/move-prover/move-docgen/src/docgen.rs
I've been building the aptos core on my gaming computer, and I realized that Windows would cause a bunch of files to have different paths, and warnings that weren't present on Unix.  This ensures that paths will always be the same.
Tested on the Windows machine, doesn't add a whole bunch of random files.  CI will test Unix.
Just check that the `cfg` parts match up
> [docgen] Windows build improvements

- testsuite/forge-cli/src/suites/realistic_environment.rs
- types/src/on_chain_config/execution_config.rs
In a previous PR (https://github.com/aptos-labs/aptos-core/pull/15613) I had deprecated the [`SenderAwareV2` shuffler](https://github.com/aptos-labs/aptos-core/blob/11ddec440cc34b58a35aded6ef2c4e77a144b561/types/src/on_chain_config/execution_config.rs#L175-L175) given that we had made the `UseCaseAwareShuffler` the default going forward.
Unfortunately, I forgot to remove all instances of the `SenderAwareV2` shuffler, including places where it was used in forge. Because of this the `forge-realistic-network-tuned-for-throughput` test (which you can find in [`realistic_network_tuned_for_throughput_test()` for aptos-core here](https://github.com/aptos-labs/aptos-core/blob/11ddec440cc34b58a35aded6ef2c4e77a144b561/testsuite/forge-cli/src/suites/realistic_environment.rs#L431-L431)) was failing. …
> [forge] Remove SenderAware shuffler from forge and tests

- .github/workflows/cli-release.yaml
Now, there's a 24.04 build, and the basic Linux and Linux ARM use 22.04 to build.
https://github.com/gregnazario/aptos-core/actions/runs/13799396090/job/38602285101
Ignore the mac builds
> [cli] Add straightforward linux CLI releases

- ecosystem/indexer-grpc/transaction-filter/src/boolean_transaction_filter.rs
- ecosystem/indexer-grpc/transaction-filter/src/filters/event.rs
- ecosystem/indexer-grpc/transaction-filter/src/filters/move_module.rs
- ecosystem/indexer-grpc/transaction-filter/src/filters/transaction_root.rs
- ecosystem/indexer-grpc/transaction-filter/src/filters/user_transaction.rs
- ecosystem/indexer-grpc/transaction-filter/src/traits.rs
Adds a `to_proto` function to the transaction filter. This makes defining the filter, both in configs and in code, a lot cleaner (look at the unit tests) when utilizing the filter protos in code. 
Unit tests.
`impl Into` for the transaction filter structs.
> [gRPC] Implement Filter to Proto

- testsuite/replay-verify/archive-pvc-template.yaml
- testsuite/replay-verify/archive_disk_utils.py
- testsuite/replay-verify/main.py
- testsuite/replay-verify/replay-verify-worker-template.yaml
Set a TTL upon worker pod creation to ensure they get cleaned up in case the scheduler fails to do so.
Set PVC storage class to `ssd-data-xfs-immediate` to ensure the underlying PVs are deleted promptly.
> Better resource cleanup for `replay-verify`

- consensus/src/consensus_observer/observer/consensus_observer.rs
- consensus/src/pipeline/buffer_manager.rs
This commit properly sets parent futures when the ordered blocks have more than one block.
> [CO] fix pipeline futures

- aptos-move/aptos-debugger/src/aptos_debugger.rs
- aptos-move/aptos-debugger/src/common.rs
Right now, the aptos debugger panics if we don't explicitly provide the `--concurrency-level` argument.
For example, the following crashes:
`aptos-debugger move execute-past-transactions --begin-version 2367592035 --limit 1 --rest-endpoint https://mainnet.aptoslabs.com/v1`
In this PR, we set a default value for the concurrency level, so that we don't panic. Also added an assert to make it easier to catch similar bugs in using `execute_transactions_at_version` incorrectly.
Manually.
Is the default value reasonable?
> [aptos-debugger] Fix aptos debugger crash

- third_party/move/move-prover/boogie-backend/src/boogie_helpers.rs
- third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
- third_party/move/move-prover/boogie-backend/src/spec_translator.rs
- third_party/move/move-prover/tests/sources/functional/enum_diff_type.exp
- third_party/move/move-prover/tests/sources/functional/enum_diff_type.move
This PR changes the encoding of enum in boogie data representation to allow enum to define field with same name but different types in different variants.
2) added a new test.
> [prover] refactor enum representation in boogie

- third_party/move/move-compiler-v2/tests/checking/receiver/call_errors.exp
- third_party/move/move-compiler-v2/tests/checking/receiver/call_errors.move
- third_party/move/move-compiler-v2/tests/checking/receiver/call_errors_2.exp
- third_party/move/move-compiler-v2/tests/checking/receiver/call_errors_2.move
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_16057.exp
- third_party/move/move-compiler-v2/tests/lambda/inline-parity/bug_16091.exp
- third_party/move/move-compiler-v2/tests/lambda/inline-parity/bug_16091.move
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/builder/module_builder.rs
This PR adds the logic to run `finalize_types` before and after `post_process_body` and only generates error in the second time so that type can be instantiated in receiver style syntax before finalizing types.
Close #16091 
Close #16057
1) existing tests;
2) added a new test.
> [compiler][trivial] fix type instantiation for receiver style syntax

- crates/aptos/CHANGELOG.md
- crates/aptos/e2e/cases/config.py
- crates/aptos/e2e/common.py
- crates/aptos/e2e/test_helpers.py
- crates/aptos/src/common/types.rs
Added `network` to the output of `aptos config show-profiles`. 
Example output:
```
$ aptos config show-profiles
{
"Result": {
"default": {
"network": "Devnet",
"has_private_key": true,
"public_key": "0xe8dee7e202b2f68d10faf2efb46ee7e2ca51655179cfab07ef54752c1f3e0818",
"account": "4dc6729e92ad055050fd8afd85ebbc27d43e0503a4eadd670ede31cf5617f002",
"rest_url": "https://fullnode.devnet.aptoslabs.com",
"faucet_url": "https://faucet.devnet.aptoslabs.com"
}
}
}
```
- Updated `test_config_show_profiles` to also test the new network value.
- Also manually tested the CLI using the compiled binary, for both Aptos networks and custom networks.
> [cli] add network to show-profiles

- crates/aptos/CHANGELOG.md
- crates/aptos/src/update/mod.rs
- crates/aptos/src/update/move_mutation_test.rs
- crates/aptos/src/update/tool.rs
With this PR, we can run `aptos update move-mutation-test` to install the latest version of the move mutation test tool.
Manually. The tool's release on `eigerco/move-mutation-tools` still needs to be update to reflect the correct version number, after which I will test the update again. For now, it will always update when you run the command.
> [cli] Add move-mutation-test to `aptos update`

- testsuite/replay-verify/archive_disk_utils.py
- testsuite/replay-verify/main.py
Cleanup stray PVCs too. The TTL is the same as the pod mounting the PVC.
Will start a replay-verify workflow on the PR branch.
Test run: https://github.com/aptos-labs/aptos-core/actions/runs/13955750026
> Replay-verify: set TTL on PVCs as well

- aptos-node/src/network.rs
- consensus/consensus-types/src/quorum_cert.rs
- consensus/consensus-types/src/timeout_2chain.rs
- mempool/src/shared_mempool/priority.rs
- network/builder/src/builder.rs
This PR fixes several typographical errors in documentation comments across multiple files in the repository. These changes improve the readability and clarity of the codebase without altering any functionality.
aptos-node/src/network.rs
- Fixed typo: inteface → interface
consensus/consensus-types/src/quorum_cert.rs
- Improved comment clarity: The vote information certified by the quorum. → The vote information is certified by the quorum.
consensus/consensus-types/src/timeout_2chain.rs
- Fixed typo: timout → timeout
mempool/src/shared_mempool/priority.rs
- Fixed typo: recieved → received
network/builder/src/builder.rs
- Fixed typo: thorugh → through
> docs: fix typos in files

- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/sources/coin.move
- aptos-move/framework/aptos-framework/sources/coin.spec.move
- aptos-move/framework/aptos-framework/sources/managed_coin.move
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.move
- aptos-move/framework/move-stdlib/sources/configs/features.spec.move
- types/src/on_chain_config/aptos_features.rs
Before we kick off the migration of all coinstore, we have to enable primary fungible store by default for all the new accounts.
The PR does not put the flag into default features to make sure existing code is not broken.
ut
and cicd tests.
> [migration] add a new flag to enable fa store by default

- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/sources/coin.move
This reverts commit e504d112d168121e5a724cf01a7aa0baaee6736c, which was patched before exchanges support APT FA.
Now they have supported it.
> Revert "[fa] add back migration_flag for exchanges (#15738)"

- crates/aptos-rest-client/examples/account/main.rs
- crates/aptos-rest-client/src/lib.rs
add get_account_balance() to get balance of coin/fa.
```
aptos node run-local-testnet --with-indexer-api
cargo run --example account -- --api-url http://127.0.0.1:8080
```
```
2025-03-26T00:30:34.330986Z [main] INFO crates/aptos-rest-client/examples/account/main.rs:38 Successfully retrieved 52 account resources with JSON
2025-03-26T00:30:34.373258Z [main] INFO crates/aptos-rest-client/examples/account/main.rs:47 Successfully retrieved 52 account resources with BCS
2025-03-26T00:30:34.525277Z [main] INFO crates/aptos-rest-client/examples/account/main.rs:56 Successfully retrieved 114 account modules with JSON
2025-03-26T00:30:34.578263Z [main] INFO crates/aptos-rest-client/examples/account/main.rs:65 Successfully retrieved 114 account modules with BCS
2025-03-26T00:30:34.580279Z [main] INFO …
```
> [rust api] add get_account_balance() using new api endpoint

- consensus/src/consensus_observer/common/metrics.rs
- consensus/src/consensus_observer/observer/active_state.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
- consensus/src/consensus_observer/observer/execution_pool.rs
- consensus/src/consensus_observer/observer/mod.rs
- consensus/src/consensus_observer/observer/ordered_blocks.rs
- consensus/src/consensus_observer/observer/pending_blocks.rs
This PR adds a new `ObservedOrderedBlock` wrapper to consensus observer, with skeleton code. This supports self-contained ordered blocks, and blocks with windows (for execution pool).
1. Add the new `ObservedOrderedBlock` type, and integrate it into the pending block store.
2. Add `ObservedOrderedBlock` to the ordered block store.
3. Add a new hash index to the pending block store (including tests). This will be used for window dependency checking and traversal.
In the next PR, I'll work on the window dependency traversal logic, and start working on the new buffering and clearing logic.
> [Consensus Observer] Add ObservedOrderedBlock to various stores.

- .github/actions/wait-images-ci/action.yaml
- .github/workflows/forge-continuous-land-blocking-test.yaml
Add a new workflow that runs Forge land-blocking tests (e2e (realistic_env_max_load), compat, and framework upgrade) on the main branch every hour. 
This uses a new composite action that waits for the build (artifacts) on a given commit.
Note on the future of continuous Forge jobs:
- There's some amount of copy-pasta between where the land blocking tests are actually defined `docker-build-test.yaml` and the new workflow `forge-continuous-land-blocking-test.yaml`, but any additional factoring out at this point is complicated and error prone.
- In the future we might consider moving the logic of how to trigger these Forge runs outside of GHA such as in PIES
Workflow dispatch on PR merge
Also canary on push to this branch
The test plan and the new workflow
> [gha] continuous forge on main, composite action for wait images

- Cargo.lock
- Cargo.toml
- experimental/bulk-txn-submit/Cargo.toml
- experimental/bulk-txn-submit/README
- experimental/bulk-txn-submit/src/coordinator.rs
- experimental/bulk-txn-submit/src/event_lookup.rs
- experimental/bulk-txn-submit/src/indexer.rs
- experimental/bulk-txn-submit/src/lib.rs
- experimental/bulk-txn-submit/src/main.rs
- experimental/bulk-txn-submit/src/metrics.rs
- experimental/bulk-txn-submit/src/workloads.rs
It can be used for submitting transactions from single account, it can be used for submitting transactions from a pool of worker accounts.
It can be used for submitting list of transactions from a file.
> Create extensible Bulk Txn Submit script

- aptos-move/framework/aptos-experimental/doc/overview.md
- aptos-move/framework/aptos-experimental/doc/test_derivable_account_abstraction_ed25519_hex.md
- aptos-move/framework/aptos-experimental/sources/test_derivable_account_abstraction_ed25519_hex.move
- aptos-move/vm-genesis/src/lib.rs
- third_party/move/move-core/types/src/account_address.rs
Adds a DAA authentication function to be later used by the aptos-ts-sdk in tests
Related to https://github.com/aptos-labs/aptos-ts-sdk/pull/648
With a local build against the aptos-ts-sdk
> add test daa auth function to the experimental framework

- crates/aptos/CHANGELOG.md
- crates/aptos/src/account/balance.rs
Removes a TODO around FA balances in the CLI
```
.\target\debug\aptos account balance --account 0x5 --url https://api.mainnet.aptoslabs.com --coin-type 0xA
{                      
"Result": [
{
"asset_type": "fa",
"coin_type": "0xa",
"balance": 10000
}
]
}
```
> [cli] Add ability to lookup fungible asset balance from CLI

- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/transaction_validation.rs
- aptos-move/framework/aptos-framework/doc/account_abstraction.md
- aptos-move/framework/aptos-framework/doc/domain_account_abstraction_ed25519_hex.md
- aptos-move/framework/aptos-framework/doc/transaction_validation.md
- aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
- aptos-move/framework/aptos-framework/sources/transaction_validation.move
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.move
- aptos-move/framework/src/natives/dispatchable_fungible_asset.rs
- aptos-move/framework/src/natives/function_info.rs
- types/src/on_chain_config/aptos_features.rs
Gating was requiring AA to be enabled before dAA. 
Based on recent discussions, we want to enable dAA first, so adjusting gating that way.
One detail - AA registration wasn't gated, only usage, I added gating for it now. Once we decide to enable AA, we should see if any changes we make need to be applied to anything already registered 
Tested on a stacked PR, with disabling AA flag, and enabling dAA flag, confirming dAA flow works e2e (igor/daa_example_test)
> Allow dAA before AA

- .github/workflows/forge-continuous-land-blocking-test.yaml
Minor fixes to the forge conginuous land blocking test:
- use the timestamp in the forge namespace name, to avoid collisions and preemption
- remove the schedule trigger. instead, we can trigger this via PIES and workflow_dispatch. We need these runs to be relatively timely, and the GHA scheduler does not guarantee that. 
- shorten `workflow-dispatch` to `w-d` in the namespace name
- remove concurrency group. the jobs run in k8s anyways and not on the runner, so this ensures that the runners stay alive so long as the forge jobs in k8s are alive, and never preempted
canary on push, build images with labels: https://github.com/aptos-labs/aptos-core/actions/runs/14205975471
Also by sanity check, our longest test name is under 64 char
```
echo "forge-framework-upgrade-clbt-schedule-$(date …
```
> [gha] forge clbt fix

- .github/workflows/workflow-run-replay-verify-on-archive.yaml
The TTL controller already takes care of cleaning up unused disks. Also, deleting all unused disks project-wide is dangerous because it could delete disks unrelated to the current replay-verify run.
> Remove disk cleanup from replay-verify

- ecosystem/indexer-grpc/indexer-grpc-table-info/src/table_info_service.rs
- storage/indexer/src/db_v2.rs
For nested table case in the same batch, when the outer table is processed in ram, but before it got stored into db, the inner table handle may still be added into the `pending_on` (in a different thread, because the in memory `result` is not shared among threads). In this case we shouldn't blindly cleanup the `pending_on` map.
> [Fix] Fix table info handling.

- ecosystem/indexer-grpc/indexer-grpc-manager/src/data_manager.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/file_store_uploader.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/grpc_manager.rs
- ecosystem/indexer-grpc/indexer-grpc-manager/src/metrics.rs
- ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator_v2/file_store_operator.rs
The file store version in cache (for gc purpose) need to be initialized after the file store uploader recovers.
Also added several logs and metrics.
>  [Indexer-Grpc-V2] Fix the version tracking.

- third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16198.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16198.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16199.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16199.move
Lambda lifter uses the field `free_locals` and `free_params` to store locals and params to be captured when generating closure. However, for the code below, `x` is captured when analyzing the inner lambda and will be dropped when analyzing the outer one.  
```
let x = ...;
let f: | | | | u64 has drop = || || x;
```
This PR removes the logic to drop free locals and params so that free variables/params can also be captured in the outer lambda.
close #16198 
close #16199 
2) added a new test case.
Whether the fix does not introduce new issues.
> [compiler-v2] append free vars and params from inner lambda during lambda lifting

- third_party/move/move-binary-format/serializer-tests/tests/serializer_tests.rs
- third_party/move/move-binary-format/src/deserializer.rs
- third_party/move/move-binary-format/src/file_format.rs
- third_party/move/move-binary-format/src/serializer.rs
- third_party/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/dependencies_tests.rs
- third_party/move/move-bytecode-verifier/src/features.rs
- third_party/move/move-compiler-v2/src/file_format_generator/mod.rs
- third_party/move/move-ir-compiler/move-ir-to-bytecode/src/compiler.rs
- third_party/move/move-vm/integration-tests/src/tests/invariant_violation_tests.rs
- third_party/move/move-vm/integration-tests/src/tests/leak_tests.rs
- third_party/move/move-vm/integration-tests/src/tests/vm_arguments_tests.rs
This adds access specifiers to compiled scripts in binary format v8. They are not supported anywhere yet, but this change will allow us to add support later without breaking binary compatibility of scripts and requiring new v9 binary format.
Actual usage of this feature is gated by ENABLE_RESOURCE_ACCESS_CONTROL feature, which is not enabled.
> [move-vm][rac] Add access specifiers to CompiledScript in binary format v8

- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/resolve_from_storage.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/resolve_from_storage.move
- third_party/move/move-vm/runtime/src/loader/function.rs
Function values if coming from storage are resolved, and layouts of captured arguments are constructed and checked. If captured argument is generic, the function parameter is generic as well and needs to be instantiated.
Commenting out instantiation results in test failing with:
```
thread 'tests::function_value_tests::test_function_value_resolution' panicked at third_party/move/move-vm/integration-tests/src/tests/function_value_tests.rs:71:7:
Call must succeed: VMError { major_status: UNKNOWN_INVARIANT_VIOLATION_ERROR, sub_status: None, message: Some("No type layout for TyParam(0) @Unknown invariant violation generated:\nIn function backtrace::backtrace::libunwind::trace::h62ffc7317c823599 at /Users/george/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace …
```
> [vm] function value resolution with  generic captured arguments

- aptos-move/framework/aptos-framework/doc/aptos_account.md
- aptos-move/framework/aptos-framework/doc/genesis.md
- aptos-move/framework/aptos-framework/doc/nonce_validation.md
- aptos-move/framework/aptos-framework/doc/overview.md
- aptos-move/framework/aptos-framework/doc/transaction_validation.md
- aptos-move/framework/aptos-framework/sources/aptos_account.move
- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/nonce_validation.move
- aptos-move/framework/aptos-framework/sources/transaction_validation.move
- aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
- aptos-move/framework/aptos-framework/sources/vesting.move
- aptos-move/framework/aptos-token/doc/token.md
- aptos-move/framework/aptos-token/sources/token.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.move
- third_party/move/move-examples/diem-framework/move-packages/DPN/sources/DiemAccount.move
> [RFC] Prologue and nonce validation for orderless transactions

- .github/workflows/indexer-protos-sdk-update.yaml
Update indexer-protos-sdk-update workflow to trigger SDK updates when proto changes are detected. Previously, the workflow would fail if generated proto code changed, but now it detects these changes and sets an output variable that triggers the SDK update job when necessary.
> udpate proto change check workflow

- docker/image-helpers.js
- docker/release-images.mjs
Fix a bug where `crane` is not referenced properly in the release scripts
Dry run exercises a codepath with `crane` CLI: namely check that `crane version` runs correctly and doesn't have a reference error
```
$ IMAGE_TAG_PREFIX=devnet AWS_ACCOUNT_ID=bla GCP_DOCKER_ARTIFACT_REPO=us-docker.pkg.dev/aptos-registry/docker GIT_SHA=$(git fetch && git rev-parse origin/main) ./docker/release-images.mjs --wait-for-image-seconds=3600 --dry-run
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 413ms
$ git rev-parse --show-toplevel
/Users/rustielin/Code/aptos-core
$ command -v crane
/opt/homebrew/bin/crane
$ crane version
0.12.1
INFO: crane version: 0.12.1
INFO: dry run: true
INFO: image release group: aptos-node
INFO: image names to release: …
```
> [release] fix crane install for release images

- consensus/src/consensus_observer/observer/active_state.rs
it's possible to have an interesting race in this gc function with get_last_ordered_block
1. handle_committed_blocks gc'ed round 6499 in ordered block store
2. get_last_ordered_block reads the ordered block store and see None
3. get_last_ordered_block reads the root and see 6498 (old one)
4. it decides to forward block 6499 again to pipeline
5. handle_committed_block updates the root to 6499
> [CO] fix a race of inconsistent data view

- testsuite/testcases/src/compatibility_test.rs
Compat test was failing because we were trying to send traffic to the node when the node was upgrading..some time this causes race condition and the emitter job can't start. Change the test to upgrade the node first before sending the traffic. 
Ran the compat tests few times and it succeeded.
> fix compat test

- Cargo.lock
- testsuite/forge-test-runner-template.yaml
- testsuite/testcases/Cargo.toml
- testsuite/testcases/src/compatibility_test.rs
Few changes to simplify and fix compat test:
* Removing tokio_scoped
* Also explicitly add `RUST_LOG=info` in the test runner to get more logs
* Increase the upgrade delay to 60s to account for cold start of a new container/image
Run Forge tests on PR 
Test output
> [forge] compat simplify

- .gitignore
- testsuite/fuzzer/.cargo/config.toml
- testsuite/fuzzer/.gitignore
- testsuite/fuzzer/fuzz/Cargo.toml
- testsuite/fuzzer/fuzz/build.rs
- testsuite/fuzzer/fuzz/fuzz_targets/move/aptosvm_publish_and_run.rs
Added compile time and runtime checks to disable gas divergence checks in the move_aptosvm_publish_and_run fuzzer, which is time sensitive and triggers many false positives while generating coverage reports.
Generated a coverage report offline
N/A
> [Fuzz] Disable gas check in fuzzer while generating coverage

- testsuite/fuzzer/.cargo/config.toml
Revert --no-rosegment linker flag
N/A
N/A
> [Fuzz] Revert --no-rosegment linker flag

- testsuite/fuzzer/fuzz.sh
OSS-Fuzz builds are [failing](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#aptos-core) for a couple of days. This might be due to changes on their side, but since KILL-9 in the linking phase previously meant OOM on their machines, it limits the built threat to 4.
Only available on Google systems.
N/A
> [OSS-Fuzz] Tentative: limit memory while linking in oss-fuzz

- third_party/move/tools/move-linter/src/model_ast_lints.rs
- third_party/move/tools/move-linter/src/model_ast_lints/nonminimal_bool.rs
- third_party/move/tools/move-linter/tests/model_ast_lints/nonminimal_bool.exp
- third_party/move/tools/move-linter/tests/model_ast_lints/nonminimal_bool.move
This change adds lint check for additional boolean identities - namely those that a involve boolean literal (true or false) used inside a boolean operator (and, or, not, iff, implies).
New tests were added for each additional case that linter now covers.
In the modified file "nonminimal_bol.move", see the test for "fun combo". This entire expression is equivalent to true, but the lint rule as it is currently implemented only looks a single operator at a time (so this conditional gets three separate warnings). Is this an issue?
> Expand lint checker to cover additional boolean identities

- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16336.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16336.move
- third_party/move/move-compiler-v2/tests/checking/typing/recursive_local.exp
- third_party/move/move-compiler-v2/tests/checking/typing/recursive_local.move
- third_party/move/move-model/src/ty.rs
The `Substitution::bind` function could create a cyclic substitution by evaluating constraints after the occurrs check and before the variable was assigned, causing stackoverflow crashes. Kind of a reentrancy problem.
This moves the occurs check after constraint evaluation. As we are specializing types before assignment since a while anyway, the occurs check logic could be simplified.
Closes #16336
New test
> [compiler] Fix cyclic substitution bug

- aptos-move/framework/aptos-framework/doc/account.md
- aptos-move/framework/aptos-framework/sources/account/account.move
- aptos-move/framework/aptos-framework/sources/account/account.spec.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
This adds a rotate auth key private entry function whose input is a public key (in bytes).
Added a spec but the function is very simple.
> Add a rotate auth key from public key private entry function

- crates/aptos/e2e/cases/account.py
If I understand the test correctly, it initializes an account (with 0 octas), then funds it with the faucet and is supposed to test that the balance afterwards is equal to the amount transferred. Therefore the error test should be `!=` instead of `==`.
> Fix CLI e2e test case `test_account_fund_with_faucet`

- Cargo.lock
- aptos-move/aptos-transaction-simulation/src/account.rs
- aptos-move/aptos-transaction-simulation/src/state_store.rs
- aptos-move/e2e-move-tests/Cargo.toml
- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-move-tests/src/tests/mod.rs
- aptos-move/e2e-move-tests/src/tests/remote_state.rs
- aptos-move/e2e-tests/src/executor.rs
This introduces a few e2e Move tests demonstrating how to use `MoveHarness`'s newly-added network-forking feature, allowing simulations on top of the current state of a remote Aptos network.
> [e2e move tests] simulate with remote states

- crates/aptos-rest-client/src/lib.rs
- testsuite/testcases/src/compatibility_test.rs
Temporarily increase the upgrade delay from 1m to 5m to observe if it stabilizes the test.
> Increase forge test upgrade delay to 5 mins

- aptos-move/framework/aptos-framework/doc/dispatchable_fungible_asset.md
- aptos-move/framework/aptos-framework/sources/dispatchable_fungible_asset.move
- aptos-move/framework/aptos-framework/tests/clamped_token.move
- aptos-move/framework/aptos-framework/tests/clamped_token_tests.move
- aptos-move/framework/aptos-framework/tests/nil_op_token_tests.move
This PR removes the balance check in the `dispatchable_fungible_asset` module that was verifying the withdrawn amount matched the requested amount. The check was unnecessary and was causing tests to fail. Additionally, it enhances the `ten_x_token` test module by implementing and registering proper withdraw and deposit dispatch functions.
The changes have been tested through the existing `nil_op_token_tests` which previously expected a failure but now passes correctly. The test verifies that withdrawal and deposit operations work properly without the balance check.
- Removal of the balance check in `dispatchable_fungible_asset.move` which was comparing start and end balances
- Implementation of withdraw and deposit functions in the `ten_x_token.move` test module
- Registration of these …
> [aptos-framework] Remove balance checks in DFA

- Cargo.lock
- api/src/context.rs
- api/src/transactions.rs
- aptos-move/aptos-validator-interface/src/storage_interface.rs
- crates/aptos-rest-client/src/lib.rs
- peer-monitoring-service/server/src/tests.rs
- state-sync/state-sync-driver/src/tests/mocks.rs
- state-sync/storage-service/server/src/tests/mock.rs
- storage/aptosdb/src/db/fake_aptosdb.rs
- storage/aptosdb/src/db/include/aptosdb_reader.rs
- storage/aptosdb/src/db/mod.rs
- storage/aptosdb/src/db/test_helper.rs
- storage/aptosdb/src/transaction_store/mod.rs
- storage/aptosdb/src/transaction_store/test.rs
- storage/indexer/src/db_indexer.rs
- storage/indexer/src/indexer_reader.rs
- storage/storage-interface/src/lib.rs
- testsuite/forge/src/interface/aptos.rs
- testsuite/smoke-test/src/rest_api.rs
- testsuite/smoke-test/src/rosetta.rs
- testsuite/smoke-test/src/transaction.rs
- types/src/indexer/indexer_db_reader.rs
- types/src/transaction/mod.rs
- types/src/unit_tests/transaction_test.rs
Some of the API calls and DB functions use sequence numbers and only work on sequence number based transactions. These functions are renamed with `_ordered_` tag.
> Rename some DB functions that work only for ordered transactions

- .github/workflows/docker-build-test.yaml
- .github/workflows/forge-continuous-land-blocking-test.yaml
Increased the `FORGE_RUNNER_DURATION_SECS` for compatibility tests from 300 seconds (5 minutes) to 1800 seconds (30 minutes) in both the Docker build test workflow and the continuous land-blocking test workflow. This change allows compatibility tests to run for a longer duration, providing more thorough testing.
Previously in https://github.com/aptos-labs/aptos-core/pull/16387 the upgrade time was increased for debugging and that has caused all compat tests to timeout
The change modifies CI workflow parameters and will be tested in the CI pipeline itself when compatibility tests run with the new duration setting.
- Verify that the increased test duration is appropriate for compatibility testing needs
- Confirm that CI resources can accommodate the longer test runs
> [forge] Bump timeout for compat

- .gitignore
Only touches the .gitignore to ignore local cursor rules directory.
> Git ignore rule for cursor rules

- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-move-tests/src/tests/remote_state.data/test_package/Move.toml
- aptos-move/e2e-move-tests/src/tests/remote_state.data/test_package/sources/test.move
- aptos-move/e2e-move-tests/src/tests/remote_state.rs
- aptos-move/e2e-tests/src/executor.rs
This adds two new e2e move tests, demonstrating how one can simulate code upgrades with remote states. 
Additionally, it introduces an additional interface that allows one to specify an API key, plus some slight adjustments to the docs.
> [e2e move tests] add more examples using remote states

- aptos-move/aptos-release-builder/src/components/feature_flags.rs
- consensus/src/dag/rb_handler.rs
- consensus/src/round_manager.rs
- types/src/jwks/jwk/mod.rs
- types/src/jwks/mod.rs
- types/src/jwks/unsupported/mod.rs
- types/src/on_chain_config/aptos_features.rs
- types/src/validator_txn.rs
Adding some types needed for per-key JWK consensus.
Currently the jwk consensus is per-issuer: validators agree on the key set returned by provider API. This may not be enough, especially if the provider:
- rolls out a key one region by another, and
- allows concurrent rollouts of multiple keys.
In per-key JWK consensus, validators agree on key-level diffs like "provider A key 1 should be removed", "provider B key 2 should be upserted", which should ensure progress even if the provider equivocates as described above.
UT
n/a
> per-key jwk consensus 1: types

- testsuite/smoke-test/src/jwks/jwk_consensus_per_key.rs
- testsuite/smoke-test/src/jwks/mod.rs
Adding a smoke test needed for per-key JWK consensus.
Currently the jwk consensus is per-issuer: validators agree on the key set returned by provider API. This may not be enough, especially if the provider:
- rolls out a key one region by another, and
- allows concurrent rollouts of multiple keys.
In per-key JWK consensus, validators agree on key-level diffs like "provider A key 1 should be removed", "provider B key 2 should be upserted", which should ensure progress even if the provider equivocates as described above.
n/a
n/a
> per-key jwk consensus 2: smoke test

- aptos-move/framework/aptos-framework/doc/jwks.md
- aptos-move/framework/aptos-framework/sources/jwks.move
- aptos-move/framework/move-stdlib/doc/features.md
- aptos-move/framework/move-stdlib/sources/configs/features.move
Framework changes needed for per-key JWK consensus.
Currently the jwk consensus is per-issuer: validators agree on the key set returned by provider API. This may not be enough, especially if the provider:
- rolls out a key one region by another, and
- allows concurrent rollouts of multiple keys.
In per-key JWK consensus, validators agree on key-level diffs like "provider A key 1 should be removed", "provider B key 2 should be upserted", which should ensure progress even if the provider equivocates as described above.
UT
n/a
> per-key jwk consensus 3: framework changes

- crates/aptos-jwk-consensus/src/jwk_manager/mod.rs
- crates/aptos-jwk-consensus/src/jwk_manager/tests.rs
- crates/aptos-jwk-consensus/src/lib.rs
- crates/aptos-jwk-consensus/src/mode/mod.rs
- crates/aptos-jwk-consensus/src/mode/per_issuer.rs
- crates/aptos-jwk-consensus/src/observation_aggregation/mod.rs
- crates/aptos-jwk-consensus/src/observation_aggregation/tests.rs
- crates/aptos-jwk-consensus/src/types.rs
- crates/aptos-jwk-consensus/src/update_certifier.rs
- types/src/jwks/mod.rs
Refactor per-issuer implementation so some logic can later be shared with per-key logic.
Currently the jwk consensus is per-issuer: validators agree on the key set returned by provider API. This may not be enough, especially if the provider:
- rolls out a key one region by another, and
- allows concurrent rollouts of multiple keys.
In per-key JWK consensus, validators agree on key-level diffs like "provider A key 1 should be removed", "provider B key 2 should be upserted", which should ensure progress even if the provider equivocates as described above.
Existing UT
n/a
> per-key jwk consensus 4: no-op refactoring per-issuer logic

- .github/workflows/lint-test.yaml
Move prover tests fail if Boogie is not locally installed.
> Rust unit tests require the Move prover tools

- .github/actions/move-prover-setup/action.yaml
- .github/actions/rust-setup/action.yaml
- .github/workflows/windows-build.yaml
The new version switches to v4 of the `checkout` and `upload-artifact` actions, adds support for Cargo.lock v4, as well as improving cacheing.
> Update Swatinem/rust-cache to 2.7.8

- aptos-move/framework/tests/move_unit_test.rs
- aptos-move/move-examples/duplicate_scripts/.gitignore
- aptos-move/move-examples/duplicate_scripts/Move.toml
- aptos-move/move-examples/duplicate_scripts/scripts/first.move
- aptos-move/move-examples/duplicate_scripts/scripts/second.move
- aptos-move/move-examples/duplicate_scripts/sources/main.move
- aptos-move/move-examples/tests/move_unit_tests.rs
- third_party/move/extensions/move-table-extension/tests/move_unit_tests.rs
- third_party/move/move-compiler-v2/src/file_format_generator/mod.rs
- third_party/move/move-stdlib/tests/move_unit_test.rs
- third_party/move/tools/move-cli/src/base/test.rs
- third_party/move/tools/move-package/src/compilation/compiled_package.rs
- third_party/move/tools/move-package/tests/test_sources/compilation/case_insensitive_check/Move.exp
- third_party/move/tools/move-package/tests/test_sources/compilation/one_dep_with_scripts/Move.exp
- third_party/move/tools/move-unit-test/tests/pkg_tests.rs
With this PR, the compiler now throws an error if there are script functions in a package that have duplicate names.
Note: the bytecode files generated for scripts no longer have an "_<number>" suffix.
In addition, this PR contains some behavioral changes to some unit testing APIs that exited on error instead of returning an `Result::Err`.
- Added a new test that shows that the compiler throws an error.
> [compiler-v2] Error on duplicate script function names

- aptos-move/framework/aptos-framework/doc/solana_derivable_account.md
- aptos-move/framework/aptos-framework/sources/account/common_account_abstractions/solana_derivable_account.move
- testsuite/smoke-test/src/account_abstraction.rs
Add a warning message to the message format when signing a message on the wallet. This is to add another extra step of security, especially when signing a message with wallets that dont implement SIWS and therefore dont do domain verification.
SIWS
Sign Message
local and unit tests
> Modify solana derivable account message format

- third_party/move/tools/move-linter/src/lib.rs
- third_party/move/tools/move-linter/src/model_ast_lints.rs
- third_party/move/tools/move-linter/src/model_ast_lints/almost_swapped.rs
- third_party/move/tools/move-linter/src/utils.rs
- third_party/move/tools/move-linter/tests/model_ast_lints/almost_swapped.exp
- third_party/move/tools/move-linter/tests/model_ast_lints/almost_swapped.move
This adds a linting rule for catching "almost swapped" sequences of assignments (such as `a = b; b = a;`). As implemented, this specifically targets simple assignments: those that involve local vars or structs, and do not contain any non-builtin functions (including vector functions)/global storage accesses.
A testing file was added (almost_swapped.move).
1) Is utils setup in a good way? I made a utils file because other lint rules (such as self assignment, `a = a;`) is likely to use this same functionality. I am new to rust though, and am not sure if this is the idiomatic way to handle such functions.
2) This lint rule will catch `a = a; a = a;`. The self-assignment rule (yet to be added) will also catch this. Is that fine? Should I disable almost_swapped from catching self-assignment …
> [Linter] Added support for almost swapped lint check

- third_party/move/tools/move-linter/src/model_ast_lints/nonminimal_bool.rs
- third_party/move/tools/move-linter/tests/model_ast_lints/nonminimal_bool.exp
- third_party/move/tools/move-linter/tests/model_ast_lints/nonminimal_bool.move
The initial version of nonminimal bool had a small typo in the `!` case (incorrectly stating that `!b` is equivalent `b`). This fixes that, slightly cleans up the message, and takes out some unnecessary whitespace in the tests.
Existing tests sufficiently cover this.
N/A
> [Linter] Fixed a typo in nonminimal bool lint

- third_party/move/tools/move-linter/src/lib.rs
- third_party/move/tools/move-linter/src/model_ast_lints.rs
- third_party/move/tools/move-linter/src/model_ast_lints/almost_swapped.rs
- third_party/move/tools/move-linter/src/model_ast_lints/self_assignment.rs
- third_party/move/tools/move-linter/src/utils.rs
- third_party/move/tools/move-linter/tests/model_ast_lints/almost_swapped.exp
- third_party/move/tools/move-linter/tests/model_ast_lints/almost_swapped.move
- third_party/move/tools/move-linter/tests/model_ast_lints/self_assignment.exp
- third_party/move/tools/move-linter/tests/model_ast_lints/self_assignment.move
This adds a linting rule for catching "self assignments" (such as `a = a;`, `a.b = a.b;`, `let a = x;`, etc). As implemented, this specifically targets simple assignments: those that involve local vars or structs, and do not contain any non-builtin functions (including vector functions)/global storage accesses. Note that unlike the almost_swapped lint, this lint additionally catches let statements.
A testing file was added (self_assignment.move).
This is similar in nature to the almost swapped lint and has the same area of concerns (namely, is there any statement we may unintentionally lint).
> [Linter] added self assignment lint rule

- aptos-move/framework/aptos-framework/doc/config_buffer.md
- aptos-move/framework/aptos-framework/doc/consensus_config.md
- aptos-move/framework/aptos-framework/doc/execution_config.md
- aptos-move/framework/aptos-framework/doc/gas_schedule.md
- aptos-move/framework/aptos-framework/doc/jwk_consensus_config.md
- aptos-move/framework/aptos-framework/doc/jwks.md
- aptos-move/framework/aptos-framework/doc/keyless_account.md
- aptos-move/framework/aptos-framework/doc/randomness_api_v0_config.md
- aptos-move/framework/aptos-framework/doc/randomness_config.md
- aptos-move/framework/aptos-framework/doc/randomness_config_seqnum.md
- aptos-move/framework/aptos-framework/doc/version.md
- aptos-move/framework/aptos-framework/sources/configs/config_buffer.move
- aptos-move/framework/aptos-framework/sources/configs/config_buffer.spec.move
- aptos-move/framework/aptos-framework/sources/configs/consensus_config.move
- aptos-move/framework/aptos-framework/sources/configs/execution_config.move
- aptos-move/framework/aptos-framework/sources/configs/gas_schedule.move
- aptos-move/framework/aptos-framework/sources/configs/jwk_consensus_config.move
- aptos-move/framework/aptos-framework/sources/configs/randomness_api_v0_config.move
- aptos-move/framework/aptos-framework/sources/configs/randomness_config.move
- aptos-move/framework/aptos-framework/sources/configs/randomness_config_seqnum.move
- aptos-move/framework/aptos-framework/sources/configs/version.move
- aptos-move/framework/aptos-framework/sources/jwks.move
- aptos-move/framework/aptos-framework/sources/keyless_account.move
Add `config_buffer::extract_v2()` and deprecate `config_buffer::extract()` which has incorrect visibility.
Existing UT
n/a
> config_buffer fix

- third_party/move/move-compiler-v2/src/env_pipeline/closure_checker.rs
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/generic_wrapper_abilities.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/generic_wrapper_abilities.move
They were ignored since during the run of the closure checker, implicit constructors have not yet been inserted, which happens at bytecode gen time.
Closes #16158
test case
> [compiler] Handling function wrapper types in closure checker

- third_party/move/move-compiler-v2/legacy-move-compiler/src/parser/syntax.rs
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16195.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16195.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16195_variant1.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16195_variant1.move
#16195 is a trivial bug. The function [`is_start_of_type`](https://github.com/aptos-labs/aptos-core/blob/fa9adf8fc987993e25f38f1ec76bf861d36d800a/third_party/move/move-compiler-v2/legacy-move-compiler/src/parser/syntax.rs#L2604-L2609) does not consider `||` (the so-called `Tok::PipePipe`) as a start of a type. The PR fixes it by adding support for `Tok::PipePipe` in  `is_start_of_type`.
- Add the test case reported by #16195 to move-compiler-v2/tests; See [bug_16195.move](https://github.com/aptos-labs/aptos-core/blob/3ac112ec51f8176d3fce764d812a920eca784ecd/third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16195.move) and other variants to test trickier cases and the impacts on `OR` operations.
- Re-run all `tests` and `transactional-tests` under `move-compiler-v2`
- …
> fix issue #16195

- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/inferred_default_with_abilities.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/inferred_default_with_abilities.move
- third_party/move/move-model/src/ty.rs
Inferred type defaults where not checked for abilities. Closes #16405
New test
> [compiler] Fixing a bug in inferred type defaults

- crates/aptos/CHANGELOG.md
- crates/aptos/src/move_tool/fmt.rs
This is a bug fix. Currently, if `aptos move fmt --package-path /path/typo` is called such that `/path/typo` does not exist, then this command is treated as though no package path was provided and the current directory is instead reformatted. The pr here fixes that. This pr also reformats the cli error message outputs to convey the actual path to the user instead of the debug-mode path with escape characters.
Manual testing
For cli error messages: I assume that displaying actual file error paths like
`  "Error": "Unexpected error: Unable to find package manifest in /Users/jake/Desktop or in its parents"
`
is better than displaying with escaped chars like 
`  "Error": "Unexpected error: Unable to find package manifest in \"/Users/jake/Desktop\" or in its parents"
`
Let me know if this is …
> [CLI Movefmt] Fix bug where movefmt runs over curr directory if package path given does not exist

- .github/workflows/cli-e2e-tests.yaml
update the poetry version to make cli-e2e-tests pass.
run locally.
> update cli-e2e-tests poetry version

- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/receiver_ambiguous.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/receiver_ambiguous.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/field_access_closure.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/field_access_closure.move
- third_party/move/move-model/src/ty.rs
A call of the form `f.bar()` is always interpreted as a method call, i.e., it is equivalent to `bar(f)` (or `bar(&f)` or `bar(&mut f)`, as appropriate for the context).
However, with the introduction of function values, `f` may be a struct with field `bar` that is a function value. In such a case, `f.bar()` leads to an error saying there is no receiver method `bar`. In this PR, we provide an additional hint saying, surround the field access with parenthesis if you intend to call the closure in field `bar`.
Closes #16448.
Added new tests to showcase the hints.
> [compiler-v2] Provide error hints when trying to call a closure via field access

- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/returning_a_function.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/returning_a_function.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16408.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16408.move
- third_party/move/move-model/src/builder/exp_builder.rs
Closes #16408.
When we type checked the expression `return exp`, the type of `exp` was expected to be the return type of the function containing this expression. This is not correct if we are inside a lambda expression, in which case, we should instead expect the return type of the nearest enclosing lambda expression.
Previously, we would admit:
```move
fun make_bad_func_1(): |u64|u64 has copy + drop {
|x: u64| {
return (|y| x + y)
}
}
```
But this would fail bytecode verification.
Now we fail type check on this code.
- Added new tests.
> [compiler-v2] Fix type checking of returns within lambdas

- third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs
- third_party/move/move-compiler-v2/tests/checking/typing/recursive_function_types.exp
- third_party/move/move-compiler-v2/tests/checking/typing/recursive_function_types.move
#16155 reports a recursive structure definition that involves function types and bypasses compiler checks. This is because the existing [recursive struct checker](https://github.com/aptos-labs/aptos-core/blob/jun/bug_16155/third_party/move/move-compiler-v2/src/env_pipeline/recursive_struct_checker.rs#L60) does not check function types nested inside structure definitions.
The fix adds support for function types, as well as other missing types (tuple and reference).
Close #16155
- New [compiler test cases](https://github.com/aptos-labs/aptos-core/blob/jun/bug_16155/third_party/move/move-compiler-v2/tests/checking/typing/recursive_function_types.move) added
- Existing compile tests and transactional_tests
- Potential side effects of new supports of other types in [recursive struct …
> Fix issue #16155

- aptos-move/aptos-validator-interface/src/lib.rs
Remote state value fetches were not in parallel as expected.
```
RUST_LOG=error cargo run --release -p aptos-debugger move execute-past-transactions --begin-version 2664750000 --limit 100 --rest-endpoint http://localhost:8080 --skip-result --concurrency-level 8
```
result:
```
[100 txns from 2664750000] Finished execution round 1/1 with concurrency_level=8 in 30990ms
```
vs (without the fix):
```
[100 txns from 2664750000] Finished execution round 1/1 with concurrency_level=8 in 52732ms
```
> [debugger] release sender lock early

- aptos-move/framework/aptos-experimental/doc/confidential_asset.md
- aptos-move/framework/aptos-experimental/sources/confidential_asset/confidential_asset.move
This updates the confidential_asset module to use dispatchable_fungible_asset::transfer instead of fungible_asset::transfer.  This is needed to cover both dispatchable and non-dispatchable cases.
Deposit and withdraw use primary_fungible_store which utilizes   dispatchable_fungible_asset.
Todo
> Update confidential asset transfer to use dispatchable_fungible_asset

- third_party/move/move-compiler-v2/tests/ability-check/v1-typing/instantiate_signatures.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/constraints.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/ref_ref.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/ref_ref.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/ref_to_ref_inferred.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/ref_to_ref_inferred.move
- third_party/move/move-compiler-v2/tests/checking/abilities/instantiate_signatures.exp
- third_party/move/move-compiler-v2/tests/checking/typing/ref_to_a_ref.exp
- third_party/move/move-compiler-v2/tests/checking/typing/ref_to_a_ref.move
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/builder/module_builder.rs
- third_party/move/move-model/src/model.rs
- third_party/move/move-model/src/ty.rs
With this PR, the compiler checks various places where you can create reference of a reference. Overall, this fixes three different bugs.
1. This closes #16491.
2. Also found that even before function values, we could cause bytecode verification failure:
```move
fun test3(x: &mut &mut u64): &mut &mut u64 {x}
```
would result in:
```
bug: bytecode verification failed with unexpected status code `INVALID_SIGNATURE_TOKEN`. This is a compiler bug, consider reporting it.
Error message: reference not allowed at type 0
┌─ TEMPFILE:2:1
│  
2 │ ╭ module 0xc0ffee::m {
3 │ │     fun test3(x: &mut &mut u64): &mut &mut u64 {x}
4 │ │ }
│ ╰─^
```
This is also fixed.
3. Finally, we can cause reference to a reference without providing any explicit types anywhere, just through type inference:
```move
fun …
```
> [compiler-v2] Compiler checks for various reference of a reference

- aptos-move/block-executor/src/lib.rs
- aptos-move/block-executor/src/scheduler_status.rs
- aptos-move/block-executor/src/scheduler_v2.rs
Introduces the foundation for BlockSTMv2 scheduler by adding two new modules:
1. `scheduler_status.rs`: Implements a transaction status management system with:
- A well-defined transaction lifecycle (PendingScheduling → Executing → Executed/Aborted)
- Two-step abort mechanism (try_abort + finish_abort) for efficient concurrency control
- Stall mechanism implementation for a given status (to reduce cascading aborts by tracking dependencies between transactions). SchedulerV2 will manage stall signals across the block.
- Lock-free dependency resolution flags
2. `scheduler_v2.rs`: Provides the execution queue management infrastructure:
- Manages scheduling and rescheduling of transactions
- Exposes a proxy interface to execution status file / structure.
The implementation includes detailed …
> BlockSTMv2 PR [1/n]: scheduler_status and tests

- third_party/move/move-compiler-v2/tests/checking/typing/nested_tuple_err.exp
- third_party/move/move-compiler-v2/tests/checking/typing/return_nested_tuple.exp
- third_party/move/move-compiler-v2/tests/checking/typing/return_nested_tuple.move
- third_party/move/move-model/src/builder/exp_builder.rs
Closes #16539.
Return types of functions could have nested tuples, but unless an expression of that type was created, we could end up with a compiler ICE, which we fix with this PR.
- Existing tests
- A new test has been added which used to ICE before, but gives a compiler error now.
> [compiler-v2] Error on returning nested tuples

- consensus/src/network.rs
> [!WARNING]  
> Should not be merged until https://github.com/aptos-labs/aptos-core/pull/14076 is included in the next release
Changes `request_block` to use new `ConsensusMsg::BlockRetrievalRequest` instead of `ConsensusMsg::DeprecatedBlockRetrievalRequest`.
> [exec-pool] Enable new ConsensusMsg::BlockRetrievalRequest

- aptos-move/framework/aptos-framework/doc/ethereum_derivable_account.md
- aptos-move/framework/aptos-framework/sources/account/common_account_abstractions/ethereum_derivable_account.move
- testsuite/smoke-test/src/account_abstraction.rs
We use the `domain` as the `uri` in the message for the EVM dAA, but while it works locally (i.e `localhost:3001`) it is misleading since in production (i.e `aptos-labs.github.io`) it fails on the client (wallet) verification because it does not follow the `uri` format which is `<scheme>:<path>`.
Since we need to construct the message the user signed on on-chain, and need to include the `scheme`, we add it to the abstract signature so we can extract it from there and use it in the message we build on chain.
unit tests + locally
> Add the URI scheme field to the evm daa abstract signature + add MessageV2

- consensus/src/consensus_observer/observer/consensus_observer.rs
This PR fixes a small typo that was introduced in: https://github.com/aptos-labs/aptos-core/pull/16570. Without the fix, consensus observer fails to make progress.
Existing test infrastructure (a new test to detect these types of breakages is being worked on: https://github.com/aptos-labs/aptos-core/pull/16600).
> [Consensus Observer] Fix parent pipeline futures in CO.

- api/doc/spec.json
- api/doc/spec.yaml
- api/types/src/derives.rs
Remove the incorrect whitespace in the example address value in api/types/src/derive.rs
This causes an error in the current spec file's example because there is an extra space after the address.
- https://github.com/aptos-labs/aptos-core/blob/4f09b3b797e8549329eacaa793bff1c2c2d0ae1e/api/doc/spec.json#L15383
- https://github.com/aptos-labs/aptos-core/blob/4f09b3b797e8549329eacaa793bff1c2c2d0ae1e/api/doc/spec.json#L16365
- https://github.com/aptos-labs/aptos-core/blob/4f09b3b797e8549329eacaa793bff1c2c2d0ae1e/api/doc/spec.yaml#L11496
- https://github.com/aptos-labs/aptos-core/blob/4f09b3b797e8549329eacaa793bff1c2c2d0ae1e/api/doc/spec.yaml#L12221
> [fix] Remove the incorrect whitespace in the example address value in api/types/src/derive.rs

- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/config.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/historical_data_service.rs
- ecosystem/indexer-grpc/indexer-grpc-data-service-v2/src/live_data_service/mod.rs
- ecosystem/indexer-grpc/transaction-filter/src/boolean_transaction_filter.rs
Title + include size in error message
Config format
> [Indexer gRPC v2] Make data service maximum transaction filter size configurable

- aptos-move/block-executor/src/scheduler_status.rs
- aptos-move/block-executor/src/scheduler_v2.rs
Refactoring statuses to find ownership for queue manager (avoid passing Arcs to each status, as well as more logical ownership). 
Address @georgemitenkov's outstanding comments on PR 1/n (https://github.com/aptos-labs/aptos-core/pull/16447).
Next PR introduces scheduler_v2, separated for clarity.
> BlockSTMv2 PR [1.5/n] Refactor Status: comments, queue manager

- third_party/move/move-compiler-v2/src/env_pipeline/closure_checker.rs
- third_party/move/move-compiler-v2/src/lib.rs
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16592.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16592.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16593.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16593.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16594.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16594.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16609.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16609.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16616.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16616.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16623_a.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16623_a.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16623_b.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/bug_16623_b.move
Allowing lambda lifting in functions causes a variety of bugs (with different observed errors). This PR disallows it.
Closes #16592, closes #16593, closes #16594, closes #16609, closes #16616, closes #16623.
Added a number of tests.
> [compiler-v2] Disallow lambda lifting in functions

- Cargo.lock
- aptos-move/script-composer/Cargo.toml
- aptos-move/script-composer/src/builder.rs
We've received a lot of complaints about the Script Composer:
It requires multiple fetch calls, which makes composing transactions too slow, and there's no way to cache the results.
The package size is too large due to the heavy Wasm dependency.
We plan to address the fetch issue here by relying on externally passed-in modules. This change will allow Script Composer to focus solely on its core functionality—composing scripts. It will also result in a cleaner architecture and make it easier for other developers to build their own versions of the Script Composer.
Unfortunately, we don't seem to have any other testing methods at the moment. Our current testing relies on manual verification. I've already released a follow-up support package for the TS SDK to demonstrate its effectiveness.
> [ScriptComposer] Remove the usage of Fetch and rely on an externally passed-in Module

- .github/workflows/bump-release-version.yaml
- aptos-move/aptos-transaction-benchmarks/src/main.rs
- crates/aptos-telemetry/src/service.rs
- crates/node-resource-metrics/src/collectors/basic_node_info_collector.rs
- crates/node-resource-metrics/src/lib.rs
- execution/executor-benchmark/src/main.rs
- execution/executor-service/src/process_executor_service.rs
This PR adds a new release versioning workflow to bump the version number in `aptos-node/Cargo.toml` for each release. It's a dispatch based workflow that creates a PR against the target release branch to set the proper version. It also increments the patch version when multiple patch releases need to be made. Since the PR is created by the bot, the release manager can stamp it, so only requires one additional reviewer.
Also, updates telemetry service to export the package version as a metric.
> [release] Bump Version Workflow

- aptos-move/framework/aptos-framework/doc/jwks.md
- aptos-move/framework/aptos-framework/sources/jwks.move
- crates/aptos-jwk-consensus/src/jwk_manager_per_key.rs
- testsuite/smoke-test/src/jwks/jwk_consensus_basic.rs
- testsuite/smoke-test/src/jwks/mod.rs
- types/src/jwks/mod.rs
- types/src/on_chain_config/aptos_features.rs
- Use `UnsupportedJWK` as the issuer-level representation of a DELETE command (instead of `RSA_JWK`)
- Why not `RSA_JWK`: its KID type is `string` (and `UnsupportedJWK`'s KID type is `Vec<u8>`).
As a result, a DELETE of an unsupported JWK with kID `x` can not be represented (and therefore cannot be agreed on) this way.
- Side effect of using `UnsupportedJWK`: now the following 2 commands have the same issuer-level representation:
- (a) "DELETE the unsupported JWK with KID `x`
- (b) "UPSERT an unsupported JWK with KID `x` and payload `b'THIS_IS_A_DELETE_COMMAND'`
When translating it back to `KeyLevelUpdate`, the implementation always takes it as (a) and effectively disallows (b) from happening. In practice this should be fine?
- Enable the feature by default in genesis, update smoke tests …
> per-key jwk consensus 6: extra

- aptos-move/framework/aptos-experimental/doc/confidential_asset.md
- aptos-move/framework/aptos-experimental/doc/confidential_proof.md
- aptos-move/framework/aptos-experimental/sources/confidential_asset/confidential_asset.move
- aptos-move/framework/aptos-experimental/sources/confidential_asset/confidential_proof.move
- aptos-move/framework/aptos-experimental/tests/confidential_asset/confidential_asset_tests.move
- aptos-move/framework/aptos-experimental/tests/confidential_asset/confidential_proof_tests.move
- Split `transfer_amount` into `sender_amount` and `recipient_amount`: contracts check that C_s == C_r and D_s is encrypted under the sender's EK. `sender_amount` is needed for indexing purposes, so that if the user loses their tx history, they can easily restore the balance.
- Fixed the bug in `confidential_transfer`. Currently, we use different randomness for the `new_sender_balance` and `recipient_amount`. `sender_amount`, `recipient_amount` and `auditor_amounts` are still encrypted with the same randomness.
- Adjusted Fiat Shamir functions so they correspond to the docs. 
UT
- confidential_asset.move
- confidential_proof.move
> [move][docs] fixed confidential_transfer

- aptos-move/framework/aptos-framework/doc/big_ordered_map.md
- aptos-move/framework/aptos-framework/doc/ordered_map.md
- aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.move
- aptos-move/framework/aptos-framework/sources/datastructures/ordered_map.move
- aptos-move/move-examples/data_structures/Move.toml
- aptos-move/move-examples/data_structures/sources/big_ordered_map_usage_examples.move
for_each methods are using ability for inline functions to receive function as an argument.
For that - they require whole body of the inline function to be public. 
With that, we need to fallback to this less efficient way to handle it.
After function values are enabled, we can implement them as a non-inline functions, which will then be able to use internal methods. 
Also went through and applied move2 syntax throughout (separate commit for easy review)
added example test
> Fix inline for_each* methods in OrderedMap and BigOrderedMap

- third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs
- third_party/move/move-compiler-v2/tests/visibility-checker/cross_module_enum_access_01.exp
- third_party/move/move-compiler-v2/tests/visibility-checker/cross_module_enum_access_01.move
- third_party/move/move-compiler-v2/tests/visibility-checker/cross_module_enum_access_02.exp
- third_party/move/move-compiler-v2/tests/visibility-checker/cross_module_enum_access_02.move
- third_party/move/move-compiler-v2/tests/visibility-checker/cross_module_enum_access_03.exp
- third_party/move/move-compiler-v2/tests/visibility-checker/cross_module_enum_access_03.move
- third_party/move/move-compiler-v2/tests/visibility-checker/inline_with_enums_01.exp
- third_party/move/move-compiler-v2/tests/visibility-checker/inline_with_enums_01.move
- third_party/move/move-compiler-v2/tests/visibility-checker/inline_with_enums_02.exp
- third_party/move/move-compiler-v2/tests/visibility-checker/inline_with_enums_02.move
- third_party/move/move-compiler-v2/tests/visibility-checker/inline_with_enums_03.exp
- third_party/move/move-compiler-v2/tests/visibility-checker/inline_with_enums_03.move
In this PR, the compiler disallows performing certain privileged operations on enums defined in a different modules. Previously, the compiler would emit an internal compiler error (ICE) in these cases.
For example, the compiler would ICE on the code below before, but we now instead give a compiler error:
```move
module 0xc0ffee::m {
enum Wrapper has drop {
V1(u64),
V2(u64),
}
public fun make(x: u64): Wrapper {
Wrapper::V1(x)
}
}
module 0xc0ffee::n {
use 0xc0ffee::m;
fun test1() {
let x = m::make(22);
match (x) { // !! match on enum defined in a different module
m::Wrapper::V1(v) => assert!(v == 22, 1),
_ => abort(0),
};
}
}
```
Added several new tests.
Completeness of the fix.
> [compiler-v2] Check privileged enum operations outside the defining module

- third_party/move/move-compiler-v2/tests/checking/typing/borrow_local.exp
- third_party/move/move-compiler-v2/tests/checking/typing/borrow_local.move
- third_party/move/move-compiler-v2/tests/checking/typing/borrow_local_temp_invalid.exp
- third_party/move/move-compiler-v2/tests/checking/typing/borrow_tuple_invalid.exp
- third_party/move/move-compiler-v2/tests/checking/typing/borrow_tuple_invalid.move
- third_party/move/move-compiler-v2/tests/checking/typing/derefrence_invalid.exp
- third_party/move/move-compiler-v2/tests/more-v1/parser/spec_parsing_inside_fun.exp
- third_party/move/move-model/src/builder/exp_builder.rs
Resolves #16583
Disallow borrowing tuples.
Existing text coverage
1) Look at error message added to `third_party/move/move-compiler-v2/tests/more-v1/parser/spec_parsing_inside_fun.exp`. This is potentially a bit confusing if the user doesn't know that `spec` has type `unit`. Are we fine with this error message?
2) I don't love that my solution spaghettifies the code. Curious if a better way to do this. 
3) Perhaps worth looking into: there were existing move language tests that clearly intended to capture this bug (which is why I didn't need to write new tests), but the`.exp` files were incomplete (for example, `spec_parsing_inside_fun.move` noted that the expression `&mut spec {};` is a typing error but the corresponding `.exp` file did not capture this). Are there other instances of …
> [Compiler] Catch borrow of tuple at expression builder time

- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_infer_err.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_infer_err.move
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_infer_ok.exp
- third_party/move/move-compiler-v2/tests/checking/variants/variants_test_infer_ok.move
- third_party/move/move-model/src/builder/exp_builder.rs
Fix for compiler warning no type argument during enum variant test when type argument can be inferred from context.
Close: https://github.com/aptos-labs/aptos-core/issues/16014, https://github.com/aptos-labs/aptos-core/issues/16360
New test cases added
I want to confirm that on `line 4265` of `exp_builder.rs`, the behavior should be to continue incase of `self.resolve_struct_access` failing. It is my understanding that `self.resolve_struct_access` will handle the error reporting.
> [Compiler] Fix bug relating to inferring enum variant during is check

- testsuite/fuzzer/fuzz/Cargo.toml
- testsuite/fuzzer/fuzz/fuzz_targets/move/type_tag_to_string.rs
Add a new fuzz target type_tag_to_string to test the to_string() implementation of TypeTag.
Ensures that two different TypeTag values do not produce the same string representation.
- [] I have made corresponding changes to the documentation
> [fuzzer] Add fuzzer for TypeTag to string conversion

- .github/actions/rust-lints/action.yaml
This PR fixes the `cargo sort` install version to `1.0.7` inside CI/CD. The latest version appears to cause some issues with our `Cargo.toml` formatting.
> [CI/CD] Fix cargo sort version on install.

- third_party/move/move-binary-format/src/file_format.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/scripts.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/scripts.move
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/loader/modules.rs
- third_party/move/move-vm/runtime/src/loader/script.rs
- third_party/move/move-vm/runtime/src/loader/single_signature_loader.rs
Refactors loading single signatures (for instructions like `VecPack`, etc.) so that it is reused when loading scripts and modules. The match is now exhaustive so that if new instructions are added there is a compile-time error. This also fixes an issue when calling closures from scripts (added a test which was failing before).
New transactional test + existing tests.
> [vm] Single signature loading

- aptos-move/aptos-vm/src/verifier/event_validation.rs
- aptos-move/e2e-move-tests/src/tests/module_event.rs
- aptos-move/framework/aptos-framework/doc/event.md
- aptos-move/framework/aptos-framework/sources/event.move
- aptos-move/framework/src/natives/event.rs
With closures, event validation needs to be adjusted to account for `0x1::event::emit` captured in a closure. This PR improves event validation and event natives to account for that:
1. For scripts, any event emission is disallowed (i.e., for any function handle, it should not be `0x1::event::emit`). As scripts have no struct definitions, there is nothing to emit.
2. Native `emit` implementation ensure the caller is known. When the caller is `None` (i.e., the call comes from script), an error is also returned.
3. For modules, in addition to direct static calls to `0x1::event::emit`, we also check any closure that is packed from `0x1::event::emit`. This is sufficient to enforce that all event structs come from the same module at publish time.
- New tests for scripts
- New tests for modules
> [vm] Event validation with closures

- third_party/move/move-compiler-v2/tests/bytecode-generator/bug_16678.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/bug_16678.move
- third_party/move/move-compiler-v2/tests/bytecode-generator/bug_16679.exp
- third_party/move/move-compiler-v2/tests/bytecode-generator/bug_16679.move
- third_party/move/move-model/src/builder/exp_builder.rs
This PR adds a check to forbid using inline functions as a function value.
close #16678  close #16679 
Existing tests and two new test cases.
> [compiler-v2][trivial] Do not allow using inline functions as function value

- aptos-move/aptos-vm-types/src/abstract_write_op.rs
- aptos-move/aptos-vm-types/src/resolver.rs
- aptos-move/aptos-vm-types/src/resource_group_adapter.rs
- aptos-move/aptos-vm/src/move_vm_ext/session/view_with_change_set.rs
- aptos-move/block-executor/src/captured_reads.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/view.rs
- aptos-move/mvhashmap/src/types.rs
- aptos-move/mvhashmap/src/unsync_map.rs
- execution/executor-benchmark/src/native/native_vm.rs
Do not default forward APIs at the trait level, pass appropriate ReadKind in view implementations and enhance CapturedReads to easily handle RawFromStorage, as well as its Size and Metadata properties: allows granular access and prepares for the case when such accesses will happen without the read (to avoid read-write conflicts).
Added tests to CapturedReads for MetadataAndSize variant. Pass existing tests.
> [Block Executor] Capturing MetadataAndSize, no default API forwarding. View changes [1/4]

- testsuite/forge/src/backend/k8s/cluster_helper.rs
Previously era was a random u8. With an increasing number of tests and changes to how genesis data is stored (in a persistent bucket rather than in the same namespace as a secret which gets cleared each time), era needs to not collide with better probability. 
Existing tests incl full forge run on PR
> [forge] era as random hex

- api/src/tests/transactions_test.rs
- api/src/transactions.rs
- config/src/config/transaction_filter_type.rs
- consensus/src/block_preparer.rs
- consensus/src/transaction_filter/mod.rs
This PR extends the transaction filtering support offered by the `simulation` API on fullnodes. The PR offers the following commits:
1. Add support for the `BlockEpochGreaterThan` and `BlockEpochLessThan` filter. These filter transactions based on the epoch of the block containing the transactions.
2. Add support for the `MatchesAllOf` filter. This allows filter rules to be combined, e.g., filter transactions that touch specific modules in blocks with a timestamp greater than a specific value.
3. Add tests for the new filters, and extend the tests for the existing filters (e.g., negative and positive cases).
> [API] Extend simulation filtering support.

- api/types/src/convert.rs
- aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/function_values/sources/function_store.move
- aptos-move/e2e-move-tests/src/tests/aggregator_v2_function_values.rs
- aptos-move/framework/move-stdlib/src/natives/bcs.rs
- aptos-move/framework/src/natives/string_utils.rs
- testsuite/fuzzer/fuzz/fuzz_targets/move/utils/helpers.rs
- third_party/move/move-binary-format/src/constant.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/storage_examples.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/storage_examples.move
- third_party/move/move-core/types/src/function.rs
- third_party/move/move-core/types/src/value.rs
- third_party/move/move-vm/runtime/src/storage/ty_layout_converter.rs
- third_party/move/move-vm/types/src/values/function_values_impl.rs
- third_party/move/move-vm/types/src/values/serialization_tests.rs
- third_party/move/move-vm/types/src/values/values_impl.rs
- third_party/move/tools/move-bytecode-utils/src/layout.rs
- third_party/move/tools/move-resource-viewer/src/fat_type.rs
Before, we defined function value layout as a triple of argument layouts, return value layouts and abilities. This design does not make sense because then it is not possible to store functions which operate on references (#16664):
```move
// Invariant violation returned at runtime, because reference layout is not possible.
struct Wrapper(|&signer|) has copy, drop, store, key;
```
In general, layout of function value is well defined as the function identifier, type arguments, and captured argument-layout pairs, so argument layouts and return value layouts are really not needed. In the end, here we talk about *layout*, not a *type*. Note that adding a "reference" variant to layout is not correct.
This PR changes function layout to a primitive `MoveTypeLayout::Function`. This works perfectly …
> [vm] Refactor function type layout

- third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs
- third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16363.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16684.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16684.move
- third_party/move/move-model/src/builder/exp_builder.rs
- third_party/move/move-model/src/well_known.rs
There are bunch of functions in `std::vector` that are implemented as bytecode instructions. Closures cannot directly reference such functions, they need to be lambda-lifted (instead of currying).
In cases where we refer to such functions by just the name, we explicitly build a wrapper lambda around it. E.g.,
`std::vector::destroy_empty` -> `|p__0| std::vector::destroy_empty(p__0)`.
Note: we could use the same technique for inline functions (i.e., instead of disallowing inline functions as function values, as done in https://github.com/aptos-labs/aptos-core/pull/16681).
Closes #16684.
- Added a number of tests
- Fixed an existing test
Creation of the wrapper lambda.
> [compiler-v2] Handle function values that are referring to functions like `vector::empty`

- third_party/move/move-binary-format/src/file_format.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16335.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16335_split.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16335_split.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/mut_ref_downgrade.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/mut_ref_downgrade.move
- third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
To be sound, assignments of mutable references should have invariance.
This PR fixes the static bytecode verifier and the paranoid mode accordingly.
The follow up compiler fix is here: https://github.com/aptos-labs/aptos-core/pull/16692
- Added a test showcasing the issue. Checked manually that if I disable the static bytecode verifier fix, then the paranoid mode fix is triggered. This test is a good candidate for adding assembler-based tests, because the compiler will start rejecting this code after #16692 lands.
- Split an existing test to separate out the valid and invalid code.
- Completeness of the fix, if there are other areas we should consider
> [vm] Make mutable references invariant

- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/bug_16335.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/mut_ref_downgrade.exp
- third_party/move/move-model/src/ty.rs
To be sound, unifying mutable references should have invariance.
In this PR, we fix the compiler's type checker accordingly. Related to another fix: #16691.
- Existing tests that already showed the bug
Completeness of the fix.
> [compiler-v2] Make mutable references invariant in the complier

- aptos-move/block-executor/src/scheduler.rs
- aptos-move/block-executor/src/scheduler_status.rs
- aptos-move/block-executor/src/scheduler_v2.rs
SchedulerV2 file including interfaces that are hopefully intuitive to understand even without being used yet, alongside the accompanying tests and documentation.
> BlockSTMv2 PR [2/n]: SchedulerV2 & tests

- crates/aptos-faucet/cli/src/main.rs
- crates/aptos-faucet/core/src/endpoints/errors.rs
- crates/aptos-faucet/core/src/funder/common.rs
- crates/aptos-faucet/core/src/funder/mint.rs
- crates/aptos-faucet/core/src/funder/transfer.rs
- crates/aptos-faucet/core/src/server/run.rs
If you want to make the faucet use a node API, often you'll need to be able to set some kind of auth, e.g. an API key or some other kind of header.
Using this config:
```
server_config:
api_path_base: ""
listen_port: 8010
metrics_server_config: {}
bypasser_configs: []
checker_configs: []
funder_config:
type: "MintFunder"
node_url: "https://api.testnet.aptoslabs.com"
api_key: <key>
chain_id: 2
key:
key: <key>
maximum_amount: 100000000
maximum_amount_with_bypass: 10000000000
do_not_delegate: true
transaction_expiration_secs: 15
wait_for_outstanding_txns_secs: 20
handler_config:
use_helpful_errors: true
return_rejections_early: true
```
Run this:
```
cargo run -p aptos-faucet-service -- run --config-path ~/faucet-config.yaml
```
Then mint:
```
curl -H 'Content-Type: application/json' …
```
> [faucet] Allow setting API key / headers

- third_party/move/move-compiler-v2/src/env_pipeline/lambda_lifter.rs
- third_party/move/move-compiler-v2/src/env_pipeline/spec_rewriter.rs
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/inline-parity/inline_fun_in_spec.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/inline-parity/inline_fun_in_spec.move
- third_party/move/move-model/src/ast.rs
- third_party/move/move-prover/tests/sources/functional/closure.exp
- third_party/move/move-prover/tests/sources/functional/closure.move
- third_party/move/move-prover/tests/sources/functional/restrictions.exp
As the first step to support function value in Move prover, this PR adds the logic to rewrite invoke(closure) operation into call to the corresponding lifted move/spec function. Note that rewrite only happens when `rewrite_spec` flag is turned on, which means no code will be rewritten for execution.
Existing tests and a new test case.
Check whether this change only applies code generation for formal verification.
> [Move prover] Rewrite invoke closure into move function call during spec rewriting

- third_party/move/move-compiler-v2/src/bytecode_generator.rs
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_14817.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_14817.opt.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_14817_extended.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_14817_extended.move
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_16599.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_16599.move
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_16607.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_16607.move
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_16622.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_16622.move
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_16625.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_16625.move
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/mutate_if.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/mutate_if.move
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/nested_mutate.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/nested_mutate.move
In this PR, we fix a few cases in the bytecode generator where we need to escape from "reference mode".
When we have an expression like `a.b.c` (which could appear in various contexts, like `*&mut a.b.c = 1;`, or `a.b.c = 1;`, or `let x = a.b.c + 1`):
- we need to generate the appropriate kind of intermediate references to `a`, and then derive the field reference `.b` from it
- finally, we either need to either just derive the field reference `.c`, or also do a readref on this final field reference.
What we do depends on the context in which `a.b.c` appears. All of this is tracked using whether you are in reference mode or not, and we were missing some cases where we escaped reference mode.
fixes #14817, fixes #16599, fixes #16607, fixes #16622, fixes #16625
- several new tests have been …
> [compiler-v2] Fix bytecode generator's generation of args

- third_party/move/move-compiler-v2/tests/checking/typing/borrow_tuple_invalid.exp
- third_party/move/move-compiler-v2/tests/checking/typing/borrow_tuple_invalid.move
- third_party/move/move-model/src/builder/exp_builder.rs
Close #16666.
Resolves issue of borrow of tuple as return signature going unresolved.
Some testing added; mostly just current coverage.
> [Compiler] Fix issue of return signature of borrow of tuple not caught during type checking

- crates/aptos/CHANGELOG.md
- crates/aptos/src/update/aptos.rs
Fixes CLI update paths for macOS and Linux.
I removed logic for OpenSSL v1.  It's been deprecated for a while now.
> [cli] Update paths for CLIs to be updated

- .github/workflows/workflow-run-replay-verify-on-archive.yaml
- storage/db-tool/src/replay_on_archive.rs
- testsuite/replay-verify/main.py
- testsuite/replay-verify/replay-verify-worker-template.yaml
Temporary hack to split heavy ranges and verify.
also enlarge timeout to allow pods finish on mismatch
This test almost went thorough except one range, which I have addressed: https://github.com/aptos-labs/aptos-core/actions/runs/15496818186/job/43636449393
> replay-verify: print mismatches as found.

- Cargo.lock
- aptos-move/block-executor/Cargo.toml
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/executor_utilities.rs
- aptos-move/block-executor/src/lib.rs
- aptos-move/block-executor/src/scheduler.rs
- aptos-move/block-executor/src/scheduler_wrapper.rs
- aptos-move/block-executor/src/txn_last_input_output.rs
- aptos-move/block-executor/src/view.rs
- aptos-move/mvhashmap/src/versioned_group_data.rs
Introduce SchedulerWrapper by wrapping the dispatching logic (currently V2 branches marked unimplemented!). Refactor executor.rs to:
- decouple parameters (module read validation), 
- isolate functionality (process execution results), 
- clean up and streamline the prepare and commit ready txns method
- introduce AggregatorV1 KeyKind
- add additional validation to confirm safaty in post commit parallel hook
All facilitating later re-use and integration of features with Scheduler/BlockSTMv2 alongside V1. 
- other minor / convenience clean-ups from the prototype branch, such as extracting parameters from a result before calling finalize groups (https://github.com/aptos-labs/aptos-core/compare/main...gelash/v2scheduler#diff-9ef162a216d74568caa85b78dfaf100e0c8b3eb1e66536451492392d8c00d2b0) to …
> BlockSTMv2 PR [3/n]: executor refactors for integration preparation

- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/sources/coin.move
1. delete CoinStore<invalidated_coin_type> such as `CoinStore<String>`.
2. sync decimal length between coin and fa.
> [migration] optimize for CoinStore<String>

- aptos-move/framework/aptos-framework/doc/vesting.md
- aptos-move/framework/aptos-framework/sources/vesting.spec.move
Removes unnecessary generic parameter for the `ActiveVestingContractAbortsIf` schema, which confusingly overwrites the actual `VestingContract` struct. 
Compiler seems to just ignore it, but it hits the IDE and I wanted to clean it up. 
Should not affect any behaviour.
> [framework] Remove generic parameter for `ActiveVestingContractAbortsIf` as `VestingContract` is available in the scope

- aptos-move/e2e-move-tests/src/tests/any.data/pack/Move.toml
- aptos-move/e2e-move-tests/src/tests/any.data/pack/sources/any_with_function_values.move
- aptos-move/e2e-move-tests/src/tests/any.rs
- aptos-move/e2e-move-tests/src/tests/mod.rs
- third_party/move/move-vm/runtime/src/loader/function.rs
1. Removing `abilities()` on function. This is not used and is error-prone as captured arguments need to be taken into account.
2. More tests for `Any` and function values.
Move end-to-end tests.
N/A
> [tests] Add tests for any and function values

- Cargo.lock
- aptos-move/aptos-gas-meter/src/meter.rs
- aptos-move/aptos-gas-profiling/src/log.rs
- aptos-move/aptos-gas-profiling/src/profiler.rs
- aptos-move/aptos-memory-usage-tracker/src/lib.rs
- aptos-move/aptos-native-interface/Cargo.toml
- aptos-move/aptos-native-interface/src/builder.rs
- aptos-move/aptos-native-interface/src/context.rs
- aptos-move/aptos-native-interface/src/errors.rs
- aptos-move/framework/src/natives/account_abstraction.rs
- aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
- aptos-move/framework/src/natives/dispatchable_fungible_asset.rs
- aptos-move/framework/src/natives/function_info.rs
- aptos-move/framework/src/natives/string_utils.rs
- aptos-move/framework/table-natives/src/lib.rs
- aptos-move/replay-benchmark/src/overrides.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/native_functions.rs
- third_party/move/move-vm/runtime/src/storage/dependencies_gas_charging.rs
- third_party/move/move-vm/test-utils/src/gas_schedule.rs
- third_party/move/move-vm/types/src/gas.rs
This refactors native context to be able to use `GasMeter` directly. Note that using the trait as is is not possible, because it cannot be maid a trait object (which is a requirement for native functions). Hence, I added 2 more traits:
```rust
// moved from GasMeter
pub trait DependencyGasMeter {
fn charge_dependency(
&mut self,
is_new: bool,
addr: &AccountAddress,
name: &IdentStr,
size: NumBytes,
) -> PartialVMResult<()>;
}
```
```rust
// charge_heap_memory is moved from GasMeter, legacy_gas_budget_in_native_context == balance_internal
pub trait NativeGasMeter: DependencyGasMeter {
fn legacy_gas_budget_in_native_context(&self) -> InternalGas;
fn is_metering_in_native_context_enabled(&self) -> bool;
fn charge_native_execution(&mut self, amount: InternalGas) -> PartialVMResult<()>;
fn …
```
> [vm] Support gas meter in native functions

- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/executor_utilities.rs
- aptos-move/block-executor/src/txn_last_input_output.rs
- aptos-move/mvhashmap/src/unsync_map.rs
- aptos-move/mvhashmap/src/versioned_data.rs
The values were obtained from a shared multi-versioned data-structure, but they should also be cached in local captured reads. Should be more logical and better performance wise.
> [DelayedFields] Get exchange ID->value from local captured reads [2/4]

- aptos-move/aptos-gas-schedule/src/ver.rs
This PR bumps the gas version to v1.33 after the v1.32 branch cut.
> [Gas] Bump gas version to v1.33

- .github/actionlint.yaml
- .github/workflows/cli-e2e-tests.yaml
- .github/workflows/copy-images-to-dockerhub.yaml
- .github/workflows/coverage-move-only.yaml
- .github/workflows/coverage.yaml
- .github/workflows/docker-build-rosetta.yaml
- .github/workflows/faucet-tests-main.yaml
- .github/workflows/faucet-tests-prod.yaml
- .github/workflows/find-packages-with-undeclared-feature-dependencies.yaml
- .github/workflows/fuzzer-data-update.yml
- .github/workflows/indexer-processor-testing.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/node-api-compatibility-tests.yaml
- .github/workflows/prover-daily-test.yaml
- .github/workflows/run-gas-calibration.yaml
- .github/workflows/rust-client-tests.yaml
- .github/workflows/workflow-run-docker-rust-build.yaml
Upgraded runs-on controller. Now we specify disk size via `disk=...`
Workflows
> [runs-on] use large disk for all workflows with runs-on/cache for docker

- aptos-move/e2e-move-tests/src/tests/cmp_generic.data/pack/Move.toml
- aptos-move/e2e-move-tests/src/tests/cmp_generic.data/pack/sources/test.move
- aptos-move/e2e-move-tests/src/tests/cmp_generic.data/script/Move.toml
- aptos-move/e2e-move-tests/src/tests/cmp_generic.data/script/sources/script.move
- aptos-move/e2e-move-tests/src/tests/generic_cmp.rs
- aptos-move/e2e-move-tests/src/tests/mod.rs
- third_party/move/move-compiler-v2/legacy-move-compiler/src/expansion/dependency_ordering.rs
- third_party/move/move-compiler-v2/src/env_pipeline/cmp_rewriter.rs
- third_party/move/move-compiler-v2/src/env_pipeline/mod.rs
- third_party/move/move-compiler-v2/src/experiments.rs
- third_party/move/move-compiler-v2/src/lib.rs
- third_party/move/move-model/src/builder/builtins.rs
- third_party/move/move-model/src/lib.rs
- third_party/move/move-model/src/well_known.rs
The in-house Lt/Le/Gt/Ge operations only allow integer operands. This PR introduces support for non-integer types. It replaces Lt/Le/Gt/Ge expressions (on non-integer types) at the model AST level with calls to the `std::cmp::compare` and `std::cmp::is_lt/is_le/is_gt/is_ge` functions from `Move-Stdlib` to perform the comparison. 
Example:
```
x <= y
==>
std::cmp::compare<T>(&x, &y).std::cmp::is_le()
```
The feature is only enabled in language version 2.2 and onward.
**Key implementation:**
- [`fn rewrite_cmp_operation`](https://github.com/aptos-labs/aptos-core/blob/jun/enable-generic-cmp/third_party/move/move-compiler-v2/src/env_pipeline/cmp_rewriter.rs#L108):
- Given an ast exp representing a comparison operation, e.g., `Call(Operation::Lt, [arg1, arg2])`, the function takes five steps …
> Enable comparison operations, Lt/Le/Gt/Ge, on non-integer types

- aptos-move/framework/aptos-framework/doc/account.md
- aptos-move/framework/aptos-framework/sources/account/account.move
This call is problematic, so temporarily disabling
added a test, also data analysis suggests it has only been called 4 times
> disable set_originating_address

- aptos-move/framework/aptos-framework/doc/account.md
- aptos-move/framework/aptos-framework/sources/account/account.move
This call is problematic, so temporarily disabling
added a test, also data analysis suggests it has only been called 4 times
> disable set_originating_address for 1.30

- .github/actions/rust-lints/action.yaml
- aptos-move/e2e-move-tests/src/tests/fee_payer.rs
- aptos-move/framework/aptos-framework/doc/transaction_validation.md
- aptos-move/framework/aptos-framework/sources/transaction_validation.move
This is to patch an issue where sponsored txns were failing.
Now we will only do the auth key check if any of the following is true
1. Its not sponsored
2. The account exists
3. sponsored_automatic_account_creation is NOT enabled
The existing move harness tests with stateless accounts disabled
> Patch transaction_validation.move auth key check

- third_party/move/move-core/types/src/value.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/loader/function.rs
As discussed with @wrwg (https://github.com/aptos-labs/aptos-core/pull/16461/files#r2113554726, https://github.com/aptos-labs/aptos-core/pull/16462/files#r2126285385) , there is no need to check captured layouts being compatible with existing layouts:
- Storage integrity is assumed for resources, so it should be assumed for layouts.
- The check isn't complete anyway because it is not based on types but on layout, so type confusion would not be discovered by it.
- It adds extra runtime overhead and gas metering complexity.
N/A
> [vm] Remove captured layout compatibility check for closures

- third_party/move/move-compiler-v2/tests/ability-check/fv_as_keys/compiler_ok_case.move
This PR removes a redundant comment from a test case merged into PR #16878
- Existing test cases
> Remove redundant comment in test case

- aptos-move/framework/aptos-framework/doc/transaction_validation.md
- aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
- aptos-move/framework/move-stdlib/doc/cmp.md
- aptos-move/framework/move-stdlib/sources/cmp.move
- aptos-move/framework/src/aptos-natives.bpl
- aptos-move/framework/tests/move_prover_tests.rs
- third_party/move/move-model/src/model.rs
- third_party/move/move-model/src/ty.rs
- third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
- third_party/move/move-prover/boogie-backend/src/lib.rs
- third_party/move/move-prover/boogie-backend/src/prelude/prelude.bpl
- third_party/move/move-prover/boogie-backend/src/spec_translator.rs
This PR adds native support using cmp::compare to Move prover, which is the prerequisite of supporting ordered_map and big_ordered_map in Move prover.
Unit tests are added to `cmp.move`.
> [Move Prover] Add native support of cmp

- third_party/move/move-model/bytecode/src/astifier.rs
- third_party/move/tools/move-decompiler/tests/nested_loops.exp
- third_party/move/tools/move-decompiler/tests/nested_loops.move
The [`astifier`](https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-model/bytecode/src/astifier.rs) component in the decompiler adds a virtual edge from each block in a loop to every successor block outside of the loop, when topologically sorting the stackless bytecode cfg (after original loop backedges are removed). This can bring loops back and fail the topological sorting, when nested loops exist. Below is an example where:
- An outer loop exists (including B, C, D)
- An inner loop exists (including C, D)
- Backedges D->C, C->B are removed
- Yet, B is an outer successor of C when dealing with the inner loop. Thus, a virtual edge C->B was re-introduced, preventing topological sorting.
This PR introduces checks to make sure the above does not happen when adding …
> [Bug] Fix an issue in decompiling nested loops

- aptos-move/e2e-move-tests/src/tests/fv_as_table_keys.rs
- aptos-move/e2e-move-tests/src/tests/mod.rs
The PR adds e2e-move-test for using function values as table keys.
* New [e2e-move-test](https://github.com/aptos-labs/aptos-core/blob/jun/function-val-review-1/aptos-move/e2e-move-tests/src/tests/fv_as_table_keys.rs)
> e2e-move-test for using fun values as table keys

- testsuite/forge-cli/src/suites/realistic_environment.rs
This PR increases the consensus observer (CO) fallback threshold for triggering failures in the land blocking forge performance test (`realistic_env_max_load`). We've seen some recent flakes when the fullnodes are saturated. Hopefully this will reduce/remove the flakes.
Anecdotal inspection of previous flakes to determine failure thresholds due to saturation. Flake rates [are less than](https://cloud.us.humio.com/k8s/search?live=false&query=%22fullnode%20failures%22%0A%7C%20%22k8s.labels.forge-namespace%22%20%3D%2Fforge-e2e-clbt-w-d-%2F%0A%7C%20!%22No%20fullnode%20failures%22&start=21d&tz=America%2FLos_Angeles) ~1 per day.
Note: the test is a correctness check, not a performance check, so the exact threshold we use doesn't matter too much (we just want to check that CO is not completely …
> [Forge] Increase CO fallback threshold for failures.

- storage/aptosdb/src/pruner/ledger_pruner/transaction_pruner.rs
- storage/aptosdb/src/transaction_store/mod.rs
- storage/aptosdb/src/utils/truncation_helper.rs
Prune transaction summaries only in ledger db and do not prune in indexer db.
> Prune transaction summaries only in ledger db

- third_party/move/move-bytecode-verifier/src/instantiation_loops.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/no-recursive-type-check/bug_16939_a.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-recursive-type-check/bug_16939_a.move
- third_party/move/move-compiler-v2/transactional-tests/tests/no-recursive-type-check/bug_16939_b.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-recursive-type-check/bug_16939_b.move
- third_party/move/move-compiler-v2/transactional-tests/tests/tests.rs
The bytecode verifier pass "instantiation loop checker" was missing a check for the recently introduced bytecode `PackClosureGeneric`. This PR fixes it, and also adds explicit bytecodes in a `match`, so that future bytecode addition will have to reason through this.
Closes #16939.
- Added new transactional tests turning the corresponding compiler check off, showing that we now produce a bytecode verification error.
Completeness of the fix.
> [vm] [bytecode-verifier] Fix instantiation loop verifier

- third_party/move/move-vm/runtime/src/interpreter.rs
Fixes #16974
Module ID for function value must always be set because:
- Lambda lifting is not supported for functions in scripts.
- Script's entrypoint cannot be captured.
> [vm] Function values always have module ID

- aptos-move/block-executor/src/captured_reads.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/executor_utilities.rs
- aptos-move/block-executor/src/proptest_types/baseline.rs
- aptos-move/block-executor/src/proptest_types/delta_tests.rs
- aptos-move/block-executor/src/proptest_types/group_tests.rs
- aptos-move/block-executor/src/proptest_types/module_tests.rs
- aptos-move/block-executor/src/proptest_types/resource_tests.rs
- aptos-move/block-executor/src/proptest_types/types.rs
- aptos-move/block-executor/src/scheduler.rs
- aptos-move/block-executor/src/scheduler_v2.rs
- aptos-move/block-executor/src/scheduler_wrapper.rs
- aptos-move/block-executor/src/view.rs
- aptos-move/mvhashmap/src/versioned_data.rs
Mainly dealing w. executor.rs, on top of [5/n].
Integrate normal resources, and enable corresponding proptests for BlockSTMv2.
> BlockSTMv2 PR [6/n]: Executor flow w. resources & tests

- third_party/move/move-model/bytecode/src/astifier.rs
- third_party/move/tools/move-decompiler/tests/closure.exp
- third_party/move/tools/move-decompiler/tests/closure.move
- third_party/move/tools/move-decompiler/tests/nested_loops.exp
- third_party/move/tools/move-decompiler/tests/nested_loops.move
- third_party/move/tools/move-decompiler/tests/noexit_loops.exp
- third_party/move/tools/move-decompiler/tests/noexit_loops.move
This PR addresses three issues in the [astifier](https://github.com/aptos-labs/aptos-core/blob/jun/fix-astfier-issues/third_party/move/move-model/bytecode/src/astifier.rs) component of the decompiler.
- Revise a recent fix introduced by https://github.com/aptos-labs/aptos-core/pull/16908 to ensure topological sorting works as expected.
- Add support to deal with cyclic label substitution.
- Given a block like `Label L1; goto L2`, the astifier substitutes `L1` with `L2`. This can create cyclic substitutions when encountering endless loops (e.g., `Label L1; goto L2`, `Label L2; goto L3`, `Label L3; goto L1`). The current implementation panics on such cases.
- This PR prevents cyclic substitutions by replacing all labels with the last one. In the example above, both `L1` and `L2` will be …
> [decompiler] fix issues; support closure

- third_party/move/move-compiler-v2/src/env_pipeline/cyclic_instantiation_checker.rs
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/bug_16938.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/bug_16938.move
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/recursive_type_instantiation.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/complex_1.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/mutually_recursive_three_args_type_con_non_generic_types_ok.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/mutually_recursive_three_args_type_con_shifting.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/mutually_recursive_two_args_swapping_type_con.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/mutually_recursive_type_con.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/nested_types_1.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/nested_types_2.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/recursive_infinite_type_terminates.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/recursive_one_arg_type_con.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/recursive_two_args_swapping_type_con.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-tests/two_loops.exp
- third_party/move/move-compiler-v2/tests/cyclic-instantiation-checker/v1-typing/infinite_instantiations_invalid.exp
Cyclic instantiation checker in the compiler was not addressing function values in various aspects, leading to a panic and a bytecode verifier error.
We address this by:
- considering function types (and other types that can be contained in it)
- considering recursive use of closures
Closes #16938.
- Added several new tests
- Existing tests have been updated (the only changes are the wordings in the error messages)
> [compiler-v2] Fix cyclic instantiaton checker to consider function types

- aptos-move/aptos-release-builder/src/components/mod.rs
Minor fix to generate the metadata file under `metadata/vX.XX.X` instead of `metadata`. Existing way makes it tricky/hard to copy to mainnet proposals repo. 
Generated the proposal to make sure.
> [release-builder] generate metadata under versioned dir

- config/src/config/consensus_config.rs
- testsuite/forge-cli/src/suites/realistic_environment.rs
- testsuite/forge/src/config.rs
This PR enabled Opt Proposal in forge by default for all runs. Further, it increases  the target block time to 90 ms in main. Only force is tuned for 15 blocks per second with 60ms target block time.
> [consensus] Enable Opt Proposal and increase execution target time

- third_party/move/move-bytecode-verifier/src/stack_usage_verifier.rs
Handle the unlikely case of `overall_push` overflow in `stack_usage_verifier`, which would cause `checked_add` to return `None`.
```
if let Some(new_pushes) = u64::checked_add(overall_push, num_pushes) {
overall_push = new_pushes
}
```
Not necessary.
> Stack usage verifier early exit on error

- third_party/move/move-model/bytecode/ast-generator-tests/tests/abort_example.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/bit_vector_loop_example.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/conditionals.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/loops.exp
- third_party/move/move-model/bytecode/ast-generator-tests/tests/match.exp
- third_party/move/move-model/bytecode/src/astifier.rs
- third_party/move/move-model/src/exp_builder.rs
- third_party/move/tools/move-decompiler/tests/bit_vector.exp
- third_party/move/tools/move-decompiler/tests/cfg_opt.exp
- third_party/move/tools/move-decompiler/tests/cfg_opt.move
- third_party/move/tools/move-decompiler/tests/closure.exp
- third_party/move/tools/move-decompiler/tests/fixed_point32.exp
- third_party/move/tools/move-decompiler/tests/nested_loops.exp
- third_party/move/tools/move-decompiler/tests/noexit_loops.exp
- third_party/move/tools/move-decompiler/tests/option.exp
- third_party/move/tools/move-decompiler/tests/simple_map.exp
- third_party/move/tools/move-decompiler/tests/string.exp
- third_party/move/tools/move-decompiler/tests/vector.exp
This PR fixes three issues.
The `try_make_if_else` optimization transfers the following pattern
```Move
loop {
loop { // no loop header
( if (c_i) break; )+
<else-branch> // no reference to inner loop
break[1]
}
<then-branch>
}
```
==>
```Move
if (c1 || .. || cn) {
loop {
<then-branch>
}
}
else {
loop {
<else-branch> where loop_nest -= 1
}
}
```
The transformation is not semantically equivalent:
- Let's assume `then-branch` does not have any `break`. In the original code, it can still break the outer loop via the `else-branch`. Yet, in the transformed code, `then-branch` will loop forever ...
- `c_1`, `c_2` etc. can be updated by `then-branch` and `else-branch` in each iteration in the original code, affecting how the loops work. Yet, in the optimized code, they become irrelevant once the …
> [decompiler]: fix issues in control flow optimizations

- config/src/config/state_sync_config.rs
- state-sync/storage-service/server/src/handler.rs
- state-sync/storage-service/types/src/requests.rs
- state-sync/storage-service/types/src/responses.rs
- state-sync/storage-service/types/src/tests.rs
This PR adds new RPC request types to the storage service for transaction data v2 (i.e., transactions with auxiliary data). It also includes all the basic tests for serviceability.
Note: we've updated the storage service to drop the requests if it receives them (e.g., from a malicious client). In the next PR, we'll begin processing the requests.
> [Storage Service] Add new request types for txn V2 data.

- .github/workflows/workflow-run-replay-verify-on-archive.yaml
The jobs needs a job-level timeout in addition to step level timeout.
> [bugfix] add job-level timeout to replay verify

- config/src/config/transaction_filters_config.rs
- consensus/Cargo.toml
- consensus/src/block_storage/block_store.rs
- consensus/src/counters.rs
- consensus/src/dag/tests/helpers.rs
- consensus/src/epoch_manager.rs
- consensus/src/payload_manager/co_payload_manager.rs
- consensus/src/payload_manager/direct_mempool_payload_manager.rs
- consensus/src/payload_manager/mod.rs
- consensus/src/payload_manager/quorum_store_payload_manager.rs
- consensus/src/round_manager.rs
- consensus/src/round_manager_fuzzing.rs
- consensus/src/round_manager_tests/consensus_test.rs
- consensus/src/round_manager_tests/mod.rs
- consensus/src/round_manager_tests/opt_proposal_test.rs
- consensus/src/round_manager_tests/txn_filter_proposal_test.rs
- consensus/src/round_manager_tests/vtxn_on_proposal_test.rs
- crates/aptos-transaction-filters/src/block_transaction_filter.rs
- crates/aptos-transaction-filters/src/tests/block_transaction_filter.rs
This PR extends transaction filtering support to consensus. It offers the following commits:
1. Adopt the block transaction filter when processing payloads, and reject/drop any proposals that include denied inline transactions.
2. Add new unit tests for the logic.
> [Transaction Filter] Extend filtering support.

- .github/workflows/replay-verify-mainnet.yaml
- .github/workflows/replay-verify-testnet.yaml
- testsuite/replay-verify/replay-verify-worker-template.yaml
Switch instance type to C3D.
Split the workflow in two: separate testnet from mainnet and leave 6 hours between the runs, to avoid a peak of nearly 5k cores used when both run in parallel.
> Run replay-verify on C3D instead of T2D

- .github/actions/wait-images-ci/action.yaml
- .github/workflows/copy-images-to-dockerhub.yaml
- .github/workflows/node-api-compatibility-tests.yaml
- .github/workflows/prune-old-workflow-runs.yaml
- .github/workflows/test-copy-images-to-dockerhub.yaml
Maintenance update: switch all jobs to setup-node@v4 for better performance and compatibility. Pure maintenance, behavior unchanged. More details in the [v4.0.0 release](https://github.com/actions/setup-node/releases/tag/v4.0.0).
> ci: bump setup-node to v4

- api/types/src/transaction.rs
- crates/aptos/src/common/transactions.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
- sdk/src/transaction_builder.rs
In order to create orderless transaction, add `--replay-protection-type turbo` at the end of your move command.
```
cargo run --bin aptos -- move run   --profile testnet  --replay-protection-type nonce --function-id 0x1::aptos_account::transfer --args address:0x49ffe7968750a5ffea80af6fd7657bb246ff8ce6657cbf2c8ed13d9276096b3f u64:20000
```
> Adding replay protection type option in Move CLI

- config/src/config/state_sync_config.rs
- state-sync/storage-service/server/src/handler.rs
- state-sync/storage-service/server/src/optimistic_fetch.rs
- state-sync/storage-service/server/src/storage.rs
- state-sync/storage-service/server/src/subscription.rs
- state-sync/storage-service/server/src/tests/cache.rs
- state-sync/storage-service/server/src/tests/mock.rs
- state-sync/storage-service/server/src/tests/new_transaction_outputs.rs
- state-sync/storage-service/server/src/tests/new_transactions.rs
- state-sync/storage-service/server/src/tests/new_transactions_or_outputs.rs
- state-sync/storage-service/server/src/tests/optimistic_fetch.rs
- state-sync/storage-service/server/src/tests/subscribe_transaction_outputs.rs
- state-sync/storage-service/server/src/tests/subscribe_transactions.rs
- state-sync/storage-service/server/src/tests/subscribe_transactions_or_outputs.rs
- state-sync/storage-service/server/src/tests/subscription.rs
- state-sync/storage-service/server/src/tests/transaction_outputs.rs
- state-sync/storage-service/server/src/tests/transactions.rs
- state-sync/storage-service/server/src/tests/transactions_or_outputs.rs
- state-sync/storage-service/server/src/tests/utils.rs
- state-sync/storage-service/server/src/utils.rs
- state-sync/storage-service/types/src/responses.rs
- storage/aptosdb/src/db/include/aptosdb_reader.rs
- storage/aptosdb/src/db/include/aptosdb_testonly.rs
- storage/storage-interface/src/lib.rs
- types/src/transaction/mod.rs
Notes:
- 95% of this PR is me updating 60+ unit tests. 😓 The line count is also artificially increased because the diffs can't tell when I've added lines around code blocks 👀
This PR adds new RPC response types for transaction v2 data in state sync. It offers the following commits:
1. Add the new response types, including the transaction v2 lists and the storage service functionality to read the auxiliary data from the DB.
2. Update unit tests to the various components. This is the large commit, and just boilerplate.
> [Storage Service] Add new response types for txn V2 data.

- testsuite/replay-verify/main.py
- testsuite/replay-verify/replay-verify-worker-template.yaml
Remove resource limit to allow getting as much as possible if available on the instance.
Schedule on a dedicated node pool, and oversubscribe each instance to
take advantage of running without limits.
Increase the replay parallelism to be higher than core count.
Remove some noisy logging that caused the Github UI to freeze.
> Adjust resources for replay-verify

- third_party/move/tools/move-linter/src/model_ast_lints.rs
- third_party/move/tools/move-linter/src/model_ast_lints/assert_const.rs
- third_party/move/tools/move-linter/tests/model_ast_lints/assert_const.exp
- third_party/move/tools/move-linter/tests/model_ast_lints/assert_const.move
assert_const flags assert!(true) and assert!(false) and suggests replacements.
This PR implements bullet point
> Find cases of assert!(true) or assert!(false), and suggest they can either be removed or replaced with an explicit abort.
from https://github.com/aptos-labs/aptos-core/issues/15221
Positive and negative test cases have been added to the move lint unit tests.
Additionally, the linter has been run on the crates in the `aptos-move/framework` subdirectory, with the following results:
Crate | Result | Notes
-|-|-
aptos-experimental | Language errors | Move 2.2 language construct is not enabled
aptos-framework | 1 warning | See below
aptos-stdlib | No warnings |  
aptos-token | No warnings |  
aptos-token-objects | No warnings |  
move-stdlib | No warnings |  
table-natives | No …
> [lint] Implemented assert_const linter

- testsuite/replay-verify/archive-pvc-template.yaml
- testsuite/replay-verify/archive_disk_utils.py
Try using PD-BALANCED instead of PD-SSD for replay-verify, as it's 2x cheaper.
> [replay-verify] Try PD-BALANCED instead of PD-SSD

- third_party/move/testing-infra/transactional-test-runner/src/framework.rs
- third_party/move/tools/move-asm/src/assembler.rs
- third_party/move/tools/move-asm/src/module_builder.rs
- third_party/move/tools/move-asm/src/syntax.rs
- third_party/move/tools/move-asm/tests/assembler/call_different_module.exp
- third_party/move/tools/move-asm/tests/assembler/call_different_module.masm
- third_party/move/tools/move-asm/tests/assembler/declare_entry_fun.exp
- third_party/move/tools/move-asm/tests/assembler/declare_entry_fun.masm
- third_party/move/tools/move-asm/tests/assembler/enum.exp
- third_party/move/tools/move-asm/tests/assembler/enum.masm
- third_party/move/tools/move-asm/tests/assembler/enum_generic.exp
- third_party/move/tools/move-asm/tests/assembler/enum_generic.masm
- third_party/move/tools/move-asm/tests/assembler/resource.exp
- third_party/move/tools/move-asm/tests/assembler/resource.masm
- third_party/move/tools/move-asm/tests/assembler/resource_generic.exp
- third_party/move/tools/move-asm/tests/assembler/resource_generic.masm
- third_party/move/tools/move-asm/tests/assembler/struct.exp
- third_party/move/tools/move-asm/tests/assembler/struct.masm
- third_party/move/tools/move-asm/tests/assembler/struct_generic.exp
- third_party/move/tools/move-asm/tests/assembler/struct_generic.masm
- third_party/move/tools/move-asm/tests/assembler/struct_use.exp
- third_party/move/tools/move-asm/tests/assembler/struct_use.masm
- third_party/move/tools/move-asm/tests/assembler/unknown_field.exp
- third_party/move/tools/move-asm/tests/assembler/unknown_field.masm
- third_party/move/tools/move-asm/tests/assembler/unknown_variant.exp
- third_party/move/tools/move-asm/tests/assembler/unknown_variant.masm
This implements declaration of structs and enums as well as the related bytecodes, and completes most of the assembler functionality. There are still things missing (like string constants for byte vectors) but otherwise should be fairly complete, or can be easily extended self-service style.
New tests
> [move-asm] Struct and enum related features

- testsuite/forge/src/config.rs
To make sure the config remains compatible with 1.32 branch, because the config was added after 1.32.
> disable opt proposal in 1.33 branch

- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/block-executor/src/captured_reads.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/scheduler_status.rs
- aptos-move/block-executor/src/scheduler_v2.rs
- aptos-move/block-executor/src/view.rs
- aptos-move/e2e-tests/src/executor.rs
- aptos-move/mvhashmap/src/unit_tests/dependencies.rs
- aptos-move/mvhashmap/src/unit_tests/mod.rs
- aptos-move/mvhashmap/src/unit_tests/proptest_types.rs
- aptos-move/mvhashmap/src/versioned_data.rs
- aptos-move/mvhashmap/src/versioned_group_data.rs
- aptos-move/replay-benchmark/src/execution.rs
- types/src/block_executor/config.rs
- Address comments on landed PRs, incl. a fix to early return to fallback on errors properly (before side effects).
- Add a local config flag, set to false.
- Refactor docs.
> BlockSTMv2 PR [10.5/n]: Retrospective comments, v2 flag, simple refactors

- testsuite/forge-test-runner-template.yaml
Looking at the last 30 days of Forge, the runners maxed out at around 8 cores and 14G RAM, so reduce the minimum request and eliminate limits, to allow runners to burst if necessary.
> Reduce resources for Forge runner

- config/src/config/state_sync_config.rs
- state-sync/aptos-data-client/src/client.rs
- state-sync/aptos-data-client/src/interface.rs
- state-sync/aptos-data-client/src/tests/advertise.rs
- state-sync/aptos-data-client/src/tests/compression.rs
- state-sync/aptos-data-client/src/tests/mock.rs
- state-sync/aptos-data-client/src/tests/mod.rs
- state-sync/aptos-data-client/src/tests/peers.rs
- state-sync/aptos-data-client/src/tests/request_v2.rs
- state-sync/data-streaming-service/src/data_stream.rs
- state-sync/data-streaming-service/src/stream_engine.rs
- state-sync/data-streaming-service/src/tests/streaming_service.rs
- state-sync/data-streaming-service/src/tests/utils.rs
- state-sync/storage-service/server/src/tests/new_transaction_outputs.rs
- state-sync/storage-service/server/src/tests/new_transactions.rs
- state-sync/storage-service/server/src/tests/new_transactions_or_outputs.rs
- state-sync/storage-service/server/src/tests/optimistic_fetch.rs
- state-sync/storage-service/server/src/tests/subscription.rs
- state-sync/storage-service/server/src/tests/transaction_outputs.rs
- state-sync/storage-service/server/src/tests/transactions_or_outputs.rs
- state-sync/storage-service/server/src/tests/utils.rs
- state-sync/storage-service/types/src/requests.rs
- state-sync/storage-service/types/src/responses.rs
- state-sync/storage-service/types/src/tests.rs
- types/src/transaction/mod.rs
Notes:
- This PR is mostly just new unit tests 😄 
This PR updates the Aptos data client to support transaction v2 data in state sync. It offers the following commits:
1. Refactor: Add helper methods for request creation.
2. Aptos Data Client: Add support for fetching transaction v2 data. If v2 support is disabled (via the config flag), the client will only fetch v1 data (without aux infos), and populate the aux info responses with `None` results. 
- Note: the aux infos are currently dropped by the data streaming service. In the next PR, we'll avoid this.
4. Tests: Add tests to the data client (to verify the new feature and flag).
> [Aptos Data Client] Add support for txn V2 data

- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/runtime_type_checks.rs
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_local_num.baseline.exp
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_local_num.masm
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_local_num.paranoid.exp
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_pass.baseline.exp
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_pass.masm
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_pass.paranoid.exp
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_return.baseline.exp
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_return.masm
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_assign_return.paranoid.exp
- third_party/move/move-vm/transactional-tests/tests/function_values_safety/closure_captured_typing.paranoid.exp
- third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
- The captured argument types are now checked _before_ the LazyFunction is constructed, which requires to construct layouts. Thus a more descriptive error will be produced than failure in layout construction.
- Types of returned values of a function are checked explicitly. Before, those types would have been checked at some later point implicitly, when the returned values are used. Though the current behavior isn't wrong, the adjusted behavior is more aligned with what the bytecode verifier does.
Closes #17156
New tests, all tests change behavior
> [move-vm] Some fixes for runtime checks

- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/keyless_validation.rs
- aptos-move/aptos-vm/src/move_vm_ext/session/mod.rs
- third_party/move/move-vm/integration-tests/src/tests/module_storage_tests.rs
- third_party/move/move-vm/runtime/src/data_cache.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/native_functions.rs
- third_party/move/move-vm/runtime/src/storage/loader/eager.rs
- third_party/move/move-vm/runtime/src/storage/loader/lazy.rs
- third_party/move/move-vm/runtime/src/storage/loader/traits.rs
- third_party/move/move-vm/runtime/src/storage/module_storage.rs
- types/src/account_config/resources/core_account.rs
This PR adds support for metered metadata accesses:
```rust
pub trait ModuleMetadataLoader {
fn load_module_metadata(
&self,
gas_meter: &mut impl GasMeter,
traversal_context: &mut impl ModuleTraversalContext,
module_id: &ModuleId,
) -> PartialVMResult<Vec<Metadata>>;
}
```
Lazy loader charges gas for metadata if module is not visited. Eager loader is unmetered.
On Aptos VM layer, metadata is accessed without loader. There, we expect all metadata accesses be metered or not requiring metering:
1. Getting an error information in Aptos VM: module must be visited if it error's location is set to its ID.
2. Checking if account needs creation: `Account` is defined at `0x1`, no metering needed.
3. Fetching keyless resources: those are defined at special addresses, no metering needed.
4. When …
> [lazy-loading] Module metadata integration (6/n)

- crates/aptos-dkg/benches/crypto.rs
Just adding a few useful benchmarks to `aptos-dkg`.
No need; just benchmarks.
Nothing.
> add benchmarks for field ops

- aptos-move/framework/aptos-framework/doc/staking_contract.md
- aptos-move/framework/aptos-framework/sources/staking_contract.move
Add this function for CB which can help customized indexing since most functions need both staker and pool address but we don't have onchain mapping before.
e2e
> [staking_contract] add view function to get staker given pool address

- Cargo.lock
- crates/aptos-transaction-filters/src/batch_transaction_filter.rs
- crates/aptos-transaction-filters/src/block_transaction_filter.rs
- crates/aptos-transaction-filters/src/transaction_filter.rs
- testsuite/smoke-test/Cargo.toml
- testsuite/smoke-test/src/lib.rs
- testsuite/smoke-test/src/transaction_filter.rs
This PR adds several new smoke tests to verify the functionality of different transaction filters (i.e., mempool, quorum store, and consensus).
> [Transaction Filter] Add simple smoke tests for filter.

- consensus/src/counters.rs
> Label status codes for discarded transactions

- Cargo.lock
- Cargo.toml
- third_party/move/tools/move-package-cache/Cargo.toml
- third_party/move/tools/move-package-cache/src/canonical.rs
- third_party/move/tools/move-package-cache/src/file_lock.rs
- third_party/move/tools/move-package-cache/src/lib.rs
- third_party/move/tools/move-package-cache/src/listener.rs
- third_party/move/tools/move-package-cache/src/main.rs
- third_party/move/tools/move-package-cache/src/package_cache.rs
This implements the Move Package Cache, a component of the next-gen package system.
It is responsible for downloading, indexing, and storing all remote dependencies (Git repositories and on-chain packages) in a local globally accessible directory.
The package cache is implemented as a modular library and is intended to be used by other tools in the Move ecosystem, such as the package resolver.
The package cache manages two types of dependencies:
- **Git repositories** (`git/`): Full Git repositories and immutable checkouts at specific commits
- **On-chain packages** (`on-chain/`): Bytecode packages from the blockchain
```
.
├── git
│   ├── checkouts/     # Immutable snapshots at specific commits
│   └── repos/         # Full Git repositories
└── on-chain/          # Fetched bytecode …
```
> [new move package] implement package cache

- aptos-move/block-executor/src/cold_validation.rs
- aptos-move/block-executor/src/lib.rs
- aptos-move/block-executor/src/scheduler_status.rs
Half of the PR is tests.
A structure to manage cold validation requirements, i.e. validations that are not likely to be performed often or for all the blocks. Validations that occur due to module publishing are a primary example: we do not want each speculative execution of every transaction to record their accesses when most likely those are not going to be invalidated. For such requirements when the condition for validation is met, a dedicated worker will traverse the affected transactions and perform required validations (only Executing or Executed transactions at the time when validation is requested are affected, and moreover, with a specific incarnation, as if the transaction re-executes with a new incarnation afterwards, it will observe correct data).
This structure and its …
> BlockSTMv2 PR [9/n]: Managing cold validation requirements & tests

- aptos-move/framework/aptos-framework/doc/account.md
- aptos-move/framework/aptos-framework/doc/coin.md
- aptos-move/framework/aptos-framework/sources/account/account.move
- aptos-move/framework/aptos-framework/sources/account/account.spec.move
- aptos-move/framework/aptos-framework/sources/coin.move
delete coinstore that has 0 balance but 
1. already initialized 
2. not able to convert to valid FA because of > 32 decimals.
> [migration] delete invalid coinstore that cannot be migrated

- config/src/config/state_sync_config.rs
- state-sync/storage-service/server/src/storage.rs
- state-sync/storage-service/server/src/tests/cache.rs
- state-sync/storage-service/server/src/tests/new_transaction_outputs.rs
- state-sync/storage-service/server/src/tests/new_transactions.rs
- state-sync/storage-service/server/src/tests/new_transactions_or_outputs.rs
- state-sync/storage-service/server/src/tests/subscribe_transaction_outputs.rs
- state-sync/storage-service/server/src/tests/subscribe_transactions.rs
- state-sync/storage-service/server/src/tests/subscribe_transactions_or_outputs.rs
- state-sync/storage-service/server/src/tests/subscription.rs
- state-sync/storage-service/server/src/tests/transaction_outputs.rs
- state-sync/storage-service/server/src/tests/transactions.rs
- state-sync/storage-service/server/src/tests/transactions_or_outputs.rs
- state-sync/storage-service/server/src/tests/utils.rs
This PR updates the storage service to respect the max response sizes specified by clients when making requests for v2 transaction data. Now, the storage service will use the client specified size, or the local storage config maximum, whichever is smaller (to avoid excessive data sizes). The PR also increases the default max response size from 10MB -> 15MB (to help favor output syncing).
1. Update the storage service to respect the max response sizes.
2. Update the tests to verify the new functionality.
> [Storage Service] Respect max response sizes for v2 requests.

- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs
- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/optimizers.rs
- third_party/move/tools/move-unit-test/tests/test_sources/issue_17188.exp
- third_party/move/tools/move-unit-test/tests/test_sources/issue_17188.move
The compiler's peephole optimizations on file-format bytecode has an issue on maintaining the code loc info. See #17188 for an example. 
Specifically, the optimizer ignored previously-maintained location mapping during recursive optimizations. This PR fixes the issue.
Close #17188 
- Existing `move-unit-test` with a new test case borrowed from #17188
> fix issue #17188

- .github/workflows/forge-stable.yaml
- .github/workflows/workflow-run-forge.yaml
- testsuite/forge.py
Adds a new env variable to indicate to forge wrapper of a forge continuous test from land blocking test. This is to ensure forge only fails on land blocking test for soft failures.
> [forge] Soft failures shouldn't exit with code 1

- third_party/move/move-model/bytecode/src/astifier.rs
- third_party/move/tools/move-decompiler/tests/control-flow-recovery/noexit_loops.exp
- third_party/move/tools/move-decompiler/tests/move-v2-features/closure.exp
- third_party/move/tools/move-decompiler/tests/move-v2-features/enum.exp
The decompiler optimizes the following pattern
```Move
t1 = rhs;
...
use(t1)
```
===>
```Move
...
use(rhs)
```
If `t1` is never used (i.e., `use(t1)` does not exist), the decompiler will eliminate `t1 = rhs` entirely. This is not safe as `rhs` can have side effects (e.g., `rhs` being a function call). This PR fixes this issue by checking if `rhs` carries potential side effects. Currently, it only checks if `rhs` is a `Call(Operation::MoveFunction)` or `Invoke`. 
Close issue #17008.
- Existing decompiler test cases
> fix decompiler assignment optimization issue #17008

- third_party/move/move-compiler-v2/src/env_pipeline/inliner.rs
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_17283_a.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_17283_a.move
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_17283_b.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_17283_b.move
- third_party/move/move-prover/tests/sources/functional/inline-lambda.exp
When inlining, if the free variables in the lambda expressions being inlined could get shadowed, then using name mangling, such shadowing is prevented.
But if lambda expressions captured function parameters of the inline function caller, then it would not be part of free variables (because it would show up as a used temporary). This caused incorrect shadowing, leading to compiler ICE, bytecode verification errors, etc.
This PR fixes the computation of free variables in the lambda expressions during inlining, and thus the above errors.
Close #17283.
Added new tests that failed with compiler ICE previously, that now perform computations as expected.
> [compiler-v2] Fix inlining when params are captured and shadowed in lambdas

- third_party/move/testing-infra/transactional-test-runner/Cargo.toml
The interpreter attaches `exec_state` on error, only if `"testing"` or `"stacktrace"` features are enabled https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-vm/runtime/src/interpreter.rs#L842).
Recently, `transactional-test-runner`'s dependency on `move-vm-runtime` was changed from `[features = "testing"]` to `features = ["disable_verifier_cache"]`. This caused transactional tests to no longer have `exec_state`s attached.
We fix it in this PR.
> [transactional-test] Fix features expected for transactional test runner

- .github/actions/wait-images-ci/action.yaml
- .github/workflows/docker-build-test.yaml
- .github/workflows/replay-verify-mainnet.yaml
- .github/workflows/replay-verify-testnet.yaml
- .github/workflows/workflow-run-docker-rust-build.yaml
- .github/workflows/workflow-run-replay-verify-on-archive.yaml
- docker/image-helpers.js
- docker/wait-images-ci.mjs
Ticket involved: https://app.clickup.com/t/868d02t85
replay-verify-on-archive workflow fails if an image tag passed in does not exist. 
Fix issue on replay-verify-on-archive running without proper image being built. This PR fixes that by building the image if it's does not already exist and no other job is currently building them. 
It checks first if the image is built: 
- If its already built, it skips the building process and goes straight into the test
- If its not built, it checks if there is another workflow building the images via existence of a lock file in a gcs bucket
- If the lock file exists, the workflow is intended to exit with a message specifying where the image is already being built/ workflow is being run
- if the lock file doesn't exist, the docker image build process …
> [ci] build images automatically if not present

- third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
- third_party/move/move-prover/tests/sources/functional/closures/closure_empty_result.move
This fixes a boogie translation error when not storing results of function values. Without this fix, is possible to cause boogie compiler error from move code translation.
New tests added
There is one additional area that looks suspicious: the write statement on line 1969 of `bytecode_translate` (the `Function/Closure` arm of `translate_bytecode` function. This arm emits similar looking boogie code. I did not add a guard to check for empty `dest_str` here because I was unable to find a test case where `dest_str` is actually empty and so I am not sure it is even possible. Perhaps I should still add a check here just incase though?
> [Prover] Fixing boogie formatting command for fun values

- mempool/src/counters.rs
- mempool/src/shared_mempool/network.rs
- mempool/src/shared_mempool/tasks.rs
This PR adds new logs and metrics to the shared mempool broadcast loop. The purpose is to improve observability of the loop, and better highlight any errors.
> [Mempool] Add metrics & logs for broadcast behaviour.

- config/src/config/inspection_service_config.rs
- crates/aptos-inspection-service/src/server/identity_information.rs
- crates/aptos-inspection-service/src/server/index.rs
- crates/aptos-inspection-service/src/server/mod.rs
- crates/aptos-inspection-service/src/server/tests.rs
This PR adds an `identity_information` endpoint to the node inspection service, allowing node operators to quickly fetch the peer IDs of each network in their nodes. 
For example, running a local PFN and accessing `localhost:9101/identity_information` will produce this output:
```
Identity Information:
- Fullnode network (Public), peer ID: 0x595c2fc0fe636ebfeb89ea136c7494849cafe5d429f38200a0d5e197bdedde53
```
Existing test infrastructure and manual verification.
> [Inspection Service] Add "identity_information" endpoint.

- api/src/basic.rs
This PR adds peer ID information to the `/info` endpoint for the REST API. After pinging the `/info` endpoint, you now get responses like this:
```
{"fullnode_network_peer_id_Public":"266687edf6bb6f90f28b84bf00ec2234eb3f36f0f23bc722566e5515366ad057",..."}
```
Existing test infrastructure and manual verification.
> [API] Add peer IDs to "/info" endpoint.

- .github/actions/fullnode-sync/fullnode_sync.py
This PR enables storage sharding on the fullnode sync Github actions (i.e., nightly tests). This is now required, and if it is not set, the fullnode panics. The tests are currently failing because of this.
Manual verification (e.g., see here: https://github.com/aptos-labs/aptos-core/actions/runs/17197860491)
> [Fullnode Sync] Enable storage sharding on the fullnode sync tests.

- api/src/tests/account_abstraction_test.rs
- api/src/tests/accounts_test.rs
- api/src/tests/simulation_test.rs
- api/src/tests/state_test.rs
- api/src/tests/string_resource_test.rs
- api/src/tests/transaction_vector_test.rs
- api/src/tests/transactions_test.rs
- api/src/tests/view_function.rs
- api/test-context/src/test_context.rs
- crates/aptos/src/common/transactions.rs
- crates/aptos/src/common/types.rs
- crates/transaction-workloads-lib/src/args.rs
- crates/transaction-workloads-lib/src/move_workloads.rs
- execution/executor-benchmark/src/db_reliable_submitter.rs
- execution/executor-benchmark/src/lib.rs
- execution/executor-benchmark/src/transaction_generator.rs
- sdk/src/transaction_builder.rs
- testsuite/single_node_performance_values.tsv
- types/src/transaction/mod.rs
There are two ways folks will commonly use orderless:
* switch to always use orderless. For that it should be a flag in TransactionFactory, so it doesn't need to be done on per-txn level
* for a specific transaction, set nonce. upgrade_payload allows to set a random one, adding set_replay_protection_nonce when user wants to explicitly set it.
In executor benchmark, there is an issue that we don't create BlockMetadata, and so timestamp is always 0. because orderless txns can be only set with max 60s expiration, they all fail. Adding ability to set absolute expiration to transaction factory, and set it to 30 for executor benchmark.
Alternatively, we should allow BlockMetadata in benchmark, but I run into some issues implementing it (here is the change for that - …
> Orderless TransactionFactory improvements and integration with executor benchmark

- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer.rs
- third_party/move/move-compiler-v2/src/file_format_generator/peephole_optimizer/optimizers.rs
In this PR, we add a unit test for peephole optimization (for both the code transformation and offset remapping calculation used for source locations).
While the peephole optimization itself is reasonably well tested with compiler end-to-end tests and transactional tests, the location transformation was not explicitly tested, which this PR addresses.
The added unit test triggers multiple peephole optimizations in multiple passes and multiple basic block merges. It fails before the bug fix in #17403, but passes now.
Adds a new test.
> [compiler-v2] Adding unit test for peephole optimizer

- ecosystem/indexer-grpc/indexer-grpc-table-info/src/table_info_service.rs
Propagating the error from value annotator so that the node does not panic, and only grpc is not working.
> [indexer] Propagate errors

- .github/actions/get-latest-docker-image-tag/action.yml
- .github/workflows/cli-e2e-tests.yaml
- .github/workflows/forge-stable.yaml
- .github/workflows/node-api-compatibility-tests.yaml
`get-latest-docker-image-tag` sometimes times out. Add a simple retry
Example failure:
https://github.com/aptos-labs/aptos-core/actions/runs/17309005899/attempts/1
Workflows run on PR that use that composite action
> [gha] add retry to get-latest-docker-image-tag

- Cargo.lock
- keyless/pepper/README.md
- keyless/pepper/example-client-rust/Cargo.toml
- keyless/pepper/example-client-rust/src/lib.rs
- keyless/pepper/example-client-rust/src/main.rs
- keyless/pepper/example-client-rust/src/utils.rs
- keyless/pepper/scripts/start-pepper-client.sh
- keyless/pepper/scripts/start-pepper-service.sh
This PR cleans up the pepper service client example and attempts to make it a little more approachable from a developer perspective, e.g., make the required and optional steps clearer, refactor code into modular groups, standardize flows, use real random number generation, support command line inputs, etc. Outside of cosmetic changes, nothing else should really change.
Manual verification (i.e., I re-ran the client example against a local pepper service and verified that the flows worked correctly).
> [Keyless] Clean up pepper service client example.

- third_party/move/tools/move-linter/src/model_ast_lints.rs
- third_party/move/tools/move-linter/src/model_ast_lints/aborting_overflow_checks.rs
- third_party/move/tools/move-linter/tests/model_ast_lints/aborting_overflow_checks.exp
- third_party/move/tools/move-linter/tests/model_ast_lints/aborting_overflow_checks.move
This PR adds a new lint to `aptos move lint`: Checking for C-like overflow checks, as requested in #15221
> Find code patterns that resemble C-style underflow/overflow checks: `if (a + b < a) { ... }`.
Added test in `move_linter/tests` folder
This lint do not triggers in any file in `aptos-move/framework/*`.
- Recognized patterns are enough?
- Lint message.
New feature
Other (move_linter)
> [linter] Added aborting_overflow_checks lint

- third_party/move/move-compiler-v2/src/env_pipeline/function_checker.rs
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_17477.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_17477.move
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_17477.opt.exp
Closes #17477.
When a spec block is present, the checker for privileged access incorrectly did an early return, skipping checking other AST nodes coming after it. Instead, we now skip the check only for AST nodes that are descendants of a spec bloc.
Added a new test.
> [compiler-v2] Fix privileged access error when spec blocks are present

- Cargo.lock
- keyless/pepper/service/Cargo.toml
- keyless/pepper/service/src/cached_resources.rs
- keyless/pepper/service/src/jwk.rs
- keyless/pepper/service/src/lib.rs
- keyless/pepper/service/src/main.rs
- keyless/pepper/service/src/metrics.rs
- keyless/pepper/service/src/request_handler.rs
- keyless/pepper/service/src/tests/process_common.rs
- keyless/pepper/service/src/tests/request_handler.rs
- keyless/pepper/service/src/utils.rs
This PR makes several cleanups to the JWK fetching logic in the pepper service. For example, it:
- Removes the use of lazy/static variables (so that the code can be tested efficiently), and adds appropriate unit tests.
- Adds a new pepper service endpoint `/cached/jwk` which exposes the state of the JWK cache. This is useful for observability and debugging, e.g., at runtime we can see the supported JWK issuers and keys (see below).
- Refactors the code, improves runtime logging for JWK updates, etc.
The snippet below shows an example response when hitting the new endpoint:
```
{
...
"https://accounts.google.com": {
"2d7ed338c0f1457b214a274b5e0e667b44a42dde": {
"kid": "2d7ed338c0f1457b214a274b5e0e667b44a42dde",
"kty": "RSA",
"alg": "RS256",
"e": "AQAB",
"n": …
```
> [Keyless] Clean up JWK fetching logic, add tests, and a new endpoint.

- state-sync/data-streaming-service/src/stream_engine.rs
- state-sync/data-streaming-service/src/tests/stream_engine.rs
- state-sync/state-sync-driver/src/driver.rs
- state-sync/state-sync-driver/src/error.rs
- state-sync/state-sync-driver/src/notification_handlers.rs
This PR updates the state sync driver to return an error if it detects that consensus has sent a sync request with a version less than the pre-committed, or committed versions. It also updates the continuous transaction stream engine to return an error if a stream is created that cannot request any data (because the target is not ahead of the currently known version).
> [State Sync] Check pre-committed version on sync requests.

- Cargo.lock
- aptos-move/aptos-vm/src/block_executor/mod.rs
- aptos-move/block-executor/Cargo.toml
- aptos-move/block-executor/src/combinatorial_tests/mock_executor.rs
- aptos-move/block-executor/src/combinatorial_tests/resource_tests.rs
- aptos-move/block-executor/src/counters.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/executor_utilities.rs
- aptos-move/block-executor/src/scheduler.rs
- aptos-move/block-executor/src/scheduler_status.rs
- aptos-move/block-executor/src/scheduler_v2.rs
- aptos-move/block-executor/src/scheduler_wrapper.rs
- aptos-move/block-executor/src/task.rs
- aptos-move/block-executor/src/txn_last_input_output.rs
- aptos-move/mvhashmap/src/lib.rs
- aptos-move/mvhashmap/src/versioned_data.rs
- aptos-move/mvhashmap/src/versioned_delayed_fields.rs
- aptos-move/mvhashmap/src/versioned_group_data.rs
Refactors block epilogue txn to be executed and materialized after the main worker loop has completed, but reusing the structures (txn_last_input_output, mvhashmap, etc) involved. Unless we observe any performance issues (e.g. epilogue txn logic becomes heavy), this approach provides clean separation and a relative safety of no concurrent workers.
More specifically:
(1) changes in multi-versioned data structure to truncate above the last committed version are reverted, instead we use a view at an appropriate index and adjust execution / materialization logic to view block epilogue txn as just an incarnation of a txn at that index (if txn_idx == num_txns, then it's a fresh incarnation 0 and the scheduler is not even needed). 
(2) whether block epilogue should be appended is now determined …
> BlockSTMv2 PR [11/n]: block epilogue support

- Cargo.lock
- Cargo.toml
- aptos-move/block-executor/src/executor.rs
- aptos-move/block-executor/src/txn_last_input_output.rs
- types/Cargo.toml
- types/src/state_store/state_value.rs
Two optimizations:
1) Short circuit value equality checks if length is not equal, or for large values if rapid hash is not equal.
2) When execution detects an inconsistency due to speculative nature of parallel execution and returns early, including validation failure while executing possible in BlockSTMv2, make sure that empty output is not recorded in shared data-structures, moreover causing push invalidations that the scheduler could then add to the stall propagation graph.
> BlockSTMv2 PR [11.2/n]: Short-circuit value Eq, ignore speculative failure output 

- testsuite/replay-verify/main.py
Adjust PVC TTL as workflows are crashing due to disks being deleted.
> Increase replay-verify disk TTL to 9 hours

- third_party/move/move-compiler-v2/src/env_pipeline/inliner.rs
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_17602.exp
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_17602.move
- third_party/move/move-compiler-v2/tests/file-format-generator/bug_17602.opt.exp
Closes #17602.
Compiler crashed when running on the following code:
```move
module 0x42::test {
struct S<A, B, C>(A, B, C) has drop;
struct T<A, B> has drop {
x: A,
y: B
}
inline fun proj_0<A, B: drop, C: drop>(self: S<A, B, C>): A {
let S(x, ..) = self;
x
}
fun test_proj_0(): u8 {
let x = S(42, @0x1, true);
x.proj_0()
}
}
```
This was because the inliner did not type specialize wildcards. This PR fixes this issue.
Added a new test that crashed the compiler before this PR, but now runs as expected.
> [compiler-v2] Compiler crash fix on inlining bodies involving wildcards with type instantiations

- aptos-move/framework/aptos-framework/doc/big_ordered_map.md
- aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.move
- aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.spec.move
`upsert` was missing invariant that ensures that arbitrary new keys are not added. This corrects that
Modified verification test of `upsert` to check for this.
> [Prover] Fix upsert spec

- third_party/move/move-vm/runtime/src/interpreter.rs
Depth checks were used to bound value size. Removing them for `Unpack...` instructions because
- Unpack makes value strictly smaller - no need to check depth (otherwise we must have checked and failed on load from storage or pack)
- This hurts performance
- With lazy loading we will get these metered, so let's remove them before enabling lazy loading :))
> [vm] Remove depth checks for unpack

- api/src/tests/function_value_test.rs
- api/src/tests/move/pack_function_values_with_struct/Move.toml
- api/src/tests/move/pack_function_values_with_struct/sources/test.move
- api/types/src/move_types.rs
When converting from `RawMoveStruct` to `MoveStructValue`, positional field name cannot be directly used as the identifier. This PR adds `_` prefix to avoid the failure.
A new test
Need to double check whether feature flag is needed.
- [] Move/Aptos Virtual Machine
> [api][trivial] fix identifier bug when converting RawMoveStruct into MoveStructValue

- keyless/pepper/service/src/external_resources/jwk_fetcher.rs
- keyless/pepper/service/src/external_resources/resource_fetcher.rs
- keyless/pepper/service/src/main.rs
- keyless/pepper/service/src/metrics.rs
- keyless/pepper/service/src/request_handler.rs
This PR adds simple metrics for operations in the pepper service. These include:
1. Metrics for JWK fetching times and success rates.
2. Metrics for external resource fetching times and success rates (e.g., cached resources).
3. Metrics for request processing and response generation (e.g., request rates, methods, endpoints, errors, etc.)
Existing test infrastructure. More tests will be added soon.
> [Keyless] Add simple metrics for pepper service operation latencies.

- third_party/move/move-compiler-v2/src/env_pipeline/ast_simplifier.rs
- third_party/move/move-compiler-v2/src/env_pipeline/inlining_optimization.rs
- third_party/move/move-compiler-v2/src/env_pipeline/mod.rs
- third_party/move/move-compiler-v2/src/experiments.rs
- third_party/move/move-compiler-v2/src/file_format_generator/mod.rs
- third_party/move/move-compiler-v2/src/lib.rs
- third_party/move/move-compiler-v2/tests/inlining-optimization/caller_callee_shadowing.exp
- third_party/move/move-compiler-v2/tests/inlining-optimization/caller_callee_shadowing.move
- third_party/move/move-compiler-v2/tests/inlining-optimization/fib.exp
- third_party/move/move-compiler-v2/tests/inlining-optimization/fib.move
- third_party/move/move-compiler-v2/tests/inlining-optimization/if_else_const_bool_after_inlining.exp
- third_party/move/move-compiler-v2/tests/inlining-optimization/if_else_const_bool_after_inlining.move
- third_party/move/move-compiler-v2/tests/inlining-optimization/mut_refs_freeze.exp
- third_party/move/move-compiler-v2/tests/inlining-optimization/mut_refs_freeze.move
- third_party/move/move-compiler-v2/tests/inlining-optimization/unbounded_recursion.exp
- third_party/move/move-compiler-v2/tests/inlining-optimization/unbounded_recursion.move
- third_party/move/move-compiler-v2/tests/inlining-optimization/within_module_simple.exp
- third_party/move/move-compiler-v2/tests/inlining-optimization/within_module_simple.move
- third_party/move/move-compiler-v2/tests/testsuite.rs
- third_party/move/move-model/bytecode/src/function_target_pipeline.rs
- third_party/move/move-model/src/ast.rs
- third_party/move/move-model/src/model.rs
In this PR, we implement the inlining compiler optimization:
With inlining, a call site of the form:
```move
foo(a, b, c, ...)
```
where, 
```move
fun foo(x, y, z, ...) { body }
```
becomes:
```move
let (x, y, z, ...) = (a, b, c, ...); body
```
The inlining is applicable only if it is safe to perform such inlinling (e.g., the inlined body should not have operations that cannot be performed by the caller directly, including having function calls that are not visible).
Various heuristics are used to decide whether or not inlining should be performed at a particular callsite: we expect these heuristics to evolve and be tuned. In this PR, we have some default heuristics.
Inlining also makes certain follow up optimizations like AST simplification and code elimination even more applicable. For …
> [compiler-v2] Compiler inlining optimization

- third_party/move/move-compiler-v2/src/env_pipeline/inlining_optimization.rs
- third_party/move/move-compiler-v2/tests/inlining-optimization/nested_loop_labels.exp
- third_party/move/move-compiler-v2/tests/inlining-optimization/nested_loop_labels.move
- third_party/move/move-compiler-v2/tests/inlining-optimization/wildcard.exp
- third_party/move/move-compiler-v2/tests/inlining-optimization/wildcard.move
- third_party/move/move-compiler-v2/transactional-tests/tests/constants/large_vectors.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/control_flow/for_loop_nested_break.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/control_flow/for_loop_non_terminating.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/evaluation_order/lazy_assert.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/evaluation_order/short_circuiting_invalid.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/evaluation_order/struct_arguments.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/inlining/bug_11223.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_14243_stack_size.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_14817_extended.baseline.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_14817_extended.no-optimize.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_14817_extended.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/bug_14817_extended.optimize.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/misc/build_with_warnings.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/assert_one.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy_local.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy_module_lock.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/closures/reentrancy_nested.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_field_select.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_field_select_different_offsets.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/enum/enum_scoping.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/fv_as_keys.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/print_bytecode.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/optimization/bug_14223_unused_non_droppable.opt-extra.exp
- third_party/move/move-compiler-v2/transactional-tests/tests/tests.rs
In this PR, we enable inlining optimization as a config in the compiler's transactional tests. Thus, in addition to running under no-optimize and optimize configs, they all also run under the newly added config and compare outputs.
There are also fixes for:
1. When `#[module_lock] attribute is present, if we perform inlining, we can have more lenient semantics because across-modules calls. While this is safe, to prevent change in semantics, we do not perform inlining when such an attribute is present.
2. When resource access control specifiers (`reads` or `writes`) are present, call sites to those functions should not be inlined because their dynamic access control checks won't be run when they are inlined away.
Also added some more tests, e.g., when the same loop labels are present in …
> [compiler-v2] Enable inlining optimization in transactional tests

- third_party/move/move-compiler-v2/src/env_pipeline/closure_checker.rs
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_1.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_1.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_2.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_2.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_3.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_3.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_4.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_4.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_5_no_warning.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_5_no_warning.move
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_6_phantom.exp
- third_party/move/move-compiler-v2/tests/checking-lang-v2.2/lambda/capturing_option_6_phantom.move
- third_party/move/move-model/src/model.rs
- third_party/move/tools/move-linter/tests/model_ast_lints/equal_operands_in_bin_op.exp
This PR adds to logic to generate warning when trying to capture a value that contains option in a closure.
5 unit tests care added
- [] Validator Node
> [compiler] Add warning for capturing option values

- config/src/config/consensus_observer_config.rs
- consensus/src/consensus_observer/observer/block_data.rs
- consensus/src/consensus_observer/observer/consensus_observer.rs
This PR makes two small improvements to consensus observer:
1. Increases the max number of pending blocks for test networks (e.g., devnet). This is required to handle the increased block production rates.
2. Handles a race condition where state sync notifies CO about a completed sync task, at the same time that CO requests an update to the sync target.
> [Consensus Observer] Increase pending blocks and handle state sync race condition.

- config/src/config/state_sync_config.rs
This PR temporarily disables size and time-aware chunking in the storage service of state sync. This will be reverted when the optimization is stable for legacy data.
> [State Sync] Temporarily disable size and time-aware chunking.

- testsuite/single_node_performance.py
- testsuite/single_node_performance_values.tsv
Single node benchmark fails on Continuous flow (full test) to fetch calibration numbers for monotonic counter because it is not in the table.
> [benchmarks] Update calibration table to include monotonic counter

- keyless/pepper/service/src/dedicated_handlers/pepper_request.rs
- keyless/pepper/service/src/tests/mod.rs
This PR adds several simple tests for pepper and account address generation in the pepper service. These are currently missing, making it difficult to ensure backward compatibility and prevent breakages. To construct these values, I did the following:
1. Wrote the tests, ran them and saved the outputs as hard-coded test constants (as you see in the files here).
2. Checked out this commit of the codebase: https://github.com/aptos-labs/aptos-core/commit/b1ffc171bcf8dee3ba48c0c63686ae0a1feece49 (before any of my changes were made), and added equivalent versions of these tests to ensure the same values were produced. This was the case, thus verifying that no "trivial breakages" were detected.
> [Keyless] Add simple test for pepper and address generation.

- api/src/error_converter.rs
- api/src/runtime.rs
- vm-validator/src/vm_validator.rs
- Catch unwind vm transaction validation to catch panics.
- Catch panics in API to return 500 status code, without crashing the node.
> Catch potential panics without crashing the node

- crates/aptos-telemetry/src/service.rs
This PR improves environment variable handling for telemetry. Currently, if an environment variable is set to false (e.g., `ENV_APTOS_DISABLE_TELEMETRY=false`), the code treats the variable as true (because it only checks for the presence of the variable). Instead, we now check for "truth" values, e.g., `true`, `1`, `yes`, etc.
> [Telemetry] Improve environment variable handling.

- testsuite/replay-verify/replay-verify-worker-template.yaml
Add T2D to the allowed machine families for replay-verify.
> Allow scheduling replay-verify shards on T2D

- execution/executor-benchmark/src/block_preparation.rs
- execution/executor-benchmark/src/transaction_generator.rs
Earlier, the executor benchmark used empty auxiliary info. This PR fixes it.
> Using correct auxiliary information in executor benchmark

- consensus/src/block_storage/sync_manager.rs
There's a race condition where if the commit proof is forwarded, sync manager decides to sync but fails to retrieve block or something, then a lower round commit proof can come and decides to pause pre_commit and sync but previous commit proof can resume the pre_commit to go beyond the target version.
> [consensus] fix a race condition

- Cargo.lock
- aptos-move/aptos-gas-meter/src/algebra.rs
- aptos-move/aptos-gas-schedule/src/gas_schedule/misc.rs
- aptos-move/aptos-memory-usage-tracker/src/lib.rs
- aptos-move/aptos-native-interface/src/context.rs
- aptos-move/aptos-vm-profiling/src/profile_aptos_vm.rs
- aptos-move/aptos-vm-profiling/src/profile_move_vm.rs
- aptos-node/Cargo.toml
- third_party/move/move-core/types/src/account_address.rs
- third_party/move/move-core/types/src/function.rs
- third_party/move/move-vm/metrics/src/lib.rs
- third_party/move/move-vm/runtime/Cargo.toml
- third_party/move/move-vm/runtime/src/access_control.rs
- third_party/move/move-vm/runtime/src/frame.rs
- third_party/move/move-vm/runtime/src/frame_type_cache.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/loader/function.rs
- third_party/move/move-vm/runtime/src/loader/modules.rs
- third_party/move/move-vm/runtime/src/reentrancy_checker.rs
- third_party/move/move-vm/runtime/src/runtime_type_checks.rs
- third_party/move/move-vm/runtime/src/storage/environment.rs
- third_party/move/move-vm/runtime/src/storage/implementations/unsync_module_storage.rs
- third_party/move/move-vm/runtime/src/storage/ty_depth_checker.rs
- third_party/move/move-vm/runtime/src/storage/verified_module_cache.rs
- third_party/move/move-vm/types/Cargo.toml
- third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
- third_party/move/move-vm/types/src/values/values_impl.rs
The Move VM's interpreter loop calls many small helper functions. This PR ensures calls to these functions are always inlined, reduction function call overhead significantly.
> aggresstive inlining in the Move VM interpreter loop

- aptos-move/aptos-vm/src/move_vm_ext/session/user_transaction_sessions/user.rs
- aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
- aptos-move/block-executor/src/code_cache_global_manager.rs
- aptos-move/block-executor/src/counters.rs
- aptos-move/block-executor/src/executor.rs
- aptos-move/e2e-benchmark/data/calibration_values.tsv
- third_party/move/move-vm/runtime/src/frame.rs
- third_party/move/move-vm/runtime/src/frame_type_cache.rs
- third_party/move/move-vm/runtime/src/interpreter.rs
- third_party/move/move-vm/runtime/src/interpreter_caches.rs
- third_party/move/move-vm/runtime/src/loader/function.rs
- third_party/move/move-vm/runtime/src/loader/mod.rs
- third_party/move/move-vm/runtime/src/loader/modules.rs
- third_party/move/move-vm/runtime/src/loader/script.rs
- third_party/move/move-vm/runtime/src/loader/single_signature_loader.rs
- third_party/move/move-vm/runtime/src/loader/type_loader.rs
- third_party/move/move-vm/runtime/src/storage/environment.rs
- third_party/move/move-vm/runtime/src/storage/loader/traits.rs
- third_party/move/move-vm/types/src/lib.rs
- third_party/move/move-vm/types/src/loaded_data/struct_name_indexing.rs
- third_party/move/move-vm/types/src/ty_interner.rs
- types/src/block_executor/config.rs
Per-interpreter cache for generic functions. For every call-site, we cache the loaded function and its frame cache. If not there, we intern the function's type argument vector and load the frame from the cache entry. In practice, interning is done at load time and is not too expensive while it allows us to
1. Drop generic function frame caches when interpreter is done.
2. Re-use instantiated types, and other metadata.
3. Maybe share caches across re-executions in Block-STM!
Tests results in 3-5% speedup.
Existing tests + new tests for fingerprint calculation.
Ensure hashing of type arguments is correct and is collision-resistant (via different salt on different machines)
> [vm] Generic per-interpreter function frame caches
