- ecosystem/platform/server/app/components/icon_component.rb
Now that we're switching to redis for caching, this avoids making a network call to redis every time an icon is rendered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1930)
> [community] Keep icon SVGs in memory.

- .github/workflows/find-packages-with-undeclared-feature-dependencies.yaml
- consensus/Cargo.toml
- crates/aptos-rest-client/Cargo.toml
- crates/bounded-executor/Cargo.toml
- scripts/find-packages-with-undeclared-dependencies.sh
This PR adds missing feature dependencies to some of our rust packages. This is a follow up to some problems that surfaced once we removed the aptos-workspace-hack.
It also adds a script that we'll run every night at 3am to automatically find missing feature declarations in future.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1923)
> devinfra: add missing feature dependencies and add script to automati… …cally find them in future

- Cargo.lock
- execution/executor-benchmark/src/state_committer.rs
- execution/executor-test-helpers/src/integration_test_impl.rs
- execution/executor-types/Cargo.toml
- execution/executor-types/src/executed_chunk.rs
- execution/executor-types/src/in_memory_state_calculator.rs
- execution/executor-types/src/lib.rs
- execution/executor/src/components/apply_chunk_output.rs
- storage/aptosdb/src/backup/restore_handler.rs
- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/aptosdb/src/test_helper.rs
- storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs
- storage/backup/backup-cli/src/utils/mod.rs
- storage/storage-interface/src/in_memory_state.rs
- storage/storage-interface/src/lib.rs
- types/src/proptest_types.rs
- types/src/transaction/mod.rs
As title, we now cache the pending state updates in `state_store.in_memory_state` instead of in_memory_state_calculator.
Also, we commit only at checkpoints the data in `state_store.in_memory_state.updated_from_checkpoint`. 
It is the prep for lazy commit. later we're gonna make the commit function call async.
ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1902)
> [Storage] Delegate state updates caching to state store from InMemoryStateCalculator 

- consensus/src/network_interface.rs
bcs is more compact and efficient than json, json is used for upgrading the messages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1932)
> [consensus] switch back to bcs for consensus messages

- ecosystem/platform/server/app/components/table_header_column_component.rb
- ecosystem/platform/server/app/controllers/application_controller.rb
- ecosystem/platform/server/app/controllers/leaderboard_controller.rb
- ecosystem/platform/server/app/views/leaderboard/it2.html.erb
- ecosystem/platform/server/public/it2_leaderboard_example.json
- `last_metrics_update` is now `latest_reported_timestamp`
- `validator` should not be sortable
- null timestamps are now received as '1970-01-01' instead of an empty string
- increase cache timeout to get more hits (since source data is now updated every 15 minutes instead of every minute)
- adds "this page refreshes every 15 minutes" disclaimer
Manual testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1911)
> [community] Update leaderboard/it2 for new schema.

- consensus/src/epoch_manager.rs
- consensus/src/state_computer.rs
- storage/aptosdb/src/lib.rs
This commit adds a mutex to provide commit and sync_to so they can't run concurrently.
Also we unwrap the storage commit result since we can't do anything if commits fail and we should fail fast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1939)
> [consensus] prevent commit and sync_to happen at the same time

- consensus/src/experimental/buffer_manager.rs
- consensus/src/experimental/decoupled_execution_utils.rs
- consensus/src/experimental/pipeline_phase.rs
- consensus/src/experimental/tests/execution_phase_tests.rs
- consensus/src/experimental/tests/phase_tester.rs
- consensus/src/experimental/tests/signing_phase_tests.rs
Previous implementation only guards the `process` function, this commit changes it to guard the whole `request` life cycle to avoid the race condition that the request is created but not dequeued and the counter is 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1951)
> [consensus] properly guard the buffer manager requests

- consensus/src/experimental/buffer_manager.rs
- consensus/src/experimental/decoupled_execution_utils.rs
- consensus/src/experimental/pipeline_phase.rs
- consensus/src/experimental/tests/execution_phase_tests.rs
- consensus/src/experimental/tests/phase_tester.rs
- consensus/src/experimental/tests/signing_phase_tests.rs
Previous implementation only guards the `process` function, this commit changes it to guard the whole `request` life cycle to avoid the race condition that the request is created but not dequeued and the counter is 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1953)
> [cherry-pick][consensus] properly guard the buffer manager requests

- mempool/src/shared_mempool/coordinator.rs
- mempool/src/shared_mempool/types.rs
The boolean logic was wrong. This means that since #1185 all transactions forwarded from fullnodes were NOT being broadcasted within the validator network.
It's evident that the boolean logic is now fixed to be equivalent to before #1185 when `shared_mempool_validator_broadcast=true` which is the default. TODO to add more testing in general around transaction forwarding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1954)
> Fix validator broadcast of transactions coming from fullnodes

- api/goldens/aptos_api__tests__transactions_test__test_post_transaction_rejected_by_mempool.json
- mempool/src/core_mempool/mempool.rs
- mempool/src/core_mempool/transaction.rs
- mempool/src/core_mempool/transaction_store.rs
- mempool/src/shared_mempool/tasks.rs
- mempool/src/tests/common.rs
- mempool/src/tests/core_mempool_test.rs
- mempool/src/tests/mocks.rs
- mempool/src/tests/node.rs
"Transaction already in mempool" is not very helpful of a message, because it doesn't tell you why it failed.  It's also not hiding anything since you can lookup the pending transaction via the API.
So, I've added a breakdown that tells you if the message matches accordingly.
E2E tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1952)
> [mempool] Improve transaction already in mempool messaging

- mempool/src/shared_mempool/coordinator.rs
- mempool/src/shared_mempool/tasks.rs
- mempool/src/shared_mempool/types.rs
Transactions directly submitted to validators were still being broadcast. Also cherry-pick bug fix from #1954 
Previously, we could see the same transactions in every validator. Not anymore.
Run `cargo x test -p smoke-test -- test_basic_state_synchronization --nocapture` with an injected panic to preserve logs.
```
% grep "get_block" 0/log 1/log 2/log 3/log | grep -v '"txns":""'
0/log:2022-07-13T23:48:47.738494Z [shared-mem] DEBUG mempool/src/core_mempool/mempool.rs:250 {"block_size":1,"name":"get_block","result_size":1,"seen_after":1,"seen_consensus":0,"txns":"D012E1AB072A101E76EF2C6FDC73D930596F29238E70E265E26E8C9C732E3C6D:0 ","walked":1}
0/log:2022-07-13T23:48:48.789123Z [shared-mem] DEBUG mempool/src/core_mempool/mempool.rs:250 …
```
> Do not broadcast client transactions in validator network

- consensus/src/counters.rs
- consensus/src/liveness/leader_reputation.rs
The metrics were being populated only for the author - changing them to be populated for all validators instead - that way we can get a view of all the validator's voting/proposing activity from our node. 
Existing UTs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1963)
> [Consensus] Get metrics for leader reputation metrics across all validators

- consensus/src/counters.rs
- consensus/src/liveness/leader_reputation.rs
Description
The metrics were being populated only for the author - changing them to be populated for all validators instead - that way we can get a view of all the validator's voting/proposing activity from our node.
Test Plan
Existing UTs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1966)
> [Cherry-pick] [Consensus] Get metrics for leader reputation metrics across all validators

- aptos-move/framework/aptos-framework/sources/configs/Stake.move
- aptos-node/src/lib.rs
During genesis, there has been no block so timestamp stored on chain is set to 0. This means that if the initial lockup time provided by the initial validators as part of genesis cannot be validated correctly. This PR allows skipping this validation (trusting the genesis configurations are generated correctly).
E2e tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1978)
> [Genesis] [Aptos Framework] Fix an issue with validator lockup validation when timestamp has not been set (happens during genesis)

- ecosystem/platform/server/app/controllers/leaderboard_controller.rb
- ecosystem/platform/server/app/controllers/static_page_controller.rb
- ecosystem/platform/server/app/helpers/application_helper.rb
- ecosystem/platform/server/app/views/layouts/_application.html.erb
- ecosystem/platform/server/test/controllers/static_page_controller_test.rb
The point was to reduce latency for page loads in combination with a CDN. However, we don't have a CDN so let's remove the HTTP caching to simplify things.
Existing tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1970)
> [community] Remove HTTP caching.

- consensus/src/block_storage/sync_manager.rs
- consensus/src/experimental/buffer_manager.rs
Previously we protect three pipeline phases with atomic counters, but missed the incoming blocks from ordering phase.
It's difficult to do the same with OrderedBlocks because processing that is in the same thread as reset, so we just pull until it's empty.
The assumption is that upon reset request, there's no concurrent incoming blocks but only requests that're already in the queue.
Another race condition is after committing the reconfiguration block, execution will create the new epoch's genesis and drop any leftover blocks.
Continue to execute reconfiguration suffix blocks will result in BlockNotFound error.
Also relaxed the block retrieval timeout from 200ms to 500ms
--- …
> [consensus] another attempt to fix race condition in buffer manager

- Cargo.lock
- aptos-node/Cargo.toml
- aptos-node/src/lib.rs
- aptos-node/src/main.rs
- crates/aptos-faucet-cli/src/main.rs
- crates/aptos-faucet/Cargo.toml
- crates/aptos-faucet/src/lib.rs
- crates/aptos-faucet/src/main.rs
- crates/aptos-rest-client/src/faucet.rs
- crates/aptos-rosetta/Cargo.toml
- crates/aptos-rosetta/src/main.rs
- testsuite/smoke-test/src/aptos_cli.rs
To make it easier to make the dockerfile, I've made the aptos node main thread run in a thread alongside the Rosetta implementation.  It's required by rosetta to run the docker
With this, we may be able to improve the performance better later by not using the REST API.
```
$ cargo run -p aptos-rosetta -- online --test --seed 0000000000000000000000000000000000000000000000000000000000000000
Finished dev [unoptimized + debuginfo] target(s) in 0.29s
Running `target/debug/aptos-rosetta online --test --seed 0000000000000000000000000000000000000000000000000000000000000000`
Entering test mode, this should never be used in production!
Log file: "/tmp/31d462a28b5fb41e16a1c88228a90a1a/validator.log"
Config path: "/tmp/31d462a28b5fb41e16a1c88228a90a1a"
Aptos root …
```
> [aptos-rosetta] Run aptos-node alongside aptos-rosetta

- .github/workflows/build-images.yaml
- .github/workflows/run-forge.yaml
- Cargo.lock
- scripts/run_forge.sh
- terraform/helm/forge/templates/continuous_test.yaml
- terraform/helm/forge/values.yaml
- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/helm-values/aptos-node-values.yaml
- testsuite/forge/src/backend/k8s/helm-values/genesis-values.yaml
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/run_forge.sh
- testsuite/testcases/src/performance_test.rs
- x.toml
Improve Forge reliability and testing:
* Add more detailed healthchecking mechanism after network spin-up. Now requires all validators to reach version 100 before deeming the network healthy
* Increase performance test duration to 3min to get more data
* Forge was hitting validators directly previously, and validators were running out of network sockets to support the load. For now, introduce a flag `--enable-haproxy` to spin up Forge network with HAProxy in front of each validator. This seems to make the network more reliable. We should figure out how to just use validators though -- either increasing the file descriptor limit or change how the txn-emitter works
* Write a script `scripts/run_forge.sh` that sets up and configures Forge test runner for k8s. You can either tell it to invoke …
> [forge] improve healthcheck, option to toggle haproxy, and new script

- crates/aptos/src/move_tool/mod.rs
I noticed that the Aptos cli doesn't handle the address aliases in the run function args, which is inconsistent with the rest of the code.
TBD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1981)
> [aptos-cli] Fix profiles as inputs to function inputs

- storage/aptosdb/src/lib.rs
- storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs
- storage/storage-interface/src/lib.rs
- storage/storage-interface/src/mock.rs
- storage/storage-interface/src/state_view.rs
as title
now checkpoint is not always snapshot.
ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1991)
> [easy] s/get_latest_state_checkpoint/get_latest_state_snapshot

- .gitignore
- docker/rosetta/README.md
- docker/rosetta/docker-build-rosetta.sh
- docker/rosetta/rosetta.Dockerfile
This introduces a dockerfile file to run a fullnode with a rosetta API - https://www.rosetta-api.org/ .
The dockerfile tries to follow the conventions set here https://www.rosetta-api.org/docs/node_deployment.html#dockerfile-expectations.
Ran this locally:
```
GIT_SHA=main ./docker/rosetta/docker-build-rosetta.sh && \
mkdir -p data && \
cp config/src/config/test_data/public_full_node.yaml data/fullnode.yaml && \
curl -o data/genesis.blob https://devnet.aptoslabs.com/genesis.blob && \
curl -o data/waypoint.txt https://devnet.aptoslabs.com/waypoint.txt && \
docker run -p 8082:8082 -p 8083:8083 --rm -v $(pwd)/data:/opt/aptos/data aptos-core:rosetta-latest online --config /opt/aptos/data/fullnode.yaml
```
and accessed the rosetta API on `localhost:8082` (that part is still TBD, waiting for …
> rosetta: add rosetta compliant dockerfile and docs how to build+run it

- execution/executor/src/block_executor.rs
- execution/executor/src/chunk_executor.rs
- execution/executor/src/db_bootstrapper.rs
- execution/executor/src/fuzzing.rs
- execution/executor/src/tests/mod.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
- storage/aptosdb/src/backup/restore_handler.rs
- storage/aptosdb/src/backup/test.rs
- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/aptosdb/src/test_helper.rs
- storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs
- storage/backup/backup-cli/src/backup_types/transaction/restore.rs
- storage/backup/backup-cli/src/utils/mod.rs
- storage/backup/backup-cli/src/utils/test_utils.rs
- storage/storage-interface/src/executed_trees.rs
- storage/storage-interface/src/lib.rs
- types/src/proptest_types.rs
- types/src/transaction/mod.rs
This PR has two major changes:
1. We add back the optimizations computing the JMT node hashes before committing JMT.
2. Batch committing the blocks into one state_merkle_db writes instead of one write per block. This will recover the state-sync speed.
Also, fix a lot of tests issue when the aforementioned changes have been made.
cargo xtest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1983)
> [storage] add back computing jf_node_hashes and recover batch commit

- crates/aptos-crypto/benches/ed25519.rs
- crates/aptos-crypto/src/ed25519.rs
- crates/aptos-crypto/src/hash.rs
- crates/aptos-crypto/src/unit_tests/ed25519_test.rs
- crates/aptos-crypto/src/validatable.rs
1. Removed MIRAI annotations, which are no longer used.
2. Removed the single-threaded, optimized batch verification, because it is inconsistent with individual signature verification.
3. Added benchmark for small subgroup checks.
4. Added comments to indicate that we only have a dummy Validatable implementation for Ed25519PublicKey, since our signature verification code already checks the PKs for small subgroup attacks.
`ed25519-dalek`'s batch verification is cofactorless AND does NOT check public keys for small subgroup membership. As a result, batch verification **will not be consistent** with individual signature verification. In the worst case, batch verification might say “yes” when one of the individual signatures does NOT verify (i.e., **false positives**). Furthermore, this batch …
> [crypto] clean up Ed25519 implementation and documentation

- .github/workflows/run-forge.yaml
- testsuite/run_forge.sh
so we can track regressions across runs with automation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1999)
> [gha/forge] report avg_tps and p99_latency to prometheus

- api/goldens/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- aptos-move/framework/aptos-framework/sources/Account.move
- aptos-move/framework/aptos-framework/sources/AptosGovernance.move
- aptos-move/framework/aptos-framework/sources/Genesis.move
So proposal resolution can obtain the signer to create resources, deploy new modules or upgrade existing modules at 0x1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1990)
> [Aptos Framework] Give AptosGovernance the signer capability for AptosFramework account

- storage/aptosdb/src/backup/test.rs
- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/aptosdb/src/test_helper.rs
- storage/backup/backup-cli/src/utils/test_utils.rs
Just rename `in_memory_state` to `buffered_state` as it is a special in_memory_state maintained by state store and its checkpoint is actually the latest snapshot (persisted checkpoint).
ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1998)
> [state store] rename in_memory_state to buffered_state

- .github/workflows/build-images.yaml
Forge is now land-blocking
New labels in GH that skip certain e2e tests, meant for PRs that change code that is not relevant to the tests. We will ask PR authors to flip these labels until we have a smart enough target determinator in CI that determines which tests to run
* `CICD:skip-sdk-integration-test` for skipping flaky sdk integration tests
* `CICD:skip-forge-e2e-test` for skipping Forge for irrelevant PRs
Check if GHA workflow config is valid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2002)
> [gha] labels to skip sdk and forge e2e tests

- .github/workflows/run-forge.yaml
- testsuite/run_forge.sh
* submit metrics over PushGateway from `run_forge.sh` script, so we can test it locally as long as the env vars area set
* `dry-run` mode for testing locally with existing reports
Run test successfully, which generates a report, and then use `FORGE_RUNNER_MODE=dry-run` 
Metrics flowing: see `forge_job_avg_tps` and `forge_job_p99_latency` http://o11y.aptosdev.com/grafana/explore?orgId=1&left=%7B%22datasource%22:%22Local%20Prometheus%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22forge_job_avg_tps%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2001)
> [forge/gha] clean up report parsing and metrics push

- storage/aptosdb/src/pruner/state_store/mod.rs
After introduction of the state checkpoints, there's versions in the
ledger history that don't update the JMT, which broke the state pruner.
deployed on an ait2 node to observe disk write bandwidth drop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2007)
> [storage] state pruner: fix duplicate deletes

- aptos-move/framework/aptos-framework/sources/PropertyMap.move
- aptos-move/framework/aptos-framework/sources/TokenV1.move
[Semi-fungbile](https://www.coindesk.com/tech/2021/08/17/what-is-a-semi-fungible-crypto-token/) token is used for gaming and some other areas. Semi-fungible token is a token that is fungible at the beginning and become non-fungible overtime. For example, game equipments and gift cards with same value. They are fungible initially. However, if a gift card lost its value, it cannot be fungible with other giftcards that still have value. If we have a sword token, use it multiple times. The durability property of the sword decreases. The sword I used is not the same as other new swords.
We create a fungible token with a serial_number 0. The token has an `amount` field to indicate the quantity. All these token share the same `TokenID with the components like { token_data_id, serial_number}`. …
> [Token] add serial_number

- aptos-move/framework/aptos-token/Move.toml
- aptos-move/framework/aptos-token/sources/PropertyMap.move
- aptos-move/framework/aptos-token/sources/TokenCoinSwap.move
- aptos-move/framework/aptos-token/sources/TokenV1.move
- aptos-move/framework/cached-packages/Cargo.toml
- aptos-move/framework/cached-packages/build.rs
- aptos-move/framework/cached-packages/src/aptos_stdlib.rs
- aptos-move/framework/cached-packages/src/aptos_token_stdlib.rs
- aptos-move/framework/cached-packages/src/lib.rs
- aptos-move/framework/src/release.rs
- aptos-move/framework/tests/move_unit_test.rs
1. create a new package for token related modules
2. update the cached framework to have two compiled package and transaction_script
will modify genesis to deploy the token package to 0x2 in the next PR
use default tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2008)
> [Token] [1/2]Separate the token package from core-framework

- Cargo.toml
Makes it behave the same as debug mode.
put this in one of the cli tools and it panics at runtime (in release mode):
```
let mut a = u64::MAX - 10;
for _ in 0..100 {
a = a + 1;
println!("{}", a);
}
```
output:
```
17:42 $ cargo run --release -p executor-benchmark
Compiling executor-benchmark v0.1.0 (/home/msmouse/work/aptos_repos/aptos-core/execution/executor-benchmark)                                                                                      Finished release [optimized + debuginfo] target(s) in 25.69s
Running `target/release/executor-benchmark`
18446744073709551606
18446744073709551607
18446744073709551608
18446744073709551609
18446744073709551610
18446744073709551611
18446744073709551612
18446744073709551613
18446744073709551614
18446744073709551615
thread 'main' panicked at …
```
> enable overflow checks in release mode

- state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/utils.rs
- state-sync/state-sync-v2/state-sync-driver/src/utils.rs
- storage/aptosdb/src/lib.rs
- storage/storage-interface/src/lib.rs
This PR updates storage to add a new API call: `get_latest_epoch_state`. In addition, it updates state sync to use this new API instead of `get_startup_info()`, which fetches a bit more data and requires locking.
Existing unit tests have been updated and should cover this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2003)
> [Storage] Add a new API call: `get_latest_epoch_state`

- testsuite/forge-test-runner-template.yaml
- testsuite/run_forge.sh
- x.toml
Makes Forge test results more consistent
Move the Forge test-runner pod config to a separate template, as it was getting too complex to use `kubectl run --override`. This allows us to set more granular pod affinities, nodeTolerations, and resources:
* Schedule Forge test-runner pod on its own machine using antiaffinity 
* Schedule it on a machine in the `validators` nodegroup so it has access to more CPU
* Guarantee 15.5 vCPU so we can push it to its limit, though in practice we only see under 6vCPU being used 
Run forge a few times in testing environment.
```
"text": "all up : 3195 TPS, 1379 ms latency, 1750 ms p99 latency,no expired txns"
"text": "all up : 3229 TPS, 1368 ms latency, 1650 ms p99 latency,no expired txns"
"text": "all up : 3195 TPS, 1382 ms latency, 1800 ms p99 latency,no …
```
> [forge] separate test runner template for customizations

- .github/workflows/run-forge.yaml
- testsuite/run_forge.sh
* Generate a link to the validator logs in the Github comment. 
* Default to the o11y resources (Grafana, Opensearch) hosted by Aptos Labs in the `run_forge.sh` script, depending on the cluster name. They are used to generate the links in the Github comment and this just moving them from GHA environment variables to be hard-coded in the script.
* Also fix a bug in metrics parsing and report to PushGateway
Run Forge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2016)
> [forge] logs link and fix metrics parsing

- config/src/config/consensus_config.rs
- crates/transaction-emitter-lib/src/emitter/mod.rs
- testsuite/run_forge.sh
- testsuite/testcases/src/performance_test.rs
Tuning the transaction emitter configurations to send up to 10k TPS.
Run forge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2020)
> [forge] Tune transaction emitter config for forge to send up to 10k TPS

- crates/aptos-rosetta/src/types/objects.rs
- developer-docs-site/static/examples/python/first_transaction.py
event's no longer are guids inside of guids
just an id inside a guid, see
```{'counter': '1', 'guid': {'id': {'addr':
'0xfe30dec34daa1ba55d661905cdcc579018563316231b52f3c17505b93da99018',
'creation_num': '1'}}}```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2039)
> [rosetta] fix rosetta after event update

- developer-docs-site/docs/guides/getting-started.md
Adds a reference to the Intellij-Move plugin to the `Getting Started` section of the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2047)
> [Docs] mention intellij-move plugin in the "Getting Started"

- crates/aptos-genesis/src/builder.rs
The path was wrong, which was making it crash when safety
rules finally tried to write or load from storage.  This
now ensures that it can write to an existing path that is
in the correct place.
E2E tests should still pass
Local testnet mode works now and makes a secure storage file
```
$ cargo run -p aptos-node -- --test                                            
Entering test mode, this should never be used in production!
Log file: "/private/var/folders/1c/n_v_74m52fn50xf0y2c46byh0000gn/T/6ea35ced629f07f1f20987db0c503141/validator.log"
Config path: "/private/var/folders/1c/n_v_74m52fn50xf0y2c46byh0000gn/T/6ea35ced629f07f1f20987db0c503141"
Aptos root key path: "/private/var/folders/1c/n_v_74m52fn50xf0y2c46byh0000gn/T/6ea35ced629f07f1f20987db0c503141/mi …
```
> [aptos-genesis] Fix Validator builder secure storage path

- docker/rosetta/rosetta.Dockerfile
The git command doesn't work with origin/<hash>, because it doesn't know that it's a hash.  Since it always pulls from source, I just changed it to checkout the hash or branch, since it's the latest state anyways.
Ran the docker command locally and it built and started
```
./docker/rosetta/docker-build-rosetta.sh && \
mkdir -p data && \
cp config/src/config/test_data/public_full_node.yaml data/fullnode.yaml && \
curl -o data/genesis.blob https://devnet.aptoslabs.com/genesis.blob && \
curl -o data/waypoint.txt https://devnet.aptoslabs.com/waypoint.txt && \
docker run -p 8082:8082 --rm -v $(pwd)/data:/opt/aptos/data aptos-core:rosetta-latest online --test
+ export GIT_REPO=https://github.com/aptos-labs/aptos-core.git
+ GIT_REPO=https://github.com/aptos-labs/aptos-core.git
++ git rev-parse …
```
> [docker] Fix Rosetta git command

- crates/transaction-emitter-lib/src/emitter/mod.rs
- crates/transaction-emitter-lib/src/emitter/submission_worker.rs
- testsuite/forge-cli/src/main.rs
This PR adds some optimizations to the transaction emitter to reduce the volume of the REST call made when waiting for transactions to be committed as follows
1. Instead of making REST call for all the accounts, use a random single account to wait for sequence number and once that is done, we can wait for all the accounts. This way, we don't need to make the REST calls for all the accounts when the transactions are waiting.
2. Increase the sleep time between calls from 250 ms to 500 ms
3. Add the sleep before the first call
Ran forge and observed the CPU usage for the transaction emitter went down from 14 core to less than 4 core - http://o11y.aptosdev.com/grafana/explore?orgId=1&left=%7B%22datasource%22:%22Remote%20Prometheus%20Devinfra%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%2 …
> [Txn-emitter] Optimize transaction emitter to reduce REST API call 

- .github/workflows/lint-test.yaml
this adds Datadog CI visibility - sharing link to reports internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2063)
> cicd: add Datadog CI visibility

- execution/executor/src/block_executor.rs
- execution/executor/src/chunk_executor.rs
- execution/executor/src/components/chunk_output.rs
- execution/executor/src/db_bootstrapper.rs
- execution/executor/src/tests/mod.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/storage-interface/src/cached_state_view.rs
- storage/storage-interface/src/executed_trees.rs
- storage/storage-interface/src/no_proof_fetcher.rs
- storage/storage-interface/src/sync_proof_fetcher.rs
- vm-validator/src/vm_validator.rs
The use cases of verified_state_view are always ephemeral which is not the case for `CacheStateView<NoProofFetcher>`. So we should not pass `Arc<DbReader>` in. It may help the initialization of `StateStore` too.
ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2064)
> [storage] limit the lifetime of CacheStateView<SyncProofFetcher>

- terraform/aptos-node-testnet/main.tf
- terraform/aptos-node-testnet/variables.tf
- terraform/aptos-node/aws/kubernetes.tf
- terraform/aptos-node/aws/variables.tf
- terraform/helm/vector-daemonset/Chart.yaml
- terraform/helm/vector-daemonset/README.md
- terraform/helm/vector-daemonset/example-values/humio-sink.yaml
- terraform/helm/vector-daemonset/example-values/observe-sink.yaml
- terraform/helm/vector-daemonset/files/vector-config.yaml
- terraform/helm/vector-daemonset/templates/vector-daemonset.yaml
- terraform/helm/vector-daemonset/values.yaml
This introduces a new helm chart to collect logs as k8s daemonset via vector + corresponding example sink configurations for Humio and Observe.
The previous vector deployment was running as "aggregator" deployment and required containers to use remote writes to send logs to it which in turn it forwarded to the sink (AWS OpenSearch).
With this new setup (daemonset) we collect all cluster logs on the node level from logfiles that the container runtime creates and rotates. This is generally the best practice for k8s and has a number of advantages:
- applications/containers don't need to explicitly support some kind of remote write, instead they simply need to write to stdout. So it's easy to collect logs from _everything_ that runs in the cluster.
- Much higher chance of collecting crash …
> observability: introduce vector daemonset for log collection

- .actrc
- .github/workflows/sdk-integration-test.yaml
- crates/crash-handler/src/lib.rs
- secure/storage/src/on_disk.rs
- x.toml
This PR originally was intented to just fix the sdk integration tests.
To figure out what's going on I had to make the crash reason more observable by:
- print docker-compose logs when sdk integration test failed
- make sure aptos-node actually prints the crash reason
- enhance the error message in `.expect` to give more details on why we are crashing.
So this PR is basically fixing these 3 things.
The SDK integration tests themselves already have been fixed by #2059 after we printed the crash reason in this PR.
TODO: follow up on #2038 for a cleaner fix to lacking crash logging.
Let the node crash a few times before #2059 was merged and observed the crash reason being printed in CI.
--- …
> observability: temp fix to log panic when aptos-node crashes

- consensus/src/block_storage/sync_manager.rs
- consensus/src/experimental/buffer_manager.rs
- consensus/src/network.rs
- consensus/src/network_tests.rs
- consensus/src/round_manager.rs
- previously we only had failpoints on processing of the messages (i.e. on receiving the messages),
making it hard to test things where one node is failing to send something. Adding failpints
on all send messages (and for that separating different types of broadcasts into their own functions
- made sure all failpoints code is behind configuraiton. we had inject_reconfiguration_error always enabled
whenever code was compiled with failpoints feature (which can lead to flaky tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2049)
> [consensus] Add failpoints on sending and have all failpoints code be behind configuration

- Cargo.lock
- aptos-node/Cargo.toml
- aptos-node/src/lib.rs
- crates/aptos/Cargo.toml
- crates/aptos/src/common/types.rs
- crates/aptos/src/common/utils.rs
- crates/aptos/src/main.rs
- crates/aptos/src/node/mod.rs
Ever wanted to run a local testnet node that matches your CLI exactly, now you can!
This allows for running a local testnet node and minting coins with a faucet on that node.
(This is also a possible workaround for https://github.com/aptos-labs/aptos-core/issues/1700)
```
$ aptos node run-local-testnet --help
aptos-node-run-local-testnet 0.2.0
Run local testnet
This local testnet will run it's own Genesis and run as a single node network locally.  Optionally,
a faucet can be added for minting coins.
USAGE:
aptos node run-local-testnet [OPTIONS]
OPTIONS:
--assume-no
Assume no for all yes/no prompts
--assume-yes
Assume yes for all yes/no prompts
--config-path <CONFIG_PATH>
An overridable config template for the test node
--faucet-port <FAUCET_PORT>
Port to run the faucet on
[default: 8081] …
```
> [aptos-cli] Add local testnet command to run a local testnet node and mint coins

- Cargo.lock
- aptos-move/framework/Cargo.toml
- aptos-move/framework/aptos-framework/sources/signature.move
- aptos-move/framework/src/natives/signature.rs
This [commit](https://github.com/aptos-labs/aptos-core/commit/e623f228d68f09141ff0b47c314777f0efce948a#diff-9c464e51b249d8512f7638ff80fd8b5bac5b725d1e6d45c1bbd1ef0bed89bd6c) removed the small subgroup check on  Ed25519 public keys when deserializing them.
As a result, our `ed25519_validate_pubkey` Move function does not actually check for small subgroups, which can lead to big problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2077)
> [crypto] fixed the (lack of) Ed25519 public key validation in Move

- terraform/helm/vector-daemonset/files/vector-config.yaml
- terraform/helm/vector-daemonset/templates/vector-daemonset.yaml
- terraform/helm/vector-daemonset/values.schema.json
- terraform/helm/vector-daemonset/values.yaml
- testsuite/run_forge.sh
also: improving run_forge.sh DX when running it locally
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2074)
> observability: add k8s.cluster field to logs to identify the cluster it came from

- developer-docs-site/docs/concepts/basics-events.md
Pretty self explanatory, the address should be 32 bytes, not 16.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2091)
> Update Events dev docs to reflect 32 byte addresses

- terraform/helm/vector-daemonset/example-values/honeycomb-sink.yaml
- testsuite/run_forge.sh
Adds a honeycomb sink to the vector daemonset.
Also some improvements to run_forge.sh which previously implicitly expected the kubectl context to be on the `default` namespace. Now it also works when the kubectl context is set to a different namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2097)
> observability: add honeycomb sink to vector

- config/src/config/storage_config.rs
- storage/aptosdb/src/db_options.rs
- storage/backup/backup-cli/src/utils/mod.rs
When db is huge, we sometimes see the compaction cannot catch up, and stalls/stops the write. The log shows the CPU time used for compaction is large, so increasing the # of threads should help.
e.g. Before this change we can see
```2022/07/15-03:54:04.092403 7f95747fb700 [WARN] [db/column_family.cc:917] [jellyfish_merkle_node] Stopping writes because of estimated pending compaction bytes 611474697013``` and 
```2022/07/15-04:34:35.750367 7f9571bff700 [WARN] [db/column_family.cc:895] [jellyfish_merkle_node] Stopping writes because we have 2 immutable memtables (waiting for flush), max_write_buffer_number is set to 2```,
which completely stopped writes for several minutes.
After this change they are gone.
Manually tested on large DB.
--- …
> [Storage] Increase the # of background threads for Rocksdb.

- .github/workflows/sdk-integration-test.yaml
This hopefully makes the sdk integration tests more stable.
We can also probably deprecate/remove the validator-testnet docker-compose template after this.  #2100 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2099)
> cicd: use new aptos cli feature to run local testnet with faucet instead of docker compose

- aptos-move/framework/aptos-framework/sources/block.move
- aptos-move/framework/aptos-framework/sources/configs/stake.move
Currently setters such as stake::update_required_stake requires passing the GovernanceProposal object, which effectively consumes it in one call. This means that a governance proposal cannot invoke multiple setters in a single transaction script since the GovernanceProposal that voting::resolve returns can only used once.
This PR updates these functions to accept &GovernanceProposal instead so it can be reused in the same resolution script for multiple changes.
Unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2101)
> [Aptos Framework] Update setters in stake and block modules to allow multiple actions in one governance proposal

- Cargo.lock
- aptos-move/framework/aptos-framework/sources/table.move
- aptos-move/move-deps/Cargo.toml
Per the title, this takes in the latest move so that we can record the K, V types in the new_tables and add that to an indexer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2102)
> [aptos-move] update to latest version to support K,V table indexing

- consensus/src/logging.rs
- consensus/src/network.rs
- consensus/src/pending_votes.rs
- consensus/src/round_manager.rs
- consensus/src/round_manager_test.rs
- types/src/validator_verifier.rs
This change removes the help_remote behavior and adds echo timeout instead.
The problem of help_remote is during vote or timeout, the first 2f+1 messages will advance the round by 1 and we'll bounce off a sync info message back for the rest f messages unnecessarily.G
Echo timeout is part of the bracha broadcast protocol that we immediately timeout if receive f+1 timeout messages (at least 1 honest).
This can help the scenario that node A is behind and everyone else is timing out, when node A receive the timeout, it'll first enter the round and wait for the whole timeout period to actually timeout the round. With echo timeout, node A would immediately timeout after receive f+1 timeout message.
--- …
> [consensus] remove help_remote option for sync up

- state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs
- state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver.rs
This PR explicitly hardens state sync from ever handing over to consensus until all pending data has been flushed out of the execute-commit pipeline. Right now, there's only a single case where this is possible and it requires: (i) malicious peers to construct a precise set of malicious data chunks that pass the streaming service's validation; and (ii) perfect timing between checking the current synced version, handing over to consensus, and processing another chunk. Both of these are conditions are *incredibly* unlikely, but this let's play it safe and avoid the race condition entirely.
Existing unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1937)
> [State Sync] Harden against all consensus/state sync race conditions (from the state sync side).

- state-sync/aptos-data-client/src/aptosnet/mod.rs
- state-sync/aptos-data-client/src/lib.rs
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/utils.rs
This PR makes several small tweaks to the state sync logic and logging:
1. We improve the logs (to prevent them from getting too large when we have a large number of peers and validators in each ledger info).
2. We remove the old and unnecessary yield code (this was resolved in a different PR, but never removed from the code, e.g., see https://github.com/aptos-labs/aptos-core/issues/623)
3. We fix a small bug in handling epoch state changes when the continuous syncer is running. The bug didn't have any practical impact other than forcing a speculative stream reset. But, it's a bug nonetheless :)
Manual verification and existing unit tests.
--- …
> [State Sync] Small tweaks to logic and logging

- terraform/aptos-node-testnet/addons.tf
- terraform/aptos-node-testnet/forge.tf
- terraform/aptos-node/aws/kubernetes.tf
- terraform/aptos-node/aws/variables.tf
- terraform/aptos-node/azure/kubernetes.tf
- terraform/aptos-node/azure/variables.tf
- terraform/aptos-node/gcp/kubernetes.tf
- terraform/aptos-node/gcp/variables.tf
- terraform/fullnode/aws/main.tf
- terraform/fullnode/digital_ocean/kubernetes.tf
- terraform/fullnode/digital_ocean/variables.tf
- terraform/fullnode/gcp/kubernetes.tf
- terraform/fullnode/gcp/variables.tf
- terraform/fullnode/vultr/kubernetes.tf
- terraform/fullnode/vultr/variables.tf
- terraform/modules/indexer/helm.tf
- testsuite/forge-test-runner-template.yaml
* Remove the resource requirement for Forge test runner to use 15.5 vCPU. This number will change anyways depending on the machine type. Instead, rely on the pod antiaffinity and have it use as much CPU as it needs on the node it's scheduled on
* Trigger helm_release using the chart's sha1, instead of relying on timestamp which will change every time. This makes the TF plan smarter! Applied the same change to all our TF configs that previously used timestamp for the `helm_release` resource 
TF apply and create a new forge cluster 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2083)
> [tf/forge] use sha1 to trigger helm release

- consensus/src/consensus_provider.rs
- consensus/src/experimental/buffer_manager.rs
- consensus/src/experimental/tests/buffer_manager_tests.rs
- consensus/src/state_computer.rs
1. execute reconfiguration suffix to avoid rare race condition
2. add delay for retry requests to avoid busy looping
3. spawn_blocking for execution and commit to free cooperative threads
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2082)
> [consensus] buffer manager cleanups and spawn_blocking

- Cargo.lock
- crates/aptos/Cargo.toml
- crates/aptos/src/config/mod.rs
- crates/aptos/src/lib.rs
- crates/aptos/src/move_tool/mod.rs
This should help us debug stuff and complete some features with the CLI.  I wanted to fix the fact that the move download is slow and that it doesn't always match, but I wasn't able to get that working quite yet.  Waiting on updates to package referencing.
```
$ aptos info 
{
"Result": {
"build_branch": "main",
"build_cargo_version": "cargo 1.61.0 (a028ae42f 2022-04-29)",
"build_commit_hash": "1e7ab8569be65cefd78b2f44724831010ee8dbdc",
"build_os": "macos-aarch64",
"build_pkg_version": "0.2.0",
"build_rust_channel": "1.61.0-aarch64-apple-darwin",
"build_rust_version": "rustc 1.61.0 (fe5b13d68 2022-05-18)"
}
}
$ aptos config show-global-config
{
"Result": {
"config_type": "Global"
}
}
$ aptos move init --name test --package-dir tester
"tester/Move.toml" already exists, are you sure you want …
```
> [aptos-cli] Usability fixes to CLI

- aptos-move/move-examples/hello_prover/Move.toml
- aptos-move/move-examples/hello_prover/sources/prove.move
- aptos-move/move-examples/tests/move_prover_tests.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
- Enabled the Prover command in Aptos CLI (`$ aptos move prove`)
- Added a test package (`hello_prover`) and a test script in `move-examples`
cargo test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2086)
> [Aptos CLI][Move Prover] Add the subcommand to run Move Prover in Aptos CLI

- Cargo.lock
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-node/src/lib.rs
- config/src/config/execution_config.rs
- storage/storage-interface/Cargo.toml
- storage/storage-interface/src/async_proof_fetcher.rs
- storage/storage-interface/src/lib.rs
- storage/storage-interface/src/mock.rs
Implement AsyncProofFetcher. Will use this in execution to only get state value in foreground, and put proof reading to background, to reduce latency.
New UT, and manually tested on large DBs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2093)
> [Execution] Add AsyncProofFetcher.

- developer-docs-site/docs/tutorials/first-coin.md
- developer-docs-site/static/examples/python/first_coin.py
- developer-docs-site/static/examples/rust/first_coin/src/lib.rs
- developer-docs-site/static/examples/typescript/first_coin.ts
Broken after recent refactoring.
Manual tests again local network
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2119)
> [Move examples] Fix example code

- crates/aptos-faucet/src/lib.rs
Print out the faucet address and port so we can tell in local testnet mode of the CLI
```
$ target/debug/aptos node run-local-testnet --with-faucet --assume-yes --force-restart
Log file: "/Users/greg/.aptos/testnet/validator.log"
Test dir: "/Users/greg/.aptos/testnet"
Aptos root key path: "/Users/greg/.aptos/testnet/mint.key"
Waypoint: 0:d302c6b10e0fa68bfec9cdb383f24ef1189d8850d50b832365eea21ae52d8101
ChainId: TESTING
REST API endpoint: 0.0.0.0:8080
FullNode network: /ip4/0.0.0.0/tcp/6181
Aptos is running, press ctrl-c to exit
Faucet started on 0.0.0.0:8081
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2123)
> [aptos-faucet] Print out the endpoint running the faucet on stdout

- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/framework/aptos-framework/sources/governance_proposal.move
Currently a proposal has code location, title and description. This is not very flexible. This PR changes the fields to be more generic, allowing the metadata to be constructed in dynamically off-chain.
Unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2121)
> [Aptos Framework] Update proposal fields for AptosGovernance to allow more generic metadata

- crates/aptos-genesis/src/builder.rs
- testsuite/forge/src/backend/local/mod.rs
- testsuite/forge/src/backend/local/node.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/smoke-test/src/network.rs
- testsuite/smoke-test/src/smoke_test_environment.rs
- testsuite/smoke-test/src/state_sync.rs
- testsuite/smoke-test/src/state_sync_v2.rs
- testsuite/smoke-test/src/test_utils.rs
- Allowing setting (per-node) validator configuration,
so that we don't need to restart the node to do so
- disallowing starting already running nodes (which restarts them silently)
- all smoke tests. added test for not starting a node twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2098)
> [smoke-tests] Minimizing node restarts in local swarm smoke tests

- consensus/src/block_storage/sync_manager.rs
- consensus/src/experimental/buffer_manager.rs
- consensus/src/network.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2130)
> [consensus] rename some network methods and failpoints to make them more consistent

- aptos-move/framework/aptos-token/Move.toml
- aptos-move/framework/aptos-token/sources/token_v1.move
- aptos-move/framework/move-stdlib/sources/acl.move
1. store the token burn, transfer and mutate_properties authority at owner account (TokenStore).
2. enable delegation and revoke of burn authority
3. 3rd party can acquire capability for burn 
unit test 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2055)
> [Token] update token burn authority and capability

- testsuite/forge-cli/src/main.rs
- testsuite/forge-test-runner-template.yaml
- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/run_forge.sh
Ability to reuse existing forge-management configmaps. This lets you re-run a Forge test in the same namespace as one that did not clean up properly (e.g. crashed or was `--keep`). We see this crash Forge every now and then due to high test volume and high test pre-emption due to GHA triggering logic.
Also introduce `forge test k8s --reuse` option, which reuses the running network (e.g. it was `--keep` before) instead of wiping the network (re-run genesis and re-install validators)
Run on forge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2132)
> [forge] reuse existing management configmap

- ecosystem/indexer-server/doc/openapi.yaml
- ecosystem/indexer-server/typescript/prisma/schema.prisma
- ecosystem/indexer-server/typescript/src/api/v1/openapi.yaml
- ecosystem/indexer-server/typescript/src/controllers/DefaultController.ts
- ecosystem/indexer-server/typescript/src/openapi-schema.ts
- ecosystem/indexer-server/typescript/src/services/DefaultService.ts
- ecosystem/indexer-server/typescript/src/services/service_v1.test.ts
* Fix bugs for /ownerships/byToken
* Changed ownerships/{ownership_id} to ownerships/byId and pass ownership_id as query param (otherwise subsequent paths never get reached).
* Added ownerships/byOwner (note, this is only returning items where amount > 0). 
Fixed service_v1.test.ts and ran `yarn run test`. Tests pass. Then I added a test case for ownerships/byOwner and ensured test pass. 
Also tested in open API. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2112)
> [Indexer Server] Add ownership query by owner and fix errors / tests

- Cargo.lock
- testsuite/forge/Cargo.toml
- testsuite/forge/src/backend/k8s/cluster_helper.rs
Print a better error message when you're not authorized. Additionally remove some overly complex logic for performing retries in favor of the more standard again crate.
I also added unittests and split up the function a bit to make it somewhat testable.
Test Plan:
Running unauthorized fails
```
$ cargo run -p forge-cli -- test k8s-swarm --namespace forge-banana --port-forward
2022-07-21T22:27:35.976025Z [main] INFO testsuite/forge/src/backend/k8s/mod.rs:53 Using forge namespace: forge-banana
running 1 tests
Starting Swarm with supported versions: ["devnet", "devnet"]
Failed to run tests:
Unauthorized, did you authorize with kubernetes? Try running `kubectl get current-context`
Error: Unauthorized, did you authorize with kubernetes? Try running `kubectl get current-context`
```
Then …
> [forge] Better error message when unauthorized

- config/src/config/storage_config.rs
- execution/executor-benchmark/src/main.rs
- storage/aptosdb/src/aptosdb_test.rs
- storage/aptosdb/src/metrics.rs
- storage/aptosdb/src/pruner/db_pruner.rs
- storage/aptosdb/src/pruner/event_store/test.rs
- storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
- storage/aptosdb/src/pruner/mod.rs
- storage/aptosdb/src/pruner/state_store/mod.rs
- storage/aptosdb/src/pruner/state_store/test.rs
- storage/aptosdb/src/pruner/transaction_store/test.rs
- storage/aptosdb/src/pruner/utils.rs
- storage/aptosdb/src/pruner/worker.rs
- storage/aptosdb/src/state_store/state_store_test.rs
Add a capability to only prune a partial version for state pruner
Context: https://linear.app/aptoslabs/issue/BLK-19/[db]-state-pruner-smaller-commits
- Previously, max version in prune_state_store means the max number of versions to prune. In each version, there can be multiple stale nodes. Now, the same parameter means the max number of stale nodes to prune.
- Previously, we don't immediately delete the stale node index after pruning the node from DB but only do it periodically. After this change, we will delete the stale node indexes immediately after pruning the stale node.
- Previously, if deleting the stale node index, we will just print a warning. Now we treat failures of deleting the stale node index the same as that of deleting the node.
- Split config `pruning_batch_size` into …
> [storage][pruner] Add capability of incremental pruning

- aptos-move/aptos-vm/src/move_vm_ext/transaction_context.rs
- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/framework/aptos-framework/sources/voting.move
Empty execution hash technically is not exploitable as transaction_context::script_hash() only returns empty if voting::resolve() is called from a script function and not script. This is not a serious issue as the transaction can only call voting::resolve() but cannot do anything else (script function is a single call per transaction). However, we might as well add a validation against empty execution hash for peace of mind.
Unit Tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2154)
> [Aptos Framework] Validate against empty execution hash in voting::resolve()

- .cargo/config.toml
- Cargo.lock
- aptos-move/aptos-sdk-builder/Cargo.toml
- aptos-move/aptos-sdk-builder/examples/golang/stdlib_demo.go
- aptos-move/aptos-sdk-builder/src/common.rs
- aptos-move/aptos-sdk-builder/src/golang.rs
- aptos-move/aptos-sdk-builder/src/lib.rs
- aptos-move/aptos-sdk-builder/src/main.rs
- aptos-move/aptos-sdk-builder/src/rust.rs
This brings back reasonable support for the generator for golang!
Note: There seems to be some amount of code duplication to support Scripts and ScriptFunctions. This can probably be merged to some degree.
To run this:
In the `aptos-move/framework` folder:
`cargo run`
In the `aptos-move/aptos-sdk-builder` folder:
`cargo run -- --language go --module-name aptosstdlib --package-name testing --with-aptos-types "../../testsuite/generate-format/tests/staged/aptos.yaml" --target-source-dir examples/golang "../framework/aptos-framework/releases/artifacts/current"`
In the `aptos-move/aptos-sdk-builder/examples/golang` folder:
`go mod init testing`
`go mod edit -replace testing=`pwd``
`go get github.com/aptos-labs/serde-reflection/serde-generate/runtime/golang/bcs`
`go get …
> [aptos-sdk-builder] Brought back generator and go support

- api/types/src/error.rs
In the Error struct type comment, renamed Diem to Aptos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2177)
> [api] discard diem for aptos

- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/aptos-framework/sources/bucket_table.move
- aptos-move/framework/aptos-framework/sources/timestamp.move
- aptos-move/framework/aptos-framework/sources/transaction_context.move
- aptos-move/framework/aptos-stdlib/Move.toml
- aptos-move/framework/aptos-stdlib/sources/signature.move
- aptos-move/framework/aptos-stdlib/sources/table.spec.move
- aptos-move/framework/aptos-stdlib/sources/type_info.move
- aptos-move/framework/move-stdlib/sources/error.move
- aptos-move/framework/move-stdlib/sources/hash.move
This commit makes the Aptos Framework compatible with Prover.
- fixed the existing spec that has been broken
- mocked up the native functions and the xor operation so that Prover does not crash.
`aptos move prove` works without any error/crash for all of the following Move packages:
- `aptos-framework`
- `aptos-token`
- `aptos-stdlib`
- `move-stdlib`
TODO:
- add a new spec to the Stake module
- add the boogie implementation for the native functions which are temporarily mocked up in this PR.
Run `aptos move prove` in any of the Aptos Move packages above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2162)
> [Aptos Framework][Prover] Made the Aptos Framework compatible with Prover

- consensus/src/block_storage/block_store.rs
- consensus/src/liveness/round_state.rs
- consensus/src/network.rs
- consensus/src/network_interface.rs
- consensus/src/round_manager.rs
- consensus/src/round_manager_fuzzing.rs
- consensus/src/util/mock_time_service.rs
- consensus/src/util/time_service.rs
Leader enters the round earlier than others, the difference is the whole broadcast period, increase the timeout period to compensate it.### Description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2178)
> [consensus] increase timeout for leader and make sleep async

- .pre-commit-config.yaml
- Cargo.lock
- consensus/src/experimental/linkedlist.rs
- crates/aptos-crypto/src/unit_tests/compilation/cross_test.rs
- crates/aptos-logger/Cargo.toml
- crates/aptos-logger/src/aptos_logger.rs
- crates/aptos-logger/src/filter.rs
- crates/aptos-logger/src/macros.rs
- crates/aptos-logger/src/metadata.rs
- crates/aptos-logger/src/tracing_adapter.rs
- docker/rust-all.Dockerfile
This introduces support for printing json-formatted logs to stdout by setting the environment variable `RUST_LOG_FORMAT=json`. This is part of the observability improvements.
furthermore this does some general enhancements to the aptos-logger json logging:
- removes redundant `file` and `line` attribute from logger metadata
- renames `location` to `file`
- rename `target` to `package`
- wrap `package` and `file` into a `source` object. E.g. `source: {package: "foo", file: "src/stuff.rs:44"`
- skips `module_path` from json output (package and file are already useful enough imo)
This should produce less noisy / more human-readable json logs that look like this:
```json
{"level":"INFO","source":{"package":"aptos_logger","file":"crates/aptos-logger/src/aptos_logger.rs:735"},"thread_name":"apto …
```
> observability: implement json-logging to stdout for aptos-logger

- Cargo.lock
- vm-validator/Cargo.toml
- vm-validator/src/vm_validator.rs
https://github.com/aptos-labs/aptos-core/blob/67691be4d2d4232dd5227b058d0843116b1c1fa0/vm-validator/src/vm_validator.rs#L100
This line never release the oldest ancestor of the in-memory smt chain. So the smt size keep growing... forever.
ut.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2193)
> [vm-validator] hot fix for vm-validator memory leak

- docker/compose/indexer-postgres/docker-compose.yaml
The docker-compose.yaml specifies the indexer dependency on postgres. But the postgres service itself is called db, which caused an error on startup
Description
Change 'db' to 'postgres' in docker-compose.yaml
Test Plan
docker-compose up -d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2163)
> fix service name for postgres

- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/framework/aptos-framework/sources/block.move
- aptos-move/framework/aptos-framework/sources/configs/stake.move
It makes more sense to require the signer of 0x1 to make upgrades to framework modules that are governed by the on-chain AptosGovernance as only a passed proposal (via voting) can be resolved to obtain the signer.
Unit tests, integration tests (WIP), and manual tests in local testnet and AITs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2157)
> [Aptos Framework] Replace GovernanceProposal with AptosFramework signer in stake and block's update functions

- ecosystem/platform/server/app/models/user.rb
- ecosystem/platform/server/spec/factories/it1_profiles.rb
- ecosystem/platform/server/spec/factories/it2_profiles.rb
- ecosystem/platform/server/spec/factories/it2_surveys.rb
- ecosystem/platform/server/test/controllers/settings_controller_test.rb
Fixes this error:
```
PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_4650fd3769" on table "it1_profiles"
DETAIL:  Key (id)=(17392) is still referenced from table "it1_profiles".
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1840)
> [community] Fix deleting accounts with it1_profile.

- crates/aptos-telemetry/src/build_information.rs
- docker/docker-bake-rust-all.hcl
- docker/docker-bake-rust-all.sh
- docker/rust-all.Dockerfile
Fixes #2109 
**Issue:** The docker image build flow ignores the .git/ repository from docker build context which `shadow_rs` uses to extract git revision info including commit hash consumed and emitted by the telemetry-service's metrics.
**Fix:** Set Git metadata as environment variable in `Dockerfile` and consume it within the telemetry-service.
- Adds three arguments ARGs  and environment variables ENVs to Dockerfile: `GIT_COMMIT_HASH`, `GIT_BRANCH`, and `GIT_TAG`.
- Modifies the `docker-bake-rust-all.sh` to define these arguments and pass then to the buildx bake definition `docker-bake-rust-all.hcl`.
- Add a `println!` to print [`build_information`](https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos-telemetry/src/build_information.rs#L113)
- Build a container by …
> [telemetry] pass git revision info via env variables

- .github/workflows/build-images.yaml
- .github/workflows/run-forge.yaml
- terraform/helm/genesis/templates/genesis.yaml
- testsuite/run_forge.sh
A few improvements to the Forge UX:
* Move the GHA comment creation to `run_forge.sh` script, since it serves for a pretty good command output as well. The comment contents can be redirected using env var `FORGE_COMMENT`. 
* Generate some useful pre-Forge output such as auto-refreshing dashboards and logs. Use it to generate a comment that gets posted right before tests run in `FORGE_PRE_COMMENT`
* Use https://github.com/marocchino/sticky-pull-request-comment to post and update a single Forge output comment on PRs, rather than spamming the PR each time. Use the action in `recreate` mode, which ensures that the Forge comment will always append to the bottom, and since it's deleted and re-created, will trigger a GH notification. This makes it easier to see what is exactly running and when …
> [gha] sticky forge comment

- .dockerignore
- crates/transaction-emitter-lib/src/emitter/account_minter.rs
- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/chaos.rs
- testsuite/forge/src/backend/k8s/chaos/network_bandwidth.yaml
- testsuite/forge/src/backend/k8s/chaos/network_delay.yaml
- testsuite/forge/src/backend/k8s/chaos/network_partition.yaml
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/chaos.rs
- testsuite/forge/src/interface/mod.rs
- testsuite/forge/src/interface/swarm.rs
- testsuite/run_forge.sh
- testsuite/testcases/src/lib.rs
- testsuite/testcases/src/network_chaos_test.rs
Introduce network chaos at the swarm level. New test suite `land_blocking_real` attempts to run tests against three types of network chaos, in a new experiment called `NetworkChaosTest`. In three independent steps, the experiment injects latency, limits bandwidth, and partitions the network, all while using txn-emitter to validate the network is still healthy.
Abstractly, we're introducing `SwarmChaos` with options `Delay`, `Bandwidth`, and `Partition`. Then we can do `Swarm::inject_chaos(SwarmChaos)` and `Swarm::remove_chaos(SwarmChaos)`. It's unimplemented for `LocalSwarm`, but for `K8sSwarm`, it creates/manages/deletes the NetworkChaos CRDs from Chaos Mesh: https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/
Also included is some boilerplate for `NodeChaos`, which is …
> [forge] swarm network chaos

- Cargo.lock
- consensus/src/consensusdb/mod.rs
- storage/aptosdb/Cargo.toml
- storage/aptosdb/src/backup/restore_utils.rs
- storage/aptosdb/src/pruner/state_store/mod.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/schemadb/Cargo.toml
- storage/schemadb/src/lib.rs
- storage/schemadb/tests/db.rs
It is cpu heavy so we should do it in parallel.
This reduces the JMT update time to ~30% on a 250M accounts DB.
Manually tested on large DBs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2115)
> [Storage] Serialize JMT updates in multiple threads.

- ecosystem/typescript/sdk/examples/typescript/bcs_transaction.ts
- ecosystem/typescript/sdk/examples/typescript/multisig_transaction.ts
- ecosystem/typescript/sdk/src/aptos_client.test.ts
- ecosystem/typescript/sdk/src/aptos_client.ts
- ecosystem/typescript/sdk/src/transaction_builder/aptos_types/abi.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/aptos_types/abi.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder_utils.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder_utils.ts
This PR aims to provide similar features as the [Ethereum web3 Contract interface](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html). With Ethereum, developers are able to generate ABI in JSON format and provide the JSON object to the web3 JS. Web3 JS then converts the Javascript function calls to RPC calls.
In Aptos TS SDK, developers must manually construct the transaction payloads for BCS endpoints, which are verbose. With this PR, developers can provide ABI information to the SDK, and the SDK can use the type information in ABI to translate the plain javascript parameters to BCS payloads. This significantly reduces the burden on SDK developers.
The ABIs are generated when compiling Move modules. The ABI bytes can then be provided to the SDK by developers.
Jest test
--- …
> feat: add abi support to TS SDK

- Cargo.lock
- api/Cargo.toml
- api/src/context.rs
- api/src/failpoint.rs
- api/src/poem_backend/accept_type.rs
- api/src/poem_backend/accounts.rs
- api/src/poem_backend/events.rs
- api/src/poem_backend/index.rs
- api/src/poem_backend/mod.rs
- api/src/poem_backend/page.rs
- api/src/poem_backend/response.rs
- api/src/poem_backend/transactions.rs
- api/types/src/transaction.rs
This PR reworks the response and error handling.
The good:
- Previously, every endpoint returned the same response struct. This meant the spec would say every endpoint could return (for example), 200, 202 on the success path and 400, 404, 413, 500 on the failure path. This is misleading because not all endpoints return the same set of status codes (as evidenced by the existing spec). With this change, we have the ability to generate types at a more granular level for each endpoint.
- Returning errors from endpoint handler functions is much less verbose now.
- "Internal functions", as in those below the endpoint handlers (but still in the API code) can now return errors specific to the endpoints, with the status code data baked in. This is all guaranteed at compile time, we don't do any …
> [API] Rework response and error handling

- .github/actions/upload-test-results/action.yaml
- .github/workflows/coverage.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/run-forge.yaml
- codecov.yml
This introduces code coverage measurement for our rust code via codecov.io.
Coverage runs either when:
- triggered through `CICD:run-coverage` label on PRs.
- every morning 9am via cronjob
- manually triggered via Actions tab "Run Workflow".
It's measuring coverage from all the unit and smoke tests which run through nextest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2120)
> devtools: measure and report test coverage to codecov.io

- ecosystem/platform/server/app/components/header_component.html.erb
- ecosystem/platform/server/app/javascript/controllers/header_controller.ts
On hover, if another nav group has focus (and thus its dropdown is visible), remove focus so that only one dropdown is visible at a time.
Manual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2220)
> [community] Fix bad hover/focus interaction.

- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/pruner/utils.rs
- storage/aptosdb/src/pruner/worker.rs
As a first step to separate ledger and state pruners, replace the vector of pruners with objects ledger pruner and state pruner. The next step is to wake them up separately and probably running in different threads.
Existing UTs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2213)
> [storage][pruner] separate ledger and state pruners

- .github/workflows/build-images.yaml
[forge] Run e2e tests when #e2e in pull request message
This change adds the ability to trigger forge on your commit by simply adding #e2e anywhere in your PR message body!
Test Plan:
I changed pull_request_target -> pull_request in build-images.yaml github action, then it will run from this workflow instead of from main workflow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2208)
> [forge] Run e2e tests when #e2e in pull request message

- terraform/helm/monitoring/files/prometheus.yml
Scrape all prometheus pods with annotation `prometheus.io/scrape: "true"`, such as the cluster-autoscaler.
Apply in a cluster and query metrics from Prometheus. Run Forge and watch the autoscaler spin up nodes and query unschedulable pods to understand the autoscaler's performance
The scrape target gets cluster-autoscaler since it is annotated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2224)
> [helm][monitoring] prom scrape pods with annotation

- terraform/aptos-node/aws/cluster.tf
- terraform/aptos-node/aws/variables.tf
- terraform/modules/eks/cluster.tf
- terraform/modules/eks/variables.tf
Upgrade minimum version of k8s to 1.22 across all supported clouds. Only EKS needed to be updated. Also include an lifecycle `ignore_changes` block so we don't force the upgrade, which might take a while. This makes it such that only new clusters are spun up directly at the new version. Existing clusters need to upgrade manually outside of TF, which is much safer -- e.g. through cloud consoles or other CLI.
Apply to a test Forge cluster and see that things still work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2165)
> [tf] upgrade k8s minimum version to 1.22

- crates/transaction-emitter-lib/src/emitter/mod.rs
- crates/transaction-emitter-lib/src/wrappers.rs
- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/interface/network.rs
- testsuite/forge/src/lib.rs
- testsuite/forge/src/report.rs
- testsuite/forge/src/runner.rs
- testsuite/forge/src/success_criteria.rs
- testsuite/run_forge.sh
- testsuite/testcases/src/fixed_tps_test.rs
- testsuite/testcases/src/gas_price_test.rs
- testsuite/testcases/src/lib.rs
- testsuite/testcases/src/network_chaos_test.rs
- testsuite/testcases/src/partial_nodes_down_test.rs
- testsuite/testcases/src/performance_test.rs
Moving the success criteria validation to test runner, which can evolve over time and also simplifies the run script. Also, make the duration configurable, which can be used in nightly run for forge to run for a longer time period. 
Running locally
```
FORGE_RUNNER_MODE=local ./testsuite/run_forge.sh
```
Output
```
=====START FORGE COMMENT=====
```
all up : 653 TPS, 4513 ms latency, 8900 ms p99 latency,no expired txns
```
* [Grafana dashboard](https://o11y.aptosdev.com/grafana/d/overview/overview?orgId=1&refresh=10s&var-Datasource=Remote%20Prometheus%20Devinfra&var-namespace=forge-sitalkedia-1658864771&var-chain_name=forge-0&from=1658864772000&to=1658865474000)
* [Validator 0 logs](https://es.devinfra.aptosdev.com/_dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0 …
```
> [Forge] Add TPS/latency validation to forge test runner

- developer-docs-site/docs/nodes/staking.md
Blatant error. Fixing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2226)
> Stating epoch in seconds, correctly.

- config/src/config/network_config.rs
- config/src/config/state_sync_config.rs
This PR makes two small improvements to the default config values for state sync and networking:
1. Turn on the data pre-fetcher for performance.
2. Increase the default number of outbound connections from 2 to 5. With more validators and more decentralization, we're seeing that 2 outbound connections is not great (there's a reasonably high chance of connecting to bad/slow peers on PFNs).
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2136)
> [Configs] Increase default configs for state sync.

- .github/workflows/build-images.yaml
- .github/workflows/pre-release-continuous-test.yaml
- .github/workflows/run-forge.yaml
Forge is currently running on PR as a "quick" e2e / perf test however there are many behaviors that we find post release that cannot be easily captured in a couple minutes. Therefore we'd like to run forge on a longer, continuous basis with more realistic setting to replicate realistic released network characteristics.
Test Plan:
Put up pr, with pull_request instead of pull_request_target in build-images.yaml
Run #e2e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2235)
> continuous testing

- .github/workflows/pre-release-continuous-test.yaml
A major lacking aspect of github actions is that certain things seem to be almost entirely untestable...
Test Plan:
hope for the best (its not in prod)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2238)
> [forgery] Attempt to fix pre release workflow

- aptos-node/src/lib.rs
- consensus/src/state_computer.rs
- execution/executor-types/src/lib.rs
- execution/executor/src/block_executor.rs
- execution/executor/src/chunk_executor.rs
- execution/executor/src/components/chunk_commit_queue.rs
- execution/executor/src/fuzzing.rs
- execution/executor/src/tests/chunk_executor_tests.rs
- execution/executor/src/tests/mod.rs
- state-sync/state-sync-v1/src/executor_proxy.rs
- state-sync/state-sync-v1/src/shared_components.rs
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
- state-sync/state-sync-v2/state-sync-multiplexer/src/lib.rs
- storage/aptosdb/src/lib.rs
- storage/backup/backup-cli/src/backup_types/transaction/restore.rs
- testsuite/forge-cli/src/main.rs
This PR wraps both `BlockExecutor` and `ChunkExecutor` with a wrapper that can drop the inner executors to release the `ExecutedTrees` they hold. Specifically, we want the `StateDelta` that includes 2 SMTs to be dropped. Otherwise, the SMT descendants from these trees would increase the memory usage into infinity, causing memory leak. 
This is a hot fix. The best solution should merge these two executors together into one and shared by StateSync and Consensus. 
ut should all be okay. Will deploy to clusters to see the counter will change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2210)
> [fix] wrap BlockExecutor and ChunkExecutor as an Option of Inner

- Cargo.lock
- Cargo.toml
- crates/aptos-compression/Cargo.toml
- crates/aptos-compression/src/lib.rs
- crates/aptos-compression/src/metrics.rs
- crates/aptos-compression/src/tests.rs
This PR introduces a simple `aptos-compression` crate so that we can have a single unified interface and implementation for data compression. Once this lands, state sync and consensus will be updated to make use of it.
Internally, the crate uses [LZ4](https://github.com/10xGenomics/lz4-rs) compression, which provides reasonable compression ratios with high compression speeds (determined using anecdotal benchmarks). The crate also offers basic metrics counters for us to track the cumulative compression ratio and compression durations.
A simple unit test has been added to ensure that basic Aptos data structures can be compressed and decompressed successfully.
--- …
> [Aptos Compression] Add a simple compression crate.

- Cargo.lock
- crates/aptos/src/node/mod.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/Cargo.toml
- testsuite/smoke-test/src/aptos_cli.rs
- testsuite/smoke-test/src/rosetta.rs
node CLI for stake handling was broken:
- module names are case sensitive : Stake => stake
- when we moved to bls, CLI wasn't updated to receive proof of possesion
Extracted ValidatorConfigArgs for being able to use same args for future new commands
Adding unit test to catch issues like that in the future
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2234)
> [cli][smoke-test] Fix node CLI for stake handling, and add register_validator_candidate unit test

- .github/workflows/run-forge.yaml
- testsuite/forge/src/success_criteria.rs
This improves the UX when a forge job fails.
Previously the github actions job failure would occur in a separate step that was meant to check for whether forge is land blocking or not and didn't give any context whatsoever:
With this change:
- the actual step that runs forge will fail
- when latency requirements etc. fail, it will print a nice error message by leveraging the `::error::` syntax
- the job summary will be posted as github actions job summary.
Overall this should make it more obvious what and why things failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2250)
> cicd: improve forge failure UX

- execution/executor/src/block_executor.rs
- execution/executor/src/chunk_executor.rs
- execution/executor/src/components/chunk_output.rs
- execution/executor/src/db_bootstrapper.rs
- execution/executor/src/tests/mod.rs
- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/storage-interface/src/cached_state_view.rs
- storage/storage-interface/src/executed_trees.rs
- storage/storage-interface/src/sync_proof_fetcher.rs
- vm-validator/src/vm_validator.rs
Switch to AsyncProofFetcher in block executor.
On a 250M accounts DB, observed tps increases from 3.25K to 5.8K for p2p txns on a 32vCPU, 128G RAM machine.
Tested on large DB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2240)
> [Execution] Use AsyncProofFetcher.

- aptos-node/src/lib.rs
1. The staking module was renamed from `Stake` to `Stake`
2. The minimum lockup for a proposal was 7 days, whereas the maximum proposal allowed when running a test node locally was 24 hours. Updated maximum stake to be 14 days
Tested Manually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2247)
> [CLI][AF] Fix max staking time

- crates/aptos/src/account/create_resource_account.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/op/key.rs
Remove some general unwraps so that errors are handled more gracefully in the CLI
E2E tests / Clippy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2251)
> [aptos-cli] Remove some unwraps for error handling

- aptos-move/aptos-vm/src/move_vm_ext/code_context.rs
- aptos-move/e2e-testsuite/Cargo.toml
As there are still some vulnerabilities about code caching which may be hit on devnet if someone figures out how to construct the `code::publish_package_txn`, this PR guards this features temporarily. The transaction for now aborts if not compiled in fuzzing or test mode.
Existing tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2265)
> [move] Disable package publishing for devnet release.

- crates/transaction-emitter-lib/src/emitter/mod.rs
- testsuite/forge-cli/src/main.rs
There is a regression in forge TPS and latency after https://github.com/aptos-labs/aptos-core/pull/2241. Updating the threshold for now until we land a bunch of improvements on storage side to speed it up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2269)
> [Forge] Increase the latency threshold and decrease load

- terraform/helm/aptos-node/values.yaml
4 seems to conservative especially considering the target hardware spec in everyone's mind.
(forge goes up to > 5k with 8, and a bit more with 16)
forge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2243)
> defaulting concurrency level to 8

- Cargo.lock
- terraform/helm/k8s-metrics/values.yaml
- testsuite/forge/Cargo.toml
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/prometheus.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/swarm.rs
Implement `Swarm::query_metrics`, which uses the [`prometheus_http_query` crate](https://docs.rs/prometheus-http-query/latest/prometheus_http_query/index.html) to connect to a prometheus instance. This will allow us to define specific SuccessCriteria that are backed by metrics.
New unit tests written and can be run with `cargo test -p forge`. 
```
running 4 tests
test backend::k8s::prometheus::tests::test_create_query ... ok
test backend::k8s::cluster_helper::tests::test_create_namespace_final_error ... ok
test backend::k8s::cluster_helper::tests::test_create_namespace_retryable_error ... ok
test backend::k8s::prometheus::tests::test_query_prometheus ... ok
test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.17s
```
One of the tests attempts to …
> [forge] prometheus integration

- .github/workflows/run-forge.yaml
- testsuite/run_forge.sh
Add the test runner output for both the pre-forge and forge results comment. Also add an indicator for the GHA run attempt, which makes it easier to parse spammy GH comments in the case where Forge is triggered many times in a row.
Also fixes a bug that was introduced in https://github.com/aptos-labs/aptos-core/commit/6e88ffbea18d4147497e83bbf54638b72c8bb27a which did a bit of variable name cleanup, resulting in bad GH comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2262)
> [gha] keep one forge run comment per attempt

- crates/aptos/src/node/mod.rs
- crates/aptos/src/test/mod.rs
- testsuite/forge/src/backend/local/mod.rs
- testsuite/forge/src/interface/chain_info.rs
- testsuite/smoke-test/src/aptos_cli.rs
- testsuite/smoke-test/src/network.rs
- testsuite/smoke-test/src/test_utils.rs
- types/src/network_address/mod.rs
- types/src/on_chain_config/mod.rs
extracted the same config from registering a new validator and used for the new command.
Seems like registering a new validator is broken on main, as bls proof of availability is missing,
but since I want to merge this to testnet branch (I assume?) that cannot be part of this diff.
how should I test this properly?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1946)
>  [cli][smoke-tests] Add command and test to update validator network addresses

- .pre-commit-config.yaml
We have files larger than the 500kb default (package.json in the SDK), and I need to generate a file that is similar to that existing file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2293)
> Bump maxkb pre-commit hook

- .github/workflows/pre-release-continuous-test.yaml
The last attempt at this tried to do too much, turns out github actions are really difficult to test (oh the irony).
Instead this embodies KISS by doing as little as possible to get something, anything running first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2313)
> [forge] Add back most simple version for continuous testing

- .github/workflows/pre-release-continuous-test.yaml
Add permissions that forge needs to function
Test Plan:
commit and try to run the workflow from the ui
https://github.com/aptos-labs/aptos-core/actions/runs/2754772940
Sounds clowny but this is the best I've got for now
> [forge] Add required permissions for forge workflow

- ecosystem/platform/server/app/views/layouts/_application.html.erb
Allows setting additional classes on `<body>` via `content_for(:body_class, "additional classes here")`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2318)
> [community] Add :body_class slot for classes on <body>.

- testsuite/smoke-test/src/rosetta.rs
This test was failing, and I didn't know why, until we found out that
the block height had been increased by one.  So, this test should now
do it's proper job.
It's a test, so the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2340)
> [testsuite] Re-enable rosetta block test

- .cargo/config.toml
- Cargo.lock
- aptos-node/src/lib.rs
- config/src/config/logger_config.rs
- config/src/config/mod.rs
- crates/aptos-logger/Cargo.toml
- crates/aptos-logger/src/aptos_logger.rs
- crates/aptos-logger/src/logger.rs
- crates/aptos-logger/tests/tracing_translation_tests.rs
- docker/build-rust-all.sh
Hey Folks, I'm enabling tokio-console for all our builds. 
It can be disabled with --cfg disable_tokio_console
+ 
Adding Cargo.lock to .gitignore
cargo install --locked tokio-console // Once
1. kubectl port-forward pods/<pod-name> 6669:6669
2. tokio-console
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2203)
> Enabling Tokio-Console

- consensus/src/counters.rs
- consensus/src/experimental/buffer_manager.rs
the check for if the request is retry has a bug when the cursor is None, it'll spawn the request as retry and delay for 100ms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2331)
> [consensus] fix the retry request in buffer manager

- CODEOWNERS
I want this for now while we have two APIs, to make sure changes don't introduce any kind of incompatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2352)
> Add codeowners for `/api`

- crates/aptos-genesis/src/builder.rs
- testsuite/forge/src/interface/node.rs
- testsuite/smoke-test/src/full_nodes.rs
* VFN was sending transactions to all validators using the public network.
* The test_vfn_failover smoke-test was nonsensical. It should actually fail to run the transactions if the VFN's validator is down. But managed to do so because the transactions were reaching other validators through the public network.
Existing and modified smoke tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2248)
> [smoke-tests] Fix vfn failover test to send transactions across public network to vfn instead of validator

- terraform/helm/aptos-node/templates/_helpers.tpl
- terraform/helm/aptos-node/values.yaml
- terraform/helm/genesis/templates/_helpers.tpl
- terraform/helm/genesis/values.yaml
- testsuite/forge-test-runner-template.yaml
- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/helm-values/aptos-node-values.yaml
- testsuite/forge/src/backend/k8s/helm-values/genesis-values.yaml
- testsuite/run_forge.sh
Make forge test runner pod names more descriptive and non-overlapping. Include in the pod name the Forge namespace, timestamp, and image_tag/git_ref. 
Also label all resources managed by Forge (the test runner, all resources in the included helm releases) with labels `forge-namespace` and `forge-image-tag`. We could consider labeling with the Github actions run ID too, but we'd need to propagate that into the rust code.
Also fix a big that was re-introduced where the test runner acquires a namespace by pre-empting another test runner, but fails on the k8s API 409 error code instead of continuing.
Run forge with k8s test runner. Then run another one in the same namespace and let them pre-empt each other.
Run it the first time with a known namespace. Test runner pod starts with the name …
> [forge] label test runner pods with image tag

- Cargo.lock
- aptos-move/framework/cached-packages/Cargo.toml
- aptos-move/framework/cached-packages/src/lib.rs
- aptos-move/move-deps/Cargo.toml
- aptos-move/move-deps/src/lib.rs
I also would have wished to remove the entire custom `build.rs` but there are various dependencies from abis, bytecode, etc. which are referenced through our code. Better wait with refactoring this until there is more clarity about our release process beyond running genesis every time again.
Closes #2348
New tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2354)
> [framework] Adds tests that generated Rust SDKs are up-to-date

- .github/workflows/build-images.yaml
- .github/workflows/pre-release-continuous-test.yaml
- .github/workflows/run-forge.yaml
- testsuite/run_forge.sh
Since nightly forge tests will run on a separate cluster, try running a few concurrently. We should have enough capacity since land-blocking Forge tests are run in a separate cluster. For now, two namespaces/jobs spin up: 
* `forge-continuous-0`
* `forge-continuous-1`
Also explicitly specify which Forge cluster each job is using in GHA in the job spec yaml itself, rather than injecting it via Github secrets. The secrets were are hard to read (can't read them once you set them), and not exactly secret either.
Also include some logic in `run_forge.sh` that will crawl the last few commits behind `HEAD` to find the last built docker image. This ensures that we're testing a valid image tag now that we're not running Forge after the `build-images` job.
Add GHA trigger to run the nightly tests …
> [gha] run multiple forge tests on nightly

- terraform/helm/aptos-node/templates/_helpers.tpl
- terraform/helm/genesis/templates/_helpers.tpl
Template `.Values.labels` into the helpers using a range and specifying each key/value, rather than trying to use `toYaml`
Previous way results in cryptic helm error in the case that additional labels are not supplied... 
```
Error: YAML parse error on aptos-node/templates/configmap.yaml: error converting YAML to JSON: yaml: line 9: mapping values are not allowed in this context
```
Warning was not heeded in https://github.com/aptos-labs/aptos-core/pull/2276#issuecomment-1200034519 😅 
TF apply in a testnet both when labels are specified and not
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2370)
> [helm] template label helper as range

- .github/workflows/build-images.yaml
- .github/workflows/pre-release-continuous-test.yaml
- .github/workflows/run-forge.yaml
- testsuite/run_forge.sh
This reverts commit cdfa3052adce806fccda6203608c023378d1f934 from #2361 since it breaks the Build+Push Images / Forge GH workflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2378)
> Revert "[gha] run multiple forge tests on nightly"

- api/src/tests/test_context.rs
- aptos-node/src/lib.rs
- crates/aptos-genesis/src/builder.rs
- crates/aptos-genesis/src/test_utils.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/test/mod.rs
- testsuite/forge/src/backend/local/mod.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/smoke-test/src/aptos_cli.rs
- testsuite/smoke-test/src/network.rs
- testsuite/smoke-test/src/rosetta.rs
- testsuite/smoke-test/src/smoke_test_environment.rs
- testsuite/smoke-test/src/state_sync.rs
- testsuite/smoke-test/src/state_sync_v2.rs
- Made genesis and stake configurable from local swarm tests
- In order to do that nicely, without every test needing to set everything, add SwarmBuilder. 
- removed LocalSwarmBuilder that was used always with same configuration
Unit test added follows the full validator e2e runbook  from AIT2 :
https://aptos.dev/nodes/ait/connect-to-testnet#joining-validator-set
https://aptos.dev/nodes/ait/connect-to-testnet/#leaving-validator-set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2273)
> [cli][smoke-test] Make genesis and stake configurable in swarm and test e2e validator runbook

- api/src/context.rs
- api/src/index.rs
- api/src/lib.rs
- api/src/set_failpoints.rs
- config/src/config/api_config.rs
- crates/aptos-rest-client/src/lib.rs
- crates/aptos-rosetta/src/main.rs
- testsuite/smoke-test/src/rosetta.rs
Adding failpoints REST API (/failpoints?name=str&actions=str), to allow modifying failpoints during execution.
This will allow more targeted/surgical testing - both within smoke tests as well as forge/cluster tests
Used in new smoke tests in the stacked diffs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2048)
> [api] Add REST API to modify failpoints during execution

- docker/compose/validator-testnet/docker-compose.yaml
You should specify the test directory explicitly, because otherwise faucet will not be able to use the mint.key
In the new version `aptos-node` without the `--test-dir` flag the mint.key will not be created in `/opt/aptos/var/`. This will cause faucet not to start.
Without flag:
```
Entering test mode, this should never be used in production!
Log file: "/tmp/27eaa46b5aa5363e2bdac1279e1386be/validator.log"
Test dir: "/tmp/27eaa46b5aa5363e2bdac1279e1386be"
-> Aptos root key path: "/tmp/27eaa46b5aa5363e2bdac1279e1386be/mint.key" <- Before
Waypoint: 0:f0f52e7410713832f22ce3da2c1eaf0c7c81fc3b0c3bd2a2cf2e50441e9b71f0
ChainId: TESTING
REST API endpoint: 0.0.0.0:8080
FullNode network: /ip4/0.0.0.0/tcp/6181
```
With `--test-dir /opt/aptos/var`:
```
Entering test …
```
> [docker] Fix command for validator

- docker/compose/aptos-node/docker-compose-fullnode.yaml
- docker/compose/aptos-node/docker-compose.yaml
- docker/compose/public_full_node/docker-compose.yaml
- docker/compose/validator-testnet/docker-compose.yaml
- docker/rust-all.Dockerfile
- terraform/helm/aptos-node/templates/fullnode.yaml
- terraform/helm/aptos-node/templates/validator.yaml
- terraform/helm/fullnode/templates/fullnode.yaml
this puts the built binaries all into `/usr/local/bin` for all images (which we already did for all the images except the validator and NHC one) which improves consistency and also makes it easier to call them since `/usr/local/bin` is already in the $PATH
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2394)
> infra: consistency - put all built binaries into thes same path in docker image and make them available in $PATH

- Cargo.lock
- Cargo.toml
- aptos-move/aptos-sdk-builder/Cargo.toml
- testsuite/generate-format/Cargo.toml
Using multiple versions of serde-reflection breaks tools like Nix or
cargo-vendor which expect only one version of a crate per
dependency.
#1779 cleaning up this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2389)
> [deps] align on a single version of serde-reflection

- docker/compose/aptos-node/docker-compose-fullnode.yaml
- docker/compose/aptos-node/docker-compose.yaml
- docker/compose/public_full_node/docker-compose.yaml
- docker/compose/validator-testnet/docker-compose.yaml
- docker/rust-all.Dockerfile
- terraform/helm/aptos-node/templates/fullnode.yaml
- terraform/helm/aptos-node/templates/validator.yaml
- terraform/helm/fullnode/templates/fullnode.yaml
Reverts aptos-labs/aptos-core#2394
this is breaking the instructions to run a fullnode since the docs copy a fullnode config from main instead of devnet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2401)
> Revert "infra: consistency - put all built binaries into thes same path in docker image and make them available in $PATH"

- .github/workflows/build-images.yaml
- .github/workflows/pre-release-continuous-test.yaml
- .github/workflows/run-forge.yaml
- testsuite/run_forge.sh
Re-introduce #2361 
Also fix the GHA workflow triggering logic that was missed in above PR. Namely: making the `run-forge.yaml` inputs `required: false` and specifying a default when appropriate.
* `FORGE_CLUSTER_NAME` defaults to `aptos-forge-0` for all land-blocking Forge invocations. Otherwise explicitly use `aptos-forge-1` for nightly continuous testing
* `GIT_SHA` has no default and is not required. If specified, Forge will try to use images that are tagged with that git SHA. Otherwise if not specified, Forge will check out the current branch and check the last few commit hashes (e.g. nightly test will check latest commits in `main`, but the last commit may not necessarily have finished building)
The nighty workflow itself was tested in …
> [gha] fix nightly forge tests and cluster selection

- docker/rust-all.Dockerfile
This add tini as entrypoint to our docker images (https://github.com/krallin/tini).
This is quite important as otherwise the processes we run inside the container don't receive SIGTERM as signal properly. For example I noticed that while trying to run aptos-node via docker locally it never terminated when doing CTRL+C but rather I hard to hard SIGKILL it via docker stop in another terminal. This very likely also negatively affected our node's shutdown behaviour in kubernetes since essentially in our current setup the container would always get SIGKILLED after a while.
This might be also the root cause behind aptos-logger not logging certain exit conditions properly.
Also solves #1994 
Build image on a codespace and compared CTRL+C behaviour before and after the change. Before change, …
> docker: add tini as init process to docker images to ensure SIGTERM is propagated

- crates/aptos-rest-client/src/lib.rs
- ecosystem/indexer/migrations/2022-07-28-181243_ledger_info/down.sql
- ecosystem/indexer/migrations/2022-07-28-181243_ledger_info/up.sql
- ecosystem/indexer/src/indexer/fetcher.rs
- ecosystem/indexer/src/indexer/tailer.rs
- ecosystem/indexer/src/main.rs
- ecosystem/indexer/src/models/ledger_info.rs
- ecosystem/indexer/src/models/mod.rs
- ecosystem/indexer/src/schema.rs
Saves chain_id when the indexer starts. If we somehow try to index a different chain, exit program. 
I also had to create a trait for TransactionFetcher in order to mock the data for the test. 
```
Cargo test
running 1 test
test indexer::tailer::test::test_chain_id_check ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s
```
Also tested by running
`cargo run -- --pg-uri "postgresql://localhost/postgres" --node-url "http://0.0.0.0:8080" --emit-every 25 --batch-size 100` and making sure that if we tail a different full node (e.g. devnode) the process crashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2334)
> [Indexer] Create ledger_info table and add test

- terraform/helm/monitoring/templates/monitoring.yaml
- testsuite/forge-test-runner-template.yaml
Add a separate `ClusterIP` prometheus service to the `monitoring` helm chart.
This makes it such that pods within the cluster can access prometheus, such as Forge, which will use prometheus to define and validate complex success criteria a la https://github.com/aptos-labs/aptos-core/pull/2270
Terraform apply, and see that the service comes up and we're able to access it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2425)
> [helm] separate prometheus k8s service

- ecosystem/typescript/sdk/src/transaction_builder/bcs/helper.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/helper.ts
Add more BCS helpers and expose them. This would simplify the usage of BCS. e.g.
```
const serializer = new Serializer();
serializer.serializeU32(123);
const bytes = serializer.getBytes();
```
can be reduced to
`const bytes =  bcsSerializeU32(123);`
Added unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2369)
> feat: expose more BCS helpers

- config/src/config/mempool_config.rs
While running transaction emitter in AIT2, one thing we observed is that the REST APIs become the major bottleneck in transaction submission. Per REST endpoint, we are not able to submit more than ~250 transaction per second. Digging into it, figured that the reason for this is we limit the maximum outstanding transaction processing task to be 2 and given each transaction validation takes ~8 ms, we can only process ~250 TPS. Bumping up the max concurrent transaction processing backlog for mempool to 24. This change will hopefully help us achieve a higher TPS for upcoming AIT3.  This along with other changes I have in flight for the transaction emitter can help bump up the TPS for forge as well to 6.5K (https://github.com/aptos-labs/aptos-core/pull/2375).
Ran forge with this change and can …
> [Mempool] Increase the maximum concurrent task for bounded executor

- Cargo.lock
- execution/executor-benchmark/src/lib.rs
- storage/schemadb/Cargo.toml
Had to open rocksdb non-readonly as a mitigation for DB checkpointing deadlock. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2453)
> [storage] update rocksdb dependency

- Cargo.lock
- Cargo.toml
- config/src/config/state_sync_config.rs
- state-sync/aptos-data-client/src/aptosnet/mod.rs
- state-sync/aptos-data-client/src/aptosnet/state.rs
- state-sync/aptos-data-client/src/aptosnet/tests.rs
- state-sync/storage-service/server/src/lib.rs
- state-sync/storage-service/server/src/tests.rs
- state-sync/storage-service/types/Cargo.toml
- state-sync/storage-service/types/src/lib.rs
- state-sync/storage-service/types/src/requests.rs
- state-sync/storage-service/types/src/responses.rs
- state-sync/storage-service/types/src/tests.rs
- testsuite/smoke-test/src/state_sync_v2.rs
This PR adds data compression to state sync (i.e., it utilizes the recently added `aptos-compression` crate: https://github.com/aptos-labs/aptos-core/pull/2232). At a high-level:
1. Storage service clients will specify (in the `StorageServiceRequest`) whether or not the response should be compressed. Compression can be configured via the `AptosDataClientConfig`. The default is true.
2. If the client requests compression, the server will compress the response (see `StorageServiceResponse`).
3. Compression happens at the application layer (instead of at the network layer). There's obviously trade-offs with this approach, but the benefits are: (i) clients can enable/disable compression easily; (ii) the storage service can use cached responses to serve directly to clients, without needing to …
> [State Sync] Add data compression to state sync.

- ecosystem/platform/server/config/environments/production.rb
- ecosystem/platform/server/config/routes.rb
Redirects community.aptoslabs.com to aptoslabs.com/community and everything else to aptoslabs.com/{path}.
To be merged after #1640 is deployed and DNS for both domains is pointing to it.
Tested manually with curl and Host header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2200)
> Redirect community.aptoslabs.com -> aptoslabs.com.

- docker/docker-bake-rust-all.hcl
- docker/docker-bake-rust-all.sh
- docker/rust-all.Dockerfile
It turns out the regular docker builder doesn't respect our `.dockerignore` properly: https://github.com/aptos-labs/aptos-core/pull/2471. This PR makes it impossible to use the regular builder, you must invoke the docker build from a script that sets an arg. It also tells you how to get around it if you're 100% sure you know what you're doing.
```
$ docker build -f docker/rust-all.Dockerfile -t rust-all .
#10 0.379
#10 0.379 ===
#10 0.379 READ ME
#10 0.379 ===
#10 0.379
#10 0.379 You likely just tried run a docker build using this Dockerfile using
#10 0.379 the standard docker builder (e.g. docker build). The standard docker
#10 0.379 build command uses a builder that does not respect our .dockerignore
#10 0.379 file, which will lead to a build failure. To build, you should instead
#10 …
```
> Ensure `rust-all` Dockerfile is being run with appropriate builder

- aptos-move/framework/aptos-token/sources/token.move
This can not be exposed before devnet cut as we should make sure that
the user opts into receiving unsolicited NFTs. The world is divided on
what the right approach is but this is a one way door as is.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2474)
> [framework] do not expose token::transfer

- mempool/src/shared_mempool/network.rs
Peer prioritization is used to broadcast transactions from a fullnode to a subset of outbound connections.
Add some randomness between fullnodes for deciding peer prioritization, by using a simple hash. (Within a fullnode, the prioritization sorting is still stable.)
Before the change, because fullnodes did the same sorting, fullnode connections could be skewed. Most notably if `NetworkConfig.max_outbound_connections` > `MempoolConfig.default_failovers`.
Ran a modified smoke test with 10 validators and VFNs and `NetworkConfig.max_outbound_connections=10` and `MempoolConfig.default_failovers = 1`. Before the change, a single VFN (with smallest peerId) was the outbound broadcast node for most VFNs; now the connections are more evenly spread out.
--- …
> [mempool] make broadcast peer prioritization random between fullnodes

- .dockerignore
See https://aptoslabs.pagerduty.com/incidents/Q25RRHTAYP052P.
This was failing before:
```
docker context create builders
docker context use builders
docker buildx create --driver docker-container --use --builder builders --name builder-dda7b2c6-4289-4ae5-9b50-38624dae0f9f --buildkitd-flags '--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host'
docker buildx inspect --bootstrap --builder builder-dda7b2c6-4289-4ae5-9b50-38624dae0f9f
export LAST_GREEN_COMMIT=25e4d7320a0a4dac20b4c07e353350636a8c3d01
docker/docker-bake-rust-all.sh
```
These steps capture what CI was doing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2486)
> Allow .mv files in .dockerignore

- docker/build-rust-all.sh
- docker/rust-all.Dockerfile
I want to use this in CI. Having it in the tools image enables me to use this from docker, potentially benefiting from caching to speed up the CI.
I sort some stuff while I'm at it.
Build the tools image:
```
docker context create builders
docker context use builders
docker buildx create --driver docker-container --use --builder builders --name builder-dda7b2c6-4289-4ae5-9b50-38624dae0f9f --buildkitd-flags '--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host'
docker buildx inspect --bootstrap --builder builder-dda7b2c6-4289-4ae5-9b50-38624dae0f9f
export LAST_GREEN_COMMIT=25e4d7320a0a4dac20b4c07e353350636a8c3d01
docker/docker-bake-rust-all.sh tools
```
See that the new binary is in there:
```
todo, waiting for long ass build
```
--- …
> Add aptos-openapi-spec-generator to CI

- ecosystem/platform/server/app/assets/stylesheets/application.tailwind.css
- ecosystem/platform/server/app/components/dialog_component.rb
- ecosystem/platform/server/app/javascript/controllers/dialog_controller.ts
- ecosystem/platform/server/package.json
- ecosystem/platform/server/yarn.lock
This is no longer necessary since the last two versions of Safari support `<dialog>`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2493)
> [community] Remove dialog polyfill.

- crates/aptos-genesis/src/builder.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/swarm.rs
- testsuite/smoke-test/src/full_nodes.rs
- testsuite/smoke-test/src/fullnode.rs
- testsuite/smoke-test/src/lib.rs
- testsuite/smoke-test/src/network.rs
- testsuite/smoke-test/src/state_sync_v2.rs
- testsuite/smoke-test/src/txn_broadcast.rs
Add smoke test that checks txn goes through consensus even if the local validator is not creating proposals. This behavior should be true with both mempool and quorum store.
Also improve bringing up vfn in a local swarm to:
* Avoid having a public network at validators on launch
* Avoid restart of validators on vfn startup
Locally reverted #1954 and confirmed the test will fail with that bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2249)
> [smoke-tests] Add a smoke test for txn broadcasting

- Cargo.lock
- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/helm-values/aptos-node-values.yaml
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/mod.rs
- testsuite/forge/src/interface/factory.rs
- testsuite/forge/src/runner.rs
- testsuite/testcases/src/lib.rs
- testsuite/testcases/src/performance_test.rs
Add validator-fullnode (VFN) support to Forge. This lets us be more expressive in Forge network topology and opens the door for more tests.
Changes to the Forge CLI:
* `forge operator resize` now takes an optional `--num-fullnodes` option, which defaults to 1
* The default `land_blocking` test suite now spins up 30 validators and 1 VFN (attached to validator-0), and the `PerformanceBenchmark` now targets all validators and fullnodes available to the swarm context.
Changes to `Factory`:
* `launch_swarm` now takes in `num_validators` and `num_fullnodes`. The former continues to be `NonZeroUsize`, but the latter is just a `usize`
Changes to `ForgeConfig`:
* We can now specify `initial_fullnode_count` similar to how we specified `initial_validator_count`. Use this method to spin up a network …
> [forge] spin up swarm with num_fullnodes

- mempool/src/shared_mempool/tasks.rs
#1954 only applies to transactions coming from a VFN. This covers the case when we submit directly to validators, which happens in some of our tests (e.g., perf tests).
Smoke tests added in #2249.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1957)
> [mempool] on direct client txn submission to a validator, only broadcast if configured to do so

- Cargo.lock
- consensus/src/network_interface.rs
- crates/aptos-compression/src/lib.rs
- crates/aptos-compression/src/metrics.rs
- crates/aptos-compression/src/tests.rs
- network/Cargo.toml
- network/src/protocols/network/mod.rs
- network/src/protocols/wire/handshake/v1/mod.rs
- state-sync/storage-service/types/src/responses.rs
- testsuite/generate-format/tests/staged/network.yaml
This PR adds data compression to consensus messages using the compression crate at the network layer. Specifically:
1. Compression can now be configured via the consensus config.
2. We add additional metrics labels to the compression crate to better track the compression ratios and latencies between clients (i.e., consensus and state sync).
3. In order to get this to work, I've added the node config to the network sender trait and all relevant code. This isn't great, but there doesn't appear to be an easy work around without heavy refactoring (and I'd like to minimize the amount of network changes I make 😄).
Existing tests should cover this. I've also inspected the metrics on a forge run. Here's the compression ratio being reported by consensus for the last run:
--- …
> [Consensus] Add compression to consensus messages.

- ecosystem/platform/server/config/routes.rb
Some routes like `/users/sign_in` weren't getting redirected because they had precedence over the redirect.
Tested manually with curl + host header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2481)
> [community] Fix redirect for devise + admin routes.

- ecosystem/platform/server/config/application.rb
Enables gzip for HTTP responses via Rack middleware. Ideally the CDN would handle this instead.
Before
After
Manual
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2496)
> [community] Enable gzip for HTTP responses.

- Cargo.lock
- aptos-move/e2e-tests/Cargo.toml
- crates/aptos/Cargo.toml
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/move_tool/transactional_tests_runner.rs
Add a subcommand to run the transactional test runner. With this command, Move developers don't have to write Move transactional tests in a Rust repo. Instead, they can run a CLI command and verify the results.
cargo run -p aptos -- move run-transactional-test  --root-path aptos-core/aptos-move/aptos-transactional-test-harness/tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2291)
> [cli] Add a subcommand to run transactional test runner

- crates/aptos/src/node/mod.rs
- crates/aptos/src/test/mod.rs
hand written functions provide no guarantees and we can see that
increase lockup was actually broken.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2529)
> [aptos-cli] use aptos-transaction-builder instead of hand written functions

- .github/workflows/pre-release-continuous-test.yaml
- .github/workflows/run-forge.yaml
Remove duplicate continuous job, instead make it the template for adding a new continuous test
Adding new continuous test is going to also require plumbing suite name through which is not set yet but I'm trying to KISS
Also reduce the continuous TPS success criteria because we want to be able to reasonably success and expectations for TPS in longer run is lower than shorter run. Not that that is noit a problem, but for now set a realistic goal for success.
Test Plan:
gh workflow run -r forgery pre-release-continuous-test.yaml
https://github.com/aptos-labs/aptos-core/actions/runs/2799804929
#e2e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2544)
> [forge] Remove duplicate continuous job, increase frequency, reduce duration

- ecosystem/typescript/sdk/src/generated/AptosGeneratedClient.ts
- ecosystem/typescript/sdk/src/generated/core/OpenAPI.ts
Slipped through after the spec changed because I had to force land because of the pull_request / pull_request_target thing.
Now that the CI is updated, I can actually wait for it to run before landing this to finally get the build green.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2546)
> Regenerate TS client

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/README.md
- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/index.ts
The current changelog is a total mess because the tool we're using doesn't seem to be able to figure out which commits belong in which version. Beyond that the formatting is gross. Then beyond that, building your changelog out of just git commits is not a great user experience (https://keepachangelog.com/en/1.0.0/).
In this PR I rewrite the changelog manually for now until we come up with a better solution.
```
./check.sh
```
Then CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2543)
> Update CHANGELOG for TS SDK

- ecosystem/platform/server/app/components/header_component.html.erb
- ecosystem/platform/server/app/javascript/controllers/header_controller.ts
- Don't navigate to `#` when top-level links are clicked (exception - Currents)
- On mobile, toggle nav group when anywhere in the group is clicked, not just the toggle button (exception - don't toggle when nav items are clicked)
- Increase nav item click target to span the full width
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2531)
> [community] Improve nav click behavior.

- ecosystem/platform/server/config/application.rb
In production, only HTML responses were being gzipped (not JS & CSS). This change gzips everything in prod.
Tested manually with RAILS_ENV=production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2533)
> [community] Fix gzip for assets in production.

- storage/aptosdb/src/aptosdb_test.rs
- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/pruner/db_pruner.rs
- storage/aptosdb/src/pruner/db_sub_pruner.rs
- storage/aptosdb/src/pruner/event_store/event_store_pruner.rs
- storage/aptosdb/src/pruner/event_store/test.rs
- storage/aptosdb/src/pruner/ledger_pruner_manager.rs
- storage/aptosdb/src/pruner/ledger_pruner_worker.rs
- storage/aptosdb/src/pruner/ledger_store/ledger_counter_pruner.rs
- storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
- storage/aptosdb/src/pruner/mod.rs
- storage/aptosdb/src/pruner/pruner_manager.rs
- storage/aptosdb/src/pruner/state_pruner_manager.rs
- storage/aptosdb/src/pruner/state_pruner_worker.rs
- storage/aptosdb/src/pruner/state_store/mod.rs
- storage/aptosdb/src/pruner/state_store/test.rs
- storage/aptosdb/src/pruner/transaction_store/transaction_store_pruner.rs
- storage/aptosdb/src/pruner/transaction_store/write_set_pruner.rs
- storage/aptosdb/src/pruner/utils.rs
- Always initialize pruners in order to keep track of the right min_readable_version. More details in the sceenshot. Get rid of `Some(...` in code.
- When pruner is disabled, do not spawn the thread to run the running command.
- Do not keep track min_readable_version in pruner manager and pruner worker but use the pruner as the source of truth.
- Change `get_first_txn_version` and `get_first_write_set_version` to get their values from `transaction_store`.
- In state store, record the progress (i.e. update the min_readable_version) before deleting the items from DB to avoid the edge case that API queries the wrong min_readable_version when pruning is in progress.
- Change the threading model of pruners to be continuous.
- Add bool configs to explicitly enable/disable pruners.
- A lower pri …
> [storage][pruner] Always initialize pruners

- crates/aptos/src/test/mod.rs
Or at least add more logs to see why it is failing.
Basically one of the two cli accounts that we create don't have needed funding.
Not sure if we hit the same address as one of the nodes (so making it generate truly random addresses), or there is something else going on (like interaction with another test?). Tried a few times locally, it always succeeds. (12 failures in a day is probably very low failure rate to catch locally)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2537)
> [smoke-test] Try to fix flaky aptos_cli smoke test

- ecosystem/platform/server/app/components/footer_component.html.erb
Remove those pesky footer navigation link underlines as these should only be used within paragraph content. 
Ensure no underlines exist below links in footer navigation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2558)
> [community] Remove underline from footer navigation links

- crates/aptos-rosetta/src/types/objects.rs
- crates/aptos/src/account/transfer.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/aptos_cli.rs
- testsuite/smoke-test/src/rosetta.rs
Gas unit price wasn't being used in calculations (because it defaulted to 1).  Now it will properly handle gas by adding the appropriate fields and calculations.  Additionally added more tests for rosetta
Now there are ton more tests in rosetta covering these cases for failed transactions and variable gas price
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2547)
> [aptos-rosetta/aptos-cli] Fix Gas price handling

- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/framework/aptos-framework/sources/stake.move
- sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_block_transactions_work.json
- sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_table_item_parsing_works.json
Currently for on chain governance voting, only an active validator's active stake is taken into account. This diverges from consensus where both active and pending_inactive stakes are counted. This is more of a problem now after we switch to the recurring lockup model in staking where pending_inactive can remain so for a long time (before it's cleared at the end of every epoch. Now it's only cleared at the end of the validator's lockup period). 
Unit tests. Will add e2e tests for governance in a separate PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2532)
> [Aptos Framework][Governance] Update voting power to take into account pending_inactive stake

- ecosystem/platform/server/app/components/footer_component.html.erb
- ecosystem/platform/server/app/components/header_component.html.erb
- ecosystem/platform/server/app/components/header_component.rb
- ecosystem/platform/server/app/form_builders/aptos_form_builder.rb
- Make main navigation Front & Center
- Adjust spacing for various breakpoints
- Move "Currents" into appropriate top-level item "About"
- Change cursor to all Top-level (ghost) items to `cursor: default` to make clear distinction as to what's navigational
- Reduce vertical padding within dropdowns
Manually verify above changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2559)
> [community] Tighten Main Navigation & move "Currents" into "About"

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/aptos_client.test.ts
- ecosystem/typescript/sdk/src/token_client.test.ts
- ecosystem/typescript/sdk/src/token_client.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/helper.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/helper.ts
JSON txn submission interface is going to be deprecated from SDK. This PR updates the token client to use BCS txn submission interface.
Make sure all the tests still pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2596)
> Replace JSON txn submittion interface with BCS interface for token client

- consensus/src/persistent_liveness_storage.rs
- consensus/src/state_computer.rs
- execution/executor-types/src/lib.rs
- execution/executor/src/block_executor.rs
- execution/executor/src/components/block_tree/mod.rs
- execution/executor/src/fuzzing.rs
- execution/executor/src/tests/mod.rs
- execution/executor/tests/db_bootstrapper_test.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
- state-sync/storage-service/server/src/tests.rs
- storage/aptosdb/src/backup/backup_handler.rs
- storage/aptosdb/src/ledger_store/ledger_info_test.rs
- storage/aptosdb/src/ledger_store/mod.rs
- storage/aptosdb/src/lib.rs
- storage/backup/backup-cli/src/coordinators/backup.rs
- storage/storage-interface/src/lib.rs
- types/src/proof/accumulator/mod.rs
- types/src/proof/definition.rs
Instead of trying to fake it, the block executor now refuses to start when the ledger info doesn't match the latest transaction. An error will be returned to consensus and @zekun000 promises consensus will (in the end) switch to state sync to let it finish the sync.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2606)
> [storage] remove get_startup_info()

- crates/aptos-rosetta/src/account.rs
- crates/aptos-rosetta/src/types/requests.rs
- testsuite/smoke-test/src/rosetta.rs
As requested, metadata is required saying the sequence number as in here https://www.rosetta-api.org/docs/models/AccountBalanceResponse.html
Updated the current test for it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2594)
> [aptos-rosetta] Add sequence number to account balance lookups

- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_block_transactions_work.json
- sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_table_item_parsing_works.json
Currently the vote() function doesn't check for double checking until 2-3 other checks. Double voting is arguably more likely to happen than other validations so it can potentially save gas and fail earlier if we move the assertion to the top.
Existing unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2578)
> [Aptos Framework] [On-chain Governance] Shuffle assertion checks in aptos_governance::vote to allow earlier failures

- crates/aptos/src/move_tool/mod.rs
The new publishing flow should be the default now so we are getting some feedback how it works. The old flow is still reachable for a bit using `--legacy-flow`. Once we remove that flag, we should also remove the transaction type of module bundle publishing; at that point, no one can publish code unless going over `aptos_framework:code` module.
NA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2610)
> [code publishing] Make new flow the default

- api/goldens/v0/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- api/goldens/v1/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/framework/aptos-framework/sources/genesis.move
- sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_block_transactions_work.json
- sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_table_item_parsing_works.json
Currently the governance only stores the signer cap for 0x1. This change allows storing signer caps for multiple addresses under the on-chain governance's control.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2620)
> [Aptos Framework][Governance] Add a generic map to store signer caps for addresses under on-chain governance's control

- api/types/src/convert.rs
abort code is displayed as a decimal number now. Which is not friendly to use error::* functions to generate error code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2613)
> feat: make abort code readable

- sf-stream/src/tests/golden_output.rs
- sf-stream/src/tests/mod.rs
- sf-stream/src/tests/proto_converter_tests.rs
- sf-stream/src/tests/test_context.rs
Golden is causing merge conflicts due to changes between now and mainnet. Let's remove it for now and add it back later when the contracts are finalized. 
```
> cargo test
running 4 tests
test tests::proto_converter_tests::test_genesis_works ... ok
test tests::proto_converter_tests::test_block_transactions_work ... ok
test tests::proto_converter_tests::test_block_height_and_ts_work ... ok
test tests::proto_converter_tests::test_table_item_parsing_works ... ok
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2619)
> [Indexer] Remove golden from streamingfast tests

- api/src/poem_backend/accept_type.rs
Now if there is a BCS accept type, BCS will be returned.  Otherwise,
for any other combination of types, JSON will be returned.
Current tests
```
http://localhost:8080/v1/accounts/0x1
{"sequence_number":"0","authentication_key":"0x0000000000000000000000000000000000000000000000000000000000000001"}
```
```
// JSON is also accepted as JSON
$ curl -H"Accept: application/json" localhost:8080/v1
{"chain_id":4,"epoch":"4","ledger_version":"515","oldest_ledger_version":"0","ledger_timestamp":"1659831099801124","node_role":"validator"}%
// Text (Via chrome etc.). is JSON
$ curl -H"Accept: text/html" localhost:8080/v1
{"chain_id":4,"epoch":"4","ledger_version":"535","oldest_ledger_version":"0","ledger_timestamp":"1659831106374266","node_role":"validator"}%
// Any header is JSON
$ curl -H"Accept: …
```
> [api] Change accept type handling

- api/goldens/v0/aptos_api__tests__events_test__test_get_events_by_account_event_handle.json
- api/goldens/v1/aptos_api__tests__events_test__test_get_events_by_account_event_handle.json
- api/src/context.rs
- api/src/events.rs
- api/src/poem_backend/events.rs
- api/types/src/convert.rs
- api/types/src/lib.rs
- api/types/src/transaction.rs
without a version, events are of very limited use.
with a version, one can query the transaction that emitted the event and
the timestamp when that transaction was committed.
this makes it effectively possible to graph the entirety of a user
through events -- if events represent a canonical flow for the resources
they involve which should be true for Coin and Token.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2618)
> [api] expose versioned events for event specific APIs

- developer-docs-site/docs/cli-tools/aptos-cli-tool/index.md
- developer-docs-site/docs/cli-tools/aptos-cli-tool/using-a-local-testnet.md
Added a readme style guide for the local testnet.
TODO: Add a scenario based "I want to develop a module against a local testnet" guide.
https://github.com/gregnazario/aptos-core/blob/cli-guides/developer-docs-site/docs/cli-tools/aptos-cli-tool/using-a-local-testnet.md
Docs docs docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2626)
> [docs] Add Aptos CLI local testnet readme / guide

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/examples/typescript/bcs_transaction.ts
- ecosystem/typescript/sdk/examples/typescript/multisig_transaction.ts
- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/index.ts
The transaction_builder index file already re-exported stuff in namespaces, no need to add another layer.
```
cd ecosystem/typescript/sdk
yarn test
cd examples/typescript
yarn test
cd ../javascript
yarn test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2653)
> [SDK][TS] Re-expose BCS and builder items from root of module

- ecosystem/platform/server/config/routes.rb
Create redirect for attempting to access via www
- Will fix https errors
- Redirecting requests from a non-preferred domain is important because search engines consider URLs with and without “www” as two different websites. Without the redirect It creates a duplicate entry, which is not suitable for SEO.
Prepend url with www and ensure redirect is working.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2556)
> [community] Redirect www to non-www to avoid https conflicts

- mempool/src/core_mempool/transaction_store.rs
- mempool/src/counters.rs
This will help understand the duplication due to FN forwarding.
The counter code registration and use is straightforward.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2656)
> [mempool] add counter for duplicate idempotent txns

- Cargo.lock
- api/src/context.rs
- execution/executor-test-helpers/Cargo.toml
- execution/executor-test-helpers/src/integration_test_impl.rs
- sdk/src/types.rs
- storage/aptosdb/src/event_store/mod.rs
- storage/aptosdb/src/event_store/test.rs
- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/test_helper.rs
- storage/aptosdb/src/transaction_store/mod.rs
- storage/aptosdb/src/transaction_store/test.rs
- storage/backup/backup-cli/src/backup_types/state_snapshot/backup.rs
- storage/backup/backup-cli/src/backup_types/state_snapshot/manifest.rs
- storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs
- storage/backup/backup-cli/src/backup_types/tests.rs
- storage/backup/backup-cli/src/coordinators/backup.rs
- storage/backup/backup-cli/src/metadata/mod.rs
- storage/backup/backup-cli/src/metadata/view.rs
- storage/backup/backup-cli/src/metrics/backup.rs
- storage/storage-interface/src/lib.rs
- terraform/helm/fullnode/templates/backup.yaml
- terraform/helm/fullnode/values.yaml
- testsuite/smoke-test/src/storage.rs
- testsuite/smoke-test/src/test_utils.rs
- types/src/account_config/events/new_block.rs
now the state snapshot backup controller takes an epoch as the input and takes the snapshot at the end of it.
Since we guarantee at end of epochs a snapshot is persisted, this makes the backup coordinator work again.
existing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2551)
> [storage] backup-cli: state snapshots taken at epoch ending

- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/helm-values/aptos-node-values.yaml
- testsuite/forge/src/backend/k8s/helm-values/genesis-values.yaml
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/node.rs
- testsuite/forge/src/interface/node.rs
- testsuite/run_forge.sh
- testsuite/testcases/src/forge_setup_test.rs
- testsuite/testcases/src/lib.rs
- testsuite/testcases/src/partial_nodes_down_test.rs
- testsuite/testcases/src/state_sync_performance.rs
Resurrect the ability to start, stop (reboot), and clear the storage for `K8sNode`. This will help in getting the state sync performance tests back! (and other tests that require poking running nodes)
A few changes to how this works vs how it was done previously:
* `Node::stop` is now `async`, and guarantees that the process has completely stopped, rather than just issuing to the API that it will stop.
* Use the kube API directly, mostly to scale the underlying `StatefulSet`, rather than issuing calls to `kubectl` 
* When the `StatefulSet` status is unavailable, try to get the underlying `Pod` status. This will tell us whether things are `Pending` (e.g. sometimes indefinitely in case of autoscaler issue), etc.
Bonus:
* Also start to add back the ability to query metrics directly off of a …
> [forge] support K8SNode start,stop,clear_storage and metrics port

- CODEOWNERS
This PR adds code owners for consensus, storage and state-sync. Feel free to add more people in follow-up PRs, but let's start the party 🥳 
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2674)
> [Code Owners] Add code owners for consensus, storage and state-sync.

- developer-docs-site/docs/guides/guide-for-system-integrators.md
- developer-docs-site/docs/guides/index.md
- developer-docs-site/docs/guides/local-testnet-dev-flow.md
- developer-docs-site/docs/nodes/aptos-deployments.md
- developer-docs-site/docs/nodes/local-testnet/using-cli-to-run-a-local-testnet.md
- developer-docs-site/sidebars.js
There are two main correct dev flows:
1. devnet + sponsored version on npmjs (with each devnet we should say “use this SDK version”)
2. local testnet on main (or any commit on aptos-core really) and the SDK from that same commit (as in, not from npmjs)
Some devs mix and match the network and SDK in ways other than these two, which leads to incompatibilities. This PR is a start at making clear these options. As part of this, I add a guide for flow number 2.
There is still more work to do here, but this is a start.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2677)
> Add guide for the local testnet dev flow

- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-tests/src/executor.rs
The previous format only allowed for reading resources, this allows for
raw access as well as tables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2675)
> [move-tests] add better storage interface

- api/goldens/v0/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- api/goldens/v1/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/vm-genesis/src/lib.rs
- aptos-node/src/lib.rs
- crates/aptos-genesis/src/builder.rs
- crates/aptos-genesis/src/config.rs
- crates/aptos-genesis/src/lib.rs
- crates/aptos/src/genesis/mod.rs
- crates/aptos/src/genesis/tests.rs
- terraform/helm/genesis/templates/genesis.yaml
- terraform/helm/genesis/values.yaml
- testsuite/smoke-test/src/aptos_cli.rs
Reward rate and on chian governance params are currently hardcoded. This makes them configurable in genesis configurations. Reasonable defaults are also set for tests and local node setup.
Existing e2e, smoke tests and Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2641)
> [Genesis] Make rewards and governance params configurable and set reasonable defaults in tests

- .github/workflows/sdk-release.yaml
- ecosystem/typescript/sdk/README.md
This PR updates our CI such that we publish the TS SDK from the devnet branch. The instructions for how to do this are in the README.
Change pull_request_target to pull_request and see that the CI works (**update**, it does). For the push phase, we can test that with a new temporary push trigger once we're ready to make a release. Once we're good, I'll change it back to pull_request_target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2672)
> [SDK] Re-enable release steps in CI

- crates/aptos/src/common/types.rs
- crates/aptos/src/config/mod.rs
Fixes https://github.com/aptos-labs/aptos-core/issues/2642
Tested manually that CLI no longer is required to load full config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2685)
> [aptos-cli] Allow empty config in global config

- api/types/src/derives.rs
- execution/executor-test-helpers/Cargo.toml
Addressing https://github.com/aptos-labs/aptos-core/issues/2562. In short, we need to make sure the example ends up wrapped with strings.
This is a bit of a hack, the YAML generator should just wrap it in a string, or the stoplight UI should treat it as a string regardless of whether it has quotes around it (since type is string). But it works for now, the examples are only used for the UI / docs (visual inspection, nothing programmatic) so this should be okay.
```
$ cargo run -p aptos-openapi-spec-generator -- -f yaml | grep -A 8 HexEncodedBytes:
HexEncodedBytes:
type: string
format: hex
description: |
All bytes (Vec<u8>) data is represented as hex-encoded string prefixed with `0x` and fulfilled with
two hex digits per byte.
Unlike the `Address` type, HexEncodedBytes will not trim any …
```
> [API] Ensure hex strings are wrapped in quotes in the spec

- developer-docs-site/static/examples/typescript/package.json
This fixes the docs site examples for TS to work with the current devnet.
```
yarn first_transaction
yarn first_nft
yarn first_coin
yarn hello_blockchain
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2705)
> Fix TS examples in docs site

- crates/aptos/src/account/create.rs
- crates/aptos/src/account/fund.rs
- crates/aptos/src/common/utils.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/aptos_cli/account.rs
- testsuite/smoke-test/src/aptos_cli/validator.rs
- testsuite/smoke-test/src/rosetta.rs
- testsuite/smoke-test/src/smoke_test_environment.rs
*  cli tests (aptos_cli and rosseta) were flaky, because FundAccount CLI command didn't wait to finish, and because funding through fauced is two transactions - creating account and minting. Unit test waited for account to exist to assert balance. Under extreme load, those two transactions would be in a different block, and so test would fail.
* all CLI commands wait for completion - so making FundAccount do the same
* we really should be waiting on transactions - not on accounts and balances. so removed those functions from CliTestFramework, and made functions check for balance now. this way current test (without FundAccount waiting) fails consistently (even without load)
* and added assert_account_balance_now function that when accounts don't match, print more details on the …
> [smoke-tests][cli] Fix flaky CLI smoke tests using FundAccount through faucet

- types/src/account_config/events/new_block.rs
Seems like this issue slipped through from https://github.com/aptos-labs/aptos-core/pull/2582, we probably need to be testing with all feature permutations.
Before (from within `crates/aptos-rest-client`):
```
$ cargo build
warning: patch for `diesel` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
Blocking waiting for file lock on build directory
Compiling aptos-rest-client v0.0.0 (/Users/dport/a/core/crates/aptos-rest-client)
error[E0599]: no function or associated item named `new` found for struct `NewBlockEvent` in the current scope
--> crates/aptos-rest-client/src/lib.rs:403:47
|
403 | ...                   Ok(NewBlockEvent::new(
|                                         ^^^ function or …
```
> Make NewBlockEvent::new accessible without a feature

- testsuite/smoke-test/src/rosetta.rs
This is flaky, it's only been passing because of retries. This helps.
```
cargo nextest run --package smoke-test --test-threads 8 test_block --profile ci
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2723)
> Make test_block smoke test less flaky

- execution/executor-benchmark/src/main.rs
It works differently than I was expecting...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2731)
> [Fix] Remove "requires" in pruner flags for executor-benchmark.

- ecosystem/platform/server/app/components/button_component.rb
- ecosystem/platform/server/app/components/footer_component.html.erb
- ecosystem/platform/server/app/components/header_component.html.erb
- ecosystem/platform/server/app/form_builders/aptos_form_builder.rb
- ecosystem/platform/server/app/views/settings/profile.html.erb
- ecosystem/platform/server/tailwind.config.js
- Adjust `max-sm` breakpoint within tailwind.config.js as the specified size was not allowing for dropdown items to be clicked at any window size larger than this this
- Update Header / Footer ghost buttons to utilize button component (secondary scheme)
- Tweak ghost button styling
- Adjust font-weight as the browser was compensating for a **font-bold** which didn't exist for mono font, 
- Adjust Font smoothing (only when text is on colored background buttons converts to `subpixel-antialiased` as to not appear so thin due to the font-weight adjustment
- Utilize `ring` instead of `border` for ghost buttons and form fields
- Small tweaks to Profile Settings buttons - Any action to Delete Account is now red to signify danger. Initial "Delete Account" is now Tertiary style without background …
> [community] Update button styles, Change max-sm breakpoint size

- aptos-move/framework/aptos-stdlib/sources/simple_map.move
- aptos-move/framework/aptos-token/sources/property_map.move
- aptos-move/framework/aptos-token/sources/token.move
- testsuite/smoke-test/src/indexer.rs
- testsuite/smoke-test/src/nft_transaction.rs
Existing mutate logic allows users to put any arbitrary Property when mutating the propertyMap.
We should only allow mutating the properties that are already defined when creating the token. 
It allows users to bear the assumptions that all token with different property_version all have the same set of property keys
add a unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2673)
> [Token] Only update property in pre-define propertyMap

- Cargo.lock
- aptos-move/aptos-sdk-builder/Cargo.toml
- testsuite/generate-format/Cargo.toml
Duplicate identifiers for serde-reflection's git revision causes `cargo vendor` to break, causing my build tools to break.
Cargo build works. Check the `Cargo.lock` to see that the new lockfile is more sensible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2741)
> Ensure there is only one rev for serde-reflection

- crates/aptos-telemetry/src/build_information.rs
- docker/docker-bake-rust-all.hcl
- docker/rust-all.Dockerfile
Since #2512, we are now defining build environment variables in the post binary build stage in the `Dockerfile`, so these variables should be read at runtime. This commit changes from compile-time env resolution to runtime resolution.
Added unit test to verify that env variables are read properly if present.
`cargo test --lib`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2713)
> [aptos-telemetry] pull build env variables at runtime

- aptos-move/framework/aptos-token/sources/token.move
* Token mutations should be on the token in the owner account not the creator
* direct_deposit should not be public
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2756)
> [framework] cleanup some token code

- Cargo.lock
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/parallel_executor/mod.rs
- aptos-move/parallel-executor/Cargo.toml
- aptos-move/parallel-executor/src/errors.rs
- aptos-move/parallel-executor/src/executor.rs
- aptos-move/parallel-executor/src/proptest_types/bencher.rs
- aptos-move/parallel-executor/src/proptest_types/tests.rs
- aptos-move/parallel-executor/src/proptest_types/types.rs
- aptos-move/parallel-executor/src/task.rs
- aptos-move/parallel-executor/src/txn_last_input_output.rs
- aptos-move/parallel-executor/src/unit_tests/mod.rs
- types/src/access_path.rs
Adjusted existing tests, ensured ModuleReadWrite error is returned when module read and write paths intersect.
In a later diff: split large blocks into smaller chunks, in ParallelAptosVM.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2627)
> [Parallel Execution] Publishing support: Module Read & Write intersection and seq fallback

- crates/aptos-telemetry/src/build_information.rs
This println ends up printing all the time, which is weird e.g. `calling collect Err(NotPresent)`
Removed it accordingly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2746)
> [aptos-telemetry] Remove println

- crates/transaction-emitter-lib/src/emitter/mod.rs
- crates/transaction-emitter-lib/src/transaction_generator/account_generator.rs
0. Fix wrong address of the new account.
1. Use different rng for different generators.
Manually tested on Alden-net.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2733)
> [Txn-emitter] Fix account_generation.

- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/swarm.rs
we should check the right config for >1 nodes swarms, but this is a start
client.test_latest_events_and_transactions now starts swarm in 5s (instead of 15s)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2743)
> [smoke-tests] Speed up LocalSwarm startup 15s => 5s (remove statesync 10s wait time)

- crates/aptos/src/common/types.rs
In order to test things on existing database, we need to make all info in genesis to be deterministic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2724)
> [Genesis Tool] Expose --random-seed so forge can use it to generate keys in a deterministic way.

- Cargo.lock
- aptos-node/src/lib.rs
- config/src/config/state_sync_config.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/utils.rs
- state-sync/state-sync-v2/state-sync-driver/Cargo.toml
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver_factory.rs
- state-sync/state-sync-v2/state-sync-driver/src/lib.rs
- state-sync/state-sync-v2/state-sync-driver/src/metadata_storage.rs
- state-sync/state-sync-v2/state-sync-driver/src/notification_handlers.rs
- state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/driver_factory.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/metadata_storage.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mod.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/storage_synchronizer.rs
- testsuite/smoke-test/Cargo.toml
- testsuite/smoke-test/src/state_sync.rs
Note: 65% of this PR is just new unit tests 😱 
This PR takes the first step towards making fast sync crash fault tolerant (i.e., able to recover after a reboot while synchronizing state keys and values). To achieve this, the PR:
1. Adds a new persistent metadata storage for state sync (i.e., `state_sync_db`) that persists the sync progress to the local file system (similar to other persistent storage files, e.g., `consensus_db`).
2. Updates the bootstrapper to read from the persistent storage when handling reboots and restarting new data streams. This includes ensuring at least one item overlap in the state key/value chunks after reboots (as required by the snapshot receiver, 'cc @msmouse).
3. Updates the storage synchronizer to write to the persistent storage file when new state keys and …
> [State Sync] Make fast sync crash fault tolerant (Step 1)

- Cargo.lock
- crates/aptos/Cargo.toml
Bump for the upcoming devnet release
@sherry-x push this when we make a devnet cut.
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2770)
> [aptos-cli] Bump CLI version to 0.2.4

- terraform/aptos-node/aws/cluster.tf
- terraform/modules/eks/cluster.tf
Increase the default EKS worker node root volume size. We are running out of space when pulling large docker images
Apply to a test cluster and inspect the volume size: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2776)
> [tf][aws] increase root volume size

- api/src/context.rs
- config/src/config/storage_config.rs
- execution/executor-benchmark/src/main.rs
- storage/aptosdb/src/aptosdb_test.rs
- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/pruner/event_store/test.rs
- storage/aptosdb/src/pruner/ledger_pruner_manager.rs
- storage/aptosdb/src/pruner/pruner_manager.rs
- storage/aptosdb/src/pruner/state_pruner_manager.rs
- storage/aptosdb/src/pruner/state_store/test.rs
- storage/aptosdb/src/pruner/transaction_store/test.rs
- storage/storage-interface/src/lib.rs
There is a non-zero amount of time between requesting the oldest version
and making a second request to get that information.  This causes issues
where the data is already pruned at that point.  This should ensure that
there's at least a buffer for users.
We can improve the calculation of the buffer at a later time.
CI :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2768)
> [storage/api] Ensure oldest version provided to users can be queried

- Cargo.lock
- aptos-node/src/lib.rs
- config/src/config/mod.rs
- crates/aptos-telemetry-service/src/auth.rs
- crates/aptos-telemetry-service/src/context.rs
- crates/aptos-telemetry-service/src/custom_event.rs
- crates/aptos-telemetry-service/src/error.rs
- crates/aptos-telemetry-service/src/index.rs
- crates/aptos-telemetry-service/src/jwt_auth.rs
- crates/aptos-telemetry-service/src/lib.rs
- crates/aptos-telemetry-service/src/tests/auth_test.rs
- crates/aptos-telemetry-service/src/tests/test_context.rs
- crates/aptos-telemetry-service/src/types/auth.rs
- crates/aptos-telemetry-service/src/types/mod.rs
- crates/aptos-telemetry-service/src/types/telemetry.rs
- crates/aptos-telemetry-service/src/types/validator_set.rs
- crates/aptos-telemetry-service/src/validator_cache.rs
- crates/aptos-telemetry/Cargo.toml
- crates/aptos-telemetry/src/build_information.rs
- crates/aptos-telemetry/src/cli_metrics.rs
- crates/aptos-telemetry/src/constants.rs
- crates/aptos-telemetry/src/core_metrics.rs
- crates/aptos-telemetry/src/lib.rs
- crates/aptos-telemetry/src/metrics.rs
- crates/aptos-telemetry/src/network_metrics.rs
- crates/aptos-telemetry/src/sender.rs
- crates/aptos-telemetry/src/service.rs
- crates/aptos-telemetry/src/system_information.rs
This PR implements a sender to send telemetry to the telemetry web service in an authenticated way.
Run in one terminal `cargo run -p aptos-telemetry-service -- -f telemetry-service.yaml`
Run in another terminal: `cargo run -p aptos-node -- --test`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2763)
> [aptos-telemetry] telemetry service client integration

- storage/aptosdb/src/state_store/buffered_state.rs
- storage/aptosdb/src/state_store/mod.rs
- storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
- storage/aptosdb/src/state_store/state_snapshot_committer.rs
There is a bug caught by @grao1991 today that when async commit pipelined and the previous batch may be not committed yet, the current batch may start to merklize data and tries to read from the snapshot of the previous batch. We need another channel to sync this and make our code even more complicated :(
Added some logs in this PR too.
ut...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2783)
> [lazy_db] fix of unsynced snapshot

- api/doc/v1/spec.json
- api/doc/v1/spec.yaml
- api/src/poem_backend/runtime.rs
This ensures that the open API spec always uses /v1 when on the webpage
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2790)
> [api] Have OpenAPI spec html page use correct path

- config/src/config/storage_config.rs
https://serde.rs/container-attrs.html#default
This seems to work?
```
cat config/src/config/test_data/public_full_node.yaml 
base:
data_dir: "/opt/aptos/data"
role: "full_node"
waypoint:
from_file: "./waypoint.txt"
execution:
genesis_file_location: "./genesis.blob"
full_node_networks:
- discovery_method: "onchain"
listen_address: "/ip4/127.0.0.1/tcp/6180"
network_id: "public"
seeds:
{}
storage:
storage_pruner_config:
enable_state_store_pruner: false
api:
enabled: true
address: 127.0.0.1:8080
(venv)  greg@jiggy  /opt/git/aptos-core   fix-config ±  cargo run -p apto
s -- node run-local-testnet --config-path /opt/git/aptos-core/config/src/config/test_data/public_full_node.yaml
warning: patch for `diesel` uses the features mechanism. default-features and features will not take effect …
```
> [storage] Use default values for pruner when not provided

- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__on_chain_configs__drop_txn_after_reconfiguration_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__on_chain_configs__initial_aptos_version_version_4.exp
- aptos-move/framework/aptos-framework/sources/stake.move
- Rearranged the rewards formula in the stake module to avoid the arithmetic overflow and minimize the rounding error
cargo test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2722)
> [Stake] Rearranged the rewards formula in the stake module

- aptos-move/framework/aptos-token/sources/token_coin_swap.move
When exchange token with coin, there has a error when token royalty denominator is 0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2782)
> [Token] fixed calc error when token royalty denomintor is zero

- api/doc/v1/spec.html
- developer-docs-site/docusaurus.config.js
Minor fixes. Next time when the API spec gets into the binary, it will have the correct title, I think. 
@banool The published doc version says "v0.1.0" still, even though the spec.yaml has the correct version. Do you know what might be going on?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2817)
> [Docs] Fixing nav bar link in the docs and window title for the spec.

- aptos-move/framework/aptos-framework/sources/bucket_table.move
- aptos-move/framework/aptos-stdlib/sources/hash.move
- aptos-move/framework/move-stdlib/sources/hash.move
- aptos-move/framework/src/natives/hash.rs
- aptos-move/framework/src/natives/mod.rs
@vgao1996 requested to fix the missing gas metering.
Also, there are some potential gas metering problems in the native Rust code AFAICT due to the use of the ? operator. @zekun000 and @vgao1996 please take a look at the `TODO`'s in the changes.
Oh, and I tried moving `sip_hash` into `aptos-stdlib` (as per the TODO) but had a naming conflict because both `std` and `aptos_std` are at 0x01, I think.
After fixing that by renaming `aptos_std::hash` to `aptos_std::hashing`, I still had a problem with the `test_genesis_e2e_flow` test, which AFAICT publishes Move modules in the genesis block (I think). So I couldn't move it.
If you tell me how to fix that I can move it to `aptos-stdlib`, which maybe we should move to a new address, to avoid future naming conflicts?
- - - …
> [move] add gas metering for SipHash

- api/src/context.rs
- api/src/poem_backend/blocks.rs
- storage/aptosdb/src/lib.rs
- storage/storage-interface/src/lib.rs
To find the block corresponding to a transaction, this provides the API for it.
```
$ curl localhost:8080/v1/blocks/by_version/1
{"block_height":"1","block_hash":"0x380029b65e0db2311f9aa9c3fdb92207ebc201873cfe141f9f50f4c66d6cabbd","block_timestamp":"1660247629760032","first_version":"1","last_version":"1","transactions":null}%
$ curl 'localhost:8080/v1/blocks/by_version/1?with_transactions=false' 
{"block_height":"1","block_hash":"0x380029b65e0db2311f9aa9c3fdb92207ebc201873cfe141f9f50f4c66d6cabbd","block_timestamp":"1660247629760032","first_version":"1","last_version":"1","transactions":null}%
$ curl 'localhost:8080/v1/blocks/by_version/1?with_transactions=true' 
{"block_height":"1","block_hash":"0x380029b65e0db2311f9aa9c3fdb92207ebc201873cfe141f9f50f4c66d6cabbd","block_timestamp":"1660247 …
```
> [api] Add get block by version

- api/goldens/v0/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- api/goldens/v1/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- aptos-move/aptos-gas/src/transaction.rs
- aptos-move/e2e-testsuite/src/tests/verify_txn.rs
- config/src/config/api_config.rs
- vm-validator/src/unit_tests/vm_validator_test.rs
This `bumps max_transaction_size_in_bytes` up to 6 MB to allow larger transactions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2829)
> [gas] bump max_transaction_size_in_bytes to 6 MB

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/src/aptos_client.ts
- ecosystem/typescript/sdk/src/util.test.ts
- ecosystem/typescript/sdk/src/util.ts
It'll be annoying for users to update the URLs for nodes, this PR makes it that we add the `v1` if you don't have it. This makes it easier for new API versions in the future too.
I removed `/v1` from the configured node URL for the testing and saw that the tests all passed:
```
yarn test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2837)
> [TS][SDK] Add /v1 if missing automatically

- api/src/poem_backend/runtime.rs
- api/src/set_failpoints.rs
- crates/aptos-faucet/src/lib.rs
- crates/aptos-faucet/src/main.rs
- crates/aptos-rest-client/src/faucet.rs
- crates/aptos-rest-client/src/lib.rs
- crates/aptos-rest-client/src/types.rs
- crates/aptos/src/common/init.rs
- crates/aptos/src/common/types.rs
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/local/node.rs
- testsuite/smoke-test/src/rest_api.rs
- testsuite/smoke-test/src/rosetta.rs
This PR switches over all Rust tooling, including the REST client, the smoke tests, and forge, to use the v1 API.
Smoke tests:
```
cargo nextest run --package smoke-test --test-threads 8
```
Other CI tests:
```
cargo nextest run --profile ci --workspace --exclude smoke-test --exclude backup-cli --exclude testcases
```
Manual CLI testing. I tested that these all work as expected:
```
cargo run -p aptos -- account create --use-faucet --faucet-url http://localhost:8081 --url http://localhost:8080/v1 --private-key `yq .profiles.default.private_key < ~/.aptos/config.yaml` --account `yq .profiles.default.account < ~/.aptos/config.yaml`
cargo run -p aptos -- account transfer --url http://localhost:8080 --account `yq .profiles.default.account < ~/.aptos/config.yaml` --amount 10
cargo run -p aptos …
```
> Switch Rust tooling over to v1 API

- crates/aptos/src/config/mod.rs
```
cargo run -p aptos -- node run-local-testnet --with-faucet
warning: patch for `diesel` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
Compiling aptos v0.2.4 (/opt/git/aptos-core/crates/aptos)
Finished dev [unoptimized + debuginfo] target(s) in 26.22s
Running `target/debug/aptos node run-local-testnet --with-faucet`
Building genesis with 1 validators. Directory of output: "/opt/git/aptos-core/.aptos/testnet"
Log file: "/opt/git/aptos-core/.aptos/testnet/validator.log"
Test dir: "/opt/git/aptos-core/.aptos/testnet"
Aptos root key path: "/opt/git/aptos-core/.aptos/testnet/mint.key"
Waypoint: 0:baf2610e2c80c28204b22f116f15341a952b82cdd2556b685c772b4867bf2c38 …
```
> [aptos-cli] Use current directory for workspace .aptos if it doesn't exist

- crates/aptos/src/config/mod.rs
Cherry pick of (#2845)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2847)
> [aptos-cli] Use current directory for workspace .aptos if it doesn't exist (#2845)

- README.md
CircleCI was removed in https://github.com/aptos-labs/aptos-core/commit/be3936ea1a5aec5f9e67f327416c09a695d15497
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2830)
> Replace CircleCI badge with Github

- ecosystem/platform/server/app/helpers/application_helper.rb
- ecosystem/platform/server/test/controllers/leaderboard_controller_test.rb
Fixes this error:
```
NoMethodError
undefined method `split' for #<ActionController::Parameters {"$foo"=>"1"} permitted: false>
(params.fetch(:sort, nil).presence || '').split(',').map do |attr|
^^^^^^
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2808)
> [community] Fix error when sort param is malformed.

- crates/aptos-logger/src/macros.rs
- mempool/src/core_mempool/mempool.rs
- mempool/src/shared_mempool/coordinator.rs
- mempool/src/shared_mempool/runtime.rs
- mempool/src/shared_mempool/types.rs
Removed where huge vectors of transaction (summaries) are logged.
For the snapshot, made a check to check log level while also downgrading to trace.
Run existing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2846)
> [mempool] avoid excessive logging (snapshot, excluded txns) except at trace level

- Cargo.lock
- consensus/src/liveness/leader_reputation_test.rs
- crates/aptos-rest-client/src/lib.rs
- crates/aptos/Cargo.toml
- crates/aptos/src/node/analyze/analyze_validators.rs
- crates/aptos/src/node/analyze/fetch_metadata.rs
- crates/aptos/src/node/analyze/mod.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/aptos_cli/validator.rs
- testsuite/smoke-test/src/client.rs
Adding utilities to analyze validator performance, based on accessing live on-chain data 
Fastest to run a full node locally, and connecting cli to it.
Currently fetching from all transactions. We can fetch create API for just metadata transactions and/or fetch from BigQuery, if this is too slow for people. When we run loadtest, and BlockMetadata transactions are not the majority, it does slow down. 
Test Plan:
cargo run -p aptos -- node analyze-validator-performance --analyze-mode=all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2364)
> [cli][consensus] Add analyze-validator-performance to node cli

- Cargo.lock
- api/Cargo.toml
- api/src/poem_backend/log.rs
- api/types/Cargo.toml
- config/Cargo.toml
- crates/aptos-openapi/Cargo.toml
- ecosystem/node-checker/Cargo.toml
An awesome change was just landed in Poem that gives access to the operation ID, so we don't have to log by path anymore (which wasn't working): https://github.com/poem-web/poem/issues/351. This PR makes our code use this new feature.
TBA, I need to chat with Brian to figure out how to make sure this is working properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2781)
> [API] Log per-endpoint metrics based on operation_id

- .github/workflows/continuous-e2e-tests.yaml
Make the workflow name a little more clear
Try out the new chaos testing suite (including network loss)
Try out the new cluster as well running k8s v 1.23 fresh off the presses
Test plan:
push branch and dispatch a workflow, however it cannot be dispatched until it lands :upside_down_smile:
Worst case it breaks continuous job, but that is easy to fix because after its in main i can test it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2879)
> [forge] Rename workflow, try out chaos suite, new cluster

- ecosystem/web-wallet/src/core/queries/account.ts
The wallet extension wasn't building properly due to this eslint error.
``` 
./aptos-core/ecosystem/web-wallet/src/core/queries/account.ts
57:1  error  This line has a length of 108. Maximum allowed is 100  max-len
```
This PR uses the optional chaining operator to fix the error and eliminate the ternary.
Build the wallet extension
Install in chrome, Brave, Firefox and any other supported browsers
Make sure coin amount queries work properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2458)
> Fix Wallet build with JS optional operator

- Cargo.lock
- testsuite/forge-cli/src/main.rs
- testsuite/forge-test-runner-template.yaml
- testsuite/forge/Cargo.toml
- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/constants.rs
- testsuite/forge/src/backend/k8s/helm-values/aptos-node-values.yaml
- testsuite/forge/src/backend/k8s/kube_api.rs
- testsuite/forge/src/backend/k8s/mod.rs
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/k8s/stateful_set.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/swarm.rs
- testsuite/forge/src/runner.rs
- testsuite/run_forge.sh
- testsuite/testcases/src/compatibility_test.rs
- testsuite/testcases/src/lib.rs
Give Forge k8s the ability to upgrade validator StatefulSet image tags, which lets us write tests that roll out a new image tag upgrade across the cluster, while maintaining backwards compatibility.
Give Forge k8s the ability to upgrade validator StatefulSet image tags. This can be invoked via a a test or via the command line. For example, you can now do:
```
$ cargo run -p forge-cli -- operator set-node-image-tag \
--image-tag 5da07eed1df564a0b28b1183a6ea32515b9af16e \
--namespace forge-rustielin \
--stateful-set-name aptos-node-28-validator \
--container-name validator
```
Under the hood, we're just invoking `kubectl set image`, and then running a healthcheck against the node.
Also bring back the `compat` test, which runs with a lower number of validators (5), since this test is only …
> [forge] resurrect set image tag

- ecosystem/typescript/sdk/README.md
Explicitly call out that:
Public SDK is pinned to devnet. SDK from main branch works with local network
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2848)
> doc: info about how to use SDK with devnet and local network

- crates/aptos-faucet/src/main.rs
- crates/aptos-rest-client/src/faucet.rs
The regular client is async, so to use the faucet client we jump through all kinds of hoops with blocking calls and whatnot. This PR just makes it async to fix all those problems.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2866)
> Make FaucetClient async

- terraform/helm/k8s-metrics/values.yaml
- testsuite/forge/src/backend/k8s/cluster_helper.rs
Tests timing out before they should. This makes sure we wait sufficiently long (~22 min) for the cloud provider backing Forge clusters to provision machines. The worst case is when we're spinning up from idle or if there is a burst of additional required compute.
We will retry exponentially until a max of 1 min, and then just retry every 1 min until a threshold 
Did some math.
```
>>> [min(5*2**i, 60) for i in range(25)]
[5, 10, 20, 40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2908)
> [forge] tune the timeout for waiting for nodes provisioning

- api/doc/v0/openapi.yaml
- api/goldens/v0/aptos_api__tests__invalid_post_request_test__test_invalid_payload_data_type.json
- api/goldens/v0/aptos_api__tests__invalid_post_request_test__test_invalid_payload_type.json
- api/goldens/v0/aptos_api__tests__invalid_post_request_test__test_invalid_script_function_function_id.json
- api/goldens/v0/aptos_api__tests__invalid_post_request_test__test_invalid_type_argument_data_type.json
- api/src/tests/test_context.rs
- api/src/tests/v0/invalid_post_request_test.rs
- api/src/tests/v1/invalid_post_request_test.rs
- aptos-move/aptos-vm/src/aptos_vm_impl.rs
- aptos-move/aptos-vm/src/errors.rs
- developer-docs-site/docs/concepts/basics-txns-states.md
- developer-docs-site/static/examples/python/first_transaction.py
- developer-docs-site/static/examples/rust/first_transaction/src/lib.rs
- documentation/specifications/move_adapter/README.md
- ecosystem/indexer-server/doc/openapi.yaml
- ecosystem/indexer-server/typescript/src/openapi-schema.ts
- ecosystem/typescript/sdk/src/aptos_client.ts
This is an artifact from Diem time and no longer relevant - Aptos only has one gas currency (APT).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2902)
> [Framework][API] Remove the deprecated gas_currency_code field

- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
FAILURE proving 1 modules from package `debug-move-example` in 0.369s
{
"Error": "Move Prover failed: No boogie executable set.  Please set BOOGIE_EXE"
}
address #2898
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2904)
> [aptos] expose prover error

- crates/aptos/src/account/create.rs
- crates/aptos/src/account/create_resource_account.rs
- crates/aptos/src/account/fund.rs
- crates/aptos/src/account/list.rs
- crates/aptos/src/account/mod.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/config/mod.rs
- crates/aptos/src/genesis/git.rs
- crates/aptos/src/genesis/keys.rs
- crates/aptos/src/genesis/mod.rs
- crates/aptos/src/governance/mod.rs
- crates/aptos/src/lib.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/op/key.rs
CLI information is now much more consistent
Manual testing, it's all docs
Example:
```
./target/debug/aptos --help
aptos 0.2.4
Aptos Labs <opensource@aptoslabs.com>
Command Line Interface (CLI) for developing and interacting with the Aptos blockchain
USAGE:
aptos <SUBCOMMAND>
OPTIONS:
-h, --help       Print help information
-V, --version    Print version information
SUBCOMMANDS:
account       Tool for interacting with accounts
config        Tool for interacting with configuration of the Aptos CLI tool
genesis       Tool for setting up an Aptos chain Genesis transaction
governance    Tool for on-chain governance
help          Print this message or the help of the given subcommand(s)
info          Show build information about the CLI
init          Tool to initialize current directory for …
```
> [aptos-cli] Improve documentation consistency

- network/src/protocols/health_checker/mod.rs
Resetting HC failure count on ingress HC request
1. *For testing only*, don't reply to incoming HC Pings.
2. Check logs to make sure there are no discinnects
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2910)
> [Networking HC] Reseting HC failure count on ingress HC request

- developer-docs-site/static/examples/typescript/hello_blockchain.ts
Word `module` was incorrectly written as `moudle`. This PR fixes it :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2927)
> Fix "moudle" typo

- aptos-move/e2e-tests/src/account.rs
- aptos-move/framework/aptos-framework/sources/account.move
Two cleanup commits
* Remove dead code from account.rs
* Make CoinStore and Account resource in the move tests more sensible... unless you like archaic serialization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2920)
> Cleanup move tests and account code

- ecosystem/typescript/sdk/src/aptos_client.test.ts
Fixing this broken test. I previously disabled it bc it was broken. Positional arguments of the same type were in the wrong order, classic.
```
yarn test -t 'submits multiagent transaction'
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2880)
> Fix multiagent txn test in TS SDK

- .github/workflows/sdk-release.yaml
This makes the sdk-release CI run on our own machines and updates it so that'll work. More context in the comments in the PR.
Run the CI with pull_request instead of pull_request_target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2955)
> Run sdk-release on high-perf-docker with correct volume usage

- .github/workflows/sdk-release.yaml
https://github.com/aptos-labs/aptos-core/pull/2955 worked in the PR but not on main. I'm investigating why and fixing it in this PR.
Same as in https://github.com/aptos-labs/aptos-core/pull/2955.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2957)
> Make sdk-release work on high-perf-docker

- state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/storage_synchronizer.rs
- storage/aptosdb/src/backup/restore_handler.rs
- storage/aptosdb/src/backup/restore_utils.rs
- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
- storage/aptosdb/src/pruner/state_store/mod.rs
- storage/aptosdb/src/pruner/utils.rs
- storage/aptosdb/src/state_store/state_store_test.rs
- storage/storage-interface/src/lib.rs
- testsuite/smoke-test/src/state_sync.rs
During the fast sync process, we need to perform three tasks once all state keys/values have been restored to storage: (i) finalize the sync by writing the transaction information to storage; (ii) save the newly verified epoch ending ledger infos to storage; and (iii) delete the genesis transaction. This PR updates the three operations to occur atomically. This prevents crashes from causing storage to end up in an invalid state (e.g., if the node crashes between step (i) and (ii)). With this, fast sync should be mostly* crash fault tolerant.
Notes:
- To achieve this, I've had to refactor a bunch of code so that we can pass in an existing change set to various functions (so that all storage alterations can be committed atomically), including updating the pruners.
*I say mostly, because …
> [Storage] Make state snapshot finalization atomic.

- .github/workflows/build-images.yaml
Main is failing a lot due to preemption, lets rely on continuous instead
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2965)
> [forge] Stop running forge on main, rely on continuous

- api/goldens/v0/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- api/goldens/v1/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- api/goldens/v1/aptos_api__tests__blocks_test__test_get_genesis_block_by_version.json
- aptos-move/framework/aptos-framework/sources/coin.move
- aptos-move/framework/aptos-framework/sources/managed_coin.move
Make decimals a u8. There are 20 digits in u64, and 39 in a u128: u64 is a bit much
Existing tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2935)
> [framework] Adjust coin module decimal type

- consensus/consensus-types/src/block.rs
- consensus/consensus-types/src/block_data.rs
- consensus/consensus-types/src/block_test.rs
- consensus/consensus-types/src/block_test_utils.rs
- consensus/consensus-types/src/common.rs
- consensus/safety-rules/src/safety_rules.rs
- consensus/safety-rules/src/test_utils.rs
- consensus/safety-rules/src/tests/suite.rs
- consensus/src/block_storage/block_store.rs
- consensus/src/block_storage/block_store_test.rs
- consensus/src/block_storage/sync_manager.rs
- consensus/src/epoch_manager.rs
- consensus/src/experimental/buffer.rs
- consensus/src/experimental/buffer_manager.rs
- consensus/src/experimental/tests/execution_phase_tests.rs
- consensus/src/experimental/tests/test_utils.rs
- consensus/src/liveness/proposal_generator.rs
- consensus/src/liveness/round_state.rs
- consensus/src/liveness/unequivocal_proposer_election_test.rs
- consensus/src/network_tests.rs
- consensus/src/round_manager_test.rs
- consensus/src/test_utils/mock_state_computer.rs
- consensus/src/test_utils/mod.rs
We only fallback to state sync when ordered root falls behind, and we'll hit the problem of ordering phase
can catch up but keep queueing more transactions in the buffer manager, this commit ensures that we also fallback to state sync.
Also update a few log levels to reduce noise as well as increase visibility
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2894)
> [consensus] fallback to state sync if commit root falls behind too much

- Cargo.toml
Remove warning because features can't be in the patches
Before
```
cargo run -p aptos
warning: patch for `diesel` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
Compiling aptos-types v0.0.3 (/opt/git/aptos-core/types)
```
After
```
cargo run -p aptos
Compiling aptos-types v0.0.3 (/opt/git/aptos-core/types)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2947)
> [deps] Remove diesel patch warning

- .github/workflows/build-images.yaml
Last time this accidentally disable whole build workflow!
This time just dont schedule forge on main if the branch name is main
Test Plan: this feels fairly not testable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2971)
> [forge] Dont schedule forge on main push take 2

- crates/aptos-rest-client/src/lib.rs
- testsuite/smoke-test/src/rosetta.rs
I spent a bunch of time trying to figure out why Rosetta wasn't working.  But I finally got it working after I realized `version` != `ledger_version`.  This will need to be cleaned up tomorrow, but for now, we have a test that actually tests full functionality of Rosetta (similar to the Rosetta CLI), but with the constraints that we actually know how long it will run for.
This adds the test that checks all of it in Rosetta.
1. Makes a bunch of valid & invalid transfers
2. Tracks creation of accounts & transfers
3. Checks balances afterwards to see if they're correct
4. Validates blocks, transactions, and operations correctness.
5. Has almost excessive expect & assert messages
- - - …
> [aptos-rest-client/smoke-test] Fix aptos rest client to use correct version & add rosetta test

- ecosystem/typescript/sdk/src/aptos_client.test.ts
- ecosystem/typescript/sdk/src/aptos_client.ts
- ecosystem/typescript/sdk/src/faucet_client.test.ts
- ecosystem/typescript/sdk/src/faucet_client.ts
- ecosystem/typescript/sdk/src/util.test.ts
To avoid confusion, we don't default the SDK tests against devnet anymore. Developers and contributors should explicitly provide the node and faucet URLs. 
Added tests to verify correct messages are thrown.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2769)
> fix: remove default devnet urls for TS SDK tests

- .github/workflows/continuous-e2e-tests.yaml
Lower the thresholds to where they currently are for test duration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2973)
> [forge] Lower continuous chaos thresholds

- storage/aptosdb/src/lib.rs
- storage/aptosdb/src/pruner/db_pruner.rs
- storage/aptosdb/src/pruner/ledger_pruner_manager.rs
- storage/aptosdb/src/pruner/ledger_pruner_worker.rs
- storage/aptosdb/src/pruner/pruner_manager.rs
- storage/aptosdb/src/pruner/state_pruner_manager.rs
- storage/aptosdb/src/pruner/state_pruner_worker.rs
- storage/aptosdb/src/pruner/state_store/test.rs
- Instead of using a channel to send pruning commands to the pruner threads, periodically prune states and ledgers.
- Added a config for the pruning intervals.
- Existing UTs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2832)
> [storage][pruner] Run pruners periodically instead of using channels.

- crates/aptos/src/account/create.rs
- crates/aptos/src/account/fund.rs
- crates/aptos/src/account/mod.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/lib.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/stake/mod.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/aptos_cli/account.rs
- testsuite/smoke-test/src/aptos_cli/validator.rs
- Added owner-related CLI functions 
- Added AIT3 e2e flow for creating owner/validator/voter accounts and delegating everything appropriately
- separated out "stake owner" related commands into "stake" subcommand, leaving "node" subcommand for validator node operations
- change transfer CLI to use account_transfer (so that account gets created if not present already)
- deduped CreateAccount +faucet and FundAccount into FundWithFaucet, and made explicit testing APIs which use faucet, so that we can create more end-to-end flows be realistic - i.e. without faucet.
- updated register_validator_candidate into initialize_validator. 
- named initialize_stake_owner the CLI call (instead of initialize_owner_only) to be clearer, I would recommend updating move accordingly
Added e2e test
Will sync …
> [cli][delegation] Add owner-relatd CLI functions and AIT3 flow e2e test

- crates/aptos-genesis/src/config.rs
- crates/aptos/src/genesis/git.rs
- crates/aptos/src/genesis/keys.rs
- crates/aptos/src/genesis/mod.rs
- crates/aptos/src/genesis/tests.rs
1. Add path support for git client, so we can have folders with multiple files in them easily
2. Add a `generate-layout-template` command so that users stop being confused about what fields they need to fill out with a template of the fields.
The only question is if I add these defaults will people remember to change them.
```
$ aptos genesis generate-layout-template
"layout.yaml" already exists, are you sure you want to overwrite it? [yes/no] >
yes
{
"Result": "Success"
}
$ cat layout.yaml 
---
root_key: ~
users: []
chain_id: 4
allow_new_validators: false
epoch_duration_secs: 86400
is_test: true
min_stake: 0
min_voting_threshold: 0
max_stake: 18446744073709551615
recurring_lockup_duration_secs: 86400
required_proposer_stake: 0
rewards_apy_percentage: 1
voting_duration_secs: 1 …
```
> [aptos-cli] Cleanup genesis layout

- Cargo.lock
- aptos-move/parallel-executor/Cargo.toml
- aptos-move/parallel-executor/src/proptest_types/tests.rs
- aptos-move/parallel-executor/src/proptest_types/types.rs
This test catches both false overwrite (https://github.com/aptos-labs/aptos-core/pull/2916) and prior to that, deadlock on early abort optimization (https://github.com/aptos-labs/aptos-core/pull/2876). Verified in earlier repo states, and also verified it passes with current Head.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2925)
> [Parallel Execution] Combinatorial test to check module intersection

- ecosystem/platform/server/app/assets/stylesheets/application.tailwind.css
This adds some scroll padding to compensate for the sticky header, so that when the browser scrolls to an element (e.g. when a form input is invalid on submit) it's not covered beneath the header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2960)
> [community] Don't cover anchors with sticky header.

- crates/aptos/src/common/types.rs
- crates/aptos/src/genesis/keys.rs
- crates/aptos/src/genesis/tests.rs
- crates/aptos/src/governance/mod.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/test/mod.rs
This allows for operators to be different than owners, but
still use the files that exist today.
```
$ ./target/debug/aptos genesis generate-keys --owner-address 0xDEADBEEF
{
"Result": [
"/opt/git/aptos-core/private-keys.yaml",
"/opt/git/aptos-core/validator-identity.yaml",
"/opt/git/aptos-core/validator-full-node-identity.yaml"
]
}
$ cat /opt/git/aptos-core/validator-identity.yaml 
---
account_address: 00000000000000000000000000000000000000000000000000000000deadbeef
account_private_key: "***"
consensus_private_key: "***"
network_private_key: "***"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2981)
> [aptos-cli] Allow owner to be different when generating validator keys

- Cargo.lock
- api/types/src/error.rs
- crates/aptos-rest-client/Cargo.toml
- crates/aptos-rest-client/src/lib.rs
With the `oai` annotation it was serializing this data with snake case, but the REST client was using serde to deserialize it, which did not have the snake case annotation. This PR fixes it in two ways:
- Make the REST client use the correct deserialization function (the counterpart to how it was serialized), as provided by the derive from Poem.
- Make it possible to deserialize it with serde by adding the snake case annotation (so it works elsewhere if it is being used).
See this issue for more on this problem: https://github.com/aptos-labs/aptos-core/issues/3014.
```
cargo run -p aptos --release -- node run-local-testnet --with-faucet --faucet-port 8081 --force-restart --assume-yes
```
```
cargo run -- --pg-uri "postgresql://localhost/postgres" --node-url "http://localhost:8080" …
```
> Make AptosErrorCode compatible with serde deserialization

- crates/aptos/src/governance/mod.rs
- crates/aptos/src/move_tool/mod.rs
Added two CLI sub-commands for governance.
`prepare-script` takes in a script package path, compiles the script, and prints out the script hash
`run-script` can submit a compiled script to the blockchain.
Tested with a modified version of moon_coin package. 
For `prepare-script`:
For `run-script`:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3009)
> [cli] Governance subcommands for preparing and exeucting scripts

- state-sync/aptos-data-client/src/aptosnet/state.rs
- state-sync/aptos-data-client/src/aptosnet/tests.rs
- state-sync/storage-service/types/src/requests.rs
- state-sync/storage-service/types/src/responses.rs
This PR updates the Aptos Data Client to only consider peers eligible for an optimistic data fetch (i.e., single subscription request) if the peer is within some delta of the synced version of the client. This prevents the case where a node sends one of these requests to a peer that has fallen behind, and thus will wait for the request to timeout (5 seconds) before checking if there's new data available in the rest of the network. 
Note: we saw this behaviour in `devnet`, where a validator got stuck, and its VFN would get up-to-date via fallback peers and then send the subscription request to the validator (because it is considered a priority peer). But, because the validator was behind the VFN, the VFN would wait for 5 seconds before being to request data from the fallback peers.
Added a …
> [Aptos Data Client] Make optimistic fetch take into account peer state.

- terraform/helm/fullnode/files/fullnode.yaml
- terraform/helm/fullnode/values.yaml
Add couple option to run fullnode with different profile.
- to run fullnode with full transaction history
- to run fullnode with full transaction execution 
Apply changes to a PFN cluster
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2882)
> [helm] update fullnode config

- api/src/log.rs
This single line was contributing to the vast majority of log lines.
Rely on land-blocking forge test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3034)
> [api] reduce api log rate to 1 per second

- types/src/network_address/mod.rs
This was blocking cargo install for some reason
When running `cargo install aptos`
```
Compiling move-deps v0.0.1 (/Users/greg/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/157a3f6/aptos-move/move-deps)
Compiling aptos-types v0.0.3 (/Users/greg/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/157a3f6/types)
error[E0433]: failed to resolve: could not find `private` in `anyhow`
--> types/src/network_address/mod.rs:487:21
|
487 |             anyhow::private::Err(ParseError::EmptyProtocolString)
|                     ^^^^^^^ could not find `private` in `anyhow`
For more information about this error, try `rustc --explain E0433`.
```
TBD once this is in main
- - - …
> [types] Remove private usage of anyhow

- types/src/chain_id.rs
Making the accepted names be case insensitive for those who want to not type all caps network names / make them lowercase.
Current tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3041)
> [chain-id] Make chain id inputs case insensitive

- Cargo.lock
- api/test-context/src/test_context.rs
- crates/aptos-genesis/src/builder.rs
- crates/aptos-genesis/src/config.rs
- crates/aptos-genesis/src/keys.rs
- crates/aptos-genesis/src/test_utils.rs
- crates/aptos/src/genesis/git.rs
- crates/aptos/src/genesis/keys.rs
- crates/aptos/src/genesis/mod.rs
- crates/aptos/src/genesis/tests.rs
- terraform/helm/genesis/files/genesis.sh
Now you can have voters and operators in genesis.  Owner is the validator's address, and operator and voter is used for the other addresses.
There's an E2E test for this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3023)
> [aptos-genesis] Allow voters and operators to be split from owner in genesis

- ecosystem/platform/server/app/controllers/users/sessions_controller.rb
- ecosystem/platform/server/app/views/devise/sessions/new.html.erb
Initial template for a dedicated Sign in page no longer reliant on AIT layout
Manually test "Sign in" links and verify the following layout: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3026)
> [community] Dedicated layout for user Sign in

- crates/aptos/src/account/create.rs
- crates/aptos/src/account/create_resource_account.rs
- crates/aptos/src/account/fund.rs
- crates/aptos/src/account/list.rs
- crates/aptos/src/account/transfer.rs
- crates/aptos/src/common/init.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/config/mod.rs
- crates/aptos/src/genesis/git.rs
- crates/aptos/src/genesis/keys.rs
- crates/aptos/src/genesis/mod.rs
- crates/aptos/src/governance/mod.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/op/key.rs
- crates/aptos/src/stake/mod.rs
- crates/aptos/src/test/mod.rs
* fixes up readability, moving flattens to the bottom (no particular order)
* Adds documentation for undocumented commands and arguments
* Ensures profiles can be used anywhere that takes an AcccountAddress
* Ensures inputs are consistently read across the board 
Note:
I did not touch the Move CLI commands so that they don't have merge conflicts.  Will do later.
Current tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3049)
> [aptos-cli] Make input args consistent and commented

- developer-docs-site/docs/nodes/ait/node-requirements.md
- developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md
Discussed offline. tldr, if we say you need 32 GiB of RAM, people will get 32GB instances and then be confused when they're 2GiB short of the requirement.
(My editor also removed random whitespace).
Eyes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3061)
> Change GiB to GB for node requirements

- crates/aptos-logger/src/aptos_logger.rs
- crates/aptos-logger/tests/logger.rs
- crates/aptos-logger/tests/logger_custom_format.rs
- crates/aptos-logger/tests/tracing_translation_tests.rs
- println is both unbufferd and takes a lock on stdout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2962)
> [Aptos logger] Adding buferred log writes

- crates/aptos/src/common/init.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/config/mod.rs
A lot of the use cases I've seen about people copying their address
outside is hard when you can't show the available profiles.  This
will show the config without the private keys for ease of use.
Also uses a BTreeMap now for stability purposes
```
aptos config show-profiles
{
"Result": {
"greg": {
"has_private_key": true,
"public_key": "0xfe6276f3440264cc72af48ca5a160cd37c8b113ad17e0e860b59bfae9ec2baea",
"account": "a1a52c66dcc30fa6536bf1490d9a9ed83437c3063d063fb5560ef4e1764b420e",
"rest_url": "https://my-unknown-url.xyz/"
},
"operator": {
"has_private_key": true,
"public_key": "0x1e3c5982a7a4f2d7d93c2ad82e2f67406d587e8c6bcd41bff79933de59e41fb9",
"account": "4c43820067724df9f5c97637d82d0643fd45511b28b60592d690b1b3498a9a69",
"rest_url": "https://fullnode.devnet.aptoslabs.com/v1", …
```
> [aptos-cli] Show Profiles

- ecosystem/node-checker/src/configuration/types.rs
- ecosystem/node-checker/src/evaluators/build_evaluators.rs
- ecosystem/node-checker/src/evaluators/system_information/hardware.rs
- ecosystem/node-checker/src/evaluators/system_information/mod.rs
For AIT3 registration we want to explicitly check their hardware.
Setup the config from internal-ops (which I'm updating to use this evaluator):
```
cp /Users/dport/a/internal-ops/infra/apps/node-checker/configs/ait3_registration.yaml /tmp/ait3.yaml
sed -i -e "s/REPLACE_ME_WITH_MINT_KEY/<mint key but removed here trust me>/" /tmp/ait3.yaml
```
Run NHC:
```
cargo run server run --baseline-node-config-paths /tmp/ait3.yaml --listen-address 0.0.0.0
```
Test the baseline node against itself:
```
curl 'http://localhost:20121/check_node?node_url=http://35.184.73.143&api_port=80&baseline_configuration_name=ait3_registration' | jq .
```
Output:
```
{
"headline": "cpu_count is too low",
"score": 25,
"explanation": "The value for cpu_count is too small: 4 cores. It must be at least 8 cores", …
```
> [NHC] Add evaluator to check hardware requirements

- crates/aptos-rosetta/src/types/misc.rs
- crates/aptos-rosetta/src/types/objects.rs
- testsuite/smoke-test/src/rosetta.rs
Split gas fee into a different operation
E2E test handles it accordingly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3039)
> [aptos-rosetta] Add gas fee operation to rosetta

- testsuite/smoke-test/src/aptos_cli/validator.rs
- testsuite/smoke-test/src/storage.rs
- testsuite/smoke-test/src/transaction.rs
- testsuite/smoke-test/src/txn_broadcast.rs
This PR makes two changes: (i) for tests that are notoriously flaky it bumps the timeouts (where applicable); (ii) for tests that do not appear to be timeout based, it ignores them until the owners can jump in and debug. I haven't had time to dig into each test to identify what's going wrong.
Land blocking!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3081)
> [Smoke Tests] Small fixes to help improve flakiness.

- aptos-move/framework/aptos-framework/sources/aggregator/aggregator.move
- aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.move
- aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.move
- aptos-move/framework/aptos-framework/tests/aggregator_tests.move
**Second PR in supporting aggregatable total supply in Move, should land after #3048**
All aggregator code moved to `framework`. Reasons: 1) it makes many assumptions based on framework (we want to have aggregator during genesis, use system accounts, etc.); 2) this way we can friend some modules in framework.
Note: base branch is not main, when #3048 merges it will be rebased to main automatically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3050)
> [Aptos Framework] Move aggregator to framework

- crates/aptos-genesis/src/builder.rs
- testsuite/forge/src/backend/local/node.rs
- testsuite/forge/src/backend/local/swarm.rs
For more comprehensive testing, having those keys allows us for those nodes to leave validator set/change their lockup/etc.
Also, made validators list be consistent (which matters as most tests fetch first validator for RestClient, and if we are changing reliability of nodes, we can get into odd cases.
Stacked unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3065)
> [local swarm] Surface nodes account private keys

- crates/aptos-logger/src/aptos_logger.rs
- testsuite/smoke-test/src/full_nodes.rs
This PR adds a newline after each log to ensure logs are printed to separate lines. This was introduced by: https://github.com/aptos-labs/aptos-core/pull/2962/files.
I tested this by running a local validator swarm with and without this change. Without the change, logs were on the same line. With the change, logs are back to their own lines. 😄
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3092)
> [Logger] Add a new line after each log.

- Cargo.lock
- crates/aptos/Cargo.toml
- crates/aptos/build.rs
- crates/aptos/src/common/utils.rs
- crates/aptos/src/lib.rs
It's been too hard to investigate issue people have with the CLI, so I am reintroducing the build information.
I won't push this until right before the branch cut
When there is less churn, I will move all the inner files to a different crate so that telemetry is only built for the executable (just main) and none of the dependent crates.
```
aptos info
{
"Result": {
"build_branch": "cli-metrics",
"build_cargo_version": "cargo 1.62.1 (a748cf5a3 2022-06-08)",
"build_commit_hash": "215b8fff0340dfe56ca3718c435e5fe9dd3b0678",
"build_os": "macos-aarch64",
"build_pkg_version": "0.2.6",
"build_rust_channel": "1.62.1-aarch64-apple-darwin",
"build_rust_version": "rustc 1.62.1 (e092d0b6b 2022-07-16)"
}
}
```
- - - …
> [aptos-cli] CLI build information and bump version

- config/src/config/state_sync_config.rs
- state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_service.rs
This PR adds a new config for specifying the max number of concurrent requests allowed for state value streams. This is separate to the existing config which only applies to other stream types. This is useful because state value syncing is bottlenecked by the network, while other streams are not. So, we need to be slightly more aggressive with state value prefetching.
Added a new unit test for this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3090)
> [State Sync] Add custom configs for state value streams.

- storage/jellyfish-merkle/src/iterator/mod.rs
- storage/jellyfish-merkle/src/jellyfish_merkle_test.rs
- storage/jellyfish-merkle/src/lib.rs
- storage/jellyfish-merkle/src/node_type/mod.rs
- storage/jellyfish-merkle/src/restore/mod.rs
We support empty tree at any version in storage.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3095)
> [jmt] support empty tree

- storage/aptosdb/src/db_options.rs
- storage/aptosdb/src/pruner/event_store/test.rs
- storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
- storage/aptosdb/src/pruner/mod.rs
- storage/aptosdb/src/pruner/pruner_metadata.rs
- storage/aptosdb/src/pruner/state_store/mod.rs
- storage/aptosdb/src/pruner/state_store/test.rs
- storage/aptosdb/src/schema/mod.rs
- storage/aptosdb/src/schema/pruner_metadata/mod.rs
- storage/aptosdb/src/schema/pruner_metadata/test.rs
- storage/aptosdb/src/state_store/state_store_test.rs
- When initializing min_readable_version in pruner, avoid using seek_to_first due to https://github.com/facebook/rocksdb/issues/5265.
- Create a DB index to memorize the min_readable_version pruned to every time and store it in the ledger db for ledger pruner and state db for state pruner. On machine restart, read the min_readable_version from the directly instead of using seek_to_first
In the existing UTs, create a pruner before every pruning operation instead of keep using the same pruner to touch the min_readable_version initialization code path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3032)
> [storage][pruner] Add index to avoid seek_to_first on pruner startup

- crates/aptos/src/account/create.rs
- crates/aptos/src/account/create_resource_account.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/stake/mod.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/aptos_cli/validator.rs
Now that there are less move tool changes going through, I'm cleaning up the inputs into the APIs and the associated docs.
Additionally, now TransactionSummary is nice and simple.  If users want the large number of changes, they can look it up on the explorer.
Let's see how CI goes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3098)
> [aptos-cli] Cleanup general CLI output and make it more consistent

- aptos-move/aptos-sdk-builder/src/golang.rs
* Replaces []byte with Bytes so sdk is buildable.
* Currently in main, the SDK contains functions defined as `Deserialize[]byte()` which fail to compile.
* Any suggestion would be helpful!
Tested locally
1. Generated a framework release on `d45d355a2414791d48e879cfe4d14bd3b5630d41`
2. Generated using the go sdk builder
3. Go build succeeds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3038)
> [SDK] Replace []byte with Bytes so golang sdk is buildable

- ecosystem/platform/server/app/controllers/onboarding_controller.rb
- ecosystem/platform/server/app/views/onboarding/email.html.erb
- ecosystem/platform/server/app/views/onboarding/email_success.html.erb
Setup initial template for Onboarding to deviate general onboarding from AIT flow.
- Sets onboarding templates specific to "Create Account"
- Move username helper text below field and match styling to Profile settings
- Remove default value of username field `@oauth_username` as this does not pass validation if left untouched
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3086)
> [CP] Create initial layout for Onboarding, remove default OATH username

- .github/workflows/run-forge.yaml
So here is a fun one...
Because we use pull request target instead of pull request... workflows all use
the yaml definition from main. Now what does this mean?
It means that if you modify a workflow in a way that might not be backwards
compatible with repo like say in https://github.com/aptos-labs/aptos-core/pull/2992
then your land time check will succeed, however when it lands all other PR will
start using the non backwards compatible changes in workflow, and if they dont
have your commit in their ancestor their workflow will break.
The only silver lining is that because of this you can also quickly fix forward
everyone broken workflow.
Unless there is a very good reason we should get rid of pull_request_target
Test plan:
push to branch and make sure that branch job doesnt run step …
> [forge] Add back python install action

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/aptos_client.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/aptos_types/abi.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder.ts
Aptos REST APIs export JSON ABIs, which can be used to instruct BCS to serialize transaction arguments. The code in this PR fetches the JSON ABIs and converts the JSON ABIs to their binary format. The reason is that we want to reuse the code as much as possible since we have a builder that accepts binary ABIs already.
Note: Remote ABIs only support ScriptFunction aka Entry Function payloads. Script and other payloads are not supported.
Jest test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3093)
> feat: serializes txn arguments with remote ABI info

- ecosystem/platform/server/app/assets/stylesheets/application.tailwind.css
- ecosystem/platform/server/tailwind.config.js
Set default font-weight to 300 to prevent need for `font-light` everywhere. This is due to a "mismatch" between Apparat's normal weight (300) v.s. browser / Tailwind default weight (400). 
Check any text (or parent element) without adding `font-light` class to match Apparat's proper weight for _normal_.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3046)
> [CP] set default font-weight to 300

- network/src/connectivity_manager/mod.rs
Removing a redundant collect inside the connectivity manager.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3132)
> [Netowrking] Removing a redundant collect, using iter instead.

- .github/workflows/continuous-e2e-tests.yaml
- .github/workflows/run-forge.yaml
- testsuite/forge-test-runner-template.yaml
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/run_forge.sh
Run a new job in the GHA continuous testing workflow that runs Forge `compat` test suite on `forge-2`. This test will upgrade from `devnet` to the latest build on `main`.
Bonus:
* Improve the slack comment
* Always run the Forge test runner with the latest image tag, even if we're spinning up the network at an older version. The change is in `run_forge.sh` and we can port it into the python wrapper as that lands
Trigger on `push`: https://github.com/aptos-labs/aptos-core/runs/7886586797?check_suite_focus=true. 
For now, the test fails likely because of a race on the kube StatefulSet state in the remote environment -- upgrading the image tag doesn't necessarily spin down the pod immediately. To fix that, when upgrading the image tag of a running node, we first spin it down, upgrade the …
> [forge] run compat in continuous

- testsuite/forge/src/backend/k8s/cluster_helper.rs
Prevent overflow on the log, when `cleanup_time_since_epoch` < `time_since_the_epoch`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3130)
> [forge] fix cleanup timestamp parse

- api/goldens/aptos_api__tests__blocks_test__test_get_genesis_block_by_version.json
- aptos-move/e2e-move-tests/src/stake.rs
- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/stake.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- crates/aptos/src/stake/mod.rs
I've used this name in the CLI PR yesterday, but wanted to leave breaking change to move separately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3015)
> [move] Rename initialize_owner_only to initialize_stake_owner

- testsuite/forge/src/backend/local/swarm.rs
Another mitigation for flaky tests
Smoke tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3083)
> [smoke tests] extends startup timeout 10 -> 30s

- testsuite/smoke-test/src/rosetta.rs
This test was disabled because it didn't handle the startup time for Rosetta
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3141)
> [aptos-rosetta] Re-enable E2E test

- api/goldens/aptos_api__tests__state_test__test_get_account_resource_with_version.json
- api/goldens/aptos_api__tests__state_test__test_get_account_resource_with_version_too_large.json
- api/src/tests/state_test.rs
- crates/aptos-rest-client/src/lib.rs
Unfortunately, REST API doesn't reject invalid arguments, and so
a change from version => ledger_version silently started returning
wrong data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3155)
> [api] Fix RestClient version => ledger_version change

- developer-docs-site/docs/cli-tools/aptos-cli-tool/index.md
Changed link to reflect `using-cli-to-run-a-local-testnet`'s move to `/nodes/local-testnet/`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3146)
> [doc] fix broken link

- developer-docs-site/docs/nodes/ait/steps-in-ait3.md
AIT3 is not going to be live during registration. They don't need to change networks during registration. This is only necessary after selection and the network is live.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3180)
> Remove reference to network change for sign up

- developer-docs-site/docs/concepts/staking.md
- developer-docs-site/yarn.lock
Updates to the staking doc. I worked in comments from this PR: https://github.com/aptos-labs/aptos-core/pull/2211 and from this [Notion doc](https://www.notion.so/aptoslabs/Staking-Doc-DRAFT-ac5d13a449804a948ba7da3bf1da4bbd).
**Questions for @movekevin:**
1. https://github.com/aptos-labs/aptos-core/blob/00a234cc233b01f1a7e1680f81b72214a7af91a9/aptos-move/framework/aptos-framework/sources/stake.move#L62 says "Lockup period is longer than allowed." Does it mean can I manually set a lockup period? I got the impression only automatic initial setting and automatic extensions are supported? 
2. Has the rewards formula changed or only the terminology changed? The rewards now says are computed as:
`stake amount * rewards rate* performance multiplier` 
whereas previously it was:
`Reward = Maximum …
> Staking doc update for AIT-3

- .github/workflows/run-forge.yaml
So again an issue of pull_request_target action...
Because the workflow and pip requirements are out of sync for now it makes
sense to keep the dependencies minimal and just install them directly from the
command line.
Otherwise if you are running on an older commit, you will not find the
requirements file and fail :|
This on the other hand is guaranteed to just work (tm)
Test plan:
push to branch chaotic with killswitch off and make sure it installs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3117)
> [forge] Add pip install until requirements.txt exists everywhere

- terraform/helm/aptos-node/values.yaml
To get them allocatable. Other required pods on the machines take up a few gb mem by themselves
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3199)
> [helm][aptos-node] bump down cpu and mem requirements

- developer-docs-site/docs/guides/building-wallet-extension.md
We went back and forth on this, this week. the latest release is back to json, so I updated the docs to reflect that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3177)
> [docs] Move wallet dapp transaction back to json

- crates/aptos/src/node/mod.rs
Delegating the minting work to another account is going to delay the booting time of the faucet for at least 10 seconds. Users should be able to bypass the minting delegation by passing in a CLI flag. Doing so, minting will be handled by the Aptos root test account. 
`yes | cargo run -p aptos -- node run-local-testnet --force-restart  --with-faucet --do-not-delegate` boots almost instantly 
`yes | cargo run -p aptos -- node run-local-testnet --force-restart  --with-faucet` took at least 10 seconds on M1 Mac
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3207)
> [cli] Allow users to bypass minting delegation

- ecosystem/platform/server/app/controllers/it3_profiles_controller.rb
- ecosystem/platform/server/app/models/it3_profile.rb
- ecosystem/platform/server/app/views/it3_profiles/_form.html.erb
- ecosystem/platform/server/db/migrate/20220819233543_add_consensus_pop_to_it3_profiles.rb
- ecosystem/platform/server/db/schema.rb
- ecosystem/platform/server/spec/factories/it3_profiles.rb
- ecosystem/platform/server/test/controllers/it3_profiles_controller_test.rb
We changed the format for consensus keys, including a new field for consensus proof of possession.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3217)
> [community] Add consensus_pop to it3 profiles.

- Cargo.lock
- api/goldens/aptos_api__tests__blocks_test__test_get_unknown_block_by_height.json
- api/goldens/aptos_api__tests__index_test__test_get_index.json
- api/src/accept_type.rs
- api/src/accounts.rs
- api/src/blocks.rs
- api/src/context.rs
- api/src/events.rs
- api/src/response.rs
- api/src/state.rs
- api/src/tests/blocks_test.rs
- api/src/transactions.rs
- api/types/src/address.rs
- api/types/src/block.rs
- api/types/src/index.rs
- api/types/src/lib.rs
- api/types/src/mime_types.rs
- api/types/src/move_types.rs
- api/types/src/transaction.rs
- crates/aptos-rest-client/Cargo.toml
- crates/aptos-rest-client/src/lib.rs
- crates/aptos-rosetta/src/block.rs
- crates/aptos/src/account/list.rs
- ecosystem/node-checker/src/evaluators/direct/api/node_identity.rs
- ecosystem/node-checker/src/evaluators/direct/api/transaction_availability.rs
- ecosystem/node-checker/src/evaluators/direct/types.rs
- testsuite/smoke-test/src/rest_api.rs
- testsuite/smoke-test/src/rosetta.rs
- types/src/account_config/resources/core_account.rs
- types/src/account_state.rs
For performance reasons, BCS is a lot faster.  If we don't convert the structs in the middle, then we save time, plus JSON is just generally slower.
APIs that are supported in this PR:
* get account
* get ledger info (was already supported)
* get block by height / version
* get account resources
* get account modules
* get account transactions
* get transactions
* simulate transaction
* submit transaction
* get transaction by hash
* get transaction by version
APIs that are not supported in this PR:
* get events by key
* get events by handle
* get account resource
* get account module
* get table item
There is one E2E test that handles all of these, comparing them to the ones that already exist.
- - - …
> [api] Add BCS as an alternative to JSON with similar but slightly different types

- api/goldens/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
- api/goldens/v1/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json
- aptos-move/aptos-gas/src/aptos_framework.rs
- aptos-move/aptos-vm/src/move_vm_ext/vm.rs
- aptos-move/aptos-vm/src/natives.rs
- aptos-move/framework/aptos-stdlib/sources/cryptography/ristretto255.move
- aptos-move/framework/src/natives/cryptography/mod.rs
- aptos-move/framework/src/natives/cryptography/ristretto255.rs
- aptos-move/framework/src/natives/cryptography/ristretto255_point.rs
- aptos-move/framework/src/natives/cryptography/ristretto255_scalar.rs
- aptos-move/framework/src/natives/mod.rs
Adding support for Ristretto255 elliptic curve arithmetic. The Ristretto255 curve has prime-order $\ell$.
- A `Scalar` Move struct for representing scalars
+ All such objects are guaranteed to be valid scalars from 0 to $\ell$
+ Supports addition, subtraction, negation, multiplication, (multiplicative) inversion, uniform sampling by hashing a message, and more
- A `CompressedRistretto` Move struct for representing a 32-byte compressed Ristretto255 elliptic curve point, which can be put in blockchain storage
+ No arithmetic can be performed on this struct
- A `RistrettoPoint` Move struct implemented natively in Rust via a handle (similar to `Table`), decompressable from a `CompressedRistretto` struct
+ Supports addition, multiplication by scalar, fast multiplication for the Ristretto …
> [crypto+move] add Ristretto255 elliptic curves support in Move

- developer-docs-site/docs/nodes/validator-node/using-aws.md
- developer-docs-site/docs/nodes/validator-node/using-azure.md
- developer-docs-site/docs/nodes/validator-node/using-docker.md
- developer-docs-site/docs/nodes/validator-node/using-gcp.md
This needs to be in `~/$WORKSPACE` to work. Make the command do what the instructions say. `-P` in `wget` lets us download to a directory prefix
Running through registration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3209)
> [docs] make download AptosFramework step more clear

- api/src/context.rs
- types/src/account_config/events/new_block.rs
This cuts out an extra query for get block without transactions
Current tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3228)
> [api] Use block hash from new block event

- developer-docs-site/docs/concepts/basics-node-networks-sync.md
https://github.com/aptos-labs/aptos-core/issues/3062
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3232)
> Removing the older, v1, state synchronizer link.

- aptos-move/aptos-gas/src/gas_meter.rs
- aptos-move/aptos-gas/src/misc.rs
Previously when you calculate the abstract size of a reference, you would get a constant size. This was reasonable as it was the size of the reference itself being measured. However this is not suitable for the `eq` and `neq` instructions. This adds an alternative function that if given a reference value, will return the size of the value behind the reference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3245)
> [gas] fix bug in abstract value size calculation

- state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_service.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/utils.rs
- testsuite/smoke-test/src/state_sync.rs
This PR adds new tests to ensure that state sync can tolerate network frame limits and non-contiguous data chunks from the prefetcher. How this works is: the driver will accept data from a stream as long as it is contiguous. When a gap in data is detected, the data chunk with the gap will be deemed invalid, dropped, and a new data stream will be started. In a future PR, I'll update the peer scoring logic to avoid penalizing the peer that sends the non-contiguous chunk. But, given this happens rarely, it should be okay.
New tests!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3018)
> [State Sync] Add tests to ensure that state sync can tolerate network frame limits

- Cargo.lock
- api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
- aptos-move/e2e-move-tests/Cargo.toml
- aptos-move/e2e-move-tests/src/lib.rs
- aptos-move/e2e-move-tests/src/package_builder.rs
- aptos-move/e2e-move-tests/tests/code_publishing.rs
- aptos-move/e2e-move-tests/tests/common/mod.rs
- aptos-move/e2e-move-tests/tests/error_map.rs
- aptos-move/e2e-move-tests/tests/generate_upgrade_script.rs
- aptos-move/e2e-move-tests/tests/init_module.rs
- aptos-move/e2e-move-tests/tests/max_loop_depth.rs
- aptos-move/e2e-move-tests/tests/string_args.rs
- aptos-move/framework/Cargo.toml
- aptos-move/framework/aptos-framework/sources/code.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- aptos-move/framework/src/built_package.rs
- aptos-move/framework/src/release_bundle.rs
- crates/aptos/src/governance/mod.rs
- crates/aptos/src/move_tool/mod.rs
This adds a generator for proposal scripts as `aptos governance generate-upgrade-proposal <options>`. With some tweaking of the compilation scheme, the generated proposal for our largest package, aptos-framework, compiles fine.
Besides:
- Fixes a bug in the `--included-artifacts` flag; that one was simply ignored (also for publish ...)
- Adding a new test helper to e2e-move-tests to construct packages from the fly.
Added e2e test. Manually tested with aptos-framework.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3248)
> [governance upgrade] Proposal script generator for package upgrade

- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-move-tests/tests/code_publishing.rs
- aptos-move/e2e-move-tests/tests/error_map.rs
- aptos-move/e2e-move-tests/tests/init_module.rs
- aptos-move/e2e-move-tests/tests/string_args.rs
- aptos-move/framework/src/built_package.rs
- crates/aptos/src/move_tool/mod.rs
Small PR which slightly speeds up the e2e Move tests, avoiding creation of artifacts which aren't needed for a test. Flamegraph did show that those tests spend a lot of time in artifact generation.
This also fixes a small bug which let error maps be injected into bytecode only under certain settings. Error maps should always be injected, they aren't longer part of the package metadata.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3267)
> [code publishing] Improve test speed, ensure error maps are included in build code

- Cargo.lock
- ecosystem/indexer/Cargo.toml
- ecosystem/indexer/src/database.rs
- ecosystem/indexer/src/default_processor.rs
- ecosystem/indexer/src/models/events.rs
- ecosystem/indexer/src/models/write_set_changes.rs
Diesel has a limitation of 65535 items (parameters) per insert (https://github.com/diesel-rs/diesel/issues/2414). We need to chunk inserts while respecting this limit
Running indexer would throw. `Error running query: DatabaseError(UnableToSendCommand, "number of parameters must be between 0 and 65535\n")`
```
cargo run -- --pg-uri "postgresql://localhost/postgres" --node-url "https://fullnode.devnet.aptoslabs.com/v1" --emit-every 25 --batch-size 100 --start-from-version 2871943 --skip-previous-errors
```
Same command above would not throw. 
I want to add some tests around the chunking logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3269)
> [Indexer] Fix diesel exceed max number of params during insert error

- developer-docs-site/static/examples/python/first_coin.py
- developer-docs-site/static/examples/rust/first_coin/src/lib.rs
0x1::managed_coin::initialize expects u8 for decimals, not string
'The given transaction is invalid: Failed to parse transaction
payload: parse arguments[2] failed, expect integer, caused by error:
invalid type: string "6", expected u8'
To follow the tutorial in the docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3272)
> [docs] fix coin initialize expects u8 for decimals

- api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
- api/test-context/src/test_context.rs
the initial approach to stripping out some data seemed to work for only
a limited type that isn't even being tracked any more :O
this makes the code a lot more general purpose for all possible
resources...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3273)
> [api] fix up goldens to be less noisy

- api/src/accounts.rs
- api/src/events.rs
- api/src/transactions.rs
I went through the TODOs in the codebase to see if anything was of particular note.  404s on accounts existing, and paging were the things I tackled
This is built on top of:
https://github.com/aptos-labs/aptos-core/pull/3256
Event lookup gives account not found
```
curl http://localhost:8080/v1/accounts/0xDEAD/events/0x1::block::BlockResource/new_block_events\?start\=10
{"message":"Account not found by Address(0xdead) and Ledger version(39022)","error_code":"account_not_found","vm_error_code":null}%
```
Account transactions lookup gives account not found
```
curl http://localhost:8080/v1/accounts/0xDEAD/transactions\?start\=10
{"message":"Account not found by Address(0xdead) and Ledger version(39157)","error_code":"account_not_found","vm_error_code":null}
```
- - - …
> [api] Fix some bugs in the API

- Cargo.lock
- aptos-move/aptos-gas/Cargo.toml
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__borrow_after_move.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__change_after_move.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__move_from_across_blocks.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__mint__mint_to_new_account_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__on_chain_configs__drop_txn_after_reconfiguration_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__on_chain_configs__initial_aptos_version_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__peer_to_peer__cycle_peer_to_peer_multi_block_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__peer_to_peer__cycle_peer_to_peer_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__peer_to_peer__few_peer_to_peer_with_event_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__peer_to_peer__many_to_one_peer_to_peer_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__peer_to_peer__one_to_many_peer_to_peer_version_4.exp
- aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__peer_to_peer__single_peer_to_peer_with_event_version_4.exp
- aptos-move/gas-algebra-ext/Cargo.toml
- aptos-move/move-deps/Cargo.toml
- crates/aptos-faucet/src/main.rs
I spent too much time trying to rework so we have a consistent
output, but it became too hard with the (to_hex_literal), so
I've at least made the default behavior for AccountAddresses to
print out lowercase, so it is easy to compare (same as serialization)
for configs and such.  This became clear when debugging networking
and the peer ids were in all caps (but normally displayed all lower)
CI - TBD, will need to coordinate possibly with the goldenfiles / any output checks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3266)
> [account-address] Make account addresses print lowercase

- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
added rotation capability functions to allow a user to offer their rotation capability to another account, and allow another account to accept a rotation capability.
unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3091)
> Rotation Capability

- testsuite/testcases/src/performance_with_fullnode_test.rs
There is clearly a restart bug in forge, stop checking this in main because it
is impacting developers unrelated to this failure
Test Plan: #e2e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3283)
> [forge] Deflake main performance test

- api/types/src/convert.rs
- aptos-move/aptos-sdk-builder/tests/generation.rs
- aptos-move/framework/aptos-framework/sources/code.move
- aptos-move/framework/cached-packages/build.rs
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- aptos-move/framework/src/aptos.rs
- aptos-move/framework/src/built_package.rs
- aptos-move/framework/src/lib.rs
- aptos-move/framework/src/main.rs
- aptos-move/framework/src/natives/code.rs
- aptos-move/framework/src/release_builder.rs
- aptos-move/framework/src/release_bundle.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/move_tool/package_hooks.rs
- crates/aptos/src/move_tool/stored_package.rs
This consolidates on-chain package data and finalizes the on-chain representation:
- Remove all hacks for JSON via the API. Instead request BCS. This allows us to make the representation on-chain as it is supposed to be logically.
- Remove ABIs from metadata because they are clearly derivable from byte code (as the existing API code for list of modules already shows).
- Remove the verbose BuildInfo from metadata, instead have a dedicated field `source_digest`, the real information one needs.
- Moving composition of chunks for publish from entry function to client.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3281)
> [on-chain package data] Consolidate on-chain package data

- testsuite/forge/src/runner.rs
So we can have more signal in the test report text that gets printed as a Github comment, in the event of test failure. Previously, we were failing tests due to some "success criteria" such as no validators/fullnodes restarted, TPS, latency, etc, but often you wouldn't know unless you looked at the actual test runner logs.
Canary in CI: https://github.com/aptos-labs/aptos-core/pull/3247#issuecomment-1221432979
Output looks like:
```
performance benchmark with full nodes : 6938 TPS, 4324 ms latency, 6000 ms p99 latency,no expired txns
Test Failed: TPS requirement failed. Average TPS 6938, minimum TPS requirement 100000000
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/apt …
> [forge] write TestResult to report text

- Cargo.lock
- consensus/Cargo.toml
Noticed an issue with `v0.3.23` of futures crate that causing the network_tests to fail in the consensus crate because messages are not received in the channel. Pinning it to `v0.3.21` to unblock development.
`cargo test -p consensus` passes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3298)
> [dependency][consensus][bug-fix] Pin dependency to fix failing tests

- config/src/config/consensus_config.rs
- consensus/consensus-types/src/request_response.rs
- consensus/src/epoch_manager.rs
- consensus/src/liveness/proposal_generator.rs
- consensus/src/liveness/proposal_generator_test.rs
- consensus/src/payload_manager.rs
- consensus/src/quorum_store/direct_mempool_quorum_store.rs
- consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs
- consensus/src/round_manager_fuzzing.rs
- consensus/src/round_manager_test.rs
- consensus/src/state_replication.rs
- consensus/src/test_utils/mock_payload_manager.rs
- mempool/src/core_mempool/mempool.rs
- mempool/src/shared_mempool/tasks.rs
- mempool/src/shared_mempool/types.rs
- mempool/src/tests/common.rs
- mempool/src/tests/core_mempool_test.rs
- mempool/src/tests/mocks.rs
- mempool/src/tests/multi_node_test.rs
- mempool/src/tests/test_framework.rs
There's a bump for single transaction size limit to 6MB https://github.com/aptos-labs/aptos-core/pull/2829, there's no way we can support 6mb  * 6000 blocks, this commit adds the limit on bytes level
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2844)
> [mempool] add support to limit maximum bytes for a batch

- Cargo.lock
- config/src/config/state_sync_config.rs
- state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
- state-sync/state-sync-v2/data-streaming-service/src/logging.rs
- state-sync/state-sync-v2/data-streaming-service/src/metrics.rs
- state-sync/state-sync-v2/data-streaming-service/src/streaming_client.rs
- state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/mod.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_client.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_service.rs
- state-sync/state-sync-v2/state-sync-driver/Cargo.toml
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/driver.rs
- state-sync/state-sync-v2/state-sync-driver/src/notification_handlers.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/utils.rs
- state-sync/state-sync-v2/state-sync-driver/src/utils.rs
This PR makes several fixes and improvements to the data streaming service to ensure that data streams are being terminated correctly:
1. First, we fix a small bug where data streams weren't being removed because the removal code was using `notification_id` instead of `data_stream_id`.
2. Second, we update the driver logic to ensure that all streams are terminated, whether or not the reason was due to a bad notification (i.e., notification feedback is now optional).
3. Third, we add logic to the streaming service to ensure that dropped data stream listeners result in the data stream being removed from the service. This protects against bad clients that don't terminate the stream before dropping it.
4. Finally, we've added a new metric to help track the number of active data streams …
> [Data Streaming Service] Improve stream visibility and termination.

- crates/aptos/src/common/types.rs
- crates/aptos/src/governance/mod.rs
* Accidentally confused myself on hash values and ported the script hash to use the same as the block, which is address (u32) -- this is up for debate, but it is ... kinda nicer
* There were breakages in the CLI tool possibly due to not using the aptos_stdlib generated transaction builder
* Simplified the execute proposal so that people like me can use it easier
* Removed submit_entry_function from the CLI since it isn't used and should have no usage for the foreseeable future
Somethings one has to do to test (and sadly I wiped away some of my changes):
```
diff --git a/aptos-move/framework/aptos-framework/sources/aptos_governance.move b/aptos-move/framework/aptos-framework/sources/aptos_governance.move
index 5ea08f34b1..85310e666a 100644
--- …
```
> Validated end-to-end governance upgrade

- Cargo.lock
- config/src/config/network_config.rs
- crates/aptos-telemetry-service/Cargo.toml
- crates/aptos-telemetry-service/src/clients/humio.rs
- crates/aptos-telemetry-service/src/clients/mod.rs
- crates/aptos-telemetry-service/src/constants.rs
- crates/aptos-telemetry-service/src/context.rs
- crates/aptos-telemetry-service/src/index.rs
- crates/aptos-telemetry-service/src/lib.rs
- crates/aptos-telemetry-service/src/log_ingest.rs
- crates/aptos-telemetry-service/src/tests/test_context.rs
- crates/aptos-telemetry-service/src/types/mod.rs
This PR introduces the log ingestion endpoint in the telemetry service to accept push logs from Aptos nodes. The logs will be ingested into humio using the configured credentials. Client-side changes are in #3151.
I and @bchocho tested e2e by running a local validator node and a service and validated that logs were sent to humio.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3254)
> [telemetry-service] Log Ingest Endpoint

- crates/aptos-rest-client/src/lib.rs
- testsuite/forge/src/interface/aptos.rs
- testsuite/smoke-test/src/aptos_cli/validator.rs
- testsuite/smoke-test/src/storage.rs
- testsuite/smoke-test/src/test_utils.rs
Previously, after reconfig, it wasn't guaranteed that new epoch has started, making it easy to have race condition in the tests.
current, and rewards and consensus tests stacked on top
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3138)
> [smoke-test] Improve reconfig test utils

- crates/aptos-genesis/src/builder.rs
- testsuite/forge/src/backend/local/node.rs
- testsuite/forge/src/backend/local/swarm.rs
retrying #3065  with ConfigKey, to not break the build.
`cargo build -p aptos-node `works now
For more comprehensive testing, having those keys allows us for those nodes to leave validator set/change their lockup/etc.
Also, made validators list be consistent (which matters as most tests fetch first validator for RestClient, and if we are changing reliability of nodes, we can get into odd cases.
Stacked unit test
`cargo build -p aptos-node`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3214)
> [local swarm] [try2] Surface nodes account private keys

- crates/aptos-telemetry-service/src/auth.rs
- crates/aptos-telemetry-service/src/clients/mod.rs
- crates/aptos-telemetry-service/src/context.rs
- crates/aptos-telemetry-service/src/custom_event.rs
- crates/aptos-telemetry-service/src/lib.rs
- crates/aptos-telemetry-service/src/tests/auth_test.rs
- crates/aptos-telemetry-service/src/tests/test_context.rs
- crates/aptos-telemetry-service/src/types/auth.rs
- crates/aptos-telemetry-service/src/types/validator_set.rs
- crates/aptos-telemetry-service/src/validator_cache.rs
- crates/aptos-telemetry/src/constants.rs
- crates/aptos-telemetry/src/sender.rs
This PR adds support for authenticating validator full nodes using the `fullnode_network_addresses` in the onchain config.
I ran a local validator and a validator full node and was able to check that the service could authenticate Validators and VFNs accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3145)
> [aptos-telemetry] Authenticate Validator Full Nodes

- ecosystem/platform/server/app/controllers/it3s_controller.rb
- ecosystem/platform/server/test/controllers/it3s_controller_test.rb
If you go to /it3 when signed out, it's supposed to redirect back to /it3 after you sign in. This wasn't working previously because the controller didn't use `authenticate_user!`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3334)
> [community] Fix redirect to /it3 after sign in.

- Cargo.lock
- aptos-node/src/lib.rs
- config/src/config/logger_config.rs
- crates/aptos-logger/Cargo.toml
- crates/aptos-logger/src/aptos_logger.rs
- crates/aptos-logger/src/counters.rs
- crates/aptos-logger/src/lib.rs
- crates/aptos-logger/src/telemetry_log_writer.rs
- crates/aptos-telemetry/src/lib.rs
- crates/aptos-telemetry/src/metrics.rs
- crates/aptos-telemetry/src/sender.rs
- crates/aptos-telemetry/src/service.rs
- crates/aptos-telemetry/src/telemetry_log_sender.rs
Add log ingest via telemetry service on the client side. (#3254 added the endpoint.)
Logs are sent to telemetry service asynchronously in batches. Batches are sent every 5 seconds, or earlier if the batch size is reached. Other than the time to add to channel, there should be no slowdown for the main threads.
```
RUST_LOG_TELEMETRY=warn cargo run -p aptos-node -- --test
cargo run -p aptos-telemetry-service -- -f telemetry-service.yaml
```
(with local `telemetry-service.yaml` and `bq-sa.json`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3151)
> [telemetry] client side of log ingest via telemetry service

- config/src/config/state_sync_config.rs
This PR increases the default batch size for state sync (from 1k to 2k txns/outputs per batch), and also bumps the prefetcher (from 2 to 3 concurrent requests). These values provide a more stable experience when the system is running under max. load for sustained periods.
Existing tests and also a forge run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3333)
> [State Sync] Increase the default batch size and prefetcher.

- crates/aptos-rosetta/src/types/misc.rs
- crates/aptos-rosetta/src/types/objects.rs
- testsuite/smoke-test/src/rosetta.rs
Sort operations in transactions so that we have a predictable order
E2E test now tests negative balances at end of transactions to ensure this doesn't happen
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3348)
> [aptos-rosetta] Sort operations in transactions

- terraform/modules/indexer/rds.tf
- terraform/modules/indexer/variables.tf
Add new parameter for `rds.logical_replication`, and also ability to tune db iops
Apply to new stack. Existing stacks look fine
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3354)
> [tf][indexer] tune db_iops and enable logical replication

- aptos-node/src/lib.rs
- config/src/config/logger_config.rs
- consensus/src/round_manager.rs
- crates/aptos-logger/src/aptos_logger.rs
- crates/aptos-logger/src/lib.rs
- crates/aptos-logger/src/logger.rs
- crates/aptos-logger/src/telemetry_log_writer.rs
- crates/aptos-telemetry/src/service.rs
- crates/aptos-telemetry/src/telemetry_log_sender.rs
With this change, panics can make it into humio. Flush is expensive -- today it is only called from `handle_panic`.
End-to-end test with an instrumented panic. Previously the panic did not make it to humio; now it does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3351)
> [telemetry] Add flush to allow panics to be logged through telemetry

- ecosystem/platform/server/Gemfile.lock
- ecosystem/platform/server/app/admin/network_operations.rb
- ecosystem/platform/server/app/notifications/base_notification.rb
- ecosystem/platform/server/app/views/admin/network_operations/notify.html.erb
- ecosystem/platform/server/db/migrate/20220819161242_add_notified_at_to_network_operation.rb
- ecosystem/platform/server/db/migrate/20220823183316_change_notification_preferences_default_to_false.rb
- ecosystem/platform/server/db/schema.rb
- ecosystem/platform/server/test/notifications/governance_proposal_notification_test.rb
Adds the ability to send network operation notifications from admin.
cc @sherry-x 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3187)
> [community] Add the ability to send notifications from admin.

- .github/workflows/lint-test.yaml
Its an unfortunate reality of life that unittests can be flaky, especially when
they're creating databases or interacting with files or both!
To deal with this reality lets not fail PR / main when we have a flaky test,
however in tandem we need to monitor the flaky test in main and work to remove
the flakiness.
Test Plan: 
https://github.com/aptos-labs/aptos-core/runs/7983894955?check_suite_focus=true
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3360)
> [nextest] Add retries and don fail fast in CI

- aptos-move/framework/aptos-framework/sources/code.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- aptos-move/framework/src/built_package.rs
- aptos-move/framework/src/natives/any.rs
- aptos-move/framework/src/natives/code.rs
- aptos-move/framework/src/release_bundle.rs
This allows us to extend package metdata without breaking change and without scattering data over multiple resources.
As a side-effect also closes #2399.
NA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3350)
> [package metadata] Add `Any` extension field to package metadata

- testsuite/testcases/src/performance_with_fullnode_test.rs
This was disabled because of memory leak SEV, which has been resolved now. 
Run Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3349)
> [Forge] Re-enable validator and FN restart check

- Cargo.lock
- sdk/Cargo.toml
- sdk/src/lib.rs
- sdk/src/transaction_builder.rs
- sdk/src/types.rs
These changes were inspired by making the docs site examples use the Rust SDK. I found myself wanting things that weren't exposed. Now they are. The philosophy is users shouldn't need to import any aptos crate besides aptos-sdk. Requiring them to import other opinionated crates is fine and desirable (e.g. anyhow, tokio, etc).
CI. These changes are backwards compatible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2869)
> Expose a greater set of necessary components from aptos-core in the Rust SDK

- ecosystem/node-checker/src/evaluators/direct/api/mod.rs
- ecosystem/node-checker/src/evaluators/direct/api/transaction_availability.rs
Testing the BCS side of the API, works a treat.
Config: https://gist.github.com/69edcae0809be7ee7b5670bcfc20f4e7.
```
cargo run server run --baseline-node-config-paths ~/a/internal-ops/infra/apps/node-checker/configs/ait3_vfn.yaml --listen-address 0.0.0.0
```
```
curl 'http://localhost:20121/check_node?node_url=http://127.0.0.1&baseline_configuration_name=ait3_vfn'  | jq .
```
```
{
"evaluation_results": [
{
"headline": "Chain ID reported by baseline and target match",
"score": 100,
"explanation": "The node under investigation reported the same Chain ID testing as is reported by the baseline node",
"evaluator_name": "node_identity",
"category": "api",
"links": []
},
{
"headline": "Role Type reported by baseline and target match",
"score": 100,
"explanation": "The node under investigation …
```
> Use BCS version of get_transaction in NHC transaction availability evaluator

- ecosystem/platform/server/app/views/it3s/show.html.erb
We now have the wallet live on the chrome store and should just have them download it from there
https://user-images.githubusercontent.com/19931667/186287826-65bdfe4d-c3d1-4fbc-9d06-d2ee0c5b3c26.mov
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3370)
> [community] Fix wallet download link

- developer-docs-site/static/examples/rust/first_transaction/Cargo.toml
Just replacing an old dependency with what we use throughout the rest of the repo.
We'll revisit using `fiat-crypto` throughout our repo in the future (@davidiw).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3359)
> [crypto] replace old ed25519-dalek-fiat dependency

- crates/aptos-telemetry/src/cli_metrics.rs
- crates/aptos-telemetry/src/sender.rs
- crates/aptos-telemetry/src/service.rs
Changing all the error logs to debug in telemetry service because it is very noisy but not useful for our validator operators. We will rely on metric counts for now and improve error logging in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3371)
> [aptos-telemetry] change error logs to debug

- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/aptos_account.test.ts
- ecosystem/typescript/sdk/src/aptos_account.ts
Create Account with [hdpath 637](https://github.com/satoshilabs/slips/pull/1364) 
```
test('generates derive path accounts', () => {
const address = '0x07968dab936c1bad187c60ce4082f307d030d780e91e694ae03aef16aba73f30';
const a1 = AptosAccount.fromDerivePath('m/44\'/637\'/0\'/0\'/0\'', mnemonic);
expect(a1.address().hex()).toBe(address);
});
test('generates derive path accounts', () => {
expect(() => { AptosAccount.fromDerivePath('', mnemonic); }).toThrow(new Error('Invalid derivation path'));
});
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2073)
> Add Create Account fromDerivePath

- aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move
- aptos-move/move-examples/hello_blockchain/sources/hello_blockchain_test.move
- developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md
- developer-docs-site/docs/tutorials/first-move-module-cli.md
- developer-docs-site/sidebars.js
- developer-docs-site/static/move-examples
this is a pretty rough doc, but my goal is to just power through and hopefully massage a bit...
considering that we're going to be disabling the module publishing transaction very soon...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3384)
> [docs] port hello_blockchain to being purely cli tutorial

- ecosystem/platform/server/app/components/footer_component.rb
- ecosystem/platform/server/app/components/header_component.rb
Add Whitepaper link to Main navigation dropdown (About) and within Footer links. 
Ensure "Whitepaper" positioning within menus makes sense and URL is correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3303)
> [CP] Add Whitepaper to Main / Footer navigation

- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/test/mod.rs
Added a option from move-cli: `--instructions`, `-i`
Bound the number of instructions that can be executed by any one test.
see: https://github.com/diem/move/blob/main/language/tools/move-cli/src/package/cli.rs#L135
```bash
aptos move test --instructions <NUMBER>
```
or
```bash
aptos move test -i <NUMBER>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2444)
> [CLI] Bound the number of instructions that can be executed by any one test.

- aptos-move/framework/aptos-stdlib/sources/cryptography/ristretto255.move
Move `Scalar` type should not have `key`. Oops.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3402)
> [crypto+move] oops, Move Scalar type should not have 'key'

- developer-docs-site/docs/concepts/basics-events.md
This PR just fixes only the links. I just noticed that I couldn't tell which `field_name` I should use to extract event info from the Events REST API. I will create an issue for REST API docs separately. cc: @banool
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3328)
> Fixing links in Concepts>Events doc

- aptos-move/framework/aptos-framework/sources/voting.move
Title
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3410)
> [Aptos Framework][Voting] Add a field to track proposal's resolution timestamp

- terraform/aptos-node-testnet/main.tf
- terraform/aptos-node-testnet/variables.tf
- terraform/aptos-node/aws/kubernetes.tf
- terraform/aptos-node/aws/network.tf
- terraform/aptos-node/aws/variables.tf
- testsuite/run_forge.sh
Provide variable `maximize_single_az_capacity` for AWS `aptos-node` Terraform to be able to more greedily allocate larger CIDR blocks to the subnet the NodeGroups are in. This lets us increase our Forge test capacity by 4x to roughly 16-20 concurrent tests in a single EKS cluster (based off of https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt). My plan is to create at least 3 of these clusters (to replace the existing 3 we have). We will have one dedicated to Land-blocking tests, one for long-running continuous tests, and at least one more for backup capacity / manual testing.
We can have more too, as the cost to having these around is minimal since the autoscaler spins down to the cluster to near-zero when idle.
The other way around this is to add another CIDR …
> [tf][aws] maximize subnset size

- api/src/tests/state_test.rs
- api/src/tests/transactions_test.rs
- aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/e2e-tests/src/executor.rs
- aptos-move/e2e-testsuite/src/tests/module_publishing.rs
- ecosystem/sf-indexer/firehose-stream/src/tests/proto_converter_tests.rs
The code is still there for now, but disabled with a status code `FEATURE_UNDER_GATING`.
Lets see whether all tests still pass after this...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3412)
> [code publish] Disable module bundle publishing

- aptos-node/src/lib.rs
- config/src/config/error.rs
- config/src/config/execution_config.rs
- config/src/config/mod.rs
This PR provides some basic improvements to the error messages displayed when starting up a node and attempting to the load the config, genesis blob and waypoint. This relates to: https://github.com/aptos-labs/aptos-core/issues/2399.
Examples:
1. Failed to find config file
```
thread 'main' panicked at 'The node config file could not be found! Ensure the given path is correct: "./broken_full_node.yaml123"', aptos-node/src/lib.rs:139:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
2. Failed to find genesis blob
```
thread 'main' panicked at 'Failed to parse node config file! Given file path: "./broken_full_node.yaml". Error: Unexpected("The genesis file could not be found! Ensure the given path is correct: …
```
> [Aptos Node] Improve error messages for config file loading.

- terraform/aptos-node-testnet/addons.tf
- terraform/helm/aptos-node/files/configs/fullnode.yaml
- terraform/helm/aptos-node/files/configs/validator.yaml
- terraform/helm/aptos-node/templates/NOTES.txt
- terraform/helm/aptos-node/templates/configmap.yaml
- terraform/helm/aptos-node/values.yaml
Passing in individual helm values and having to template them in the validator/fullnode NodeConfigs is confusing and error prone. Especially is the case when the helm values do not match the same YAML structure as the NodeConfig struct in rust, nor the final/templated YAML. This PR gives operators two options for configuring their validators/fullnodes in the aptos-node hem chart:
1. Provide NodeConfig values in the structure as they are expected, in `.Values.validator.config` and `.Values.fullnode.config`. 
2. Option to specify `.Values.overrideNodeConfig`, and generate your own k8s ConfigMaps that hold the desired NodeConfig. One potential downside to this though is that operators would need to know the exact paths to the waypoint, genesis, etc which are specific to the helm chart since …
> [helm][aptos-node] option to pass in entire NodeConfig

- config/src/config/mempool_config.rs
Increase mempool capacity from 1M -> 2M. See https://www.notion.so/aptoslabs/Blockchain-default-config-review-c0ec77c6fc4341b4a270e013eb4a33f7
Forge run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3406)
> [Mempool] Tune mempool capacity configuration for AIT/mainnet

- crates/aptos/src/node/analyze/fetch_metadata.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/test/mod.rs
cargo run -p aptos -- node analyze-validator-performance --analyze-mode=all --url=https://sherryx.aptosdev.com --start-epoch=-5 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3416)
> [cli] Enable setting epoch range from the end ( i.e. -2) in analyze validators, and show partial newest epochs 

- testsuite/run_forge.sh
This should balance 66% of the traffic to the new `forge-big-*` clusters, which can support 4x the max capacity. Once these are stable, we can fully roll out the big clusters and tear down the old ones .
Note: this change does not need to be made to the new forge python wrapper as that does cluster selection by regex from all running clusters, rather than selecting from a hardcoded list
Spun up 3 new forge-big clusters, 2 of which will be used here. On each, I've run some load testing and can see that they can burst up to at least 600 nodes, barring intermittent txn emitter failures
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3432)
> [forge] add new capacity for cluster autoselection

- crates/transaction-emitter-lib/src/emitter/account_minter.rs
Sometimes, we see the emitter fails complaining about sending account doesn't exists. This is because of REST end point is not up to date with the latest ledger state. This diff adds waiting for the REST end point to catch up to the ledger state so that the account exists. 
Also add retry for waiting for transaction call which was failing sometime. 
Run Forge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3431)
> [Txn emitter] Various fixes for the transaction emitter

- ecosystem/indexer/src/default_processor.rs
- ecosystem/indexer/src/indexer/errors.rs
- ecosystem/indexer/src/indexer/fetcher.rs
- ecosystem/indexer/src/indexer/processing_result.rs
- ecosystem/indexer/src/indexer/tailer.rs
- ecosystem/indexer/src/indexer/transaction_processor.rs
- ecosystem/indexer/src/main.rs
- ecosystem/indexer/src/models/metadata.rs
- ecosystem/indexer/src/models/processor_statuses.rs
- ecosystem/indexer/src/models/transactions.rs
- ecosystem/indexer/src/token_processor.rs
- testsuite/smoke-test/src/indexer.rs
Separate threads for fetching data, and separate threads for pushing it to DB in parallel
increases (locally) performance of (old) indexer from 1.4k TPS, to 2.7k TPS (locally, running against sherrynet)
Pushing from local to RDS performance went from 20TPS to ~150 TPS with bulk fetch, and to 600 TPS with batch write.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3372)
> [ECO] Fast Indexer

- config/src/config/state_sync_config.rs
- state-sync/aptos-data-client/src/lib.rs
- state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
- state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_client.rs
- state-sync/state-sync-v2/state-sync-driver/Cargo.toml
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/metrics.rs
- state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/continuous_syncer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/storage_synchronizer.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/utils.rs
This PR makes two changes to the state sync logic:
1. We use channels that apply back pressure between the driver, executor and committer. This means when the pipeline becomes full, the code will block before sending any more data (as opposed to previously dropping the messages and waiting for the pipelines to flush).
2. Adds some additional metrics around these operations, for better visibility.
Existing unit and smoke tests should cover this. Likewise, we deployed it on a testnet to verify the behaviour.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3433)
> [State Sync] Add backpressure to execute-commit pipeline.

- crates/aptos-rosetta/src/construction.rs
- crates/aptos-rosetta/src/error.rs
- testsuite/smoke-test/src/rosetta.rs
Gas estimation was only working because the max gas was below the
amount used in the test.  This has been fixed.  Additionally, more
testing variables were changed to account and test this.  Error
codes are now static accordingly.
The e2e test was changed to have smaller than 1 million coins so that it would test this behavior.  Similarly with having an account with more than the max gas (which is something like 4 million at this moment).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3467)
> [aptos-rosetta] Fix gas estimation for Rosetta and cleanup tests

- crates/aptos/src/node/analyze/analyze_validators.rs
- crates/aptos/src/node/analyze/fetch_metadata.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/test/mod.rs
ValidatorSet is not ordered any more, and analyze-validators was expecting that. 
Already reviewed as a part of #3066
cargo run -p aptos -- node analyze-validator-performance --analyze-mode=all --url=https://sherryx.aptosdev.com --start-epoch=30 --end-epoch=36
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3342)
> Cherry-pick to testnet for fixing analyze-validators CLI

- terraform/aptos-node-testnet/addons.tf
- terraform/helm/k8s-metrics/templates/autoscaler.yaml
- terraform/helm/k8s-metrics/values.yaml
- terraform/helm/testnet-addons/templates/waypoint.yaml
- terraform/helm/testnet-addons/values.yaml
Few changes that explicitly set resource requests. Autoscaler and metrics-server must scale to 1000 node Forge. Waypoint has issues with devnet and sherrynet genesis downloads.
* fix bug in autoscaler resource request. it now requests 1CPU, 1Gi Memory
* metrics-server has now resource request based on the max number of nodes, if specified. 1m CPU per node, 2Mi Memory per node
* waypoint didn't have resources set. set it
Apply to my cluster 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3472)
> [helm] add resource requests for metrics-server, autoscaler, and waypoint

- .github/workflows/continuous-e2e-release-test.yaml
Pre release test has a runtime of 10 hours, however github action has default limit of 6 hours :|
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
Test Plan: land + verify, its not production critical right now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3478)
> [forge] Increase timeout for pre release test

- docker/compose/aptos-node/validator.yaml
- terraform/helm/aptos-node/files/configs/validator.yaml
This PR updates the docker configs to use rocks db for secure storage. Note: the path only needs to specify the name of the file (the actual file location will be the data directory used by the node).
Manually ran a node with this config. Also will verify CI/CD can build and deploy the docker images.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3464)
> [Docker] Use rocks db secure storage by default.

- config/src/config/state_sync_config.rs
This PR decreases the potential backlog of data streams under complete node saturation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3477)
> [Data Streaming Service] Limit the backlog on data chunks under saturation

- developer-docs-site/docs/tutorials/first-transaction-sdk.md
- ecosystem/typescript/sdk/examples/typescript/transfer_coin.ts
- ecosystem/typescript/sdk/src/aptos_client.ts
- ecosystem/typescript/sdk/src/coin_client.test.ts
- ecosystem/typescript/sdk/src/coin_client.ts
- ecosystem/typescript/sdk/src/token_client.test.ts
- ecosystem/typescript/sdk/src/token_client.ts
We had many variants of essentially the same functions all over the SDKs, tests and examples. These functions in one way or another would either generate, sign, and submit a transaction, or wait for a transaction. I added a richer (but notably backwards compatible) set of functions for this. I then use these throughout the specialized clients (token and coin) and some of the tests and examples (more to come).
I also make the CoinClient conform to how TokenClient works, specifically by returning a txn hash without waiting.
SDK tests:
```
cd ecosystem/typescript/sdk
yarn test
```
Examples:
```
cd ecosystem/typescript/sdk/examples/typescript
yarn test
```
Docs site:
```
cd developer-docs-site
yarn start
```
- - - …
> Reduce duplication of specialized clients in TS SDK, make transaction submission functions more uniform

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/package.json
This won't trigger a release until we land it into the devnet branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3480)
> Bump TS SDK to 1.3.8

- .github/actions/gar-auth/action.yaml
- .github/actions/load-ci-env/action.yaml
- .github/actions/load-secrets/action.yaml
- .github/workflows/build-images.yaml
- .github/workflows/copy-images-to-dockerhub.yaml
- .github/workflows/deploy-community-platform.yaml
- .github/workflows/run-forge.yaml
- .github/workflows/sdk-release.yaml
- docker/docker-bake-rust-all.hcl
- ecosystem/indexer-server/docker-bake.hcl
- ecosystem/platform/server/docker-bake.hcl
This PR does an overhaul of how we inject secrets into GitHub jobs.
Previously we exclusively used Github's secret management to both inject actual secrets and to set (not-really-secret) environment variables like `FORGE_BLOCKING`. Since Github's secret management doesn't inject secrets into pull_request events created by forks we implemented a sophisticated workaround using pull_request_target, which sorta worked fine for a bit but caused a lot of confusion and testability issues when trying to change a workflow.
This PR aims to solves this by:
1. We switch primarily to GCP's Secret Manager for actual secrets management using https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions?authuser=1. In short secrets are now stored in GCP …
> CICD: overhaul secrets management and move from github actions's secret management to GCP Secrets Manager

- .github/workflows/continuous-e2e-single-vfn-test.yaml
- terraform/helm/aptos-node/values.yaml
- testsuite/forge-cli/src/main.rs
With these changes, a single VFN can push 5K TPS to the validator.
The previous configs would only allow up to 2K (20 broadcasts/s * 100 txn/broadcast).
Also add a forge test to detect any regressions. It is not scheduled, pending testing it via github.
Ran the forge test, saw > 5K TPS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3363)
> [mempool] update configs for better VFN -> validator throughput

- developer-docs-site/package.json
- developer-docs-site/yarn.lock
- ecosystem/typescript/sdk/package.json
To fix it I pin TS to 4.7.4.
```
cd ecosystem/typescript/sdk
yarn lint
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3495)
> Fix ecosystem-lint

- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/system_addresses.move
0x10 is 16 not 10. It should be 0xa. This is discovered in https://github.com/aptos-labs/aptos-core/pull/3460
Existing unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3511)
> [Aptos Framework] Fix incorrect hex address value

- docker/rosetta/rosetta.Dockerfile
- docker/rust-all.Dockerfile
- ecosystem/indexer-server/Dockerfile
- ecosystem/platform/server/Dockerfile
Pin and upgrade docker base images
Notably, upgrade rust-all debian-base to `debian:buster-20220822`, and the `builder` to `rust:1.63.0-buster`
Build in CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3482)
> [docker] upgrade and pin docker base images

- ecosystem/platform/server/app/views/layouts/it3.html.erb
- ecosystem/platform/server/app/views/static_page/incentivized_testnet.html.erb
- Fix Footer spacing issues due to placement of `<style>` tag outside of `render 'layouts/application'`
- Address text wrapping for "Incentivized Testnet 3" on mobile as it was creating a widow
Ensure footer layout is correct on Safari:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3476)
> [CP] Fix spacing issue on Safari due to <style> tag placement

- .github/workflows/check-docs-site-examples.yaml
- .github/workflows/sdk-release.yaml
- ecosystem/typescript/sdk/examples/README.md
- ecosystem/typescript/sdk/examples/javascript/package.json
- ecosystem/typescript/sdk/examples/typescript/package.json
We previously decided that we would consolidate our examples so they only exist in the SDK directory, meaning we delete the examples directly within developer-docs-site. As part of this, since these examples are used in the dev docs site tutorials and are a key way folks learn how to use our SDK, they should be built to work against the network that they build against, devnet. So instead of depending on the SDK locally, they should depend on the npmjs SDK, which is what they'll do themselves with their own dapps. When mainnet rolls around nothing much will change here; we'll make the SDK on npmjs work for mainnet, and have pre-release devnet versions, like `1.3.8-devnet.1`.
Coming up next in another PR, deleting the dev docs site examples and updating that CI accordingly.
```
cd …
```
> Make TS SDK examples use npmjs package

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/aptos_client.test.ts
- ecosystem/typescript/sdk/src/aptos_client.ts
Fix the bug in `waitForTransactionWithResult`. When API returns `404`, the function should continue waiting rather than returning early. The reason is that the txn might not be committed promptly. `waitForTransactionWithResult` should either timeout or get an error in such case.
Ran all the tests and ran the examples against devnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3518)
> fix: fix the txn waiting bug

- aptos-move/e2e-move-tests/src/aggregator.rs
- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-move-tests/src/package_builder.rs
- aptos-move/e2e-move-tests/tests/code_publishing.rs
- aptos-move/framework/aptos-framework/sources/code.move
- aptos-move/framework/aptos-stdlib/sources/any.move
- aptos-move/framework/aptos-stdlib/sources/copyable_any.move
- aptos-move/framework/src/built_package.rs
- aptos-move/framework/src/natives/any.rs
- aptos-move/framework/src/natives/code.rs
- crates/aptos/src/account/create.rs
This implements a new policy for package dependencies: A package is not allowed to refer to another package which has a lower upgrade policy. For example, an immutable package cannot refer to a compatible package. This check wasn't yet implemented and is added in this PR. 
This PR also suggests to reenable policy `arbitrary` with a semantics such that is suited for the 'app' developer (in contrast to the library developer): references to packages with `arbitrary` upgrade policy are allowed only if the dependency is _at the same address_ (plus the above condition is fulfilled). This allows an app developer to update their packages following other notions of compatibility. For example, the current compatible policy does not allow to remove public functions. But someone can very well remove …
> [code upgrade] Verify package dependency policy on chain

- aptos-move/e2e-move-tests/tests/code_publishing.data/pack_stdlib/sources/string.move
- aptos-move/e2e-move-tests/tests/code_publishing.data/pack_stdlib_incompat/sources/string.move
- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/aptos-framework/sources/aptos_account.move
- aptos-move/framework/aptos-framework/sources/resource_account.move
- aptos-move/framework/aptos-stdlib/sources/any.move
- aptos-move/framework/aptos-stdlib/sources/copyable_any.move
- aptos-move/framework/aptos-stdlib/sources/from_bcs.move
- aptos-move/framework/move-stdlib/sources/string.move
- aptos-move/framework/src/natives/any.rs
- aptos-move/framework/src/natives/mod.rs
- crates/aptos/src/governance/mod.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/aptos_cli/move.rs
This PR introduces as the matching counterpart to `std::bcs` the module `aptos_std::from_bcs`. It seems to be appropriate to tie the byte conversions together under the `bcs` label because that is how we have implemented them.
All safe conversions from bytes to primitive types + Strings are supported. Naming is as in `from_bcs::to_<type>`. Example:
```
use std::bcs;
use aptos_std::from_bcs;
assert!(from_bcs::to_address(bcs::to_bytes(&@0xabcdef)) == @0xabcdef;
```
While the previous `byte_conversions` appeared more intuitive, this is more consistent and precise, and those features are for expert users anyway. 
Also the friend native `from_bytes` is now defined in `from_bcs` instead of `any`.
We still have to introduce formatting conversions for `T <-> String`, but they are bit more tricky …
> [framework] Consolidate conversions

- terraform/helm/monitoring/files/prometheus.yml
- terraform/helm/monitoring/values.yaml
Do a few things to reduce metrics volume for onboard prometheus in the `monitoring` helm chart.
* Explicitly drop a few known spammy metrics (found via tsdb stats), using `metric_relabel_configs`. These include metrics from EBS CSI driver, vector, and `container_tasks_state` fromcAdvisor
* Rename `monitoring.fullKubernetesScrape` to `monitoring.prometheus.fullKubernetesScrape`, and set it to `false` by default. This reduces all the metrics load from kube API servers and a few spammy (kube node) metrics, which most folks should not be concerned with. This is fine IMO for reference monitoring solution
Apply to testnet, and prometheus targets are greatly minimized. 
- - - …
> [helm][monitoring] drop spammy metrics

- .github/workflows/continuous-e2e-compat-test.yaml
- .github/workflows/run-forge.yaml
Fix the workflow spec.
Also add a new parameter `IMAGE_TAG`, which overrides `GIT_SHA`. This allows us to do compat against `devnet` and also fetch enough git history to get the latest main. Planning on using `devnet` or `testnet` going forward -- whatever mutable image tag we're using for the long-running (longevity) testnets
Trigger on push: https://github.com/aptos-labs/aptos-core/actions/runs/2935741904
```
Compatibility test results for devnet ==> 8c9ffb8a50dbd7c5e8194d02a3ace24ec80fe3e6 (PR)
1. Check liveness of validators at old version: devnet
compatibility::simple-validator-upgrade::liveness-check : 10831 TPS, 2809 ms latency, 5000 ms p99 latency,no expired txns
2. Upgrading first Validator to new version: 8c9ffb8a50dbd7c5e8194d02a3ace24ec80fe3e6 …
```
> [gha] bring back forge compat against devnet

- ecosystem/indexer/src/models/transactions.rs
- ecosystem/indexer/src/token_processor.rs
The code wasn't built for batch transactions, and now it should handle most cases with it.
I ran it locally, but we should check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3541)
> [indexer] Fix token ownership data to work with batching

- crates/aptos-telemetry-service/src/prometheus_push_metrics.rs
…ility with our existing grafana dashboards
This changes some of the metrics label ingestion naming in the telemetry service.
Previously the service was ingesting a numerical value for `peer_role`. Our grafana dashboards expect the attribute to be named `role` and be of type string. Also changed some of the other labels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3519)
> telemetry-service: optimize label naming for readability and compatibility

- Cargo.lock
- state-sync/aptos-data-client/Cargo.toml
- state-sync/aptos-data-client/src/aptosnet/metrics.rs
This PR removes the peer id from various Aptos Data Client metrics. These were useful in a previous life, but now the code has stabilized enough that it's okay not to collect them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3532)
> [Aptos Data Client] Remove peer id from various metrics.

- ecosystem/indexer/src/database.rs
- ecosystem/indexer/src/indexer/fetcher.rs
- ecosystem/indexer/src/indexer/tailer.rs
- ecosystem/indexer/src/indexer/transaction_processor.rs
- ecosystem/indexer/src/main.rs
- ecosystem/indexer/src/models/events.rs
- ecosystem/indexer/src/models/metadata.rs
- ecosystem/indexer/src/models/processor_statuses.rs
- ecosystem/indexer/src/models/token.rs
- ecosystem/indexer/src/models/transactions.rs
- ecosystem/indexer/src/models/write_set_changes.rs
- ecosystem/indexer/src/token_processor.rs
- ecosystem/indexer/src/util.rs
There's a ton of messy indexer code here that's doing unwraps when it shouldn't, or panicking when it shouldn't.  I left one panic on if a batch of transactions isn't found.  Everything else should try until the program ends.
None, but this should be better
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3547)
> [indexer] Fix logic and remove panics and unwraps

- ecosystem/platform/server/app/controllers/it3_profiles_controller.rb
- ecosystem/platform/server/app/controllers/it3s_controller.rb
Flipper doesn't allow actor-specific overrides for negative statements, i.e they only allow overriding `enabled` per actor, not disabled. This means we can't conditionally enable per user for most of our actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3574)
> [CP] Make AIT3 registration positive for flipper

- .github/workflows/continuous-e2e-chaos-test.yaml
- .github/workflows/continuous-e2e-compat-test.yaml
- .github/workflows/continuous-e2e-performance-test.yaml
- .github/workflows/continuous-e2e-single-vfn-test.yaml
- testsuite/fixtures/testDashboardLink.fixture
- testsuite/fixtures/testMain.fixture
- testsuite/forge_test.py
- testsuite/run_forge.sh
`forge-$i` clusters have been replaced by `forge-big-$i` (new) clusters, which have 4x the maximum capacity. This PR removes all the original `forge-$i` clusters from CI and land-blocking Forge. 
Land-blocking forge is load-balanced between `forge-big-0` and `forge-big-2`.
Continuous forge runs on `forge-big-1`
To roll this out, I'll keep the old clusters around for at least a few days since unmerged PRs using old `run_forge.sh` will continue to hit the old clusters. After that, we'll either need devs to rebase on main to bring in the new script changes to use the new clusters, or we turn on the new python forge wrapper (which simply selects from all clusters named `forge-*`
2/3 of land-blocking forge has been scheduled on `forge-big-$i` clusters.
- - - …
> [forge] decommission old clusters

- ecosystem/typescript/sdk/src/transaction_builder/builder.ts
If address has preceding zeros, e.g, 0x027c2f73843c53f046be43a18cc7c2c20ad956d1708d51e478a89ea1d755c526, fetchABI will return address without zeros, so that it will fail when find a function with full-length address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3569)
> fix(ts-sdk): failed to find function in abiMap if address have preceding zeros

- ecosystem/platform/server/test/controllers/projects_controller_test.rb
Fixes this issue:
```
Error:
ProjectsControllerTest#test_view_all_projects:
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (10, 4, null, admin, t, 2022-08-29 17:06:58.130081, 2022-08-29 17:06:58.130081).
test/controllers/projects_controller_test.rb:21:in `block (2 levels) in <class:ProjectsControllerTest>'
test/controllers/projects_controller_test.rb:20:in `times'
test/controllers/projects_controller_test.rb:20:in `block in <class:ProjectsControllerTest>'
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3592)
> [community] Fix flaky test.

- ecosystem/platform/server/app/views/layouts/_application.html.erb
- ecosystem/platform/server/app/views/static_page/incentivized_testnet.html.erb
- ecosystem/platform/server/config/routes.rb
- ecosystem/platform/server/test/controllers/it3_profiles_controller_test.rb
- ecosystem/platform/server/test/controllers/it3s_controller_test.rb
- Show the IT3 leaderboard at /it3
- Remove the global IT3 announcement
- Change register CTA to "view results" on IT landing page
- Skip IT3 registration tests
Manual
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3590)
> [community] Update IT3 registration pages.

- .github/workflows/continuous-e2e-compat-test.yaml
- testsuite/forge/src/runner.rs
This PR makes it such that we always run genesis with the same version as the nodes at network startup. 
Specifically, within the test runner, make `genesis_version (of the genesis process) == initial_version (of the validators)`. Previously, `initial_version` was being set to the oldest image provided, whereas `genesis_version` was being set to the newest image. This means that for compat tests, we were spinning up genesis and validators at different versions. While this scenario is not likely, it technically constitutes a breaking/backwards incompatible change to genesis.
For example, this run https://github.com/aptos-labs/aptos-core/runs/8073630388?check_suite_focus=true (and many like it), is running compat upgrading image tags `devnet` ==> `279066e8c63360acf9fa722d12d519cd655badca`. …
> [forge] always run genesis from initial_version

- terraform/helm/monitoring/files/prometheus.yml
Previously, cAdvisor scrape config was dropping metrics that did not match the deployment namespace if `fullKubernetesScrape = false` (which recently became the default value). This doesn't work in Forge case, since swarms are created in non-default namespaces.
Apply and check that we get cAdvisor metrics. This un-breaks the Forge metrics checking for CPU and memory
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3601)
> [helm][monitoring] do not drop other namespaces for cadvisor

- ecosystem/platform/server/app/views/leaderboard/it3.html.erb
Fix typo in Explorer Address URL from `address` to `account` within AIT-3 Validator Status table
Ensure URL is correct when clicking rows within AIT-3 Validator Status table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3614)
> [CP] Fix typo in Explorer Address URL

- ecosystem/typescript/sdk/.eslintrc.js
- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/package.json
The newer TS version, linter, and specific lint (as per https://stackoverflow.com/a/61555310/3846032.) seems to fix the previously broken `yarn lint` run.
```
rm yarn.lock && rm -rf node_modules/
yarn install
yarn lint
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3617)
> Fix yarn lint by upgrading TS and linter versions

- Cargo.lock
- Cargo.toml
- docker/build-rust-all.sh
- docker/rust-all.Dockerfile
- ecosystem/node-checker/Cargo.toml
- ecosystem/node-checker/src/bin/aptos-node-checker.rs
- ecosystem/node-checker/src/evaluator/types.rs
- ecosystem/node-checker/src/evaluators/direct/api/node_identity.rs
- ecosystem/node-checker/src/lib.rs
- ecosystem/node-checker/vfn-check-client/Cargo.toml
- ecosystem/node-checker/vfn-check-client/README.md
- ecosystem/node-checker/vfn-check-client/src/big_query.rs
- ecosystem/node-checker/vfn-check-client/src/check.rs
- ecosystem/node-checker/vfn-check-client/src/helpers.rs
- ecosystem/node-checker/vfn-check-client/src/main.rs
We will use this tool to periodically check how the VFNs in AIT 3 and beyond are going.
Run local NHC:
```
cargo run -p aptos-node-checker -- server run --baseline-node-config-paths ~/a/internal-ops/infra/apps/node-checker/configs/ait3_vfn.yaml --listen-address 0.0.0.0
```
Run local testnet:
```
cargo run -p aptos -- node run-local-testnet --with-faucet --faucet-port 8081 --force-restart --assume-yes
```
Run the tool:
```
cargo run -p aptos-vfn-check-client -- --node-address http://127.0.0.1:8080 --nhc-address http://127.0.0.1:20121 --nhc-baseline-config-name ait3_vfn --big-query-key-path ~/a/internal-ops/helm/observability-center/files/bigquery-cron-key.json
```
Output: https://gist.github.com/banool/cf54430db439e216e5216d884d83b44b.
Submitting to BigQuery instead:
```
cargo run -p …
```
> Add tool that calls NHC for all VFNs on chain

- config/src/config/mempool_config.rs
- mempool/src/core_mempool/mod.rs
- mempool/src/core_mempool/transaction.rs
- mempool/src/core_mempool/transaction_store.rs
- mempool/src/counters.rs
- mempool/src/tests/core_mempool_test.rs
- types/src/transaction/mod.rs
This can prevent larger transactions from adding memory pressure or OOMing the node.
Did _not_ add a per-user limit. This assumes (max txn size) * (max txn per user) << max capacity in bytes.
Also noticed we are now caching BCS txn bytes which is unnecessary and removed this.
Added unit test for capacity in bytes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3608)
> [mempool] add max capacity in bytes

- config/src/config/mempool_config.rs
- mempool/src/core_mempool/mod.rs
- mempool/src/core_mempool/transaction.rs
- mempool/src/core_mempool/transaction_store.rs
- mempool/src/counters.rs
- mempool/src/tests/core_mempool_test.rs
- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/interface/network.rs
- testsuite/forge/src/interface/swarm.rs
- testsuite/forge/src/runner.rs
- testsuite/forge/src/success_criteria.rs
- testsuite/forge/src/test_utils/consensus_utils.rs
- testsuite/smoke-test/src/aptos_cli/validator.rs
- testsuite/smoke-test/src/full_nodes.rs
- testsuite/smoke-test/src/state_sync.rs
- testsuite/smoke-test/src/storage.rs
- testsuite/smoke-test/src/txn_broadcast.rs
- types/src/transaction/mod.rs
previously we were catching panics, and when that happens no info other than that there was a failure was shown.
I don't see any reasons to catch panics, after making this change, we actually see the panic message.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3558)
> [forge] Disable panic catching and enable wait for catchup

- .github/workflows/continuous-e2e-release-test.yaml
Pre-release tests are failing with GH timeout. We need to figure out a way to increase the GH workflow timeout but running it for 5 hours for now to make it stable.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3637)
> [Forge] Pre-release test to run for 5 hours for now

- ecosystem/typescript/sdk/jest.config.js
- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/aptos_account.test.ts
- ecosystem/typescript/sdk/src/aptos_account.ts
- ecosystem/typescript/sdk/src/bytes_to_hex.test.ts
- ecosystem/typescript/sdk/src/bytes_to_hex.ts
- ecosystem/typescript/sdk/src/generated/core/request.ts
- ecosystem/typescript/sdk/src/hex_string.test.ts
- ecosystem/typescript/sdk/src/hex_string.ts
- ecosystem/typescript/sdk/src/index.ts
- ecosystem/typescript/sdk/src/transaction_builder/aptos_types/authentication_key.ts
- ecosystem/typescript/sdk/src/transaction_builder/aptos_types/index.ts
- ecosystem/typescript/sdk/src/transaction_builder/aptos_types/transaction.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder.ts
- ecosystem/typescript/sdk/src/transaction_builder/transaction_builder.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/transaction_vector.test.ts
- ecosystem/typescript/sdk/tsconfig.json
Removes the `buffer` dependency from the Aptos TypeScript SDK, helping to reduce bundle size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3456)
> Remove 'buffer' dependency from Typescript SDK

- ecosystem/platform/server/app/controllers/it3_profiles_controller.rb
Fixes this issue:
```
AbstractController::DoubleRenderError
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3643)
> [community] Fix DoubleRenderError.

- developer-docs-site/docs/tutorials/first-transaction.md
Remove the extra 'a'. See pic:
yarn start and verified in browser
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3624)
> [doc] Remove the extra 'a' in first transaction TS snippet

- ecosystem/typescript/sdk/examples/typescript/transfer_coin.ts
The second `waitForTransaction` wrongly waits on the first transaction as the `txnHash` has not been re-assigned.
This leads to a potential race condition where the wrong balances are printed at the end of the script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3642)
> fix `waitForTransaction` bug in `transfer_coin` example

- config/src/config/firehose_streamer_config.rs
- ecosystem/sf-indexer/firehose-stream/src/runtime.rs
Firehose is sending us starting block instead of starting version. Switching to starting version is non trivial on the firehose side and will incur additional processing, so we should just change it to starting block on our side. We are keeping starting_version in the config to keep backward compatibility. 
Node still runs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3607)
> [Indexer] Switch starting version to starting block

- ecosystem/node-checker/vfn-check-client/src/check.rs
This will be helpful for further processing / testing, e.g. for continuous txn emission.
```
cargo run -p aptos-vfn-check-client -- --node-address https://ait3.aptosdev.com --nhc-address https://node-checker.prod.gcp.aptosdev.com --nhc-baseline-config-name ait3_vfn --big-query-key-path ~/a/internal-ops/helm/observability-center/files/bigquery-cron-key.json | jq .
```
Sample of output:
```json
"17e6eeec824c4ebe71f276aeb2115b63defcd8b5898663074d02c6db6494991b": [
{
"result": {
"type": "success",
"evaluation_summary": {
"evaluation_results": [
{
"headline": "Chain ID reported by baseline and target match",
"score": 100,
"explanation": "The node under investigation reported the same Chain ID 47 as is reported by the baseline node",
"evaluator_name": "node_identity",
"category": "api", …
```
> [vfn-check-client] Output address of node in success case

- crates/aptos-telemetry-service/src/jwt_auth.rs
- crates/aptos-telemetry-service/src/log_ingest.rs
- crates/aptos-telemetry-service/src/prometheus_push_metrics.rs
- crates/aptos-telemetry-service/src/types/auth.rs
- crates/aptos-telemetry/src/sender.rs
- Set default role type in AuthRequest for backwards compatibility
- Set proper with_auth roles for prometheus and log ingest
- Bug fix: Remove multiple auth token set in header for push metrics endpoint
- Bug fix: Add ability to handle multiple auth tokens in header at service as fix for currently running validators
Hot fix was deployed and I validated that the service is working fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3441)
> [aptos-telemetry] set default for role type and auth bug fix

- .github/workflows/continuous-e2-account-creation-state-sync.yaml
- crates/transaction-emitter-lib/src/emitter/mod.rs
- crates/transaction-emitter-lib/src/wrappers.rs
- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/interface/network.rs
- testsuite/forge/src/runner.rs
- testsuite/forge_test.py
- testsuite/run_forge.sh
- testsuite/smoke-test/src/txn_emitter.rs
- testsuite/testcases/src/lib.rs
- testsuite/testcases/src/network_bandwidth_test.rs
- testsuite/testcases/src/network_latency_test.rs
- testsuite/testcases/src/network_loss_test.rs
- testsuite/testcases/src/network_partition_test.rs
- testsuite/testcases/src/performance_test.rs
- testsuite/testcases/src/performance_with_fullnode_test.rs
- testsuite/testcases/src/state_sync_performance.rs
- Moved duration out of load test params, and into Forge.
- load tests is now specified together with SuccessCriteria, and not via CLI as duration is.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3609)
> [forge] Add account creation continuous forge test and having loadtest params per test

- ecosystem/platform/server/app/components/icon_tooltip_component.html.erb
- ecosystem/platform/server/app/components/table_header_column_component.rb
- ecosystem/platform/server/app/components/table_row_column_component.rb
- ecosystem/platform/server/app/helpers/leaderboard_helper.rb
- ecosystem/platform/server/app/views/leaderboard/it1.html.erb
- ecosystem/platform/server/app/views/leaderboard/it2.html.erb
- ecosystem/platform/server/app/views/leaderboard/it3.html.erb
Make adjustments to AIT tables to prevent horizontal scrollbar from appearing on large screens:
- Font sizing, padding adjustments
- Integrate new `truncate_address` function which splits a string down the middle with an ellipsis, leaving 4 characters on each side (see Explorer). 
- Verify tables on large screens do not show horizontal scrollbars at full width 
- Check truncated ellipsis formatting for addresses
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3648)
> [CP] Adjust tables to prevent horizontal scrollbar on large screens

- ecosystem/node-checker/vfn-check-client/src/check.rs
- ecosystem/node-checker/vfn-check-client/src/main.rs
https://aptoslabs.pagerduty.com/incidents/Q2Z1NI1YGFP465. In short, there can be invalid addresses on chain right now. This adds code to handle that case.
This was failing before:
```
cargo run -p aptos-vfn-check-client -- --node-address https://ait3.aptosdev.com --nhc-address https://node-checker.prod.gcp.aptosdev.com --nhc-baseline-config-name ait3_vfn --big-query-key-path ~/a/internal-ops/helm/observability-center/files/bigquery-cron-key.json
```
Output snippet:
```
"86b5e89746c45648735ef61c722debec0c35e051db941c783a82756d77a54f8c": [
{
"result": {
"type": "invalid_network_address"
},
"timestamp": {
"secs": 1661902010,
"nanos": 37977000
},
"vfn_address": null
}
],
```
- - - …
> Handle when there are invalid network addresses on chain

- ecosystem/platform/server/app/components/icon_tooltip_component.html.erb
- ecosystem/platform/server/app/helpers/leaderboard_helper.rb
- ecosystem/platform/server/app/views/leaderboard/it1.html.erb
- ecosystem/platform/server/app/views/leaderboard/it2.html.erb
- ecosystem/platform/server/app/views/leaderboard/it3.html.erb
Creates a hidden dummy element containing full address to allow for users to Ctrl+F the full address and land on the appropriate row. 
`Ctrl+F` / browser search for full address and ensure it reveals the appropriate row with truncated address. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3666)
> [CP] Create hidden dummy address to allow for Ctrl+F full string

- mempool/src/core_mempool/ttl_cache.rs
There is an extreme (and rare) edge case whereby if the expiration time is too large, we might not be able to insert a new transaction into the `ttl_index` but it could still exist in `data` (as it was never removed). To avoid this, we remove from `ttl_index` and `data` together, and insert into them together. This is a very rare case (and unlikely in practice), but better safe than sorry 😄 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3671)
> [Mempool] Small consistency fix.

- aptos-move/e2e-move-tests/tests/code_publishing.rs
- aptos-move/framework/aptos-framework/sources/account.move
- aptos-move/framework/aptos-framework/sources/resource_account.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
* add create_resource_address due to 1) popular demand and 2) improved testability. I don't think anyone should use this in production to compute an address of an already created account, that seems bad, but it can serve some purposes.
* support the ability to create a resource account and fund it (for the legacy flow)
* support the ability to create a resource account and publish modules to it -- note this one explicitly does not support funding because that should be something that can be done when transferring over the ownership cap if that is desirable
I'd like to get this in the cut for Wednesday devnet if possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-c …
> [framework] improve resource account

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/src/aptos_client.ts
This PR exposes the detailed errors that are returned from APIs. Instead of requiring developers to parse the `error.body`, the `error_code` and `vm_error_code` are directly accessible through a wrapped error class. This PR also makes sure the error thrown carries a meaningful message. Also, in case of errors thrown, the stack trace can now show the correct call stack.
All tests pass. Manually tested error cases. See pic below
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3669)
> feat(ts-sdk): expose API error details

- ecosystem/typescript/sdk/src/aptos_client.ts
`AptosClient.waitForTransactionWithResult` is skipping the sleep, causing many requests per second.
This fixes it
Will test that polling is done once per second as expected
Closes #3553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3554)
> [sdk][typescript] fix unthrottled requests in `waitForTransactionWithResult`

- terraform/helm/fullnode/templates/ingress.yaml
- terraform/helm/fullnode/values.yaml
For operators that are running a kubernetes cluster, it is common to have many services exposed publicly via ingress resources. This PR enables these operators to leverage their existing ingress controller for fullnode deployments.
I have these changes deployed to my cluster already and everything is working as expected
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2651)
> add ingress support to fullnode helm chart

- .github/workflows/build-images.yaml
- docker/docker-bake-rust-all.hcl
- docker/docker-bake-rust-all.sh
- docker/retag-rust-images.sh
- docker/rust-all.Dockerfile
This optimizes our docker builds a bit.
1. First runs the image building step in a single step / docker invocation instead of 3 seperate ones. This seems to speed things a bit.
2. Also we're changing from an `inline` cache to `registry,mode=max` as cache strategy. The main difference between inline and the mode=max one is that inline will only cache the final docker layers whereas the mode=max  one will cache each layer, incl. intermediate ones seperately.
3. We're using a seperate `retag` step via `crane` which simply retags some of the images from <branch_name> to <git_sha> which is also used as cache source. Had to do this in a seperate step since docker buildx can only push one cache manifest per image by itself.
4. It removes the cache mounts from the step that compiles the rust code …
> cicd: optimize docker build caching

- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/local/node.rs
- testsuite/forge/src/interface/node.rs
- testsuite/smoke-test/src/state_sync.rs
- testsuite/testcases/src/forge_setup_test.rs
- testsuite/testcases/src/state_sync_performance.rs
This unbreaks the `state_sync` k8s forge test.
Previously, the `K8sNode::clear_storage` method deleted the underlying storage volume. This was finicky because:
* it requires scaling down the workload, deleting the volume, then spinning the workload back up (and re-create the volume in the case of validators, since the lifecycle of the storage volume is decoupled from that of the validators. This is not the case for fullnodes)
* it's really async
This PR changes the clear_storage logic such that it execs into the running pod and delete its storage via path, the same way `LocalNode::clear_storage` does.
Run Forge with the `forge_setup` and `state_sync` tests
- - - …
> [forge] K8sNode::clear_storage deletes paths directly

- testsuite/forge.py
- testsuite/forge_test.py
Fix forward new wrapper was not sanitizing namespaces the way the old wrapper was.
This adds sanitization and testing, also adds to tail command and remove som unused imports
Test plan: This PR #e2e and unittests pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3709)
> [forge] Fix forward namespace sanitization

- ecosystem/platform/server/app/views/leaderboard/it3.html.erb
It was linking to the wrong s3 bucket.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3706)
> [community] Fix incorrect link.

- developer-docs-site/docs/guides/interacting-with-the-blockchain.md
- developer-docs-site/docs/nodes/local-testnet/run-a-local-testnet.md
- developer-docs-site/docs/whats-new-in-docs.md
- developer-docs-site/docusaurus.config.js
Addresses https://github.com/aptos-labs/aptos-core/issues/3646. As part of this I fix the broken links.
Docs: https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks.
```
cd developer-docs-site
yarn build
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3657)
> [docs] Make it a build error if there are broken links

- developer-docs-site/docs/tutorials/first-dapp.md
- developer-docs-site/docs/tutorials/your-first-nft.md
- ecosystem/python/sdk/Makefile
- ecosystem/python/sdk/aptos_sdk/client.py
- ecosystem/python/sdk/examples/common.py
- ecosystem/python/sdk/examples/simple-nft.py
- ecosystem/python/sdk/examples/transfer-coin.py
- ecosystem/python/sdk/poetry.lock
- Make the token functions in the Python SDK work the same as the TS SDK, namely return something on 404 instead of throwing.
- Change the Python SDK to raise an exception instead of assert when response >= 400.
- Format the examples as well.
- Fix tab stuff in the first NFT example.
I have made sure the docs still look good since the section tags moved around.
```
cd ecosystem/python/sdk
curl -sSL https://install.python-poetry.org/ | python3
poetry update
poetry run python -m examples.simple-nft
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3710)
> Fix token client functions, simple-nft in Python SDK

- Cargo.lock
- api/types/src/error.rs
- crates/aptos-rest-client/Cargo.toml
- crates/aptos-rest-client/src/error.rs
- crates/aptos-rest-client/src/lib.rs
- crates/aptos-rosetta/src/error.rs
- ecosystem/indexer/src/indexer/fetcher.rs
The rest client wasn't handling throttles very well, this will now handle throttles.  I suspect we will need to look into this for all of our SDKs.
Additionally, the indexer which caught this issue, will now backoff and go along it's merry way.  Will likely need to tune the numbers later
Tested locally on the indexer
```
2022-08-30T08:11:09.535200Z [tokio-runtime-worker] INFO crates/aptos-rest-client/src/lib.rs:1040 Failed to call API, retrying in 1000ms: Http(429)
2022-08-30T08:11:10.563343Z [tokio-runtime-worker] INFO crates/aptos-rest-client/src/lib.rs:1040 Failed to call API, retrying in 2000ms: Http(429)
2022-08-30T08:11:12.590567Z [tokio-runtime-worker] INFO crates/aptos-rest-client/src/lib.rs:1040 Failed to call API, retrying in 4000ms: Http(429)
2022-08-30T08:11:16.618698Z …
```
> [aptos-rest-client/indexer] Backoff rest client

- .github/workflows/continuous-e2e-single-vfn-test.yaml
The wrong indentation meant the job is not scheduled
Read code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3712)
> [forge] fix wrong indentation in #3493

- api/src/log.rs
5xx are logged at error, and others were logged at debug. Having some 4xx messages in info can be useful.
Simple change in code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3316)
> [api] log 4xx status messages at info (sampled)

- .cargo/config.toml
Fixing this bug
```
warning: lint `clippy::eval_order_dependence` has been renamed to `clippy::mixed_read_write_in_expression`
|
= note: requested on the command line with `-A clippy::eval_order_dependence`
```
`cargo xclippy`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3714)
> [clippy] Remove clippy warning about deprecated name

- ecosystem/platform/server/app/components/header_component.rb
Removes "Network Status" from main navigation as this URL is currently not maintained. Will restore once the new Status Page is ready. 
Ensure "Network Status" no longer exists within main navigation "Network" dropdown.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3689)
> [CP] Remove Network Status from main nav

- crates/aptos/src/account/create.rs
- crates/aptos/src/account/create_resource_account.rs
- crates/aptos/src/account/transfer.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/governance/mod.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/node/mod.rs
- crates/aptos/src/stake/mod.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/aptos_cli/account.rs
- testsuite/smoke-test/src/aptos_cli/validator.rs
- testsuite/smoke-test/src/rosetta.rs
If Rosetta can do it, why not make the CLI estimate the gas parameters accordingly.
Additionally, asks you if you want to spend the estimated amount (when it's more than 1).  You can always provide the gas price in another CLI call which will override that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3440)
> [aptos-cli] Have Aptos CLI estimate gas parameters automatically

- ecosystem/python/sdk/aptos_sdk/client.py
- ecosystem/python/sdk/aptos_sdk/transactions.py
Add a Move package publishing helper to python SDK
Tested with 
```
class Test(unittest.TestCase):
def test_publish_package(self):
client = RestClient("http://localhost:8080/v1")
account = Account.load_key(
"0x883fdd67576e5fdceb370ba665b8af8856d0cae63fd808b8d16077c6b008ea8c")
faucet = FaucetClient("http://localhost:8081", client)
faucet.fund_account(account.address().hex(), 50000)
txn_hash = client.publish_package(
account,
bytes.fromhex("084578616d706c657301000000000000000040314137344146383742383132393043323533323938383036373846304137444637393737373637383734334431434345443230413446354345334238464446388f011f8b08000000000002ff3dccc10ac2300c06e07b9ea2f46ee70b78f0a02f31c6886d74a55d5b1a51417c7713c1915c927cf9c7863ee18d2628b89239187b7ae1da32b18507758eb5e872efa42cc088217462269e60a19ceb7cc9d527bf6 …
```
> [python-sdk] support package publishing

- state-sync/aptos-data-client/src/aptosnet/state.rs
- state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs
- state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_service.rs
Cherry-picking into AIT3. *NOT FOR MAIN*
This PR offers a quick workaround to ignore invalid data advertisements from nodes regarding the availability of state snapshot data. This is because nodes in AIT3 are not running this PR: https://github.com/aptos-labs/aptos-core/commit/31b9148f00a5eefd59bd4536fe8768d6f1de05e2 
I've tested that fast sync works locally in AIT3 when using this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3726)
> [State Sync] Ignore invalid data advertisements for states.

- crates/aptos-rosetta/src/types/objects.rs
- testsuite/smoke-test/src/rosetta.rs
This adds the transaction status to the transaction.  It also adds the VM status for good measure to tell what happened to the transaction
See smoke test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3737)
> [aptos-rosetta] Add failed & vm status to transactions

- Cargo.lock
- crates/aptos/Cargo.toml
Bump to 0.3.3 for the next devnet release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3733)
> [aptos-cli] Bump version to 0.3.3

- config/src/config/storage_config.rs
This PR removes an unused config variable in the `StorageConfig`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3744)
> [Config] Remove unused config variable.

- consensus/src/counters.rs
- consensus/src/epoch_manager.rs
- consensus/src/network.rs
- consensus/src/network_tests.rs
Spawn block retrieval to a dedicated task to not block the epoch manager
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3745)
> [consensus] spawn block retrieval to a dedicated task

- CODEOWNERS
Adding myself as a code owner for the TypeScript implementation of an Aptos account, due to the cryptographic operations there.
...and for other crypto-related things.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3589)
> [codeowners] update CODEOWNERS

- ecosystem/python/sdk/examples/your-coin.py
At present, this example fails because the coin decimals are given as a u64 instead of a u8.
See https://github.com/aptos-labs/aptos-core/blob/49b2991b341e96060aa310c8090e4ee469817697/aptos-move/framework/aptos-framework/sources/managed_coin.move#L54-L60 for reference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3752)
> Correct coin decimal datatype in your-coin.py Python example

- crates/transaction-emitter-lib/src/args.rs
- crates/transaction-emitter-lib/src/emitter/account_minter.rs
- crates/transaction-emitter-lib/src/emitter/mod.rs
- testsuite/smoke-test/src/txn_emitter.rs
Addressing comments left after I landed the PR.
- flags --mempool-backlog and --target-tps are now exclusive
- better accounting of how much coins we create, and whether we have enough
- turned off txn-emitter smoke test, I think it might be that one that is causing flakiness to others (as it is probably creating some connections)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3693)
> txn emitter followup

- Cargo.lock
- consensus/Cargo.toml
Previously some futures related crates are using 0.3.21 and some are using 0.3.23. There is also a known issue in 0.3.23. (see: https://github.com/rust-lang/futures-rs/releases/tag/0.3.24)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3756)
> [Cherry-pick] All futures crates to 0.3.24 

- Cargo.lock
- consensus/Cargo.toml
Previously some futures related crates are using 0.3.21 and some are using 0.3.23. There is also a known issue in 0.3.23. (see: https://github.com/rust-lang/futures-rs/releases/tag/0.3.24)
test_rpc passes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3754)
> [futures] pin to 0.3.24

- .github/workflows/grafana-sync.yaml
- CODEOWNERS
grafana-sync works: https://github.com/aptos-labs/aptos-core/pull/3758 (it even updates its previous PRs by force push!)
this just updates the pull request title and body to be more descriptive.
Also add codeowners for dashboards and github actions
just do it 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3759)
> [gha] better pull request title and body

- Cargo.lock
- Cargo.toml
- crates/aptos-network-checker/Cargo.toml
- crates/aptos-network-checker/src/args.rs
- crates/aptos-network-checker/src/check_endpoint.rs
- crates/aptos-network-checker/src/lib.rs
- network/src/transport/mod.rs
This is a resurrection of this tool: https://github.com/diem/diem/blob/latest/config/management/operational/src/network_checker.rs. I just yanked it, removed the code related to checking multiple endpoints (since we already do the validator set discovery in another tool), made it natively async, and adapted it to our new libraries.
See https://github.com/aptos-labs/aptos-core/pull/3746
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3740)
> Restore `aptos-network-checker`

- Cargo.lock
- ecosystem/node-checker/Cargo.toml
- ecosystem/node-checker/doc/spec.json
- ecosystem/node-checker/doc/spec.yaml
- ecosystem/node-checker/src/configuration/mod.rs
- ecosystem/node-checker/src/configuration/types.rs
- ecosystem/node-checker/src/evaluator/traits.rs
- ecosystem/node-checker/src/evaluators/build_evaluators.rs
- ecosystem/node-checker/src/evaluators/direct/api/node_identity.rs
- ecosystem/node-checker/src/evaluators/direct/mod.rs
- ecosystem/node-checker/src/evaluators/direct/noise/handshake.rs
- ecosystem/node-checker/src/evaluators/direct/noise/mod.rs
- ecosystem/node-checker/src/metric_collector/traits.rs
- ecosystem/node-checker/src/runner/blocking_runner.rs
- ecosystem/node-checker/src/runner/traits.rs
- ecosystem/node-checker/src/server/api.rs
- ecosystem/node-checker/src/server/run.rs
- ecosystem/node-checker/ts-client/CHANGELOG.md
- ecosystem/node-checker/ts-client/package.json
- ecosystem/node-checker/ts-client/src/index.ts
- ecosystem/node-checker/ts-client/src/models/EvaluatorArgs.ts
- ecosystem/node-checker/ts-client/src/models/HandshakeEvaluatorArgs.ts
- ecosystem/node-checker/ts-client/src/schemas/$EvaluatorArgs.ts
- ecosystem/node-checker/ts-client/src/schemas/$HandshakeEvaluatorArgs.ts
- ecosystem/node-checker/ts-client/src/services/DefaultService.ts
This PR adds an evaluator to NHC that uses aptos-network-checker. As part of this, I've added support to NHC for optionally providing a public key to check node. Accordingly, I've added support for evaluators to validate the input args, e.g. so the handshake evaluator can ensure that public key was provided.
Some questions:
- In `src/configuration/types.rs` I have a function that takes the regular address + noise port + public key and turns it into a `NetworkAddress`. This function can fail in a few ways, but I think the main way it could fail is if the DNS look up fails. At this point however I've already checked that. How else could this realistically fail?
Generate appropriate config:
```
cargo run -p aptos-node-checker -- configuration create --configuration-name ait3_fullnode …
```
> [NHC] Add evaluator that uses `aptos-network-checker`

- Cargo.lock
- crates/aptos-genesis/Cargo.toml
- crates/aptos-genesis/src/builder.rs
- testsuite/forge-cli/src/README.md
- testsuite/forge/src/backend/local/node.rs
- testsuite/forge/src/backend/local/swarm.rs
This PR adds additional logs and instructions for running a faucet inside local swarms and minting test tokens. This is useful for developers who wish to build, test and deploy local networks and develop on top of them. The README now also contains instructions for doing these things (e.g., running a faucet and minting tokens).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3730)
> [Forge] Add instructions for running a faucet and minting inside local swarms.

- Cargo.lock
- aptos-move/framework/cached-packages/build.rs
- aptos-move/framework/cached-packages/src/lib.rs
- aptos-move/framework/src/aptos.rs
- aptos-node/Cargo.toml
- aptos-node/src/main.rs
- consensus/Cargo.toml
- consensus/src/experimental/tests/phase_tester.rs
- consensus/src/round_manager.rs
- consensus/src/test_utils/mock_state_computer.rs
- crates/aptos/src/common/utils.rs
- crates/transaction-emitter/Cargo.toml
- crates/transaction-emitter/src/diag.rs
- execution/executor-benchmark/Cargo.toml
- execution/executor-benchmark/src/main.rs
We're making the Aptos CLI for everyone, so not everyone has to access the CLI commands via
Linux!  This allows users to run all Aptos CLI commands in Windows.  Note, not all of them are
tested, but it seems a local testnet node runs fine locally on my windows computer.
This removes the colored terminal outputs used in consensus and transaction builder, as well
as puts jemalloc behind a flag for unix since it isn't supported on windows.
Additionally, the move packaging system seemed to put too much on the stack, and the whole program crashed, this just does a little hack for the move packaging to continue to build locally.
This successfully allows me to run `aptos.exe` to run commands like `account list`, `init`, etc on a windows machine without issue.
```
PS Z:\git\aptos-core> …
```
> [aptos-node/cli] Add windows compatibility

- Cargo.lock
- aptos-move/aptos-gas/src/aptos_framework.rs
- aptos-move/framework/Cargo.toml
- aptos-move/framework/aptos-stdlib/sources/hash.move
- aptos-move/framework/src/natives/hash.rs
- aptos-move/framework/src/natives/mod.rs
Added Keccak-256 in exchange for a Mountain Dew Zero tomorrow from @davidiw.
Tested the output on two hashes. Can always add more.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3755)
> [crypto+move] add support for Keccak-256 hashing

- Cargo.lock
- consensus/Cargo.toml
- consensus/src/counters.rs
- consensus/src/epoch_manager.rs
This PR adds a simple interval stream to the problematic tokio::select loop. We can see if it ever get's hit at the grind.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3792)
> [Consensus] Debug tokio loop using progress check timers.

- ecosystem/typescript/sdk/src/aptos_client.ts
- ecosystem/typescript/sdk/src/token_client.test.ts
Just a few small changes.
```
yarn test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3807)
> [TS SDK] Simplify parseApiError, fix NFT test, add comment for retry behavior

- .github/workflows/cli-release.yaml
- scripts/cli/build_cli_release.ps1
- scripts/cli/build_cli_release.sh
Originally I was trying to build on ubuntu-latest with the windows toolchain to avoid writing another script for building the CLI, but I realized that's silly, this is simpler and more native to Windows.
This is only possible now because of https://github.com/aptos-labs/aptos-core/pull/3751.
I confirmed that the built CLI works on Windows 11. I haven't been able to test `run-local-testnet` because I haven't been able to get my hands on an x86_64 machine (this particular command doesn't work under ARM windows, it just exits). Greg tested this as working earlier though, so we should be good there (and it's not relevant to this particular PR).
On a Windows machine:
```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
.\scripts\cli\build_cli_release.ps1
```
I tested the …
> Add CI to build aptos CLI for Windows

- crates/aptos-logger/src/aptos_logger.rs
This adjusts the log level for remote logs from error -> warn , so that we also ship warn logs. This gives us more signal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3808)
> [observabilty] ship warn logs via remote telemetry

- .github/workflows/copy-images-to-dockerhub.yaml
This changes the structure of the copy images to dockerhub job to avoid running into github rate limits.
It uses the wait-for-check action to wait for image builds to have been completed.
Previously it was doing so seperately for each job in a matrix build and did so every 10 seconds. Now it only awaits once for all matrix job builds and only every 30 seconds.
This should fix the problem. This should reduce the number of requests this job/step makes by factor 18x (6 matrix -> 1 step and 10sec polling to 30sec polling. I.e. 6x3 = 18x).
I also checked via the humio logs and found that in the last 12 hours whenever we ran into the rate limiting issue this job/workflow was the trigger of the rate limit. …
> cicd: avoid reaching github actions api rate limit

- crates/aptos-logger/src/aptos_logger.rs
Cherry-pick logging level warn for remote logs into testnet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3812)
> [cherry-pick] remote logs as log level warn

- ecosystem/typescript/sdk/src/bytes_to_hex.ts
The spread operator of Uint8Array doesn't work well with tsdx. This PR gets rid of the spread operator. Will replace tsdx in another PR.
Make sure all tests pass
Packed a local package and make sure examples pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3806)
> fix(ts-sdk): get rid of spread operator for Uint8Array

- aptos-move/aptos-gas/src/aptos_framework.rs
- aptos-move/aptos-gas/src/natives.rs
- aptos-move/aptos-gas/src/params.rs
This allows one to designate gas parameters as being optional in the gas macros by putting the `optional` keyword before the key for the on-chain entry. Such parameters will default to 0 if their corresponding entry cannot be found on-chain.
Also fixes the issue introduced by https://github.com/aptos-labs/aptos-core/pull/3755 so it doesn't need to be reverted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3816)
> [gas] allow gas parameters to be optional

- developer-docs-site/docs/guides/basics-life-of-txn.md
under "Client submits a transaction" on [this page](https://aptos.dev/guides/basics-life-of-txn), in the table of raw transaction fields, "Chain ID" links to /aptos/aptos/... instead of /aptos-core/aptos-labs/...
thanks to egormajj, who reported this on Discord ☺️
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3729)
> fix broken link: "Chain ID" to chain_id.rs

- developer-docs-site/docs/guides/system-integrators-guide.md
on [this page](https://aptos.dev/guides/system-integrators-guide), clicking "Publish your first Move module" gives a 404 error
/your-first-move-module => /first-move-module
reported by egormajj on Discord
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3798)
> fix broken link

- .dockerignore
- docker/build-rust-all.sh
This just ensures that the build flags we set there are included in the Docker build. This means we don't need to set `RUSTFLAGS` explicitly like we were doing.
CI, it'll fail if the tokio unstable cfg flag isn't included, so we'll know if it's working that way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3831)
> Ensure .cargo is included in docker build

- aptos-node/src/lib.rs
- aptos-node/src/log_build_information.rs
This should make it easier to know what we're running. The telemetry crate debug logs the build information as it sends it already, but printing it at startup at info level ensures we get it when debug logs are disabled. The feature information previously wasn't logged anywhere.
Without a feature enabled:
```
cargo run -p aptos-node -- --test
```
```
2022-09-03T18:26:33.890264Z [main] INFO aptos-node/src/print_build_information.rs:21 Build information:
2022-09-03T18:26:33.890493Z [main] INFO aptos-node/src/print_build_information.rs:24 build_branch:
2022-09-03T18:26:33.890509Z [main] INFO aptos-node/src/print_build_information.rs:24 build_cargo_version: cargo 1.63.0 (fd9c4297c 2022-07-01)
2022-09-03T18:26:33.890609Z [main] INFO aptos-node/src/print_build_information.rs:24 …
```
> Log build + feature information at startup in aptos node

- .github/workflows/run-forge.yaml
We shouldn't default IMAGE_TAG to GIT_SHA on the workflow level. Rather this defaulting logic is already implemented more or less in forge.py itself.  The current defaulting to GIT_SHA is responsible for the issue discussed here https://aptos-org.slack.com/archives/C03EP0XM99D/p1662257852595839?thread_ts=1662238231.302019&cid=C03EP0XM99D which makes the forge.py script think the user set explicitly an image_tag which isn't actually the case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3846)
> cicd: do not default IMAGE_TAG to GIT_SHA on the workflow level

- ecosystem/platform/server/app/notifications/base_notification.rb
- ecosystem/platform/server/test/notifications/governance_proposal_notification_test.rb
Fixes this error:
```
Error:
GovernanceProposalNotificationTest#test_is_not_delivered_by_email_if_preference_is_true_but_user_does_not_have_a_confirmed_email:
ArgumentError: SMTP To address may not be blank: []
app/jobs/application_job.rb:19:in `block (2 levels) in <class:ApplicationJob>'
app/jobs/application_job.rb:14:in `block in <class:ApplicationJob>'
test/notifications/governance_proposal_notification_test.rb:46:in `block (3 levels) in <class:GovernanceProposalNotificationTest>'
test/notifications/governance_proposal_notification_test.rb:45:in `block (2 levels) in <class:GovernanceProposalNotificationTest>'
test/notifications/governance_proposal_notification_test.rb:44:in `block in <class:GovernanceProposalNotificationTest>'
```
- - - …
> [community] Only send email notifications if email confirmed.

- crates/aptos-build-info/build.rs
- crates/aptos-build-info/src/lib.rs
The shadow rs docs misleadingly imply that `BUILD_RUST_CHANNEL` has this information, but in reality it's the Rust channel (like the name implies). This PR adds a key to the build info showing whether the build is a release or debug build.
```
cargo run -p aptos-node --features failpoints -- --test
```
```
cat /private/var/folders/w_/0mh2yzrs5fx2hknmdqxpz40w0000gn/T/514ea5cfb3783e98e7eea9cef2c3af26/validator.log | grep -o -E 'is_release_build": "false"'
is_release_build": "false"
```
```
cargo run -p aptos-node --release --features failpoints -- --test
```
```
cat /private/var/folders/w_/0mh2yzrs5fx2hknmdqxpz40w0000gn/T/514ea5cfb3783e98e7eea9cef2c3af26/validator.log | grep -o -E 'is_release_build": "true"'
is_release_build": "true"
```
```
$ cargo run -p aptos-node --features failpoints …
```
> Include additional build info: release vs debug, tokio unstable usage, build profile

- Cargo.lock
- aptos-move/aptos-gas/Cargo.toml
- aptos-move/e2e-move-tests/tests/lazy_natives.rs
- aptos-move/gas-algebra-ext/Cargo.toml
- aptos-move/move-deps/Cargo.toml
This enables the new `lazy_natives` feature for the Aptos VM. With this landed, we should be able to avoid staged rollout for adding new native Move functions.
Add a test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3868)
> [aptos-vm] Enable lazy_natives feature and add test case

- terraform/fullnode/aws/addons.tf
- terraform/fullnode/aws/auth.tf
- terraform/fullnode/aws/fullnode/values.yaml
- terraform/fullnode/aws/main.tf
Add back ALB ingress controller as its own helm chart. It was previously removed
External-DNS is its own helm chart as well now. This makes things easier to manage and upgradable if they are not bundled into the same helm chart like before.
Also we should consider merging all these special charts together, or removing them. AWS fullnode TF invokes two helm charts both named `fullnode`, but the one embedded in AWS folder is actually just special AWS addons, including external-dns, alb ingress controller, monitoring. The first two can be standalone helm charts invoked as they are in this PR. Monitoring chart we have our own separate chart for that as well
Apply to fullnode cluster
- - - …
> [tf/helm][fullnode] add back alb ingress and external-dns

- aptos-move/framework/aptos-stdlib/sources/any.move
- aptos-move/framework/aptos-token/sources/property_map.move
- aptos-move/framework/aptos-token/sources/token.move
we can directly read the value in the original type on chain as shown the in unit test
add a unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3313)
> [Token] enable PropertyMap to read primitive types

- ecosystem/node-checker/src/configuration/types.rs
- ecosystem/node-checker/src/evaluators/build_evaluators.rs
- ecosystem/node-checker/src/evaluators/direct/api/mod.rs
- ecosystem/node-checker/src/evaluators/direct/api/node_identity.rs
- ecosystem/node-checker/src/evaluators/direct/api/state_sync.rs
- ecosystem/node-checker/src/evaluators/direct/api/transaction_availability.rs
- ecosystem/node-checker/src/evaluators/metrics/state_sync/version.rs
- ecosystem/node-checker/src/runner/blocking_runner.rs
This PR adds a version of the state sync evaluator that uses the API, vs the data from the metrics port.
I chose to keep the metrics based version of this evaluator, just in case there are setups where the metrics port is open but not the API port. Though I don't think it'll see as much use, so I rename it and steal its name for the new API based version. We can delete it later if we decide it's not useful.
Generate appropriate config:
```
cargo run -p aptos-node-checker -- configuration create --configuration-name devnet_fullnode --configuration-name-pretty "Devnet Fullnode Checker" --url http://fullnode.devnet.aptoslabs.com --api-port 80 --evaluators api_latency api_transaction_availability state_sync_version --target-tps 1200 > …
```
> [NHC] Add state sync evaluator that leverages the API

- crates/aptos-genesis/src/config.rs
- crates/aptos/src/op/key.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/network.rs
Extract key command wasn't loading the network key, and was
trying to load Ed25519 keys, which was wrong
The extracted value should be the same exact as the public key.
Additionally, requires a host to be added to build a network address
Resolves https://github.com/aptos-labs/aptos-core/issues/2372
```
$ cat private-key.txt.pub
6638222DA2225F4E72F2C57775BCF040A20E635CC885B64E3D17AA05C39E1325%
$ aptos key extract-peer --host example.com:6180 --public-network-key-file private-key.txt.pub --output-file extracted-peer
"extracted-peer" already exists, are you sure you want to overwrite it? [yes/no] >
yes
{
"Result": {
"6638222da2225f4e72f2c57775bcf040a20e635cc885b64e3d17aa05c39e1325": {
"addresses": [
"/dns/example.com/tcp/6180/noise-ik/0x6638222da2225f4e72f2c57775bcf040a20e635cc885b64e3d17aa05 …
```
> [aptos-cli] Fix extract key command

- testsuite/forge.py
- testsuite/forge_test.py
Assert that if we're trying to use failpoints via `FORGE_ENABLE_FAILPOINTS` env var, that the image tags are correct, if we're manually specifying image tags
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3890)
> [forge] assert image tags have prefix if profile or feature

- testsuite/forge.py
- testsuite/forge_test.py
To use failpoints with the local test runner against the k8s backend, we need to `cargo run --features failpoints`
Run it and the command looks right
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3814)
> [forge] cargo run with failpoints with local test runner

- crates/aptos-rest-client/src/lib.rs
- crates/aptos/src/node/analyze/fetch_metadata.rs
fixing #3871 issue
```
% cargo run -p aptos -- node analyze-validator-performance --analyze-mode=network-health-over-time --url=http://34.176.214.8 --start-epoch=0 --end-epoch=36 
Oldest full epoch that can be retreived is 35 
Fetching 535419 to 886531 sequence number, wanting epochs [35, 36), last version: 224127645 and epoch: 127
Network health over epochs [35, 35]:
epoch    | reliable   | r low vote | unreliable | only vote  | down(cons) | rounds   | failure rate
35       | 135        | 23         | 14         | 1          | 59         | 9306     | 0.58027077
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3874)
> [cli] Fix analyze-validators when pruning deletes oldest events

- ecosystem/platform/server/app/controllers/nft_offers_controller.rb
- ecosystem/platform/server/app/views/nft_offers/show.html.erb
- Update copy
- Integrate Sign in dialog / modal
- Increase button size to large
- Conditional bottom padding on steps only if is currently active step `!step.disabled && !step.completed`
- Fluid container for NFT with `aspect-ratio: 1/1;`
- Muted completed steps by reducing opacity
- Utilize CSS Grid
- Vertically center colon within APTOS:ZERO heading
- Non-breaking space added to end of hero lead-in copy to prevent widow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3862)
> [community] Update copy, integrate login Dialog, utilize css grid

- consensus/src/epoch_manager.rs
- consensus/src/round_manager.rs
The close message can be in the end of the event queue and not get polled for significant time, although if we receive the
close message, any message in the current epoch is useless. Split it out can help shut down the round manager much faster under load.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3860)
> [consensus] dedicate channel to shutdown round manager

- terraform/fullnode/aws/main.tf
- terraform/helm/monitoring/files/prometheus.yml
Still scrape all cadvisor targets even when `.Values.monitoring.prometheus.fullKubernetesScrape = false`, so that we get all container metrics. Previously, it was only scraping the namespace in which prometheus is installed
This makes the monitoring solution work regardless of where the `aptos-node` helm chart is installed
Apply to cluster.
Before: 
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3922)
> [monitoring] prometheus scrape all cadvisor targets

- .github/workflows/docker-build-test.yaml
Run forge-compat test alongside forge-e2e (performance) test. Both of these should be land-blocking. Few things should happen before this lands though:
* ~Fix or roll back the current backwards breaking change (move native function https://aptos-org.slack.com/archives/C03PKBQM2RY/p1662053271975889)~
* Add this new job as a check to the `main` branch protection rules
This should increase our cluster usage by ~17%, since compat test uses only 5 nodes.
Run Forge with label to check things still work. It won't run compat test yet though
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3793)
> [gha] run compat forge test alongside e2e

- crates/aptos-genesis/src/builder.rs
- terraform/helm/genesis/README.md
- terraform/helm/genesis/files/genesis.sh
- terraform/helm/genesis/templates/genesis.yaml
- terraform/helm/genesis/values.yaml
- testsuite/forge/src/backend/k8s/node.rs
- testsuite/forge/src/backend/k8s/swarm.rs
- testsuite/forge/src/backend/local/node.rs
- testsuite/forge/src/backend/local/swarm.rs
- testsuite/forge/src/interface/node.rs
- testsuite/forge/src/interface/swarm.rs
- testsuite/forge/src/test_utils/consensus_utils.rs
- testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs
- testsuite/testcases/src/continuous_progress_test.rs
- testsuite/testcases/src/state_sync_performance.rs
- through passing genesis configuration (same way as epoch change)
- with that, surface validator indices, and have iterators on validators
be consistent with what they return
(so that we can properly know which nodes were set with larger stake)
- additionally, make continuous_progress_test return Err on checks,
instead of panicing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3896)
> [forge] Enable different genesis validator stake in forge

- .github/workflows/run-forge.yaml
- testsuite/forge.py
- testsuite/forge_test.py
When no image tags are provided, make sure we do not assert
Also, only autoselect from forge-big clusters, so we can start to phase out the original (small) forge clusters
Unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3937)
> [forge] fix assert image tags have prefix if profile or feature

- ecosystem/node-checker/Cargo.toml
- ecosystem/node-checker/src/configuration/types.rs
- ecosystem/node-checker/src/evaluators/direct/api/node_identity.rs
- ecosystem/node-checker/src/evaluators/direct/api/transaction_availability.rs
- ecosystem/node-checker/src/evaluators/direct/noise/handshake.rs
- ecosystem/node-checker/src/evaluators/direct/types.rs
- ecosystem/node-checker/src/metric_collector/reqwest_metric_collector.rs
- ecosystem/node-checker/src/runner/blocking_runner.rs
- ecosystem/node-checker/src/server/api.rs
- ecosystem/node-checker/src/server/configurations_manager.rs
- ecosystem/node-checker/src/server/run.rs
This PR helps resolve this problem: https://github.com/aptos-labs/aptos-core/issues/3912. It doesn't address the DNS aspect of the problem, since that isn't relevant at least for our baselines, but instead makes our clients use cookies to leverage the cookie based sticky routing we have enabled on our LBs.
Run local NHC:
```
cargo run -p aptos-node-checker -- server run --baseline-node-config-paths ~/a/internal-ops/infra/apps/node-checker/configs/* --listen-address 0.0.0.0
```
Query it:
```
curl 'http://127.0.0.1:20121/check_node?node_url=http://34.64.49.220&baseline_configuration_name=ait3_fullnode&metrics_port=9101&api_port=80&noise_port=6182&public_key=0x44fd1324c66371b4788af0b901c9eb8088781acb29e6b8b9c791d5d9838fbe1f' | jq .
```
I tested a metrics evaluator to make sure that still …
> Refactor NHC so clients use a single cookie store per NHC run

- mempool/src/core_mempool/transaction_store.rs
- mempool/src/tests/core_mempool_test.rs
An example of the issue:
1. txn0 and txn1 are added to mempool.
2. GC removes txn0. txn1 is sent to parking lot and removed from timeline_index. But timeline_state is still Ready!
3. txn0 is resubmitted by the user. txn1 is removed from the parking lot, but only NonReady transactions are added to the timeline_index, so txn1 is not added to timeline_index.
4. (txn1 never gets broadcast)
The fix is to reset Ready to NotReady in (2).
Added this case to the existing gc test case. Failed before the fix and now passes after the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3895)
> [mempool] fix issue where gaps in seq no can cause txn to not be broadcast

- .github/workflows/run-forge.yaml
- testsuite/forge.py
- testsuite/forge_test.py
I accidentally mistyped? a variable name and we didnt check after that the image was correct...
So I added an assertion after modifying the variable name as well and fix the typo
Also removed the optional args, since they really should not be optional
Test Plan: unittests + run forge locally with failopint enabled
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3947)
> [forge] Fix woopsie in failpoint logic

- storage/aptosdb/src/pruner/state_store/test.rs
- storage/aptosdb/src/state_store/mod.rs
We forget to delete stale_value_index itself when delete stale value. it will incur lots of garbage/deprecated stale value indices data.
reinforced unit test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3942)
> [fix] prune stale state value index

- config/src/config/consensus_config.rs
- consensus/src/epoch_manager.rs
Removin this check as we can have false positive in case of epoch change and epoch manager is busy doing state sync. We have been running the chain stably for few days for now, so this check shouldn't be needed. We can plan to bring this back in main after making this robust. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3948)
> [Consensus] Remove stuck epoch manager check

- Cargo.lock
- testsuite/generate-format/Cargo.toml
- testsuite/generate-format/src/api.rs
- testsuite/generate-format/src/lib.rs
- testsuite/generate-format/tests/staged/api.yaml
The API requires slightly different types for generating a valid bcs payload.
To solve this poorly, added all the API types to a new file the be generated by serde-reflection.
* Not all api types will be able to use the serde-reflection library
* The serde-reflection library does not accept two types of the same name.
Use these types in the go sdk generator, hit `/v1/transactions` `Accept`: `application/x-bcs` and parse the transaction
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3713)
> [API] Adds api types to testsuite serde yaml generator

- crates/aptos/src/common/types.rs
- crates/aptos/src/test/mod.rs
Now you need to pass --estimate-max-gas, otherwise, it defaults to 50k for now.
We'll need to get rid of this before mainnet, as we should not be defaulting gas, because it hides how much it'll cost.
CI, has it enabled
```
$ aptos account transfer --profile other --account testnet --amount 1000000000
{
"Error": "API error: API error Error(VmError): Invalid transaction: Type: Validation Code: INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE"
}
$ aptos account transfer --profile other --account testnet --amount 1000000000 --estimate-max-gas
{
"Error": "API error: Simulated transaction failed with status Transaction Executed and Committed with Error MAX_GAS_UNITS_BELOW_MIN_TRANSACTION_GAS_UNITS"
}
```
- - - …
> [aptos-cli] Add flag to turn on max gas estimation

- ecosystem/node-checker/fn-check-client/src/check.rs
- ecosystem/node-checker/fn-check-client/src/get_pfns.rs
- ecosystem/node-checker/fn-check-client/src/get_vfns.rs
- ecosystem/node-checker/fn-check-client/src/helpers.rs
The tool was erroneously not including the noise port in the NHC requests, meaning NHC was just using the default. This doesn't matter for the existing data, since we're only checking VFNs and for those we're not doing the handshake check, but it does matter for PFNs.
```
cargo run -p aptos-fn-check-client -- --nhc-address https://node-checker.prod.gcp.aptosdev.com --nhc-baseline-config-name ait3_vfn --big-query-key-path ~/a/internal-ops/helm/observability-center/files/bigquery-cron-key.json --big-query-dry-run check-validator-full-nodes --node-address https://ait3.aptosdev.com 
```
```
cargo run -p aptos-fn-check-client -- --nhc-address https://node-checker.prod.gcp.aptosdev.com --nhc-baseline-config-name ait3_vfn --big-query-key-path …
```
> [fn-check-client] Explicitly include noise port in NHC requests

- ecosystem/typescript/sdk/examples/typescript/bcs_transaction.ts
- ecosystem/typescript/sdk/examples/typescript/multisig_transaction.ts
- ecosystem/typescript/sdk/src/aptos_client.ts
- ecosystem/typescript/sdk/src/coin_client.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/consts.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/deserializer.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/deserializer.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/helper.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/serializer.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/bcs/serializer.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder_utils.test.ts
- ecosystem/typescript/sdk/src/transaction_builder/transaction_builder.test.ts
BigInt literals require ES2020 or above as `target` in TS `compilerOptions`. This PR gets rid of the bigint literals.
Make sure tests still pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3943)
> refactor(ts-sdk): get rid of bigint literals

- api/types/src/block.rs
- crates/aptos-rest-client/src/lib.rs
- crates/aptos-rosetta/src/account.rs
- crates/aptos-rosetta/src/block.rs
- crates/aptos-rosetta/src/construction.rs
- crates/aptos-rosetta/src/main.rs
- crates/aptos-rosetta/src/types/identifiers.rs
- crates/aptos-rosetta/src/types/objects.rs
- testsuite/smoke-test/src/rosetta.rs
- types/src/stake_pool.rs
This migrates all old JSON calls to BCS for Rosetta.  This should improve its performance and simplify the code significantly.
This additionally fixes the BCS output of the block APIs.
Currently E2E tests fail on the last commit.  I suspect there's something wrong with the BCS serialization and the Block by height API.  Will need more debugging
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3967)
> [aptos-rosetta] Cleanup rosetta with BCS

- storage/backup/backup-service/src/lib.rs
Looks like the behavior swings between the original and #3993
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4000)
> [backup] second try fixing routing_and_error_codes

- aptos-move/aptos-sdk-builder/src/golang.rs
Added `VecBytes` (`vec<vec<U8>>`) into bcs primitive generation.
There are probably missed places that should handle this too.
* Ran against latest and go compiles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4018)
> [SDK] Handle bcs Vecbytes primitive in golang generation

- crates/aptos/src/governance/mod.rs
- crates/aptos/src/move_tool/mod.rs
- crates/aptos/src/test/tests.rs
Run arbitrary script files from the CLI
Note, no arguments are supported at this moment.
```
aptos move run-script --script-path /Users/greg/aptos-core/test_script.move --framework-git-rev testnet-stable --profile local
{
"Result": {
"transaction_hash": "0xd865716879f7e0a875ce82b6c06da4ed60db2eab019f6560108d10579860c734",
"gas_used": 1,
"gas_unit_price": 1,
"sender": "5ddf80d85bcd7bd8b833a2589def64ca0cf7df18b8b5ed0d7bdd067658fc49e3",
"sequence_number": 0,
"timestamp_us": 1662689728636741,
"version": 8537,
"vm_status": "Executed successfully"
}
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4016)
> [aptos-cli] Add ability to run move script from CLI

- Cargo.lock
- crates/aptos/Cargo.toml
This PR removes a (seemingly unused?) dependency from the Aptos crate. This dependency has a known vulnerability (and no known fix): https://rustsec.org/advisories/RUSTSEC-2021-0041
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4003)
> [Aptos Crate] Remove unused (and buggy) crate.

- crates/transaction-emitter-lib/src/emitter/mod.rs
- crates/transaction-emitter-lib/src/emitter/stats.rs
- crates/transaction-emitter-lib/src/emitter/submission_worker.rs
- testsuite/testcases/src/lib.rs
As metrics can differ during that period. I think keeping 5% on each end shouldn't reduce the test much, but might give useful stability to it.
CI landblocking forge
Warmup stats: submitted: 7160 txn/s, committed: 7160 txn/s, expired: 0 txn/s, failed submission: 0 tnx/s, latency: 4082 ms, p99 latency: 6000 ms"}
Test stats: submitted: 6827 txn/s, committed: 6827 txn/s, expired: 0 txn/s, failed submission: 0 tnx/s, latency: 4380 ms, p99 latency: 6000 ms"}
Cooldown stats: submitted: 7042 txn/s, committed: 7042 txn/s, expired: 0 txn/s, failed submission: 0 tnx/s, latency: 4324 ms, p99 latency: 6000 ms"}
Bigger difference can be seen with ConstTps (3000):
Warmup stats: submitted: 2970 txn/s, committed: 2970 txn/s, expired: 0 txn/s, failed submission: 0 tnx/s, latency: 1381 ms, p99 latency: …
> [forge] Add warmup and cooldown to measuring performance

- aptos-node/src/lib.rs
- config/src/config/mod.rs
- config/src/config/network_config.rs
This PR ensures that `mutual_authentication` is always enabled for validators on startup. If this isn't set, it's possible that `AntiReplayTimestamps` won't be enforced. I'm not sure if it's practically exploitable, but let's avoid the issue entirely and panic if a validator starts without `mutual_authentication`.
Existing and new tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3782)
> [Network] Ensure mutual_authentication is enabled for all validators.

- .github/workflows/continuous-e2e-state-sync-perf-fullnode-apply-test.yaml
- .github/workflows/continuous-e2e-state-sync-perf-fullnode-execute-test.yaml
- .github/workflows/continuous-e2e-state-sync-perf-validator-test.yaml
- testsuite/forge-cli/src/main.rs
- testsuite/testcases/src/state_sync_performance.rs
This PR expands the single state sync performance test into three separate tests:
1. A fullnode syncing test for transaction output application.
2. A fullnode syncing test for transaction execution.
3. A validator syncing test for validators that have fallen behind.
Each of the above tests will measure and report state sync throughput.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3919)
> [Forge] Add new state sync performance tests.

- aptos-move/e2e-move-tests/tests/rotate_auth_key.rs
- crates/aptos-rest-client/src/lib.rs
- crates/aptos/src/account/key_rotation.rs
- crates/aptos/src/account/mod.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/common/utils.rs
- crates/aptos/src/test/mod.rs
- testsuite/smoke-test/src/aptos_cli/account.rs
Add a CLI command to rotate an account's auth key. 
Smoke test + 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3438)
> [cli] Command to rotate account auth keys

- ecosystem/platform/server/app/components/global_announcement_component.html.erb
- ecosystem/platform/server/app/views/nft_offers/show.html.erb
- ecosystem/platform/server/app/views/static_page/incentivized_testnet.html.erb
Global announcement banner for Aptos:Zero NFT
Ensure global announcement banner is displayed on pages other than Aptos:Zero NFT
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4047)
> [community] global announcement banner update - Aptos:Zero NFT

- ecosystem/platform/server/app/components/claim_nft_button_component.html.erb
- ecosystem/platform/server/app/controllers/nft_offers_controller.rb
- ecosystem/platform/server/app/models/wallet.rb
- ecosystem/platform/server/db/migrate/20220910032621_adjust_wallet_uniqueness.rb
- ecosystem/platform/server/db/schema.rb
- ecosystem/platform/server/test/services/wallet_creator_test.rb
Makes it possible to have the same account in multiple wallets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4064)
> [community] Relax wallet uniqueness constraint to include wallet name.

- aptos-move/move-examples/data_structures/sources/big_vector.move
Tagging @davidiw who added this file in its previous commit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4051)
> Correct doc comment typo in `BigVector`

- crates/aptos-faucet/src/main.rs
- crates/aptos-faucet/src/mint.rs
- crates/aptos-rest-client/src/error.rs
- crates/aptos-rest-client/src/lib.rs
- crates/aptos-rosetta/src/error.rs
Just using printing the error as we do now is not sufficient to get anything useful, since the `Http` error variant only contains the status code. https://github.com/aptos-labs/aptos-core/pull/4044 only made it print that status code, not anything too useful about the error itself. This changes it so it includes the full reqwest error. This is mostly a fix on the REST client moreso than the faucet itself.
```
cd crates/aptos-faucet
cargo test
```
Old output:
```
Faucet account 8e0d19280063fa870fe4dbb85cc724091a398451c5c11e1e76e64cdc7b588510 not found: Http error 404 Not Found
```
New output:
```
Faucet account 8e0d19280063fa870fe4dbb85cc724091a398451c5c11e1e76e64cdc7b588510 not found: Http error 404 Not Found: error decoding response body: missing field `error_code` at line 1 column 34" …
```
> Print error when unable to find faucet account in minting

- crates/aptos-telemetry-service/src/auth.rs
- crates/aptos-telemetry-service/src/context.rs
- crates/aptos-telemetry-service/src/custom_event.rs
- crates/aptos-telemetry-service/src/error.rs
- crates/aptos-telemetry-service/src/jwt_auth.rs
- crates/aptos-telemetry-service/src/lib.rs
- crates/aptos-telemetry-service/src/log_ingest.rs
- crates/aptos-telemetry-service/src/prometheus_push_metrics.rs
- crates/aptos-telemetry-service/src/tests/auth_test.rs
- crates/aptos-telemetry-service/src/tests/custom_event.rs
- crates/aptos-telemetry-service/src/tests/mod.rs
- crates/aptos-telemetry-service/src/tests/test_context.rs
- crates/aptos-telemetry-service/src/types/auth.rs
- crates/aptos-telemetry-service/src/types/mod.rs
This PR adds support for telemetry service to accept metrics and logs from PFNs via an allow list. The allow list (map of peer ID to public keys per chain ID) is defined in the config file and is read during start-up.
Ran a devnet public fullnode locally and was able to send metrics successfully to telemetry service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3887)
> [telemetry-service] Allowlist for PFNs

- consensus/src/experimental/buffer_manager.rs
We blindly broadcast the commit votes every 1s today, which creates a thundering herd problem in a large network as the receiving side also needs to spend cycles verifying and processing the commit votes. This PR introduces a change to only broadcast the commit vote in case there is no commit progress. Also increase the frequency of checking from 1s to 1.5s to align with round timeout. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4029)
> [Consensus] Rebroadcast commit vote only in case of no commit progress

- developer-docs-site/docs/tutorials/first-move-module.md
Some people are very confused because it doesn't tell you to replace addresses in each of the commands.  Using the profiles allow for auto replacement of fields for now.  Ideally, CLI commands should mostly be done with profiles anyways.
I worked through this with a user on Discord, but feel free to test it out
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4074)
> [docs] Update first move module tutorial to use default profile

- developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md
- scripts/dev_setup.sh
I've gone through testing multiple platforms, and ensured that the source does build
at least on the installations I can get on Amazon EC2.  Remembering that I'm not really
worried about supporting the CLI on Raspberry PIs or more obscure OS's.
Architectures and OS's I tested (All with Intel except one graviton):
1. Opensuse x86_64 -> doesn't work because of Zypper
2. Fedora x86_64 -> Works, had to do some tweaks to the dev setup you see here
3. Ubuntu 22.04 (previously also 20.04) x86_64 -> Works
4. Ubuntu 22.04 Arm -> Works (Prover guaranteed doesn't work)
5. Amazon Linux x86_64 -> Works (Prover guaranteed doesn't work)
I also tested the prebuilt binaries on:
1. Mac OSX Arm (I've previously tested on x86_64 without issue)
2. Windows 11 (I haven't tried windows 10, but I'm pretty sure …
> [docs] Use only prebuilt binaries and source to build / install CLI

- ecosystem/platform/server/app/javascript/controllers/claim_nft_controller.ts
- ecosystem/platform/server/app/javascript/controllers/connect_wallet_controller.ts
- ecosystem/platform/server/app/views/nft_offers/show.html.erb
The top errors are
1. Petra Wallet Not being installed (redirect to chrome store)
2. No accounts found
3. Petra Wallet Not being installed (redirect to chrome store)
4. User is not connected to a wallet in the last step because they switch wallets or some other reason. (redirect to connect)
https://user-images.githubusercontent.com/19931667/189506026-edb94da8-c971-4a45-8822-f10c2db33753.mov
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4082)
> Fixes for not having wallet installed and switching accounts

- aptos-move/framework/aptos-framework/sources/aptos_coin.move
- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/framework/aptos-framework/sources/stake.move
1. Add the ability for on chain governance to remove validators from the active validator set.
2. Allow the core resources account to get framework signers in tests and testnets.
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4084)
> [Aptos Framework] Add a few governance powers

- storage/backup/backup-cli/src/backup_types/epoch_ending/restore.rs
- storage/backup/backup-cli/src/coordinators/restore.rs
- testsuite/smoke-test/src/storage.rs
make the logic straightforward -- all it tries to do is to get the latest snapshot
because State Sync catches up faster, there's no point at this point for the db-restore to replay txns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4095)
> [backup] simplify restore coordinator

- mempool/src/core_mempool/mempool.rs
- mempool/src/core_mempool/transaction_store.rs
- mempool/src/tests/core_mempool_test.rs
The hashmap entry with no transactions is 56 bytes (32 account address + 24 empty btree).
Since it's never cleaned up this can grow to the number of accounts ever seen in the mempool. E.g., 330M (twitter MAU) * hashmap entry = 18GB
After the change, the number of hashmap entries is bounded by the total mempool size.
Add unit test that checks the transaction store no longer has an entry for the account after transaction removal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4041)
> [mempool] remove per-account data structure when no more transactions

- terraform/aptos-node-testnet/README.md
- terraform/aptos-node/README.md
- terraform/helm/aptos-node/README.md
- terraform/helm/aptos-node/README.md.gotmpl
Write some common `aptos-node` helm/terraform operational docs to open source. These are quite dense and can belong in READMEs for now. We may want to link to them from the docs site
TODO docs after this:
* aptos-node-testnet
* unify the aptos-node Terraform docs (they exist for each cloud independently now, but share a lot of common steps)
* addons
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4113)
> [docs] aptos-node helm docs

- ecosystem/typescript/sdk/package.json
Since `openapi` is a devDependency, better make sure the dependency is up to date when generating the openapi client files.
Ran `yarn generate-client`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4048)
> chore(ts-sdk): make sure dependencies are up to date when generating openapi clients

- testsuite/forge-cli/src/main.rs
Genesis helm values were not getting set in the correct place
After this lands, we should really change the interface to change the aptos-node and genesis configuration. Editing helm values directly breaks a few abstraction barriers and isn't too friendly
Canary in Forge
* run1: https://github.com/aptos-labs/aptos-core/runs/8299083397?check_suite_focus=true 
* FORGE_RUNNER_DURATION_SECS: 300
* `State sync throughput : 13586 txn/sec`
* run2: https://github.com/aptos-labs/aptos-core/runs/8299083256?check_suite_focus=true
* FORGE_RUNNER_DURATION_SECS: 480
* `State sync throughput : 14045 txn/sec`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4098)
> [forge] correctly apply genesis config for state_sync tests

- crates/aptos-rosetta/src/account.rs
- types/src/account_config/resources/coin_info.rs
CoinInfo was being deserialized wrong because it was using a custom type.  Now with BCS serialization, it can use the real type.
I wanted to make a more in depth test, but that requires me to upload a move module in the test for the coin, and I'm going to hold off on that for now.
Here is a successful run against testnet (which failed previously)
```
$ aptos-rosetta-cli account balance --account 0xd945a1c6dd2180bd2e257e427494c1396b195981738227e86efa7cd7e4f4888b --chain-id testnet
{
"index": 1056846,
"hash": "testnet-1056846"
},
"balances": [
{
"value": "0",
"currency": {
"symbol": "455448",
"decimals": 9,
"metadata": {
"move_type": "0xd945a1c6dd2180bd2e257e427494c1396b195981738227e86efa7cd7e4f4888b::Coin::ETH"
}
}
},
{
"value": "48619",
"currency": {
"symbol": "APT", …
```
> [aptos-rosetta] Fix deserialization bug of coin info

- aptos-move/framework/aptos-stdlib/sources/math.move
- aptos-move/framework/aptos-stdlib/sources/math128.move
- aptos-move/framework/aptos-stdlib/sources/math64.move
Adds a math standard library. There are currently four functions; max, min, average, and pow. These will be helpful, especially for DeFi builders on Aptos Network to calculate something.
In the file `math.move`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3172)
> [move] add standard math library

- Cargo.lock
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/e2e-move-tests/Cargo.toml
- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-move-tests/tests/code_publishing.rs
- aptos-move/framework/aptos-framework/sources/code.move
- aptos-move/framework/aptos-framework/sources/code.spec.move
- aptos-move/framework/aptos-framework/sources/configs/features.move
- aptos-move/framework/aptos-framework/sources/configs/features.spec.move
- aptos-move/framework/aptos-framework/sources/reconfiguration.move
- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- aptos-move/framework/src/natives/code.rs
- types/src/on_chain_config/aptos_features.rs
- types/src/on_chain_config/mod.rs
This PR introduces the new module `aptos-framework/configs/features.move` which manages feature flags for version control and code rollout. 
As a first application, it introduces a new native function in the `code` module to harden package dependency metadata.  If the metadata fakes the dependencies, this will be detected because the module dependencies in the bytecode are not allow-listed. 
It finally shows in the `code_publishing` test case how to generalize tests for multiple feature flag combinations.
Generalizing existing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3928)
> [code publishing] Make package dependency metadata unforgeable

- Cargo.lock
- aptos-move/aptos-gas/Cargo.toml
- aptos-move/gas-algebra-ext/Cargo.toml
- aptos-move/move-deps/Cargo.toml
For the bug fix, see https://github.com/move-language/move/pull/472 for details.
I've manually checked the commits between this and the one we currently depend on and there should be no breaking changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4122)
> [move] bump move dependencies to fix the SignatureToken deserialization bug

- mempool/src/shared_mempool/network.rs
- mempool/src/tests/integration_tests.rs
- mempool/src/tests/test_framework.rs
On broadcast error (e.g., receiver mempool is full) the broadcast is retried later. If this retry was empty (e.g., all transactions were since notified as committed) `determine_broadcast_batch` would continuously return `BroadcastError::NoTransactions` without removing the (now-empty) retry.
Add an integration test that would stall because of this issue in main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4129)
> [mempool] fix broadcast retry fails if retry is empty

- ecosystem/platform/server/app/views/static_page/careers.html.erb
Display Job Departments in alphabetical order on Careers page.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4140)
> [community] sort Job Departments alphabetically on Careers

- aptos-move/aptos-vm/src/aptos_vm.rs
- vm-validator/src/unit_tests/vm_validator_test.rs
since we want to delete this as much as possible, we need to prevent them from getting into mempool and hitting a committed but aborted state. To that end, we need protect further upstream. We already added an abort call in the VM for testnet to protect it, but that's a hack considering the code situation. Moving this in here simplifies testnet, makes sure weird behavior cannot happen on devnet (e.g., committed but aborted ModuleBundle), and makes it so we don't have to think about it for mainnet.
I would have deleted the ModuleBundle code, but it looks like @wrwg is using it to validate module upgrades work as expected for now.
- - - …
> [aptos-vm] disable modules during prologue

- consensus/src/block_storage/block_store.rs
- consensus/src/epoch_manager.rs
- consensus/src/network.rs
- consensus/src/round_manager.rs
- consensus/src/round_manager_fuzzing.rs
- consensus/src/round_manager_test.rs
- testsuite/forge/src/runner.rs
Previously, in case of back pressure (sync_only) mode, the voters simply ignore all proposal messages and rely on round timeout, which is 1.5 seconds. However, it is possible that the backpressure is resolved before the round timeout and they can still vote on the proposal instead of timing out. Waiting for 1.5s blindly in case of backpressure cause performance degradation as seen on Forge and this PR will address that. 
Ran Forge and we can do ~7.5k TPS after this change. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3580)
> [Consensus] Delay proposal processing in case of sync_only mode

- api/src/context.rs
- api/src/events.rs
- api/src/page.rs
- api/src/transactions.rs
- config/src/config/api_config.rs
- storage/aptosdb/src/lib.rs
This allows users to change their max page size to make their own choices.  Additionally, it's only 1000 by default.  This is required for my future Rosetta changes, and it's up to the node runner to determine what they are comfortable with.
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4139)
> [api/storage] Allow for a configurable max page size up to 10000

- aptos-move/framework/aptos-token/sources/property_map.move
- aptos-move/framework/aptos-token/sources/token.move
- aptos-move/framework/aptos-token/sources/token_coin_swap.move
Based on recent NFT airdrop feedbacks and observation, make the following improvement over token module to make it easy to use
1. add read methods for PropertyMap with type conversion
2. add a mutate one token method that can be directly used by community contracts
3. add a set of public get method for getting token data. 
4. add a mint_to method reduce the number of resource touched for lazy_mint
add new unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4118)
> [Token] add public methods to get data from token module and do type conversion 

- crates/aptos-rest-client/src/lib.rs
- crates/aptos/src/account/key_rotation.rs
- crates/aptos/src/common/types.rs
- crates/aptos/src/test/mod.rs
- crates/aptos/src/test/tests.rs
- testsuite/smoke-test/src/aptos_cli/account.rs
Currently, the CLI doesn't support having an account address that's different than the one directly derived by the public key.  No longer is that the case!  It will let you sign with different account addresses, and handle it properly.
Additionally, the Rotate key has better testing, and lookup address works with non-rotated accounts.
Checkout the E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4096)
> [aptos-cli] Support key rotation cli and resource accounts

- crates/transaction-emitter-lib/src/args.rs
- crates/transaction-emitter-lib/src/cluster.rs
- crates/transaction-emitter-lib/src/emitter/account_minter.rs
- crates/transaction-emitter-lib/src/emitter/mod.rs
- crates/transaction-emitter-lib/src/transaction_generator/nft_mint.rs
- crates/transaction-emitter/src/diag.rs
{} only prints a message from the last error or context call. {:?} prints errors/contexts beyond the last, and the stack trace if available.
retry logic for nfts initialization, to match account_creation retry logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4143)
> [txn-emitter] Log and retry improvements

- config/src/config/consensus_config.rs
In AIT3, we are seeing many timeouts under load, the main reason for that being the proposal broadcast time being very high. Reducing the block size, which should help reduce the broadcast time. 
Run Forge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4151)
> [Consensus] Tune max block size from 6k -> 3.5k

- aptos-move/framework/aptos-framework/sources/aptos_governance.move
- aptos-move/framework/aptos-framework/sources/block.spec.move
- aptos-move/framework/aptos-framework/sources/chain_status.spec.move
- aptos-move/framework/aptos-framework/sources/coin.move
- aptos-move/framework/aptos-framework/sources/coin.spec.move
- aptos-move/framework/aptos-framework/sources/configs/staking_config.move
- aptos-move/framework/aptos-framework/sources/configs/staking_config.spec.move
- aptos-move/framework/aptos-framework/sources/event.move
- aptos-move/framework/aptos-framework/sources/event.spec.move
- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/genesis.spec.move
- aptos-move/framework/aptos-framework/sources/stake.move
- aptos-move/framework/aptos-framework/sources/stake.spec.move
- aptos-move/framework/aptos-framework/sources/timestamp.spec.move
- aptos-move/framework/aptos-stdlib/sources/table.spec.move
- defined and proved an invariant for `validator_set`
- validators in the validator sets have been initialized
- validator indices are valid (in-range)
- proved `update_performance_statistics` and `on_new_epoch` does not abort unexpectedly.
- proved the genesis steps partially 
- only the parts that the `stake` module depends on
- Note that there was some changes in the Move code
- a `while` was split into two for loop invariant writing
- `remove_validators` uses a help function (e.g., `..._internal`) for the global invariant verification
- also a few minor changes
- TOOD:
- add the comments for the specs so that they are better auditable.
- completely verify the genesis steps
- - - …
> Proved an invariant and the non-aborting property in the `stake` module

- consensus/src/block_storage/tracing.rs
- consensus/src/experimental/buffer_manager.rs
- consensus/src/experimental/tests/buffer_manager_tests.rs
- consensus/src/network.rs
In happy path, we now only send the commit vote to the block proposer (still broadcast if it's a NIL block).
On receiver side, if the node aggregates the decision and is the block proposer, it'll broadcast the decision.
We still rebroadcast if there's no progress within a time frame.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4076)
> [consensus] avoid broadcasting commit vote in happy path

- storage/backup/backup-cli/src/backup_types/epoch_ending/restore.rs
Edge case where the last txn chunk containing the target version carries a proof from the next epoch -- we can't write that epoch ending info to the DB so we didn't load it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4108)
> [backup] ignore "History until epoch X can't verify" error

- mempool/src/shared_mempool/tasks.rs
This was pointed out as a potential problem. Today this only happens on the failpoint; but having one less status in that case is also potentially problematic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4135)
> [mempool] handle when validate_transaction returns an error

- .github/workflows/check-minimum-revision.yaml
Add a check that prevents old PR from running and using capacity if we expect them to fail
This can also help guarantee that we can make breaking change to ci or builds
Test plan: pull request target -> pull request and test on this PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3905)
> [gha] Add minimum revision check

- api/types/src/transaction.rs
- api/types/src/wrappers.rs
This should allow Events to be parsed forwards and backwards.  Note we'll need to deprecate the original event key
Unit tests, and ran the validator checker
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4170)
> [aptos-api-types] Allow Event to be forwards and backwards compatible

- crates/aptos/src/move_tool/mod.rs
After `u8, u64, u128, bool, hex, string, address`  are passed in cmd, they are encoded again by BCS.
Add `Raw` type which is encoded by BCS, and passed in with Hex format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3872)
> [cli] Add `Raw` type to support passing BCS-encoded parameters directly

- .github/workflows/lint-test.yaml
- scripts/rust_lint.sh
Long requested, much desired, finally here. Running this script will ensure that your PR passes the `rust-lint` step in CI.
```
scripts/rust_lint.sh
```
```
scripts/rust_lint.sh --check
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4175)
> Add rust_lint.sh, use it in CI

- terraform/helm/genesis/files/genesis.sh
- terraform/helm/genesis/templates/genesis.yaml
- terraform/helm/genesis/values.yaml
- testsuite/forge/src/backend/k8s/cluster_helper.rs
- testsuite/forge/src/backend/k8s/constants.rs
- Add a seed parameter for keys generation so that the keys generation will be deterministic and can be accessed from forge tests.
- The i th validator will use the `passed in paremeter + i` as seed to generate keys.
Apply the label CICD:run-e2e-tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4042)
> [forge] Set random-seed parameter for key generation

- config/src/config/state_sync_config.rs
- state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
- terraform/helm/monitoring/files/rules/alerts.yml
This PR makes two small tweaks to state sync:
1. It adds an alert for state sync when the node is lagging more than 1 million versions behind head. We might want to tweak this in the future based on how often it fires, but let's start here.
2. It increases the `num_versions_to_skip_snapshot_sync` in the state sync config.
Existing infrastructure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4178)
> [State Sync] Add a new alert for state sync lag and tweak a config.

- Cargo.lock
- types/Cargo.toml
- types/src/network_address/mod.rs
This PR updates the network parsing code to only support ASCII dns names and prevent unicode. The concern is that with unicode phishing attacks may be possible. I'm not sure how easy it is to exploit this given that we're also embedding public keys in network addresses, but let's play it safe 😄 .
For example, this is valid:
```
/dns6/example.com/tcp/123";
```
This is not:
```
/dns6/еxample.com/tcp/123";
```
Can you spot it? 😆 
A new unit test has been added. I'm relying on existing test infrastructure to help verify that we aren't relying on unicode in production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4186)
> [Networking] Remove unicode support from dns names.

- network/netcore/src/transport/tcp.rs
- network/src/transport/mod.rs
This PR offers two tiny fixes to the network code:
1. It fixes some comments for `upgrade_inbound` and `upgrade_outbound`.
2. It handles the else branch to `connect_via_proxy` to prevent us from ignoring an unexpected response and continuing to read until the buffer is full.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4192)
> [Network] Fix comment and handle proxy else branch.

- Cargo.lock
- aptos-move/aptos-gas/Cargo.toml
- aptos-move/aptos-vm/src/aptos_vm.rs
- aptos-move/aptos-vm/src/aptos_vm_impl.rs
- aptos-move/aptos-vm/src/move_vm_ext/vm.rs
- aptos-move/e2e-move-tests/src/harness.rs
- aptos-move/e2e-move-tests/tests/code_publishing.rs
- aptos-move/e2e-move-tests/tests/framework_compatibility.rs
- aptos-move/e2e-tests/src/executor.rs
- aptos-move/framework/aptos-framework/sources/configs/features.move
- aptos-move/gas-algebra-ext/Cargo.toml
- aptos-move/move-deps/Cargo.toml
- aptos-move/vm-genesis/src/lib.rs
- aptos-move/writeset-transaction-generator/src/writeset_builder.rs
- types/src/on_chain_config/aptos_features.rs
This PR does two things:
- Updates the move-deps to link to the commit of the new [aptos release branch on move-language](https://github.com/move-language/move/tree/aptos). 
- Based on the new feature in the Move repo/branch, adds the feature `TREAT_FRIEND_AS_PRIVATE` to Move and Rust code, inclusive a test.
New test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4199)
> [move-deps & friend compat] Updates move-deps & relaxes friend compatibility

- Cargo.lock
- api/src/runtime.rs
Needed to allow browsers to use cookies, which we need for cookie-based session.
I can see in the Poem code that this does what we want:
```
if self.allow_credentials {
builder = builder.header(header::ACCESS_CONTROL_ALLOW_CREDENTIALS, "true");
}
```
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4198)
> [API] Respond with Access-Control-Allow-Credentials

- aptos-move/framework/aptos-framework/sources/block.move
Add a public function to emit a new block event. This is needed for #4037 . The reason is that a genesis writeset will need both a new block event and a new epoch event for it to be committed. As of now, there's no way to emit this new block event which thus prevented any WriteSet scripts to be executed and committed.
Tested this change along side with #4172 by manually pinning the git version to this commit [here](https://github.com/aptos-labs/aptos-core/blob/90306accf2f6e665cc436e54c68ec710d58637fb/testsuite/smoke-test/src/genesis.rs#L127). Once this PR lands we will be able to run the test in #4172 again and enable the testing there.
- - - …
> [Aptos-framework] Add a public function to emit a new block event

- mempool/src/core_mempool/mempool.rs
- mempool/src/core_mempool/transaction_store.rs
- mempool/src/core_mempool/ttl_cache.rs
- mempool/src/tests/core_mempool_test.rs
There were two issues previously:
1. An account's sequence_number_cache could get GC'd before its transactions in mempool were sent to consensus. In this case because a cached sequence number does not exist, the transactions are never sent to consensus (get_batch checks the sequence number).
2. The sequence_number_cache capacity is the same as the mempool, but it could have grown beyond this because sequence_number_cache entries are retained for accounts after transaction removal (until they expire). In this case old sequence_number_cache entries are removed and those transactions may never be sent to consensus (same reason as above).
There doesn't seem to be a need for a separate sequence_number_cache at all. When transactions are submitted to mempool, the latest account sequence number …
> [mempool] remove sequence_number_cache and instead store directly in transaction_store

- crates/aptos-rosetta-cli/src/block.rs
- crates/aptos-rosetta-cli/src/common.rs
- crates/aptos-rosetta/src/block.rs
- crates/aptos-rosetta/src/common.rs
- crates/aptos-rosetta/src/lib.rs
- crates/aptos-rosetta/src/main.rs
- crates/aptos-rosetta/src/network.rs
- crates/aptos-rosetta/src/types/objects.rs
- crates/aptos-rosetta/src/types/requests.rs
- testsuite/smoke-test/src/rosetta.rs
You can make up blocks based on transactions if you feel that variable block size is not good enough for your current state.
Remembering that the timestamps can be wrong on a block.
Additionally, drops transactions that have no operations by default.
This is a feature that's not supported in tests.  It has been tested manually to work
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4165)
> [aptos-rosetta] Allow synthetic blocks in Rosetta

- mempool/src/core_mempool/transaction_store.rs
- mempool/src/logging.rs
Displaying all txns is infeasible, except for trace-level logging.
Simple change. Read the code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4147)
> [mempool] only display first 10 txns of debug logs

- config/src/config/mempool_config.rs
- mempool/src/core_mempool/transaction.rs
The previous implementation does not work; it would just output the size of the static parts of the struct so all transactions had the same estimate. Instead we replace with BCS raw transaction size. While this does not show an exact allocation of bytes it is a good stand-in estimate -- as BCS does not attempt to compress or otherwise reduce data (e.g., RLE).
The BCS size is cached and later used to compute size on broadcast. So this only requires more work for transactions that end up not being broadcasted.
Added a unit test that shows relative difference in estimated sizes. This previously failed in main because the sizes outputted were the same.
- - - …
> [mempool] estimate in-memory size using BCS raw transaction

- ecosystem/platform/server/config/routes.rb
aptoslabs.com/discord should redirect to the Discord invite.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4215)
> [community] Redirect /discord to the Discord invite URL.

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/src/aptos_client.ts
- ecosystem/typescript/sdk/src/faucet_client.ts
10s is the borderline timeout time. Recently, we received a couple of reports. Plus, we also observed the timeouts ourselves.  Change 10s to 20s, and this should reduce the timeouts.
yarn test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4190)
> fix: longer default txn wait time

- .github/ts-tasks/package.json
- .github/ts-tasks/prune-github-workflow-runs.ts
- .github/ts-tasks/tasksfile.ts
- .github/workflows/prune-old-workflow-runs.yaml
Addressing https://github.com/aptos-labs/aptos-core/security/dependabot/64.
```
cd .github/ts-tasks
yarn pruneGithubWorkflowRuns
```
I haven't tested that the CI itself works, but I can if yall want. It's just painful bc it's a cron / manual workflow, so I'll have to fork and experiment there. The above does work though (up to the point where the token isn't there).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4213)
> Avoid using tasksfile in ts-tasks

- .github/workflows/prover-test.yaml
- aptos-move/framework/aptos-stdlib/sources/math128.move
- aptos-move/framework/aptos-stdlib/sources/math64.move
- replaced the recursive `pow` functions with iterative ones
- the new implementation also has the logarithmic time complexity (log e).
- this bypasses the Prover's issue with recursive Move functions.
- turned on the CI test for prover because Prover is now back to working
cargo test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4229)
> Turned the recursive `pow` functions into iterative ones

- aptos-move/framework/aptos-framework/sources/reconfiguration.move
This adds a test function that one can use to set reconfiguration time for tests. This is helpful in testing on-chain validator oracles.
Test only function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4077)
> Test helper for reconfiguration time

- crates/aptos-rosetta-cli/src/block.rs
- crates/aptos-rosetta-cli/src/common.rs
- crates/aptos-rosetta/src/block.rs
- crates/aptos-rosetta/src/types/requests.rs
- testsuite/smoke-test/src/rosetta.rs
This should save users who don't want to keep track of transactions without associated operations.  They can be re-enabled by a flag.
> [aptos-rosetta] Drop transactions that don't have associated operations

- crates/aptos-genesis/src/builder.rs
- docker/compose/aptos-node/validator.yaml
- terraform/helm/aptos-node/files/configs/validator.yaml
- testsuite/forge/src/backend/local/node.rs
Rocksdb seems unnecessary for the simple use case and creates friction to operate on it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4196)
> [safety-rules] switch back to file based backend

- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- consensus/src/block_storage/block_store.rs
- consensus/src/block_storage/block_tree.rs
- consensus/src/epoch_manager.rs
The prune already happened here before rebuild the block tree https://github.com/aptos-labs/aptos-core/blob/1398201b2a1e339624dd2798c048cbac057000cd/consensus/src/block_storage/sync_manager.rs#L322
This prune may also prune blocks that's in the new tree if the old tree has overlap with the new tree.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4232)
> [block store] fix some race conditions

- crates/aptos-rest-client/src/lib.rs
- crates/aptos/src/node/analyze/fetch_metadata.rs
- testsuite/forge/src/test_utils/consensus_utils.rs
- testsuite/smoke-test/src/client.rs
Improves 3x the speed of this command:
cargo run -p aptos -- node analyze-validator-performance --analyze-mode=all --url=https://ait3.aptosdev.com  --start-epoch=190 --end-epoch=195
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4166)
> [cli] Use bcs when fetching events from API for analyze_validators

- .github/workflows/continuous-e2e-network-partition-test.yaml
- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/backend/k8s/chaos/network_partition.yaml
- testsuite/testcases/src/network_partition_test.rs
Fixed the existing network partition test to be more stable. Instead of randomly partitioning the network, it partitions the first 3 nodes and ensures that we don't send transactions there. 
Ran the test locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4146)
> [Forge] Fix network partition test

- aptos-move/framework/aptos-framework/sources/stake.move
Multiple minor cleanups that are still backward-compatible:
1. Check that a resource exists before borrowing it. This would return a nicer error to the users.
2. Use the correct error::function instead of error::invalid_argument() for everything.
3. Remove unnecessary type argument when it can be inferred from arguments. For example coin::value<AptosCoin>(aptos_coins) => coin::value(aptos_coins)
4. Remove unused error codes.
5. Short-circuit rather than throwing an error in several places. Throwing errors makes the stake module less composable as the modules building on top of them have to watch out for error conditions. For example, withdraw(0) can return zero coins instead of throwing an error because amount is 0.
Unit Tests
- - - …
> [Aptos Framework][Cleanup] Minor backward-compatible cleanups in stake module

- aptos-move/framework/aptos-framework/sources/configs/gas_schedule.move
- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/reconfiguration.move
- aptos-move/framework/aptos-framework/sources/state_storage.move
- aptos-move/framework/aptos-framework/sources/storage_gas.move
We implement a customizable curve for storage-based gas base unit and map x <-[0, 10000]  to y<-[0, 10000].
storage gas = min_gas + (max_gas - min_gas) * (current_usage / target_utilization)
The curve is a vector of point(x, y), both are basis points.
1. curve's points' y value must be monotonically non-decreasing, and x values must be monotonically increasing.
2. curve's points must start with a point of x = 0 and end with a point of x = 10000.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3810)
> [storage_gas] implement customizable storage gas config

- aptos-move/framework/aptos-framework/sources/coin.spec.move
- aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
- aptos-move/framework/aptos-framework/sources/stake.spec.move
- aptos-move/framework/aptos-framework/sources/state_storage.spec.move
- aptos-move/framework/aptos-framework/sources/storage_gas.spec.move
- missing an aborting condition in `stake::is_current_epoch_validator`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4251)
> Fix the failure of Prover in CI

- developer-docs-site/docs/guides/system-integrators-guide.md
While reading the docs found that the mention of Rust SDK is missing, so added the links to it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4230)
> [docs] Add links to Rust SDK to the system integration guide

- api/src/context.rs
- testsuite/smoke-test/src/rest_api.rs
There's now V2.  For compatibility, it will use V1 if V2 doesn't exist
E2E test only tests V2
Tested locally against a testnet full node, and got http://localhost:8080/v1/estimate_gas_price -> `{"gas_estimate":1}`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4258)
> [api] Use gas schedule v2 for gas estimation

- aptos-move/framework/aptos-framework/sources/aptos_account.move
- aptos-move/framework/aptos-framework/sources/stake.move
- aptos-move/framework/aptos-framework/sources/staking_contract.move
- aptos-move/framework/aptos-framework/sources/system_addresses.move
- aptos-move/framework/aptos-framework/sources/timestamp.move
- aptos-move/framework/aptos-framework/sources/vesting.move
- aptos-move/framework/aptos-stdlib/sources/pool_u64.move
This creates a separate StakePool per delegation (from a delegator to an operator) and does not allow pooling funds from multiple delegators at all.
Unit + e2e tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3570)
> [Aptos Framework] Add a module for creating staking contracts between stakers and operators and a vesting module

- ecosystem/platform/server/app/controllers/application_controller.rb
- ecosystem/platform/server/app/javascript/controllers/claim_nft_controller.ts
- ecosystem/platform/server/test/controllers/nft_offers_controller_test.rb
Use HTTP 303 instead of 302 for the `ensure_confirmed!` redirect. This indicates that clients should issue a GET for the redirect URL (so it should work even if the initial method was POST/PUT/etc.).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4259)
> [community] Use 303 instead of 302 for unconfirmed email redirect.

- .github/workflows/docker-build-test.yaml
- .github/workflows/run-forge.yaml
Instead of appending to a single comment (which can get massive + there are no reliable timestamps e.g. this massive comment https://github.com/aptos-labs/aptos-core/pull/4119#issuecomment-1247424891), hide the previous one and recreate the comment at the bottom. The old test runs are still able to be referenced
Also only report to slack the failures
Land it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4217)
> [gha] forge sticky hide and report failure only

- ecosystem/platform/server/app/controllers/projects_controller.rb
- ecosystem/platform/server/app/models/project.rb
- ecosystem/platform/server/app/views/projects/index.html.erb
- ecosystem/platform/server/test/controllers/projects_controller_test.rb
- Redirect to /projects after creating a project, and show the "not visible until verified" message
- Save empty URLs as NULL instead of an empty string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4271)
> [community] Fix issues with project submission.

- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/storage_gas.move
- aptos-move/framework/aptos-framework/sources/vesting.move
- aptos-move/framework/tests/move_unit_test.rs
Test failures where silently accepted because of wrong usage of the unit test API.
Actually failing on failed tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4264)
> [move unit tests] Propagate Move unit test failure

- consensus/src/round_manager.rs
This bug was introduced in https://github.com/aptos-labs/aptos-core/pull/3580, which breaks the sync_only mode for write set txns. 
Will add a UT as a follow up, landing this without test as this is critical to unbreak the write set tool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4266)
> [Consensus] Don't allow execution and vote in sync_only mode

- ecosystem/platform/server/app/controllers/nft_offers_controller.rb
Only requires captcha for NFT minting if `:require_captcha_for_nft` is enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4274)
> [community] Add flag for nft captcha.

- aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- mempool/src/core_mempool/transaction_store.rs
Clippy was failing on an issue
```
Checking peer-monitoring-service-types v0.1.0 (/opt/git/aptos-core/network/peer-monitoring-service/types)
error: you are using an explicit closure for copying elements
--> mempool/src/core_mempool/transaction_store.rs:634:33
|
634 |                 let timestamp = self.get_insertion_time(account, *seq_num).map(|v| *v);
|                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider calling the dedicated `copied` method: `self.get_insertion_time(account, *seq_num).copied()`
|
= note: `-D clippy::map-clone` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_clone
```
CI, plus I ran clippy
- - - …
> Fix generation and lint issues

- ecosystem/platform/server/db/migrate/20220916125743_adjust_username_index.rb
- ecosystem/platform/server/db/schema.rb
- ecosystem/platform/server/spec/factories/users.rb
The query to determine `username` uniqueness was not optimized.
Additionally, this PR adjusts the user factory to reduce the chance of duplicate usernames.
Before:
```
postgres=> explain analyze select 1 as one from "users" where lower("users"."username") = lower('zach') and "users"."id" != 9000000 limit 1;
QUERY PLAN
------------------------------------------------------------------------------------------------------------
Limit  (cost=0.00..10.87 rows=1 width=4) (actual time=37.787..37.789 rows=1 loops=1)
->  Seq Scan on users  (cost=0.00..9556.35 rows=879 width=4) (actual time=37.786..37.787 rows=1 loops=1)
Filter: ((id <> 9000000) AND (lower((username)::text) = 'zach'::text))
Rows Removed by Filter: 76098
Planning Time: 0.873 ms
Execution Time: 37.830 ms
(6 rows)
```
After:
``` …
```
> [community] Fix index so that it's used in uniqueness query.

- aptos-move/framework/aptos-stdlib/sources/math128.move
- aptos-move/framework/aptos-stdlib/sources/math64.move
This was found in an audit. (a + b) can overflow.
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4270)
> [Aptos StdLib] Fix potential overflow issues with math average

- scripts/rust_lint.sh
Making this exit with non zero if there is a problem with any commands, instead of just the last one.
I introduced a formatting error (not the last command) and ran it with `--check` and it returned with 1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4286)
> Make `rust_lint --check` exit with failure if it fails

- ecosystem/platform/server/.rubocop.yml
- ecosystem/platform/server/app/controllers/projects_controller.rb
- ecosystem/platform/server/app/views/projects/show.html.erb
- ecosystem/platform/server/test/controllers/projects_controller_test.rb
Redirects to the newly-created project instead of the index page upon submission.
Also allows admins to view all projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4275)
> [community] Redirect to new project after creation.

- .github/workflows/prover-test.yaml
- aptos-move/framework/aptos-framework/sources/aggregator/aggregator.spec.move
- aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.spec.move
- aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.spec.move
- aptos-move/framework/aptos-framework/sources/chain_status.spec.move
- aptos-move/framework/aptos-framework/sources/code.spec.move
- aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
- aptos-move/framework/aptos-framework/sources/vesting.spec.move
- Turned off the verification for the modules which are not related to the `block_prologue`
- This suppresses the verification failure, and reduces the verification time
aptos move prove, or CI Prover test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4295)
> [Move Prover] Fixed the Prover failure in CI

- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/genesis.spec.move
- aptos-move/framework/src/natives/mod.rs
- aptos-move/vm-genesis/src/lib.rs
- types/src/chain_id.rs
This is still a bit early:
* I'll ask @movekevin  to kindly land at least his interfaces and data structures as soon as possible, so I can rebase on top of them...
* I'll ask @gregnazario to start looking at these interfaces and consider the right way to make the tooling work.... maybe we just have a dedicated main function / binary?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4182)
> Prepare for mainnet genesis

- crates/indexer/src/processors/default_processor.rs
- crates/indexer/src/util.rs
chrono::NaiveDateTime::MAX.timestamp() is for some reason year 54680
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4309)
> [indexer][ez] fix timestamp max

- Cargo.lock
- aptos-move/vm-genesis/src/lib.rs
- crates/aptos-genesis/src/builder.rs
- crates/aptos-genesis/src/config.rs
- crates/aptos-genesis/src/mainnet.rs
- crates/aptos/Cargo.toml
- crates/aptos/src/genesis/git.rs
- crates/aptos/src/genesis/keys.rs
- crates/aptos/src/genesis/mod.rs
- crates/aptos/src/genesis/tests.rs
Add a new end-to-end flow for mainnet genesis, which involves new data types (account maps, employee vesting, etc.).
Unit + E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4308)
> Mainnet genesis building

- storage/aptosdb/src/lib.rs
Hopefully this addresses the other internal indexer's errors wrt the table typing info not available fast enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4315)
> [storage] internal indexer indexes before setting latest LI

- .github/workflows/lint-test.yaml
Reverts aptos-labs/aptos-core#4260
turns out to be a false alarm
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4314)
> Revert "[CICD] Add an explicit step for running Move module tests"

- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/vesting.move
- aptos-move/vm-genesis/src/lib.rs
- types/src/account_address.rs
I tested commissioned validators by forcing the codebase to use it by default..
The reality is we'll likely want to extend the testing to validate the data was written (just as a check) and then also review the output binary, but this should be reasonably acceptable to move forward and unblock collaboration ... I think.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4310)
> Genesis support for commissioned validators and employee vesting

- ecosystem/typescript/sdk/src/token_client.ts
- `account` to `sender` at line 207 
- delete an extra space at line 208
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4145)
> Fix typo in token_client.ts

- mempool/src/core_mempool/transaction_store.rs
- mempool/src/logging.rs
- mempool/src/shared_mempool/coordinator.rs
* Most GCRemoveTxns logs are when 0 txns are removed. These don't need to be logged (moving to trace).
* GC coordinator running (every 60 seconds) doesn't need to be info.
Existing tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4278)
> [mempool] further reduce gc logs

- terraform/helm/aptos-node/templates/fullnode.yaml
- terraform/helm/aptos-node/templates/validator.yaml
- terraform/helm/fullnode/templates/fullnode.yaml
- terraform/helm/vector-log-agent/files/vector-transforms.yaml
This PR does two things:
1. add explicit annotation-based prometheus scrape config. This is a step towards getting rid of aptos-specific configuration in prometheus/vmagent and make it easier to use other metric collectors.
2. Delete some redundant log attributes in vector config to reduce log ingest volume.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4327)
> observability: annotation based prometheus config and reduce logging volume slightly

- testsuite/forge-cli/src/main.rs
- testsuite/forge/src/runner.rs
Continous tests are flaky because validators are using more memory - this is expected because we have 2 rocks DB instance and both of them can use 3-4G each. Bumping up the memory requirement to 10G by default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4340)
> [Forge] Increase default memory threshold from 5G -> 10G

- .github/workflows/docker-build-test.yaml
There's no current protections on the `testnet` branch. Pin the git rev we're testing compat against to be consistent
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4283)
> [gha] pin compat at latest build on testnet

- Cargo.lock
- crates/aptos-telemetry-service/Cargo.toml
- crates/aptos-telemetry-service/src/auth.rs
- crates/aptos-telemetry-service/src/clients/mod.rs
- crates/aptos-telemetry-service/src/constants.rs
- crates/aptos-telemetry-service/src/custom_event.rs
- crates/aptos-telemetry-service/src/index.rs
- crates/aptos-telemetry-service/src/jwt_auth.rs
- crates/aptos-telemetry-service/src/lib.rs
- crates/aptos-telemetry-service/src/log_ingest.rs
- crates/aptos-telemetry-service/src/prometheus_push_metrics.rs
- crates/aptos-telemetry-service/src/types/mod.rs
- crates/aptos-telemetry-service/src/validator_cache.rs
- crates/aptos-telemetry/src/sender.rs
This change brings multiple debugging and API improvements.
- The APIs are now versioned v1 and have consistent naming schemes. The old API will still be available until we move all the traffic to the new API.
- The service now has tracing support and integrates with GCP CloudRun's tracing system, so it is easier to debug failures based on specific requests.
- Miscellaneous log message improvements
- Validated that the API works with new as well old clients running a test node locally
- Fixed unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4174)
> [telemetry-service] API endpoint and logging improvements

- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/tsup.config.js
- ecosystem/typescript/sdk/typedoc.json
- ecosystem/typescript/sdk/yarn.lock
?? is not widely supported by browsers and frameworks. e.g. CRA older than 3.3.0 doesn't support `??` transpiling. We would like to transpile all `??` to ternary operators in SDK.
yarn build
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4332)
> chore: clean up nullish coalescing (??) operators

- ecosystem/typescript/sdk/README.md
Add instructions on using the SDK as a bundle that can be served from CDN.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4288)
> doc: update ts-sdk readme

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/aptos_client.ts
- ecosystem/typescript/sdk/src/generated/core/request.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder.ts
- ecosystem/typescript/sdk/yarn.lock
For ts-sdk to support cookies in browser environment, we need to set `WITH_CREDENTIALS` to true. However, this doesn't work in nodejs environment. `axios` doesn't have a built-in cookie store. The best cookie store for nodejs is 'tough-cookie'. However, 'tough-cookie' doesn't bundle well in a browser environment. Since we don't need a full cookie store, it is best for us to write a simple cookie store manually.
1. Made sure all tests pass 
2. Made sure cookie headers are set in both the browser and the nodejs environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4285)
> feat: enable cookies for ts-sdk axios client

- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/aptos_account.ts
- ecosystem/typescript/sdk/src/aptos_types/authentication_key.ts
- ecosystem/typescript/sdk/src/aptos_types/transaction.ts
- ecosystem/typescript/sdk/src/transaction_builder/builder.ts
- ecosystem/typescript/sdk/yarn.lock
js-sha3 is not needed anymore. `@noble/hashes` is audited and easy to use. Since we have already used `@noble/hashes` in SDK, there is no need to keep js-sha3.
All tests pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4300)
> refactor: replaces js-sha3 with @noble/hashes/sha3

- ecosystem/typescript/sdk/CHANGELOG.md
- ecosystem/typescript/sdk/package.json
- ecosystem/typescript/sdk/src/aptos_client.test.ts
- ecosystem/typescript/sdk/src/aptos_client.ts
Add two functions for AptosClient sdk:
* getBlockByHeight
* getBlockByVersion
Run a local node (run from the root of the repo):
```
cargo run -p aptos -- node run-local-testnet --with-faucet --faucet-port 8081 --force-restart --assume-yes
```
Run the SDK tests and make sure they pass. Go to the SDK directory, and setup an env to configure the URLs:
```
rm .env
echo 'APTOS_NODE_URL="http://127.0.0.1:8080/v1"' >> .env
echo 'APTOS_FAUCET_URL="http://127.0.01:8081"' >> .env
```
Run the tests:
```
yarn test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4287)
> [TS SDK] Add getBlock

- aptos-move/framework/aptos-framework/sources/genesis.move
- aptos-move/framework/aptos-framework/sources/genesis.spec.move
- aptos-move/vm-genesis/src/lib.rs
- crates/aptos-genesis/src/builder.rs
- crates/aptos-genesis/src/config.rs
- crates/aptos/src/genesis/keys.rs
- crates/aptos/src/genesis/mod.rs
- crates/aptos/src/genesis/tests.rs
1. Allow validators to have the same owner (but different operators) in genesis.
2. Allow validators to be set up but not yet join the validator set immediately during genesis.
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4325)
> [Genesis] Update mainnet genesis flow

- aptos-move/vm-genesis/src/lib.rs
- crates/aptos/src/genesis/tests.rs
Remove unnecessary zeroes in the vesting schedule. Vesting's cliff is protected with the vesting schedule's start time: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/vesting.move#L442
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4377)
> [Genesis][Tests only] Remove unnecessary zeros

- aptos-move/aptos-gas/src/gas_meter.rs
This fixes a pre-condition for `AptosGasMeter::new`. I made a mistake when simplifying the boolean expression. This is a fully compatible change since the only client already enforces the right condition.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4356)
> [gas] fix pre-condition for AptosGasMeter::new

- .github/workflows/continuous-e2e-account-creation-test.yaml
- .github/workflows/continuous-e2e-nft-mint-test.yaml
- crates/transaction-emitter-lib/src/transaction_generator/nft_mint.rs
- testsuite/forge-cli/src/main.rs
NFT mint is a bit flaky, so trying to improve it.
But also creating a separate test just for it, while having the other tests run without it, so they are not affected by it's flakiness (if it continues)
e2e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4334)
> [forge][flaky] Create separate nft mint test, and remove nft minting from other tests

- Cargo.lock
- crates/node-resource-metrics/Cargo.toml
- crates/node-resource-metrics/src/collectors/common.rs
- crates/node-resource-metrics/src/collectors/cpu_metrics_collector.rs
- crates/node-resource-metrics/src/collectors/disk_metrics_collector.rs
- crates/node-resource-metrics/src/collectors/loadavg_collector.rs
- crates/node-resource-metrics/src/collectors/memory_metrics_collector.rs
- crates/node-resource-metrics/src/collectors/mod.rs
- crates/node-resource-metrics/src/collectors/network_metrics_collector.rs
- crates/node-resource-metrics/src/collectors/process_metrics_collector.rs
- crates/node-resource-metrics/src/lib.rs
This PR introduces ability to export linux-specific stats as prometheus metrics. The included ones are CPU time per state, disk IOPS stats, and memory (rss/ vm) stats.
```
node_linux_disk_io_in_progress{name="sda"} 0
node_linux_disk_io_in_progress{name="sda1"} 0
node_linux_disk_io_in_progress{name="sdb"} 0
node_linux_disk_io_in_progress{name="sdb1"} 0
node_linux_disk_io_in_progress{name="sdb14"} 0
node_linux_disk_io_in_progress{name="sdb15"} 0
node_linux_disk_num_merged_reads{name="sda"} 0
node_linux_disk_num_merged_reads{name="sda1"} 0
node_linux_disk_num_merged_reads{name="sdb"} 6297
node_linux_disk_num_merged_reads{name="sdb1"} 6177
node_linux_disk_num_merged_reads{name="sdb14"} 0
node_linux_disk_num_merged_reads{name="sdb15"} 120
node_linux_disk_num_merged_writes{name="sda"} 75513 …
```
> [node-resource-metrics] linux-specific stats

- consensus/src/counters.rs
- consensus/src/epoch_manager.rs
- consensus/src/liveness/round_state.rs
- consensus/src/pending_votes.rs
- consensus/src/round_manager.rs
- consensus/src/round_manager_fuzzing.rs
- crates/aptos-metrics-core/src/lib.rs
chain health metrics can see participation from successful rounds, and so is limited by >66%.
If network is in a really bad state, we want to see how many votes we can actually collect, which is what these counters do.
We can also see potentially for some failure rounds, how far were they able to collect votes.
Looking at charts on CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4276)
> [consensus] Add collected voting power counters

- testsuite/forge/src/backend/local/swarm.rs
- testsuite/smoke-test/src/storage.rs
I'm still seeing all failures in test_db_restore in waiting for the swarm to start.. wish to try to wait longer and see if it passes more
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4388)
> smoke-test: longer wait for local swarm to launch

- developer-docs-site/docs/concepts/coin-and-token/index.md
- developer-docs-site/docs/tutorials/first-move-module.md
- developer-docs-site/docs/tutorials/first-transaction.md
- developer-docs-site/docs/tutorials/index.md
- developer-docs-site/docs/tutorials/your-first-nft.md
If we no more touch these tutorials, these are ready for the prime time, formatting and readability wise.
- Better code snippet highlighting 
- Editing to fix minor snafus
- Horizontal ruler between each step for tutorials. Enhances readability, especially with the tabs.
- Change CLI install pointer from git source to precompiled binary.
- Reflowed the Move module tutorial with a slight modification, adding step numbers. 
I will have a separate PR for the remaining tutorials.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4407)
> Tutorial docs cleanup (three tutorials)

- terraform/aptos-node-testnet/variables.tf
- terraform/aptos-node/aws/variables.tf
- terraform/aptos-node/gcp/variables.tf
bump the instance size for utilities to 8vcpu 32gb memory so we can recommend beefier HAProxy deployments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4404)
> [tf] update utility node requirement

- developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md
Demoted the CLI install by source method. Kept it in a collapsed section at the bottom of the page with sufficient warnings that it is for advanced users only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4421)
> [Docs] Demoting the CLI install by source in the docs.

- crates/aptos-logger/src/aptos_logger.rs
For better debugging
Key is required to have debug, so we'd at least know which field name is failing.  That should be good enough to narrow down which one causes the issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4417)
> [aptos-logger] Add key to error message telling that serialization failed

- api/src/context.rs
This should prevent from too much churn due to always pulling the gas schedule.  Gas schedule will always be pulled if the epoch changes.
E2E tests?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4345)
> [api] Cache the gas schedule

- .github/workflows/lint-test.yaml
This command was not updated when the indexer feature was added to smoke tests in `cargo.rs`.
`test_error_report` (and concurrent tests) always took > 2min, now in this check it took under 2 s. So this does seem to reduce the time spent in cargo within the smoke tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4441)
> [cicd] smoke tests: build with all features

- aptos-node/src/lib.rs
I've decreased a bunch of the polling timeouts and concurrency amounts to decrease the CPU overhead of a local testnet.  On my M1 mac the decrease in overhead is from >800% to ~250%.
I ran this locally, I guess I didn't try any direct executions against it, but the CI does I think...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4435)
> [aptos-node] Tune local testnet parameters

- testsuite/forge/src/backend/local/swarm.rs
- testsuite/smoke-test/src/smoke_test_environment.rs
- testsuite/smoke-test/src/storage.rs
- testsuite/smoke-test/src/txn_broadcast.rs
Applied to `test_db_restore` and `test_txn_broadcast`.
Includes re-enabling `test_txn_broadcast` which was previously disabled due to flakiness.
If this helps, can follow-up to apply the retry globally.
Injected a retry and at least confirmed that we can successfully create a new swarm after having created a swarm (that was itself successful).
Will have to continue bake in CICD and observe the flakiness trend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4437)
> [smoke tests] add a retry for initializing swarm, apply to 2 tests

- crates/aptos-rosetta/src/client.rs
- crates/aptos-rosetta/src/construction.rs
- crates/aptos-rosetta/src/types/misc.rs
- crates/aptos-rosetta/src/types/move_types.rs
- crates/aptos-rosetta/src/types/objects.rs
- testsuite/smoke-test/src/rosetta.rs
This adds set voter support, and fixes a bug in set operator on failed transactions.
Note this does not add support for the staking contracts built on top of stake.move.
E2E tests, including a set voter check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4422)
> [aptos-rosetta] Add SetVoter support

- aptos-move/framework/aptos-framework/sources/configs/staking_config.move
- aptos-move/framework/aptos-framework/sources/configs/staking_config.spec.move
- aptos-move/framework/aptos-framework/sources/stake.move
- aptos-move/framework/aptos-framework/sources/stake.spec.move
This commit adds assertions and a spec to ensure `rewards_rate <= MAX_REWARDS_RATE` where `MAX_REWARDS_RATE = 1000000`, and `rewards_rate <= rewards_rate_denominator`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4185)
> Limit the upper bound of `rewards_rate`

- Cargo.lock
- aptos-node/src/lib.rs
- crates/aptos-logger/Cargo.toml
- crates/aptos-logger/src/aptos_logger.rs
- crates/aptos-logger/src/lib.rs
- crates/aptos-telemetry-service/src/auth.rs
- crates/aptos-telemetry-service/src/context.rs
- crates/aptos-telemetry-service/src/index.rs
- crates/aptos-telemetry-service/src/lib.rs
- crates/aptos-telemetry-service/src/remote_config.rs
- crates/aptos-telemetry-service/src/tests/test_context.rs
- crates/aptos-telemetry-service/src/validator_cache.rs
- crates/aptos-telemetry/Cargo.toml
- crates/aptos-telemetry/src/constants.rs
- crates/aptos-telemetry/src/lib.rs
- crates/aptos-telemetry/src/sender.rs
- crates/aptos-telemetry/src/service.rs
This changes introduces the ability to configure `RUST_TELEMETRY_LOG` remotely via the telemetry service. The telemetry crate polls the service periodically and updates the `RUST_TELEMETRY_LOG` to the value sent by the service, if any. A new periodic thread within `aptos_logger` rebuilds log filters, which already uses the aforementioned env variable. The periodicity is set to 5 minutes.
The telemetry service uses a static config mapping chain ID, peer ID to a log level. This will be replaced with a database in the future.
Validated locally, by changing log level in the service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4367)
> [telemetry-service] remote log level configuration

- crates/aptos-telemetry/src/service.rs
- crates/node-resource-metrics/src/collectors/linux_collectors.rs
- Stop filtering by `sd` prefix and filter out only loop devices. This was preventing metrics from nvme disks.
- Enable node metrics collection by default regardless of telemetry service is enabled.
Verified changes work properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4443)
> [node-resource-metrics][bugfix] allow disk metrics for nvme disks
