aptos-labs/aptos-core

terraform/testnet/testnet/templates/ingress.yaml
have fullnode.<domain> available for testnet
=> [helm] update testnet ingress

developer-docs-site/docs/basics/basics-merkle-proof.md
This PR provides some small cleanups and re-wording for the proofs basics section: https://aptos.dev/basics/basics-merkle-proof
Yes.
Manually inspected the files.
None.
=> Small cleanups to Proofs basics.

developer-docs-site/docs/transactions/interfacing-with-the-blockchain.md
(Write your answer here.)
* Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
* Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
* Why we must have it for V1 launch.
* What workarounds and alternative we have if we do not push the PR.
=> Fix broken link

developer-docs-site/docs/basics/basics-validator-nodes.md
This PR offers some fixes and cleanups to the "Validator nodes" developer documents file: https://aptos.dev/basics/basics-txns-states
Yes.
Manually inspected the files.
None.
=> Small cleanups to the Validator nodes dev docs.

developer-docs-site/docs/tutorials/run-a-fullnode.md
Our community is diving into the details of running fullnode, provide a bit more guide on setting up node identity. This is from our old operator runbook.
=> [doc] add fullnode identity guide

terraform/helm/fullnode/values.yaml, terraform/helm/validator/values.yaml, terraform/testnet/testnet/values.yaml
=> [helm] update dockerhub repo

.circleci/config.yml
Mirror images from private ECR to dockerhub `aptoslab` https://hub.docker.com/orgs/aptoslab/repositories every 4 hours  on CP
Yes
Canary via bors https://github.com/aptos-labs/aptos-core/pull/201. New image tags in Dockerhub: https://hub.docker.com/repository/docker/aptoslab/validator `main` and `dev_73851995`
=> [circleci] push to dockerhub

terraform/fullnode/fullnode/templates/service.yaml, terraform/fullnode/fullnode/values.yaml, terraform/fullnode/main.tf, terraform/fullnode/variables.tf
- add option to create real network address for pfn
- add a new variable for passing in different helm value per fullnode
=> [helm] add option to create real network address for pfn

.circleci/config.yml
tag and push images when `devnet` branch is updated
=> [circleci] build and push on devnet branch

terraform/helm/fullnode/files/fullnode.yaml, terraform/helm/fullnode/templates/fullnode.yaml, terraform/helm/fullnode/templates/service.yaml
open port for aptosnet, to allow fullnode connection
=> [helm] open port for fullnode

config/src/config/test_data/public_full_node.yaml, docker/compose/public_full_node/public_full_node.yaml
- add seeds to public fullnode config
- cleanup the json_rpc config
=> [config] add seeds to fullnode config

.github/ISSUE_TEMPLATE/questions.md, README.md, developer-docs-site/docs/intro.md, developer-docs-site/docusaurus.config.js
=> [docs] Update Discord invite link

developer-docs-site/docs/transactions/interfacing-with-the-blockchain.md
This PR makes some small fixes to the developer documentation: Interacting with the Aptos Blockchain, found here: https://aptos.dev/transactions/interacting-with-the-aptos-blockchain
Yes.
Manually inspected all of the change sites.
None.
=> [Documentation] Small cleanups to "Interacting with the Aptos Blockchain"

developer-docs-site/docs/tutorials/run-a-fullnode.md
This PR makes some small fixes to the developer documentation: "Run a FullNode". Found here: https://aptos.dev/tutorials/run-a-fullnode
Yes.
Manually inspected all of the change sites.
None.
=> [Documentation] Small fixes to "Run a FullNode"

terraform/testnet/testnet/templates/monitoring.yaml, terraform/testnet/testnet/values.yaml
Missed this env var in https://github.com/aptos-labs/aptos-core/pull/276
=> [tf][testnet] custom grafana datasources from aws

developer-docs-site/docs/tutorials/run-a-fullnode.md
Provide general guidance on upgrades
=> [doc] add instruction for upgrade

developer-docs-site/docs/tutorials/run-a-fullnode.md
Some body may not understand what file we are talking about, in my opinion it is better to clarify.
Some may not understand what file we are talking about, in my opinion it is better to clarify.
yes
* Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
* Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
* Why we must have it for the release.
* What workarounds and alternative …
=> [Documentation] Name of the configuration file

developer-docs-site/docs/tutorials/first-move-module.md
This PR makes some small fixes to the developer documentation: Your First Move Module, found here: https://aptos.dev/tutorials/your-first-move-module
Yes.
Manually inspected all of the change sites.
None.
=> [Documentation] Small fixes to "Your First Move Module"

developer-docs-site/docs/tutorials/run-a-fullnode.md
This PR updates the "Run a FullNode" tutorial to make mention of storage requirements and add some instructions around where to add seeds in the config file. It seems this comes up a lot.
Yes.
None.
=> [Documentation] Added some instructions for seeds and storage.

terraform/helm/validator/files/haproxy.cfg
use the helm values max connection config to set haproxy maxconn.
=> [haproxy] keep max connection config in sync

terraform/fullnode/aws/fullnode/files/alertmanager.yml, terraform/fullnode/aws/fullnode/files/dashboards/api.json.gz, terraform/fullnode/aws/fullnode/files/dashboards/ddos.json.gz, terraform/fullnode/aws/fullnode/files/dashboards/fullnodes.json.gz, terraform/fullnode/aws/fullnode/files/dashboards/mempool.json.gz, terraform/fullnode/aws/fullnode/files/dashboards/network.json.gz, terraform/fullnode/aws/fullnode/files/dashboards/state_sync.json.gz, terraform/fullnode/aws/fullnode/files/dashboards/storage.json.gz, terraform/fullnode/aws/fullnode/files/grafana.ini, terraform/helm/logger/templates/logging.yaml, terraform/helm/logger/values.yaml, terraform/helm/validator/values.yaml
- fix the soft links
- pull in more dashboards for fullnodes
- update vector to recent version
=> [fullnode] update dashboard templates

developer-docs-site/docs/tutorials/run-a-fullnode.md
- update doc for release instruction.
- also update all our example / seeds with new address
=> [doc] update release doc for address change

.circleci/config.yml
=> [circleci] remove old job name

state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-v2/state-sync-driver/src/driver.rs, state-sync/state-sync-v2/state-sync-driver/src/lib.rs, state-sync/state-sync-v2/state-sync-driver/src/logging.rs, state-sync/state-sync-v2/state-sync-driver/src/notification_handlers.rs, state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs, state-sync/state-sync-v2/state-sync-driver/src/utils.rs
This PR updates the state sync driver to use structured logging instead of logging only strings.
Yes.
Manually inspected the log formats.
None, but this PR relates to: https://github.com/aptos-labs/aptos-core/issues/245
=> [State Sync] Use structured logging for the state sync driver.

developer-docs-site/static/examples/python/first_nft.py, developer-docs-site/static/examples/python/first_transaction.py, developer-docs-site/static/examples/python/hello_blockchain.py, developer-docs-site/static/examples/rust/first_transaction/src/lib.rs
A couple fixes to our tutorials...
1. Gas prices for Tokens are high until we get real maps
2. Rust had some random code :O
3. auth_key api in faucet seems broken -- probably best to just remove it
=> Few fixes to our tutorial sample code

developer-docs-site/docs/tutorials/run-a-fullnode.md
=> Full node tutorial docker update

.circleci/config.yml, ecosystem/typescript/sdk/.eslintrc.js, ecosystem/typescript/sdk/.prettierrc, ecosystem/typescript/sdk/examples/javascript/index.js, ecosystem/typescript/sdk/examples/typescript/index.ts, ecosystem/typescript/sdk/package.json, ecosystem/typescript/sdk/src/aptos_account.test.ts, ecosystem/typescript/sdk/src/aptos_account.ts, ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/faucet_client.test.ts, ecosystem/typescript/sdk/src/faucet_client.ts, ecosystem/typescript/sdk/src/hex_string.test.ts, ecosystem/typescript/sdk/src/util.test.ts
unify formatting :-) with prettier
=> Add prettierrc formatter to JS/TS

developer-docs-site/docs/tutorials/run-a-fullnode-on-gcp.md
(Write your answer here.)
* Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
* Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
* Why we must have it for the release.
* What workarounds and alternative we have if we do not push the PR.
=> Removing Debian installation bash script.

Cargo.lock, api/types/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/move_vm_ext/mod.rs, aptos-move/aptos-vm/src/move_vm_ext/resolver.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/e2e-tests/Cargo.toml, storage/aptosdb/Cargo.toml
Stack is getting deeper, sending out those don't depend on upstream change.
Y
=> Plumbing for native table

developer-docs-site/static/examples/typescript/first_nft.ts, developer-docs-site/static/examples/typescript/first_transaction.ts
No developer doc for writing the first NFT transaction exists for typescript. I am adding code to show how to create a new NFT and transfer it to someone. This can be used by other developers as a reference.
(Write your answer here.)
* Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
* Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
* Why we must have it for the release. …
=> adding NFT dev doc for typescript

execution/executor/tests/db_bootstrapper_test.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/utils.rs, state-sync/storage-service/server/src/tests.rs, storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/backup/backup_handler.rs, storage/aptosdb/src/backup/restore_handler.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/schema/jellyfish_merkle_node/mod.rs, storage/aptosdb/src/schema/jellyfish_merkle_node/test.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/backup.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/inspector/src/main.rs, storage/jellyfish-merkle/src/lib.rs, storage/storage-interface/src/lib.rs, types/src/proof/definition.rs, types/src/state_store/state_value.rs
Adding StateKey to JMT leaf node, which will be used for indexing purposes needed for https://github.com/aptos-labs/aptos-core/issues/291.
Existing UTs
=> [Storage] Add State Key to the JMT leaf node

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_script_function_payload.json, api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_module_payload_bytecode.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_script_function_address.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_script_function_arguments.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_script_function_module_name.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_script_function_name.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_script_payload_bytecode.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_missing_script_function_arguments.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_script_function_validation.json, api/goldens/aptos_api__tests__transactions_test__test_post_bcs_format_transaction.json, sdk/src/transaction_builder.rs, sdk/transaction-builder/errmap/error_description.errmap, testsuite/smoke-test/Cargo.toml, testsuite/smoke-test/src/lib.rs, testsuite/smoke-test/src/nft_transaction.rs, testsuite/smoke-test/src/rest_api.rs, testsuite/smoke-test/tests/forge-aptos.rs
this is a copy of the first_nft tutorial but in smoke test form, yay
=> [smoke-test] add nft smoke test

api/goldens/aptos_api__tests__state_test__test_query_resource.json, api/goldens/aptos_api__tests__state_test__test_query_resource_address_not_found.json, api/goldens/aptos_api__tests__state_test__test_query_resource_by_invalid_address.json, api/goldens/aptos_api__tests__state_test__test_query_resource_by_invalid_struct_tag.json, api/goldens/aptos_api__tests__state_test__test_query_resource_struct_tag_not_found.json, api/src/context.rs, api/src/index.rs, api/src/lib.rs, api/src/state.rs, api/src/tests/mod.rs, api/src/tests/state_test.rs, storage/storage-interface/src/state_view.rs
prepare for fine grained state access, especially 
1. table items
2. query path (state/resource/0x123/0x1::Collections::Collections/table/collection_name/token_id)
will add doc once API is complete. (modules, table items, query paths will follow)
y
unittests
=> state Rest API

docker/build-aws.sh, docker/build-common.sh, docker/txn-emitter/Dockerfile, docker/txn-emitter/build.sh, docker/txn-emitter/buildspec.yaml
- add txn-emitter so that we can run load testing
- although I really hate how our docker build scripts are structured right now....I will have to file a TODO for clean it up later. for now just adding another binary to build for everyone :(
=> [docker] add txn-emitter image

terraform/testnet/testnet/templates/loadtest.yaml, terraform/testnet/testnet/values.yaml
- add load-test component so that we can start building super big DB testnet
=> [testnet] add load test

testsuite/forge/src/backend/k8s/cluster_helper.rs
=> update forge nodesgroup

storage/aptosdb/src/schema/state_value_index/mod.rs, storage/aptosdb/src/state_store/mod.rs, types/src/nibble/nibble_path/mod.rs, types/src/state_store/state_key.rs
A set of follow up from the review comments in PR - https://github.com/aptos-labs/aptos-core/pull/466
=> [Storage] Follow up from adding index for JMT leaf

terraform/validator/vault-init/main.tf
To make upsizing/downsizing easier
=> [vault] add option to allow deleting key

docker/build-aws.sh, docker/build-common.sh, docker/indexer/Dockerfile, docker/indexer/build.sh, docker/indexer/buildspec.yaml, docker/safety-rules/Dockerfile, docker/tools/Dockerfile, docker/txn-emitter/Dockerfile, docker/validator/Dockerfile
Build and copy `aptos-indexer` binary. Install `libpq-dev` and build as before
Unblock indexer TF module https://github.com/aptos-labs/aptos-core/pull/475
=> [docker] add indexer image

api/src/accounts.rs, api/src/index.rs, api/src/state.rs
Just realized that's how it should be organized. (See events.rs)
Y
=> [API] trivial: move get_resource / get_module handlers to state.rs

terraform/helm/validator-lite/files/configs/validator.yaml
0x address change has been reverted for now but we missed a place.
=> [deployment] fix address format

.circleci/config.yml, ecosystem/typescript/sdk/src/faucet_client.test.ts
The two tests are duplicate and are also flaky as well. 
While they are running the same test, usually only one of them will succeed
Yes
Remove duplicated test
=> [CircleCI] Remove duplicated circleci test

developer-docs-site/docs/basics/basics-accounts.md
I suspect this was missed by mistake.
=> [docs] Update basics-accounts.md for 32 bit addresses

developer-docs-site/docs/tutorials/run-a-fullnode-on-gcp.md
=> [docs] fix typos in gcp docs

.circleci/config.yml
=> [cicd] rename workflow

terraform/helm/validator-lite/files/configs/validator.yaml, terraform/helm/validator-lite/values.yaml, terraform/helm/validator/files/configs/validator.yaml, terraform/helm/validator/values.yaml
So that we can change it based on different machines and clusters
=> [helm] make concurrentcy level configurable

developer-docs-site/docs/basics/basics-accounts.md
=> #399 Remove 16-byte account address references

terraform/testnet/testnet/files/prometheus.yml, terraform/testnet/testnet/values.yaml
Add option for testnet prometheus to do remote write too
=> [helm] add remote write option for testnet monitoring

.circleci/config.yml
Reverts aptos-labs/aptos-core#662
=> Revert "[cicd] rename workflow"

terraform/helm/validator-lite/files/configs/validator.yaml, terraform/helm/validator-lite/values.yaml, terraform/helm/validator/files/configs/fullnode.yaml, terraform/helm/validator/files/configs/validator.yaml, terraform/helm/validator/values.yaml
Config was renamed recently in https://github.com/aptos-labs/aptos-core/pull/646.
=> [Storage] Rename config default_prune_window -> ledger_prune_window

documentation/specifications/consensus/README.md
There were links to a `block_store.md` but I couldn't find anything in the repo that it might be referring to, so I just changed it to an internal link.
You can see that the updated links are correct here: https://github.com/banool/aptos-core/tree/main/documentation/specifications/consensus.
=> Fix broken links, typos in consensus spec

Cargo.lock, crates/aptos/Cargo.toml, crates/aptos/src/account/create.rs, crates/aptos/src/account/list.rs, crates/aptos/src/account/mod.rs, crates/aptos/src/account/transfer.rs, crates/aptos/src/common/init.rs, crates/aptos/src/common/types.rs, crates/aptos/src/common/utils.rs, crates/aptos/src/lib.rs, crates/aptos/src/main.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/op/key.rs, testsuite/smoke-test/src/network.rs, testsuite/smoke-test/src/operational_tooling.rs
The full transaction outputs serialized is not helpful, as there's a bunch of serialized binary.  This now cuts down the outputs to a summary size, that tells the basics and the changes. There's a slightly different one for transfer (so it looks like a wallet).
Additionally, I did some cleanup to consolidate a lot of the code and make portions of it more consistent.
Yes
```
$ aptos move publish --package-dir /opt/git/aptos-core/aptos-move/move-examples --named-addresses HelloBlockchain=Greg --profile Greg
{
"Result": {
"changes": {
"0x91617bf0bb0114492eea544618bc88b085ff5cc7dc5c154db1ec3cd7f48cdcb1": "Module written",
"0x91617bf0bb0114492eea544618bc88b085ff5cc7dc5c154db1ec3cd7f48cdcb1::0x1::Account::Account": {
"authentication_key": …
```
=> [aptos-cli] Cleanup outputs and code

config/src/config/test_data/public_full_node.yaml
This will be less confusing for people who follow the tutorial the first time.
y
ran my local fullnode
=> update sample public fullnode config

ecosystem/web-wallet/src/components/ChakraLink.tsx, ecosystem/web-wallet/src/components/CreateWalletHeader.tsx, ecosystem/web-wallet/src/components/HelpHeader.tsx, ecosystem/web-wallet/src/components/WalletFooter.tsx, ecosystem/web-wallet/src/components/WalletHeader.tsx, ecosystem/web-wallet/src/constants.ts, ecosystem/web-wallet/src/hooks/useWalletState.ts, ecosystem/web-wallet/src/index.tsx, ecosystem/web-wallet/src/pages/Account.tsx, ecosystem/web-wallet/src/pages/CreateWallet.tsx, ecosystem/web-wallet/src/pages/Help.tsx, ecosystem/web-wallet/src/pages/Login.tsx, ecosystem/web-wallet/src/pages/Wallet.tsx, ecosystem/web-wallet/src/utils/account.ts
https://user-images.githubusercontent.com/31301117/166158954-4a513395-ce0e-4e60-840d-1e34ea36f79b.mov
Addressing issues tasks in here: https://github.com/aptos-labs/aptos-core/issues/703
Completed MVP requirements for web-wallet:
Yes
See above
=> Adding error states for transfer, account page

developer-docs-site/static/examples/python/first_nft.py, developer-docs-site/static/examples/python/first_transaction.py
* was crashing on retrieving rest data
* make sure collections works
=> [dev-docs] some fixes to python demos

aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/vm-genesis/src/lib.rs
IIUC Zekun wants to make one of the table based data structures into the genesis.
https://github.com/aptos-labs/aptos-core/pull/803
y
existing coverage, and Zekun's diff.
(We can add more "e2e" tests in the Rest API, TS sdk crates after the genesis gets a table.)
=> Take into account table changes while making the genesis change set

crates/aptos/README.md
=> Fix typos in README.md.

ecosystem/web-wallet/src/pages/Wallet.tsx
=> [web-wallet] Fix build

developer-docs-site/docs/tutorials/building-wallet-extension.md
Want to make sure to disclaim that this is still under development
=> [web-wallet] Add disclaimer

ecosystem/web-wallet/src/pages/Login.tsx, ecosystem/web-wallet/src/pages/Wallet.tsx, ecosystem/web-wallet/yarn.lock
Turn  caching off on the input for private key
https://files.slack.com/files-pri/T032LMSJ0T0-F03EF8S9FKL/screen_shot_2022-05-06_at_11.42.30_am.png
=> Turn autocomplete off on private key input

developer-docs-site/docs/guides/move.md
=> [dev-docs] add move doc

.circleci/config.yml
Add CI/CD docker build for testnet branch, prep for AIT1
=> [CI/CD] add testnet branch

execution/executor/proptest-regressions/executor_test.txt, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/jellyfish-merkle/src/iterator/iterator_test.rs, storage/jellyfish-merkle/src/jellyfish_merkle_test.rs, storage/jellyfish-merkle/src/lib.rs, storage/jellyfish-merkle/src/mock_tree_store.rs, storage/jellyfish-merkle/src/restore/mod.rs, storage/jellyfish-merkle/src/test_helper.rs, storage/jellyfish-merkle/src/tree_cache/mod.rs, storage/jellyfish-merkle/src/tree_cache/tree_cache_test.rs, storage/scratchpad/src/sparse_merkle/mod.rs
in preparation for per-block and less frequent state updating
y
=> [storage] cache latest persisted state version

aptos-move/framework/aptos-framework/sources/BigVector.move
Reserve/shrink decouples the responsibility of maintaining buckets from using the vectors.
Owner of the vector can reserve/shrink properly while the user of the vector and do push_back_no_grow and pop_back
so the gas fee is predictable.
=> [AptosFramework] add reserve/shrink to BigVector

terraform/helm/monitoring/Chart.yaml, terraform/helm/monitoring/files/alertmanager.yml, terraform/helm/monitoring/files/dashboards, terraform/helm/monitoring/files/grafana.ini, terraform/helm/monitoring/files/prometheus.yml, terraform/helm/monitoring/files/rules/alerts.yml, terraform/helm/monitoring/templates/_helpers.tpl, terraform/helm/monitoring/templates/monitoring.yaml, terraform/helm/monitoring/templates/serviceaccount.yaml, terraform/helm/monitoring/values.yaml
Create monitoring chart so that it can be installed into any deployment separately
=> [helm] add monitoring chart

terraform/aptos-node/gcp/README.md
=> [doc] add doc for gcp aptos-node

ecosystem/platform/server/app/assets/config/manifest.js
=> [CP] Fix asset build

terraform/aptos-node/aws/README.md
=> [doc] add doc for aws aptos-node

docker/compose/aptos-node/README.md, docker/compose/aptos-node/docker-compose.yaml, docker/compose/aptos-node/fullnode.yaml, docker/compose/aptos-node/validator.yaml
=> [docker] add aptos-node docker compose

ecosystem/platform/server/app/assets/stylesheets/application.css, ecosystem/platform/server/app/controllers/onboarding_controller.rb, ecosystem/platform/server/app/controllers/welcome_controller.rb, ecosystem/platform/server/app/views/it1_profiles/_form.html.erb, ecosystem/platform/server/app/views/it1_profiles/edit.html.erb, ecosystem/platform/server/app/views/it1_profiles/new.html.erb, ecosystem/platform/server/app/views/layouts/_application.html.erb, ecosystem/platform/server/app/views/layouts/_flash.html.erb, ecosystem/platform/server/app/views/layouts/application.html.erb, ecosystem/platform/server/app/views/layouts/it1.html.erb, ecosystem/platform/server/app/views/onboarding/email.html.erb, ecosystem/platform/server/app/views/shared/_it1_schedule.html.erb, ecosystem/platform/server/app/views/welcome/index.html.erb, ecosystem/platform/server/app/views/welcome/it1.html.erb
=> [ecosystem] Update /, /onboarding/email, and /it1_profiles styles.

terraform/aptos-node/aws/cluster.tf, terraform/aptos-node/aws/kubernetes.tf, terraform/aptos-node/aws/variables.tf, terraform/helm/aptos-node/templates/validator.yaml, terraform/helm/monitoring/files/prometheus.yml, terraform/helm/monitoring/files/rules/alerts.yml, terraform/helm/monitoring/templates/monitoring.yaml, terraform/helm/monitoring/templates/psp.yaml, terraform/helm/monitoring/values.yaml
- Add option to install monitoring chart for aws terraform
- Cleanup monitoring config a bit more
=> [helm/tf/aws] add monitoring/logging option to aptos-node

terraform/aptos-node/gcp/kubernetes.tf, terraform/aptos-node/gcp/variables.tf
=> [tf/gcp] add monitoring/logging option

terraform/helm/aptos-node/files/configs/validator.yaml
=> [config] update validator config

ecosystem/platform/server/app/controllers/onboarding_controller.rb, ecosystem/platform/server/app/views/it1_profiles/_form.html.erb, ecosystem/platform/server/app/views/onboarding/email.html.erb, ecosystem/platform/server/app/views/onboarding/email_success.html.erb, ecosystem/platform/server/app/views/welcome/index.html.erb, ecosystem/platform/server/app/views/welcome/it1.html.erb
=> [ecosystem] Update terms links + email success page.

config/src/config/test_data/validator.yaml, config/src/config/test_data/validator_full_node.yaml
- Update configs in test-data.
- Add example on how to use other methods to provide keys
=> [config] update example test config

ecosystem/typescript/sdk/src/token_client.test.ts, ecosystem/web-wallet/package.json, ecosystem/web-wallet/src/components/CreateNFTModal.tsx, ecosystem/web-wallet/src/components/GalleryItem.tsx, ecosystem/web-wallet/src/components/WalletFooter.tsx, ecosystem/web-wallet/src/constants.ts, ecosystem/web-wallet/src/index.tsx, ecosystem/web-wallet/src/pages/Gallery.tsx, ecosystem/web-wallet/src/pages/Login.tsx, ecosystem/web-wallet/src/pages/Wallet.tsx, ecosystem/web-wallet/src/types/TokenMetadata.ts, ecosystem/web-wallet/yarn.lock
https://user-images.githubusercontent.com/31301117/168168976-2dc118f4-d075-4b3d-b56a-3885b776de9d.mov
MVP for displaying and minting collectibles via wallet extension
- Displays a gallery of collectibles (notably NFTs only at the moment). 
- Also allows users to create single tokens / collections
- External storage structure for Arweave, IPFS, etc should be iterated on in the future
See above
=> NFT Gallery functionality with error logging

types/src/state_store/state_key.rs
detected by flaky test `state_value_index::test::test_no_panic_decoding`
y
unit test
=> [storage] fix that StateKey::decode() can panic

ecosystem/platform/server/app/assets/stylesheets/application.css, ecosystem/platform/server/app/components/button_component.rb, ecosystem/platform/server/app/form_builders/aptos_form_builder.rb, ecosystem/platform/server/app/views/shared/_captcha_helper.html.erb, ecosystem/platform/server/app/views/welcome/index.html.erb, ecosystem/platform/server/app/views/welcome/it1.html.erb, ecosystem/platform/server/config/environments/development.rb
Last minute changes for clarity
https://user-images.githubusercontent.com/1482859/168214595-d342b104-c97a-4012-9135-87aa13618f91.mov
and
=> [CP] buttons and rubocop-ing

developer-docs-site/docs/reference/node-liveness-criteria.md
Start the doc that informs node operators the conditions upon which they are incentivized for AIT1.
=> [doc] testnet node liveness criteria

developer-docs-site/docs/tutorials/validator-node/_category_.json, developer-docs-site/docs/tutorials/validator-node/connect-to-testnet.md, developer-docs-site/docs/tutorials/validator-node/intro.md, developer-docs-site/docs/tutorials/validator-node/using-aws.md, developer-docs-site/docs/tutorials/validator-node/using-docker.md, developer-docs-site/docs/tutorials/validator-node/using-gcp.md, developer-docs-site/docs/tutorials/validator-node/using-source-code.md
=> [doc] add validator doc

ecosystem/platform/server/app/controllers/application_controller.rb, ecosystem/platform/server/app/views/it1_profiles/_form.html.erb, ecosystem/platform/server/config/initializers/crash_if_no_db.rb
- Don't explode on startup if the table doesn't exist yet
- Change name of "network key" to "validator network key"
=> [CP] Fixes before launch

ecosystem/platform/server/app/models/it1_profile.rb, ecosystem/platform/server/app/models/user.rb
=> [CP] Bug fixes

developer-docs-site/docs/tutorials/validator-node/_category_.json, developer-docs-site/docs/tutorials/validator-node/intro.md, developer-docs-site/docs/tutorials/validator-node/using-docker.md
Minor updates, only descriptive and section headers.
=> [Documentation] Minor edits to AIT1 docs.

ecosystem/platform/server/app/controllers/onboarding_controller.rb, ecosystem/platform/server/app/jobs/send_email_job.rb, ecosystem/platform/server/app/views/it1_profiles/_form.html.erb
=> [ecosystem] Improve email form error handling.

ecosystem/platform/server/app/helpers/node_helper.rb, ecosystem/platform/server/app/jobs/location_job.rb, ecosystem/platform/server/app/models/location.rb, ecosystem/platform/server/app/views/it1_profiles/_form.html.erb
=> [CP] Fix location job

developer-docs-site/docs/tutorials/validator-node/using-docker.md, docker/compose/aptos-node/README.md, docker/compose/aptos-node/docker-compose-fullnode.yaml, docker/compose/aptos-node/fullnode.yaml
- Split validator / fullnode docker compose
- Update documentation for installing nodes on different machine
=> [deployment] update docker

consensus/src/epoch_manager.rs
2022-05-17T18:52:35.202738Z [consensus] INFO consensus/src/epoch_manager.rs:387 Starting new epoch {"epoch":2,"root_block":"[id: 5f131d39, epoch: 2, round: 00, parent_id: 00000000, timestamp: 1652813552926740]","validators":"ValidatorSet: [f85fd00e30cd388d2609db24d6cc44f2652f27413456938eaa059f65231647cc: 1, ]"}
=> [consensus] format Block with Display

state-sync/state-sync-v2/state-sync-driver/src/driver.rs, state-sync/state-sync-v2/state-sync-driver/src/notification_handlers.rs, storage/aptosdb/src/lib.rs
This PR changes some log lines to help improve logging observability. 
Note: I've down-graded a storage log because it's getting hit really often and doesn't seem to be that important. I'm not sure what's changed as I've previously not seen this log get hit frequently. Anyway, if we'd prefer to log this, let me know and I can apply some sampling:
```
2022-05-18T21:26:41.099437Z [shared-mem] INFO storage/aptosdb/src/lib.rs:1088 Got latest TreeState. {"tree_state":{"ledger_frozen_subtree_hashes":["c006481ddfdb85ea225db7cabad110de7297ed8e47af39d2741e27aa568f3fb7","ef0c506271cc05ae65a734bb736c9ee8d68fbde192997c1e779a4c53d428eeee","fea65c31a0fd78e94f384f48c08b2f259aceea979420d9a73a8eb2018c33d4ba","d1cbcf559acbd0f713d983853747863d934f0abee8977433453193234243c117","a7ae98081f918a5ba489b001f0dfcfc …
```
=> [State Sync] Update some log types for observability.

ecosystem/platform/server/app/models/user.rb
Reverts aptos-labs/aptos-core#1090
Causing deadlocks :-)
=> Revert "Merge authorizations if they belong to another user."

ecosystem/platform/server/app/admin/authorizations.rb, ecosystem/platform/server/app/helpers/node_helper.rb
allows merging (via changing userid) and deleteing
=> [CP] Admin powers for authz

ecosystem/platform/server/config/initializers/sentry.rb
=> [CP] Sample Sentry: we're running low

Cargo.lock, aptos-move/mvhashmap/Cargo.toml, aptos-move/parallel-executor/Cargo.toml, aptos-move/transaction-replay/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, aptos-node/Cargo.toml, config/management/operational/Cargo.toml, crates/aptos/Cargo.toml, network/Cargo.toml, state-sync/aptos-data-client/Cargo.toml, state-sync/state-sync-v1/Cargo.toml, state-sync/state-sync-v2/state-sync-driver/Cargo.toml, storage/schemadb/Cargo.toml, storage/scratchpad/Cargo.toml, x.toml
This PR removes unused dependencies from `aptos-core`.
Yes.
Existing unit tests.
None.
=> [Dependencies] Remove unused dependencies.

developer-docs-site/docs/tutorials/validator-node/connect-to-testnet.md
=> [doc] update doc for connecting to testnet

terraform/helm/aptos-node/templates/fullnode.yaml, terraform/helm/aptos-node/templates/validator.yaml, terraform/helm/aptos-node/values.yaml
Add option to push logs to remote location
=> [helm] add remote logging option

ecosystem/indexer/migrations/2022-05-05-233518_alter_block_metadata_transactions/up.sql, ecosystem/indexer/migrations/2022-05-19-174526_tokens/down.sql, ecosystem/indexer/migrations/2022-05-19-174526_tokens/up.sql, ecosystem/indexer/migrations/2022-05-19-174534_collections/down.sql, ecosystem/indexer/migrations/2022-05-19-174534_collections/up.sql, ecosystem/indexer/migrations/2022-05-19-174539_ownerships/down.sql, ecosystem/indexer/migrations/2022-05-19-174539_ownerships/up.sql, ecosystem/indexer/migrations/2022-05-19-174609_token_activities/down.sql, ecosystem/indexer/migrations/2022-05-19-174609_token_activities/up.sql, ecosystem/indexer/src/indexer/tailer.rs, ecosystem/indexer/src/lib.rs, ecosystem/indexer/src/main.rs, ecosystem/indexer/src/models/collection.rs, ecosystem/indexer/src/models/mod.rs, ecosystem/indexer/src/models/ownership.rs, ecosystem/indexer/src/models/token.rs, ecosystem/indexer/src/models/token_activity.rs, ecosystem/indexer/src/schema.rs, ecosystem/indexer/src/token_processor.rs, testsuite/smoke-test/src/indexer.rs
To provide basic DB tables for token indexer API.
1. add models for serde token, token id, tokenData and token events
2. add a token processor to add records to token table
document the todos in https://github.com/aptos-labs/aptos-core/issues/1132 and will continuous to get the rest of items done. 
Yes
test run token processor with fullnode and see the table created as expect.
=> [ecosystem] [1/3] add token tables to indexer

aptos-move/framework/aptos-framework/sources/Token.move
add an initial balance to create token event, which will be consumed by downstream indexer
add a mint event as well. will add mint and burn later
Yes
cargo test -p framework passed
=> [ecosystem] add mint event and initial supply to create token event

ecosystem/platform/server/app/javascript/controllers/index.js, ecosystem/platform/server/app/javascript/controllers/refresh_controller.js, ecosystem/platform/server/app/views/leaderboard/it1.html.erb
So you don't have to press F5.
Manual
=> [ecosystem] Auto-refresh the leaderboard table every minute.

ecosystem/platform/server/app/components/dialog_component.html.erb, ecosystem/platform/server/app/components/divider_component.html.erb, ecosystem/platform/server/app/components/divider_component.rb, ecosystem/platform/server/app/helpers/node_helper.rb, ecosystem/platform/server/app/helpers/persona_helper.rb, ecosystem/platform/server/app/views/devise/sessions/new.html.erb, ecosystem/platform/server/app/views/it1_profiles/_form.html.erb, ecosystem/platform/server/app/views/it1_profiles/edit.html.erb, ecosystem/platform/server/app/views/it1_profiles/new.html.erb, ecosystem/platform/server/app/views/layouts/it1.html.erb, ecosystem/platform/server/app/views/leaderboard/it1.html.erb, ecosystem/platform/server/app/views/shared/_bump.html.erb, ecosystem/platform/server/app/views/shared/_bump_hero.html.erb, ecosystem/platform/server/app/views/welcome/it1.html.erb, ecosystem/platform/server/spec/components/divider_component_spec.rb
Replaces bump and bump_hero with a view_component (DividerComponent).
(Separately) Fixes "already initialized constant" errors.
=> [ecosystem] Merge bump and bump_hero into DividerComponent.

ecosystem/platform/server/app/views/leaderboard/it1.html.erb
=> [ecosystem] Update IT1 stats.

ecosystem/web-wallet/src/core/components/Faucet.tsx, ecosystem/web-wallet/src/pages/Wallet.tsx
Making Wallet Faucet its own component
Faucet still operates per normal
```bash
yarn run lint:fix
```
=> Refactor Wallet Faucet to be its own component

docker/compose/aptos-node/validator.yaml, terraform/helm/aptos-node/values.yaml
- tune the timeout
- disable parallel execution
=> [consensus] tune consensus configs

ecosystem/platform/server/config/routes.rb
Replace the it1 landing page with the it1 leaderboard.
Manual
=> [ecosystem] Display leaderboard at /it1.

ecosystem/platform/server/app/helpers/leaderboard_helper.rb, ecosystem/platform/server/app/views/leaderboard/it1.html.erb
=> [ecosystem] Update liveness range & s/Peer ID/Account Address/.

ecosystem/indexer-server/doc/openapi.yaml
Update the OpenAPI spec after review
test API sub generation works
=> [Ecosystem] update the open API based on review feedbacks

Cargo.lock, storage/state-view/Cargo.toml
This just makes the dependencies the same.
=> [storage] Update Move dep to match rest of move dependencies

ecosystem/platform/server/Gemfile, ecosystem/platform/server/Gemfile.lock, ecosystem/platform/server/app/components/button_component.rb, ecosystem/platform/server/app/components/card_outline_component.rb, ecosystem/platform/server/app/controllers/leaderboard_controller.rb, ecosystem/platform/server/app/form_builders/aptos_form_builder.rb, ecosystem/platform/server/app/helpers/genesis_helper.rb, ecosystem/platform/server/app/helpers/node_helper.rb, ecosystem/platform/server/app/helpers/persona_helper.rb, ecosystem/platform/server/app/jobs/it1_final_check_job.rb, ecosystem/platform/server/app/models/application_record.rb, ecosystem/platform/server/app/models/it1_profile.rb, ecosystem/platform/server/db/migrate/20220522220553_add_final_checks_for_it1.rb, ecosystem/platform/server/db/schema.rb
Create a genesis layout (in the style of the demo https://github.com/aptos-labs/jjlake genesis setup)
=> Create Genesis Creator

ecosystem/platform/server/app/views/devise/sessions/new.html.erb, ecosystem/platform/server/app/views/welcome/index.html.erb
Temporarily disable github login until we can update all the pages
=> [CP] Remove github option from Oauth login

terraform/testnet/testnet/templates/faucet.yaml
JSONRPC is gone, replace with api
=> [helm] fix testnet faucet

CODEOWNERS
Adding codeowners file for the docs directory to alert the owners for the docs changes.
=> [Documentation] Adding codeowners for the docs and its subdirectories.

ecosystem/indexer-server/doc/openapi.yaml
fix a error in the metadata API
update the docs for API
=> [Ecosystem] Update metadata API and description

x.toml
=> add CODEOWNER to determinator to fix linter

crates/aptos-faucet/Cargo.toml, crates/aptos-rosetta-cli/Cargo.toml, crates/aptos-rosetta/Cargo.toml, ecosystem/indexer/Cargo.toml, network/peer-monitoring-service/client/Cargo.toml, network/peer-monitoring-service/server/Cargo.toml, storage/aptosdb/src/lib.rs, storage/aptosdb/src/schema/state_value/mod.rs, storage/aptosdb/src/test_helper.rs, testsuite/smoke-test/src/rosetta.rs
CI didn't catch some lint problems, this fixes them
ran `cargo x lint` `cargo x clippy --all-targets` `cargo x fmt` `cargo sort --grouped --check --workspace`
Yes
=> [linters] Fix main branch

execution/executor-types/src/lib.rs, execution/executor/src/block_executor.rs, execution/executor/src/components/block_tree/mod.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/storage-interface/src/lib.rs
according to lazy commit, we are going to separate commits to ledger db and state merkle db separately with different phases. This PR is a preparation for that in terms of API separation.
=> [storage] lazy commit step 1: separate commits to two dbs

developer-docs-site/docs/tutorials/validator-node/connect-to-testnet.md
Fixing a small typo in the documentation
=> Fixing a small typo

storage/aptosdb/src/state_store/mod.rs
we will use get_value_by_version instead at all callsites.
Y
ut
=> [state_store] delete get_value_at_version

Cargo.lock, consensus/Cargo.toml, consensus/src/epoch_manager.rs, consensus/src/quorum_store/quorum_store.rs
=> spawning the real quorum store

aptos-node/src/lib.rs, config/src/config/network_config.rs
=> [Network] Minor changes to network runtime thread config

crates/aptos/src/genesis/mod.rs, x.toml
=> [config] fix the stake amount in genesis tool

developer-docs-site/docs/tutorials/building-wallet-extension.md
Will the latest release of wallet we have some new features that we want to loosely document. Hopefully this week, I'll have a chance to build out the wallet documentation to it's standalone thing
=> [Documentation] Update wallet documentation for latest release

consensus/consensus-types/src/request_response.rs, consensus/src/data_manager.rs, consensus/src/epoch_manager.rs, consensus/src/payload_manager.rs, consensus/src/quorum_store/batch_aggregator.rs, consensus/src/quorum_store/direct_mempool_quorum_store.rs, consensus/src/quorum_store/quorum_store.rs, consensus/src/quorum_store/quorum_store_wrapper.rs, consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs, consensus/src/quorum_store/types.rs, consensus/src/test_utils/mock_payload_manager.rs, consensus/src/txn_notifier.rs
Hopefully, all the logic to start testing is there. 
A few optimizations and refactoring in TODOs
=> wrapper counts batch bytes

ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/token_client.ts, ecosystem/typescript/sdk/src/transaction_builder/aptos_types/transaction.ts, ecosystem/typescript/sdk/src/transaction_builder/bcs/helper.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts, ecosystem/typescript/sdk/src/transaction_builder/transaction_builder.test.ts
Support multiagent transaction submission in TS SDK. 
yarn test
=> [ts-sdk] support multiagent transaction submission

terraform/aptos-node-testnet/addons.tf
Same as https://github.com/aptos-labs/aptos-core/pull/1574, but for when DNS records are not created
=> [tf][testnet] fix ingress var

terraform/helm/monitoring/templates/monitoring.yaml
v1betav1 is deprecated. 
applied to a node on GCP
=> [helm] update monitoring rbac version

terraform/aptos-node-testnet/addons.tf, terraform/aptos-node-testnet/outputs.tf, terraform/helm/testnet-addons/templates/ingress.yaml
Also force all helm_releases to release in TF with timestamp value.
=> [tf][testnet] some cleanup for when zone_id empty

crates/transaction-emitter/src/lib.rs, crates/transaction-emitter/src/main.rs
The logging was a bit of mess, with a blend of log and print. I clean it up here so main uses print while lib uses log. I also improve some of the messages.
See https://www.notion.so/aptoslabs/Single-node-testnet-transaction-load-test-guide-57e82a909e614243bed9694641f581f9.
=> Improve logging situation in txn emitter

terraform/aptos-node/aws/kubernetes.tf, terraform/helm/monitoring/templates/monitoring.yaml, terraform/helm/monitoring/values.yaml, terraform/helm/testnet-addons/templates/ingress.yaml
make google auth work on testnet monitoring
deploy to a testnet
=> [helm] fix google auth for monitoring

terraform/helm/aptos-node/files/configs/fullnode.yaml, terraform/helm/aptos-node/files/configs/validator.yaml, terraform/helm/aptos-node/values.yaml
set couple more configs for nodes
apply to existing deployment
=> [helm] add more validator config

ecosystem/typescript/sdk/CONTRIBUTING.md
Add a light contributing guideline
No
=> chore: add contributing guide for sdk

terraform/aptos-node-testnet/addons.tf, terraform/aptos-node-testnet/variables.tf
So we can override things like WAF / rate limiting settings
=> [tf][testnet] expose testnet-addons values as var

terraform/helm/aptos-node/files/configs/fullnode.yaml
=> [helm][aptos-node] fix templating for max_inbound_connections

ecosystem/typescript/sdk/src/token_client.test.ts, ecosystem/typescript/sdk/src/token_client.ts
1. Existing methods are only able to get token balance for the creator account. Add methods to get token balance for any accounts.
2. Improve the token tests. Add assertions.
yarn test
=> feat: support retrieving token balance for any account

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
Add change log and bump to version 1.2.0
N/A
=> [ts-sdk] changelog and bump to version 1.2.0

aptos-move/framework/aptos-framework/sources/configs/Stake.move
=> [Stake] validate consensus public key

Cargo.lock, aptos-move/vm-genesis/src/lib.rs, config/src/config/consensus_config.rs, consensus/src/epoch_manager.rs, consensus/src/twins/basic_twins_test.rs, consensus/src/twins/twins_node.rs, types/Cargo.toml, types/src/on_chain_config/consensus_config.rs, types/src/on_chain_config/mod.rs
=> [consensus] Move protocol-affecting configs to onchain configuration

terraform/helm/monitoring/files/prometheus.yml, terraform/helm/monitoring/files/rules/alerts.yml
remove unused labels 
deploy on sherryx testnet
=> [helm] update alerts

consensus/src/epoch_manager.rs, consensus/src/network.rs, consensus/src/state_computer.rs
=> [consensus] fix metrics report

docker/rust-all.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1596)
=> [testnet] Install the perf metapackage for debian based distro

terraform/helm/aptos-node/templates/validator.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1636)
=> [testnet] In privileged mode, log in as root

.github/workflows/copy-images-to-dockerhub-nightly.yaml, .github/workflows/prune-old-workflow-runs.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1637)
=> cicd: skip running cronjobs on forks

ecosystem/platform/server/app/components/header_component.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1633)
=> [ecosystem] Add settings link to nav.

ecosystem/platform/server/config/routes.rb
In preparation for IT2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1641)
=> [ecosystem] Redirect to /it2 instead of /it1 after confirming email.

ecosystem/platform/server/app/models/user.rb, ecosystem/platform/server/app/views/onboarding/email.html.erb, ecosystem/platform/server/app/views/settings/profile.html.erb
Adds `-_` and removes `#` from username chars.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1642)
=> [ecosystem] Update username format & add placeholder text.

terraform/aptos-node/aws/versions.tf, terraform/aptos-node/azure/versions.tf, terraform/aptos-node/gcp/versions.tf
Upgrade terraform
Terraform init on couple of my aptos-node deployment, and make sure they can be applied successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1652)
=> [tf] upgrade to latest for terraform

terraform/helm/monitoring/templates/monitoring.yaml, terraform/helm/monitoring/values.yaml
As above
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1644)
=> Add support for deleteWal in test-net

crates/aptos/src/node/mod.rs
Make input easier for users
Works with the CLI:
```
aptos node register-validator-candidate --validator-config-file me.yaml --profile local
{
"Result": {
"type": "user_transaction",
"version": "76684",
"hash": "0xf842fcc6f5f6dd898ad78e000b5071c6990c3e7220e379f0fe1a70df436a1ce6",
"state_root_hash": "0x5b49ce34a8610b1b79606383b662966f7a3f42098b1fe5d1e23c4092c6503b87",
"event_root_hash": "0x414343
...
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1653)
=> [aptos-cli] Add validator configuration file as input for register validator candidate

Cargo.lock, crates/aptos-workspace-hack/Cargo.toml, crates/aptos/Cargo.toml, crates/aptos/src/account/list.rs, crates/aptos/src/common/types.rs, crates/aptos/src/node/mod.rs
Add viewing CLI commands, as well as cleanup so we can put in "1 day" or "1d" as inputs to duration.
I tested these all manually via the CLI
```
$ aptos node show-validator-stake --profile local
{
"Result": {
"active": {
"value": "0"
},
"inactive": {
"value": "0"
},
"locked_until_secs": "1656558293",
"operator_address": "0xcb48471868293a5feb8fac3871775b62a671b7c405b43e7755f368901df9ec8c",
"pending_active": {
"value": "0"
},
"pending_inactive": {
"value": "0"
}
}
}
$ aptos node show-validator-config --profile local
{
"Result": {
"consensus_pubkey": "0xd7da35e9f58f7b9e4891a15480feb688484d325b220ae047c891940b4734a445",
"fullnode_addresses": "0x00",
"network_addresses": "0x012d0400000000000539050720d2abf50d6eb7df2d8aadc546ee8d868e8ea581a04deb2a4aca03893f51c1e76a0800",
"validator_index": "0"
} …
```
=> [aptos-cli] Address more tooling feedback

developer-docs-site/docs/nodes/validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/using-docker.md, developer-docs-site/docs/nodes/validator-node/using-gcp.md, developer-docs-site/docs/nodes/validator-node/using-source-code.md
Update node installation doc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1660)
=> [doc] update instruction for ait2

developer-docs-site/docs/nodes/ait/connect-to-testnet.md, developer-docs-site/docs/nodes/validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/using-docker.md, developer-docs-site/docs/nodes/validator-node/using-gcp.md, developer-docs-site/docs/nodes/validator-node/using-source-code.md
more docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1662)
=> [doc] add staking instruction

ecosystem/platform/server/.env.example, ecosystem/platform/server/app/components/header_component.rb, ecosystem/platform/server/app/controllers/application_controller.rb, ecosystem/platform/server/app/controllers/discourse_controller.rb, ecosystem/platform/server/app/controllers/settings_controller.rb, ecosystem/platform/server/app/helpers/discourse_helper.rb, ecosystem/platform/server/app/helpers/node_helper.rb, ecosystem/platform/server/app/models/user.rb, ecosystem/platform/server/app/views/it2_profiles/_form.html.erb, ecosystem/platform/server/app/views/layouts/it2.html.erb, ecosystem/platform/server/app/views/onboarding/email.html.erb, ecosystem/platform/server/app/views/settings/connections.html.erb, ecosystem/platform/server/app/views/settings/profile.html.erb, ecosystem/platform/server/config/routes.rb, ecosystem/platform/server/test/controllers/settings_controller_test.rb, ecosystem/platform/server/test/models/user_test.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1638)
=> [CP] Smooth discourse SSO

developer-docs-site/docs/nodes/validator-node/using-source-code.md
Add instruction to download framework directly, instead of build it your own
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1667)
=> [doc] update node doc

docker/compose/aptos-node/validator.yaml, terraform/helm/aptos-node/files/configs/validator.yaml, terraform/helm/aptos-node/values.yaml
- update quorum_store_poll_count
- turn metrics port on as default, and we will ask people to close it off later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1668)
=> Update node config

developer-docs-site/docs/nodes/ait/connect-to-testnet.md
ask people to close metrics port when joining the network
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1669)
=> [doc] add instruction to close metrics port

ecosystem/platform/server/app/components/header_component.rb, ecosystem/platform/server/app/controllers/it2_profiles_controller.rb
Only use NHC if the `:node_health_checker` flag is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1670)
=> [ecosystem] Add feature flag for node health checker.

terraform/helm/monitoring/files/dashboards
update symlink for dashboards
apply to a node
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1672)
=> [helm] update link for dashboards

ecosystem/platform/server/app/components/button_component.rb, ecosystem/platform/server/app/views/it2_profiles/_form.html.erb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1682)
=> [community] Add style for disabled buttons.

ecosystem/web-wallet/src/scripts/background.js
We're actually trying to use the official wallet to submit user transaction. TypeScript would have called it out.
Tested by using the wallet extension in our dex dapp (successful in sending user transactions after the fix).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1665)
=> [wallet]: fix signAndSubmitTransaction

developer-docs-site/docs/guides/getting-started.md, developer-docs-site/docs/nodes/ait/connect-to-testnet.md, developer-docs-site/docs/nodes/ait/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1684)
=> [Docs] Link fixes and minor text fixes.

developer-docs-site/docs/nodes/ait/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1686)
=> [Docs] Link fix.

storage/storage-interface/src/lib.rs, types/src/transaction/mod.rs
Remove definition of PRE_GENEIS_VERSION
UTs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1692)
=> [storage] Delete definition of PRE_GENEIS_VERSION

ecosystem/node-checker/src/evaluators/direct/latency.rs, ecosystem/node-checker/src/evaluators/direct/node_identity.rs
These should be fast.
Same as https://github.com/aptos-labs/aptos-core/pull/1683.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1694)
=> [NHC] Set better timeouts for hitting nodes

.github/workflows/build-images.yaml, .github/workflows/deploy-community-platform-to-staging.yaml, .github/workflows/deploy-community-platform.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1696)
=> cicd: community-platform worker deployment

.github/workflows/deploy-community-platform.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1698)
=> cicd: fix CP deployment config

ecosystem/platform/server/app/controllers/it2_profiles_controller.rb, ecosystem/platform/server/app/jobs/nhc_job.rb, ecosystem/platform/server/app/models/it2_profile.rb, ecosystem/platform/server/app/views/it2_profiles/_form.html.erb, ecosystem/platform/server/config/database.yml, ecosystem/platform/server/db/migrate/20220701031008_add_job_id_to_it2_profile.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1699)
=> [CP] fix CP NHC

crates/aptos/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1704)
=> update version of CLI

ecosystem/platform/server/app/controllers/onboarding_controller.rb, ecosystem/platform/server/app/models/user.rb, ecosystem/platform/server/app/views/devise/sessions/new.html.erb, ecosystem/platform/server/app/views/static_page/community.html.erb
Tested manually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1726)
=> [CP] Enable Github Login + fix weird null email edge case

Cargo.lock, Cargo.toml, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-module-verifier/src/lib.rs, aptos-move/aptos-module-verifier/src/module_init.rs, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/aptos_vm.rs, crates/aptos/Cargo.toml, crates/aptos/src/move_tool/mod.rs, testsuite/smoke-test/src/aptos/module_publish.rs, testsuite/smoke-test/src/aptos/move_modules/sources/hello.move
To allow initialize data when publishing the module. 
The function should 
1. have a name `init_module`
2. be private 
3. not return any value
Yes
Added new smoke test 
tested in Cli manually and see error as expected
--- …
=> [Ecosystem] auto execute init_module when publishing module

api/types/src/move_types.rs, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/block.rs, crates/aptos-rosetta/src/types/misc.rs, crates/aptos-rosetta/src/types/objects.rs
This allows us now to fully pass the check:data tests in rosetta except for one case:
Gas is collected at a time that isn't clear via the current interfaces.  This makes the rosetta reconciler fail and then it won't pass.
Why does this use JSON instead of BCS?  Well, it required a bunch of changes on the API that will come in the future, but I didn't want to touch it for now.
Additionally, I know it's not the cleanest and it's very messy, but I will come back to break it down more in the future.
```
rosetta-cli check:data --configuration-file rosetta_config.json
...
+--------------------+--------------------------------+--------+
|  CHECK:DATA TESTS  |          DESCRIPTION           | STATUS |
+--------------------+--------------------------------+--------+
| Request/Response   | Rosetta …
```
=> [aptos-rosetta] Finish reconciliation and operation parsing for blocks

ecosystem/platform/server/app/admin/users.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1767)
=> [CP] Quick fix admin users view

developer-docs-site/docs/nodes/node-health-checker-faq.md, ecosystem/node-checker/src/main.rs
@rajkaramchedu since the other PR landed somewhat inadvertently, we can use this PR as a chance to fix up developer-docs-site/docs/nodes/node-health-checker-faq.md if necessary.
```
cargo test
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1765)
=> [NHC] Make minor docs and logging changes

ecosystem/platform/server/app/admin/users.rb, ecosystem/platform/server/app/models/user.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1768)
=> [CP] Add IT1Profile links to admin user view

crates/aptos/README.md
… 0.2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1732)
=> change the aptos-cli install command using cargo to aptos-cli version 0.2.0

developer-docs-site/docs/guides/getting-started.md
Checking this simple task off my list.
cc: @geekflyer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1772)
=> [Docs] Adding move-analyzer VS Code plugin link.

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_script_function_payload.json, api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json, api/types/src/transaction.rs, ecosystem/indexer/migrations/2022-07-06-183433_add_failed_to_block_metadata_transactions/down.sql, ecosystem/indexer/migrations/2022-07-06-183433_add_failed_to_block_metadata_transactions/up.sql, ecosystem/indexer/src/indexer/tailer.rs, ecosystem/indexer/src/models/transactions.rs, ecosystem/indexer/src/schema.rs, types/src/block_metadata.rs
Used RestClient in smoke test I am testing leader election on to confirm correct
failed_proposer_indices are present
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1710)
=> Add failed_proposer_indices to indexer/API

terraform/aptos-node-testnet/main.tf, terraform/helm/testnet-addons/templates/loadtest.yaml
Fix minor tf incompatibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1805)
=> [loadtest] Get loadtest working with recent txn emitter changes

consensus/consensus-types/src/quorum_cert.rs, consensus/consensus-types/src/sync_info.rs, consensus/src/block_storage/block_store.rs, consensus/src/block_storage/block_tree.rs, consensus/src/block_storage/mod.rs, consensus/src/block_storage/sync_manager.rs, consensus/src/persistent_liveness_storage.rs, testsuite/generate-format/tests/staged/consensus.yaml
Leaving fixing of the bug and fetching appropriate blocks to a separate diff
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1813)
=> [consensus] Propagate commit QC

crates/aptos-metrics-core/src/lib.rs, execution/executor/src/metrics.rs, storage/aptosdb/src/metrics.rs, storage/schemadb/src/metrics.rs, storage/scratchpad/src/sparse_merkle/metrics.rs
Apply proper buckets for latency related metrics, so we can get better understanding of the distribution.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1820)
=> [Metrics] Apply proper buckets for latency related metrics.

consensus/consensus-types/src/quorum_cert.rs, consensus/consensus-types/src/sync_info.rs, consensus/src/block_storage/block_store.rs, consensus/src/block_storage/block_tree.rs, consensus/src/block_storage/mod.rs, consensus/src/block_storage/sync_manager.rs, consensus/src/persistent_liveness_storage.rs, testsuite/generate-format/tests/staged/consensus.yaml
Leaving fixing of the bug and fetching appropriate blocks to a separate diff
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1843)
=> [cherry-pick][consensus] Propagate commit QC (#1813)

consensus/consensus-types/src/block.rs, consensus/consensus-types/src/block_data.rs, consensus/consensus-types/src/block_test.rs, consensus/safety-rules/src/fuzzing_utils.rs, consensus/src/liveness/proposal_generator.rs, consensus/src/round_manager.rs, testsuite/generate-format/tests/staged/consensus.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1845)
=> [cherry-pick][consensus] Add failed authors to NIL block (#1717)

consensus/src/block_storage/sync_manager.rs, consensus/src/persistent_liveness_storage.rs
https://www.notion.so/aptoslabs/Bug-in-block-retrieval-71d4191353c84dca80374e4dd38bbe93
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1826)
=> [consensus] Fix missing QC when highest_commit_cert is pointing to a dangling node

consensus/src/block_storage/sync_manager.rs, consensus/src/persistent_liveness_storage.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1851)
=> [cherry-pick][consensus] Fix missing QC when highest_commit_cert is pointing to a dangling node

.dockerignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1855)
=> fix docker image builds

docker/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1858)
=> infra: add instructions how to build docker images

docker/README.md, x.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1859)
=> infra: fix readme formatting and ignore MD files in x-lint

developer-docs-site/docs/guides/getting-started.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1875)
=> docs: Update link to Aptos CLI releases

consensus/src/counters.rs, consensus/src/liveness/leader_reputation.rs
.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1802)
=> [consensus] Fix failed proposals counter

ecosystem/platform/server/app/components/header_component.html.erb, ecosystem/platform/server/app/javascript/controllers/header_controller.ts
Opens the user menu on click instead of on hover. The nav menu is closed when the user menu is opened and vice versa.
Manual
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1879)
=> [community] Open user menu on click.

developer-docs-site/docs/tutorials/first-move-module.md
add documentation for describing init_module function 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1884)
=> [Ecosystem] add init_module description

developer-docs-site/docs/guides/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1888)
=> Fix typos in getting-started.md

developer-docs-site/docs/nodes/ait/additional-doc.md, developer-docs-site/docs/nodes/ait/connect-to-testnet.md, developer-docs-site/sidebars.js
- add destroy instruction
- add monitoring instruction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1889)
=> [doc] add more docs for ait

developer-docs-site/docs/tutorials/first-move-module.md
@areshand, a minor tweak to the description in this PR:https://github.com/aptos-labs/aptos-core/pull/1884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1887)
=> [Docs] Minor init_module doc fix.

consensus/consensus-types/src/sync_info.rs, consensus/src/block_storage/sync_manager.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1901)
=> [consensus] cleanup for block retrieval

ecosystem/platform/server/app/components/table_header_column_component.rb, ecosystem/platform/server/app/controllers/application_controller.rb, ecosystem/platform/server/app/controllers/leaderboard_controller.rb, ecosystem/platform/server/app/controllers/onboarding_controller.rb, ecosystem/platform/server/app/helpers/application_helper.rb, ecosystem/platform/server/app/views/leaderboard/it2.html.erb, ecosystem/platform/server/config/routes.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1896)
=> Update final things for AIT2 launch

ecosystem/platform/server/app/helpers/application_helper.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1905)
=> [CP] fix missing sort param breaking

ecosystem/platform/server/app/views/layouts/it2.html.erb
Update AIT2 Schedule
Manual Review:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1903)
=> [CP] update AIT2 schedule & typography hierarchy adjustments

scripts/find-packages-with-undeclared-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1936)
=> devinfra: make undeclared feature dependency script fail when it finds a missing declaration

storage/aptosdb/src/pruner/state_store/mod.rs
see inline comment
a bit tricky to test, I'd delegate to our eyes if okay..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1850)
=> [storage] state pruner: fix stale node index purging logic

consensus/consensus-types/src/request_response.rs, consensus/src/data_manager.rs, consensus/src/epoch_manager.rs, consensus/src/payload_manager.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/mod.rs, consensus/src/quorum_store/quorum_store_db.rs, consensus/src/quorum_store/quorum_store_wrapper.rs, consensus/src/quorum_store/schema.rs, consensus/src/state_computer.rs, consensus/src/state_replication.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1917)
=> persist batch id

ecosystem/platform/server/Gemfile, ecosystem/platform/server/Gemfile.lock, ecosystem/platform/server/config/environments/production.rb
Tested with local redis, confirmed that cache items were being written to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1928)
=> [community] Use redis for caching in production.

ecosystem/platform/server/app/components/button_component.rb, ecosystem/platform/server/app/components/footer_component.html.erb, ecosystem/platform/server/app/components/footer_component.rb, ecosystem/platform/server/app/form_builders/aptos_form_builder.rb
In preparation for #1640.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1918)
=> [community] Use the marketing footer on community.

consensus/consensus-types/src/sync_info.rs, consensus/src/block_storage/sync_manager.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1948)
=> [cherry-pick][consensus] cleanup for block retrieval

ecosystem/platform/server/Gemfile, ecosystem/platform/server/Gemfile.lock, ecosystem/platform/server/app/controllers/health_controller.rb, ecosystem/platform/server/spec/factories/it2_profiles.rb, ecosystem/platform/server/spec/factories/users.rb, ecosystem/platform/server/test/controllers/it2_profiles_controller_test.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1514)
=> [ecosystem] Add test for It2ProfilesController.

Cargo.lock, api/src/context.rs, api/src/transactions.rs, api/types/src/error.rs, api/types/src/hash.rs, api/types/src/move_types.rs, crates/aptos-rosetta-cli/src/common.rs, crates/aptos-rosetta/Cargo.toml, crates/aptos-rosetta/aptos.ros, crates/aptos-rosetta/build.rs, crates/aptos-rosetta/rosetta_cli.json, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/block.rs, crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/error.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/network.rs, crates/aptos-rosetta/src/types/identifiers.rs, crates/aptos-rosetta/src/types/objects.rs, crates/aptos-rosetta/src/types/requests.rs
Some inconsistent inputs, and additional missing debug data was making it hard to test.  Now, there's proper debug data, the DSL is complete, with a possible need  of a few tweaks, and there may be some work around some edge cases left.
I will be coming back around to fix documentation, and some of the other edge cases after this PR.
```
[STATS] Blocks: 1225 (Orphaned: 0) Transactions: 2483 Operations: 119 Accounts: 17 Reconciliations: 117 (Inactive: 46, Exempt: 0, Skipped: 0, Cov)
Success: Reconciliation Coverage End Condition [Coverage: 100.000000%]
+--------------------+--------------------------------+--------+
|  CHECK:DATA TESTS  |          DESCRIPTION           | STATUS |
+--------------------+--------------------------------+--------+
| Request/Response   | Rosetta implementation …
```
=> [aptos-rosetta] Ensure construction APIs all work

ecosystem/platform/server/README.md
update readme file with development instructions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1949)
=> update readme file with dev instructions

state-sync/inter-component/mempool-notifications/src/lib.rs
Minor review comments as a follow up from https://github.com/aptos-labs/aptos-core/pull/1965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1980)
=> [mempool] Address minor review comments

consensus/src/block_storage/sync_manager.rs, consensus/src/experimental/buffer_manager.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1979)
=> [cherrypick] another attempt to fix the race condition in buffer manager

consensus/src/quorum_store/quorum_store_db.rs, consensus/src/quorum_store/quorum_store_wrapper.rs, consensus/src/quorum_store/tests/quorum_store_wrapper_test.rs
Created `trait BatchIdDB` and mocked it for the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1982)
=> Fix quorum_store_wrapper_test.

aptos-move/framework/aptos-framework/sources/TokenV1.move
1. add a TokenCapabilityStore for storing burn capability
2. add functions for create and delegate burn capability. Not implementing revoke since it is not needed (it doesn't make sense from another entity to revoke the burn capability assigned to the owner.)
add a move unit test
cargo test -p framework
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1871)
=> [Token] add burn function and capability

crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs, crates/aptos/src/account/transfer.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/node/mod.rs
Right now this should support both upper and lower until it's updated, then we can remove the upper version.
Unit tests?  We'll see how they go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1988)
=> [aptos-cli/rosetta] Support lowercase module names

aptos-move/framework/aptos-framework/sources/Voting.move
Proposals were deleted to save on storage before but this makes it harder for off chain components such as the Voting UI to query past proposals. They would need to rely on events but this can be tricky for certain setups. We shouldn't have a lot of proposals so there's not too much storage implication for storing resolved proposals.
Unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1992)
=> [Aptos Framework] Don't delete proposals after resolution

developer-docs-site/docusaurus.config.js, developer-docs-site/src/css/custom.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1996)
=> Fixed dark mode items: search results window color and footer logo

consensus/src/network_interface.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1997)
=> [consensus] switch from json to bcs

execution/executor-types/src/in_memory_state_calculator.rs, execution/executor/src/block_executor.rs, execution/executor/src/chunk_executor.rs, execution/executor/src/db_bootstrapper.rs, execution/executor/src/fuzzing.rs, execution/executor/src/tests/mod.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/test_helper.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs, storage/storage-interface/src/executed_trees.rs, storage/storage-interface/src/lib.rs, storage/storage-interface/src/state_delta.rs
Also rename its fields.
ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2006)
=> [easy] rename InMemoryState to StateDelta

api/goldens/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json, aptos-move/vm-genesis/src/lib.rs, types/src/account_config/constants/addresses.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1984)
=> [Aptos Framework] Enable Aptos Governance by default

.github/workflows/run-forge.yaml
pass the GH secret to Env Var, which is used in the comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2009)
=> [gha] propagate forge blocking var

crates/aptos-genesis/src/builder.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2010)
=> [smoke test] use on disk storage in smoke tests

docker/rosetta/README.md, docker/rosetta/docker-build-rosetta.sh, docker/rosetta/rosetta.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2012)
=> rosetta: improve dockerfile for rosetta

crates/aptos-rosetta/src/main.rs, crates/aptos/src/local_testnet/mod.rs, docker/rosetta/README.md, docker/rosetta/rosetta.Dockerfile
I can't seem to get these to build with the script without it being in main, but it should fix the issues of connectivity on startup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2011)
=> [aptos-rosetta] Fix dockerfiles

aptos-move/framework/aptos-framework/sources/AptosGovernance.move, aptos-move/framework/aptos-framework/sources/Reconfiguration.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2033)
=> [Aptos Framework] Allow on-chain governance proposals to trigger reconfiguration in case of on-chain config changes

developer-docs-site/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2051)
=> Removing git fork step

.github/workflows/lint-test.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2066)
=> cicd: skip uploading datadog test reports on fork-based PRs

developer-docs-site/docs/nodes/run-a-local-testnet.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2019)
=> docs: update local testnet docs title

aptos-move/framework/aptos-framework/sources/AptosGovernance.move, aptos-move/framework/aptos-framework/sources/GovernanceProposal.move, aptos-move/framework/aptos-framework/sources/Voting.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1987)
=> [Aptos Framework] Add required fields to governance proposal

testsuite/forge/src/backend/k8s/swarm.rs
Run forge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2069)
=> [forge] Increase genesis timeout to 10 mins

testsuite/run_forge.sh
After a bunch of improvement to forge, we now can consistently do over 5k TPS. Tuning the parameters so that we don't regress.
Past forge runs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2061)
=> [forge] Tune TPS threshold and latency for forge

Cargo.lock, consensus/consensus-types/Cargo.toml, consensus/consensus-types/src/block.rs, consensus/consensus-types/src/common.rs, consensus/consensus-types/src/executed_block.rs, consensus/src/block_storage/block_store.rs, consensus/src/data_manager.rs, consensus/src/epoch_manager.rs, consensus/src/state_computer.rs, consensus/src/test_utils/mock_state_computer.rs
adding expirations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2079)
=> cache data

storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/db_pruner.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs, storage/aptosdb/src/pruner/state_store/mod.rs, storage/aptosdb/src/pruner/worker.rs
Move ledger_db_batch into ledger pruner since it is not needed by state store pruner
Existing UTs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2084)
=> [storage][pruner] Refactor worker.rs

types/src/state_store/state_value.rs
as title
ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2056)
=> [storage] skip serde StateValue hash

.gitattributes
use move syntax highlighting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2037)
=> use move syntax highlighting

api/src/param.rs, api/src/state.rs, api/types/src/convert.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, testsuite/generate-format/tests/staged/aptos.yaml, testsuite/generate-format/tests/staged/consensus.yaml, types/src/state_store/mod.rs, types/src/state_store/state_key.rs, types/src/state_store/table.rs
in case we change the table handle from u128 to something longer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2107)
=> [storage] TableHandle

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
Update docs to match reality
TODO: Add documentation around node commands for staking
TODO: Update genesis documentation
Just docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2124)
=> [aptos-cli] Update documentation for Aptos CLI

crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/identifiers.rs, crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs, crates/aptos-rosetta/src/types/requests.rs, crates/aptos/src/test/mod.rs, testsuite/smoke-test/src/rosetta.rs
Adds back in E2E tests for Rosetta.  Now that Rosetta has been stabilized, this should prevent things from breaking as much.
TODO: Add more testing around certain fields, and construction APIs
These are the tests :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2043)
=> [aptos-rosetta] E2E testing

developer-docs-site/docs/nodes/ait/connect-to-testnet.md
add instruction on how people leave validator set properly 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2148)
=> [doc] add leave instruction

terraform/helm/aptos-node/files/configs/fullnode.yaml, terraform/helm/aptos-node/files/configs/validator.yaml, terraform/helm/aptos-node/values.yaml
Propagate config from https://github.com/aptos-labs/aptos-core/pull/2004 into the validator and fullnode configs in helm chart.
(tbd) Validators spin up in Forge with correct config, and test passes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2161)
=> [helm][aptos-node] config for incremental pruning

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
Upgrade the SDK version so we can release it.
Should it be a minor version release?  Probably, but we're doing too many minor version releases above 1 right now, and we'll need another one next week.
```
yarn test
yarn run v1.22.19
$ jest
PASS  src/transaction_builder/aptos_types/multi_ed25519.test.ts
PASS  src/hex_string.test.ts
PASS  src/transaction_builder/aptos_types/account_address.test.ts
PASS  src/transaction_builder/bcs/helper.test.ts
PASS  src/transaction_builder/bcs/deserializer.test.ts
PASS  src/util.test.ts
PASS  src/transaction_builder/bcs/serializer.test.ts
PASS  src/aptos_account.test.ts
PASS  src/transaction_builder/transaction_builder.test.ts
PASS  src/faucet_client.test.ts (6.841 s)
PASS  src/transaction_builder/transaction_vector.test.ts (13.802 s)
PASS …
```
=> [ts-sdk] Upgrade to 1.2.1 for release

developer-docs-site/docusaurus.config.js, developer-docs-site/sidebars.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2176)
=> [Docs] Using Stoplight version of REST API docs.

api/types/src/error.rs
More minor renamings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2179)
=> [Cleanup] Renaming

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
- clean typo
- https://github.com/aptos-labs/aptos-core/pull/1658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2184)
=> [doc] clean: fix typo - AptosCoib -> AptosCoin

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
Apply change I applied to devnet.
This won't work against the main code base.  It will need to be upgraded in a following PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2175)
=> [ts-sdk] Upgrade to 1.2.1

consensus/src/liveness/round_state.rs, consensus/src/round_manager.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2187)
=> [consensus] only echo timeout when no timeout yet

aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
Other blockchains typically allow folks to create accounts and transfer
funds at the same time, because the idea of an account is just ownership
of a private key. Aptos uses a different model, which means that
accounts must be created first.
We could generalize this to any coin or other resource types, but I'm
cautious to support this more generally as each interaction likely has
certain specializers that expect the signer to explicitly opt-in --
except for this one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2185)
=> [framework] add a transfer and optionally create account function

developer-docs-site/docs/sdks/transactions-with-ts-sdk.md
TestCoin -> AptosCoin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2150)
=> [doc] Upate TestCoin to AptosCoin for the transactions with sdk doc

Cargo.lock, vm-validator/Cargo.toml, vm-validator/src/vm_validator.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2194)
=> [cherry-pick][vm-validator] hot fix for vm-validator memory leak

testsuite/run_forge.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2196)
=> observability: post humio link to forge logs into github PR

api/doc/openapi.yaml, ecosystem/typescript/sdk/README.md, ecosystem/typescript/sdk/src/api/Transactions.ts, ecosystem/typescript/sdk/src/api/data-contracts.ts, ecosystem/typescript/sdk/src/aptos_client.ts, ecosystem/typescript/sdk/src/transaction_builder/aptos_types/transaction.ts, ecosystem/typescript/sdk/src/transaction_builder/aptos_types/type_tag.ts
Updates module names that were not lowercased
CI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2146)
=> [ts-sdk] Update module names to be lowercase

.github/workflows/build-images.yaml, .github/workflows/run-forge.yaml, testsuite/run_forge.sh
Revert the change to build docker on merge, since that doesn't seem to be working  well.
Also fix syntax error in `run_forge.sh` that results in sticky comment not working
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2207)
=>  [gha] build docker on head sha and fix forge sticky comment

CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2212)
=> [docs] added owner for cryptography crate

ecosystem/platform/server/app/assets/images/icons/accordion_arrow.svg, ecosystem/platform/server/app/components/header_component.html.erb, ecosystem/platform/server/app/javascript/controllers/header_controller.ts
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2230)
=> [community] Implement accordion mobile nav.

ecosystem/platform/server/app/components/header_component.html.erb, ecosystem/platform/server/app/javascript/controllers/header_controller.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2233)
=> [community] Show a close icon when the mobile nav is open.

developer-docs-site/docs/nodes/index.md
Reported by James Waugh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2231)
=> [Docs] Fixing pesky links that break on some iPhones.

Cargo.lock, aptos-move/move-deps/Cargo.toml, storage/state-view/Cargo.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2237)
=> [move] update Move dependency

.github/workflows/build-images.yaml
build on merged git sha rather than tip of PR branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2204)
=> [gha] build on merge sha

.github/workflows/build-images.yaml
Reverts aptos-labs/aptos-core#2204
due to issue with image pulling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2252)
=> Revert "[gha] build on merge sha"

developer-docs-site/docs/tutorials/first-transaction.md
See title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2246)
=> Fix grammar

aptos-move/framework/aptos-framework/sources/configs/stake.move
Partial withdrawal is useful for staking services as it allows withdrawing exactly the amount needed for a single user.
Unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2199)
=> [Aptos Framework] Add more getters to Stake module and update withdraw to allow partial withdrawals

ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/transaction_builder/aptos_types/transaction.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts
Add UserTransaction and allow users to calculate the hash on the client side
Added a test case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2236)
=> feat: add UserTransaction and hashing capability

aptos-move/framework/aptos-framework/sources/aptos_governance.move
So calling create_proposal via the simulation API can return the proposal id for off-chain usage convenience.
Unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2227)
=> [Aptos Framework] Return proposal id from aptos_governance::create_proposal

crates/aptos-crypto/src/ed25519.rs, crates/aptos-crypto/src/ed25519/ed25519_keys.rs, crates/aptos-crypto/src/ed25519/ed25519_sigs.rs, crates/aptos-crypto/src/ed25519/mod.rs
Just moving files around for now. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2225)
=> Reorganize Ed25519 implementation

developer-docs-site/docs/cli-tools/aptos-cli-tool/index.md, developer-docs-site/docs/nodes/run-a-local-testnet.md
Fixing local testnet doc errors pointed out by a partner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2244)
=> [Docs] Doc fixes to local testnet and aptos cli index pages.

aptos-node/src/lib.rs, consensus/src/state_computer.rs, execution/executor-types/src/lib.rs, execution/executor/src/block_executor.rs, execution/executor/src/chunk_executor.rs, execution/executor/src/components/chunk_commit_queue.rs, execution/executor/src/fuzzing.rs, execution/executor/src/tests/chunk_executor_tests.rs, execution/executor/src/tests/mod.rs, state-sync/state-sync-v1/src/executor_proxy.rs, state-sync/state-sync-v1/src/shared_components.rs, state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-v2/state-sync-driver/src/driver.rs, state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, state-sync/state-sync-v2/state-sync-multiplexer/src/lib.rs, storage/aptosdb/src/lib.rs, storage/backup/backup-cli/src/backup_types/transaction/restore.rs, testsuite/run_forge.sh
Fix memory leak.
ut and forge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2241)
=> [cherry-pick][fix] wrap BlockExecutor and ChunkExecutor as an Option of Inner (#2210)

aptos-move/framework/aptos-framework/sources/aptos_governance.move
Reverts aptos-labs/aptos-core#2227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2266)
=> Revert "[Aptos Framework] Return proposal id from aptos_governance::create_proposal"

.github/workflows/run-forge.yaml, testsuite/forge-test-runner-template.yaml, testsuite/forge/src/success_criteria.rs, testsuite/run_forge.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2257)
=> cicd: fix forge comment logic

Cargo.lock, crates/aptos/Cargo.toml, ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
New versions of the SDK for the latest devnet release
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2283)
=> [aptos-cli/sdk] Release new version of SDK & CLI

.config/nextest.toml, .github/workflows/coverage.yaml, crates/aptos-logger/src/aptos_logger.rs
previous config didn't actually run all tests as desired due to a bug in llvm-cov's argument parsing.
Implementing the workaround of flipping argument order and other things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2255)
=> cicd: fix coverage config

aptos-move/aptos-transactional-test-harness/Cargo.toml, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
I just ran my linting script: https://gist.github.com/banool/5743d283a4fbafb4fb12645e5ff42fde.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2290)
=> Run linter on aptos-move

developer-docs-site/docs/tutorials/first-transaction.md
see title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2294)
=> align code snippet indentation

.github/workflows/pre-release-continuous-test.yaml
Woops this is still required
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2314)
=> [forge] Pass merge or canary to forge workflow

.github/actions/rust-setup/action.yaml, aptos-move/move-examples/tests/move_prover_tests.rs
install the Prover dependencies such as Z3 and Boogie
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2217)
=> [move-prover] Updated the rust build setup to install Prover's dependencies for CI

ecosystem/platform/server/app/components/footer_component.html.erb, ecosystem/platform/server/app/components/footer_component.rb
Update bg-color and icon.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2311)
=> [community] Update footer design.

ecosystem/platform/server/app/components/header_component.rb, ecosystem/platform/server/app/javascript/controllers/header_controller.ts
Fixes an issue with nav visibility if the viewport changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2271)
=> [community] Close the nav on window resize.

testsuite/forge/src/backend/k8s/helm-values/aptos-node-values.yaml
To get more signal when we're collecting logs via collector, rather than using remote log
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2321)
=> [forge] default debug rust_log

state-sync/state-sync-v2/state-sync-driver/src/driver.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2326)
=> [cherry-pick][State Sync] Add a yield to the driver to avoid spin locking.

Cargo.lock, api/goldens/aptos_api__tests__transactions_test__test_get_transaction_by_hash.json, api/src/accounts.rs, api/src/context.rs, api/src/events.rs, api/src/poem_backend/accounts.rs, api/src/poem_backend/events.rs, api/src/poem_backend/transactions.rs, api/src/state.rs, api/src/tests/converter_test.rs, api/src/tests/transactions_test.rs, api/src/transactions.rs, api/types/Cargo.toml, api/types/src/convert.rs, api/types/src/move_types.rs, api/types/src/transaction.rs, aptos-move/aptos-transactional-test-harness/Cargo.toml, aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs, ecosystem/indexer/src/models/write_set_changes.rs, storage/aptosdb/src/lib.rs, storage/storage-interface/src/lib.rs
If the indexer is enabled, we expect the values to be there. Otherwise, we don't populate this in the API.
This is the pre-step to putting this into the indexer (as we re-use the types + converter)
`cargo test test_get_transaction_by_hash`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2301)
=> [API] Add table data on writes to API

consensus/src/experimental/buffer_manager.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2330)
=> [consensus] revert spawn retry request in buffer manager

developer-docs-site/docs/guides/move-guides/move-on-aptos.md, developer-docs-site/docs/tutorials/first-coin.md
see title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2304)
=> [Docs] Doc fixes broken link and refactored module name

mempool/src/shared_mempool/coordinator.rs
this was printing every transaction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2329)
=> trivial: remove a spammy debug log

developer-docs-site/docs/guides/move-guides/move-on-aptos.md
see title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2338)
=> [Docs] fix broken links

crates/aptos/src/test/mod.rs, testsuite/smoke-test/src/aptos_cli.rs, testsuite/smoke-test/src/rosetta.rs
Config was causing contention among tests.  Now it just keeps the keys in memory
Current E2E tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2336)
=> [smoke-test] Make aptos-cli tests not use the config

storage/aptosdb/src/state_merkle_db.rs, storage/aptosdb/src/state_store/buffered_state.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_merkle_batch_committer.rs, storage/aptosdb/src/state_store/state_snapshot_committer.rs
Pipelined batch commit.
current ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2324)
=> [storage] pipeline state merkle batch commit

aptos-move/framework/aptos-stdlib/sources/simple_map.move
make the generic simple map dropable
cargo test -p framework
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2355)
=> Make SimpleMap dropable

Cargo.lock, storage/jellyfish-merkle/Cargo.toml, storage/jellyfish-merkle/src/restore/mod.rs, storage/jellyfish-merkle/src/restore/restore_test.rs
It'll make the life easier when dealing with resumption. 
UT updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2332)
=> [storage] JellyfishMerkleRestore accepts overlapping chunks

api/goldens/v0/aptos_api__tests__accounts_test__test_account_modules.json, api/goldens/v0/aptos_api__tests__accounts_test__test_account_modules_structs.json, api/goldens/v0/aptos_api__tests__accounts_test__test_account_resources_response.json, api/goldens/v0/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json, api/goldens/v0/aptos_api__tests__accounts_test__test_get_module_aptos_config.json, api/goldens/v0/aptos_api__tests__accounts_test__test_get_module_with_script_functions.json, api/goldens/v0/aptos_api__tests__transactions_test__test_get_transactions_output_genesis_transaction.json, api/goldens/v0/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_script_function_payload.json, api/goldens/v0/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json, api/goldens/v1/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json, api/goldens/v1/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_script_function_payload.json, api/goldens/v1/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json, api/src/context.rs, aptos-move/framework/aptos-framework/sources/block.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2362)
=> [move] Fix epoch_internal typo

developer-docs-site/docs/tutorials/first-coin.md, developer-docs-site/docs/tutorials/first-move-module.md, developer-docs-site/docs/tutorials/first-transaction.md
See title.
No test needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2344)
=> Fix rust example path

ecosystem/platform/server/app/models/it1_profile.rb, ecosystem/platform/server/app/models/it2_profile.rb, ecosystem/platform/server/db/migrate/20220729235238_add_account_address_to_itprofiles.rb, ecosystem/platform/server/db/migrate/20220730180322_populate_account_address_on_itprofiles.rb, ecosystem/platform/server/db/schema.rb
This makes life significantly easier in our data warehouse, as we can connect user accounts to on-chain data much more easily
tested (and migrated) manually 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2367)
=> [CP] Add account address to IT profiles

developer-docs-site/static/examples/typescript/first_nft.ts
the function name of offer/claim nft should be "0x1::token_transfers::offer_script" and "0x1::token_transfers::claim_script"
change dict to developer-docs-site/static/examples/typescript
run `npm install && ts-node first_nft.ts`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2382)
=> fix your-first-nft tutorial

storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_snapshot_committer.rs
as title we don't need fancy buffer
ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2357)
=> [storage] change async commit channels to rendezvous channel

aptos-move/aptos-sdk-builder/src/golang.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2388)
=> [aptos-sdk] fix go lang gen

state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2347)
=> [ssv2][easy] remove unnecessary select

crates/aptos-rosetta/aptos.ros
A couple fields weren't updated accordingly
TBD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2373)
=> [aptos-rosetta] Update Aptoscoin for rosetta

execution/executor/src/block_executor.rs
Just in case there are multiple place calling the block executor at the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2353)
=> [Execution] Do not reuse proof fetcher across multiple block executions.

developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md
These CLI instructions are pointing people in the wrong direction, since the tag is old.  Updating to use branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2398)
=> [docs] Update docs for CLI installation

crates/aptos/src/governance/mod.rs, crates/aptos/src/lib.rs
This provides a simple submit proposal and vote flow.  It does need some work on printing out the proposal, but it does generate the hash of the metadata and the metadata parsing on its own.
We can create a separate PR and command for showing the proposal next.
I can sort of run the governance, but I need to do the extra steps to allocate stake etc.
```
cargo build -p aptos && aptos governance propose --pool-address local --metadata-url https://gist.githubusercontent.com/gregnazario/dae573cbb50ef25f8ab138a0c3daedae/raw/0ea04e4ea498b83bfd02a78a5e9091ff1696ee75/gistfile1.txt --execution-hash 0000000000000000000000000000000000000000000000000000000000000000 --profile local
Finished dev [unoptimized + debuginfo] target(s) in 0.35s
Proposal:
Title:TestProposal
Description:This is a test …
```
=> [aptos-cli] Add governance commands

Cargo.lock, storage/storage-interface/Cargo.toml, storage/storage-interface/src/async_proof_fetcher.rs, storage/storage-interface/src/lib.rs, storage/storage-interface/src/metrics.rs
to understand how long we wait for async proof fetching results to come back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2411)
=> [storage] add timers for AsyncProofFetcher

aptos-move/framework/aptos-framework/sources/block.move, aptos-move/framework/aptos-stdlib/sources/event.move, aptos-move/framework/aptos-token/sources/token.move
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2350)
=> [block] ensure height equal to event counter

state-sync/aptos-data-client/src/aptosnet/mod.rs, state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs, state-sync/storage-service/server/src/lib.rs
This PR reduces some debug logs to trace logs in state sync (to help reduce log noise 😄).
Manually ran a fullnode and watched the logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2415)
=> [Logs] Reduce debug to trace logs.

ecosystem/indexer/src/models/transactions.rs
sometimes the user provided timestamp is past the heat death of the universe
This truncates the indexer representation to be max 10 years in future
Added new test, and tested manually with 
`cargo run -- --pg-uri "postgresql://localhost/indexer_test" --node-url "https://fullnode.devnet.aptoslabs.com" --emit-every 25 --batch-size 100 --start-from-version 2352530` to replicate the fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2419)
=> Truncate expiration timestamp to 10 years in future if it is longer

Cargo.lock, api/doc/v1/spec.json, api/doc/v1/spec.yaml, api/goldens/v1/aptos_api__tests__transactions_test__test_get_transactions_param_limit_exceeds_limit.json, api/goldens/v1/aptos_api__tests__transactions_test__test_get_transactions_with_start_version_is_too_large.json, api/goldens/v1/aptos_api__tests__transactions_test__test_get_transactions_with_zero_limit.json, api/src/poem_backend/response.rs, api/src/poem_backend/transactions.rs, api/types/src/convert.rs
Error improvements.
```
cd api
cargo test
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2420)
=> [API] Use snake case errors, improve error messages

consensus/src/round_manager_test.rs, consensus/src/test_utils/mock_payload_manager.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2335)
=> [consensus] add unit test for the echo timeout

aptos-move/move-examples/hello_blockchain/sources/HelloBlockchain.move, aptos-move/move-examples/hello_blockchain/sources/HelloBlockchainTest.move, aptos-move/move-examples/moon_coin/sources/MoonCoinType.move, developer-docs-site/docs/tutorials/first-coin.md, developer-docs-site/docs/tutorials/first-move-module.md, developer-docs-site/docs/tutorials/first-transaction.md, developer-docs-site/docs/tutorials/your-first-nft.md, developer-docs-site/static/examples/python/first_coin.py, developer-docs-site/static/examples/python/first_nft.py, developer-docs-site/static/examples/python/first_transaction.py, developer-docs-site/static/examples/python/hello_blockchain.py, developer-docs-site/static/examples/rust/first_coin/src/lib.rs, developer-docs-site/static/examples/rust/first_coin/src/main.rs, developer-docs-site/static/examples/rust/first_transaction/src/main.rs, developer-docs-site/static/examples/rust/hello_blockchain/src/lib.rs, developer-docs-site/static/examples/rust/hello_blockchain/src/main.rs, developer-docs-site/static/examples/typescript/first_coin.ts, developer-docs-site/static/examples/typescript/first_nft.ts, developer-docs-site/static/examples/typescript/first_transaction.ts, developer-docs-site/static/examples/typescript/hello_blockchain.ts, developer-docs-site/static/examples/typescript/package.json
Improve the code examples by using TS SDK. We don't want developers to copy and paste the code to submit txns with JSON payloads.
Tested every code example manually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2365)
=> [docs] Improve the TS code examples

mempool/src/lib.rs, mempool/src/shared_mempool/tasks.rs, mempool/src/thread_pool.rs, vm-validator/src/unit_tests/vm_validator_test.rs, vm-validator/src/vm_validator.rs
see individual commits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2428)
=> [mempool] 1. dedicated IO_POOL 2. get seq_num with shared state view

ecosystem/python/sdk/aptos_sdk/client.py
Fixes a crash caused by an undefined variable
Manually tested
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2433)
=> [python-sdk] Fixes a crash caused by undefined variable

Cargo.lock, api/Cargo.toml, api/types/Cargo.toml, config/Cargo.toml, crates/aptos-openapi/Cargo.toml, ecosystem/node-checker/Cargo.toml
I was using Poem from the repo because some changes I needed were in main, but not in crates.io. A new version just made it out, so we can cut over. I also clean up some feature stuff.
Just CI for this one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2448)
=> Use specific Poem version

docker/rust-all.Dockerfile
Needed to debug issues in prod.
Forge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2446)
=> [Docker] Install GDB to all validator nodes

api/goldens/v0/aptos_api__tests__transactions_test__test_get_transaction_by_hash.json, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/table.exp, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/table.move, aptos-move/framework/aptos-token/sources/property_map.move, aptos-move/framework/aptos-token/sources/token.move, aptos-move/framework/aptos-token/sources/token_coin_swap.move, aptos-move/framework/aptos-token/sources/token_transfers.move, developer-docs-site/static/examples/python/first_nft.py, developer-docs-site/static/examples/typescript/first_nft.ts, ecosystem/python/sdk/aptos_sdk/client.py, ecosystem/typescript/sdk/src/token_client.ts, testsuite/smoke-test/src/nft_transaction.rs
1. fix typo in royalty
2. remove redundant method
3.  put propertyMap in token struct
4. update the position of property_version in arg list. cannot update in the SDK since the arg with default values should be at the end of list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2437)
=> [Token] Cleanup token contracts

Cargo.lock, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/submission_worker.rs
As above
Forge run
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2457)
=> [Txn-emitter] Fix submitted txn stats in emitter

types/src/proof/unit_tests/proof_test.rs, types/src/transaction/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2470)
=> [storage] txn_list_with_proof.verify() verifies write set

ecosystem/typescript/sdk/src/token_client.ts
A one line change to get rid of the no unused vars linting comment
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2477)
=> Token client nit

aptos-move/move-examples/tests/move_prover_tests.rs
- Ignore the example Prover test until we properly make it optional
cargo test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2494)
=> [Prover] Ignore the example Prover test

developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md, docker/compose/aptos-node/docker-compose-fullnode.yaml, docker/compose/aptos-node/docker-compose.yaml, docker/compose/validator-testnet/docker-compose.yaml, docker/rust-all.Dockerfile, terraform/helm/aptos-node/templates/fullnode.yaml, terraform/helm/aptos-node/templates/validator.yaml, terraform/helm/fullnode/templates/fullnode.yaml
reapplying aptos-labs/aptos-core#2394
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2498)
=> infra: consistency - put all built binaries into thes same path in docker image and make them available in $PATH

developer-docs-site/docs/tutorials/your-first-nft.md
This doc still needs some syntax and formatting fixes, including dark mode image. But for now I am fixing the minimum required to pass the docs build. I will come back to this later. Not a priority at the moment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2500)
=> [Docs] Fixing build errors.

storage/scratchpad/src/sparse_merkle/mod.rs, storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2495)
=> [scratchpad] test_multithread_get_oldest_ancestor

developer-docs-site/static/examples/typescript/first_nft.ts
during rebase, changes were merged incorrectly
start local test
- `cargo run -p aptos -- node run-local-testnet  --with-faucet --force-restart`
- replace the urls in example with local node and faucet URL since the contract updated as well
- `yarn first_nft `
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2506)
=> [Token] fix nft example

Cargo.lock, crates/aptos-rosetta/Cargo.toml, crates/aptos-rosetta/build.rs, crates/aptos-rosetta/src/network.rs, crates/aptos-telemetry/Cargo.toml, crates/aptos-telemetry/build.rs, crates/aptos-telemetry/src/build_information.rs, crates/aptos/Cargo.toml, crates/aptos/build.rs, crates/aptos/src/lib.rs
Removes shadow-rs, still uses env vars if they exist
Local builds no longer rebuild
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2511)
=> [telemetry] Remove Shadow-rs

Cargo.lock, consensus/src/network_interface.rs, crates/aptos-compression/src/lib.rs, crates/aptos-compression/src/metrics.rs, crates/aptos-compression/src/tests.rs, network/Cargo.toml, network/src/protocols/network/mod.rs, network/src/protocols/wire/handshake/v1/mod.rs, state-sync/storage-service/types/src/responses.rs, testsuite/generate-format/tests/staged/network.yaml
cherrypick https://github.com/aptos-labs/aptos-core/pull/2459
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2510)
=> [cherry-pick][Consensus] Add compression to consensus messages.

terraform/helm/testnet-addons/templates/loadtest.yaml, terraform/helm/testnet-addons/values.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2521)
=> [cherry-pick][helm] fix load tester

terraform/helm/testnet-addons/templates/loadtest.yaml, terraform/helm/testnet-addons/values.yaml
Transaction emitter parameters changed, update commands to fix the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2520)
=> [helm] fix load tester

.github/workflows/build-images.yaml, .github/workflows/sdk-release.yaml, ecosystem/typescript/sdk/check.sh, ecosystem/typescript/sdk/examples/README.md, ecosystem/typescript/sdk/examples/javascript/package.json, ecosystem/typescript/sdk/examples/typescript/package.json, ecosystem/typescript/sdk/examples/typescript/tsconfig.json, ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/aptos_client.ts, ecosystem/typescript/sdk/src/faucet_client.test.ts, ecosystem/typescript/sdk/src/generated/models/RoleType.ts, ecosystem/typescript/sdk/src/token_client.test.ts, ecosystem/typescript/sdk/src/token_client.ts
Previously I landed the CI early, to get the file in so it could be tested against. This was unfortunately a misunderstanding of how our CI worked, so it wasn't necessary. Nonetheless, the CI was incomplete, so I'm fixing it up now.
This PR makes a few changes to the job layout, spec change verification, env files, etc.
I also had to fix tests that had broken because of changes that landed while these tests were out of action. Mostly I just had to bump all the gas limits / account funding.
Change `pull_request_target` to `pull_request` temporarily and see if the CI passes in this PR. If that works, I'll change it back and then force land.
- - - …
=> Finalize TS SDK CI

.github/workflows/sdk-release.yaml
Fixes some container stuff.
Run with the trigger changed to pull_request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2527)
=> Fix docker issue in SDK CI

terraform/helm/genesis/values.yaml
Update genesis value to make recurring lockup configurable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2530)
=> Update genesis value to make recurring lockup configurable

terraform/helm/genesis/values.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2536)
=> [cherry-pick] Update values.yaml (#2530)

Cargo.lock, crates/aptos/Cargo.toml
Update, and I'll port it back on the devnet branch so it looks all good
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2550)
=> [aptos-cli] Bump version to 0.2.3

ecosystem/platform/server/app/components/header_component.html.erb
- Adjust font size on medium widths to fix breakpoint shifting.
- Increase gap / spacing for large screen widths
See comparison:
https://user-images.githubusercontent.com/98909677/182765110-585e0fa6-3e9f-4325-97e6-6641af49d184.mov
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2518)
=> [community] Fix Nav breakpoint shift & adjust desktop spacing

storage/aptosdb/src/pruner/ledger_pruner_manager.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs, storage/aptosdb/src/pruner/state_pruner_manager.rs, storage/aptosdb/src/pruner/state_store/mod.rs
- Fix flaky tests introduced in https://github.com/aptos-labs/aptos-core/pull/2466#issuecomment-1205987723.
- The flaky reason is here https://github.com/aptos-labs/aptos-core/pull/2466#discussion_r938328948.
- A proper fix is to make test waiting for DB write is done. Added a todo.
Run the flaky tests 100 times locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2560)
=> [storage][pruner] Fix flaky tests

ecosystem/platform/server/app/components/header_component.html.erb, ecosystem/platform/server/tailwind.config.js
- don't apply `[open]` style on large screens
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2568)
=> Fix issues with nav when moving from small to large screen.

developer-docs-site/docs/concepts/basics-accounts.md
This [Linear issue](https://linear.app/aptoslabs/issue/DOC-16/revamp-accounts-documentation-in-aptosdev) calls for enhancing the Accounts doc with a few specific details. This PR addresses them. 
cc: @jjleng
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/1961)
=> Revising the Concepts > Accounts doc.

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
See title
No test needed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2561)
=> Fix broken links in docs

crates/transaction-emitter-lib/src/emitter/submission_worker.rs
As above
Forge run
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2557)
=> [txn-emitter] Sample noisy error logs

Cargo.toml
Optimize release build config
Ran forge with different release profile configs: 
"text": "all up : 8567 TPS, 3451 ms latency, 5000 ms p99 latency,no expired txns
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2575)
=> [Build Profile] Optimising the relase build profile

testsuite/run_forge.sh
Forge jobs occupy a namespace (roughly a git ref, such as a branch). When a bunch of PRs land in `main` at the same time, only the last one should be tested by forge to prevent resource contention.
Fix a bug in the Forge job preemption logic that made our jobs fail to give the right exit code and comment when a job was preempted. 
Also improve some of the output to make it more readable 
Run a bunch of jobs in parallel in the same namespace. This simulates a bunch of PRs landing in `main` at the same time. See that they preempt each other
```
$ FORGE_NAMESPACE=forge-rustielin ./testsuite/run_forge.sh
<job runs>
...
<preempt it by running the same command in a different terminal>
<the test runner pod is deleted at this time>
...
Forge pod status: Error from server (NotFound): pods …
```
=> [forge] fix exit code on job preemption and print more output

aptos-move/framework/aptos-framework/sources/configs/consensus_config.move, aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_block_transactions_work.json, sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_table_item_parsing_works.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2617)
=> [Aptos Framework][Staking] Add missing getters to stake module

aptos-move/framework/aptos-stdlib/sources/big_vector.move, sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_block_transactions_work.json, sf-stream/goldens/sf_v1/aptos_sf_stream__tests__proto_converter_tests__test_table_item_parsing_works.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2623)
=> [aptos-move-framework] fix empty big_vector contains

developer-docs-site/docs/tutorials/first-transaction.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2577)
=> 5000 - 3927 - 1000 = 73

ecosystem/python/sdk/README.md, ecosystem/python/sdk/aptos_sdk/client.py, ecosystem/python/sdk/examples/coin.py, ecosystem/python/sdk/examples/common.py, ecosystem/python/sdk/examples/token.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2624)
=> [python-sdk] improve utility of sdk and examples

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/examples/javascript/index.js, ecosystem/typescript/sdk/examples/typescript/bcs_transaction.ts, ecosystem/typescript/sdk/examples/typescript/index.ts, ecosystem/typescript/sdk/examples/typescript/multisig_transaction.ts, ecosystem/typescript/sdk/package.json, ecosystem/typescript/sdk/src/aptos_client.ts, ecosystem/typescript/sdk/src/faucet_client.test.ts
The changes to downscale gas landed, let's adjust accordingly in the TS SDK.
```
yarn test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2635)
=> [SDK][TS] Downscale max gas, tests accordingly

api/doc/v1/spec.json, api/doc/v1/spec.yaml, ecosystem/typescript/sdk/src/generated/index.ts, ecosystem/typescript/sdk/src/generated/models/VersionedEvent.ts, ecosystem/typescript/sdk/src/generated/schemas/$VersionedEvent.ts, ecosystem/typescript/sdk/src/generated/services/EventsService.ts
Regenerating the API spec and TS client following https://github.com/aptos-labs/aptos-core/pull/2618.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2639)
=> Regenerate the API spec and TS client with events changes

aptos-move/framework/aptos-token/sources/token_coin_swap.move
Not use struct TokenId in entry function. 
Abigen now will generate abi for entry function with struct txn argument (copy ability and no key ability) and this will break our SDK builder
cargo test -p framework
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2645)
=> [Token] Not use struct TokenId in entry function

sdk/transaction-builder/src/error_explain.rs
before this test would have failed, now it passes, yay...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2646)
=> [sdk] bring back error codes in particular for the web interface

config/src/config/storage_config.rs, execution/executor-benchmark/src/main.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/tests.rs, storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/event_store/test.rs, storage/aptosdb/src/pruner/ledger_pruner_manager.rs, storage/aptosdb/src/pruner/pruner_manager.rs, storage/aptosdb/src/pruner/state_pruner_manager.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/pruner/transaction_store/test.rs, storage/storage-interface/src/lib.rs, terraform/helm/aptos-node/files/configs/fullnode.yaml, terraform/helm/aptos-node/files/configs/validator.yaml, terraform/helm/aptos-node/values.yaml
- Add configs to explicitly enable/disable pruners instead of depending on the pruner windows.
- Make pruner window non option.
Existing Tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2598)
=> [storage][pruner] Add explicit config to enable/disable pruners

developer-docs-site/docs/guides/index.md, developer-docs-site/docs/guides/move-guides/guide-move-transactional-testing.md, developer-docs-site/docs/guides/move-guides/index.md, developer-docs-site/docusaurus.config.js, developer-docs-site/sidebars.js
New doc. Reviewed and edited internally first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2604)
=> [Docs] New Move transactional testing guide.

api/src/context.rs, aptos-move/aptos-validator-interface/src/lib.rs, aptos-move/aptos-validator-interface/src/storage_interface.rs, aptos-move/transaction-replay/src/lib.rs, aptos-move/transaction-replay/src/unit_tests/mod.rs, consensus/src/liveness/leader_reputation.rs, consensus/src/liveness/leader_reputation_test.rs, execution/executor-test-helpers/src/integration_test_impl.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, state-sync/storage-service/server/src/tests.rs, storage/aptosdb/src/lib.rs, storage/storage-interface/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2652)
=> [storage] AptosDB::get_events() accepts ledger_version

api/src/context.rs, storage/aptosdb/src/event_store/mod.rs, storage/aptosdb/src/event_store/test.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/transaction_store/mod.rs, storage/aptosdb/src/transaction_store/test.rs, storage/storage-interface/src/lib.rs, types/src/account_config/events/new_block.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2505)
=> [storage] utilize the NewBlockEvent to find out block boundaries

testsuite/forge-cli/src/main.rs, testsuite/forge/src/backend/k8s/chaos.rs, testsuite/forge/src/backend/k8s/chaos/network_loss.yaml, testsuite/forge/src/interface/chaos.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/src/network_loss_test.rs
Test Plan:
```
cargo run -p forge-cli -- --suite chaos test k8s-swarm --namespace forge-banana --port-forward
```
Run forge command locally
And #e2e signal on PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2661)
=> [forge] Add packet loss test and make a chaos test suite

consensus/src/persistent_liveness_storage.rs, consensus/src/state_computer.rs, execution/executor-types/src/lib.rs, execution/executor/src/block_executor.rs, execution/executor/src/components/block_tree/mod.rs, execution/executor/src/fuzzing.rs, execution/executor/src/tests/mod.rs, execution/executor/tests/db_bootstrapper_test.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, state-sync/storage-service/server/src/tests.rs, storage/aptosdb/src/backup/backup_handler.rs, storage/aptosdb/src/ledger_store/ledger_info_test.rs, storage/aptosdb/src/ledger_store/mod.rs, storage/aptosdb/src/lib.rs, storage/backup/backup-cli/src/coordinators/backup.rs, storage/storage-interface/src/lib.rs, types/src/proof/accumulator/mod.rs, types/src/proof/definition.rs
To fix SEV285
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2615)
=> cherry-pick: [storage] remove get_startup_info() (#2606)

developer-docs-site/docs/nodes/ait/node-requirements.md
Update hardware requirement for AIT3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2662)
=> update hardware requirement

api/goldens/v0/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json, api/goldens/v1/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json, aptos-move/framework/aptos-framework/sources/aptos_coin.move, crates/aptos-rosetta/aptos.ros, crates/aptos-rosetta/src/common.rs
APTOS -> APT
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2668)
=> [aptos-framework] Change aptos coin currency code to APT

Cargo.lock, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/types/objects.rs, crates/aptos-rosetta/src/types/requests.rs, crates/aptos/src/account/transfer.rs, crates/aptos/src/test/mod.rs, testsuite/smoke-test/src/aptos_cli.rs, testsuite/smoke-test/src/rosetta.rs
Ensuring this cherry pick works still
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2634)
=> [cherry-pick] Rosetta changes into rosetta-stable

aptos-move/aptos-gas/src/gas_meter.rs, aptos-move/aptos-gas/src/instr.rs, aptos-move/aptos-gas/src/lib.rs, aptos-move/aptos-gas/src/natives.rs, aptos-move/aptos-gas/src/transaction.rs
This adds some missing comments to aptos-gas. No code is changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2696)
=> [gas] add comments in crate aptos-gas

aptos-move/framework/aptos-framework/sources/stake.move
1. Removing the max stake cap in voting power and rewards distribution. Rationale: We already prevent people from adding stake if the total exceeds the maximum, rewards alone would not take someone that far past the max stake (let's say 10% per year. So it should not affect the network's security/decentralization if we don't "cap" the voting power and reward distribution by the max stake amount.
2. Mint rewards to both active and pending_inactive. This would allow users to receive their rewards earlier instead of auto-locking it in the active stake portion. This also makes the UX of staking services better as they can allow users to unlock funds and still receive the rewards on that unlocked funds until the end of the lockup cycle. For example, if a user requests to withdraw 50 coins half …
=> [Aptos Framework][Staking] Remove max stake flooring and update rewards distribution to mint to both active/pending_inactive

developer-docs-site/tsconfig.json
Ran `yarn typecheck`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2718)
=> [docs] Fix yarn typecheck for docs.

.github/actions/docker-buildx-setup/action.yaml
This makes our CI more predictable.
See that GitHub actions pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2487)
=> Pin buildx to specific version

ecosystem/python/sdk/.gitignore, ecosystem/python/sdk/Makefile, ecosystem/python/sdk/README.md, ecosystem/python/sdk/aptos_sdk/client.py, ecosystem/python/sdk/aptos_sdk/transactions.py, ecosystem/python/sdk/examples/.gitignore, ecosystem/python/sdk/examples/common.py, ecosystem/python/sdk/examples/token.py, ecosystem/python/sdk/poetry.lock, ecosystem/python/sdk/pyproject.toml, ecosystem/python/sdk/setup.py
This PR updates our Python SDK to work with the v1 API.
While I'm here I add package management and command runner stuff and update the README.
CI next to come.
```
make fmt
make examples
make test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2600)
=> Update Python SDK to use API v1

developer-docs-site/docusaurus.config.js, developer-docs-site/package.json, developer-docs-site/yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2730)
=> [Docs] Removing unusued plugins.

consensus/src/persistent_liveness_storage.rs, consensus/src/state_computer.rs, execution/executor-types/src/lib.rs, execution/executor/src/block_executor.rs, execution/executor/src/components/block_tree/mod.rs, execution/executor/src/fuzzing.rs, execution/executor/src/tests/mod.rs, execution/executor/tests/db_bootstrapper_test.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, state-sync/storage-service/server/src/tests.rs, storage/aptosdb/src/backup/backup_handler.rs, storage/aptosdb/src/ledger_store/ledger_info_test.rs, storage/aptosdb/src/ledger_store/mod.rs, storage/aptosdb/src/lib.rs, storage/backup/backup-cli/src/coordinators/backup.rs, storage/storage-interface/src/lib.rs, types/src/proof/accumulator/mod.rs, types/src/proof/definition.rs
Reverts aptos-labs/aptos-core#2615
this breaks devnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2735)
=> Revert "cherry-pick: [storage] remove get_startup_info() (#2606)"

storage/aptosdb/src/lib.rs, storage/aptosdb/src/metrics.rs, storage/jellyfish-merkle/src/lib.rs, storage/jellyfish-merkle/src/metrics.rs
The old way stopped working since we changed commit to be async. Move it to JMT side after we compute the new root node should fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2726)
=> [Storage] Fix leaf count metric.

developer-docs-site/static/examples/python/first_coin.py, developer-docs-site/static/examples/rust/first_coin/src/lib.rs, developer-docs-site/static/examples/typescript/first_coin.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2690)
=> [move examples]: modify coin::register to coins::register

testsuite/run_forge.sh
Some forge runs are failing because `run_forge.sh` finishes tailing the logs before kube can change the pod status from Running to Complete
wait after run_forge.sh finishes tailing the logs. sleep and `kubectl get pods` for the condition status
try running the `kubectl get pods -o....` command on some running and completed pods
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2759)
=> [forge] wait after logs

ecosystem/typescript/sdk/src/aptos_client.test.ts
Bring multiagent tests back. Updated the tests to be compatible with the latest Token contract.
Make sure the test pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2765)
=> fix: revive multiagent tests for TS SDK

storage/aptosdb/src/pruner/transaction_store/test.rs, storage/aptosdb/src/pruner/transaction_store/transaction_store_pruner.rs, storage/aptosdb/src/transaction_store/mod.rs
To address https://github.com/aptos-labs/aptos-core/issues/1288
Added a UT.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2734)
=> [storage][pruner] Incrementally prune transaction accumulator

Cargo.lock, crates/aptos-protos/Cargo.toml, sf-stream/Cargo.toml
Removes an unneeded dep since we're slowly rolling our own WKT  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2777)
=> [SF] remove protoc dep library from build

storage/scratchpad/benches/sparse_merkle.rs, storage/scratchpad/src/sparse_merkle/mod.rs, storage/scratchpad/src/sparse_merkle/test_utils/proptest_helpers.rs
not longer used
existing UT
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2775)
=> [scratchpad] remove SMT::serial_update()

config/src/config/storage_config.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2773)
=> [storage] trivial: remove unused config

storage/storage-interface/src/lib.rs
no longer used
cargo xclippy
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2804)
=> [storage] trivial: remove unused DbWriter apis

developer-docs-site/docs/nodes/ait/node-requirements.md, developer-docs-site/docs/nodes/full-node/network-identity-fullnode.md, developer-docs-site/docs/whats-new-in-docs.md
For the GitHub issue: https://github.com/aptos-labs/aptos-core/issues/2644
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2766)
=> [Docs] Clarifying port settings for nodes.

storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/pruner/ledger_pruner_manager.rs
To fix ledger pruner config
Added a test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2814)
=> [storage][pruner] Fix the config to enable ledger pruner

storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/pruner/ledger_pruner_manager.rs
=> [cherry-pick][storage][pruner] Fix the config to enable ledger pruner (#2814)

docker/build-rust-all.sh, docker/docker-bake-rust-all.hcl, docker/rust-all.Dockerfile
Include telemetry service as part of Dockerfile builds and create a separate image for it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2725)
=> [aptos-telemetry] Include telemetry service in Dockerfile

storage/aptosdb/src/aptosdb_test.rs
Follow up of https://github.com/aptos-labs/aptos-core/pull/2814#discussion_r943770695
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2820)
=> [storage][pruner] Add more tests for storage config

ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/aptos_client.ts
Eliminate the need for users to prepare all the parameters for creating a raw transaciton
yarn test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2831)
=> feat: expose method to create a raw txn out of a txn payload

developer-docs-site/docs/guides/guide-for-system-integrators.md, developer-docs-site/docs/guides/sign-a-transaction.md, developer-docs-site/docs/index.md, developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md, developer-docs-site/docs/tutorials/first-coin.md, developer-docs-site/docs/tutorials/first-move-module.md, developer-docs-site/docs/tutorials/first-transaction.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2834)
=> [Docs] Missing links and typos.

api/goldens/v0/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json, api/goldens/v1/aptos_api__tests__accounts_test__test_get_account_resources_returns_empty_array_for_account_has_no_resources.json, aptos-move/aptos-gas/src/transaction.rs, aptos-move/e2e-testsuite/src/tests/verify_txn.rs, config/src/config/api_config.rs, vm-validator/src/unit_tests/vm_validator_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2841)
=> [cherry-pick][gas] bump max_transaction_size_in_bytes to 10 MB (#2829)

crates/aptos/src/move_tool/mod.rs
=> [cli] make legacy publishing default

Cargo.lock, crates/aptos/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2850)
=> bump cli version

aptos-move/aptos-vm/src/adapter_common.rs, types/src/transaction/mod.rs
to get the txn size, we go through serde every time which is .. crazy, this commit fixes it by adding a once cell cache assuming the txn is immutable.
also get rid of the preload cache that does nothing after fine grained storage, it used to load the account blob but now it loads nothing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2852)
=> [perf] cache txn size and get rid of preload_cache

ecosystem/platform/server/app/controllers/it3_profiles_controller.rb, ecosystem/platform/server/app/controllers/it3s_controller.rb, ecosystem/platform/server/app/javascript/controllers/application.ts, ecosystem/platform/server/app/javascript/controllers/connect_wallet_controller.ts, ecosystem/platform/server/app/javascript/controllers/index.js, ecosystem/platform/server/app/views/it3_profiles/_form.html.erb, ecosystem/platform/server/app/views/it3s/show.html.erb, ecosystem/platform/server/config/routes.rb
https://user-images.githubusercontent.com/310773/183739457-b126630b-5021-4b93-99ea-def20071d5d5.mp4
Tested manually
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2714)
=> [community] Integrate with wallet to determine owner key.

terraform/helm/genesis/files/genesis.sh, terraform/helm/genesis/templates/genesis.yaml, terraform/helm/genesis/values.yaml
Update default value to be closer to reality 
- update epoch length to 2 hours
- update min stake
apply to sherrynet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2861)
=> [helm] update default value for genesis

developer-docs-site/docs/tutorials/first-coin.md
Just update the docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2824)
=> Update docs to use coins::register

aptos-move/framework/aptos-stdlib/sources/table.move
added an upsert function to the aptos-stdlib/table.move with test code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2858)
=> add table::upsert

testsuite/testcases/src/performance_test.rs
As above.
Forge run
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2875)
=> [Forge] Fix validator restart checkin in performance test

consensus/src/network_interface.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2890)
=> [consensus] fix the network queue order

CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2907)
=> [CODEOWNERS] Add codeowners for CLI, SDK, Rosetta

Cargo.lock, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/move-deps/Cargo.toml, aptos-move/transaction-replay/Cargo.toml, aptos-move/transaction-replay/src/main.rs, aptos-move/transaction-replay/src/unit_tests/bisection_tests.rs
This bumps the Move version to the latest, giving us access to the new ChangeSet and the loop depth check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2909)
=> [move] bump move version

aptos-move/parallel-executor/src/executor.rs, aptos-move/parallel-executor/src/txn_last_input_output.rs
don't preemptively return threads upon detecting possible module publishing race
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2876)
=> [Parallel Execution] Let execution finish even if it needs to fallback to sequential

aptos-move/parallel-executor/src/txn_last_input_output.rs
Never write false, as that can overwrite a true value due to a concurrency race.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2916)
=> [Parallel Execution] Fix module detection (again)

.github/workflows/coverage.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2915)
=> cicd: limit test threads in coverage run to avoid OOM

Cargo.lock, api/Cargo.toml, api/src/poem_backend/log.rs, api/types/Cargo.toml, config/Cargo.toml, crates/aptos-openapi/Cargo.toml, ecosystem/node-checker/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2938)
=> [API] Log per-endpoint metrics based on operation_id (#2781)

crates/aptos-telemetry/src/build_information.rs
Fix naming for variables
Just a naming fix, no functionality affected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2864)
=> [telemetry] Fix naming

CONTRIBUTING.md
x lint doesn't exist anymore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2943)
=> [CONTRIBUTING] Updated contribution docs

terraform/fullnode/gcp/backup.tf, terraform/fullnode/gcp/cluster.tf, terraform/fullnode/gcp/kubernetes.tf, terraform/fullnode/gcp/variables.tf, terraform/helm/fullnode/templates/backup.yaml
Support backup on gcp fullnodes
Deployed a fullnode cluster on GCP, with backup enabled
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2897)
=> [tf][gcp] support backup on gcp fullnodes

storage/storage-interface/Cargo.toml, storage/storage-interface/src/lib.rs
It does not compile.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2961)
=> [fix] fix async_proof_reader compile

developer-docs-site/docs/sdks/transactions-with-ts-sdk.md
Add a short tutorial about building raw transactions with the ABI transaction builder
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2895)
=> doc: add ABI usage tutorial

developer-docs-site/docs/guides/building-wallet-extension.md
With the new update we only support BCS transactions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2963)
=> [docs] Updating the wallet guide for bcs change

aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
This package keeps regenerating, but it's not committed.  This commits it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2975)
=> [framework] Update SDK builder from generated inputs

consensus/src/liveness/leader_reputation.rs, consensus/src/liveness/leader_reputation_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2994)
=> [cherry-pick][consensus] Fix cross-epoch leader election

developer-docs-site/docs/guides/index.md, developer-docs-site/docs/guides/system-integrators-guide.md, developer-docs-site/sidebars.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2997)
=> [docs] update for mvp of system-integrators-guide

crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/misc.rs, crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
Adding set operator operation to rosetta
TBD, need to test changing operator, which likely needs implementing more operations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2889)
=> [aptos-rosetta] Add set operator operation to rosetta

consensus/src/experimental/buffer_item.rs, consensus/src/experimental/buffer_manager.rs
We fixed a race condition in https://github.com/aptos-labs/aptos-core/pull/2082/commits/b3083b202fcdbf0133cc4a1116bfe429a78bf451
which didn't take into consideration of the timestamps for suffix batches.
Previously the timestamp is only fixed for the blocks in the same batch as reconfig block because we reject any suffix batches.
This commit adds an epoch end timestamp and ensures it's applied for all suffix batches.
We should add more stress tests on reconfigurations, or spend some time to simulate the reconfig in fake executions so that we can write an unit test for such a scenario.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2995)
=> [consensus] propagate reconfig timestamp to all reconfig suffix blocks

ecosystem/platform/server/app/assets/stylesheets/application.tailwind.css
Updates colors for autofilled inputs.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2970)
=> [community] Update autocomplete input styles to new colors.

consensus/src/liveness/leader_reputation.rs, consensus/src/liveness/leader_reputation_test.rs
When we started fetching history cross-epochs, we removed filtering on epoch from the db. But when new epoch happens, comparison between rounds is not sufficient.
Added unit test to catch it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2990)
=> [consensus] Fix cross-epoch leader election

aptos-move/framework/aptos-framework/sources/coin.move
- Removed the unnecessary abilities in the coin module
- Simplified the code a little bit with a helper function
cargo test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2979)
=> [Coin] Removed the key-ability for the capabilities of coin

terraform/helm/genesis/values.yaml
- fix some comments
- fix some value miss match
- reduce `voting_power_increase_limit`, 50% new stake join at same time will take down the network since new nodes will take time to sync and be able to vote. even 20% is probably too much but let's start with 20. 
- rearrange configs to group by amount config and duration config etc. 
deploy to sherrynet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2946)
=> [helm][genesis] update genesis default value

developer-docs-site/docs/tutorials/first-transaction-sdk.md, developer-docs-site/sidebars.js
The existing tutorial only teaches users how to build their own sdk.
This new tutorial teaches users a lot more and in a way that we can grow
from into other tutorials.
Currently only Python is supported, since well I have a limited
skillset.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3002)
=> [docs] first transaction using the sdk

sdk/publishing.md
modify repository address to aptos-core of publishing document.
in case to ambiguous with diem
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2950)
=> [sdk] modify repository address to aptos-core of publishing document

aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/transaction_metadata.rs, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, types/src/transaction/authenticator.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2978)
=> [Aptos VM] changed authentication_key_preimage to authentication_key in transaction_metadata

testsuite/forge/src/interface/swarm.rs
state_sync test that sporadically fail
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2998)
=> [swarm][test] Better error for waiting to catchup

config/src/config/storage_config.rs, execution/executor-benchmark/src/db_generator.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/event_store/test.rs, storage/aptosdb/src/pruner/ledger_pruner_manager.rs, storage/aptosdb/src/pruner/ledger_pruner_worker.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs, storage/aptosdb/src/pruner/state_pruner_manager.rs, storage/aptosdb/src/pruner/state_pruner_worker.rs, storage/aptosdb/src/pruner/state_store/mod.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/pruner/transaction_store/test.rs, storage/aptosdb/src/pruner/utils.rs, storage/aptosdb/src/state_store/state_store_test.rs, terraform/helm/aptos-node/files/configs/fullnode.yaml, terraform/helm/aptos-node/files/configs/validator.yaml
Separate pruner configs.
Existing UTs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2983)
=> [storage][pruner] Separate ledger and state merkle pruner configs

storage/aptosdb/src/db_options.rs, storage/aptosdb/src/schema/mod.rs, storage/aptosdb/src/schema/stale_state_value_index/mod.rs, storage/aptosdb/src/schema/stale_state_value_index/test.rs, storage/aptosdb/src/state_store/mod.rs, types/src/state_store/state_value.rs
create stale value index.
will add test when pruner is added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3036)
=> [Storage] Stale state value index

ecosystem/platform/server/app/views/layouts/it3.html.erb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3012)
=> [community] Update IT3 schedule copy.

scripts/create-restore-job.py, terraform/fullnode/gcp/kubernetes.tf, terraform/fullnode/gcp/variables.tf, terraform/helm/fullnode/templates/fullnode.yaml
Support restore from the backup data for GCP fullnode
running a restore job from the backup data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3003)
=> [tf][gcp] add restore support

execution/executor-benchmark/src/transaction_committer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3028)
=> [Executor-benchmark] Update benchmark to use async commit.

crates/aptos/src/governance/mod.rs
TBD
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3060)
=> [aptos-cli] Save hashes as hex for proposal

crates/aptos/src/node/mod.rs, crates/aptos/src/test/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3070)
=> [aptos-cli] Ensure all commands work with new genesis files

ecosystem/platform/server/app/models/notification_preference.rb, ecosystem/platform/server/app/models/user.rb, ecosystem/platform/server/app/notifications/base_notification.rb, ecosystem/platform/server/app/notifications/governance_proposal_notification.rb, ecosystem/platform/server/app/notifications/node_upgrade_notification.rb, ecosystem/platform/server/db/migrate/20220817185306_create_notification_preferences.rb, ecosystem/platform/server/db/schema.rb, ecosystem/platform/server/spec/factories/notification_preferences.rb, ecosystem/platform/server/test/notifications/governance_proposal_notification_test.rb
Adds a model for notification preferences by notification type and delivery method. Updates existing notifications to take notification preferences into account.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3073)
=> [community] Create notification preferences model.

crates/aptos-telemetry-service/src/auth.rs, crates/aptos-telemetry-service/src/custom_event.rs, crates/aptos-telemetry-service/src/error.rs, crates/aptos-telemetry-service/src/index.rs, crates/aptos-telemetry-service/src/jwt_auth.rs, crates/aptos-telemetry-service/src/types/mod.rs, crates/aptos-telemetry-service/src/types/telemetry.rs
- Service errors are refined and meaningful errors are returned back to the client
- Adding new columns to identify each big query row
Fixes #2245 and #2118
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2996)
=> [telemetry-service] error handling and big query ingest improvements

.github/workflows/lint-test.yaml, testsuite/forge/src/backend/local/cargo.rs, testsuite/smoke-test/src/client.rs, testsuite/smoke-test/src/rosetta.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3074)
=> [smoke-test] Add option to have use --release mode for nodes, and enable it in CI

state-sync/storage-service/server/src/tests.rs
This PR fixes a genuine rebase collision not caught by CI/CD during test flake time.
The land blocking tests pipeline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3089)
=> [State Sync] Fix rebase collision in tests.

testsuite/smoke-test/src/aptos_cli/validator.rs
If the epoch change happens in between the calls, we cannot assert JOINING/LEAVING
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3085)
=> [smoke-test] Fix flaky validator test

crates/aptos/src/governance/mod.rs, crates/aptos/src/move_tool/mod.rs, testsuite/smoke-test/src/aptos_cli/move.rs
```
aptos governance --help
aptos-governance 0.2.4
Tool for on-chain governance
This tool allows voters that have stake to vote the ability to propose changes to the chain, as well
as vote and execute these proposals.
USAGE:
aptos governance <SUBCOMMAND>
OPTIONS:
-h, --help
Print help information
-V, --version
Print version information
SUBCOMMANDS:
execute-proposal
Execute a proposal that has passed voting requirements
help
Print this message or the help of the given subcommand(s)
propose
Submit proposal to other validators to be proposed on
vote
Submit a vote on a current proposal
```
New proposal:
```
aptos governance propose --script-path <SCRIPT_PATH> --framework-git-rev <FRAMEWORK_GIT_REV> --metadata-url <METADATA_URL> --pool-address <POOL_ADDRESS>
```
Voting
```
aptos governance …
```
=> [aptos-cli] Voting improvements

ecosystem/platform/server/app/controllers/projects_controller.rb, ecosystem/platform/server/app/models/project.rb, ecosystem/platform/server/app/views/projects/_form.html.erb, ecosystem/platform/server/app/views/projects/index.html.erb, ecosystem/platform/server/app/views/projects/show.html.erb, ecosystem/platform/server/db/migrate/20220816173205_add_initial_categories.rb, ecosystem/platform/server/db/schema.rb, ecosystem/platform/server/test/controllers/projects_controller_test.rb
Implement `projects#index` with projects grouped by category and support for filtering by category.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3017)
=> [community] Create projects index page.

ecosystem/platform/server/.better-html.yml, ecosystem/platform/server/.erb-lint.yml, ecosystem/platform/server/app/mailers/user_mailer.rb, ecosystem/platform/server/app/views/layouts/user_mailer.html.erb, ecosystem/platform/server/app/views/user_mailer/governance_proposal_notification.html.erb, ecosystem/platform/server/app/views/user_mailer/node_upgrade_notification.html.erb, ecosystem/platform/server/config/environments/development.rb, ecosystem/platform/server/config/initializers/better_html.rb, ecosystem/platform/server/test/mailers/previews/user_mailer_preview.rb
Tested manually with actionmailer previews.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3063)
=> [community] Update email template for notifications.

crates/aptos-rosetta-cli/src/construction.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/requests.rs
Now you can set expiry time on transactions through rosetta
TBD manual testing or a test that sets it into the past.
This will likely collide with my other PRs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3051)
=> [aptos-rosetta] Add configurable transaction expiry time

crates/aptos/src/account/list.rs
A requested feature, simple enough https://github.com/aptos-labs/aptos-core/issues/2629
```
aptos account list --profile local
{
"Result": [
{
"0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>": {
"coin": {
"value": "10000"
},
"deposit_events": {
"counter": "1",
"guid": {
"id": {
"addr": "0x5c30d8e8274549e0e4b2ca7de5599ffaa4326ef9ce977cb40557f6307dd9557b",
"creation_num": "1"
}
}
},
"frozen": false,
"withdraw_events": {
"counter": "0",
"guid": {
"id": {
"addr": "0x5c30d8e8274549e0e4b2ca7de5599ffaa4326ef9ce977cb40557f6307dd9557b",
"creation_num": "2"
}
}
}
}
},
{
"0x1::guid::Generator": {
"counter": "3"
}
},
{
"0x1::account::Account": {
"authentication_key": "0x5c30d8e8274549e0e4b2ca7de5599ffaa4326ef9ce977cb40557f6307dd9557b",
"coin_register_events": {
"counter": "1",
"guid": {
"id": { …
```
=> [aptos-cli] Add move type to list resources API

ecosystem/platform/server/app/components/header_component.html.erb, ecosystem/platform/server/app/components/header_component.rb, ecosystem/platform/server/app/javascript/controllers/header_controller.ts
Hide the user dropdown if the user clicks outside.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3082)
=> Hide the user dropdown if the user clicks outside.

crates/aptos/src/account/create.rs, crates/aptos/src/account/create_resource_account.rs, crates/aptos/src/common/types.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/node/mod.rs, crates/aptos/src/stake/mod.rs, crates/aptos/src/test/mod.rs, testsuite/smoke-test/src/aptos_cli/validator.rs
Let's see if this fixes the CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3104)
=> Revert "[aptos-cli] Cleanup general CLI output and make it more consistent"

aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.move, aptos-move/framework/aptos-framework/sources/coin.move, aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/framework/aptos-framework/sources/managed_coin.move, aptos-move/framework/aptos-framework/sources/supply.move
**Fourth PR in supporting aggregatable total supply in Move, should land after #3054 or even later!**
Integrates supply with coin, note that upgradability will be addressed in the next PR
Note: base branch is not main, when #3054 merges it will be rebased to main automatically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3055)
=> [Aptos Framework] Integrated aggregatable total supply with coins

developer-docs-site/docs/nodes/validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/using-docker.md, developer-docs-site/docs/nodes/validator-node/using-gcp.md, developer-docs-site/docs/nodes/validator-node/using-source-code.md
update doc to reflect CLI/deployment changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3115)
=> [doc] update deployment doc for AIT3

terraform/helm/monitoring/templates/monitoring.yaml
This got changed during API v0 deprecation. fix it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3129)
=> [helm] fix monitoring liveness probe

storage/aptosdb/src/metrics.rs, storage/aptosdb/src/state_store/buffered_state.rs, storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
To consolidate our dashboard.
ut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2368)
=> [storage] add counters for latest committed/snapshot version

ecosystem/platform/server/app/components/header_component.rb, ecosystem/platform/server/app/controllers/application_controller.rb, ecosystem/platform/server/app/controllers/onboarding_controller.rb, ecosystem/platform/server/config/routes.rb
Adds IT3 to the main nav and updates redirects to go to /it3 instead of /it2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2857)
=> [community] Show it3 in the nav and update redirects.

testsuite/testcases/src/performance_with_fullnode_test.rs
Seeing Forge failure because of this - https://github.com/aptos-labs/aptos-core/runs/7904217460?check_suite_focus=true. Disabling it until we resolve the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3137)
=> [Forge] Disable system metrics check

storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/event_store/test.rs, storage/aptosdb/src/pruner/ledger_pruner_manager.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs, storage/aptosdb/src/pruner/state_store/mod.rs, storage/aptosdb/src/pruner/state_store/state_value_pruner.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/pruner/transaction_store/test.rs, storage/aptosdb/src/pruner/utils.rs, storage/aptosdb/src/state_merkle_db.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/aptosdb/src/test_helper.rs, storage/jellyfish-merkle/src/restore/mod.rs
prune state value as part of ledger pruner.
also fix the restore of empty tree.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3106)
=> [pruner] state kv pruner

ecosystem/platform/server/app/views/projects/show.html.erb
Before:
After:
Manual.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3020)
=> [community] Improve projects#show page appearance.

fh-stream/src/runtime.rs
Minor change to fix firehose integration.
cargo test
tested w/ firehose
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3143)
=> [Indexer] Change log to be compliant with firehose expectations

developer-docs-site/docs/nodes/ait/additional-doc.md, developer-docs-site/docs/nodes/ait/connect-to-testnet.md, developer-docs-site/docs/nodes/ait/index.md, developer-docs-site/docs/nodes/ait/steps-in-ait3.md, developer-docs-site/docs/nodes/ait/whats-new-in-ait3.md
Match the flow with community platform steps. @rajkaramchedu we would need to update the image too. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3152)
=> [docs] update AIT3 flow

types/src/network_address/mod.rs
This was blocking cargo install for some reason.
Cherry picking while we don't update devnet quite yet.
We will also need to change the associated tag location
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3164)
=> Cherry pick dfc2f64bc1926e3078351a073b4da2e83d7d35c7 to fix cargo install issues

config/src/config/storage_config.rs, storage/aptosdb/src/db_options.rs, storage/aptosdb/src/lib.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/schemadb/src/lib.rs
add more rocksdb configs.
cargo build
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3159)
=> [rocksdb-config] add block_cache and cache_filter_and_index_block flag

aptos-move/framework/aptos-framework/sources/aptos_governance.move, aptos-move/framework/aptos-framework/sources/governance_proposal.move, aptos-move/framework/aptos-framework/sources/voting.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3140)
=> [Aptos Framework][Governance] Add a separate metadata field to voting::Proposal

terraform/helm/monitoring/files/prometheus.yml
drop spamming metrics from vector and kubernetes apiserver
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3135)
=> [helm] drop spamming metrics

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json, api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__on_chain_configs__drop_txn_after_reconfiguration_version_4.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__on_chain_configs__initial_aptos_version_version_4.exp, aptos-move/framework/aptos-framework/sources/block.move, aptos-move/framework/aptos-stdlib/sources/cryptography/crypto_hash.move, consensus/src/liveness/leader_reputation_test.rs, crates/aptos-crypto/src/hash.rs, crates/aptos-rest-client/src/lib.rs, storage/aptosdb/src/event_store/test.rs, testsuite/generate-format/tests/staged/aptos.yaml, testsuite/generate-format/tests/staged/consensus.yaml, types/src/account_config/events/new_block.rs, types/src/block_metadata.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3147)
=> [aptos-framework] introduce HashValue to aptos-stdlib and add block id to NewBlockEvent

developer-docs-site/docs/guides/install-petra-wallet.md, developer-docs-site/sidebars.js
After this lands, I will update the links in AIT-3 docs to point to this doc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3170)
=> [Docs] New doc for installing Petra.

config/src/config/storage_config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2968)
=> [Storage] Update default config.

terraform/aptos-node/aws/variables.tf, terraform/aptos-node/azure/variables.tf, terraform/aptos-node/gcp/variables.tf, terraform/fullnode/aws/variables.tf, terraform/fullnode/digital_ocean/variables.tf, terraform/fullnode/gcp/variables.tf, terraform/fullnode/vultr/variables.tf, terraform/helm/aptos-node/values.yaml, terraform/helm/fullnode/values.yaml
- Update resources based on https://aptos.dev/nodes/ait/node-requirements
- Update instance types
- did not update testnet deployment yet, since it might still make sense to run smaller instance there
TODO deploy on multiple clouds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3005)
=> [helm][tf] update default resources and machine types

crates/aptos/src/genesis/keys.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3185)
=> [aptos-genesis] Use validator full node identity for vfn

Cargo.lock, crates/aptos/Cargo.toml
=> [aptos-cli] Release 0.3.0

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/aptos_client.ts
Recreation of https://github.com/aptos-labs/aptos-core/pull/3011.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3196)
=> Switch from BigInt to BigInt | number for TS SDDK parameters

developer-docs-site/docs/nodes/validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/using-gcp.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3197)
=> [docs] update testnet chain ID

terraform/aptos-node/aws/variables.tf
don't use graviton lol
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3198)
=> [tf][aws] update aws utilities spec

ecosystem/platform/server/app/controllers/onboarding_controller.rb, ecosystem/platform/server/config/routes.rb, ecosystem/platform/server/test/controllers/onboarding_controller_test.rb
Updates onboarding redirects to the new /community landing page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3194)
=> [community] Update onboarding redirects to /community.

developer-docs-site/docs/nodes/validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/using-docker.md, developer-docs-site/docs/nodes/validator-node/using-gcp.md, developer-docs-site/docs/nodes/validator-node/using-source-code.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3201)
=> [docs] update command for framework

ecosystem/platform/server/app/views/layouts/it3.html.erb, ecosystem/platform/server/app/views/static_page/incentivized_testnet.html.erb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3202)
=> [CP] Update AIT3 dates + links

terraform/helm/aptos-node/values.yaml
Fullnode and validator resources are separate
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3203)
=> [helm][aptos-node/fullnode] bump down cpu and mem requirements

developer-docs-site/docs/nodes/validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/using-docker.md, developer-docs-site/docs/nodes/validator-node/using-gcp.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3205)
=> [docs] update CLI version

ecosystem/platform/server/app/views/static_page/privacy.html.erb
Same as title
Ran locally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3167)
=> Update privacy policy with Petra

developer-docs-site/docs/nodes/node-health-checker.md, ecosystem/node-checker/configuration_examples/ait3_validator.yaml, ecosystem/node-checker/configuration_examples/devnet_fullnode.yaml, ecosystem/node-checker/configuration_examples/single_node_validator.yaml
The config examples were old and broken and the docs had broken links.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3216)
=> [NHC] Update configuration examples and docs accordingly

ecosystem/platform/server/app/views/it3s/show.html.erb
Update copy for IT3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3221)
=> [community] Update selection deadline copy.

testsuite/smoke-test/src/storage.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3114)
=> Fix flaky storage::test_db_restore smoke test

developer-docs-site/docs/nodes/ait/index.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3223)
=> [Docs] AIT-3 dates.

developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3225)
=> Fix CLI install command for AIT-3

Cargo.lock, storage/scratchpad/Cargo.toml, storage/scratchpad/benches/sparse_merkle.rs
broken after smt deletion and get_usage()
cargo bench -p scratchpad --features bench
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3219)
=> [scratchpad] fix benchmark build

ecosystem/platform/server/app/views/layouts/it3.html.erb, ecosystem/platform/server/app/views/static_page/incentivized_testnet.html.erb
Updates page title, meta images and descriptions for AIT3
Check title, meta images and descriptions for `/incentivized-testnet` and `/ait3`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3204)
=> [CP] Update Titles, Meta Images and Descriptions for AIT3

api/doc/spec.json, api/doc/spec.yaml, crates/aptos/src/account/create.rs, crates/aptos/src/account/create_resource_account.rs, crates/aptos/src/account/list.rs, crates/aptos/src/account/transfer.rs, crates/aptos/src/common/init.rs, crates/aptos/src/common/types.rs, crates/aptos/src/config/mod.rs, crates/aptos/src/genesis/mod.rs, crates/aptos/src/governance/mod.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/move_tool/package_hooks.rs, crates/aptos/src/move_tool/stored_package.rs, crates/aptos/src/node/analyze/analyze_validators.rs, crates/aptos/src/node/analyze/fetch_metadata.rs, crates/aptos/src/node/mod.rs, crates/aptos/src/op/key.rs, crates/aptos/src/stake/mod.rs, crates/aptos/src/test/mod.rs, ecosystem/typescript/sdk/src/generated/models/IndexResponse.ts, ecosystem/typescript/sdk/src/generated/schemas/$IndexResponse.ts, testsuite/smoke-test/src/aptos_cli/move.rs, testsuite/smoke-test/src/aptos_cli/validator.rs
This is the previous PR I had reverted https://github.com/aptos-labs/aptos-core/pull/3104 plus some clone removal.  I have a feeling that the Move package system is doing some recursive calls that are the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3107)
=> [aptos-cli] Update CLI commands & remove excessive memory clones

api/doc/spec.json, api/doc/spec.yaml, api/src/accept_type.rs, api/src/bcs_payload.rs, api/types/src/mime_types.rs, crates/aptos-rest-client/src/lib.rs, ecosystem/typescript/sdk/src/generated/models/IndexResponse.ts, ecosystem/typescript/sdk/src/generated/schemas/$IndexResponse.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3226)
=> [api] Remove unused old BCS type

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json, aptos-move/framework/aptos-framework/sources/aptos_governance.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3210)
=> [Governance] Allow stakers who have a lockup but are not part of active validator set vote

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json, aptos-move/framework/aptos-framework/sources/configs/version.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3224)
=> [Aptos Framework] Fix broken unit tests

CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3236)
=> [OWNERS] Update code owners for important directories under aptos-move

developer-docs-site/docs/nodes/ait/node-liveness-criteria.md
The issues link for AIT-3 needs someone to create a repo for it. I will defer it to a separate PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3241)
=> Update Medium link for AIT-3

crates/aptos/src/config/mod.rs, ecosystem/python/sdk/Makefile, ecosystem/python/sdk/README.md, ecosystem/python/sdk/aptos_sdk/client.py, ecosystem/python/sdk/poetry.lock, ecosystem/typescript/sdk/jest.config.js, ecosystem/typescript/sdk/package.json
* cli recursive checks were broken
* ts didn't make it easy to filter for tests
* python was missing a critical instruction on how to use poetry
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3239)
=> cli and sdk tweaks

CODEOWNERS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3242)
=> add code owners for execution

developer-docs-site/docs/nodes/ait/connect-to-testnet.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3240)
=> fix some errors in commands

ecosystem/platform/server/app/views/shared/_it3_intro.html.erb
Additional Medium URL needed to be updated for AIT3
Ensure URL within `/ait3` for _Aptos Incentivized Testnet 3 details_ links to the updated Medium post
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3238)
=> [CP] Update AIT3 Medium url within node registration flow

ecosystem/platform/server/app/views/it3s/show.html.erb
The bracket is in wrong position so target param is not passed to `LinkComponent`'s `initialize` method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3231)
=> [community] Fix target for Aptos Wallet external URL on IT3 page 

Cargo.lock, api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json, aptos-move/aptos-aggregator/src/aggregator_extension.rs, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-gas/src/gas_meter.rs, aptos-move/aptos-gas/src/lib.rs, aptos-move/aptos-gas/src/table.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/framework/src/natives/aggregator_natives/context.rs, aptos-move/move-deps/Cargo.toml
This updates the move dependencies and adds the on-chain gas parameters for table native functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3250)
=> [gas] update move dependencies and add on-chain gas parameters for table

aptos-move/framework/aptos-stdlib/sources/table_with_length.move
credit goes to @lzhanson
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3175)
=> bug fix: length++ when !contains

developer-docs-site/docs/nodes/validator-node/using-source-code.md
-fix reference to config folder for config files
-add note for data directory and write access requirement
Change configuration file locations to match config folder created.  Also mentioned changing data directory to a location with write access.  Default of /opt/aptos requires root access and will fail unless running node as root.
Personally followed the new instruction to start a validator node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3249)
=> Update config and data paths

README.md
This cleans up the readme of unused stuff and adds a working coverage badge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2936)
=> [docs] cleanup README and add coverage badge

developer-docs-site/static/examples/python/first_coin.py, developer-docs-site/static/examples/python/first_nft.py, developer-docs-site/static/examples/python/first_transaction.py, developer-docs-site/static/examples/python/hello_blockchain.py, developer-docs-site/static/examples/rust/first_coin/src/lib.rs, developer-docs-site/static/examples/rust/first_coin/src/main.rs, developer-docs-site/static/examples/rust/first_transaction/src/lib.rs, developer-docs-site/static/examples/rust/first_transaction/src/main.rs, developer-docs-site/static/examples/rust/hello_blockchain/src/main.rs, developer-docs-site/static/examples/typescript/first_coin.ts, developer-docs-site/static/examples/typescript/first_nft.ts, developer-docs-site/static/examples/typescript/first_transaction.ts, developer-docs-site/static/examples/typescript/hello_blockchain.ts, developer-docs-site/static/examples/typescript/package.json
No need to review unless you want... these are in dire need of update, so I'll autoland assuming they pass the dev docs tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3261)
=> dev docs example fix up

api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json, aptos-move/framework/aptos-framework/sources/block.move, aptos-move/framework/aptos-framework/sources/reconfiguration.move, aptos-move/framework/aptos-framework/sources/stake.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3268)
=> [Staking] Add some useful public test functions

Cargo.lock, Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-gas/src/algebra.rs, aptos-move/aptos-gas/src/aptos_framework.rs, aptos-move/aptos-gas/src/lib.rs, aptos-move/aptos-gas/src/misc.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/framework/Cargo.toml, aptos-move/framework/src/natives/event.rs, aptos-move/framework/src/natives/mod.rs, aptos-move/framework/src/natives/type_info.rs, aptos-move/framework/tests/move_unit_test.rs, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/gas-algebra-ext/src/lib.rs, aptos-move/move-examples/tests/move_unit_tests.rs, aptos-move/vm-genesis/src/lib.rs, aptos-move/writeset-transaction-generator/src/writeset_builder.rs, crates/aptos/src/move_tool/aptos_debug_natives.rs, crates/aptos/src/move_tool/mod.rs
This manages to break up the dependency cycle and fixes the last few broken gas formulae in aptos-framework.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3274)
=> [gas] fix gas formulae for natives in aptos-framework

developer-docs-site/docs/nodes/validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/using-docker.md, developer-docs-site/docs/nodes/validator-node/using-gcp.md, developer-docs-site/docs/nodes/validator-node/using-source-code.md
Adding CLI install link to the validator install by source code page, and fixing CLI links in all validator install cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3278)
=> [Docs] Fixing CLI install links.

aptos-move/move-examples/hello_blockchain/Move.toml, aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move, aptos-move/move-examples/hello_blockchain/sources/hello_blockchain_test.move, aptos-move/move-examples/message_board/Move.toml, aptos-move/move-examples/message_board/sources/acl_message_board.move, aptos-move/move-examples/message_board/sources/cap_message_board.move, aptos-move/move-examples/message_board/sources/offer.move, aptos-move/move-examples/tests/move_unit_tests.rs, crates/aptos/src/test/mod.rs, developer-docs-site/docs/tutorials/first-move-module.md, developer-docs-site/static/examples/python/hello_blockchain.py, ecosystem/python/sdk/examples/hello-blockchain.py, testsuite/smoke-test/src/aptos_cli/move.rs
* rename to modern style
* add offer.move so it can be built again -- probably should explore
other ways to write this
* add test to move_unit_tests so it doesn't fall apart again
also some minor fixes to hello blockchain
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3275)
=> [move-examples] fix message board

developer-docs-site/docs/tutorials/first-transaction-sdk.md, developer-docs-site/docs/tutorials/index.md, developer-docs-site/docs/tutorials/your-first-nft-sdk.md, developer-docs-site/sidebars.js, developer-docs-site/src/remark/code-injector.js, developer-docs-site/static/sdks/python, ecosystem/python/sdk/aptos_sdk/client.py, ecosystem/python/sdk/examples/common.py, ecosystem/python/sdk/examples/simple-nft.py, ecosystem/python/sdk/examples/transfer-coin.py
* Use links
* Update to entry functions
* Add python headers
* bring up common.py
* add first nft doc
* Rename quickstarts -> tutorials
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3263)
=> [docs] cleanup dev docs

terraform/aptos-node/aws/README.md
Wrong name in readme.
eyes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3218)
=> Fix aws aptos-node tf README regarding region var

Cargo.lock, api/types/src/error.rs, crates/aptos-crypto/Cargo.toml, crates/aptos-crypto/src/ed25519/ed25519_keys.rs, crates/aptos-rest-client/Cargo.toml, crates/aptos-rest-client/src/error.rs, crates/aptos-rest-client/src/faucet.rs, crates/aptos-rest-client/src/lib.rs, crates/aptos-rest-client/src/response.rs, crates/aptos-rosetta-cli/Cargo.toml, crates/aptos-rosetta/Cargo.toml, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/block.rs, crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/error.rs, crates/aptos-rosetta/src/types/identifiers.rs, crates/aptos-rosetta/src/types/misc.rs, crates/aptos-rosetta/src/types/requests.rs, crates/aptos-telemetry-service/src/clients.rs, crates/aptos/src/account/list.rs, crates/aptos/src/common/types.rs, ecosystem/node-checker/src/evaluators/direct/api/transaction_availability.rs, testsuite/forge/src/backend/k8s/swarm.rs, testsuite/forge/src/backend/local/node.rs, testsuite/forge/src/interface/node.rs, testsuite/smoke-test/src/rosetta.rs
* Add Create account on transfer
* Add sequence numbers as input to transaction metadata
* Add proper testing that tests both construction and data APIs
* Add error codes for the rest api client
* Convert all REST API errors to rosetta API errors with compliant codes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3229)
=> [aptos-rosetta] Rosetta features

.dockerignore, Cargo.lock, aptos-move/framework/aptos-framework/sources/aggregator/aggregator.spec.move, aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.spec.move, aptos-move/framework/aptos-framework/sources/state_storage.spec.move, aptos-move/framework/aptos-framework/sources/timestamp.spec.move, aptos-move/framework/aptos-stdlib/Move.toml, aptos-move/framework/aptos-stdlib/sources/capability.move, aptos-move/framework/aptos-stdlib/sources/capability.spec.move, aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381.move, aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381.spec.move, aptos-move/framework/aptos-stdlib/sources/cryptography/ed25519.spec.move, aptos-move/framework/aptos-stdlib/sources/cryptography/secp256k1.spec.move, aptos-move/framework/aptos-stdlib/sources/event.move, aptos-move/framework/aptos-stdlib/sources/event.spec.move, aptos-move/framework/aptos-stdlib/sources/hash.move, aptos-move/framework/aptos-stdlib/sources/hash.spec.move, aptos-move/framework/aptos-stdlib/sources/type_info.move, aptos-move/framework/aptos-stdlib/sources/type_info.spec.move, aptos-move/framework/move-stdlib/Move.toml, aptos-move/move-deps/Cargo.toml, aptos-move/move-deps/src/lib.rs, crates/aptos/src/move_tool/aptos-natives.bpl, crates/aptos/src/move_tool/mod.rs
- Added `aptos-natives.bpl`
- `Aptos CLI` includes it in invoking Prover
- Separated the spec from the code
- Prover should finish without error for the Aptos Framework
cargo test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3206)
=> [Move Prover] Support the custom boogie file

aptos-move/framework/aptos-framework/sources/util.move, aptos-move/framework/aptos-stdlib/sources/any.move, aptos-move/framework/src/natives/any.rs, aptos-move/framework/src/natives/mod.rs
This adds the `Any` type which allows polymorphic representation of values.
Added test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3291)
=> [aptos-stdlib] Any type

storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/ledger_pruner_manager.rs, storage/aptosdb/src/pruner/pruner_manager.rs, storage/aptosdb/src/pruner/state_pruner_manager.rs
existing UTs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3292)
=> [storage] simplify wake_and_wait_pruner

storage/aptosdb/src/aptosdb_test.rs
no longer necessary to do nested loops now that we separate the pruner
configs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3299)
=> [storage] trivial: test_pruner_config simpler

ecosystem/platform/server/app/controllers/discourse_controller.rb, ecosystem/platform/server/app/models/user.rb
Fixes https://sentry.io/organizations/aptos-labs/issues/3516506240/?project=6388301&query=is%3Aunresolved
Ran existing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3297)
=> [community] Don't attempt to add users to nonexistent group.

testsuite/run_forge.sh
The kubectl context doesn't exist until you do `aws eks update-kubeconfig`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3306)
=> [forge] change kubectl context

Cargo.lock, api/Cargo.toml, api/doc/spec.json, api/doc/spec.yaml, api/goldens/aptos_api__tests__index_test__test_cors_forbidden.json, api/src/tests/index_test.rs, api/test-context/Cargo.toml, api/types/Cargo.toml, aptos-move/gas-algebra-ext/Cargo.toml, config/Cargo.toml, crates/aptos-openapi/Cargo.toml, crates/aptos-rest-client/Cargo.toml, ecosystem/node-checker/Cargo.toml
We were using a specific git revision because a feature we needed was in GitHub but not released to crates.io yet. It has been released now, so we can cut back.
I did a review of all the other changes we're bringing in (not many) and it looks fine.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3296)
=> Switch back to crates.io version of Poem

aptos-move/framework/aptos-stdlib/sources/any.spec.move, aptos-move/framework/aptos-stdlib/sources/cryptography/ristretto255.move, aptos-move/framework/aptos-stdlib/sources/cryptography/ristretto255.spec.move
- Added the missing mockup specs for the recently added native functions
- Prover should work again
cargo test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3305)
=> [Move Prover] Added the missing spec files

crates/aptos-rosetta/src/types/objects.rs
Operation metadata is required to be flat JSON, so I've fixed it accordingly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3282)
=> [aptos-rosetta] Fix operation metadata to fit spec

terraform/helm/aptos-node/values.yaml
The values I have indicated will allow participants to save about $ 150 per month on paying for disk storage, which is installed automatically.
The specified disk space size will be more than enough during network testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3259)
=> Change FullNode and Validator storage size.

aptos-move/aptos-vm/src/errors.rs, aptos-move/aptos-vm/src/system_module_names.rs, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.move, aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.move, aptos-move/framework/aptos-framework/sources/block.move, aptos-move/framework/aptos-framework/sources/chain_id.move, aptos-move/framework/aptos-framework/sources/coin.move, aptos-move/framework/aptos-framework/sources/configs/consensus_config.move, aptos-move/framework/aptos-framework/sources/configs/gas_schedule.move, aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/framework/aptos-framework/sources/managed_coin.move, aptos-move/framework/aptos-framework/sources/reconfiguration.move, aptos-move/framework/aptos-framework/sources/resource_account.move, aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/aptos-framework/sources/state_storage.move, aptos-move/framework/aptos-framework/sources/timestamp.move, aptos-move/framework/aptos-framework/sources/timestamp.spec.move, aptos-move/framework/aptos-framework/sources/transaction_fee.move, aptos-move/framework/aptos-framework/tests/aggregator_tests.move, aptos-move/framework/aptos-stdlib/sources/bucket_table.move, aptos-move/framework/aptos-stdlib/sources/capability.move, aptos-move/framework/aptos-stdlib/sources/capability.spec.move, aptos-move/framework/aptos-stdlib/sources/debug.move, aptos-move/framework/aptos-stdlib/sources/guid.move, documentation/specifications/move_adapter/README.md, testsuite/smoke-test/src/aptos/gas_check.rs, types/src/account_config/resources/chain_account_info.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3294)
=> [Aptos Framework][Cleanups] Various cleanups of function visibility and unused code

crates/aptos/src/node/analyze/analyze_validators.rs, crates/aptos/src/node/analyze/fetch_metadata.rs, crates/aptos/src/node/mod.rs, crates/aptos/src/test/mod.rs, testsuite/smoke-test/src/aptos_cli/validator.rs
Added rewards test:
- we have 4 nodes.
- one leaves validator set
- one is unreliable
We fetch their stakes, and confirm increases match their proposal success rate.
added test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3066)
=> [stake][swarm] Add e2e rewards test

aptos-move/framework/aptos-framework/sources/stake.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3341)
=> [Aptos Framework][Staking] Add explicit errors for missing StakePool resource

developer-docs-site/docs/tutorials/first-dapp.md, developer-docs-site/static/examples/typescript/dapp-example/src/App.tsx
Fix dapp example for script function rename and module lower case
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3315)
=> [wallet] Fix dapp example for script function rename and module lower case

storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/pruner_manager.rs, storage/aptosdb/src/pruner/state_pruner_manager.rs, storage/aptosdb/src/pruner/state_pruner_worker.rs, storage/aptosdb/src/pruner/state_store/mod.rs, storage/aptosdb/src/state_merkle_db.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_merkle_batch_committer.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/jellyfish-merkle/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3327)
=> [storage] more pruner fixes

ecosystem/platform/server/Gemfile, ecosystem/platform/server/Gemfile.lock, ecosystem/platform/server/config/routes.rb
Adds flipper-ui for managing feature flags (only available to admins).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3200)
=> [community] Add UI for managing feature flags.

ecosystem/platform/server/app/controllers/settings_controller.rb, ecosystem/platform/server/app/helpers/settings_helper.rb, ecosystem/platform/server/app/views/settings/notifications.html.erb, ecosystem/platform/server/app/views/settings/profile.html.erb, ecosystem/platform/server/config/routes.rb, ecosystem/platform/server/test/controllers/settings_controller_test.rb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3131)
=> [community] Create notification settings page.

storage/aptosdb/src/aptosdb_test.rs
temporarily 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3357)
=> [storage] disable test_state_merkle_pruning

developer-docs-site/docs/guides/install-petra-wallet.md
I added the Chrome Web Store extension page, instructions for installation, and also a note about restoring an existing Aptos wallet account.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3252)
=> Updated instructions

aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/pruner/state_store/mod.rs
Test no longer flaky on my dev machine.
```
for i in `seq 1 30`; do cargo test -p aptosdb -- test_state_merkle_pruning; done
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3364)
=> [storage] state pruner: add mutex to protect pruning progress

aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, types/src/proof/definition.rs
existing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3368)
=> trivial: type_name::<Self>() in some error msgs

aptos-move/e2e-move-tests/tests/aggregator.data/pack/sources/aggregator_test.move, aptos-move/framework/aptos-framework/sources/aggregator/aggregator.move, aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.move, aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.move, aptos-move/framework/aptos-framework/tests/aggregator_tests.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3353)
=> [Aptos Framework][Aggregator] Cleanup

ecosystem/platform/server/app/components/global_announcement_component.html.erb, ecosystem/platform/server/app/components/global_announcement_component.rb, ecosystem/platform/server/app/javascript/controllers/index.js, ecosystem/platform/server/app/javascript/controllers/visibility_controller.ts, ecosystem/platform/server/app/views/layouts/_application.html.erb, ecosystem/platform/server/app/views/layouts/it3.html.erb, ecosystem/platform/server/app/views/shared/_it3_intro.html.erb, ecosystem/platform/server/app/views/static_page/incentivized_testnet.html.erb, ecosystem/platform/server/app/views/static_page/root.html.erb, ecosystem/platform/server/spec/components/global_announcement_component_spec.rb
- Create Global Announcement Banner component 
- Setup new `visibility_controller` for targeting visibility of elements with options for utilizing `sessionStorage`
- Ensure global banner displays correctly on all pages
- Test **sessionStorage** capabilities by closing the banner
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3355)
=> [CP] Setup global announcement banner

aptos-move/framework/aptos-framework/sources/aptos_governance.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3380)
=> [Governance] Only allow validators to vote if the validator set is closed (e.g. in devnet)

api/doc/spec.json, api/doc/spec.yaml, api/src/accounts.rs, api/src/blocks.rs, api/src/context.rs, api/src/events.rs, api/src/index.rs, api/src/response.rs, api/src/state.rs, api/src/transactions.rs, api/types/src/error.rs, config/src/config/api_config.rs, crates/aptos-rosetta/src/error.rs, crates/aptos-rosetta/src/main.rs, ecosystem/typescript/sdk/src/generated/models/AptosErrorCode.ts, testsuite/smoke-test/src/rosetta.rs
Add ability to turn off 3 APIs with 3 checks
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3377)
=> [api] Allow turning off transaction submission, simulation, and encoding

.github/workflows/pre-release-e2e-tests.yaml, testsuite/forge/src/backend/k8s/cluster_helper.rs
- Test forge by messing things up
- [forge] Add Pre Release forge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3388)
=> releaseforge

storage/aptosdb/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3403)
=> [cherry-pick][storage] use the correct pruner to determine data availability

config/src/config/consensus_config.rs, config/src/config/execution_config.rs, terraform/helm/aptos-node/values.yaml, testsuite/forge/src/backend/local/swarm.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3344)
=> [consensus][configs] Set quorum_store_poll_count=5 and concurrency_level=8

aptos-move/e2e-move-tests/tests/code_publishing.rs, aptos-move/framework/aptos-framework/sources/code.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3381)
=> [Aptos Framework][Upgradability] Disable incompatible upgrade policy

aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/aptos_governance.move, aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/framework/aptos-framework/sources/system_addresses.move
put 0x2 .. 0x10 under aptos governance
update unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3365)
=> [Token] Store the framework reserved accounts unders goverance

testsuite/smoke-test/src/client.rs, testsuite/smoke-test/src/full_nodes.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3407)
=> [smoke-test] Disable flaky

api/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3330)
=> Fixing README links

developer-docs-site/docs/sdks/python-sdk.md, developer-docs-site/docs/tutorials/first-transaction-sdk.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3383)
=> [Docs] Syncing tabs.

crates/transaction-emitter-lib/src/emitter/submission_worker.rs
Continuous test logs are pretty noisy - reducing the volume. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3401)
=> [Txn emitter] Reduce log frequency to reduce log volume for Forge

consensus/consensus-types/src/common.rs, consensus/src/quorum_store/quorum_store_wrapper.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3358)
=> fix build error

storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/pruner_manager.rs, storage/aptosdb/src/pruner/transaction_store/test.rs, storage/storage-interface/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3423)
=> [storage] fix that get_accumulator_summary requires full txn accumualtor

Cargo.lock, ecosystem/indexer/Cargo.toml, ecosystem/indexer/src/database.rs, ecosystem/indexer/src/default_processor.rs, ecosystem/indexer/src/indexer/errors.rs, ecosystem/indexer/src/indexer/fetcher.rs, ecosystem/indexer/src/indexer/processing_result.rs, ecosystem/indexer/src/indexer/tailer.rs, ecosystem/indexer/src/indexer/transaction_processor.rs, ecosystem/indexer/src/main.rs, ecosystem/indexer/src/models/events.rs, ecosystem/indexer/src/models/metadata.rs, ecosystem/indexer/src/models/processor_statuses.rs, ecosystem/indexer/src/models/transactions.rs, ecosystem/indexer/src/models/write_set_changes.rs, ecosystem/indexer/src/schema.rs, ecosystem/indexer/src/token_processor.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3419)
=> add batch write

crates/aptos/Cargo.toml, crates/aptos/src/common/types.rs, crates/aptos/src/governance/mod.rs, crates/aptos/src/move_tool/mod.rs
Fixes the output of voting, and removes an unused input field for creating proposals.
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3429)
=> [aptos-cli] Fix output of voting

ecosystem/platform/server/app/controllers/projects_controller.rb, ecosystem/platform/server/app/controllers/users_controller.rb, ecosystem/platform/server/app/helpers/users_helper.rb, ecosystem/platform/server/app/models/category.rb, ecosystem/platform/server/app/models/user.rb, ecosystem/platform/server/app/views/layouts/users.html.erb, ecosystem/platform/server/app/views/projects/index.html.erb, ecosystem/platform/server/app/views/projects/show.html.erb, ecosystem/platform/server/app/views/users/activity.html.erb, ecosystem/platform/server/app/views/users/projects.html.erb, ecosystem/platform/server/app/views/users/rewards.html.erb, ecosystem/platform/server/app/views/users/show.html.erb, ecosystem/platform/server/config/routes.rb, ecosystem/platform/server/db/migrate/20220823211505_add_bio_to_users.rb, ecosystem/platform/server/db/schema.rb, ecosystem/platform/server/spec/factories/categories.rb, ecosystem/platform/server/spec/factories/project_categories.rb, ecosystem/platform/server/spec/factories/projects.rb, ecosystem/platform/server/spec/factories/users.rb, ecosystem/platform/server/test/controllers/projects_controller_test.rb, ecosystem/platform/server/test/controllers/users_controller_test.rb
Creates user profile pages, gated behind the `:projects` flag. Most of the pages have placeholder content for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3361)
=> [community] Create user profile pages.

ecosystem/indexer/src/indexer/fetcher.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3446)
=> [ECO] Set indexer max batches to 20

developer-docs-site/docs/nodes/ait/steps-in-ait3.md
Update ait3 doc with new UI transactions and the correct staking page url
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3443)
=> Update ait3 doc

developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md, developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
- Updated the dev doc with Move Prover's dependency installation description
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3461)
=> [Move Prover] dependency installation description

ecosystem/indexer/src/indexer/fetcher.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3465)
=> [ECO] Fix 'attempt to subtract with overflow'

aptos-move/framework/aptos-framework/sources/account.spec.move, aptos-move/framework/aptos-framework/sources/timestamp.spec.move, scripts/dev_setup.sh
- Fixed the `dev_setup.sh` to install Prover's dependencies properly.
scripts/dev_setup.sh -yp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3457)
=> [Move Prover] Fixed the broken script

developer-docs-site/docs/guides/install-petra-wallet.md, developer-docs-site/docs/whats-new-in-docs.md
Regular clean up and link fixing stuff.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3449)
=> [Docs] Formatting and link fixes.

crates/aptos/src/governance/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3409)
=> Fix proposal CLI

storage/aptosdb/src/state_store/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3445)
=> [Storage] Add a metric to show the latency of k/v read inside put_stats_and_indices.

testsuite/fixtures/testMain.fixture, testsuite/fixtures/testMainComment.fixture, testsuite/fixtures/testMainReport.fixture, testsuite/forge.py, testsuite/forge_test.py
Handle pre emption and even print the killer!
Fix bug where I forgot to use the process abstraction for killing things, wrap multiprocess and rlimits as well.
Add list-jobs command to go through and list jobs in all forge clusters
Test plan: unittest and running two instances locally to trigger preemption
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3452)
=> [forge] Handle preemption, fix bugs, add list-jobs command

terraform/helm/aptos-node/templates/fullnode.yaml
Similar to https://github.com/aptos-labs/aptos-core/pull/1636, for fullnodes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3470)
=> [testnet] In privileged mode, log in as root for fullnodes.

Cargo.lock, crates/aptos/Cargo.toml
Cherrypick update to cli version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3499)
=> [aptos-cli] Bump to 0.3.1

.github/workflows/continuous-e2e-release-test.yaml, .github/workflows/run-forge.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3481)
=> [forge] Fix workflow

developer-docs-site/docs/concepts/index.md, developer-docs-site/docs/concepts/upgrading-code.md
Adds a page to the concepts section of docsite.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3322)
=> [docs] Concept doc of code upgrade

aptos-move/framework/aptos-token/sources/token_transfers.move
to remove the nested table from token transfer
updated unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3506)
=> [Token] use flat map to replace the nested table

CODEOWNERS
Be aware of token and related doc changes
CICD
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3437)
=> Watch for token and related doc change

Cargo.lock, crates/aptos/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3492)
=> [aptos-cli] Bump version 0.3.1

Cargo.lock, crates/aptos/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3525)
=> [aptos-cli] Update to version 0.3.2

Cargo.lock, crates/aptos/Cargo.toml
=> [aptos-cli] Update to version 0.3.2 cherry-pick

ecosystem/platform/server/.env.example, ecosystem/platform/server/app/controllers/leaderboard_controller.rb, ecosystem/platform/server/app/helpers/leaderboard_helper.rb, ecosystem/platform/server/app/views/leaderboard/it3.html.erb, ecosystem/platform/server/config/routes.rb, ecosystem/platform/server/public/it3_leaderboard_example.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3469)
=> [community] Create it3 leaderboard.

ecosystem/indexer/src/indexer/fetcher.rs
Sometimes API fails so we retry 5 times. 
CI
Resolves: https://github.com/aptos-labs/aptos-core/issues/3504
Slightly improved version of https://github.com/aptos-labs/aptos-core/pull/3505
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3517)
=> [indexer] Allow for failures in ledger info

state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3494)
=> [state sync] spawn_blocking around synchronous executor calls

ecosystem/indexer/src/models/transactions.rs, ecosystem/indexer/src/token_processor.rs
Fix issues with token indexer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3542)
=> [indexer] Fix token ownership data to work with batching

config/src/config/consensus_config.rs, consensus/src/epoch_manager.rs, consensus/src/network.rs, testsuite/forge/src/interface/aptos.rs, testsuite/forge/src/interface/swarm.rs, testsuite/forge/src/lib.rs, testsuite/forge/src/test_utils/consensus_utils.rs, testsuite/forge/src/test_utils/mod.rs, testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs, testsuite/smoke-test/src/consensus/mod.rs, testsuite/smoke-test/src/lib.rs, testsuite/smoke-test/src/test_utils.rs
Adding LocalSwarm tests for consensus fault tolerance, and preparing code to be able to run it on remote Forge as well.
run tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/2827)
=> [consensus][smoke-tests] Add consensus fault tolerance test

execution/executor/src/components/chunk_output.rs, storage/aptosdb/src/state_store/mod.rs, storage/storage-interface/src/cached_state_view.rs
This can 10x state-sync TPS when these read hit disk.
Tested on Alden-net.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3502)
=> [Storage] Use thread pools to make IO operations async.

terraform/helm/monitoring/templates/monitoring.yaml, terraform/helm/monitoring/values.yaml
Try to reduce prometheus memory footprint by tuning retention and block duration
Deploy to forge prometheus and observe memory utilization
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3545)
=> [helm][monitoring] tune prometheus for lower memory footprint

.github/workflows/continuous-e2e-chaos-test.yaml, .github/workflows/continuous-e2e-compat-test.yaml, .github/workflows/continuous-e2e-performance-test.yaml, .github/workflows/continuous-e2e-release-test.yaml, .github/workflows/continuous-e2e-shadow-test.yaml, .github/workflows/continuous-e2e-single-vfn-test.yaml, .github/workflows/run-forge.yaml, testsuite/forge-cli/src/main.rs, testsuite/forge-test-runner-template.yaml, testsuite/forge.py, testsuite/forge/src/runner.rs, testsuite/forge_test.py, testsuite/run_forge.sh
- adding single epoch change to land blocking run
- adding waiting for all nodes to sync (after traffic has stopped) to a few runs (including land blocking)
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3534)
=> [forge] Success criteria per forge run

testsuite/testcases/src/performance_with_fullnode_test.rs
As above
Run Forge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3567)
=> [Forge] Disable System metrics check as querying prometheus is not stable

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
No test needed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3509)
=> fix aptos fund command

ecosystem/typescript/sdk/examples/typescript/simple_nft.ts
Code different from [Your First NFT](https://aptos.dev/tutorials/your-first-nft#step-3-understand-the-output) document may cause confusion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3562)
=> Fix typescript example log

developer-docs-site/docs/guides/move-guides/upgrading-move-code.md
Adapt to newest implementation and extend discussion
NA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3560)
=> [upgrade docs] Refine documentation for code upgrade

ecosystem/platform/server/app/controllers/it3_profiles_controller.rb, ecosystem/platform/server/test/controllers/it3_profiles_controller_test.rb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3585)
=> [CP] Fix flipper redirect

storage/scratchpad/src/sparse_merkle/mod.rs
hopefully it's clearer by a little bit
cargo test -p scratchpad -- multithread drop
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3529)
=> [scratchpad] simplify the BranchTracker and add comments

consensus/src/liveness/leader_reputation.rs, consensus/src/liveness/leader_reputation_test.rs, consensus/src/liveness/proposer_election.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3591)
=> [consensus] cherry pick leader election overflow

consensus/src/liveness/leader_reputation.rs, consensus/src/liveness/leader_reputation_test.rs, consensus/src/liveness/proposer_election.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3586)
=> [consensus] Fixed leader election overflow

config/src/config/storage_config.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3598)
=> [storage] test default prune window config

testsuite/smoke-test/src/aptos_cli/validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3593)
=> [e2e test] Total voting power being u128

api/src/context.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rest_api.rs, testsuite/smoke-test/src/rosetta.rs
Gas estimation fails when there are no user transactions in the last 100k transactions
See attached E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3606)
=> [api/rosetta] Fix gas estimations

developer-docs-site/docs/guides/building-wallet-extension.md
People have been running into problems following this tutorial. We might as well simplify it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3602)
=> Simplify building wallet extension demo

ecosystem/platform/server/app/components/table_component.html.erb, ecosystem/platform/server/app/components/table_header_column_component.rb, ecosystem/platform/server/app/components/table_row_column_component.rb, ecosystem/platform/server/app/components/table_row_component.rb, ecosystem/platform/server/app/javascript/controllers/index.js, ecosystem/platform/server/app/javascript/controllers/table_row_controller.ts, ecosystem/platform/server/app/views/leaderboard/it1.html.erb, ecosystem/platform/server/app/views/leaderboard/it2.html.erb, ecosystem/platform/server/app/views/leaderboard/it3.html.erb
- Update Validator Status / Leaderboard templates to better reflect current styling within Explorer
- Integrate clickable rows controller which will take user to `https://explorer.devnet.aptos.dev/account/0x{metric.validator}?network=ait3`
Review updated styles and ensure clicking of rows takes you to correct route within Explorer. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3595)
=> [CP] Validator Status / Leaderboard clickable rows & styling updates

developer-docs-site/docs/guides/getting-started.md
Fixed a typo "Aptos Exporer" => "Aptos Explorer"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3584)
=> Fixed typo

ecosystem/platform/server/app/components/footer_component.rb, ecosystem/platform/server/app/components/header_component.rb
Update Whitepaper URL within Main / Footer navigation to abstract link
Ensure URL's within Main Navigation (`About -> Whitepaper`) and Footer Navigation (`Whitepaper`) link to: https://aptos.dev/aptos-white-paper/aptos-white-paper-index/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3575)
=> [CP] Update Whitepaper URL to abstract link

ecosystem/platform/server/app/models/it3_profile.rb, ecosystem/platform/server/db/migrate/20220826211507_add_owner_address_to_itprofiles.rb, ecosystem/platform/server/db/migrate/20220826211508_populate_owner_address_on_itprofiles.rb, ecosystem/platform/server/db/schema.rb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3618)
=> [CP] Add owner address to it3 profiles

developer-docs-site/docs/nodes/node-health-checker.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3391)
=> Public port for call api local

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/submission_worker.rs, crates/transaction-emitter-lib/src/lib.rs, crates/transaction-emitter-lib/src/transaction_generator/account_generator.rs, crates/transaction-emitter-lib/src/transaction_generator/mod.rs, crates/transaction-emitter-lib/src/transaction_generator/nft_mint.rs, crates/transaction-emitter-lib/src/transaction_generator/p2p_transaction_generator.rs, crates/transaction-emitter-lib/src/transaction_generator/transaction_mix_generator.rs, crates/transaction-emitter-lib/src/wrappers.rs, testsuite/smoke-test/src/txn_emitter.rs
Add ability to pass a mix of transaction types for txn-emitter to generate load from.
unit test. used on AIT3 testnet. will add forge tests on top
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3488)
=> [txn-emitter] Transaction mix for txn-emitter

.github/workflows/continuous-e2e-compat-test.yaml, .github/workflows/continuous-e2e-performance-test.yaml, .github/workflows/continuous-e2e-state-sync-perf-test.yaml, Cargo.lock, testsuite/forge-cli/src/README.md, testsuite/forge-cli/src/main.rs, testsuite/forge/Cargo.toml, testsuite/forge/src/backend/local/mod.rs, testsuite/forge/src/backend/local/node.rs, testsuite/forge/src/interface/network.rs, testsuite/forge/src/interface/swarm.rs, testsuite/forge/src/success_criteria.rs, testsuite/smoke-test/Cargo.toml, testsuite/smoke-test/src/full_nodes.rs, testsuite/smoke-test/src/smoke_test_environment.rs, testsuite/smoke-test/src/state_sync.rs, testsuite/testcases/src/state_sync_performance.rs
This PR adds a simple state sync performance test and adds fullnode support for local swarms. To achieve this, we: (i) add a new flag for local swarms; (ii) support storage, consensus and state sync file deletion; and (iii) add a simple forge test that creates a swarm, deletes the fullnodes and times how long it takes the nodes to synchronize.
This is a basic starting point. We'll want to add additional state sync tests (e.g., different syncing and failures modes), as well as integrate the tests into our CI/CD pipeline. One step at a time.
Running the test locally, I get:
```
% cargo run -p forge-cli -- --suite "state_sync" --num-validators 4 --num-validator-fullnodes 1 --duration-secs 20 --mempool-backlog 5000 test local-swarm
...
2022-08-24T21:36:58.464658Z [main] INFO …
```
=> [Forge] Add simple state sync performance test and support fullnodes in local swarms.

ecosystem/platform/server/app/controllers/it3_profiles_controller.rb, ecosystem/platform/server/app/controllers/leaderboard_controller.rb, ecosystem/platform/server/app/views/leaderboard/it3.html.erb
- Fix sorting when governance votes includes values with zero denominator.
- Adjust copy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3639)
=> [community] Update leaderboard sorting + copy.

api/src/context.rs, testsuite/smoke-test/src/rest_api.rs
Cherry pick missed commit to fix bug
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3641)
=> [api] Fix gas estimation API when no user transactions occur

ecosystem/typescript/sdk/src/transaction_builder/aptos_types/multi_ed25519.test.ts, ecosystem/typescript/sdk/src/transaction_builder/aptos_types/multi_ed25519.ts
Fixed minor bug with deserialization of Ed25519Signature and MultiEd25519PublicKey and added unit tests for them.
This pr is used instead of #3565 to merge into main branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3635)
=> [sdk][typescript] fix bug of deserialize of MultiEd25519

storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/state_store/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3655)
=> [storage] prune state store usage data

.github/workflows/continuous-e2e-single-vfn-test.yaml
Introduced in #3363 . Run every 12 hours
Manually triggered to see the test succeeds https://github.com/aptos-labs/aptos-core/actions/runs/2930950790
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3493)
=> [forge] turn on run-forge-single-vfn-perf

developer-docs-site/docs/concepts/staking.md, developer-docs-site/docs/nodes/ait/ait3-leaderboard-metrics.md, developer-docs-site/docs/nodes/ait/node-liveness-criteria.md, developer-docs-site/sidebars.js
- Also added in the staking doc a brief explanation of how validation works.
- Cleaned up the node liveness doc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3579)
=> AIT-3 leaderboard metrics doc

developer-docs-site/docs/nodes/ait/ait3-leaderboard-metrics.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3673)
=> Updated the leaderboard link.

CODEOWNERS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3630)
=> [Docs] Sorting CODEOWNERS file.

aptos-move/framework/aptos-framework/sources/stake.move
Currently the pending_active validator needs to wait for the next epoch to be added to the validator set then leave (and wait 1 more epoch to effectively leave)
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3604)
=> [Aptos Framework][Staking] Allow pending active validator to leave validator set directly without waiting for epoch change

ecosystem/platform/server/app/views/leaderboard/it3.html.erb, ecosystem/platform/server/config/routes.rb, ecosystem/platform/server/test/controllers/it3_profiles_controller_test.rb, ecosystem/platform/server/test/controllers/it3s_controller_test.rb
Close registration and show the leaderboard at /it3.
Existing tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3662)
=> [community] Show the IT3 leaderboard at /it3.

execution/executor/src/components/chunk_output.rs, storage/aptosdb/src/state_store/mod.rs, storage/storage-interface/src/cached_state_view.rs
10x state-sync tps on large DB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3611)
=> [cherry-pick][Storage] Use thread pools to make IO operations async. (#3502)

execution/executor/src/block_executor.rs, execution/executor/src/components/block_tree/mod.rs
This PR adds a safety check to ensure the child and parent blocks are correctly related when executed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3670)
=> [Execution] Ensure the child and parent blocks are related.

ecosystem/node-checker/src/server/run.rs
So we can call it from a web UI.
CI. This works in the API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3696)
=> Configure CORS for NHC

crates/aptos-rosetta-cli/src/construction.rs, crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/network.rs, testsuite/smoke-test/src/rosetta.rs
Suggested fee is supposed to be positive, tests are built now around it.
Additionally, some extra checks around the chain id
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3659)
=> [aptos-rosetta] Suggested fee and chain id updates

crates/aptos-rosetta-cli/src/construction.rs, crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/network.rs, testsuite/smoke-test/src/rosetta.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3701)
=> [aptos-rosetta] Cherry pick fixes

ecosystem/platform/server/app/admin/it3_profiles.rb, ecosystem/platform/server/app/controllers/it3_profiles_controller.rb, ecosystem/platform/server/app/controllers/it3s_controller.rb, ecosystem/platform/server/app/controllers/onboarding_controller.rb, ecosystem/platform/server/app/models/it3_profile.rb, ecosystem/platform/server/app/views/it3_profiles/_form.html.erb, ecosystem/platform/server/app/views/layouts/_application.html.erb, ecosystem/platform/server/app/views/static_page/incentivized_testnet.html.erb, ecosystem/platform/server/config/routes.rb, ecosystem/platform/server/db/migrate/20220831174120_add_fullnode_api_port_to_it3_profiles.rb, ecosystem/platform/server/db/schema.rb, ecosystem/platform/server/spec/factories/it3_profiles.rb, ecosystem/platform/server/test/controllers/it3_profiles_controller_test.rb, ecosystem/platform/server/test/controllers/it3s_controller_test.rb
Manual + automated
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3694)
=> [community] Create fullnode-only registration.

developer-docs-site/docs/sdks/typescript-sdk.md
Typo fix: environemnt -> environment
Not req.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3651)
=> [docs] Fixed spelling mistake

developer-docs-site/docs/nodes/full-node/run-a-fullnode-on-gcp.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3720)
=> Update the API server url with /v1

ecosystem/platform/server/app/views/it3_profiles/_form.html.erb, ecosystem/platform/server/spec/factories/it3_profiles.rb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3725)
=> [community] Remove errant whitespace.

crates/aptos-rosetta-cli/src/construction.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
Now adds a test that properly handles all of set operator since that is
now properly stable in the stake modules
Tested manually, as well as with the added test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3715)
=> [aptos-rosetta] Fix block lookup of set operator

consensus/src/block_storage/sync_manager.rs, consensus/src/epoch_manager.rs, consensus/src/experimental/buffer_manager.rs, consensus/src/network_interface.rs
cherry pick monitor/log changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3738)
=> [consensus] cherry pick #3435

crates/aptos-rosetta-cli/src/construction.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
* Fix set operator
* Add failed transaction field
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3743)
=> [aptos-rosetta] Cherry pick fixes for rosetta

consensus/src/block_storage/block_tree.rs, consensus/src/block_storage/sync_manager.rs, consensus/src/epoch_manager.rs, consensus/src/experimental/buffer_item.rs
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3741)
=> Add more monitoring for state sync issue

consensus/src/counters.rs, consensus/src/epoch_manager.rs, consensus/src/network.rs, consensus/src/network_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3747)
=> [consensus] cherry pick #3745

consensus/src/epoch_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3753)
=> [consensus] add more instrumentation

consensus/src/epoch_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3750)
=> [consensus] remove unnecessary async/await

aptos-move/framework/aptos-framework/sources/account.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3761)
=> updated broken move unit test

consensus/src/epoch_manager.rs, consensus/src/round_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3764)
=> [consensus] dedicate channel to shutdown round manager

consensus/src/epoch_manager.rs, consensus/src/experimental/buffer_manager.rs, crates/aptos-telemetry/src/telemetry_log_sender.rs
Due to possible concerns with tokio::select
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3763)
=> tokio select -> futures select

developer-docs-site/docs/nodes/ait/additional-doc.md, developer-docs-site/docs/nodes/ait/connect-to-testnet.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3718)
=> Adding a note on max gas in the doc

consensus/src/epoch_manager.rs, consensus/src/experimental/buffer_manager.rs, crates/aptos-telemetry/src/telemetry_log_sender.rs
Due to possible concerns with tokio::select
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3783)
=> [cherry-pick] tokio select -> futures select (#3763)

consensus/src/counters.rs, consensus/src/network.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3788)
=> [consensus] swap aptos channel with futures channel

Cargo.lock, crates/aptos/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3790)
=> [aptos-cli] Bump version to 0.3.3

consensus/src/counters.rs, consensus/src/network.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3800)
=> Revert "[consensus] swap aptos channel with futures channel"

crates/transaction-emitter-lib/src/cluster.rs
running against AIT3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3748)
=> [txn-emitter] Filter bad/stale clients

storage/aptosdb/src/backup/restore_handler.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/schema/db_metadata/mod.rs, storage/aptosdb/src/state_restore/mod.rs, storage/aptosdb/src/state_restore/restore_test.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/jellyfish-merkle/src/lib.rs, storage/jellyfish-merkle/src/restore/mod.rs, storage/jellyfish-merkle/src/test_helper.rs
as title
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3647)
=> [storage] move state_restore structs to aptos_db

consensus/src/block_storage/sync_manager.rs, consensus/src/experimental/buffer_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3825)
=> [consensus] dial down retry frequencies

consensus/src/epoch_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3826)
=> [consensus] split select into multiple tasks

Cargo.lock, consensus/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3828)
=> tokio: 1.19.2 -> 1.18.2, tokio-util: 0.7.3 -> 0.7.2

config/src/config/consensus_config.rs, consensus/src/epoch_manager.rs
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3829)
=> [epoch_manager] Panic on stuck, so node can restart

aptos-node/src/lib.rs, consensus/src/consensus_provider.rs
This PR spawns the network consensus task on a separate runtime.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3842)
=> [Consensus] Add a separate runtime for network consensus message handling.

execution/executor/src/chunk_executor.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3688)
=> [executor] commit_chunk panics if error is hit after writing to DB

consensus/src/epoch_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3852)
=> [consensus] not proactively rely with EpochChangeProof

crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/types/objects.rs
* All errors need to return as 500s
* Make signature type optional in signing payload (even though I always set it)
* 
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3820)
=> [aptos-rosetta] More rosetta adjustments

consensus/src/epoch_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3857)
=> revert back to use select

terraform/fullnode/aws/variables.tf, terraform/fullnode/digital_ocean/variables.tf, terraform/fullnode/gcp/variables.tf, terraform/fullnode/vultr/variables.tf, terraform/helm/fullnode/values.yaml
Update fullnode resource requirement to match with validator so that they can catch up when the network is loaded 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3856)
=> [fullnode] update fullnode requirement

consensus/src/epoch_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3853)
=> [consensus] not proactively reply epoch change proof

ecosystem/platform/server/app/components/claim_nft_button_component.html.erb, ecosystem/platform/server/app/components/claim_nft_button_component.rb, ecosystem/platform/server/app/components/connect_wallet_button_component.html.erb, ecosystem/platform/server/app/components/connect_wallet_button_component.rb, ecosystem/platform/server/app/controllers/nft_offers_controller.rb, ecosystem/platform/server/app/controllers/wallets_controller.rb, ecosystem/platform/server/app/javascript/controllers/application.ts, ecosystem/platform/server/app/javascript/controllers/claim_nft_controller.ts, ecosystem/platform/server/app/javascript/controllers/connect_wallet_controller.ts, ecosystem/platform/server/app/javascript/controllers/index.js, ecosystem/platform/server/app/models/nft_offer.rb, ecosystem/platform/server/app/models/wallet.rb, ecosystem/platform/server/app/services/nft_claimer.rb, ecosystem/platform/server/app/services/wallet_creator.rb, ecosystem/platform/server/app/views/nft_offers/show.html.erb, ecosystem/platform/server/app/views/static_page/community.html.erb, ecosystem/platform/server/app/views/static_page/incentivized_testnet.html.erb, ecosystem/platform/server/config/routes.rb, ecosystem/platform/server/db/migrate/20220903154019_drop_nft_tables.rb, ecosystem/platform/server/db/schema.rb, ecosystem/platform/server/spec/factories/wallets.rb, ecosystem/platform/server/test/controllers/wallets_controller_test.rb, ecosystem/platform/server/test/services/wallet_creator_test.rb
Sign in works; connect wallet and claim nft does not yet work.
n.b. I fixed some unclosed tags on the community/incentivized testnet pages. I suggest viewing the diff without whitespace changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3827)
=> [community] Create "Claim NFT" page.

ecosystem/platform/server/app/javascript/controllers/application.ts, ecosystem/platform/server/app/javascript/controllers/connect_wallet_controller.ts, ecosystem/platform/server/app/services/wallet_creator.rb, ecosystem/platform/server/test/controllers/wallets_controller_test.rb, ecosystem/platform/server/test/services/wallet_creator_test.rb
Uses the aptos wallet signMessage() function to generate a signature.
Manual + automated
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3863)
=> [community] Implement wallet signature verification.

ecosystem/platform/server/app/javascript/controllers/application.ts, ecosystem/platform/server/app/javascript/controllers/claim_nft_controller.ts
Adjusts arguments so that the Claim NFT button works correctly.
Tested manually. https://explorer.devnet.aptos.dev/txn/63744011
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3864)
=> [community] Adjust transaction to match module expectations.

execution/executor/src/block_executor.rs
Add an assertion to verify that the last block id matches the block id to commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3690)
=> [Execution] Add simple check to commit_blocks_ext.

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/e2e-move-tests/tests/init_module.rs
Closes #3573
Added test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3880)
=> [move-vm] Call init_module only the first time a module is ever published

ecosystem/typescript/sdk/src/transaction_builder/builder.ts
Needed for parsing type tags in external libraries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3839)
=> sdk: Export TypeTagParser

crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/types/objects.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3886)
=> Cherry pick rosetta changes to testnet

crates/aptos/src/governance/mod.rs, crates/aptos/src/test/mod.rs, crates/aptos/src/test/tests.rs
Now the governance tooling doesn't crash because of duplicate input parameters
Added a test that ensures that at least input parameters are parsable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3901)
=> [aptos-cli] Fix governance tooling

developer-docs-site/docs/nodes/full-node/network-identity-fullnode.md
Updated docs for https://github.com/aptos-labs/aptos-core/pull/3885.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3899)
=> [Docs] CLI command update for extracting the peer.

testsuite/forge/src/test_utils/consensus_utils.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3902)
=> [forge] fix consensus stress test check

terraform/fullnode/aws/backup.tf, terraform/fullnode/aws/main.tf, terraform/fullnode/aws/variables.tf, terraform/modules/eks/cluster.tf, terraform/modules/eks/variables.tf
create all resources needed to host a backup on aws fullnode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3882)
=> [aws] add backup support

terraform/aptos-node/azure/kubernetes.tf, terraform/aptos-node/gcp/kubernetes.tf
fullnode also need ssd to be performant and being able to catch up with validators. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3916)
=> [tf] make fullnode to also use ssd

aptos-node/src/lib.rs
Closes https://github.com/aptos-labs/aptos-core/issues/3628
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3819)
=> [aptos-node] Fix aptosnet endpoint println

crates/aptos-push-metrics/src/lib.rs, storage/aptosdb/src/state_merkle_db.rs, storage/aptosdb/src/state_restore/mod.rs, storage/aptosdb/src/state_store/mod.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs, storage/backup/backup-cli/src/backup_types/transaction/restore.rs, storage/backup/backup-cli/src/metadata/cache.rs, storage/backup/backup-cli/src/metrics/mod.rs
i.e. prefetch state chunks so add_chunk() can be called continously
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3924)
=> [backup] pipeline downloading state snapshot chunks

crates/aptos/src/node/analyze/analyze_validators.rs, crates/aptos/src/node/analyze/fetch_metadata.rs
cargo run -p aptos -- node analyze-validator-performance --analyze-mode=all --url=https://ait3.aptosdev.com --start-epoch=54 --end-epoch=57
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3813)
=> [cli] Fix analyze validators fetching, when we hit 1000 limit for API

ecosystem/node-checker/src/evaluators/direct/api/transaction_availability.rs
https://github.com/aptos-labs/aptos-core/issues/3913.
Run local NHC:
```
cargo run -p aptos-node-checker -- server run --baseline-node-config-paths ~/a/internal-ops/infra/apps/node-checker/configs/* --listen-address 0.0.0.0
```
Hit NHC (comparing the node to itself):
```
curl 'http://127.0.0.1:20121/check_node?node_url=http://34.64.49.220/&baseline_configuration_name=ait3_fullnode&metrics_port=9101&api_port=80&noise_port=6182&public_key=0x44fd1324c66371b4788af0b901c9eb8088781acb29e6b8b9c791d5d9838fbe1f' | jq .
```
Output:
```
{
"headline": "Target node produced valid recent transaction",
"score": 100,
"explanation": "We were able to pull the same transaction (version: 164409742) from both your node and the baseline node. Great! This implies that your node is keeping up with other nodes in …
```
=> [NHC] Use transaction from middle of available version range in API availabilty checker

ecosystem/platform/server/db/seeds.rb
Remove old and unused seed account
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3935)
=> [CP] Remove old and unused seed account

ecosystem/platform/server/app/components/claim_nft_button_component.rb, ecosystem/platform/server/app/controllers/nft_offers_controller.rb, ecosystem/platform/server/app/javascript/controllers/application.ts, ecosystem/platform/server/app/javascript/controllers/claim_nft_controller.ts, ecosystem/platform/server/app/javascript/controllers/index.js, ecosystem/platform/server/app/javascript/controllers/minted_nft_controller.ts, ecosystem/platform/server/app/models/nft_offer.rb, ecosystem/platform/server/app/views/nft_offers/minted.html.erb
Adds a "success" page to the nft flow.
Manual
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3933)
=> [community] Add "minted nft" page.

.github/workflows/forge-unittests.yaml, .github/workflows/lint-test.yaml, .github/workflows/run-forge.yaml, testsuite/fixtures/testMain.fixture, testsuite/forge.py
Print the dashboard link for the run after finishing even when running locally
Also move the debugging output above the summary since its very confusing to
see debugging output instead of result.
Also fix some string interpolation bugs :P
Test Plan: run locally, see the dashboard link :D
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3941)
=> [forge] Print dashboard link after running

execution/executor-types/src/lib.rs, execution/executor/src/chunk_executor.rs, execution/executor/src/fuzzing.rs, execution/executor/src/tests/chunk_executor_tests.rs, execution/executor/src/tests/mod.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, testsuite/aptos-fuzzer/src/fuzz_targets.rs, testsuite/aptos-fuzzer/src/fuzz_targets/executor.rs
used only by SSv1, which is deleted. clean up too.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3625)
=> [executor] clean up execute/apply_and_commit_chunk

consensus/src/counters.rs, consensus/src/network.rs, consensus/src/network_interface.rs
This will be useful to understand the breakdown of different messages and see if there is room for optimization to reduce the volume of consensus messages. 
Existing UT.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3900)
=> [Consensus] Add counters for consensus messages by type

Cargo.lock, api/src/runtime.rs, aptos-move/parallel-executor/src/executor.rs, aptos-node/Cargo.toml, aptos-node/src/lib.rs, consensus/src/consensus_provider.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-telemetry/src/service.rs, crates/inspection-service/src/inspection_service.rs, mempool/src/shared_mempool/runtime.rs, state-sync/state-sync-v2/state-sync-driver/src/driver_factory.rs, storage/aptosdb/src/state_store/buffered_state.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_snapshot_committer.rs, storage/backup/backup-service/src/lib.rs, storage/jellyfish-merkle/src/lib.rs
Add a number when possible, and also make the name shorter to avoid being truncated (there is a 15 bytes limit).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3897)
=> Better thread name.

crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
There were a lot of if 1,2,3, and I've collapsed it down to match statements using string matching.  It's just about the same with a lot less code complexity
This is needed to add staking and other commands to Rosetta
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3957)
=> [aptos-rosetta] Consolidate and simplify Rosetta conditionals

consensus/consensus-types/src/block_retrieval.rs, consensus/src/block_storage/sync_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3954)
=> [consensus] limit maximum block retrieval retry to 5

storage/aptosdb/src/pruner/event_store/test.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
There might be some cases when the progress is not populated (e.g. fast sync, maybe more in the future).
Ledger pruner thread doesn't quit on my node for ait3 after this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3949)
=> [Fix] Do a db seek when initializing ledger pruner.

aptos-move/move-examples/moon_coin/Move.toml, aptos-move/move-examples/moon_coin/sources/MoonCoin.move, aptos-move/move-examples/moon_coin/sources/MoonCoinType.move, developer-docs-site/docs/tutorials/first-coin.md, developer-docs-site/docs/tutorials/index.md, developer-docs-site/sidebars.js, ecosystem/python/sdk/aptos_sdk/client.py, ecosystem/python/sdk/aptos_sdk/transactions.py, ecosystem/python/sdk/examples/your-coin.py
refresh the moon coin tutorial
update python to support it
leverage `init_module`
reformatted
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3925)
=> [examples] update moon coin tutorial

storage/aptosdb/src/lib.rs
1 line msg
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3425)
=> [storage] fix ensure msg

storage/aptosdb/src/pruner/event_store/test.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3976)
=> [CP][Fix] Do a db seek when initializing ledger pruner. (#3949)

storage/aptosdb/src/lib.rs
we have landed #3942 but the garbage data is still there.
Will revert it later
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3956)
=> [storage][temporary fix] delete garbage stale value index data for AIT3

storage/backup/backup-service/src/lib.rs
https://github.com/aptos-labs/aptos-core/pull/3858/commits/9c940dc681ccc7b1aca459875e9a8fc39d24f2b1 made behavior change (error is now caught)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3973)
=> [backup] fix routing_and_error_codes

storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/state_store/mod.rs
#3942 #3956 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3981)
=> [fix] prune stale state value index (#3942)

aptos-move/framework/aptos-framework/sources/aptos_governance.move, aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/aptos-framework/sources/transaction_validation.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3952)
=> Prepare for LLT

.github/workflows/docker-build-test.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3992)
=> [GHA] build image for testnet-stable

storage/storage-interface/src/async_proof_fetcher.rs, storage/storage-interface/src/cached_state_view.rs, storage/storage-interface/src/proof_fetcher.rs, storage/storage-interface/src/sync_proof_fetcher.rs, types/src/proof/definition.rs
Add back proof verification.
Existing UT + manual test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3022)
=> [Storage] Verify proof.

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3998)
=> chore: bump up TS SDK version

storage/aptosdb/src/pruner/transaction_store/test.rs
Was removed in https://github.com/aptos-labs/aptos-core/pull/3949 because the event and transaction versions are not synced in UTs. Move it to transaction store test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3984)
=> [Storage] Add back the test for min_readable_version.

developer-docs-site/docs/guides/building-your-own-wallet.md, developer-docs-site/docs/guides/index.md, developer-docs-site/sidebars.js
There has been a need to make these things official. This will be a living doc. Need help from @chloeqjz @jjleng for the key rotation integration.
`yarn start` developer docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3869)
=> Add guide for building your own wallet

aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/framework/aptos-framework/sources/stake.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4006)
=> Fix an issue with initializing stake pool during genesis

ecosystem/typescript/sdk/src/aptos_client.ts
Adopt the new Move function for key rotation. Although the new Move function support rotation for multied25519, this PR only supports ed25519 scheme. multied25519 support will be added in another PR.
Make sure tests still pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4001)
=> feat(ts-sdk): adopt the new Move function for key rotation

Cargo.lock, Cargo.toml, crates/aptos-compression/Cargo.toml, storage/rocksdb-options/Cargo.toml, storage/schemadb/Cargo.toml
now that lz4 upgraded with our desired change, and is depended on by our rust-rocksdb patch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4004)
=> unpatch lz4

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/examples/typescript/bcs_transaction.ts, ecosystem/typescript/sdk/examples/typescript/multisig_transaction.ts, ecosystem/typescript/sdk/package.json, ecosystem/typescript/sdk/src/aptos_client.ts, ecosystem/typescript/sdk/src/coin_client.test.ts, ecosystem/typescript/sdk/src/transaction_builder/bcs/consts.ts, ecosystem/typescript/sdk/src/transaction_builder/bcs/deserializer.test.ts, ecosystem/typescript/sdk/src/transaction_builder/bcs/deserializer.ts, ecosystem/typescript/sdk/src/transaction_builder/bcs/helper.test.ts, ecosystem/typescript/sdk/src/transaction_builder/bcs/serializer.test.ts, ecosystem/typescript/sdk/src/transaction_builder/bcs/serializer.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts, ecosystem/typescript/sdk/src/transaction_builder/builder_utils.test.ts, ecosystem/typescript/sdk/src/transaction_builder/transaction_builder.test.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4013)
=> Cherry pick for TS SDK 1.3.12

ecosystem/typescript/sdk/src/generated/core/AxiosHttpRequest.ts, ecosystem/typescript/sdk/src/generated/core/request.ts
regenerate openapi client
yarn test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4019)
=> chore: regenerate openapi client

ecosystem/typescript/sdk/src/generated/core/AxiosHttpRequest.ts, ecosystem/typescript/sdk/src/generated/core/request.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4020)
=> cherry-pick chore: regenerate open api client

LICENSE, network/README.md, network/src/protocols/wire/messaging/v1/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3877)
=> [Docs] Fix docs's link bugs.

aptos-move/framework/aptos-framework/sources/account.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3996)
=> [Aptos Framework] [Account] emit event upon key rotation

developer-docs-site/docs/tutorials/first-move-module.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4032)
=> [docs] Fix typos in first-move-module.md.

ecosystem/platform/server/app/controllers/nft_images_controller.rb, ecosystem/platform/server/app/controllers/nft_offers_controller.rb, ecosystem/platform/server/app/javascript/controllers/minted_nft_controller.ts, ecosystem/platform/server/app/models/nft_image.rb, ecosystem/platform/server/app/models/nft_offer.rb, ecosystem/platform/server/app/views/nft_offers/minted.html.erb, ecosystem/platform/server/config/routes.rb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4033)
=> [CP] Shorten NFT URL

.github/workflows/continuous-e2e-changing-working-quorum-test copy.yaml, .github/workflows/continuous-e2e-changing-working-quorum-test-high-load.yaml, .github/workflows/continuous-e2e-different-node-speed-and-reliability-test.yaml, Cargo.lock, aptos-move/aptos-vm/src/aptos_vm.rs, testsuite/forge-cli/src/main.rs, testsuite/forge/Cargo.toml, testsuite/forge/src/runner.rs, testsuite/forge/src/test_utils/consensus_utils.rs, testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs, testsuite/testcases/Cargo.toml, testsuite/testcases/src/consensus_reliability_tests.rs, testsuite/testcases/src/continuous_progress_test.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/tests/forge-local-compatibility.rs, testsuite/testcases/tests/forge-local-performance.rs
added 3 continuous tests for consensus reliability
tuning params in stacked PRs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3958)
=> [forge] Add Consensus reliability tests

crates/aptos-faucet/src/mint.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4044)
=> [faucet] expose response error

storage/aptosdb/src/state_restore/mod.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs
35k items per second to about 60k 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4040)
=> [backup] add_chunk concurrently to the kv store and the jmt store

ecosystem/platform/server/app/components/connect_wallet_button_component.html.erb, ecosystem/platform/server/app/components/connect_wallet_button_component.rb, ecosystem/platform/server/app/controllers/wallets_controller.rb, ecosystem/platform/server/app/javascript/controllers/connect_wallet_controller.ts
Prompts the user to select which wallet they have installed before connecting.
This also fixes the rendering of server-side errors when connecting the wallet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4046)
=> [community] Add a "Select Wallet" dialog.

developer-docs-site/docs/tutorials/first-coin.md, ecosystem/python/sdk/examples/your-coin.py, ecosystem/typescript/sdk/examples/typescript/package.json, ecosystem/typescript/sdk/examples/typescript/yarn.lock, ecosystem/typescript/sdk/examples/typescript/your_coin.ts
Add the first coin example for TS. 
Build a local SDK and verified manually
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4011)
=> [doc] first coin example for TS

crates/aptos/src/node/mod.rs, crates/aptos/src/test/mod.rs, testsuite/smoke-test/src/aptos_cli/validator.rs, types/src/on_chain_config/validator_set.rs
Before it didn't print network addresses, now it prints network addresses properly
```
aptos node show-validator-set                
{
"Result": {
"scheme": "BLS12381",
"active_validators": [
{
"account_address": "c2365fd303b4473729a59d02f60f3747e8dd7ecdb25351fde1e52865e8d81a85",
"consensus_voting_power": 100015982794673,
"config": {
"consensus_public_key": "0xb7b923559545c113d06a4ff29c258e595d740191e21be0fcb067eb25635d6a455f1544caaae38e7532f93201b9add6b7",
"validator_network_addresses": [
"/dns/dev-aptos-node-24-validator-lb/tcp/6180/noise-ik/0xabd5f52d87cfb33689abb17e6cbf2a41964943f0d85d81fac75ebdda36b35638/handshake/0"
],
"fullnode_network_addresses": [
"/dns/fullnode24.devnet.aptoslabs.com/tcp/6182/noise-ik/0x5fa7dc900f85384ff4133b00f6056da93b6ccd9981514fe33a648e2468189f65/handshake/0" …
```
=> [aptos-cli] Fix validator config and validator set CLI commands

terraform/helm/testnet-addons/templates/loadtest.yaml
txn emitter takes either target-tps or mempool-backlog
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4059)
=> [helm][testnet-addons] fix loadtest with optional args

developer-docs-site/docs/concepts/basics-node-networks-sync.md, developer-docs-site/docs/concepts/state-sync.md, developer-docs-site/sidebars.js
I will add a diagram for the state sync architecture later on. I still haven't got it entirely correct. Diagram not a blocker for landing this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3920)
=> [Docs] State sync doc.

Cargo.lock, crates/transaction-emitter-lib/src/cluster.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/lib.rs, testsuite/forge-cli/src/main.rs, testsuite/forge/src/interface/swarm.rs, testsuite/testcases/Cargo.toml, testsuite/testcases/src/lib.rs, testsuite/testcases/src/load_vs_perf_benchmark.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3945)
=> [forge] load vs perf benchmark

developer-docs-site/docs/guides/getting-started.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4072)
=> [docs] share testnet info

Cargo.lock, aptos-move/aptos-gas/src/transaction.rs, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/adapter_common.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/lib.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/framework/aptos-framework/sources/aptos_governance.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, crates/aptos/src/governance/mod.rs, types/src/account_view.rs, types/src/on_chain_config/approved_execution_hashes.rs, types/src/on_chain_config/mod.rs
* Set max txn size to 32KB
* Add a method to trigger that a proposal has been approved -- both optimistically and via entry function
* Add a parser for approved execution hashes
* Cleanup something that as bothering me in on_chain_configs
* Fix a CLI issue where groups were added without validation
* Bypass transaction size for any approved governance transaction (either optimistically or as a result of the explicit check)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3966)
=> large governance transaction bypass

storage/aptosdb/src/aptosdb_test.rs
it's known tests relying on prometheus metrcis will be flaky. We kinda have high confidence that these work and it's not critical if they don't either.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4060)
=> [storage] remove flaky test

developer-docs-site/docs/tutorials/first-dapp.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4069)
=> Your First Dapp spelling error

developer-docs-site/docs/tutorials/first-coin.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4071)
=> Your First Coin Spelling Error

storage/aptosdb/src/pruner/db_pruner.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
The put fails in readonly mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4075)
=> [storage] fix that pruner initialization can hang in read only mode

storage/aptosdb/src/backup/restore_handler.rs, storage/aptosdb/src/state_restore/mod.rs, storage/aptosdb/src/state_restore/restore_test.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/jellyfish-merkle/src/lib.rs, storage/jellyfish-merkle/src/restore/mod.rs
~50k items per second -> ~80k items per second
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4058)
=> [backup] async committing state snapshot chunks

storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs
so multiple cores can be utilized
~80k -> ~115k
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4091)
=> [backup] state snapshot restore: deserialize in seperate task

developer-docs-site/docs/concepts/staking.md
Fixed the staking doc by removing obsolete behavior. Thanks for the prod, @wintertoro!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3914)
=> [Docs] Updating the staking doc.

api/types/src/block.rs, crates/aptos-rest-client/src/lib.rs, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/block.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/main.rs, crates/aptos-rosetta/src/types/identifiers.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs, types/src/stake_pool.rs
BCS is more performant, and this removes some bugs and complexity related to the current rosetta compatibility.
Additionally, fixes a bug in the BCS block API
Tested against a local running node, and it works great
```
cargo run -p aptos-rosetta -- online --chain-id testnet --config ~/testnet-node/fullnode.yaml
```
```
./target/debug/aptos-rosetta-cli block get --block-index 294514 --chain-id testnet
{
"block": {
"index": 294514,
"hash": "testnet-294514"
},
"parent_block_identifier": {
"index": 294513,
"hash": "testnet-294513"
},
"timestamp": 1662778516096,
"transactions": [
{
"transaction_identifier": {
"hash": "43c38260e0d6b571754d989e0a87e78ab70444f0a2806edc8ad02fcbb9ad57fc"
},
"operations": [],
"metadata": {
"transaction_type": "BlockMetadata",
"version": …
```
=> [aptos-rosetta] Move rosetta testnet to bcs

Cargo.lock, crates/aptos/Cargo.toml
Update for the next release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4106)
=> [aptos-cli] Bump version to 0.3.4

.github/workflows/continuous-e2e-changing-working-quorum-test copy.yaml, .github/workflows/continuous-e2e-changing-working-quorum-test-high-load.yaml, .github/workflows/continuous-e2e-different-node-speed-and-reliability-test.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4109)
=> [forge] Fix forge tests removing USE_NEW_WRAPPER

aptos-move/framework/aptos-token/sources/token.move
when maximal is 0, assume user don't want to track supply 
The benefit is that txns of creating NFT under the same collection or mint tokens can be parallel as they don't have to modify a shared counter. 
CICD
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3906)
=> [Token] unblock token creation from parallel execution

developer-docs-site/docs/nodes/full-node/bootstrap-fullnode.md, developer-docs-site/docs/nodes/full-node/index.md, developer-docs-site/sidebars.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4107)
=> [doc] add restore doc

developer-docs-site/docs/concepts/staking.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4111)
=> Restoring the note on an owner can extend the lockup period.

crates/aptos-rosetta/src/account.rs, types/src/account_config/resources/coin_info.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4126)
=> Cherry pick rosetta fix for account balance with different coins

Cargo.lock, crates/aptos-faucet-cli/Cargo.toml, crates/aptos-keygen/Cargo.toml, crates/aptos-keygen/src/main.rs, crates/aptos-network-checker/Cargo.toml, crates/aptos-openapi/Cargo.toml, crates/aptos-protos/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4115)
=> [deps] Remove more dependencies

developer-docs-site/docs/concepts/state-sync.md
Fixing the errors identified in https://github.com/aptos-labs/aptos-core/pull/3920
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4117)
=> [Docs] Fixing state sync doc.

ecosystem/platform/server/app/javascript/controllers/claim_nft_controller.ts
I'm trying to get to the bottom of why our number 1 error continues to be "Unauthorized" and I think this is causing noise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4120)
=> Don't sentry on redirect

terraform/helm/fullnode/values.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4101)
=> [helm] add testnet link

developer-docs-site/docs/guides/move-guides/upgrading-move-code.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4133)
=> upgrading move code spelling error
