aptos-labs/aptos-core

mempool/README.md
Just a small documentation fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4102)
=> Correctly link specification for mempool

docker/compose/data-restore/docker-compose.yaml, docker/compose/data-restore/gcs.yaml, docker/compose/data-restore/s3.yaml
Update data-restore docker compose to add gcs support
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3876)
=> [docker] update restore docker compose

network/memsocket/src/lib.rs
This PR offers some small readability fixes to the memsocket code (based on feedback). Note: this code is only used for testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4134)
=> [Network] Small readability fixes to memsocket.

aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs, consensus/src/block_storage/block_store.rs, consensus/src/block_storage/sync_manager.rs, consensus/src/counters.rs, consensus/src/experimental/buffer_manager.rs, consensus/src/persistent_liveness_storage.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4055)
=> [consensus] small cleanup 

Cargo.toml
as we agreed offline
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4158)
=> enable overflow-checks for performance build

Cargo.lock, crates/aptos-rosetta/Cargo.toml, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/block.rs, crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/error.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
The coin cache will keep track of currencies that it sees and ensure that they are converted to rosetta types.
```
$ target/debug/aptos-rosetta-cli block get --chain-id testnet --block-index 242581
{
"block": {
"index": 242581,
"hash": "testnet-242581"
},
"parent_block_identifier": {
"index": 242580,
"hash": "testnet-242580"
},
"timestamp": 1662772816745,
"transactions": [
{
"transaction_identifier": {
"hash": "2ebdcf139dc795d69135bc30e3f12592a56a8e7da3428162603a4e1d5b69bd84"
},
"operations": [],
"metadata": {
"transaction_type": "BlockMetadata",
"version": "562684",
"failed": false,
"vm_status": "Success"
}
},
{
"transaction_identifier": {
"hash": "e79c73d467882d5587f53bd74f0d5a02b5eee481d903301057f0fa2656fcf006"
},
"operations": [
{
"operation_identifier": { …
```
=> [aptos-rosetta] Use coin cache for all interactions

Cargo.lock, crates/aptos-rosetta/Cargo.toml, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/block.rs, crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/error.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4164)
=> Cherry pick coin cache

consensus/src/block_storage/tracing.rs, consensus/src/epoch_manager.rs, consensus/src/network.rs, consensus/src/round_manager.rs
This will help figure out if certain channels/threads in consensus is the bottleneck or just sending the proposal over the wire takes time. 
Existing UT
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4160)
=> [Consensus] Add tracing for proposal receiving

storage/scratchpad/src/sparse_merkle/mod.rs
auditing result
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4156)
=> trivial: fix a unused variable

.github/workflows/prover-test.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4168)
=> [gha] Stop running prover command until its fixed

state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-v2/state-sync-driver/src/error.rs, state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
This PR offers some small readability fixes and improvements to the state sync code. Nothing changes logically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4104)
=> [State Sync] Small cleanups to readability.

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
- Removed version #s in the help output.
- Clarified the local vs global configuration near the `aptos init` section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4169)
=> [Docs] Editorial cleanup and clarified configuration section.

ecosystem/platform/server/app/components/connect_wallet_button_component.html.erb, ecosystem/platform/server/app/javascript/controllers/connect_wallet_controller.ts
Remove old wallet.persisted? / onPageLoad logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3997)
=> [community] Remove old wallet.persisted? / onPageLoad logic.

Cargo.lock, Cargo.toml, docker/compose/aptos-node/blocked.ips, docker/compose/aptos-node/docker-compose.yaml, docker/compose/aptos-node/haproxy.cfg, terraform/helm/aptos-node/files/haproxy.cfg, terraform/helm/aptos-node/values.yaml, testsuite/dos/README, testsuite/dos/listener/Cargo.toml, testsuite/dos/listener/src/main.rs, testsuite/dos/sender/Cargo.toml, testsuite/dos/sender/src/main.rs
- test specific scenarios for 
- whitelisted IPs.
- Blacklisted IPs.
- Connection Rate Limit.
- BW Rate limit 
- Run forge with FORGE_ENABLE_HA_PROXY=true
- 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3779)
=> Haproxy bisect

Cargo.lock, crates/aptos-rosetta/Cargo.toml, crates/aptos-rosetta/src/types/objects.rs
The code was assuming there was only one event per event stream in a transaction.  This fixes it
E2E tests and
https://explorer.devnet.aptos.dev/txn/3639584?network=testnet
```
cargo run -p aptos-rosetta-cli -- block get --chain-id testnet --block-index 1405122
Finished dev [unoptimized + debuginfo] target(s) in 0.57s
Running `target/debug/aptos-rosetta-cli block get --chain-id testnet --block-index 1405122`
{
"block": {
"index": 1405122,
"hash": "testnet-1405122"
},
"parent_block_identifier": {
"index": 1405121,
"hash": "testnet-1405121"
},
"timestamp": 1662880135763,
"transactions": [
{
"transaction_identifier": {
"hash": "155ba2c8d21e46a66cf72e35e72731322a2f8e865b093cb81f9a5d64a3652d92"
},
"operations": [],
"metadata": {
"transaction_type": "BlockMetadata", …
```
=> [aptos-rosetta] Allow for multiple events in one transaction

ecosystem/platform/server/app/views/layouts/_application.html.erb, ecosystem/platform/server/app/views/layouts/_google_analytics.html.erb
Before
```
gtag('config', "&quot;G-CWW2TW4HSD&quot;", {"debug_mode":true});
```
After
```
gtag('config', "G-CWW2TW4HSD", {"debug_mode":true});
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4025)
=> [community] Fix GA ID interpolation.

ecosystem/platform/server/Gemfile, ecosystem/platform/server/Gemfile.lock, ecosystem/platform/server/app/components/project_card_component.rb, ecosystem/platform/server/app/controllers/projects_controller.rb, ecosystem/platform/server/app/models/project.rb, ecosystem/platform/server/test/controllers/projects_controller_test.rb
Adds support for searching projects, using the `pg_search` gem. The query it produces is unoptimized for now - we will need to add a generated column for the tsvector once we have more data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4200)
=> [community] Add support for searching projects.

Cargo.lock, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, state-sync/storage-service/server/src/tests.rs, storage/aptosdb/src/lib.rs, storage/storage-interface/src/lib.rs, storage/storage-interface/src/mock.rs
unused
audit result
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4157)
=> [storage] remove DbReader::get_latest_state_value

ecosystem/platform/server/config/application.rb
We don't need to analyze images. In some cases the analysis was producing errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4197)
=> [community] Disable activestorage analysis.

aptos-move/framework/aptos-framework/sources/stake.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4220)
=> [framework] add acl for testnet validators

developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md, developer-docs-site/package.json, developer-docs-site/yarn.lock
Ignore the yarn stuff, that's just Docusaurus updates. 
Cleaning up the Using Aptos CLI doc in a separate PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4162)
=> [Docs] Editorial pass at installing CLI.

developer-docs-site/docs/guides/index.md, developer-docs-site/docs/guides/running-a-local-multi-node-network.md, developer-docs-site/docs/whats-new-in-docs.md, developer-docs-site/sidebars.js
Port of this README: https://github.com/aptos-labs/aptos-core/pull/3730
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4141)
=> Forge CLI doc for running multiple validators and VFN locally

developer-docs-site/docs/nodes/ait/node-requirements.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4159)
=> Update hardware requirements.

ecosystem/platform/server/app/javascript/controllers/claim_nft_controller.ts, ecosystem/platform/server/app/javascript/controllers/minted_nft_controller.ts, ecosystem/platform/server/package.json, ecosystem/platform/server/yarn.lock
`yarn upgrade --latest`
Ran linter + spot-checked the site.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4234)
=> [community] Upgrade JS deps to latest versions.

terraform/helm/genesis/files/genesis.sh
https://github.com/aptos-labs/aptos-core/pull/4042/files was auto committed before the final comments were addressed
local forge tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4205)
=> [forge] Address comments of pull/4042

aptos-move/framework/aptos-framework/sources/coin.move, aptos-move/framework/aptos-token/sources/property_map.move, aptos-move/framework/aptos-token/sources/token.move
without limits, people could do some very silly things on fields that ultimately act as the primary key
existing tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4225)
=> [AF] Add limits to strings in core contracts

.github/workflows/codeql-analysis.yaml
This is just the autogenerated workflow file, with some changes to the schedule and languages (removed go). I also renamed from yml to yaml.
We can configure this further down the line.
Ran it in my fork, it worked and found some issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4235)
=> Enable CodeQL scanning

consensus/src/experimental/buffer_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4243)
=> [consensus] fix the counter in reset

crates/aptos-rosetta/src/block.rs, crates/aptos-rosetta/src/common.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/main.rs, crates/aptos-rosetta/src/network.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
This is no longer needed, it was an experiment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4240)
=> Revert rosetta synthetic blocks

ecosystem/platform/server/app/controllers/nft_offers_controller.rb
Require email confirmation before NFT minting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4248)
=> [community] Require email confirmation before minting.

storage/aptosdb/src/event_store/mod.rs, storage/aptosdb/src/ledger_store/mod.rs, storage/aptosdb/src/transaction_store/iterators.rs, storage/aptosdb/src/transaction_store/mod.rs, storage/schemadb/src/iterator.rs, storage/schemadb/src/lib.rs, storage/schemadb/tests/iterator.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4216)
=> [storage] add get_write_set_iterator

aptos-move/framework/aptos-token/sources/property_map.move, aptos-move/framework/aptos-token/sources/token.move, aptos-move/framework/aptos-token/sources/token_coin_swap.move, aptos-move/framework/aptos-token/sources/token_transfers.move
1. address a bug that property map can grow more than the limit
2. add explanation to error code 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4237)
=> [Token][1/2] add comment and assert property_map length when initializing

developer-docs-site/docs/nodes/ait/additional-doc.md, developer-docs-site/docs/nodes/ait/connect-to-testnet.md, developer-docs-site/docs/nodes/ait/node-requirements.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4254)
=> [doc] update AIT3 to LLT

Cargo.lock, api/Cargo.toml, api/src/context.rs, testsuite/smoke-test/src/rest_api.rs
Gas estimation floor should be based on the gas schedule directly. Now it pulls properly.
E2E tests, my computer keeps crashing with a lld error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4247)
=> [api] Fix gas estimation floor value

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/framework/aptos-framework/sources/configs/gas_schedule.move, aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/gas_schedule.rs, types/src/on_chain_config/mod.rs
This introduces an on-chain version number that governs gas-related behaviors in the VM. As we discussed previously, this is a special case that cannot be well supported by the individual feature flags.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4163)
=> [gas] introduce gas feature version

ecosystem/platform/server/app/controllers/nft_offers_controller.rb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4252)
=> [CP] Feature flag email verif

developer-docs-site/docs/tutorials/first-move-module.md
Fix #3571
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4228)
=> [docs] Fix Documentation Bug #3571.(#4228)

config/src/config/storage_config.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4250)
=> [Fix] Add serde attribute.

aptos-move/framework/aptos-framework/sources/aptos_account.move, aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/aptos-framework/sources/system_addresses.move, aptos-move/framework/aptos-framework/sources/vesting.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/3674)
=> [Aptos Framework] Add vesting module

ecosystem/platform/server/app/controllers/projects_controller.rb, ecosystem/platform/server/app/views/projects/index.html.erb, ecosystem/platform/server/spec/factories/projects.rb
Connects the form so that it actually searches / filters projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4261)
=> [community] Connect search / category form.

ecosystem/platform/server/app/components/claim_nft_button_component.html.erb, ecosystem/platform/server/app/components/claim_nft_button_component.rb, ecosystem/platform/server/app/controllers/nft_offers_controller.rb, ecosystem/platform/server/app/javascript/controllers/claim_nft_controller.ts, ecosystem/platform/server/app/views/nft_offers/show.html.erb
(n.b. this captcha is only displayed as a fallback if the invisible v3 captcha doesn't succeed)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4268)
=> [community] Require captcha to mint NFT.

aptos-move/framework/aptos-framework/sources/storage_gas.move
forget to change the test assertion after made changes to initialization code.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4269)
=> [aptos framework] fix storage_gas.move tests

Cargo.lock, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/types/objects.rs
Some of the code was making assumptions about the data and this removes them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4212)
=> [aptos-rosetta] Remove unwrap assumptions

.github/workflows/docker-build-test.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4289)
=> [gha] stop compat for now on LBT

execution/db-bootstrapper/src/bin/db-bootstrapper.rs
Looks like it doesn't see the latest data in cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4267)
=> [db-bootstrapper] stop using open_as_secondary

developer-docs-site/docs/concepts/staking.md
@movekevin I was going to include the flow we are discussing in Slack but deferring it for now. I still have a few questions but don't want to get into them right now. Fyi. I will come back to it later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4284)
=> More staking doc updates

aptos-move/framework/aptos-framework/sources/account.move
updated error & error comments 
existing unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4282)
=> [Account] updated error message

terraform/helm/genesis/files/genesis.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4294)
=> [genesis] Fix the use of empty random seed for now

aptos-move/framework/aptos-framework/sources/coin.move, aptos-move/framework/aptos-token/sources/token.move
add withdraw with capability
tested in https://github.com/aptos-labs/aptos-core/pull/3276
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4262)
=> [Token] auction house add token withdraw with proof  

Cargo.lock, aptos-move/aptos-gas/src/gas_meter.rs, aptos-move/aptos-gas/src/lib.rs, aptos-move/aptos-gas/src/transaction.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__borrow_after_move.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__change_after_move.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__data_store__move_from_across_blocks.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__module_publishing__layout_compatible_module.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__module_publishing__linking_compatible_module.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__module_publishing__test_publishing_allow_modules.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__module_publishing__test_publishing_modules_proper_sender.exp, aptos-move/e2e-testsuite/Cargo.toml, aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs, aptos-move/framework/aptos-framework/sources/storage_gas.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/gas_schedule.rs, types/src/on_chain_config/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4302)
=> [gas] dynamic storage costs

consensus/src/counters.rs, consensus/src/liveness/leader_reputation.rs, crates/aptos-metrics-core/src/lib.rs, crates/inspection-service/src/inspection_client.rs, testsuite/forge/src/interface/node.rs
To check counters on CI dashboard. (compat should show changing counters during restarts)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4255)
=> [consensus] Add chain health counters

aptos-move/framework/aptos-framework/sources/stake.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4318)
=> [framework] add missing comment to allow list

aptos-move/aptos-gas/src/transaction.rs
after receiving some feedback from the community and realizing we don't have good tools to split these up easily, let's relax this for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4319)
=> [gas] bump txn limit to 64K

developer-docs-site/docs/tutorials/your-first-nft.md
Both Alice and Bob's account are funded.
Fixed tutorial description.
Only text changes to tutorial content.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4291)
=> Fix tutorial content

ecosystem/platform/server/app/admin/projects.rb, ecosystem/platform/server/app/views/admin/projects/_images.html.erb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4277)
=> [community] Add project images to admin pages.

aptos-move/framework/aptos-token/sources/token.move
Adds a check to see if tokendata exists or not
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4323)
=> [TOK] Add check for tokendata existence

ecosystem/typescript/sdk/src/aptos_client.ts
These were unintentionally left out.
👀
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4337)
=> [TS SDK] Add query params argument to getEventsByCreationNumber

Cargo.lock, testsuite/forge-cli/src/main.rs, testsuite/forge/Cargo.toml, testsuite/forge/src/interface/mod.rs, testsuite/forge/src/interface/network.rs, testsuite/forge/src/interface/swarm.rs, testsuite/forge/src/runner.rs, testsuite/forge/src/success_criteria.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/tests/forge-local-performance.rs, types/src/account_config/events/new_block.rs
added to landblocking
run had: 
Passed progress check. Max round gap was 1 [limit 4] at version 2213899. Max no progress secs was 3.080434 [limit 10] at version 3689446.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4144)
=> [forge] Add continuous progress check to SuccessCriteria

testsuite/forge-cli/src/main.rs
The test has been flaky with TPS requirement - lowering it to stabilize it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4339)
=> [Forge] Tune validator reboot stress test

ecosystem/typescript/sdk/src/aptos_client.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts
Add gas estiamte API to SDK. default maxGasAmount is still hard coded. Gas simulation doesn't help here since gas simulation itself uses transactions.
All tests still pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4298)
=> feat(ts-sdk): support gas estimate

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4296)
=> [Docs] Adding a note on Move module publishing.

.github/workflows/prover-test.yaml
Run prover continuously for now. We can come back and stabilize this later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4350)
=> [gha] Only run prover continuously for now

ecosystem/typescript/sdk/examples/typescript/multisig_transaction.ts
There are a few details of the description that need to be expressed clearly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4305)
=> update multisig script

ecosystem/platform/server/config/routes.rb
Addresses https://github.com/aptos-labs/aptos-core/security/code-scanning/1.
Not sure, will see what the CP folks say.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4330)
=> Make CP host regex more exact

ecosystem/typescript/sdk/src/index.ts
Export derivePath for wallets
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4299)
=> chore(ts-sdk): export derivePath

terraform/helm/monitoring/files/rules/alerts.yml
Update count capacity and rate to reflect current default. Add bytes.
Observe the charts in o11y
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4331)
=> [mempool] alerts: update capacity and rate (count, bytes)

storage/aptosdb/src/state_restore/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/jellyfish-merkle/src/restore/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4352)
=> [storage] fix flaky test_get_rightmost_leaf

Cargo.lock, aptos-move/aptos-gas/Cargo.toml, aptos-move/e2e-move-tests/tests/code_publishing.rs, aptos-move/framework/aptos-framework/sources/code.move, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4361)
=> Update move deps

ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/aptos_client.ts
This adds TS SDK support for the query params added in https://github.com/aptos-labs/aptos-core/pull/4273.
With a local testnet:
```
yarn test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4362)
=> [TS SDK] Add support for transaction simulation gas query params

aptos-move/framework/aptos-framework/sources/storage_gas.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4363)
=> update storage gas curves

testsuite/smoke-test/src/storage.rs
Hard to reproduce locally. These will help the debugging tomorrow.
---
I think it's the first time waiting for the swarm to come up that takes longer than currently allowed (30 seconds), making it significantly longer (180 seconds, which is seen else where in the smoke-test crate). 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4365)
=> [storage] add prints to help debugging flaky test_db_restore

aptos-move/framework/aptos-framework/sources/vesting.move
Add support for multi-roles in the vesting module. First role will be a beneficiary resetter that can reset the beneficiary to the original shareholder account.
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4355)
=> [Aptos Framework][Vesting] Multi-role support

api/goldens/aptos_api__tests__events_test__test_get_events_by_invalid_account_event_handle_field_type.json, api/goldens/aptos_api__tests__invalid_post_request_test__test_invalid_entry_function_argument_address_string.json, api/goldens/aptos_api__tests__invalid_post_request_test__test_invalid_entry_function_argument_address_type.json, api/goldens/aptos_api__tests__invalid_post_request_test__test_invalid_entry_function_argument_data_type.json, api/goldens/aptos_api__tests__invalid_post_request_test__test_invalid_entry_function_argument_u64_string.json, api/goldens/aptos_api__tests__invalid_post_request_test__test_invalid_entry_function_function_name.json, api/goldens/aptos_api__tests__invalid_post_request_test__test_invalid_entry_function_module_address.json, api/goldens/aptos_api__tests__invalid_post_request_test__test_invalid_entry_function_module_name.json, api/goldens/aptos_api__tests__invalid_post_request_test__test_missing_entry_function_arguments.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_entry_function_invalid_function_name.json, api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_entry_function_invalid_module_name.json, api/goldens/aptos_api__tests__transactions_test__test_post_invalid_bcs_format_transaction.json, api/src/events.rs, api/src/state.rs, api/src/transactions.rs, api/types/src/error.rs
Turns out our error messages were having the useful parts of the messages clipped off.  This fixes it.
Tested manually, plus the goldenfiles show
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4369)
=> [api] Api error messages

state-sync/state-sync-v2/state-sync-driver/src/driver.rs, state-sync/state-sync-v2/state-sync-driver/src/metrics.rs, state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs, state-sync/state-sync-v2/state-sync-driver/src/utils.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4351)
=> observability: remove obsolete state sync high cardinality metric

aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/vm-genesis/src/lib.rs, crates/aptos/src/genesis/tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4378)
=> [Genesis] Support beneficiary resetter in mainnet genesis

aptos-move/framework/aptos-token/sources/token.move
1. Update one error code 
2. update the burn function to work with unlimited collection and token whose maximal is 0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4316)
=> [Token] fix issues

developer-docs-site/docs/aptos-developer-resources.md, developer-docs-site/docs/cli-tools/aptos-cli-tool/index.md, developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md, developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md, developer-docs-site/docs/guides/getting-started.md, developer-docs-site/sidebars.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4347)
=> [Docs] Adding new doc for developer resources.

terraform/helm/aptos-node/files/haproxy.cfg, terraform/helm/aptos-node/values.yaml
- Revert "[HAProxy] adding support for fn port 6181"
- Revert "[Haproxy] Minor fixups"
- Revert "[haproxy] Adding a new HAProxy for better DDoS Protection"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4408)
=> Revert recent haproxy changes

ecosystem/typescript/sdk/examples/javascript/index.js, ecosystem/typescript/sdk/examples/javascript/yarn.lock, ecosystem/typescript/sdk/examples/typescript/bcs_transaction.ts, ecosystem/typescript/sdk/examples/typescript/multisig_transaction.ts, ecosystem/typescript/sdk/examples/typescript/transfer_coin.ts, ecosystem/typescript/sdk/examples/typescript/yarn.lock, ecosystem/typescript/sdk/examples/typescript/your_coin.ts, ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/coin_client.test.ts
Update the gas params
simple_nft example still fails. The clients were created without exposing gas params. Will fix that later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4405)
=> chore: update TS SDK gas costs

terraform/helm/fullnode/files/backup/gcs.yaml, terraform/helm/fullnode/templates/backup.yaml, terraform/helm/fullnode/templates/restore.yaml
Couple broken things because of the toml to yaml change
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4326)
=> [helm] fix backup and restore helm

Cargo.lock, Cargo.toml, crates/indexer/Cargo.toml, crates/indexer/src/database.rs, crates/indexer/src/indexer/tailer.rs, crates/indexer/src/indexer/transaction_processor.rs, crates/indexer/src/models/block_metadata_transactions.rs, crates/indexer/src/models/collection_datas.rs, crates/indexer/src/models/events.rs, crates/indexer/src/models/ledger_info.rs, crates/indexer/src/models/move_modules.rs, crates/indexer/src/models/move_resources.rs, crates/indexer/src/models/move_tables.rs, crates/indexer/src/models/processor_statuses.rs, crates/indexer/src/models/signatures.rs, crates/indexer/src/models/token_datas.rs, crates/indexer/src/models/tokens.rs, crates/indexer/src/models/transactions.rs, crates/indexer/src/models/user_transactions.rs, crates/indexer/src/models/write_set_changes.rs, crates/indexer/src/processors/default_processor.rs, crates/indexer/src/processors/token_processor.rs, crates/indexer/src/util.rs, ecosystem/sf-indexer/aptos-sf-indexer/src/indexer/substream_processor.rs, ecosystem/sf-indexer/aptos-sf-indexer/src/substream_processors/block_output_processor.rs, ecosystem/sf-indexer/aptos-sf-indexer/src/substream_processors/tokens_processor.rs, testsuite/smoke-test/Cargo.toml, testsuite/smoke-test/src/indexer.rs
Upgraded to diesel 2.0.0
cargo test
also ran smoke test
also tested locally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4402)
=> [indexer] upgrade to diesel 2.0.0

ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/aptos_client.ts, ecosystem/typescript/sdk/src/coin_client.ts, ecosystem/typescript/sdk/src/faucet_client.ts, ecosystem/typescript/sdk/src/token_client.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts, ecosystem/typescript/sdk/src/utils/misc.ts
1. add extra gas paramters to TokenClient apis.
2. clean up the TS doc
3. show detailed error message for txn submission failures
yarn test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4411)
=> Clean up TS SDK

ecosystem/typescript/sdk/examples/javascript/package.json, ecosystem/typescript/sdk/examples/javascript/yarn.lock, ecosystem/typescript/sdk/examples/typescript-esm/package.json, ecosystem/typescript/sdk/examples/typescript-esm/yarn.lock, ecosystem/typescript/sdk/examples/typescript/package.json, ecosystem/typescript/sdk/examples/typescript/yarn.lock, ecosystem/typescript/sdk/src/aptos_client.test.ts
The new SDK should have the examples fixed automatically. It is safe to make the examples depend on the latest public SDK. We won't have frequent breaking changes in the future. Even though we see examples broken with the latest SDK, that means we do need to update/fix the examples. Therefore, make all examples depending on the latest public SDK.
Make sure all tests pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4425)
=> fix(ts-sdk): fix the failing example tests

api/doc/spec.json, api/doc/spec.yaml, api/src/blocks.rs, api/src/context.rs, crates/aptos-rest-client/src/lib.rs, crates/aptos-rosetta/src/block.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/main.rs, ecosystem/typescript/sdk/src/generated/services/BlocksService.ts, testsuite/smoke-test/src/rosetta.rs
Rosetta and block usage use pagination accordingly.
E2E tests.  It's actually a little hard to jam so many transactions into the block.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4392)
=> [api/rosetta] Fix api pagination

consensus/src/counters.rs, consensus/src/experimental/buffer_manager.rs
The previous counter didn't give us a breakdown of blocks per stage, this is going to provide us that insight. 
Existing UTs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4357)
=> [Consensus] Add metrics for pending blocks per stage

consensus/src/round_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4434)
=> [consensus] fix log spew from u128 in structured logs

consensus/src/round_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4438)
=> [testnet cherry-pick][consensus] fix log spew from u128 in structured logs

aptos-move/framework/aptos-token/sources/token.move
There is currently no way to go from tokendata to getting the latest tokenid. With this, now you can!
Added test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4436)
=> [Token] Add get max property version

developer-docs-site/docs/aptos-developer-resources.md, developer-docs-site/docs/guides/getting-started.md
Work in progress.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4444)
=> [Docs] Enhancing docs stuff.

consensus/consensus-types/src/quorum_cert.rs, consensus/consensus-types/src/sync_info.rs, consensus/src/experimental/buffer_manager.rs, consensus/src/experimental/pipeline_phase.rs, consensus/src/persistent_liveness_storage.rs, consensus/src/round_manager.rs, consensus/src/txn_notifier.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4395)
=> [consensus] a few cleanups

crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/misc.rs, crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4448)
=> [aptos-rosetta] Cherry-pick SetVoter changes

developer-docs-site/docs/tutorials/first-coin.md, developer-docs-site/docs/tutorials/first-dapp.md
Editorial cleanup with minor fixes. Continuation of https://github.com/aptos-labs/aptos-core/pull/4407. Added line numbers to the code where it refers to the `CoinInfo` check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4446)
=> [Docs] Editorial cleanup.

aptos-move/framework/aptos-framework/sources/configs/staking_config.move, aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/aptos-framework/sources/staking_contract.move, aptos-move/framework/aptos-framework/sources/staking_proxy.move, aptos-move/framework/aptos-framework/sources/staking_proxy.spec.move, aptos-move/framework/aptos-framework/sources/timestamp.move, aptos-move/framework/aptos-framework/sources/vesting.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4420)
=> Add a staking proxy contract

storage/backup/backup-cli/src/storage/command_adapter/sample_configs/local_folder.sample.yaml
sorry
Used to backup LLT to a local folder.
Checked other sample files for the same mistake, looks fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4394)
=> [backup] fix local_folder.sample.yaml

aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/aptos-framework/sources/staking_contract.move, aptos-move/framework/aptos-framework/sources/vesting.move, aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs, aptos-move/mvhashmap/src/unit_tests/mod.rs, aptos-move/parallel-executor/src/scheduler.rs, consensus/consensus-types/src/block_data.rs, consensus/src/state_computer.rs, crates/aptos-build-info/src/lib.rs, developer-docs-site/docs/guides/system-integrators-guide.md, documentation/specifications/consensus/README.md, documentation/tech-papers/lbft-reconfig/mechanism.tex, ecosystem/node-checker/src/evaluators/direct/api/state_sync.rs, ecosystem/typescript/sdk/src/aptos_client.ts, storage/aptosdb/src/ledger_store/mod.rs, storage/backup/backup-cli/src/coordinators/backup.rs, storage/backup/backup-cli/src/metadata/cache.rs, testsuite/forge/src/backend/local/swarm.rs, types/src/proof/position/mod.rs
1. typo: "the the"
2. small doc fix from audit result
3. moved a log line
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4459)
=> small fixes

aptos-move/framework/aptos-framework/sources/staking_contract.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4465)
=> [aptos-move] Allow updating operator without changing commission

aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move, aptos-move/framework/aptos-framework/sources/stake.spec.move, aptos-move/framework/aptos-framework/sources/storage_gas.move, aptos-move/framework/aptos-framework/sources/storage_gas.spec.move
- Proved that `storage_gas::on_reconfig` would never abort unexpectedly.
- Added the assertions to limit the upper bounds of certain parameters in order to prevent the arithmetic overflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4452)
=> Proved the `storage_gas` module

crates/aptos-rosetta/src/main.rs
Logs once every 10 seconds to tell us to look at the logs
E2E tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4462)
=> [aptos-rosetta] Keep checking that the API isn't up forever

crates/aptos/src/genesis/keys.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4476)
=> Fix broken compile call in CLI

developer-docs-site/docs/guides/system-integrators-guide.md
This describes how to retrieve balance changes from transactions (Similar to the Rosetta implementation).
Additionally, updates with the new event GUIDs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4449)
=> [docs] Add information about retrieving balance changes from events

aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
Update to the latest built from main, since it keeps showing up
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4478)
=> [cached-packages] Update framework builder

developer-docs-site/docs/concepts/basics-gas-txn-fee.md, developer-docs-site/docs/guides/system-integrators-guide.md
@chloeqjz hey, see the nit fixed. Thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4464)
=> [Docs] New gas doc and a minor nit in sys integ doc.

storage/aptosdb/src/lib.rs, storage/scratchpad/src/sparse_merkle/mod.rs
as title 
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4423)
=> [storage-audit-fix] dedup some constants

storage/jellyfish-merkle/src/lib.rs, storage/jellyfish-merkle/src/node_type/mod.rs
Fix auditing result.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4477)
=> [certik] fix storage comments

Cargo.lock, aptos-move/aptos-gas/Cargo.toml, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/package-builder/Cargo.toml
Update to a new version
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4497)
=> [aptos-move] Update move dependency

.github/workflows/copy-images-to-dockerhub-on-devnet-or-testnet-push.yaml, .github/workflows/docker-build-test.yaml
add branch for GHA to trigger docker build and docker publish
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4501)
=> [GHA] add branch for docker

aptos-move/framework/aptos-framework/sources/vesting.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4504)
=> [Genesis][Vesting] Add a convenient update_operator feature with same commission

crates/aptos-faucet/src/lib.rs
Log the x-forwarded-for header
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4520)
=> [aptos-faucet] Log x-forwarded-for header

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
Typo on the word directory on line 133
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4488)
=> Fix type on line 133

aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/call_function.exp, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/execute_script.exp, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/publish_module.exp, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/table.exp, aptos-move/framework/aptos-token/sources/token_transfers.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4494)
=> [Token] Fix two fields in the token transfer event

aptos-move/framework/aptos-stdlib/sources/table_with_length.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4500)
=> fix(aptos-stdlib): typo

scripts/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4530)
=> [dev_setup] remove codegen as we don't use it anymore

aptos-move/e2e-move-tests/src/tests/init_module.data/pack/sources/hello.move, aptos-move/e2e-move-tests/src/tests/init_module.data/pack/sources/unrelated.move, aptos-move/e2e-move-tests/src/tests/init_module.data/pack_initial/Move.toml, aptos-move/e2e-move-tests/src/tests/init_module.data/pack_initial/sources/unrelated.move, aptos-move/e2e-move-tests/src/tests/init_module.rs, aptos-move/e2e-move-tests/tests/init_module.data/pack_initial/Move.toml, aptos-move/e2e-move-tests/tests/init_module.data/pack_initial/sources/unrelated.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4487)
=> [Tests] Add a test for init_module when republishing package

aptos-move/framework/aptos-stdlib/sources/table_with_length.move
Adds upsert from Table to TableWithLength
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4535)
=> [FW] Add upsert to TableWithLength

aptos-move/framework/aptos-framework/sources/voting.move
Currently minimum vote threshold can be set to > early resolution threshold. This means that early resolution threshold would be ignored if min vote threshold is not yet met. This is a strange state in the system and should be validated against.
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4534)
=> [Voting][Minor fix] Validate that minimum vote threshold <= early resolution threshold

developer-docs-site/docs/cli-tools/aptos-cli-tool/install-aptos-cli.md
Fixed up version of PR: https://github.com/aptos-labs/aptos-core/pull/4538
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4543)
=> [Docs] Adding Windows platform option and enhancing the doc.

config/src/config/execution_config.rs, execution/README.md
Added description for execution configs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4548)
=> execution readme update

crates/aptos/src/move_tool/mod.rs
A widely requested feature, supporting `vector<vector<u8>>`
I modified hello blockchain so that it would take a vec vec u8
You can see the resource here:
https://explorer.aptoslabs.com/account/0xfdf0c99777dd2821101c0b1c26a140c8fcfd63f99a371c4103397ed27791e65d?network=Devnet
```
$ aptos -- move run --function-id default::message::set_message --args hex_array:AB,BC
Do you want to submit a transaction for a range of [24800 - 37200] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
"Result": {
"transaction_hash": "0xc3c3844c923fa9a019dd6e8622883239365440cb71b9377498e483b4e2f379b7",
"gas_used": 257,
"sender": "fdf0c99777dd2821101c0b1c26a140c8fcfd63f99a371c4103397ed27791e65d",
"sequence_number": 1,
"timestamp_us": 1664214700463742,
"version": …
```
=> [aptos-cli] Support vector<vector<u8>> for run function and script

config/src/config/execution_config.rs, execution/README.md, storage/aptosdb/src/event_store/mod.rs, storage/jellyfish-merkle/src/lib.rs, storage/schemadb/src/lib.rs, storage/schemadb/src/metrics.rs, storage/schemadb/tests/db.rs
we don't use it and the auditing complains about the test.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4469)
=> [storage] delete range_delete

developer-docs-site/docs/whats-new-in-docs.md
Compile and summarize changes from the last two weeks
Manually built and tested docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4561)
=> Update whats-new-in-docs.md with changes from late September

crates/aptos/src/node/mod.rs, crates/aptos/src/stake/mod.rs, crates/aptos/src/test/mod.rs, crates/aptos/src/test/tests.rs, types/src/lib.rs, types/src/staking_conttract.rs, types/src/vesting.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4564)
=> [CLI] Make GetStakePool CLI easier to use and add CreateStakingContract

ecosystem/node-checker/README.md
This will change again, but for now this is the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4578)
=> Fixing broken link.

testsuite/smoke-test/src/client.rs, testsuite/smoke-test/src/full_nodes.rs
Reenabling, as swarm init has stabilized
Run tests in CICD. Will have to check if they show up in flaky tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4544)
=> [smoke tests] reenable some more tests

.github/workflows/forge-continuous.yaml, testsuite/forge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4418)
=> [forge] Fix step summary formatting

crates/aptos/src/genesis/mod.rs, terraform/helm/genesis/files/genesis.sh, testsuite/testcases/src/compatibility_test.rs, testsuite/testcases/src/gas_price_test.rs, testsuite/testcases/src/partial_nodes_down_test.rs, testsuite/testcases/src/state_sync_performance.rs
hardcoded to 1 before, which is not backwards compatible... this makes it adopt a sane default
canary in CI, check with compat test, which I've updated the compat target commit hash to the latest tip of `testnet` branch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4590)
=> [forge] set default gas price

crates/aptos-rosetta-cli/src/construction.rs, crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/misc.rs, crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs, crates/aptos-rosetta/src/types/requests.rs, testsuite/smoke-test/src/rosetta.rs
* Removes stake balance changes
* Adds balance of account for SetOperator
* Adds operators in balance for total stake
* Adds ability to create stake pool experimentally
Fails exactly the same on testnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4593)
=> [rosetta] Update staking and add CreateStakePool

CODEOWNERS
`CODEOWNERS` file for telemetry service and related crates
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4583)
=> [telemetry] CODEOWNERS file

crates/aptos/Cargo.toml
For the pending release, update the version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4600)
=> [aptos-cli] Bump to version 0.3.6

ecosystem/typescript/sdk/package.json, ecosystem/typescript/sdk/src/aptos_account.test.ts, ecosystem/typescript/sdk/src/aptos_client.ts, ecosystem/typescript/sdk/src/bcs/serializer.test.ts, ecosystem/typescript/sdk/src/generated/core/request.ts, ecosystem/typescript/sdk/src/token_client.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts, ecosystem/typescript/sdk/src/transaction_builder/builder_utils.ts, ecosystem/typescript/sdk/src/utils/memoize-decorator.ts, ecosystem/typescript/sdk/src/utils/test_helper.test.ts, ecosystem/typescript/sdk/tsconfig.json, ecosystem/typescript/sdk/yarn.lock
Make typescript more strict about the type checking for SDK.
yarn test
yarn build
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4496)
=> refactor: add "strict" to SDK tsconfig

Cargo.lock, terraform/helm/fullnode/values.yaml
https://github.com/aptos-labs/aptos-core/pull/4265 wrongly removed the parameters in hope that default values in the binary will be used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4618)
=> [backup] tf: add back backup intervals

api/test-context/src/test_context.rs, aptos-move/aptos-validator-interface/src/storage_interface.rs, aptos-node/src/lib.rs, config/src/config/storage_config.rs, crates/aptos-genesis/src/lib.rs, crates/aptos-genesis/src/mainnet.rs, execution/db-bootstrapper/src/bin/db-bootstrapper.rs, execution/executor-benchmark/src/db_generator.rs, execution/executor-benchmark/src/lib.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/driver_factory.rs, storage/README.md, storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/state_store/buffered_state.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/test_helper.rs, storage/backup/backup-cli/src/bin/replay-verify.rs, storage/backup/backup-cli/src/utils/mod.rs
better description.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4615)
=> [storage] rename target_snapshot_size

crates/transaction-emitter-lib/src/emitter/account_minter.rs
With increased gas fees, we were exceeding u64. But we really shouldn't be needing that much money - and it was due to this bug
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4614)
=> [txn-emitter] Fix computation for needed coin balance

Cargo.lock, config/src/config/consensus_config.rs, consensus/consensus-types/Cargo.toml, consensus/consensus-types/src/common.rs, consensus/src/epoch_manager.rs, consensus/src/quorum_store/direct_mempool_quorum_store.rs, consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs, consensus/src/round_manager.rs, consensus/src/round_manager_fuzzing.rs, consensus/src/round_manager_test.rs, network/src/peer/mod.rs, network/src/protocols/stream/mod.rs, network/src/protocols/wire/messaging/v1/test.rs, testsuite/generate-format/tests/staged/consensus.yaml, testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs
- enforce max fragments in stream messages
- enforce max block txn
- remove the quorum store variant
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4581)
=> enforce size limit on receiver side

developer-docs-site/docs/nodes/validator-node/operator/connect-to-aptos-network.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-docker.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-gcp.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-source-code.md
Test mode only relevant for AIT, removing it for now to prepare for mainnet/testnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4626)
=> [doc] update doc to remove test mode

developer-docs-site/sidebars.js
Just ran `yarn fmt` in developer-docs-site/ 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4637)
=> [Lint only] Fix docs lint

aptos-move/framework/aptos-framework/sources/vesting.move
1. pool_u64::update_total_coins call in create_vesting_contract is unnecessary as pool_u64::buy_in calls should already keep the total amount up to date.
2. Vesting contract currently would be stuck if the vesting schedule has 0 for some vesting periods. This PR fixes this issue by advancing the last vested period even if vesting amount is 0.
3. If the vesting period's amounts in the schedule don't add up to 1, last vest can lead to underflows. This PR fixes this by capping the vested amount by remaining grant.
4. A copy of the commission rate stored in the vesting account resource is not updated when it's updated in the underlying staking contract by update_operator. 
Unit tests
- - - …
=> [Vesting][Audit] Fix several minor issues in the vesting contract

aptos-move/framework/aptos-token/sources/token.move, aptos-move/framework/aptos-token/sources/token_coin_swap.move
no direct deposit zero balance token
no split zero balance token
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4611)
=> [Token] Enforce the Token with non-zero amount and update the collection supply correctly

testsuite/forge-cli/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4643)
=> [forge] fix max_block_txns rename

aptos-move/e2e-move-tests/src/tests/mint_nft.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/move-examples/mint_nft/Move.toml, aptos-move/move-examples/mint_nft/sources/minting.move, aptos-move/move-examples/tests/move_unit_tests.rs
example for minting NFT
unit & e2e tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4512)
=> [move-examples] NFT minting example 

consensus/consensus-types/src/block_retrieval.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4644)
=> [consensus] Remove skip_serializing_if from BlockRetreivalRequest

terraform/helm/aptos-node/README.md, terraform/helm/aptos-node/values.yaml, terraform/helm/fullnode/values.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4622)
=> [Config] Update disk size to 1000Gi.

aptos-move/framework/aptos-token/sources/token.move
just to re-oraganize code to public private entry and deprecated section. Make it easy to navigate through all the functions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4648)
=> [Token] re-organize code

mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs, mempool/src/tests/core_mempool_test.rs
Add metrics for ranking score and additional latency metrics for stages of going through mempool.
Run land blocking test, observe new dashboard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4616)
=> [mempool] more/better metrics

aptos-move/framework/aptos-framework/sources/configs/staking_config.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4657)
=> [Audit] Fix minor issues from audit

aptos-move/framework/aptos-token/sources/token_coin_swap.move
we restrict buyer cannot buy token while the lock time hasn't expire. This adds unnecessary restriction
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4545)
=> [Token] Deprecate Token Coin Swap Module

aptos-move/vm-genesis/src/lib.rs, crates/aptos-genesis/src/config.rs, crates/aptos-genesis/src/mainnet.rs, crates/aptos/src/genesis/git.rs, crates/aptos/src/genesis/mod.rs, crates/aptos/src/genesis/tests.rs
This adds mainnet genesis customization to the tooling.  Additionally, it handles lots of checks to make sure that everything is as it is expected to be.
Tested manually against a detailed example
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4613)
=> [genesis] Mainnet genesis tooling

aptos-move/aptos-vm/src/transaction_arg_validation.rs, aptos-move/e2e-move-tests/src/tests/string_args.data/pack/sources/hello.move, aptos-move/e2e-move-tests/src/tests/string_args.rs
Here we are again...
this solution has (or should have) some significant benefits over the previous one. 
Please review and find holes!
The most important change is that now we only walk and verify string arguments. Anything else is simply skipped. That should avoid the problem with the old implementation and save us from walking and spending time over arguments that do not matter.
We also check the overall size as we go and if we get over `static MAX_STRING_ARGS_SIZE: usize = 64 * 1024;` we stop and report a bad argument. A note about this limit:
- if the arguments are in fact correct, the overall transaction size check is before any function in args verification (the file changed) is invoked and the transaction fails for being too big. I believe that is 32K so the bigger value does not …
=> Validate string arguments to transaction

aptos-move/framework/aptos-framework/sources/configs/staking_config.move, aptos-move/framework/aptos-framework/sources/genesis.move
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4655)
=> [Trivial] Remove an used index variable

aptos-move/aptos-sdk-builder/src/main.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4652)
=> [sdk-builder] Fix default sdk builder language

terraform/helm/fullnode/templates/backup-verify.yaml, terraform/helm/fullnode/templates/backup.yaml
```
msmouse@ubuntu-dev:~$ kc logs testnet0-aptos-fullnode-backup-0 -f
W0929 09:48:31.530928 1332496 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
2022-09-29T16:48:07.328516Z [main] INFO crates/aptos-push-metrics/src/lib.rs:71 PUSH_METRICS_ENDPOINT env var is not set. Skipping sending metrics.
2022-09-29T16:48:07.335686Z [main] INFO storage/backup/backup-cli/src/utils/mod.rs:321 Determined concurrency level for downloading. {"concurrent_downloads":1}
2022-09-29T16:48:08.798275Z [main] INFO storage/backup/backup-cli/src/metadata/cache.rs:98 Metadata files listed.
2022-09-29T16:48:10.071673Z [main] INFO …
```
=> change backup pod log level to info

terraform/helm/testnet-addons/templates/ingress.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4682)
=> [helm] redirect primary ingress

aptos-move/framework/aptos-token/sources/property_map.move
also has some comments in PR.
cicd
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4597)
=> [audit] property_map.move

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4689)
=> chore: bump TS SDK version

terraform/helm/testnet-addons/templates/ingress.yaml
cherry-pick ssl redirect to devnet branch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4698)
=> CHERRY_PICK: [helm] redirect primary ingress (#4682)

codecov.yml
As above
Will rerun coverage once this lands.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4177)
=> Fix test coverage ignore path

scripts/dev_setup.sh
Another unzip path that was being missed by the dev setup script
This time I edited and ran this manually to check it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4594)
=> [dev_setup] Add unzip to another path in dev setup script

crates/aptos-genesis/src/builder.rs, crates/aptos-genesis/src/config.rs, crates/aptos-genesis/src/keys.rs, crates/aptos/src/common/types.rs, crates/aptos/src/genesis/git.rs, crates/aptos/src/genesis/keys.rs, crates/aptos/src/genesis/mod.rs, crates/aptos/src/genesis/tests.rs, types/src/account_address.rs
1. Prints which file is being checked
2. Adds more specific outputs when deserializing an AccountAddress with a wrapper
3. Checks the root key isn't set for mainnet
Manual testing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4686)
=> [genesis] Add checks to genesis tooling for debugging

api/src/transactions.rs, api/types/src/lib.rs, api/types/src/move_types.rs, network/src/protocols/wire/handshake/v1/mod.rs
Restrict the API txn to 16 and mempool message to 32 other system messages are left with 64.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4701)
=> [serde] apply stricter recursion limit on user input

terraform/helm/aptos-node/files/haproxy.cfg, terraform/helm/aptos-node/values.yaml
This reverts commit b4cfff630e4ffa5e5ffedd7954f3d1a44e0c6f49.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4719)
=> Revert "[haproxy] haproxy config and resources v3"

storage/backup/backup-cli/src/utils/stream/futures_unordered_x.rs
In one of the previous tries I intened to make sure every task yields but unfortunately I changed the wrong number (actually made sure there's more than 0 tasks, but they can sleep for 0ms).
This time around I'll just wait for the maximum concurrency to be reached in the tasks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4690)
=> [backup] fix flaky test utils::stream::futures_unordered_x::tests

aptos-move/framework/aptos-framework/sources/genesis.move, aptos-move/vm-genesis/src/lib.rs, crates/aptos-genesis/src/builder.rs, crates/aptos-genesis/src/config.rs, crates/aptos-genesis/src/lib.rs, crates/aptos-genesis/src/mainnet.rs, crates/aptos/src/genesis/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4718)
=> [Genesis] Move previously hardcoded vesting configurations into genesis configurations

terraform/helm/aptos-node/files/haproxy.cfg, terraform/helm/aptos-node/values.yaml
This reverts commit 75a8989024133aa5fd8629dd73db2cdc8e672fcc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4723)
=> Revert "Revert "[haproxy] haproxy config and resources v3" (#4719)"

crates/aptos/src/account/key_rotation.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4696)
=> Fix spelling error

developer-docs-site/docs/concepts/basics-gas-txn-fee.md, developer-docs-site/docs/whats-new-in-docs.md, developer-docs-site/sidebars.js
Incorporate docs from:
https://github.com/aptos-labs/aptos-core/pull/4680
Manual review and testing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4720)
=> Incorporate How Base Gas Works doc into dev site

aptos-move/framework/aptos-framework/sources/account.move
By default, only the SignerCapability should have control over the resource account and not the auth key.
If the source account wants direct control via auth key, they would need to explicitly rotate the auth key of the resource account using the SignerCapability.
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4709)
=> [Aptos Framework] Remove resource accounts' default auth key

crates/aptos/src/node/mod.rs, crates/aptos/src/stake/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4729)
=> [CLI] Fix issues with GetStakePool CLI

Cargo.lock, crates/aptos/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4742)
=> [cli] Update to 0.3.8

developer-docs-site/docs/nodes/validator-node/operator/connect-to-aptos-network.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4746)
=> Change owner-address to pool-address on line 188

terraform/helm/testnet-addons/README.md, terraform/helm/testnet-addons/templates/waypoint.yaml, terraform/helm/testnet-addons/values.yaml
swap out the waypoint http image to a more resource efficient one
config: https://sws.joseluisq.net/configuration/command-line-arguments/
deploy on my testnet to ensure correctness. have not load tested it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4745)
=> [helm][testnet-addons] change waypoint http image

crates/aptos-crypto/src/bls12381/bls12381_pop.rs, crates/aptos-genesis/src/config.rs, crates/aptos/src/genesis/mod.rs, crates/aptos/src/genesis/tests.rs
* Checks uniqueness of all keys
* Ensures that there are no empty "host" inputs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4734)
=> [genesis] Add more mainnet checks

developer-docs-site/docs/concepts/index.md
Addressing missing item reported in:
https://github.com/aptos-labs/aptos-core/pull/4720#issuecomment-1266108476
Manual edit in GH web editor and testing via Preview.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4737)
=> Add Coin and Token to Aptos Concepts list

api/src/log.rs, crates/aptos-logger/src/aptos_logger.rs, crates/aptos-logger/src/sample.rs, crates/aptos-rest-client/src/lib.rs, crates/aptos-warp-webserver/src/log.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/submission_worker.rs, crates/transaction-emitter-lib/src/transaction_generator/account_generator.rs, state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs, storage/aptosdb/src/pruner/ledger_pruner_worker.rs, storage/aptosdb/src/pruner/state_pruner_worker.rs, storage/storage-interface/src/async_proof_fetcher.rs
Cleans up the sampling macro, and reduces logs on telemetry failures
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4753)
=> [logging] Cleanup sampling and logs for telemetry

.github/workflows/cli-release.yaml
Looking at the script we use to build the CLI, this should just work without any further changes, but we should run it to be sure.
Sorta tough, it'd be best practice to fork the repo and test it there, but we could also just yolo lol.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4743)
=> Build CLI on Ubuntu 20 and 22

terraform/helm/aptos-node/files/haproxy.cfg
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4761)
=> [haproxy] http timeout 60ms -> 60s

config/src/config/api_config.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4685)
=> [api] reduce submit_batch size to planned 10 txn per single request

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/cluster.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/lib.rs, crates/transaction-emitter-lib/src/transaction_generator/p2p_transaction_generator.rs, crates/transaction-emitter-lib/src/wrappers.rs, crates/transaction-emitter/src/diag.rs, ecosystem/node-checker/src/evaluators/direct/tps.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4724)
=> [txn-emitter] allow txn-emitter to submit transactions from given (non-root) source account

developer-docs-site/docs/sdks/ts-sdk/index.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4765)
=> Qualify TS install doc link in index

developer-docs-site/docusaurus.config.js, developer-docs-site/package.json, developer-docs-site/yarn.lock
See the [Storage gas](https://deploy-preview-4747--aptos-developer-docs.netlify.app/concepts/base-gas#storage-gas) of the base-gas.md doc. The LaTeX formulas now render properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4747)
=> [Docs] Adding KaTeX plugin

storage/backup/backup-cli/src/bin/replay-verify.rs, storage/backup/backup-cli/src/coordinators/replay_verify.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4783)
=> [backup] add concurrency-level to replay-verify

crates/aptos/src/genesis/mod.rs, crates/aptos/src/genesis/tools.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4752)
=> [genesis] Add tool that parses pool addresses for all validators

config/src/config/indexer_config.rs, config/src/config/mod.rs, crates/indexer/migrations/2022-10-02-011020_ans_lookup_table/down.sql, crates/indexer/migrations/2022-10-02-011020_ans_lookup_table/up.sql, crates/indexer/src/models/token_models/ans_lookup.rs, crates/indexer/src/models/token_models/mod.rs, crates/indexer/src/processors/token_processor.rs, crates/indexer/src/runtime.rs, crates/indexer/src/schema.rs
* Add ANS lookup table based on lookup tables
* Contract address is configurable via indexer.ans_contract_address
Tested in localnet with the ANS contract. Observe that table is populated correctly. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4624)
=> [indexer] add ANS lookup table

developer-docs-site/docs/nodes/validator-node/voter/index.md
Update governance url pointer in doc file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4780)
=> [DOC] update governance url 

aptos-move/e2e-move-tests/src/tests/code_publishing.rs, aptos-move/framework/aptos-framework/sources/account.move, types/src/account_address.rs, types/src/transaction/authenticator.rs
Take it away @movekevin.
Will update the description soon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4787)
=> [move] fix resource account address derivation

Cargo.lock, api/Cargo.toml, api/types/Cargo.toml, aptos-move/aptos-aggregator/Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-sdk-builder/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/e2e-move-tests/src/tests/vector_numeric_address.rs, aptos-move/framework/Cargo.toml, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/package-builder/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, crates/aptos-rest-client/Cargo.toml, ecosystem/sf-indexer/firehose-stream/Cargo.toml, execution/executor/Cargo.toml, storage/aptosdb/Cargo.toml, storage/indexer/Cargo.toml, storage/storage-interface/Cargo.toml, types/Cargo.toml
This pulls in a fix in the compiler for vector operations. 
Also adds a test for this scenario.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4802)
=> [move] Update Move commit hash

developer-docs-site/docs/issues-and-workarounds.md
All the stuff in the https://www.notion.so/aptoslabs/Mainnet-TODOs-f3e123a68899444691e7a23d6e8939ac doc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4777)
=> [Docs] Update frequently asked issues.

developer-docs-site/docs/guides/getting-started.md
This is mostly fact finding as a ran into some questions and snags while getting set up. Like which OSes do we and the script support?
I also hit a snag building Aptos:
```
claymurphy@MacBook-Air aptos-core % cargo build        
Updating git repository `https://github.com/aptos-labs/rust-rocksdb`
Updating git submodule `https://github.com/facebook/rocksdb.git`
warning: spurious network error (2 tries remaining): SecureTransport error: connection closed via error; class=Net (12)
warning: spurious network error (1 tries remaining): SecureTransport error: connection closed via error; class=Net (12)
error: failed to load source for dependency `rocksdb`
Caused by:
Unable to update https://github.com/aptos-labs/rust-rocksdb#3698ab20
Caused by:
failed to update submodule `rocksdb_sys/rocksdb` …
```
=> Update Getting Started with missing details

state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4808)
=> [State-sync] Add more logs.

crates/aptos-rosetta-cli/README.md, crates/aptos-rosetta-cli/src/account.rs, crates/aptos-rosetta-cli/src/common.rs, crates/aptos-rosetta-cli/src/construction.rs, crates/aptos-rosetta/README.md, crates/aptos-rosetta/aptos.ros, crates/aptos-rosetta/src/types/requests.rs
An initial stab at talks about the implementation and details about rosetta.
This is mostly just for internal operational purposes, and not for a user guide or anything specific around Rosetta.  Rosetta is still use at your own risk at this point.
None, it's documentation!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4807)
=> [rosetta] Rosetta API docs

Cargo.lock, aptos-move/aptos-aggregator/src/transaction.rs, aptos-move/aptos-gas/src/gas_meter.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/vm-genesis/src/lib.rs, aptos-move/writeset-transaction-generator/src/writeset_builder.rs, config/src/config/execution_config.rs, execution/executor/Cargo.toml, execution/executor/src/mock_vm/mod.rs, execution/executor/tests/db_bootstrapper_test.rs, state-sync/inter-component/mempool-notifications/src/lib.rs, types/src/proptest_types.rs, types/src/transaction/change_set.rs
there was old txns who exceeded these limits that broke backward competibility on testnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4809)
=> feature gate change set size checks

terraform/aptos-node/aws/variables.tf, terraform/fullnode/aws/variables.tf
run fmt and lint
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4820)
=> [tf] fix lint on storage type config

aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/gas.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/vm-genesis/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4801)
=> [Evaluation] Add gas cost evaluation test

aptos-move/framework/aptos-names/sources/token_helper.move
Make `create_token_data` private
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4828)
=> Make create_token_data private

crates/aptos/src/node/mod.rs, crates/aptos/src/stake/mod.rs, types/src/lib.rs, types/src/on_chain_config/validator_set.rs, types/src/staking_contract.rs, types/src/validator_performances.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4794)
=> [CLI] Return more info in get-stake-pool and add request-commission CLI

storage/jellyfish-merkle/src/lib.rs, storage/jellyfish-merkle/src/metrics.rs
add a counter to prove the deletion of leaf works.
ut. will run on forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4744)
=> [storage] add deleted_leaf counter

Cargo.lock, crates/aptos/Cargo.toml
This release gets in updates to node operator tooling
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4846)
=> [cli] Bump to version 0.3.9

developer-docs-site/docs/concepts/base-gas.md
@rajkaramchedu @clay-aptos
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4845)
=> Add missing conjunction to gas docs

crates/aptos/src/node/mod.rs, crates/aptos/src/stake/mod.rs, crates/aptos/src/test/mod.rs, testsuite/smoke-test/src/aptos_cli/validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4781)
=> [CLI] Update stake CLI to support staking_contract and vesting

crates/indexer/migrations/2022-10-06-193846_add_indexer_status/down.sql, crates/indexer/migrations/2022-10-06-193846_add_indexer_status/up.sql, crates/indexer/src/schema.rs
* Add some views for stitch
* Add indexer down table
I can add status to this table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4838)
=> [Indexer] Add views and indexer status table

api/Cargo.toml, api/types/Cargo.toml, aptos-move/aptos-aggregator/Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-sdk-builder/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/framework/Cargo.toml, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/package-builder/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, crates/aptos-rest-client/Cargo.toml, ecosystem/sf-indexer/firehose-stream/Cargo.toml, execution/executor/Cargo.toml, storage/aptosdb/Cargo.toml, storage/indexer/Cargo.toml, storage/storage-interface/Cargo.toml, types/Cargo.toml
This gets in https://github.com/move-language/move/pull/553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4857)
=> [move] Update Move reference for bytecode verifier update.

crates/aptos/src/node/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4863)
=> [CLI] Delete debugging print

Cargo.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4866)
=> fix cargo lock for bcs version

aptos-move/framework/aptos-names/sources/token_helper.move
Cherry pick #4828 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4840)
=> Cherry pick f93e23550ac68688e2c70cd3b97fb05649bc25c7

crates/aptos/src/node/analyze/fetch_metadata.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4868)
=> [cli][analyze-validators] Make fetching work when api can return less than limit

AptosFramework/storage_gas.md
@davidiw 
Addresses changes from following commits:
* 7ad1c053f8a33aba4a485fe28e81a6f419187eaf
* dd3f6c05614caae6b37d7691b1f33a8c76e1ec8b
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4876)
=> Update storage gas DocGen file per param updates

developer-docs-site/docs/concepts/state-sync.md, state-sync/README.md
This PR updates the state sync README and developer docs with additional instructions and troubleshooting for fast syncing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4874)
=> [State Sync] Update README and docs.

developer-docs-site/docs/nodes/validator-node/voter/index.md
Voter doc update. Let's land this, but know that I will likely update this doc once more before mainnet. 
cc: @movekevin
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4879)
=> [Docs] Updating Voter doc for mainnet

crates/aptos/src/node/mod.rs, crates/aptos/src/test/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4864)
=> [CLI] Update analyze performance CLI to allow filtering by specific validators

developer-docs-site/docs/nodes/validator-node/operator/node-requirements.md, terraform/aptos-node/gcp/auth.tf, terraform/aptos-node/gcp/variables.tf
Test Plan: update our nodes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4877)
=> [tf] Update node requirement for gcp

developer-docs-site/docs/nodes/aptos-deployments.md
@sherry-x This PR updates the blockchain deployment table. ~The mainnet column is partially unfilled because it needs your input.~ I removed the local testnet column because it was getting too difficult to fit so many columns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4789)
=> [Docs] Update the blockchain deployment table.

crates/aptos-telemetry/src/cli_metrics.rs, crates/aptos/src/common/utils.rs
Upload the error codes from each CLI command accordingly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4892)
=> [cli] Log error codes in cli telemetry

.github/workflows/lint-test.yaml, docker/build-rust-all.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4880)
=> lock cargo lock file to prevent it being out-of-date

docker/compose/aptos-node/fullnode.yaml
These configs are applied in terraform (https://github.com/aptos-labs/aptos-core/blob/main/terraform/helm/aptos-node/values.yaml#L127) for 1+ months, but not outside of terraform.
Tested docker-compose up (via @rustielin )
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4890)
=> [mempool] add VFN-specific configs

Cargo.lock, developer-docs-site/docs/concepts/coin-and-token/aptos-token.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4872)
=> [Token] improve doc of off-chain storage section

developer-docs-site/docs/concepts/base-gas.md
@davidiw 
Addresses changes from following commits:
0d575cec3980fda12ad179fe011acbfbac80568b
7ad1c053f8a33aba4a485fe28e81a6f419187eaf
dd3f6c05614caae6b37d7691b1f33a8c76e1ec8b
63e5c543742f17e0f09b98ea39f40744c7cf4abf
@clay-aptos @rajkaramchedu @msmouse @vgao1996
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4886)
=> Add new gas schedule analysis per recent refactor

Cargo.lock, crates/aptos/Cargo.toml
For the next release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4884)
=> [cli] Update to 0.4.0 for release

storage/aptosdb/src/lib.rs
to understand how much overhead we are paying
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4893)
=> [storage] add counter for the internal indexer

consensus/src/counters.rs, consensus/src/epoch_manager.rs
Will be useful to debug consensus performance 
Existing UTs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4819)
=> [Consensus] Add metrics for voting power for the validator

api/Cargo.toml, api/types/Cargo.toml, aptos-move/aptos-aggregator/Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-sdk-builder/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/framework/Cargo.toml, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/package-builder/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, crates/aptos-rest-client/Cargo.toml, ecosystem/sf-indexer/firehose-stream/Cargo.toml, execution/executor/Cargo.toml, storage/aptosdb/Cargo.toml, storage/indexer/Cargo.toml, storage/storage-interface/Cargo.toml, types/Cargo.toml
This gets in https://github.com/move-language/move/pull/553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4871)
=> [move] Update Move reference for bytecode verifier update. (Cherrypick #4857)

aptos-move/framework/aptos-token/sources/property_map.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4902)
=> [Token] Add a new construct for property map

storage/storage-interface/src/lib.rs, types/src/move_resource.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4927)
=> remove unused

developer-docs-site/docs/sdks/ts-sdk/index.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4923)
=> Add Typescript SDK Reference to Typescript index

Cargo.lock, api/Cargo.toml, api/types/Cargo.toml, aptos-move/aptos-aggregator/Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-sdk-builder/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/framework/Cargo.toml, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/package-builder/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, crates/aptos-rest-client/Cargo.toml, ecosystem/sf-indexer/firehose-stream/Cargo.toml, execution/executor/Cargo.toml, storage/aptosdb/Cargo.toml, storage/indexer/Cargo.toml, storage/storage-interface/Cargo.toml, types/Cargo.toml
This commit contains (at least temporary but safe) fix for the bug related to count of locals the new fuzzer detected (https://github.com/move-language/move/pull/564).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4913)
=> [Move] Update commit

docker/compose/aptos-node/fullnode.yaml
This reverts commit 2f8408b37e3ac8daa72e440385e6dacaf8f69e58.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4940)
=> Revert "[mempool] add VFN-specific configs (#4890)"

docker/compose/aptos-node/fullnode.yaml
This reverts commit 51a47989d8fd695a5e78362937662df2ca5c5bf5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4941)
=> Revert "[mempool] add VFN-specific configs (#4890) (#4895)"

developer-docs-site/docs/issues-and-workarounds.md, developer-docs-site/docs/nodes/validator-node/operator/staking-pool-operations.md
A couple of additional helpful cross links and notes for the staking pool doc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4931)
=> [Docs] Minor modifications to staking pool ops doc.

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-node/src/lib.rs, config/src/config/execution_config.rs, execution/executor/src/components/chunk_output.rs, execution/executor/src/metrics.rs
Test plan:
running full node locally against the LLT.
Counters with detailed logging on:
https://gist.githubusercontent.com/igor-aptos/2fa7f7aff16a717971a98d6ce7b88799/raw/107d84baa5eb8a33b4bb7be01d569c3dd355fd89/gistfile1.txt
counters with detailed logging off: 
https://gist.github.com/igor-aptos/02e2a3dac34ac5219b7a0a86387694a9
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4784)
=> [consensus] Track counters about executed transaction details

developer-docs-site/docs/guides/system-integrators-guide.md
Line-by-line edit of the System Integrators Guide:
https://aptos.dev/guides/system-integrators-guide
Frankly, we may want to break this into sub-pages sometime.
Manual review and editing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4646)
=> Edit systems integrators guide

config/src/config/mempool_config.rs, mempool/src/tests/shared_mempool_test.rs
Gives finer granularity than before.
Ran several load tests to ensure no regression with more buckets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4964)
=> [mempool] update the default broadcast bucket config

aptos-move/move-examples/marketplace/readme.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4971)
=> fix format

Cargo.lock, api/Cargo.toml, api/goldens/aptos_api__tests__transactions_test__test_gas_estimation.json, api/types/Cargo.toml, aptos-move/aptos-aggregator/Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-sdk-builder/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/framework/Cargo.toml, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/package-builder/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, crates/aptos-rest-client/Cargo.toml, ecosystem/sf-indexer/firehose-stream/Cargo.toml, execution/executor/Cargo.toml, storage/aptosdb/Cargo.toml, storage/indexer/Cargo.toml, storage/storage-interface/Cargo.toml, types/Cargo.toml
Pull in fixes in restricting number of type nodes and preventing a crash in compatibility checks.
https://github.com/move-language/move/pull/567
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4978)
=> [move] Update commit hash

Cargo.lock, api/Cargo.toml, api/goldens/aptos_api__tests__transactions_test__test_gas_estimation.json, api/types/Cargo.toml, aptos-move/aptos-aggregator/Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-sdk-builder/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/framework/Cargo.toml, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/package-builder/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, crates/aptos-rest-client/Cargo.toml, ecosystem/sf-indexer/firehose-stream/Cargo.toml, execution/executor/Cargo.toml, storage/aptosdb/Cargo.toml, storage/indexer/Cargo.toml, storage/storage-interface/Cargo.toml, types/Cargo.toml
Pull in fixes in restricting number of type nodes and preventing a crash in compatibility checks.
https://github.com/move-language/move/pull/567
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4987)
=> [move] Update commit hash (#4978)

developer-docs-site/docs/guides/building-wallet-extension.md
Just a minor fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4815)
=> [Docs] Remove transaction param in disconnect()

terraform/aptos-node/gcp/auth.tf, terraform/helm/aptos-node/Chart.yaml, terraform/helm/fullnode/Chart.yaml
update release versions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4617)
=> [helm] update versions

developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md, developer-docs-site/docs/nodes/node-files.md
rename genesis repo from aptos-genesis-waypoint to aptos-networks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5000)
=> [doc] update genesis repo

terraform/helm/fullnode/values.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5001)
=> update genesis url

developer-docs-site/docs/nodes/node-files.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-aws.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-azure.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-docker.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-gcp.md, developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-source-code.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4966)
=> [Docs] Adding haproxy cfg file to the node file list.

developer-docs-site/docs/guides/state-sync.md, state-sync/README.md
This PR adds some small warnings about resorting to fast sync in the case of validator and validator fullnodes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5009)
=> [Docs] Additional docs about fast sync.

developer-docs-site/docs/issues-and-workarounds.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5010)
=> Update premainnet refs to mainnet in docs

crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/requests.rs
Requested feature to make gas price change based on estimation
TBD & CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4995)
=> [rosetta] Add ability to change gas price based on estimation

developer-docs-site/docs/nodes/validator-node/operator/connect-to-aptos-network.md
Found and fixed a small broken link
Locally built and tested.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4998)
=> Fix link to Node Liveness Criteria from Connecting to Aptos Network

crates/indexer/src/models/token_models/ans_lookup.rs, ecosystem/sf-indexer/aptos-sf-indexer/src/models/indexer_states.rs
Null was treated as noop
`cargo run -p aptos-node --features "indexer" --release -- -f ./fullnode_token.yaml`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5015)
=> [Indexer] fix ans bug

aptos-move/framework/aptos-framework/sources/account.move
fix some nits
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4979)
=> [aptos-framework] nits in account.move

developer-docs-site/docs/nodes/node-connections.md, developer-docs-site/docs/whats-new-in-docs.md, developer-docs-site/sidebars.js
Initial version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4985)
=> [Docs] New Node Connections doc.

developer-docs-site/docs/sdks/index.md, developer-docs-site/docs/sdks/python-sdk.md, developer-docs-site/docs/sdks/rust-sdk.md, developer-docs-site/docs/sdks/ts-sdk/index.md, developer-docs-site/docs/tutorials/first-coin.md
Link into source
Introduce TS SDK
Encourage TS SDK use
Bi-capitalize TypeScript
Local build and test
Test with deploy preview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5022)
=> Add links to all SDK source directories from respective introductions

developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-source-code.md
Including the `cargo clean` step prior to running `cargo run -p ...` step. Per Slack thread: https://aptos-org.slack.com/archives/C041UPR5PF1/p1665685530221159?thread_ts=1665681886.601939&cid=C041UPR5PF1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5027)
=> Including cargo clean step

crates/indexer/src/models/transactions.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5028)
=> remove bad logs

aptos-move/framework/cached-packages/build.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5030)
=> [cherry-pick] [cached packages] remove non-existant aptos-names (#5025)

crates/aptos/src/account/create.rs, crates/aptos/src/account/create_resource_account.rs, crates/aptos/src/account/fund.rs, crates/aptos/src/account/key_rotation.rs, crates/aptos/src/account/list.rs, crates/aptos/src/account/transfer.rs, crates/aptos/src/config/mod.rs, crates/aptos/src/governance/mod.rs, crates/aptos/src/node/mod.rs, crates/aptos/src/stake/mod.rs
Start of updating CLI documentation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4981)
=> [cli] Update documentation

developer-docs-site/docs/nodes/full-node/fullnode-network-connections.md
This PR offers two tiny tweaks to the network connections docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5038)
=> [Docs] Small tweaks to network connections docs.

consensus/src/liveness/leader_reputation.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4997)
=> [consensus] just fix health counters

consensus/src/liveness/leader_reputation.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5032)
=> [cherry-pick][4997] [consensus] just fix health counters

execution/executor/src/components/chunk_output.rs, execution/executor/src/metrics.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5048)
=> [mainnet cherry-pick][5042][move] more transaction counters

aptos-move/move-examples/mint_nft/sources/minting.move
updated comment in `minting.move` to reflect the latest change in resource address generation 
N/A 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4934)
=> [move-examples] updated comment for mint_nft

storage/storage-interface/src/async_proof_fetcher.rs, types/src/proof/definition.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5045)
=> [Log] More details when failed to verify proof.

storage/storage-interface/src/async_proof_fetcher.rs, types/src/proof/definition.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5054)
=> [CP][Log] More details when failed to verify proof.

developer-docs-site/docs/sdks/ts-sdk/index.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5046)
=> Fix embarrassing typo in TypeScript intro

crates/aptos/src/account/key_rotation.rs, crates/aptos/src/account/list.rs, crates/aptos/src/common/types.rs, crates/aptos/src/config/mod.rs, crates/aptos/src/genesis/git.rs, crates/aptos/src/genesis/keys.rs, crates/aptos/src/genesis/mod.rs, crates/aptos/src/genesis/tools.rs, crates/aptos/src/governance/mod.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/node/mod.rs, crates/aptos/src/op/key.rs, crates/aptos/src/test/mod.rs, testsuite/smoke-test/src/aptos_cli/move.rs
This cleans up a bunch more of the command documentation, and a few inputs that were deprecated
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5058)
=> [cli] Add more docs & cleanup deprecated fields

Cargo.lock, api/Cargo.toml, api/types/Cargo.toml, aptos-move/aptos-aggregator/Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-sdk-builder/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/framework/Cargo.toml, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/package-builder/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, crates/aptos-rest-client/Cargo.toml, ecosystem/sf-indexer/firehose-stream/Cargo.toml, execution/executor/Cargo.toml, storage/aptosdb/Cargo.toml, storage/indexer/Cargo.toml, storage/storage-interface/Cargo.toml, types/Cargo.toml
Also needs to update some outdated sdk builder stuff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5076)
=>  [move] Update commit hash (cherry-pick #5074) 

developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/index.md
@geekflyer can you land this when approved? Thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5079)
=> [Docs] Link fixes.

developer-docs-site/docs/reference/telemetry.md
Land asap when approved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5069)
=> [Docs] Updates to the telemetry doc.

developer-docs-site/docs/whats-new-in-docs.md
Adding latest docs updates
Local build and test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5003)
=> Add Explorer, Petra Wallet, and Aptos resources updates to What's New in Docs

terraform/helm/fullnode/templates/backup-verify.yaml
Test plan: helm apply to failing job
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5089)
=> [backup] Fix toml -> yaml for backup verify

scripts/devnet_message.sh, terraform/aptos-node-testnet/main.tf, terraform/aptos-node-testnet/variables.tf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5031)
=> [testnet] Add ability to pass storage class to testnet

storage/aptosdb/src/lib.rs
We have to make sure the coming requests always follows local data.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5088)
=> [storage] consolidate save_transactions

developer-docs-site/docs/concepts/base-gas.md, package.json
this seems to be breakign docs builds, which assumes npm
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5133)
=> roll back pnpm default package manager

developer-docs-site/docs/concepts/basics-accounts.md, developer-docs-site/docs/guides/interacting-with-the-blockchain.md, ecosystem/typescript/sdk/src/aptos_client.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5123)
=> [docs] Cleanup account address output formats and module names

developer-docs-site/docs/reference/telemetry.md
Found a broken link to a Rust file, found the latest contents, and am fixing the link.
Local build and test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5102)
=> Update telemetry.md with fixed link to moved build_information.rs file

crates/aptos-logger/src/aptos_logger.rs
using try_send and recv_timeout
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5126)
=> [logging] make sure flush doesn't block

crates/aptos-logger/src/aptos_logger.rs
using try_send and recv_timeout
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5136)
=> [logging] make sure flush doesn't block (#5126)

.github/workflows/docker-build-test.yaml
forgot to do this with testnet update
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5140)
=> [gha] update base image in compat test

developer-docs-site/docs/concepts/coin-and-token/aptos-token.md
Add more details to the token standard 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5138)
=> [Token] update the standard doc

api/src/tests/converter_test.rs, api/types/src/move_types.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5156)
=> [api] Fix some output validation

crates/aptos-rest-client/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5161)
=> Fix wait for error message

mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs, mempool/src/tests/core_mempool_test.rs
For use in mempool and general health (gas schedule) dashboards.
Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5100)
=> [mempool] add bucket to latency stats (#5057)

aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/write_set_too_large.exp, aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/write_set_too_large.move
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4982)
=> add test for STORAGE_WRITE_LIMIT_REACHED

developer-docs-site/docs/issues-and-workarounds.md, developer-docs-site/docs/nodes/full-node/run-a-fullnode-on-gcp.md
- Fixing links.
- General line editing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5164)
=> [Docs] Fixing links and line editing.

api/src/tests/converter_test.rs, api/types/src/move_types.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5172)
=> [cherry-pick-testnet][api] Handle unparsable utf-8 on output

developer-docs-site/docs/nodes/indexer-fullnode.md
cc: @geekflyer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5158)
=> [Docs] Calling out that Docker is not supported yet for indexer fullnode

aptos-move/aptos-vm/src/aptos_vm_impl.rs
Hotfix for metadata cache
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5180)
=> [vm] Flush metadata cache on new session creation

.github/actions/replay-verify/action.yaml, .github/workflows/nightly-replay-verify.yaml, .github/workflows/replay-verify-mainnet.yaml, .github/workflows/replay-verify-testnet.yaml, storage/backup/backup-cli/src/coordinators/replay_verify.rs, storage/backup/backup-cli/src/metadata/cache.rs, storage/backup/backup-cli/src/metadata/mod.rs, storage/backup/backup-cli/src/metadata/view.rs
1. Replay LLT transactions starting from 142m versions because it's known to be broken before that.
2. replay in parallel (processes) to better utilize concurrency. (The parallel executor is not effective because the blocks are too small)
3. also replay the mainnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5011)
=> [gha] replay-verify in parallel

.github/actions/replay-verify/action.yaml, .github/workflows/replay-verify-mainnet.yaml, .github/workflows/replay-verify-testnet.yaml, storage/aptosdb/src/state_restore/mod.rs, storage/jellyfish-merkle/src/restore/mod.rs
To make it faster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5206)
=> [gha] use beefy machine to replay-verify

config/src/config/state_sync_config.rs
This PR updates the state sync configurations to default to execution mode.
Existing test infra.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5229)
=> [State Sync] Default to execution mode.

consensus/src/block_storage/block_store.rs, consensus/src/block_storage/block_tree.rs, consensus/src/epoch_manager.rs, consensus/src/liveness/leader_reputation.rs, consensus/src/network.rs, consensus/src/network_interface.rs, consensus/src/recovery_manager.rs, consensus/src/round_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5186)
=> [consensus][logs] Demote non-critical error logs in consensus

state-sync/aptos-data-client/src/aptosnet/mod.rs, state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs, state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs, state-sync/state-sync-v2/state-sync-driver/src/driver.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5188)
=> [state-sync][logs] Demote non-critical error logs in StateSync

network/src/peer_manager/mod.rs, network/src/peer_manager/transport.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5189)
=> [network][logs] Demote non-critical error logs in Network

api/src/log.rs, crates/aptos-faucet/src/mint.rs, crates/aptos-push-metrics/src/lib.rs, mempool/src/shared_mempool/tasks.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5190)
=> [misc][logging] Demote non-critical error logs in rest

.github/workflows/docker-build-test.yaml, .github/workflows/replay-verify-mainnet.yaml, .github/workflows/replay-verify-testnet.yaml
looks like it's hourly now..
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5232)
=> replay-verify jobs: make it daily

terraform/helm/fullnode/README.md, terraform/helm/fullnode/values.yaml
backup-verify jobs are ooming
testnet backup verification now finishes in an hour.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5247)
=> bump memory for backup-verify job

ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/coin_client.test.ts, ecosystem/typescript/sdk/src/faucet_client.test.ts, ecosystem/typescript/sdk/src/token_client.test.ts, ecosystem/typescript/sdk/src/utils/test_helper.test.ts
I've had user reports that the timeouts were too low (@msmouse) and I just witnessed it myself. This PR bumps the timeouts.
```
yarn test
````
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4933)
=> [TS][SDK] Bump timeouts on tests

terraform/helm/fullnode/templates/_helpers.tpl, terraform/helm/fullnode/templates/backup-verify.yaml, terraform/helm/fullnode/templates/backup.yaml, terraform/helm/fullnode/templates/restore.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5101)
=> [backup] push metrics to vmagent

crates/indexer/src/models/token_models/token_utils.rs, crates/indexer/src/processors/token_processor.rs
collection_data_id is wrong on the token level tables because I mistakenly use the token name to hash instead of the collection name :( 
Verified in DB that after fix the collection name matches. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5223)
=> [Indexer] Fix collection data

crates/indexer/migrations/2022-10-21-055518_stake_to_voter/down.sql, crates/indexer/migrations/2022-10-21-055518_stake_to_voter/up.sql, crates/indexer/src/models/mod.rs, crates/indexer/src/models/stake_models/mod.rs, crates/indexer/src/models/stake_models/stake_utils.rs, crates/indexer/src/models/stake_models/staking_pool_voter.rs, crates/indexer/src/models/token_models/token_utils.rs, crates/indexer/src/processors/mod.rs, crates/indexer/src/processors/stake_processor.rs, crates/indexer/src/processors/token_processor.rs, crates/indexer/src/runtime.rs, crates/indexer/src/schema.rs
Parsing staking pool to voter address mapping from StakingPool resource. 
We get exactly 102 which is what we expect. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5215)
=> [Indexer] Staking pool to voter mapping

developer-docs-site/docs/guides/indexing.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5205)
=> [Docs] Adding rate limits section.

crates/aptos/Cargo.toml
I realized this is how we're doing it in other places too.
👀
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5293)
=> [CLI] Only depend on jemalloc crate on unix

aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/bcs.move, aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib_incompat/sources/bcs.move, aptos-move/framework/move-stdlib/doc/bcs.md, aptos-move/framework/move-stdlib/sources/bcs.move
- Fix broken BCS links.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5322)
=> Fix broken BCS links

ecosystem/python/sdk/aptos_sdk/client.py
I used it today and fixed it.
human test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5315)
=> [python-sdk] fix client.py offer_token and claim_token

developer-docs-site/docs/guides/move-guides/upgrading-move-code.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5311)
=> Edit Upgrading Move Code

crates/aptos/src/common/init.rs
Just a small typo in profile creation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5273)
=> chore: fix typo in aptos cli for profile creation

aptos-move/framework/aptos-token/sources/token.move
Fix comment typo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5220)
=> Fix comment

crates/aptos/src/move_tool/stored_package.rs
See the issue: https://github.com/aptos-labs/aptos-core/issues/5233
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5234)
=> [cli] Fix move download error

developer-docs-site/package.json, developer-docs-site/src/components/BlockQuote/index.tsx, developer-docs-site/src/components/Cards/BaseContainer/index.tsx, developer-docs-site/src/components/Cards/CardsWrapper/index.tsx, developer-docs-site/src/components/Cards/SimpleTextCard/index.tsx, developer-docs-site/src/components/Cards/WithBackgroundImage/index.tsx
While playing around with the docs site I noticed tsx wasn't formatted / linted. This PR fixes that.
```
yarn fmt
yarn lint
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5344)
=> [docs] Run fmt / lint on tsx in docs site

execution/executor-benchmark/src/main.rs
gas is expensive now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5332)
=> [executor-benchmark] more default initial balance

.github/actions/replay-verify/action.yaml, storage/backup/backup-cli/src/backup_types/transaction/restore.rs
Increase concurrency to leverage super large memory on the instance we currently use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5266)
=> replay-verify: more processes

aptos-move/move-examples/resource_account/sources/simple_defi.move
we recently changed how we generate resource account address, so need to update the unit test as well 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5361)
=> [move-examples] fixed simple defi's unit test

aptos-move/framework/aptos-token/sources/token.move
add error wrapper around the error code 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5371)
=> [token] add error wrapper

crates/indexer/migrations/2022-10-30-053525_add_vote_data/down.sql, crates/indexer/migrations/2022-10-30-053525_add_vote_data/up.sql, crates/indexer/src/indexer/fetcher.rs, crates/indexer/src/indexer/tailer.rs, crates/indexer/src/models/stake_models/mod.rs, crates/indexer/src/models/stake_models/proposal_votes.rs, crates/indexer/src/models/stake_models/stake_utils.rs, crates/indexer/src/models/token_models/ans_lookup.rs, crates/indexer/src/processors/stake_processor.rs, crates/indexer/src/processors/token_processor.rs, crates/indexer/src/runtime.rs, crates/indexer/src/schema.rs
Token name
votes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5355)
=> [Indexer] Add proposal votes table and token name in ans

aptos-move/framework/src/natives/cryptography/multi_ed25519.rs
This change fixes the warning occurred while building aptos cli.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5418)
=> fix aptos build warning

consensus/src/epoch_manager.rs, consensus/src/liveness/leader_reputation.rs, consensus/src/liveness/leader_reputation_test.rs, types/src/on_chain_config/consensus_config.rs
not yet backward compatible
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4973)
=> [consensus] Fix voting history for leader reputation

api/Makefile, api/doc/spec.json, api/doc/spec.yaml, api/src/accounts.rs, api/src/transactions.rs, ecosystem/typescript/sdk/src/aptos_client.ts, ecosystem/typescript/sdk/src/generated/services/AccountsService.ts, ecosystem/typescript/sdk/src/generated/services/TransactionsService.ts
Address feedback in Discord regarding transaction retrieval.
Include relevant changes from:
https://github.com/aptos-labs/aptos-core/pull/5343
https://github.com/aptos-labs/aptos-core/pull/3397
Local build and test. See new internal docs for flow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5376)
=> Clarify which endpoints return committed / pending transactions

Cargo.lock, testsuite/forge-cli/Cargo.toml, testsuite/forge-cli/src/main.rs
Same as for https://github.com/aptos-labs/aptos-core/pull/5249.
Forge run in CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5254)
=> Use jemalloc for the forge CLI

consensus/src/block_storage/block_store_test.rs, consensus/src/block_storage/sync_manager.rs, consensus/src/experimental/tests/buffer_manager_tests.rs, consensus/src/experimental/tests/phase_tester.rs, consensus/src/network_tests.rs, consensus/src/quorum_store/direct_mempool_quorum_store.rs, consensus/src/round_manager_test.rs, consensus/src/test_utils/mock_state_computer.rs, consensus/src/test_utils/mock_storage.rs, consensus/src/test_utils/mod.rs, consensus/src/twins/basic_twins_test.rs, consensus/src/twins/twins_node.rs
Fixing issue https://aptoslabs.pagerduty.com/postmortems/1721c26b-3ee6-4b46-0ae2-f3d49a464b47
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5309)
=> [consensus] Additional round manager test and fixing block retrieval panic

terraform/helm/testnet-addons/templates/loadtest.yaml
=> [helm][testnet-addons] fix loadtest resource spec

developer-docs-site/netlify.toml
We should define this kind of thing in the repo. That way we can change it atomically, vs making changes in code and then changing things in the UI.
You can see the build works here: https://app.netlify.com/sites/aptos-developer-docs/deploys/6365ac035c730d0009b42fee.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5460)
=> Define build configuration in netlify.toml for dev docs site

mempool/README.md
Fixed a typo in a mempool/README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4914)
=> [mempool] fix typo

aptos-move/framework/aptos-token/doc/token.md, aptos-move/framework/aptos-token/sources/token.move
1. update the field description 
2. organize the functions without changing its content
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5435)
=> [Token] update the field doc and re-organize code

ecosystem/python/sdk/Makefile, ecosystem/python/sdk/examples/hello-blockchain.py
As https://github.com/aptos-labs/aptos-core/pull/4858, we should also format `setup.py`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4947)
=> add all python file in sdk folder to format and fix some typo

developer-docs-site/docs/tutorials/first-move-module.md
Fix typo error.
Previous: call REST API from local host
Following: call REST API from devnet node (In the same flow as the example above)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4952)
=> Fix: Typos

developer-docs-site/docs/tutorials/first-dapp.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5125)
=> [docs] aptos-client types in tutorial are fixed

ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/aptos_client.ts
Support multi transaction simulation.  (https://github.com/aptos-labs/aptos-core/issues/5117)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5119)
=> [typescript-sdk] support multisig transaction simulation

ecosystem/typescript/sdk/src/index.ts
export all from ./aptos_types
solve the error when importing types inside it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5120)
=> export aptos_types

developer-docs-site/docs/concepts/basics-accounts.md, developer-docs-site/docs/guides/indexing.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5207)
=> [Docs] Note on account address.

.github/workflows/docker-build-test.yaml
use the testnet_ -prefixed release image
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5283)
=> [gha] update compat image to testnet prefix

config/src/config/state_sync_config.rs, state-sync/storage-service/server/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5363)
=> [cherry-pick][State Sync] Reduce max message size and increase timeout.

CODEOWNERS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5351)
=> [codeowners] Added owners for aggregator

aptos-move/framework/aptos-framework/sources/account.move
@davidiw
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5350)
=> Correct typo in resource account doc comment

aptos-move/framework/README.md
Link to the latest docs. Work in all available versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5438)
=> Update Aptos Framework README to link to new reference files in all versions

Cargo.lock, Cargo.toml, aptos-move/aptos-gas/src/gen.rs, aptos-move/aptos-release-builder/Cargo.toml, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-release-builder/src/components/framework.rs, aptos-move/aptos-release-builder/src/components/gas.rs, aptos-move/aptos-release-builder/src/components/mod.rs, aptos-move/aptos-release-builder/src/components/version.rs, aptos-move/aptos-release-builder/src/lib.rs, aptos-move/aptos-release-builder/src/main.rs, aptos-move/aptos-release-builder/src/utils.rs, testsuite/smoke-test/Cargo.toml, testsuite/smoke-test/src/upgrade.rs
…we need for new releases.
Implement a tool to generate all the governance proposal scripts we need for releases.
Updated the `upgrade` smoke test to use this new tool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5403)
=> [aptos-release-tooling] Implement a tool to generate all the governance proposal scripts

.github/workflows/close-stale-issues.yaml
This will auto mark and close stale issues using https://github.com/actions/stale to cleanup our issue backlog a bit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5468)
=> auto mark and close stale issues

.github/workflows/close-stale-issues.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5475)
=> allow manual triggering of stale issue workflow

.github/workflows/docker-build-test.yaml
missed it on the compat test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5495)
=> [gha] remove docker build performance dependency from compat

developer-docs-site/docs/sdks/ts-sdk/index.md
Add links to @banool 's new auto-generated docs.
Local build and test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5535)
=> Add TypeScript SDK Reference Source files to TS overview

developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-source-code.md
Addressing input from Aptos Node Community channel.
Local build and test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5534)
=> Replace cargo run with running binaries directly in fullnode source setup

ecosystem/typescript/sdk/package.json, ecosystem/typescript/sdk/pnpm-lock.yaml, ecosystem/typescript/sdk/src/generated/core/request.ts
regenerate openapi client
pnpm run generate-client
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5528)
=> feat: more meaningful message for HTTP code 429

Cargo.toml
This PR adds comments around the move deps, as required by @wrwg's tooling 😄 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5565)
=> [Cargo] Add comments around move deps.

config/src/config/consensus_config.rs, consensus/src/counters.rs, consensus/src/epoch_manager.rs, consensus/src/liveness/cached_proposer_election.rs, consensus/src/liveness/leader_reputation.rs, consensus/src/liveness/leader_reputation_test.rs, consensus/src/liveness/proposal_generator.rs, consensus/src/liveness/proposal_generator_test.rs, consensus/src/liveness/proposer_election.rs, consensus/src/liveness/unequivocal_proposer_election.rs, consensus/src/round_manager_fuzzing.rs, consensus/src/round_manager_test.rs
To avoid ever reaching unstable state
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4834)
=> [consensus] Add gracefull backoff based on chain health

Cargo.lock, api/Cargo.toml, api/types/Cargo.toml, aptos-move/aptos-aggregator/Cargo.toml, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-gas/src/move_stdlib.rs, aptos-move/aptos-module-verifier/Cargo.toml, aptos-move/aptos-sdk-builder/Cargo.toml, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/framework/Cargo.toml, aptos-move/framework/cached-packages/Cargo.toml, aptos-move/framework/src/built_package.rs, aptos-move/framework/src/error_map.rs, aptos-move/framework/tests/move_unit_test.rs, aptos-move/gas-algebra-ext/Cargo.toml, aptos-move/move-deps/Cargo.toml, aptos-move/move-examples/tests/move_unit_tests.rs, aptos-move/package-builder/Cargo.toml, aptos-move/vm-genesis/Cargo.toml, crates/aptos-rest-client/Cargo.toml, crates/aptos/src/move_tool/mod.rs, ecosystem/sf-indexer/firehose-stream/Cargo.toml, execution/executor/Cargo.toml, storage/aptosdb/Cargo.toml, storage/indexer/Cargo.toml, storage/storage-interface/Cargo.toml, types/Cargo.toml
This specifically updates us to the fixes [here](https://github.com/move-language/move/pull/669). Some updates on test related infra are also needed in order to be able to take this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5575)
=> [hotfix] Update for hotfix of Move VM issues

aptos-move/aptos-gas/src/gas_meter.rs
By default, the memory usage tracker considers the memory released when values enter a native function. This is however not the desired behavior for the event natives as the values stay in the event buffer until the end of the transaction. This gets it fixed by considering the memory leaked conceptually.
The change is gated by a new gas feature version (4).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5377)
=> [gas] consider memory leaked for values entering the event natives

ecosystem/typescript/sdk/examples/javascript/index.js, ecosystem/typescript/sdk/examples/typescript-esm/index.ts, ecosystem/typescript/sdk/examples/typescript/bcs_transaction.ts
fix sdk examples logs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5569)
=> [TS-SDK]fix sdk examples logs

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
Caught with Aspell and Daniel. :-)
in browser-edit and review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5583)
=> Fix typos in Using Aptos CLI

aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-stdlib/doc/comparator.md, aptos-move/framework/aptos-token/doc/token.md, aptos-move/framework/aptos-token/sources/token.move
no valid usecase for royalty can exceed the txn price
cargo test -p framework
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5444)
=> [Token] enforce royalty numerator is smaller or equal to denominator

aptos-move/vm-genesis/src/lib.rs, crates/aptos-genesis/src/builder.rs, crates/aptos-genesis/src/lib.rs, crates/aptos/src/genesis/mod.rs, types/src/on_chain_config/mod.rs
Used in #4986 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5527)
=> [smoke-test][genesis] enabling configuring genesis onchain configs in test

ecosystem/typescript/sdk/src/aptos_client.ts
This should help with https://github.com/aptos-labs/aptos-core/issues/5589, @jjleng was right to begin with 😛. Yet to be confirmed though.
todo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5590)
=> [TS][SDK] Use larger pagination values

Cargo.toml, api/Cargo.toml, api/openapi-spec-generator/Cargo.toml, api/test-context/Cargo.toml, api/types/Cargo.toml
This PR update all crates under the `api` directory to use workspace dependencies.
Relying on existing testing infrastructure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5592)
=> [API] Move to workspace dependencies.

developer-docs-site/README.md
We should explain how to avoid build breakage by properly formatting JS and other files in the docs repo.
In-browser edit and review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5603)
=> Add Format command to Dev Site Build docs

developer-docs-site/docs/whats-new-in-docs.md
Quick fix to link nav
Also sussing out how to make links work in GitHub too
(or not for named anchors in this case)
Local build and test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5606)
=> Fix links in See What's New by using Markdown extension sometime

developer-docs-site/docs/guides/move-guides/index.md
Accidentally replaced it.
In-browser edit and review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5624)
=> Restore Move Book link at move-language.github.io

developer-docs-site/docs/concepts/basics-accounts.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5623)
=> [Docs only] Update Concepts > Accounts page

testsuite/forge.py
Fixing grafana dashboard links for Forge.
Run Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5604)
=> [Forge] Fix grafana dashboard link

developer-docs-site/docs/guides/move-guides/move-on-aptos.md, developer-docs-site/docs/guides/move-guides/upgrading-move-code.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5610)
=> docs: minor updates and wording of Move docs

developer-docs-site/docs/concepts/basics-accounts.md
Use a relative link and Markdown format to make link work in GitHub and on Aptos.dev.
Local build and test
=> Fix link from Accounts to Your First Transaction

developer-docs-site/docs/whats-new-in-docs.md
Indexer rate limit increase in See What's New
In-browser edit and test
=> Announce Indexer rate limit increase

developer-docs-site/docs/concepts/basics-accounts.md
Replace Address account with Standard account in Accounts concept
In-browser edit, test and review
=> Replace Address account

developer-docs-site/docs/sdks/ts-sdk/typescript-sdk-overview.md, developer-docs-site/scripts/additional_dict.txt
Updates Typescript SDK overview page
=> [DOC] Typescript SDK overview page

.github/workflows/lint-test.yaml
=> [gha] increase smoke test retention 1 day -> 14 days

developer-docs-site/docs/nodes/local-testnet/run-a-local-testnet.md
Addressing:
https://github.com/aptos-labs/aptos-core/issues/5465
In-browser edit and review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5620)
=> Remove Docker option from running a local testnet

.github/mergify.yml
=> cicd: fix regex in mergify config

developer-docs-site/docs/whats-new-in-docs.md
=> Fix silly typos on Whats New page

developer-docs-site/docs/nodes/validator-node/operator/update-validator-node.md
=> Remove reference to epoch change in VN failover doc

developer-docs-site/docs/nodes/validator-node/operator/update-validator-node.md
"even" looks redundant in this sentence.
=> [doc] trival fix

Cargo.lock, Cargo.toml, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/e2e-move-tests/src/tests/type_too_large.data/type_too_large/Move.toml, aptos-move/e2e-move-tests/src/tests/type_too_large.data/type_too_large/sources/test.move, aptos-move/e2e-move-tests/src/tests/type_too_large.rs, aptos-move/framework/aptos-stdlib/doc/type_info.md, aptos-move/framework/aptos-token/doc/token.md, consensus/src/liveness/proposal_generator.rs, crates/aptos-crypto/src/multi_ed25519.rs
- Update of Move commit hash to take https://github.com/move-language/move/pull/703
- Adding an e2e move tests to verify effect of above Move commit
- Fix of one-off error in multied25519
=> [move] Multiple fixes

crates/aptos/src/move_tool/mod.rs
The command line inputs would require quotes around them (depending on your shell), but you should be able to send vectors now of any type (a much requested feature)
Successfully tested manually
```
./target/debug/aptos move run --args 'vector<address>:greg,default' 'u64:5' --function-id default::multiple_transfer::transfer 
Do you want to submit a transaction for a range of [86700 - 130000] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
"Result": {
"transaction_hash": "0xb61fb3a3491c263f24f60372a9b2509ced00ed39b7880bad5933c50b38674427",
"gas_used": 935,
"sender": "b6dbf76636021a840c64da0ca6aa94297b4ead015f7398521f57347f68364898",
"sequence_number": 5,
"timestamp_us": 1666316889927270,
"version": 13885786,
"vm_status": "Executed …
```
=> [cli] Add vector support for command line inputs

.github/workflows/replay-verify-mainnet.yaml, .github/workflows/replay-verify-testnet.yaml
To recover the nightly replay jobs.
=> [txn-replay] set HISTORY_START to known compatible versions

state-sync/storage-service/server/src/tests.rs
This PR refactors some of the storage service tests to reduce code duplication and readability. It also updates a couple tests to explicitly check that at least 1 item is returned even when data is larger than the maximum network frame size.
=> [State Sync] Refactor storage service tests.

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
bump TS SDK version from 1.3.18 to 1.4.0
=> [TS SDK ] bump version to 1.4.0

developer-docs-site/docs/nodes/full-node/bootstrap-fullnode.md
=> Edit Bootstrap a New Fullnode and Remove AIT3 reference

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/index.ts, ecosystem/typescript/sdk/src/token_types.ts, ecosystem/typescript/sdk/src/utils/property_map_serde.test.ts
Export classes and functions from property_map_serde. SDK users will be able to import these from the top level of exports from the SDK.
yarn test
=> chore: export classes and functions from property_map_serde

aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/e2e-move-tests/src/tests/token_event_store.rs, aptos-move/framework/aptos-framework/doc/resource_account.md, aptos-move/framework/aptos-token/doc/overview.md, aptos-move/framework/aptos-token/doc/token.md, aptos-move/framework/aptos-token/doc/token_event_store.md, aptos-move/framework/aptos-token/doc/token_event_utils.md, aptos-move/framework/aptos-token/sources/token.move, aptos-move/framework/aptos-token/sources/token_event_store.move, aptos-move/framework/aptos-token/sources/token_event_utils.move
Add the missing events for key token functions
Test with a move e2e test on one event
=> [Token] Add token events

aptos-move/framework/aptos-token/doc/token_event_store.md, aptos-move/framework/aptos-token/sources/token_event_store.move
=> [token] fix a typo

developer-docs-site/sidebars.js
=> Remove Bootstrap Fullnode doc from nav temporarily

crates/aptos/src/move_tool/mod.rs
Fixes bug where you can't clean the cache without a build directory.
Closes https://github.com/aptos-labs/aptos-core/issues/5387
```
aptos move clean
Do you also want to delete the local package download cache at `/Users/greg/.move`? [yes/no] >
y
{
"Result": "succeeded"
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5500)
=> [cli] Allow to clean cache without a build dir

docker/release-images.mjs
So we can publish `performance` build to dockerhub. The naming convention is: `[REF_PREFIX][PROFILE_PREFIX][FEATURES_PREFIX]GIT_SHA`
So for example for the next testnet release, we might ask folks validators and fullnodes to switch to something like: `testnet_performance_d7fe6d2f68e6b25bddce8e13546e0b24076f47a5`, which is the validator image compiled with no features but on the performance profile
Where we might have indexers switch to `testnet_indexer_d7fe6d2f68e6b25bddce8e13546e0b24076f47a5`. Where indexer is only built with the default release profile but with the indexer feature
Run the script while printing the cmds
Also created a `nightly` branch to trigger a re-release of nightly images as a canary: 
* job triggered: https://github.com/aptos-labs/aptos-core/actions/runs/3596026380/j …
=> [docker] publish different build profiles

.cargo/config.toml, docker/rust-all.Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5573)
=> [Dockerfile] validator testing for bcc

developer-docs-site/docs/guides/indexing.md, developer-docs-site/docs/whats-new-in-docs.md
=> docs: update PFN and indexer rate limits

api/doc/spec.json, api/doc/spec.yaml, api/types/src/index.rs, ecosystem/typescript/sdk/src/generated/models/IndexResponse.ts, ecosystem/typescript/sdk/src/generated/schemas/$IndexResponse.ts
It was called out that there was no documentation for this field, and now there is.
CI
=> [api] Add doc comment for git hash in index API

developer-docs-site/docs/guides/handle-aptos-errors.md
=> update MODULE_ADDRESS_DOES_NOT_MATCH_SENDER description

developer-docs-site/scripts/additional_dict.txt
=> add Ohlone to dict

.github/actions/gar-auth/action.yaml, .github/actions/rust-setup/action.yaml, .github/workflows/copy-images-to-dockerhub.yaml, .github/workflows/docker-rust-build.yaml, .github/workflows/lint-test.yaml, .github/workflows/sdk-release.yaml, docker/docker-bake-rust-all.hcl, docker/docker-bake-rust-all.sh, docker/rust-all.Dockerfile
[gha] Add composite action for git credentials
Summary: Easy support for composite actions across workflows
Test Plan: see the jobs pass in the PR
=> [gha] Add composite action for git credentials

Cargo.lock, Cargo.toml, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/framework/aptos-framework/doc/aptos_account.md, aptos-move/framework/aptos-framework/doc/block.md, aptos-move/framework/aptos-framework/doc/state_storage.md, aptos-move/framework/aptos-stdlib/doc/type_info.md, aptos-move/framework/aptos-token/doc/token.md
See the individual commits. This also updates us to the Move state after move-language/move#718.
=> [hotfixes] Update testnet branch with the most recent hotfixes

developer-docs-site/docs/whats-new-in-docs.md
=> Announce Aptos Developer Experience Survey in See what

aptos-move/framework/aptos-framework/doc/voting.md
=> trivial: build cached-packages

Cargo.lock
Update the lock file after the crate refactor.
Existing infra.
=> [Cargo] Update lock file.

aptos-move/framework/aptos-framework/doc/aggregator.md, aptos-move/framework/aptos-framework/doc/version.md
This PR updates the broken move docs. I think this slipped through before the latest check was added (looking at the PR, it appears the check didn't actually run, so I'm hoping it was a merge issue 🤷): https://github.com/aptos-labs/aptos-core/pull/5653
Hopefully this will be the last. If not, I'll need to dig.
=> [Move Documentation] Update broken move documentation.

developer-docs-site/docs/guides/wallet-adapter-for-dapp.md
=> Fix title in new page

aptos-move/framework/aptos-framework/sources/aptos_coin.move
=> [test helper] add function to enable initializing and minting of aptos coin with genesis

docker/build-rust-all.sh, docker/rust-all.Dockerfile, execution/db-bootstrapper/src/bin/aptos-db-bootstrapper.rs, testsuite/smoke-test/src/genesis.rs, types/src/transaction/mod.rs
This PR fixes some build scripts after the large crate rename. These scripts were missed.
Existing test infrastructure!
=> [Build scripts] Fix some build scripts after crate renames.

developer-docs-site/docs/nodes/node-health-checker/index.md
=> Link to Node Health Checker Web UI from NHC page

aptos-move/move-examples/marketplace/sources/marketplace_auction_example.move, aptos-move/move-examples/marketplace/sources/marketplace_bid_utils.move, aptos-move/move-examples/marketplace/sources/marketplace_listing_utils.move, aptos-move/move-examples/tests/move_unit_tests.rs
* Looks like not everything was being tested
* Each test had a lot of boiler plate
* The marketplace examples had consts that broke general testing
=> [move-examples] cleanup testing

developer-docs-site/docs/whats-new-in-docs.md
On AIPs and the technical implementation of Aptos Governance
=> Announce Aptos Governance rename and additional resources

developer-docs-site/docs/concepts/base-gas.md
=> Fix links in How Base Gas Works to moved/renamed transaction/mod.rs file

developer-docs-site/docs/guides/getting-started.md
=> Link to documentation directory from Getting Started

developer-docs-site/docs/whats-new-in-docs.md
=> Name and link directly to aptos-node-v1.1.0 release from See what's new

docker/rust-all.Dockerfile
=> [validator-test] binding docker to specific bcc commit

api/doc/spec.json, api/doc/spec.yaml, api/src/transactions.rs, ecosystem/typescript/sdk/src/generated/services/TransactionsService.ts
Fixes the documentation related to the input variables
Closes https://github.com/aptos-labs/aptos-core/issues/4710
=> [api] Fix documentation around start field for account transactions

.github/workflows/continuous-e2e-account-creation-test.yaml, .github/workflows/continuous-e2e-changing-working-quorum-test copy.yaml, .github/workflows/continuous-e2e-changing-working-quorum-test-high-load.yaml, .github/workflows/continuous-e2e-compat-test.yaml, .github/workflows/continuous-e2e-consensus-stress-test.yaml, .github/workflows/continuous-e2e-different-node-speed-and-reliability-test.yaml, .github/workflows/continuous-e2e-full-node-reboot-stress-test.yaml, .github/workflows/continuous-e2e-graceful-overload-test.yaml, .github/workflows/continuous-e2e-haproxy-test.yaml, .github/workflows/continuous-e2e-network-latency-test.yaml, .github/workflows/continuous-e2e-network-latency-with-different-node-speed-test.yaml, .github/workflows/continuous-e2e-network-partition-test.yaml, .github/workflows/continuous-e2e-nft-mint-test.yaml, .github/workflows/continuous-e2e-performance-test.yaml, .github/workflows/continuous-e2e-validator-reboot-stress-test.yaml, .github/workflows/twin-validator-test.yaml
This PR reduces the frequency of our continuous test jobs from every 3 hours, to every 12 hours.
=> [Forge] Reduce test run frequency.

aptos-move/framework/aptos-stdlib/doc/simple_map.md, aptos-move/framework/aptos-stdlib/sources/simple_map.move
as title.
I should have taken a look...
ut
=> [simple_map] remove unnecessary bubble sort

Cargo.lock, crates/aptos/Cargo.toml
Fixes CLI compiliation issue due to Move language version issues
=> [cli] Bump to 1.0.3

execution/executor-types/src/in_memory_state_calculator.rs, execution/executor/src/block_executor.rs, execution/executor/src/components/apply_chunk_output.rs, execution/executor/src/metrics.rs, storage/aptosdb/src/event_store/mod.rs, storage/aptosdb/src/event_store/test.rs, storage/aptosdb/src/ledger_store/ledger_info_test_utils.rs, storage/aptosdb/src/ledger_store/mod.rs, storage/aptosdb/src/ledger_store/transaction_info_test.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/event_store/test.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/pruner/transaction_store/test.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/aptosdb/src/test_helper.rs, storage/aptosdb/src/transaction_store/mod.rs, storage/aptosdb/src/transaction_store/test.rs
10%~20% improvement when db is not huge, on a 128vCPU machine.
=> [Execution/Commit] Tiny optimizations.

Cargo.lock, Cargo.toml, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/gas.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/e2e-move-tests/src/tests/token_event_store.rs, aptos-move/framework/aptos-framework/doc/aptos_account.md, aptos-move/framework/aptos-framework/doc/block.md, aptos-move/framework/aptos-framework/doc/resource_account.md, aptos-move/framework/aptos-framework/doc/state_storage.md, aptos-move/framework/aptos-stdlib/doc/simple_map.md, aptos-move/framework/aptos-stdlib/doc/type_info.md, aptos-move/framework/aptos-stdlib/sources/simple_map.move, aptos-move/framework/aptos-token/doc/overview.md, aptos-move/framework/aptos-token/doc/property_map.md, aptos-move/framework/aptos-token/doc/token.md, aptos-move/framework/aptos-token/doc/token_event_store.md, aptos-move/framework/aptos-token/doc/token_event_utils.md, aptos-move/framework/aptos-token/sources/property_map.move, aptos-move/framework/aptos-token/sources/token.move, aptos-move/framework/aptos-token/sources/token_event_store.move, aptos-move/framework/aptos-token/sources/token_event_utils.move
=> [token] cherry pick token changes for mainnet release

terraform/helm/aptos-node/templates/fullnode.yaml, terraform/helm/aptos-node/templates/validator.yaml, testsuite/forge-cli/src/main.rs, testsuite/forge/src/backend/k8s/cluster_helper.rs, testsuite/forge/src/backend/k8s/mod.rs, testsuite/forge/src/backend/local/mod.rs, testsuite/forge/src/interface/factory.rs, testsuite/forge/src/runner.rs
Add the capability to claim an existing PV using a specified tag.
Manually verified that this can successfully mount an existing EBS volume.
=> [Forge] Add basic support for large db test in forge.

.github/actions/verify-modules/action.yaml, .github/workflows/replay-verify-testnet.yaml, .github/workflows/verify-on-chain-modules-mainnet.yaml, .github/workflows/verify-on-chain-modules-testnet.yaml, aptos-move/aptos-vm/src/aptos_vm.rs, execution/executor/src/chunk_executor.rs
Cherry pick #5849 and #5898 into the release branch.
#5849 is needed for future move hotfixes, where I added a new CI job called `verify-modules` that could verify existing move modules with the current verifier config.
#5898 is needed for fixing a file format compatibility issue.
NA
=> Cherry Pick PRs

Cargo.lock, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/src/counters.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/output_delta_resolver.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/block-executor/src/view.rs, aptos-move/mvhashmap/Cargo.toml, aptos-move/mvhashmap/src/lib.rs, aptos-move/mvhashmap/src/unit_tests/proptest_types.rs, config/src/config/consensus_config.rs, config/src/config/execution_config.rs, consensus/src/liveness/proposal_generator.rs, execution/executor/src/block_executor.rs, storage/storage-interface/src/cached_state_view.rs, testsuite/forge-cli/src/main.rs, testsuite/forge.py, testsuite/forge/src/runner.rs, types/src/access_path.rs
- Changes to add various latency metrics
- Config tuning to reach 10k TPS.
-
=> concurrency

consensus/src/liveness/proposal_generator.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/transaction_generator/p2p_transaction_generator.rs, testsuite/forge/src/runner.rs
=> Update txn emitter to produce p2p txns with less confliction.

.github/actions/replay-verify/action.yaml, .github/actions/verify-modules/action.yaml, .github/workflows/replay-verify-testnet.yaml, .github/workflows/verify-on-chain-modules-mainnet.yaml, .github/workflows/verify-on-chain-modules-testnet.yaml, Cargo.lock, aptos-move/aptos-vm/src/move_vm_ext/mod.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, execution/executor-types/src/lib.rs, execution/executor/src/chunk_executor.rs, execution/executor/src/tests/mod.rs, storage/backup/backup-cli/Cargo.toml, storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs, storage/backup/backup-cli/src/backup_types/tests.rs, storage/backup/backup-cli/src/backup_types/transaction/restore.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, storage/backup/backup-cli/src/bin/db-restore.rs, storage/backup/backup-cli/src/bin/replay-verify.rs, storage/backup/backup-cli/src/coordinators/replay_verify.rs, storage/backup/backup-cli/src/coordinators/restore.rs, storage/backup/backup-cli/src/coordinators/verify.rs
=> cherry pick for replay jobs

developer-docs-site/docs/index.md
Now we can link to the ecosystem projects page from the docs page
=> [docs] Update index to have ecosystem projects

README.md
Updating the README with a more up-to-date description of Aptos.
👀
=> Update README with new description of Aptos

developer-docs-site/docs/guides/wallet-standard.md
Add `network` to wallet standard
=> [DOC] add network to wallet standard

developer-docs-site/docs/nodes/full-node/bootstrap-fullnode.md
This PR fixes two tiny links in the fullnode bootstrapping guide.
=> [Docs] Fix broken links in bootstrapping guide.

docker/rust-all.Dockerfile
Currently, the validator-image is built each time because the previous step invalidates the cache. This increases build time as the bcc tools should be built every single time. 
This PR moves the bcc tools and apt-get install steps into a separate build called validator-testing-base and builds the validator-testing image on top of this image. This however means that we need to duplicate steps from validator image to the validator-testing image, but I think we can accept this tradeoff for reduced build times.
CI build
=> [dockerfile] Improve validator-testing image build speed

developer-docs-site/docs/nodes/validator-node/operator/node-requirements.md
=> Remove line indicating cloud is preferred for node operators

developer-docs-site/docs/guides/move-guides/upgrading-move-code.md
=> Link to Use Aptos CLI doc from Upgrade Move Code

CONTRIBUTING.md
=> [doc] correct link url for the word 'repository'

ecosystem/typescript/sdk/src/aptos_types/account_address.test.ts, ecosystem/typescript/sdk/src/aptos_types/account_address.ts
Adds an isValid function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5127)
=> [ts-sdk] Add an isValid function for AccountAddress

terraform/aptos-node/gcp/cluster.tf, terraform/aptos-node/gcp/versions.tf
=> Updating tf version and adding cluster monitoring service for GCP.

CONTRIBUTING.md
This PR updates the contributing guide to mention our standard developer workflow.
=> [Contributing guide] Mention standard developer workflow.

CODEOWNERS
This PR updates the CODEOWNERS file for networking. I think the previous typo meant no-one was getting notifications 😄 
=> [CodeOwners] Update ownership for networking.

developer-docs-site/docs/guides/state-sync.md
This PR fixes a broken link in the new archival node section.
=> [Docs] Small fixes to archival node section.

developer-docs-site/docs/nodes/nodes-landing.md
This PR fixes a small broken link to the health checker (that has now been moved).
Manual verification and pnpm workflow.
=> [Docs] This fixes an old link to the health checker.

network/src/noise/stream.rs
This PR updates the networking code to only make a single call into `poll_write` when writing a network frame to a socket. 
Previously, we were making two calls, one to write the message length (2 bytes) and another to write the message. As a result, the OS was often sending tiny TCP packets along the wire (containing only the 2 bytes), giving us a bad packet utilization ratio. This was reported by some of our auditors. Instead, we now make only as single call to `poll_write` by writing all the data to the socket at once. 
Note: I'd be very surprised if we actually see any practical differences with this change 😄 
This is covered by existing test infrastructure.
=> [Network] Avoid two calls to poll_write for each network frame

crates/aptos/README.md
=> Fix broken link in Aptos CLI

.github/workflows/check-sdk-examples.yaml, crates/indexer/src/util.rs, ecosystem/python/sdk/Makefile, ecosystem/python/sdk/aptos_sdk/bcs.py, ecosystem/python/sdk/aptos_sdk/client.py, ecosystem/python/sdk/aptos_sdk/ed25519.py, ecosystem/python/sdk/aptos_sdk/transactions.py, ecosystem/python/sdk/aptos_sdk/type_tag.py, ecosystem/python/sdk/examples/read-aggregator.py, ecosystem/python/sdk/pyproject.toml, ecosystem/python/sdk/setup.py
* Add aggregator read ability
* Improve errors on resource not found
* Fixing CI/CD runs (work in progress)
* Fix linting issues that crept in due to poor CI/CD
=> Some fixes for python sdk and aggregator support

developer-docs-site/docs/tutorials/first-dapp.md
This fills in some much needed updates to the dapp tutorial as a stopgap to fill things that just are confusing and don't make sense.
1. adds labels to outputs
2. improves the initialization for Petra wallet as well as the CLI
3. Makes sure messages come back out in the way that they're uploaded to the chain
4. Some documentation improvements
I took these all from a run I did through manually.  We'll need a reference implementation updated from it, but we need simple things like CSS and formatting that makes it look a little better.  I'd rather probably scratch this later for something like a tic tac toe, or something more interactive.
=> [docs] My first dapp updates

testsuite/forge-cli/src/main.rs
Note: this PR makes no logical changes.
This PR cleans up some of the code in the Forge CLI. Specifically, single test suites were previously being inlined into one function, which has now grown too large. This PR simply moves all the test suite definitions into their own functions.
=> [Forge] Clean up some of the code in the Forge CLI

network/src/protocols/health_checker/mod.rs
This removes an unnecessary `println!` 😄 
Manual vericiation.
=> [Health Checker] Remove the println!

ecosystem/python/sdk/aptos_sdk/client.py
Adds support for looking up at a ledger version for functions that it made sense for currently https://testnet.aptoslabs.com/v1/spec#/operations/get_account_resource
None
=> [python-sdk] Add ability to request resources at a ledger version

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs
this removes some unused functions and commented code
=> [aptos-vm] cleanup

.github/workflows/lint-test.yaml, ecosystem/python/sdk/aptos_sdk/client.py
=> [python-sdk] ensure folks actually run the linter

developer-docs-site/docs/cli-tools/build-from-source.md
=> Explain when building CLI importance of selecting branch

Cargo.lock, aptos-move/aptos-release-builder/Cargo.toml, aptos-move/aptos-release-builder/data/example.yaml, aptos-move/aptos-release-builder/src/components/consensus_config.rs, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-release-builder/src/components/framework.rs, aptos-move/aptos-release-builder/src/components/gas.rs, aptos-move/aptos-release-builder/src/components/mod.rs, aptos-move/aptos-release-builder/src/components/version.rs, aptos-move/aptos-release-builder/src/main.rs, aptos-move/aptos-release-builder/src/utils.rs, aptos-move/framework/src/release_bundle.rs, crates/aptos-rest-client/src/lib.rs, crates/aptos/src/governance/mod.rs, testsuite/smoke-test/src/upgrade.rs
Cherry picking #5562, #5834, #5796 into framework-mainnet branch.
CI/CD
=> [release-tooling] Cherry pick the release tooling into the framework-mainnet

Cargo.lock, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/e2e-move-tests/Cargo.toml, aptos-move/e2e-move-tests/src/tests/attributes.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/framework/Cargo.toml, aptos-move/framework/src/module_metadata.rs
* ensure that RuntimeModuleMetadataV1 can be safely upgraded
* ensure that only known attributes can be published
=> make module metadata safer

storage/aptosdb/src/lib.rs, storage/aptosdb/src/test_helper.rs, storage/storage-interface/src/lib.rs
In preparation for dynamic packing (based on size) from state sync side.
`cargo test -p aptos-db`
=> [storage] ledger iterators

aptos-move/move-examples/post_mint_reveal_nft/Move.toml, aptos-move/move-examples/post_mint_reveal_nft/sources/minting.move
added logic to dedup token uris; similar to what @jjleng has done in a prev PR 
added an unit test
=> [move-examples] added bucket table to deduplicate token uris

testsuite/smoke-test/src/storage.rs
To detect breakage in build
`cargo test`
=> [storage] trivial: use replay-verify in smoke test

developer-docs-site/README.md, developer-docs-site/docusaurus.config.js, developer-docs-site/package.json, developer-docs-site/scripts/contributors.js, developer-docs-site/src/contributors.json, developer-docs-site/src/theme/DocItem/Footer/index.js
Use a different approach for the contributors info that should work with Netlify.
The src/contributors.json file (which powers the list of Authors at the bottom of doc pages) needs to be manually generated. Run the following command:
```
pnpm contributors
```
And then create a PR with the updated src/contributors.json.
Fixes #5808
See https://github.com/aptos-labs/aptos-core/issues/5808#issuecomment-1347202758 for context
Check if authors are present in Netlify preview
=> [docs] Use a local .json file for contributors.

developer-docs-site/docs/guides/state-sync.md
=> Fix link to Data Pruning from State Sync

developer-docs-site/docs/nodes/measure/index.md, developer-docs-site/docs/nodes/measure/node-inspection-service.md
=> Simplify nodes links in attempt to fix them

developer-docs-site/docs/concepts/accounts.md
=> Link to account.move for more details on key rotation

crates/aptos-infallible/src/mutex.rs
=> fix default mutex

developer-docs-site/docs/index.md, developer-docs-site/docs/whats-new-in-docs.md
=> Announce Authors list in See what's new and on home page

aptos-move/framework/aptos-stdlib/doc/any.md, aptos-move/framework/aptos-stdlib/doc/copyable_any.md, aptos-move/framework/aptos-stdlib/doc/from_bcs.md, aptos-move/framework/aptos-stdlib/sources/any.spec.move, aptos-move/framework/aptos-stdlib/sources/copyable_any.spec.move, aptos-move/framework/aptos-stdlib/sources/from_bcs.spec.move, aptos-move/framework/move-stdlib/doc/acl.md, aptos-move/framework/move-stdlib/sources/acl.spec.move
- Added the specs for `acl`
- Enabled an axiom in`from_bcs`. However, two generic axioms still don't work causing a timeout.
- Completed the specs for `any` and `copyable_any`
=> [Spec] Specified the stdlib module `acl`

aptos-move/framework/aptos-token/doc/token.md, aptos-move/framework/aptos-token/sources/token.move
Add getter functions to get mutability config. 
The function can be used to check if the token's maximum is mutable. 
we need to merge this PR to mainnet to unblock NFT DAO
=> [token] add get functions to get mutability config

developer-docs-site/docs/guides/indexing.md
=> Add devnet indexer link

testsuite/forge/src/backend/k8s/cluster_helper.rs
=> [forge] fix lint

Cargo.lock, crates/aptos/Cargo.toml
This release has some compiler bug fixes, and some extra configuration for the CLI around transaction expiration.
CI
=> [cli] Release 1.0.4

api/src/page.rs
=> Fix `max_transactions_page_size` not working bug

crates/aptos-rest-client/src/lib.rs
(Transient) failure in issuing a rest API call abruptly fails waiting for transaction. Instead, retry again, until expected time is reached.
=> Fix request failure stopping waiting for transaction

docker/release-images.mjs
`validator-testing` image is being used in Forge and other testing environments to debug better. This change makes it such that the releases re-tag images with branch prefixes, such as `testnet`, `mainnet`, `devnet`, etc. in our internal repos.
=> [docker] release validator-testing image internally with new tag

developer-docs-site/docs/tutorials/first-dapp.md
Adds instruction on how to publish a package using the TS SDK in `my first dapp` guide
=> [docs] Publish a move module using ts sdk in my first dapp

aptos-move/aptos-vm-profiling/src/profile_aptos_vm.rs
This PR fixes the current lint failure on `main` introduced by: https://github.com/aptos-labs/aptos-core/pull/3794
=> [Lint] Fix small rust lint failure.

developer-docs-site/docs/guides/getting-started.md, developer-docs-site/docs/whats-new-in-docs.md
=> Split out build dependencies and branch checkout into distinct sections

developer-docs-site/docs/concepts/accounts.md
=> Fix incorrect line break in bullet point

developer-docs-site/docs/tutorials/first-dapp.md
=> Make light edits to expanded Dapp tutorial

.github/workflows/docker-build-test.yaml, .github/workflows/lint-test.yaml
also remove old branch targets
other checks will run when you make a PR / label the PR
=> [gha] run on push to aptos-node-v branches

developer-docs-site/docs/guides/move-guides/index.md
=> Link to Move langauage channel and Aptos Discord from Move docs index

developer-docs-site/docs/concepts/coin-and-token/aptos-token.md, developer-docs-site/docs/whats-new-in-docs.md, developer-docs-site/scripts/additional_dict.txt
=> Compile, summarize and publish doc updates for early Jan. 2023

Cargo.lock, Cargo.toml
This updates the commit hash from the [aptos-main](https://github.com/move-language/move/commit/9ba4d3d40d4c59b0afdf905ace949b0d795a51e8) branch
=> Update commit hash from aptos-main

ecosystem/typescript/sdk/src/bcs/helper.ts
=> Fix typo in comment

aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/framework/src/module_metadata.rs
=> [aptos-vm] Guard usage of new metadata by VM_BINARY_FORMNAT_V6 feature flag (#6175)

docker/rust-all.Dockerfile
=> cherry-pick Dockerfile testing image build failure fix

aptos-move/framework/aptos-framework/doc/aggregator.md, aptos-move/framework/aptos-framework/sources/aggregator/aggregator.spec.move, aptos-move/framework/aptos-stdlib/doc/pool_u64.md, aptos-move/framework/aptos-stdlib/doc/type_info.md, aptos-move/framework/aptos-stdlib/sources/pool_u64.spec.move, aptos-move/framework/aptos-stdlib/sources/type_info.spec.move, aptos-move/framework/move-stdlib/doc/error.md, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/doc/fixed_point32.md, aptos-move/framework/move-stdlib/sources/configs/features.spec.move, aptos-move/framework/move-stdlib/sources/error.move, aptos-move/framework/move-stdlib/sources/fixed_point32.move, aptos-move/framework/move-stdlib/sources/vector.move
This PR add the spec for the bit operations of the `features` module.
This PR also resolved the multiple TODOs existing in the framework specs.
One TODO is added due to the known issue of data invariant verification: https://github.com/move-language/move/issues/819
move prove
=> [Spec] Specified `features` module

aptos-move/framework/aptos-token/doc/token.md, aptos-move/framework/aptos-token/sources/token.move
=> Cherry pick PR#6060 into v1.2.0

developer-docs-site/docs/sdks/ts-sdk/typescript-sdk-overview.md
=> [doc] update token client doc

aptos-move/aptos-sdk-builder/examples/golang/Makefile, aptos-move/aptos-sdk-builder/src/golang.rs
we will need to add rich typing at some point....
skip over some entry functions that golang cannot support without generics
=> [golang] Skip entry functions that Golang can't support

developer-docs-site/src/contributors.json
=> Regenerate authors list as of 2023-01-17

docker/release-images.mjs
Cherry pick #5991 , which publishes the `validator-testing` image to our internal repos with the `testnet` tag each time a push happens on `testnet` branch.
Otherwise, Forge tests that use the `testnet` branch will not use the latest tip of `testnet` branch.
Tested on `main` when the initial PR was landed.
=> [docker] release validator-testing image internally with new tag (#5991)

developer-docs-site/docs/guides/get-test-funds.md, developer-docs-site/docs/whats-new-in-docs.md
=> Fix navigation for and announce new Create and Fund Accounts

ecosystem/typescript/sdk/src/aptos_types/abi.ts
=> ArgumentABI typo

developer-docs-site/scripts/additional_dict.txt
=> Add terms for PR #6218 in Create a Signed Transaction

aptos-move/move-examples/data_structures/sources/big_vector.move, aptos-move/move-examples/data_structures/sources/smart_vector.move
1. fix a bug in smart_vector::remove that can break the invariant that v.big_vec.len() < 2. This can cause a DOS in pop_back because if there’s only one item in big_vec , removing it doesn’t remove the empty big_vec inside smart vector.
2. follow OtterSec's suggestion of BigVector api to use native `vector` api as much as possible to save 5x - 10x gas. Did similar change to smart_vector, too
ut
=> [smart/big_vector] fix bug and gas optimization

developer-docs-site/scripts/additional_dict.txt
=> Add IPFS and uri to spelling dictionary

developer-docs-site/docs/concepts/coin-and-token/silver_coin.md
=> [doc] Mint fungible tokens with on-chain data (silver coin)

developer-docs-site/docs/whats-new-in-docs.md
=> Add batch signing and connect to Aptos updates to See what's new

state-sync/storage-service/server/src/tests.rs
This PR adds 3 new tests to the storage service for state sync. These tests simply verify that if two peers have the same peer ID, but connect over different networks, they don't interfere with each other when making subscription requests. 😄 
Existing testing infrastructure.
=> [State Sync] Add 3 more tests to the storage service.

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/aptos_client.test.ts, ecosystem/typescript/sdk/src/aptos_client.ts
Adds view function support to the TS SDK
=> [TS SDK] add view function support

developer-docs-site/docs/concepts/coin-and-token/aptos-token-overview.md, developer-docs-site/scripts/additional_dict.txt
A short intro between token standard. @clay-aptos please take a look.
n/a
=> [doc] token overview with comparison

developer-docs-site/docs/concepts/wallet-adapter-concept.md
=> Fix some small issues in Wallet Adapter, add verb to title

developer-docs-site/docs/guides/indexing.md
=> Fix broken Diesel migrations link in Indexing guide

sdk/README.md
=> Replace old RPC link and ref with REST API in SDK README

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
Bump TS SDK version with the new view function support
all tests pass
=> [TS SDK] bump version to 1.6.0

execution/executor/src/components/chunk_output.rs
This will help us debug issues where certain nodes are discarding txns causing state mismatch. 
Unit tests
=> [Execution] Log discarded transactions

.github/workflows/copy-images-to-dockerhub-on-devnet-or-testnet-push.yaml
=> [gha] copy images on tag

.github/workflows/verify-on-chain-modules-mainnet.yaml, .github/workflows/verify-on-chain-modules-testnet.yaml, Cargo.lock, Cargo.toml, crates/crash-handler/Cargo.toml, crates/crash-handler/src/lib.rs
Cherrypick #6134 and #6091 into 1.2.0 release.
NA
=> [move] cherrypick #6134

developer-docs-site/docs/concepts/coin-and-token/nft-minting-tool.md
=> Retitle minting tool doc, add more explicit purpose

developer-docs-site/docs/guides/aptos-apis.md
=> Add View function to Use the Aptos REST Read API

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-emitter-lib/src/transaction_generator/mod.rs, crates/transaction-emitter-lib/src/wrappers.rs
- use larger gas fee for minting, to help with cases when multiple txn emitters are running
- make minting fault tolerant - continue minting until enough accounts have been minted
=> Make account minting more reliable

developer-docs-site/docs/nodes/measure/index.md, developer-docs-site/docs/whats-new-in-docs.md
=> Announce multiple site sidebars and View function in See what's new

developer-docs-site/src/contributors.json
=> Update the Authors list for Aptos.dev

developer-docs-site/docs/guides/aptos-apis.md
=> Fix grammar in sentence regarding return values of a View function

developer-docs-site/docs/index.md
=> Add direct link to #docs-feedback channel on Aptos.dev home page

aptos-move/move-examples/defi/sources/locked_coins.move
This makes the locked_coins contract more secured if the sponsor account is compromised. Hackers can cancel locks but funds would be sent back to the predefined withdrawal address.
Unit tests
=> [Move examples] Add withdrawal address to locked_coins contract

developer-docs-site/docs/guides/handle-aptos-errors.md
Now people can look at this page and have possible resolutions to their error codes
=> [docs] Add resolutions to aptos errors page

developer-docs-site/docs/whats-new-in-docs.md
=> Announce Automated Aptos CLI Installation in See what's new

developer-docs-site/docs/guides/wallet-standard.md
=> Make edits to recent Wallet Standard additions

config/src/config/storage_config.rs, storage/aptosdb/src/db_options.rs, storage/aptosdb/src/lib.rs, storage/backup/backup-cli/src/utils/mod.rs
Configure the new db. No real behavior change for now.
=> [Storage][Sharding] Prepare to split state kvs to a separate db.

Cargo.lock, execution/executor-benchmark/Cargo.toml, execution/executor-benchmark/src/fake_executor.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/metrics.rs
=> Add some metrics in fake executor, and handle the case of seed accounts re-creation.

ecosystem/python/sdk/aptos_sdk/transactions.py
=> Correct __str__() typo

crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/transaction_generator/accounts_pool_wrapper.rs, crates/transaction-emitter-lib/src/transaction_generator/call_custom_modules.rs, crates/transaction-emitter-lib/src/transaction_generator/mod.rs, crates/transaction-emitter-lib/src/wrappers.rs, testsuite/forge-cli/src/main.rs, testsuite/smoke-test/src/txn_emitter.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/src/load_vs_perf_benchmark.rs
=> Test different workloads (transaction types) to see TPS achieved

Cargo.lock, Cargo.toml, aptos-move/framework/aptos-stdlib/sources/simple_map.move
See https://github.com/move-language/move/pull/840
=> [inlining] Update move commit for getting bug fix

developer-docs-site/docs/concepts/coin-and-token/index.md, developer-docs-site/scripts/additional_dict.txt
Updates with wallet standards, shortens the lengthy descriptions, cleans up duplicate text, talks about more than just tokens
=> [docs] Update standards page

aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/framework/aptos-stdlib/doc/groth16.md, aptos-move/framework/aptos-stdlib/doc/groups.md, aptos-move/framework/aptos-stdlib/sources/cryptography/groth16.move, aptos-move/framework/aptos-stdlib/sources/cryptography/groups.move, aptos-move/framework/src/natives/cryptography/groups/mod.rs, types/src/on_chain_config/aptos_features.rs
=> use macros to reduce PR size

.github/actions/docker-buildx-setup/action.yaml
=> [gha][docker-buildx-setup] bump version to fix 191

developer-docs-site/docs/guides/aptos-apis.md
Proposed a few tweaks to the view function focs.
NA
=> [docs] Update the doc for view function 

crates/aptos/src/update/tool.rs
Addressing feedback from https://github.com/aptos-labs/aptos-core/pull/6288.
👀
=> Improve comments for CLI update subcommand, use args properly

aptos-move/move-examples/split_transfer/sources/split_transfer.move
Fixed this small typo while browsing examples.
=> Fix typo in parameter name

aptos-move/framework/src/module_metadata.rs
somehow module metadata v1 snuck into bytecode v5 creating validation head aches for all...
this also contains @vgao1996 fix that we saw some other bytecode leverage the legacy enum serialization.
=> Fix module metadata bleed

developer-docs-site/docs/tutorials/build-e2e-dapp/1-create-smart-contract.md
=> [docs] Update e2e dapp tutorial with new names

execution/executor/src/chunk_executor.rs, storage/backup/backup-cli/src/bin/replay-verify.rs, storage/backup/backup-cli/src/coordinators/replay_verify.rs, storage/backup/backup-cli/src/metadata/cache.rs
=> Hotfix v1.2.0 david

aptos-move/framework/aptos-stdlib/doc/simple_map.md, aptos-move/framework/aptos-stdlib/doc/table.md, aptos-move/framework/aptos-stdlib/doc/table_with_length.md, aptos-move/framework/aptos-stdlib/sources/simple_map.move, aptos-move/framework/aptos-stdlib/sources/table.move, aptos-move/framework/aptos-stdlib/sources/table_with_length.move, aptos-move/move-examples/data_structures/sources/big_vector.move, aptos-move/move-examples/data_structures/sources/bucket_table.move, aptos-move/move-examples/data_structures/sources/iterable_table.move, aptos-move/move-examples/data_structures/sources/smart_vector.move
Reverts aptos-labs/aptos-core#6138
cuz it may break the "module publish". holding off it.
=> Revert "[framework] remove unnecessary abilities"

developer-docs-site/docs/guides/move-guides/upgrading-move-code.md
Context: https://github.com/move-language/move/issues/864
=> [Docs] Update upgradability docs

developer-docs-site/docs/concepts/coin-and-token/nft-minting-tool.md, developer-docs-site/docs/guides/aptos-apis.md
=> [docs] fix docs from learnings at Seoul hackathon

developer-docs-site/docs/guides/aptos-apis.md, developer-docs-site/docs/guides/indexing.md, developer-docs-site/docs/guides/system-integrators-guide.md
=> Add rate limits and API spec to API doc, link from sys int guide

state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
This PR addresses what might be a possible race condition in some of the driver tests. Note: I've run these tests locally 1000 times and still no flake, but better to be safe than sorry 😄 
=> [State Sync] Improve checks around auto bootstrapping.

CODEOWNERS
Adds new owners and removes some old ones
=> Update CODEOWNERS with newest owners

ecosystem/typescript/sdk/CHANGELOG.md
=> [docs] Update CHANGELOG.md

testsuite/forge-cli/src/main.rs
- consensus stress tests got affected by chain health backoff
=> [forge] Adjust flaky forge tests based on past history

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/transaction_generator/call_custom_modules.rs, crates/transaction-emitter-lib/src/transaction_generator/mod.rs, crates/transaction-emitter-lib/src/transaction_generator/nft_mint_and_transfer.rs, crates/transaction-emitter-lib/src/wrappers.rs, testsuite/smoke-test/src/txn_emitter.rs
Allows load test with small and precise amount of money should solve forge tests broken on insufficient resources
=> [txn emitter] adding arguments for more precise balance management for txn emitter

crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/stats.rs, crates/transaction-emitter/src/main.rs, ecosystem/node-checker/src/checker/tps.rs, testsuite/forge-cli/src/main.rs, testsuite/forge/src/success_criteria.rs, testsuite/smoke-test/src/consensus/consensus_only.rs, testsuite/smoke-test/src/txn_emitter.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/src/load_vs_perf_benchmark.rs, testsuite/testcases/src/two_traffics_test.rs
especially when init (minting) takes a lot of time
=> [txn-emitter][forge] Fix duration used for TPS computation

aptos-move/framework/aptos-token/doc/token.md, aptos-move/framework/aptos-token/sources/token.move, aptos-move/move-examples/post_mint_reveal_nft/sources/minting.move
Check https://github.com/aptos-foundation/AIPs/pull/29 for more details
=> [token] add token standard reserved properties

crates/aptos/homebrew/README.md
Per Jing's comment, making this README.md more beginner friendly for people who just want to download the Aptos CLI from homebrew
N/A
=> [homebrew] adding clarity to homebrew readme docs

.github/workflows/replay-verify-mainnet.yaml, .github/workflows/replay-verify-testnet.yaml
=> replay-verify: change cron format

aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-framework/doc/aptos_account.md, aptos-move/framework/aptos-framework/doc/coin.md, aptos-move/framework/aptos-framework/doc/governance_proposal.md, aptos-move/framework/aptos-framework/doc/system_addresses.md, aptos-move/framework/aptos-framework/doc/transaction_context.md, aptos-move/framework/aptos-framework/sources/account.spec.move, aptos-move/framework/aptos-framework/sources/aptos_account.spec.move, aptos-move/framework/aptos-framework/sources/coin.spec.move, aptos-move/framework/aptos-framework/sources/governance_proposal.spec.move, aptos-move/framework/aptos-framework/sources/system_addresses.spec.move, aptos-move/framework/aptos-framework/sources/transaction_context.spec.move
This PR adds more spec to the following modules in the Aptos Framework:
- account
- aptos_account
- governance_proposal
- system_addresses
- transaction_context
=> [Spec] Added more spec to the `account` and `aptos_account` modules

developer-docs-site/docs/concepts/events.md
=> [doc] fix events dev doc example

Cargo.lock, Cargo.toml, storage/aptosdb/src/db_debugger/ledger/check_range_proof.rs, storage/aptosdb/src/db_debugger/ledger/check_txn_info_hashes.rs, storage/aptosdb/src/db_debugger/ledger/mod.rs, storage/aptosdb/src/db_debugger/mod.rs, storage/aptosdb/src/db_debugger/state_tree/mod.rs, storage/aptosdb/src/db_debugger/truncate/mod.rs, storage/backup/backup-cli/src/coordinators/verify.rs, storage/backup/backup-cli/src/storage/command_adapter/mod.rs, storage/backup/backup-cli/src/storage/local_fs/mod.rs, storage/backup/backup-cli/src/storage/mod.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/db-tool/Cargo.toml, storage/db-tool/src/backup.rs, storage/db-tool/src/debugger.rs, storage/db-tool/src/lib.rs, storage/db-tool/src/main.rs, storage/db-tool/src/replay_verify.rs, storage/db-tool/src/restore.rs, storage/db-tool/src/tests.rs
add a new crate db cli to 
1. combine existing db tools
2. hide global option that are too verbose
3. rearrange the commands to make it easier to use
TODO:
delete the existing cli once this tool is stable
add unit test
=> [storage][1/2] Add a DB Tool Crate to Combine Existing Tools

developer-docs-site/docs/guides/getting-started.md
=> Add link to paper directory found while reviewing partner doc

developer-docs-site/docusaurus.config.js
=> Shorten top nav titles in Aptos.dev to one word

.github/workflows/replay-verify.yaml
correct the condition to run on `schedule` event type, as well as bump the cadence to run today
=> [gha] replay-verify on cadence correct conditional

.github/workflows/replay-verify.yaml, .github/workflows/workflow-run-replay-verify.yaml
* run it twice a day
* have it run the right script
=> [gha] fix replay verify cadence and job

.github/workflows/docker-build-test.yaml
=> [gha] run image build on performance_benchmark branch

developer-docs-site/docs/tutorials/first-dapp.md
=> Link from First Dapp tutorial to Build an End-to-End Dapp on Aptos

aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/src/proptest_types/types.rs, consensus/Cargo.toml, consensus/consensus-types/src/request_response.rs, consensus/src/counters.rs, consensus/src/epoch_manager.rs, consensus/src/experimental/ordering_state_computer.rs, consensus/src/lib.rs, consensus/src/payload_client.rs, consensus/src/payload_manager.rs, consensus/src/quorum_store/direct_mempool_quorum_store.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/tests/batch_generator_test.rs, consensus/src/quorum_store/tests/proof_manager_test.rs, consensus/src/quorum_store/utils.rs, consensus/src/sender_aware_shuffler.rs, consensus/src/state_computer.rs, consensus/src/state_replication.rs, consensus/src/test_utils/mock_state_computer.rs, consensus/src/transaction_shuffler.rs, execution/executor/src/components/chunk_output.rs, types/src/on_chain_config/execution_config.rs, types/src/on_chain_config/mod.rs
=> [BlockSTM] Optimized transaction shuffling

.github/workflows/replay-verify.yaml, .github/workflows/workflow-run-replay-verify.yaml, testsuite/replay_verify.py
=> replay-verify workflow fixes

testsuite/replay_verify.py
previously we weren't collecting the exit code for each of the replay partitions
=> [replay-verify] exit with correct status

Cargo.lock, Cargo.toml, aptos-move/aptos-gas/src/aptos_framework.rs, aptos-move/aptos-gas/src/gas_meter.rs, aptos-move/e2e-move-tests/src/tests/token_objects.rs, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/framework/src/natives/mod.rs, aptos-move/framework/src/natives/object.rs, aptos-move/move-examples/token_objects/sources/collection.move, aptos-move/move-examples/token_objects/sources/hero.move, aptos-move/move-examples/token_objects/sources/token.move, types/src/account_address.rs, types/src/transaction/authenticator.rs
=> [framework] swap (untyped) object id for object ref 

aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-framework/doc/aptos_account.md, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/aptos_account.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, testsuite/smoke-test/src/rosetta.rs
Cherrypicking https://github.com/aptos-labs/aptos-core/pull/5871 and https://github.com/aptos-labs/aptos-core/pull/6169 into v1.2.0. These contain changes associated with https://github.com/aptos-foundation/AIPs/issues/24
=> Cherrypick coin improvements PRs

aptos-move/framework/aptos-framework/doc/vesting.md, aptos-move/framework/aptos-framework/sources/vesting.move
This is per an approved AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-14.md
Release and test in testnet
=> Cherrypick vesting contract update

testsuite/replay_verify.py
return the partition num and return code instead. avoid trying to pickle a `Popen`, which results in error
=> [replay-verify] avoid pickle process

developer-docs-site/docs/guides/move-guides/mint-nft-cli.md
=> Update mint-nft-cli.md with link to latest sample code

.github/actions/check-branch-commits/expected_on_testnet_not_devnet.txt, .github/workflows/check-branch-commits.yaml
This PR removes unnecessary file exceptions after the devnet recut.
=> [Commit Checker] Remove unnecessary file exceptions.

storage/aptosdb/src/db_debugger/truncate/mod.rs, storage/aptosdb/src/utils/mod.rs, storage/aptosdb/src/utils/truncation_helper.rs
Some functions will be reused after we split ledger db into multiple databases.
=> [Storage] Move some truncation helper functions to its own file.

developer-docs-site/src/contributors.json
=> Update Authors list with latest contributors

developer-docs-site/docs/guides/basics-life-of-txn.md, developer-docs-site/docs/nodes/full-node/fullnode-network-connections.md, developer-docs-site/docs/sdks/ts-sdk/typescript-sdk-overview.md
=> Remove or fix links resulting from deleted and moved files

Cargo.lock, crates/aptos/Cargo.toml
=> [cli] Release 1.0.6

consensus/src/network.rs, testsuite/smoke-test/src/txn_broadcast.rs
Cleanup failpoints strings that were not following convention
Existing tests, specifically failpoint tests
=> [Quorum Store] cleanup failpoints

Cargo.lock, aptos-move/framework/src/built_package.rs, aptos-move/framework/src/lib.rs, crates/aptos/Cargo.toml, crates/aptos/src/move_tool/mod.rs
=> [Aptos-CLI] Add extended checks to aptos move test

developer-docs-site/docs/guides/handle-aptos-errors.md
=> [docs] Add LOOKUP_FAILED error message

.github/workflows/forge-stable.yaml
avoid flaky signal from `quorum-store` tests
=> [gha] forge-stable posts to slack only on main

.github/workflows/workflow-run-module-verify.yaml, .github/workflows/workflow-run-replay-verify.yaml, Cargo.lock, Cargo.toml, crates/aptos/Cargo.toml, docker/build-rust-all.sh, docker/compose/README.md, docker/compose/data-restore/docker-compose.yaml, docker/rust-all.Dockerfile, storage/README.md, storage/aptosdb/src/backup/restore_utils.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/db-tool/src/backup.rs, storage/storage-interface/src/lib.rs, terraform/helm/fullnode/templates/backup-verify.yaml, terraform/helm/fullnode/templates/backup.yaml, terraform/helm/fullnode/templates/restore.yaml, testsuite/module_verify.py, testsuite/module_verify_run_local.py, testsuite/replay_verify.py, testsuite/replay_verify_run_local.py, testsuite/smoke-test/src/genesis.rs, testsuite/smoke-test/src/storage.rs, testsuite/verify_core/common.py
replace the existing db tooling with new aptos-db-tool
existing testing
=> [storage] Replace existing tools

testsuite/forge-cli/src/main.rs, testsuite/testcases/src/two_traffics_test.rs
This PR introduces a variant of graceful overload test for gas market with three region simulation mode.
[See this comment](https://github.com/aptos-labs/aptos-core/pull/6717#issuecomment-1439224199)
=> [forge] Three-region gas market graceful overload test

.github/workflows/replay-verify.yaml, storage/db-tool/src/replay_verify.rs, testsuite/replay_verify.py
python3 testsuite/replay_verify_run_local.py works
=> replace replay-verify with new db tool

LICENSE
This PR extends the license file with the full apache license text.
=> [License] Extend the license file to contain the required text.

aptos-move/framework/aptos-framework/doc/aggregator_factory.md, aptos-move/framework/aptos-framework/doc/coin.md, aptos-move/framework/aptos-framework/doc/transaction_fee.md, aptos-move/framework/aptos-framework/doc/vesting.md, aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.spec.move, aptos-move/framework/aptos-framework/sources/coin.spec.move, aptos-move/framework/aptos-framework/sources/transaction_fee.spec.move, aptos-move/framework/aptos-framework/sources/vesting.spec.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/doc/option.md, aptos-move/framework/move-stdlib/sources/configs/features.spec.move, aptos-move/framework/move-stdlib/sources/option.move
- added more specs to `transaction_fee` and `coin`
- rewrote and simplified the spec of `features` using a spec function
- fixed the recursive spec in the `option` module, whose behavior was unclear.
=> [spec] updated the specs of `transaction_fee`, `coin` and `features`

developer-docs-site/docs/guides/indexing.md
=> docs: update indexer intro section

developer-docs-site/docs/guides/install-petra-wallet.md
=> Link to Aptos Wallet Standard from Install a Wallet

api/Makefile, scripts/cargo_check_dependencies.sh, scripts/cargo_update_outdated.sh, scripts/changed-files.sh, scripts/dev_setup.sh, scripts/git-checks.sh, scripts/run_quarantined.sh, testsuite/aptos-fuzzer/fuzz/google-oss-fuzz/build.sh, testsuite/aptos-fuzzer/fuzz/google-oss-fuzz/build_corpus.sh, testsuite/aptos-fuzzer/fuzz/google-oss-fuzz/build_fuzzer.sh
This PR updates the repository with shared licenses for python files that also contain some Meta code.
=> [License] Add shared license to relevant files.

aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-framework/sources/account.move
Added functions to get info about the signer capability of an address.
Should I add tests for these?
=> [framework] Functions to get signer capability info. of an account.

scripts/dev_setup.sh
=> disable protoc dev dependencies in dev_setup. (#6751)

types/src/state_store/state_value.rs
=> [state value] make hash compute lazy

.github/workflows/docker-build-test.yaml, .github/workflows/sdk-release.yaml
https://github.com/aptos-labs/aptos-core/issues/6707
=> [TS SDK] Remove SDK release steps from SDK CI

consensus/src/round_manager.rs
=> [round mananger] downgrade logs to warn

developer-docs-site/src/contributors.json
=> Add 2023-02-23 contributors to Authors lists for Aptos.dev

execution/executor-benchmark/src/account_generator.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, execution/executor-benchmark/src/transaction_committer.rs, execution/executor-benchmark/src/transaction_generator.rs
=> [executor benchmark] print overall TPS

docker/rosetta/rosetta.Dockerfile
=> [docker][rosetta] update rust version

developer-docs-site/docs/whats-new-in-docs.md
=> Announce Move Book publishing to Aptos.dev

Cargo.lock, aptos-move/aptos-gas/Cargo.toml, aptos-move/aptos-gas/src/gas_meter.rs
As titled. Although unlikely, if we indeed hit this branch we'd want to know.
=> trivial: add an error log

Cargo.lock, Cargo.toml, api/src/accounts.rs, api/src/context.rs, aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs, aptos-move/aptos-vm/src/access_path_cache.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/lib.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/access_path_test.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, aptos-move/e2e-tests/src/account.rs, aptos-move/e2e-tests/src/data_store.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/e2e-testsuite/src/tests/back_edges.rs, aptos-move/framework/src/natives/mod.rs, aptos-move/vm-genesis/src/lib.rs, execution/executor-benchmark/src/fake_executor.rs, execution/executor/src/mock_vm/mod.rs, execution/executor/tests/db_bootstrapper_test.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs, storage/storage-interface/src/lib.rs, types/src/access_path.rs, types/src/account_config/resources/coin_info.rs, types/src/account_view.rs, types/src/on_chain_config/mod.rs, types/src/on_chain_config/timed_features.rs
This also brings the Move commit to the newest state of `aptos-main`.
=> [hotfix] Chery pick various fixes around bytecode verifier

developer-docs-site/docs/guides/basics-life-of-txn.md
fix guide basic-life-of-txn.md function name
=> [Docs] fix guide basic-life-of-txn.md function name

.github/actions/check-branch-commits/expected_on_mainnet_not_main.txt, .github/actions/check-branch-commits/expected_on_testnet_not_devnet.txt, .github/actions/check-branch-commits/expected_on_testnet_not_main.txt
This PR updates the exception lists for the branch commit checker after a few recent hot-fixes were applied to the various branches.
=> [Branch Commit Checker] Update exceptions list.

crates/aptos/src/test/mod.rs, testsuite/forge-cli/src/main.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/src/quorum_store_onchain_enable_test.rs
This PR introduces a forge test for enabling the quorum store on chain config by sending a governance proposal.
[See this comment](https://github.com/aptos-labs/aptos-core/pull/6719#issuecomment-1440814715)
=> [Forge][Quorum Store] On Chain Enable Quorum Store Test

consensus/consensus-types/src/proof_of_store.rs, consensus/src/quorum_store/batch_coordinator.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/proof_coordinator.rs, consensus/src/quorum_store/tests/proof_coordinator_test.rs, consensus/src/quorum_store/tests/proof_manager_test.rs, testsuite/generate-format/tests/staged/consensus.yaml
Incentives needs a batch author. We add it to the signed digest info, so the proof of store signatures guarantee that the author is not forged.
=> [Quorum Store] sign the author along with the digest

crates/transaction-emitter-lib/src/emitter/account_minter.rs, testsuite/forge-cli/src/main.rs
This PR fixes an multiplication overflow issue when calculating the maximum allowed gas in transaction-emitter-lib.
https://github.com/aptos-labs/aptos-core/pull/6815#issuecomment-1449067364
=> [forge] fix total txns gas overflow

config/src/config/consensus_config.rs, config/src/config/execution_config.rs, config/src/config/network_config.rs, config/src/config/state_sync_config.rs, config/src/config/storage_config.rs
Reusing the same configs that we used for multi-region benchmark to achieve more than 10k TPS - https://gist.github.com/igor-aptos/a923b02f98d41a8f662dc919832feff6.
=> [Previewnet] Configuration tuning to achieve high TPS

testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs
Smoke test to repeatedly switch quorum store on/off (5 times).
Added the smoke test.
=> [Quorum Store] add a smoke test to rollback quorum store

consensus/consensus-types/src/request_response.rs, consensus/src/epoch_manager.rs, consensus/src/payload_client.rs, consensus/src/quorum_store/direct_mempool_quorum_store.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/quorum_store_builder.rs, consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs, consensus/src/quorum_store/tests/proof_manager_test.rs, consensus/src/test_utils/mock_payload_manager.rs
=> [Quorum Store] rename enums to be clearer

aptos-move/framework/src/natives/account.rs, aptos-move/framework/src/natives/aggregator_natives/aggregator.rs, aptos-move/framework/src/natives/aggregator_natives/aggregator_factory.rs, aptos-move/framework/src/natives/code.rs, aptos-move/framework/src/natives/create_signer.rs, aptos-move/framework/src/natives/cryptography/bls12381.rs, aptos-move/framework/src/natives/cryptography/ed25519.rs, aptos-move/framework/src/natives/cryptography/multi_ed25519.rs, aptos-move/framework/src/natives/cryptography/ristretto255.rs, aptos-move/framework/src/natives/cryptography/ristretto255_point.rs, aptos-move/framework/src/natives/cryptography/ristretto255_scalar.rs, aptos-move/framework/src/natives/cryptography/secp256k1.rs, aptos-move/framework/src/natives/event.rs, aptos-move/framework/src/natives/hash.rs, aptos-move/framework/src/natives/helpers.rs, aptos-move/framework/src/natives/mod.rs, aptos-move/framework/src/natives/object.rs, aptos-move/framework/src/natives/state_storage.rs, aptos-move/framework/src/natives/transaction_context.rs, aptos-move/framework/src/natives/type_info.rs, aptos-move/framework/src/natives/util.rs, crates/aptos-crypto/benches/ristretto255.rs, crates/aptos-crypto/src/multi_ed25519.rs, crates/aptos-crypto/src/unit_tests/multi_ed25519_test.rs, types/src/on_chain_config/timed_features.rs
Cherry-picks support for safe natives and converts remaining natives.
=> Cherry-picks support for safe natives

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
Bump TS SDK version from 1.6.0 to 1.7.0
=> [TS SDK] Bump TS SDK version from 1.6.0 to 1.7.0

Cargo.lock, crates/aptos/Cargo.toml
Release to update bytecode version default
=> [cli] Update to 1.0.7

ecosystem/typescript/sdk/CHANGELOG.md
Update changelog with new features released today
=> [TS SDK] Update changelog

developer-docs-site/docs/index.md
=> Update Aptos.dev home page with newer REST API reference interface

api/types/src/convert.rs, aptos-move/aptos-aggregator/src/aggregator_extension.rs, aptos-move/aptos-aggregator/src/delta_change_set.rs, aptos-move/aptos-aggregator/src/transaction.rs, aptos-move/aptos-gas/src/transaction/mod.rs, aptos-move/aptos-gas/src/transaction/storage.rs, aptos-move/aptos-validator-interface/src/lib.rs, aptos-move/aptos-validator-interface/src/rest_interface.rs, aptos-move/aptos-vm/src/delta_state_view.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-tests/src/data_store.rs, aptos-move/mvhashmap/src/unit_tests/mod.rs, aptos-move/mvhashmap/src/unit_tests/proptest_types.rs, aptos-move/vm-genesis/src/genesis_context.rs, crates/aptos-rosetta/src/types/objects.rs, execution/executor-types/src/in_memory_state_calculator.rs, state-sync/storage-service/server/src/tests.rs, storage/aptosdb/src/fake_aptosdb.rs, storage/indexer/src/lib.rs, storage/scratchpad/benches/sparse_merkle.rs, testsuite/generate-format/tests/staged/api.yaml, testsuite/generate-format/tests/staged/aptos.yaml, testsuite/generate-format/tests/staged/consensus.yaml, types/src/proptest_types.rs, types/src/state_store/state_value.rs, types/src/write_set.rs
…king
* StateValue now has a new flavor which carries StateValueMetadata.
* similarly there is now WriteOp::CreationWithMetadata and friends
replay-verify: https://github.com/aptos-labs/aptos-core/actions/runs/4299055448
=> Add update StateValue and WriteOp to support metadata tracking

developer-docs-site/docs/sdks/ts-sdk/typescript-sdk-overview.md
This PR adds documentation for Provider and IndexerClient classes on the TS SDK
=> [DOC][TS SDK] add documentation for Provider and IndexerClient classes

api/src/tests/view_function.rs, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/aptos_account.move, aptos-move/framework/aptos-framework/sources/aptos_governance.move, aptos-move/framework/aptos-framework/sources/block.move, aptos-move/framework/aptos-framework/sources/chain_id.move, aptos-move/framework/aptos-framework/sources/chain_status.move, aptos-move/framework/aptos-framework/sources/coin.move, aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/aptos-framework/sources/timestamp.move, aptos-move/framework/aptos-framework/sources/voting.move
https://github.com/aptos-labs/aptos-core/issues/6253
Manual tests to verify these view functions can be called through the view API/CLI.
=> [Aptos Framework][No behavior changes] Add #[view] annotations for view functions in Aptos Framework

consensus/src/block_storage/sync_manager.rs, consensus/src/state_computer.rs, types/src/block_info.rs
This commit does a few things to avoid that sync_to races with commit in state computer.
=> [consensus] better protect sync condition

aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/sources/multisig_account.move
=> [Minor refactoring][No behavior change] Deduplicate some logic in multisig_account.move

.github/workflows/docker-build-test.yaml, terraform/aptos-node-testnet/aws/variables.tf, terraform/aptos-node-testnet/gcp/variables.tf, terraform/aptos-node/aws/variables.tf, terraform/aptos-node/gcp/variables.tf
Build docker images on push to `preview` branch. 
Also ensure the new machine type requirements for previewnet
=> [tf/gha] build on push to preview branch and bump machine type

testsuite/forge_test.py
=> [forge] enforce max pod name len fix

.github/workflows/docker-build-test.yaml, testsuite/forge.py, testsuite/forge_test.py
Fix this off-by-1 error in Forge namespaces
=> [forge] enforce max pod name len

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json, ecosystem/typescript/sdk/src/providers/indexer.ts, ecosystem/typescript/sdk/src/tests/e2e/provider.test.ts, ecosystem/typescript/sdk/src/utils/test_helper.test.ts
Hot fix for IndexerClient error parsing using JSON.stringify() to display the error message correctly on the console
=> [TS SDK] Fix IndexerClient error parsing using JSON.stringify()

.github/workflows/adhoc-forge.yaml
Support for running one-off forge tests via Github workflow dispatch
=> [GHA] Ad-hoc forge workflow

Cargo.lock, Cargo.toml, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.spec.move, aptos-move/framework/src/aptos-natives.bpl, aptos-move/framework/src/prover.rs, crates/aptos/src/move_tool/aptos-natives.bpl
- Added the boogie implementation of `object::exists_at` to `aptos-natives.bpl`.
=> [Prover] Natively modeled `object::exists_at`

developer-docs-site/docs/guides/move-guides/index.md
=> Add Aptos Move Book to Move index

developer-docs-site/docs/nodes/node-files-all-networks/node-files-devnet.md, developer-docs-site/docs/nodes/node-files-all-networks/node-files-testnet.md
=> Fix paths to Fullnode Docker Compose file in testnet and devnet lists

crates/aptos-push-metrics/src/lib.rs
This PR adds support for pushing metrics to token-based authenticated endpoints in aptos-push-metrics crate.
=> [push-metrics] Support endpoints with token-based authentication

terraform/aptos-node/gcp/cluster.tf
Fix node taint key.
Tested by spinning up Previewnet on GCP.
=> [TF] Fix Kubernetes node taint

terraform/helm/aptos-node/values.yaml
Follow the recommendation for resource limit
```
- CPU: 48 physical cores or 64 thread
- Memory: 64 GB of RAM
- Clock speed: 2.8GHz, or faster
- Storage: 2T SSD with at least 40K IOPS and 200MiB/s bandwidth.
- Networking bandwidth: 1Gbps
```
=> [PREVIEWNET ONLY][helm][aptos-node] update validator and VFN resources

crates/inspection-service/src/inspection_service.rs
This PR: (i) adds a "Content-Type" HTTP header to the node inspection service; (ii)  updates the status codes for disabled endpoints; and (iii) extends support for the HEAD method. This has been requested by several users (e.g., in discord).
=> [Node Inspection] Add HTTP headers and more appropriate codes.

crates/aptos/src/governance/mod.rs
Now listing won't crash when it's not a proper btree map format
```
./target/debug/aptos governance list-proposals --url https://fullnode.mainnet.aptoslabs.com
{
"Result": [
{
"proposer": "bc7cd15595245af1ae39d91d3cd16e024de3544c1d528d568350a13b71e23917",
"stake_pool": "fcbc1da54b125c093d49bf4a604a1854d38f99b6cffc09255d8af5446898ddba",
"proposal_id": 0,
"execution_hash": "14bbbcc8b5ecd167b4527fc6f8caee3f9a12f93e8543eabaae696bf1eedec044",
"proposal_metadata": {
"metadata_hash": "121db59881d2934f0b80e66d71a3888511dbd5107f487e05c12f3db78b02fa2e",
"metadata_location": "https://raw.githubusercontent.com/aptos-labs/mainnet-proposals/main/metadata/0-reduce-increase-limit-to-10.json"
}
},
{
"proposer": "db009ab1a3259c4b27a0d8ff9d0e913e13e4c8b657fc73768f4e9bb811c7a1d8",
"stake_pool": …
```
=> [cli] Fix governance proposal listing

crates/aptos-push-metrics/src/lib.rs, execution/executor-benchmark/src/main.rs, storage/backup/backup-cli/src/bin/db-backup-verify.rs, storage/backup/backup-cli/src/bin/db-backup.rs, storage/backup/backup-cli/src/bin/db-restore.rs, storage/db-tool/src/backup.rs, storage/db-tool/src/restore.rs
=> trivial: MetricsPusher not deprecated

SECURITY.md
(please feel free to shred this PR and correct the document as you see fit. Just correct it, those `****` look really strange...)
=> Reformat slightly, remove a duplicate

developer-docs-site/src/contributors.json
=> Generate latest list of Aptos.dev contributors

.github/workflows/cli-release.yaml
Update text to match what we've been using since devnet
=> [cli] Update CLI release example text

developer-docs-site/docs/nodes/measure/node-health-checker.md, ecosystem/node-checker/configuration_examples/README.md
I was answering questions in Discord and noticed that these docs were quite of date compared to NHC as it is today. This PR fixes that.
=> Improve NHC docs

developer-docs-site/docs/tutorials/build-e2e-dapp/4-fetch-data-from-chain.md, developer-docs-site/scripts/additional_dict.txt
=> [docs] pulled in an incomplete change

developer-docs-site/scripts/additional_dict.txt, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, storage/backup/backup-cli/src/coordinators/restore.rs
update unit test
local test works
=> [storage] add save txn option back

crates/aptos-push-metrics/src/lib.rs, execution/executor-benchmark/src/main.rs, storage/backup/backup-cli/src/bin/db-backup-verify.rs, storage/backup/backup-cli/src/bin/db-backup.rs, storage/backup/backup-cli/src/bin/db-restore.rs, storage/db-tool/src/backup.rs, storage/db-tool/src/restore.rs
Addressing minor review comments in the previous PR and adding support for sticky namespaces. Also, reverting changes to all other tool apart from `executor-benchmark` as those changes break existing dashboards for other tools.
=> [Executor-benchmark][Trivial]  Minor changes in metrics pusher

config/src/config/storage_config.rs, execution/executor-benchmark/src/main.rs, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/tests.rs, storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/fake_aptosdb.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/event_store/test.rs, storage/aptosdb/src/pruner/ledger_pruner_manager.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs, storage/aptosdb/src/pruner/ledger_store/mod.rs, storage/aptosdb/src/pruner/ledger_store/version_data_pruner.rs, storage/aptosdb/src/pruner/mod.rs, storage/aptosdb/src/pruner/pruner_utils.rs, storage/aptosdb/src/pruner/state_kv_pruner.rs, storage/aptosdb/src/pruner/state_kv_pruner_manager.rs, storage/aptosdb/src/pruner/state_kv_pruner_worker.rs, storage/aptosdb/src/pruner/state_merkle_pruner_manager.rs, storage/aptosdb/src/pruner/state_merkle_pruner_worker.rs, storage/aptosdb/src/pruner/state_store/mod.rs, storage/aptosdb/src/pruner/state_store/state_value_pruner.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/pruner/transaction_store/test.rs, storage/aptosdb/src/schema/db_metadata/mod.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_merkle_batch_committer.rs, storage/storage-interface/src/lib.rs
Cherry-pick https://github.com/aptos-labs/aptos-core/pull/6829 to preview branch.
=> [CP][Preview] State kv db pruner, and restore.

developer-docs-site/docs/guides/getting-started.md
=> fix anchor

storage/aptosdb/src/pruner/state_store/test.rs, testsuite/smoke-test/src/genesis.rs, testsuite/smoke-test/src/storage.rs
Use the correct db in test when the --use_state_kv_db is enabled.
=> [Storage] Fix tests.

developer-docs-site/docs/nodes/indexer-fullnode.md
=> Clarified the process of launching the indexer

.github/actions/check-branch-commits/expected_on_devnet_not_main.txt, .github/workflows/check-branch-commits.yaml
This PR updates the exception list for devnet.
=> [Branch Checker] Update exception list for devnet.

CODEOWNERS
=> [codeowners] Fix invalid name

consensus/src/consensus_provider.rs, consensus/src/epoch_manager.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/quorum_store_builder.rs, consensus/src/quorum_store/quorum_store_db.rs, consensus/src/quorum_store/tests/batch_generator_test.rs, consensus/src/quorum_store/tests/quorum_store_db_test.rs, consensus/src/twins/twins_node.rs
=> [Previewnet] [cherry-pick] PR 6978: [Quorum Store] Use a single quorum_store_db instance across epochs

crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/misc.rs, crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs, types/src/stake_pool.rs
This PR adds `unlock_stake` operation support in Rosetta. 
Added smoke test to verify the changes.
=> [rosetta] Add unlock_stake command

aptos-move/framework/aptos-stdlib/doc/smart_vector.md, aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.move
=> [cherry-pick][smart_vec] vector of big_vec is not necessary

developer-docs-site/docs/whats-new-in-docs.md
=> Announce Unity SDK docs and new Community section

config/src/config/mempool_config.rs, mempool/src/core_mempool/index.rs, mempool/src/core_mempool/transaction.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs
=> [Previewnet] [cherry-pick] PR 6965: [mempool] eager expiration based on queued transaction age

.github/ISSUE_TEMPLATE/documentation_bug_report.md
=> remove bug label from docs issue template

CONTRIBUTING.md
=> Fix link and grammar in contributing readme

developer-docs-site/scripts/additional_dict.txt
=> Add ide to spellcheck dictionary

config/src/config/quorum_store_config.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/quorum_store_builder.rs, consensus/src/quorum_store/tests/proof_manager_test.rs, consensus/src/quorum_store/utils.rs
cherry pick
NOTE: config changed: 80 -> 400
=> [cherry-pick] PR 6969

consensus/src/payload_client.rs
=> Add new block poll based on time

crates/transaction-emitter-lib/src/args.rs, crates/transaction-emitter-lib/src/cluster.rs, crates/transaction-emitter/src/diag.rs, crates/transaction-emitter/src/main.rs, ecosystem/node-checker/src/checker/tps.rs
=> [Txn emitter] Add support for load testing from a file and ping end points

config/src/config/quorum_store_config.rs
=> [cherry-pick] PR 7013

consensus/src/payload_manager.rs, consensus/src/quorum_store/batch_coordinator.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/batch_requester.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/network_listener.rs, consensus/src/quorum_store/proof_coordinator.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/quorum_store_coordinator.rs, consensus/src/quorum_store/quorum_store_db.rs, consensus/src/quorum_store/utils.rs, mempool/src/core_mempool/mempool.rs, testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs
Downgrade most logs to trace, only keep around enough debug logs to track locally created batch/digest/proof through the stages.
Run smoke test, observe logs are not too spammy.
=> [Quorum Store] Downgrade most logs to trace

consensus/src/payload_manager.rs, consensus/src/quorum_store/batch_coordinator.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/batch_requester.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/network_listener.rs, consensus/src/quorum_store/proof_coordinator.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/quorum_store_coordinator.rs, consensus/src/quorum_store/quorum_store_db.rs, consensus/src/quorum_store/utils.rs, mempool/src/core_mempool/mempool.rs
=> [cherry-pick] PR 7016

aptos-move/e2e-move-tests/src/tests/token_objects.rs, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/move-examples/token_objects/sources/collection.move, aptos-move/move-examples/token_objects/sources/hero.move, aptos-move/move-examples/token_objects/sources/royalty.move, aptos-move/move-examples/token_objects/sources/token.move
* improve royalties
* replace aggregable supply with untracked
* add a counter to fixed supply and to token to track a more effective guid for if and when we support guid based tokens -- those that can be deleted
* add mutation events for token and collection mutable fields
* adjust errors to start at 1, because @movekevin 
* address some auditor feedback
* update todos
=> [token] several improvements to the tokenv2 model

terraform/aptos-node/gcp/main.tf
=> Remove empty stanza that causes a warning on tf apply

developer-docs-site/docs/community/aptos-style.md
=> Fix header indentation

aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/framework/aptos-framework/doc/delegation_pool.md, aptos-move/framework/aptos-framework/doc/overview.md, aptos-move/framework/aptos-framework/doc/staking_contract.md, aptos-move/framework/aptos-framework/sources/delegation_pool.move, aptos-move/framework/aptos-framework/tests/delegation_pool_integration_tests.move, aptos-move/framework/aptos-stdlib/doc/overview.md, aptos-move/framework/aptos-stdlib/doc/pool_u64_unbound.md, aptos-move/framework/aptos-stdlib/sources/pool_u64_unbound.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
Cherrypicking https://github.com/aptos-labs/aptos-core/pull/6075 for AIP-6 into v1.3
Existing automated tests + more manual tests specifically for v1.3
=> [AIP-6] Add support for stake delegations (#6075)

aptos-move/framework/aptos-framework/doc/delegation_pool.md, aptos-move/framework/aptos-framework/sources/delegation_pool.spec.move, aptos-move/framework/aptos-stdlib/doc/pool_u64_unbound.md, aptos-move/framework/aptos-stdlib/sources/pool_u64_unbound.spec.move
* This PR adds the spec for `aptos_std::pool_u64_unbound`.
* It also adds a mockup spec file for `aptos_framework::delegation_pool` so that Prover does not fail.
=> [Spec] Added the spec for `aptos_std::pool_u64_unbound`

config/src/config/indexer_config.rs, crates/indexer/migrations/2023-03-08-205402_nft_points/down.sql, crates/indexer/migrations/2023-03-08-205402_nft_points/up.sql, crates/indexer/src/models/token_models/mod.rs, crates/indexer/src/models/token_models/nft_points.rs, crates/indexer/src/processors/token_processor.rs, crates/indexer/src/runtime.rs, crates/indexer/src/schema.rs
=> [Indexer] added nft_points custom contract parsing

storage/aptosdb/src/db_debugger/truncate/mod.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/utils/truncation_helper.rs, storage/schemadb/src/lib.rs
Share the same code to sync the databases for production and truncation tool.
Also fix a bug that we didn't write the progress during truncation.
UT
=> [Storage] Update truncation tool to support recent state kv db change.

developer-docs-site/docs/community/index.md
=> Rename Help the Ecosystem as Contribute, remove Labs refs

aptos-move/framework/README.md
Update the outdated Layout section in README.MD.
=> Update Layout section in framework README.MD

developer-docs-site/docs/tutorials/first-transaction.md, developer-docs-site/docs/tutorials/your-first-nft.md
=> Fix paths to embedded and moved TypeScript files

ecosystem/typescript/sdk/src/providers/aptos_client.ts
=> [TS SDK] update generate transaction functions doc

consensus/src/epoch_manager.rs, consensus/src/experimental/buffer_manager.rs, consensus/src/network.rs
This will help us understand if any single threaded task is getting choked.
=> [Consensus] Add monitoring for main loops

Cargo.lock, Cargo.toml
This picks https://github.com/move-language/move/pull/975 and closes #7040.
=> [move dependencies] Relax metering during tests

Cargo.lock, api/Cargo.toml, api/src/runtime.rs, config/src/config/api_config.rs
This is a cherry-pick of https://github.com/aptos-labs/aptos-core/pull/7083 into the `preview` branch.
=> [Config] Add config for API runtime workers.

config/src/config/quorum_store_config.rs, consensus/src/epoch_manager.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/quorum_store_builder.rs
=> [cherry-pick] PR 7058

consensus/src/quorum_store/batch_generator.rs
=> [cherry-pick] one-liner panic fix

consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/network_listener.rs, consensus/src/quorum_store/proof_coordinator.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/quorum_store_coordinator.rs
Will help us understand if any quorum store loops are being saturated.
=> [QS] Add monitoring counters for main loops in quorum store

consensus/consensus-types/src/proof_of_store.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/proof_coordinator.rs, crates/aptos-metrics-core/src/avg_counter.rs, crates/aptos-metrics-core/src/lib.rs
shared cherry-pick first, as PR on main (#7091) will need to rebase on top of @zekun000's changes
=> Add metrics around batch creation and eventually received replies [cherry-pick to previewnet]

ecosystem/indexer-grpc/indexer-grpc-parser/src/worker.rs
* fix the re-connection issue and improve the responsiveness of indexing.
=> [indexer grpc] fix the re-connection issue and improve the responsiveness of indexing.

storage/aptosdb/src/backup/restore_handler.rs, storage/aptosdb/src/backup/restore_utils.rs, storage/aptosdb/src/lib.rs, storage/backup/backup-cli/src/backup_types/transaction/restore.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs
save writeset while saving transactions
updated unit test
=> [storage] save writeset while saving txns

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json
=> [TS SDK] Bump version from 1.7.1 to 1.7.2

Cargo.lock, Cargo.toml, aptos-move/aptos-aggregator/src/delta_change_set.rs, aptos-move/aptos-gas/src/transaction/storage.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/errors.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs, execution/executor/src/mock_vm/mod.rs, types/src/transaction/multisig.rs
Updates existing code to compile with the additional error message field now supported by the VM. This is not yet a functional change, as the new information isn't used/populated yet
=> [move errors] Adapt to new Error variant with message

consensus/src/quorum_store/utils.rs
=> [cherry-pick] PR 7135

ecosystem/indexer-grpc/indexer-grpc-parser/src/worker.rs
=> [indexer parser] Remove obsolete comments and add more logging.

storage/aptosdb/src/state_store/mod.rs
=> [Storage] Log more information when usage number doesn't match expectation.

config/src/config/consensus_config.rs
=> Turn off chain-health for previewnet temporarily

ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs
* Redis eviction is probabilistic-based. It samples over the all non-expired entries and pick the ones with shortest TTL. But it's possible that a entry still being used is evicted. 
* Add the active eviction logic to avoid redis eviction kicks-in. 
ref: Cache storage status:
=> [indexer grpc] Actively delete expiring cache entries.

consensus/src/counters.rs, consensus/src/epoch_manager.rs, consensus/src/round_manager.rs
=> [Consensus] Dedicated channel for proposal processing

config/src/config/quorum_store_config.rs, consensus/src/quorum_store/batch_requester.rs
=> [eager cherry-pick] PR 7159: [Quorum Store] bump num_peers=5 and add monitor

storage/aptosdb/src/db_debugger/truncate/mod.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/pruner_utils.rs, storage/aptosdb/src/pruner/state_kv_pruner.rs, storage/aptosdb/src/pruner/state_kv_pruner_manager.rs, storage/aptosdb/src/pruner/state_store/state_value_pruner.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/state_kv_db.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/aptosdb/src/test_helper.rs, storage/aptosdb/src/utils/truncation_helper.rs, storage/schemadb/src/lib.rs
Add a wrapper class for StateKvDb.
Tested using executor benchmark.
=> [Stroage][Sharding] Add a wrapper for StateKvDb.

consensus/src/quorum_store/quorum_store_db.rs
To allow breaking change in DB
=> [previewnet only] temporarily change QS db path

config/src/config/quorum_store_config.rs, types/src/on_chain_config/consensus_config.rs
The current default shows regression in land_blocking
Run land_blocking
=> [Quorum Store] increase default backlog_txn_limit_count

developer-docs-site/scripts/additional_dict.txt
=> Added PowerShell and MSVC to the list

config/src/config/quorum_store_config.rs, consensus/src/quorum_store/batch_store.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/quorum_store_builder.rs, consensus/src/quorum_store/tests/batch_store_test.rs
=> max num batches for quota manager

developer-docs-site/scripts/additional_dict.txt
=> Add terms from latest external resources

aptos-move/framework/aptos-stdlib/doc/simple_map.md, aptos-move/framework/aptos-stdlib/sources/simple_map.spec.move, aptos-move/framework/move-stdlib/doc/vector.md, aptos-move/framework/move-stdlib/sources/vector.move
Fix the broken spec regarding vector and simple_map
=> [Spec] Fix the broken spec regarding vector and simple_map

consensus/src/lib.rs
the counter is not decremented if there's return statement inside the $fn, using a guard to fix it
=> [consensus] fix the monitor macro

crates/aptos/CHANGELOG.md, crates/aptos/src/account/create_resource_account.rs, crates/aptos/src/account/derive_resource_account.rs, crates/aptos/src/account/mod.rs, crates/aptos/src/move_tool/mod.rs
Adds ability to derive resource accounts, and fixes the behavior where onchain and offchain representations of passing in a string were different.
Additionally, adds the long awaited CLI changelog
```
$ ./target/debug/aptos account derive-resource-account-address --address devnet --seed 0x6162 --seed-encoding hex
{
"Result": "cba9515383e5893d0eca1b581386326ed1113585f9e06af7fcc0a7df684fd6b7"
}
$ ./target/debug/aptos account derive-resource-account-address --address devnet --seed 0x6162 --seed-encoding bcs
{
"Result": "81002ccd78f77a46eb06bd8458f41f41d44ba5293f7a153f51dfa4058fa36df6"
}
$ ./target/debug/aptos account derive-resource-account-address --address devnet --seed 0x6162 --seed-encoding utf8
{
"Result": "40994409e77d2096e3e2665cb20209fddae2fad74ef5422f7f3d76615bd29a52"
}
$ …
```
=> [cli] Add ability to derive resource account and changelog

crates/aptos/CHANGELOG.md
Update changelog for 1.0.8 release
=> [cli] Set changelog for 1.0.8

developer-docs-site/docs/guides/getting-started.md
Cleans up some weird double boxing that doesn't look right
=> [docs] Fix double boxing for checkout commands on getting started

developer-docs-site/scripts/additional_dict.txt
=> Add hotfix and Paymagic to spellcheck list

Cargo.lock, Cargo.toml
=> [deps] Upgrade dependencies

.github/actions/docker-setup/action.yaml
Reverts aptos-labs/aptos-core#7170
=> Revert "Pin crane version in docker-setup" (#7214

docker/compose/aptos-node/validator.yaml, terraform/helm/aptos-node/files/configs/validator-base.yaml
This PR removes unnecessary config overrides for state sync.
Nonde.
=> [Configs] Remove overrides.

consensus/src/quorum_store/quorum_store_db.rs
=> [previewnet only] prep for another QS DB breaking change

ecosystem/indexer-grpc/indexer-grpc-data-service/README.md, ecosystem/indexer-grpc/indexer-grpc-data-service/src/main.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs, ecosystem/indexer-grpc/indexer-grpc-parser/README.md, ecosystem/indexer-grpc/indexer-grpc-parser/src/worker.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/config.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs
* Added authentication for data service & processor. 
* Auth tested successfully locally.
=> Add authentication for data service + processors

config/src/config/consensus_config.rs
=> increase block size without QS

config/src/config/network_config.rs, config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/aptosnet/metrics.rs, state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs, state-sync/state-sync-v2/data-streaming-service/src/metrics.rs
This PR offers two commits:
1. Update some state sync and network configs for testing. 
2. Improve some metrics around the data client and streaming service.
=> [Configs and metrics] Tweak configs and improve metrics.

docker/compose/aptos-node/validator.yaml, terraform/helm/aptos-node/files/configs/validator-base.yaml
This PR removes the unnecessary state sync configs from the default terraform yaml file.
None.
=> [Terraform Configs] Remove unnecessary override.

docker/compose/aptos-node/validator.yaml, terraform/helm/aptos-node/files/configs/validator-base.yaml
Already deployed to previewnet.
=> Cherry-pick to preview: [Terraform Configs] Remove unneccessary override.

consensus/src/block_storage/sync_manager.rs
=> increase distance before state sync - cherry pick  Zekun/experiment #7249

consensus/src/epoch_manager.rs, consensus/src/network.rs, consensus/src/quorum_store/quorum_store_builder.rs
=> message order and buffer size

crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-emitter-lib/src/wrappers.rs
=> more and earlier retries, and better logging in txn emitter

docker/release-images.mjs
=> [indexer grpc][docker] indexer grpc docker image release.

developer-docs-site/docs/concepts/index.md
Fixes some of the links that were missing `.md`
=> Fix concepts links

developer-docs-site/docs/guides/system-integrators-guide.md
Updates faucet links and some typos
=> [docs] Update system integrators guide links

crates/aptos/src/move_tool/mod.rs
This was the same message as `aptos move run`.
👀
=> Update help text for aptos move view

aptos-move/e2e-move-tests/src/tests/token_objects.rs, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/framework/aptos-stdlib/doc/from_bcs.md, aptos-move/framework/aptos-stdlib/sources/from_bcs.move, aptos-move/move-examples/token_objects/sources/aptos_token.move, aptos-move/move-examples/token_objects/sources/collection.move, aptos-move/move-examples/token_objects/sources/hero.move, aptos-move/move-examples/token_objects/sources/property_map.move, aptos-move/move-examples/token_objects/sources/royalty.move, aptos-move/move-examples/token_objects/sources/token.move
* Move mutability configuration out of collection and token
* Make a no code tokenv2 with some core properties
* Property maps
* Burnable tokens
=> [tokenv2] start building standalone no-code token

aptos-move/framework/aptos-framework/doc/aggregator.md, aptos-move/framework/aptos-framework/doc/aggregator_factory.md, aptos-move/framework/aptos-framework/doc/aptos_governance.md, aptos-move/framework/aptos-framework/doc/block.md, aptos-move/framework/aptos-framework/doc/coin.md, aptos-move/framework/aptos-framework/doc/consensus_config.md, aptos-move/framework/aptos-framework/doc/gas_schedule.md, aptos-move/framework/aptos-framework/doc/optional_aggregator.md, aptos-move/framework/aptos-framework/doc/reconfiguration.md, aptos-move/framework/aptos-framework/doc/stake.md, aptos-move/framework/aptos-framework/doc/staking_contract.md, aptos-move/framework/aptos-framework/doc/transaction_fee.md, aptos-move/framework/aptos-framework/doc/version.md, aptos-move/framework/aptos-framework/sources/aggregator/aggregator.spec.move, aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.spec.move, aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.spec.move, aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move, aptos-move/framework/aptos-framework/sources/block.spec.move, aptos-move/framework/aptos-framework/sources/coin.move, aptos-move/framework/aptos-framework/sources/coin.spec.move, aptos-move/framework/aptos-framework/sources/configs/consensus_config.spec.move, aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move, aptos-move/framework/aptos-framework/sources/configs/version.spec.move, aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move, aptos-move/framework/aptos-framework/sources/stake.spec.move, aptos-move/framework/aptos-framework/sources/staking_contract.spec.move, aptos-move/framework/aptos-framework/sources/transaction_fee.spec.move, aptos-move/framework/move-stdlib/doc/option.md, aptos-move/framework/move-stdlib/sources/option.move, aptos-move/framework/src/aptos-natives.bpl
This PR: 
-   adds natives for aggregator
-   adds specs for `aggregator`, `aggregator_factory` and `optional_aggregator`
-   modifies related specs
=> [Spec] Add natives for aggregator and modify specs

api/src/context.rs, api/src/tests/resource_groups.rs, api/types/src/convert.rs, api/types/src/lib.rs, api/types/src/move_types.rs, aptos-move/aptos-vm/src/natives.rs
Currently resource group writeset is not getting parsed/deserialized correctly when converting to MoveValue
Updated e2e api tests
=> [API] Expand resource group writeset changes in transactions API

api/src/context.rs, api/src/tests/resource_groups.rs, api/types/src/convert.rs, api/types/src/lib.rs, api/types/src/move_types.rs
Cherrypick of https://github.com/aptos-labs/aptos-core/pull/7273 from main into v1.3
=> [Cherrypick][API] Expand resource group writeset changes in transactions API

ecosystem/indexer-grpc/indexer-grpc-parser/Dockerfile, ecosystem/indexer-grpc/indexer-grpc-parser/README.md, ecosystem/indexer-grpc/indexer-grpc-parser/parser.yaml
* Add document about how to work with indexer grpc for existing processors/parsers
* Tested on gcp with [docker image](https://hub.docker.com/r/aptoslabs/indexer-grpc/tags) looks good overall.
=> [Indexer GRPC ]updatet the readme for indexer grpc.

consensus/src/counters.rs, consensus/src/payload_manager.rs
=> [qs] add counters to monitor batch wait

network/src/protocols/wire/messaging/v1/mod.rs
=> [network] remove rate limiter that based on ip addr

aptos-move/framework/aptos-stdlib/doc/fixed_point64.md, aptos-move/framework/aptos-stdlib/sources/fixed_point64.move
Fix the prover test failure by adding a larger timeout
=> [Spec] Fix the prover test failure
