aptos-labs/aptos-core

Cargo.lock
api/types/src/convert.rs
api/types/src/lib.rs
crates/aptos-rest-client/Cargo.toml
crates/aptos-rest-client/src/lib.rs
crates/aptos/src/common/types.rs

This is the last CLI change that's needed to cleanup the default max gas in the CLI.
This fixes Error descriptions, by pulling from the onchain bytecode.  This allows people to actually see why they failed.
Additionally, makes the CLI by default no longer have a fixed max gas amount.  It will now always use estimation.  This also gives the basis for providing proper error messages in Rosetta as well via the Rest client.
CLI now stops beforehand rather than still sending failed transactions with an explained error:
```
$ aptos account transfer --profile testnet --account testnet-operator --amount 10
{
"Error": "Simulation failed with status: Move abort in 0x1::coin: 0x60005"
}
```
Successful actions will tell you the range (from the amount simulated, to what the max gas is being set to …

[aptos-rest-client] Fix Error descriptions for simulated transactions / Remove default max gas for CLI

---

consensus/src/block_storage/block_store_test.rs
consensus/src/block_storage/sync_manager.rs

There's no guarantee that nodes still have blocks beyond committed block, the current condition for sync allows a gap between local ordered round and remote committed round.
There's an edge case that remote peer may have already pruned those blocks in between and the node would never be able to sync the gap.
The fix guarantees the node always syncs if the remote committed block doesn't exist locally and only fetch blocks that are ancestors of committed block.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4445)

[consensus] fix edge case of block retrieval

---

crates/aptos-rosetta/src/construction.rs
crates/aptos-rosetta/src/types/requests.rs

Adds debugging information to parse transaction in Rosetta.  Lets the viewer see all
the details for the transaction.
E2E tests, but otherwise none
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4458)

[aptos-rosetta] Put decoded full transaction into parse transaction

---

storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_restore/restore_test.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/jellyfish-merkle/src/lib.rs
storage/jellyfish-merkle/src/mock_tree_store.rs
storage/jellyfish-merkle/src/node_type/node_type_test.rs
storage/jellyfish-merkle/src/restore/mod.rs

Take a version now so fast sync wouldn't take a wrong leaf node at a different version in any case.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4123)

[storage] get_rightmost_leaf take a version

---

crates/indexer/migrations/2022-09-04-194128_add_token_data/up.sql
crates/indexer/migrations/2022-09-20-055651_add_current_token_data/down.sql
crates/indexer/migrations/2022-09-20-055651_add_current_token_data/up.sql
crates/indexer/src/database.rs
crates/indexer/src/indexer/tailer.rs
crates/indexer/src/indexer/transaction_processor.rs
crates/indexer/src/models/collection_datas.rs
crates/indexer/src/models/mod.rs
crates/indexer/src/models/token_datas.rs
crates/indexer/src/models/token_utils.rs
crates/indexer/src/models/tokens.rs
crates/indexer/src/processors/default_processor.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/schema.rs
crates/indexer/src/util.rs
testsuite/smoke-test/src/indexer.rs

* Cleaned up code a bit with types
* Added current token tables
* Make sure that for current token tables, only latest will be overridden (i.e. current transaction processing > last transaction stored in db)
Ran locally and against devnet
Specifically to make sure that only latest will be overridden, I did extensive manual testing for now. 
1. Version 13760 has token X, amount 1
2. Ran indexer w/ mocked data: hardcoded to version 13761 with amount 1000, pulled token X and observed that it was updated
3. hardcoded to version 13761 with amount 9000, pulled token X and observed that it was *not* updated
4. hardcoded to version 13760 with amount 9000, pulled token X and observed that it was *not* updated
5. hardcoded to version 13770 with amount 9000, pulled token X and observed that it was …

[Indexer] Create current token tables

---

aptos-move/e2e-move-tests/tests/code_publishing.data/pack_stdlib/sources/configs/features.move
aptos-move/e2e-move-tests/tests/code_publishing.data/pack_stdlib/sources/configs/features.spec.move
aptos-move/e2e-move-tests/tests/code_publishing.data/pack_stdlib_incompat/sources/configs/features.move
aptos-move/e2e-move-tests/tests/code_publishing.data/pack_stdlib_incompat/sources/configs/features.spec.move
aptos-move/framework/aptos-framework/sources/code.move
aptos-move/framework/move-stdlib/sources/configs/features.move
aptos-move/framework/move-stdlib/sources/configs/features.spec.move

This requires unfortunately that the boolean functions checking for features cannot be longer friends (and henceforth need to stay and cannot be remove), but otherwise seems to be straightforward.
Existing tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4467)

[framework] Move `features.move` into stdlib so it can be used from everywhere

---

crates/aptos/src/governance/mod.rs
crates/aptos/src/move_tool/mod.rs
crates/aptos/src/test/mod.rs

The remote git framework can be cached funny, and for the need for speed it should not have users be pulling down a git repo that they may already have.
This is also needed to test creating proposals, and running scripts
E2E tests, as well as some testing
```
aptos move run-script --script-path script.move --framework-local-dir /opt/git/aptos-core/aptos-move/framework/aptos-framework
Do you want to execute a transaction for a maximum of 10000000 coins at a gas unit price of 100? [yes/no] >
yes
{
"Result": {
"transaction_hash": "0x875c36d8f6f68134365014df03e1ed200b6197f035ffd61df292981f87722554",
"gas_used": 151,
"sender": "b6dbf76636021a840c64da0ca6aa94297b4ead015f7398521f57347f68364898",
"sequence_number": 0,
"timestamp_us": 1663787494093360, …
```

[aptos-cli] Allow compiling scripts and proposals with local framework

---

aptos-move/aptos-vm/src/aptos_vm.rs
crates/aptos/src/genesis/keys.rs
crates/aptos/src/genesis/mod.rs
execution/db-bootstrapper/src/bin/db-bootstrapper.rs
testsuite/forge/src/backend/k8s/swarm.rs
testsuite/forge/src/backend/local/swarm.rs
testsuite/forge/src/interface/swarm.rs
testsuite/smoke-test/src/genesis.rs
testsuite/smoke-test/src/lib.rs
testsuite/smoke-test/src/test_utils.rs

Resurrect the writeset generator tool to generate the genesis writeset need to apply to nodes manually in case of network outages. 
`cargo test --package smoke-test --lib -- genesis::test_genesis_transaction_flow --exact --nocapture`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4037)

[aptos-cli] Add a command to generate writeset for fire events

---

aptos-move/framework/aptos-framework/sources/genesis.move
aptos-move/vm-genesis/src/lib.rs

This keeps things simple as we do not need to deal with some stake pools being owned by direct owner accounts and some owned through the staking_contract module.
Existing unit + e2e tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4466)

[Genesis] Always create staking contracts in mainnet genesis

---

Cargo.lock
Cargo.toml
aptos-move/aptos-gas/Cargo.toml
aptos-move/aptos-gas/src/bin/gen_proposal.rs
aptos-move/aptos-gas/src/gas_meter.rs
aptos-move/aptos-gas/src/gen.rs
aptos-move/aptos-gas/src/lib.rs
aptos-move/aptos-gas/tests/gen_tests.rs
aptos-move/e2e-move-tests/Cargo.toml
aptos-move/e2e-move-tests/src/lib.rs
aptos-move/e2e-move-tests/tests/code_publishing.rs
aptos-move/e2e-move-tests/tests/generate_upgrade_script.rs
aptos-move/e2e-move-tests/tests/lazy_natives.rs
aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs
aptos-move/package-builder/Cargo.toml
aptos-move/package-builder/src/lib.rs
aptos-move/vm-genesis/src/lib.rs

This adds a script to generate the gas schedule update proposal.
To run the script:
```
cargo run -p aptos-gas -o <output path>
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4471)

[gas] add script to generate gas schedule update proposal

---

crates/aptos/src/account/create_resource_account.rs
crates/aptos/src/account/fund.rs
crates/aptos/src/account/transfer.rs
crates/aptos/src/common/init.rs
crates/aptos/src/common/types.rs
crates/aptos/src/common/utils.rs
crates/aptos/src/node/mod.rs
crates/aptos/src/stake/mod.rs
crates/aptos/src/test/mod.rs
crates/aptos/src/test/tests.rs
testsuite/smoke-test/src/rosetta.rs

We were using the non-create with transfer in the CLI.  We should fix this accordingly.
Tested with manual testing
```
aptos account transfer --profile devnet --account 0x77 --amount 50
Do you want to submit a transaction for a range of [26200 - 39300] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
"Result": {
"gas_used": 271,
"balance_changes": {
"0000000000000000000000000000000000000000000000000000000000000077": {
"coin": {
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4473)

[aptos-cli] Move to using account transfer over coin transfer

---

aptos-move/framework/aptos-framework/sources/storage_gas.move

init_module isn't called on package upgrade even for new modules,  therefore we forever get to expose this initialize method  so that we  can call it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4368)

[framework] prepare for testnet upgrade

---

crates/node-resource-metrics/src/lib.rs

Double register caused node to crash.  Now there's a mutex so it doesn't double register
Ran node locally, didn't crash immmediately
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4482)

[node-resource-metrics] Fix double prometheus register

---

Cargo.lock
crates/aptos-telemetry-service/Cargo.toml
crates/aptos-telemetry-service/src/auth.rs
crates/aptos-telemetry-service/src/clients/humio.rs
crates/aptos-telemetry-service/src/clients/mod.rs
crates/aptos-telemetry-service/src/context.rs
crates/aptos-telemetry-service/src/custom_event.rs
crates/aptos-telemetry-service/src/jwt_auth.rs
crates/aptos-telemetry-service/src/lib.rs
crates/aptos-telemetry-service/src/log_ingest.rs
crates/aptos-telemetry-service/src/prometheus_push_metrics.rs
crates/aptos-telemetry-service/src/remote_config.rs
crates/aptos-telemetry-service/src/tests/auth_test.rs
crates/aptos-telemetry-service/src/tests/custom_event.rs
crates/aptos-telemetry-service/src/tests/test_context.rs
crates/aptos-telemetry-service/src/types/mod.rs
crates/aptos-telemetry-service/src/validator_cache.rs
crates/aptos-telemetry/src/service.rs

This PR introduces a set of security-audit related fixes to the Telemetry service.
- Removes fields that hold secrets from config. The config is logged at service startup and was logging the secrets.
- Secrets are read from the environment variables. 
- Unit tests pass
- Verified telemetry ingestion running a test node and the service locally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4433)

[telemetry-service] security audit fixes and related refactorings

---

mempool/src/tests/integration_tests.rs

The test fails and succeeds on retry in CICD sometimes: only the first transaction is propagated. There is a race condition where the broadcast from the pfn happens after txn0 is added but before txn1 is added. In that case, only txn0 is broadcasted (because the test is instrumented to only send a single message). By adding the txns first, we can avoid this.
Will have to observe if flakiness goes down after land.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4468)

[mempool] possibly fix flaky fn_to_val_test

---

sdk/examples/transfer-coin.rs
sdk/src/coin_client.rs

Close https://github.com/aptos-labs/aptos-core/issues/4470
Increase `gas_unit_price` to fix error `GAS_UNIT_PRICE_BELOW_MIN_BOUND` in issue https://github.com/aptos-labs/aptos-core/issues/4470.
Test with command `cargo run --example transfer-coin` in `sdk` folder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4485)

[Bug] [Rust SDK] Increase `gas_unit_price` and fund balance in `transfer-coin` example

---

.github/workflows/continuous-e2e-graceful-overload-test.yaml
crates/transaction-emitter-lib/src/cluster.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/emitter/submission_worker.rs
crates/transaction-emitter/src/diag.rs
testsuite/forge-cli/src/main.rs
testsuite/forge/src/backend/k8s/swarm.rs
testsuite/testcases/src/lib.rs

Add graceful_overload test to confirm we see high TPS even when we send more txn than the system can handle.
(separate PR for high gas-fee txns going through)
Fix ConstTps txn-emitter to wait enough for transactions to be committed
When we overload the system, individual nodes can start being stale, so in order to check that transaction was definitelly not committed, we need to wait for ledger timestamp to be passed.
So change time waits to be based on ledger timestamp / txn expiration time, instead of relative.
Add some more (sampled) logs to help with future debugging
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4354)

[txn-emitter] Add Graceful Forge test, and Fix ConstTps txn-emitter

---

mempool/src/core_mempool/mempool.rs
mempool/src/counters.rs
mempool/src/shared_mempool/tasks.rs

We have txn/committed block counter, but without re-serializing things there, I cannot easily get the size. This seems an easy place to measure it, and it also enables us to easily see if different nodes are trying to propose different sizes as well (irrespective of whether those land on the blockchain)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4460)

[mempool] Add counter for created block size in txn count and byte size

---

testsuite/smoke-test/src/smoke_test_environment.rs
testsuite/smoke-test/src/storage.rs
testsuite/smoke-test/src/txn_broadcast.rs

Adding retries on a couple tests in #4437 seems to have worked. They have not flaked on local swarm startup. So expanding to all local swarm startup.
(same as #4437) Injected a retry and at least confirmed that we can successfully create a new swarm after having created a swarm (that was itself successful).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4461)

[smoke tests] local swarm build retries 3 times

---

config/src/config/consensus_config.rs
docker/compose/aptos-node/validator.yaml
terraform/helm/aptos-node/files/configs/validator.yaml
terraform/helm/aptos-node/values.yaml

- reduce block size to 2.5k (to reduce chance of stalls and lags, while potentially trading off some minimal TPS)
- corresponding max bytes should be 500-600k, to have the similar load
- I think we wanted to increase quorum poll count to be around 250ms, correct?
- made all three deployments have the same configs
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4505)

[configs] Update block size (txns/bytes) and make configs consistent across deployments

---

aptos-move/framework/aptos-framework/sources/aptos_governance.move
aptos-move/framework/aptos-framework/sources/voting.move

This is not a critical issue if proposal resolution always happens instantly but can be an issue otherwise as outcome can change with more votes coming in after the voting period is already over.
New unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4518)

[Aptos Framework][Voting][Audit issue] Do not allow changing votes after voting is over

---

aptos-move/framework/aptos-token/sources/property_map.move
aptos-move/framework/aptos-token/sources/token.move
aptos-move/framework/aptos-token/sources/token_coin_swap.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs

When creator creates NFTs, they can add a control flag in the default properties to indicate if the token is burnable by owner or creator.
These control flags are stored in default property map, which is immutable after token creation. 
The default behavior is the token cannot be burned by either owner or creator unless there is a config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4358)

[Token] add burn control flag

---

aptos-move/framework/aptos-token/sources/token.move

Add helpers to check to see if tokenstore exists, and to not explode for a balance check if tokenstore doesn't exist
Added test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4516)

[TOK] Add helpers to token

---

crates/aptos-faucet/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4529)

observability: structured logging for faucet requests

---

aptos-move/framework/aptos-framework/sources/stake.move

Otherwise the validator set could technically exceed the max allowed by one. This is a very minor issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4532)

[Staking][Minor fix] Enforce max validator set size after adding the validator

---

developer-docs-site/docs/guides/building-your-own-wallet.md

Add multi-signer account case to building-your-own-wallet and update some interfaces.
Just update document. No test needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4416)

Add multi-signer wallet doc

---

aptos-move/e2e-move-tests/src/tests/stake.rs
aptos-move/e2e-tests/src/account.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4537)

[Tests only] Add an e2e test for staking_contract flow

---

mempool/src/core_mempool/transaction_store.rs
mempool/src/logging.rs
testsuite/forge-cli/src/main.rs

There was a bug where GC'd txns were not showing up in metrics, because `get_insertion_time` did not return anything. Instead, directly use `txn.insertion_time`.
Ran 15K TPS test. Where previously no GC's are shown, now client expired txns show up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4502)

[mempool] fix GC'd txn metric

---

crates/aptos-rest-client/src/lib.rs
testsuite/forge-cli/src/main.rs

- looked through consensus stress/failure tests, and updated configuration to hopefully make all reliable
after this, only nft_mint (orthogonal issues), and some failures in txn-emitter due to #4456 should be left.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4515)

[forge] Fix continuous forge tests by updating configurations

---

storage/backup/backup-cli/src/bin/db-backup.rs
storage/backup/backup-cli/src/coordinators/backup.rs
storage/backup/backup-cli/src/metadata/view.rs
testsuite/smoke-test/src/storage.rs

There's the edge case where the only state snapshot is at a newer version than all txn backups.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4524)

[backup] fix still flaky smoke test test_db_restore

---

crates/aptos/src/node/mod.rs
crates/aptos/src/test/mod.rs
crates/aptos/src/test/tests.rs

We now have three type of stake pools an account can own:
1. Directly via the stake module
2. Via forming multiple staking contracts with different operators
3. Indirectly via vesting module
Manual tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4503)

[Node CLI] Add a command that returns the stake pool address

---

.github/workflows/copy-images-to-dockerhub.yaml

We wait in a separate GHA workflow for all docker builds to succeed, before copying them into Doeckerhub. This is done with a 3rd party github action, which waits on regexp of github job name
regexp sometimes doesn't work well with retries. This PR makes it such that we only wait on the release image builds `rust-images / rust-all`, rather than everything named `rust-images.*` (includes performance and testing builds, etc)
https://github.com/aptos-labs/aptos-core/actions/runs/3115987663/jobs/5053810467
```
Checks completed:
rust-images-performance / rust-all: completed (success)
rust-images / rust-all: completed (success)
rust-images-indexer / rust-all: completed (success)
rust-images-testing / rust-all: completed (success)
rust-images-testing / rust-all: completed (cancelled)
rust-images …
```

[gha] only copy release images to dockerhub

---

aptos-move/framework/aptos-framework/sources/coin.move
aptos-move/framework/aptos-framework/sources/reconfiguration.move

Coin can now be unfrozen. I preferred the term 'unfreeze' to 'thaw' (like on Solana) because I thought it was simpler, but either function name works for me.
I added a unit test in the coin.move module.
closes #3850
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4065)

[Community] Add coin::unfreeze_coin_store function to coin module

---

aptos-move/aptos-sdk-builder/src/common.rs
aptos-move/aptos-sdk-builder/src/golang.rs

Go SDK generation was conflicting on string and vec<u8> and we'll assume this will be an issue in other languages as well, so we rename the base type.
Additionally, fix the type for Go.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4563)

[sdk-builder] Ensure string encoding is named a separate function

---

crates/transaction-emitter-lib/src/emitter/submission_worker.rs

This debugging log was added to show txns around the failure, but when it is the first request, there is no previous transaction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4567)

[txn-emitter] Fix underflow when first request fails

---

scripts/dev_setup.sh

This failed on a new machine because unzip didn't exist.  Now it's fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4557)

[dev setup] Ensure unzip installed before protoc

---

Cargo.lock
aptos-move/aptos-gas/Cargo.toml
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/framework/src/built_package.rs
aptos-move/framework/src/error_map.rs
aptos-move/gas-algebra-ext/Cargo.toml
aptos-move/move-deps/Cargo.toml

This branch contains the most recent fixes on the vm. Others updates are related to the prover, the Move book, and a new flag to the CIL to update git deps automatically.
For the full PR which updates the aptos branch see [here](https://github.com/move-language/move/pull/506).
Most of the VM changes have been already merged into testnet before, besides the latest ones which are around stabilization.
Existing tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4571)

[move] Update to latest commit of `aptos` release branch in Move repo

---

.github/workflows/docker-build-test.yaml

As a follow up to last week breakage, this attempts to run pull request and
pull request target to make sure that changes to a workflow using pull request
target are both forwards and backwards compatible.
For context, right now if you modify a workflow with pull reqeust target it
will not actually test the workflow on PR so you can break it completely and
the PR would just happily land immediately breaking all workflows!!!!
The longer term that would be ideal is getting rid of pull reqeust target
because currently its impossible to version.
Test Plan: ensure pull request running and passes on PR #e2e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4551)

[gha] Conditionally run pull request and pull request target based on files changed

---

crates/aptos-compression/src/lib.rs
crates/aptos-compression/src/tests.rs
mempool/src/tests/common.rs
network/src/protocols/wire/handshake/v1/mod.rs
state-sync/storage-service/types/src/responses.rs

Adding limits to compression:
* On the receiving end, a limit is needed to prevent malicious node from sending messages that decompress into a large size. Given lz4, decompression could have been as large as 2 GiB (i32::MAX).
* On the sending end, a limit is needed to ensure delivery of the compressed message to honest nodes.
Each call will have to set a limit; for network messages `MAX_APPLICATION_MESSAGE_SIZE` should be a good value as anyway the message needs to be sent over the network.
Add unit test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4556)

[compression] limit (de)compression, to network application limit size

---

.github/workflows/continuous-e2e-account-creation-test.yaml
.github/workflows/continuous-e2e-changing-working-quorum-test copy.yaml
.github/workflows/continuous-e2e-changing-working-quorum-test-high-load.yaml
.github/workflows/continuous-e2e-compat-test.yaml
.github/workflows/continuous-e2e-consensus-stress-test.yaml
.github/workflows/continuous-e2e-different-node-speed-and-reliability-test.yaml
.github/workflows/continuous-e2e-full-node-reboot-stress-test.yaml
.github/workflows/continuous-e2e-graceful-overload-test.yaml
.github/workflows/continuous-e2e-network-latency-test.yaml
.github/workflows/continuous-e2e-network-partition-test.yaml
.github/workflows/continuous-e2e-nft-mint-test.yaml
.github/workflows/continuous-e2e-performance-test.yaml
.github/workflows/continuous-e2e-single-vfn-test.yaml
.github/workflows/continuous-e2e-state-sync-perf-fullnode-apply-test.yaml
.github/workflows/continuous-e2e-state-sync-perf-fullnode-execute-test.yaml
.github/workflows/continuous-e2e-state-sync-perf-validator-test.yaml
.github/workflows/continuous-e2e-validator-reboot-stress-test.yaml
.github/workflows/twin-validator-test.yaml
testsuite/forge/src/backend/k8s/stateful_set.rs

Better forge error for statefulset state
Also randomly select continuous forge runs on GHA rather than just using forge-big-1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4582)

[forge] better sts errors

---

crates/aptos-genesis/src/builder.rs
crates/aptos-genesis/src/config.rs
crates/aptos/src/genesis/mod.rs
terraform/helm/genesis/files/genesis.sh

This will save validators who are joining post genesis from having to generate and verify operator.yaml file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4569)

[Genesis][Tooling] Allow skipping operator config file if validator is not joining genesis validator set

---

.github/workflows/continuous-e2e-haproxy-test.yaml

Run the default `land_blocking` performance test suite in Forge with HAProxy enabled, continuously every 3 hr.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4391)

[gha] test haproxy in forge continuously

---

ecosystem/typescript/sdk/src/aptos_client.ts

The query params for getting txns by account are sequence number based, not txn version based.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4549)

fix: fix the interface doc about getting txns for by account

---

ecosystem/typescript/sdk/src/aptos_client.ts

nodeUrl could be useful information for many use cases. Per user request, re-expose nodeUrl.
yarn test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4553)

feat(ts-sdk): expose nodeUrl

---

api/src/transactions.rs

Simulation endpoints did not expose Move error details. Aptos wrapped Move execution error details in execution output not the vanilla Move execution status. This PR allows clients to see the Move error details when running the simulations.
Before, printing exec_status:
MoveAbort { location: 0000000000000000000000000000000000000000000000000000000000000003::token, code: 65543, info: None }
After, printing exec_status:
MoveAbort { location: 0000000000000000000000000000000000000000000000000000000000000003::token, code: 65543, info: Some(AbortInfo { reason_name: "EMINT_WOULD_EXCEED_TOKEN_MAXIMUM", description: "Exceed the token data maximal allowed" }) }
End to end:
- - - …

[Api] Expose Move error details for simulation endpoints

---

docker/compose/aptos-node/blocked.ips
docker/compose/aptos-node/docker-compose.yaml
docker/compose/aptos-node/haproxy.cfg
terraform/helm/aptos-node/files/haproxy.cfg
terraform/helm/aptos-node/values.yaml

Re-Enabling haproxy and adding more CPU+Mem to haproxy nodes.
- Join AIT3 with haproxy node
- run 100 validator forge with haproxy
- manual testing with /testsuite/ddos/ tools.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4336)

Increasing haproxy resources

---

config/src/config/storage_config.rs

As discussed.
Follow up issue:
https://linear.app/aptoslabs/issue/BLK-140/[db][after-launch]-smart-state-merkle-pruner-window
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4610)

[storage] larger default state prune window

---

crates/aptos/Cargo.toml

Add indexer feature to aptos cli so that we can run localnet with indexer
```
cargo run -p aptos --features indexer node run-local-testnet --with-faucet
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4586)

[Indexer] Add indexer to aptos cli

---

consensus/src/block_storage/sync_manager.rs
consensus/src/epoch_manager.rs
consensus/src/lib.rs
consensus/src/persistent_liveness_storage.rs
consensus/src/recovery_manager.rs
consensus/src/test_utils/mock_storage.rs
testsuite/smoke-test/src/consensus/consensusdb_recovery.rs
testsuite/smoke-test/src/consensus/mod.rs

This commit allows node to sync without a consensus db and the process would exit after it finishes and the validator can operator normally after restart.
It's not ideal that it requires another restart but it's better than what we have today.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4475)

[consensus] support a recovery mode if consensusdb is gone

---

terraform/helm/aptos-node/templates/fullnode.yaml
terraform/helm/aptos-node/templates/validator.yaml
terraform/helm/aptos-node/values.yaml
testsuite/forge/src/backend/k8s/helm-values/aptos-node-default-values.yaml

This PR enables the node's telemetry in forge to assert the telemetry crate code paths during forge tests. A bug introduced in #4443 was uncaught in forge e2e test because the telemetry crate wasn't enabled. 
Enabling the `APTOS_FORCE_ENABLE_TELEMETRY` env variable does not still assert the telemetry web service code path in forge, but it's not in the critical path of the nodes' operation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4490)

[forge][telemetry] Enable node telemetry service in forge

---

.github/workflows/lint-test.yaml
execution/executor-test-helpers/src/integration_test_impl.rs

when run via `cargo nextest -p executor`, GAS_UNIT_PRICE is 100 instead of 0 as in unit tests or when it's run via `cargo nextest --workspace`. Better to make it work with non-zero gas charge anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4608)

[executor] fix integration test helper

---

.github/workflows/forge-continuous.yaml
.github/workflows/run-forge.yaml
testsuite/forge.py
testsuite/forge_test.py

Namespace should be optional, this allows for overlapping test runs which could
exhaust capacity, however that risk is already present and this shouldnt be our
defense against overscheduling.
Test Plan: this pr will run forge-continuous and run-forge as pull request which will actually test this! :D
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4603)

[gha] Make forge namespace optional

---

.github/workflows/continuous-e2e-release-test.yaml
.github/workflows/run-forge.yaml

Change the release test to run (for only 5 mins) on PR and also to enable
haproxy on the release test for more confidence around haproxy change.
Test Plan: this workflow will run for a short time on the PR itself
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4609)

[gha] Enable release on PR, enable HAProxy on release test

---

aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381.move
aptos-move/framework/aptos-stdlib/sources/pool_u64.move

Currently scaling_factor is useless as the calculation multiplies by it and then immediately divides. This PR makes it useful in minimize rounding errors by multiplying shares by it.
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4558)

[Aptos Stdlib][Audit] Make scaling factor actually useful in pool_u64

---

Cargo.lock
crates/aptos-rest-client/Cargo.toml
crates/aptos-rest-client/src/lib.rs
crates/aptos/src/account/fund.rs
crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/transaction_generator/nft_mint.rs
ecosystem/python/sdk/aptos_sdk/client.py
testsuite/smoke-test/src/rest_api.rs
testsuite/smoke-test/src/rosetta.rs

Previously wait_for_transaction waited only for 60 seconds, and then failed, even if expiry didn't finish. 
Error message was confusing (timeout vs expired), so clarifying all messages better (so user knows if transaction can still succeed or not)
But it seems very odd to not wait to the expiry time passed in, so fixing that. 
wait_for_transaction_by_hash(_bcs) are now configurable with:
server_lag_timeout_after_expiry: Option<Duration>,
timeout_from_call: Option<Duration>,
First one is to finish at some point if rest endpoint is too stale. second one is if a caller wants absolute timeout (even before expiry)
Previously default would be server_lag_timeout_after_expiry=None and timeout_from_call=60s, and I am putting that for now in all other methods …

[API Client] Fix wait_for_transaction to wait for expiry and return better messages

---

aptos-move/aptos-vm/src/natives.rs

The native vector implementations in the Move stdlib are not longer needed as vectors are since a while implemented via new opcodes. Still someone could call them by manipulating bytecode. This PR just filters those natives from the list of Aptos natives. If in the future someone calls into them, this will generate a VM error.
Existing tests pass without those natives
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4621)

[move] Do not include vector native implementations

---

aptos-move/framework/aptos-framework/sources/timestamp.move

nits
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4619)

[audit] timestamp.move

---

crates/aptos/src/common/types.rs
crates/aptos/src/test/mod.rs

We saw bunch of timeouts with 10s timeout during loadtests, and then the experience is confusing - transaction actually goes through, but that is not clear.
We used 30s timeout for txn emitter, and that worked well.
together with #4456, CLI experience should be better now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4628)

[cli] Increase REST endpoint timeout to 30s

---

aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/bit_vector.move
aptos-move/framework/move-stdlib/sources/bit_vector.move

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4654)

[Prover spec only] Fix a typo in the bit_vector.move's prover specs

---

aptos-move/framework/aptos-framework/sources/stake.move
aptos-move/framework/aptos-framework/sources/stake.spec.move

- Fixed the spec which was broken due to the recent change in the module
- `remove_validators_internal` is removed. It was needed for specification, but not anymore.
cargo test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4656)

[Stake] Fixed the spec in the stake module

---

aptos-move/aptos-gas/src/gas_meter.rs
aptos-move/aptos-gas/src/table.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs

Previously I forgot to set the initial gas parameters for table. This gets them added and also makes sure that when a table op loads data from storage, it is charged in the same way as other global operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4659)

[gas] initial gas parameters for table operations

---

aptos-move/framework/aptos-framework/sources/voting.move

This can protect against any attacks (although unlikely) that try to vote + execute proposal in a single transaction.
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4612)

[Voting] Ensure proposal execution cannot happen in the same transaction as the last vote

---

aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs
crates/aptos/src/account/fund.rs
crates/aptos/src/common/utils.rs

The underlying load balancer in front of the faucet doesn't allow for empty body.  This now supports that properly.
Additionally, this also supports `0x` in front of hashes, as well as updated the SDK changes.
```
apt account fund-with-faucet --profile local --account local
{
"Result": "Added 500000 Octas to account 5ddf80d85bcd7bd8b833a2589def64ca0cf7df18b8b5ed0d7bdd067658fc49e3"
}
apt account fund-with-faucet --profile testnet --account testnet
{
"Result": "Added 500000 Octas to account 5ddf80d85bcd7bd8b833a2589def64ca0cf7df18b8b5ed0d7bdd067658fc49e3"
}
apt account fund-with-faucet --profile testnet --account testnet
{
"Error": "API error: Faucet issue: 429 Too Many Requests"
}
```
- - - …

[cli] Fix cli faucet

---

Cargo.lock
storage/storage-interface/Cargo.toml
storage/storage-interface/src/async_proof_fetcher.rs

This could happen when execution fails and proof fetch gets dropped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4663)

[Execution][Fix] Do not panic when proof fetcher cannot send proof.

---

Cargo.lock
crates/aptos-rest-client/src/lib.rs
crates/aptos/Cargo.toml

Right now it's spitting out warnings in the CLI, and it should be info or lower.  I've changed these to DEBUG, as there's no reason to make people panic over a transaction not being present.
CICD
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4667)

[rest-client] Change warn level message to debug for a transaction not being present

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/e2e-move-tests/src/tests/init_module.rs

This invalidates the loader cache if an error happens either in module bundle loading or execution of `init_module`. In such case, none of the modules is committed to storage, but some may linger in the cache. This can lead to inconsistencies, like binding to `init_module` of an older (failed) version of a module.
The added test fails with the code before this PR, and succeeds with this one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4668)

[vm] Invalidate loader cache on module loading errors

---

aptos-move/framework/aptos-framework/sources/aggregator/aggregator.move

A simple fix in the documentation to say that subtracts are also parallelizable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4672)

[aggregator] Fixed the description of sub()

---

aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/bit_vector.move
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib_incompat/sources/bit_vector.move
aptos-move/framework/move-stdlib/sources/bit_vector.move

- Fix the spec mistake which has existed since the Move repo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4674)

[Prover] fix the spec of `bit_vector::unset`

---

aptos-move/framework/aptos-framework/sources/account.move

We discussed 4 approaches for this:
* Ignore it for now
* Use some timestamp to mitigate but not resolve
* Use top k bits to namespace resource accounts at the risk of breaking tools but making explicit
* Leverage probability and cryptographic complexity to recognize that there will never be a valid resource account address that maps to a private key and not break anything for anyone -- we went this direction
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4598)

[framework] eliminate front running of resource accounts

---

developer-docs-site/docusaurus.config.js

I didn't realize we never had a sitemap. Useful to have.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4653)

[Docs] Adding sitemap option.

---

.github/workflows/continuous-e2e-state-sync-failures-catching-up-test.yaml
.github/workflows/continuous-e2e-state-sync-slow-processing-catching-up-test.yaml
testsuite/forge-cli/src/main.rs
testsuite/forge/src/backend/k8s/swarm.rs
testsuite/forge/src/interface/swarm.rs
testsuite/forge/src/success_criteria.rs
testsuite/forge/src/test_utils/consensus_utils.rs
testsuite/testcases/src/consensus_reliability_tests.rs
testsuite/testcases/src/lib.rs

Adds two tests, where we send constant TPS, and have nodes get stale, and see that they catchup.
(will separately send a PR to add a check that they participate in the consensus)
- test 1 - cut network on a node for some period of time
- test 2 - make subset of nodes execute blocks slower (by adding sleep in aptos_vm block metadata processing)
run both on forge to confirm they pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4036)

[forge] Add state sync catching up stress tests

---

Cargo.lock
api/Cargo.toml
api/doc/spec.json
api/doc/spec.yaml
api/goldens/aptos_api__tests__index_test__test_get_index.json
api/src/index.rs
api/types/src/index.rs
api/types/src/lib.rs
crates/aptos-build-info/src/lib.rs
crates/aptos-rest-client/src/lib.rs
ecosystem/node-checker/src/configuration/types.rs
ecosystem/node-checker/src/evaluators/direct/types.rs
ecosystem/typescript/sdk/src/generated/models/IndexResponse.ts
ecosystem/typescript/sdk/src/generated/schemas/$IndexResponse.ts

The BCS type for `IndexResponse` is now named `IndexResponseBcs`.  The JSON type includes a new field `git_hash` which is an optional parameter, so it should be backwards compatible with the old version unless strict JSON matching is used by a downstream reader.
Tested manually.  It shows up on the JSON index
```
curl localhost:8080/v1
{"chain_id":4,"epoch":"3","ledger_version":"573","oldest_ledger_version":"0","ledger_timestamp":"1664557571835805","node_role":"validator","oldest_block_height":"0","block_height":"286","git_hash":"254d1af5f6d994d142a48c70528d861682c0908f"}%
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4662)

[api] Add git build hash as an extra optional field in the API

---

Cargo.lock
crates/transaction-emitter-lib/Cargo.toml
crates/transaction-emitter-lib/src/args.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/transaction_generator/account_generator.rs
crates/transaction-emitter-lib/src/transaction_generator/mod.rs
crates/transaction-emitter-lib/src/transaction_generator/nft_mint_and_transfer.rs
crates/transaction-emitter-lib/src/transaction_generator/p2p_transaction_generator.rs
crates/transaction-emitter-lib/src/transaction_generator/transaction_mix_generator.rs
testsuite/forge-cli/src/main.rs
testsuite/smoke-test/src/txn_emitter.rs

I believe there is some issue with the previous version of code. The nft is distributed from receiver side to the sender side. I don't know how this can be successful. Talk to Zekun, it seems currently all txns not aborted will be regarded as successful...
Fix the issue and add transfer logic to transfer all the NFTs to another account if the current account has NFTs, otherwise mint it from a faucet account(creator account)
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4349)

[txn-emitter] fix mint and add transfer traffic

---

storage/backup/backup-cli/src/storage/local_fs/mod.rs

it's an overlook that LocalFs::save_metadata_line() didn't shutdown the file handle, resulting in chance that the written file not immediately visible on the FS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4681)

[backup] fix flaky test_save_list_metadata_files

---

Cargo.lock
api/Cargo.toml
api/types/Cargo.toml
aptos-move/aptos-aggregator/Cargo.toml
aptos-move/aptos-gas/Cargo.toml
aptos-move/aptos-module-verifier/Cargo.toml
aptos-move/aptos-sdk-builder/Cargo.toml
aptos-move/aptos-vm/Cargo.toml
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/counters.rs
aptos-move/aptos-vm/src/move_vm_ext/vm.rs
aptos-move/framework/Cargo.toml
aptos-move/framework/cached-packages/Cargo.toml
aptos-move/gas-algebra-ext/Cargo.toml
aptos-move/move-deps/Cargo.toml
aptos-move/package-builder/Cargo.toml
aptos-move/vm-genesis/Cargo.toml
aptos-node/src/lib.rs
config/src/config/execution_config.rs
crates/aptos-rest-client/Cargo.toml
ecosystem/sf-indexer/firehose-stream/Cargo.toml
execution/executor/Cargo.toml
storage/aptosdb/Cargo.toml
storage/indexer/Cargo.toml
storage/storage-interface/Cargo.toml
types/Cargo.toml

Update the Move commit hash to enable runtime type checks in MoveVM. This is another defense measure against possible type confusions in the move bytecode verifier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4547)

[move] Enable runtime checks in MoveVM

---

docker/docker-bake-rust-all.sh
docker/rust-all.Dockerfile

There were numerous problems found with the base image we were using. Upgrading changes the number of found issues from 127 to <TBA>. See here for the vulnerabilities: https://aptos-org.slack.com/archives/C03EP0XM99D/p1663630803709199.
We have yet to evaluate whether this is more beneficial than risky.
Build images:
```
docker buildx create --use
docker/docker-bake-rust-all.sh
```
Scan validator image:
```
docker scan validator
```
Confirm the validator runs (from the tools image):
```
docker run tools aptos -- node run-local-testnet --with-faucet --faucet-port 8081 --force-restart --assume-yes
```
For now beyond that, I'll run the CI to build the images and run forge. **Update**: I haven't been able to actually do the above because the build just fails locally for one reason or another. …

Update to `debian:bullseye-20220912` in our Rust images Dockerfile

---

aptos-move/move-examples/split_transfer/Move.toml
aptos-move/move-examples/split_transfer/sources/split_transfer.move
crates/aptos/src/move_tool/mod.rs

An example for splitting and using type args
https://explorer.aptoslabs.com/txn/0x70a3380369c1c7e341faef036bb6f969b4bf4392fc5b16db62cbd24364e08da8
```
aptos move run-script --script-path aptos-move/move-examples/split_transfer/sources/split_transfer.move --type-args 0x1::aptos_coin::AptosCoin --args address:677c3d5724fdf179c86ae705614a404df978c9c6a8ca7735a995da4f2c83c73d address:3bec5a529b023449dfc86e9a6b5b51bf75cec4a62bf21c15bbbef08a75f7038f u64:10  --profile greg
Do you want to submit a transaction for a range of [30900 - 46300] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
"Result": {
"transaction_hash": "0x70a3380369c1c7e341faef036bb6f969b4bf4392fc5b16db62cbd24364e08da8",
"gas_used": 317,
"sender": …
```

[cli] Add typeargs for script support and move example

---

crates/aptos/src/move_tool/mod.rs
crates/aptos/src/test/tests.rs

Support passing `"string:https://aptoslabs.com"` as args
Added test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4706)

[CLI] Allow args to contain colons

---

dashboards/overview.json
dashboards/shared-monitoring.json
dashboards/validator-connectivity.json
terraform/helm/monitoring/files/prometheus.yml

these metrics are getting double scraped now that this has landed https://github.com/aptos-labs/aptos-core/commit/413dc2e3b09f2393b2966645d0f7c1c2f759cd21
* remove the `aptos-procs` job since it's now double scraping the same endpoints with the annotation
* also update some of the dashboards that use `aptos-procs` as the job name explicitly
TODO: vmagent scrape config needs to update as well
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4495)

[prometheus] remove aptos-procs job for k8s pod discovery

---

ecosystem/typescript/sdk/src/aptos_client.test.ts
ecosystem/typescript/sdk/src/coin_client.test.ts
ecosystem/typescript/sdk/src/faucet_client.test.ts
ecosystem/typescript/sdk/src/faucet_client.ts
ecosystem/typescript/sdk/src/token_client.test.ts
ecosystem/typescript/sdk/src/utils/test_helper.test.ts

The tap (new faucet) has the ability to let clients set an auth token which will let them bypass ratelimits. This PR adds support for enabling this via an env var in the SDK tests. This will be helpful for CI/CD.
I'll update `ecosystem/typescript/sdk/examples` to use this after we land a package with this in it.
Run a local testnet like this:
```
```
Run tap locally like this:
```
curl https://gist.github.com/banool/94ef72c03cf1ed79d06fa99799cd5e04 > /tmp/config.yaml
cargo run -- run -c /tmp/config.yaml
```
To switch between each faucet, change env:
```
APTOS_NODE_URL="http://127.0.0.1:8080/v1"
APTOS_FAUCET_URL="http://127.0.0.1:10212"
FAUCET_AUTH_TOKEN="abc123"
```
I ran `yarn test` for all of these …

[TS][SDK] Add ability to build FaucetClient with auth token

---

.github/workflows/run-forge.yaml
terraform/fullnode/aws/fullnode/values.yaml
terraform/helm/monitoring/values.yaml

we're not longer collecting metrics via pushgateway, but rather prefer to parse them out of humio log events. the new python wrapper does not even use these env vars, so clean them up
also upgrade grafana to 9.0.9
upgrade grafana in my cluster
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4707)

[gha] remove external pushgateway reference

---

types/Cargo.toml

`aptos-types` depends on `itertools` with all default features disabled. `itertools::IterTools::collect_vec` is only available with feature "use_alloc" so `aptos-types` is now failing to build in standalone mode. This is a preexisting issue but it wasn't exposed in the past due to feature unification. This PR fixes the broken build by enabling the default features
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4684)

[types] fix feature flags for itertools

---

crates/aptos-compression/src/lib.rs

The compression limit needs to be checked before compression, not after - this is to ensure that on the receiver side, the receiver can successfully decompress a valid compressed message from the sender. 
Existing UTs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4708)

[Compression] Enforce size limit before compression

---

.github/workflows/check-sdk-examples.yaml
.github/workflows/sdk-release.yaml

This PR makes it that our tests / examples won't get ratelimited, leveraging the new auth token based ratelimit / check bypassing added to the tap.
Note: This won't do anything yet for the examples, they'll need to be upgraded to use a newer, yet unreleased version of the aptos package.
See that CI works, it should test this change following @perryjrandall's changes to use pull_request for changes to `.github`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4716)

Add auth token to TS tests / examples to bypass devnet tap ratelimits

---

config/src/config/indexer_config.rs
config/src/config/mod.rs
crates/indexer/migrations/2022-10-02-011015_add_table_handle_to_collection/down.sql
crates/indexer/migrations/2022-10-02-011015_add_table_handle_to_collection/up.sql
crates/indexer/src/indexer/tailer.rs
crates/indexer/src/models/token_models/collection_datas.rs
crates/indexer/src/models/token_models/tokens.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/runtime.rs
crates/indexer/src/schema.rs

**Problem**
We currently panic when the collection resource is not present in the transaction but collection data is modified. 
https://fullnode.testnet.aptoslabs.com/v1/transactions/by_version/142269725 is an example of a transaction where this can happen. Basically a token is burned, the token data is also burned which reduces collection supply by 1, but the collection resource isn't there. 
**What this PR does**
In such an event we need to get the owner of the collection somehow. The quickest way (not necessarily the most scalable or efficient way though) to do this is via querying the db. This PR adds table handle as an indexed column in current_collection_datas table which keeps track of the latest collection state. 
Backfilling error. Fix works. 
- - - …

[Indexer] Fix token indexing failure when collection table handle is missing

---

aptos-move/framework/aptos-framework/Move.toml
aptos-move/framework/aptos-framework/sources/account.move
aptos-move/framework/aptos-framework/sources/event.move
aptos-move/framework/aptos-framework/sources/event.spec.move
aptos-move/framework/aptos-framework/sources/guid.move
storage/storage-interface/Cargo.toml

1. `create_account` must check **none** of our reserved system addresses are being created, including `@aptos_token` (`@core_resources` is actually created via `create_account` so it is excluded.)
2. `aptos_std::guid` was previously moved into `aptos_framework/` but not renamed to `aptos_framework::guid`; things only worked because `aptos_framework` and `aptos_std` have the same address.
3. `aptos_std::event` suffered the same treatment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4725)

[move] small aptos_framework fixes

---

crates/aptos-rosetta-cli/src/construction.rs
crates/aptos/src/account/fund.rs
crates/aptos/src/account/key_rotation.rs
crates/aptos/src/account/list.rs
crates/aptos/src/common/init.rs
crates/aptos/src/common/types.rs
crates/aptos/src/move_tool/mod.rs
crates/aptos/src/node/mod.rs

As brought up by @sirouk, profiles don't error out when they don't exist.  Well now they do!
```
$ aptos account list --profile b
{
"Error": "Invalid arguments: Profile b not found"
}
$ aptos account list --profile default
{
"Error": "API error: API error Error(AccountNotFound): Account not found by Address(0xfdf0c99777dd2821101c0b1c26a140c8fcfd63f99a371c4103397ed27791e65d) and Ledger version(4341899)"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4750)

[cli] Error out if a profile is not found

---

developer-docs-site/docs/concepts/base-gas.md

Addressing formatting issue reported in:
https://github.com/aptos-labs/aptos-core/pull/4720#issuecomment-1266109214
Manual viewing in GitHub markdown.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4736)

Replace escaped vertical line with Unicode

---

crates/aptos-faucet/src/lib.rs
crates/aptos-faucet/src/mint.rs

we could get hammered rather hard. the queue isn't kept in order, it is arbitrary based upon how tokio schedules the works after a sleep. this may result in slightly less throughput fro instanteous tests, but it should result in a better experience.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4756)

[faucet] track the ordering of transactions more effectively

---

terraform/aptos-node/gcp/cluster.tf
terraform/fullnode/aws/kubernetes.tf
terraform/fullnode/aws/variables.tf
terraform/fullnode/digital_ocean/kubernetes.tf
terraform/fullnode/digital_ocean/variables.tf
terraform/fullnode/gcp/kubernetes.tf
terraform/fullnode/gcp/variables.tf
terraform/fullnode/vultr/kubernetes.tf
terraform/fullnode/vultr/variables.tf

* Fix the validator node tainting for GCP -- which fixes scheduling errors and guarantees that only validators and critical pods are scheduled on `validator` nodegroup. NOTE: this re-creates the entire nodegroup, so operators applying this change will see some downtime. It's possible that their nodes are not working without this change anyways, so it should be fine
* Make `chain_name` configurable at the TF level. This makes it easier for node oeprators to know which chain they're pointed to, and make one place to override the config. Instead of doing:
```
module "fullnode" {
...
fullnode_helm_values = {
chain = {
name = "mainnet"              # replace with `ait3` or other values if connecting to different networks.
}
}
```
we can do now
```
module "fullnode" {
...
chain_name = "mainnet" …
```

[tf/helm] deployment fixes for mainnet

---

aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/aptos-vm/src/transaction_metadata.rs
aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-move-tests/src/tests/governance_updates.rs
aptos-move/e2e-move-tests/src/tests/mod.rs
aptos-move/e2e-tests/src/executor.rs

* Limit the size of non-approved data to the maximum transaction size (64K)
* Limit the maximum governance transaction to 1MB
* Write a lot of tests to validate this
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4751)

[aptos-vm] further restrictions on governance transaction sizes

---

consensus/consensus-types/src/common.rs
consensus/src/txn_notifier.rs
mempool/src/core_mempool/mempool.rs
mempool/src/core_mempool/transaction_store.rs
mempool/src/shared_mempool/coordinator.rs
mempool/src/shared_mempool/tasks.rs
mempool/src/shared_mempool/types.rs
mempool/src/tests/core_mempool_test.rs
mempool/src/tests/mocks.rs
mempool/src/tests/shared_mempool_test.rs
mempool/src/tests/test_framework.rs

Avoid errantly removing transactions by checking hash when processing rejected transactions.
Add unit tests for the new behavior. In particular `test_reject_transaction` checks bad rejected transactions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4694)

[mempool] check hash for rejected transactions

---

crates/aptos-telemetry/src/constants.rs
crates/aptos-telemetry/src/service.rs

We will have a separate high availability instance of telemetry service and Victoria metrics backend for mainnet chain. This PR hardcodes the mainnet URL to telemetry crate and configures its use when node starts with mainnet chainID.
__Alternatives Considered:__
Alternatively, we could have a redirect from telemetry.aptoslabs.com to telemetry.mainnet.aptoslabs.com if chain ID is mainnet ID. This will not require any node code changes but only telemetry service changes. However, this would defeat the purpose of separating the telemetry service and make the mainnet dependent of telemetry.aptoslabs.com.
Ensured that requests hit mainnet URL if Chain ID is 1.
- - - …

[telemetry] configure mainnet telemetry service URL

---

api/src/tests/transactions_test.rs
config/src/config/mempool_config.rs
mempool/src/core_mempool/index.rs
mempool/src/core_mempool/mempool.rs
mempool/src/core_mempool/transaction_store.rs
mempool/src/counters.rs
mempool/src/logging.rs
mempool/src/shared_mempool/network.rs
mempool/src/shared_mempool/tasks.rs
mempool/src/shared_mempool/types.rs
mempool/src/tests/common.rs
mempool/src/tests/core_mempool_test.rs
mempool/src/tests/mocks.rs
mempool/src/tests/shared_mempool_test.rs
mempool/src/tests/test_framework.rs

Instead of a single timeline for broadcast, divide the timeline into buckets of ranking_score (gas) ranges. This allows gas prioritization even when broadcast is saturated.
Add unit tests. Confirm high pri transactions run well in "graceful overload" test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4728)

[mempool] bucketed broadcast

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/node/mod.rs
types/src/account_config/events/new_block.rs

Everyone keeps asking, when is the next epoch?  Well now you know an estimated time for the next epoch based on the previous epoch.  Also, prints out in UTC to make the readability easier.
Manual test
```
aptos node show-epoch-info --url https://fullnode.testnet.aptoslabs.com
{
"Result": {
"epoch": 550,
"epoch_interval": 3600000000,
"last_reconfiguration_time": {
"unix_time": 1664928771964315,
"utc_time": "2022-10-05T00:12:51.964315Z"
},
"estimated_next_reconfiguration_time": {
"unix_time": 1664932371964315,
"utc_time": "2022-10-05T01:12:51.964315Z"
}
}
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4785)

[cli] Add ability to see current epoch and the next epoch time

---

crates/aptos/src/stake/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4786)

[CLI] Add support for vesting contract

---

aptos-move/aptos-gas/src/gas_meter.rs
aptos-move/e2e-move-tests/src/tests/memory_quota.data/table_and_vec/Move.toml
aptos-move/e2e-move-tests/src/tests/memory_quota.data/table_and_vec/sources/test.move
aptos-move/e2e-move-tests/src/tests/memory_quota.rs

Right now we do not have a way to keep track of memory usage within the table extension. This adds a temporary workaround so that all values enter the table extension are considered "leaked" -- their heap memory will not be considered released. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4803)

[gas] do not release memory for table natives

---

aptos-node/src/lib.rs

__Issue:__ In premainnet, nodes stopped sending telemetry after a restart. Turns out, we don't start the telemetry service until after state sync has caught up (which is a blocking call), which under high loads can take a very long time. 
__Fix:__ Start the telemetry runtime very early in `setup_environment` step, so we can start seeing metrics early on.
Ran a local node and made sure we still are able to send telemetry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4806)

[telemetry][bugfix] start node telemetry service before blocking calls

---

aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-move-tests/src/tests/code_publishing.rs
aptos-move/vm-genesis/src/lib.rs

moving forward, whenever someone adds a new feature, they should enable it in genesis much like this, otherwise we will never validate the features until we deploy on a live network .... :scared:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4821)

[framework] enable all outstanding feature flags in genesis

---

developer-docs-site/docs/nodes/node-files.md
developer-docs-site/sidebars.js

A new doc listing all the downloadable files, like yaml, genesis and waypoint. Needed for either a validator node or a validator/public fullnode, so keeping it at a higher level. **Merge only when we finalize the haproxy files.** as per this [Slack thread.](https://aptos-org.slack.com/archives/C042WTC9S3A/p1665013166144089)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4812)

[Docs] New file listing all the downloadable files during installation

---

developer-docs-site/docs/nodes/validator-node/operator/connect-to-aptos-network.md
developer-docs-site/docs/nodes/validator-node/operator/staking-pool-operations.md
developer-docs-site/sidebars.js

@wintertoro Added the info you requested. Also added a note that they need the latest CLI version. However, we need to clarify the following:
- By `get-performance` in the [Linear issue](https://linear.app/aptoslabs/issue/DOC-68/add-commands-for-node-operators-for-mainnet) you mean `analyze-validator-performance`, I think. There is no CLI sub-command like `get-performance` in 0.3.8.
- The `request-commision` (Linear issue description) isn't available. Is it being added soon? 
- We do not document rotating keys yet. We must. @movekevin, do you have an example command? 
- Add anything else you need before we land this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-co …

[Docs] Adding a few more commands for stake pool and validator info.

---

.github/workflows/copy-images-to-dockerhub.yaml
docker/release-images.sh

This moves some of the logic for releasing docker images into a seperate bash script instead of fully relying on github actions. This makes it easier to make emergency releases of images when github actions is broken.
Also removed publishing to `aptoslab` legacy docker hub organization.
Executed script locally with `release_testing` as image tag. Observed images in docker hub: https://hub.docker.com/layers/aptoslabs/validator/release_testing_377b6697d44c3f2c9b3e23424c6840581506ff71/images/sha256-645cec292b649611211b77462a34d034872cbeb425f6554c47409f51d667c7cc?context=explore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4855)

cicd: create release-images.sh script which can be run from local and use it in CICD

---

ecosystem/typescript/sdk/src/aptos_client.test.ts
ecosystem/typescript/sdk/src/aptos_client.ts
ecosystem/typescript/sdk/src/aptos_types/ed25519.ts
ecosystem/typescript/sdk/src/faucet_client.test.ts
ecosystem/typescript/sdk/src/utils/test_helper.test.ts

The current simulation interface requires an `AptosAccount` as an arg. This means SDK users need to possess the private key. This PR relaxes the rule by allowing users to pass in a public key. It would be nice if the argument can be an `address`. However, this is not possible since an address itself cannot be used to create a valid authenticator.
yarn test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4842)

feat: allow txn simulation without private key

---

crates/aptos/src/common/types.rs
crates/aptos/src/op/key.rs

Add bls key generation to the CLI
```
$ aptos key generate --key-type bls12381 --output-file bls-key
"bls-key" already exists, are you sure you want to overwrite it? [yes/no] >
yes
"bls-key.pub" already exists, are you sure you want to overwrite it? [yes/no] >
yes
{
"Result": {
"PrivateKey Path": "bls-key",
"PublicKey Path": "bls-key.pub",
"Proof of possession Path": "bls-key.pop"
}
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4873)

[cli] Add BLS key generation

---

aptos-move/framework/cached-packages/build.rs
aptos-move/framework/src/aptos.rs
aptos-move/framework/src/main.rs
aptos-move/framework/src/release_builder.rs

Additionally, add the ability to put in the multiple paths for package paths in the custom release
```
$ cargo run --release -- release; ls -lah head.mrb
Including package `MoveStdlib` size 21k
Including package `AptosStdlib` size 67k
Including package `AptosFramework` size 195k
Including package `AptosToken` size 34k
Including package `AptosNames` size 30k
-rw-r--r--  1 greg  wheel   341K Oct  6 12:23 head.mrb
$ cargo run --release -- release --without-source-code; ls -lah head.mrb
Including package `MoveStdlib` size 8k
Including package `AptosStdlib` size 22k
Including package `AptosFramework` size 83k
Including package `AptosToken` size 17k
Including package `AptosNames` size 15k
-rw-r--r--  1 greg  wheel   144K Oct  6 12:23 head.mrb
```
- - - …

[move-release] Add ability to strip source from release bundle

---

crates/aptos/src/move_tool/mod.rs
crates/aptos/src/move_tool/stored_package.rs

This was a requested feature by some users.
This does a byte code verification against local source.  The local source is packaged in the same way it was uploaded and verified that every piece is the same as is on-chain.  This ensures that you know that what is on chain is what you're using locally (if you have a local version or maybe a github repo).
Manual testing, will need to add automated testing around this
```
aptos move verify-package --account 0x1 --package-dir aptos-move/framework/aptos-framework --profile local
{
"Result": "Successfully verified source of package"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4791)

[cli] Add package source code verifier

---

storage/backup/backup-cli/src/coordinators/replay_verify.rs

calling with start-version 1 resulted in the genesis snapshot being recovered and then the txn backup starting at ver 1 directly being applied on top, which is bad because the DB thought its empty due to lack of TxnInfo at ver 0. This fixes that.
```bash
$ rm -rf db && ./replay-verify  --concurrent-downloads 16  --metadata-cache-dir ./mc --target-db-dir db --start-version 1 command-adapter --config s3-pfn.yaml
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4854)

fix replay-verify

---

.github/workflows/cli-release.yaml
scripts/cli/build_cli_release.sh

Right now the builds conflict, which causes the 22.04 one to overwrite the 20.04 build
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4888)

[cli-build] Rename 22.04 build to Ubuntu22.04

---

docker/compose/aptos-node/fullnode.yaml

Cherry-pick from main:
These configs are applied in terraform (https://github.com/aptos-labs/aptos-core/blob/main/terraform/helm/aptos-node/values.yaml#L127) for 1+ months, but not outside of terraform.
Tested docker-compose up (via @rustielin )
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4895)

[mempool] add VFN-specific configs (cherry-pick #4890)

---

Cargo.lock
api/src/transactions.rs

Right now simulation with too little gas will put your max gas amount below the min gas units, which will cause it to error with MAX_GAS_UNITS_BELOW_MIN_TRANSACTION_GAS_UNITS.  Now this fixes, it to INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE which makes more sense if you don't have enough money
Before
```
$ aptos account transfer --account 0x22 --amount 100 --profile local
{
"Error": "Simulation failed with status: Transaction Executed and Committed with Error MAX_GAS_UNITS_BELOW_MIN_TRANSACTION_GAS_UNITS"
}
```
After
```
$ aptos account transfer --account 0x22 --amount 100 --profile local  
{
"Error": "Simulation failed with status: Transaction Executed and Committed with Error INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE"
}
```
- - - …

[api] Fix estimation error for too little funds

---

developer-docs-site/docs/concepts/base-gas.md

@davidiw
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4901)

Correct internal/external gas mismatch for max gas

---

developer-docs-site/docs/guides/sign-a-transaction.md

Fixed a typo in a code snippet from `Unint8Array` to `Uint8Array`.
Fixed a typo in the code snippet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4909)

fix: Typo in snippet

---

developer-docs-site/docs/nodes/aptos-deployments.md
developer-docs-site/docs/nodes/leaderboard-metrics.md
developer-docs-site/docs/nodes/validator-node/operator/node-requirements.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-aws.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-azure.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-docker.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-gcp.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-source-code.md

This PR makes the following changes:
@sherry-x: 
- Removes test mode section from node requirements doc.
- Generalizes all validator deploy instructions to mainnet.
- Makes explicit that the use should run the validator deploy instructions twice, one for validator node on one machine and second time on another machine for the validator fullnode.
- Removes version number for CLI mentions.
- Links to the new Nodes List doc in steps to download files.
-  Added epoch row to the deployments table.
- General clean up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4905)

Update node requirements doc and generalize validator docs.

---

aptos-move/framework/aptos-stdlib/sources/table_with_length.move

@davidiw test-only, mimics same functionality from `table.move`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4844)

Add test-only drop table with length func, test

---

ecosystem/python/sdk/Makefile
ecosystem/python/sdk/aptos_sdk/transactions.py
ecosystem/python/sdk/examples/common.py
ecosystem/python/sdk/examples/transfer-two-by-two.py
ecosystem/python/sdk/examples/your-coin.py

This pr is for issue https://github.com/aptos-labs/aptos-core/issues/4859
`Make fmt` will scan .venv in default. We just need to specify `aptos_sdk/` and `examples/` folder.
And in this pr, some files are formated after running `make fmt`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4858)

make fmt for examples and aptos_sdk folders

---

developer-docs-site/docs/concepts/staking.md
developer-docs-site/docs/issues-and-workarounds.md
developer-docs-site/docs/nodes/validator-node/operator/connect-to-aptos-network.md
developer-docs-site/docs/nodes/validator-node/operator/shutting-down-nodes.md
developer-docs-site/docs/nodes/validator-node/operator/staking-pool-operations.md
developer-docs-site/docs/nodes/validator-node/owner/index.md
developer-docs-site/docs/nodes/validator-node/voter/index.md

A bunch of updates to the staking operations doc, including Slack thread discussion extracts, insights and gotchas. Updated the related docs also. 
@sherry-x this below especially needs your attention:
- I generalized the Connecting to the network section with "mainnet" as default. Hence I removed steps that ask the user to pull the main branch at specific commit hash, and specific Docker image ID. Wouldn't these be default default on the main branch for mainnet? I did retain the instruction to change the chain ID and set it to 1. 
- Other changes are not invasive like the above. If these changes are okay, then we should land this asap.
- **Question**: I need to move the **Add monitoring components** from Shutting Down section. I think this belongs in the validator installation section. …

Revised staking operations doc

---

aptos-move/e2e-tests/src/executor.rs

The parallel executor uses busy loops for its workers, so we need to limit the concurrency level in tests or otherwise they would run for a really long time.
Update: it looks like we're saving about 7 minutes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4920)

[e2e tests] limit concurrency level for faster execution

---

crates/aptos/src/governance/mod.rs
crates/aptos/src/node/mod.rs
crates/aptos/src/test/mod.rs
testsuite/smoke-test/src/aptos_cli/validator.rs

Current aptos node get-stake-pool errors out if consensus key or network/fullnode addresses are empty,
Manual tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4885)

[CLI] Handle empty consensus key and addresses

---

developer-docs-site/docs/sdks/index.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4924)

Fix link to TypeScript index from SDKs index

---

aptos-move/framework/aptos-framework/sources/aptos_governance.move
aptos-move/framework/aptos-framework/sources/block.move
aptos-move/framework/aptos-framework/sources/coin.move
aptos-move/framework/aptos-framework/sources/reconfiguration.move
aptos-move/framework/aptos-framework/sources/stake.move
aptos-move/framework/aptos-framework/sources/staking_contract.move
aptos-move/framework/aptos-framework/sources/vesting.move
aptos-move/framework/aptos-framework/sources/voting.move
aptos-move/framework/aptos-names/sources/domains.move
aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move
aptos-move/move-examples/message_board/sources/acl_message_board.move
aptos-move/move-examples/message_board/sources/cap_message_board.move

@alinush proposed that bc we moved events from `aptos_std` to `aptos_framework`, it makes sense to rename all these imports
existing unit tests, e2e tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4929)

[aptos-move] renamed all `aptos_std::event` to `aptos_framework::event`

---

.github/workflows/lint-test.yaml
aptos-node/src/main.rs
docker/build-rust-all.sh
testsuite/forge/src/backend/local/cargo.rs

Ensure that the aptos-node binary is never run with these feature flags. Panic if it is.
If the node has the feature, then it will fail to start. Run all tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4935)

[aptos-node] assert no Move test natives

---

aptos-move/aptos-gas/src/transaction.rs

the only real reason for a ceiling is to prevent integer overflow, this gives us the room for a 900x multiplier either in max gas or bumping the max gas units
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4963)

[gas] bump max gas unit price

---

docker/compose/aptos-node/fullnode.yaml

The mempool config for VFNs in docker compose are now the same as helm.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4959)

[mempool] default_failovers 0 everywhere

---

.github/README.md
.github/actions/docker-buildx-setup/action.yaml
.github/actions/gar-auth/action.yaml
.github/actions/rust-setup/action.yaml
.github/workflows/check-minimum-revision.yaml
.github/workflows/check-sdk-examples.yaml
.github/workflows/cli-release.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/continuous-e2e-network-latency-test.yaml
.github/workflows/continuous-e2e-release-test.yaml
.github/workflows/copy-images-to-dockerhub.yaml
.github/workflows/coverage.yaml
.github/workflows/docker-build-test.yaml
.github/workflows/docker-rust-build.yaml
.github/workflows/find-packages-with-undeclared-feature-dependencies.yaml
.github/workflows/forge-continuous.yaml
.github/workflows/grafana-sync.yaml
.github/workflows/helm-lint.yaml
.github/workflows/nightly-replay-verify.yaml
.github/workflows/prover-test.yaml
.github/workflows/prune-old-workflow-runs.yaml
.github/workflows/python-unit-test.yaml
.github/workflows/run-forge.yaml
.github/workflows/sdk-release.yaml

This PR pins GH workflows we depend on to specific commits (which in itself cannot be spoofed to have different content with the same hash). We consider nothing to be first party, even stuff from `actions/`, though we could revise that pending discussion.
At first I wrote my own script for this (https://gist.github.com/banool/2f19d6a9b8ab2faec77aae4e596704a9) but then I found something that already exists in the wild, though it does mess with the formatting in ways that I undid manually for now.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4936)

Pin third party GH workflows

---

api/types/src/convert.rs
api/types/src/transaction.rs
crates/aptos-faucet/src/main.rs
crates/indexer/README.md
crates/indexer/migrations/2022-10-07-231825_add_coin_supply/down.sql
crates/indexer/migrations/2022-10-07-231825_add_coin_supply/up.sql
crates/indexer/src/indexer/fetcher.rs
crates/indexer/src/indexer/tailer.rs
crates/indexer/src/models/coin_models/coin_activities.rs
crates/indexer/src/models/coin_models/coin_infos.rs
crates/indexer/src/models/coin_models/coin_supply.rs
crates/indexer/src/models/coin_models/coin_utils.rs
crates/indexer/src/models/coin_models/mod.rs
crates/indexer/src/models/token_models/token_datas.rs
crates/indexer/src/models/transactions.rs
crates/indexer/src/models/user_transactions.rs
crates/indexer/src/processors/coin_processor.rs
crates/indexer/src/processors/default_processor.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/runtime.rs
crates/indexer/src/schema.rs

Track coin supply in indexer. To enable, we need to first process CoinInfo which contains the aggregator key and handle. 
Ran locally against devnet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4907)

[Indexer] Add aptos coin supply

---

ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/yarn.lock

@noble/hashes 1.1.3 has a few minor issues fixed. Users reported that a compiling issue with Vite was fixed in 1.1.3. 
yarn test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4711)

chore: bump up @noble/hashes version

---

developer-docs-site/docs/guides/data-pruning.md
developer-docs-site/docs/guides/state-sync.md
state-sync/README.md

This PR offers two improvements to the data pruning and state sync docs. Each of these is in their own commit:
1. A quick pass over the pruning document to make some of the wording more consistent with the rest of the docs.
2. Added a small section about security implications for state syncing modes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4976)

[Docs] Improvements to pruning and state sync docs.

---

network/netcore/src/transport/tcp.rs
network/src/peer_manager/transport.rs

cherry-pick #4999
This was done within `TcpListener.bind()` before #4649.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5005)

[networking] set_reuseaddr before bind, and a logging improvement

---

aptos-move/framework/cached-packages/build.rs

Was missed in #4943.
It was slowing down builds and in particular smoke tests.
CICD, also verified locally that a rebuild is much faster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5025)

[cached packages] remove non-existant aptos-names

---

Cargo.lock
api/Cargo.toml
api/types/Cargo.toml
aptos-move/aptos-aggregator/Cargo.toml
aptos-move/aptos-gas/Cargo.toml
aptos-move/aptos-module-verifier/Cargo.toml
aptos-move/aptos-sdk-builder/Cargo.toml
aptos-move/aptos-vm/Cargo.toml
aptos-move/framework/Cargo.toml
aptos-move/framework/cached-packages/Cargo.toml
aptos-move/gas-algebra-ext/Cargo.toml
aptos-move/move-deps/Cargo.toml
aptos-move/package-builder/Cargo.toml
aptos-move/vm-genesis/Cargo.toml
crates/aptos-rest-client/Cargo.toml
ecosystem/sf-indexer/firehose-stream/Cargo.toml
execution/executor/Cargo.toml
storage/aptosdb/Cargo.toml
storage/indexer/Cargo.toml
storage/storage-interface/Cargo.toml
types/Cargo.toml

This fixes an index shifting bug in bytecode verifier's instantiation loop checker by updating the Move dependencies 
Original fix in the Move repo: https://github.com/move-language/move/pull/573
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5034)

[vm] fix index shifting bug in bytecode verifier's instantiation loop checker

---

sdk/publishing.md

just a small nit - the changed part of `publishing.md` will go from 
to 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5035)

[publishing runbook] typo nit

---

aptos-move/framework/aptos-token/sources/token.move

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4930)

[Token] make transfer function public entry

---

aptos-move/e2e-move-tests/src/tests/rotate_auth_key.rs
aptos-move/framework/aptos-framework/sources/account.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs

this PR has a lot of very minor changes (comments, capitalization, etc. ), but the slightly more noteworthy ones in `account.move` are:  
- red line 296 is redundant - we don't need to generate the current auth key by doing `bcs::to_address` again, since we already did that earlier in the function; 
- red line 308 in `account.move` we had a redundant line `let account_resource = borrow_global_mut<Account>(addr)` - we already have this at the beginning of the file; 
- red line 338 and 373 are redundant - we don't need to check if the signer's address exists; 
existing unit tests & e2e tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4944)

[account][minor fix] nits in key rotation

---

crates/aptos-rest-client/src/faucet.rs
sdk/examples/transfer-coin.rs

Faucet API now requires `content-length`, however, the Rust faucet client is not passing one in. This fixes it.
cargo run --example transfer-coin
=== Addresses ===
Alice: 0x6e10921aa60ac688ee842fbb3ec9bd7dd46225ec1cc35b2d8f5d300bd911e31c
Bob: 0x65ede8aa5acbb9c1bb59bd6427c142cf61897d327c608cb5e5ec78dce15b6b99
=== Initial Balances ===
Alice: 100000000
Bob: 0
=== Intermediate Balances ===
Alice: 99944900
Bob: 1000
=== Final Balances ===
Alice: 99889800
Bob: 2000
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5052)

[Rust SDK] Fix Rust coin transfer example

---

terraform/helm/monitoring/files/prometheus.yml

report `owner` label as the fullnode or validator name, so it's easier to differentiate 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5024)

[prometheus] external_labels owner for fullnode or vaildator name

---

developer-docs-site/sidebars.js

Move Typescript SDK to top of SDKs list in left nav since it's the most complete
Manual link check in local build and deploy preview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5047)

Move Typescript SDK to top of SDKs list

---

crates/aptos/src/common/init.rs
crates/aptos/src/common/types.rs
crates/aptos/src/test/mod.rs

I finally got tired of typing in two URLs every time.  This gives pretyped CLI network names and associated URLs.  Defaults to custom so the current behavior sticks (other than an extra enter)
There's confusion between the faucet and network endpoints.  This just adds prenamed combinations that can be used, while leaving the ability for custom combinations.  Additionally, stops making the init fail if the faucet fails.
```
$ aptos init --profile new
Aptos already initialized for profile new, do you want to overwrite the existing config? [yes/no] >
yes
Configuring for profile new
Choose network from [testnet, devnet, local, custom | defaults to custom]
testnet
Enter your private key as a hex literal (0x...) [Current: Redacted | No input: Generate new key (or keep one if present)]
No key …
```

[aptos-cli] Use named networks

---

Cargo.lock
api/Cargo.toml
api/types/Cargo.toml
aptos-move/aptos-aggregator/Cargo.toml
aptos-move/aptos-gas/Cargo.toml
aptos-move/aptos-module-verifier/Cargo.toml
aptos-move/aptos-sdk-builder/Cargo.toml
aptos-move/aptos-vm/Cargo.toml
aptos-move/framework/Cargo.toml
aptos-move/framework/cached-packages/Cargo.toml
aptos-move/gas-algebra-ext/Cargo.toml
aptos-move/move-deps/Cargo.toml
aptos-move/package-builder/Cargo.toml
aptos-move/vm-genesis/Cargo.toml
crates/aptos-rest-client/Cargo.toml
ecosystem/sf-indexer/firehose-stream/Cargo.toml
execution/executor/Cargo.toml
storage/aptosdb/Cargo.toml
storage/indexer/Cargo.toml
storage/storage-interface/Cargo.toml
types/Cargo.toml

This updates the commit hash from the  `aptos` branch in the Move repo, taking the following PRs:
- [#586 ](https://github.com/move-language/move/pull/586) which fixes a bug in the reference_safety anaylsis (main objective)
- [#571](https://github.com/move-language/move/pull/571), a trivial PR which removes an unnecessary debug assert (side effect but save)
- [#573](https://github.com/move-language/move/pull/573), a trivial PR which fixes a bug in the instantiation loop checker (side effect but save)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5074)

[move] Update commit hash

---

crates/indexer/migrations/2022-08-08-043603_core_tables/up.sql
crates/indexer/migrations/2022-10-15-185912_improve_processor_recovery/down.sql
crates/indexer/migrations/2022-10-15-185912_improve_processor_recovery/up.sql
crates/indexer/src/indexer/tailer.rs
crates/indexer/src/models/ledger_info.rs
crates/indexer/src/models/mod.rs
crates/indexer/src/models/processor_status.rs
crates/indexer/src/models/processor_statuses.rs
crates/indexer/src/runtime.rs
crates/indexer/src/schema.rs

The old processor_statuses table is way too large (since we're saving every version) and restarting takes 10+ minutes. Tracking every version and finding the first gap is overkill anyway since we panic at the first error, so it's sufficient to just save fully completed batches. The other benefit of only saving the latest completed version is that we can use it to inform products (i.e. if it's behind). 
I also improved error handling here and there by removing expects and unwraps. 
Tested locally and in staging environments. 
I'm also running the old processor_statuses table in parallel to make sure that the results are the same. E.g.
**old gap query**
**new query**
There's a 1 version difference b/c the gap formula gets the "next" version. So we just need to add +1 to the new table to get …

[Indexer] Improve processor tracking and error handling

---

storage/aptosdb/src/lib.rs

It used to be paranoid like this, but https://github.com/aptos-labs/aptos-core/commit/8c16409042b102aad343aa873aaeef8c758c86bd started allowing two concurrent commits to be issued at the same time again (although they will be processed one after another because of the lock). Now that get_startup_info is removed by https://github.com/aptos-labs/aptos-core/pull/2606, we can be paranoid again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5068)

[storage] disallow concurrent commit

---

crates/indexer/migrations/2022-08-08-043603_core_tables/up.sql
crates/indexer/migrations/2022-10-15-185912_improve_processor_recovery/down.sql
crates/indexer/migrations/2022-10-15-185912_improve_processor_recovery/up.sql
crates/indexer/src/indexer/tailer.rs
crates/indexer/src/models/ledger_info.rs
crates/indexer/src/models/mod.rs
crates/indexer/src/models/processor_status.rs
crates/indexer/src/models/processor_statuses.rs
crates/indexer/src/models/token_models/collection_datas.rs
crates/indexer/src/models/token_models/token_ownerships.rs
crates/indexer/src/models/token_models/tokens.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/runtime.rs
crates/indexer/src/schema.rs

Currently there's a bug where `token_ownerships` and `current_token_ownerships` are mishandling non 0x3::token::TokenStore objects. (e.g. missing delete event). This PR removes non 0x3 TokenStore tables from token ownership tables. This should be fine b/c products should be filtering on TokenStore anyway (e.g. to get user owned NFTs). 
This PR also fixes a previous issue with table handles. We now get all the table metadata per batch. 
```
/// Note, there's an edge case where this could still break. If the collection is written in the same thread in an earlier transaction, we won't be able to process.
/// TODO: Fast follow with a fix for above problem.
```
Tested locally and deployed against devnet. 
- - - …

[Indexer] Limit token ownership to only tokenstore

---

developer-docs-site/docs/guides/move-guides/upgrading-move-code.md

Typo 3 instead of 2, since arbitrary was removed earlier.
https://github.com/aptos-labs/aptos-core/issues/4994
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5083)

Fix typo move upgrade guide

---

scripts/cli/build_cli_release.ps1
scripts/cli/build_cli_release.sh

The CLI release script was wrongly generating the file names so no releases were being added for non-windows builds.  Additional cleanup as well
Works: See https://github.com/gregnazario/aptos-core/releases/tag/aptos-cli-v0.4.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5081)

[cli] Fix naming of zips on CLI release

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/common/init.rs
crates/aptos/src/common/types.rs
crates/aptos/src/test/mod.rs

Adds devnet as the default network, and cleans up some error messages with the custom
endpoint flow.
Doing nothing, is much easier now, it'll default to devnet and not have you type in all the URLs:
```
apt init --profile awesome-test
Configuring for profile awesome-test
Enter your private key as a hex literal (0x...) [Current: None | No input: Generate new key (or keep one if present)]
No key given, generating key...
Account 24ff19d58561b7ff4430f68798565c99c9fa1d8fa7b1ee194d1bf3f135b4ea57 doesn't exist, creating it and funding it with 100000000 Octas
Account 24ff19d58561b7ff4430f68798565c99c9fa1d8fa7b1ee194d1bf3f135b4ea57 funded successfully
---
Aptos CLI is now set up for …
```

[cli] Add updates to make CLI default to devnet, cleanup messages

---

aptos-move/framework/src/built_package.rs

Fix the output to be the same as the Move CLI, and warn users about downloading dependencies.
https://github.com/aptos-labs/aptos-core/issues/4049
Now it says all the same things as the move compiler does in the Move CLI, but it stderr, so stdout can be reserved for the output.
```
aptos move run-script --script-path aptos-move/move-examples/scripts/minter/sources/minter.move
Compiling, may take a little while to download git dependencies
BUILDING RunScript
{
"Error": "API error: API error Error(ResourceNotFound): Resource not found by Address(0xfdf0c99777dd2821101c0b1c26a140c8fcfd63f99a371c4103397ed27791e65d), Struct tag(0x1::account::Account) and Ledger version(5594617)"
}
```
- - -
This …

[cli] Add compiler output and dependency warning

---

terraform/fullnode/gcp/cluster.tf
terraform/fullnode/gcp/kubernetes.tf
terraform/fullnode/gcp/network.tf
terraform/fullnode/gcp/variables.tf

Option to make the cluster have public nodes + remove the NAT, such that all GKE worker nodes have a different outbound IP address, and also add the option to enable and configure the autoscaler
Apply
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5043)

[tf/gcp][fullnode] customize autoscaler and NAT

---

crates/aptos-telemetry/src/service.rs
crates/aptos/src/common/utils.rs

https://github.com/aptos-labs/aptos-core/issues/5039
```
APTOS_DISABLE_TELEMETRY=true RUST_LOG=debug apt info  
{
"Result": {
"build_branch": "mainnet",
"build_cargo_version": "cargo 1.63.0 (fd9c4297c 2022-07-01)",
"build_commit_hash": "b76f23484df4e370fde053f3833cc2c48c019528",
"build_is_release_build": "false",
"build_os": "macos-aarch64",
"build_pkg_version": "0.4.0",
"build_profile_name": "debug",
"build_rust_channel": "1.63.0-aarch64-apple-darwin",
"build_rust_version": "rustc 1.63.0 (4b91a6ea7 2022-08-08)",
"build_tag": "",
"build_time": "2022-10-12 11:18:31 -07:00",
"build_using_tokio_unstable": "true"
}
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/ …

[cli] Allow disabling telemetry

---

mempool/src/core_mempool/mempool.rs
mempool/src/core_mempool/transaction_store.rs
mempool/src/counters.rs
mempool/src/tests/core_mempool_test.rs

For use in mempool and general health (gas schedule) dashboards.
Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5057)

[mempool] add bucket to latency stats

---

developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md

Command was missing a `\` at the end of the line, plus sometimes need `sudo`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5114)

[docs] Fix node docker docs

---

testsuite/forge/src/backend/local/mod.rs
testsuite/smoke-test/src/full_nodes.rs
testsuite/smoke-test/src/smoke_test_environment.rs

Change test_vfn_failover smoke test to explicitly have default_failovers=0. This matches what we run in the VFNs in prod.
Run the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4953)

[mempool] smoke test to confirm failover on default_failovers=0

---

aptos-move/framework/src/natives/code.rs

A reader could be led to believe that we do not enable compatibility check for stricter than arbitrary upgrades...
note, this is a no-op, but if we enable compatibility checking again in the future, it could be dangerous.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5078)

[framework] improve readability of compat check

---

api/src/tests/state_test.rs
aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/table.exp
aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/table.move
aptos-move/e2e-move-tests/src/tests/gas.rs
aptos-move/framework/aptos-token/sources/token.move
aptos-move/move-examples/mint_nft/sources/minting.move
crates/transaction-emitter-lib/src/transaction_generator/nft_mint_and_transfer.rs
ecosystem/typescript/sdk/src/token_client.test.ts
testsuite/smoke-test/src/indexer.rs

^
p.s. didn't delete any existing functions/tests, just moved the order so that it'll be in the order of maximum, uri, royalty, description, and properties
unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5017)

[token] added functions for mutating token data

---

terraform/aptos-node-testnet/main.tf

This PR disables the logger chart in testnet by default. We let nodes write logs to stdout and then export them to our desired logging platform using vector. 
This change should also stop nodes from trying to write logs via TCP, which has been failing because the logger replicaset was rolled back to 0 few weeks ago.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5132)

[terraform][testnet] disable logger

---

terraform/helm/fullnode/values.yaml
terraform/helm/monitoring/files/alertmanager.yml
terraform/helm/monitoring/files/rules/alerts.yml
terraform/helm/monitoring/values.yaml

update genesis info for mainnet
only alert on consensus alerts if we're a validator
also group by some labels (`instance`, `kubernetes_pod_name`, `role`) so we avoid alert spam -- now we'll get at most one alert per validator/fullnode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5103)

[helm] consensus alerts and mainnet urls

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/common/init.rs

Fix network argument in `aptos init`
```
aptos init --profile testing --network custom
Configuring for profile testing
Configuring for network Custom
Enter your rest endpoint [Current: None | No input: Exit (or keep the existing if present)]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5137)

[cli] Fix network argument in aptos init

---

crates/indexer/src/indexer/fetcher.rs

Temporary fix for unable to json serialize this transaction https://fullnode.testnet.aptoslabs.com/v1/transactions/by_version/286297914
Until we figure out how to properly parse those transactions we should skip them and reindex later. 
Testing on testnet deployment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5143)

[Indexer] Refactor fetcher to be able to skip over bad txns easily

---

developer-docs-site/docs/nodes/validator-node/operator/staking-pool-operations.md

To clear up confusion, we should use profile everywhere, since it handles the URL & the private key
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5175)

[docs] Update to use profiles everywhere in operator docs

---

config/src/config/state_sync_config.rs

This PR makes several small tweaks to the default state sync configs:
1. Update the max message size from 12MB to 16MB. This should cover the worst possible cases.
2. Default to transaction output syncing instead of re-execution.
3. Increase the number of retries for failed requests. This will simply give more breathing room for slow peers before we fetch a new data stream.
Existing test infra.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5182)

[State Sync] Small tweaks to configs.

---

api/src/runtime.rs

This was left over from when the Poem API was running behind a warp reverse proxy. This is no longer the case.
👀 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5185)

[API] Remove erroneous log message about reverse proxy on startup

---

crates/indexer/src/models/block_metadata_transactions.rs
crates/indexer/src/models/coin_models/coin_activities.rs
crates/indexer/src/models/coin_models/coin_balances.rs
crates/indexer/src/models/events.rs
crates/indexer/src/models/move_modules.rs
crates/indexer/src/models/move_resources.rs
crates/indexer/src/models/move_tables.rs
crates/indexer/src/models/signatures.rs
crates/indexer/src/models/token_models/ans_lookup.rs
crates/indexer/src/models/token_models/collection_datas.rs
crates/indexer/src/models/token_models/token_activities.rs
crates/indexer/src/models/token_models/token_claims.rs
crates/indexer/src/models/token_models/token_datas.rs
crates/indexer/src/models/token_models/token_ownerships.rs
crates/indexer/src/models/token_models/tokens.rs
crates/indexer/src/models/user_transactions.rs
crates/indexer/src/models/write_set_changes.rs
crates/indexer/src/util.rs

* If an address or table handle is less than 66 characters long (0x + 64 char hex), add 0 to fill to 64 chars. 
Tested locally, made sure that new address added are 66 characters. Also 
```select * from current_token_ownerships cto where owner_address like '0x0%'```
returns something. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5170)

standardize address and table handle

---

.github/workflows/lint-test.yaml
testsuite/smoke-test/src/aptos/error_report.rs

Previously only kept logs on failure. Now, we will always try to create the artifact, but if there are no failures or flaky tests, the artifact doesn't get created anyway because there are no directories.
Created a flaky test (using rng) on CICD and confirmed artifact created on flaky and not created on flawless runs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5167)

[smoke tests] keep logs even on flaky tests

---

Cargo.lock
Cargo.toml
aptos-move/framework/Cargo.toml
aptos-move/framework/src/built_package.rs
aptos-move/framework/src/lib.rs
aptos-move/framework/src/prover.rs
aptos-move/framework/tests/move_prover_tests.rs
crates/aptos/src/move_tool/mod.rs

This PR creates a new `prover` module (in framework) which lives side-by-side with the `docgen` module and serves as a single point of integration of the prover into the aptos stack. This comes with is own clap-ified set of options which are hand-selected from the many (some obsolete) options the core prover has in the move repo and which are now available via the CLI.
```
USAGE:
aptos move prove [OPTIONS]
OPTIONS:
--check-inconsistency
Whether to check consistency of specs by injecting impossible assertions
--cvc5
Whether to use cvc5 as the smt solver backend. The environment variable `CVC5_EXE`
should point to the binary
--dump
Whether to dump intermediate step results to files
--keep-loops
Whether to keep loops as they are and pass them on to the underlying solver
--loop-unroll …
```

[move-prover] Refactor prover integration

---

terraform/fullnode/aws/backup.tf

if `var.enable_public_backup = true`, then add an additional ACL on the bucket to enable `public-read`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5252)

[tf/aws][fullnode] public-read acl for public backups

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/main.rs

We use jemalloc at main for the node, but not for the CLI. This could lead to inconsistencies between nodes run normally and nodes run through the CLI. This PR makes the CLI use jemalloc like the node does (unix only).
I'm not 100% sure why we didn't do this already. I'm assuming it was just an oversight, but perhaps there was some other reason, e.g. compatibility concerns. We can figure it out in this PR / through CI 😛 
Running the TS SDK tests worked against a local testnet. Beyond that, CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5249)

[CLI] Use jemalloc for the CLI

---

config/src/config/state_sync_config.rs
state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/continuous_syncer.rs
state-sync/state-sync-v2/state-sync-driver/src/utils.rs
state-sync/storage-service/server/src/lib.rs
testsuite/smoke-test/src/state_sync.rs

This PR updates the state sync code with the following tweaks to improve the experience of fullnodes. Each of these is in their own commits:
1. Make the max number of data stream timeouts configurable and increase the value from 3 to 6 to reduce stream termination rates when waiting for data. Each wait is up to 5 seconds, so this change goes from (3x5) 15 seconds to (6x5) 30 seconds before a stream will be terminated.
2. Increase the max RPC response timeout from 10 seconds to 20 seconds to allow nodes with limited network bandwidth to receive larger messages. In addition, reduce the max message size from 16MB to 4MB and update the logic such that if a single item cannot fit inside 4MB, it is still sent.
4. Add simple smoke tests to verify at least 1 item is sent per chunk on overflow. …

[State Sync] Increase request timeouts and reduce max. message sizes.

---

testsuite/smoke-test/src/genesis.rs

This is one of the top flaky tests.
Observed flaky runs fail with `Waiting for nodes to catch up to version 10 timed out after 10s`. While this is probably enough time for state sync, there may be variation in node restart times, so adding the waits.
If things still fail, at least it will be clearer which is at fault.
Will have to observe if the flakes go away.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5262)

[smoke tests] test_genesis_transaction_flow: add wait checks on validator restarts

---

crates/indexer/migrations/2022-10-21-055518_stake_to_voter/down.sql
crates/indexer/migrations/2022-10-21-055518_stake_to_voter/up.sql
crates/indexer/src/indexer/tailer.rs
crates/indexer/src/models/mod.rs
crates/indexer/src/models/stake_models/mod.rs
crates/indexer/src/models/stake_models/stake_utils.rs
crates/indexer/src/models/stake_models/staking_pool_voter.rs
crates/indexer/src/models/token_models/token_utils.rs
crates/indexer/src/processors/coin_processor.rs
crates/indexer/src/processors/default_processor.rs
crates/indexer/src/processors/mod.rs
crates/indexer/src/processors/stake_processor.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/runtime.rs
crates/indexer/src/schema.rs
crates/indexer/src/util.rs

* Fix error where expiration timestamp could be > i64. 
* Revert to original way of restarting from gap (the issue is that other threads might cause indexer to skip over bad transactions completely which isn't good). 
* Also update inserted_at field in all the tables
Note, I would recommend backfilling from `7602762`. 
Tested locally (`cargo run -p aptos-node --features "indexer" --release -- -f ./fullnode.yaml | grep -E _processor`)
Tested on devnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5214)

[Indexer] Fix timestamp bug and restart from gap

---

aptos-move/aptos-vm/src/natives.rs
aptos-move/framework/src/natives/cryptography/ed25519.rs

When feature testing is disabled, the `natives` vector declared as `mut` is never mutated...
Also, we forgot to update `assert_no_test_natives`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5289)

ed25519 test-only natives implementation tweak

---

terraform/helm/aptos-node/templates/haproxy.yaml

For now, in the `aptos-node` helm chart, we only support:
* single validator
* 0 or multiple VFN "groups", each with their own k8s service, but potentially multiple replicas. In practice, this is only up to 1 VFN per group per validator
Since there's usually only up to 1 instance behind each k8s service, k8s probes don't make much sense. Instead, we should rely on the application itself to handle failed connections.
Forge. This unblocks HAProxy forge tests, as previously HAProxy instances without corresponding VFNs would fail livenessProbe.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5306)

[helm][aptos-node] remove haproxy probes

---

terraform/helm/aptos-node/README.md
terraform/helm/aptos-node/values.yaml
terraform/helm/fullnode/README.md
terraform/helm/fullnode/values.yaml

otherwise pod can be killed because of increased use of fs cache
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5310)

[tf] update requested and limit mem to be the same

---

testsuite/forge/src/backend/local/cargo.rs
testsuite/forge/src/backend/local/mod.rs
testsuite/smoke-test/src/lib.rs
testsuite/smoke-test/src/test_smoke_tests.rs
testsuite/smoke-test/src/txn_broadcast.rs
testsuite/smoke-test/src/workspace_builder.rs

With smoke tests running in parallel, some tests failed on node panic after asserting that feature "testing" from crate move-stdlib is set.
```
thread 'main' panicked at 'assertion failed: aptos_natives(NativeGasParameters::zeros(),\n            AbstractValueSizeGasParameters::zeros(),\n            LATEST_GAS_FEATURE_VERSION).into_iter().all(|(_, module_name,\n            func_name, _)|\n        module_name.as_str() != \"unit_test\" &&\n            func_name.as_str() != \"create_signers_for_testing\")', aptos-move/aptos-vm/src/natives.rs:55:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is because other tests that call `get_bin` were recompiling aptos-node without release flags. So there is a race where a node is startup with the non-release …

[smoke tests] fix flaky node panic due to rebuild in parallel tests

---

aptos-node/src/lib.rs

Currently if you pass in an explicit config path but there is no file at the path, or the config is missing, it just silently continues without even a warning. This PR makes it return an error in this case.
```
cargo run --release -p aptos -- node run-local-testnet --force-restart --config-path /tmp/does_not_exist.yaml --assume-yes
```
Output (when this PR is on top of https://github.com/aptos-labs/aptos-core/pull/5261):
```
Node stopped unexpectedly Err(
Error {
context: "Failed to load config at path: \"/tmp/does_not_exist.yaml\"",
source: Unexpected(
"Failed to open config file: \"/tmp/does_not_exist.yaml\". Error: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }",
),
},
)
{
"Error": "Unexpected error: One of the components stopped unexpectedly"
}
```
I checked …

Return error if provided config was missing or invalid

---

Cargo.toml

This PR adds a small comment to the performance profile in Cargo.toml to warn the reader that performance builds are not stable yet.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5284)

[Cargo] Add comment about performance profile.

---

developer-docs-site/docs/nodes/validator-node/operator/node-requirements.md
terraform/aptos-node/gcp/variables.tf
terraform/fullnode/gcp/variables.tf
terraform/modules/eks/variables.tf

Make it consistent with https://aptos.dev/nodes/validator-node/operator/node-requirements/
All VFN, PFN, Validators in the following clouds will run by default:
* GCP: `n2-standard-32` (it's not 30)
* AWS: `c6i.8xlarge` (subject to change)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5312)

[tf/gcp] update default instance to recommended n2

---

aptos-move/aptos-vm/src/natives.rs
aptos-node/src/lib.rs
aptos-node/src/main.rs

This adds a meaningful error message to the feature flag check so users know what to do when they bump into it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5330)

[aptos-node] better error message for the feature flag check

---

aptos-move/framework/aptos-stdlib/doc/math128.md
aptos-move/framework/aptos-stdlib/doc/math64.md
aptos-move/framework/aptos-stdlib/doc/type_info.md
aptos-move/framework/aptos-stdlib/sources/math128.spec.move
aptos-move/framework/aptos-stdlib/sources/math64.move
aptos-move/framework/aptos-stdlib/sources/math64.spec.move
aptos-move/framework/aptos-stdlib/sources/type_info.move
aptos-move/framework/aptos-stdlib/sources/type_info.spec.move
aptos-move/framework/aptos-token/doc/token.md

- Specified the `math64` and `math128` modules
- Updated the spec of `type_info`
- `type_of` and `type_name` are natively supported by Prover now.
- added a `[verify_only]` function to test the feature
TODO:
- the `pow` functions have non trivial loops, which still need abort-conditions and loop invariants.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5341)

[Spec] Specs for math64, math128 and type_info

---

network/src/peer_manager/transport.rs
testsuite/forge/src/backend/local/node.rs
testsuite/smoke-test/src/genesis.rs

Add more debug logging to understand why ports are not released. Smoke test logs all ports (that have been observed with conflicts) and PIDs, which can be compared to lsof output.
Verified lsof output (on MacOS)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5347)

[smoke tests] test_genesis_transaction_flow: some more debugging output

---

aptos-move/framework/aptos-token/sources/token.move

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5096)

[token] fix collection supply underflow

---

crates/aptos/src/move_tool/mod.rs

It just needed to be turned on. However, the existing implementation in the Move repo isn't optimal. For example, it prints stacktrace only on Move abort, but not internal (like division by zero) error.
Tests locally with some of our unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5374)

[move] Print stack trace in unit tests

---

aptos-move/move-examples/defi/Move.toml
aptos-move/move-examples/defi/sources/locked_coins.move

Simple module that can be used to lock up coins until an unlock timestamp
Unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5334)

[Move examples] Add an example for locked coins contract

---

aptos-move/framework/aptos-framework/doc/resource_account.md
aptos-move/framework/aptos-framework/sources/resource_account.move

currently, if a user calls `resource_account::retrieve_resource_account_cap(resource: &signer, source_addr: address)` with a resource address that wasn't created by the `source_account`, it will abort with a `SimpleMap` error of `key_not_found`. It'd be easier for them to debug if we added a new error explicitly letting them know that the resource address does not exist in the source address' container. 
added a unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5378)

[framework] added explicit error code for resource account

---

crates/indexer/src/indexer/fetcher.rs
crates/indexer/src/indexer/tailer.rs
crates/indexer/src/runtime.rs

This makes indexer snappy again, by skipping empty processor threads. The issue before was that we were spawning 10 threads to process transactions but if fetcher channel < 10, then we'd just be stuck waiting.
tested locally w/ 
`cargo run -p aptos-node --features "indexer" --release -- -f ./fullnode_token.yaml | grep -E _processor`
changed to fetch_task = 1 and observed that it was chunky, but after change it's snappy again!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5391)

[Indexer] Make indexer snappy again

---

CODEOWNERS
Cargo.lock
aptos-move/aptos-gas/src/aptos_framework.rs
aptos-move/aptos-gas/src/gas_meter.rs
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/configs/features.move
aptos-move/framework/Cargo.toml
aptos-move/framework/aptos-stdlib/doc/hash.md
aptos-move/framework/aptos-stdlib/sources/hash.move
aptos-move/framework/aptos-stdlib/sources/hash.spec.move
aptos-move/framework/aptos-token/doc/token.md
aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move
aptos-move/framework/src/natives/hash.rs
aptos-move/framework/src/natives/mod.rs

Added support for SHA2-512, SHA3-512 and RIPEMD-160, to support folks write bridge contracts to other platforms, as per conversations with @JoshLind.
This PR should be good to go:
- it is feature-gated
- it has (reasonable) gas costs for the new hash functions, marked with `optional`
- it bumps up the gas feature version
This PR merely exports existing hash function crates, which are either already used throughout `aptos-core/` or are believed to be trustworthy implementations. Therefore, we only made sure the native implementation give the expected hash values for the empty string "" and for `b"testing"`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4181)

[crypto+move] added support for SHA2-512, SHA3-512 and RIPEMD-160 in Move

---

aptos-move/aptos-gas/src/aptos_framework.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/aptos-vm/src/move_vm_ext/vm.rs
aptos-move/aptos-vm/src/natives.rs
aptos-move/e2e-move-tests/src/tests/chain_id.data/pack/Move.toml
aptos-move/e2e-move-tests/src/tests/chain_id.data/pack/sources/chain_id_test.move
aptos-move/e2e-move-tests/src/tests/chain_id.rs
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/configs/features.move
aptos-move/e2e-move-tests/src/tests/mod.rs
aptos-move/e2e-tests/src/executor.rs
aptos-move/framework/aptos-framework/doc/chain_id.md
aptos-move/framework/aptos-framework/doc/resource_account.md
aptos-move/framework/aptos-framework/sources/chain_id.move
aptos-move/framework/aptos-framework/sources/reconfiguration.move
aptos-move/framework/aptos-stdlib/doc/type_info.md
aptos-move/framework/aptos-stdlib/sources/type_info.move
aptos-move/framework/aptos-stdlib/sources/type_info.spec.move
aptos-move/framework/aptos-token/doc/token.md
aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move
aptos-move/framework/src/natives/mod.rs
aptos-move/framework/src/natives/transaction_context.rs
aptos-move/framework/src/natives/type_info.rs
aptos-move/vm-genesis/src/lib.rs
aptos-move/writeset-transaction-generator/src/writeset_builder.rs
types/src/chain_id.rs
types/src/on_chain_config/chain_id.rs
types/src/on_chain_config/mod.rs

This PR exposes the chain ID inside the `aptos_stdlib` package by adding a public `chain_id()` function in the `type_info` module, which calls a native `chain_id_internal()` Rust function (Happy to move it somewhere better too.)
Everything is feature-gated too.
The chain ID is now fetched inside `AptosVMImpl::new` via an `OnChainConfig` implementation for `ChainId`. As a result, most of this PR deals with making sure all calling code correctly passes the chain ID into `AptosVMImpl`.
@davidiw, @movekevin, @wrwg and @vgao1996 your feedback is much appreciated.
One problem of this approach is that `aptos_stdlib::type_info::chain_id()` will return `4u8` inside a testing environment (like a `#[test]` Move function), whereas `aptos_framework::chain_id::get()` will return whatever chain ID was …

[move] add `chain_id()` call in `aptos_stdlib::type_info`

---

.github/actions/rust-setup/action.yaml

Install lsof on rust machines, which is needed for smoke tests for #5347 
Look at checks, confirm that apt-get lsof was successful as part of rust setup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5381)

[github actions] add lsof to rust setup

---

docker/release-images.mjs

This change makes it so that we release the validator/fullnode image with the `indexer` feature flag to dockerhub, which should allow folks to run an indexer fullnode without building from source. This has been requested by the community.
The image released will have tags like these:
`aptoslabs/validator:nightly_indexer`
`aptoslabs/validator:mainnet_indexer`
`aptoslabs/validator:mainnet_indexer_<git_sha>`
cc @clay-aptos Once merged we can update https://aptos.dev/nodes/indexer-fullnode#summary stating that the docker option works.
Run github action job and verify that image shows up in dockerhub
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5389)

cicd: release indexer fullnode image to dockerhub

---

aptos-move/framework/aptos-token/sources/token.move

Tokendata maximum should not be able to be mutated to or from 0.
1 unit test was added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5382)

[token] tokendata maximum should not be changed from or to 0.

---

crates/indexer/README.md
crates/indexer/migrations/2022-10-30-053525_add_vote_data/down.sql
crates/indexer/migrations/2022-10-30-053525_add_vote_data/up.sql
crates/indexer/src/indexer/fetcher.rs
crates/indexer/src/indexer/tailer.rs
crates/indexer/src/models/stake_models/mod.rs
crates/indexer/src/models/stake_models/proposal_votes.rs
crates/indexer/src/models/stake_models/stake_utils.rs
crates/indexer/src/models/token_models/ans_lookup.rs
crates/indexer/src/processors/stake_processor.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/runtime.rs
crates/indexer/src/schema.rs

Recording every version and restarting from gap is inefficient (takes about 30 minutes to restart in testnet). We tried to explore an easy solution where we only record the latest version processed, but the existing way skips ahead even though a batch may fail. 
We now wait for the full X batch to finish processing before logging. The tradeoff is that we may see a performance hit when processing large batches (before, we'd just go ahead, but now, we're stopping). Realistically though this is a non issue because we're wayyyy above our actual TPS. 
I tested by crashing the node, `processor_status` returned `latest_version_processed = 14999` 
```        
if start_version == Some(1000) {
tokio::time::sleep(std::time::Duration::from_millis(500)).await;
panic!("test panic");
}
```
Same crash …

[Indexer] Improve indexer restart

---

.github/actions/rust-setup/action.yaml
.github/workflows/cli-release.yaml

Fixing the CLI build because on Linux they need lld. More context here: https://aptos-org.slack.com/archives/C036X27DZNG/p1667351722975209.
Probably fork and try it there. I'd say we just land this though and if this doesn't work, then I'll go through that whole process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5416)

Install lld in rust-setup action, use in Linux jobs of CLI release workflow

---

consensus/src/epoch_manager.rs
consensus/src/liveness/leader_reputation.rs
consensus/src/liveness/leader_reputation_test.rs
types/src/on_chain_config/consensus_config.rs

Add root hash of the most recent block used for leader reputation
This is change changes the protocol, but this diff makes it backwards compatible:
- if new genesis is created - new protocol is used
- old network uses old protocol, until onchain config is changed via governance to use new protocol
Needs multiple nodes for a proper test, smoke/forge coverage (including compat) should cover this well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4253)

[consensus] Improve seed for leader election

---

aptos-move/e2e-move-tests/src/tests/mint_nft.rs
aptos-move/move-examples/mint_nft/Move.toml
aptos-move/move-examples/mint_nft/sources/minting.move

added the concept of `admin_account` in `mint_nft` module, and assert the caller is the admin signer instead of the resource signer. for details, pls see added / modified comments in the files. 
tested manually with devnet (plus existing unit tests + e2e tests).
devnet explorer links: 
- resource account: https://explorer.aptoslabs.com/account/9a0e3291258d2a3d7698fe850509d37bc8ae29d83b9f9796dea188fe9a7b5cd3
- nft receiver's account:
https://explorer.aptoslabs.com/account/0x5343d6d52df22187ea922ab08668d2f551cdc1d5e9a6490db663a15f0f57400/resources
testing steps:
```
chloe@Chloes-MBP mint_nft % cargo run -p aptos -- move create-resource-account-and-publish-package --seed hex_array:4321 --address-name mint_nft --named-addresses source_addr=default …
```

[move-examples] updated nft tutorial

---

developer-docs-site/docs/concepts/coin-and-token/aptos-token.md

Fix the wrong `token_data_id` type
Before
`token_data_id: TokenId`
After
`token_data_id: TokenDataId`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5426)

[docs] fix wrong `token_data_id` type

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/pnpm-lock.yaml
ecosystem/typescript/sdk/src/aptos_client.ts
ecosystem/typescript/sdk/src/generated/core/request.ts
ecosystem/typescript/sdk/src/utils/index.ts
ecosystem/typescript/sdk/src/utils/pagination_helpers.ts

This PR makes getAccountResources and getAccountModules use pagination, leveraging the support added in https://github.com/aptos-labs/aptos-core/pull/5313. 
I ran the below tests both against a local node built from main and prod devnet, to ensure compatibility with both.
Run the SDK tests:
```
yarn test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5405)

[TS][SDK] Use pagination in getAccountResources and getAccountModules

---

terraform/helm/testnet-addons/templates/loadtest.yaml
terraform/helm/testnet-addons/values.yaml

So we can run load test with more resources as a CronJob. Also be able to adjust the parallelism
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5455)

[helm][testnet-addons] specify resources for load test

---

terraform/helm/testnet-addons/templates/loadtest.yaml
terraform/helm/testnet-addons/values.yaml

partial revert of 9da65d76aed757231cdfb22480abc81678bda1dd, removing parallelism on the k8s job due to invalid spec

[helm][testnet-addons] revert loadtest parallelism

---

developer-docs-site/docs/tutorials/first-dapp.md

first-dapp was not working for aptos^1.3.15
I managed to get it running by changing `Types.MoveModule` into `Types.MoveModuleBytecode`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4825)

error fixed in first-dapp in tutorials

---

ecosystem/typescript/sdk/src/aptos_account.ts
ecosystem/typescript/sdk/src/aptos_types/authentication_key.ts

Delegate auth key generation logic to a single place -- `AuthenticationKey`
yarn test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4843)

refactor: consolidate the code of generating auth key for Aptos account

---

ecosystem/typescript/sdk/src/aptos_types/abi.test.ts
ecosystem/typescript/sdk/src/aptos_types/index.ts

This PR `export` the [aptos_types/abi.ts](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/aptos_types/abi.ts) and adds some `serialize` samples. 
```js
yarn test 
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5431)

[TS][SDK] export aptos abi methods and add some serializer samples

---

Cargo.lock
aptos-move/framework/aptos-token/doc/token.md
crates/indexer/Cargo.toml
crates/indexer/src/models/mod.rs
crates/indexer/src/models/property_map.rs
crates/indexer/src/models/token_models/token_utils.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/util.rs

* Decoding and flatten property map. Instead of 
```
{
"map":{
"data":[
{
"key":"type",
"value":{
"type":"0x1::string::String",
"value":"0x06646f6d61696e"
}
},
....
```
we now have 
```
{
"type": "domain",
...
}
```
* Also some fields can be bcs encoded, adding a bcs decoding deserializer. 
Before
Well this cleaned up nicely :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5427)

[Indexer] decode BCS in some token fields

---

.github/workflows/docker-build-test.yaml
.github/workflows/docker-rust-build.yaml
docker/docker-bake-rust-all.hcl

`validator-testing` image is the `validator` image, but with a bunch of debug tools installed on top of it, which is useful for testing purposes. Use the `BUILD_ADDL_TESTING_IMAGES` env var to trigger building the extra `validator-testing` image for each of our image build workflows
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5482)

[gha] build additional testing images for all profile and features builds

---

config/src/utils.rs

Trying to eliminate an entire class of smoke test flakiness in CICD due to conflicting ports.
Doing lsof on flaky tests in CICD, we observe that a new parallel test takes a port from a currently running node between the time it is stopped and started. When a node N goes down (by design, in the test) a port that was being used by that node N is stolen by a node M in another test. When node N restarts, the conflict occurs.
It seems very hard to hit if things were really random, yet in practice we see this at least once a day. Possibly the OS is prioritizing recently released ephemeral ports. In this PR we use pseudo-randomness, so the chances of a new process taking a port between process stop and restart should be fairly low.
(Note cargo nextest runs parallel tests in different processes, …

[smoke tests] use a random port instead of an OS-assigned port (with bind to 0)

---

.github/workflows/docker-build-test.yaml

Performance images take on average 2x longer to build. Since we're not using them for forge land-blocking tests, remove them from the GHA dependency tree. We could also do this with the `failpoints` image, but keeping that for now as the build time is roughly the same. (We can potentially add some quick safety checks using the failpoints image too to land-blocking)
Also rename the GHA job  `rust-images-testing` to  `rust-images-failpoints` to be more clear. This separates it from the concept of "testing" images
Some GHA data analysis...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5492)

[gha] remove docker build performance dependency

---

terraform/aptos-node-testnet/forge.tf
terraform/aptos-node-testnet/variables.tf
terraform/helm/monitoring/values.yaml
testsuite/fixtures/forge-default-helm-values-after.fixture
testsuite/fixtures/forge-default-helm-values-before.fixture
testsuite/fixtures/forge-default-helm-values-preview.fixture
testsuite/forge.py
testsuite/forge_test.py
testsuite/forge_wrapper_core/filesystem.py
testsuite/forge_wrapper_core/git.py
testsuite/forge_wrapper_core/process.py
testsuite/forge_wrapper_core/shell.py
testsuite/forge_wrapper_core/time.py

Add the `default_helm_values` config, which allows a per-chart override of default helm values. Previously, Forge runs just inherited the helm values from the `aptos-node` and `aptos-genesis` helm releases in the `default` namespace. Moving it to a config makes it easier to tune across all clusters at once.
Bonus:
* start to separate out some of the common core abstractions for testable python CLIs (process, filesystem, git, etc)
* fix metrics scraping for node exporter and kube-state-metrics, which now relies on scrape annotations by default
* grant the `forge` service account access to the config bucket
* format and lint python code
Added new unit tests
- - - …

[forge] refactor and helm values config

---

aptos-move/move-examples/tests/move_unit_tests.rs

run_tests_for_pkg was running tests, however it was not correctly interpreting
the result of run_move_unit_tests, so it was not actually blocking diffs as
intended!
These should probably be consolidated with the way the framework tests are
being run but for now this is an ez win to stop these from breaking.
Test Plan:
Before I ran cargo nextest locally and it passed with breakages
After I ran cargo nextest locally and it failed as intended
cargo nextest run -p move-examples
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5494)

[move-examples] Actually fail tests when test fail

---

docker/rosetta/rosetta.Dockerfile

aptos-cli-v1.0.1 Docker fails to build rosetta
Missing lld
fixed #5477 
```
=> => writing image sha256:10f2aedfa6c53609a42f8746c16377de3120fe115e4cd785f57297a3a85590f1                                                                                                                            0.0s 
=> => naming to docker.io/library/aptos-core:rosetta-aptos-cli-v1.0.1                                                                                                                                                  0.0s
=> => naming to docker.io/library/aptos-core:rosetta-latest 
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5503)

[docker] bug fix Add apt-get install lld

---

.github/workflows/replay-verify-mainnet.yaml
.github/workflows/replay-verify-testnet.yaml

"high-perf-docker" was gone.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5483)

use available machine type for mainnet replay job

---

scripts/grafana-sync.mts

Be able to override what was previously set constant:
* `GRAFANA_URL`
* `GRAFANA_DASHBOARD_FOLDER_NAME_TO_SYNC`
* `LOCAL_DASHBOARD_FOLDER_TO_SYNC`
run grafana-sync
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5166)

[scripts] override env vars for grafana-sync

---

.github/ISSUE_TEMPLATE/config.yml

Encourage contributors to use issue templates by setting `blank_issues_enabled` to false. Note that ppl can still delete the issue template after creating the issue, but this adds an extra step.
Following https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5509)

[gh] disable blank issues without template

---

ecosystem/typescript/sdk/src/aptos_account.test.ts
ecosystem/typescript/sdk/src/aptos_account.ts
ecosystem/typescript/sdk/src/aptos_types/authentication_key.ts

Added a function to get resource account addresses in SDK.
pnpm test -- -t "Gets the resource account address"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5506)

feat: get resource account address out of source address and seed

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/index.ts

Bump SDK version and get rid of `export * as AptosTypes from "./aptos_types";`. We have already exported TxnBuilderTypes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5511)

chore: bump sdk version

---

package.json

This lockfile was out of sync, which was causing grafana-sync jobs to fail: https://github.com/aptos-labs/aptos-core/actions/runs/3397890836/jobs/5650451505
```
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
```
Remove the unneeded `path-to-regex` dep and run `pnpm install --no-frozen-lockfile`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5514)

update pnpm-lock.yaml and remove path-to-regex

---

Cargo.lock
crates/aptos/src/node/analyze/fetch_metadata.rs
crates/aptos/src/test/mod.rs
testsuite/forge/src/interface/aptos.rs
testsuite/smoke-test/Cargo.toml
testsuite/smoke-test/src/aptos_cli/validator.rs

running locally with:
LOCAL_SWARM_NODE_RELEASE=1 cargo test --release --package smoke-test --lib -- aptos_cli::validator::test_onchain_config_change --exact --nocapture
we get:
With new config: 23 rounds from vote to elected: Some(20) to Some(43)
With old config: 61 rounds from vote to elected: Some(12) to Some(73)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4986)

[consensus][e2e] Add e2e smoke test for changing onchain config and voting history fix

---

testsuite/forge.py
testsuite/forge_test.py
testsuite/forge_wrapper_core/process.py

Make the usage of the `failpoints` feature explicit with `FORGE_ENABLE_FAILPOINTS` env var, rather than something generic like `FORGE_ENABLE_TESTING_IMAGE`. The notion of "testing image" is a bit ambiguous since it doesn't say anything about how the underlying aptos binary is built.
Also the change that had renamed failpoints --> testing image did not change the GHA workflows which specified `FORGE_ENABLE_FAILPOINTS: true` anyways, so it wasn't working as intended
For now, if you want to run a Forge test with failpoints, override `enable_failpoints = "true"` in the wrapper's main function
Also fix a bug in python imports..
run from CLI with the env var set to enable failpoints. The subsequent job that spins up uses the latest revision built with failpoints.
```
$ …
```

[forge] make invoking failpoints explicit

---

Cargo.lock
config/Cargo.toml
config/src/utils.rs

This should eliminate an entire class of smoke test flakiness in CICD due to conflicting ports.
Doing lsof on flaky tests in CICD, we observe that a new parallel test takes a port from a currently running node between the time it is stopped and started. When a node N goes down (by design, in the test) a port that was being used by that node N is stolen by a node M in another test. When node N restarts, the conflict occurs. (It seems very hard to hit if things were really random, yet in practice we see this at least once a day. Possibly the OS is prioritizing recently released ephemeral ports.)
cargo nextest runs parallel tests in different processes, so we need to avoid conflicts between processes. This introduces a counter file that keeps track of the last port used and a file for …

[smoke tests] when getting "random" ports, use the filesystem to avoid conflicts between parallel test cases (processes)

---

developer-docs-site/docusaurus.config.js

Specify `@stoplight` css version to avoid integrity attribute failure which prevented script from loading after version bumps.
Ensure no console errors when loading script and verify correct layout @ `/nodes/aptos-api-spec/`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5557)

[docs] specify @stoplight css version to avoid integrity failure

---

Cargo.toml
state-sync/aptos-data-client/Cargo.toml
state-sync/inter-component/consensus-notifications/Cargo.toml
state-sync/inter-component/event-notifications/Cargo.toml
state-sync/inter-component/mempool-notifications/Cargo.toml
state-sync/state-sync-v2/data-streaming-service/Cargo.toml
state-sync/state-sync-v2/state-sync-driver/Cargo.toml
state-sync/storage-service/client/Cargo.toml
state-sync/storage-service/server/Cargo.toml
state-sync/storage-service/types/Cargo.toml

This PR updates all state sync related code to use workspace dependencies. This begins our transition to adopt unified dependencies across the entire codebase. One benefit of this PR is that we've removed at least two instances where we're depending on multiple versions of the same crate 😄
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5559)

[Cargo] Update state sync code to use workspace dependencies.

---

Cargo.lock
Cargo.toml
aptos-move/aptos-vm/src/move_vm_ext/vm.rs

This brings us to the newest state of the `aptos` branch in the Move repo. This catches multiple devx improvements (e.g. debug print, stack traces in unit tests, etc) as well as some security improvements.
These are all commits [here](https://github.com/move-language/move/commits/main) since 4/11.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5564)

[move] Update move commit hash

---

.github/workflows/continuous-e2e-state-sync-failures-catching-up-test.yaml
.github/workflows/continuous-e2e-state-sync-slow-processing-catching-up-test.yaml
testsuite/forge-cli/src/main.rs

This PR updates the broken forge tests for state sync by moving to transaction output syncing (making state sync faster and thus able to catch up). This is a temporary workaround until we make transaction output syncing the default.
Note: I've also renamed the tests and github jobs to be consistent with the rest of the state sync tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5563)

[Forge] Update broken state sync tests to use txn output syncing.

---

.github/workflows/lint-test.yaml
.github/workflows/python-lint-test.yaml
testsuite/determinator.py
testsuite/determinator_test.py
testsuite/forge.py
testsuite/forge_test.py
testsuite/lint.py
testsuite/lint_test.py

Some better testing for python code. Now includes `pyright` for static type checking (to use alongside devs' setup with pylance), and `black` for formatting
Ignore type checking in some areas for the reasons of:
* ForgeConfig class having optional fields for backwards compatibility reasons
* For some unit tests which check for assertions being non-null and having error msgs 
Fix locally, and make sure CI passes now
https://github.com/aptos-labs/aptos-core/actions/runs/3441551789/jobs/5741220501
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5537)

[python] lint fmt check

---

terraform/helm/testnet-addons/templates/loadtest.yaml

So we load `.Values.load_test.resources` correctly. Previously, it was loading `.Values.resources` due to being in the wrong `with` block
`helm template`
Load custom values with resource spec into `addons-values.yaml`, then run `helm template -s templates/loadtest.yaml . -f ../../../addons-values.yaml`:
```
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
name: release-name-testnet-addons-load-test
labels:
helm.sh/chart: testnet-addons-0.1
app.kubernetes.io/part-of: testnet-addons
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "0.1.0"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: load-test
spec:
concurrencyPolicy: Replace
schedule: "*/60 * * * *"
jobTemplate:
spec:
template:
metadata:
labels:
app.kubernetes.io/part-of: testnet-addons …
```

[helm][testnet-addons] fix loadtest resource spec

---

mempool/src/shared_mempool/coordinator.rs
mempool/src/tests/mocks.rs
mempool/src/tests/node.rs
mempool/src/tests/test_framework.rs
vm-validator/src/mocks/mock_vm_validator.rs

Previously mempool was not reading the initial config before starting, which seems like an oversight. For up-to-date nodes, the initial read will prevent a race on restart where mempool could initially handle transactions with old onchain configs. (Note though, this provides no guarantees for stale nodes or nodes that are currently undergoing an onchain config change.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5578)

[mempool] wait on init reconfig at startup

---

api/types/src/transaction.rs

This tiny PR improves the error message displayed when a transaction signature or public key length is invalid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5561)

[Types] Improve error message for signature and public key len.

---

crates/aptos-network-checker/Cargo.toml

This PR adds the missing dependency feature required to build the Aptos network checker (see: https://github.com/aptos-labs/aptos-core/issues/5504).
`cargo build -p aptos-network-checker` now works 😄
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5560)

[Aptos Network Checker] Fix required dependency.

---

Cargo.lock
aptos-move/aptos-release-builder/Cargo.toml
aptos-move/aptos-release-builder/data/example.yaml
aptos-move/aptos-release-builder/src/components/consensus_config.rs
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-release-builder/src/components/gas.rs
aptos-move/aptos-release-builder/src/components/mod.rs
aptos-move/aptos-release-builder/src/components/version.rs
aptos-move/aptos-release-builder/src/main.rs
aptos-move/aptos-release-builder/src/utils.rs
testsuite/smoke-test/src/upgrade.rs

Implement the parser to parse the release config from a yaml file. Added generation logic for consensus config as well.
`cargo run -- write-default --output-path data/example.yaml`
and `cargo run -- generate-proposals --release-config  data/example.yaml --output-dir <OUTPUT_DIR>`
The upgrade smoke test will make sure upgrading consensus config would work as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5562)

[release-tooling] Implement a parser from yaml

---

.github/workflows/continuous-e2e-state-sync-perf-fullnode-fast-sync-test.yaml
crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/wrappers.rs
testsuite/forge-cli/src/main.rs
testsuite/forge/src/interface/swarm.rs
testsuite/testcases/src/state_sync_performance.rs

This PR adds a simple forge test that benchmarks the throughput of state sync when running fast sync. Specifically, it counts and displays the throughput of the number of state values synced per second.
Note: most of this PR is simply just refactoring code into reusable methods to avoid code duplication 😄 
Ran this on forge and verified the results, e.g., a very quick run showed:
```
State sync throughput : 21837 state values / sec
Test Ok
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5584)

[Forge] Add simple test for fast sync throughput.

---

aptos-move/move-examples/moon_coin/scripts/register.move
developer-docs-site/docs/tutorials/first-coin.md

Docs were not compiling due to missing `section_name` within `/docs/tutorials/first-coin.md`
Compile docs and verify `/tutorials/your-first-coin/#step-432-registering-a-coin`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5596)

[docs] fix compile error due to missing section_name

---

.github/workflows/auto-approve-doc-prs.yaml

This automatically adds one approval for doc-change PRs to effectively reduce the required "human" approval count from 2 -> 1.
There's one gotcha with the logic:
Author creates PR, reviewer 1 approves the PR, bot adds another approval, Author amends the commit and adds non-doc changes. Ideally in this situation the bot approval should be removed, however that's not what'll happen. Once the bot approval was made, it'll remain there. 
Since I believe this sort of a rare edge case and long term we're building some more sophisticated approval gating anyways, I'll leave this problem unsolved for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5609)

cicd: auto add 1 approval for doc-change PRs

---

developer-docs-site/src/css/custom.css

Fixes color contrast issue for Algolia Search within light mode. 
Before:
After:
Review Docs in light mode and test search for readability issues related to color contrast.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5598)

[docs] Adjust Primary Color for Search within light mode

---

ecosystem/python/sdk/Makefile
ecosystem/python/sdk/README.md
ecosystem/python/sdk/pyproject.toml

I believe this was picked up by accident (because it is a toml file) as part of the change to workspace dependencies: https://github.com/aptos-labs/aptos-core/pull/5342.
I fix an issue with the Makefile while I'm here and because I'm crazy I also sort the deps alphabetically.
```
```
```
cd ecosystem/python/sdk
make examples
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5617)

Revert changes to pyproject.toml from 8958b01

---

Cargo.lock
Cargo.toml
aptos-node/Cargo.toml
config/Cargo.toml
consensus/Cargo.toml
consensus/consensus-types/Cargo.toml
consensus/safety-rules/Cargo.toml
ecosystem/node-checker/Cargo.toml
ecosystem/node-checker/fn-check-client/Cargo.toml
ecosystem/sf-indexer/firehose-stream/Cargo.toml

This PR migrates several crates to use workspace dependencies:
- `aptos-node`
- `config`
- `consensus`
- `consensus/consensus-types`
- `consensus/safety-rules`
- `ecosystem/node-checker`
- `ecosystem/node-checker/fn-check-client`
- `ecosystem/sf-indexer/firehose-stream`
Note: the rest of the `ecosystem` crates will be deleted, so I've avoided updating them here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5605)

[Cargo] Migrate several crates to use workspace deps.

---

.github/checkgroup.yml

This leverages https://tianhaoz95.github.io/check-group/#/.
This should make us more productive as it allows to only require a subset of checks to pass depending on which files in the repo have changed.
In the first phase this will allow doc changes to bypass all the other changes, hence allowing them to merge (for example via auto-merge) a lot faster.
I tested out this app (and other alternatives) in the aptos-core-playground repo https://github.com/aptos-labs/aptos-core-cicd-playground/pull/9.
Seems like check-groups does exactly what we want.
Once this is merged I will remove the required status checks in githubs branch protection rule and simply add the `Required checks` as the single requirement.
- - - …

cicd: introduce checkgroup github app to conditionally require status checks

---

Cargo.lock
Cargo.toml
execution/db-bootstrapper/Cargo.toml
execution/executor-benchmark/Cargo.toml
execution/executor-test-helpers/Cargo.toml
execution/executor-types/Cargo.toml
execution/executor/Cargo.toml
mempool/Cargo.toml
network/Cargo.toml
network/builder/Cargo.toml
network/discovery/Cargo.toml
network/memsocket/Cargo.toml
network/netcore/Cargo.toml
network/peer-monitoring-service/client/Cargo.toml
network/peer-monitoring-service/server/Cargo.toml
network/peer-monitoring-service/types/Cargo.toml
network/src/protocols/wire/handshake/v1/mod.rs
network/src/protocols/wire/handshake/v1/test.rs
sdk/Cargo.toml

This PR migrates several more crates to use workspace dependencies:
```
- execution/db-bootstrapper/Cargo.toml
- execution/executor-benchmark/Cargo.toml
- execution/executor-test-helpers/Cargo.toml
- execution/executor-types/Cargo.toml
- execution/executor/Cargo.toml
- mempool/Cargo.toml
- network/Cargo.toml
- network/builder/Cargo.toml
- network/discovery/Cargo.toml
- network/memsocket/Cargo.toml
- network/netcore/Cargo.toml
- network/peer-monitoring-service/client/Cargo.toml
- network/peer-monitoring-service/server/Cargo.toml
- network/peer-monitoring-service/types/Cargo.toml
- sdk/Cargo.toml
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/ …

[Cargo] Move some crates to workspace dependencies.

---

crates/aptos-faucet/src/lib.rs
crates/aptos/src/node/mod.rs

As it is now, if you run this command and the node thread panics, it just prints the panic without exiting. Worse than that, if it returns an error, it prints nothing at all and just silently sits there, broken.
```
cargo run -p aptos -- node run-local-testnet --force-restart --assume-yes
```
This PR fixes that, making sure that the CLI exists if the local testnet / faucet exit.
This is a very imperfect fix. Really what we want is something like what we do in the tap: https://github.com/aptos-labs/aptos-tap/blob/main/src/server/run.rs#L170. In this setup, all never-ending tasks are represented as futures (whereas this is a blend of future and blocking thread) and all tasks return errors, so instead of printing the error and then bubbling up a `()`, it actually returns the error, which can …

[CLI] Exit if the node / faucet stops when running a local testnet

---

.github/checkgroup.yml
.github/mergify.yml

semi tested manually in the cicd-playground repo.
will modify the branch protection rule to block on the mergify check instead of check-group.

cicd: introduce mergify as check-group alternative due to check-group bug

---

Cargo.lock
crates/transaction-emitter-lib/src/emitter/account_minter.rs
testsuite/forge-cli/Cargo.toml
testsuite/forge-cli/src/main.rs

- using output state sync for a few more tests
- updating gracefull backoff for tests where block sizes are reduced 
- not retrying transaction waiting, waiting is now fixed to wait as much as needed. reduced parallelism a bit, as we have failures like these sometimes - https://github.com/aptos-labs/aptos-core/actions/runs/3461311500/jobs/5778754867
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5595)

[forge] Fix flaky forge tests

---

crates/aptos/src/account/create.rs

The devnet faucet (the only prod faucet `fund-with-faucet` works with), gives out 1 APT max, so let's request that.
Really the tap doesn't even need to be given an amount, it will just use the max by default, but that can come later.
I confirmed the faucet run with the local testnet has no max, so this change should work in that case too.
```
cargo test
```
```
cargo run -p aptos --  account fund-with-faucet --account 0xb078d693856a65401d492f99ca0d6a29a0c5c0e371bc2521570a86e40d95f823
```

[CLI] Give 1 APT for `fund-with-faucet`

---

aptos-move/framework/aptos-token/sources/token.move
developer-docs-site/docs/concepts/coin-and-token/aptos-token.md

1. token transfer as one part of token lifecycle
2. update the token transfer documentation to clearly list 3 different mode with links
3. remove detail struct field documentation and should directly link to code comment

[token] update transfer doc

---

.github/workflows/continuous-e2e-network-latency-with-different-node-speed-test.yaml
aptos-move/aptos-vm/src/aptos_vm.rs
testsuite/forge-cli/src/main.rs
testsuite/testcases/src/three_region_simulation_test.rs

Add a test where, on top of realistic network latencies, we add more realistic heterogeneous processing speed.
Among other things, this tests that chain-health backoff works correctly, and we don't experience any chain pauses.
```
network::three-region-simulation : 2844 TPS, 1322 ms latency, 211400 ms p99 latency,(!) expired 6716639 out of 15830420 txns
Test Ok
```
* [Grafana dashboard](https://o11y.aptosdev.com/grafana/d/overview/overview?orgId=1&refresh=10s&var-Datasource=VictoriaMetrics%20Global&var-namespace=forge-e2e-pr-5576&var-metrics_source=All&var-chain_name=forge-big-2&from=1669055609000&to=1669060210000)
* [Humio Logs](https://cloud.us.humio.com/k8s/search?query=%24forgeLogs%28validator_instance%3D%2A%29+%7C+forge-e2e-pr-5576&widgetType=list-view&columns=%5B%7B%22type%22%3A+%22f …

[forge] Add three_region_simulation_with_different_node_speed

---

crates/transaction-emitter-lib/src/emitter/account_minter.rs
testsuite/forge-cli/src/main.rs
testsuite/testcases/src/consensus_reliability_tests.rs

- performance test success criteria need to be dynamic, as we have 2 and 5 hour runs
- backoff for stress tests is not great, as it reduces consensus stress
- for stress test on the edge of quorum, increasing the time we look for TPS from 27s to 53s, to reduce flakiness.

[forge] Fix more flaky forge

---

developer-docs-site/src/css/custom.css

`@stoplight` external CSS was disabling `list-style`.  Since our custom.css doesn't define `list-style` (relies on browser default), we needed to override this:
Now fixed:
Review lists and ensure bullet point styling has been restored.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5616)

[docs] Fix list styling (bullets) due to @stoplight css conflict

---

.github/mergify.yml

Adds more stuff to be land-blocking, as it's in the critical test path:
* `forge-compat-test / forge` should be land-blocking, along with e2e
* `helm-lint` (helm charts used in all k8s deployments)
* `python-lint-test` (tests the forge wrapper)
Also, edit the `post_check` action for mergify, clarifying to the PR author the quirk that a failed status could mean either that  (1) the checks failed, or (2) checks are pending (mergify marks these as failure still https://docs.mergify.com/actions/post_check/). This will take effect post-land. Below snippets show some test runs in a sandbox repo:
For example, if a test is still pending that is required:
And the more detailed summary:
CI and testing in a sandbox repo with mergify set up.

[mergify] block on more critical tests, and clarify the mergify title message

---

consensus/src/epoch_manager.rs
consensus/src/liveness/cached_proposer_election.rs
consensus/src/liveness/cached_proposer_election_test.rs

exclude_rounds is 20 by default, which means we don't consider last 20 rounds in leader reputation history - but we do so from the same epoch - we consider everyone is caught up with the previous epoch.
genesis is epoch=0, round=0
first block is epoch=1 round=1, and that is a reconfig, that triggers epoch 2. because votes in block metadata are for previous round, they are empty in that round. So in that round - only "active" node is proposer.
For first 20 rounds of epoch 2, that is the only history we have - and so proposer of epoch=1 round=1 will always be elected for the first 20 rounds.
That can cause issues in tests, as they might be executed over very few rounds. So removing epoch=1,round=1 from being considered for history in epoch 2.
We can make this change without backward …

[leader election] Improve leader election for first 20 rounds

---

testsuite/smoke-test/src/state_sync.rs

This PR ignores two flaky smoke tests that have started failing after logic changes were made to consensus voting. They need to be debugged.

[Smoke Tests] Ignore flaky tests.

---

aptos-move/framework/aptos-stdlib/sources/type_info.move

Addresses @davidiw 's [request to decouple commits](https://github.com/aptos-labs/aptos-core/pull/4067#discussion_r979445090)
Adds `size_of()` function for calculating number of bytes in a type, tests with vector size dynamism.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4540)

Add size_of implementation, decoupled from #4067

---

developer-docs-site/src/components/ApiExplorer/index.tsx

Fixes https://github.com/aptos-labs/aptos-core/issues/5461, though https://github.com/stoplightio/elements/issues/2279 would be the ideal fix.
```
pnpm start
```
Then I checked that the "try it" feature works by hand.

Use correct server URL in docs site API spec explorers

---

aptos-move/e2e-move-tests/Cargo.toml
aptos-move/e2e-testsuite/Cargo.toml

Both `e2e-move-tests` and `e2e-testsuite` are broken when running individually. This gets it fixed by adding the feature flag they are missing.

[e2e move tests] fix broken tests when running individually

---

developer-docs-site/src/css/custom.css

Update `<ol>` elements to utilize `list-style-type: decimal;` to enable ordered lists styling to display numbers
Verify numbers are displayed to the left of ordered lists instead of bullet points (disc). Eg: `/nodes/validator-node/operator/update-validator-node`

[docs] Fix Ordered List styling to display numbers

---

.github/mergify.yml

If a PR has not triggered `automerge` or has not been labelled with the corresponding e2e test or build labels, the title message displayed by `post_check` action in mergify is misleading.
Now, if a check has been skipped, it displays: `Some checks were skipped (try rebasing, toggling automerge, or applying the corresponding labels)...`

[mergify] check title reflects skipped status

---

aptos-move/aptos-vm/src/errors.rs

Adjust the error severity of Move functions inside AptosVM. Currently the known move functions such as block prologue, txn prologue and epilogue are viewed as non fallible from `AptosVM`. This should be the case only with sequential execution though, as with speculative parallel execution, some of the functions may fail because prior txn hasn't been scheduled to be executed yet. 
This happens quite frequently to the blockmetadata transaction during state sync where multiple block metadata transactions are executed at once, which created very nasty false positive alarms for on call.
TBD
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5586)

[aptos-vm] Adjust severity of some error codes.

---

aptos-move/framework/aptos-framework/doc/resource_account.md
aptos-move/framework/aptos-framework/sources/resource_account.move
aptos-move/move-examples/mint_nft/sources/minting.move
aptos-move/move-examples/resource_account/sources/simple_defi.move

Read to learn. And I think it is not useful and a waste of gas. Remove it.
ut
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5486)

[Framework] remove unnecessary lines creating resource acct signer

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/abis.ts
ecosystem/typescript/sdk/src/aptos_account.test.ts
ecosystem/typescript/sdk/src/aptos_account.ts
ecosystem/typescript/sdk/src/coin_client.test.ts
ecosystem/typescript/sdk/src/coin_client.ts

This addresses https://github.com/aptos-labs/aptos-core/issues/5648 and https://github.com/aptos-labs/aptos-core/issues/5720. While I'm here I fix some incorrect documentation on `checkBalance`, clarify the docs for generating ABIs, and add some more comments to these functions.
Based on a manual inspection and the current / new tests, this should be backwards compatible.
I added new tests, run them like this:
```
pnpm test
```

[TS SDK] Update CoinClient to address #5648 and #5720

---

.github/workflows/sdk-release.yaml
Cargo.lock
api/types/src/headers.rs
crates/aptos-rest-client/Cargo.toml
crates/aptos-rest-client/examples/README.md
crates/aptos-rest-client/examples/account/main.rs
crates/aptos-rest-client/src/lib.rs
crates/aptos-rest-client/src/state.rs

This PR adds support for using the pagination added in https://github.com/aptos-labs/aptos-core/pull/5313.
You'll see that there are two functions, `paginate_with_cursor` and `paginate_with_cursor_bcs`. They're pretty similar, but I think the extra logic required to have just one function would be more complex than it's worth (it'd probably necessitate a trait and/or some extra closures passed into the function for building the collections).
For now I've tested manually by lowering the limit values and adding printing and I can see that it indeed makes multiple requests, doesn't loop forever, merges the data correctly, etc. We should add tests, though the client is currently totally untested, so that'd require a bit of extra testing boilerplate.
I also need to see if CI passes, lots of …

Fix functions for getting all resources / modules on an account by using pagination

---

Cargo.lock
aptos-move/aptos-transaction-benchmarks/Cargo.toml

Fix the benchmark regression because of feature unification. Previously benchmark runner is always executing failed transaction and thus not providing any useful information. 
Manually ran the benchmarker and print the transaction output to make sure we all transaction are executed successfully.

[aptos-transaction-benchmark] Fix benchmark regression

---

aptos-move/framework/aptos-stdlib/doc/any.md
aptos-move/framework/aptos-stdlib/doc/copyable_any.md
aptos-move/framework/aptos-stdlib/doc/from_bcs.md
aptos-move/framework/aptos-stdlib/doc/type_info.md
aptos-move/framework/aptos-stdlib/sources/copyable_any.spec.move
aptos-move/framework/aptos-stdlib/sources/from_bcs.spec.move
aptos-move/framework/aptos-stdlib/sources/type_info.move
aptos-move/framework/aptos-stdlib/sources/type_info.spec.move

Added the spec of the following modules:
- `from_bcs`
- `any`
- `copyable_any`
- `type_info`
There are TODOs which are filed as separate Github issues:
- https://github.com/move-language/move/issues/699
- https://github.com/move-language/move/issues/700
- https://github.com/move-language/move/issues/701
- https://github.com/move-language/move/issues/702

[Spec] Completed the spec of `from_bcs`, `any`, `copyable_any` and `type_info`

---

ecosystem/typescript/sdk/.npmignore
ecosystem/typescript/sdk/README.md

Moving to manual release instructions.

Update the release instructions for the TS SDK

---

aptos-move/framework/aptos-token/doc/token.md
aptos-move/framework/aptos-token/sources/token.move

address the request on enabling partial withdraw token with capability.
This allows people list x fungible tokens and buyer can buy a smaller than x amount. The rest of the tokens can still be listed on sale until all the tokens are bought

[token] add partial withdraw with capability

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/transaction_builder/builder_utils.ts
ecosystem/typescript/sdk/src/utils/property_map_serde.test.ts
ecosystem/typescript/sdk/src/utils/property_map_serde.ts

currently, string type is "0x1::string::String", which is not consistent with convension
This PR basically allows people to parse string/String and they will be converted to aptos String type on-chain

[Token] parse string type in property map

---

aptos-move/framework/src/aptos.rs
aptos-move/framework/src/built_package.rs
crates/aptos/src/common/types.rs
crates/aptos/src/governance/mod.rs
crates/aptos/src/move_tool/mod.rs
crates/aptos/src/test/mod.rs

Now all the confusion is gone around why dependencies are out of date, it follows similar to cargo, where you want to use a git hash if you want frozen dependencies.  Otherwise, it will updated.  Additionally, there's a flag to turn it off if your network is disconnected, or something like that.
TBD. need to test locally, but it did work fine in the move CLI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4595)

[aptos-cli] Pull latest packages by default for cached branch dependencies

---

developer-docs-site/docs/tutorials/first-dapp.md

add connect() function.
add connect() function before account() function.
I tried aptos's tutorial  「Your First Dapp」and `window.aptos.account()` in the app didn't work well.
So I added `connect()` function before `account()` function.
Below is the link of my github repo.
[https://github.com/mashharuki/AptosRepo](https://github.com/mashharuki/AptosRepo)
Pleae try the following to test.
1. `cd first-dapp`
2. `npm i`
3. `npm run start`
4.  please access to [http://localhost:3000](http://localhost:3000)
You can see a dapp like this.
If you push "送信" button , a popup will appear.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4988)

【Developer Tutorials】fix useEffect()

---

aptos-move/framework/aptos-framework/sources/account.move

Adds test-only standalone signer creation, independent of an Aptos-style account.
@davidiw @wrwg @alinush @chen-robert
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5433)

Add test-only standalone signer creation

---

types/src/transaction/authenticator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5415)

fix doc for AuthenticationKey

---

crates/aptos-rosetta/src/client.rs
crates/aptos-rosetta/src/construction.rs
crates/aptos-rosetta/src/types/misc.rs
crates/aptos-rosetta/src/types/move_types.rs
crates/aptos-rosetta/src/types/objects.rs
testsuite/smoke-test/src/rosetta.rs

Adds Reset Lockup command to Rosetta for staking pools
Smoke test now covers reset lockup and create staking pool

[rosetta] Add reset lockup command

---

developer-docs-site/docs/guides/handle-aptos-errors.md

Explain LINKER_ERROR

---

aptos-move/framework/src/docgen.rs

@wrwg @davidiw @gregnazario @alinush 
Per #5581 , DocGen CLI options defaulting to true prohibit negation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5582)

Remove CLI option true defaults to enable negation

---

terraform/fullnode/gcp/cluster.tf
terraform/fullnode/gcp/kubernetes.tf

Fixes workload scheduling when node-auto-provisioning (NAP) is enabled, by removing the nodeSelector, which isn't present in nodes created by NAP. Also do not set NAP resource limits when it is disabled, as that results in API failure.
Related to and resolves the primary issue in https://github.com/aptos-labs/aptos-core/pull/5645
Apply to cluster

[tf/gcp][fullnode] fix nap scheduling and apply when disabled

---

.github/workflows/check-sdk-examples.yaml
.github/workflows/lint-test.yaml
ecosystem/python/sdk/Makefile
ecosystem/python/sdk/aptos_sdk/authenticator.py
ecosystem/python/sdk/aptos_sdk/bcs.py
ecosystem/python/sdk/aptos_sdk/client.py
ecosystem/python/sdk/aptos_sdk/ed25519.py
ecosystem/python/sdk/aptos_sdk/transactions.py
ecosystem/python/sdk/examples/common.py
ecosystem/python/sdk/examples/simple-nft.py
ecosystem/python/sdk/examples/transfer-coin.py
ecosystem/python/sdk/examples/your-coin.py

* Found bugs in the last update to Python and fixed those
* Finished up the process of bringing in mypy and flushing out good type checking
Tested with
`make test && make examples`
I'm not competent enough to figure out how to integrate with CI/CD

Fix Python SDK

---

aptos-move/framework/aptos-stdlib/doc/ed25519.md
aptos-move/framework/aptos-stdlib/doc/multi_ed25519.md
aptos-move/framework/aptos-stdlib/sources/cryptography/ed25519.spec.move
aptos-move/framework/aptos-stdlib/sources/cryptography/multi_ed25519.move
aptos-move/framework/aptos-stdlib/sources/cryptography/multi_ed25519.spec.move
aptos-move/framework/aptos-token/doc/token.md

- modeled the native functions with uninterpreted functions
- added functional specifications
- the axioms of the uninterpreted functions will be added when needed.

[Spec] Add the initial specs for `ed25519` and `multi_ed25519`

---

aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/sources/genesis.move
aptos-move/framework/aptos-framework/sources/genesis.spec.move
aptos-move/framework/aptos-token/doc/token.md

* This commits update the `[verify_only]` function in genesis (i.e., `initialize_for_verification`) to reflect the `encode_aptos_mainnet_genesis_transaction` of `vm-genesis`.
* The spec of `create_signer` is added.
* One TODO is removed because the `Table` issue has been fixed.
move prove

[Spec] Updated the spec of the Genesis module

---

ecosystem/python/sdk/Makefile
ecosystem/python/sdk/aptos_sdk/client.py
ecosystem/python/sdk/aptos_sdk/ed25519.py
ecosystem/python/sdk/examples/simulate-transfer-coin.py

* Cleaned up some typing
* Some aesthetic changes
* Support for simulating txns within python
* Basic support for a client config
tested locally and now with ci/cd!

[Python] Simulation and other trivial improvements

---

Cargo.lock
Cargo.toml
storage/accumulator/Cargo.toml
storage/aptosdb/Cargo.toml
storage/aptosdb/src/event_store/mod.rs
storage/aptosdb/src/ledger_store/mod.rs
storage/aptosdb/src/pruner/transaction_store/test.rs
testsuite/aptos-fuzzer/Cargo.toml
testsuite/aptos-fuzzer/src/fuzz_targets/storage.rs

Just one crate to start with, then I'll start batching these changes. This is part of the plan to name all crates `aptos-<name>`.
CI.

[crates] Rename accumulator to aptos-accumulator

---

.github/workflows/lint-test.yaml
testsuite/smoke-test/src/aptos_cli/account.rs

Previously the condition was removed, but that defaults to `success()` so would only upload the artifact for flaky test runs and not actually failed test runs. 
Confirm upload on flaky and injected final failure.

[smoke tests] fix artifact upload so it works on failure again

---

aptos-node/src/lib.rs
config/src/config/mod.rs
consensus/src/consensusdb/mod.rs
consensus/src/lib.rs
docker/compose/aptos-node/validator.yaml
state-sync/state-sync-v2/state-sync-driver/src/metadata_storage.rs
storage/aptosdb/src/lib.rs
terraform/helm/aptos-node/files/configs/validator-base.yaml
testsuite/forge/src/backend/local/node.rs

For largedb test now, but could also be a useful feature in the future. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4591)

[Forge] Add working_dir param to support running node on checkpoint dir, so that the existing data on disk is preserved.

---

aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/voting.md
aptos-move/framework/aptos-framework/sources/aptos_governance.move
aptos-move/framework/aptos-framework/sources/voting.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs

Implementation of this AIP: https://github.com/aptos-foundation/AIPs/issues/3. 
TLDR: we're supporting multi-step proposals in this PR. We do so by updating `proposal.execution_hash` and `ApprovedExecutionHashes` on-chain to the `next_execution_hash`. 
Summary of changes included in this PR:
`aptos_governance` module: 
Added:
- `aptos_governance::create_proposal_v2()`: this is similar to the existing `aptos_governance::create_proposal`, but here we call the newly added `voting::create_proposal_v2` to create an Aptos governance proposal. 
- `aptos_governance::resolve_multi_step_proposal()`: similar to the existing `aptos_governance::resolve()`, but here we replace the current execution hash in `ApprovedExecutionHashes` with `next_execution_hash`, and call `voting::resolve_proposal_v2` to …

[framework] governance multi-step proposal

---

.github/workflows/check-minimum-revision.yaml
testsuite/determinator.py
testsuite/determinator_test.py

`::save-state` and `::set-output` GHA commands will be deprecated soon, as per: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ and the warnings on runs such as: https://github.com/aptos-labs/aptos-core/actions/runs/3526688470
The warnings are visually noisy and you have to scroll past all of them to view test summaries.
This is mostly used in python test code and whatever sits behind our mini python target determinator determinator. There are some 3rd party Github Actions that still use it as well. For these we can either update the git ref for these if it's been updated upstream already, otherwise just leave it as is.
Determinator still works

[gha] deprecate set-output for determinator

---

state-sync/state-sync-v2/state-sync-driver/src/metrics.rs
state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs

This PR adds additional state sync metrics to better track chunk sizes of data being fed to the storage synchronizer.
Verified the metrics work manually.

[State Sync] Add metrics around chunk sizes.

---

terraform/aptos-node-testnet/addons.tf
terraform/aptos-node-testnet/main.tf
terraform/aptos-node-testnet/variables.tf
terraform/aptos-node/aws/kubernetes.tf
terraform/aptos-node/aws/variables.tf
terraform/aptos-node/gcp/kubernetes.tf
terraform/aptos-node/gcp/variables.tf

Add a variable `manage_via_tf` which allows operators to choose whether to use Terraform to manage their aptos-node (application) deployment, or simply deploy it once (re-deploying on infra changes), but otherwise relying on other toolling such as another k8s client to update the application.
The way it works is:
* all changes to `values` blocks are ignored via lifecycle ignore. This prevents re-deploy (or at least a helm re-evaluation) on small changes like irrelevant helm values.
* all changes `set` blocks are conditionally ignored depending on whether `manage_via_tf` is set or not. The type of values set using `set` blocks are those such as `imageTag` and `era`, which we *would* expect a re-deployment of the application if we want TF to manage the k8s deployment
Apply while toggling …

terraform k8s separation

---

state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs

This PR adds additional state sync metrics to better track chunk sizes of data being fed to the storage synchronizer for fast sync.
Verified the metrics work manually.

[State Sync] Add metrics for fast syncing chunk sizes.

---

.github/actions/replay-verify/action.yaml

backup-cli is now aptos-backup-cli and one reference didn't get changed.

trivial: crate name change

---

crates/aptos-rest-client/src/lib.rs
crates/aptos/src/common/types.rs

The API errors for simulation are fixed, so we will use those now in the cli rather than fetching from the ABI
Tested manually as both a success and a failure:
```
$ ./target/debug/aptos account transfer --account 0x1337 --amount 999999999999999999
{
"Error": "Simulation failed with status: Move abort in 0x1::coin: EINSUFFICIENT_BALANCE(0x10006): Not enough coins to complete transaction"
}
$ ./target/debug/aptos account transfer --account 0x1337 --amount 1                
Do you want to submit a transaction for a range of [184400 - 276600] Octas at a gas unit price of 100 Octas? [yes/no] >
y
{
"Result": {
"gas_used": 1878,
...
```
- - - …

[cli] Use simulation errors from API

---

execution/executor-types/src/lib.rs
execution/executor/src/chunk_executor.rs
execution/executor/src/tests/mod.rs
storage/backup/backup-cli/src/backup_types/tests.rs
storage/backup/backup-cli/src/backup_types/transaction/restore.rs
storage/backup/backup-cli/src/backup_types/transaction/tests.rs
storage/backup/backup-cli/src/bin/db-restore.rs
storage/backup/backup-cli/src/bin/replay-verify.rs
storage/backup/backup-cli/src/coordinators/replay_verify.rs
storage/backup/backup-cli/src/coordinators/restore.rs
storage/backup/backup-cli/src/coordinators/verify.rs

Add an option to intentionally skip re-execution for txns that broke backwards compatibility
Ran the logic with the known transactions on chain that broke backwards compatibility and made sure those txn info were correct.

[replay-verify] Add an option to skip txns that are known to broke backward compatibility

---

aptos-move/framework/aptos-token/doc/token.md
aptos-move/framework/aptos-token/sources/token.move

fix the duplicated the error code

[token] fix the duplicated error code

---

developer-docs-site/docs/concepts/txns-states.md

Correct database versioning classification

---

developer-docs-site/docs/concepts/governance.md

Added more details to the governance doc. Lmk if I'm missing anything, would be happy to add more : )

[docs] updated governance doc

---

aptos-move/framework/aptos-stdlib/sources/comparator.move

The [comarator](https://github.com/0xpause/aptos-core/blob/49d77e6d466b9b0a22a5765d35393bb27a035cd3/aptos-move/framework/aptos-stdlib/sources/comparator.move#L27) is not suitable for Move integer types. Add more comment to describe this and fix the unittest.
No

[aptos-stdlib] fix comparator tests

---

testsuite/forge-cli/src/main.rs

There has been some flakiness found in forge performance - reducing it temporarily to reduce the noise. We will increase it as we land single-node performance improvement items in next few months.

[Forge] Reduce the TPS requirement from 6000 to 5500

---

Cargo.lock
aptos-move/aptos-release-builder/Cargo.toml
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-release-builder/src/components/mod.rs
aptos-move/aptos-release-builder/src/main.rs
crates/aptos-rest-client/src/lib.rs

Add an option to compare on chain configs so that governance proposal will only be generated when they are modified.
Tested the fetch and compare logic with local aptos node. Was wondering if we should persist such test in smoke test?

[aptos-release-tooling] Add an option to compare release binary with on chain configs

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/coin_client.ts

Use `getAccountResource` to replace `getAccountResources` in `CoinClient#checkBalance`, which can reduce network load.
```
pnpm test
```

[TS SDK] use getAccountResource in checkBalance

---

developer-docs-site/docs/guides/move-guides/index.md
developer-docs-site/docs/guides/move-guides/mint-nft-cli.md
developer-docs-site/sidebars.js

Begin porting Move Workshop #1 to Aptos.dev

---

aptos-move/e2e-move-tests/src/tests/gas.rs
aptos-move/framework/aptos-stdlib/doc/simple_map.md
aptos-move/framework/aptos-stdlib/sources/simple_map.move
aptos-move/framework/aptos-token/doc/property_map.md
aptos-move/framework/aptos-token/doc/token.md
aptos-move/framework/aptos-token/sources/property_map.move
aptos-move/framework/aptos-token/sources/token.move

Change the internal implementation of SimpleMap in order to reduce gas prices with minimal impact on Move and Public APIs.
The current implementation of SimpleMap uses a BCS-based logarithmic comparator identifying slots on where to store data in a Vector. Unfortunately this is substantially more expensive than a trivial linear implementation, because each comparison requires BCS serialization followed by a comparison. The conversion to BCS cannot be resolved as quickly as traditional comparator can and substantially impacts gas prices.
- Replace the internal definition of `find` from the current logarithmic implementation to a linear search across the vector.
- Replace the functionality within `add` to call `vector::push_back` and append new values instead of inserting them into their …

Improve simple_map gas cost

---

aptos-move/move-examples/post_mint_reveal_nft/Move.toml
aptos-move/move-examples/post_mint_reveal_nft/sources/minting.move
aptos-move/move-examples/tests/move_unit_tests.rs

[move-examples] post-mint reveal example

---

Cargo.lock
crates/aptos/Cargo.toml

Need to update CLI, due to compiler change causing errors on tests.
See: https://github.com/aptos-labs/aptos-core/issues/5867
Tested manually to build
Old release:
```
aptos move test --named-addresses hello_blockchain=default --package-dir aptos-move/move-examples/hello_blockchain
BUILDING Examples
error[E03002]: unbound module
┌─ aptos-move/move-examples/hello_blockchain/../../framework/aptos-framework/sources/coin.move:950:57
│
950 │     #[expected_failure(abort_code = 0x50003, location = aptos_framework::system_addresses)]
│                                                         ^^^^^^^^^^^^^^^ Unbound module alias 'aptos_framework'
error[E03002]: unbound module
┌─ …
```

[aptos-cli] Update to 1.0.2

---

developer-docs-site/docs/concepts/accounts.md
developer-docs-site/docs/whats-new-in-docs.md

Add references to ANS in Accounts concept and See what's new

---

developer-docs-site/docs/concepts/governance.md

Fix link to Aptos Foundation AIP GitHub from Aptos Governance page

---

.github/actions/verify-modules/action.yaml
.github/workflows/replay-verify-testnet.yaml
.github/workflows/verify-on-chain-modules-mainnet.yaml
.github/workflows/verify-on-chain-modules-testnet.yaml
execution/executor/src/chunk_executor.rs

Made two changes to the replay verify pipeling:
1. Enabled the recent feature implemented in #5747 so that we no longer need to replay from the middle of history.
2. Added a manual CI job to scan through the currently published modules in production. related to #5793
TBD

[CI] Adjust the replay verify job

---

aptos-move/aptos-vm/src/aptos_vm.rs

Make sure deserializing module bundles will have the feature flag for v6 file format
TBD.

[aptos-vm] Fix binary format version compatibility.

---

aptos-move/aptos-vm/src/verifier/view_function.rs
aptos-move/framework/src/extended_checks.rs
aptos-move/framework/src/module_metadata.rs

This generalizes metadata stored in the bytecode for attributes to allow parameters, as in `#[storage_group(group)]`. This was added recently for `#[view]` but did not support parameters. Folding this into current release will avoid breaking changes later.

[move-vm] Generalize metadata for attribute parameters

---

aptos-node/src/lib.rs
config/src/config/state_sync_config.rs
state-sync/state-sync-v2/data-streaming-service/src/data_notification.rs
state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs
state-sync/state-sync-v2/data-streaming-service/src/streaming_client.rs
state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs
state-sync/state-sync-v2/data-streaming-service/src/tests/utils.rs
state-sync/state-sync-v2/state-sync-driver/Cargo.toml
state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
state-sync/state-sync-v2/state-sync-driver/src/driver.rs
state-sync/state-sync-v2/state-sync-driver/src/driver_factory.rs
state-sync/state-sync-v2/state-sync-driver/src/metrics.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/continuous_syncer.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/driver_factory.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
state-sync/state-sync-v2/state-sync-driver/src/utils.rs
state-sync/storage-service/server/src/tests.rs
testsuite/smoke-test/src/state_sync.rs

Note: Over 1k lines of this PR are just new tests. The rest is boring boilerplate for supporting client-side data requests and a new syncing mode.
This PR adds the client-side implementation of the new semi-intelligent [syncing mode](https://github.com/aptos-labs/aptos-core/pull/5742) that switches between output application and transaction execution depending on whichever is faster. To achieve this, we:
1. Add a new set of state sync modes to fetch transactions or outputs.
2. Add all the boilerplate for the new state sync modes to fetch the correct data from the server (e.g., via data streams).
3. Set the maximum transaction output chunk size to be 1k (from 2k). Based on data in mainnet, this is more optimal as it results in fewer pre-fetcher misses.
4. Add a new fallback mechanism to …

[State sync] Add client-side of new state syncing mode.

---

config/src/config/state_sync_config.rs

This PR bumps the fallback time in intelligent syncing mode from 2 minutes to 3 minutes.

[State Sync] Bump fallback time from 2 minutes to 3 minutes.

---

aptos-move/block-executor/src/counters.rs
aptos-move/block-executor/src/executor.rs

Add a counter for monitoring, e.g. with more threads should observe more aborts and dependency waits, and actually dependency waits are saving aborts, so good complementary metric to the number of speculative aborts.

[Parallel Execution] Counter for dependency waits

---

aptos-move/framework/src/aptos.rs
aptos-move/framework/src/built_package.rs
crates/aptos/src/common/types.rs
crates/aptos/src/governance/mod.rs
crates/aptos/src/move_tool/mod.rs
crates/aptos/src/test/mod.rs

The CLI & the underlying BuiiltPackage didn't handle bytecode version correctly. This gets them fixed.

[cli] fix errors caused by mishandling of bytecode version

---

crates/indexer/src/database.rs

support all statement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5060)

[index] support all statement

---

aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/configs/features.move
aptos-move/framework/aptos-stdlib/doc/multi_ed25519.md
aptos-move/framework/aptos-stdlib/sources/cryptography/multi_ed25519.move
aptos-move/framework/aptos-stdlib/sources/cryptography/multi_ed25519.spec.move
aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move
aptos-move/framework/src/natives/cryptography/multi_ed25519.rs
crates/aptos-crypto/src/multi_ed25519.rs
crates/aptos-crypto/src/unit_tests/multi_ed25519_test.rs

Our MultiEd25519 Move module allowed for some invalid MultiEd25519 PKs to be deserialized as `ValidatedPublicKey` structs. Such incorrectly-deserialized structs would've been caught later on during signature verification. Nonetheless, we will fix this bug to guarantee correct semantics of MultiEd25519 validated PKs.
**TODO:** <strike>`grep` for uses of deprecated APIs, if any and update this description.</strike>
Our native implementation of the `public_key_validate_internal` Move function did not check that a MultiEd25519 PK had >= 1 sub-PKs. 
Furthermore, this implementation did not minimize the gas costs charged to the user, when aborting early.
This PR introduces a new `public_key_validate_v2_internal` API that addresses these two issues. As a result, it deprecates two public …

[move] fix MultiEd25519 PK validation small bug

---

aptos-move/aptos-vm/src/verifier/view_function.rs
aptos-move/framework/src/extended_checks.rs
aptos-move/framework/src/module_metadata.rs

This generalizes metadata stored in the bytecode for attributes to allow parameters, as in `#[storage_group(group)]`. This was added recently for `#[view]` but did not support parameters. Folding this into current release will avoid breaking changes later.

[move-vm] Generalize metadata for attribute parameters (cherry-pick #5896)

---

.github/workflows/continuous-e2e-account-creation-test.yaml
.github/workflows/continuous-e2e-changing-working-quorum-test copy.yaml
.github/workflows/continuous-e2e-changing-working-quorum-test-high-load.yaml
.github/workflows/continuous-e2e-compat-test.yaml
.github/workflows/continuous-e2e-consensus-stress-test.yaml
.github/workflows/continuous-e2e-different-node-speed-and-reliability-test.yaml
.github/workflows/continuous-e2e-forge-continuous.yaml
.github/workflows/continuous-e2e-full-node-reboot-stress-test.yaml
.github/workflows/continuous-e2e-graceful-overload-test.yaml
.github/workflows/continuous-e2e-haproxy-test.yaml
.github/workflows/continuous-e2e-network-latency-test.yaml
.github/workflows/continuous-e2e-network-latency-with-different-node-speed-test.yaml
.github/workflows/continuous-e2e-network-partition-test.yaml
.github/workflows/continuous-e2e-nft-mint-test.yaml
.github/workflows/continuous-e2e-performance-test.yaml
.github/workflows/continuous-e2e-release-test.yaml
.github/workflows/continuous-e2e-single-vfn-test.yaml
.github/workflows/continuous-e2e-state-sync-failures-catching-up-test.yaml
.github/workflows/continuous-e2e-state-sync-perf-fullnode-apply-test.yaml
.github/workflows/continuous-e2e-state-sync-perf-fullnode-execute-test.yaml
.github/workflows/continuous-e2e-state-sync-perf-fullnode-fast-sync-test.yaml
.github/workflows/continuous-e2e-state-sync-perf-validator-test.yaml
.github/workflows/continuous-e2e-state-sync-slow-processing-catching-up-test.yaml
.github/workflows/continuous-e2e-twin-validator-test.yaml
.github/workflows/continuous-e2e-validator-reboot-stress-test.yaml

9am forge test runs
continuous suite runs 9am, 3pm
tune down test intervals for the holidays to reflect lower commit rate
also rename some files so forge tests are easier to find in `.github`. They are all prefixed `continuous-e2e-*` now

[gha] run forge once a day, continuous forge twice a day

---

.github/actions/gar-auth/action.yaml

fixes 403 errors on some jobs/builds from @igor-aptos

cicd: increase gcp auth token lifetime

---

developer-docs-site/docs/guides/move-guides/upgrading-move-code.md

This PR makes some small tweaks and additions to the doc for upgrading move code. Specifically, it makes it explicit that to republish move code, simply publish it again at the same address :) In addition, it cleans up a few things that were otherwise slightly confusing to me.

[Docs] Some small tweaks and additions to upgrade move code.

---

developer-docs-site/docs/guides/move-guides/index.md
developer-docs-site/docs/index.md
developer-docs-site/docs/reference/glossary.md
developer-docs-site/docs/whats-new-in-docs.md

Link to certik.com blog post on Move Prover, solicit contributions

---

Cargo.lock
config/Cargo.toml
config/src/config/network_config.rs
network/builder/src/builder.rs
network/discovery/Cargo.toml
network/discovery/src/lib.rs
network/discovery/src/rest.rs
network/discovery/src/validator_set.rs
network/src/connectivity_manager/mod.rs
testsuite/smoke-test/src/network.rs

Now, if the network has fallen too far behind, a user can use the REST API discovery to parse the Validator set directly to get a more up to date view of the validator set.
Tested locally with onchain discovery off.  It does get the nodes, and syncs from onchain
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/4412)

[network] Add REST API discovery for Validator full nodes

---

aptos-node/src/lib.rs
config/src/config/state_sync_config.rs
state-sync/state-sync-v2/state-sync-driver/src/driver.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
testsuite/forge/src/backend/local/swarm.rs
testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs

This PR adds a simple config flag around auto-bootstrapping to disable it in production (because it's only really useful for testing environments), i.e., auto-bootstrapping only happens if a node is a validator, it has no peer connections for a sustained period of time, and the waypoint version is genesis. In a production environment, we don't want auto-boostrapping because the node should always have peers.

[State Sync] Add a config flag around auto-bootstrapping.

---

config/src/config/state_sync_config.rs
state-sync/inter-component/event-notifications/src/lib.rs
state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs
state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs
state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
state-sync/state-sync-v2/state-sync-driver/src/driver.rs
state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
state-sync/state-sync-v2/state-sync-driver/src/utils.rs

This PR removes unnecessary panics and expects from the state sync code. While all of these instances should never be exploitable in practice, converting them to errors is safer :)
Note: this PR also increases the default `max_epoch_chunk_size` and `max_state_chunk_size`. Experimentation on `mainnet` shows that we can increase these without incurring network truncation.

[State Sync] Remove unnecessary panics and expects.

---

aptos-move/aptos-gas/src/aptos_framework.rs
aptos-move/aptos-gas/src/gas_meter.rs

The gas version there is wrong. New native functions added should use the next gas version. The new hash native function added in that commit uses an existing gas version (4) while the current latest version is 5 - https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/aptos-gas/src/gas_meter.rs#L49
Compat test

[Gas] Correct the gas schedule version for a recently added native function

---

aptos-move/aptos-sdk-builder/src/main.rs

Addresses part of the issues mentioned in https://github.com/aptos-labs/aptos-core/issues/5986#issuecomment-1363427483 by defaulting to `local_types` generation.

rust-sdk-builder: default to using local types

---

developer-docs-site/docs/nodes/full-node/bootstrap-fullnode.md
developer-docs-site/sidebars.js

This PR refreshes the fullnode bootstrapping guide and adds the guide back to the navigation bar. This should help unblock users until we have dedicated Aptos backup services running.

[Docs] Refresh the fullnode bootstrapping guide.

---

developer-docs-site/docs/cli-tools/build-from-source.md
developer-docs-site/docs/guides/getting-started.md

This updates dependency instructions for Windows, Linux, and macOS on the getting started page for downloading source.  This should be eventually replace any other place that downloads source in the instructions.
I tested the manual instructions for Windows directly in a Windows VM.  The instructions for Linux have been there for a long time / the script should be good enough.
The instructions for macOS are not tested, but similar on the script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aptos-labs/aptos-core/5090)

[docs] Add dependency instructions for from source for Windows

---

.editorconfig
.gitattributes
scripts/dev_setup.ps1

Add some extra files to help prevent CRLF from getting into the codebase.  Additionally, there's a package manager for Windows, that allows for easy installation of the latest dependencies (which was suggested by LLVM).
I ran the script locally and it worked; however, I will need to try the whole process on a machine that wasn't ready for development.
Additionally, this PR was built on Windows using this setup

[dev setup] Add improvements to the Windows development experience

---

developer-docs-site/docs/guides/state-sync.md

This PR adds a small blurb about running an archival fullnode to the state synchronization page. Related to the issue here: https://github.com/aptos-labs/aptos-core/issues/6024

[Docs] Add small note about archival fullnodes.

---

developer-docs-site/docs/nodes/measure/index.md
developer-docs-site/docs/nodes/measure/node-health-checker-faq.md
developer-docs-site/docs/nodes/measure/node-health-checker.md
developer-docs-site/docs/nodes/measure/node-inspection-service.md
developer-docs-site/docs/nodes/validator-node/operator/update-validator-node.md
developer-docs-site/docs/whats-new-in-docs.md
developer-docs-site/docusaurus.config.js
developer-docs-site/sidebars.js
ecosystem/node-checker/README.md
ecosystem/node-checker/configuration_examples/README.md

This PR makes a few small modifications to the doc site:
1. Rename "Find Nodes" to "Understand Nodes".
2. Add a new "Measure Nodes" section.
3. Move all health check docs to the "Measure Nodes" section.
4. Add a new doc that describes the Node Inspection service and existing node metrics (this was added to the "Measure Nodes" section).
Note: to do this, I had to rearrange a few things. Testing locally seems okay. 
Manual verification (i.e., locally deploying and inspecting the new docs format).

[Docs] Add a new doc about the node inspection service.

---

crates/aptos/src/common/types.rs
crates/aptos/src/common/utils.rs
crates/aptos/src/test/mod.rs
testsuite/smoke-test/src/aptos_cli/account.rs
testsuite/smoke-test/src/rosetta.rs

As shown from some Discord conversations, the CLI didn't have expiration time configurable.  So, if you're trying to do something like submit a large transaction over a slow connection, it's possible your transaction doesn't make it.
```
aptos account transfer --expiration-secs 1 --amount 1 --account default 
Do you want to submit a transaction for a range of [45500 - 68200] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
"Result": {
"gas_used": 522,
"balance_changes": {
"b6dbf76636021a840c64da0ca6aa94297b4ead015f7398521f57347f68364898": {
"coin": {
"value": "99478000"
},
"deposit_events": {
"counter": "11",
"guid": {
"id": {
"addr": "0xb6dbf76636021a840c64da0ca6aa94297b4ead015f7398521f57347f68364898",
"creation_num": "2"
}
}
},
"frozen": false, …
```

[cli] Add expiration time to the CLI

---

aptos-move/framework/src/built_package.rs
aptos-move/framework/src/module_metadata.rs

This allows the CLI to operate with older networks. Notice this also means that by default, view functions do not work unless one uses the option `--bytecote-version 6`.

[metadata] Only generate V1 module metadata if file format v>=6

---

aptos-move/framework/aptos-framework/doc/account.md
aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/sources/account.spec.move
aptos-move/framework/aptos-framework/sources/coin.spec.move
aptos-move/framework/aptos-stdlib/doc/ed25519.md
aptos-move/framework/aptos-stdlib/doc/multi_ed25519.md
aptos-move/framework/aptos-stdlib/doc/type_info.md
aptos-move/framework/aptos-stdlib/sources/cryptography/ed25519.spec.move
aptos-move/framework/aptos-stdlib/sources/cryptography/multi_ed25519.spec.move
aptos-move/framework/aptos-stdlib/sources/type_info.spec.move
aptos-move/framework/move-stdlib/doc/option.md
aptos-move/framework/move-stdlib/sources/option.move

- this PR completes many TODOs in the specs of coin and account modules.
- added more specs and helper spec functions to `ed25519` and `multi_ed25519` modules
- enhanced the spec of `type_info` module
- TODO: the spec of `chain_id()` is blocked by the bit operation support.
`move prove`

[Spec] Added more specs to the `coin` and `account` modules

---

docker/rust-all.Dockerfile

We use `sid` unstable apt package sources in validator-testing image and install certain packages without version pinning. As a result, clang and llvm got updated to v14 recently, which breaks bcc which depends on v11. 
This PR pins the version fro clang and llvm to v11. 
Wait for CICD.

[Dockerfile] Pin llvm and clang dependency version in validator-testing image

---

crates/aptos/e2e/README.md
crates/aptos/e2e/cases/account.py
crates/aptos/e2e/cases/init.py
crates/aptos/e2e/common.py
crates/aptos/e2e/local_testnet.py
crates/aptos/e2e/main.py
crates/aptos/e2e/test_helpers.py

This PR adds a framework for running aptos CLI tests and a few tests to boot. See the comment in main.py for more information on how this works.
This is pretty custom, we could look at using some existing framework if anyone has something to suggest.
```
python3 main.py -d --base-network mainnet --test-cli-tag mainnet_0431e2251d0b42920d89a52c63439f7b9eda6ac3
```
This will result in output like this:
```
$ ls -1aR /tmp/aptos-cli-tests
.
..
.aptos
out
/tmp/aptos-cli-tests/.aptos:
.
..
config.yaml
/tmp/aptos-cli-tests/out:
.
..
test_account_create.command
test_account_create.stderr
test_account_create.stdout
test_account_fund_with_faucet.command
test_account_fund_with_faucet.stderr
test_account_fund_with_faucet.stdout
test_init.command
test_init.stderr
test_init.stdout
```
I also tested the …

Add framework for CLI tests

---

crates/aptos/src/stake/mod.rs
crates/aptos/src/test/mod.rs
testsuite/smoke-test/src/aptos_cli/validator.rs

aptos stake withdraw-stake currently only supports the classic stake contract, and not staking_contract (where operator and commission are involved).
Unit and manual tests

[CLI][Staking] Add support for withdrawing from a staking contract

---

developer-docs-site/src/theme/DocItem/Footer/index.js

The trailing slash (which sometimes gets added on initial page load) caused the authors not to be found.
Tested that both https://deploy-preview-6094--aptos-developer-docs.netlify.app/nodes/local-testnet/local-testnet-index/ and https://deploy-preview-6094--aptos-developer-docs.netlify.app/nodes/local-testnet/local-testnet-index work correctly.

Remove trailing slash from URL path if it exists.

---

.github/workflows/docker-build-test.yaml
.github/workflows/lint-test.yaml
Cargo.lock
aptos-node/Cargo.toml
aptos-node/src/lib.rs
aptos-node/src/storage.rs
execution/executor/Cargo.toml
execution/executor/src/chunk_executor.rs
execution/executor/src/components/chunk_output.rs
execution/executor/src/tests/chunk_executor_tests.rs
execution/executor/src/tests/mod.rs
execution/executor/tests/db_bootstrapper_test.rs
execution/executor/tests/storage_integration_test.rs
mempool/Cargo.toml
mempool/src/shared_mempool/tasks.rs
storage/aptosdb/Cargo.toml
storage/aptosdb/src/fake_aptosdb.rs
storage/aptosdb/src/lib.rs
storage/backup/backup-cli/src/backup_types/tests.rs
testsuite/forge-cli/src/main.rs
testsuite/forge/src/backend/k8s/cluster_helper.rs
testsuite/forge/src/backend/local/cargo.rs
testsuite/smoke-test/src/consensus/consensus_only.rs
testsuite/smoke-test/src/consensus/mod.rs
testsuite/smoke-test/src/txn_emitter.rs
testsuite/testcases/src/load_vs_perf_benchmark.rs

This PR enables running aptos-node in consensus-only mode by disabling execution and parts of mempool transaction validation features and by faking database calls. This is useful for evaluating the performance of the consensus stack individually in forge, and is not for *production use*. The change is feature-gated across multiple crates, such that without the feature enabled, the change is a no-op and should not affect **production binary** in any way.
Below is the description of changes per component. Each one of the change is gated behind a feature flag that should be enabled.
* Consensus: No change to how consensus communicates with the rest of the system
* Execution: Only the genesis block is executed on the VM while for other blocks an empty WriteSet is returned.
* Storage: …

[aptos-node] Enable consensus-only aptos-node for forge tests

---

docker/rust-all.Dockerfile
terraform/aptos-node/aws/kubernetes.tf
terraform/aptos-node/azure/kubernetes.tf
terraform/aptos-node/gcp/kubernetes.tf
terraform/helm/aptos-node/templates/fullnode.yaml
terraform/helm/aptos-node/templates/validator.yaml
terraform/helm/aptos-node/values.yaml
testsuite/forge.py
testsuite/forge/src/backend/k8s/cluster_helper.rs
testsuite/forge/src/backend/k8s/helm-values/aptos-node-default-values.yaml
testsuite/forge/src/backend/k8s/mod.rs

Installs `pyroscope` on each of the `validator-testing` images and wraps the `aptos-node` binary exec call with it. A few tweaks to get this to work:
* Always run Forge as privileged
* Each cluster needs a secret to connect to pyroscope. For Forge, we guarantee it in the `default` namespace, and then it is copied over to the test namespace. Otherwise, it can be configured.
* Forge copies the pyroscope secret from a known location (`default` namespace) to its own testing namespace so all validators/fullnodes can be profiled individually
* The pyroscope app will be named `aptos-node.${NAMESPACE}.${POD_NAME}`, such as `aptos-node.forge-e2e-pr-6083.aptos-node-7-validator-0`
Run Forge and check the pretty stuff

[helm/docker] enable pyroscope profiling on forge

---

crates/aptos-rosetta-cli/src/construction.rs
crates/aptos-rosetta/src/client.rs
crates/aptos-rosetta/src/construction.rs
crates/aptos-rosetta/src/types/objects.rs
testsuite/smoke-test/src/rosetta.rs

Commission percentage was hardcoded to 0, this lets it be variable.
E2E test covers this, it's optional, so it won't do anything if not provided.

[rosetta] Allow commission percentage to be adjustable

---

.github/workflows/verify-on-chain-modules-mainnet.yaml
.github/workflows/verify-on-chain-modules-testnet.yaml

Adjust the machine type for verify module task. The previous machine don't have enough memory and would OOM after a few minutes of execution.
Manually trigger the job.

[CI] Adjust machine type used for verify module

---

.cargo/config.toml

The linker has to be set for the stack size in Windows, and by default it's set to 1MB, which is too small for the Move compiler.  More info
here: https://users.rust-lang.org/t/stack-overflow-when-compiling-on-windows-10/50818/6
Ran with a Windows VM, didn't get any out of memory errors
https://github.com/aptos-labs/aptos-core/issues/5474

[cargo] Change stack size to 8MB on Windows

---

developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md

This PR updates the docs for running a node via source (or docker). Specifically, it makes the warning about downloading the correct waypoint and genesis a little more obvious. A few users have run into this.

[Docs] Provide a bigger warning around network types.

---

terraform/aptos-node-testnet/addons.tf
terraform/aptos-node-testnet/main.tf
terraform/aptos-node-testnet/variables.tf
terraform/aptos-node/aws/kubernetes.tf
terraform/aptos-node/gcp/kubernetes.tf

Change the functionality of `var.manage_via_tf` to still trigger helm updates when relevant TF variables are updated. It now only toggles the inclusion of the `chart_sha1` helm value that we use to force helm chart update.
If any of the built-in/derived or user-specified helm values change, the `helm_release` resource will be updated. All these changes should be either (1) rare or (2) user-triggered
Bonus: `var.validator_image_tag` lets you specify image tags for validator/fullnode workloads separately from `var.image_tag`, e.g. to use `var.validator_image_tag = performance_<REV>`, and `var.image_tag = <REV>`
Apply some different scenarios we expect testnet operators to be in:
* update `var.chain_id`
* update `var.image_tag`
* update `var.era`
* update `var.num_validators`
* update …

[tf] manage_via_tf triggers chart_sha1

---

terraform/aptos-node/gcp/cluster.tf
terraform/aptos-node/gcp/variables.tf
terraform/fullnode/gcp/cluster.tf
terraform/fullnode/gcp/variables.tf

Enables pulling the many images into a k8s host. Useful for systems like Forge, which pulls many images, as well as enabling backup-restore, which uses the `tools` image (which is really big).
Note that this does not make the default disk size larger, as that would trigger re-provisioning nodes and could result in some downtime for existing deployments. We can consider bumping this in a later PR though (e.g. to enable backup-restore for all clusters, not just PFNs), once we make it clear the immediate consequences. 
apply

 [tf/gcp] option to increase GKE node disk size

---

aptos-move/aptos-gas/src/aptos_framework.rs
aptos-move/aptos-gas/src/gas_meter.rs

There was a previous attempt (https://github.com/aptos-labs/aptos-core/commit/57294de2ce700faefaff508373eb181de52dbdc3) to fix the incorrect gas feature version for this native function, but even that number was too low.

[gas] fix incorrect gas feature version for hash.blake2b_256

---

api/test-context/src/test_context.rs
execution/executor/src/tests/mod.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/utils/iterators.rs
storage/backup/backup-cli/src/coordinators/restore.rs
testsuite/smoke-test/src/state_sync.rs
testsuite/smoke-test/src/storage.rs
testsuite/smoke-test/src/test_utils.rs

At lower traffic, we enlarged the number of txns in each txn backup, hence it's likely that one txn backup now crosses multiple epoch boundaries, which exposes a bad edge case of the `db-restore auto` command where there are epoch endings in the txn backup after the state snapshot version selected -- and those epoch ending are missing in the restored DB.
The fix is (according to the latest spirit of the tool), we don't replay additional txns after the recovered state snapshot.
smoke-test is updated to verify the breakage (with added checks in the code) and the fix.
smoke-test updated

[backup] fix that db-restore can create db will missing LedgerInfos at the tail of history

---

crates/aptos/homebrew/README.md
crates/aptos/homebrew/aptos.rb

With this you can now install the aptos-cli via
```
brew install aptos
```
Details on how to modify the code and get started are located in the README.md
Will probably need input from @clay-aptos on how to update the docs accordingly
(Formula is still updating on their website, but it works)
https://user-images.githubusercontent.com/31301117/211170806-370de772-089e-49c3-8a68-545f04d64586.mov

Aptos CLI Homebrew and README.md

---

developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-aws.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-azure.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-gcp.md

This is relevant to https://github.com/aptos-labs/aptos-core/issues/5508. While it's not recommended/common for node operators to be wiping their storage, this doc change clarifies a quirk with our k8s setup.
If operators wipe their storage on k8s changing the `era`, they must also check if there are any dangling volumes from previous eras and delete them accordingly. Otherwise, their costs might stack up.

[docs] add a note on dangling volumes after changing era

---

crates/aptos/homebrew/README.md
crates/aptos/homebrew/aptos.rb

Docs and Formula were updated to use cli release bash script. This dramatically reduces the binary size for release builds that are stored on homebrew and makes them in-line with the compiled binaries on the releases tab of aptos-core. 
Running e2e tests yields
```bash
2023-01-10 18:34:40,206 - INFO - Running aptos CLI local testnet from image: aptoslabs/tools:devnet
2023-01-10 18:34:40,206 - INFO - Waiting for node and faucet APIs for aptos-tools-devnet to come up
2023-01-10 18:34:56,387 - INFO - Node and faucet APIs for aptos-tools-devnet came up
2023-01-10 18:34:56,394 - INFO - Running test: test_init
2023-01-10 18:34:57,804 - INFO - Test passed: test_init
2023-01-10 18:34:57,806 - INFO - Running test: test_account_fund_with_faucet
2023-01-10 18:34:59,416 - INFO - Test passed: …
```

Updating homebrew docs and formula

---

Cargo.lock
Cargo.toml
aptos-move/aptos-vm-profiling/src/profile_aptos_vm.rs
aptos-move/aptos-vm/src/move_vm_ext/vm.rs
crates/crash-handler/Cargo.toml
crates/crash-handler/src/lib.rs

Update the commit hash for Move repo and made crash handler skip the error coming from move-bytecode-verifer.
Had a one-off rust test to make sure the rust thread_local primitive will behave as expected. We've already test the panic behavior in https://github.com/move-language/move/pull/750

[crash-handler] Ignore crashed from verifier

---

Cargo.lock
Cargo.toml
aptos-move/aptos-vm/src/move_vm_ext/vm.rs
crates/indexer/src/util.rs

This updates the commit hash from the [aptos-v1.2.0](https://github.com/move-language/move/commit/318fe9b3314d88aabc3fe641033dad06aaee7c14) branch

Update commit hash from aptos-v1.2.0

---

aptos-move/framework/aptos-framework/doc/vesting.md
aptos-move/framework/aptos-framework/sources/vesting.move

This is a bug in the outstanding rewards calculation of the vesting contract. Every time staking_contract::request_commission is called, it updates the principal to the total active stake - commission paid out. Since the vesting contract relies on this staking contract's principal to calculate accumulated rewards (to be sent out to shareholders), request_commission, when call before vesting::unlock_rewards, effectively locks up this accumulated rewards for the vesting contract's entire vesting schedule.
The correct accumulated rewards calculation for vesting::unlock_rewards should use the vesting contract's remaining grant as the base to get the actual amount of accumulated rewards so far.
A newly added unit test that succeeds with the fix but fails otherwise.

[Aptos Framework][Vesting] Pay out the accumulated rewards relatively to vesting's remaining grant instead of staking contract's principal

---

aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/framework/src/module_metadata.rs

This feature flag seems to guard also usage of u256.

[aptos-vm] Guard usage of new metadata by VM_BINARY_FORMNAT_V6 feature fkag

---

aptos-move/aptos-vm/src/move_vm_ext/vm.rs

Set newly introduced flags in `VerifierConfig` to None to avoid potential back-compatibility issue

Set new fields to None

---

.github/workflows/lint-test.yaml

The consensus-only feature changes are not picked into all the production branches yet, so it fails on other branches providing a false negative signal even though it does not block merging. 
This PR changes it such that it is only enabled if a particular label is set. This label matches the label used for building the consensus-only images.
Wait for CI.

[gh-workflow] invoke consensus-only-unit-test job on label

---

aptos-move/aptos-vm/src/move_vm_ext/vm.rs

As we did for aptos-node-v1.2.0 in #6181 , set the values for the new limits to be None.
NA

[move-vm] Reset verifier config to none

---

docker/rust-all.Dockerfile

Quick fix to docker build on testnet branch.
context: https://aptos-org.slack.com/archives/C037JDQJAQG/p1673649882442679?thread_ts=1673639771.403529&cid=C037JDQJAQG

hotfix: remove rust_demangler cp from docker build due it breaking build

---

crates/indexer/migrations/2022-12-29-222902_curr_table_items/down.sql
crates/indexer/migrations/2022-12-29-222902_curr_table_items/up.sql
crates/indexer/src/models/coin_models/coin_activities.rs
crates/indexer/src/models/events.rs
crates/indexer/src/models/move_tables.rs
crates/indexer/src/models/token_models/token_activities.rs
crates/indexer/src/models/write_set_changes.rs
crates/indexer/src/processors/coin_processor.rs
crates/indexer/src/processors/default_processor.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/schema.rs

* Added current_table_items table to be exposed via graphql
* Added event_index in several tables: events, token_activities, and coin_activities. This index represents the order in which the event is logged so sorting by transaction_version and event_index will be the best way to display events in the correct ordering moving forward. 
Tested in devnet and testnet
current_table_items
events
token_activities
coin_activities

Add current_table_items and event index. Also clean up some code in default_processor

---

aptos-move/framework/aptos-framework/doc/aptos_account.md
aptos-move/framework/aptos-framework/sources/aptos_account.move
testsuite/smoke-test/src/rosetta.rs

Resource accounts might not be registered to receive APT. aptos_account::transfer would error out for them. This updates aptos_account::transfer to implicitly register the recipient for APT if needed. 
A general side effect of implicit registration is that users can now send coins to reserved account - 0x1, 0x2, ..., 0xa. This is fine and in general a way to "burn" coins.
Unit tests

[Aptos Framework] Update aptos_account::transfer to do implicit registering of APT if necessary

---

aptos-node/src/lib.rs
aptos-node/src/services.rs
config/src/config/logger_config.rs
config/src/config/mod.rs
config/src/config/network_config.rs
config/src/config/storage_config.rs

Mainly fixing typo for aptos-node and config package
A short explanation for `config/src/config/mod.rs`
1. `network.load_fullnode_network` will check whether it is a `validator`, so the `invariant` check is not needed.
2. Add each `network_id` to the `network_ids` seems to be useless.
cargo test

Some codes cleanup for aptos-node & config

---

.github/workflows/lint-test.yaml
crates/aptos/src/move_tool/mod.rs
crates/aptos/src/test/mod.rs

Currently, if you have warnings in your move project, running `aptos move test` will not run tests until your fix the warnings, this PR adds a new flag `--ignore-compile-warnings` for `aptos move test` which skips this behavior.

[CLI] Flag to skip warnings while running tests.

---

developer-docs-site/docs/index.md

Add Aptos Docs GitHub project to Aptos.dev home page

---

aptos-move/framework/aptos-framework/doc/vesting.md
aptos-move/framework/aptos-framework/sources/vesting.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs

In reality we often want to call these functions for multiple contracts all at once. This helps with that without having to use multiple txns / a script function.
For now just this:
```
aptos move compile
```
Not sure what we normally do for aptos-framework, though this feels quite simple. I'll ask around.

Add `*_many` versions of functions to vesting module

---

Cargo.lock
aptos-move/aptos-release-builder/Cargo.toml
aptos-move/aptos-release-builder/src/components/consensus_config.rs
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-release-builder/src/components/framework.rs
aptos-move/aptos-release-builder/src/components/gas.rs
aptos-move/aptos-release-builder/src/components/mod.rs
aptos-move/aptos-release-builder/src/components/version.rs
aptos-move/aptos-release-builder/src/utils.rs
aptos-move/framework/aptos-framework/sources/aptos_governance.move
aptos-move/framework/aptos-framework/sources/voting.move
aptos-move/framework/src/release_bundle.rs
crates/aptos/src/governance/mod.rs
crates/aptos/src/test/mod.rs
testsuite/forge/src/interface/aptos.rs
testsuite/smoke-test/src/aptos_cli/mod.rs
testsuite/smoke-test/src/aptos_cli/validator.rs
testsuite/smoke-test/src/upgrade.rs
testsuite/smoke-test/src/upgrade_multi_step_test_metadata.txt

This PR is part of multi-step governance proposal work. In this PR, we
- added e2e and unit tests to test out the multi-step governance proposal flow e2e;
- added CLI support for (1) submitting multi-step proposal and (2) generating execution hash for a script. 
Tests 
- Added a smoke test `test_upgrade_flow_multi_step()` in [testsuite/smoke-test/src/upgrade.rs](https://github.com/aptos-labs/aptos-core/blob/54015d0199fc0b5215f757c149134ef658859492/testsuite/smoke-test/src/upgrade.rs)
- Added two unit tests to test on-chain update of `next_execution_hash` in [voting.move](https://github.com/aptos-labs/aptos-core/blob/54015d0199fc0b5215f757c149134ef658859492/aptos-move/framework/aptos-framework/sources/voting.move) and [aptos_governance.move](https://github.com/aptos-labs/aptos-core/blob/540 …

[testsuite] CLI & smoke test for multi-step governance proposal 

---

consensus/src/counters.rs
consensus/src/liveness/leader_reputation.rs

PR adds metrics to emit status for each peer for consensus participation. This metric is emitted from each peer - so even if at least one node in the network is up, we will continue getting this data. The downside however is that the O(N2) number of series are emitted but this is okay because we don't have more than 100 nodes in testnet or mainnet. 
Run UTs

[Consensus] Add metrics for per peer consensus participation

---

aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/vm-genesis/src/lib.rs
types/src/on_chain_config/aptos_features.rs

Enables a few cryptography related feature flags:
- SHA2-512, SHA3-512 and RIPEMD-160 hash functions
- `aptos_stdlib::type_info::chain_id()` native
- A new V2 MultiEd25519 PK validation native
- Blake2b-256 hash function
@davidiw told me these were never enabled :'-(
Test in production.

enable cryptography features and type_info::chain_id() feature in Move

---

Cargo.lock
api/types/Cargo.toml
api/types/src/convert.rs

Currently if the internal indexer is turned on, parsing tables would cause panics if the handle cannot be found in that internal indexer. This generally is the desired behavior but there is an edge case when we try to simulate a transaction. The table "created" does not get into the internal indexer (since it's not actually created) but when the API is queried, it expects the table to be in the internal indexer, hence the crash. 
The fix is to send a warning when internal indexer cannot find a table handle instead of crashing. 
Manual testing.

[API] avoid API failure for table item deserialization

---

aptos-move/framework/src/aptos.rs
aptos-move/framework/src/built_package.rs
crates/aptos/src/governance/mod.rs
crates/aptos/src/move_tool/mod.rs

Right now the aptos cli didn't forward the file format flag to the release bundle generator, causing the cli to always emit the modules with the latest version of file format.
Manually inspected the generated module to make sure the major version is as expected.

[CLI] Fix file format flag for governance proposal generator

---

mempool/src/shared_mempool/network.rs
network/peer-monitoring-service/server/src/tests.rs
network/src/application/storage.rs
network/src/application/tests.rs
network/src/protocols/health_checker/interface.rs
network/src/protocols/health_checker/mod.rs
network/src/testutils/test_node.rs
state-sync/aptos-data-client/src/aptosnet/tests.rs

Note: this PR doesn't make any logical changes (only refactors).
This PR makes the following small refactors to the networking code:
1. Removes `LockingHashMap<T>` and all uses from the code. `LockingHashMap` is a simple wrapper around a `RwLock<HashMap<T>>`. While nice in theory, it has the following practical downsides: (i) it still has to expose the write lock to clients, which leaks abstractions; (ii) it performs unnecessary data copying (e.g., where a simple iterator through the hashmap would be cheaper than copying the entire map and returning it); and (iii) it results in another layer of indirection for calling code. Given that we're wanting to do some major cleanups to the code and reduce complexity, it seems cleaner to remove this entirely.
2. Cleans up some of the health checker …

[Network] Clean up uses of LockingHashmap and the health checker.

---

CODEOWNERS
Cargo.lock
aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/block-executor/Cargo.toml
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/output_delta_resolver.rs
aptos-move/block-executor/src/proptest_types/bencher.rs
aptos-move/block-executor/src/proptest_types/tests.rs
aptos-move/block-executor/src/scheduler.rs
aptos-move/block-executor/src/task.rs
aptos-move/block-executor/src/unit_tests/mod.rs
aptos-move/mvhashmap/Cargo.toml
aptos-move/mvhashmap/src/lib.rs
aptos-move/mvhashmap/src/unit_tests/proptest_types.rs

Another follow-up in the ongoing refactoring stream:
(1) Get rid of ugly process_parallel/sequential_output dispatching.
(2) MVHashMap improvements: 
- track aggregator paths (paths that have had a delta)
- fix the error precedence over delta aggregation. not relevant to the current limited (e.g. total supply) uses, but still.
(3) Make delta resolution an internal implementation detail of block executor
- use the MVHashMap records to avoid traversing all outputs sequentially to find delta paths
In the future, we will do output (& delta, final logging) resolution in parallel by post-processing tasks after we have the rolling commit (@danielxiangzl), but most of the improvements in this PR are useful regardless.
The next follow-up on block-executor will be refactoring prop-tests and adding …

[Parallel Executor] Block executor output and mvhashmap/resolver refactoring

---

developer-docs-site/docs/cli-tools/aptos-cli-tool/index.md
developer-docs-site/docs/cli-tools/build-from-brew.md
developer-docs-site/sidebars.js

Simplify the homebrew instructions.  The README currently linked gives too much information, when this should be dead simple.

[docs] Add dedicated page for brew instructions

---

crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/transaction_generator/account_generator.rs
crates/transaction-emitter-lib/src/transaction_generator/call_custom_modules.rs
crates/transaction-emitter-lib/src/transaction_generator/mod.rs
crates/transaction-emitter-lib/src/transaction_generator/nft_mint_and_transfer.rs
crates/transaction-emitter-lib/src/transaction_generator/p2p_transaction_generator.rs
crates/transaction-emitter-lib/src/transaction_generator/publish_modules.rs
crates/transaction-emitter-lib/src/transaction_generator/publishing/module_simple.rs
crates/transaction-emitter-lib/src/transaction_generator/publishing/publish_util.rs
crates/transaction-emitter-lib/src/transaction_generator/transaction_mix_generator.rs
crates/transaction-emitter-lib/src/wrappers.rs
crates/transaction-emitter/src/diag.rs

Build on top of @dariorussi PR for publishing modules, this adds a generic way to issue transaction from that module (but not load test the module publishing, working set of modules is created in the initialization stage)
Also created TransactionExecutor to wrap submitting and rertrying on the transactions in parallel, and fixed/sped up NFT txn generator with it.
Next PR in the stack will test out using this

Add generic CallCustomModule transaction generator

---

crates/transaction-emitter-lib/src/args.rs
crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/emitter/stats.rs
crates/transaction-emitter-lib/src/emitter/submission_worker.rs
crates/transaction-emitter-lib/src/lib.rs
crates/transaction-emitter-lib/src/transaction_generator/account_generator.rs
crates/transaction-emitter-lib/src/transaction_generator/mod.rs
crates/transaction-emitter-lib/src/transaction_generator/transaction_mix_generator.rs
crates/transaction-emitter-lib/src/wrappers.rs
terraform/helm/node-health-checker/files/nhc_baseline_fullnode.yaml
testsuite/forge-cli/src/main.rs
testsuite/smoke-test/src/consensus/consensus_only.rs
testsuite/smoke-test/src/txn_emitter.rs
testsuite/testcases/src/lib.rs
testsuite/testcases/src/two_traffics_test.rs

Make transaction emitter configuration more powerful:
- Transactions are now parametrized enums, and each contains flags relevant for it.
- additionally add phases support, so that we can run first one workload, then second. This way we can first create bunch of accounts, and then do something with them in the second phase.
run on forge and through txn emitter

Add txn emitter phases and generic configuration

---

developer-docs-site/static/scripts/install_cli.py

Other tools out there (generally package managers, but there is nothing too special about that) often have one-stop install scripts. Even better than the standard two scripts, I saw that Poetry was just doing it all with Python, which I think is a pretty good choice because most people have Python on their system already. So I yanked their install script and adapted it for our needs.
This means you can do this on Unix:
```
curl -s "https://aptos.dev/scripts/install_cli.py" | python
```
Or this on Windows:
```
iwr -uesb "https://aptos.dev/scripts/install_cli.py" | Select-Object -ExpandProperty Content | python
```
There are a couple of action items left that I mention in those PRs, including:
- Test on WSL
- Figure out which of the two Ubuntu packages to install (or fix the OpenSSL …

Add cross platform install script for Aptos CLI

---

developer-docs-site/docs/guides/wallet-standard.md

Now the wallet standard doesn't use "we" as in "Petra".  It also expands a bit on the descriptions and ensures that it references the wallet adapter standard as well.

[docs] Reword Wallet standard to be generic

---

aptos-move/framework/aptos-framework/doc/account.md
aptos-move/framework/aptos-framework/doc/aptos_account.md
aptos-move/framework/aptos-framework/doc/create_signer.md
aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/doc/overview.md
aptos-move/framework/aptos-framework/sources/account.move
aptos-move/framework/aptos-framework/sources/account.spec.move
aptos-move/framework/aptos-framework/sources/aptos_account.move
aptos-move/framework/aptos-framework/sources/create_signer.move
aptos-move/framework/aptos-framework/sources/create_signer.spec.move
aptos-move/framework/aptos-framework/sources/genesis.move
aptos-move/framework/aptos-framework/sources/genesis.spec.move
aptos-move/framework/src/natives/account.rs
aptos-move/framework/src/natives/create_signer.rs
aptos-move/framework/src/natives/mod.rs

we already have 3 places that use create_signer... more are coming in order to support objects and account v2
placing create_signer in account can result in spaghetti code and adds to auditing overhead...
this PR isolates it to a single module
unfortunately due to the way natives / gas work, we can never remove the src/natives/* code related to this, but we need not add any more! unless another address wants access...
Forking this off from the object PR, since it can be landed independently of it...

[framework] make a dedicated module for create_signer

---

Cargo.lock
Cargo.toml
aptos-move/framework/aptos-stdlib/sources/simple_map.move
aptos-move/framework/move-stdlib/doc/fixed_point32.md
aptos-move/framework/move-stdlib/sources/fixed_point32.move
aptos-move/framework/move-stdlib/sources/option.move
aptos-move/framework/move-stdlib/sources/vector.move
aptos-move/framework/move-stdlib/tests/bcs_tests.move
aptos-move/framework/move-stdlib/tests/bit_vector_tests.move
aptos-move/framework/move-stdlib/tests/fixedpoint32_tests.move
aptos-move/framework/move-stdlib/tests/option_tests.move
aptos-move/framework/move-stdlib/tests/string_tests.move
aptos-move/framework/move-stdlib/tests/vector_tests.move
aptos-move/framework/tests/move_unit_test.rs
crates/aptos/src/node/mod.rs
crates/indexer/src/models/coin_models/coin_activities.rs
crates/transaction-emitter/src/diag.rs

This specifically brings the implementation of inline functions and lambdas as part of the compiler in the cli to the newest state. This also aligns move-stdlib sources importing the new functionals and other extensions. The tests for the stdlib had been deactivated before, and needed some adaption to newer standards for reactivation.

[move] Update to the latest Move commit

---

ecosystem/typescript/sdk/package.json

There's an error message below when I use aptos sdk in ESM project.
> There are types at '/node_modules/aptos/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'aptos' library may need to update its package.json or typings.
So I added types field to exports.

[TS SDK] Add types field to avoid any type error on ESM projects

---

Cargo.lock
aptos-move/aptos-debugger/Cargo.toml
aptos-move/aptos-debugger/src/lib.rs
aptos-move/aptos-debugger/src/main.rs
aptos-move/aptos-validator-interface/Cargo.toml
aptos-move/aptos-validator-interface/src/lib.rs
aptos-move/aptos-validator-interface/src/rest_interface.rs
crates/aptos-rest-client/src/lib.rs

Implemented a CLI tool to spawn an aptos vm and re-execute transactions locally providing an remote endpoint. The cli was built on top of `aptos-validator-interface` crate, which implements a `StateView` trait for the json-rpc/db endpoint so that aptos-vm can use either one of those to execute transactions.
This PR also includes a few optimizations and bug fixes to  `aptos-validator-interface`:
1. Added a LRU cache to optimize the query performance
2. Fixed the locking issue when serving concurrent readers.
3. Fixed the bad module fetching logic for rest api endpoint.
4. Add batching logic for the rest endpoint in order to execute a bigger chunk when needed.
In order to try out the tool:
For replaying with local db instance, run `cargo run -p aptos-debugger -- --begin-version …

[aptos-debugger] Implement the CLI interface

---

crates/aptos-build-info/build.rs

This PR adds change detection flags to `aptos-build-info/build.rs` to force run the aptos-build-info's build script on changes to the Git HEAD reference file that indicates changes to the source, build.rs changes, or if the SOURCE_DATE_EPOCH special distribution environment variable changes.
I made three empty amend commits on this branch, and I ran `cargo run -p aptos-node -- --test` and verified that the commit hash changes every time in the build information from the logs.

[build-info] Recompute shadow_rs on Git changes

---

testsuite/smoke-test/src/upgrade.rs

Previous upgrade flow test is now flaky because the CLI will by default fetch the aptos framework from main and the recent inline feature is causing old move compiler to panic. 
Tested `test_upgrade_flow`

[smoke-test] Fix flaky test for upgrade flow

---

Cargo.lock
storage/aptosdb/Cargo.toml
storage/aptosdb/src/state_store/buffered_state.rs
storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
storage/aptosdb/src/state_store/state_snapshot_committer.rs
storage/aptosdb/src/versioned_node_cache.rs

The sync mechanism was introduced in https://github.com/aptos-labs/aptos-core/pull/2783. It is not needed anymore because we now caches nodes in memory from previous batches before they get committed to DB.

[Storage] Make the state commit to be fully async.

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_init_module_failed/Move.toml
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_init_module_failed/sources/test.move
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_init_module_second_attempt/Move.toml
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_init_module_second_attempt/sources/test.move
aptos-move/e2e-move-tests/src/tests/code_publishing.rs

Apply hotfix from v1.1.4 to 1.2.2

[VM] Update execution logic to invalidate loader cache upon all partial errors when there's a code publish

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_init_module_failed/Move.toml
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_init_module_failed/sources/test.move
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_init_module_second_attempt/Move.toml
aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_init_module_second_attempt/sources/test.move
aptos-move/e2e-move-tests/src/tests/code_publishing.rs

VM's loader cache is not properly flushed when a code publish fails either during init_module execution or later steps (e.g. in success_cleanup). This means re-attempts of publishing the same module (not upgrade because earlier attempts failed) would still use the loaded code from the failed attempts.
This PR addresses this by properly invalidating the loader cache further up the stack to account for all possible failures.
E2E test that tries to upload the same module twice (first attempt always fails).
Without the fix, the second attempt would also fail because the same init_module from the first attempt lingers around in the loader cache and is used.
With the fix, the second attempt succeeds (loader cache is cleared and new init_module logic is used).

[VM] Invalidate loader cache upon all failures if a newly published module is loaded

---

aptos-move/framework/aptos-stdlib/doc/simple_map.md
aptos-move/framework/aptos-stdlib/doc/table.md
aptos-move/framework/aptos-stdlib/doc/table_with_length.md
aptos-move/framework/aptos-stdlib/sources/simple_map.move
aptos-move/framework/aptos-stdlib/sources/table.move
aptos-move/framework/aptos-stdlib/sources/table_with_length.move
aptos-move/move-examples/data_structures/sources/big_vector.move
aptos-move/move-examples/data_structures/sources/bucket_table.move
aptos-move/move-examples/data_structures/sources/iterable_table.move
aptos-move/move-examples/data_structures/sources/smart_vector.move

As discussed. Let's remove unnecessary abilities.
tldr:
1. We remove `store` ability constraint on most data structures including simple_map to enable ephemeral usage of those structs. For example, then you can create a temporary simple_map to dedup (K, V)s where K or V is not `store`.
2. We remove the unnecessary generic constraint on all methods except for the constructor such as what we did for table is. This is to make it more consistent with the pattern on other data structures where we don't annotate type arguments with constraints if not needed since constructor functions will enforce that anyway. We want to stress this will be a pattern that we will follow along the way.
cargo test

[framework] remove unnecessary abilities

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/lib.rs
crates/aptos/src/update/helpers.rs
crates/aptos/src/update/mod.rs
crates/aptos/src/update/tool.rs

This adds to the CLI the ability to update itself.
First, I changed the version of the CLI in Cargo.toml from 1.0.4 to 1.0.3 to make the CLI think it needs to update itself:
```
$ cargo build-p aptos
$ mv target/debug/aptos /tmp/aptos
$ /tmp/aptos --version
aptos 1.0.3
```
Next, run the self update subcommand:
```
$ /tmp/aptos -- update
Checking target-arch... MacOSX-x86_64
Checking current version... v1.0.3
Looking for tag: aptos-cli-v1.0.4
aptos release status:
* Current exe: "/Users/dport/a/core/target/debug/aptos"
* New exe release: "aptos-cli-1.0.4-MacOSX-x86_64.zip"
* New exe download url: "https://api.github.com/repos/aptos-labs/aptos-core/releases/assets/91367154"
The new release will be downloaded/extracted and the existing binary will be replaced.
Do you want to continue? [Y/n] …
```

Add ability to self update to aptos CLI

---

Cargo.lock
crates/node-resource-metrics/Cargo.toml
crates/node-resource-metrics/src/collectors/basic_node_info_collector.rs
crates/node-resource-metrics/src/collectors/cpu_metrics_collector.rs
crates/node-resource-metrics/src/collectors/mod.rs
crates/node-resource-metrics/src/lib.rs

This will help us map peer_id to hostname as well as gives us release split information in real-time.
Existing UTs

[Monitoring] Emit prometheus metrics for hostname and git sha

---

developer-docs-site/docusaurus.config.js

This PR adds the new "Build E2E Dapp on Aptos" tutorial to the top nav menu under "Build Apps"

add e2e dapp tutorial to top menu

---

.github/actions/docker-buildx-setup/action.yaml

Following incident and discussion from last week. Synced from upstream https://github.com/docker/setup-buildx-action/issues/190#issuecomment-1408660839
NOTE: this will soon be migrated out of this repo to: https://github.com/aptos-labs/actions/pull/1
Docker build works

[gha] pin setup-buildx-action to v2.4.0

---

terraform/helm/vector-log-agent/files/vector-config.yaml
terraform/helm/vector-log-agent/values.yaml

The issue is described in https://github.com/vectordotdev/vector/issues/12014
Redeploy shows logs coming back in, but that's expected even without the fix. We can monitor the log volume over the next few days.

[helm][vector-log-agent] fix k8s log drop issue

---

crates/aptos-telemetry-service/src/auth.rs
crates/aptos-telemetry-service/src/context.rs
crates/aptos-telemetry-service/src/lib.rs
crates/aptos-telemetry-service/src/prometheus_push_metrics.rs
crates/aptos-telemetry-service/src/tests/test_context.rs
crates/aptos-telemetry-service/src/types/mod.rs

This PR enables the telemetry service to accept prometheus metrics from any Aptos Node, either Validator or Full Node, even if they are not whitelisted or not part of the validator set. The service will categorize any node that is able to authenticate via handshake with the service as either `UnknownValidator` or `UnknownFullNode` based on what the node identifies itself as during the authentication. 
To prevent any adverse behavior from accepting metrics from untrusted sources, these metrics will be emitted to a separate configurable destination. 
As part of the change, I also cleaned up some metrics related configuration, streamlined how metrics urls and secrets are defined as part of the telemetry service config.
Also, cleans up certain hacks that was implemented for premainnet to …

[telemetry-svc] Ingest metrics from unknown nodes

---

Cargo.lock
aptos-move/aptos-debugger/Cargo.toml
aptos-move/aptos-debugger/src/lib.rs
aptos-move/aptos-validator-interface/Cargo.toml
aptos-move/aptos-validator-interface/src/lib.rs
aptos-move/aptos-validator-interface/src/rest_interface.rs
aptos-move/aptos-validator-interface/src/storage_interface.rs

To detect backward compatibility issues.
running
```
./aptos-debugger.main --limit 1 --begin-version 417354092 rest https://testnet.aptoslabs.com/v1
```
gives me
```
Mismatch: ver:417354093 status:Keep(MoveAbort { location: 0000000000000000000000000000000000000000000000000000000000000001::coin, code: 65542, info: None }) on_chain:Keep(MoveAbort { location: 0000000000000000000000000000000000000000000000000000000000000001::coin, code: 65542, info: Some(AbortInfo { reason_name: "EINSUFFICIENT_BALANCE", description: "Not enough coins to complete transaction" }) })
```

[aptos-debugger] detect execution result mismatch vs onchain result

---

consensus/src/counters.rs
consensus/src/epoch_manager.rs

Currently, the voting power metric is emitted just for own host, which makes it unreliable, when a node is down. This change emits the voting power for all nodes in the validator set, so we get these metrics as long as one node is up and running.  This creates some overhead of duplicate time series but given this is a critical metric and is currently unreliable, this is worth the additional overhead. 
Existing UTs

[Consensus] Emit voting power metrics for all peers instead of just own

---

crates/aptos/src/update/helpers.rs
developer-docs-site/static/scripts/install_cli.py

You know how sometimes you think "this might be an issue" but then do nothing about it and then it turns out to be an issue? Well that's what happened here.
The problem is the "latest" tag points to the latest release of any description, but these tools just blindly look at the latest release. This PR makes it filter through the tags to look for the latest CLI release only.
Installation script:
```
$ python3 install_cli.py
Latest CLI release: 1.0.4
Currently installed CLI: 1.0.4
The latest version (1.0.4) is already installed.
```
Self update:
```
$ cargo build -p aptos
$ cp target/debug/aptos
$ /tmp/aptos update
{
"Result": "CLI already up to date (v1.0.4)"
}
```

Make CLI installation / self updating lookup latest CLI release correctly

---

crates/aptos/src/common/init.rs

We can do this now that the testnet faucet is captcha free.
```
cd aptos-move/move-examples/hello_blockchain/
~/a/core/target/debug/aptos init 
Account 7aaafbea10f1ffe9d957953102b040939add4d40d6ffff41da0dd0c371901c92 doesn't exist, creating it and funding it with 100000000 Octas
Account 7aaafbea10f1ffe9d957953102b040939add4d40d6ffff41da0dd0c371901c92 funded successfully
---
Aptos CLI is now set up for account 7aaafbea10f1ffe9d957953102b040939add4d40d6ffff41da0dd0c371901c92 as profile default!  Run `aptos --help` for more information about commands
{
"Result": "Success"
}
```
```
$ ~/a/core/target/debug/aptos account list | grep value
"value": "100000000"
```

[CLI] Add support for now-public testnet faucet

---

ecosystem/node-checker/src/provider/helpers.rs

`cargo test -p aptos-node-checker --doc` is broken.
cargo test -p aptos-node-checker --doc

[fix] fix node_checker_lib helpers

---

aptos-move/e2e-move-tests/src/tests/attributes.rs
aptos-move/framework/src/module_metadata.rs

This switches the representation for know attribute kind from u16 to u8 to maintain compatibility with the current testnet behavior.

[module metadata] use u8 instead of u16 to represent known attribute kind

---

aptos-move/framework/src/module_metadata.rs

0 is legacy view function due to older compilers

Fix metadata parsing with older compilers

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/governance/mod.rs
crates/aptos/src/move_tool/mod.rs

* Bytecode version fixed for scripts
* Removed w as shorthand for ignore warnings

[cli] Release for 1.0.5

---

developer-docs-site/docs/nodes/full-node/run-a-fullnode-on-gcp.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-aws.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-azure.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-gcp.md

Terraform 1.3.6 is needed to run through steps now, so it might as well be updated.
I was running through this tutorial directly, and it wouldn't let me use a version less than this for devnet

[docs] Update GCP to 1.3.6 Terraform

---

.github/actions/fullnode-sync/README
.github/actions/fullnode-sync/action.yaml
.github/actions/fullnode-sync/fullnode_sync.py
.github/workflows/fullnode-execute-devnet-main.yaml
.github/workflows/fullnode-fast-mainnet-main.yaml
.github/workflows/fullnode-fast-testnet-main.yaml
.github/workflows/fullnode-intelligent-devnet-main.yaml
.github/workflows/fullnode-output-mainnet-main.yaml

This PR adds nightly Github action workflows to verify fullnode health. Specifically, we add the following workflows:
1. Start a node using the `main` branch, connect it to `devnet` and verify it can sync using execution syncing.
2. Start a node using the `main` branch, connect it to `testnet` and verify it can sync using fast syncing.
3. Start a node using the `main` branch, connect it to `mainnet` and verify it can sync using output syncing.
4. Start a node using the `main` branch, connect it to `mainnet` and verify it can sync using fast syncing.
5. Start a node using the `main` branch, connect it to `devnet` and verify it can sync using intelligent syncing mode.
The workflows will spawn and monitor the node and wait for it to sync to a target version (where the target is the latest …

[Github Actions] Add new workflows for fullnode syncing.

---

crates/aptos/src/governance/mod.rs
crates/aptos/src/move_tool/mod.rs

The current move compile command doesn't let you also compile a script by itself.  This adds the functionality, and gives the hash of the bytecode for convenience.
```
./target/debug/aptos move compile-script --package-dir aptos-move/move-examples/scripts/two_by_two_transfer/
BUILDING TwoByTwoTransfer
{
"Result": {
"script_location": "aptos-move/move-examples/scripts/two_by_two_transfer/script.mv",
"script_hash": "79a45944e000a09a40983ada600a061daf861955747c1e37035cc551187af932"
}
}
```

[cli] Add compile script command

---

crates/aptos-build-info/build.rs

With #6348 , `aptos-build-info` ended up compiling with every change, increasing build times by recompiling the crate and a long list of dependencies, even if git reference did not change. The change did not actually trigger with changes to `.git/HEAD` changes because the `rerun-if-changed` path is relative to where `build.rs` is located. Moreover, the `cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH` does not seem useful.
This PR fixes the path so that `rerun-if-changed` is triggered properly. 
Made sure the crate only compiles when `.git/HEAD` is touched.

[build-info][bugfix] trigger shadow-rs on git ref change

---

crates/aptos-telemetry-service/src/context.rs
crates/aptos-telemetry-service/src/errors.rs
crates/aptos-telemetry-service/src/lib.rs
crates/aptos-telemetry-service/src/tests/auth_test.rs
crates/aptos-telemetry-service/src/tests/test_context.rs
crates/aptos-telemetry-service/src/types/mod.rs
crates/aptos-telemetry-service/src/validator_cache.rs

Currently, telemetry service config `trusted_full_node_addresses` maps chain ID as key to full node address and asserts that the chain ID provided by the node matches the key. This causes friction for devnet releases because its chain ID changes for each release and increasing deployment burden.
Instead, this PR changes the mapping such that it maps common chain name (e.g. devnet, mainnet, testnet) to full node address and trusts the chain ID provided by the full node. We already trust the full node's validator set, so we can also trust it for the chain ID.

[telemetry-service] use common names for chain full node mapping

---

Cargo.lock
aptos-move/aptos-release-builder/Cargo.toml
aptos-move/aptos-release-builder/data/example.yaml
aptos-move/aptos-release-builder/src/components/consensus_config.rs
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-release-builder/src/components/framework.rs
aptos-move/aptos-release-builder/src/components/mod.rs
testsuite/smoke-test/src/upgrade.rs

Cherrypick the fix from v.1.2.0 to main. The biggest change is to add an option for the framework release to force cli to compile the framework at a given bytecode version to avoid release framework at a newer unexpected bytecode version.
Original PR is #6248.
Updated the example config via
`cargo run -p aptos-release-builder -- write-default --output-path aptos-move/aptos-release-builder/data/example.yaml`
And generated the scripts via
`cargo run -p aptos-release-builder -- generate-proposals --release-config aptos-move/aptos-release-builder/data/example.yaml  --output-dir ~/release`
And manually inspected the generated scripts to verify that the modules are indeed emitted at file format version 5.

[release-tooling] Fix release tooling for 1.2.0

---

storage/backup/backup-cli/src/metadata/cache.rs
testsuite/smoke-test/src/storage.rs

There's a race condition between the backup coordinator and the process to pull the backup storage state, where they both see a completely empty metadata folder and try to create the "identity" metadata.
This is to fix a flaky smoke test

fix flaky test_db_restore: avoid race to initialize backup store

---

.github/actions/fullnode-sync/fullnode_sync.py
.github/workflows/fullnode-execute-devnet-main.yaml
.github/workflows/fullnode-fast-mainnet-main.yaml
.github/workflows/fullnode-fast-testnet-main.yaml
.github/workflows/fullnode-intelligent-devnet-main.yaml
.github/workflows/fullnode-output-mainnet-main.yaml

This PR adds slack support to the fullnode nightly jobs, such that if a job fails, we should see a notification in slack.

[Nightly] Add slack support to fullnode jobs.

---

.github/actions/fullnode-sync/fullnode_sync.py
.github/workflows/fullnode-execute-devnet-stable.yaml
.github/workflows/fullnode-fast-mainnet-stable.yaml
.github/workflows/fullnode-fast-testnet-stable.yaml

This PR adds 3 final fullnode sync tests to ensure no breakages occur in any of our stable networks and releases:
1. Start a node using the `devnet` branch, connect it to `devnet` and verify it can sync using execution syncing from genesis.
2. Start a node using the `testnet` branch, connect it to `testnet` and verify it can sync using fast syncing (and tail the blockchain using execution syncing).
3. Start a node using the `mainnet` branch, connect it to `mainnet` and verify it can sync using fast syncing (and tail the blockchain using execution syncing).
Note: once these all land, we could probably clean things up a little regarding duplication, etc.

[Workflows] Add 3 more fullnode sync tests for stable builds.

---

consensus/src/payload_manager.rs
consensus/src/state_computer.rs

These warnings have been here for a long time. I'll open an issue to clean these up later.
```
cargo run -p aptos-node
```

Silence dead code warnings in consensus

---

consensus/src/experimental/buffer_manager.rs

Minor change to add basic information like author and commit info to the error message. 
Existing UTs

[Consensus] Add more information to commit mismatch message

---

.cargo/config.toml

This will significantly improve RocksDB performance (when DB is getting enough load and becomes the bottleneck) since it provides CRC32 instructions.
The graph shows the JMT node reading latency before and after the change, on a 600M items DB, doing account creation by a fake executor that simulates read/write.

[Performance] Enable sse4.2.

---

crates/aptos-logger/src/aptos_logger.rs

If running concurrently, the setting of env and reading race.
To reproduce, can run 
`aptos-logger git:(main) cargo test test_logger_`
a few times.

[Logger] combine two tests that flake when running concurrently

---

Cargo.lock
crates/aptos-telemetry-service/Cargo.toml
crates/aptos-telemetry-service/src/auth.rs
crates/aptos-telemetry-service/src/clients/humio.rs
crates/aptos-telemetry-service/src/jwt_auth.rs
crates/aptos-telemetry-service/src/log_ingest.rs
crates/aptos-telemetry-service/src/prometheus_push_metrics.rs
crates/aptos-telemetry-service/src/remote_config.rs
crates/aptos-telemetry-service/src/tests/auth_test.rs
crates/aptos-telemetry-service/src/tests/custom_event.rs
crates/aptos-telemetry-service/src/types/auth.rs
crates/aptos-telemetry-service/src/types/mod.rs
crates/aptos-telemetry/src/sender.rs

This PR adds support to identify multiple (concurrent) runs of aptos-node with the same identity config (i.e. peer id, chain, etc). It is accomplished by generating a UUID every time a node boots up and using that UUID as part of authentication with the telemetry service. The telemetry service will include embed UUID into logs, events, and metrics so it is easily accessible.
Backwards Compatibility: A nil UUID will be generated at the telemetry service to maintain backwards compatibility until all nodes are upgraded.

[telemetry-svc] Ability to identify nodes with duplicate identity

---

Cargo.lock
Cargo.toml
aptos-node/Cargo.toml
aptos-node/src/lib.rs
crates/aptos-logger/Cargo.toml
crates/aptos-logger/src/aptos_logger.rs
crates/aptos-node-identity/Cargo.toml
crates/aptos-node-identity/src/lib.rs

This PR adds Peer ID as a field to each log entry. It does so by introducing a new crate `aptos-node-identity` that acts as a global object to provide this information to callers using a `static OnceCell` variable. The variable is initialized from `aptos-node` via the `init()` method. It has as few internal dependencies as possible to avoid any possible cyclic dependency errors. It also separates initializing chain_id from peer_id, because the latter is available at node boot, while the former is only available later after DB bootstrap. To add to the log entry, a new `peer_id` Entry field is introduced, which is populated by calling the new crate. 
`RUST_LOG_FORMAT=json cargo run -p aptos-node -- --test`

[aptos-logger] Add Peer ID and Chain ID as a field to each log entry

---

aptos-move/aptos-validator-interface/src/storage_interface.rs

So it works even if the state tree is pruned (but the ledger is not)
`aptos-debugger --begin-version 4 --limit 1 db ~/work/testnet-fullnode/data/db`

aptos-debugger: trivial: use non-proved state access version

---

testsuite/smoke-test/src/aptos_cli/validator.rs
testsuite/smoke-test/src/client.rs
testsuite/smoke-test/src/consensus/consensusdb_recovery.rs
testsuite/smoke-test/src/full_nodes.rs
testsuite/smoke-test/src/fullnode.rs
testsuite/smoke-test/src/genesis.rs
testsuite/smoke-test/src/network.rs
testsuite/smoke-test/src/state_sync.rs
testsuite/smoke-test/src/storage.rs
testsuite/smoke-test/src/test_smoke_tests.rs
testsuite/smoke-test/src/test_utils.rs
testsuite/smoke-test/src/txn_broadcast.rs

This PR bumps the timeout durations for the smoke tests when bringing nodes online, waiting for connectivity and waiting for healthy nodes. It also defines constants for these which will make life easier if we need to bump and/or modify them.

[Smoke test] Bump the timeout durations for smoke tests.

---

.github/actions/replay-verify/action.yaml
.github/workflows/replay-verify-testnet.yaml
aptos-move/aptos-debugger/src/lib.rs
execution/executor-types/src/executed_chunk.rs
execution/executor-types/src/lib.rs
execution/executor-types/src/parsed_transaction_output.rs
execution/executor/src/chunk_executor.rs
execution/executor/src/tests/mod.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/lru_node_cache.rs
storage/aptosdb/src/pruner/db_sub_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner_manager.rs
storage/aptosdb/src/pruner/ledger_pruner_worker.rs
storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
storage/aptosdb/src/pruner/pruner_manager.rs
storage/aptosdb/src/pruner/state_store/state_value_pruner.rs
storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/versioned_node_cache.rs
storage/backup/backup-cli/src/backup_types/tests.rs
storage/backup/backup-cli/src/backup_types/transaction/restore.rs
storage/backup/backup-cli/src/backup_types/transaction/tests.rs
storage/backup/backup-cli/src/bin/db-restore.rs
storage/backup/backup-cli/src/bin/replay-verify.rs
storage/backup/backup-cli/src/coordinators/replay_verify.rs
storage/backup/backup-cli/src/coordinators/restore.rs
storage/backup/backup-cli/src/coordinators/verify.rs
types/src/transaction/mod.rs

1. db-restore doesn't go through the VM, which will make it faster
2. replay-verify has --lazy-quit option which will list out all execution problems and quit with an error in the end.
existing UTs and manually played with the CLI

[replay-verify] add lazy-quit mode which prints out all violations

---

execution/executor-types/src/lib.rs
state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs

Note: nothing changes in this PR.
This PR makes some small cleans up to the state sync storage synchronizer:
1. Wraps the `execute_chunk` call in a `spawn_blocking` wrapper. This was missed by an old PR: https://github.com/aptos-labs/aptos-core/pull/3494
2. Extracts the `spawn_blocking` behaviour to helper functions to improve readability.

[State Sync] Small cleanups to the storage synchronizer.

---

state-sync/storage-service/server/src/tests.rs

This PR bumps the storage service timeout in the storage service unit tests. We're seeing a very rare rate of flakes, so let's bump the timeout. If flakes still continue, I'll dig.

[State Sync] Bump timeout in flaky test.

---

aptos-move/framework/aptos-stdlib/doc/hash.md
aptos-move/framework/aptos-stdlib/sources/hash.move

Dots at the end of URL are breaking the links.

[docs] fix broken URLs due to dot at the end

---

aptos-move/aptos-vm/src/verifier/view_function.rs

unfortunately, some functions were compiled and published with an older compiler on a more permissive metadata check. As a result, there are some modules that have view function at 0 and not 1. The existing check for view functions only allowed for them to be called if they were at 1. This allows anything considered to be a view function to be called.

[aptos-vm] change restriction on view functions to support legacy view

---

api/src/tests/transactions_test.rs

The plan is to 
1. clean up ModuleBundle in transaction_tests.rs since it's no longer used in code. 
- remove the tests that no longer use
- add tests to make sure we still cover all scenarios
2. use the right publish flow to cover the tests with [publish_package()](https://github.com/aptos-labs/aptos-core/blob/f582c24cc4034613f5554cafa3f38344c0cff25a/api/src/tests/resource_groups.rs#L153)
In this PR I delete two ignored tests that not used anymore. Those two scenarios are covered by other tests
**test_signing_message_with_module_payload** covered by **test_signing_message_with_payload** 
**test_get_txn_execute_failed_by_invalid_module_payload_bytecode** covered by **test_get_txn_execute_failed_by_invalid_script_payload_bytecode**
cargo test to make sure all tests are working.

[transaction test] remove two tests using module payload

---

ecosystem/typescript/sdk/src/transaction_builder/builder_utils.ts

If method contains array (ie `code::publish_package_txn`), when we send array argument from browser to wallet extension to sign and submit. Transaction should sign and submit successfully, but it throw `Invalid vector args` instead. 
`instanceof Array` doesn't work properly if array was created from different context, this is known issue. (https://www.samanthaming.com/tidbits/63-better-array-check-with-array-isarray/)
NOTE: this problem doesn't happen in nodejs, because array was created and check from the same js context.
Try publish code using `code::publish_package_txn` from browser and sign with wallet extension.

Fix when passing array to wallet extension, array cannot be detected using instanceof

---

aptos-move/aptos-vm/src/verifier/view_function.rs

unfortunately, some functions were compiled and published with an older compiler on a more permissive metadata check. As a result, there are some modules that have view function at 0 and not 1. The existing check for view functions only allowed for them to be called if they were at 1. This allows anything considered to be a view function to be called.

[aptos-vm] change restriction on view functions to support legacy view (1.2.0 hotfix)

---

crates/aptos-telemetry-service/src/context.rs
crates/aptos-telemetry-service/src/custom_event.rs
crates/aptos-telemetry-service/src/errors.rs
crates/aptos-telemetry-service/src/lib.rs
crates/aptos-telemetry-service/src/log_ingest.rs
crates/aptos-telemetry-service/src/tests/test_context.rs
crates/aptos-telemetry/src/sender.rs

This PR introduces the ability to ingest logs from all aptos-nodes even though their identity is not on chain. The service exposes the ability to configure the backend for known and unknown logs individually, so that unknown logs can be kept separate from known ones.
Ran an Aptos full node locally and was able to send logs to log service.

[telemetry-svc] Ingest logs from unknown nodes

---

.github/actions/fullnode-sync/fullnode_sync.py
.github/workflows/fullnode-execute-devnet-main.yaml
.github/workflows/fullnode-execute-devnet-stable.yaml
.github/workflows/fullnode-fast-mainnet-main.yaml
.github/workflows/fullnode-fast-mainnet-stable.yaml
.github/workflows/fullnode-fast-testnet-main.yaml
.github/workflows/fullnode-fast-testnet-stable.yaml
.github/workflows/fullnode-intelligent-devnet-main.yaml
.github/workflows/fullnode-output-mainnet-main.yaml
.github/workflows/run-forge.yaml
.github/workflows/run-fullnode-sync.yaml

This PR makes the following small improvements to the fullnode sync workflows:
1. Updates the fullnode sync python script to track the node syncing progress via the metrics port instead of the REST API. This allows the script to be more accurate and avoid the limitations in the REST API regarding syncing versions and states.
2. Removes the duplication between the various fullnode workflow files by introducing a new unified workflow file that individual test instances call.
3. Simplifies the slack message logic for displaying failures (e.g., see the comment here https://github.com/aptos-labs/aptos-core/pull/6443 by @ibalajiarun) 😄 

[Workflows] Some improvements to the fullnode sync workflows.

---

state-sync/storage-service/server/Cargo.toml
state-sync/storage-service/server/src/lib.rs
state-sync/storage-service/server/src/logging.rs
state-sync/storage-service/server/src/tests.rs

This PR makes three small changes:
1. Changes an `error!` log to `warn!` when the storage service encounters an error (e.g., due to an invalid request).
2. Handles a small edge case where clients might send invalid subscription requests that do not respect epoch boundaries (because the client is not aware of the epoch change yet). In these cases, we simply drop the request (as opposed to trying to handle it and returning an error).
3. Adds 2 new unit tests to verify basic behaviour of the subscription task.

[State Sync] Provide better support for invalid requests.

---

crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/emitter/transaction_executor.rs
crates/transaction-emitter-lib/src/transaction_generator/mod.rs

Improved minting for graceful test from 40minutes to 120s.
- organizing all initialization in the RestApiTransactionExecutor class, made it so that transactions from same sender were going to a different rest endpoint, causing them to be parked
- plan for huge number of accounts was imbalanced - 180000 accounts via only 100 seed accounts, each doing 1800. split the stages into more balanced - 425 seed accounts with 424 accounts each
- increased parallelism to utilize larger TPS for initialization
- increased fee to use for initialization in TwoTraffic test
Before:
```
2023-02-03 23:39:17.862	Account creation plan created for 180000 accounts with 5555600055555 balance each.
2023-02-03 23:39:17.862	    through 100 seed accounts with 10003682099999000 each, each to fund 1800 accounts …
```

[txn emitter] Improve minting speed and more debug details

---

crates/aptos-logger/src/tracing_adapter.rs

With this PR, we will include source path in the logs from crates that log using the `tracing` crate. 
The aptos-logger subscribes to tracing events from crates that log using the `tracing` crate (e.g. move-vm) and logs those events. This change populates the source path field of the logger from the event trace metadata. 
N/A

[aptos-logger][tracing] add source path to log metadata

---

testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs

Main was broken because of changes in #6497 and #6055 which landed 'simultaneously'
CICD

[build fix] One-liner fix to unbreak main

---

.github/actions/replay-verify/action.yaml
.github/actions/verify-modules/action.yaml
.github/workflows/lint-test.yaml
.github/workflows/replay-verify-mainnet.yaml
.github/workflows/replay-verify-testnet.yaml
.github/workflows/verify-on-chain-modules-mainnet.yaml
.github/workflows/verify-on-chain-modules-testnet.yaml

`verify-modules` and `replay-verify` composite actions now take in `GIT_CREDENTIALS`, which is used by cargo  to pull in dependencies. Since `rust-setup` is run within these other composite actions, the `GIT_CREDENTIALS` input needs to be propagated down from caller > `verify-modules`/`replay-verify` > `rust-setup`
This also needs to be included in https://github.com/aptos-labs/aptos-core/pull/6435
mainnet module verify is triggered on PR that touches the workflow file. Ensure that the workflow run that is triggered includes the git credentials setup

[gha] use git credentials for verify jobs

---

state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/db_pruner.rs
storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
storage/aptosdb/src/pruner/state_store/mod.rs
testsuite/forge/src/backend/local/node.rs
testsuite/smoke-test/src/state_sync.rs

Also fixed a bug that we mistakenly used the SchemaBatch for ledger db to prune genesis in state merkle db.

Update pruner progress after fast sync is done.

---

Cargo.lock
aptos-move/aptos-release-builder/Cargo.toml
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-release-builder/src/components/mod.rs
aptos-move/aptos-release-builder/src/lib.rs
aptos-move/aptos-release-builder/src/main.rs
aptos-move/aptos-release-builder/src/validate.rs
crates/aptos/src/governance/mod.rs
testsuite/smoke-test/Cargo.toml
testsuite/smoke-test/src/upgrade.rs

Create a new `validate-proposal` command such that the release tooling will:
1. Generate the scripts 
2. Send the scripts to a local testnet
3. Execute and compare if all the config flags are being set properly.
Specifically, it will follow the governance proposal / multi-step governance proposal process for the local network, so that we will be able to simulate how the real network could potentially react to the upgrade.
To try out the command:
- Spawn a local testnet via: `cargo run --bin aptos -- node run-local-testnet --with-faucet --seed 0000000000000000000000000000000000000000000000000000000000000000 --assume-yes`
- Validate the proposal via `cargo run -p aptos-release-builder -- validate-proposals --release-config aptos-move/aptos-release-builder/data/example.yaml --test-dir …

[aptos-release-builder] Add an option to validate the release process

---

aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move
crates/aptos-rest-client/src/lib.rs
crates/aptos/src/common/types.rs
crates/aptos/src/move_tool/mod.rs
crates/aptos/src/test/tests.rs

Adds view function support to the CLI, tested with adding to hello blockchain
```
aptos move view --function-id devnet::message::get_message --profile devnet --args address:devnet
{
"Result": [
"ViewFunctions!"
]
}
aptos move run  --function-id devnet::message::set_message --profile devnet --args "string:I can use view functions"
Do you want to submit a transaction for a range of [41200 - 61800] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
"Result": {
"transaction_hash": "0xf04af6810f40b3b6ba6de5445c9c7896c4fad12ef09aa523c3d2c1c7839e7702",
"gas_used": 412,
"sender": "b11affd5c514bb969e988710ef57813d9556cc1e3fe6dc9aa6a82b56aee53d98",
"sequence_number": 3,
"timestamp_us": 1675409546603551,
"version": 9800433,
"vm_status": "Executed …
```

[cli] Add view function support

---

consensus/src/quorum_store/tests/batch_store_test.rs

Flaking with log messages like
```
--- TRY 4 STDERR:        aptos-consensus quorum_store::tests::batch_store_test::test_batch_store_recovery ---
thread 'quorum_store::tests::batch_store_test::test_batch_store_recovery' panicked at 'QuorumstoreDB open failed; unable to continue: IO error: lock hold by current process, acquire time 1676282739 acquiring thread 149771: 
/tmp/eb53042e829fdcb82884b45d8807d41a/quorumstoreDB/LOCK: No locks available', consensus/src/quorum_store/quorum_store_db.rs:38:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

[Quorum Store] Ignore a flaky test which is preventing some PRs landing

---

Cargo.lock
crates/aptos-network-checker/src/args.rs
crates/aptos-network-checker/src/check_endpoint.rs
crates/aptos-network-checker/src/lib.rs
crates/aptos/Cargo.toml
crates/aptos/src/node/mod.rs
crates/aptos/src/test/tests.rs
types/src/chain_id.rs

This PR adds a new `check-network-connectivity` command to the Aptos CLI. This is useful for testing network connections to Aptos nodes by performing a noise handshake with the node. For example, this run verifies that we can connect to a VFN in testnet:
```
% cargo run -p aptos -- node check-network-connectivity --address "/ip4/34.70.116.169/tcp/6182/noise-ik/0x249f3301db104705652e0a0c471b46d13172b2baf14e31f007413f3baee46b0c/handshake/0" --chain-id testnet
...
{
"Result": "Successfully connected to /ip4/34.70.116.169/tcp/6182/noise-ik/0x249f3301db104705652e0a0c471b46d13172b2baf14e31f007413f3baee46b0c/handshake/0"
}
```
New unit tests have been added. Also, I verified the behaviour manually. For example, giving the tool the wrong chain ID:
```
% cargo run -p aptos -- node …
```

[Aptos CLI] Added simple CLI command to check the network.

---

.github/workflows/replay-verify.yaml

The cron trigger was accidentally removed. Add it back as `0 19 * * *`, which will run at 11AM PST
We can now trigger it manually: https://github.com/aptos-labs/aptos-core/actions/runs/4176814975
https://github.com/aptos-labs/aptos-core/actions/workflows/workflow-run-replay-verify.yaml 
Triggered testnet replay manually on the latest `main` at the time: `7fb9071ea877e5ddfe6e21bc546d478c3e7c2dfb`, using workflow specs from `main`.
We can also run the same workflow via:
```
gh workflow run replay-verify.yaml --ref main \
-F=GIT_SHA=7fb9071ea877e5ddfe6e21bc546d478c3e7c2dfb \
-F=BUCKET=aptos-testnet-backup-2223d95b \
-F=SUB_DIR=e1 -F=HISTORY_START=250000000 \
-F=TXNS_TO_SKIP="46874937 151020059 409163615 409163669 409163708 409163774 409163845 409163955 409164059 409164191 414625832" \ …
```

[gha] replay-verify on cadence

---

.github/workflows/run-fullnode-sync.yaml
config/src/config/quorum_store_config.rs
consensus/src/quorum_store/batch_generator.rs
testsuite/forge-cli/src/README.md

This PR makes several tiny tweaks:
1. Updates the `aptos-forge-cli` README.
3. Changes the machine running the fullnode-sync jobs (this matches the specs that are publicly defined). 
4. Updates a variable in the QS config to `u64` from `u128` (required because there's some limitations around logging and u128 -- more testing is required). But, @bchocho confirmed this can be `u64`, so doing the lazy thing 😄 

[Tweaks] Small tweaks to README, configs and GHA.

---

.github/workflows/forge-stable.yaml
testsuite/find_latest_image.py
testsuite/forge.py

fix the forge stable issue where it can't find the failpoints build https://github.com/aptos-labs/aptos-core/actions/runs/4172126738
also start to abstract in some places image tag --> build variant
check the test run in `determine-test-metadata`
https://github.com/aptos-labs/aptos-core/actions/runs/4181370693/jobs/7243247681
log snippet from run:
```
Finding latest image with build variants: ['failpoints']
With prefixes: ['failpoints_']
Found latest images: ['failpoints_a4e24eace8204f9ae[16](https://github.com/aptos-labs/aptos-core/actions/runs/4181370693/jobs/7243247681#step:6:17)b329b5f419bcac20501ad']
Exporting latest image as base GIT_SHA: a4e24eace8204f9ae16b329b5f419bcac20501ad
```

[testsuite] find latest image variants

---

.github/workflows/forge-stable.yaml

separate cadence from `main` that runs the same suite of stable forge tests against the new `quorum-store` branch
check the test determine-test-metadata job. Then, we include this in the `quorum-store` branch

[gha] run forge stable against quorum-store branch

---

testsuite/forge.py
testsuite/forge_test.py

image finding logic broke for when we're trying to find more than 1 image, which only affects the compat test, since we need the 2 latest images.
existing and new unit tests
also check compat test works on this PR

[forge] fix compat test image find

---

types/src/on_chain_config/consensus_config.rs

So continuous forge runs will always run with quorum store enabled.

[TEST BRANCH ONLY] hard code quorum store enabled in onchain config

---

.github/workflows/docker-build-test.yaml
.github/workflows/forge-stable.yaml
testsuite/find_latest_image.py

so we can start battle-testing `quorum-store` branch:
(1) build on push to branch. important as this branch drifts from main
(2) once image is built, continous stable forge test will use the latest images from the branch for testing nightly
forge stable `determine-test-metadata` test finds a valid `IMAGE_TAG` to test. On `workflow_dispatch`, we can manually specify it. Anywhere else, it will crawl the git history of the current checkout.

[gha] build on push to quorum-store branch and make IMAGE_TAG optional

---

consensus/src/lib.rs
consensus/src/quorum_store/batch_aggregator.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/quorum_store_db.rs
consensus/src/quorum_store/tests/batch_aggregator_test.rs
consensus/src/quorum_store/tests/batch_generator_test.rs
consensus/src/quorum_store/tests/proof_coordinator_test.rs
consensus/src/quorum_store/tests/quorum_store_db_test.rs
consensus/src/quorum_store/tests/types_test.rs
consensus/src/quorum_store/types.rs
consensus/src/quorum_store/utils.rs
testsuite/generate-format/tests/staged/consensus.yaml
testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs

Introduce a nonce into BatchId. If a validator restarts with a fresh DB, the change in nonce indicates that the id will start back at 0, and other validators will accept the new batches.
Without this, a validator with a wiped DB would timeout all batches until it reached the previous batch ID.
Add smoke test for both when DB exists on restart and when it is wiped on restart. The latter failed before this change.

[Quorum Store] Allow batches even if a validator restarts with a fresh DB

---

.github/workflows/forge-stable.yaml
Cargo.lock
Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service/README.md
ecosystem/indexer-grpc/indexer-grpc-data-service/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/processor.rs
ecosystem/indexer-grpc/indexer-grpc-utils/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs

* Context
[Design doc](https://docs.google.com/document/d/1E3J1qVwrpVWuRaJL-aAzq5fh5W-9ecbFf5e7GfQhs7E/edit#heading=h.562elfcgz0d3)
* Content
This PR creates a data service that fetch data from cache and file store if cache is not available. 
* If cache is not ready, wait for 1 sec and retry;
* If connection is closed, retry;
**Open item**
* Should verify the chain id for each batch for verification purpose;
* Add back-pressure to the streaming in case of server OOM;
* Metrics
* Use YAML file instead of env var.
* Staleness check, including stale file store/cache/data service: for internal ones(file store/cache), emit metrics/alerts;
for external ones(data service), notify them with RPC status.
Run
```
REDIS_ADDRESS=127.0.0.1 \
CHAIN_NAME=devnet \
GRPC_ADDRESS=0.0.0.0:50052 \ …
```

[indexer grpc][4/n] Indexer grpc data service 0.1

---

api/src/tests/mod.rs
api/src/tests/modules.rs
api/src/tests/move/pack_abi/Move.toml
api/src/tests/move/pack_abi/sources/test.move
api/src/tests/resource_groups.rs
api/types/src/move_types.rs

The ABI currently returned by /modules doesn't include private entry functions in exposed_functions. It should as private entry functions are callable by entry func transactions.
Newly added API test

[API] Include private entry functions returned in ABI's exposed functions

---

crates/crash-handler/src/lib.rs

Ignore the move deserializer error as well cuz we've already set up the catch unwind handler there as well.
Not sure what's the best way to test it.

[panic] Supress panics from move deserializer

---

developer-docs-site/docs/guides/state-sync.md

This PR provides a quick start tip for state sync configuration. Some users in discord have asked for a cheat sheet like this. It also provides a step a forward for https://github.com/aptos-labs/aptos-core/issues/6308, but doesn't address all use cases 😄 

[Dev Docs] Add a quick start tip for fullnode syncing.

---

docker/build-rust-all.sh
docker/docker-bake-rust-all.hcl
docker/retag-rust-images.sh
docker/rust-all.Dockerfile

* Add a docker image build for `indexer-grpc`, which includes binary:
* `aptos-indexer-grpc-cache-worker`: worker fetches data from fullnode grpc to cache
* `aptos-indexer-grpc-file-store`: worker fetches data from cache to gcs
* `aptos-indexer-grpc-data-service`: service that serves data from cache and gcs. 
Built successfully:

[indexer grpc][docker] add the docker image building script for indexer grpc.

---

testsuite/testcases/src/lib.rs
testsuite/testcases/src/network_bandwidth_test.rs
testsuite/testcases/src/network_loss_test.rs
testsuite/testcases/src/performance_with_fullnode_test.rs
testsuite/testcases/src/three_region_simulation_test.rs
testsuite/testcases/src/twin_validator_test.rs
testsuite/testcases/src/two_traffics_test.rs
testsuite/testcases/src/validator_join_leave_test.rs
testsuite/testcases/src/validator_reboot_stress_test.rs

and to validators otherwise
This is generally always the intention of the test, I thought it was always the default, but isn't. Some test override if needed (or if they override the function, as there is no super in traits in rust)

[forge] Change default to send traffic only to FN (if any are defined)

---

aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/sources/object.spec.move

- This PR fix the broken spec by mocking up the `aptos_framework::object::exists_at`.
- It's because a correct spec is not supported by Prover. This is a TODO and filed as an issue: https://github.com/aptos-labs/aptos-core/issues/6658

[Spec] Fix the broken spec

---

config/src/config/storage_config.rs
execution/executor-benchmark/src/db_generator.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/main.rs
storage/aptosdb/src/db_options.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/state_store/test.rs
storage/aptosdb/src/schema/db_metadata/mod.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/aptosdb/src/test_helper.rs
storage/aptosdb/src/utils/truncation_helper.rs
storage/backup/backup-cli/src/utils/mod.rs

Commit state k/v and the rest of data in parallel in different Rocksdb commits. Add logic at the start to ensure they are consistent.
The change of using a separate database for state k/v is guarded by a config flag, thus without turning on the flag, this just split a commit batch into two batches, and both will still get committed into ledger db.
Pruner is not handled in this PR.
Truncation tool is not handled in this PR.

[Storage][Sharding] Split state k/v commit from ledger db commit.

---

aptos-move/aptos-gas/src/transaction/storage.rs

I don't think the limit was ever triggered, so doesn't matter.
replay-verify to make sure there was no hitorical transaction that was affected by this oversight.
https://github.com/aptos-labs/aptos-core/actions/runs/4198903814

fix that a wrong gas parameter was assumed before feature version 3

---

config/src/config/consensus_config.rs
config/src/config/quorum_store_config.rs
consensus/src/quorum_store/batch_coordinator.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/utils.rs

* We no longer backpressure QS based on consensus backpressure. It's only based on local batch count.
* [bugfix] backpressure did not work properly if all fragments are end_batch fragments
* [bugfix] count end batch fragment to number of fragments per batch.
* [bugfix] batch builder should end batch if it can no longer accept more transactions when called again.
* Config changes based on results from gas market overload test #6537

[Quorum Store] End batch, backpressure fixes and gas market test configuration

---

aptos-node/src/lib.rs
aptos-node/src/main.rs
config/global-constants/src/lib.rs
config/src/config/api_config.rs
config/src/config/consensus_config.rs
config/src/config/error.rs
config/src/config/execution_config.rs
config/src/config/logger_config.rs
config/src/config/mempool_config.rs
config/src/config/mod.rs
config/src/config/network_config.rs
config/src/config/safety_rules_config.rs
config/src/config/secure_backend_config.rs
config/src/config/state_sync_config.rs
config/src/config/storage_config.rs
config/src/config/test_config.rs
config/src/generator.rs
config/src/keys.rs
config/src/lib.rs
config/src/network_id.rs
config/src/utils.rs

This PR updates the `aptos-node` and `config` directories with shared licenses for rust files that also contain some Meta code.

[Aptos Node + Config] Add shared license to relevant files.

---

mempool/src/core_mempool/index.rs
mempool/src/core_mempool/mempool.rs
mempool/src/core_mempool/mod.rs
mempool/src/core_mempool/transaction.rs
mempool/src/core_mempool/transaction_store.rs
mempool/src/counters.rs
mempool/src/lib.rs
mempool/src/logging.rs
mempool/src/shared_mempool/coordinator.rs
mempool/src/shared_mempool/mod.rs
mempool/src/shared_mempool/network.rs
mempool/src/shared_mempool/runtime.rs
mempool/src/shared_mempool/tasks.rs
mempool/src/shared_mempool/types.rs
mempool/src/tests/common.rs
mempool/src/tests/core_mempool_test.rs
mempool/src/tests/fuzzing.rs
mempool/src/tests/integration_tests.rs
mempool/src/tests/mocks.rs
mempool/src/tests/mod.rs
mempool/src/tests/multi_node_test.rs
mempool/src/tests/node.rs
mempool/src/tests/shared_mempool_test.rs
mempool/src/tests/test_framework.rs

This PR updates the `mempool` directory with shared licenses for rust files that also contain some Meta code.

[Mempool] Add shared license to relevant files.

---

secure/net/src/lib.rs
secure/storage/github/src/lib.rs
secure/storage/src/crypto_kv_storage.rs
secure/storage/src/crypto_storage.rs
secure/storage/src/error.rs
secure/storage/src/github.rs
secure/storage/src/in_memory.rs
secure/storage/src/kv_storage.rs
secure/storage/src/lib.rs
secure/storage/src/namespaced.rs
secure/storage/src/on_disk.rs
secure/storage/src/policy.rs
secure/storage/src/storage.rs
secure/storage/src/tests/github.rs
secure/storage/src/tests/in_memory.rs
secure/storage/src/tests/mod.rs
secure/storage/src/tests/on_disk.rs
secure/storage/src/tests/suite.rs
secure/storage/src/tests/vault.rs
secure/storage/src/vault.rs
secure/storage/vault/src/dev.rs
secure/storage/vault/src/fuzzing.rs
secure/storage/vault/src/lib.rs

This PR updates the `secure` directory with shared licenses for rust files that also contain some Meta code.

[Secure] Add shared license to relevant files.

---

vm-validator/src/lib.rs
vm-validator/src/mocks/mock_vm_validator.rs
vm-validator/src/mocks/mod.rs
vm-validator/src/unit_tests/vm_validator_test.rs
vm-validator/src/vm_validator.rs

This PR updates the `vm-validator` directory with shared licenses for rust files that also contain some Meta code.

[VM Validator] Add shared license to relevant files.

---

terraform/fullnode/gcp/addons.tf

Fixes an error reported by community member that looks like:
```
spec.domains[0] in body should match '^(([a-z0-9]+|[a-z0-9][-a-z0-9]*[a-z0-9])\.)+[a-z][-a-z0-9]*[a-z0-9]$
```
Apply it and check if google ingress stops complaining

[tf/gcp][fullnode] fix trailing dot in GCE ingress domain

---

Cargo.lock
Cargo.toml
crates/aptos/Cargo.toml

Resurrected the awesome debugger feature that move vm once implemented.
To run the debugger, simply do `MOVE_VM_STEP=1 aptos move test`. We can also generate the VM execution trace via `MOVE_VM_TRACE=1`
This is a really awesome feature and maybe we should document it down somewhere. cc @clay-aptos

[aptos] Enable move debugger

---

sdk/src/lib.rs
sdk/src/transaction_builder.rs
sdk/src/types.rs

This PR updates the `sdk` directory with shared licenses for rust files that also contain some Meta code.

[SDK] Add shared license to relevant files.

---

crates/aptos/src/governance/mod.rs

For large transactions such as aptos-framework package upgrade, the script hash needs to be approved to bypass transaction size limit. This is not always done automatically when voting ends (depends on if the last vote brings total yes to > 50%).
This PR adds a CLI that can be used to explicitly approve the execution hash for an approved governance proposal.
Manual tests

[CLI] Add a CLI for explicitly approving execution hash for governance proposals

---

.github/workflows/copy-images-to-dockerhub-nightly.yaml
.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml
.github/workflows/fullnode-execute-devnet-main.yaml
.github/workflows/fullnode-execute-devnet-stable.yaml
.github/workflows/fullnode-fast-mainnet-main.yaml
.github/workflows/fullnode-fast-mainnet-stable.yaml
.github/workflows/fullnode-fast-testnet-main.yaml
.github/workflows/fullnode-fast-testnet-stable.yaml
.github/workflows/fullnode-intelligent-devnet-main.yaml
.github/workflows/fullnode-output-mainnet-main.yaml
.github/workflows/module-verify.yaml
.github/workflows/replay-verify.yaml

The top level `permissions` block will override the default token permissions, which may not work in all cases (e.g. private forks). We need to add back the permissions https://github.com/actions/checkout/issues/254
* Also, pin `check-aptos-core` action to `@main`, rather than using the one in the checkout. This resolves failures like this: https://github.com/aptos-labs/aptos-core/actions/runs/4246942647/jobs/7384389591, which runs Forge on the `quorum-store` branch, which does not have this GHA.
* Also, grant `actions: write` to any workflows that call `check-aptos-core`, since it is needed for the action to cancel the workflow
Test checkout in a private fork. The `determine-test-metadata` job in each `forge-stable` and `forge-unstable` should pass
Also canary the `check-aptos-core` …

[gha] fix permissions for forge and check-aptos-core on forks

---

.github/actions/check-aptos-core/action.yaml

So `gh` CLI can call with the right permissions. Forgot this in https://github.com/aptos-labs/aptos-core/pull/6726
canary in private fork

[gha][check-aptos-core] use GH_TOKEN

---

aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/sources/coin.move

Before:
```
public merge<Ty0>(Arg0: &mut Coin<Ty0>, Arg1: Coin<Ty0>) {
B0:
0: Nop
1: CopyLoc[0](Arg0: &mut Coin<Ty0>)
2: ImmBorrowFieldGeneric[1](Coin.value: u64)
3: ReadRef
4: ImmBorrowLoc[1](Arg1: Coin<Ty0>)
5: ImmBorrowFieldGeneric[1](Coin.value: u64)
6: ReadRef
7: Add
8: MoveLoc[0](Arg0: &mut Coin<Ty0>)
9: MutBorrowFieldGeneric[1](Coin.value: u64)
10: WriteRef
11: MoveLoc[1](Arg1: Coin<Ty0>)
12: UnpackGeneric[1](Coin<Ty0>)
13: Pop
14: Ret
}
```
After:
```
public merge<Ty0>(Arg0: &mut Coin<Ty0>, Arg1: Coin<Ty0>) {
B0:
0: Nop
1: MoveLoc[1](Arg1: Coin<Ty0>)
2: UnpackGeneric[1](Coin<Ty0>)
3: StLoc[2](loc0: u64)
4: CopyLoc[0](Arg0: &mut Coin<Ty0>)
5: ImmBorrowFieldGeneric[1](Coin.value: u64)
6: ReadRef
7: MoveLoc[2](loc0: u64)
8: Add
9: MoveLoc[0](Arg0: &mut Coin<Ty0>)
10: …
```

Function coin::merge of gas cost optimize.

---

scripts/dev_setup.sh

* currently, `protoc-gen-prost` is broken from head; disable it right now since it's dev dependency.
works on a fresh Ubuntu machine

Disable protoc dev dependencies in dev_setup.

---

.github/workflows/workflow-run-forge.yaml

Use the permissions passed in via the workflow that invokes `.github/workflows/workflow-run-forge.yaml`, e.g. `.github/workflows/docker-build-test.yaml`
Forge still works on this PR

[gha] do not add addl permissions in forge reuse workflow

---

.github/mergify.yml

Make the new forge framework upgrade test land-blocking. The test has been running since https://github.com/aptos-labs/aptos-core/pull/6638 landed, but has not been land-blocking
Tests on this PR. Test takes roughly the same amount of time as the rest

[mergify] make framework upgrade test land-blocking

---

.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml
.github/workflows/replay-verify.yaml

Write a job summary to each Forge Stable/Unstable job that includes the branch and image tag, which helps with determining which jobs are for which cadence. On the UI for scheduled workflows, Github will not show the ref it is running, because it only runs on the default `main` branch -- we change the branch based on the cadence via some special workflow logic. This makes it difficult to determine whether the workflow is for `main` or `quorum-store` branch. 
Also, start to run `forge-stable` and `replay-verify` (both testnet and mainnet) against push to new release branches `aptos-release-v*` e.g. #6768 
CI

[gha] forge continuous summary & trigger on release branch push

---

crates/indexer/migrations/2023-02-15-070116_stake_delegation/down.sql
crates/indexer/migrations/2023-02-15-070116_stake_delegation/up.sql
crates/indexer/src/models/stake_models/delegator_activities.rs
crates/indexer/src/models/stake_models/delegator_balances.rs
crates/indexer/src/models/stake_models/mod.rs
crates/indexer/src/models/stake_models/stake_utils.rs
crates/indexer/src/processors/stake_processor.rs
crates/indexer/src/schema.rs

Added 2 tables
* delegated_staking_activities
* gets the pool activities and 0x1 rewards distribute events 
* current_delegator_balances
* gets the delegator - pool - balances combo. Only active shares for now
**delegated_staking_activities**
**current_delegator_balances**

Delegator activities

---

.github/workflows/forge-stable.yaml
.github/workflows/replay-verify.yaml

Run Forge and replay-verify to `aptos-node-v*` branches as well as the newer `aptos-release-v*` branches.
This keeps the support for existing branches

[gha] run on push to aptos-node-v branches

---

.github/workflows/copy-images-to-dockerhub-nightly.yaml
.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml
.github/workflows/fullnode-execute-devnet-main.yaml
.github/workflows/fullnode-execute-devnet-stable.yaml
.github/workflows/fullnode-fast-mainnet-main.yaml
.github/workflows/fullnode-fast-mainnet-stable.yaml
.github/workflows/fullnode-fast-testnet-main.yaml
.github/workflows/fullnode-fast-testnet-stable.yaml
.github/workflows/fullnode-intelligent-devnet-main.yaml
.github/workflows/fullnode-output-mainnet-main.yaml
.github/workflows/replay-verify.yaml

`replay-verify` workflow was not getting triggered on `push`, since the conditional was not updated after https://github.com/aptos-labs/aptos-core/commit/d11074b7bc27edc53ff95885f06a1909243be92f, this fixes that
Also amend the usage of `check-aptos-core` to only  cancel workflows that are scheduled. Workflows should still run on other triggers, such as `workflow_dispatch` and `push` especially
Also stop running fullnode sync workflows on `pull_request`. They can continue to be tested via `schedule` or `workflow_dispatch`. 
CI

[gha] fix replay-verify run on push & only cancel scheduled workflows

---

.github/workflows/docker-build-rosetta.yaml
docker/rosetta/rosetta.Dockerfile
docker/rust-all.Dockerfile

New base image: https://hub.docker.com/layers/library/rust/1.66.1-bullseye/images/sha256-f72949bcf1daf8954c0e0ed8b7e10ac4c641608f6aa5f0ef7c172c49f35bd9b5?context=explore
The toolchain has been updated to 1.66.1, but the docker base image was not been updated
Build on this PR

[docker] update to rust:1.66.1-bullseye

---

Cargo.lock
aptos-move/e2e-move-tests/Cargo.toml
aptos-move/e2e-move-tests/src/tests/transaction_fee.rs

This fixes `test_fee_collection_and_distribution_for_burn_percentages`. The problem with the test was that the rewards per epoch was a hardcoded value, and did not account that distributing fees can break it.
Also added some other improvements: e.g. lazy script building.

[testsuite] Fixed flaky fees distribution test

---

crates/aptos-network-checker/src/check_endpoint.rs
network/builder/src/builder.rs
network/builder/src/dummy.rs
network/src/application/storage.rs
network/src/application/tests.rs
network/src/connectivity_manager/builder.rs
network/src/connectivity_manager/mod.rs
network/src/connectivity_manager/test.rs
network/src/noise/error.rs
network/src/noise/fuzzing.rs
network/src/noise/handshake.rs
network/src/noise/mod.rs
network/src/noise/stream.rs
network/src/peer_manager/builder.rs
network/src/peer_manager/mod.rs
network/src/peer_manager/tests.rs
network/src/testutils/mod.rs
network/src/transport/test.rs

Note: this PR relates to: https://github.com/aptos-labs/aptos-core/issues/6789.
This PR offers a simple refactor for moving the trusted peers into the peers and metadata container. This provides several benefits:
1. It offers better encapsulation: (i) we no longer have to pass around the trusted peers to all objects that require them; and (ii) it is easier to reason about because the trusted peers are now part of a single container.
2. It makes the trusted peers available to the applications, e.g., the peer monitoring service, which is useful for sharing discovery information between nodes.
Note: other than this simple refactor, the network logic should not change in this PR.

[Network] Move trusted peers into peers and metadata.

---

aptos-move/move-examples/data_structures/sources/bucket_table.move
aptos-move/move-examples/data_structures/sources/smart_table.move

Personally I researched again around linear hashing, spiral storage and extendible hashing schemes. And still admit the best option for us is linear hashing. So I made a similar change to `bucket_table` to intelligently set the configurations such as
bucket_size and split_threshold.
Also, add two public functions to change these two values at any time as it does not have to be fixed after creation. Those methods give the users more flexibility to adjust their needs on the fly.
cargo test

[smart_table] refine bucket_table to smart_table

---

.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml

Some formerly "unstable" Forge tests are now stable. Promote them to stable, so that we use their signal for release. They will also be run on the `quorum-store` branch!
Also since the number of stable Forge tests is now 17 (higher than I remember!), we may need to start thinking of separating them out into dedicated workflows based on test type. This is because the maximum number of nested workflows in Github Actions is 20: https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations. We can create workflows such as `forge-stable-chaos`, `forge-stable-changing-quorum`, `forge-stable-performance`, etc to further categorize these tests. For now, I've left some comments to divide the existing tests into rough categories.
Based off of discussion: …

[gha][forge] promote formerly unstable tests to stable

---

consensus/src/quorum_store/counters.rs
consensus/src/quorum_store/utils.rs
mempool/src/core_mempool/transaction_store.rs
types/src/on_chain_config/consensus_config.rs

Add the time it takes proof-of-store to get pulled into a proposed block, and committed.
Fix a couple longstanding issues in mempool metrics:
* CONSENSUS_READY was wrongly including all txns that are checked for processing, rather than only the newly added txns.
Run forge, observe dashboard.

[Quorum Store] add latency metrics for better visibility

---

.github/workflows/experimental-docker-build-test.yaml
.github/workflows/experimental-docker-rust-build.yaml
.github/workflows/workflow-run-forge.yaml
docker/experimental/docker-bake-rust-all.sh

This PR enables the docker experimental build action on each push to the main branch. The built images with have a `experimental` tag prefix and a separate land-blocking forge is run with image produced by the build workflow.
It is not enabled in the PRs yet because if it fails, it might send false-positive signals to PR authors and will add unnecessary friction. 
Test in main.

[Dockerfile] Enable experimental docker build on push to main

---

aptos-node/src/lib.rs

This PR adds a simple `info` log line for the node config and removes the use of `println!`.

[Aptos node] Add simple log line for node config.

---

terraform/aptos-node-testnet/aws/variables.tf
terraform/aptos-node-testnet/gcp/variables.tf
terraform/aptos-node/aws/kubernetes.tf
terraform/aptos-node/aws/variables.tf
terraform/aptos-node/gcp/kubernetes.tf
terraform/aptos-node/gcp/variables.tf
terraform/fullnode/aws/kubernetes.tf
terraform/fullnode/aws/variables.tf
terraform/fullnode/gcp/kubernetes.tf
terraform/fullnode/gcp/variables.tf
terraform/helm/aptos-node/README.md
terraform/helm/aptos-node/templates/fullnode.yaml
terraform/helm/aptos-node/templates/validator.yaml
terraform/helm/aptos-node/values.yaml
terraform/helm/fullnode/README.md
terraform/helm/fullnode/templates/fullnode.yaml
terraform/helm/fullnode/values.yaml

Use the helm `lookup` function (https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) to avoid overwriting the image if `.Values.manageImages = false`. Many complex setups may require helm to do the initial workload setup, but require a separate procedure to handle release rollouts. This is the case with testnets: we want to be able to roll out each validator and fullnode more or less independently, and definitely not all at once, which is what Terraform/helm would do. With this new config flag flipped, this allows the operator to set the validator and fullnode images using a separate process like `kubectl set image`, etc, and then subsequent `helm upgrade` or `terraform apply` will fetch the image set separately, rather than blowing it away with …

[helm][aptos-node/fullnode] use helm lookup to avoid overwriting image tag if specified

---

Cargo.lock
aptos-node/Cargo.toml
aptos-node/src/logger.rs
config/src/config/indexer_config.rs

Mask the password of indexer's database when logging. Resolve issue #6206 .
If the `postgres_uri` has password ,then replace it with `*`.
1. For `printltn`,  implement `Debug` trait manually.
Usage:
https://github.com/aptos-labs/aptos-core/blob/35976bfa00bc06d376285da38739ee86f8a96d75/aptos-node/src/lib.rs#L126
2. for `aptos-logger`, clone `NodeConfig` and change `postgre_uri` of `IndexerConfig` if needed.
Usage: 
https://github.com/aptos-labs/aptos-core/blob/35976bfa00bc06d376285da38739ee86f8a96d75/aptos-node/src/logger.rs#L80
Build `aptos-node`, run with different config, check the output
1. With password
```
Using node config NodeConfig....
, indexer: IndexerConfig { enabled: true, postgres_uri: Some("postgres://postgres:*@localhost:5432/postgres").....}
``` 
``` …
```

mask indexer’s database password when logging

---

.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml

Fix a bug where some Forge tests in both `forge-stable.yaml` and `forge-unstable.yaml` did not have an `IMAGE_TAG` specified, meaning that they would resort to searching the git history of the current checked out branch to find an image tag. While this works for `main` branch, this means that tests on `quorum-store` branch will actually test images from `main` branch in this case.
Also for the `compat` test, the base swarm `IMAGE_TAG = testnet` but set `GIT_SHA` to the correct latest commit with built images on the right branch
@bchocho 's `quorum-store` tests are healthy :p

[gha][forge] specify IMAGE_TAG for all tests

---

docker/rosetta/rosetta.Dockerfile

Looks like some compatibility issues with some build systems for bullseye, so changing back to buster for now.
Autobuild

[rosetta] Change docker to 1.66 buster from bullseye

---

Cargo.lock
Cargo.toml
aptos-move/aptos-gas/src/aptos_framework.rs
aptos-move/aptos-gas/src/table.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/framework/src/natives/mod.rs
aptos-move/framework/src/natives/object.rs

This fixes two gas issues
1. `exists_at` is not charging for loading resources
2. The table natives double charge the base read fee when an item has already been loaded
Note this is a continuation of https://github.com/aptos-labs/aptos-core/pull/6852

[gas] fix gas formulae for exists_at & table natives (load resource) 

---

aptos-move/framework/aptos-framework/doc/account.md
aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/block.md
aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/doc/managed_coin.md
aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/doc/voting.md
aptos-move/framework/aptos-framework/sources/account.spec.move
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/block.spec.move
aptos-move/framework/aptos-framework/sources/coin.spec.move
aptos-move/framework/aptos-framework/sources/managed_coin.spec.move
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
aptos-move/framework/aptos-framework/sources/voting.spec.move

This is a part of spec work for Aptos Framework from MoveBit. The changes are:
- Updated the spec of `account::create_guid()`
- Fixed the specs of all functions that depend on `account::create_guid()`
Tested with move prover.

[Spec] update spec of `account::create_guid()`

---

.github/workflows/copy-images-to-dockerhub-release.yaml
.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml

Various fixes to prepare CI for release 1.3 branch cut. Continuously as well as on push to release branches, we run the following workflows:
* run `replay-verify` on any release branch
* run `forge-stable` on any release branch
* run `docker-build-test` on any release branch
* as well as all other existing tests at PR-time
With Forge tests running from many possible triggers, we need to make sure each test's namespace is unique for each trigger. To solve this, we can just append the image tag under test to the namespace. 
Also for succinctness, rename the `copy-images-to-dockerhub-on-devnet-or-testnet-push.yaml` to `copy-images-to-dockerhub-release.yaml` to note that we're copying images not only on branch push now, but also on tag of `aptos-node-v*`.
CI works on branch cut

[gha] rename dockerhub release workflow & avoid forge preemption

---

.github/workflows/copy-images-to-dockerhub-release.yaml
.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml

* [gha] rename dockerhub release workflow
* [gha][forge] include image tag in namespace to prevent cadence clash

[gha] rename dockerhub release workflow & avoid forge preemption (#6842)

---

.github/workflows/docker-build-test.yaml
testsuite/forge.py

Fix off-by-1 error in Forge pod name creation. Max len is 64 for k8s resources
Also land the preview branch push build, which is in `preview` branch already

[forge] enforce max pod name len

---

ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator.rs

* Improve the cache worker performance by 3000% on GCP. Now TPS is 30k.
Tested on devent

Indexer grpc refactor cache performance

---

developer-docs-site/docs/nodes/node-files-all-networks/node-files.md

On the [Run a Validator Node setup pages](https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-docker) page and similar, you are asked to download docker-compose.yaml and docker-compose-fullnode.yaml from this [nodes file page](https://aptos.dev/nodes/node-files-all-networks/node-files/). If you use the commands on this page how ever, you will end up with only 1 file as the wget for docker-compose-full node overwrites the docker-compose.yaml. Please confirm this isn't intentional
Documentation improvement

Prevent Overwrite of Docker-Compose

---

docker/experimental/builder.Dockerfile
docker/experimental/debian-base.Dockerfile
docker/experimental/docker-bake-rust-all.hcl

This PR does two things: 
- Removes cargo-chef, because there is elaborate `RUN` step caching throughout and cargo-chef is redundant and just adds to build time in worst-case when dependencies change.
- Remove unnecessary path context from tools and node build targets, because it can cause builds to slow down (ref: https://github.com/docker/buildx/issues/1377)
Build works. Will monitor performance after landing.

[Dockerfile][Experimental] Remove cargo-chef

---

.github/workflows/adhoc-forge.yaml

It appears the only way to test a GH workflow is to commit the first version to main, so that GH actions registers it, and then can be invoked referring to changes in another branch via the CLI.
```
gh workflow run adhoc-forge.yaml --ref balaji/gha-consensus-only -f IMAGE_TAG=a8234a8d8bc054d3dcb407a57ebd79fedeea41ef -f FORGE_IMAGE_TAG=a8234a8d8bc054d3dcb407a57ebd79fedeea41ef
```
https://github.com/aptos-labs/aptos-core/actions/runs/4324838075/jobs/7550194841

[GHA][bugfix] Ad-hoc forge workflow

---

Cargo.lock
aptos-node/Cargo.toml
aptos-node/src/services.rs
config/src/config/network_config.rs
config/src/network_id.rs
crates/aptos-id-generator/src/lib.rs
network/peer-monitoring-service/client/Cargo.toml
network/peer-monitoring-service/client/src/error.rs
network/peer-monitoring-service/client/src/lib.rs
network/peer-monitoring-service/client/src/logging.rs
network/peer-monitoring-service/client/src/metrics.rs
network/peer-monitoring-service/client/src/network.rs
network/peer-monitoring-service/client/src/peer_states/key_value.rs
network/peer-monitoring-service/client/src/peer_states/latency_info.rs
network/peer-monitoring-service/client/src/peer_states/mod.rs
network/peer-monitoring-service/client/src/peer_states/network_info.rs
network/peer-monitoring-service/client/src/peer_states/peer_state.rs
network/peer-monitoring-service/client/src/peer_states/request_tracker.rs
network/peer-monitoring-service/server/src/lib.rs
network/peer-monitoring-service/types/src/lib.rs
network/src/application/metadata.rs
network/src/application/storage.rs
network/src/application/tests.rs
state-sync/aptos-data-client/src/aptosnet/state.rs
state-sync/storage-service/client/src/lib.rs
testsuite/smoke-test/src/network.rs
testsuite/smoke-test/src/state_sync.rs

Note:
- The structure of the peer monitoring client is very similar to that of the Aptos Data Client, so 70% of this PR is just boilerplate.
This PR adds a basic framework for the client side of the peer monitoring service. Specifically, it:
- Adds configs for the peer monitoring client. The client is disabled by default.
- Adds a peer monitor loop, which loops over all connected peers and refreshes the state for each peer.
- Adds the state refresher loop, which goes through all types of states and sends out network requests to refresh those states if they're stale. At the moment we only track two state types: (i) latency info; and (ii) network info.
- Adds basic support for structured logging and metrics.
- Adds …

[Network] Add client side of the peer monitoring service.

---

.github/workflows/copy-images-to-dockerhub-release.yaml
.github/workflows/copy-images-to-dockerhub.yaml

* copy images that are built on the `preview` branch to dockerhub (on every push)
* add to `copy-images-to-dockerhub.yaml` the ability to trigger release of any commit's built image via `workflow_dispatch`. this is useful in scenarios where we haven't updated the workflows to trigger on push, so we can release manually in those cases

[gha] copy preview images to dockerhub

---

config/src/config/state_sync_config.rs

This PR updates the output syncing chunk sizes to 5k (to match those of execution syncing).

[State Sync] Update output syncing chunk sizes.

---

terraform/aptos-node/gcp/cluster.tf

Node taint was using the incorrect key.
Tested by spinning up Previewnet.

[TF] Fix Kubernetes node taint on GCP

---

testsuite/forge.py
testsuite/forge_test.py
testsuite/forge_wrapper_core/cluster.py

List job contents so we can get a better picture of how many validators and fullnodes are in each running job.
Specifically, when getting all running Forge jobs, use the `forge-namespace` label to identify the namespace the test is running in, and search all pods in that namespace to determine how many validators and fullnodes are currently running in that namespace. This in conjunction with the Forge dashboards which show the number of active machines provisioned by the autoscaler will give us a better picture of utilization and capacity.
Also add `labels` field to `GetPodsItemMetadata` so we can model the pod better
Unit tests

[forge] list job contents

---

consensus/src/block_storage/sync_manager.rs
consensus/src/state_computer.rs
types/src/block_info.rs

This commit avoids that sync_to races with commit in state computer. previously it'd result in state sync error, with quorum store, it may panic the node because of decreasing round number.

[Previewnet] [cherry-pick] PR 6830: [consensus] better protect sync condition

---

consensus/src/epoch_manager.rs
consensus/src/experimental/ordering_state_computer.rs
consensus/src/quorum_store/batch_reader.rs
consensus/src/sender_aware_shuffler.rs
consensus/src/state_computer.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_state_computer.rs
consensus/src/transaction_shuffler.rs
types/src/on_chain_config/execution_config.rs

[Quorum Store] Implement end_epoch to clear state_computer between epoch end and start (#6889)
We should not be using a stale PayloadManager after epoch end, so adding a end_epoch function that sets the PayloadManager to None.
This fixes a panic that was observed because the stale PayloadManager was still held at StateComputer during sync_to called from initiate_new_epoch. The PayloadManager expects to only see commits from its epoch, which is violated if the epoch change includes multiple epochs.
changing_working_quorum_test (with failpoints) failed with panics. Rerun and observe no panics. TODO (not in this PR): would be nice to have a test that explicitly causes a multiple epoch sync_to from epoch manager.

[Previewnet] [cherry-pick] PR 6889: [Quorum Store] Implement end_epoch to clear state_computer between epoch end and start

---

consensus/Cargo.toml
consensus/src/counters.rs
consensus/src/epoch_manager.rs
consensus/src/experimental/ordering_state_computer.rs
consensus/src/lib.rs
consensus/src/payload_manager.rs
consensus/src/sender_aware_shuffler.rs
consensus/src/state_computer.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_state_computer.rs
consensus/src/transaction_shuffler.rs
execution/executor/src/components/chunk_output.rs
types/src/on_chain_config/execution_config.rs
types/src/on_chain_config/mod.rs

An implementation of transaction shuffler, which tries to spread transactions from same senders in a block in order to reduce conflict. On a high level, it works as follows - It defines a `conflict_window_size`, which maintains a set of senders added to the block in last `conflict_window_size` transactions. When trying to select a new transaction to the block, the shuffler tries to find a transaction which are not part of the conflicting senders in the window. If it does, it adds
the first non-conflicting transaction it finds to the block, if it doesn't then it preserves the order and adds the first transaction in the remaining block. It always maintains the following invariant in terms of ordering 
1. Relative ordering of all transactions from the same before and after shuffling is same …

[BlockSTM] Sender aware transaction shuffling

---

ecosystem/node-checker/configuration_examples/mainnet_fullnode.yaml
ecosystem/node-checker/configuration_examples/testnet_fullnode.yaml

The config we had for devnet was referring to a baseline node that isn't there.
This PR also adds configs for testnet and mainnet.
We're using these in prod.

Update NHC config examples

---

.github/workflows/cli-e2e-tests.yaml
.github/workflows/docker-build-test.yaml
.github/workflows/sdk-release.yaml
crates/aptos/e2e/cases/init.py
crates/aptos/e2e/cases/shared.py
crates/aptos/e2e/common.py
crates/aptos/e2e/local_testnet.py
crates/aptos/e2e/main.py
crates/aptos/e2e/test_helpers.py

In https://github.com/aptos-labs/aptos-core/pull/5946 I added a framework for running CLI tests. This PR configures CI to run those tests. The policy of when it runs is the same as sdk-release.yaml.
Check CI.

Add CI for running Aptos CLI test suite

---

Cargo.lock
crates/aptos-push-metrics/Cargo.toml
crates/aptos-push-metrics/src/lib.rs
execution/executor-benchmark/src/main.rs
storage/backup/backup-cli/src/bin/db-backup-verify.rs
storage/backup/backup-cli/src/bin/db-backup.rs
storage/backup/backup-cli/src/bin/db-restore.rs
storage/db-tool/src/backup.rs
storage/db-tool/src/restore.rs

Will be helpful to get insights from executor benchmark running on laptop. 
Tested by running the benchmark on laptop
```
2023-03-05T00:58:06.877199Z [main] INFO crates/aptos-push-metrics/src/lib.rs:119 Execution dashboard link: https://o11y.aptosdev.com/grafana/d/execution/execution?from=now-5m&to=now&var-Datasource=VictoriaMetrics+Global&var-metrics_source=All&var-chain_name=executor-benchmark&var-cluster=All&var-namespace=1677977886876947000&var-role=All
```

[Executor-benchmark] Add support for pushing metrics to victoriametrics

---

docker/compose/aptos-node/docker-compose-src.yaml
docker/compose/aptos-node/docker-compose.yaml

Port 8180 on machines running docker-compose validator will expose validator REST API via HAProxy. Port 8080 is already the VFN REST API, exposed via a separate HAProxy

[PREVIEWNET ONLY][docker] expose validator REST API

---

terraform/scripts/migrate_cluster_psp_to_pss.sh
terraform/scripts/privileged-psp.yaml

The script `migrate_cluster_psp_to_pss.sh` has two modes of operation:
* check: will check whether there are pods that violate the PSS `baseline` profile. It's useful to see where the security policy can be tightened from the default `privileged` profile.
* migrate: will perform the migration on the current K8s context. `--policy-version` should specify the target policy version, usually the same version as the K8s cluster.
The migration works in two phases:
1. Disabling PodSecurityPolicy
* create an allow-everything security policy
* create a rolebinding that binds each namespace service account to the security policy newly created. this effectively disables the PodSecurityPolicy admission controller
2. Enabling Pod Security Standards
* enforce the "privileged" profile on all namespaces …

[PSS] Add script for migrating a cluster from PSP to PSS

---

ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs

* Now it's `write_resource.data.data` and type information doesn't include in the result data.

[indexer grpc] Move the WriteResource data one-level down. 

---

config/src/config/storage_config.rs
execution/executor-benchmark/src/main.rs
state-sync/storage-service/server/src/lib.rs
state-sync/storage-service/server/src/tests.rs
storage/aptosdb/src/aptosdb_test.rs
storage/aptosdb/src/fake_aptosdb.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/event_store/test.rs
storage/aptosdb/src/pruner/ledger_pruner_manager.rs
storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
storage/aptosdb/src/pruner/ledger_store/mod.rs
storage/aptosdb/src/pruner/ledger_store/version_data_pruner.rs
storage/aptosdb/src/pruner/mod.rs
storage/aptosdb/src/pruner/pruner_utils.rs
storage/aptosdb/src/pruner/state_kv_pruner.rs
storage/aptosdb/src/pruner/state_kv_pruner_manager.rs
storage/aptosdb/src/pruner/state_kv_pruner_worker.rs
storage/aptosdb/src/pruner/state_merkle_pruner_manager.rs
storage/aptosdb/src/pruner/state_merkle_pruner_worker.rs
storage/aptosdb/src/pruner/state_store/mod.rs
storage/aptosdb/src/pruner/state_store/state_value_pruner.rs
storage/aptosdb/src/pruner/state_store/test.rs
storage/aptosdb/src/pruner/transaction_store/test.rs
storage/aptosdb/src/schema/db_metadata/mod.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
storage/storage-interface/src/lib.rs

1. Rename state pruner to state merkle pruner.
2. Split state k/v pruner from ledger pruner.
3. Change StateValueWriter to use state_kv_db.

[Storage][Pruner] Split state k/v pruning to a separate pruner.

---

docker/experimental/docker-bake-rust-all.hcl

#6930 did not upgrade rust version actually, because it did not replace the sha hash. 
Ran the experimental build and made sure it works this time.

[Dockerfile][Experimental][Bugfix] Upgrade rust version

---

consensus/src/consensus_provider.rs
consensus/src/epoch_manager.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/batch_store.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/quorum_store/quorum_store_db.rs
consensus/src/quorum_store/tests/batch_generator_test.rs
consensus/src/quorum_store/tests/quorum_store_db_test.rs
consensus/src/twins/twins_node.rs

Previously, the quorum_store_db instance was torn down and restarted on epoch changes.
We observed this occasionally caused panic when the new instance couldn't start.
The DB doesn't have to be torn down and restarted. The only interesting thing here is the DB
will be created regardless of whether quorum store is turned on, but that should be negligible overhead.
Includes some refactoring to make twins unit tests work.
ref: #6855 
Existing tests

[Quorum Store] Use a single quorum_store_db instance across epochs

---

.github/workflows/cli-e2e-tests.yaml
crates/aptos/e2e/README.md
crates/aptos/e2e/cases/account.py
crates/aptos/e2e/cases/init.py
crates/aptos/e2e/cases/shared.py
crates/aptos/e2e/common.py
crates/aptos/e2e/main.py
crates/aptos/e2e/poetry.lock
crates/aptos/e2e/pyproject.toml
crates/aptos/e2e/test_helpers.py
crates/aptos/e2e/test_results.py

The framework as it was had a design issue where it assumed the test would only ever fail at CLI invocation. This isn't right, since in your test you might want to assert something based on the CLI invocation. In this case you would raise an exception, which would work in that the CLI tests would fail, but the exception would not be caught and the whole framework would exit. Now every test case is wrapped in a decorator where we capture the results of the test and we can present which ones succeeded and which failed at the end of the test suite.
This was originally motivated by the desire to add some more assertions to the existing tests, which I did as part of this PR. To facilitate this I needed the Aptos SDK, so I introduced Poetry like we use elsewhere to manage the deps.
I also …

Improve results capturing, assertions in CLI E2E testing framework

---

config/src/config/mempool_config.rs
mempool/src/core_mempool/index.rs
mempool/src/core_mempool/transaction.rs
mempool/src/core_mempool/transaction_store.rs
mempool/src/counters.rs

Introduces eager expiration, which expires transactions earlier (default: 3s) than its true client-provided expiration. This prevents transactions that are pulled from mempool expiring upon execution, but more importantly it prevents these transactions from blocking transactions that would have succeeded at execution.
Eager expiration is triggered if sufficiently old transactions (default: 10s) are observed. This internally signals to mempool that a backlog is building.
Run an overload test `three_region_simulation_graceful_overload` with quorum store and observe that expirations drop from ~3K/s to < 100/s and this pushes TPS up +15% from 3.8K -> 4.4K

[mempool] eager expiration based on queued transaction age

---

config/src/config/consensus_config.rs
consensus/consensus-types/src/request_response.rs
consensus/src/counters.rs
consensus/src/epoch_manager.rs
consensus/src/liveness/proposal_generator.rs
consensus/src/payload_client.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/direct_mempool_quorum_store.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/tests/batch_generator_test.rs
consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs
consensus/src/quorum_store/tests/proof_manager_test.rs
consensus/src/quorum_store/utils.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_payload_manager.rs
crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
mempool/src/core_mempool/mempool.rs
mempool/src/shared_mempool/tasks.rs
mempool/src/shared_mempool/types.rs
mempool/src/tests/common.rs
mempool/src/tests/core_mempool_test.rs
mempool/src/tests/mocks.rs
mempool/src/tests/multi_node_test.rs
mempool/src/tests/test_framework.rs

Adding two new flags, to improve blockchain performance.
// Whether to create partial blocks when few transactions exist, or empty blocks when there is
// pending ordering, or to wait for quorum_store_poll_count * 30ms to collect transactions for a block
//
// It is more efficient to execute larger blocks, as it creates less overhead. On the other hand
// waiting increases latency (unless we are under high load that added waiting latency
// is compensated by faster execution time). So we want to balance the two, by waiting only
// when we are saturating the execution pipeline:
// - if there are more pending blocks then usual in the execution pipeline,
//   block is going to wait there anyways, so we can wait to create a bigger/more efificent block
// - in case our node is faster than …

[mempool] Wait until max block size or quorum_store_poll_count is reached

---

CONTRIBUTING.md

trivial
(Did the most important changes, the document needs still some revisions)

add origin/upstream remotes, minor edits

---

crates/aptos-rosetta/src/client.rs
crates/aptos-rosetta/src/construction.rs
crates/aptos-rosetta/src/types/misc.rs
crates/aptos-rosetta/src/types/move_types.rs
crates/aptos-rosetta/src/types/objects.rs
testsuite/smoke-test/src/rosetta.rs

This PR adds `distribute` supports in Rosetta to support Unstake. Based on the [description](https://github.com/aptos-labs/aptos-core/commit/4f3f0859dc24a1240d713f1e0505f1391b5f0e14), anyone can trigger the tx, so in the PR we put both operator and staker to the metadata. However this tx involve implicit balance change. The amount can only be determined once tx issued on the blockchain. Wanna see if there is any better way to put balance change in the parsing/construction logic.
Will add smoke test once balance change required in this has been confirmed.

[Rosetta] Add staking_contract distribute implementation

---

consensus/src/counters.rs
consensus/src/liveness/proposal_generator.rs
consensus/src/payload_client.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/counters.rs
crates/aptos-metrics-core/src/avg_counter.rs
crates/aptos-metrics-core/src/lib.rs

Adding AverageIntCounter utility, providing ability to have average chart in Grafana (rate(sum) / rate(count)).
This is basically providing _sum and _count counters from Histogram counter, and no other counters.

AverageIntCounter for backpressure states

---

Cargo.lock
Cargo.toml
aptos-move/aptos-vm-logging/Cargo.toml
aptos-move/aptos-vm-logging/src/counters.rs
aptos-move/aptos-vm-logging/src/lib.rs
aptos-move/aptos-vm-logging/src/log_schema.rs
aptos-move/aptos-vm/Cargo.toml
aptos-move/aptos-vm/src/adapter_common.rs
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
aptos-move/aptos-vm/src/counters.rs
aptos-move/aptos-vm/src/errors.rs
aptos-move/aptos-vm/src/lib.rs
aptos-move/block-executor/Cargo.toml
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/task.rs
aptos-move/block-executor/src/unit_tests/mod.rs
aptos-move/block-executor/src/view.rs
aptos-move/e2e-testsuite/Cargo.toml
aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs
crates/aptos-speculative-state-helper/src/lib.rs

Speculative state helper is a separate (and well-tested) crate now, this integrates into aptos-vm, initializes per every block and flushes at the end of block execution.
speculative logs are cleared on parallel execution abort, and also all logs are cleared during module r/w fallback to sequential execution. 
the drawback of this approach currently, as brought up by @wrwg is that if there are crashes, we may not log some entries stuck in the speculative buffer. I will create a github issue for tracking and fixing this (i.e. by rolling commit granularity, or something flushing on crash/panic handlers, etc), but the current PR if all works as intended, should still provide an incremental improvement to what we have now. Once landed, it will also allow @danielxiangzl to proceed w. early …

Speculative logging support in Aptos VM

---

config/src/config/quorum_store_config.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/counters.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/quorum_store/tests/proof_manager_test.rs
consensus/src/quorum_store/utils.rs

We poll mempool for transactions at a fast rate (default 25 ms), unless there is backpressure. If there is backpressure then the next poll will be tried in + 25ms, until a max of 250 ms is reached. Since this makes the poll duration variable, we compute the max txns to pull based on the time passed since the last poll.
The backpressure is based on the number of proofs left in proof manager. So proofs are used for the rate of pulling, and txns are used for the max number of txns on the pull.
Running tests with low TPS (2 TPS per validator), confirmed that the time spent in mempool reduced: roughly from an average of 125ms (from the previous 250ms poll time) to an average of 12.5ms (fro the 25ms faster poll time).

[Quorum Store] poll mempool at a faster pace to reduce mempool queueing time, except when backpressure

---

config/src/config/quorum_store_config.rs

Set defaults to be suitable for a 100 validator network.
Paraphrasing Sasha:
20000 tps * 1000B (size of a tnx) * 60 s (duration) = 1_200_000_000 bytes
Divide by 100 validator = 12_000_000B each validator ask me to persist on average.
Adding some buffer for peaks:
Memory: 10x - 120_000_000 bytes
Storage 25x - 300_000_000 bytes

[Quorum Store] adjust memory and db quotas

---

aptos-move/block-executor/src/scheduler.rs
aptos-move/block-executor/src/unit_tests/mod.rs

Addressing the issue in https://github.com/aptos-labs/aptos-core/issues/6951, based on the description there (except, as pointed out by @sitalkedia, we still can't avoid using compare-and-swap for incrementing validation index, as f&i could still skip over indices due to concurrency).
Some additional changes to the scheduler and unit tests. The hope is that the change improves performance with many threads and low contention.

[BlockSTM] No eager validation for first execution wave

---

consensus/src/epoch_manager.rs
testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs

This PR adds a new smoke test to test the presence of a non-QS validator amongst a swarm of QS validators. It uses failpoints to force a validator to disable the QS and observe that other honest validators make progress.
Test succeeds.

[Quorum Store][smoketest] non-QS validator in swarm

---

.github/workflows/lint-test.yaml

This PR disables the consensus-only smoke test on the aptos-node-v1.2 branch because we don't have support for consensus-only on that branch. This PR is much simpler than cherry-picking the consensus-only changes to the branch which I consider is a much more involved change.
Forge works.

[consensus-only] disable consensus-only smoke test in v1.2

---

Cargo.lock
Cargo.toml
aptos-move/framework/src/built_package.rs
aptos-move/framework/src/prover.rs
aptos-move/framework/tests/move_prover_tests.rs
aptos-move/writeset-transaction-generator/src/admin_script_builder.rs
crates/aptos/src/governance/mod.rs
crates/aptos/src/move_tool/mod.rs

This should remove any more dependency on the environment variable.  Now, bytecode version should be passed in via CLI arguments for every command if it is different than the default.
Environment variable is now ignored, but you can override with a command line arg:
```
VAR_BYTECODE_VERSION=5 ./target/debug/aptos move compile --package-dir /opt/git/aptos-checkers/move/tic-tac-toe --named-addresses deploy_account=0x22 
UPDATING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
BUILDING ExampleTicTacToe
{
"Result": [
"0000000000000000000000000000000000000000000000000000000000000022::tic_tac_toe"
]
}
```
Then with …

[aptos-move] Remove usage of bytecode version environment variable

---

ecosystem/indexer-grpc/indexer-grpc-fullnode/src/counters.rs

Thanks @levicook for calling out the interesting issue here. Basically we're using the same counter names for old and new indexer (grpc) and if run at the same time they will lead to naming collision. This PR fixes that. 
https://gist.github.com/levicook/cf365cb89def0c6d9633c31cddaf7f31
Error doesn't happen anymore when running
```
grpcurl  -max-msg-sz 10000000  -d '{ "starting_version": 0 }' -import-path crates/aptos-protos/proto -proto aptos/datastream/v1/datastream.proto  -plaintext localhost:50051 aptos.datastream.v1.IndexerStream/RawDatastream
```

[Indexer] Avoid panics running old indexer and new grpc indexer 

---

aptos-move/aptos-release-builder/data/release.yaml
aptos-move/vm-genesis/src/lib.rs

Disables the feature flags that were not supposed to be enabled in https://github.com/aptos-labs/aptos-core/pull/7015.
The flags will be enabled during the release process.
@thepomeranian and @perryjrandall, for visibility.

oops, these flags should be disabled for now

---

aptos-move/framework/aptos-stdlib/doc/smart_vector.md
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.move

I think I made a mistake that "`Option` cannot be used here".
Previously I used a `vector` with an invariant that the length is always 1 to to represent an option. But actually we can just use option here.
If possible I wanna cherry-pick v1.3... since it can preclude some potential bugs.
ut

[smart_vec] vector of big_vec is not necessary

---

Cargo.lock
consensus/Cargo.toml
consensus/src/consensus_provider.rs
consensus/src/epoch_manager.rs
consensus/src/experimental/tests/buffer_manager_tests.rs
consensus/src/network_tests.rs
consensus/src/round_manager.rs
consensus/src/twins/twins_node.rs
crates/channel/src/aptos_channel.rs

Dispatch message verification to multi threaded executor to avoid choking epoch manager since after quorum store we have many more messages flooding in.
Tested in https://github.com/aptos-labs/aptos-core/pull/7045 which wired self messages through network layer too, before the change it causes perf regression, after the change it looks good

[consensus] dispatch verify message into executor

---

aptos-move/move-examples/my_first_dapp/client/package-lock.json
aptos-move/move-examples/my_first_dapp/client/package.json
aptos-move/move-examples/my_first_dapp/client/src/App.tsx
aptos-move/move-examples/my_first_dapp/move/Move.toml
aptos-move/move-examples/my_first_dapp/move/sources/todolist.move
developer-docs-site/docs/tutorials/build-e2e-dapp/4-fetch-data-from-chain.md
developer-docs-site/docs/tutorials/build-e2e-dapp/5-submit-data-to-chain.md
developer-docs-site/docs/tutorials/build-e2e-dapp/6-handle-tasks.md
developer-docs-site/docs/tutorials/build-e2e-dapp/index.md

Update e2e dapp tutorial with
- Use TS SDK `Provider` class instead of `AptosClient` to interact with the network
- Link the tutorial on aptos-core repo instead of an external repo (will delete external repo after this PR lands)
- Change move module name to `todolist` due to issues with the `main` name.
Tests are passing

[DOC] Update e2e dapp tutorial

---

consensus/src/quorum_store/batch_store.rs
consensus/src/quorum_store/tests/batch_store_test.rs

Fix the issue of not holding the lock while checking expiration and inserting a new entry (that can extend expiration but could end up truncating).
Simple test that replicates the panic without the fix.
More tests (more coverage, concurrent, proptests, injecting pause) coming separately.

[QuorumStore] fix insert/expire issue

---

config/src/config/quorum_store_config.rs
consensus/src/epoch_manager.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/quorum_store_builder.rs

In consensus-only tests, we saw large gaps where backpressure seemed "stuck". This was because we only checked the numbers after commit, and if commit is delayed then the numbers didn't get updated at all. This PR now increments when proofs are received. It can be an overestimate until the actual cleaning takes place.
In addition
* Make the minimum time between pulls that had transactions 100 ms. 25 ms pulls seem unsustainable, even if there is no other load in the network.
* Change the config for proof-based backpressure so it is a multiple of number of validators. This makes the config more portable between networks.
Re-run consensus only tests where we saw issues.

[Quorum Store] fix backpressure only checking on commits

---

Cargo.lock
docker/compose/data-restore/gcs.yaml
docker/compose/data-restore/s3.yaml
storage/backup/backup-cli/src/backup_types/tests.rs
storage/backup/backup-cli/src/coordinators/backup.rs
storage/backup/backup-cli/src/metadata/cache.rs
storage/backup/backup-cli/src/metadata/mod.rs
storage/backup/backup-cli/src/metadata/view.rs
storage/backup/backup-cli/src/storage/command_adapter/config.rs
storage/backup/backup-cli/src/storage/command_adapter/mod.rs
storage/backup/backup-cli/src/storage/command_adapter/sample_configs/azure.sample.yaml
storage/backup/backup-cli/src/storage/command_adapter/sample_configs/gcp.sample.yaml
storage/backup/backup-cli/src/storage/command_adapter/sample_configs/local_folder.sample.yaml
storage/backup/backup-cli/src/storage/command_adapter/sample_configs/s3.sample.yaml
storage/backup/backup-cli/src/storage/command_adapter/tests.rs
storage/backup/backup-cli/src/storage/local_fs/mod.rs
storage/backup/backup-cli/src/storage/mod.rs
storage/db-tool/Cargo.toml
storage/db-tool/src/backup_maintenance.rs
storage/db-tool/src/lib.rs
storage/db-tool/src/tests.rs
terraform/helm/fullnode/files/backup/azure.yaml
terraform/helm/fullnode/files/backup/gcs.yaml
terraform/helm/fullnode/files/backup/oci.yaml
terraform/helm/fullnode/files/backup/s3-public.yaml
terraform/helm/fullnode/files/backup/s3.yaml
terraform/helm/fullnode/files/backup/scw_s3.yaml
testsuite/smoke-test/src/storage.rs

add manual backup compaction
TODO: 
1. add continuous backup compaction
2. add metadata backup cleanup
1. updated smoke test
2. add unit test
3. local run DB restore on testnet with 2 concurrent downloads and 100 compaction counter
The metadata loading time reduces from 45 mins to less than 1 min after compaction

[storage][1/2] manual backup compaction

---

consensus/src/quorum_store/batch_store.rs
consensus/src/quorum_store/tests/batch_store_test.rs

[cherry-pick] PR 7070

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/indexer/generated/operations.ts
ecosystem/typescript/sdk/src/indexer/generated/queries.ts
ecosystem/typescript/sdk/src/indexer/queries/getLedgerInfo.graphql
ecosystem/typescript/sdk/src/providers/indexer.ts
ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts

We rely on indexer devnet and fullnode devnet to be in sync when running tests - in some cases they are not yet updated and tests are failing.
This PR is a part 1 of fixing the problem by adding `getIndexerLedgerInfo` query to `IndexerClient`.
In a second PR (and after releasing a new sdk version) we would use this query to check indexer devnet chainId with fullnode chainId and make sure they are synced before running tests.

[TS SDK] Add indexer ledger info query

---

aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/scheduler.rs
aptos-move/block-executor/src/unit_tests/mod.rs

Following up on https://github.com/aptos-labs/aptos-core/pull/6996.
- Uniformizes the treatment of decrease_validation_idx to always reduce to txn_idx +1 and set max_triggered_wave there (as per @zekun000's suggestion)
- Adds a test to check total number of validation and execution tasks is equal if there are no aborts (conflicts).
Some of the possible races we discovered while making these changes were scary and hard to catch (due to the interleaving that's required). We have a structured way to be sure that these aren't a concern for now, but one further follow-up is to start injecting failure points to make the thread sleep to generate and test against some of the problematic concurrent behaviors.

[Block-STM] Scheduler uniform wave treatment & test for number of tasks

---

consensus/consensus-types/src/proof_of_store.rs
consensus/src/network.rs
consensus/src/payload_manager.rs
consensus/src/quorum_store/batch_aggregator.rs
consensus/src/quorum_store/batch_coordinator.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/batch_store.rs
consensus/src/quorum_store/network_listener.rs
consensus/src/quorum_store/proof_coordinator.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/quorum_store/quorum_store_coordinator.rs
consensus/src/quorum_store/quorum_store_db.rs
consensus/src/quorum_store/schema.rs
consensus/src/quorum_store/tests/batch_aggregator_test.rs
consensus/src/quorum_store/tests/batch_generator_test.rs
consensus/src/quorum_store/tests/batch_store_test.rs
consensus/src/quorum_store/tests/proof_coordinator_test.rs
consensus/src/quorum_store/tests/proof_manager_test.rs
consensus/src/quorum_store/tests/quorum_store_db_test.rs
consensus/src/quorum_store/tests/types_test.rs
consensus/src/quorum_store/types.rs
consensus/src/quorum_store/utils.rs
consensus/src/round_manager.rs
consensus/src/test_utils/mock_quorum_store_sender.rs
testsuite/generate-format/tests/staged/consensus.yaml

This commit unifies fragment and proof processing such that we don't differentiate whether the message is for local or remote.

[qs] another refactor

---

developer-docs-site/docs/nodes/validator-node/operator/connect-to-aptos-network.md
developer-docs-site/docs/nodes/validator-node/operator/staking-pool-operations.md
developer-docs-site/docs/nodes/validator-node/owner/index.md

I updated the relevant examples to use `--network` instead of `--rest-url`. These changes address [issue #6528](https://github.com/aptos-labs/aptos-core/issues/6528).

Updated the docs to use --network instead of --rest-url

---

Cargo.lock
network/peer-monitoring-service/client/Cargo.toml
network/peer-monitoring-service/client/src/lib.rs
network/peer-monitoring-service/client/src/peer_states/peer_state.rs
network/peer-monitoring-service/client/src/tests/mock.rs
network/peer-monitoring-service/client/src/tests/mod.rs
network/peer-monitoring-service/client/src/tests/multiple_peers.rs
network/peer-monitoring-service/client/src/tests/single_peer.rs
network/peer-monitoring-service/client/src/tests/utils.rs

Notes:
- This PR is built on: https://github.com/aptos-labs/aptos-core/pull/6942
This PR adds a new suite of integration tests to verify the correct behavior of the peer monitoring service. Specifically, the test suite verifies:
- Correct loop executions using timing signals (for both the peer monitor and peer metadata updater).
- Correct verification of service requests and responses (for latency info and network info requests).
- Single and multi-peer execution support (including disconnecting and reconnecting peers).
Note: even though this PR is huge, I've broken the tests and mock infrastructure into multiple files, so it should be relatively easy to parse.

[Peer Monitoring Service] Add extensive test suite for the client side.

---

docker/experimental/build-tools.sh
docker/experimental/faucet.Dockerfile

It seems like the CI/CD for the experimental docker build stuff didn't run in https://github.com/aptos-labs/aptos-core/pull/6748. This PR fixes it.
Add the `CICD:experimental-*` labels and see that they pass.
I also confirmed that this works locally now:
```
docker/experimental/build-tools.sh
```

Fix faucet build in docker/experimental/build-tools.sh

---

consensus/src/quorum_store/utils.rs

Was printing the whole list of batches instead of the length.

[Quorum Store] fix a log line that was long by mistake

---

config/src/config/state_sync_config.rs

This PR doubles the RPC timeout for data requests from 10 seconds to 20 seconds in the data client.

[Aptos Data Client] Increase timeout from 10 to 20 seconds.

---

crates/aptos/src/node/mod.rs

I have a PR that will add CI to run the faucet tests in https://github.com/aptos-labs/aptos-core/pull/7125. For that PR to work, I need the `--test-dir` flag to `aptos node run-local-testnet` to work correctly, which https://github.com/aptos-labs/aptos-core/pull/7126 fixed. This needs to be cherry picked into this branch specifically because those tests run the local testnet using the image built from this branch.

Cherry pick #7126 into testnet

---

crates/aptos/e2e/local_testnet.py
crates/aptos/e2e/poetry.lock
crates/aptos/e2e/pyproject.toml

This is needed because when https://github.com/aptos-labs/aptos-core/pull/6748 landed in main, the CLI e2e tests were changed expecting the faucet in the images its using to also change. I didn't think to test the case where the faucet was still the old one. I made the unfortunate (but good for deployment) choice to change the healthcheck endpoint to `/`. I didn't think to test this combination of images, my bad.
```
poetry run python main.py --base-network mainnet --test-cli-tag mainnet
```

[CLI][E2E] Fix liveness check for faucet

---

aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move

Fixes a small typo in our feature flag documentation.

[typo] feature flags should be either 'transient' or 'permanent'

---

crates/aptos/src/node/mod.rs

I have a PR that will add CI to run the faucet tests in https://github.com/aptos-labs/aptos-core/pull/7125. For that PR to work, I need the `--test-dir` flag to `aptos node run-local-testnet` to work correctly, which https://github.com/aptos-labs/aptos-core/pull/7126 fixed. This needs to be cherry picked into this branch specifically because those tests run the local testnet using the image built from this branch.

Cherry pick #7126 into devnet

---

types/src/on_chain_config/consensus_config.rs

with high TPS, we can see up to 30-35 pending blocks. we are already using this on previewnet.
this will require governance proposal for testnet.

increase exclude round

---

Cargo.lock
api/Cargo.toml
api/src/runtime.rs
config/src/config/api_config.rs

This PR updates the config for the API runtime. Specifically, it:
1. Adds a new config entry to specify the maximum number of worker threads for the runtime (defaults to None).
2. Adds a new config entry to specify the worker amplification factor (defaults to 2).
If the config does not specify the maximum number of worker threads for the API runtime, we choose 2 * the number of CPU cores. This seems to be more optimal based on the findings here: https://github.com/aptos-labs/aptos-core/issues/7082

[Config] Add config for API runtime workers.

---

aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/sources/staking_contract.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs

Fixed several typos(_commision_ => _commis**s**ion_).
The typo also exists in a entry function name. There is no easy way to correct. Leave a TODO there.
Unit tests.

[typo] fix misspelled words in aptos-framework

---

aptos-node/src/state_sync.rs
config/src/config/state_sync_config.rs
state-sync/aptos-data-client/src/aptosnet/mod.rs
state-sync/aptos-data-client/src/aptosnet/state.rs
state-sync/aptos-data-client/src/aptosnet/tests.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/driver_factory.rs
state-sync/storage-service/types/src/responses.rs
state-sync/storage-service/types/src/tests.rs

This PR makes three small improvements to the Aptos data client (each in their own commit):
1. Decouple the chunk sizes between the data client and storage service (by adding chunk sizes to the data client config). Now, we can specify the data sizes of chunks to request and the data sizes of chunks to return, independently.
2. Garbage collect peer states for peers that are no longer connected (and add a new unit test).
3. Update data summary logic to always allow clients to request data from peers, even if that peer cannot return the entire data chunk.

[Aptos Data Client] Improvements around chunk size calculations.

---

Cargo.lock
crates/aptos/Cargo.toml
crates/aptos/src/common/types.rs
crates/aptos/src/move_tool/coverage.rs
crates/aptos/src/move_tool/mod.rs

The UX was a little strange, where the command would be `aptos move coverage --package-dir X source --module-name Y`
It's now been cleaned up so all the flags are on the right side, `aptos move coverage source --package-dir X --module-name Y`
This additionally breaks it down to match the rest of the commands in the space.
I needed to make this change prior to releasing a new version of the CLI, because once something is set like this, I don't want to break the existing flow.
```
$ ./target/debug/aptos move test --named-addresses hello_blockchain=0x22 --package-dir aptos-move/move-examples/hello_blockchain --coverage
BUILDING Examples
Running Move unit tests
[ PASS    ] …
```

[cli] Cleanup coverage tool so subcommands are at the beginning

---

third_party/README.md
third_party/copy.bara.sky
third_party/move/language/README.md

This sets up [copybara](https://github.com/google/copybara) for maintaining a copy of the Move tree within the aptos tree. A workflow to push and to pull from the Move repo is defined. The `pull_move` workflow has been used to seed the initial content of `third_party/move`, the proposed directory to hold the Move tree.
Copybara will allow us submit code to the Move tree in lockstep to the Aptos tree. We then can periodically (or via some cron job) synchronize the state with the upstream Move repo. The mechanism works bidirectional. For a tutorial of the tool, see [here](https://blog.kubesimplify.com/moving-code-between-git-repositories-with-copybara).
For now we only pull in only the `language/README.md` file from Move, so this mechanism can be further studied also in the push direction. …

[Move] Setup copybara for keeping a synchronized copy of Move

---

crates/aptos/src/move_tool/mod.rs

There was a bug / feature request on discord https://github.com/aptos-labs/aptos-core/issues/7134 about that `vector<string>` didn't work.  I put it off because commas in strings can be hard, but I don't see a reason to block people from doing more common use cases (strings without commas)
Manual testing (using a modified hello blockchain):
This one we insert an array, then we view the output
```
./target/debug/aptos move run --function-id  devnet::testing::set_message --profile devnet --args 'vector<string>:hello,blockchain'
Do you want to submit a transaction for a range of [300 - 400] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
"Result": {
"transaction_hash": "0xe369bfab40ee86853fd6993e162d310f8e2326af1f36c3a1338c4ab0fb19caf0",
"gas_used": 3, …
```

[cli] Add ability for vector<string> in CLI inputs

---

api/src/page.rs

See original PR https://github.com/aptos-labs/aptos-core/pull/6116
* Without this change, maximum page size right now is 25 transactions etc. no matter what.  This can make it slower for people to get the amount of data they want.
* This change allows the page size of 25 to be adjusted accordingly to node runner's needs
* Current state: https://fullnode.mainnet.aptoslabs.com/v1/transactions?start=1&limit=30only returns 25
* Local testnet: http://localhost:8080/v1/transactions?start=1&limit=30 returns 1-30
```
{
"version": "30",
"hash": "0x905995bd6b6af8df664bd4146a8719465d8c442bf166ad8fac6fff6f32a6ebcb",
"state_change_hash": "0x1ebad0c2fbdf8
```
* Only an API change, doesn't affect any other components

[api] Aptos node v1.2.0 cherrypick pagination

---

storage/backup/backup-cli/src/backup_types/transaction/tests.rs
storage/db-tool/src/backup.rs
storage/db-tool/src/main.rs
storage/db-tool/src/replay_verify.rs
storage/db-tool/src/restore.rs
storage/db-tool/src/tests.rs

improve the robustness of the test
1. txn end_to_end has random test inputs generated, in some scenarios, there could be 0 txn to backup for the first backup. Update the logic to only backup txns when there are more than 0 txn to backup. 
2. close the runtime after a duration to avoid pthread error, also remove duplicated logger initiation

[storage] db tool tests

---

terraform/aptos-node-testnet/gcp/addons.tf

GKE uses containerd but chaos-mesh assumes Docker by default. This PR configures chaos-mesh daemon to use containerd.
Deployed to gcp-forge and verified it works.

[forge][gcp] Fix chaos-mesh daemon config

---

.github/actions/docker-setup/action.yaml

I saw an issue where the latest version lookup failed, this will avoid that problem. Beyond that, it's likely good to pin anyway, like we do with most deps.
CI.

Pin crane version in docker-setup

---

api/Cargo.toml
api/src/log.rs
api/src/metrics.rs

We want some more insight into where requests to the API are coming from, this counter helps with that.
@0xmaayan this slices up the requests by source, method they're calling, and status they got. Does that sound good, or did you want the data sliced up differently?
Run local testnet:
```
```
Make a couple of requests with just curl:
```
curl http://127.0.0.1:8080/v1
curl http://127.0.0.1:8080/v1/accounts/0x1
```
Make a couple of requests with the CLI, to which we just added the User-Agent stuff.
```
aptos account list --url http://127.0.0.1:8080 --account 0x1
```
See the metrics pushed appropriately, with `request-source-client-unknown` for the former and `aptos-cli/1.8.0` for the latter:
```
curl -s …
```

[API] Create counter for request source

---

Cargo.lock
aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/output_delta_resolver.rs
aptos-move/block-executor/src/proptest_types/tests.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/scheduler.rs
aptos-move/block-executor/src/task.rs
aptos-move/block-executor/src/txn_last_input_output.rs
aptos-move/block-executor/src/unit_tests/mod.rs
aptos-move/block-executor/src/view.rs
aptos-move/mvhashmap/Cargo.toml
aptos-move/mvhashmap/src/lib.rs
aptos-move/mvhashmap/src/types.rs
aptos-move/mvhashmap/src/unit_tests/mod.rs
aptos-move/mvhashmap/src/unit_tests/proptest_types.rs
aptos-move/mvhashmap/src/versioned_code.rs
aptos-move/mvhashmap/src/versioned_data.rs
types/src/executable.rs
types/src/lib.rs

Separate out data & modules - useful for executable / versioned code work, but also for caching MoveValues / CompiledModules, as these types (and handling) might be different.
Introduced some Executable tooling, but a separate diff will incorporate module versioning and executable treatment in parallel executor (e.g. validation based on fetching, view traits) & respective testing.

[Parallel Executor] MVHashMap refactoring to separate data / modules

---

developer-docs-site/static/scripts/prover_setup.sh

As the first step to resolve #7148, this PR adds a script to install dependencies of the Move prover (`.net`, `z3`, `cvc5` and`boogie`) and `graphviz` without relying on the `aptos-core` repo. It can be run outside the repo. The usage of this script is similar to `dev_setup.sh` because the code is borrowed from it. 
Need to test this script in different OS environments.

[Misc] Add a script to install dependencies for the prover independent of the repo

---

config/src/config/quorum_store_config.rs
consensus/consensus-types/src/proof_of_store.rs
consensus/consensus-types/src/request_response.rs
consensus/src/liveness/proposal_generator.rs
consensus/src/payload_client.rs
consensus/src/payload_manager.rs
consensus/src/quorum_store/batch_coordinator.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/batch_store.rs
consensus/src/quorum_store/counters.rs
consensus/src/quorum_store/direct_mempool_quorum_store.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/quorum_store/quorum_store_coordinator.rs
consensus/src/quorum_store/tests/batch_store_test.rs
consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs
consensus/src/quorum_store/tests/proof_coordinator_test.rs
consensus/src/quorum_store/tests/proof_manager_test.rs
consensus/src/quorum_store/tests/quorum_store_db_test.rs
consensus/src/quorum_store/tests/types_test.rs
consensus/src/quorum_store/types.rs
consensus/src/quorum_store/utils.rs
consensus/src/state_computer.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_payload_manager.rs
testsuite/generate-format/tests/staged/consensus.yaml

Previously, batches were expired using logical time, i.e., (epoch, round). Validators set batch expiration based on their local logical time. For validators that fell behind in consensus, this causes an issue where batches they create are more likely to not reach quorum or expire after quorum, as other validators have a more advanced round. There were several gap buffers introduced to try to mitigate this, which added complexity.
In this PR, logical time is replaced with system clock times (for creation) and block timestamp times (for expiration). Validators set expiration when creating a batch using their local clock time. The system clock is less likely to fall behind than round times (it doesn't depend on consensus progress). Expiration is based on the block timestamp, which is …

[Quorum Store] block timestamp-based expiration of batches

---

config/src/config/quorum_store_config.rs
consensus/consensus-types/src/proof_of_store.rs
consensus/consensus-types/src/request_response.rs
consensus/src/liveness/proposal_generator.rs
consensus/src/payload_client.rs
consensus/src/payload_manager.rs
consensus/src/quorum_store/batch_coordinator.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/batch_store.rs
consensus/src/quorum_store/counters.rs
consensus/src/quorum_store/direct_mempool_quorum_store.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/quorum_store/quorum_store_coordinator.rs
consensus/src/quorum_store/tests/batch_store_test.rs
consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs
consensus/src/quorum_store/tests/proof_coordinator_test.rs
consensus/src/quorum_store/tests/proof_manager_test.rs
consensus/src/quorum_store/tests/quorum_store_db_test.rs
consensus/src/quorum_store/tests/types_test.rs
consensus/src/quorum_store/types.rs
consensus/src/quorum_store/utils.rs
consensus/src/state_computer.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_payload_manager.rs
testsuite/generate-format/tests/staged/consensus.yaml

Previously, batches were expired using logical time, i.e., (epoch, round). Validators set batch expiration based on their local logical time. For validators that fell behind in consensus, this causes an issue where batches they create are more likely to not reach quorum or expire after quorum, as other validators have a more advanced round. There were several gap buffers introduced to try to mitigate this, which added complexity.
In this PR, logical time is replaced with system clock times (for creation) and block timestamp times (for expiration). Validators set expiration when creating a batch using their local clock time. The system clock is less likely to fall behind than round times (it doesn't depend on consensus progress). Expiration is based on the block timestamp, which is …

[cherry-pick] PR 7194: [Quorum Store] block timestamp-based expiration of batches

---

.github/actions/run-faucet-tests/action.yaml
.github/workflows/faucet-tests.yaml
crates/aptos-faucet/README.md
crates/aptos-faucet/integration-tests/README.md
crates/aptos-faucet/integration-tests/common.py
crates/aptos-faucet/integration-tests/local_testnet.py
crates/aptos-faucet/integration-tests/main.py
crates/aptos-faucet/integration-tests/poetry.lock
crates/aptos-faucet/integration-tests/prechecks.py
crates/aptos-faucet/integration-tests/pyproject.toml
crates/aptos-faucet/integration-tests/tests.py

This PR adds CI for running the faucet integration tests. Because we want to test the faucet against both devnet and testnet I use an action. Currently I use the action once in two separate jobs to make it faster, but this is also wasteful because I build the faucet for tests twice with no shared cache (I think). I'll ask the CI experts the best option.
Given the faucet changes rarely these tests might be sort of wasteful, but I figure that's already the case for many tests and the real fix is a target determinator. I'm using ubuntu-latest so it's not our runners. Of course, this means I have to build everything from scratch so this takes like 45 minutes total. Though later runs should be faster because we use `rust-cache` in our `rust-setup` action. The alternative would be to either use …

Run faucet integration tests in CI

---

config/src/config/consensus_config.rs
consensus/src/epoch_manager.rs
consensus/src/round_manager.rs

[cherry-pick] PR 7256

---

Cargo.lock
crates/aptos-protos/Cargo.toml

* Using the same aptos-proto version may have compiler invalidating the build cache incorrectly(in this case, compiler believes there is no change). 
* A minor version bump to mark the recent changes.

[protobuf] upgrade the aptos proto version

---

.github/workflows/faucet-tests.yaml

Previously, besides running on PRs, we were only running faucet tests on the devnet and testnet branches. This doesn't really make sense, since we never deploy faucet built off those branches, we deploy faucet built off the main branch. This PR changes it so we run the tests against `main` instead of those other branches.
To clarify, this doesn't change the nature of the tests themselves, we will still run the faucet integration tests against a local testnet from devnet / testnet. It's just where we choose to build and run the integration tests from.
CI.

Run faucet tests on main

---

crates/aptos/src/move_tool/mod.rs
crates/aptos/src/move_tool/show.rs

Occasionally we'll want to look at the ABI that comes directly out of the compiler. Previously when we wanted to do this we'd hack up a script for that one instance and then throw it away. This PR adds support for this in the CLI with the `aptos move show` subcommand group, starting with `aptos move show abi`.
I have marked this subcommand group has hidden for now, as the difference between this ABI and the ABI returned by the API might confuse some people.
```
$ cargo run -p aptos -- move show abi --help
aptos-move-show-abi 1.0.8
Compile a package and show information about the ABIs of the compiled modules.
For example, this would show the function `transfer` in the module `coin`:
aptos move show abi --modules coin --names transfer
USAGE:
aptos move show abi [OPTIONS]
OPTIONS: …
```

[CLI] Add `aptos move show` subcommand group

---

config/src/config/consensus_config.rs
consensus/src/epoch_manager.rs
consensus/src/round_manager.rs

This fixes a bug where a rollback of quorum store would not rollback the configs to non-quorum store values.
Config fields have to be public, so we'll just have to be careful not to read the raw values.

[Quorum Store] fix consensus config quorum store overrides

---

ecosystem/indexer-grpc/indexer-grpc-parser/README.md
ecosystem/indexer-grpc/indexer-grpc-parser/src/models/default_models/transactions.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/utils/util.rs

Part of the protobuf (e.g. payload data, events data, etc.) are converted to string from json in the fullnode and that causes the string to be escaped. This PR unescapes those parts in a safe way. 
Verified that `type_arguments` in `payload` are no longer escaped. 
```
{"function": {"name": "transfer", "module": {"name": "coin", "address": "0x1"}}, "arguments": ["0xd11d0bb59e6dc3689f20c28171fe38ff5527806a5b20ad6d0aa08cb30a8e5239", "123"], "type_arguments": [{"type": "MOVE_TYPES_STRUCT", "struct": {"name": "AptosCoin", "module": "aptos_coin", "address": "0x1"}}]}
```

[Indexer] Fix string escape in json data for parser only

---

developer-docs-site/docs/tutorials/first-multisig.md

The inclusion of the `.` in the referenced commit forces the invocation style added here.
If not updated, an ImportError will be raised when running the example according to the unmodified instructions.
@davidiw

Update call instructions forced by commit 3bbd3f3c

---

aptos-move/framework/aptos-stdlib/doc/simple_map.md
aptos-move/framework/aptos-stdlib/sources/simple_map.spec.move

As requested in #7204, this PR adds spec for newly added public API `to_vec_pair` and `upsert`. Since both functions do not fit the table model in boogie, they are written in an abstract way.

[Spec] Spec for to_vec_pair and upsert in simple_map

---

aptos-move/e2e-move-tests/src/tests/string_args.data/pack/sources/hello.move
aptos-move/e2e-move-tests/src/tests/string_args.rs

I realized that the current string argument implementation is broken for generic functions
ie,.
pub entry fun foo<T>(x:  T) { ... }
cannot be called with T=String as an entry function. This PR is adding a test case to show this

String arg

---

aptos-node/src/lib.rs

We ship warn and above logs by default, so lets make node config logging a warn level.

Make node config logging a warn

---

.github/workflows/replay-verify.yaml

Like some other expensive cron jobs, we only want to run them on the aptos-core repo, and not anywhere else like forks. `check-aptos-core` action only works when the repo has already been checked out, since it uses the `gh` CLI which needs it for context. This PR fixes that.
Also, make the replay jobs depend on the `determine-test-metadata` job, so replay will not run even if the initial check fails.

[gha][replay-verify] fix job cancellation

---

Cargo.lock
consensus/Cargo.toml
consensus/src/block_storage/sync_manager.rs
consensus/src/consensus_provider.rs
consensus/src/epoch_manager.rs
consensus/src/experimental/tests/buffer_manager_tests.rs
consensus/src/network.rs
consensus/src/network_tests.rs
consensus/src/round_manager.rs
consensus/src/twins/twins_node.rs

- dispatch message verification into multiple thread executor
- increase the message channel size and fix the ordering
- increase the state sync threshold to compensate large pipeline

[cherry-pick] consensus improvement for v1.2

---

aptos-move/framework/aptos-framework/doc/gas_schedule.md
aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
aptos-move/framework/aptos-stdlib/doc/fixed_point64.md
aptos-move/framework/aptos-stdlib/sources/fixed_point64.move
aptos-move/framework/move-stdlib/doc/option.md
aptos-move/framework/move-stdlib/sources/option.move

This PR: 
- removes timeouts in specs that are too long.
- adds the abort condition to `from_vec` in `option.move`.

[Spec] Remove long timeout in specs and add abort to from_vec

---

Cargo.lock
Cargo.toml
crates/aptos-protos/Cargo.lock

The version of Poem we are using now is missing a few features that I think would be nice to have:
- The ability to use eliptic curve private keys when using the built-in TLS: https://github.com/poem-web/poem/pull/460.
- Improved SSE support, which we might want to experiment with.
Running a local testnet and playing with that, as well as CI.

Upgrade Poem

---

developer-docs-site/scripts/additional_dict.txt

So [ANS UI library documentation](https://github.com/aptos-labs/aptos-core/pull/7212) can pass the docs-lint test.

Add customizable to the list for the ANS UI doc

---

consensus/consensus-types/src/block_retrieval.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/network.rs

Block retrieval had no parallelism, was dropping responses from previous retries during new retries, etc.
Making it similar to batch_requestor

[preview-cherry-pick of 7383][consensus] Make block retrieval more aggressive

---

aptos-move/framework/aptos-framework/doc/fungible_store.md
aptos-move/framework/aptos-framework/doc/managed_fungible_metadata.md
aptos-move/framework/aptos-framework/sources/fungible_store.spec.move
aptos-move/framework/aptos-framework/sources/managed_fungible_metadata.spec.move

This PR adds empty specs for `fungible_store.move` and `managed_fungible_metadata.move` to avoid prover test failure. 
cargo test -- --include-ignored prover

[Spec] Add mock specs for fungible contracts

---

aptos-move/framework/aptos-framework/doc/storage_gas.md
aptos-move/framework/aptos-framework/sources/storage_gas.spec.move
aptos-move/framework/aptos-stdlib/doc/table.md
aptos-move/framework/aptos-stdlib/doc/table_with_length.md
aptos-move/framework/aptos-stdlib/sources/table.spec.move
aptos-move/framework/aptos-stdlib/sources/table_with_length.spec.move

This PR adds the intrinsic spec of `borrow_mut_with_default` to the `table` and `table_with_length` module.
cargo test -- --include-ignored prover

[Spec] Add intrinsic spec of borrow_mut_with_default in the table module

---

terraform/aptos-node-testnet/aws/main.tf
terraform/aptos-node-testnet/aws/variables.tf
terraform/aptos-node/aws/security.tf
terraform/aptos-node/gcp/security.tf
terraform/aptos-node/gcp/variables.tf
terraform/fullnode/aws/security.tf
terraform/fullnode/aws/variables.tf
terraform/fullnode/gcp/security.tf
terraform/fullnode/gcp/variables.tf

Auto-detect Kubernetes version and stop pinning the PSS labels manually (they will default to the current Kubernetes version).
Tested on Rustienet and Previewnet.

Auto-detect Kubernetes version

---

developer-docs-site/docs/concepts/accounts.md
developer-docs-site/docs/guides/aptos-name-service-connector.md
developer-docs-site/docs/guides/index.md
developer-docs-site/docs/whats-new-in-docs.md
developer-docs-site/sidebars.js

Add ANS integration doc to nav and announce with other recent updates

---

.pre-commit-config.yaml

This PR removes the pre-commit checks for cargo-check. This can be expensive and we already verify it via `rust_lint.sh` (when landing), so, there's no need to do it twice 😄 
Note: `rust_lint.sh` runs `cargo xclippy`, which is a wrapper around `clippy` and ultimately calls `cargo check`, too. So, running `cargo check` separately seems redundant: https://stackoverflow.com/questions/57449356/is-cargo-clippy-a-superset-of-cargo-check.

[Pre-commit] Remove rust pre-commits

---

config/src/config/network_config.rs
network/peer-monitoring-service/client/Cargo.toml
network/peer-monitoring-service/client/src/lib.rs
network/peer-monitoring-service/client/src/peer_states/mod.rs
network/peer-monitoring-service/client/src/peer_states/network_info.rs
network/peer-monitoring-service/client/src/peer_states/peer_state.rs
network/peer-monitoring-service/client/src/tests/multiple_peers.rs
network/peer-monitoring-service/client/src/tests/single_peer.rs
network/peer-monitoring-service/client/src/tests/utils.rs
network/peer-monitoring-service/server/src/lib.rs
network/peer-monitoring-service/server/src/tests.rs
network/peer-monitoring-service/types/src/lib.rs
network/src/application/metadata.rs

Notes:
This PR makes two incremental changes to the peer monitoring service (each in their own commit):
1. Add jitter to each peer monitoring request (this adds up to 1 second of delay before sending the request). This helps prevent bursty requests.
2. Simplify the metadata being returned by the network info responses. We will add discovery information in a separate request/response type, so this is not needed.

[Peer Monitoring Service] Add jitter and simplify network info responses.

---

.github/actions/docker-setup/action.yaml
docker/experimental/build-node.sh
docker/experimental/build-tools.sh
docker/experimental/builder.Dockerfile
docker/experimental/docker-bake-rust-all.hcl
docker/experimental/docker-bake-rust-all.sh
docker/experimental/faucet.Dockerfile
docker/experimental/forge.Dockerfile
docker/experimental/node-checker.Dockerfile
docker/experimental/telemetry-service.Dockerfile
docker/experimental/tools.Dockerfile

This PR makes some caching improvements to the experimental builder.
- Fixes the cache location for `CARGO_HOME`, which is located at `/usr/local/cargo` in the Rust Docker image. We want to cache only the registry and git directories. 
- Uses separate `CARGO_TAGET_DIR`s for different features/profiles to make caching more effective when building different images in parallel using the same builder pool.
- Increases the buildx buildkit GC config to use up to 900GB of storage (assuming 1TB of disk, currently provided by the experimental docker builder node pool)
- Mount GIT_CREDENTIALS as secret instead of copying it over into the image.
Latest build ran in ~13 mins.

[Dockerfile][Experimental] Caching improvements

---

consensus/src/counters.rs
consensus/src/liveness/proposal_generator.rs
consensus/src/payload_client.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/counters.rs
consensus/src/quorum_store/proof_coordinator.rs
crates/aptos-metrics-core/src/avg_counter.rs
crates/aptos-metrics-core/src/lib.rs

naive implementation had issues with sum and count counters not being pulled by metrics reporting at the same time. 
Looking at code Histogram has complicated special handling of it, that I don't want to repeat.

Undo being "smart" and creating AverageIntCounter, as it missaligns with counter dumping

---

crates/aptos/CHANGELOG.md
crates/aptos/src/common/init.rs
crates/aptos/src/common/utils.rs

If `aptos init` is run with a faucet URL specified (which happens by default when using the local, devnet, or testnet network options) and funding the account fails, the account creation is considered a failure and nothing is persisted. Previously it would report success despite the account not being created on chain.
Before
```
$ aptos init
Configuring for profile default
local
Enter your private key as a hex literal (0x...) [Current: None | No input: Generate new key (or keep one if present)]
No key given, generating key...
Account d43a9161565a1101ff11eb173de4eeebf9040b2365bc39e1fcbb2a24a0952395 doesn't exist, creating it and funding it with 100000000 Octas
Account …
```

[CLI] Exit if funding account fails when using aptos init with faucet

---

consensus/src/counters.rs
consensus/src/epoch_manager.rs
consensus/src/network.rs

Description
Currently, our consensus channel is a LIFO queue of size 1, which is because our consensus protocol only needs the latest message of any type from other peers. However, the buffer manager that receives the commit votes/decisions uses the same channel, which is problematic since there can be multiple messages for the buffer manager to receive.
This PR creates a separate channel (FIFO, larger size) for the buffer manager to receive the messages once the messages are received through the networking channel.
Test Plan
Existing smoke and forge tests.

[Consensus][Cherry-pick] Create a seperate channel for buffer manager

---

.github/workflows/docker-build-test.yaml
.github/workflows/workflow-run-docker-rust-build.yaml

Version the docker rust build like the other reusable workflows (referring to `aptos-core@main`). Also enable the `workflow_dispatch` trigger, which will allow workflows such as forge to be able to trigger it separately. This unlocks some cost savings via not building all image variants at once
Canary via separate PR: https://github.com/aptos-labs/aptos-core/pull/7332 to get around `pull_request_target`

[gha][docker] version docker-rust-build and enable workflow_dispatch

---

.github/actions/check-branch-commits/check_branch_commits.py
.github/actions/check-branch-commits/expected_on_devnet_not_main.txt
.github/actions/check-branch-commits/expected_on_mainnet_not_main.txt
.github/actions/check-branch-commits/expected_on_mainnet_not_testnet.txt
.github/actions/check-branch-commits/expected_on_testnet_not_devnet.txt
.github/actions/check-branch-commits/expected_on_testnet_not_main.txt
.github/workflows/check-branch-commits.yaml

This PR updates the commit checker to handle PR commit numbers in the git commit messages. This typically occurs when a commit is cherry-picked across various branches (resulting in commit messages that are similar, but not identical due to the PR numbers). The PR also updates the exception lists.

[Commit Checker] Handle PR commit numbers

---

aptos-move/framework/FRAMEWORK-PROVER-GUIDE.md
aptos-move/framework/tests/move_prover_tests.rs
aptos-move/move-examples/tests/move_prover_tests.rs

This PR makes prover tests regular by removing `#[ignore]` and adds error messages when the prover tools are not installed.

[Move-prover] Remove ignore annotation from prover tests

---

third_party/move/move-compiler/src/inlining/translate.rs
third_party/move/move-compiler/tests/move_check/inlining/acquires_error_msg.exp
third_party/move/move-compiler/tests/move_check/inlining/acquires_error_msg.move
third_party/move/move-compiler/tests/move_check/inlining/resources_invalid.exp
third_party/move/move-compiler/tests/move_check/translated_ir_tests/move/borrow_tests/borrow_global_acquires_missing_annotation.exp
third_party/move/move-compiler/tests/move_check/translated_ir_tests/move/borrow_tests/imm_borrow_global_requires_acquire.exp
third_party/move/move-compiler/tests/move_check/typing/missing_acquire.exp

This was caused by a regression inlining introduced, and no previous test case. Fixes the issue and adds a test case. Closes #7412.

[move compiler] Fix a bug with error messages introduced by inlining

---

developer-docs-site/docs/guides/aptos-name-service-connector.md

I shortened the header since it takes up two lines instead of one like in the other docs.

Optimize the Aptos Names Service doc header

---

storage/backup/backup-cli/src/coordinators/backup.rs
storage/backup/backup-cli/src/metadata/cache.rs
storage/backup/backup-cli/src/metadata/view.rs
storage/db-tool/src/tests.rs

Get a snapshot of remote metadata files before syncing the metadata file.
There is a corner case that syncing metadata file can run a long time and the snapshot of remote files can contain new files that are not covered by compaction
Test on GCP with compaction job and backup verify

[storage] Get metadata file list before syncing and downloading

---

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md

It was incorrectly referring to the module as `Debug` instead of `debug` (used to be correct, no longer) as well as saying you need to use the nursery package, which you don't need to do now.
CI.

[docs] Update docs explaining how to use debug statement in Move code

---

docker/experimental/build-node.sh

cd-ing into aptos-core and building there creates target directory within the repo. Avoid the cd-ing.
Tested locally.

[Dockerfile][Bug Fix] Fix indexer and failpoint builds

---

Cargo.lock
api/doc/spec.json
api/doc/spec.yaml
api/goldens/aptos_api__tests__state_test__test_get_account_module.json
api/src/tests/modules.rs
api/src/tests/move/pack_abi/sources/test.move
api/types/Cargo.toml
api/types/src/bytecode.rs
api/types/src/move_types.rs
aptos-move/aptos-vm/src/lib.rs
aptos-move/aptos-vm/src/verifier/view_function.rs
aptos-move/framework/src/module_metadata.rs
crates/aptos-protos/Cargo.lock
ecosystem/typescript/sdk/src/generated/models/MoveFunction.ts
ecosystem/typescript/sdk/src/generated/schemas/$MoveFunction.ts

This PR adds support for returning whether a function is a view function in the ABI returned from the API. While the better long term solution would be to cut out this intermediate ABI representation and directly enhance the ABI created as part of compilation, this provides this functionality in the short term by looking up the module metadata through the VM.
Run a local testnet:
```
```
See that view function information is attached:
```
curl localhost:8080/v1/accounts/0x1/module/coin | jq '.abi.exposed_functions[1]'
```
```
{
"name": "balance",
"visibility": "public",
"is_entry": false,
"is_view_function": true,
"generic_type_params": [
{
"constraints": []
}
],
"params": [
"address"
],
"return": [ …
```

[API] Expose whether a function is a view function via the ABI

---

developer-docs-site/README.md
developer-docs-site/package.json
developer-docs-site/pnpm-lock.yaml
developer-docs-site/scripts/README.md
developer-docs-site/scripts/contributors.js
developer-docs-site/src/contributors.json

Previously to make contributors.js work we maintained a map of emails to usernames for cases where the contributor email couldn't be used to figure out the username (this is only possible if the email ends with @users.noreply.github.com). With this PR, in addition to this map (which is unfortunately still partially necessary due to reasons I explain the comments), we use the GitHub GraphQL API to lookup usernames based on the contributor emails.
As you can see, the hardcoded map has been pared down because some emails are returned by the GraphQL query. 
Thanks to this PR you can see in `src/contributors.js` that a lot of usernames that were previously null are now filled in.
```
pnpm contributors
```

[docs] Look up email -> username map automatically

---

docker/experimental/docker-bake-rust-all.hcl
docker/experimental/docker-bake-rust-all.sh
testsuite/find_latest_image.py

Update the image finding for continuous tests to search for `validator-testing` by default, which is used in the default build which only builds `forge-images`.
Looks right based off of latest build and commit history:
```
$ python3 testsuite/find_latest_image.py --variant failpoints --variant performance                                                   
Finding latest aptos/validator-testing image with build variants: ['failpoints', 'performance']
With prefixes: ['failpoints_', 'performance_', '']
Found latest images: ['failpoints_6850dc44466f572a756b2ffac197db7befb12b87', 'performance_6850dc44466f572a756b2ffac197db7befb12b87', '6850dc44466f572a756b2ffac197db7befb12b87']
Exporting latest image as base GIT_SHA: 6850dc44466f572a756b2ffac197db7befb12b87
GITHUB_OUTPUT not set, not writing …
```

[scripts/docker] find latest validator-testing image and push remote

---

crates/aptos/src/node/mod.rs

Improving the error message to make it more obvious.
```
cargo build
```

[CLI] Improve error message when local testnet node fails to start

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/README.md
ecosystem/typescript/sdk/src/providers/aptos_client.ts
ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts
ecosystem/typescript/sdk/src/version.ts

Add User-Agent header to rest api calls 
test are passing
and
```
2023-03-30T23:23:08.657964Z [api-18] DEBUG api/src/log.rs:53 {"elapsed":"835.083µs","method":"GET","path":"/v1/accounts/0x1","remote_addr":"127.0.0.1:65273","status":200,"user_agent":"aptos-ts-sdk / 1.7.2"}
```

[TS SDK] add User-Agent header

---

Cargo.toml
crates/aptos-push-metrics/Cargo.toml

This PR adds the `aptos-push-metrics` crate to our workspace members. For some reason, it was missing (causing issues with dependabot).

[Crates] Add push metrics to workspace.

---

ecosystem/python/sdk/pyproject.toml

Remove mypy as a regular dependency and leaving it only as a dev-dependency, to prevent constraining the mypy version that can be used by downstream projects.
N/A

Remove mypy from production dependencies.

---

.github/actions/run-faucet-tests/action.yaml
.github/workflows/faucet-tests.yaml

We're seeing flakiness with these tests, and not just any flakiness, but the exact same kind of flakiness we used to get with the SDK tests before switching those to our own runners too. I believe it has something to do with an unsupported instruction set. It is also possible that some GH runners just can't spin up the container bc of resource limits or something. Regardless, moving to our own runners should fix this, as well as make the whole process faster anyway.
See that the faucet integration tests CI passes.

Run faucet tests on our own runners

---

crates/indexer/migrations/2023-04-02-032121_delegator_pools/down.sql
crates/indexer/migrations/2023-04-02-032121_delegator_pools/up.sql
crates/indexer/src/models/stake_models/delegator_pools.rs
crates/indexer/src/models/stake_models/mod.rs
crates/indexer/src/models/stake_models/stake_utils.rs
crates/indexer/src/models/stake_models/staking_pool_voter.rs
crates/indexer/src/processors/stake_processor.rs
crates/indexer/src/schema.rs

This is to get all delegated staking pools, even those that are empty. To get operator address, we'll take `delegated_staking_pools` and join to `current_staking_pool_voter`. 
https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Findexer-testnet.staging.gcp.aptosdev.com%2Fv1%2Fgraphql&query=query+DelegationPools+%7B%0A++delegated_staking_pools+%7B%0A++++staking_pool_address%0A++++current_staking_pool+%7B%0A++++++operator_address%0A++++%7D%0A++%7D%0A%7D%0A

[Indexer] Add delegator pool

---

.github/workflows/module-verify.yaml
storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs
storage/backup/backup-cli/src/coordinators/verify.rs
storage/db-tool/src/backup.rs
storage/db-tool/src/lib.rs
storage/db-tool/src/tests.rs
storage/db-tool/src/utils.rs
testsuite/module_verify.py

Avoids rebuilding the tree and writing to the DB, hence costs less / is faster.
https://github.com/aptos-labs/aptos-core/actions/runs/4601955211/jobs/8130405414

[db-tool] do module-validation from backup-verify instead of replay-verify

---

crates/aptos/src/account/fund.rs
crates/aptos/src/common/init.rs
crates/aptos/src/common/utils.rs

Previously `aptos init` would say the account was funded successfully without actually waiting for and checking the success of the transactions. This PR makes it wait and check.
See https://github.com/aptos-labs/aptos-core/pull/7561.

[CLI] Wait for the funding transactions in aptos init

---

consensus/src/block_storage/sync_manager.rs
consensus/src/quorum_store/batch_coordinator.rs
consensus/src/quorum_store/batch_store.rs
consensus/src/quorum_store/quorum_store_db.rs
consensus/src/quorum_store/tests/batch_store_test.rs
consensus/src/quorum_store/tests/quorum_store_db_test.rs
consensus/src/quorum_store/types.rs

Tests for QuotaManager and BatchStore interfaces for persisting & querying. Uncovered and fixed bug in QuotaManager (DB quota could have been exceeded by memory quota if requests arrived and freed in particular order).
Some refactoring to interfaces, e.g. seems like there is no need to have digest duplicated in PersistedRequest when it is already in BatchInfo, at which point PersistedRequest just becomes a type alias. Seems like simplifies code.

[QuorumStore] BatchStore tests / bugfix + refactors

---

crates/aptos/e2e/cases/init.py
crates/aptos/e2e/common.py
crates/aptos/e2e/test_helpers.py

In the tests we were using the `--skip-faucet` flag, which until https://github.com/aptos-labs/aptos-core/pull/7509 did not actually skip the faucet for a local network. Now that it works as intended, using it in these CLI tests is wrong.
Note: Even with this change, the tests are only fully correct if this PR also lands: https://github.com/aptos-labs/aptos-core/pull/7562.
First, make sure this PR is stacked on top of https://github.com/aptos-labs/aptos-core/pull/7562.
Build a CLI:
```
cargo build -p aptos
```
Run the e2e tests using that CLI:
```
DOCKER_DEFAULT_PLATFORM=linux/amd64 poetry run python main.py --image-repo-with-project us-west1-docker.pkg.dev/aptos-global/aptos-internal --base-network devnet --test-cli-path ../../../target/debug/aptos
```
See that they all pass now:
``` …
```

[CLI] Fix e2e tests following change to `--skip-faucet`

---

network/builder/src/builder.rs
network/src/peer/fuzzing.rs
network/src/peer/mod.rs
network/src/peer/test.rs
network/src/peer_manager/builder.rs
network/src/peer_manager/mod.rs
network/src/peer_manager/tests.rs
network/src/protocols/wire/messaging/v1/mod.rs
network/src/protocols/wire/messaging/v1/test.rs

Rate limiter is set to open, so essentially a no-op, but it relies on IpAddr for bucketing which means all the dns addr falls under the same bucket and would contend for the same mutex. This commit removes it from the stack.

[network] cleanup unused rate limiter

---

developer-docs-site/docs/issues-and-workarounds.md

This PR creates a section for the Move compiler in the troubleshooting doc. The first addition to the section mentions the `legacy_entry_fun` attribute to address [issue 6863](https://github.com/aptos-labs/aptos-core/issues/6863). As per @wrwg's wishes, I did not mention the associated error codes.

Introduce a compiler section to the troubleshooting doc

---

ecosystem/node-checker/src/provider/helpers.rs

Code example would require unreasonable amount of context to actually work, ignore it so that `cargo test --doc` can pass.
`cargo test --doc` passes now

ignore an example for `cargo test --doc` to pass

---

docker/experimental/tools.Dockerfile
docker/rust-all.Dockerfile

The tools image contains, among other things, the CLI. In order to use certain features of the CLI, such as `aptos move compile` or `aptos move publish`, you must have `git` locally to download dependencies such as the framework. The tools image does not contain `git` currently so it fails with this obscure error:
```
FETCHING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
{
"Error": "Unexpected error: Unable to resolve packages for package 'aptos_names'"
}
```
This PR fixes this issue by installing git in the image.
Note: I improve the situation with the error message in https://github.com/aptos-labs/aptos-core/pull/7585.
TBD, pending resolution of these issues: https://aptos-org.slack.com/archives/C04SLLXCC4F/p1680692026091619.

Install git in the tools image
