aptos-labs/aptos-core

.github/workflows/docker-build-test.yaml
Previously, we were running 4 (+1 consensus only test build) different docker image build jobs in parallel, only one of which is blocking (and is used in subsequent tests):
* `rust-images` -- the regular "release" images, used in SDK/docker and Forge e2e tests
* `rust-images-failpoints` -- builds with the "failpoints" feature for certain forge tests
* `rust-images-indexer` -- builds with the "indexer" feature for indexer releases
* `rust-images-performance` -- builds with the "performance" profile, generally used today for ad -hoc testing, but is intended to replace the regular release images 
* `rust-images-consensus-only-perf-test` -- builds the "release" profile but with `consensus-only-perf-test` feature, used for consensus-only testing
This PR makes it such that only the release …
=> [gha] refactor how non-blocking docker and forge tests are run

.github/workflows/faucet-tests.yaml
I recently landed https://github.com/aptos-labs/aptos-core/pull/7446 to make the faucet tests run on our own runners right? Wrong, I cooked the goose and did it for devnet but missed testnet. This explains why the testnet tests take 4 times longer and fail sometimes while the devnet ones don't.
CI.
=> Run faucet tests for testnet on high-perf-docker

.github/workflows/docker-build-test.yaml
bugfix for conditional docker builds. we still need to build all variants on push, since release uses it.
canary on push: https://github.com/aptos-labs/aptos-core/pull/7614
=> [gha] build all docker variants on push

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/e2e-move-tests/src/tests/common.rs, aptos-move/e2e-move-tests/src/tests/stake.data/enable_rewards_rate_decrease/Move.toml, aptos-move/e2e-move-tests/src/tests/stake.data/enable_rewards_rate_decrease/sources/main.move, aptos-move/e2e-move-tests/src/tests/stake.rs, aptos-move/e2e-move-tests/src/tests/transaction_fee.rs, aptos-move/framework/aptos-framework/doc/aptos_governance.md, aptos-move/framework/aptos-framework/doc/block.md, aptos-move/framework/aptos-framework/doc/consensus_config.md, aptos-move/framework/aptos-framework/doc/gas_schedule.md, aptos-move/framework/aptos-framework/doc/reconfiguration.md, aptos-move/framework/aptos-framework/doc/stake.md, aptos-move/framework/aptos-framework/doc/staking_config.md, aptos-move/framework/aptos-framework/doc/version.md, aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move, aptos-move/framework/aptos-framework/sources/block.spec.move, aptos-move/framework/aptos-framework/sources/configs/consensus_config.spec.move, aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move, aptos-move/framework/aptos-framework/sources/configs/staking_config.move, aptos-move/framework/aptos-framework/sources/configs/staking_config.spec.move, aptos-move/framework/aptos-framework/sources/configs/version.spec.move, aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move, aptos-move/framework/aptos-framework/sources/stake.move, aptos-move/framework/aptos-framework/sources/stake.spec.move, aptos-move/framework/aptos-stdlib/doc/fixed_point64.md, aptos-move/framework/aptos-stdlib/sources/fixed_point64.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/framework/move-stdlib/sources/configs/features.spec.move, types/src/on_chain_config/aptos_features.rs
- Support rewards decrease over time in `stake.move` and `staking_config.move`. This feature is gated by flag `REWARDS_RATE_DECREASE`.
- In the beginning, we can specify `rewards rate` every epoch . Every `rewards rate period`(which can only be 1 year at the moment), `rewards rate` will decrease at a configurable `decrease rate`.
Unit testing, move prover testing and E2E testing.
Move unit tests coverage:
```
Module 0000000000000000000000000000000000000000000000000000000000000001::staking_contract
>>> % Module coverage: 93.90
Module 0000000000000000000000000000000000000000000000000000000000000001::stake
>>> % Module coverage: 89.65
```
=> [Aptos Framework] Rewards Decrease over Time

aptos-move/framework/aptos-framework/doc/staking_contract.md, aptos-move/framework/aptos-framework/doc/storage_gas.md, aptos-move/framework/aptos-framework/doc/version.md, aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.spec.move, aptos-move/framework/aptos-framework/sources/configs/version.spec.move, aptos-move/framework/aptos-framework/sources/staking_contract.spec.move, aptos-move/framework/aptos-framework/sources/storage_gas.spec.move, third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
This PR revives the function-level pragma `verify_duration_estimate`, which indicates an estimate how long verification takes. Verification of this function will be skipped if the its timeout value is smaller than this. 
Close #7321.
=> [Move-prover][Spec] Revive the pragma verify_duration_estimate 

crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/lib.rs, crates/aptos-rosetta/src/types/move_types.rs
BTreeMap only works if the input was ordered at first.  If it's not ordered, then it will fail at deserialization.  Simple map isn't guaranteed to be ordered.
Tested directly against Rosetta
=> [aptos-rosetta] Fix all simple maps to be vector rather than Btreemap

consensus/consensus-types/src/block_retrieval.rs, consensus/src/block_storage/sync_manager.rs, consensus/src/network.rs
Block retrieval had no parallelism, was dropping responses from previous retries during new retries, etc.
Making it similar to batch_requestor
=> [consensus] Make block retrieval more aggressive

crates/transaction-emitter-lib/src/cluster.rs, crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-emitter/src/main.rs, crates/transaction-generator-lib/src/accounts_pool_wrapper.rs, crates/transaction-generator-lib/src/lib.rs
We were pinging one client at a time, and so it can take 10s of seconds to fetch all. And we only allowing for 10s of 10k traffic in between (Because we were comparing versions)
- fetch all in parallel
- compare onchain timestamp, so it is not affected by traffic
=> [txn emitter] Fix txn emitter client filtering

Cargo.lock, aptos-node/src/lib.rs, aptos-node/src/services.rs, config/src/config/network_config.rs, network/Cargo.toml, network/peer-monitoring-service/client/Cargo.toml, network/peer-monitoring-service/client/src/error.rs, network/peer-monitoring-service/client/src/lib.rs, network/peer-monitoring-service/client/src/logging.rs, network/peer-monitoring-service/client/src/network.rs, network/peer-monitoring-service/client/src/peer_states/key_value.rs, network/peer-monitoring-service/client/src/peer_states/latency_info.rs, network/peer-monitoring-service/client/src/peer_states/network_info.rs, network/peer-monitoring-service/client/src/peer_states/peer_state.rs, network/peer-monitoring-service/client/src/tests/multiple_peers.rs, network/peer-monitoring-service/client/src/tests/single_peer.rs, network/peer-monitoring-service/client/src/tests/utils.rs, network/peer-monitoring-service/server/Cargo.toml, network/peer-monitoring-service/server/src/error.rs, network/peer-monitoring-service/server/src/lib.rs, network/peer-monitoring-service/server/src/logging.rs, network/peer-monitoring-service/server/src/network.rs, network/peer-monitoring-service/server/src/storage.rs, network/peer-monitoring-service/server/src/tests.rs, network/peer-monitoring-service/types/Cargo.toml, network/peer-monitoring-service/types/src/lib.rs, network/peer-monitoring-service/types/src/request.rs, network/peer-monitoring-service/types/src/response.rs, network/src/application/metadata.rs, network/src/application/storage.rs
Note: this PR relates to: https://github.com/aptos-labs/aptos-core/issues/6789.
This PR adds server-side support for node information requests in the peer monitoring service. These requests gather basic peer information, including: (i) the git hash the peer is running on; (ii) the highest and lowest synced data versions; (iii) the latest ledger timestamp; and (iv) the peer uptime.
The PR offers two commits:
1. First, we add a new request and response type for node information data to the monitoring service. We also move some of the logic into different files to make it easier to find metadata, request data and response data.
2. Second, we add server-side support to handle node information requests, and add unit tests to verify the new functionality. Most of this commit is just …
=> [Peer Monitoring Service] Add server-side support for node info requests.

config/src/config/mod.rs, testsuite/smoke-test/src/rosetta.rs
This PR removes an unnecessary dependency on `PersistableConfig` from the rosetta smoke tests.
=> [Configs] Remove unnecessary dependency.

aptos-node/src/state_sync.rs, config/Cargo.toml, config/global-constants/src/lib.rs, config/src/config/base_config.rs, config/src/config/identity_config.rs, config/src/config/logger_config.rs, config/src/config/mod.rs, config/src/config/network_config.rs, config/src/config/quorum_store_config.rs, config/src/config/state_sync_config.rs, config/src/config/storage_config.rs, consensus/src/epoch_manager.rs, consensus/src/quorum_store/quorum_store_builder.rs, network/peer-monitoring-service/client/src/lib.rs, network/peer-monitoring-service/client/src/peer_states/latency_info.rs, network/peer-monitoring-service/client/src/tests/utils.rs, network/peer-monitoring-service/server/src/tests.rs, network/src/noise/mod.rs
This PR makes several small cleanups to the node configs (each in their own commit):
1. Remove legacy and unused global constants.
2. Move the base and identity configs into their own files/modules.
4. Added copy derives for appropriate structs (to reduce clone calls) and small cleanups.
Note: nothing should logically change in this PR.
=> [Configs] Small clean ups and improvements to node configs.

Cargo.lock, network/peer-monitoring-service/client/Cargo.toml, network/peer-monitoring-service/client/src/logging.rs, network/peer-monitoring-service/client/src/peer_states/key_value.rs, network/peer-monitoring-service/client/src/peer_states/mod.rs, network/peer-monitoring-service/client/src/peer_states/network_info.rs, network/peer-monitoring-service/client/src/peer_states/node_info.rs, network/peer-monitoring-service/client/src/peer_states/peer_state.rs, network/peer-monitoring-service/client/src/tests/multiple_peers.rs, network/peer-monitoring-service/client/src/tests/single_peer.rs, network/peer-monitoring-service/client/src/tests/utils.rs, network/peer-monitoring-service/server/src/storage.rs
Notes:
- Most of this PR is new tests.
- This PR is built on: https://github.com/aptos-labs/aptos-core/pull/7451.
This PR adds client-side support for node info messages. Specifically, it updates the peer monitoring loop to periodically send node info requests to peers to update their node metadata. The PR offers two commits:
1. Add client-side support for the node info messages to the peer monitor (this includes a new unit test).
2. Add more extensive integration tests for the node info messages (and perform various cleanups along the way).
Once this lands, we should have end-to-end support for node info messages.
=> [Peer Monitoring Service] Add client-side support for node info messages.

config/src/config/network_config.rs
This PR adds the `Copy` derive to the `NodeMonitoringConfig` struct to fix a genuine CI/CD semantic merge conflict.
=> [Config] Add Copy derive to Monitoring Config.

network/peer-monitoring-service/client/src/lib.rs, network/peer-monitoring-service/client/src/tests/multiple_peers.rs, network/peer-monitoring-service/client/src/tests/utils.rs
Notes:
- This PR is built on: https://github.com/aptos-labs/aptos-core/pull/7459.
This PR adds garbage collection to the peer monitoring client. Specifically, we remove peer states for peers that are no longer connected. The PR offers several commits:
1. Add garbage collection to the peer monitoring client for peer states.
2. Small refactors to the tests. Nothing should change logically.
New and existing unit tests.
=> [Peer Monitoring Service] Add garbage collection for peer states.

third_party/move/move-symbol-pool/src/pool.rs
Over the weekend I investigated some SIGSEGV I experienced and was looking at unsafe code in our code base as possible culprits. I encountered this which I initially thought must be wrong (Option<Box<Entry>> is type punned as an usize). It turns out that absolute compiler magic makes Option<Box<Entry>> the same size as usize, but I feel that kind of code is ridiculous.
The problem is that one cannot use [None, NB_BUCKETS] as Bucket == Option<Box<Entry>> is non-copyable, however one can simply work around that by using cont INIT: Bucket = None, and use INIT as initialization value.
This seems cleaner
=> Remove unsafe

crates/aptos/src/common/types.rs
We should be pulling the account address directly from the profile specified if exist. Instead of derive the account_address from private key
For more detail of the issue, please refer to issue #6666 
resolve #6666 
Tested locally to make sure it works even with key rotated. (Followed the same instruction from the issue described, and make sure publish successfully)
```
aptos-debug move publish --named-addresses TestCoinType=default2 --profile default2
BUILDING module_test
package size 970 bytes
Do you want to submit a transaction for a range of [17400 - 26100] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{ …
```
=> [CLI] Update load_account_arg to pull  account address directly if exist

.github/workflows/forge-gcp.yaml
Add workflow to run Forge tests on the GCP clusters.
Test via cron and with manual invocation.
=> Add hourly Forge-on-GCP continuous workflow

terraform/aptos-node-testnet/aws/main.tf, terraform/aptos-node-testnet/aws/variables.tf, terraform/aptos-node-testnet/gcp/main.tf, terraform/aptos-node-testnet/gcp/variables.tf
Propagate variables for toggling on and off monitoring features for testnets. Previously, these were available for `aptos-node`, and defaulted to `true` for all testnets.
TF plan and remove monitoring resources
=> [tf/aws/gcp][testnet] add variables for toggling monitoring

api/src/tests/objects.rs, aptos-move/e2e-move-tests/src/tests/token_objects.rs, aptos-move/framework/aptos-framework/doc/object.md, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/framework/aptos-token-objects/doc/aptos_token.md, aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/aptos_token.move, aptos-move/framework/aptos-token-objects/sources/collection.move, aptos-move/framework/aptos-token-objects/sources/token.move, aptos-move/framework/cached-packages/build.rs, aptos-move/move-examples/token_objects/sources/hero.move, ecosystem/python/sdk/aptos_sdk/account_address.py, ecosystem/python/sdk/aptos_sdk/aptos_token_client.py, ecosystem/python/sdk/examples/async-aptos-token.py
* Remove untracked collections from being public usage for now
* Add a mint and burn event for fixed supply
* Add tracking of both the collection id and the token's address to the events
* Add an unlimited supply to replace untracked
* Add support for minting deletable tokens
it is worth noting that untracked needs more thought:
* How to make them deletable as guid isn't parallelizable
* How to add events or create collection_ids
=> [framework] improve token mint, burn tracking

crates/aptos/src/common/utils.rs, crates/aptos/src/move_tool/mod.rs
@davidiw @gregnazario the proposed PR abstracts a common pattern in the CLI in accordance with [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) design principles.
=> [CLI] DRY out repetitive pattern for profile/submit txn

aptos-move/move-examples/mint_nft/4-Getting-Production-Ready/sources/create_nft_getting_production_ready.move, developer-docs-site/docs/concepts/txns-states.md, developer-docs-site/docs/guides/move-guides/book/package-upgrades.md, developer-docs-site/docs/guides/move-guides/mint-nft-cli.md, developer-docs-site/docs/guides/move-guides/move-scripts.md, developer-docs-site/docs/guides/move-guides/move-structure.md, developer-docs-site/docs/tutorials/first-move-module.md
And Link from Move Scripts to Modules and Scripts page of Move Book
=> Replace links to Move Book and Tutorial with Aptos variants

.github/workflows/docker-build-test.yaml
Re-land #5992 (revert the reverts). 
On top of that, it was missing an `always()` in each of the subsequent Forge jobs. This is because despite `rust-all` job runs, it will terminate there, unless subsequent jobs run on `always()` as well, since there *some* skipped jobs (docker build variants). Included comments inline since it's a bit unintuitive. 
always() ensures that the job will run even if some of the previous docker variant build jobs were skipped https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
So, we need the following conditional block for all Forge tests for example:
```
forge-e2e-test:
needs:
[rust-images, rust-images-failpoints, determine-docker-build-metadata]
if: | # always() ensures that the job will run even if some of the …
```
=> [gha] docker build conditional fix

aptos-move/aptos-sdk-builder/src/rust.rs, aptos-move/framework/cached-packages/build.rs, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs, aptos-move/framework/cached-packages/src/aptos_stdlib.rs, aptos-move/framework/cached-packages/src/aptos_token_objects_sdk_builder.rs, aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs, aptos-move/framework/cached-packages/src/lib.rs
This adds token v2 bindings to Rust for usage elsewhere.
Additionally, I had to add `too many arguments` ignoring, because one of the functions has too many in token objects.
=> [framework-builder] Add Token v2 bindings to rust

types/src/transaction/mod.rs
Module bundles are not the only way to publish modules. Entry functions can publish modules too.
=> Correct erroneous module bundle comments

developer-docs-site/docs/nodes/local-testnet/run-a-local-testnet.md
It seems the faucet-service cmd args were renamed and the example command does not work... Updating.
=> update the doc for local testnet

developer-docs-site/docs/concepts/staking.md
While reading these docs I found a couple of grammar / punctuation issues.
Docs.
=> Fix some typos in staking docs

crates/aptos/CHANGELOG.md, crates/aptos/src/common/init.rs
After user rotated their pri/pub key, and they try to use `aptos init` with the updated rotated private key. The account address is incorrect, because it is derived from pub/pri key pair.
This PR updates it by lookup the account address from Public key instead.
Related feature request #6295 
1. cargo build -p aptos
2. init with rotated key, and make sure account address is correct
`aptos-debug init --private-key 0x53f667f2b0aa149eb848023c919da16482855878ea9a0ac7cb131f7365612814 --profile rotation-test-3`
=> Update aptos init in CLI to lookup onchain address based on public key

aptos-move/framework/aptos-token-objects/doc/aptos_token.md, aptos-move/framework/aptos-token-objects/sources/aptos_token.move
To make the authorization check meaningful, `authorized_borrow` needs to take the `&signer` of the creator instead of `address` as an argument. Otherwise, one can always bypass it by calling `authorized_borrow(&token, token::creator(token))`.
The same reason goes to `authorized_borrow_collection`.
cargo test
=> Updated the authorization check in `aptos_token::authorized_borrow`

aptos-move/framework/aptos-token-objects/doc/property_map.md, aptos-move/framework/aptos-token-objects/sources/property_map.move
Cleans up some docs, fixes some wrong error codes, reordered errors to have some consistency.
Also, made some functions inline that were not used anywhere else, removed duplicate code.
`aptos move test`
Additionally, I ran coverage.  For some reason `source` mode bugs out, but there are the metrics.  Will likely want to add a test for the untested ones before it goes to prod.
```
+-------------------------+
| Move Coverage Summary   |
+-------------------------+
Module 0000000000000000000000000000000000000000000000000000000000000004::property_map
fun add
total: 221
covered: 199
% coverage: 90.05
fun add_typed
total: 136
covered: 123
% coverage: 90.44
fun burn
total: 6
covered: 0
% coverage: 0.00
fun contains_key
total: 19
covered: 0
% coverage: 0.00
fun generate_mutator_ref
total: 4 …
```
=> [aptos-framework] Cleanup Property map

developer-docs-site/docs/nodes/validator-node/operator/staking-pool-operations.md
While reading the doc I found some weird phrasing.
In this doc we were using `APT coins` and `APT tokens`. I changed both to just `APT`, but feel free @clay-aptos @saharct to change it to whatever is considered standard in the docs site.
Docs.
=> Fix grammar / typos in staking pool operations doc

third_party/move/documentation/examples/diem-framework/move-packages/DPN/sources/Diem.move, third_party/move/documentation/examples/diem-framework/move-packages/DPN/sources/DiemAccount.move
A recent [PR](https://github.com/aptos-labs/aptos-core/pull/7661) implements a more strict checking when inlining schema. This PR fixes existing specs that do not comply this checking. 
run `move prove` in `third_party/move/documentation/examples/diem-framework/move-packages/DPN`.
=> [Spec] Fix specs in DPM example

aptos-move/framework/aptos-token-objects/doc/aptos_token.md, aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/aptos_token.move, aptos-move/framework/aptos-token-objects/sources/collection.move, aptos-move/framework/aptos-token-objects/sources/token.move
Adds max sizes to URI, Description, and Name for both token and collection.  Additionally, standardizes naming of errors and adds documentation
```
Test result: OK. Total tests: 59; passed: 59; failed: 0
+-------------------------+
| Move Coverage Summary   |
+-------------------------+
Module 0000000000000000000000000000000000000000000000000000000000000004::royalty
>>> % Module coverage: 83.52
Module 0000000000000000000000000000000000000000000000000000000000000004::collection
>>> % Module coverage: 83.72
Module 0000000000000000000000000000000000000000000000000000000000000004::token
>>> % Module coverage: 81.29
Module 0000000000000000000000000000000000000000000000000000000000000004::property_map
>>> % Module coverage: 86.50
Module …
```
=> Cleanup tokenv2 collection

aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/sources/fungible_asset.move
Cleaned up fungible asset docs, as well as added
a max decimals check
```
BUILDING AptosFramework
Running Move unit tests
[ PASS    ] 0x1::fungible_asset::test_create_and_remove_store
[ PASS    ] 0x1::fungible_asset::test_e2e_basic_flow
[ PASS    ] 0x1::fungible_asset::test_merge_and_exact
[ PASS    ] 0x1::fungible_asset::test_metadata_basic_flow
[ PASS    ] 0x1::fungible_asset::test_supply_overflow
[ PASS    ] 0x1::fungible_asset::test_supply_underflow
[ PASS    ] 0x1::fungible_asset::test_transfer_with_ref
[ PASS    ] 0x1::fungible_asset::test_ungated_transfer
Test result: OK. Total tests: 8; passed: 8; failed: 0
+-------------------------+
| Move Coverage Summary   |
+-------------------------+
Module …
```
=> [aptos-framework] Cleanup fungible asset

testsuite/applogging.py, testsuite/find_latest_image.py, testsuite/forge.py, testsuite/lint.py, testsuite/lint_test.py
Move init_logging() to separate file and import it into all the CLIs.
$ FORGE_TEST_SUITE=land_blocking VERBOSE=true python3 testsuite/forge.py test
$ python3 testsuite/lint.py helm terraform/helm/*
$ python3 testsuite/find_latest_image.py --variant failpoints --variant performance
=> Fix logging init in lint.py and find_latest_image.py

Cargo.lock, Cargo.toml, storage/backup/backup-cli/Cargo.toml, storage/backup/backup-cli/src/utils/backup_service_client.rs
Not reproduceable locally, but in our k8s deployments, whenever the fullnode is killed, the backup coordinator hangs on the http connection (that streams in state snapshot chunks), resulting in large gaps between state snapshots (until we restart the backup pod). 
built image and tested on testnet backup deployment in aws -- prolbem is gone
=> [db-tool] backup-continuously: add read timeout to BackupServiceClient

crates/aptos-faucet/core/src/server/run.rs, developer-docs-site/docs/nodes/local-testnet/using-cli-to-run-a-local-testnet.md
`aptos init --faucet-url` wants http:// , so we should print it in node startup status
Ran a local node, was able to copy & paste faucet endpoint into `aptos init`
=> show faucet endpoint with http scheme

third_party/README.md, third_party/copy.bara.sky
This refines the methodology for pushing and pulling and updates the description, based on the recent experiences:
- Changes from pushing directly to github to pushing to local repos instead. This allows more control over subsequent operations like manual rebasing.
- Recommends to only push if `aptos-main` is in sync with `third_party`. This will eventually allows us to automate this.
- Details the procedure for pulling with subsequent rebase.
=> [copybara] Adjust workflows and update README

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml, crates/aptos/src/account/key_rotation.rs, crates/aptos/src/common/init.rs
Fixes a bug when `aptos init` for an account doesn't exist will fail immediately.
Before:
```
./target/debug/aptos init --profile test-init2
Aptos already initialized for profile test-init2, do you want to overwrite the existing config? [yes/no] >
^C
✘ greg@jiggy  /opt/git/aptos-core   main  ./target/debug/aptos init --profile test-init3
Configuring for profile test-init3
Enter your private key as a hex literal (0x...) [Current: None | No input: Generate new key (or keep one if present)]
No key given, generating key...
{
"Error": "API error: API error Error(AccountNotFound): Account not found by Address(0x33c88b2eb0bee2dc483525b5b89a0bf5f0bb710f3f3027baeb3b337eda1fe582) …
```
=> [cli] bugfix Lookup address on init 1.0.11 release

developer-docs-site/docs/concepts/gas-txn-fee.md
The docs mention that you can prioritize your txn by specifying a gas unit price, but it doesn't say what actually happens when you do that. This change clarifies that.
https://aptos-org.slack.com/archives/C03F71PU3B5/p1681464232985649
Docs.
=> Explain gas based prioritization in greater detail

crates/aptos/src/move_tool/mod.rs
Strings were being double BCS encoded, this fixes this
This now works
```
aptos move run --function-id '0x4::aptos_token::mint' --args 'string:test collection' 'string:' 'string:normal token' 'string:uri' 'vector<string>:size' 'vector<string>:u8' 'hex_array:00' --profile local`
```
=> [cli] Fix vector<string> input in the CLI

aptos-move/aptos-transaction-benchmarks/src/transactions.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/e2e-tests/src/account_universe/peer_to_peer.rs, aptos-move/e2e-tests/src/common_transactions.rs, aptos-move/e2e-tests/src/gas_costs.rs, aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs, aptos-move/e2e-testsuite/src/tests/genesis.rs, aptos-move/e2e-testsuite/src/tests/on_chain_configs.rs, aptos-move/e2e-testsuite/src/tests/peer_to_peer.rs
We weren't using aggregator in the block-stm benchmark for total supply, like it is used in the real system. It makes sense to enable by default. It obviously slows down the benchmark, but comparably for sequential and parallel runs, i.e. it most likely comes from handling the extra write-set item.
We need this to confirm the numbers prior to landing https://github.com/aptos-labs/aptos-core/pull/7400 - and also makes sense for automated runs (@danielxiangzl / @perryjrandall).
=> Use aggregators for p2p transactions in block-stm benchmarks

Cargo.lock
We have a transitive dependency on the `openssl` crate through the `kube` and `cloud-storage` crates. I was able to update us above the necessary version without updating any of those crates though just by running `cargo update -p openssl`, since they both just specify minor versions.
CI.
=> Update openssl crate

.gitattributes
I experience some strange behavior with the .ps1 Windows powerscript files in our repo when using tools like copybara. It appears those files line endings are auto-normalized on checkout, and then create a diff. This adjusts .gitattributes to turn off autoconversion for those files, in hope that it helps (not sure it does).
=> [git config] Do not normalize .ps1 line endings

scripts/rust_lint.sh
This PR fixes an edge-case in the rust_lint.sh script (where irrelevant untracked files are causing the lint to fail). This should hopefully fix it. 
=> [Rust Lint] Fix cached-packages failure.

Cargo.lock, config/src/config/peer_monitoring_config.rs, network/peer-monitoring-service/client/src/peer_states/node_info.rs, network/peer-monitoring-service/client/src/peer_states/peer_state.rs, network/peer-monitoring-service/client/src/tests/single_peer.rs, network/peer-monitoring-service/client/src/tests/utils.rs, network/peer-monitoring-service/server/src/lib.rs, network/peer-monitoring-service/server/src/tests.rs, network/peer-monitoring-service/types/Cargo.toml, network/peer-monitoring-service/types/src/response.rs
This PR makes several small improvements to the peer monitoring service (each in their own commit):
1. Update the peer monitoring service to share the build information for all peers (instead of just the git_hash). This should help improve build visibility in the wild west 😄 
2. Change the type of the connected peers map from HashMap to BTreeMap (not super necessary, but determinism makes life easier for debugging).
3. Add a message size limit on all peer monitoring messages to prevent malicious peers from forcing us to hold large messages in memory. The message limit is configurable (and defaults to 100KB), which should be more than enough for all messages (including the future messages for discovery).
=> [Peer Monitor] Add build info to the node info requests and max message sizes.

.gitattributes
This reverts commit bcf4da937930872cd2a8b7f51232d887919af1f5.
The line ending normalization is causing GH checkouts to contain spurious diffs in one Powershell file, which are causing workflows to fail.
Example: https://github.com/aptos-labs/aptos-core/actions/runs/4726884758/jobs/8386904529?pr=7806
=> Revert "[git config] Do not normalize .ps1 line endings"

aptos-node/Cargo.toml, aptos-node/src/logger.rs, config/src/config/logger_config.rs, config/src/config/node_config.rs, consensus/src/quorum_store/quorum_store_builder.rs, crates/aptos-logger/Cargo.toml, crates/aptos-logger/src/aptos_logger.rs, crates/aptos-logger/src/logger.rs, crates/aptos-logger/src/macros.rs, crates/aptos-logger/tests/tracing_translation_tests.rs
Note: this PR is based on: https://github.com/aptos-labs/aptos-core/pull/7706
This PR makes a few small fixes/tweaks to our configs and features for tokio-console. Specifically:
- Rename the `aptos-console` feature to `tokio-console` (this seems more descriptive, as all it's doing is enabling tokio console).
- Fix a build error with quorum store (i.e., trying to build with the console feature today results in an error). For example:
```
310 |             let name = format!("batch_coordinator-{}", i).as_str();
|                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^         - temporary value is freed at the end of this statement
|                        |
|                        creates a temporary which is freed while still in use
```
- Rename `console_port` to `tokio_console_port` in …
=> [Configs] Fix and update tokio-console features.

Cargo.lock, third_party/move/move-binary-format/Cargo.toml, third_party/move/move-binary-format/src/control_flow_graph.rs, third_party/move/move-bytecode-verifier/src/absint.rs, third_party/move/move-bytecode-verifier/transactional-tests/tests/control_flow/block_traversal_order_alias.exp, third_party/move/move-bytecode-verifier/transactional-tests/tests/control_flow/block_traversal_order_alias.mvir, third_party/move/move-bytecode-verifier/transactional-tests/tests/control_flow/block_traversal_order_hot_potato.exp, third_party/move/move-bytecode-verifier/transactional-tests/tests/control_flow/block_traversal_order_hot_potato.mvir
This ports the recent security patch that fixes the bug that would allow one to bypass the bytecode verifier partially.
=> [bytecote verifier] fix the abstract interpreter bypass bug

crates/aptos/CHANGELOG.md, crates/aptos/src/account/mod.rs, crates/aptos/src/account/multisig_account.rs, crates/aptos/src/common/types.rs, crates/aptos/src/lib.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/test/mod.rs
This adds the CLI commands for interacting with multisig accounts v2. The commands are
1. aptos multisig create --addtional-owners owner1,owner2 --num-signatures-required 2
2. aptos multisig create-transaction --multisig-address <multisig address> --function-id 0x1::multisig_account::add_owners --args address:owner3
3. aptos multisig approve --multisig-address <multisig address> --sequence-number <sequence number of tx to approve>
aptos multisig reject --multisig-address <multisig address> --sequence-number <sequence number of tx to approve>
4. Execute the next tx that has enough approvals: aptos multisig execute --multisig-address <multisig address>
5. Execute (effectively remove) the next tx that has enough rejections: aptos multisig execute-reject --multisig-address <multisig address> …
=> Add CLI support for multisig accounts (v2)

config/src/config/quorum_store_config.rs
We saw the network behaving erratically when sending 10 batches/s. With 100 validators, this means processing 1000 votes/s, in addition to other messages. 5 batches/s seems more reasonable (500 votes/s).
=> [Quorum Store] bump up default min interval for batch generation

Cargo.lock, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-generator-lib/src/lib.rs, execution/executor-benchmark/Cargo.toml, execution/executor-benchmark/src/fake_executor.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, execution/executor-benchmark/src/pipeline.rs
added support for --split-stages, and preparing to add transaction-generator-lib for generating workload
This replaces PR #6761, without removing BenchmarkTransaction. But still adding support to deserialize transactions for execution, as I'll be passing all transactions from  transaction-generator-lib with empty extra info information.
=> Added support for --split-stages in executor benchmark

config/src/config/quorum_store_config.rs
This is the value that was set in `preview`.
=> [Quorum Store] bump batch request num_peers=5

api/types/src/convert.rs, third_party/move/tools/move-resource-viewer/src/fat_type.rs, third_party/move/tools/move-resource-viewer/src/lib.rs
If there's a generic, the Fat type parsing didn't use the type from the type arguments, which caused it to fail to parse.  Now, this will take in the type arguments to properly parse the inputs.
I've done manual testing, I will add a unit test to properly test this.
Arguments now come out like this instead of hex encoded
```
"arguments":[{"inner":"0xb98022721f97da65950435386a5209be2fc54bed5f12fc8ea0a1c3d0c76f562f"},"Hello"]
```
=> [resource-viewer] Fix resolution of generics in move types

ecosystem/typescript/sdk/src/aptos_types/transaction.ts
The serialized multisig sig transaction payload has an extra enum value that indicates which type of payload the multisig tx contains (currently only entry function is supported, but support for script payload can be added in the future). serialize() correctly takes this enum into value but deserialize currently doesn't.
=> [SDK] Fix MultisigTransactionPayload deserialization

config/src/config/quorum_store_config.rs, consensus/consensus-types/src/common.rs, consensus/consensus-types/src/proof_of_store.rs, consensus/src/payload_manager.rs, consensus/src/quorum_store/batch_generator.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/proof_manager.rs, consensus/src/quorum_store/quorum_store_coordinator.rs, consensus/src/quorum_store/tests/proof_manager_test.rs, consensus/src/quorum_store/utils.rs, testsuite/forge-cli/src/main.rs
Add a per-author queue in proof manager. On proposal, proofs are taken in a (shuffled) round-robin of authors. This helps maintain some amount of fairness. For example, a single author that creates a huge backlog of proofs can't monopolize blocks if other proofs are also being received.
The per-author queue is prioritized. The tail is taken of the queue, which is sorted by gas bucket (ascending) and batch id (descending).
As a safeguard to spamming attacks, only a single proof can be stored at a time for a given batch.
Added unit tests, run three region overload tests.
=> [Quorum Store] fairness and priority in proposal via per-author queue

api/src/log.rs, api/src/runtime.rs, api/types/src/headers.rs
Turns out some browsers don't let you modify the User-Agent string so we need to use our own header to identify the client.
See also the PR that originally added this using the User-Agent string: https://github.com/aptos-labs/aptos-core/pull/7037.
Run local testnet:
```
```
Make a couple of requests with just curl:
```
curl http://127.0.0.1:8080/v1
curl http://127.0.0.1:8080/v1/accounts/0x1
```
Make a couple of requests with the header set, to which we just added the User-Agent stuff.
```
curl -H 'X-Aptos-Client: aptos-cli/1.0.11' http://127.0.0.1:8080/v1/accounts/0x1
```
See the metrics pushed appropriately, with `request-source-client-unknown` for the former and `aptos-cli/1.8.0` for the latter:
``` …
```
=> [API] Log aptos client based on a custom header rather than user agent

consensus/src/quorum_store/tests/types_test.rs, consensus/src/quorum_store/types.rs, testsuite/generate-format/tests/staged/consensus.yaml
The author in the payload will prevent a malicious validator from making the same payload as another validator, which has some theoretical attacks given our implementation.
=> [Quorum Store] Include author to transactions in digest

crates/aptos-faucet/integration-tests/local_testnet.py, crates/aptos/e2e/local_testnet.py
As it was it wasn't very clear why the local testnet setup was failing if Docker wasn't running. This makes it clearer.
Turn off Docker, then:
```
$ poetry run python main.py --base-network devnet --test-cli-tag devnet
2023-04-19 17:27:02,547 - INFO - Trying to run aptos CLI local testnet from image: aptoslabs/tools:devnet
2023-04-19 17:27:02,585 - ERROR - Failed to connect to Docker. Is it installed and running?
Traceback (most recent call last):
File "/Users/dport/a/core/crates/aptos/e2e/main.py", line 158, in <module>
if main():
File "/Users/dport/a/core/crates/aptos/e2e/main.py", line 117, in main
container_name = run_node(args.base_network, args.image_repo_with_project)
File "/Users/dport/a/core/crates/aptos/e2e/local_testnet.py", line 24, in run_node
subprocess.run(
File …
```
=> Confirm Docker is running in CLI and faucet e2e tests

aptos-move/framework/aptos-framework/doc/staking_config.md, aptos-move/framework/aptos-framework/sources/configs/staking_config.move
- Change `calculate_and_save_latest_epoch_rewards_rate` from public to public(friend).
- Make `aptos_framework::staking_config` a friend of `aptos_framework::stake`.
Unit testing.
=> Fix visability of calculate_and_save_latest_epoch_rewards_rate

.dockerignore, Cargo.lock, aptos-move/aptos-release-builder/Cargo.toml, aptos-move/aptos-release-builder/data/example.yaml, aptos-move/aptos-release-builder/data/proposals/empty.move, aptos-move/aptos-release-builder/data/proposals/empty_multi_step.move, aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/mod.rs, aptos-move/aptos-release-builder/src/lib.rs, aptos-move/aptos-release-builder/src/validate.rs, testsuite/smoke-test/Cargo.toml, testsuite/smoke-test/src/upgrade.rs, testsuite/testcases/src/framework_upgrade.rs
Updated the yaml file to track release for 1.4. A few modifications were made in the PR:
1. The validate-proposal command no longer mint to the validator. Tests now need to manually mint to validators before executing the proposals. This allows the tooling to better mimic what the release process will look like in real life.
2. Added the full 1.4 release configuration. Tentatively we will have five different goverance proposals to vote. We are still waiting on finalizing the fifth one to enable transaction reshuffling cc @zekun000 
3. Change the release tooling to be able to handle multiple proposals in one release conifg.
4.  Add the ability to include a customize script for the release builder
Framework upgrade test
=> [framework] Create release config for 1.4

terraform/fullnode/aws/main.tf, terraform/fullnode/aws/security.tf, terraform/helm/forge/templates/cleanup.yaml, terraform/helm/forge/templates/continuous_test.yaml, terraform/helm/fullnode/templates/backup-verify.yaml, terraform/helm/testnet-addons/templates/loadtest.yaml
* CronJob resources are no longer in beta: update the API ref in the K8s yaml.
* remove empty backend stanza that's causing spurious warnings
* fix reference to the K8s cluster version
Updated GCP mainnet/mainnet-backup/mainnet-backup-1 manually.
=> [TF] Fixes for PFNs

crates/aptos/e2e/README.md
There were couple information missing from readme. This diff updates it so it unblock people who were testing it.
```
➜  e2e git:(jin/add_account_lookup_by_auth_key) ✗ DOCKER_DEFAULT_PLATFORM=linux/amd64 poetry run python main.py --base-network testnet --test-cli-path ~/Projects/aptos-core/target/debug/aptos
2023-04-19 09:15:40,851 - INFO - Trying to run aptos CLI local testnet from image: aptoslabs/tools:testnet
testnet: Pulling from aptoslabs/tools
Digest: sha256:869c6981eb68858b3b71abf87cd488320caefce650721113422862badccdab78
Status: Image is up to date for aptoslabs/tools:testnet
2023-04-19 09:15:43,483 - INFO - Running aptos CLI local testnet from image: aptoslabs/tools:testnet
2023-04-19 09:15:43,484 - INFO - Waiting for node and faucet APIs for aptos-tools-testnet to come up …
```
=> [CLI e2e] update the e2e readme file for CLI

config/src/config/api_config.rs, config/src/config/config_sanitizer.rs, config/src/config/consensus_config.rs, config/src/config/execution_config.rs, config/src/config/inspection_service_config.rs, config/src/config/peer_monitoring_config.rs, config/src/config/safety_rules_config.rs, types/src/chain_id.rs
This PR makes a tiny tweak to the chain ID logic. Specifically, if a given chain ID does not match a named chain, we return `None` instead of throwing an error. This is helpful for node config sanitization in unknown chain ID environments.
=> [Configs] Tiny tweak to chain ID logic.

config/src/config/consensus_config.rs, consensus/src/counters.rs, consensus/src/liveness/proposal_generator.rs
Delaying proposal works nicer than reduction of block size, so use it for chain health backoff as well.
=> Use delaying proposal for chain health backoff as well

third_party/move/move-bytecode-verifier/src/verifier.rs, third_party/move/move-vm/runtime/src/interpreter.rs, third_party/move/move-vm/runtime/src/loader.rs, third_party/move/move-vm/runtime/src/logging.rs, third_party/move/move-vm/runtime/src/runtime.rs
To avoid speculative error logging, this commit only propagates the message back with the error type instead of directly print out. In following commit we'd need to make sure corresponding error messages are logged with speculative_error macro correctly.
=> [vm] propagate error message up instead of logging directly

state-sync/storage-service/server/src/handler.rs, state-sync/storage-service/server/src/logging.rs, state-sync/storage-service/server/src/metrics.rs, state-sync/storage-service/server/src/subscription.rs
This (tiny) PR adds peer network IDs to the error logs in the storage service. This will be helpful to better understand which peers are sending requests that may be invalid and/or fail.
=> [Storage service] Add peer IDs to error logs.

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/aptos_types/type_tag.ts, ecosystem/typescript/sdk/src/plugins/aptos_token.ts, ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts, ecosystem/typescript/sdk/src/tests/e2e/aptos_token.test.ts, ecosystem/typescript/sdk/src/tests/unit/builder.test.ts, ecosystem/typescript/sdk/src/tests/unit/test_helper.test.ts, ecosystem/typescript/sdk/src/tests/unit/transaction_builder.test.ts, ecosystem/typescript/sdk/src/tests/unit/type_tag.test.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts, ecosystem/typescript/sdk/src/transaction_builder/builder_utils.ts, ecosystem/typescript/sdk/src/utils/property_map_serde.ts
Move supports generic input params, and specifically two generic functions in tokenv2 `add_typed_property` and `update_typed_property`.
This PR adds support for 
- generic params in the SDK for when we build a transaction based on remoteABI or when users pass in bcs transaction payload. This is the first step to support other input params such as Option.
- The 2 generic entry functions in TokenV2, `add_typed_property` and `update_typed_property`.
**This PR needs to be merged after** https://github.com/aptos-labs/aptos-core/pull/7486
=> [TS SDK] Add support to generic params in entry functions

testsuite/forge-cli/src/main.rs
The config was replaced, but the helm_values was not updated leading to the validators crash-looping during these forge tests.
=> [forge tests] Unbreak forge consensus stress tests

.github/workflows/check-sdk-examples.yaml, .github/workflows/lint-test.yaml, .github/workflows/sdk-release.yaml, crates/aptos-faucet/ts-client/pnpm-lock.yaml, developer-docs-site/pnpm-lock.yaml, ecosystem/node-checker/ts-client/pnpm-lock.yaml, ecosystem/typescript/sdk/examples/typescript-esm/pnpm-lock.yaml, ecosystem/typescript/sdk/examples/typescript/pnpm-lock.yaml, ecosystem/typescript/sdk/pnpm-lock.yaml, pnpm-lock.yaml, scripts/dev_setup.sh
In https://github.com/aptos-labs/aptos-core/pull/7871 we want to update the pnpm version. This PR completes that, updating the version in `dev_setup.sh` and updating the lock files accordingly for all projects that use pnpm. We'll land this PR before #7871.
I tested that it works in the following places:
- /
- developer-docs-site/
- ecosystem/typescript/sdk
- ecosystem/typescript/sdk/examples/*
- crates/aptos-faucet/ts-client
- ecosystem/node-checker/ts-client
I found these by looking for `pnpm-lock.yaml` files.
CI unfortunately will fail as it is now because of this `pull_request` / `pull_request_target` thing, where it will run the tests using the old workflow description.
=> Bump pnpm version to 8.2.0

Cargo.lock, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-generator-lib/src/args.rs, crates/transaction-generator-lib/src/lib.rs, execution/executor-benchmark/Cargo.toml, execution/executor-benchmark/src/account_generator.rs, execution/executor-benchmark/src/db_generator.rs, execution/executor-benchmark/src/fake_executor.rs, execution/executor-benchmark/src/gen_executor.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, execution/executor-benchmark/src/pipeline.rs, execution/executor-benchmark/src/transaction_executor.rs, execution/executor-benchmark/src/transaction_generator.rs
* change executor benchmark from structopt to clap
* add --transaction-type flag to executor benchmark.
* add allow_discards and allow_aborts flags (asserting on those otherwise), and fixing commit to not panic when discards are present
* fixing to fetch sequence numbers for user accounts as well, and to fill accounts beyond main_signer_accounts to be used as burner accounts
* fixing GenInit executor to have StateCheckpoint as the last transaction for each block
=> executor benchmark improvements for the different transaction types

aptos-move/framework/aptos-framework/doc/vesting.md, aptos-move/framework/aptos-framework/sources/vesting.move, aptos-move/framework/aptos-framework/sources/vesting.spec.move
In the vesting contract at this address:
```
0x3de72a2e5d6a330b919ee6de9a6f51f6250c32b1385107c7b2db02bc82bfd587
```
You see this entry in the beneficiaries map:
```
{
key: "0x3168c3c9173a81f6923496649ef69995f79d10dee31cc5580b03057ce3a5b27f"
value: "0x385c76d283c205a1ac3b117fe059d39ef80c5d67bcb1a3b73a2e220f67130512"
}
```
Where key is the shareholder and value is the beneficiary.
You can see that the `shareholder` function works as intended:
```
$ aptos move view --url https://fullnode.mainnet.aptoslabs.com --function-id 0x1::vesting::shareholder --args address:0x3de72a2e5d6a330b919ee6de9a6f51f6250c32b1385107c7b2db02bc82bfd587 address:0xd36d942f6cc900178f981e5196e4a1e4e9bdc7ed760afd33ca5553a4cad83126
{
"Result": [
"0x31711902c817a6b8cd83c999320da2c1e328695cd879f6115995c3fff7a29ac1"
]
}
``` …
=> Make shareholder function handle both beneficiary and shareholder addresses to fix `accumulated_rewards` function

aptos-move/aptos-vm/src/lib.rs
So that runtime (i.e. benchmark runtime) can get access to TXN_GAS_USAGE to monitor GAS consumption (as StateComputeResult doesn't have gas information)
used in a stacked PR
open to alternatives, but this seems simplest.
=> Expose aptos-move counters outside the module

developer-docs-site/docs/move/book/creating-coins.md
The book contained an outdated link to an older version of the language tutorial.
=> [docs] Update link to the Move language tutorial

testsuite/forge-cli/src/main.rs, testsuite/testcases/src/consensus_reliability_tests.rs, types/src/on_chain_config/consensus_config.rs
Change the default of onchain ConsensusConfig to use V2, which turns on quorum store. This will allow all tests (unit, smoke, forge) to use quorum store, and new networks that do a genesis (forge, next previewnet).
Adjust forge tests to pass with quorum store enabled. In particular:
* Bump up maximum allowed TPS in backpressure for single-node tests.
* Ensure at least one validator that is receiving transactions is not injected failures in stress tests. (Because quorum store cannot obtain proofs while in an earlier epoch.)
* Add a new `land_blocking_three_region_test_suite` that is not enabled yet. It currently gets ~4K TPS.
Run continuous forge tests and ensure all previously passing tests still pass.
https://github.com/aptos-labs/aptos-core/actions/runs/4769819164
Note, …
=> [Quorum Store] Turn quorum store onchain config on by default 

.github/workflows/docker-build-test.yaml
I suspect that performance builds on main are being canceled because this complex concurrency group name is not working as intended but it seems very difficult to actually tell without logging it
So this logs that value so that we can see if it does what is intended on PR and main
Test plan: These is not a great way to test this afaik
=> [gha] Add debug line to check if concurrency is conflictingo

Cargo.lock, storage/backup/backup-cli/src/coordinators/backup.rs, storage/backup/backup-cli/src/metadata/cache.rs, storage/backup/backup-cli/src/metadata/mod.rs, storage/backup/backup-cli/src/metadata/view.rs, storage/backup/backup-cli/src/storage/local_fs/mod.rs, storage/db-tool/Cargo.toml, storage/db-tool/src/backup_maintenance.rs, storage/db-tool/src/tests.rs
Make backup compaction transparent to clients.
when the client loads metadata files, it will try to create a view of remote metadata files.
However, it could be inconsistent when the compaction is in progress as the metadata files are moved to a backup folder.
we keep the original file initially.
we use a timestamp to determine if non compacted file or outdated compacted file could be safely deleted
update test to show original files are kept and are eventually cleanup once the expiration date passed.
=> [storage] add timestamp to metadata for compaction and cleanup

.github/workflows/docker-build-test.yaml, .github/workflows/forge-stable.yaml
quorum-store branch no longer needs to be run continuously, as quorum store is now enabled by default.
=> [Quorum Store] remove continuous test quorum-store cadence

aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/doc/primary_fungible_store.md, aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/framework/aptos-framework/sources/primary_fungible_store.move, aptos-move/move-examples/fungible_asset/sources/coin_example.move, aptos-move/move-examples/fungible_asset/sources/managed_coin.move, aptos-move/move-examples/fungible_asset/sources/managed_fungible_asset.move
`ungated_balance_transfer` is long and counter intuitive. `frozen` is definitely much better as a name.
ut
=> [fungible_asset] rename ungated_transfer to frozen

crates/aptos-faucet/core/src/server/run.rs
This removes an assertion that prevents the faucet from being started twice in the same runtime.  Running the command `cargo test --package smoke-test --lib rosetta` locally prior to this change would fail every time on the `expect` statement.
Tested locally with Rosetta tests
```
$ cargo test --package smoke-test --lib rosetta
running 6 tests
test rosetta::test_network ... ok
test rosetta::test_invalid_transaction_gas_charged ... ok
test rosetta::test_block_transactions ... ok
test rosetta::test_transfer ... ok
test rosetta::test_account_balance ... ok
test rosetta::test_block has been running for over 60 seconds
test rosetta::test_block ... ok
test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 80 filtered out; finished in 78.66s
```
=> [faucet] Allow for running in multiple threads

.gitattributes
[Reopening as a branch]
This otherwise breaks flows like copybara.
Tested with a copybara migration that this prevents the problem.
=> [gitattributes] Ensure that powerscript files are not line-ending-auto-converted

aptos-move/framework/aptos-stdlib/doc/math128.md, aptos-move/framework/aptos-stdlib/doc/math64.md, aptos-move/framework/aptos-stdlib/sources/math128.spec.move, aptos-move/framework/aptos-stdlib/sources/math64.spec.move
The function spec_pow is not functioning as intended due to an incorrect ordering of its arguments.
=> [spec] Broken spec_pow function fix

aptos-move/framework/aptos-stdlib/doc/big_vector.md, aptos-move/framework/aptos-stdlib/doc/smart_vector.md, aptos-move/framework/aptos-stdlib/sources/data_structures/big_vector.move, aptos-move/framework/aptos-stdlib/sources/data_structures/big_vector.spec.move, aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.spec.move
Here we add specifications for `big_vector`. In particular, we specify
1. Critical data invariants about the structure of `big_vector`
2. Well-scoped `aborts_if` clauses 
The goal is for this to serve as a model for further data structure specifications. 
As an aside, we also note potentially confusing behavior with `table::spec_get`. It might make sense to add a `safe_spec_get` variant that checks for the existence of the key instead of returning garbage. 
Use the Aptos prover.
=> [prover] spec for `big_vector`

Cargo.lock, aptos-move/framework/Cargo.toml
**Problem:** Running `cargo test` inside `aptos-move/framework` is too slow due to the long build time of the `aptos-cached-packages` dependency.
**Bad solution:** Testing using the CLI is NOT faster than running `cargo test` when developing new Rust native functions because the entire CLI has to be recompiled to include the developed native functions.
**Proposed solution:** Remove `aptos-cached-packages` from `framework/`'s dependencies. What might go wrong? (No seriously, I actually don't know what might go wrong.)
=> remove unnecessary dependency in `aptos-move/framework/`

crates/aptos/CHANGELOG.md, crates/aptos/src/move_tool/mod.rs
This is a fun little PTO PR. While working on a side project on a plane I noticed that `aptos move test` doesn't work when you don't have internet because we don't actually respect the `--skip-fetch-latest-git-deps` flag. This PR fixes that.
While offline.
Before:
```
$ aptos move test --skip-fetch-latest-git-deps --named-addresses addr=0x1
BUILDING tontine
{
"Error": "Unexpected error: Unable to resolve packages for package 'tontine'"
}
```
After:
```
$ cargo run -p aptos -- move test --skip-fetch-latest-git-deps --named-addresses addr=0x1 --package-dir ~/github/aptos-tontine/move …
```
=> Fix flag to skip fetching git deps in aptos move test

aptos-move/e2e-move-tests/src/tests/token_objects.rs, aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/sources/collection.move, ecosystem/python/sdk/aptos_sdk/aptos_token_client.py
As it is called as `index` in token.move but not consistent with collection.move.
This PR has to be cherry-picked to v1.4
ut
=> fix all the collection_id to index

aptos-move/framework/Cargo.toml
`aptos move test --named-addresses hello_blockchain=default` is broken because of missing the testing feature enabled here.
aptos move test --named-addresses hello_blockchain=default
=> [cli] fix hello_blockchain test

developer-docs-site/src/components/MoveReference/index.tsx
noticed the original regex was too aggressive and stripping out content
=> [docs] make regex tighter for framework prints

crates/indexer/migrations/2023-04-27-233343_delegation_pool_balances/down.sql, crates/indexer/migrations/2023-04-27-233343_delegation_pool_balances/up.sql, crates/indexer/src/models/stake_models/delegator_balances.rs, crates/indexer/src/models/stake_models/delegator_pools.rs, crates/indexer/src/models/stake_models/stake_utils.rs, crates/indexer/src/processors/stake_processor.rs, crates/indexer/src/schema.rs
* Added delegator pool balances to track total delegated staking per period
* Added current delegator pool balances to track latest total coin / total shares per period (note that shares are divided by scaling_factor to avoid having ints that are too large for downstream services (e.g. bigquery)
* In delegator balances, rename amount to shares. To get amounts in APT we recommend joining against `current_delegated_staking_pool_balances` and doing the math of `shares / total shares * total coins` (to get latest balance)
Number checks out now
Also balances look legit
=> [Indexer] Add delegator pool balances and fix delegator balances

developer-docs-site/docs/tools/aptos-cli-tool/use-aptos-cli.md
@clay-aptos is there an additional place on the docs site where it may be appropriate to link to the [`optivanity`](https://github.com/econia-labs/optivanity) tool mentioned in this PR?
=> Add optivanity tool tip, multisig vanity example

.github/workflows/copy-images-to-dockerhub.yaml, docker/release-images.mjs
Cherry-pick https://github.com/aptos-labs/aptos-core/pull/7956
Fix the release to 1.4. It's currently blocked by an API change on the dockerhub side, and we've reverted from using `crane` to simply `docker pull && tag && push` to publish docker images
The failed job is here: https://github.com/aptos-labs/aptos-core/actions/runs/4832554942
=> [docker] release images without crane

aptos-move/aptos-release-builder/data/release.yaml
[framework] Change step names, remove quorum store for now
Test Plan: build with release builder
```
cargo run -p aptos-release-builder -- generate-proposals --release-config aptos-move/aptos-release-builder/data/release.yaml --output-dir /tmp/banana
```
=> [framework] Change step names, remove quorum store for now

.github/actions/docker-setup/action.yaml
Defaults to "true", keeping existing behaviour.
Next patch: https://github.com/aptos-labs/aptos-core/pull/7975
=> [Forge] Add input EXPORT_GCP_PROJECT_VARIABLES to actions/docker-setup

.github/workflows/workflow-run-forge.yaml
Depends on changes to actions/docker-setup that were already merged in https://github.com/aptos-labs/aptos-core/pull/7973.
Wrt. workflows dependencies, this commit does not affect development branches that are sync'd to commits prior to https://github.com/aptos-labs/aptos-core/pull/7973 because it references the workflows always at @main.
It *could* fail on dev branches which are so old that they lack #7646 (detect the cloud environment from the cluster name).
This is being tested in https://github.com/aptos-labs/aptos-core/pull/7971/commits, which adds a commit to redirect workflows to be PR-relative instead of @main.
A test run was manually triggered on [aptos-core](https://github.com/aptos-labs/aptos-core/actions/runs/4866458477/jobs/8678014311) and …
=> [Forge] Add GCP auth to reusable Forge workflow

.github/workflows/replay-verify.yaml
I think after more snapshots were put in the s3-public bucket, a run will finish under 12 hours but I don't want to accidentally waste another day, let's make it 14 hours for now.
=> add a little leeway to replay-verify timeout

aptos-move/move-examples/cli_args/Move.toml, aptos-move/move-examples/cli_args/sources/cli_args.move, crates/aptos/src/common/types.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/test/mod.rs, developer-docs-site/docs/tools/aptos-cli-tool/use-aptos-cli.md
@davidiw @gregnazario @movekevin
Addresses #7709 
* Implement recursive vector parsing for `ArgWithType`
* Abstract out `ArgWithTypeVec` field in accordance with [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) design principles
* Add Move example with multiple nested vector permutations
* Add CLI docs for running example Move code
Previously, the CLI was restricted to vector arguments with a maximum depth of 1, per the below syntax:
`vector<u8>:2,5,3`
Notably, this schema does *not* support doubly nested vectors of the form `vector<vector<u8>>`, as there is no way to delimit inner vectors.
However, since Move vectors must all use the same inner type, the new schema employs JSON array syntax of the form:
`"u8:[[1, 2], [], [4, 5, 6]]"`
Note here the use of quotes to escape …
=> [CLI] Add nested vector arg support, docs (#7709)

.github/workflows/workflow-run-forge.yaml
FORGE_RUNNER_DURATION_SECS is a number not a string and VSCode type checking caught it.
=> Fix type declaration in GH yaml

.github/workflows/forge-unstable.yaml
Run part of the forge-unstable workflows on GCP, pinning to cluster "gcp-forge-0".
Triggered manually: https://github.com/aptos-labs/aptos-core/actions/runs/4876839324.
=> [Forge] Run some of the unstable tests on GCP clusters

Cargo.lock, aptos-move/aptos-validator-interface/Cargo.toml, aptos-move/aptos-validator-interface/src/rest_interface.rs
The logic for getting values in resource group was broken in the validator-interface repo: there will be nothing under the struct tag if we are querying by resource group. To work around this temporarily,  I simulated the resource group behavior by fetching all the resources and return the superset blob back to caller. This is fairly ugly workaround which may require us add a better api for resource group in the future
Manually tested the debugger with a txn that read resource group and make sure it can be executed successfully.
=> [aptos-debugger] Fix resource group fetching

testsuite/forge/src/backend/k8s/swarm.rs
Temporary hack, we should figure out why Genesis doesn't finish within 10 minutes.
=> [Forge] Increase Genesis timeout from 10min to 20min

.github/workflows/forge-unstable.yaml, .github/workflows/workflow-run-forge.yaml, testsuite/fixtures/testMain.fixture, testsuite/forge.py, testsuite/forge_test.py, testsuite/forge_wrapper_core/cluster.py
Instead of hard-coding "us-central1-c" as GCP region, which prevents Forge from scheduling workloads on clusters in other regions, get a cluster's region by listing the clusters in the project.
This is a minimally invasive change to unblock the migration to GCP. A more long-term change should read the cluster list from gs://mushu/clusters.yaml and propagate other cluster properties from there (like region, chain name, etc...).
Remove the fetching of cluster credentials in workflow-run-forge.yaml because it's redundant: Forge will overwrite them anyway. This is backwards-compatible.
Tested manually by invoking the forge-unstable workflow on the PR branch: https://github.com/aptos-labs/aptos-core/actions/runs/4886592313.
=> [Forge] Avoid hardcoding GCP cluster location

execution/executor-types/src/executed_chunk.rs, execution/executor/proptest-regressions/tests/mod.txt, execution/executor/src/block_executor.rs, execution/executor/src/components/apply_chunk_output.rs, execution/executor/src/components/chunk_output.rs, execution/executor/src/components/in_memory_state_calculator_v2.rs, execution/executor/src/tests/mod.rs, storage/aptosdb/src/lib.rs, storage/storage-interface/src/lib.rs
- Add save_transaction_block.
- Change block executor to commit blocks one by one and use the new API.
- Change block executor to use InMemoryStateCalculatorV2.
Empty block, except reconfig suffix, will be rejected now.
=> Refactor block execute/commit pipeline.

developer-docs-site/docs/move/book/packages.md
This commit fixes a doc error in the bytecode dependency example and adds a clarification for requiring an empty `sources` folder in the Move package folder.
=> [doc] Fix the folder layout of the example in the section Using Bytecode for Dependencies

developer-docs-site/docs/nodes/leaderboard-metrics.md, developer-docs-site/docs/nodes/validator-node/operator/staking-pool-operations.md
On the leaderboard metrics documentation the link to validator stats wasn't updated when delegation nodes were added and inadvertently shows a page where most nodes are down. This PR updates the link to active validators on mainnet
An alternative would be to update default behavior of the explorer to all nodes instead of delegation nodes
https://explorer.aptoslabs.com/validators
vs
https://explorer.aptoslabs.com/validators/all
=> Leaderboard link defaults to delegation nodes as opposed to all nodes

Cargo.lock, Cargo.toml, aptos-move/aptos-debugger/src/lib.rs, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/adapter_common.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/move_vm_ext/resolver.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/aptos-vm/src/verifier/resource_groups.rs, aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs, aptos-move/aptos-vm/src/verifier/view_function.rs, aptos-move/framework/src/built_package.rs, aptos-move/framework/src/module_metadata.rs, aptos-move/vm-genesis/src/lib.rs, aptos-move/writeset-transaction-generator/src/writeset_builder.rs, aptos-utils/Cargo.toml, aptos-utils/src/lib.rs, third_party/move/move-vm/runtime/src/loader.rs
Reverts aptos-labs/aptos-core#8040
The cause was me deleting a feature flag at
https://github.com/aptos-labs/aptos-core/blob/cfecfb386614b708ada45ad81034a49be6fc33cf/aptos-move/aptos-vm/src/aptos_vm_impl.rs#L603
Me reasoning was that get_module_metadata works independently of the feature flag because it just looks up the existence of the V1 key. But the feature flag causes some metadata to be dropped for txn where the feature isn't activated yet but where the metadata is already V1
=> Revert "Revert "refactor a bit (#7918)""

.github/workflows/forge-stable.yaml
The aptos-node-v* branches are no longer in use.
=> [Forge] Remove obsolete branches from watch list of forge-stable.yaml

execution/executor-types/src/executed_block.rs, execution/executor/src/tests/mod.rs, storage/aptosdb/src/lib.rs
Should pass empty state updates for reconfig suffix blocks.
Also skip the state commit if the block is empty.
New UT.
=> [Fix] Handle reconfig suffix blocks.

terraform/aptos-node-testnet/gcp/main.tf, terraform/aptos-node-testnet/gcp/variables.tf, terraform/aptos-node/gcp/security.tf, terraform/aptos-node/gcp/variables.tf
The module uses data.kubernetes_all_namespaces to dynamically get the list of all namespaces, but that can only be done after a cluster has been turned up.
On cluster creation, TF attempts to connect to the K8s control place to fetch the list of namespaces, and fails.
The solution is to split cluster bootstrap in two phases. This is only necessary while we're in the middle of the migration from PSP to PSS.
Once all clusters have been upgraded to PSS and K8s version >=1.25, the bootstrapping dance can be removed.
Tested by turning up a GCP devnet.
=> [TF] Add variable "bootstrap_cluster" to GCP base module

docker/compose/validator-testnet/docker-compose.yaml
The docker compose for the local validator testnet needed an update to get in sync with changes in the code base. 
I've verified that it runs and the faucet transactions are validated by the validator
=> [docker] Update docker compose for validator testnet

config/src/config/peer_monitoring_config.rs, network/peer-monitoring-service/client/src/peer_states/network_info.rs, network/peer-monitoring-service/server/src/lib.rs, network/peer-monitoring-service/server/src/tests.rs
Note: most of this PR is just tests.
This PR offers several commits:
- Improve the logic around distance calculations for peers in the peer monitoring service. Specifically, extend the logic to support disconnected (or badly connected) validators and VFNs.
- Enable the monitoring client for test networks and devnet (but not testnet or mainnet).
Existing and new unit tests.
=> [Peer Monitor] Improve distance logic and enable client.

.github/PULL_REQUEST_TEMPLATE.md
As per internal discussion removing the github copilot pr annotations from the PR template due to noisyness and lack of usefulness on some PRs.
PR creators can still use the copilot annotations by adding manually `copilot: summary` etc. but it's not part of the template anymore
=> Revert "update PR template to enable AI summary by default (#7948)"

aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/doc/primary_fungible_store.md, aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/framework/aptos-framework/sources/primary_fungible_store.move, aptos-move/framework/aptos-token-objects/doc/collection.md, aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token/doc/token.md, aptos-move/move-examples/fungible_asset/sources/coin_example.move, aptos-move/move-examples/fungible_asset/sources/managed_coin.move, aptos-move/move-examples/fungible_asset/sources/managed_fungible_asset.move, aptos-move/move-examples/fungible_token/sources/managed_fungible_token.move
This adds a useful field - icon uri to the fungible asset standard. 
1. icon_uri: This is different from the uri in fungible tokens. A fungible asset might not want to be listed as a token but still wants an icon. And token usually has full image not icon.
Unit tests
=> Add icon_uri to fungible asset and update comments

docker/release-images.mjs
Add `faucet` to list of images to mirror to DockerHub nightly and on releases.
CI
=> [docker] release faucet image

docker/release-images.mjs
New crane release (https://github.com/google/go-containerregistry/releases/tag/v0.15.1) includes a fix for this issue (https://github.com/google/go-containerregistry/issues/1679, PR https://github.com/google/go-containerregistry/pull/1681). This fixes our mirror from GAR to DockerHub using `crane copy`, so we can switch back from using `docker pull && push`
Also minor change to how we're calculating checksums.
CI
=> [docker] release using crane after update 0.15.1

docker/experimental/tools.Dockerfile, docker/rust-all.Dockerfile
The lack of a pin is causing failures([example](https://github.com/aptos-labs/aptos-core/actions/runs/4942740670/jobs/8836548806
)) because apt likes to update all packages and fails to backtrack to older versions if some dependencies are pinned.
The long-term solution is to figure out a way to avoid pinning packages altogether, especially foundation packages like perl-base and libtinfo, because the pins are fragile and will break often.
=> [Docker] Pin also libtinfo6 Debian package

testsuite/forge-cli/src/main.rs
Need to dig deeper on why the fluctuation in TPS is so large, but for now reducing the thresholds to reduce noise. If these fail frequently, they can mask other issues.
=> [Forge] Adjust some of the thresholds that are flaky

Cargo.lock, execution/executor-types/src/executed_block.rs, execution/executor-types/src/in_memory_state_calculator.rs, execution/executor/src/block_executor.rs, execution/executor/src/components/apply_chunk_output.rs, execution/executor/src/components/in_memory_state_calculator_v2.rs, storage/aptosdb/src/fake_aptosdb.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/aptosdb/src/test_helper.rs, storage/storage-interface/Cargo.toml, storage/storage-interface/src/async_proof_fetcher.rs, storage/storage-interface/src/cached_state_view.rs, storage/storage-interface/src/lib.rs, storage/storage-interface/src/mock.rs
Produce state cache in a sharded way during block execution, and pass it to commit stage to save the read operations.
The improvements are various, depending on the traffic pattern.
In general, two improvements:
1. It eliminates the calculation to produce the sharded state cache, so in some benchmark (e.g. batch100-transfer with native vm, we see a 10+% speed up in execution phase).
2. It reduces the # of storage read at commit stage. (depending on the traffic pattern, the counter shows up to 70%+ of reduction)
Also see below for an account creation benchmark (0->20M), left side has this PR, right side is the baseline.
=> [Performance] Pass state cache to commit stage.

ecosystem/typescript/sdk/src/tests/unit/transaction_builder.test.ts
Add test to show `getSigningMessage` works as expected
=> [TS SDK] add test to get signing message

testsuite/single_node_performance.py
- we have split out move code into multiple packages, so loading individual packages got faster
- otherwise callibrate based on larger sample set than we originally had
- enable some of the new tests that have enough examples
- test correctly caught regression on one of the PRs - https://github.com/aptos-labs/aptos-core/actions/runs/4908726176, and it got resolved before landing.
=> [single node benchmark] calibrate thresholds based on v2 runs

.github/workflows/docker-update-images.yaml, scripts/update_docker_images.py
Fixes a bug in which the workflows exits with an error when it doesn't find new updates. This was caused by the python script returning an "error" exit code, which is interpreted by GHA as a failed action. The python script now always exits gracefully, and triggers the next step via its output.
The workflow runs when a pull request includes its source or the related script, and will produce an error if it doesn't pass.
=> Fix docker-update-images workflow

Cargo.lock, Cargo.toml, aptos-node/Cargo.toml, aptos-node/src/lib.rs, aptos-node/src/tests.rs, crates/aptos/src/node/mod.rs
Add `--config-override` flag to `aptos-node`, so we can override the default nodeconfig, which is especially useful when used with `--test`, since the single node testnet mode will auto-populate a lot of fields. This PR uses `serde_merge` to handle the merging and deserialization for us.
Run a local testnet and merge it with a config that enables indexer GRPC:
```
storage:
enable_indexer: true
indexer_grpc:
enabled: true
address: 0.0.0.0:50051
processor_task_count: 10
processor_batch_size: 100
output_batch_size: 100
```
Then start the node:
```
cargo run -p aptos-node -- --test --config-override test_config.yaml
```
The output NodeConfig and also the logs show that the GRPC endpoint is now working!
```
WARNING: Entering test mode! This should never be used in production!
Completed …
```
=> [aptos-node] add --config-override

aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/sources/fungible_asset.move
It's very common in Defi to have the follow pattern:
```
let zero = fungible_asset::zero(metadata);
while (some conditions) {
// Loop through a series of positions and calculate interest
let interest = fungible_asset::extract(&mut position, interest_amount);
// Take interest
fungible_asset::merge(&mut zero, interest);
}
```
It's very hard to do this without zero(). We can add the fungible assets to a vector and then merge them at the end but this is just unnecessarily extra work that costs extra gas (once to insert into a vector and another one when passing through to merge).
=> Add zero() to fungible_asset module

execution/executor/src/components/chunk_output.rs
This PR fixes consensus-only test breakage by implementing `execute_block_with_gas_limit` for the feature. It simply falls back to executing without gas limits.
consensus-only smoke test.
=> [consensus-only] fix gas_limit execution

crates/aptos-rosetta/src/client.rs, crates/aptos-rosetta/src/construction.rs, crates/aptos-rosetta/src/types/misc.rs, crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs, testsuite/smoke-test/src/rosetta.rs
Added the following functionality for delegation_pool::add_stake and delegation_pool::unlock in the Rosetta implementation:
- Parsing of operations
- Construction API / client support
Adding support to aptos-rosetta for `delegation_pool::add_stake` and `delegation_pool::unlock`.
Smoke tests
=> [aptos-rosetta] Support add / unlock for delegation pool

terraform/aptos-node-testnet/gcp/main.tf, terraform/aptos-node/aws/dns.tf, terraform/aptos-node/gcp/dns.tf, terraform/aptos-node/gcp/variables.tf
Add variable `var.create_dns_records` to control whether or not to create validator and fullnode specific DNS records directly on the first validator. These are only really useful in the case of deploying just a single validator/VFN, since there's 2 records that need to be created (one for validator and one for fullnode). It's simpler to create the record directly in TF rather than using an external dependency like external-dns.
Since we're hosting a bunch of validators and fullnodes for testnets, we'd want each one to have a DNS name. That's a use case for external-dns. So in testnets, set `create_dns_records = false`, and let external-dns handle the rest
Lint & apply, unblocking new devnet GCP deployment
=> [tf/gcp] add dns support  for GCP testnet

scripts/dev_setup.sh
Try to repro some network issues 
There's some nasty redirects in our .NET installation it turns out. Using `wget` instead of `curl` seems to fix it for the most part.
Sometimes it redirects back to https://dot.net/v1/dotnet-install.sh (which then errors out), and sometimes to https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh (the correct one)
Also set `-x` in `dev_setup.sh` when running in CI only. Don't set it when running on laptops since it will become too verbose.
Try `wget` and `curl` the URL a bunch of times. I'm able to repro the main issue like so:
```
for i in `seq 0 100`; do curl -Ls -o /dev/null -w %{url_effective} https://dot.net/v1/dotnet-install.sh && echo ; done
```
all the CI that relies on dev_setup.sh working on this PR, despite a spike in errors …
=> [scripts] make dev_setup.sh more resilient

.github/actions/fullnode-sync/action.yaml, .github/actions/fullnode-sync/fullnode_sync.py, .github/workflows/fullnode-execute-devnet-main.yaml, .github/workflows/fullnode-execute-devnet-stable.yaml, .github/workflows/fullnode-fast-mainnet-main.yaml, .github/workflows/fullnode-fast-mainnet-stable.yaml, .github/workflows/fullnode-fast-testnet-main.yaml, .github/workflows/fullnode-fast-testnet-stable.yaml, .github/workflows/fullnode-intelligent-devnet-main.yaml, .github/workflows/fullnode-output-mainnet-main.yaml, .github/workflows/run-fullnode-sync.yaml
Adds the `workflow_dispatch` trigger to the reusable workflow `Run Fullnode Sync` (`run-fullnode-sync.yaml`). This lets someone go to the UI to trigger it, with all the options like branch (or git ref), branch, bootstrapping/continuous-syncing mode, etc. like how each of the `fullnode-execute-{network}-{branch}.yaml` jobs call.
`gh` cli. It can also equivalently be run from the GHA UI
```
gh workflow run run-fullnode-sync.yaml --ref rustielin/fullnode-sync-gh -F=TEST_NAME=rustie-test -F=BRANCH=5d067dbbd9468397a7618b040a4306ee3a36c6d1 -F=NETWORK=devnet -F=BOOTSTRAPPING_MODE=ExecuteTransactionsFromGenesis -F=CONTINUOUS_SYNCING_MODE=ExecuteTransactions
```
it makes a run like this: https://github.com/aptos-labs/aptos-core/actions/runs/5008782115/jobs/8977013420
=> [gha] ability to call run-fullnode-sync from workflow_dispatch

Cargo.lock, execution/executor-types/src/in_memory_state_calculator.rs, execution/executor/src/components/in_memory_state_calculator_v2.rs, storage/aptosdb/src/fake_aptosdb.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/state_store/buffered_state.rs, storage/aptosdb/src/state_store/state_snapshot_committer.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/aptosdb/src/test_helper.rs, storage/storage-interface/Cargo.toml, storage/storage-interface/src/lib.rs, storage/storage-interface/src/state_delta.rs
Avoid the flatten in the save_transaction_block, and move it to the async state commit stage in the background (will also be removed later when the JMT calculation part is sharded). By removing it from foreground thread, it gives us 5%+ performance gain for commit (measured by account creation benchmark from 0 to 20M accounts).
=> [Execution/Storage][Sharding] Shard state updates in StateDelta.

network/src/connectivity_manager/mod.rs, network/src/connectivity_manager/test.rs, network/src/logging.rs, network/src/noise/fuzzing.rs, network/src/noise/handshake.rs, network/src/noise/mod.rs, network/src/noise/stream.rs, network/src/peer_manager/mod.rs, network/src/testutils/mod.rs, network/src/transport/mod.rs, network/src/transport/test.rs
Note: most of this PR is just new tests.
This PR fixes a bug in the network stack whereby VFNs connecting to validators are assigned the "Unknown" role, instead of the "ValidatorFullnode" role (as they should be). The PR also helps to improve role assignment logic, specifically that peer roles should always be assigned when a noise handshake completes (regardless of inbound or outbound origin). This is not currently the case.
To achieve this, the PR offers the following commits:
1. Update the peer role logic to assign VFNs the "ValidatorFullnode" role when connecting to validators.
2. Update the noise handshake code to assign peer roles during handshake time for outbound connections. This removes a workaround that assigns the role after the handshake is done.
3. Update the stale peer …
=> [Network] Fix bug in VFN role and improve role propagation.

terraform/aptos-node-testnet/gcp/main.tf, terraform/aptos-node-testnet/gcp/variables.tf, terraform/aptos-node/gcp/cluster.tf, terraform/aptos-node/gcp/variables.tf
* Google Container File System is a virtual file-system that allows lazy-mounting an image so that containerd can start running a container without having fully downloaded the image. The file-system will fetch on-the-fly only the data that is actually read.
* Google Virtual NIC is a virtual network interface specifically optimized for GCP, as an alternative to virtIO.
Will deploy first on the GCP devnet.
=> [TF] Add toggles for enabling GCFS and GVNIC on GCP

.github/workflows/docker-build-test.yaml, .github/workflows/docker-indexer-grpc-test.yaml, docker/compose/indexer-grpc/README.md, docker/compose/indexer-grpc/cache-worker-config.yaml, docker/compose/indexer-grpc/data-service-config.yaml, docker/compose/indexer-grpc/docker-compose.yaml, docker/compose/indexer-grpc/file-store-config.yaml, docker/compose/indexer-grpc/reset_indexer_grpc_testnet.sh, docker/compose/indexer-grpc/test_indexer_grpc_docker_compose.sh, docker/compose/validator-testnet/docker-compose.yaml, docker/compose/validator-testnet/validator_node_template.yaml
Edits the existing `validator-testnet` docker-compose:
* Enable indexer grpc in the default config. (Since this whole setup is for testing, it makes sense to just enable all features. If folks feel strongly, we can remove this and just add in a README to edit the config to enable indexer GRPC instead)
New `indexer-grpc` docker-compose, including:
* cache worker
* file store (with local filestore)
* data service
* redis
Mounts into existing docker compose networks, using static IPs. (We can re-evaluate getting rid of these static IPs, as they were only necessary when we faced docker networking issues in CircleCI)
A simple check is implemented in GHA that checks if we can connect to the indexer-grpc via `grpcurl`. For now (since the workflow is not landed in main yet), we test on …
=> [docker] add docker-compose for indexer-grpc

network/peer-monitoring-service/client/src/logging.rs, network/peer-monitoring-service/client/src/metrics.rs, network/peer-monitoring-service/client/src/peer_states/key_value.rs, network/peer-monitoring-service/client/src/peer_states/latency_info.rs, network/peer-monitoring-service/client/src/peer_states/mod.rs, network/peer-monitoring-service/client/src/peer_states/network_info.rs, network/peer-monitoring-service/client/src/peer_states/node_info.rs, network/peer-monitoring-service/client/src/peer_states/peer_state.rs, network/peer-monitoring-service/client/src/peer_states/performance_monitoring.rs, network/peer-monitoring-service/server/src/lib.rs, network/peer-monitoring-service/server/src/metrics.rs
Note: this PR is built on: https://github.com/aptos-labs/aptos-core/pull/8238.
This PR updates the metrics and logs for the peer monitoring service. Specifically, it offers two commits:
1. Cleans up the network ID label in the client and server metrics.
2. Adds new metrics to track the most obvious monitoring data, e.g., average ping latencies, distance from validators, number of connected peers and node uptime. We also periodically log this information.
=> [Peer Monitoring Service] Update metrics and logs.

Cargo.lock, Cargo.toml, storage/executable-store/Cargo.toml, storage/executable-store/src/lib.rs, types/src/executable.rs
To simplify the original Code Validation PR, extracted out a crate for ExecutableStore, a simple threshold-based prunable data-structure for caching, that can be re-used across pieces (blocks / chunks).
Implementation is defensive and asserts a number of state invariants, which if not satisfied, lead to the Cache being cleared and error logged. This ensures safety and observability (esp. in the early stages of development and deployment). This was done because currently important logic during integration is splattered around the codebase (will be improved in future refactors according to the target design), and it could be easy to have incorrect usage.
The cache allows concurrent operations during parallel execution (and post-parallel execution for cache update based on final …
=> Simple ExecutableStore cache with correctness controls

aptos-move/framework/aptos-framework/doc/fungible_asset.md, aptos-move/framework/aptos-framework/doc/primary_fungible_store.md, aptos-move/framework/aptos-framework/sources/fungible_asset.move, aptos-move/framework/aptos-framework/sources/primary_fungible_store.move, aptos-move/move-examples/fungible_asset/sources/coin_example.move, aptos-move/move-examples/fungible_asset/sources/managed_coin.move, aptos-move/move-examples/fungible_asset/sources/managed_fungible_asset.move, aptos-move/move-examples/fungible_token/sources/managed_fungible_token.move, aptos-move/move-examples/tests/move_unit_tests.rs
Project url is a very commonly used metadata field for fungible assets.
Unit tests
=> Add project_url to fungible asset metadata

aptos-move/framework/aptos-framework/doc/primary_fungible_store.md, aptos-move/framework/aptos-framework/sources/primary_fungible_store.move
if the object is not `Object<Metadata>` the next line will fail too.
But I want to make it more explicit.
ut
=> [fa] consolidate primary_fungible_store code

developer-docs-site/docs/nodes/nodes-landing.md, developer-docs-site/src/css/custom.css
Update custom.css to set the color of small text within list-group-item to black/white (depending on the selected theme). The page currently looks like a wall of turquoise-colored text. 
Before:
After:
=> Increase readability of nodes landing page

Cargo.lock, execution/executor/src/chunk_executor.rs, storage/aptosdb/src/backup/restore_handler.rs, storage/aptosdb/src/backup/restore_utils.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/state_restore/mod.rs, storage/aptosdb/src/state_restore/restore_test.rs, storage/aptosdb/src/state_store/buffered_state.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/backup/backup-cli/Cargo.toml, storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs, storage/backup/backup-cli/src/backup_types/tests.rs, storage/backup/backup-cli/src/backup_types/transaction/manifest.rs, storage/backup/backup-cli/src/backup_types/transaction/restore.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, storage/backup/backup-cli/src/coordinators/replay_verify.rs, storage/backup/backup-cli/src/coordinators/restore.rs, storage/backup/backup-cli/src/coordinators/verify.rs, storage/backup/backup-cli/src/utils/mod.rs, storage/db-tool/Cargo.toml, storage/db-tool/src/restore.rs, storage/db-tool/src/tests.rs, testsuite/smoke-test/src/genesis.rs, testsuite/smoke-test/src/storage.rs
To restore a database, provide a start version and end version with:
- All data restored, including state key values, write sets, state Merkle tree at the end version, and ledger info from genesis to generate a database with full data of a certain time frame.
- Fast, different from replaying transactions, decouple state key value commit from in-memory state Merkle tree updating.
Enhance the existing DB bootstrap to support both the latest DB restore and archive DB restore.
The user provides the arguments in the CLI with (ledger_history_start_version, target_version), specifying the range of the historical database they want to restore.
Depending on the snapshot version's order with user provided arguments, two scenarios may occur:
**Scenario 1: [snapshot_a, lhs, snapshot_b, target]**
1. …
=> [storage] Restore state kv in historical range

CODEOWNERS, aptos-move/aptos-vm-logging/src/lib.rs, aptos-move/aptos-vm-logging/src/log_schema.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/sharded_block_executor/executor_shard.rs
Should make sure that when we are in simulation, speculative logging doesn't introduce errors (no speculative storage), or swallow errors (if speculative execution is running concurrently).
Need a way to confirm this works as expected.
=> Determine speculation mode from LogSchema (+allow disabling for sharding experiments)

.github/workflows/docker-build-test.yaml, api/src/context.rs, config/src/config/gas_estimation_config.rs, storage/aptosdb/src/fake_aptosdb.rs, storage/aptosdb/src/lib.rs, storage/storage-interface/src/lib.rs, testsuite/smoke-test/src/rest_api.rs, types/src/on_chain_config/mod.rs
When doing gas estimation, add criteria for considering a block full if it has reached the gas limit. (Previously, only the txn count was considered.) The gas limit is read from the onchain execution config.
Added smoke test that relies on the gas limit block full value.
=> [Gas Estimation] Include gas used as a threshold for marking blocks full

crates/transaction-emitter-lib/src/emitter/account_minter.rs, crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, crates/transaction-generator-lib/src/call_custom_modules.rs, crates/transaction-generator-lib/src/entry_points.rs, crates/transaction-generator-lib/src/lib.rs, execution/executor-benchmark/src/db_reliable_submitter.rs, execution/executor-benchmark/src/lib.rs
cleanup follow-up from this comment - https://github.com/aptos-labs/aptos-core/pull/7651#discussion_r1164756699
=> [transaction-generator] Rename TransactionExecutor to ReliableTransactionSubmitter

config/src/config/gas_estimation_config.rs
This reverts commit 0d24ca3f2236b8d2e07ac693f9a068d1bcf6e191.
=> Revert "[Gas Estimation] enable v2 by default (#8325)"

consensus/src/state_computer.rs
Currently, the storage / consensus assumptions are not aligned, and there is a possible panic when new epoch starts and block_executor is initialized when setting the block gas limit. So temporarily disable the initialization and leave the gas limit to its default value (None), and revisit once there is an agreed solution.
=> [Executor] Temporary fix to disable gas limit init

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/providers/aptos_client.ts, ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts
Adds `x-aptos-client` header to REST calls. 
**Needs to be merged after** https://github.com/aptos-labs/aptos-core/pull/7797
- tested on Chrome, Safari, Brave and Edge browsers
- testes are passing
=> add x-aptos-client header

aptos-move/aptos-vm/src/sharded_block_executor/executor_shard.rs, aptos-move/aptos-vm/src/sharded_block_executor/mod.rs
Only disable speculative logging for sharded BlockSTM, to remove the speculative error loggings when running non-sharded BlockSTM (such as single-node-benchmark).
=> [Executor Logging] enable speculative logging

developer-docs-site/src/css/custom.css
Fixes anchor scroll position accounting for `position:sticky` header using [scroll-margin-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top) css property. 
https://github.com/aptos-labs/aptos-core/assets/98909677/8154cdd0-9bfa-4685-99d3-4c64ea20acc1
Eventually we should clean this up further - instead of placing empty `<a name="0x1_account_Account"></a>` above each section we should use `id` attached to every heading tag within our `.md` files like this:
`## [Some Aptos Heading](#some-aptos-heading)`
which would render:
`<h2 id="some-aptos-heading">Some Aptos Heading</h2>`
The reason for `id` instead of `name`: The `name` attribute for the `<a>` element is not supported in HTML5. While it still works in most browsers for backward compatibility, it's considered …
=> [docs] Fix Scroll Margin for Move Reference anchors

terraform/aptos-node-testnet/gcp/main.tf, terraform/aptos-node-testnet/gcp/variables.tf, terraform/aptos-node/gcp/cluster.tf, terraform/aptos-node/gcp/variables.tf
Reverts aptos-labs/aptos-core#8249
Enabling GCFS and GVNIC seems broken on Terraform so revert this for the moment.
If any of those two features are enabled, `terraform apply` will try to destroy and recreate the cluster every time. It seems that those protobuf fields are empty when `terraform refresh` reads the cluster state, so `apply` will assume they're missing and try to recreate the cluster.
=> Revert "[TF] Add toggles for enabling GCFS and GVNIC on GCP"

testsuite/forge-cli/src/main.rs, testsuite/forge/src/backend/k8s/cluster_helper.rs, testsuite/forge/src/runner.rs
If we're running locally, infer that we should port forward
Also clean up ForgeRunnerMode a bit, add tests
Test Plan: unittest + run locally
```
cargo run -- test k8s-swarm
```
=> [forge] Infer port_forward from local runner mode

Cargo.lock, aptos-move/aptos-aggregator/src/delta_change_set.rs, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/e2e-move-tests/src/tests/aggregator.rs
This PR avoids materializing deltas before running epilogue. Instead, ChangeSetStateView stores both writes and deltas. ChangeSetStateView materializes a delta into a write only if the aggregator is read in epilogue.
=> Avoid materializing delta set before epilogue

Cargo.lock, aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-vm/src/adapter_common.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/e2e-move-tests/src/tests/access_path_test.rs, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_module_dependency_fails_verification.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_module_transitive_dependency_fails_verification.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_script_dependency_fails_verification.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_script_transitive_dependency_fails_verification.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_type_tag_dependency_fails_verification.exp, aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_type_tag_transitive_dependency_fails_verification.exp, aptos-move/e2e-testsuite/Cargo.toml, aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs, aptos-move/e2e-testsuite/src/tests/invariant_violation.rs, aptos-move/e2e-testsuite/src/tests/mod.rs, aptos-move/e2e-testsuite/src/tests/verify_txn.rs, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs, types/src/transaction/mod.rs
Charges gas for TXNs that lead to an invariant violation error, when the feature flag is set.
Will need to decide if we need to enable this flag in the upcoming release.
Uses failpoint injection to make sure that:
1. With the flag enabled, an invariant violation error TXN will be kept and charged gas.
2. With the flag disabled, the TXN will be marked as discarded.
=> [aptos-vm] Charge invariant violation txn

aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/sources/multisig_account.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
@movekevin 
This PR adds two new functions to `multisig_account.move` for simultaneous updating owners and modifying the signature count. The remaining file changes are simply the result of auto-generated code from the Move modifications.
Without this PR, the multisig account flow prohibits owners from being added/removed in the same transaction as a required signature count update. However this presents a UX problem because typically modifications to the security group comes with a signature count requirement update. For example:
Consider a 4-of-7 multisig account that wishes to remove 3 signatories and go to 2-of-4. Before this PR, this modification would have to be broken down into two operations: if the signatory count is updated before removal, then the owners who are supposed to be …
=> [Multisig v2] Implement atomic add/remove owners with signature update funcs

Cargo.toml
Fat lto takes forever to compile, thin LTO acheives most of the benefit
with little additional compile time
Test Plan: other PR is perf neutral https://github.com/aptos-labs/aptos-core/pull/8376#issuecomment-1563623164
=> [lto] Use thin LTO instead of default fat

api/src/log.rs
The current regex does not match `aptos-ts-sdk/1.9.1` because it only expects a single `-` in the part before the `/`. This was an oversight because I tested it initially with just `aptos-cli`.
```
```
```
curl -H 'x-aptos-client: aptos-ts-sdk/7.8.9' http://127.0.0.1:8080/v1
```
```
curl -s http://127.0.0.1:9101/metrics | grep -i request_source
```
Before:
```
aptos_api_request_source_client{operation_id="get_ledger_info",request_source_client="unknown",status="200"} 2
```
After:
```
aptos_api_request_source_client{operation_id="get_ledger_info",request_source_client="aptos-ts-sdk/7.8.9",status="200"} 1
```
=> [API] Fix request client regex

aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/sources/multisig_account.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
@davidiw @movekevin 
The removed doc comments refer to parameters that are not present in the relevant function signatures.
The javadoc descriptions are particularly misleading given that they refer to data structures fundamentally different from what should be validly passed. Source: https://github.com/aptos-labs/aptos-core/blob/754cdf83ce4ef2db160397aca4b4c82058999278/ecosystem/typescript/sdk/examples/typescript/multisig_account.ts#L72-L92
=> Remove misleading javadoc for non-existent parameters

crates/indexer/migrations/2023-05-22-234344_delegated_staking_improvements/down.sql, crates/indexer/migrations/2023-05-22-234344_delegated_staking_improvements/up.sql, crates/indexer/src/models/stake_models/delegator_balances.rs, crates/indexer/src/models/stake_models/delegator_pools.rs, crates/indexer/src/models/stake_models/stake_utils.rs, crates/indexer/src/models/token_models/token_utils.rs, crates/indexer/src/models/token_models/tokens.rs, crates/indexer/src/processors/stake_processor.rs, crates/indexer/src/schema.rs
We currently support tracking active shares for each delegator in a staking pool. This PR adds tracking inactive shares as well. This is complex because inactive shares require an additional level of indirection.
* Staking pool -> active shares table -> delegator-share table item
* Staking pool -> inactive shares table -> pool table table item -> delegator-share table item
=> [indexer] Add inactive share tracking

Cargo.lock, aptos-move/aptos-vm/src/block_executor/mod.rs, consensus/Cargo.toml, consensus/src/counters.rs, consensus/src/epoch_manager.rs, consensus/src/experimental/ordering_state_computer.rs, consensus/src/lib.rs, consensus/src/state_computer.rs, consensus/src/state_replication.rs, consensus/src/test_utils/mock_state_computer.rs, consensus/src/transaction_deduper.rs, consensus/src/txn_and_authenticator_deduper.rs, consensus/src/txn_hash_and_authenticator_deduper.rs, types/src/on_chain_config/execution_config.rs, types/src/on_chain_config/mod.rs, types/src/transaction/mod.rs
Adding TransactionDeduper trait and an implementation. The dedup is done within a block, just before transaction shuffle. It's guarded by an onchain config.
The purpose is to not send duplicate transactions to execution. While execution correctness is not affected by duplicates (and other work removed false error logs that fired due to them), it's possible that duplicate transactions could hurt throughput of parallel execution. By deduping ahead of time, we don't have to worry about that.
The implementation finds duplicates by matching (raw txn bcs hash, signature). Because calculating hash can be relatively expensive, it is only done when a shallow match is found of (account, seq_no), and it's done in parallel.
Overhead (as seen on forge):
* When there are no duplicates, the dedup is …
=> [Execution] Add TransactionDeduper trait and implementation using (hash, signature)

.github/actions/release-aptos-node/action.yml, .github/actions/release-aptos-node/bump_aptos_node_version.py, .github/workflows/aptos-node-release.yaml
Create a workflow that bumps the version in the Cargo.toml and submits a PR to the relevant release branch. This makes sure that the output of `aptos-node --version` is consistent to the release it comes from.
NOTE: due to potential reordering etc of the TOML during formatting etc, just using regex to edit the version key in the file.
Unit tests
Also run the following in a separate playground repo:
```
APTOS_NODE_CARGO_TOML="aptos-node/Cargo.toml" RELEASE_TAG=aptos-node-v0.6.9 ./.github/actions/release-aptos-node/bump_aptos_node_version.py
```
Context: https://aptos-org.slack.com/archives/C054M887T0D/p1685478620958779?thread_ts=1685462406.648099&cid=C054M887T0D
=> [gha] release aptos-node version with workflow_dispatch

developer-docs-site/static/scripts/install_cli.py
This support was already mostly there, we just had to use it. This will be helpful for CI.
```
$ python3 developer-docs-site/static/scripts/install_cli.py --bin-dir /tmp
Latest CLI release: 1.0.14
Currently installed CLI: None
Determined target to be: MacOSX-x86_64
Welcome to the Aptos CLI installer!
This will download and install the latest version of the Aptos CLI at this location:
/tmp
Installing Aptos CLI (1.0.14): Downloading...
Installing Aptos CLI (1.0.14): Done!
The Aptos CLI (1.0.14) is installed now. Great!
To get started you need the Aptos CLI's bin directory (/tmp) in your `PATH`
environment variable.
Add the following to your shell configuration file (e.g. .bashrc):
export PATH="/tmp:$PATH"
After this, restart your terminal.
Alternatively, you can call the Aptos CLI …
```
=> Add support for setting installation path to CLI install script

aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/sources/multisig_account.move
@davidiw @movekevin @wrwg 
Presently `remove_owners` accepts an `owners_to_remove` vector that does not necessarily have any overlap with existing signatories. Hence it is possible to successfully invoke the removal operation without actually removing any owners, resulting in an empty event emission. To avoid the confusion of empty events, this PR adds a check against a correspondingly empty vector.
Pending the resolution of #5369 there is no way to test this logic (in a unit test context), which may explain why it went unnoticed until now.
=> [Aptos Framework] Add check on empty vector during removed multisig v2 owners event emission

Cargo.lock, aptos-node/Cargo.toml
This PR bumps the cargo version of aptos-node to 1.5, so that `./aptos-node --version` will return the correct version.
=> [Aptos Node] Bump cargo version of aptos-node to 1.5

testsuite/smoke-test/src/genesis.rs
With node can start from any version, we don't need to restore to a specific version
=> [storage] not set target_version 

.github/actions/get-latest-cli/action.yaml
This PR adds a GH action to install the CLI.
We could theoretically expand this to create a profile as well but I felt that made the action sort of complicated (just look at `aptos init`, it has a lot of flags we'd probably want to expose). We can chat about that though.
Depends on https://github.com/aptos-labs/aptos-core/pull/8446.
@brianolson tested this in internal-ops, thanks Brian!!
=> Add get-latest-cli action

.github/workflows/helm-lint.yaml, terraform/helm/fullnode/templates/backup-verify.yaml, terraform/helm/fullnode/templates/backup.yaml, terraform/helm/fullnode/templates/restore.yaml
So terraform apply doesn't blow away updates to these workloads through external means:
* restore job
* backup-verify cron
* backup stateful set
This has been done for validators, VFNs, and PFNs, but the `fullnode` chart also includes the above workfloads.
This unblocks some of the work @areshand need to do with updating the fullnode helm chart with compaction https://github.com/aptos-labs/aptos-core/pull/7375, as that will require a `helm upgrade`. We want to make sure that all workloads are unaffected by that.
Verify locally using kind.
1. create a helm values file `kind_local_fullnode.yaml` specifying image tag A for all workloads (fullnode, backup, backup_verify, restore)
2. verify that all workloads come up with the right tag
3. change the tags in the values file, and also change …
=> [helm][fullnode] add lookup for all workloads

types/src/on_chain_config/consensus_config.rs, types/src/on_chain_config/execution_config.rs
This only turns on for genesis (for devnet only), without a corresponding governance proposal for now.
=> [Devnet genesis] turn on txn dedup and quorum store at genesis

testsuite/forge/src/backend/local/swarm.rs
This makes it easier to inspect node logs after running a successful smoke test.
Example usage:
```
LOCAL_SWARM_SAVE_LOGS=1 cargo test --package smoke-test test_full_node_basic_flow -- --nocapture
```
The last logged line will have the location, e.g.,
```
Logs located at /var/folders/7h/r8yg843j0tl24vsc33ddl9s40000gn/T/.tmpHbbwHX
```
=> [Smoke tests] add an env variable to save node logs locally

Cargo.lock, aptos-node/src/state_sync.rs, config/src/config/state_sync_config.rs, state-sync/aptos-data-client/Cargo.toml, state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/latency_monitor.rs, state-sync/aptos-data-client/src/lib.rs, state-sync/aptos-data-client/src/logging.rs, state-sync/aptos-data-client/src/metrics.rs, state-sync/aptos-data-client/src/poller.rs, state-sync/aptos-data-client/src/tests/mock.rs, state-sync/aptos-data-client/src/tests/mod.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/driver_factory.rs
Note: most of this PR is just tests.
This PR adds a new latency monitor to state sync, which tracks a number of important syncing latencies. This will help us to better understand, debug and improve overall end-to-end latencies in the system. The latencies now being tracked, are:
1. **Propose to sync**: The time taken from when a transaction was included in a proposed block (i.e., block timestamp), until it is eventually synced by the node.
2. **Propose to seen**: The time taken from when a transaction was included in a proposed block (i.e., block timestamp), until it is seen by the state sync data advertisements (but not necessarily synced).
3. **Seen to sync**: The time taken from when a transaction is seen by the state sync data advertisements, until it is synced.
New and existing unit …
=> [State Sync] Add latency monitor.

crates/aptos-faucet/cli/src/main.rs, crates/aptos-faucet/core/src/funder/common.rs, crates/aptos-faucet/core/src/funder/mint.rs, crates/aptos-faucet/core/src/funder/transfer.rs, crates/aptos-faucet/core/src/server/run.rs, crates/aptos-faucet/integration-tests/README.md, crates/aptos-faucet/integration-tests/local_testnet.py
> We should change the LB timeout back to 30 seconds and decrease the sleep duration from 30 seconds to 15 seconds. This way the seqnums will reset prior to the LB giving up and it’ll happen sooner than it does now.
> We should also decrease the expiration secs on the txn from 30 seconds to 10 seconds, the E2E latency on the txns should never be above 10 seconds. This is the value we generally use everywhere else (e.g. in the Rust and TS SDKs).
More information here: https://aptos-org.slack.com/archives/C05ATSJJCSV/p1685609837398169?thread_ts=1685606365.531029&cid=C05ATSJJCSV.
E2E tests in CI.
=> [Faucet] Make outstanding txn wait duration configurable, update defaults

ecosystem/python/sdk/aptos_sdk/async_client.py, ecosystem/python/sdk/aptos_sdk/client.py, ecosystem/python/sdk/aptos_sdk/metadata.py
poetry run isort .
poetry run black .
=> [Python SDK] Fix linting

state-sync/storage-service/server/src/handler.rs, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/metrics.rs, state-sync/storage-service/server/src/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/optimistic_fetch.rs
Note: this PR is based on: https://github.com/aptos-labs/aptos-core/pull/8402
This PR makes two small tweaks to the storage service metrics:
1. Replace "protocol" with "network_id" for various metrics. Protocol is not really useful anymore 😄
2. Add a new metric to track optimistic fetch latencies.
=> [Storage Service] Small tweaks to metrics.

crates/aptos/e2e/README.md, crates/aptos/e2e/cases/init.py, crates/aptos/e2e/common.py, crates/aptos/e2e/local_testnet.py, crates/aptos/e2e/main.py, crates/aptos/e2e/pyproject.toml, crates/aptos/e2e/test_helpers.py, crates/aptos/e2e/test_results.py
Currently the metrics of the node are inaccessible because the metrics port on the container is not published. This PR fixes that and tests for it.
```
poetry run python main.py --base-network mainnet --test-cli-tag mainnet
```
See CI also.
=> [CLI][E2E] Expose metrics port of local testnet node

crates/aptos/e2e/cases/account.py, crates/aptos/e2e/cases/init.py, crates/aptos/e2e/main.py
Add custom header "aptos-cli" checking e2e
```
➜  e2e git:(jin/add_e2e_for_aptos_header) ✗ DOCKER_DEFAULT_PLATFORM=linux/amd64 poetry run python main.py --base-network testnet --test-cli-path ~/Projects/aptos-core/target/debug/aptos
2023-06-01 15:18:34,453 - INFO - Trying to run aptos CLI local testnet from image: aptoslabs/tools:testnet
testnet: Pulling from aptoslabs/tools
Digest: sha256:e2cd216dcd7225546ba47caadd8d6cbe34508028988eba474145bd3032320c15
Status: Image is up to date for aptoslabs/tools:testnet
2023-06-01 15:18:42,202 - INFO - Running aptos CLI local testnet from image: aptoslabs/tools:testnet
2023-06-01 15:18:42,202 - INFO - Waiting for node and faucet APIs for aptos-tools-testnet to come up
2023-06-01 15:18:58,505 - INFO - Node and faucet APIs for aptos-tools-testnet came …
```
=> [CLI] Add customer header checking to e2e

.github/workflows/docker-build-test.yaml, developer-docs-site/docs/reference/glossary.md
Let's generically define these terms to consider current and future ways of creating fungible assets. We can rephrase or add a bullet if more specificity is needed, but we should first work toward clarifying any confusion within the standards docs.
=> Define fungible asset, token, and unit in the glossary

crates/aptos-faucet/cli/src/main.rs, crates/aptos-faucet/core/src/funder/common.rs, crates/aptos-faucet/core/src/server/run.rs
Based on https://github.com/aptos-labs/aptos-core/actions/runs/5149399311/jobs/9272587458?pr=7533 it seems like, especially for use in CI, I lowered the txn expiration too low. This PR adjusts them. For the standard case I don't change the values completely back to what they were but when the faucet is used from the CLI (for a local testnet) they're back to what they were.
Let's see how it goes in CI.
=> [Faucet] Adjust faucet txn expiration / seqnum related values

aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/bencher.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/block-executor/src/view.rs, aptos-move/mvhashmap/src/lib.rs, aptos-move/mvhashmap/src/types.rs, aptos-move/mvhashmap/src/unit_tests/mod.rs, aptos-move/mvhashmap/src/unit_tests/proptest_types.rs, aptos-move/mvhashmap/src/unsync_map.rs, aptos-move/mvhashmap/src/utils.rs, aptos-move/mvhashmap/src/versioned_data.rs, aptos-move/mvhashmap/src/versioned_modules.rs, testsuite/sequential_execution_performance.py, types/src/executable.rs
Isolating more changes from the ExecutableStore support adventure in easier to review PRs (https://github.com/aptos-labs/aptos-core/pull/7873/files#diff-8a3b172f46266133eecd1c04ba084071b6d0cc9998813e3f45d4a2ba22676a24).
Mainly refactoring, and introducing unsync_map, MVHashMap equivalent for sequential execution replacing bare BTreeMap so that it can also cache (hash-based / in-block) executables. As per comments from the big PR, baseline ExecutableCache will be passed to the MVHashMap view so base level executable caching will be similar to going to storage for blobs when data is not in MVHashMap.
=> [Executor] MVHashMap changes for ExecutableStore

ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/lib.rs, ecosystem/indexer-grpc/indexer-grpc-file-store/src/lib.rs, ecosystem/indexer-grpc/indexer-grpc-integration-tests/src/tests/fullnode_tests.rs
This was accidentally re-introduced after https://github.com/aptos-labs/aptos-core/pull/8250 landed
CI, after which point we should make the `Build+Test Docker Images / indexer-grpc-e2e-tests (pull_request_target)` test land-blocking
=> [indexer-grpc] remove server_name from all configs

.github/workflows/docker-build-test.yaml, .github/workflows/workflow-run-docker-rust-build.yaml, docker/builder/docker-bake-rust-all.hcl, docker/builder/docker-bake-rust-all.sh
`TARGET_REGISTRY` is determined in GHA based on the workflow trigger, and passed through to the docker bake file, which determines the image (tags) to push.
`TARGET_REGISTRY` can be:
* local -- doesn't push
* remote -- just the default, pushing to all supported internal remote docker repos
* gcp -- just to GAR
This saves us some time during the post-build image export phase, around 2min. So around 15% cost savings on the docker build pipeline
```
gh workflow run workflow-run-docker-rust-build.yaml --ref rustielin/docker-images-gar-only-on-pr -F=GIT_SHA=$(git rev-parse HEAD)  -F=TARGET_REGISTRY=gcp 
```
https://github.com/aptos-labs/aptos-core/actions/runs/5158877766/jobs/9293093246
```
gh workflow run workflow-run-docker-rust-build.yaml --ref rustielin/docker-images-gar-only-on-pr …
```
=> [gha][docker] only push to GAR on PR; push to ECR on postcommit

.github/workflows/build-node-binaries.yaml
This makes our builds available mirroring what we do for hotfix release
Test Plan:
Added a clause to run on PR, remove that before landing
https://github.com/aptos-labs/aptos-core/actions/runs/5159644124
=> [release] Add workflow to build release binaries

crates/aptos-rosetta/src/account.rs, crates/aptos-rosetta/src/types/identifiers.rs, crates/aptos-rosetta/src/types/misc.rs
Implement the delegator address balances rosetta endpoint.
The rosetta client should manage its own delegator and pool address relationship when fetching relevant data.
The request payload should look like this (added the metadata field under sub_account_identifier):
```
"account_identifier": {
"address": "0x899d44dca988af7895cdc9828ae0e7f6c5c42d74fa1610e693fb5f613cb8c09a", // owner/delegator address
"sub_account": {
"address": "active_stake", // string active
"metadata": {
"pool_address": "0xbd50bb20e1972747db365c3a6e31255d78867c6b8df9877ea6054bb335dd6031" // pool_address
}
}
}
```
**About balance fetching**:
Using delegator address [0x65b1e4d62e803d7e3a5c715baa33391757ae530c9fef287bf2d7d15c1ea6e3e6](https://explorer.aptoslabs.com/account/0x65b1e4d62e803d7e3a5c715baa33391757ae530c9fef287b …
=> rosetta delegator address balances

.github/workflows/docker-build-test.yaml, .github/workflows/workflow-run-docker-rust-build.yaml, docker/builder/docker-bake-rust-all.hcl, docker/builder/docker-bake-rust-all.sh
Reverts aptos-labs/aptos-core#8500
due to it breaking forge jobs
=> Revert "[gha][docker] only push to GAR on PR; push to ECR on postcommit"

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml
Releasing a CLI with changes to the faucet txn expiration times.
Just bumped release number.
=> [CLI] Bump version to 2.0.1

terraform/fullnode/gcp/cluster.tf, terraform/helm/fullnode/templates/backup-verify.yaml
When Node Auto-provisioning (NAP) is installed on the GKE cluster, use the serviceaccount created in the module, rather than leaving it unspecified, which defaults to the default GCE service account.
Also, fix an indentation issue with the fullnode backup/backup_verify/restore workloads, when specifying an affinity, such as for NAP (specifying a machine family)
Apply
=> [tf/gcp][fullnode] make NAP use PFN service account

terraform/aptos-node-testnet/aws/variables.tf, terraform/aptos-node-testnet/gcp/addons.tf, terraform/aptos-node-testnet/gcp/main.tf, terraform/aptos-node-testnet/gcp/variables.tf, terraform/aptos-node/gcp/cluster.tf, terraform/aptos-node/gcp/dns.tf, terraform/aptos-node/gcp/kubernetes.tf, terraform/aptos-node/gcp/outputs.tf, terraform/aptos-node/gcp/security.tf, terraform/aptos-node/gcp/variables.tf, terraform/aptos-node/gcp/versions.tf, terraform/helm/aptos-node/values.yaml, terraform/helm/testnet-addons/templates/ingress.yaml, terraform/helm/testnet-addons/templates/service.yaml, terraform/helm/testnet-addons/values.yaml
* add variable to control the record TTL and lower the default from 1h to 5min, as the rest of the records on GCP
* add variable *create_dns_records* to the testnet module as well, to be useable from the devnet module
Tested on the new GCP Devnet.
=> [TF] More fixes for GCP DNS

aptos-move/aptos-gas/src/gas_meter.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/move_vm_ext/resolver.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, third_party/move/extensions/async/move-async-vm/tests/testsuite.rs, third_party/move/move-core/types/src/resolver.rs, third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs, third_party/move/move-vm/runtime/src/data_cache.rs, third_party/move/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs, third_party/move/move-vm/test-utils/src/storage.rs, third_party/move/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
Reopening https://github.com/aptos-labs/aptos-core/pull/8474
=> Update gas metering

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/utils/api-endpoints.ts
local development for indexer is not widely used and it is a bit annoying to need to set it whenever we want to use local node
=> [TS SDK] make indexerUrl as an optional param

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/framework/aptos-framework/doc/reconfiguration.md, aptos-move/framework/aptos-framework/sources/reconfiguration.move, aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move
The current feature flags component of release builder is using the wrong (newly added) reconfigure function. We have an existing one in aptos_governance that was added before mainnet for precisely this purpose and should be used instead.
=> Update release builder to use the correct reconfigure function

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/indexer/generated/operations.ts, ecosystem/typescript/sdk/src/indexer/generated/queries.ts, ecosystem/typescript/sdk/src/indexer/generated/types.ts, ecosystem/typescript/sdk/src/indexer/queries/getCollectionsWithOwnedTokens.graphql, ecosystem/typescript/sdk/src/indexer/queries/getOwnedTokens.graphql, ecosystem/typescript/sdk/src/indexer/queries/getTokenOwnedFromCollection.graphql, ecosystem/typescript/sdk/src/providers/indexer.ts, ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts
Add query to fetch all collections that an account has tokens for. supports v1 and/or v2 standards
=> [TS SDK] Add query to fetch all collections that an account has tokens for

aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/sources/multisig_account.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
@davidiw @movekevin @wrwg 
This PR includes modifications to `multisig_account.move` with additional autogen file changes.
Functionality includes assorted convenience functions for multisig v2 owner schema modifications, and an abstracted inner function (`update_owner_schema`) in accordance with [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) design principles)
=> [Aptos Framework] Add multisig v2 owner helpers, abstractions

terraform/aptos-node-testnet/aws/variables.tf, terraform/aptos-node-testnet/gcp/variables.tf
The monitoring chart is no longer used internally, but we keep it because it might be used by partners.
=> [TF] Disable the monitoring Helm chart by default

crates/aptos-ledger/src/lib.rs
Mark `aptos-crypto` and `aptos-types` pub, so public user can import it as well
=> [aptos-ledger][Easy] mark crypto and types public

terraform/aptos-node-testnet/gcp/addons.tf, terraform/helm/testnet-addons/README.md, terraform/helm/testnet-addons/templates/ingress.yaml, terraform/helm/testnet-addons/values.yaml
Also, rename the Helm values to be similar to the ones in pfn-addons.
=> [TF] Use a ManagedCertificate for testnet-addons ingress

Cargo.lock, api/test-context/src/test_context.rs, consensus/src/state_computer.rs, execution/executor-benchmark/src/native_executor.rs, execution/executor-benchmark/src/transaction_executor.rs, execution/executor-test-helpers/src/integration_test_impl.rs, execution/executor-types/Cargo.toml, execution/executor-types/src/lib.rs, execution/executor/Cargo.toml, execution/executor/src/block_executor.rs, execution/executor/src/chunk_executor.rs, execution/executor/src/components/chunk_output.rs, execution/executor/src/db_bootstrapper.rs, execution/executor/src/fuzzing.rs, execution/executor/src/mock_vm/mod.rs, execution/executor/src/tests/chunk_executor_tests.rs, execution/executor/src/tests/mod.rs, execution/executor/tests/db_bootstrapper_test.rs, execution/executor/tests/storage_integration_test.rs
This PR introduces the `ExecutableBlock`, which contains a vector of transactions in case of unsharded execution and a vector of sub-blocks in case of sharded execution and updates the block execute APIs accordingly. There is no functionality change introduced - later PR will start using the sharded APIs. 
Existing UTs.
=> [Execution][Sharding] Changes to block execution API to be able to pass sharded sub-blocks

testsuite/forge-cli/src/main.rs, testsuite/forge/src/runner.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/tests/forge-local-compatibility.rs, testsuite/testcases/tests/forge-local-performance.rs
Currently, all tests need to be statically defined, which precludes using any utility function for their creation, creating dynamic objects (like vectors), etc. Boxing everything, resolves this issue
=> Remove static from ForgeConfig

Cargo.lock, consensus/src/dag/mod.rs, consensus/src/dag/reliable_broadcast.rs, consensus/src/dag/tests/mod.rs, consensus/src/dag/tests/reliable_broadcast_tests.rs, consensus/src/lib.rs, consensus/src/network_interface.rs
This commit introduces an abstracted reliable broadcast concept, it's responsible to keep trying sending message until either it aggregates enough ack or it's cancelled.
=> [dag] reliable broadcast

terraform/aptos-node/gcp/variables.tf
Terraform will complain that the default is null.
The default maintenance window is Monday-Friday, between 7am and 11am Pacific time.
=> [TF] Add default for GKE maintenance window

aptos-move/aptos-gas/src/lib.rs, aptos-move/aptos-gas/src/transaction/mod.rs, aptos-move/aptos-gas/src/transaction/storage.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs
Mainly to make it clear:
1. do not load `storage_gas_params` if there's no global `gas_params`
2. only override certain table gas parameters with io gas parameters when pricing v2 is active (for now it's equivalent to that there is the storage gas schedule stored on chain; gonna change after we deprecate the curves)
and make the above logic all exposed in `new()` (instead of partially under `StorageGasParams::new()`
started full replay run here
https://github.com/aptos-labs/aptos-core/actions/runs/5212425745
=> clean AptosVmImpl::new() up a bit

.github/workflows/cli-e2e-tests.yaml, .github/workflows/docker-build-test.yaml, crates/aptos/e2e/main.py, crates/aptos/e2e/test_helpers.py
This PR adds all the framework / CI changes that were originally in https://github.com/aptos-labs/aptos-core/pull/8550 and https://github.com/aptos-labs/aptos-core/pull/8517. This way this PR is just framework / CI stuff and the others are just test cases.
CI.
I tested with `uses: ./.github/workflows/cli-e2e-tests.yaml` with `pull_request` at first to make sure it works.
=> [CLI][E2E] Improve reliability of framework, checkout correct code in CI

testsuite/testcases/src/modifiers.rs, testsuite/testcases/src/multi_region_network_test.rs
This PR fixes a bug where some tests remove all chaoses, but it only should remove those that the test adds.
Multi-region test now succeeds properly.
```
two traffics test: inner traffic : committed: 5967 txn/s, latency: 6540 ms, (p50: 6300 ms, p90: 7800 ms, p99: 12600 ms), latency samples: 2589920
two traffics test : committed: 100 txn/s, latency: 2559 ms, (p50: 2400 ms, p90: 3000 ms, p99: 4500 ms), latency samples: 1820
Max round gap was 1 [limit 4] at version 655404. Max no progress secs was 3.913393 [limit 10] at version 655404.
Test Ok
```
=> [forge][fix] Track and remove chaos properly

crates/aptos-telemetry-service/src/prometheus_push_metrics.rs, crates/aptos-telemetry/src/sender.rs
This PR should fix a bug with telemetry service that causes metrics push requests to take a long time to complete. The issue is:
First, there is no timeout on the client side. This can affect the 15-second cadence to send metrics periodically to telemetry service. A 5-second timeout has been added on the client-side.
Second, the server waits for all backend push metrics API calls to complete either successfully or fail. This is problematic because the API calls themselves have reties associated with failures, so waiting on all the backend calls means waiting on the slowest call. To fix this, we will wait for a timeout and decide as success if any of the backend calls have succeeded.
There is now a limit on maximum retry duration of 10 seconds on the node-side and the metrics are dropped …
=> [telemetry-svc][bug-fix] Add timeouts for requests

terraform/aptos-node-testnet/gcp/variables.tf, terraform/aptos-node/gcp/variables.tf
We want to keep the maintenance window defaults to match GKE defaults because this template could be used by anyone to deploy nodes. We will override them for our nodes internally.
=> [terraform][gcp][testnet] make default daily 24h

.github/workflows/merge-gatekeeper.yaml
Try out merge gatekeeper (https://github.com/upsidr/merge-gatekeeper)
This will allow us to get close to target determination in our monorepo, if we use it in conjunction with modified GHA triggers that only run certain checks when certain file paths are changed.
Just check out the workflow output for now. We can run the merge gatekeeper in parallel with the rest of our CI without side effects, so long as we don't change the branch protection to require it.
=> [gha] set up merge gatekeeper

.github/actions/docker-setup/action.yaml, .github/workflows/workflow-run-forge.yaml, testsuite/fixtures/testPossibleAuthFailureMessage.fixture, testsuite/forge.py, testsuite/forge_test.py
Since the migration to GCP long duration forge jobs have been failing.
I looked at this with Rustie and initially we were stumped.
The code that determines the success is based on fetching the phase of the pod that is running the job, if the phase == "succeeded" then pass skip etc or anything else fail.
When looking at the debugging output (which had auth failure) I realized that the status check could possibly have auth failure as well.
This lead me to the auth duration, which is default to 1.5hr previously in aws forge we had a longer expiration by default!
So this PR addresses this by setting the auth expiration to double the runner duration.
I also add a little error handling in case someone hits this again
Test Plan: unittest + run the test on this branch
=> [forge] Fix long running job failure

.github/workflows/merge-gatekeeper.yaml
fix errors like this: https://github.com/aptos-labs/aptos-core/actions/runs/5246875935/jobs/9476292130?pr=8613
since you can't run the `gh` CLI without being in a git repo
=> [gha] fix merge gatekeeper with checkout

Cargo.lock, storage/scratchpad/Cargo.toml, storage/scratchpad/benches/sparse_merkle.rs
Use jemalloc for sparse merkle tree benchmark, and a few other tweaks.
=> sparse-merkle-tree bench update

state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/tests/new_transaction_outputs.rs, state-sync/storage-service/server/src/tests/new_transactions.rs, state-sync/storage-service/server/src/tests/new_transactions_or_outputs.rs, state-sync/storage-service/server/src/tests/utils.rs
This PR adds a simple wait to the optimistic fetch test cases. This should hopefully help to reduce some test flakes (where the test runner thread runs faster than the optimistic fetch handler).
=> [Storage Service] Add simple wait to optimistic fetch tests.

config/src/config/consensus_config.rs, testsuite/forge-cli/src/main.rs
=> Forge test for testing throughput on network purely tuned for throughput

aptos-node/src/storage.rs, config/src/config/storage_config.rs, execution/executor-benchmark/src/db_generator.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, storage/aptosdb/src/db_debugger/checkpoint/mod.rs, storage/aptosdb/src/db_debugger/examine/print_db_versions.rs, storage/aptosdb/src/db_debugger/truncate/mod.rs, storage/aptosdb/src/ledger_db.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/state_kv_db.rs, storage/backup/backup-cli/src/utils/mod.rs, testsuite/single_node_performance.py, testsuite/smoke-test/src/genesis.rs, testsuite/smoke-test/src/storage.rs
=> [Storage][Sharding] Implement create_checkpoint for LedgerDb, and deprecate use_state_kv_db flag.

ecosystem/typescript/sdk/src/bcs/helper.ts
Seems like we forgot to export `bcsSerializeU256` to the helper
=> feat: added bcsSerializeU256

crates/indexer/migrations/2023-05-24-052435_token_properties_v2/down.sql, crates/indexer/migrations/2023-05-24-052435_token_properties_v2/up.sql, crates/indexer/src/models/coin_models/mod.rs, crates/indexer/src/models/coin_models/v2_fungible_asset_utils.rs, crates/indexer/src/models/token_models/mod.rs, crates/indexer/src/models/token_models/v2_token_activities.rs, crates/indexer/src/models/token_models/v2_token_datas.rs, crates/indexer/src/models/token_models/v2_token_metadata.rs, crates/indexer/src/models/token_models/v2_token_ownerships.rs, crates/indexer/src/models/token_models/v2_token_utils.rs, crates/indexer/src/models/v2_objects.rs, crates/indexer/src/processors/token_processor.rs, crates/indexer/src/schema.rs
* Index all metadata in the resource group under `current_token_v2_metadata` table
* Actually currently we consider metadata as a part of a resource group if they have the same object address. However this should be changed to using `state_key_hash` to ensure that they are actually the same resource group
* Index fungible tokens in token ownership tables
NOTE, this PR does not include token activities yet. Coming next. 
Shipped to devnet. Works
=> [Indexer] Token v2 improvement

Cargo.lock, crates/aptos-ledger/src/lib.rs, crates/aptos/Cargo.toml, crates/aptos/src/common/init.rs, crates/aptos/src/common/types.rs, crates/aptos/src/test/mod.rs
First PR to allow user to init and create profile from their ledger account
NOTE: This is PR only assume you have your ledger account at the index 0 derivative path.
Success init
```
➜  aptos-core git:(jin/ledger_cli_integration) ✗ aptos-debug init --ledger
Aptos already initialized for profile default, do you want to overwrite the existing config? [yes/no] >
yes
Configuring for profile default
Please choose a derivative path from the following 5 ledger accounts, or choose an arbitrary path that you want to use:
Path: m/44'/637'/1'/0'/0' Address 21563230cf6d69ee72a51d21920430d844ee48235e708edbafbc69708075a86e
Path: m/44'/637'/2'/0'/0' Address …
```
=> [CLI] Add init from ledger account

aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
[This commit](https://github.com/aptos-labs/aptos-core/commit/c286ce75b2f2ed92a61bef979170d79507727ed1) broke compatibility in the past because transactions with mismatching numbers of senders vs what the number of signers the invoked function expects would result in mismatching senders error before the change and failed to deserialize error (from constructing non-signer args) after.
Replay tests
=> Fix the order of signer and non-signer tx arg validation to maintain backward compatibility

ecosystem/indexer-grpc/indexer-grpc-cache-worker/README.md, ecosystem/indexer-grpc/indexer-grpc-data-service/README.md, ecosystem/indexer-grpc/indexer-grpc-data-service/src/main.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/metrics.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs, ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs
* Add the tls support for data service: server now supports both tls and non-tls at different ports. 
* Update the latency monitoring for data service.
* Update the cache size: only 1m versions as buffer before evicted. 
locally tested; looks good overall.
=> [indexer grpc] update the tls part for data service.

aptos-move/move-examples/token_objects/ambassador/sources/ambassador.move, aptos-move/move-examples/token_objects/knight/Move.toml, aptos-move/move-examples/token_objects/knight/sources/food.move, aptos-move/move-examples/token_objects/knight/sources/knight.move
This module implements the knight token (non-fungible token) and the food tokens (fungible token). This module has the function to feed a knight token with food tokens to increase the knight's health point.
=> [Example] Added the Knight token object example

Cargo.lock, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/aptos-vm/src/sharded_block_executor/block_executor_client.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/bencher.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/e2e-tests/src/executor.rs, consensus/src/state_computer.rs, execution/block-partitioner/src/lib.rs, execution/block-partitioner/src/sharded_block_partitioner/conflict_detector.rs, execution/block-partitioner/src/sharded_block_partitioner/cross_shard_messages.rs, execution/block-partitioner/src/sharded_block_partitioner/dependency_analysis.rs, execution/block-partitioner/src/sharded_block_partitioner/dependent_edges.rs, execution/block-partitioner/src/sharded_block_partitioner/messages.rs, execution/block-partitioner/src/sharded_block_partitioner/mod.rs, execution/block-partitioner/src/sharded_block_partitioner/partitioning_shard.rs, execution/executor-benchmark/src/native_executor.rs, execution/executor-types/src/lib.rs, execution/executor/src/block_executor.rs, execution/executor/src/components/chunk_output.rs, execution/executor/src/fuzzing.rs, execution/executor/src/mock_vm/mod.rs, types/Cargo.toml, types/src/block_executor/mod.rs, types/src/block_executor/partitioner.rs, types/src/lib.rs
- Plumb the ExecutableTransactions all the way through the block executor to the parallel execution entry point. This is a pre-requisite for sharding
- No functionality change has been introduced - support for sharding will be introduced in subsequent PRs.
Existing UTs
=> [Sharding][Execution] Support sharded APIs for parallel execution

config/src/config/state_sync_config.rs
This PR updates the state sync config to default to fast syncing for all mainnet nodes. This is required now that mainnet pruning has kicked in.
=> [Config] Default to fast sync for mainnet nodes.

consensus/src/dag/dag_store.rs, consensus/src/dag/mod.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/tests/mod.rs
This commit adds basic nodes types and Dag store that handles indexing and produces links for new round.
TODO: support garbage collection
=> [dag] add dag store

storage/aptosdb/src/ledger_store/mod.rs, storage/aptosdb/src/lib.rs, testsuite/single_node_performance.py
To get a better performance, still have room to tune/improve.
=> [Storage] Reorganize calculation and commit tasks in save_transactions/save_transaction_block.

crates/aptos-ledger/src/lib.rs
Update the signing func from ledger crate to output `Ed25519Signature`. So it can be easily consume by RustSDK or CLI
Manually wrote a unit test to test this
```
#[test]
fn test_sign_txn() {
let txn_string = b"b5e97db07fa0bd0e5598aa3643a9bc6f6693bddc1a9fec9e674a461eaa00b193783135e8b00430253a22ba041d860c373d7a1501ccf7ac2d1ad37a8ed2775aee000000000000000002000000000000000000000000000000000000000000000000000000000000000104636f696e087472616e73666572010700000000000000000000000000000000000000000000000000000000000000010a6170746f735f636f696e094170746f73436f696e000220094c6fc0d3b382a599c37e1aaa7618eff2c96a3586876082c4594c50c50d7dde082a00000000000000204e0000000000006400000000000000565c51630000000022";
let signed_msg = sign_message("m/44'/637'/0'/0'/0'", txn_string.to_vec());
println!("Signed message: …
```
=> [CLI][Ledger][easy] update ledger msg signing func

developer-docs-site/docs/move/book/functions.md
Added a note in the Move Book under functions.md#return-type
=> Specify that functions can return references under certain conditions

aptos-move/move-examples/tests/move_unit_tests.rs, aptos-move/move-examples/token_objects/README.md, aptos-move/move-examples/token_objects/token_lockup/Move.toml, aptos-move/move-examples/token_objects/token_lockup/sources/token_lockup.move, aptos-move/move-examples/token_objects/token_lockup/sources/unit_tests.move
The purpose of this example is to show how a developer could create a restriction on the ability to transfer a token such that the owner must hold it for some arbitrary number of days before they can transfer it. This is commonly referred to as a lockup period.
Move unit tests
=> [move-examples] Add an example of a token that is non-transferable for the first 7 days of ownership

aptos-move/aptos-vm-logging/src/counters.rs, aptos-move/aptos-vm-logging/src/lib.rs
Previously the same alerting mechanism as for vm errors was re-used for handling errors within the speculative logging implementation itself. While those errors are also serious enough that we need to be notified, the urgency is much lower - i.e. it would make sense to configure with low urgency / priority, while the vm critical errors are highest urgency.
Separating the counters is the first step, once this code is landed, we can configure a new lower urgency alert based on this counter that can page either blockchain oncall, move oncall (and/or @gelash :D), but it at least will not be commingled with real VM-internal errors.
=> Separate speculative logging errors out in alerting (lower priority)

developer-docs-site/docs/integration/aptos-apis.md
Removed the following outdated information regarding view functions:
- View functions cannot be called via the Aptos CLI
- The requirement to pass `--bytecode-version 6` when publishing a module
Added an example of how to make a view function request in the Aptos CLI.
=> Remove outdated information about view functions and add a CLI usage example

developer-docs-site/docs/tools/aptos-cli-tool/use-aptos-cli.md
Commands such as `coverage`, `verify-package`, and `view` were missing from the `aptos move --help` example, while others, such as `bytecode-version`, `included-artifacts`, and `save-metadata`, were missing from the `aptos compile --help` example.
=> Add missing commands to the command-specific help examples

.github/workflows/execution-performance.yaml, .github/workflows/workflow-run-execution-performance.yaml
This PR duplicates the executor-performance workflow to run on `spot-runner` GHA runners which are backed by spot VM pool. We will use this to assess the availability and performance of the spot VM pool and evaluate if we can expand its use.
The duplicated workflow is not required check, so won't block merge on failure.
Tested it in this run: https://github.com/aptos-labs/aptos-core/actions/runs/5273676507
=> [GHA] Use spot VM for executor-performance

crates/transaction-emitter-lib/src/emitter/mod.rs, crates/transaction-emitter-lib/src/emitter/submission_worker.rs, testsuite/forge-cli/src/main.rs, testsuite/testcases/src/lib.rs
- visibility - add few more log lines, and print txn-emitter stats (every 1m) as well
- make txn-emitter work more precisely. With large number of accounts/submission_workes (and graceful test has 180000 of them), there were a few issues. First creating workers is slow, and so they start with some divergence to begin with - fixing by creating them first before starting, and passing the same "start" instant to all. second divergence wasn't visible because it logged only after 240s divergence (changed to log on 5s divergence)
- fix db flag that got changed recently for test tuned for throughput
=> Improve txn-emitter stability and visibility on Forge

aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-framework/doc/multisig_account.md, aptos-move/framework/aptos-framework/multisig_account.spec.move, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/account.spec.move, aptos-move/framework/aptos-framework/sources/multisig_account.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
This provides a single convenient function so auth key rotation/revocation doesn't need to be done in a separate transaction
Unit tests
=> Add a new function to allow migrating existings account to multisig account while immediately revoking auth key access

crates/aptos/e2e/README.md, crates/aptos/e2e/local_testnet.py, crates/aptos/e2e/test_helpers.py
Addresses https://github.com/aptos-labs/aptos-core/issues/8732.
Demonstrating that you get an explicit error if the config type is global.
```
aptos config set-global-config --config-type global
```
```
DOCKER_DEFAULT_PLATFORM=linux/amd64 poetry run python main.py -d --base-network mainnet --test-cli-path ~/a/core/target/debug/aptos
```
```
Traceback (most recent call last):
File "/Users/dport/a/core/crates/aptos/e2e/main.py", line 194, in <module>
if main():
File "/Users/dport/a/core/crates/aptos/e2e/main.py", line 156, in main
run_helper.prepare()
File "/Users/dport/a/core/crates/aptos/e2e/test_helpers.py", line 155, in prepare
self.prepare_cli()
File "/Users/dport/a/core/crates/aptos/e2e/test_helpers.py", line 189, in prepare_cli
raise RuntimeError(
RuntimeError: When using …
```
=> [CLI][E2E] Ensure CLI is using workspace configuration when using `--test-cli-tag`

crates/aptos/CHANGELOG.md
This PR updates the CLI CHANGELOG to mention the new rust toolchain version required for source compilation.
=> [CLI] Update CHANGELOG to mention new rust toolchain.

storage/aptosdb/src/aptosdb_test.rs, storage/aptosdb/src/pruner/db_pruner.rs, storage/aptosdb/src/pruner/event_store/event_store_pruner.rs, storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs, storage/aptosdb/src/pruner/pruner_utils.rs, storage/aptosdb/src/pruner/state_kv_pruner.rs, storage/aptosdb/src/pruner/state_merkle_pruner_manager.rs, storage/aptosdb/src/pruner/state_store/generics.rs, storage/aptosdb/src/pruner/state_store/mod.rs, storage/aptosdb/src/pruner/state_store/state_merkle_metadata_pruner.rs, storage/aptosdb/src/pruner/state_store/state_merkle_shard_pruner.rs, storage/aptosdb/src/pruner/transaction_store/transaction_accumulator_pruner.rs, storage/aptosdb/src/pruner/transaction_store/transaction_info_pruner.rs, storage/aptosdb/src/pruner/transaction_store/transaction_pruner.rs, storage/aptosdb/src/pruner/transaction_store/write_set_pruner.rs, storage/aptosdb/src/schema/db_metadata/mod.rs, storage/aptosdb/src/state_merkle_db.rs, storage/aptosdb/src/utils/mod.rs
=> [Storage][Sharding] Sharded state merkle pruner.

ecosystem/typescript/sdk/.npmignore
We don't need to publish the `examples` folder as part of the npm package. It increases the package size and there is no real need for it to be part of the package that users download but can simply be part of the repo.
Decrease package size by more than 60% from 3.9 MB to 1.3 MB and unpacked size by 29% from 9.1 MB to 6.4 MB
test are passing
=> [TS SDK] Add examples folder to .npmignore file

scripts/dev_setup.sh
Fix dev_setup.sh to get selected version of Z3 on Mac Arm64.
https://github.com/aptos-labs/aptos-core/issues/8718
Tested on Mac Arm64 with no current Z3 installation.
Code is visibly unchanged for other cases.
=> Fix Z3 for Mac arm64 install in dev_setup.sh

.github/actions/run-local-testnet/action.yaml, .github/actions/run-rust-client-tests/action.yaml, .github/actions/run-ts-sdk-e2e-tests/action.yaml, .github/workflows/docker-build-test.yaml, .github/workflows/node-api-compatibility-tests.yaml, .github/workflows/rust-client-tests.yaml, .github/workflows/ts-sdk-e2e-tests.yaml, ecosystem/typescript/sdk/scripts/publish_ans_contract.ts, ecosystem/typescript/sdk/src/tests/e2e/fungible_asset_client.test.ts
Currently we run the TS SDK tests against a local testnet built from the same commit. So if you make a PR, it will run a local testnet built from the code in that PR and then run the tests against it. This helps check for compatibility between the SDK and main but that's actually not really necessary. Instead, what matters is confirming that the SDK is compatible with each of the production networks. As such, in this PR I make it that the SDK runs against local testnets built from the production networks (devnet, testnet, mainnet).
To ensure compatibility we run these tests on main and on PRs to check for changes to the SDK that could break compatibility with the production networks.
One nice benefit of this change is the SDK tests no longer have to wait for the whole image build phase, …
=> Run TS SDK tests against local testnets built from prod branches, split API and Rust node API client checks into separate job

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/examples/javascript/index.js, ecosystem/typescript/sdk/examples/typescript-esm/index.ts, ecosystem/typescript/sdk/examples/typescript/multisig_transaction.ts, ecosystem/typescript/sdk/src/aptos_types/transaction.ts, ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts, ecosystem/typescript/sdk/src/tests/e2e/faucet_client.test.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts
use `0x1::aptos_account::transfer` instead of `0x1::coin::transfer` and update tests.
=> [TS SDK] use `0x1::aptos_account::transfer` in tests

crates/aptos/src/move_tool/disassembler.rs
We should use the `.move` extension for disassembled code instead of `.yaml`
=> [move] rename file extension from .yaml to .move

aptos-move/framework/aptos-framework/doc/staking_config.md, aptos-move/framework/aptos-framework/sources/configs/staking_config.move, aptos-move/framework/aptos-framework/sources/configs/staking_config.spec.move
- `rewards_rate_period_in_secs` can be customized when initialization. This can enable e2e testing on Devnet and Testnet.
- `rewards_rate_period_in_secs` still cannot be changed after initialization to avoid complicated logic. 
Unit testing
Devnet/Testnet testing
=> [framework]Allow Customized rewards_rate_period_in_secs when Initialization

Cargo.toml, docker/builder/docker-bake-rust-all.hcl
As a follow-up to #8693. To explicitly fail the compilation instead of having potentially confusing compiler mismatch.
https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
> If the currently selected version of the Rust compiler is older than the stated version, cargo will exit with an error, telling the user what version is required.
The check found the docker image was old and had to be bumped as well.
CICD
=> [Rust Toolchain] Set rust-version to 1.70.0

aptos-move/aptos-validator-interface/src/storage_interface.rs, execution/executor/tests/storage_integration_test.rs, network/peer-monitoring-service/server/src/tests.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/continuous_syncer.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs, state-sync/state-sync-v2/state-sync-driver/src/utils.rs, state-sync/storage-service/server/src/tests/mock.rs, storage/aptosdb/src/backup/restore_handler.rs, storage/aptosdb/src/backup/restore_utils.rs, storage/aptosdb/src/db_debugger/truncate/mod.rs, storage/aptosdb/src/fake_aptosdb.rs, storage/aptosdb/src/ledger_store/mod.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/state_merkle_db.rs, storage/aptosdb/src/state_store/mod.rs, storage/backup/backup-cli/src/backup_types/transaction/tests.rs, storage/storage-interface/src/lib.rs
After we split ledger commit to multiple batches, the latest transaction info version might not be equal to the latest "committed" version.
=> [Storage] Remove get_latest_transaction_info_option API, and move all callers to use get_latest_version.

storage/aptosdb/src/backup/restore_utils.rs, storage/aptosdb/src/db_options.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/schema/mod.rs, storage/aptosdb/src/schema/state_value_index/mod.rs, storage/aptosdb/src/schema/state_value_index/test.rs, storage/aptosdb/src/state_kv_db.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/aptosdb/src/test_helper.rs, storage/aptosdb/src/utils/iterators.rs, storage/db-tool/src/tests.rs
Historically we support an API that returns everything by key prefix (e.g. return all states under an account) operation. This was implemented by seeking the StateKv db by prefix directly. However in the new sharding world, account (or whatever prefix) is not a first class concept in the storage layer, and we will store data for an account in different shards, based on the hash of StateKey. Therefore the API cannot be supported by doing a single db seek.
Our long term vision, is to move such support into indexer, before they are ready, we add this index for now to temporarily unblock the sharded db migration.
=> [Storage][Sharding] Write a separate index to support "read everything by key prefix" operation.

.github/workflows/forge-specialized.yaml, testsuite/forge-cli/src/main.rs, testsuite/testcases/src/lib.rs, testsuite/testcases/src/public_fullnode_performance.rs
This PR adds support for two basic PFN enabled forge tests: (i) a max load test (to measure throughput and latency under load); and (ii) a const TPS test (to measure latency when the system is not saturated).
The PR also adds a new workflow for specialized forge tests (i.e., tests that don't need to run daily, like the stable and unstable forge tests). This is currently set to run every other day, but I might reduce it to bi-weekly in the future.
Note: I also plan to migrate a number of other forge tests to the new workflow to help reduce job frequencies 😄 
Manual verification using the `exp` script.
=> [Forge] Add basic PFN performance test.

config/src/config/storage_config.rs, execution/executor-benchmark/src/db_generator.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, execution/executor/src/components/in_memory_state_calculator_v2.rs, storage/aptosdb/src/backup/restore_utils.rs, storage/aptosdb/src/event_store/mod.rs, storage/aptosdb/src/event_store/test.rs, storage/aptosdb/src/lib.rs, storage/aptosdb/src/pruner/event_store/test.rs, storage/aptosdb/src/pruner/state_store/test.rs, storage/aptosdb/src/pruner/transaction_store/test.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/state_store/state_merkle_batch_committer.rs, storage/aptosdb/src/state_store/state_store_test.rs, storage/aptosdb/src/test_helper.rs, storage/aptosdb/src/transaction_store/mod.rs, storage/aptosdb/src/transaction_store/test.rs, storage/backup/backup-cli/src/utils/mod.rs, testsuite/single_node_performance.py
Add a flag to skip indices and storage usage, which will eventually be removed from core AptosDB. This will help us get a better idea in benchmark on how much TPS we can reach later.
=> [Storage] Add a flag to skip writing indices and usage which will eventually go away.

api/goldens/aptos_api__tests__transactions_test__test_gas_estimation_static_override.json, api/src/context.rs, api/src/tests/transactions_test.rs, config/src/config/gas_estimation_config.rs, config/src/config/mod.rs
Follow-up of #8186 based on feedback.
1. Add an option to override the API results with fixed constants.
2. Re-read from the cache after acquiring write lock, as the entry could have been written between the initial read and acquiring the write lock.
3. Enforce invariant that aggressive >= market >= low.
Added unit test.
=> [Gas Estimation] some improvements based on AIP feedback

testsuite/exp
This PR offers two small tweaks to the `exp` script:
1. Add a new flag `--ignore-uncommitted-changes` which will ignore uncommitted changes in the current git workspace when running the script.
2. Add a simple override that forces `--wait` to be true if `--with-forge` is set.
Verified the changes by running the script manually.
=> [Exp] Small tweaks to the exp script.

config/src/config/gas_estimation_config.rs
Enable gas estimation as default, so the updated estimation is deployed in prod on the next release.
=> [Gas Estimation] enable

.github/workflows/workflow-run-forge.yaml
Fix a typo. Outputs are written to `GITHUB_OUTPUT`
Workflow dispatch
=> [gha][forge] fix ambiguous redirect to GITHUB_OUTPUT

developer-docs-site/docs/guides/nfts/mint-nft-cli.md, developer-docs-site/docs/nodes/deployments.md, developer-docs-site/docs/reference/glossary.md
We are migrating away from the testnet-faucet page now that the testnet faucet without the captcha in front has been stable for quite a while. More context here: https://aptos-org.slack.com/archives/C03CHLDTT4M/p1687263356587499.
See also https://github.com/aptos-labs/community-platform/pull/82.
```
cd developer-docs-site
pnpm start
```
=> Remove all reference to aptoslabs.com/testnet-faucet, improve faucet docs

crates/aptos-faucet/core/src/server/run.rs
Small quality of life improvement. This way users can tell that the faucet hasn't actually started yet.
```
$ cargo run -p aptos -- node run-local-testnet --force-restart --with-faucet --assume-yes
Log file: "/Users/dport/.aptos/testnet/validator.log"
Test dir: "/Users/dport/.aptos/testnet"
Aptos root key path: "/Users/dport/.aptos/testnet/mint.key"
Waypoint: 0:645b3a18445fbb7ae17031b2e5f14929bfbf8d5612acdd668be2a6824c31ea0d
ChainId: testing
REST API endpoint: http://0.0.0.0:8080
Metrics endpoint: http://0.0.0.0:9101/metrics
Aptosnet fullnode network endpoint: /ip4/0.0.0.0/tcp/6181
Aptos is running, press ctrl-c to exit
Faucet is starting, please wait...
Faucet is running. Faucet endpoint: http://0.0.0.0:8081
```
=> [Faucet][CLI] Add message to indicate faucet is starting

Cargo.lock, sdk/Cargo.toml, sdk/src/types.rs
Add HardwareWalletAccount for ledger integration
1. mimic LocalAccount, but replace AccountKey with Derivative path
2. Added new trait for doing txn signing - We should have LocalAccount to implement this trait as well (Follow up item)
3. Add SDK to Ledger integration.
Next Step:
Will take HardwareWalletAccount into CLI, whenever we creating a LocalAccount, we need to check whether its a LocalAccount with private key, or Ledger HardwareWalletAccount
NOTE:
This will be merging into feature branch `[feature_branch/cli_ledger_integration](https://github.com/aptos-labs/aptos-core/tree/feature_branch/cli_ledger_integration)`, which will contains all ledger integration breaking changes
=> [Rust SDK] Add HardwareWalletAccount for ledger integration

execution/block-partitioner/src/sharded_block_partitioner/conflict_detector.rs, execution/block-partitioner/src/sharded_block_partitioner/cross_shard_messages.rs, execution/block-partitioner/src/sharded_block_partitioner/mod.rs
Fix partitioning logic to maintain relative ordering of transaction across senders. This is done by moving all remaining txns from the sender to the end of the block, once we detect cross shard conflict for that sender.
Added UTs.
=> [Sharding][Partitioning] Fix to ensure relative ordering for sender

aptos-move/framework/src/aptos.rs, aptos-move/framework/src/built_package.rs, aptos-move/framework/src/prover.rs, aptos-move/framework/tests/move_prover_tests.rs, aptos-move/move-examples/cli-e2e-tests/devnet/Move.toml, aptos-move/move-examples/cli-e2e-tests/mainnet/Move.toml, aptos-move/move-examples/cli-e2e-tests/testnet/Move.toml, crates/aptos/e2e/cases/move.py, crates/aptos/src/common/types.rs, crates/aptos/src/governance/mod.rs, crates/aptos/src/move_tool/coverage.rs, crates/aptos/src/move_tool/manifest.rs, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/move_tool/show.rs, crates/aptos/src/test/mod.rs, third_party/move/tools/move-cli/tests/build_tests/unbound_address/args.evm.exp, third_party/move/tools/move-cli/tests/build_tests/unbound_address/args.exp, third_party/move/tools/move-package/src/resolution/resolution_graph.rs, third_party/move/tools/move-package/tests/test_sources/resolution/basic_no_deps_address_not_assigned/Move.exp
This allows --dev to be added to use the [dev-addresses] as well as updates that really confusing error message to match
CI, and will test manually in a bit
https://github.com/aptos-labs/aptos-core/issues/8707
=> [cli] Add dev address mode for compiler

.github/workflows/faucet-tests.yaml, .github/workflows/indexer-grpc-integration-tests.yaml, .github/workflows/rust-client-tests.yaml, .github/workflows/ts-sdk-e2e-tests.yaml
Using `pull_request` works fine for contributors who are contributing via branches, but external contributors must contribute via a fork based approach. In those cases `pull_request` is unable to pull in the necessary secrets to run the test.
This PR migrates all of this CI to instead use the same approach we use in docker-build-test.yaml, where we use pull_request_target and a permissions check.
Land to main.
=> Make Developer Platform CI use pull_request_target

Cargo.lock, Cargo.toml, third_party/move/tools/move-bytecode-viewer/Cargo.toml
The previous dependent dependencies were using an incompatible changes with rust 1.70.  This should fix it and condense some of the dependencies.
I ran `cargo build -p aptos` on windows and mac
=> [deps] Upgrade windows dependencies to ensure aptos CLI builds

crates/aptos/src/move_tool/mod.rs
Improves error messages for `aptos move test` by showing full error context. This addresses the case where running the tests fails, not tests running successfully but not passing.
Command:
```
aptos move test --named-addresses addr=0x1
```
Before:
```
{
"Error": "Unexpected error: Unable to resolve packages for package 'cli_e2e_tests'"
}
```
After:
```
{
"Error": "Unexpected error: Failed to run tests: Unable to resolve packages for package 'cli_e2e_tests': Unable to resolve named address 'addr' inpackage 'cli_e2e_tests' when resolving dependencies in dev mode: Attempted to assign a different value '0x12345' to an a already-assigned named address '0x1'"
}
```
=> [CLI] Improve error message when running move tests fails

api/src/context.rs, aptos-move/aptos-gas/src/gas_meter.rs, aptos-move/aptos-gas/src/misc.rs, aptos-move/aptos-gas/src/natives.rs, aptos-move/aptos-gas/src/params.rs, aptos-move/aptos-gas/src/transaction/storage.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/common.data/do_nothing/Move.toml, aptos-move/e2e-move-tests/src/tests/common.data/do_nothing/sources/test.move, aptos-move/e2e-move-tests/src/tests/missing_gas_parameter.rs, aptos-move/e2e-move-tests/src/tests/mod.rs, third_party/move/move-core/types/src/vm_status.rs
This adds additional error messages that would help us pinpoint the failing gas parameter when the gas schedule fails to load.
Resolves https://github.com/aptos-labs/aptos-core/issues/5989
=> [vm] add error messages for failing to initialize gas parameters

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/indexer/generated/operations.ts, ecosystem/typescript/sdk/src/indexer/generated/queries.ts, ecosystem/typescript/sdk/src/indexer/queries/getTokenCurrentOwnerData.graphql, ecosystem/typescript/sdk/src/indexer/queries/getTokenOwnersData.graphql, ecosystem/typescript/sdk/src/providers/indexer.ts, ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts
This is a better solution for what we had in https://github.com/aptos-labs/aptos-core/pull/8861 .
- `getTokenOwnersData` - This query returns historical owners data. Add token v2 standard support.
- `getTokenCurrentOwnerData` - This query returns the current token owner data and supports token v2 standard.
=> [TS SDK] Get token owners and current owner data queries

testsuite/forge.py, testsuite/forge_test.py
Note: This is required to unblock a currently failing forge test.
This PR fixes a small issue in the `sanitize_forge_resource_name` function. Specifically, it's possible for the forge namespace to end in a `-` (after sanitization), which is not valid. This PR extends the function and adds some new tests.
New unit tests.
=> [Forge] Small fix to sanitize_forge_resource_name.

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/package.json, ecosystem/typescript/sdk/src/version.ts
- Add token standard v2 support to `getTokenOwnersData` query
- `propertyVersion` parameter is optional to support fetching token v2 data
- Introduce `getTokenCurrentOwnerData` to fetch the current owner of a token
- Add `mintAptosSubdomain` and `setSubdomainAddress` functions to `AnsClient`
=> [TS SDK] Bump version to 1.12.0

crates/aptos/e2e/cases/move.py, crates/aptos/e2e/main.py
2023-06-23 17:11:55,405 - INFO - These tests passed:
2023-06-23 17:11:55,405 - INFO - test_metrics_accessible
2023-06-23 17:11:55,405 - INFO - test_init
2023-06-23 17:11:55,405 - INFO - test_account_fund_with_faucet
2023-06-23 17:11:55,405 - INFO - test_account_create
2023-06-23 17:11:55,405 - INFO - test_account_lookup_address
2023-06-23 17:11:55,405 - INFO - test_aptos_header_included
2023-06-23 17:11:55,405 - INFO - test_move_view
2023-06-23 17:11:55,405 - INFO - test_move_compile
2023-06-23 17:11:55,405 - INFO - test_move_compile_script
2023-06-23 17:11:55,405 - INFO - test_move_publish
2023-06-23 17:11:55,405 - INFO - All tests passed!
=> [CLI] Add cli e2e for move view command

aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/errors.rs, aptos-move/aptos-vm/src/lib.rs, aptos-move/aptos-vm/src/transaction_validation.rs, types/src/account_config/resources/mod.rs
When we began we just copied this from the legacy code base, it appears to be unnecessary overhead.
Considering that any non-public function is upgradeable, we can seamlessly update the code / configuration without needing to separate them into code and configuration. Furthermore, the configuration is complicated by that new fields cannot be added without another resource and all the complexity that goes with that. Instead, let's assume in the VM that these functions are fixed constants rather than read them each time from storage.
Note, this is a further emphasis of the work that was begun by the fee payer that left this in limbo, so this also cleans up some potentially confusion.
=> [types] remove unnecessary transaction validation usage

aptos-move/move-examples/marketplace/sources/coin_listing.move, aptos-move/move-examples/marketplace/sources/collection_offer.move, aptos-move/move-examples/marketplace/sources/events.move, aptos-move/move-examples/marketplace/sources/fee_schedule.move, aptos-move/move-examples/marketplace/sources/listing.move, aptos-move/move-examples/marketplace/sources/test_utils.move
This adds marketplace token offers instead of just collection offers.  This allows users to bid on any token at any time, as well as cancel it at any time.
Built on top of https://github.com/aptos-labs/aptos-core/pull/8742
TBD, CI tests are copied from Collection offer, but should test once manually
=> [move-examples] Add events to marketplace example

ecosystem/python/sdk/aptos_sdk/transaction_worker.py, ecosystem/python/sdk/examples/transaction-batching.py
* We were actually using http1 when we intended to use http2 for workers
* Reduce max gas amount for the client, since it doesn't need that much
* Pass the same timeout from a tranaction worker to the account sequence number
=> [python-sdk] fix a few issues with transaction batching

aptos-move/framework/src/built_package.rs
Getting all modules in a package, including dependencies, is helpful for downstream tools I am building. For example, to generate types based on a package, you need to do it for all modules, not just the root modules.
CI.
=> Add all_modules function to BuiltPackage

ecosystem/typescript/sdk/src/account/aptos_account.ts, ecosystem/typescript/sdk/src/tests/unit/aptos_account.test.ts
Per @moonclavedev's request, adding a function that computes a collection id by providing creator address and collection name.
Also tested with
```
test("Gets the collection id", async () => {
const creatorAddress = "0x043ec2cb158e3569842d537740fd53403e992b9e7349cc5d3dfaa5aff8faaef2";
const collectionName = "Bruh Bears";
expect(AptosAccount.getCollectionID(creatorAddress, collectionName).hex()).toBe(
"0xda59e5f610419f274a20341fb198bf98415712de11a4468cfd45cbe495600c2a",
);
});
```
that matches with Indexer
https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Findexer.mainnet.aptoslabs.com%2Fv1%2Fgraphql&query=query+MyQuery+%7B%0A++current_collection_datas%28%0A++++where%3A+%7Bcollection_name%3A+%7B_eq%3A+%22Bruh+Bears%22%7D%2C+creator_address%3A+%7B_eq%3A+%220x043 …
=> [TS SDK] Add function to compute the collection id hash

aptos-move/framework/aptos-framework/doc/coin.md, aptos-move/framework/aptos-framework/sources/coin.move
There is currently not an easy way to tell if a user has frozen his CoinStore. This is can be a useful information in some scenarios. For example, in an auction based module one might decide to implement a `bid` function that returns coins back to the highest bidder when he is outbided. However, this poses a Denial of Service (DOS) vulnerability as described in the following example:
1. Chunk calls bid sending a small amount
2. Chunk immediately freezes his coin store resource
3. Alice call `bid` with a higher amount, but the call reverts because the bid function cannot return the coins back to Chunk.
4. Chunk unfreezes the CoinStore at the end of the auction and claims the resource 
We can maybe abstract this into a more general `can_deposit` function which will also take into account if …
=> feat: add is_coin_store_frozen to the coin module

third_party/move/move-prover/tests/sources/regression/vector_theory_boogie_array.exp, third_party/move/move-prover/tests/sources/regression/vector_theory_boogie_array.move, third_party/move/move-prover/tests/sources/regression/vector_theory_boogie_array_intern.move, third_party/move/move-prover/tests/sources/regression/vector_theory_smt_seq.move
This PR contains two test cases to show how vector theories might have an impact on the prover's ability on proving complicated propositions w.r.t vector, especially with heavy involvement of quantifiers:
- On test case `f1`:
- `BoogieArray` (the default vector theory) will given a verification error with an inconsistent counterexample while
- `BoogieArrayIntern` and `SmtSeq` can prove the proposition
- On test case `f2`:
- `BoogieArray` times out while
- `BoogieArrayIntern` and `SmtSeq` can prove the proposition
Addressing issue #7422 
CI
=> [move-prover] on different theories for vector modeling

ecosystem/python/sdk/examples/multisig.py
AccountAddress class is missing `from_multisig_schema` function.
Using `from_multi_ed25519` instead.
```
multisig_address = AccountAddress.from_multisig_schema(
[alice.public_key(), bob.public_key(), chad.public_key()], threshold
)
```
Inside Python `sdk` directory, run the following command:
```
poetry run python -m examples.multisig
```
=> Fix multisig address generation in multisig.py example

ecosystem/python/sdk/examples/your-coin.py
The amounts given to the "participants" in this transaction example are not high enough to pay the fee for deploying the contract. This is the result if you run the example right now:
```
File "/Users/egd/projects/aptos-core/ecosystem/python/sdk/aptos_sdk/client.py", line 222, in submit_bcs_transaction
raise ApiError(response.text, response.status_code)
aptos_sdk.client.ApiError: {"message":"Invalid transaction: Type: Validation Code: INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE","error_code":"vm_error","vm_error_code":5}
```
Raising the amount by multiples of ten indicated that 20 million is the appropriate number here.
Fixing that issue reveals another issue: https://github.com/aptos-labs/aptos-core/pull/5770 seems to have broken this code by renaming a method …
=> [Python SDK Reference Example] Update faucet amounts, fix method reference

consensus/src/epoch_manager.rs, types/src/on_chain_config/execution_config.rs
Enabling this by default for Forge runs and any other tests.
=> [Execution] Enable transaction shuffling in genesis for Forge

testsuite/forge/src/backend/local/swarm.rs
validators were sorted, but full_nodes were not -- so `test_vfn_failover` was only testing the real failover 1/4 of the time (when the hashmap iterator happened to match the sort for index 1).
Run the existing tests, otherwise read the code.
=> [smoke tests] sort full_nodes as well, to fix test_vfn_failover

aptos-move/framework/aptos-framework/doc/delegation_pool.md, aptos-move/framework/aptos-framework/doc/staking_contract.md, aptos-move/framework/aptos-framework/sources/delegation_pool.move, aptos-move/framework/aptos-framework/sources/staking_contract.move
It's hard to simulate creating a `StakingContract`/`DelegationPool` on testnet because of whitelist. Add a view function to return the expected address of stake pool to be created.
Unit testing.
=> Add a view function to return address of StakePool to be created

Cargo.lock, api/test-context/Cargo.toml, api/test-context/src/test_context.rs, aptos-move/aptos-vm-logging/src/lib.rs
* If speculative logging is disabled, don't init
* Disable speculative logging for api tests so they don't crash due to shared state
=> [vm-logging] mitigate concurrent speculative logging issues

Cargo.lock, aptos-node/src/network.rs, config/Cargo.toml, config/src/config/network_config.rs, consensus/src/network_tests.rs, consensus/src/round_manager_test.rs, consensus/src/twins/twins_node.rs, mempool/src/tests/mocks.rs, mempool/src/tests/multi_node_test.rs, mempool/src/tests/node.rs, mempool/src/tests/test_framework.rs, network/builder/src/builder.rs, network/builder/src/dummy.rs, network/peer-monitoring-service/server/src/tests.rs, network/src/application/tests.rs, network/src/peer_manager/types.rs, network/src/protocols/health_checker/test.rs, network/src/protocols/network/mod.rs, state-sync/storage-service/server/src/tests/mock.rs, testsuite/smoke-test/src/state_sync.rs
This PR updates the networking code to perform message deserialization in parallel (as opposed to serially, where each application only has a single thread that processes one message at a time). Now, we use `for_each_concurrent` that spawns up to a fixed number of threads and does deserialization in parallel (per application).
This was originally reported as a bottleneck in the consensus tests, but it has since been reproduced by the network benchmarks.
=> [Network] Perform message deserialization in parallel.

Cargo.lock, aptos-move/block-executor/src/counters.rs, aptos-move/block-executor/src/executor.rs, execution/executor-benchmark/Cargo.toml, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/pipeline.rs, testsuite/single_node_performance.py
and modify counters to have parallel/sequential be label instead of new counters, for simpler grafana queries
use output of single_node_performance run to calibrate block gas limit
=> Add non-storage gas into executor benchmark for block gas limit calibration

aptos-move/framework/aptos-stdlib/tests/math64_tests.move, third_party/move/move-compiler/src/inlining/translate.rs, third_party/move/move-compiler/tests/move_check/inlining/double_nesting.move, third_party/move/move-compiler/tests/move_check/inlining/lambda.move, third_party/move/move-compiler/tests/move_check/inlining/lambda_param.exp, third_party/move/move-compiler/tests/move_check/inlining/lambda_param.move, third_party/move/move-compiler/tests/move_check/inlining/multiple_nesting.exp, third_party/move/move-compiler/tests/move_check/inlining/multiple_nesting.move, third_party/move/move-compiler/tests/move_check/inlining/nested_mul.move, third_party/move/move-compiler/tests/move_check/inlining/order_sensitive.move, third_party/move/move-compiler/tests/move_check/inlining/recursive_nesting.move, third_party/move/move-compiler/transactional-tests/tests/inlining/nested_lambda.exp, third_party/move/move-compiler/transactional-tests/tests/inlining/nested_lambda.move, third_party/move/move-compiler/transactional-tests/tests/inlining/nested_lambda_module.exp, third_party/move/move-compiler/transactional-tests/tests/inlining/nested_lambda_module.move, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules.exp, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules.move, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules_inline.exp, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules_inline.move, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules_noinline.exp, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules_noinline.move, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules_pubinline.exp, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules_pubinline.move, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules_pubnoinline.exp, third_party/move/move-compiler/transactional-tests/tests/inlining/two_level_modules_pubnoinline.move
- This PR fixes the issue (https://github.com/aptos-labs/aptos-core/issues/8516) of move compiler not inlining calls to inlined methods in actual parameters to a call to an inlined method.
- Added a test case for nested_mul problem, which no longer panics.
- Note that inlining tests already include a recursive inlining test, but I've added more.
- This also includes some tests of nested and recursive in lining in aptos-stdlib/tests/ for the original case as well as some inlining tests that need execution, not just "checker" testing.
=> Fix partial inlining bug: visitor should keep going after inlining once

crates/aptos-ledger/src/lib.rs
This PR is built on top of this init refactor branch #8893 
1. Added new enum `AptosLedgerStatusCode` - I found these code from Aptos Ledger app and personal finding when I was testing the error. There are many error or status code out there. In this case we cover the most common ones, and the rest will go into `Unknown` error
3. Update all error return message from the ledger crate
➜  aptos-core git:(jin/ledger_status_code) aptos-debug init --ledger
Aptos already initialized for profile default, do you want to overwrite the existing config? [yes/no] >
yes
Configuring for profile default
{
"Error": "Unexpected error: Error - Ledger device is locked"
}
=> [CLI][Ledger][2/n] Add StatusCode to Aptos Ledger crate

crates/aptos/src/common/types.rs, sdk/src/types.rs
Make sure there is no more panic when any ledger error appear
Previously, the following would panic, now it is returning proper error:
```
➜  aptos-core git:(jin/ledger_status_code) ✗ aptos-debug account transfer --profile ledger --account devnet --amount 500
Do you want to submit a transaction for a range of [600 - 900] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
"Error": "Unexpected error: Error - Ledger device is locked"
}
```
=> [CLI][Ledger][3/n] Fix error handling

aptos-move/aptos-release-builder/src/components/framework.rs, aptos-move/aptos-release-builder/src/components/mod.rs, aptos-move/aptos-release-builder/src/lib.rs, aptos-move/aptos-release-builder/src/main.rs, aptos-move/aptos-release-builder/src/validate.rs, crates/aptos/src/governance/mod.rs
- By providing arg `--aptos-core-path`, release builder can read `aptos-framework` and scripts to compile from a custom `aptos-core` path. If the arg is not provided, release builder will use the path itself was compiled at.
- Fix a bug. When `--test-dir` is specified, `validate-proposals` will fail because release builder is reading compiled proposals in a wrong path.
Local test.
Rename `aptos-core` to `aptos-core-r` then run binary `validate-proposals`.
`./aptos-release-builder --aptos-core-path <path to aptos-core> validate-proposals --release-config <path to release.yaml> --output-dir /tmp/release_output --endpoint http://0.0.0.0:8080 --mint-to-validator from-directory --test-dir <path to .aptos/testnet>`
=> Release builder support custom aptos-core path

third_party/move/move-compiler/src/inlining/translate.rs, third_party/move/move-compiler/tests/move_check/inlining/native_inline.exp, third_party/move/move-compiler/tests/move_check/inlining/native_inline.move
[move-compiler] Inlining: raise an error instead of ICE on a native inline fun declaration. (#8934)
Considered doing it in the parser, but it's easier in the inliner code.
Added a test case demonstrating bug.  Should have no effect outside of this situation.
=> [move-compiler] Fix Issue 8934: display an error instead of ICE on native inline fun

consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/reliable_broadcast.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/tests/helpers.rs, consensus/src/dag/tests/mod.rs, consensus/src/dag/tests/reliable_broadcast_tests.rs, consensus/src/dag/types.rs
This PR adds the receiver side of the Certified Node handler. A validator receives a certified node via RPC and adds it to the DAG after verifying it. It is only added if its parents exist and if they don't, there is a `TODO` to try to fetch it.
New unit tests.
=> [dag] certified node receiver handler

mempool/src/core_mempool/mempool.rs, mempool/src/core_mempool/transaction_store.rs, mempool/src/counters.rs, mempool/src/shared_mempool/tasks.rs
Add insertion-to-block-timestamp latency. This helps understand the time it takes to get a txn into Consensus.
Also added more buckets to mempool latency. This helps make the percentile charts more accurate and meaningful.
Added to Mempool dashboard and ran forge.
=> [mempool] metrics: add latency to block proposal

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/aptos_types/type_tag.ts, ecosystem/typescript/sdk/src/tests/unit/type_tag.test.ts
Fix for issue  #8899 
Test cases for checking all TypeTag types have been written. In the future, it is better to add a different test for each new type.
=> [ts-sdk] fix: Incorrect serialization of TypeTags

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/providers/indexer.ts
Indexer queries fail on browser when `WITH_CREDENTIALS` is set to true
=> [TS SDK] Set `WITH_CREDENTIALS`  to false on Indexer requests

.github/workflows/cut-release-branch.yaml
Add credentials to allow pushing to aptos core
Test Plan: run workflow from branch
```
git add . && git commit --amend --no-edit && git push -f && gh workflow run --ref perry-fix-cut-branch -F NEW_VERSION=a.b cut-release-branch.yaml -F GIT_HASH=main
```
https://github.com/aptos-labs/aptos-core/actions/runs/5480751652/jobs/9984278547
=> [release] Add credentials to cut release branch workflow

consensus/src/dag/dag_handler.rs, consensus/src/dag/reliable_broadcast.rs, consensus/src/dag/tests/mod.rs, consensus/src/dag/tests/reliable_broadcast_tests.rs, consensus/src/dag/tests/types_test.rs, consensus/src/dag/types.rs
This PR adds self-contained verification checks and validation checks to `Node` and `CertifiedNode` handlers. 
Unit tests
=> [dag] node and certified node verification checks

Cargo.lock, Cargo.toml, aptos-move/aptos-debugger/Cargo.toml, aptos-move/aptos-debugger/src/lib.rs, aptos-move/aptos-gas-profiling/src/profiler.rs, aptos-move/aptos-gas/src/gas_meter.rs, aptos-move/aptos-gas/src/params.rs, aptos-move/aptos-memory-usage-tracker/Cargo.toml, aptos-move/aptos-memory-usage-tracker/src/lib.rs, aptos-move/aptos-vm/Cargo.toml, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/e2e-tests/Cargo.toml, aptos-move/e2e-tests/src/executor.rs, aptos-move/e2e-testsuite/Cargo.toml, aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs
Back in time, the memory usage tracker was directly embedded into the gas meter because trait for composability did not exist. Now I'm moving it out as a separate layer, so that we have clearer separation of the logic. This does not change the behavior of the VM in any way.
=> [vm][gas] refactor: separate out the memory usage tracker

developer-docs-site/docs/tutorials/first-coin.md, developer-docs-site/docs/tutorials/first-transaction.md, developer-docs-site/docs/tutorials/your-first-nft.md
Currently the python examples have users run `poetry update`, whereas `poetry install` is only mentioned on the introduction page.
This normally wouldn't really be an issue, but lots of python users are newer and aren't familiar with `poetry`, so they don't realize they need to run `poetry install`.
The new Python SDK headers check to see what the current version of `aptos_sdk` is, so lots of people get this specific error when running the examples now:
```importlib.metadata.PackageNotFoundError: No package metadata was found for aptos-sdk```
Changing the examples to just run `poetry install` fixes this.
=> Update the python examples to use poetry install instead of poetry update

.github/workflows/forge-specialized.yaml, testsuite/forge-cli/src/main.rs, testsuite/forge/src/backend/k8s/chaos.rs, testsuite/testcases/src/modifiers.rs, testsuite/testcases/src/multi_region_network_test.rs, testsuite/testcases/src/public_fullnode_performance.rs
This PR offers the following modifications (each in their own commit):
1. Small clean ups to the `MultiRegionNetworkEmulationTest` and network emulation helpers (so that it can be reused and support network chaos for all node types).
2. Extend the existing PFN forge tests to support network chaos, and add two new PFN forge tests: (i) PFNs with max load and network chaos; and (ii) PFNs with constant TPS and network chaos.
3. Add the new PFN forge tests to the existing Github Actions workflow.
=> [Forge] Add network emulation to PFN forge jobs.

.github/workflows/forge-specialized.yaml, testsuite/forge-cli/src/main.rs, testsuite/testcases/src/modifiers.rs, testsuite/testcases/src/multi_region_network_test.rs, testsuite/testcases/src/public_fullnode_performance.rs
This PR follows on from https://github.com/aptos-labs/aptos-core/pull/8976 and offers two improvements (each in their own commits):
1. (Trivial) Fix a forge namespace collision between the new PFN tests.
2. Add CPU chaos to the PFN forge tests (alongside 2 new PFN tests that use this chaos).
Existing test infrastructure and manual verification.
=> [Forge] Fix name collision and add CPU chaos to PFN jobs.

crates/aptos/src/common/types.rs
Need to skip serialization if derivation path is None
Previously
```
default:
public_key: "0xa49209b1817b62bf7909f6cba036667d555fb23212b3846030377f25c3c66577"
account: 6efb99725b135411c7ba442e01cd7ac53a62f341339e74420455f2908b77255a
rest_url: "https://fullnode.devnet.aptoslabs.com"
faucet_url: "https://faucet.devnet.aptoslabs.com"
derivation_path: ~
```
now
```
default:
private_key: "0x489c5505a09640e5816fafff434ba6f19c6025352f8a4a07c195f2e9decd697e"
public_key: "0x85b6e6dcdaa6551383d014bb94faac084e8412625f1c134f14ca23075761ec64"
account: e6fc96a9464ef0a85fd7146fdbae0a48c5930e44d5552ebca90ad0d0a2c7636c
rest_url: "https://fullnode.devnet.aptoslabs.com"
faucet_url: "https://faucet.devnet.aptoslabs.com"
```
=> [CLI][Easy] fix derivation path serialization

developer-docs-site/docs/move/book/conditionals.md, developer-docs-site/docs/move/book/variables.md
Grammar excerpts in the Move Book are jumbled and unreadable.  Attempt to fix them.
Ran local markdown viewer, but I don't know how to really check except on website.
=> [doc] Fix grammar syntax in Move Book

ecosystem/typescript/sdk/src/aptos_types/type_tag.ts, ecosystem/typescript/sdk/src/tests/unit/builder_utils.test.ts, ecosystem/typescript/sdk/src/tests/unit/type_tag.test.ts, ecosystem/typescript/sdk/src/transaction_builder/builder_utils.ts
Add Option, Object, Vector<Object> etc. support to SDK
Additionally, reworked the tests to be more explicit and have more as well as a refactor on the parsing logic.
See tests, they cover most success and failure cases, along with some wrapped types.
Additionally, this makes the error message no longer say String is the only struct supported.
=> [ts-sdk] Add Option, Object, Vector<Object> etc. support to SDK

aptos-move/move-examples/swap/Move.toml, aptos-move/move-examples/swap/sources/coin_wrapper.move, aptos-move/move-examples/swap/sources/liquidity_pool.move, aptos-move/move-examples/swap/sources/package_manager.move, aptos-move/move-examples/swap/sources/router.move, aptos-move/move-examples/swap/sources/tests/coin_wrapper_tests.move, aptos-move/move-examples/swap/sources/tests/liquidity_pool_tests.move, aptos-move/move-examples/swap/sources/tests/package_manager_tests.move, aptos-move/move-examples/swap/sources/tests/test_helpers.move, aptos-move/move-examples/tests/move_unit_tests.rs
This implements an e2e AMM with support for both coins and fungible assets. This is also a variant of UniswapV2 with added support for stable token pairs and separate swap fees (don't compound).
Unit Tests
=> [Move] Add a complex liquidity pool example that supports both coins and fungible assets

.github/workflows/adhoc-forge.yaml
This PR adds the ability to pass cluster name param to adhoc forge. This is useful for choosing a particular cluster (e.g. forge-multiregion).
Run locally.
https://github.com/aptos-labs/aptos-core/actions/runs/5514933716
=> [gha] add cluster param to adhoc-forge

crates/aptos/src/common/init.rs, crates/aptos/src/common/types.rs, crates/aptos/src/test/mod.rs
NOTE: This will be merging into ledger feature branch instead of main
This is similar to the private key option we had. Basically create a struct to better manage the `derivation path` or `derivation index` option. There might be case that user do not have profile initialized, but wanted to go-ahead and use their ledger for submitting the transaction
Next Step:
Add this option for txn signing
```
➜  aptos-core git:(feature_branch/cli_ledger_integration) ✗ aptos-debug init --derivation-index 15 --profile deri15
Configuring for profile deri15
Account 4b19d281ce22da0f39ac3d75d8e1aeef27c430d8830dc659d106990eb70cbd6f doesn't exist, creating it and funding it with 100000000 Octas …
```
=> [CLI][Ledger] Add hardware wallet options

aptos-move/aptos-release-builder/data/release.yaml
Also fix typo
Test Plan: valid yaml, passed framework command
```
mkdir v1.6 && cargo run --profile performance -p aptos-release-builder -- generate-proposals --release-config aptos-move/aptos-release-builder/data/release.yaml --output-dir v1.6
```
=> [framework] Clear out old v1.5 changes / messaging

aptos-move/aptos-release-builder/data/release.yaml
Also fix typo
Test Plan: valid yaml, passed framework command
```
mkdir v1.6 && cargo run --profile performance -p aptos-release-builder -- generate-proposals --release-config aptos-move/aptos-release-builder/data/release.yaml --output-dir v1.6
```
=> [framework] Update release for 1.6

storage/indexer/src/lib.rs
The internal indexer didn't get updated with resource groups introduction.
=> internal indexer: parse tables in resource groups

consensus/src/consensusdb/mod.rs, consensus/src/consensusdb/schema/dag/mod.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/mod.rs, consensus/src/dag/reliable_broadcast.rs, consensus/src/dag/storage.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/tests/reliable_broadcast_tests.rs, consensus/src/dag/types.rs
This PR adds storage support for reliable broadcast. The sender persists the node before broadcasting the node, and the receiver persists the signature before returning it. The GC logic is separated out: the idea is there will a periodic task that will call RB handler `gc_before_round` based on information from `dag` store.
New tests.
=> [dag] reliable broadcast storage

docker/builder/build-tools.sh, docker/builder/indexer-grpc.Dockerfile
Currently performance build is segfaulting due to this target
Attempt to remove the target to fix the segfault
Test Plan: label PR with performance builds
=> [docker] Remove indexer-grpc-parser from tools build to unbreak performance build

config/src/config/mempool_config.rs
* shared_mempool_batch_size: 100 -> 200
* max_broadcasts_per_peer: 1 -> 2
This will allow PFNs to have reasonable performance even with large RTT.
=> [mempool] adjust default configs for PFNs, based on testnet observations

.github/workflows/forge-pfn.yaml, .github/workflows/forge-stable.yaml, .github/workflows/forge-state-sync.yaml, testsuite/forge-cli/src/main.rs, testsuite/testcases/src/modifiers.rs, testsuite/testcases/src/public_fullnode_performance.rs
This PR reduces the swarm sizes used by the various forge jobs (to help reduce forge contention and costs). Specifically, the PR contains the following commits:
1. [Land blocking]: Reduce `compat` and `framework_upgrade` validator counts (from 5 to 4, i.e., 3f+1, where f=1); and (ii) reduce `realistic_env_max_load` validators (from 20 to 7, i.e., f=2) and VFNs (from 10 to 5).
2. [PFN]: Reduce the PFN validators (from 20 to 7, i.e., f=2), VFNs (from 10 to 7), and PFNs (from 10 to 7).
3. [Specialized]: Split the `specialized` forge workflow into two separate workflows: (i) a PFN workflow that runs every 2 days; and (ii) a state sync workflow that runs every 3 days.
4. [Unstable] Reduce the `unstable` forge workflow validators (from 20/15/10 to 7, i.e., f=2).
5. [Stable] For the `stable` …
=> [Forge] Reduce swarm sizes for various forge jobs.

consensus/src/consensusdb/mod.rs, consensus/src/consensusdb/schema/dag/mod.rs, consensus/src/dag/mod.rs, consensus/src/dag/reliable_broadcast.rs, consensus/src/dag/storage.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/tests/reliable_broadcast_tests.rs, consensus/src/dag/types.rs
Now we're signing the metadata instead of only the digest itself, so that we can verify the parents links correctly. Also rename the signature to Vote hopefully more understandable.
=> [dag] sign metadata and rename signature to vote

.github/actions/get-latest-docker-image-tag/action.yml, .github/actions/run-ts-sdk-e2e-tests/action.yaml, .github/workflows/ts-sdk-e2e-tests.yaml
Run TS SDK tests against a local testnet spun up via docker against the latest docker image built on main. A new composite action called `get-latest-docker-image-tag` gets the latest image built on a given branch. It checks out the given branch and uses the existing `find_latest_image.py` script to crawl the git history and check which commits have images built.
CI run on push: https://github.com/aptos-labs/aptos-core/actions/runs/5548754559/jobs/10132092825?pr=9090
=> [gha] run ts sdk tests on latest main best effort

crates/aptos-rosetta/src/types/move_types.rs, crates/aptos-rosetta/src/types/objects.rs
Currently we are parsing withdraw unbonded transaction operations into simple deposit and withdrawals. This makes it impossible to distinguish transfers from withdraw unbonded. This PR introduces a dummy operation without an amount to indicate this is a withdrawal tx for unbonded funds.
Ran Rosetta locally and parsed https://explorer.aptoslabs.com/txn/580239001/userTxnOverview?network=testnet into (notice operation with id 3)
```
{
"transaction_identifier": {
"hash": "49b6112248397313114c9cf769d06f06fed59e54dd634e1bc27fe9388d92f3c7"
},
"operations": [
{
"operation_identifier": {
"index": 0
},
"type": "withdraw",
"status": "success",
"account": {
"address": "bd50bb20e1972747db365c3a6e31255d78867c6b8df9877ea6054bb335dd6031"
},
"amount": {
"value": "-1500030134",
"currency": {
"symbol": …
```
=> [rosetta] add withdraw undelegated stake operation when parsing delegation_pool::withdraw txn

testsuite/exp, testsuite/fixtures/forge-test-runner-template.fixture, testsuite/forge-test-runner-template.yaml, testsuite/forge.py, testsuite/forge/src/backend/k8s/cluster_helper.rs, testsuite/forge/src/backend/k8s/constants.rs, testsuite/forge/src/backend/k8s/fullnode.rs, testsuite/forge_test.py
Tag k8s resources created by Forge with `forge-test-suite` label. This is done via environment variable rather than passing it through directly to the K8sSwarm for simplicity. The label is passed through to the k8s backend of Forge and applied via helm value
This allows for better o11y as well as cost attribution
Existing unit tests for forge python wrapper and forge rust crate updated (test fixtures match)
Use `exp` script to trigger Forge job:
* Job link: https://github.com/aptos-labs/aptos-core/actions/runs/5540565917/jobs/10112826407
* Humio logs show the label is applied: https://cloud.us.humio.com/k8s/search?live=false&query=%22forge-test-suite%22&start=1d&tz=America%2FLos_Angeles
=> [forge] tag k8s resources with testsuite name

aptos-move/move-examples/package_manager/Move.toml, aptos-move/move-examples/package_manager/sources/package_manager.move, aptos-move/move-examples/package_manager/sources/tests/package_manager_tests.move, aptos-move/move-examples/tests/move_unit_tests.rs
/// This module allows publishing to a resource account and retaining control its signer for future upgrades or
/// for other purposes such as creating an NFT collection. It also offer features around managing object and resource
/// account addresses so those can be easily accessed in other modules.
///
/// The deployment flow is as follows:
/// 1. Deploy the package, including this package_manager module, using the Aptos CLI command create-resource-and-publish-package
/// with an appropriate seed. This will create a resource account and deploy the module. The deployer address also needs
/// to be specified in Move.toml.
/// 2. Make sure the created resource address is persisted in the Move.toml for future deployments and upgrades as the
/// CLI doesn't do so by default.
/// 3. During …
=> [Move examples] Add an example for managing resource accounts when deploying

third_party/move/move-compiler/src/hlir/translate.rs, third_party/move/move-compiler/tests/move_check/typing/pay_me_a_river.exp, third_party/move/move-compiler/tests/move_check/typing/pay_me_a_river.move
Fix bug #8390: Compiling a Move module causes an ICE:
```
thread 'main' panicked at 'ICE type constraints failed 055d9d249126ed1feaea5910a42a9a8cd14d49fe0ba062d1ae05207482906c11:3035-3048', third_party\move\move-compiler\src\hlir\translate.rs:481:13
```
It turns out that buggy code can cause the HLIR translator to try to get the `base_type` of a Ref type, so this shouldn't cause an ICE.
Added a minimal test case based on the original customer test case.
Showed that it yielded the same ICE on the current compiler.  With the
fix, we yield a slightly cryptic but infinitely more useful error
output "The type '&mut ...Payments' does not have the ability 'key'"
rather than an ICE crash.
Code inspection shows this case is only relevant when a panic would
have occurred previously.
=> [compiler] Fix issue #8390: Compiling a move module causes an ICE (attempt to get base_type of Ref type in hlir translation)

crates/aptos-crypto-derive/src/lib.rs
The `SilentDebug` and `SilentDisplay` procedural macros from `aptos-crypto-derive` did not work for generic structs, leading to very unhelpful compilation errors which are difficult to trace back to these macros.
=> fix SilentDebug/Display derives to work for generic structs

aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.move, aptos-move/framework/aptos-framework/sources/block.spec.move, aptos-move/framework/aptos-framework/sources/object.move, aptos-move/framework/aptos-framework/sources/staking_contract.spec.move, aptos-move/framework/aptos-framework/sources/staking_proxy.spec.move, aptos-move/framework/aptos-framework/sources/state_storage.spec.move, aptos-move/framework/aptos-framework/sources/storage_gas.spec.move, aptos-move/framework/aptos-stdlib/Move.toml, aptos-move/framework/aptos-stdlib/sources/math128.move
because the frameworks share a common address, one can get away with using the named address incorrectly. this fixes many of those situations. this is a no-op at the bytecode level.
=> [framework] fix named addresses

crates/aptos/src/account/fund.rs, crates/aptos/src/test/mod.rs
Let's you use faucet without the `--account`
```
./target/debug/aptos account fund-with-faucet --profile devnet
{
"Result": "Added 100000000 Octas to account b11affd5c514bb969e988710ef57813d9556cc1e3fe6dc9aa6a82b56aee53d98"
}
```
=> [cli] Allow faucet to be used without passing an extra account

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/providers/provider.ts, ecosystem/typescript/sdk/src/utils/api-endpoints.ts
This allows local development with the TS SDK.  It isn't ideal though, because an indexer client still exists, it just won't work correctly.
I've tested locally
=> [ts-sdk] Allow local endpoint provider

aptos-move/framework/aptos-stdlib/Move.toml
Apparently if an application and its dependencies import aptos stdlib with and without this address set, it would break compilation, example:
{
"Error": "Move compilation failed: Unable to resolve packages for
package 'Tsunami': While resolving dependency 'Switchboard' in package 'Tsunami': Unable to resolve package depen
dency 'Switchboard': While resolving dependency 'AptosStdlib' in package 'Switchboard': Unable to resolve package dependency 'AptosStdlib': Conflicting dependencies found: package '
AptosStdlib' conflicts with 'AptosStdlib'"
}
Adding it back and everything magically works...
=> [framework] removing this resulted in incompatible framework revisions

testsuite/forge/src/backend/k8s/swarm.rs, testsuite/testcases/src/modifiers.rs, testsuite/testcases/src/multi_region_network_test.rs, testsuite/testcases/src/public_fullnode_performance.rs
Today, in the land-blocking test, only validators are in emulated networks. This means VFNs:
* Have very low latency connection with validators. This is probably realistic, but we may want to test with some more latency. We can revisit if we need smaller latencies later.
* Have very low latency connection with each other. This means a state sync path from VN1 -> VFN1 -> VFN2 can be (much) faster than VN1 -> VN2 -> VFN2, which likely doesn't happen in practice.
Instead, we now add the VFNs into the emulated networks, making sure they're in the same region as their VN.
In addition, fixed the chunking so a 7 node network will be chunked into 4 networks as (2,2,2,1). Previously the chunking was (4,1,1,1).
Run forge, observe that the VFN <-> VN RTT is ~100ms, and via logs observe that the …
=> [forge tests] put VFNs within emulated networks

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/aptos_types/type_tag.ts, ecosystem/typescript/sdk/src/tests/unit/type_tag.test.ts
Previously, anything longer than `0x1::object::Object<T>` e.g. even `0x1::object::Object<T1>` would fail parsing with `Invalid type tag.`. Now, it will just consume anything in the `< >` as it all rolls up to a single address
See unit tests, I also plan on testing with some sort of wallet integration, but tbd
=> [ts-sdk] Fix parsing Objects with longer generics or structs

Cargo.toml, api/goldens/aptos_api__tests__invalid_post_request_test__test_invalid_entry_function_argument_address_type.json, aptos-move/move-examples/cli-e2e-tests/common/sources/cli_e2e_tests.move, crates/aptos/e2e/cases/move.py, crates/aptos/e2e/main.py, crates/aptos/src/move_tool/mod.rs
This fix the issue #8982  when parsing u64, u128 and u256 args from the CLI. This was originally broken by the nested vector PR #7790  If we look at the changes carefully, we were explicitly casting to string `.to_string()` for u62 - u256, on the `.to_json()` method, but the nested vector PR missed this part.
**All tested on devnet**
Created a move func and tested make sure u64 works
```
➜  hello_blockchain git:(main) aptos-debug move view --function-id default::message::test_u64 --args u64:1
{
"Result": [
"1"
]
}
➜  devnet git:(jin/fix_u64_u128_u256_args) ✗ aptos-debug move view --function-id \
devnet::cli_e2e_tests::test_big_number \
--args \
u64:123 \  
u128:12345 \ 
u256:340282366920938463463374607431768211455 
{
"Result": [
"123"
]
}
```
Make sure nested u64 on using "move run" still …
=> [CLI] fix u64 to u256 input args

testsuite/smoke-test/src/rest_api.rs
Previously a sleep was used to wait for all non-empty blocks to clear. This resulted in the test being flaky depending on block creation timing.
Run the smoke test.
=> [smoke tests] make gas estimate smoke tests more robust

ecosystem/python/sdk/CHANGELOG.md, ecosystem/python/sdk/aptos_sdk/account.py, ecosystem/python/sdk/aptos_sdk/account_address.py, ecosystem/python/sdk/aptos_sdk/account_sequence_number.py, ecosystem/python/sdk/aptos_sdk/aptos_token_client.py, ecosystem/python/sdk/aptos_sdk/async_client.py, ecosystem/python/sdk/aptos_sdk/ed25519.py, ecosystem/python/sdk/aptos_sdk/package_publisher.py, ecosystem/python/sdk/aptos_sdk/transaction_worker.py, ecosystem/python/sdk/aptos_sdk/transactions.py, ecosystem/python/sdk/aptos_sdk/type_tag.py, ecosystem/python/sdk/examples/multisig.py, ecosystem/python/sdk/examples/read-aggregator.py, ecosystem/python/sdk/examples/simulate-transfer-coin.py
This PR adds the `to_standard_string` function which formats AccountAddress instances as strings in a way that is compliant with AIP 40.
See also https://github.com/aptos-labs/aptos-core/pull/8727.
```
make test
```
```
make examples
poetry run python -m examples.multisig
```
=> [Python][SDK] Make string representation of AccountAddress conform to AIP-40

developer-docs-site/docs/tutorials/first-transaction.md, developer-docs-site/docs/tutorials/your-first-nft.md, ecosystem/python/sdk/aptos_sdk/async_client.py
The deletion of `client.py` from the Python SDK broke some of the links in the docs so it would no longer build. Changed `client.py` to `async_client.py` and it's fixed.
`cd ~/aptos-core/developer-docs-site && pnpm install && pnpm build && pnpm start`
=> Fix the broken links in docs by changing client.py to async_client.py

ecosystem/typescript/sdk/src/tests/unit/type_tag.test.ts
Looks like we forgot to turn back on the blocking tests so this got through.  However, the test was just wrong, so I've since fixed it.
=> [ts-sdk] Fix broken test for typetags

testsuite/forge-cli/src/main.rs
This PR tweaks the TPS requirement for the HAProxy test (from `4700` to `4600`). This is because we recently reduced the number of machines for this test and have seen at least one ["unwanted"](https://github.com/aptos-labs/aptos-core/actions/runs/5573747214/jobs/10181487488) failure, i.e.:
```
TPS requirement for inner traffic failed. Average TPS 4654, minimum TPS requirement 4700.
Full stats: committed: 4654 txn/s, submitted: 4656 txn/s, expired: 2 txn/s, latency: 7720 ms,
(p50: 6600 ms, p90: 11100 ms, p99: 26200 ms), latency samples: 2746095
```
=> [Forge] Tweak HAProxy TPS requirement.

aptos-move/aptos-release-builder/data/release.yaml
Since execution config is not registered yet, removing this should take no effect.
=> remove block gas limit from release v1.6

.github/workflows/workflow-run-replay-verify.yaml
8 runners demands too much resource that can run out of resource. reduce it to 2 for now
=> reduce the runner number in the replay verify

.github/workflows/ts-sdk-e2e-tests.yaml, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_fetcher.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_store.rs, consensus/src/dag/order_rule.rs, consensus/src/dag/reliable_broadcast.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/tests/fetcher_test.rs, consensus/src/dag/tests/mod.rs, consensus/src/dag/tests/types_test.rs, consensus/src/dag/types.rs
This PR adds the receiver-side logic for handling a remote node fetch request. For simplicity, a node will return an error if it is unable to fulfill the whole request. There should be some peer in the system that should be able to satisfy this request. 
unit test
=> [dag] node fetch handler at receiver

aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/mod.rs, consensus/src/epoch_manager.rs, consensus/src/sender_aware_shuffler.rs, consensus/src/transaction_shuffler.rs, crates/aptos-genesis/src/builder.rs, crates/aptos/src/genesis/mod.rs, testsuite/smoke-test/src/aptos_cli/validator.rs, testsuite/smoke-test/src/rest_api.rs, types/src/on_chain_config/execution_config.rs, types/src/on_chain_config/mod.rs
This was introduced with transaction shuffling feature, however, we missed to add it to the onchain config registry. 
Added an smoke test and verified that the shuffling is enabled after the governance proposal.
=> [Execution][Config] Add the newly added execution config to onchain config registry

crates/indexer/migrations/2023-07-13-060328_transactions_by_address/down.sql, crates/indexer/migrations/2023-07-13-060328_transactions_by_address/up.sql, crates/indexer/src/models/coin_models/account_transactions.rs, crates/indexer/src/models/coin_models/mod.rs, crates/indexer/src/models/user_transactions.rs, crates/indexer/src/models/v2_objects.rs, crates/indexer/src/processors/coin_processor.rs, crates/indexer/src/processors/default_processor.rs, crates/indexer/src/schema.rs, ecosystem/indexer-grpc/indexer-grpc-parser/migrations/2023-07-13-060328_transactions_by_address/down.sql, ecosystem/indexer-grpc/indexer-grpc-parser/migrations/2023-07-13-060328_transactions_by_address/up.sql, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/coin_models/account_transactions.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/coin_models/coin_balances.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/coin_models/mod.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/default_models/user_transactions.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/default_models/v2_objects.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/stake_models/delegator_balances.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/collection_datas.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/v2_collections.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/v2_token_activities.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/v2_token_datas.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/v2_token_ownerships.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/processors/coin_processor.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/processors/default_processor.rs, ecosystem/indexer-grpc/indexer-grpc-parser/src/schema.rs
It's nice to have a dedicated table to get all transactions that touch an address instead of a view. I'm adding this to the coin_processor because the coin processor already needs to process every transaction. We don't want this to be in default processor currently because we've had instances where default processor takes forever to run migrations and it stalls explorer and wallet.
What qualifies as a transaction associated with an address: 
1. account signed or is part of a multi sig / multi agent
2. account resources / events are directly modified
3. account owns an object where resources / events are modified (only 1 degree)
I called out a bunch of TODOs here. Notably what we're currently unable to do: 
* Recursively find owner of an object
* Find an owner of an object that was deleted …
=> [Indexer] Add transactions by address indexing

testsuite/forge-cli/src/main.rs
With txn shuffling enabled, we are getting 10-15% TPS boost on Forge. All my run with shuffling could achieve more than 6k TPS. So bumping up the threshold to 5.5k for land blocking. Will bump other runs as well once we have some datapoints for them.
Run Forge
=> [Forge] Increase TPS threshold for land blocking after enabling txn shuffling

crates/indexer/src/models/token_models/v2_token_ownerships.rs
If there is a self transfer of token v2, we currently soft delete the token from the user's account. However, this should just be a noop
Need to backfill testnet from transaction version 514946350 and mainnet from transaction version 169213813
=> [indexer] handle edge case of self transfer token v2

testsuite/exp
Use named args for `workflow_dispatch_forge`, which was previously broken.
New unit test for this, and run `exp`
=> [exp] fix arg passing for forge gha

Cargo.lock, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/Cargo.toml, aptos-move/block-executor/benches/scheduler_benches.rs, aptos-move/block-executor/src/counters.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/bencher.rs, aptos-move/block-executor/src/proptest_types/mod.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/unit_tests/mod.rs, aptos-move/mvhashmap/src/versioned_data.rs
Our biggest pride, the mock tests for block executor, got in a rather messy state overtime due to constantly adding more and more coverage in ad-hoc ways (no named members, ad-hoc ways to get coverage, e.g. dynamic r/w behavior for different incarnations, aggregator deltas, etc). This makes it hard to maintain, extend, and in fact to support new features - including aggregator failures (or promises) and code cache. Here is a first attempt to address it by a refactor, moved out baseline generation, adjusted names, cleaned up structure, added some todos. Definitely easier to test for example delta failures now, but will be making some more follow-up changes - sending this one to keep PR sizes manageable. 
Other improvements:
- gas testing now charges different gas for different …
=> [Executor] Refactor / Improve mock tests (also gas limit)

developer-docs-site/docs/guides/account-management/key-rotation.md, developer-docs-site/docs/guides/resource-accounts/key-rotation.md, developer-docs-site/docusaurus.config.js, developer-docs-site/sidebars.js, ecosystem/python/sdk/examples/rotate-key.py, ecosystem/typescript/sdk/examples/typescript-esm/package.json, ecosystem/typescript/sdk/examples/typescript-esm/pnpm-lock.yaml, ecosystem/typescript/sdk/examples/typescript-esm/rotate_key.ts
Added examples of how to rotate an account's authentication key with an accompanying simple page in the docs that covers how to run the code and the relevant code snippets.
The intention here is to very briefly explain how to do things, not to explain all of the concepts involved in the process. This will be used later in the resource accounts tutorial, for example.
Run the examples in the docs page by copying and pasting the commands
=> [Examples] Account authentication key rotation with the CLI, Typescript and Python SDKs

terraform/helm/vector-log-agent/templates/secrets.yaml
The lack of a terminator means that Helm was effectively generating a single resource with duplicated fields, and K8s does not signal an error when applying such a malformed resource, which means that latter fields (in this case the loki-credentials secret) overrode the earlier ones.
Example:
```
apiVersion: v1
kind: Secret
metadata:
name: humio-credentials
namespace: vector
apiVersion: v1
kind: Secret
metadata:
name: loki-credentials
namespace: vector
```
Deployed manually to cluster `aptos-devtestnet/aptos-pfn`.
=> [Helm] Fix templating of aptos-vector-log-agent

.dockerignore, Cargo.lock, Cargo.toml, crates/aptos-api-tester/Cargo.toml, crates/aptos-api-tester/src/main.rs, crates/aptos-api-tester/src/utils.rs, crates/aptos-rest-client/src/types.rs, docker/builder/build-tools.sh, docker/builder/tools.Dockerfile, sdk/Cargo.toml, sdk/src/lib.rs, sdk/src/token_client.rs
This PR introduces consistent API testing where we run a consistent load through the network mimicking various user flows. See [proposal](https://www.notion.so/aptoslabs/API-Flow-Testing-Proposal-ae3424ce6e15433fa69f7c9dd99db037) for more high level information.
Changes:
* Created `aptos-api-tester` crate which runs 4 user flows:
* Account creation
* Coin transfer
* NFT transfer
* Module publishing, and outputs results to stdout.
* Added `token-client` to the SDK with the methods needed to run [Your First NFT](https://aptos.dev/tutorials/your-first-nft).
* mirroring the [typescript SDK](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/plugins/token_client.ts) and the rust [coin client](https://github.com/aptos-labs/aptos-core/blob/main/sdk/src/coin_client.rs) …
=> [api] Add consistent API testing

Cargo.lock, aptos-node/Cargo.toml
This PR bumps the `aptos-node` crate version to 1.6.
=> [Aptos Node] Bump aptos-node crate to 1.6

Cargo.lock, config/src/config/state_sync_config.rs, state-sync/storage-service/server/Cargo.toml, state-sync/storage-service/server/src/handler.rs, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/metrics.rs, state-sync/storage-service/server/src/moderator.rs, state-sync/storage-service/server/src/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/storage_summary.rs, state-sync/storage-service/server/src/tests/utils.rs
This PR offers a number of performance, scalability and observability improvements to the optimistic fetch handling logic in the storage service.
Each improvement is offered in its own commit:
1. Migrate the cached storage server summary from `Arc<RwLock<T>>` to `Arc<ArcSwap<T>>`. [ArcSwap](https://docs.rs/arc-swap/latest/arc_swap/) is more efficient for read-mostly scenarios, which matches that of the cached storage server summary (i.e., lots of concurrent reads, infrequent writes).
2. Migrate the active optimistic fetch map from `Arc<Mutex<HashMap<K,V>>>` to `Arc<DashMap<K, V>>,`. This reduces lock contention when handling concurrent optimistic fetch inserts and deletions. See [DashMap](https://docs.rs/dashmap/latest/dashmap/struct.DashMap.html).
3. Modify …
=> [Storage Service] Several performance and scalability improvements.

config/src/config/state_sync_config.rs, crates/aptos-time-service/src/lib.rs, state-sync/aptos-data-client/src/tests/priority.rs, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/metrics.rs, state-sync/storage-service/server/src/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/mock.rs, state-sync/storage-service/server/src/tests/new_transaction_outputs.rs, state-sync/storage-service/server/src/tests/new_transactions.rs, state-sync/storage-service/server/src/tests/new_transactions_or_outputs.rs, state-sync/storage-service/server/src/tests/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/utils.rs, state-sync/storage-service/server/src/utils.rs, state-sync/storage-service/types/src/responses.rs
Note: (i) nothing should really change in this PR; and (ii) this PR is built on: https://github.com/aptos-labs/aptos-core/pull/9014.
This PR offers a small number of surface changes (i.e., variable renames and utility function refactors). Specifically, it offers the following (each in their own commit):
1. Rename `max_optimistic_fetch_period` to `max_optimistic_fetch_period_ms`.
2. Rename `OPTIMISTIC_FETCH_VERSION_DELTA` to `OPTIMISTIC_FETCH_VERSION_LAG` and increase the version lag (to tolerate higher TPS networks and timeouts).
3. Add a simple `from_mock` utility method to the `TimeService`.
4. Move several utility functions into the `utils.rs` files. This is so they can be re-used in the future.
5. Alphabetically order the test `utils.rs` file. This should help make it easier to …
=> [Storage Service] Surface renames and refactors.

Cargo.lock, aptos-node/src/state_sync.rs, config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/peer_states.rs, state-sync/aptos-data-client/src/tests/priority.rs, state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs, state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_service.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/utils.rs, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/moderator.rs, state-sync/storage-service/server/src/tests/mock.rs, state-sync/storage-service/server/src/tests/optimistic_fetch.rs, state-sync/storage-service/types/Cargo.toml, state-sync/storage-service/types/src/responses.rs, state-sync/storage-service/types/src/tests.rs
Note: (i) nothing should logically change in this PR; and (ii) this PR is based on https://github.com/aptos-labs/aptos-core/pull/9021.
This PR offers several small renames, refactors and test cleanups, each in their own commit:
1. Replace `subscription` terminology in the Aptos Data Client with `optimistic fetch` (as this is more accurate and consistent with the storage service nomenclature).
2. Make the optimistic fetch lag configurable in the data client config (as opposed to hard-coded in the file).
3. Clean up the storage service types tests and add a missing test for optimistic fetch versions.
Existing and new test infrastructure.
=> [Storage Service] Small renames, refactors and test cleanups

third_party/move/move-vm/runtime/src/interpreter.rs
This closes #9236 
Note: this doesn't need to be feature gated because CastU32 and CastU256 cost have always been the same as cost for CastU16.
=> [vm] charge castu32 and u256 properly

testsuite/README.md, testsuite/indexer_grpc_local.py
Running this script didn't work if you did it from testsuite/. With this it does.
Before:
```
stat /Users/dport/a/core/testsuite/docker/compose/indexer-grpc/docker-compose.yaml: no such file or directory
```
After:
```
[Wed, 26 Jul 2023 16:28:01] INFO [indexer_grpc_local.py.wait_for_indexer_grpc_progress:170] Attempting to stream from indexer grpc for 10s
[Wed, 26 Jul 2023 16:28:11] INFO [indexer_grpc_local.py.wait_for_indexer_grpc_progress:208] Stream finished successfully
```
=> Make indexer_grpc_local.py work regardless of which directory it is invoked from

.github/workflows/indexer-grpc-integration-tests.yaml
Previously successive pushes to main branch cancelled previous jobs if they were still running. For example: https://github.com/aptos-labs/aptos-core/actions/runs/5615073388/job/15214560994
Use more of less the same concurrency rules as the main `docker-build-test.yaml` workflow
CI on pull_request_target once it lands.
=> [gha] prevent indexer grpc integration tests from cancelling on push

.github/workflows/forge-pfn.yaml, .github/workflows/forge-stable.yaml, .github/workflows/forge-state-sync.yaml, .github/workflows/forge-unstable.yaml
This PR updates the forge workflows to add dependencies between jobs. Specifically, we add a dependency between each forge test such that only one test should be running at a time. Additionally, the tests should always run, even if previous tests fail, e.g., see [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif). This should help reduce spikes in the number of machines forge requires.
I've also updated the GHA workflows to start at different times, so that we hopefully scatter the jobs one after the other based on the rough end-to-end job time and scheduling, e.g., forge stable starts at 6am UTC (11pm PDT), and forge unstable starts at 12pm UTC (5am PDT), allowing ~6 hours for the stable job to complete. It won't be perfect, but we …
=> [Forge] Add dependencies between GHA workflow jobs.

.github/workflows/lint-test.yaml
Related to #9322 . All references to the deleted workflow need to be removed on main
=> [gha] remove helm-lint from lint-test

Cargo.toml, docker/builder/indexer-grpc.Dockerfile, ecosystem/indexer-grpc/indexer-grpc-data-service/src/main.rs
* Add more logging to indexer grpc data service for TLS/non-TLS start-up.
* Locally tested and it looks good.
=> add more logging to data service.

Cargo.lock, api/types/Cargo.toml
This was blocking the SDK usage, so this fixes it so that it can be properly consumed
Built a sample app with the patch
```
cargo build
Updating git repository `https://github.com/aptos-labs/merlin`
Finished dev [unoptimized + debuginfo] target(s) in 1.71s
```
Without
```
error[E0405]: cannot find trait `ToYAML` in module `poem_openapi::types`
--> /Users/greg/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/62ca66e/api/types/src/wrappers.rs:92:47
|
92  | #[derive(Clone, Copy, Debug, Deserialize, Eq, Object, PartialEq, Serialize)]
|                                               ^^^^^^ help: a trait with a similar name exists: `ToXML`
|
::: /Users/greg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poem-openapi-2.0.11/src/types/mod.rs:152:1
|
152 | pub trait ToXML: Type {
| …
```
=> [api] Fix transitive dependency

.github/workflows/prover-daily-test.yaml, aptos-move/framework/aptos-framework/doc/aptos_coin.md, aptos-move/framework/aptos-framework/doc/aptos_governance.md, aptos-move/framework/aptos-framework/doc/execution_config.md, aptos-move/framework/aptos-framework/doc/reconfiguration.md, aptos-move/framework/aptos-framework/doc/staking_contract.md, aptos-move/framework/aptos-framework/doc/voting.md, aptos-move/framework/aptos-framework/sources/aptos_coin.spec.move, aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move, aptos-move/framework/aptos-framework/sources/configs/execution_config.spec.move, aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move, aptos-move/framework/aptos-framework/sources/staking_contract.spec.move, aptos-move/framework/aptos-framework/sources/voting.spec.move, aptos-move/framework/aptos-stdlib/doc/smart_vector.md, aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.spec.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.spec.move, aptos-move/framework/src/prover.rs, aptos-move/framework/tests/move_prover_tests.rs, third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs, third_party/move/move-prover/boogie-backend/src/options.rs
This PR does the following things:
- add the flag `--unconditional-abort-as-inconsistency` and `--disallow-global-timeout-to-be-overwritten` to `aptos move prove`;
- add a normal prover test to the daily prover test (in CI) with enough verification time so that all verification targets will be checked;
- add an inconsistency test to the daily prover test;
- fix some inconsistency issues in the specs;
- comment out problematic specs which needs further investigation.
close #9092
=> [Move prover] Some fixes in the prover and the specs

testsuite/forge-cli/src/main.rs, testsuite/forge/src/backend/k8s/fullnode.rs, testsuite/forge/src/backend/k8s/swarm.rs, testsuite/testcases/src/public_fullnode_performance.rs
For the PFN tests, also colocate VFNs and VNs, and add the PFNs as a single colocated group.
Ensure the PFNs have the correct index (larger than the VFNs), via forge.
=> [forge tests] also colocate vfns and vns for the pfn tests

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/examples/typescript/transactions_management.ts, ecosystem/typescript/sdk/package.json, ecosystem/typescript/sdk/pnpm-lock.yaml, ecosystem/typescript/sdk/src/index.ts, ecosystem/typescript/sdk/src/providers/aptos_client.ts, ecosystem/typescript/sdk/src/transactions/account_sequence_number.ts, ecosystem/typescript/sdk/src/transactions/async_queue.ts, ecosystem/typescript/sdk/src/transactions/index.ts, ecosystem/typescript/sdk/src/transactions/tests/account_sequence_number.test.ts, ecosystem/typescript/sdk/src/transactions/tests/transaction_worker.test.ts, ecosystem/typescript/sdk/src/transactions/transaction_worker.ts
based on https://github.com/aptos-labs/aptos-core/pull/7987
This PR provides a layer for managing and submitting as many transactions from a single account at once.
- AccountSequenceNumber class - a class that handles and manages an account sequence number.
- TransactionWorker class - a class that provides workers to manage transactions, from generate through sign and submit to chain. It validates the transaction submission and monitors the submission success/failure.
In addition, provide an example demonstrates the transaction management layer and how one can implement it.
1. tests are passing
2. output from running the example against devnet using a wifi connection with download speed of 23.38 mbps and upload speed of 8.40 mbps
```
starting...
5 sender accounts and 5 recipient accounts …
```
=> [TS SDK] Add account transaction management

crates/aptos/CHANGELOG.md
This PR updates the Aptos CLI change log to mention the recent rust upgrade.
=> [Aptos CLI] Updated change log to mention rust upgrade.

aptos-move/move-examples/token_objects/guild/Move.toml, aptos-move/move-examples/token_objects/guild/sources/guild.move
Guild and Member token example using Token V2. This module allows the following:
* `admin` adds guild masters to the whitelist
* a whitelisted guild master mints a guild token
* a guild master with a guild token mints a member token for a user
* a guild master burns (or revokes) a member token
For simplicity, this module does not implement the following because these are already shown in the Ambassador example (https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/move-examples/token_objects/ambassador/sources/ambassador.move):
* `admin` mutates a guild token's onchain property (e.g., guild level)
* guild master mutates a member token's onchain property (e.g., member level)
TODO:
* Typescript/indexer example for guild/member tokens
`aptos move test`
=> [Example] Added the guild/member token

Cargo.lock, Cargo.toml
So there’s this fun thing in rust-landia where the cryptographic library we use - https://github.com/dalek-cryptography/x25519-dalek/issues/92 - where they’ve pinned a version of their zeroize dependency to a 
minor version, and have refused to backport relaxing that constraint for almost a year now. Instead they’ve been focused on their V2, which is in alpha. Other libraries have moved on from relying (at this 
point) on the very old version of zeroize , and more and more often you see zeroize > 1.4 . This creates a fun incompatibility!
A few of us have run into this now, trying to use libraries from aptos core in other services. This creates an interesting situation: either we have to use an alpha (pre-release- currently on rc3) version of a 
core cryptography library (which sounds very …
=> Uses aptos-core x25519-dalek library with relaxed zeroize dep

aptos-move/framework/aptos-framework/doc/aggregator_v2.md, aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.move
and change narrower deferred read to also throw an exception, instead of returning an option.
In general, it allows simpler usage when we know it cannot overflow/underflow - https://github.com/igor-aptos/aptos-core/pull/5
=> [aggregator_v2] add utility add()/sub() methods

types/src/on_chain_config/execution_config.rs
This turns on the enabled features as defaults in genesis. The original PR was in v1.5 branch only, now adding to v1.6 and main.
(Note, revert of f313b5be43d6918a5456e738d8c7f67c7e9160fa was also applied, but it was a noop)
=> Turn on txn dedup and quorum store at genesis (#8459)

network/src/counters.rs, network/src/peer_manager/tests.rs, network/src/protocols/wire/handshake/v1/mod.rs
This PR adds latency metrics for message serialization/deserialization to the network stack. This should help improve observability when handling large message sizes. The PR also does some quick ad-hoc cleanups over the nearby code.
=> [Network] Add latency metrics for message serialization/deserialization.

third_party/move/move-core/types/src/language_storage.rs
This function helps with some of the ABI codegen work I'm doing. Part of the Move stdlib so it should be uncontentious.
I've used this successfully in code I'm adding later. Compile check. CI.
=> Add is_std_option function to StructTag

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/account/aptos_account.ts, ecosystem/typescript/sdk/src/aptos_types/account_address.ts, ecosystem/typescript/sdk/src/aptos_types/rotation_proof_challenge.ts, ecosystem/typescript/sdk/src/index.ts, ecosystem/typescript/sdk/src/plugins/ans_client.ts, ecosystem/typescript/sdk/src/plugins/aptos_token.ts, ecosystem/typescript/sdk/src/plugins/fungible_asset_client.ts, ecosystem/typescript/sdk/src/providers/aptos_client.ts, ecosystem/typescript/sdk/src/providers/index.ts, ecosystem/typescript/sdk/src/providers/indexer.ts, ecosystem/typescript/sdk/src/transaction_builder/builder.ts, ecosystem/typescript/sdk/src/utils/hd-key.ts, ecosystem/typescript/sdk/src/utils/misc.ts
There were a lot of types that were not being exported, and many users asked for them to be exported.  Any types that are not exported here are exported under `TransactionBuilderTypes`
Additionally, I cleaned up a few interfaces that were either not using the already defined types, or were less permissive than other places that took in the same values.
=> [ts-sdk] Export more types

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/index.ts, ecosystem/typescript/sdk/src/indexer/generated/operations.ts, ecosystem/typescript/sdk/src/indexer/generated/queries.ts, ecosystem/typescript/sdk/src/indexer/generated/types.ts, ecosystem/typescript/sdk/src/indexer/queries/getAccountTokensCount.graphql, ecosystem/typescript/sdk/src/indexer/queries/getCollectionData.graphql, ecosystem/typescript/sdk/src/indexer/queries/getCollectionsWithOwnedTokens.graphql, ecosystem/typescript/sdk/src/indexer/queries/getOwnedTokens.graphql, ecosystem/typescript/sdk/src/indexer/queries/getOwnedTokensByTokenData.graphql, ecosystem/typescript/sdk/src/indexer/queries/getTokenActivities.graphql, ecosystem/typescript/sdk/src/indexer/queries/getTokenActivitiesCount.graphql, ecosystem/typescript/sdk/src/indexer/queries/getTokenCurrentOwnerData.graphql, ecosystem/typescript/sdk/src/indexer/queries/getTokenData.graphql, ecosystem/typescript/sdk/src/indexer/queries/getTokenOwnedFromCollection.graphql, ecosystem/typescript/sdk/src/providers/indexer.ts, ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts, ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts, ecosystem/typescript/sdk/src/transactions/tests/account_sequence_number.test.ts, ecosystem/typescript/sdk/src/transactions/tests/transaction_worker.test.ts
Per @kent-white's request in https://github.com/aptos-labs/explorer/pull/578
- Export indexer types `export * from "./indexer/generated/types";`
- Support for token v2 activities
- Aggregate query for token v2 activities
- Support for sorting indexer queries
- Support for get owned tokens by token_data_id
ts sdk indexer tests are passing
=> [TS SDK] Improve `IndexerClient` to support tokenv2 sorting and new queries

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/providers/provider.ts, ecosystem/typescript/sdk/src/tests/e2e/provider.test.ts, ecosystem/typescript/sdk/src/utils/api-endpoints.ts
relive https://github.com/aptos-labs/aptos-core/pull/8850 - support `Network.LOCAL` enum for local development. It isn't ideal though, because an indexer client still exists, it just won't work correctly.
=> [TS SDK] Support local endpoint in Provider

aptos-move/framework/move-stdlib/tests/vector_tests.move
Looks like `#[test]` was omitted accidentally. This PR fixes that.
```
$ aptos move test | grep test_stable_partition
[ PASS    ] 0x1::vector_tests::test_stable_partition
$ aptos move test | grep test_insert
[ PASS    ] 0x1::string_tests::test_insert
[ PASS    ] 0x1::vector_tests::test_insert
[ PASS    ] 0x1::vector_tests::test_insert_out_of_bounds
```
=> Run vector tests that were unintentionally not run

testsuite/exp, testsuite/test_framework/git.py, testsuite/test_framework/git_test.py
Make the `exp` script work from a fork. It should more or less function the same, with one caveat:
From a fork, you cannot test changes to the workflows themselves (for security reasons). If you want to test a change to a workflow, you can run `exp` from a branch in `aptos-core` itself.
New unit tests. Also run `exp` from a fork. 
```
Code/rustielin-aptos-core/testsuite  rustielin/exp-from-fork ✔                                                      0m  
▶ poetry run python exp run                 
[Fri, 28 Jul 2023 17:17:01] INFO [exp.run:365] WARNING: You are running this script from a fork of aptos-labs/aptos-core.
[Fri, 28 Jul 2023 17:17:01] INFO [exp.run:368] WARNING: This script will push a new branch to your fork.
[Fri, 28 Jul 2023 17:17:01] INFO [exp.run:369] WARNING: It will run …
```
=> [exp] make it work from a fork

.github/workflows/execution-performance.yaml, .github/workflows/workflow-run-execution-performance.yaml
This PR removes the spot runner execution benchmark mode and reduces the job frequency from every 4 hours to daily. We shouldn't need to run it every 4 hours given that it runs on each PR 😄 
=> [Execution Benchmark] Remove spot runners and reduce frequency.

config/src/config/mempool_config.rs, mempool/src/logging.rs, mempool/src/shared_mempool/network.rs, mempool/src/shared_mempool/tasks.rs, testsuite/forge-cli/src/main.rs
* Increase single fullnode max throughput from 4K TPS to 6K TPS (max batch size 200 -> 300, scheduled every 50 ms)
* Increase throughput when broadcast RTT is large, by increasing the number of outstanding requests. E.g., previously an RTT of 500 ms with 2 outstanding requests, meant only 2 requests could be made every 500 ms.
Run forge with PFNs and network emulation, observe that `Avg Insertion-to-Broadcast-Batched` on PFNs drops significantly, from 1-2 s for some PFNs to < 200 ms.
=> [Mempool] optimize fullnode broadcast hops for latency

aptos-move/vm-genesis/src/lib.rs, consensus/src/epoch_manager.rs, crates/aptos-genesis/src/builder.rs, crates/aptos/src/genesis/mod.rs, testsuite/smoke-test/src/rest_api.rs, types/src/on_chain_config/execution_config.rs
Introduce a new `Missing` version for `OnChainExecutionConfig` that will maintain backwards compatibility for before the config was registered. Use this when the config is missing from epoch manager.
Otherwise, use `default_for_genesis` for all new networks e.g., forge, devnet.
Observe that e2e tests use both shuffle and dedup.
=> Re-enable dedup and shuffling as defaults (for test networks)

testsuite/forge-cli/src/main.rs, testsuite/forge/src/backend/k8s/fullnode.rs
Confirm the PFN is no longer labeled a validator in grafana system dashboard and humio.
=> [Forge] PFN should have a container name of fullnode, not validator

Cargo.lock, ecosystem/nft-metadata-crawler-parser/Cargo.toml, ecosystem/nft-metadata-crawler-parser/src/lib.rs, ecosystem/nft-metadata-crawler-parser/src/utils/database.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Run DB migrations in code instead of as a command
=> [NFT Metadata Crawler] DB migrations in code

api/types/src/address.rs, third_party/move/move-core/types/src/account_address.rs
- Previous in stack: N/A
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/9186
This PR adds a `to_standard_string()` function to the various Address structs. This function outputs the account address in a way that is compliant with the proposed standard: https://github.com/aptos-foundation/AIPs/pull/175. 
Currently the purpose of this PR is to complement the AIP. Once the AIP is accepted, I will publish this PR, making any changes if necessary based on the discussion in the AIP. 
Note that the AIP just standardizes the way we format addresses currently (v1), this is not a full identifier overhaul (v2).
In a later set of PRs I will do the following:
- In every instance where the existing Display impl is used (e.g. in `format` or with `to_string()` I will make it explicitly …
=> Add `to_standard_string` function to Address structs that is compliant with AIP 40

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/providers/aptos_client.ts, ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts
Adds support for fee payer transaction with
- a function to generate a fee payer raw transaction which returns a FeePayerRawTransaction
- a function to sign a fee payer raw transaction which returns the signer authenticator
- a function to submit the signed fee payer raw transaction
=> [TS SDK] Support fee payer transaction

ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts
This test assumed that the ObjectCore resource is always the first element in the changes array - which is not always the case and made this test flaky
=> [TS SDK] fix flaky gets object test

crates/aptos/src/common/types.rs
Looks like the format has causes some confusion. See reference - https://github.com/aptos-labs/aptos-core/issues/7906#issuecomment-1664226876
This PR updates the format comment
```
➜  aptos-core git:(feature_branch/cli_ledger_integration) ✗ aptos-debug init --ledger --profile ledger --derivation-path m/44\'/637\'/0\'/0\'/0\'
Configuring for profile ledger
Using command line argument for derivation path m/44'/637'/0'/0'/0'
Account 59836ba1dd0c845713bdab34346688d6f1dba290dbf677929f2fc20593ba0cfb has been already found onchain
---
Aptos CLI is now set up for account 59836ba1dd0c845713bdab34346688d6f1dba290dbf677929f2fc20593ba0cfb as profile ledger!  Run `aptos --help` for more …
```
=> [CLI][Ledger] update derivation path format doc

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/providers/aptos_client.ts, ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts
The sdk provides a way to return the txn data when it succeed, added an example/test on how to use it.
For when a txn has failed, we throw an error with the txn hash and the failure reason message - Error class is a bit weird as it only outputs the "message" prop, unless we wrap it with try/catch and then we can get access to the other class properties, it feels like a big change for this use case and that should be good for now.
=> [TS SDK] Return txn data on success and txn failure reason on failure

Cargo.lock, crates/aptos-push-metrics/src/lib.rs, crates/node-resource-metrics/src/collectors/linux_collectors.rs, crates/node-resource-metrics/src/lib.rs, execution/executor-benchmark/Cargo.toml, execution/executor-benchmark/src/main.rs
- Fix the metrics pusher link for executor benchmark.
- Start the node metrics collector for the benchmark to gather system information
- Add a context switch counter to the metrics collector.
Run benchmark
=> Improvements to executor benchmark metrics collector

mempool/src/core_mempool/mempool.rs
This happens due to retry/duplication and should be ignored (instead of logging time 0). This cleans up the metric a bit, especially for forge tests that have enough latency that causes frequent transaction retries.
=> [Mempool] Don't log times that are <= 0 for insertion time to block timestamp

scripts/cli/build_cli_release.ps1
Update the build script to make sure `openssl` install correctly. Otherwise we will see the following error when running the windows build
error: failed to run custom build command for `openssl-sys v0.9.85`
```
Caused by:
process didn't exit successfully: `D:\a\aptos-core\aptos-core\target\cli\build\openssl-sys-c16c984f65a02d8a\build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset …
```
=> [CLI] Update build_cli_release.ps1 to include openssl

developer-docs-site/docs/guides/system-integrators-guide.md
aptos_account::transfer and aptos_account::transfer_coins should now be used instead of coin::transfer
=> [Docs] Update outdated references to coin::transfer

.github/actions/file-change-determinator/action.yaml, .github/actions/general-lints/action.yaml, .github/actions/python-lint-tests/action.yaml, .github/actions/rust-lints/action.yaml, .github/actions/rust-setup/action.yaml, .github/actions/rust-smoke-tests/action.yaml, .github/actions/rust-unit-tests/action.yaml, .github/workflows/lint-test.yaml, .github/workflows/workflow-run-execution-performance.yaml
This PR updates our GHA to avoid running the expensive code related tests on changes that are docs only. Essentially the PR:
- Adds a new file change determinator job using this [action](https://github.com/marketplace/actions/skip-duplicate-actions). Right now, I'm just checking for docs changes (e.g., `*.md` or only changes to `/developer-docs-site`).
- If the job identifies that only docs have changed:
- We skip running expensive and not required tests (e.g., performance tests, consensus tests, etc.)
- We still run expensive and required tests, but they essentially become a no-op (e.g., smoke tests, rust unit tests, linters, etc.). This way, all required jobs still pass but they're empty.
Note: in the PR, I've moved somethings into new files (e.g., `rust_lint`, `rust_unit_tests` , …
=> [GHA] Skip expensive tests on docs only changes.

ecosystem/typescript/sdk/examples/typescript/gas_fee_payer.ts, ecosystem/typescript/sdk/examples/typescript/pnpm-lock.yaml
* Updated the gas fee payer example to adopt the new API of aptos SDK v. 1.17.0
* Simplifies the flow significantly
`pnpm run gas_fee_payer`
=> [TS] Updated the gas fee payer example to adopt the new API

.github/workflows/cli-release.yaml
Update CLI Release work flow
1. updated `release_tag` to `release_version`
2. Use formatting on actual release tag and title
3. Add `dry_run` boolean to allow dry_run instead of actual release
=> update cli release workflow

.github/actions/rust-setup/action.yaml
This PR adds a missing flag to the `dev_setup.sh` script run as part of the `rust-setup` GHA.
=> [GHA] Ensure that rust tools are installed.

testsuite/forge-cli/src/main.rs, testsuite/forge/src/interface/prometheus_metrics.rs, testsuite/testcases/src/lib.rs
There were a few sporadic failures on landblocking PRs. increasing limits, and printing them better.
=> [forge][land blocking] recalibrate latency limits

Cargo.lock, aptos-move/aptos-release-builder/Cargo.toml, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-release-builder/src/components/mod.rs, aptos-move/aptos-release-builder/src/main.rs
Added an command to print out on chain configs.
Tested with following command: 
```
cargo run -- print-configs --endpoint https://fullnode.mainnet.aptoslabs.com/v1
```
And it printed out the values of configs properly
=> [aptos-release-builder] Print out on chain configs

.github/workflows/check-sdk-examples.yaml, .github/workflows/coverage.yaml, .github/workflows/faucet-tests.yaml, .github/workflows/forge-pfn.yaml, .github/workflows/forge-state-sync.yaml, .github/workflows/forge-unstable.yaml, .github/workflows/fullnode-execute-devnet-stable.yaml, .github/workflows/fullnode-fast-mainnet-stable.yaml, .github/workflows/fullnode-fast-testnet-stable.yaml, .github/workflows/fullnode-intelligent-devnet-main.yaml, .github/workflows/fullnode-intelligent-mainnet-main.yaml, .github/workflows/fullnode-intelligent-testnet-main.yaml, .github/workflows/indexer-grpc-integration-tests.yaml, .github/workflows/lint-test.yaml, .github/workflows/prover-test.yaml, .github/workflows/run-gas-calibration.yaml, .github/workflows/rust-client-tests.yaml, .github/workflows/ts-sdk-e2e-tests.yaml
This PR offers several changes (each in their commit):
1. To avoid running unnecessary tests on each PR, we skip non-required (i.e., non-land blocking) tests. If PR authors still want to run these tests, they can add the PR label `CICD:non-required-tests`.
2. We remove the scheduled runs of non-critical forge tests. Currently, only the `stable` forge tests are considered critical and high-signal. Other tests are less stable, flaky and really only need to be run on an adhoc basis (e.g., to test performance improvements, etc.). Going forward, we may want to change this (e.g., introduce separate categories of forge jobs, split up the stable jobs, etc.). But, until then, it makes sense to disable the nightly runs and just use ad-hoc scheduling for now.
3. We reduce the schedule frequency of …
=> [GHA] Skip non-required tests in PRs and reduce scheduled jobs.

aptos-move/framework/aptos-token-objects/doc/aptos_token.md, aptos-move/framework/aptos-token-objects/sources/aptos_token.move
Cherrypicking https://github.com/aptos-labs/aptos-core/commit/78fb3739692a45235bd1b59ea7ed1a71fab00959 into v1.5
=> [framework] Add Aptos-token mint function that returns object

.github/workflows/codeql-analysis.yaml, .github/workflows/coverage.yaml, .github/workflows/find-packages-with-undeclared-feature-dependencies.yaml, .github/workflows/prover-daily-test.yaml, .github/workflows/windows-build.yaml
Note: this PR builds on https://github.com/aptos-labs/aptos-core/pull/9503.
This PR reduces the frequency of various GHA jobs and schedules:
1. `CodeQL`: This job has been broken for several weeks. So, the PR disables the scheduled runs and allows manual invocations.
2. `Test Coverage`: This job hasn't worked in a long time. So, the PR disables the scheduled runs.
3. `Find Packages with undeclared feature dependencies`: This job also hasn't worked in a long time. So, the PR disables the scheduled runs.
4. `Prover Daily Test`: This job broke around 1.5 weeks ago. The PR reduces the frequency from daily to bi-weekly.
5. `Windows Build`: This PR reduces the frequency of the build job from daily to weekly. Daily shouldn't be needed(?).
=> [GHA] Reduce various automated jobs.

api/src/context.rs, api/src/transactions.rs, api/types/src/ledger_info.rs
A missing txn is not an internal server error, 410 is a more appropriate error code.
The long term fix is to make storage return typed errors, but this is a solid fix for now.
Run a local testnet with a modified config where the pruning window is much shorter:
```
cargo run -p aptos -- node run-local-testnet --force-restart --assume-yes --with-faucet --test-config-override ~/myfullnode.yaml
```
Config: https://gist.github.com/banool/7bf5f89cbd9ab999b16eb641413902a8.
Let it run for a while.
See that now instead of it being a 500, it is a 410 when a txn is missing:
```
curl -v localhost:8080/v1/transactions/by_version/1
```
Before:
```
< HTTP/1.1 500 Internal Server Error
{"message":"Failed to get transaction by version 1: Transaction at version 1 is pruned, min available version is …
```
=> [API] Return 410 when txn has been pruned, not 500

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/plugins/coin_client.ts, ecosystem/typescript/sdk/src/tests/e2e/coin_client.test.ts
Change default in the SDK to transfer with register.  Can still be turned off by specifying false
=> [ts-sdk] Fix default for coin client transfer and register on default

aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/mod.rs, aptos-move/aptos-release-builder/src/lib.rs, aptos-move/aptos-release-builder/src/main.rs
Currently this absolute path only works from within a docker image
This change makes the path relative and possible to run from elsewhere
Test Plan:
```
RUST_BACKTRACE=1 cargo run --profile performance -p aptos-release-builder \
generate-proposals \
--release-config aptos-move/aptos-release-builder/data/release.yaml --output-dir banana
```
=> [release-builder] Make release builder use a relative path for raw script

.github/workflows/lint-test.yaml
This PR removes the now non-required GHA jobs from the `lint-test.yaml` flow. The jobs that are removed in this PR have been replaced by the new (required) GHA flows: `general-lints`, `rust-lints`, `rust-smoke-tests`, `rust-unit-tests`. The benefit of this is that these jobs use the new GHA determinator, so they will become no-ops on docs only changes. 😄 Likewise, we can continue to extend the determinator to improve PR flows. 
Note: in order for this to land, we need to modify the branch protection rules for the `main` branch:
1. Remove these jobs from the main branch protection: `scripts-lint`, `ecosystem-lint`, `ecosystem-python-lint`, `rust-lint`, `rust-doc-test`, `rust-unit-test`, `rust-smoke-test` and `check-vm-features`.
2. Add these jobs to the main branch protection: …
=> [GHA] Remove non-required GHA jobs and migrate to new flows.

Cargo.lock, aptos-node/src/services.rs, aptos-node/src/state_sync.rs, aptos-node/src/tests.rs, consensus/src/consensus_provider.rs, consensus/src/epoch_manager.rs, consensus/src/twins/twins_node.rs, mempool/src/logging.rs, mempool/src/shared_mempool/coordinator.rs, mempool/src/shared_mempool/runtime.rs, mempool/src/shared_mempool/tasks.rs, mempool/src/tests/mocks.rs, mempool/src/tests/node.rs, mempool/src/tests/test_framework.rs, network/builder/src/builder.rs, network/discovery/src/file.rs, network/discovery/src/lib.rs, network/discovery/src/validator_set.rs, state-sync/inter-component/event-notifications/Cargo.toml, state-sync/inter-component/event-notifications/src/lib.rs, state-sync/inter-component/event-notifications/src/tests.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/driver_factory.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/storage_synchronizer.rs, types/src/on_chain_config/consensus_config.rs, types/src/on_chain_config/execution_config.rs, types/src/on_chain_config/mod.rs, vm-validator/Cargo.toml, vm-validator/src/mocks/mock_vm_validator.rs, vm-validator/src/vm_validator.rs
See https://github.com/aptos-labs/aptos-core/issues/9150 for more details
Existing Unit tests.
Tested it by running `test_onchain_shuffling_change`, which toggles the shuffling flag and ensures that the txn shuffling actually takes place.
=> [Configuration] Remove the need for maintaining an on-chain config registry

aptos-move/aptos-transaction-benchmarks/src/transactions.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/lib.rs, aptos-move/aptos-vm/src/sharded_block_executor/counters.rs, aptos-move/aptos-vm/src/sharded_block_executor/cross_shard_client.rs, aptos-move/aptos-vm/src/sharded_block_executor/cross_shard_state_view.rs, aptos-move/aptos-vm/src/sharded_block_executor/executor_client.rs, aptos-move/aptos-vm/src/sharded_block_executor/global_executor.rs, aptos-move/aptos-vm/src/sharded_block_executor/local_executor_shard.rs, aptos-move/aptos-vm/src/sharded_block_executor/mod.rs, aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs, aptos-move/aptos-vm/src/sharded_block_executor/test_utils.rs, aptos-move/aptos-vm/src/sharded_block_executor/tests.rs, aptos-move/block-executor/src/executor.rs, execution/block-partitioner/src/lib.rs, execution/block-partitioner/src/main.rs, execution/block-partitioner/src/sharded_block_partitioner/mod.rs, execution/executor-benchmark/src/block_partitioning.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, execution/executor-benchmark/src/pipeline.rs, execution/executor-service/src/remote_cross_shard_client.rs, execution/executor-service/src/remote_executor_client.rs, execution/executor-service/src/test_utils.rs, execution/executor/src/components/chunk_output.rs, execution/executor/src/fuzzing.rs, execution/executor/src/mock_vm/mod.rs, types/src/block_executor/partitioner.rs
- Adds support for global execution in sharding. On a high level a `partition_last_round` flag has been added to the partitioner, if it is false, then the last round is added as a global round.  
- Cleaned up the partitioning API to returned `PartitionedTransactions`. This holds both partitioned txns and global txns. 
- Added support for the global executor in the local execution client. 
UTs and ran the benchmark.  I am not making the global executor as default as I see around 5% TPS regression with this enabled by default.
=> [Execution][Sharding] Add support for global executor in sharding

.github/workflows/cargo-metadata-upload.yaml
This PR introduces a new workflow that generate a cargo metadata json file and uploads it to a GCS bucket. The metadata will be used for target determinator CLI.
GHA checks runs fine.
=> [gha] cargo metadata uploader

crates/aptos/e2e/cases/node.py, crates/aptos/e2e/main.py
Add the following 2 e2e tests
1. test_node_update_consensus_key
2. test_node_update_validator_network_address
Note: In the test, the `proof of possession key` are pre generated and hardcoded in test.
```
➜  e2e git:(jin/update_local_testnet_initial_validator_stake) ✗ DOCKER_DEFAULT_PLATFORM=linux/amd64 poetry run python main.py --base-network testnet --test-cli-path ~/Projects/aptos-core/target/debug/aptos
Configuration file exists at /Users/jinhou/Library/Preferences/pypoetry, reusing this directory.
Consider moving TOML configuration files to /Users/jinhou/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
2023-08-01 17:11:12,225 - INFO - Trying to run aptos CLI local testnet from image: aptoslabs/tools:testnet
2023-08-01 …
```
=> [CLI][e2e] Add node update consensus and network e2e

ecosystem/nft-metadata-crawler-parser/src/worker.rs
Allows worker to parser chain id from Pubsub. Also set google account credentials to optional in config yaml for deployment because it is automatically set in cloud run instsances.
=> [NFT Metadata Crawler] Parse chain id from Pubsub and prep config for deployment

.dockerignore, docker/builder/build-tools.sh, docker/builder/docker-bake-rust-all.hcl, docker/builder/nft-metadata-crawler.Dockerfile
Add nft metadata crawler parser to the aptos-core docker build process to integrate deployment with CI
Was able to successfully build image using the remote builder by running `./docker-bake-rust-all.sh nft-metadata-crawler`
Fixes EI-254
=> [NFT Metadata Crawler] Dockerize Parser

execution/executor-benchmark/src/account_generator.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, execution/executor-benchmark/src/transaction_generator.rs
Command example:
cargo run -p aptos-executor-benchmark -- --block-size 50 --independent-tx-grps-in-a-block 10 run-executor --main-signer-accounts 1000 --data-dir /tmp/some-db --checkpoint-dir /tmp/some-checkpoint --blocks 2
Note: For a good random workload we would want 'num_accounts_per_grp' to be much greater than 'num_txns_per_grp'.
The command enforces 'num_accounts_per_grp' > 'num_txns_per_grp'.
=> [Executor-benchmark] Command to generate connected groups of random txns

ecosystem/typescript/sdk_v2/package.json, ecosystem/typescript/sdk_v2/src/api/aptos_config.ts, ecosystem/typescript/sdk_v2/src/utils/api-endpoints.ts, ecosystem/typescript/sdk_v2/src/utils/const.ts, ecosystem/typescript/sdk_v2/tests/unit/aptos_config.test.ts
This PR adds support for network and API endpoints on `AptosConfig`. Once `Aptos` is initialized, a network and API endpoints are being set.
- Ability to initialize `Aptos` with no network and then it assigns a default one (testnet)
- Ability to initializes `Aptos` with a local/devnet/test/mainnet network, and the sdk assigns the network endpoint for each service (fullnode, faucet, indexer).
- Ability to initialize `Aptos` with a custom network - it expects the user to also provide the API endpoints.
This would be much simpler once API v2/gateway is ready.
=> [TS SDK] Support network and API endpoints on `AptosConfig`

testsuite/forge-cli/src/main.rs
we should see why HA proxy increases time to commit so much afterwards
=> [forge stable] Fix HAProxy test - increase latency limits

ecosystem/indexer-grpc/indexer-grpc-data-service/src/main.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
* we're seeing about 1.6G memory usage per stream; with this change, we can reduce memory to 100mb for each stream.
=> [indexer grpc] reduce the data service streaming channel size

aptos-move/aptos-aggregator/src/delta_change_set.rs, aptos-move/aptos-validator-interface/src/lib.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/aptos-vm/src/sharded_block_executor/cross_shard_state_view.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/view.rs, aptos-move/e2e-tests/src/data_store.rs, aptos-move/vm-genesis/src/genesis_context.rs, execution/executor/src/mock_vm/mock_vm_test.rs, execution/executor/src/mock_vm/mod.rs, storage/state-view/src/in_memory_state_view.rs, storage/state-view/src/lib.rs, storage/storage-interface/src/cached_state_view.rs, storage/storage-interface/src/state_view.rs
`is_genesis()` was defined in `StateView` but never used apart from a single test with `MockVM`.
But the test set it to false always... Removing it to have better view interfaces.
=> [refactoring] Remove unused genesis check from StateView

developer-docs-site/docs/nodes/full-node/aptos-db-restore.md
This PR updates the dev docs with a small note about specifying the `target-version` in the db-restore docs.
=> [Dev Docs] Add small note about target-version in backup docs.

.github/workflows/cli-e2e-tests.yaml, .github/workflows/docker-build-test.yaml, .github/workflows/execution-performance.yaml, .github/workflows/indexer-grpc-integration-tests.yaml, .github/workflows/lint-test.yaml, .github/workflows/node-api-compatibility-tests.yaml, .github/workflows/workflow-run-forge.yaml
This PR makes the following changes:
1. Gate the smoke and performance tests to only run under appropriate conditions on each PR (e.g., auto-merge or label application). This has several benefits: (i) only run these expensive tests when folks hit auto-merge, thus helping to reduce/avoid unnecessary runs; and (ii) once @ibalajiarun's determinator lands (https://github.com/aptos-labs/aptos-core/pull/9463), we'll be able to give PR authors correctness signals much sooner (via the unit tests). The idea is that the unit tests should offer the first set of correctness signals to PR authors, before we run the more expensive tests.
2. Make the expensive forge tests no-ops on docs only changes.
=> [GHA] Run smoke, performance & forge tests when appropriate.

.github/actions/file-change-determinator/action.yaml, .github/actions/general-lints/action.yaml
This PR offers two tiny tweaks to the file change determinator and lint workflows. Specifically, we want to disable `skip_after_successful_duplicate` because it produce false positives (i.e., job skips where we don't want it).
=> [GHA] Small tweaks to target determinator.

ecosystem/python/sdk/aptos_sdk/aptos_token_client.py, ecosystem/python/sdk/aptos_sdk/async_client.py, ecosystem/python/sdk/examples/aptos-token.py
Adding a `token_transfer` function to the python client. It is really just an object transfer, but wasn't sure where to put an object transfer for now.
The transfer function and the extra documentation tags are for my next PR for the `your first non-fungible asset` tutorial that I'm updating ASAP.
----
e: Moved the transfer call to the rest client as a generic object_transfer function and updated the token_transfer function to call object_transfer. Added a simple example of it to the end of the `aptos-token.py` example:
```yaml
=== Transferring the Token from Alice to Bob ===
Alice: 0x8a6a0b29ae3ccbf00a2aba89612b19b265ad5162ccce9159b6af424774c45bae
Bob:   0x409dba9c7d4f4d6866071895fe79dbf7ba7db16486f47343ba4be0da849d76a9
Token: 0xd9f96e6cfd4eead5ba84b877b654de72fddf1ecba5abf8eba035be572182 …
```
=> [Python SDK] Add a token_transfer function to the python SDK

Cargo.lock, Cargo.toml, third_party/move/documentation/examples/diem-framework/crates/cli/Cargo.toml, third_party/move/evm/extract-ethereum-abi/Cargo.toml, third_party/move/evm/move-to-yul/Cargo.toml, third_party/move/move-analyzer/Cargo.toml, third_party/move/move-compiler-v2/Cargo.toml, third_party/move/move-compiler-v2/src/options.rs, third_party/move/move-compiler/Cargo.toml, third_party/move/move-ir-compiler/Cargo.toml, third_party/move/move-prover/Cargo.toml, third_party/move/move-prover/lab/Cargo.toml, third_party/move/testing-infra/test-generation/Cargo.toml, third_party/move/testing-infra/transactional-test-runner/Cargo.toml, third_party/move/tools/move-bytecode-viewer/Cargo.toml, third_party/move/tools/move-cli/Cargo.toml, third_party/move/tools/move-coverage/Cargo.toml, third_party/move/tools/move-disassembler/Cargo.toml, third_party/move/tools/move-explain/Cargo.toml, third_party/move/tools/move-package/Cargo.toml, third_party/move/tools/move-unit-test/Cargo.toml
This mainly just cleans up a little compiler v2 interfacing so all of the codebase is on the same version of clap.  It should just make every input a 0 or more argument input, and if there are any that you want fixed, feel free to call them out.
build seems to work, let's see how CI handles it.
=> [deps] Update clap dependency to be consistent across crates

.github/workflows/node-api-compatibility-tests.yaml
The issue was introduced by merging a bunch of `run` commands into one. How it used to work was:
1. `cd ./ecosystem/typescript/sdk && pnpm generate-client -o /tmp/generated_client`
2. `git diff --no-index --ignore-space-at-eol --ignore-blank-lines ./ecosystem/typescript/sdk/src/generated/ /tmp/generated_client/`
Now that they are merged, the `git diff` command in step 2 is trying to access `./ecosystem/typescript/sdk/src/generated/` but at this point we're already cd'd into this directory, so the path isn't there.
This PR fixes the issue by separating them into separate run commands again.
Because this uses `workflow_dispatch` I'll have to do the thing where I switch to `pull_request` temporarily. Stay posted.
Update: The fix works, see a successful run here: …
=> Fix node compatibility test CI

aptos-move/aptos-vm-types/src/storage.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/e2e-testsuite/Cargo.toml, aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs
This fixes a bug in the original abstract gas implementation, allowing the io gas to be expressed as an abstract amount rather than a concrete one. This should not change the behavior of the production binary at all.
=> [gas] fix abstract gas cost for storage

ecosystem/typescript/sdk/src/tests/e2e/client.test.ts
This test is not really a SDK test but more an API test. if we really want to test the sdk, we should probably mock the response, and then check if on second request cookies are still there.
Having this test here can block CI when devnet is down
=> remove redundant test

consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_network.rs, consensus/src/dag/reliable_broadcast.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_network_test.rs, consensus/src/dag/tests/mod.rs, consensus/src/dag/tests/reliable_broadcast_tests.rs, consensus/src/dag/tests/types_test.rs, consensus/src/dag/types.rs, crates/reliable-broadcast/src/lib.rs, crates/reliable-broadcast/src/tests.rs
This PR removes the `CertifiedNodeHandler` and instead implements the `RpcHandler` on DagDriver to handle `CertifiedNode`. 
Also, adds a method to trigger a new round from special case current round 0 from Dag Handler.
Existing tests fixed.
=> [dag] Handle certified node in DAG Driver

ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs, ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Fixed error where I was defaulting to wrong uri when parsing image. Also added logging instead of swallowing GCS errors. 
Tested locally and works
=> [NFT Metadata Crawler] Fix error for defaulting to original raw_image_uri

ecosystem/typescript/sdk/examples/typescript-esm/offer_capabilities.ts, ecosystem/typescript/sdk/examples/typescript-esm/package.json
It is sort of unclear how to sign Move structs with the typescript SDK, this PR is two examples that should make it more clear.
It is also an example of how to use the `account::offer_rotate_capability` and `account::offer_signer_capability` Move functions.
Note that for some reason the assertion failed for me a few times even though the offer was correct. Not sure what was going on there or how to reproduce it. It was on localnet, I thought it was a stale sequence number at first but wasn't able to produce the error again after casting the addresses to strings
`cd ~/aptos-core/ecosystem/typescript/sdk/examples/typescript-esm && pnpm run offer_capabilities`
The scripts assert at the end that the account's resources reflect the new offers (Alice offers to Bob).
=> [ts-sdk example] Adding an example for rotation offer capability and signer offer capability with signed structs

ecosystem/typescript/sdk_v2/package.json, ecosystem/typescript/sdk_v2/src/core/common.ts, ecosystem/typescript/sdk_v2/src/core/hex.ts, ecosystem/typescript/sdk_v2/src/core/index.ts, ecosystem/typescript/sdk_v2/src/types/index.ts, ecosystem/typescript/sdk_v2/tests/unit/hex.test.ts
This PR defines the `Hex` class. This class provides a way for working with non-account-address hex data, e.g. txn hashes. It provides methods for creating instances of the Hex class as well as static methods to make it easy to quickly work with hex data. This is explained further in the file level comment.
```
cd ecosystem/typescript/sdk_v2
npx jest -- tests/unit/hex.test.ts
```
=> [TS SDK v2] Add Hex and HexInput types

aptos-move/framework/aptos-framework/doc/resource_account.md, aptos-move/framework/aptos-framework/sources/resource_account.move
Fixing typos and renaming the (confusing) `resource` arg to `init_module` to a more appropriate `resource_account`.
=> Clearer comments in `resource_account.move`

aptos-move/aptos-vm/src/aptos_vm_impl.rs
With this we can go through all historical txns to make sure.
replay: https://github.com/aptos-labs/aptos-core/actions/runs/5815138842
=> Explicitize that the txn_seq_num param on the epilogue is unused

consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/order_rule.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/order_rule_tests.rs
This PR integrates the Order rule with the DAG driver. Whenever the dag driver adds a certified node to the DAG, it calls the order rule to try and commit nodes that have enough voting power.
=> [dag] Integrate Order Rule with dag driver

aptos-move/aptos-gas-calibration/src/main.rs, aptos-move/aptos-gas-calibration/src/solve.rs
Currently the output isn't that helpful, as the numbers represent the gas usage per instruction. This PR converts these numbers to the InternalGas cost, which allows for future roadmap items like updating the gas schedule much easier. 
Before:
```
where the gas parameter values are (microsecond per instruction):
0.03320208133434005 ADD
0.02167781151796508 AND
0.03401204199678623 BIT_AND
```
After:
```
internal gas cost (66666 InternalGas per 1µ):
ADD = 2213.4499542351136
AND = 1445.17298265666
BIT_AND = 2267.446791757751
```
=> [gas] convert output to InternalGas cost

third_party/move/move-ir-compiler/move-ir-to-bytecode/src/compiler.rs, third_party/move/move-ir-compiler/move-ir-to-bytecode/syntax/src/lexer.rs, third_party/move/move-ir-compiler/move-ir-to-bytecode/syntax/src/syntax.rs, third_party/move/move-ir-compiler/transactional-tests/tests/bytecode-generation/statements/nop.exp, third_party/move/move-ir-compiler/transactional-tests/tests/bytecode-generation/statements/nop.mvir, third_party/move/move-ir/types/src/ast.rs
Closes #9416 
Discussion: Nop has an optional NopLabel, although it is unclear the exact purpose/usage of this.
See `transactional-tests/tests/bytecode-genereation/statements/nop.mvir`
Run `cargo run -- -m ./transactional-tests/tests/bytecode-generation/statements/nop.mvir`
Run `cargo run -p aptos -- move disassemble --bytecode-path ./transactional-tests/tests/bytecode-generation/statements/nop.mv`
To see that the Nop token is included in the bytecode generation
Output:
```
// Move bytecode v6
module cafe.Nop {
nop_valid() {
B0:
0: Nop
1: Ret
}
nop_invalid() {
B0:
0: Nop
1: Pop
2: Ret
}
}
```
=> [move-ir-compiler] add Nop token support

ecosystem/typescript/sdk_v2/src/core/account_address.ts, ecosystem/typescript/sdk_v2/src/core/index.ts, ecosystem/typescript/sdk_v2/tests/unit/account_address.test.ts
This PR implements AccountAddress for the v2 TS SDK. This implementation conforms to AIP-40.
```
cd ecosystem/typescript/sdk_v2
npx jest -- tests/unit/account_address.test.ts
```
=> [TS SDK v2] Add AccountAddress

crates/aptos/src/account/key_rotation.rs
It isn't harmful that we allow this, it's just there is no point in allowing it.
```
$ ~/a/core/target/debug/aptos account rotate-key --private-key 0x98b22207d27a4b843e833f292a7f7ea8bb29829a0db018b2db6444636061aea9 --new-private-key 0x98b22207d27a4b843e833f292a7f7ea8bb29829a0db018b2db6444636061aea9 --url https://fullnode.testnet.aptoslabs.com
{
"Error": "Invalid arguments: New private key cannot be the same as the current private key"
}
```
=> [CLI] Disallow "rotating" to same private key

Cargo.lock, Cargo.toml, aptos-move/mvhashmap/Cargo.toml, aptos-move/mvhashmap/src/lib.rs, aptos-move/mvhashmap/src/types.rs, aptos-move/mvhashmap/src/versioned_aggregators.rs
Since it's keyed by ID (defined locally for now), sending to the v2 branch.
=> Multi-version (sub)-data-structure for Aggregators and AggregatorSnapshots

ecosystem/typescript/sdk/examples/typescript-esm/multi_ed25519_to_multisig.ts, ecosystem/typescript/sdk/examples/typescript-esm/package.json
As a part of an effort to address https://github.com/aptos-labs/aptos-core/issues/8710, this is the second example of signed structs with the Typescript SDK
**This example demonstrates how to convert a MultiEd25519 account to a MultiSig account and revoke its auth key using the `0x1::multisig_account` module.**
1. Initialize N accounts and fund them.
2. Initialize a MultiEd25519 account with the created accounts as owners and a signature threshold K as NUM_SIGNATURES_REQUIRED
- See: https://aptos.dev/concepts/accounts/#multi-signer-authentication for more information on MultiEd25519 accounts.
3. Create a proof struct for at minimum K of the N accounts to sign.
4. Gather the signatures from the accounts.
5. Assemble a MultiEd25519 signed proof struct with the gathered signatures.
6. Call …
=> [TS SDK example] Add a working example of converting a MultiEd25519 account to a MultiSig account

aptos-move/framework/aptos-token-objects/doc/token.md, aptos-move/framework/aptos-token-objects/sources/token.move
The comments describing two functions in token.move seem to have been copied over from the equivalent in collection.move. This PR simply updates them for the context of a token instead of a collection.
=> Improve clarity of comments on token.move

ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris_query.rs, ecosystem/nft-metadata-crawler-parser/src/utils/database.rs, ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs, ecosystem/nft-metadata-crawler-parser/src/utils/json_parser.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Fixed an error where the deduplication process was blocking all new raw_image_uris from being written. Also if a duplicate URI is detected, it should be skipped and its CDN URI should be set to the existing one. Adding functionality to the setting CDN URI part because it was previously left out. 
Works locally
Fixes EI-305
=> [NFT Metadata Crawler] Fix raw image uri parse error

third_party/move/move-compiler-v2/src/bytecode_generator.rs, third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs, third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs, third_party/move/move-compiler-v2/src/pipeline/livevar_analysis_processor.rs, third_party/move/move-compiler-v2/tests/bytecode-generator/reference_conversion.exp, third_party/move/move-compiler-v2/tests/bytecode-generator/reference_conversion.move, third_party/move/move-compiler-v2/tests/file-format-generator/generic_call.exp, third_party/move/move-compiler-v2/tests/file-format-generator/generic_call.move, third_party/move/move-compiler-v2/transactional-tests/tests/control_flow/sorter.exp, third_party/move/move-compiler-v2/transactional-tests/tests/control_flow/sorter.move, third_party/move/move-compiler-v2/transactional-tests/tests/evaluation_order/arg_order.exp, third_party/move/move-compiler-v2/transactional-tests/tests/evaluation_order/arg_order.move, third_party/move/testing-infra/transactional-test-runner/src/framework.rs, third_party/move/testing-infra/transactional-test-runner/src/tasks.rs
This fixes a few bugs and closes #9629
- Usage of precompiled stdlib in transactional tests: v2 compiler currently (and probably never) supports precompiled modules, working around this
- Stack-based bytecode generator created wrong target on generic function calls
- Needed to make implicit conversion from `&mut` to `&` explicit in generated bytecode via Freeze operation
Added some additional tests while debugging this.
=> [compiler v2] Fix bugs around compilation of vector code

ecosystem/typescript/sdk_v2/src/core/account_address.ts, ecosystem/typescript/sdk_v2/tests/unit/account_address.test.ts
In the v2 TS SDK the `fromString` function enforces strict parsing. As written though, it wasn't exactly spec compliant in that it allowed padding zeroes in addresses. This PR fixes that.
```
npx jest -- tests/unit/account_address.test.ts
```
=> [TS SDK v2] Reject invalid SHORT form for special addresses in fromString

ecosystem/typescript/sdk_v2/src/core/account_address.ts, ecosystem/typescript/sdk_v2/src/core/hex.ts, ecosystem/typescript/sdk_v2/tests/unit/account_address.test.ts, ecosystem/typescript/sdk_v2/tests/unit/hex.test.ts
Due to the magic of JS, `===` will return false for instances of these classes that have the same underlying data, and sadly there is nothing we can do about that. To remedy that, we offer these `equals` methods to help with comparing instances of these classes.
```
npx jest -- tests/unit/*
```
=> [TS SDK v2] Add equality methods for Hex and AccountAddress

third_party/move/move-prover/boogie-backend/src/options.rs
The upgrade of Z3 and Boogie is mostly backward compatible, but not always. This fix allows Prover to warn users for the higher version of Z3 and Boogie because those may be incompatible (refer: https://github.com/aptos-labs/aptos-core/issues/8718)
Tested on Mac Arm64 with no current boogie or Z3 installation
Code is visibly unchanged for other cases
=> [prover] lock version dependency for z3 and boogie (#8718)

developer-docs-site/docs/move/move-on-aptos/cli.md
Aptos Move CLI is confusing, should just be Aptos CLI
=> [docs] Rename Aptos Move CLI -> Aptos CLI

config/src/config/state_sync_config.rs, state-sync/storage-service/server/src/handler.rs, state-sync/storage-service/server/src/lib.rs, state-sync/storage-service/server/src/logging.rs, state-sync/storage-service/server/src/metrics.rs, state-sync/storage-service/server/src/optimistic_fetch.rs, state-sync/storage-service/server/src/subscription.rs, state-sync/storage-service/server/src/tests/optimistic_fetch.rs, state-sync/storage-service/server/src/tests/storage_summary.rs, state-sync/storage-service/server/src/utils.rs, state-sync/storage-service/types/src/requests.rs, state-sync/storage-service/types/src/responses.rs, state-sync/storage-service/types/src/tests.rs
Note: a lot of this PR is boilerplate (based on the existing optimistic fetch implementation).
This PR adds subscription stream support to the storage service. Specifically, it allows clients to: (i) send multiple subscription requests to the server; (ii) have the server hold those requests in a pending queue; and (iii) serve those requests (in order, one at a time) with new data, as new data is made available (e.g., locally committed). This is similar to the existing optimistic fetch functionality, but it allows the clients to have multiple in-flight requests at once (to emulate the behaviour of the server "streaming" transaction chunks to the client).
1. Add support for the new request types (including a new test to ensure serviceability of the requests by …
=> [Storage Service] Add subscription stream support.

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/framework/aptos-stdlib/sources/debug.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/framework/src/natives/string_utils.rs, types/src/on_chain_config/aptos_features.rs
- This PR fixes the issue (https://github.com/aptos-labs/aptos-core/issues/8865.) of `string_utils::native_format` in formatting signer values
Resolves https://github.com/aptos-labs/aptos-core/issues/8865.
cargo test -p aptos-framework
=> Fixed signer to be formatted properly

execution/executor/src/block_executor.rs
=> [Execution] Do not hold the Arc of committed block in execution.

ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs, ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs, ecosystem/nft-metadata-crawler-parser/src/utils/json_parser.rs
Previously the timeout was too short so many of the semi-large could not finish downloading, this increases that timeout.
=> [NFT Metadata Crawler] Increase HTTP request for large files

ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs
The original dimensions for image resizing were hardcoded to 400x400. This change updates the resizing functionality so that the aspect ratio of the original image is maintained.
=> [NFT Metadata Crawler] Maintain image aspect ration on resize

consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_fetcher.rs, consensus/src/dag/dag_network.rs, consensus/src/dag/mod.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_network_test.rs, consensus/src/network.rs
This PR implements the DAG Network Sender trait.
=> [dag] network sender implementation

aptos-move/aptos-aggregator/src/delta_change_set.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/view.rs, storage/state-view/src/lib.rs
Adds `get_state_value_u128` to `TStateView`.
It helps to clean up the code a bit when working with accumulators.
More importantly, it helps to avoid unnecessary serialization and deserialization in some cases, when one `TStateView` wraps around another as the base `TStateView` may already internally store the value as an integer.
I am using such wrappers extensively in the upcoming fast path executor.
=> Add get_state_value_u128 method to TStateView

scripts/dev_setup.sh
* Archlinux / python / pip insist that you use the package manager solutions not python for pip
* The `libudev-dev` seems to exist in the default system install and under a wildly different name.
=> [scripts] fixes to arch linux (pacman)

aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/output.rs, aptos-move/aptos-vm-types/src/tests/test_change_set.rs, aptos-move/aptos-vm-types/src/tests/test_output.rs, aptos-move/aptos-vm-types/src/tests/utils.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/baseline.rs, aptos-move/block-executor/src/proptest_types/bencher.rs, aptos-move/block-executor/src/proptest_types/tests.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/view.rs, aptos-move/mvhashmap/src/lib.rs, aptos-move/mvhashmap/src/unit_tests/mod.rs, aptos-move/mvhashmap/src/unit_tests/proptest_types.rs, aptos-move/mvhashmap/src/versioned_data.rs, aptos-move/mvhashmap/src/versioned_modules.rs, aptos-move/vm-genesis/src/lib.rs, aptos-move/writeset-transaction-generator/src/writeset_builder.rs, types/src/write_set.rs
Refactor in order to:
- Better encapsulate the state in LatestView, in particular, support the counter that is shared among worker threads in the parallel setting (like MVHashMap). @vusirikala: should address some issues from https://github.com/aptos-labs/aptos-core/pull/9000 for generating ephemeral IDs for aggregators
- Expose traits for the output to be able to process data vs modules vs aggregator_v1 changes more granularly, separate the v1 aggregator so v2 can be implemented and gated separately.
- Improve MVHashMap interfaces to avoid dispatching on module_path per key (also expensive).
- Change unnecessary BTreeMaps to HashMap.
=> [Block Executor] Refactor view & output traits & mvhashmap

ecosystem/nft-metadata-crawler-parser/src/utils/uri_parser.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Fixed an error with the URI parsing where there is an extra `/` and changed the ACKing logic to reduce queue ingestion. 
Works locally
=> [NFT Metadata Crawler] Fix double slash URI parsing error, add ACKing PubSub message on receive

crates/aptos-rest-client/src/faucet.rs, crates/aptos/Cargo.toml, crates/aptos/src/account/fund.rs, crates/aptos/src/common/init.rs, crates/aptos/src/common/types.rs, crates/aptos/src/common/utils.rs, crates/aptos/src/test/mod.rs
Might be nice to use the FaucetClient but for now there is no way to set the auth token (pending https://github.com/aptos-labs/aptos-core/pull/9577). So for now I just modify what we have already.
Without auth token:
```
cargo run -p aptos -- account fund-with-faucet --account 0x5 --url https://fullnode.testnet.aptoslabs.com --faucet-url https://faucet.testnet.aptoslabs.com
```
```
{
"Error": "API error: Faucet issue: 429 Too Many Requests"
}
```
With auth token:
```
FAUCET_AUTH_TOKEN=123 cargo run -p aptos -- account fund-with-faucet --account 0x5 --url https://fullnode.testnet.aptoslabs.com --faucet-url https://faucet.testnet.aptoslabs.com
```
```
{
"Result": "Added 100000000 Octas to account 0000000000000000000000000000000000000000000000000000000000000005"
}
```
=> [CLI] Add support for setting faucet auth token

aptos-move/aptos-release-builder/data/release.yaml
Test Plan: ran yq / generate proposals locally
```
target/performance/aptos-release-builder generate-proposals --release-config aptos-move/aptos-release-builder/data/release.yaml --output-dir output
```
=> [framework] Reset the release yaml for upcoming 1.7 release

consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_fetcher.rs, consensus/src/dag/dag_store.rs, consensus/src/dag/rb_handler.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/tests/fetcher_test.rs, consensus/src/dag/tests/order_rule_tests.rs, consensus/src/dag/tests/rb_handler_tests.rs
This PR integrates DAG fetcher to the RB node handler. Whenever the node is missing parents, the fetcher is requested to fetch those missing parents and their ancestors. To make sure the GCed DAG is not refetched, it changes the lowest_round in dag_store to provide the information.
=> [dag] Integrate dag fetcher with RB node handler

ecosystem/indexer-grpc/indexer-grpc-post-processor/src/pfn_ledger_checker.rs
* If the stream stops, we need to default to 10s. 
Locally tested; looks good.
=> [monitoring] set the default latency if entry is absent from the map.

consensus/src/dag/dag_store.rs, consensus/src/dag/tests/dag_test.rs
This PR fixes the bitmask fn in the dag_store to make it return the proper bitmask when starting from an empty DAG. Previously, it was only properly handling the case when the initial round of the DAG store is 0, which doesn't accommodate for when starting a DAG store without the whole prefix.
Fixed unit tests.
=> [dag][bugfix] fix bitmask for incomplete first round

Cargo.lock, experimental/execution/ptx-executor/Cargo.toml, experimental/execution/ptx-executor/src/analyzer.rs, experimental/execution/ptx-executor/src/common.rs, experimental/execution/ptx-executor/src/finalizer.rs, experimental/execution/ptx-executor/src/runner.rs, experimental/execution/ptx-executor/src/scheduler.rs, experimental/execution/ptx-executor/src/sorter.rs, experimental/execution/ptx-executor/src/state_reader.rs, experimental/execution/ptx-executor/src/state_view.rs
Fix a bug where runners are still pushing state values that don't block any txns to the scheduler when the latter has already quit (because all dependencies were fullfilled).
=> adjustments

consensus/src/quorum_store/batch_coordinator.rs, consensus/src/quorum_store/counters.rs, consensus/src/quorum_store/network_listener.rs, consensus/src/quorum_store/tests/batch_generator_test.rs
Add back incrementing `RECEIVED_BATCH_COUNT` which was accidentally removed in #9673.
Clean up updating `RECEIVED_REMOTE_BATCH_COUNT` so it's done in the same place.
=> [Quorum Store] Add back received batch count, and clean up around it

mempool/src/shared_mempool/network.rs, mempool/src/shared_mempool/tasks.rs
Reduce the noise added by #9309. Make expected "errors" trace, and sample regardless.
=> [Mempool] reduce mempool log noise

Cargo.lock, aptos-move/aptos-transaction-benchmarks/Cargo.toml, aptos-move/aptos-transaction-benchmarks/src/benchmark_runner.rs, aptos-move/aptos-transaction-benchmarks/src/lib.rs, aptos-move/aptos-transaction-benchmarks/src/main.rs, aptos-move/aptos-transaction-benchmarks/src/transaction_bench_state.rs, aptos-move/aptos-transaction-benchmarks/src/transactions.rs
Add a change to support pre-generating all transactions - this helps to isolate the noise from CPU usage in generating the transactions and also measures CPU utilization of execution only phase.
```
cargo run --release -p aptos-transaction-benchmarks execute --generate-then-execute --num-accounts 100000 --block-size 50000 --concurrency-level-per-shard 10
```
=> [Execution][Benchmark] Add support for a pre-generating all transactions in the block-stm benchmark

ecosystem/python/sdk/CHANGELOG.md, ecosystem/python/sdk/aptos_sdk/account_address.py
In this PR the `from_str` function on `AccountAddress` has been updated to conform to the strict parsing described by [AIP-40](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-40.md). For the relaxed parsing behavior of this function prior to this change, folks can use `AccountAddress.from_str_relaxed`.
Whereas with Rust we will almost certainly keep `from_str` the relaxed variant for now, with Python we're still at 0.x.x, so we're at greater liberty to make changes like this. Open to contrary thoughts though.
```
poetry run python -m unittest aptos_sdk/account_address.py
```
=>  [Python SDK] Make from_str strict, add from_str_relaxed

developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md
This PR updates the `Run a Public Fullnode with the Aptos Source Code or Docker` developer doc page to mention that testnet fullnodes need to use a backup or snapshot when first starting up. This avoids issues with genesis and peer discovery.
Manual verification, see:
=> [Dev Docs] Update node running instructions to mention testnet requirement.

developer-docs-site/docs/indexer/api/self-hosted.md
Addresses part of https://github.com/aptos-labs/aptos-core/issues/9758. 
This doc adds info about running the standard processor stack we offer. It doesn't tell users anything about hooking up an API to the DB.
Docs.
=> [indexer-docs] Add basic guide to self hosting the Indexer API

experimental/execution/ptx-executor/src/common.rs, experimental/execution/ptx-executor/src/finalizer.rs
A few tweaks to improve my easy workload (10k out of 1M active users, 50k block size) from 60k VM TPS to 64k vm TPS.
finalizer hack to only look at the total_supply - 60k → 62k
use hashbrown - 62k -> 64k
=> [ptx executor] small tweaks 

.github/workflows/replay-verify.yaml, .github/workflows/workflow-run-replay-verify.yaml, testsuite/replay_verify.py
Parallel partitions of each runner decreased to 16 from 32 so that we can scale on cheaper machines with 200G mem
Runner number increase to 16 from 8
Load is balanced across runners. 
Aws shows the finishing time is closed to 2 hrs. the outlier is manually adjusted
https://github.com/aptos-labs/aptos-core-private/actions/runs/5869091896
test replay https://github.com/aptos-labs/aptos-core/actions/runs/5872812275
=> balanced replay-verify

aptos-move/framework/aptos-framework/doc/vesting.md, aptos-move/framework/aptos-framework/sources/vesting.move, aptos-move/framework/aptos-framework/sources/vesting.spec.move, aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
This PR allows updating the commission percentage for a vesting contract, which is the feature that the [AIP-48](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-48.md) proposes.
- Added the function `vesting::update_commission_percentage` and test cases
- Deprecated `staking_contract::update_commision` because the function name has a typo.
- Instead, added `staking_contract::update_commission_percentage`
=> [Stake] Added `update_commission_percentage`

scripts/dev_setup.sh
node.js 14.x is no longer receiving updates, 18.x is the latest LTS release
This is hopefully a fully compatible no-op. Let the automated test suite handle things.
=> bump node.js to 18.x

aptos-move/framework/aptos-stdlib/doc/smart_table.md, aptos-move/framework/aptos-stdlib/doc/smart_vector.md, aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move, aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move, aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.move, aptos-move/framework/aptos-stdlib/sources/data_structures/tests/smart_table_test.move, aptos-move/framework/aptos-stdlib/sources/data_structures/tests/smart_vector_test.move
see the implementations. all is missing here because it triggers the error mentioned in
https://github.com/aptos-labs/aptos-core/issues/9717
https://github.com/aptos-labs/aptos-core/issues/6615
again.
cc @wrwg @brmataptos
ut
=> [smart_table] a lot of inline functions added

aptos-move/e2e-move-tests/src/aggregator.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/transaction_fee.rs
Adding parallel execution tests for aggregators to ensure
we test both sequential and parallel paths.
=> [aggregator] Add parallel execution to aggregator tests

consensus/src/state_computer.rs, execution/executor-benchmark/src/ledger_update_stage.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/pipeline.rs, execution/executor-benchmark/src/transaction_executor.rs, execution/executor-types/src/execution_output.rs, execution/executor-types/src/ledger_update_output.rs, execution/executor-types/src/lib.rs, execution/executor-types/src/state_checkpoint_output.rs, execution/executor/src/block_executor.rs, execution/executor/src/components/apply_chunk_output.rs, execution/executor/src/components/block_tree/mod.rs, execution/executor/src/components/block_tree/test.rs, execution/executor/src/components/chunk_output.rs, execution/executor/src/metrics.rs, execution/executor/src/tests/mod.rs, testsuite/single_node_performance.py
Today the ledger update being sequential and in the critical path of execution consumes around ~15% of the execution. This change introduces a new phase for ledger update. Please note that the change only affects the executor benchmark, and current production path should not be affected. We will have a separate change to add a new pipeline stage for this. 
Ran the benchmark and observed ~10% TPS gain in sharded execution.
=> [Execution][Storage] Split the ledger update to a separate phase

aptos-move/aptos-vm/src/natives.rs
Lint in `natives.rs` is broken because there was
no `#[cfg(feature = "testing")]` annotation.
=> [format] Fix lint

aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-release-builder/src/components/mod.rs
The module event feature is supposed to be enabled only briefly during framework upgrade to allow the new framework to publish, until the feature is approved by governance and enabled again. This tests the workflow and tooling work.
framework_upgrade forge test
=> disable module_event feature after framework update is done

Cargo.lock, config/Cargo.toml, config/src/config/config_optimizer.rs, config/src/config/node_config_loader.rs, config/src/config/test_data/public_full_node.yaml, network/framework/src/connectivity_manager/mod.rs, terraform/helm/aptos-node/values.yaml, terraform/helm/fullnode/values.yaml
This PR adds dedicated seed peer support for testnet and mainnet. This is useful for nodes that wish to sync to the network with only the genesis blob.
=> [Configs] Add seed peers for testnet and mainnet.

Cargo.lock, ecosystem/nft-metadata-crawler-parser/Cargo.toml, ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris_query.rs, ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs, ecosystem/nft-metadata-crawler-parser/src/utils/counters.rs, ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs, ecosystem/nft-metadata-crawler-parser/src/utils/json_parser.rs, ecosystem/nft-metadata-crawler-parser/src/utils/mod.rs, ecosystem/nft-metadata-crawler-parser/src/utils/uri_parser.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Add some metrics to the parser
- PARSER_INVOCATIONS_COUNT
- PARSER_SUCCESSES_COUNT
- PARSER_FAIL_COUNT
- PUBSUB_STREAM_RESET_COUNT
- PUBSUB_ACK_SUCCESS_COUNT
- UNABLE_TO_GET_CONNECTION_COUNT
- GOT_CONNECTION_COUNT
- DUPLICATE_TOKEN_URI_COUNT
- DUPLICATE_RAW_IMAGE_URI_COUNT
- DUPLICATE_RAW_ANIMATION_URI_COUNT
- SKIP_URI_COUNT
- PARSE_URI_INVOCATION_COUNT
- PARSE_URI_TYPE_COUNT
- PARSE_JSON_INVOCATION_COUNT
- SUCCESSFULLY_PARSED_JSON_COUNT
- FAILED_TO_PARSE_JSON_COUNT
- OPTIMIZE_IMAGE_INVOCATION_COUNT
- OPTIMIZE_IMAGE_TYPE_COUNT
- SUCCESSFULLY_OPTIMIZED_IMAGE_COUNT
- FAILED_TO_OPTIMIZE_IMAGE_COUNT
=> [NFT Metadata Crawler] Add metrics to parser

aptos-move/aptos-transaction-benchmarks/src/main.rs
The number of accounts was smaller than the block size which causes issue with no conflict txn case (default)
=> Fix number of accounts in transaction benchmark

aptos-node/src/lib.rs
Test seed parsing interface changed with a clap upgrade, and that caused all seed inputs to fail.
Previously:
```
$ ./target/release/aptos-node --test --seed 0101010101010101010101010101010101010101010101010101010101010101 
thread 'main' panicked at 'Mismatch between definition and access of `seed`. Could not downcast to TypeId { t: 16824886518787423740 }, need to downcast to TypeId { t: 4718723824409586242 }
'
$ ./target/debug/aptos-node --test --seed 0101010101010101010101010101010101010101010101010101010101010101 
thread 'main' panicked at 'Mismatch between definition and access of `seed`. Could not downcast to [u8; 32], need to downcast to core::option::Option<[u8; 32]>
'
```
Now:
```
$ ./target/debug/aptos-node --test --seed …
```
=> [node] Fix parsing of test seed

ecosystem/typescript/sdk/src/plugins/coin_client.ts, ecosystem/typescript/sdk/src/tests/e2e/coin_client.test.ts
Updating `CoinClient` `transfer()` and `checkBalance()` to check for a custom `CoinType` first before converting to a `HexString` address.
As of right now, the function assumes it's an address and tries to parse it as such, resulting in a failed conversion to `HexString`:
```typescript
throw new Error('Invalid byte sequence');
```
Added a simple `.includes("::")` check to skip the hex string conversion so it doesn't error if the user sends in a custom cointype.
```typescript
const isTypeTag = (extraArgs?.coinType ?? "").toString().includes("::");
if (extraArgs?.coinType && !isTypeTag && AccountAddress.isValid(extraArgs.coinType)) {
```
Also made the `coinType` arg consistent between the two functions by changing the `checkBalance` type to `string | MaybeHexString` instead of just …
=> [TS-SDK] Fix the coin client transfer/checkBalance functions to allow custom CoinTypes

aptos-move/aptos-release-builder/data/proposals/aip_32_initialization.move, aptos-move/aptos-release-builder/data/release.yaml
enable storage refund feature flags.
requires module events https://github.com/aptos-labs/aptos-core/pull/9811/commits/80afd5dd525a357ebc648150c84202ebaf8bbcc7
framework upgrade test
=> add release step to enable AIP-32

aptos-move/aptos-release-builder/data/release.yaml, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/verifier/resource_groups.rs, aptos-move/e2e-move-tests/src/tests/resource_groups.rs, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
Left out a check that would allow users to accidentally migrate existing resources into resource group members. It likely also let them upgrade memberless structs into resource groups.
The worst case scenario is that data would be lost equivalently to moving data to a burn address.
* using feature flag 30
* added tests for validating consistent behavior before and after
* updated the legacy resource group disabled test to actually validate before behavior...
=> [aptos-vm] prevent existing resources from becoming resource groups

developer-docs-site/docs/indexer/api/example-queries.md, developer-docs-site/docs/indexer/api/index.md, developer-docs-site/docs/indexer/api/labs-hosted.md, developer-docs-site/docs/indexer/api/self-hosted.md, developer-docs-site/docs/indexer/custom-processors/index.md, developer-docs-site/docs/indexer/custom-processors/parsing-txns.md, developer-docs-site/docs/indexer/indexer-landing.md, developer-docs-site/docs/indexer/legacy/custom-data-model.md, developer-docs-site/docs/indexer/legacy/indexer-fullnode.md, developer-docs-site/docs/indexer/txn-stream/labs-hosted.md, developer-docs-site/docs/indexer/txn-stream/local-development.md, developer-docs-site/scripts/additional_dict.txt
There is some weird behavior in docusaurus where relative links don't work when the current URL has a trialing slash. See more information here: https://aptos-org.slack.com/archives/C04PF1X2UKY/p1693348785934909. I fix this by using absolute links instead.
CI.
=> [indexer-docs] Use absolute paths for links

consensus/src/network.rs, consensus/src/quorum_store/batch_requester.rs, consensus/src/quorum_store/tests/types_test.rs, consensus/src/quorum_store/types.rs
Add a new `verify_with_hash` that is used when checking a response to a batch request. The regular `verify` is still used when receiving batches to sign.
Add to unit test.
=> [Quorum Store] check digest match, and log sender if mismatch

Cargo.lock, consensus/Cargo.toml, consensus/src/dag/tests/types_test.rs, consensus/src/dag/types.rs
Implement Debug trait to truncate bytes when debug logging DAG Network message.
unit test
=> [consensus][dag] Truncate bytes when debug logging network message

execution/block-partitioner/src/sharded_block_partitioner/mod.rs, execution/block-partitioner/src/v2/config.rs, execution/block-partitioner/src/v2/mod.rs, execution/executor-benchmark/src/lib.rs, execution/executor-benchmark/src/main.rs, execution/executor-benchmark/src/pipeline.rs
- Remove `--async-partioning` flag as we default to it now and this also reduces unnecessary code duplication.
- Add stats for partitioning at the end of the log
- Reduce number of threads from 8 to 4 - this will help reduce some context switch overhead.
=> Minor improvement to partitioning phase in executor benchmark

Cargo.lock, config/src/config/state_sync_config.rs, state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs, testsuite/smoke-test/Cargo.toml, testsuite/smoke-test/src/state_sync.rs
This PR updates state sync to support fast syncing to genesis. When a node starts up using fast sync and no epoch changes have occurred in the network, the node will fast sync to genesis before continuing. If an epoch change has occurred, fast sync will still choose the latest epoch ending ledger version (as it already does).
This is required to unblock genesis-less fast syncing (i.e., fast syncing a node without writing the genesis transaction to the DB at all).
New and existing tests!
=> [State Sync] Add fast sync support to genesis.

Cargo.lock, consensus/Cargo.toml, consensus/src/dag/tests/types_test.rs, consensus/src/dag/types.rs
This will backport the following commits from `main` to `aptos-release-v1.6`:
- [[consensus][dag] Truncate bytes when debug logging network message (#9872)](https://github.com/aptos-labs/aptos-core/pull/9872)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [aptos-release-v1.6] [consensus][dag] Truncate bytes when debug logging network message (#9872)

ecosystem/python/sdk/aptos_sdk/account_sequence_number.py, ecosystem/python/sdk/aptos_sdk/transaction_worker.py
Odds are this is broken because of the new from_str handling. Not sure how this slipped through though.
The error was coming from the fact that with strict parsing, `b0b` is not a valid address string. I fix it by changing the example address we use to `0xf`.
```
$ make test
poetry run python -m unittest discover -s aptos_sdk/ -p '*.py' -t ..
.....................................
----------------------------------------------------------------------
Ran 37 tests in 0.395s
OK
```
=> Fix Python example tests

docker/rosetta/rosetta.Dockerfile
Fixes broken Rosetta Docker build
```
#11 32.79   Package libudev was not found in the pkg-config search path.
#11 32.79   Perhaps you should add the directory containing `libudev.pc'
#11 32.79   to the PKG_CONFIG_PATH environment variable
#11 32.79   No package 'libudev' found
```
=> [rosetta] Add docker build dependencies

consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_fetcher.rs, consensus/src/dag/tests/dag_driver_tests.rs
This PR splits the DAGFetcher into service and core components. The service is needed for fetching nodes during normal operation and runs in its own task. The core is used for one time fetching of nodes, for example during state sync.
=> [dag] split fetcher into service and helper struct

.github/workflows/semgrep.yaml
This PR forces the container user for the semgrep workflow to be `root`. There is an [open issue with the checkout action](https://github.com/actions/checkout/issues/956) that produces a permission error when containers are run with standard user. See this [broken test](https://github.com/aptos-labs/aptos-core/actions/runs/6055233984).
Test passes: https://github.com/aptos-labs/aptos-core/actions/runs/6055240908/job/16433902557?pr=9902
=> Force semgrep container user to root

ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs, ecosystem/nft-metadata-crawler-parser/src/utils/counters.rs, ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs, ecosystem/nft-metadata-crawler-parser/src/worker.rs
Updated logic so the GCS client would only be queried once so that it wouldn't need to continuously query for credentials from the metadata server (issue with Cloud Run). 
Tested locally, looks good
=> [NFT Metadata Crawler] Update GCS client initialization logic

testsuite/forge-cli/src/main.rs
we calibrated from one weeks of runs, but variance is a bit higher, so we had some sporadic failures. re-calibrating for most issues (some things that happened only once, and few weeks back, I haven't loosened, until they re-appear)
=> calibrate latency numbers on stable test based on longer history of runs

consensus/src/dag/dag_fetcher.rs, consensus/src/dag/order_rule.rs
Fix a bug where the fetched nodes should be reversed before inserting into the DAG.
=> [dag][bugfix] reverse nodes before adding to dag store

.github/workflows/indexer-grpc-integration-tests.yaml
We weren't installing grpcurl or the necessary Python deps.
I temporarily changed it to `pull_request`. Here is the successful run: https://github.com/aptos-labs/aptos-core/actions/runs/6084690892/job/16507158429?pr=9920.
```
Starting 3 tests across 1 binary
PASS [   0.020s] aptos-indexer-grpc-integration-tests tests::fullnode_tests::verify_docker_compose_setup
PASS [  18.904s] aptos-indexer-grpc-integration-tests tests::fullnode_tests::test_cold_start_file_store_worker_progress
PASS [  30.406s] aptos-indexer-grpc-integration-tests tests::fullnode_tests::test_cold_start_cache_worker_progress
------------
Summary [  30.406s] 3 tests run: 3 passed, 0 skipped
```
=> Fix indexer-grpc-integration-tests

.github/actions/buildx-setup/action.yml, .github/actions/docker-setup/action.yaml, .github/workflows/docker-build-rosetta.yaml
So rosetta can build on `pull_request` . It only builds, and does not push to any repo
Rosetta build should run on this PR : https://github.com/aptos-labs/aptos-core/actions/runs/6054089308/job/16430849134?pr=9897
It runs, but failing due to deps that are added in this dependent PR https://github.com/aptos-labs/aptos-core/pull/9895#pullrequestreview-1607676897
=> [gha] set up buildx independently of login, for rosetta build

testsuite/fuzzer/fuzz/fuzz_targets/move/execute_entry_function.rs, testsuite/fuzzer/google-oss-fuzz/project.yaml, testsuite/fuzzer/repro.sh
- adds gas metering to `execute_entry_function` fuzzer
- improves `repro.sh` to support multiple modes (fuzz/build)
- updates `projects.yaml` with correct values
- `./test-fuzzer.sh` passes
=> adds gas metering to execute_entry_function fuzzer

.github/workflows/docker-build-rosetta.yaml
For best practices in CI, so we can build against any revision, even those which predate the recent CI changes
CI running `docker-build-rosetta.yaml`, now that `buildx-setup` has been merged into `main` via https://github.com/aptos-labs/aptos-core/pull/9897. The build currently fails for an unrelated reason, but the buildx-setup step uses the main branch.
=> [docker][rosetta] use buildx-setup at main

execution/block-partitioner/src/tests.rs
The test was failing because it was checking for no same read-hint for txns across shard - which actually doesn't create conflict and current partitioner allow that.
Run the test.
=> Fix no cross shard dep test

config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/latency_monitor.rs, state-sync/aptos-data-client/src/logging.rs
This PR updates the latency monitor to track all advertised versions, even if the versions were only advertised *after* they were synced by the node.
Currently, if a version is advertised after it was synced by the node, it is not tracked for latency purposes, and this results in several missing metrics. Instead, this PR updates the code such that if we've already synced an advertised version, we'll still track the version latencies and the calculated "seen to synced" latency will instead be set to 0.
=> [State Sync] Update latency monitor to track all advertised versions.

aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs, aptos-move/aptos-vm/src/move_vm_ext/mod.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs
Need to expose WriteOpConverter in order to prepare proper write-ops (with the beautiful storage metadata) from block executor. This will be required for proper resource group handling (as they are now combined in block executor and need to be converted to a WriteOp), which in turn is required for AggregatorV2 (among other benefits).
=> [VM] Expose WriteOpConverter

aptos-move/aptos-vm/src/sharded_block_executor/tests.rs
These UT are currently flaky... Temporarily disable them to avoid blocking other PRs, while I'm debugging them.
=> temp disable sharded execution unit tests

.github/workflows/docker-build-test.yaml, execution/executor-types/src/executed_chunk.rs, execution/executor/src/chunk_executor.rs, execution/executor/src/components/chunk_output.rs, execution/executor/src/tests/chunk_executor_tests.rs, execution/executor/src/tests/mod.rs, storage/aptosdb/src/fake_aptosdb.rs, testsuite/forge-cli/src/main.rs
This PR fixes/improves the consensus only benchmark:
- It fixes a bug that prevented running the benchmark due to execution results divergence during state-sync because we now add the StateCheckpoint transaction output with zero gas post-execution in the normal flow that conflicted with state-sync execution flow where in consensus-only mode, the StateCheckpoint transaction output set a non-zero gas.
- Mocks the `get_block_timestamp()` call to return the highest known block timestamp instead of passing through to the underlying aptosdb that made the call to fail and txn-emitter to consequentially fail.
- It also a realistic env forge test with tuned parameters to achieve 50-60k tps with up to 100 replicas. 
Now able to get 50-60k tps consistently. …
=> [consensus-only] execution and fakeaptosdb bugfix and realistic env test

consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/dag/tests/helpers.rs, consensus/src/dag/tests/mod.rs, consensus/src/dag/tests/order_rule_tests.rs
=> [dag] state sync good case unit test

consensus/src/dag/adapter.rs, consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/storage.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/tests/integration_tests.rs, consensus/src/dag/types.rs
This PR enables broadcasting latest ledger info with the CertifiedNode for state syncing. It obtains the ledger info from the storage adapter.
Fixed unit tests.
=> [dag] broadcast CertifiedNodeMsg with LedgerInfo

ecosystem/nft-metadata-crawler-parser/src/lib.rs, ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs, ecosystem/nft-metadata-crawler-parser/src/utils/json_parser.rs
Some of the token and collection URIs have a new line character at the end. This change trims the provided URIs before making the request.
=> [NFT Metadata Crawler] Trim URIs before making request

third_party/move/move-vm/runtime/src/lib.rs, third_party/move/move-vm/runtime/src/tracing.rs, third_party/move/tools/move-cli/src/base/test.rs, third_party/move/tools/move-cli/src/sandbox/commands/test.rs, third_party/move/tools/move-coverage/src/coverage_map.rs
This PR reduces execution time of coverage tool by 1) only printing necessary data items to the trace file; 2) using buffer writer. Close #7295
`time aptos move test --coverage`
After this change, the execution time of 1) aptos-framework is reduced from 3.5mins to 30s; 2) aptos-stdlib is reduced from 3.5mins to 30s and 3) move-stdlib is reduced from 2mins to 13s.
=> [CLI][Coverage] Reduce execution time of coverage tool

third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/bug_9459_notworking.exp, third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/bug_9459_notworking.move, third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/bug_9459_working.exp, third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/bug_9459_working.move, third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/gerbens_test.exp, third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/gerbens_test.move, third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/gerbens_test1.exp, third_party/move/move-bytecode-verifier/transactional-tests/tests/type_safety/gerbens_test1.move, third_party/move/move-compiler/src/diagnostics/codes.rs, third_party/move/move-compiler/src/hlir/translate.rs, third_party/move/move-compiler/src/inlining/translate.rs, third_party/move/move-compiler/src/inlining/visitor.rs, third_party/move/move-compiler/src/typing/translate.rs, third_party/move/testing-infra/transactional-test-runner/src/framework.rs
Fix Issue 6907: A verifier failure related to inline functions
- provide 2 test cases related to Gerben's bug:
- gerbens_test.move: ICE in hlir/translate.rs if lambda is provided to unknown or non-inline
- gerbens_test1.move: byte verifier error when (&mut vector) actual is passed to (&vector) param
- fix both errors:
- generate a useful diagnostic error instead of the ICE
- retain formal parameter types when inlining, but also
- substitute all type parameters appropriately in them
Added test cases to illustrate bug.  Any collateral damage should show up in existing test cases.
https://github.com/aptos-labs/aptos-core/issues/6907
=> Fix Issue 6907: A verifier failure related to inline functions

third_party/move/move-model/src/model.rs
This fills in the `used_modules` field in a module, enabling the `module_env.get_used_modules` and related functionality, to unblock work on the vscode plugin which depends on this.
=> [compiler v2] Populate module use information

ecosystem/typescript/sdk_v2/src/api/account.ts, ecosystem/typescript/sdk_v2/src/api/aptos.ts, ecosystem/typescript/sdk_v2/src/internal/account.ts, ecosystem/typescript/sdk_v2/tests/e2e/api/account.test.ts
EDIT: following PR comments we will roll with this idea.
This is an idea for how the end user would use the new sdk.
Currently, one initializes `Aptos`. i.e `const aptos = new Aptos()`, and then has access to all the sub classes, i.e `account` and for all future sub classes.
```
const aptos = new Aptos();
aptos.account.getInfo("0x1")
```
This PR proposes to delegate all sub classes methods to the Aptos class, so user would not need to use the namespace but simply call any sub class function
```
const aptos = new Aptos();
aptos.getInfo("0x1")
```
This way, sdk users can find the query they are looking for easily without trying to figure out what namespace a function lives in, and sdk maintainers can keep functions in different files and under different namespaces which helps with …
=> Delegate all the methods from sub classes

Cargo.lock, aptos-move/aptos-vm/src/sharded_block_executor/cross_shard_state_view.rs, aptos-move/aptos-vm/src/sharded_block_executor/mod.rs, aptos-move/aptos-vm/src/sharded_block_executor/remote_state_value.rs, aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs, execution/executor-service/Cargo.toml, execution/executor-service/src/lib.rs, execution/executor-service/src/remote_cordinator_client.rs, execution/executor-service/src/remote_executor_client.rs, execution/executor-service/src/remote_executor_service.rs, execution/executor-service/src/remote_state_view.rs, execution/executor-service/src/remote_state_view_service.rs, execution/executor-service/src/test_utils.rs, secure/net/src/network_controller/inbound_handler.rs
Adding support for remote executor and remote storage service. This is still not fully functional as the underlying network context is not reliable and drops messages. When we switch to gRPC, this should work. Adding this change before gRPC support as we would have interfaces ready to be implemented in gRPC. 
Added a test with no cross shard conflict. With cross shard conflict, this doesn't work because of unreliable network context.
=> [Execution][Sharding] Add support for remote execution 

aptos-move/framework/aptos-framework/doc/transaction_fee.md, aptos-move/framework/aptos-framework/sources/transaction_fee.move, types/src/fee_statement.rs
Just realized the fancier version of the doc on FeeStatement was put on top of the Rust struct instead of the Move counterpart.
=> Update doc for FeeStatement on-chain struct

.gitignore, developer-docs-site/docs/indexer/txn-stream/local-development.md, developer-docs-site/scripts/additional_dict.txt, docker/builder/indexer-grpc.Dockerfile, docker/compose/indexer-grpc/data-service-config.yaml, docker/compose/indexer-grpc/docker-compose.yaml, testsuite/indexer_grpc_local.py
* Allow the local development to setup both tls and non-tls endpoints.
* update the redis to version 7(i noticed some segfault on version 6). 
* non-TLS
`grpcurl  -plaintext -d  '{ "starting_version": 0 }' -H "x-aptos-data-authorization:dummy_token" localhost:50052 aptos.indexer.v1.RawData/GetTransactions`
* TLS
`grpcurl  -insecure -d  '{ "starting_version": 0 }' -H "x-aptos-data-authorization:dummy_token" localhost:50053 aptos.indexer.v1.RawData/GetTransactions`
=> [indexer] Local development improvement(docs + code)

aptos-move/framework/src/built_package.rs
See issue #7306 for more details on the problem being fixed.
When using `aptos move compile --output-dir`, the function `inject_runtime_metadata` was erroneously using the default path for the `.mv` file, instead of the path in the specified directory. We now use the specified path if one is provided, or else use the default.
I manually tested that we pick the right directory. It is not clear what sort of automated test makes sense in this scenario.
=> Fixing issue #7306

third_party/move/move-vm/integration-tests/Cargo.toml, third_party/move/move-vm/integration-tests/src/tests/mod.rs, third_party/move/move-vm/integration-tests/src/tests/native_tests.rs, third_party/move/move-vm/runtime/src/interpreter.rs
Fixing #7224 
Ran the test and see following:
```
┌── test_create_and_transfer ──────
│ error[E11001]: test failure
│     ┌─ /config/workspace/aptos-core/aptos-move/framework/aptos-token-objects/../aptos-framework/sources/object.move:207:16
│     │
│ 207 │     native fun exists_at<T: key>(object: address): bool;
│     │                ^^^^^^^^^
│     │                │
│     │                Test was not expected to error, but it aborted with code 10 originating in the module 0000000000000000000000000000000000000000000000000000000000000001::object rooted here
│     │                In this function in 0x1::object
│ 
│ 
│ stack trace
│       token::create_named_token(/config/workspace/aptos-core/aptos-move/framework/aptos-token-objects/sources/token.move:91)
│ …
```
=> [move-vm] Log stacktrace for natives

aptos-move/aptos-vm/src/sharded_block_executor/aggr_overridden_state_view.rs
=> trivial: avoid StateValue::from() in production

ecosystem/typescript/sdk_v2/src/bcs/deserializer.ts, ecosystem/typescript/sdk_v2/src/bcs/serializer.ts, ecosystem/typescript/sdk_v2/tests/unit/deserializer.test.ts, ecosystem/typescript/sdk_v2/tests/unit/serializer.test.ts
This PR is a small QOL add to the base Serializer and Deserializer classes that adds the ability to serialize and deserialize class instances that implement `serialize` and `deserialize` respectively.
Please note the majority of the code here is unit tests/documentation- this code already existed in the sdk in the helper.ts file before in the form of `bcsToBytes` and the general usage of `const myClassName: ClassName = ClassName.deserialize(...)`, but it wasn't clear how to use these functions exactly because they weren't documented or explained.
There is definitely some test overlap here (can probably put it all into a single test case, maybe 2) but I wanted to be thorough.
```typescript
/// serializer.ts
// ...
serialize<T extends Serializable>(value: T) {
// NOTE: The `serialize` …
```
=> [TS SDK v2] Adding the ability to serialize and deserialize classes in the base Serializer/Deserializer classes

network/framework/src/counters.rs, network/framework/src/peer/mod.rs, network/framework/src/protocols/rpc/mod.rs
This PR fixes several bugs in the network metrics:
1. Stop double counting traffic for outbound RPC requests.
2. Fix and improve metric labels related to inbound/outbound RPC requests/responses.
3. Start counting traffic for outbound RPC responses.
4. Add metrics for failed direct send messages.
These were found by looking at the network metrics dashboard and seeing that the inbound state sync traffic for a VFN did not match the outbound state sync traffic for the corresponding validator. I'll confirm that the metrics look more sane on the forge run.
=> [Network] Fix incorrect metrics around network traffic and messages.

consensus/src/dag/adapter.rs, consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_state_sync.rs, consensus/src/dag/order_rule.rs, consensus/src/dag/rb_handler.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/dag/tests/integration_tests.rs, consensus/src/dag/tests/order_rule_tests.rs, consensus/src/dag/tests/rb_handler_tests.rs, consensus/src/dag/types.rs
This PR introduces the rebootstrap logic for the DAG. Essentially, when there is a need to state sync the DAG, we abort the existing handlers, return to the bootstrapper and let the bootstrapper state sync the DAG and recreate all the components and start the handlers again. This is to unify the logic such that we use the same bootstraping logic for recovery as well as state sync.
Existing Tests
=> [dag] dag rebootstrap

.github/workflows/adhoc-forge.yaml
Previously, `adhoc-forge.yaml` workflow tested using a min Forge (and swarm) version based on a user provided `IMAGE_TAG` variable. However, it would also calculate an `UPGRADE_IMAGE_TAG` (for multi-version Forge swarms) based on the current checked-out git ref and its children. Often times, this would mean a scenario where:
* The specified `IMAGE_TAG` is the correct version under test
* When you want to spin up a new node and do something like `swarm().versions().max()`, such as from [public_fullnode_performance](https://github.com/aptos-labs/aptos-core/blob/main/testsuite/testcases/src/public_fullnode_performance.rs#L170), you'd actually get the the other image tag, which would be likely from `main`. 
The scenarios where you'd want to test multi-version Forge is actually not too common. …
=> [gha][forge] require git sha to checkout and test, not dependent on gha environment

consensus/src/epoch_manager.rs, consensus/src/experimental/decoupled_execution_utils.rs, consensus/src/experimental/signing_phase.rs, consensus/src/metrics_safety_rules.rs
This PR introduces a commit signer trait that allows signing post-execution ledger info in the decoupled execution pipeline. MetricsSafetyRules implements this trait so the compatibility remains intact for current consensus implementation.
=> [consensus] introduce CommitSignerProvider trait

Cargo.lock, config/src/config/state_sync_config.rs, state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/error.rs, state-sync/aptos-data-client/src/interface.rs, state-sync/aptos-data-client/src/peer_states.rs, state-sync/aptos-data-client/src/tests/mock.rs, state-sync/aptos-data-client/src/tests/priority.rs, state-sync/aptos-data-client/src/tests/utils.rs, state-sync/state-sync-v2/data-streaming-service/src/data_notification.rs, state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs, state-sync/state-sync-v2/data-streaming-service/src/logging.rs, state-sync/state-sync-v2/data-streaming-service/src/metrics.rs, state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/stream_engine.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/utils.rs, state-sync/storage-service/server/src/handler.rs, state-sync/storage-service/server/src/metrics.rs, state-sync/storage-service/server/src/moderator.rs, state-sync/storage-service/types/Cargo.toml, state-sync/storage-service/types/src/responses.rs, state-sync/storage-service/types/src/tests.rs
This PR adds client-side support for subscription syncing. It builds on the server-side support that has already landed in: https://github.com/aptos-labs/aptos-core/pull/9104.
At a high-level, the PR:
1. Modifies the data streaming service and data client to support "subscription syncing", where subscription requests are sent to peers when no new data is being advertised.
2. All subscription requests for the same stream will be sent to the same peer. A stream will be terminated if: (i) any subscription request fails (e.g., we get a timeout or a bad response); (ii) the peer is no longer able to "satisfy" subscription requests (e.g., the peer is lagging too much); or (iii) the stream hits the maximum number of consecutive subscription requests (forcing a new one to be created). All of these …
=> [State Sync] Add client-side support for subscription syncing.

consensus/src/epoch_manager.rs
This PR refactors the epoch manager and extracts common implementation logic into separate functions, so it can be used when instantiating the DAG. The functionality remains the same, with the only change that it now groups all prometheus metrics update logic in start_round_manager into its own method.
=> [consensus] epoch manager refactoring; dag is coming

consensus/src/dag/commit_signer.rs, consensus/src/dag/mod.rs, consensus/src/epoch_manager.rs
This PR introduces a commit signer struct that implements CommitSignerProvider to sign buffer manager commit proofs for DAG produced blocks.
=> [dag] commit signer

consensus/consensus-types/src/block.rs, consensus/consensus-types/src/block_data.rs, consensus/src/dag/adapter.rs
This PR introduces the ability to cache parent block info in adapter, so they can be included in the block before pushing to execution. Execution requires that the block info refer to a valid parent block info.
=> [dag] store parent block info in adapter

consensus/src/dag/dag_network.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_network_test.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/dag/tests/integration_tests.rs, consensus/src/network.rs
This PR gets rid of the DAGNetworkSenderImpl and instead makes NetworkSender implement the DAGNetworkSender. To support this, DAGNetworkSender's `send_rpc_with_fallbacks` now takes in an Arc<Self> instead of the self receiver.
=> [dag] simplify DAGNetworkSender impl

consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_fetcher.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_network.rs, consensus/src/dag/dag_state_sync.rs, consensus/src/dag/rb_handler.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/dag/tests/fetcher_test.rs, consensus/src/dag/tests/rb_handler_tests.rs
This PR makes RpcHandler trait handler method async so any implementations can call other async methods. This is necessary to support pulling payload in Dag Driver.
=> [dag] async message handler support

aptos-node/src/lib.rs, crates/aptos-genesis/src/builder.rs, testsuite/forge/src/backend/local/mod.rs, testsuite/forge/src/backend/local/swarm.rs, testsuite/smoke-test/src/aptos_cli/validator.rs, testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs, testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs, testsuite/smoke-test/src/indexer.rs, testsuite/smoke-test/src/network.rs, testsuite/smoke-test/src/rest_api.rs, testsuite/smoke-test/src/rosetta.rs, testsuite/smoke-test/src/smoke_test_environment.rs, testsuite/smoke-test/src/state_sync.rs, testsuite/smoke-test/src/test_smoke_tests.rs, testsuite/smoke-test/src/txn_broadcast.rs, testsuite/smoke-test/src/upgrade.rs
Remove stake parameter from `InitConfigFn` and create a separate `InitGenesisStakeFn`. This is a noop, but refactors the two separate parts of logic. Motivation is clarity and to make a future larger change more clear.
Run existing tests. Nothing is expected to change.
=> [refactor] Separate function for changing genesis stake

consensus/src/experimental/ordering_state_computer.rs, consensus/src/persistent_liveness_storage.rs, consensus/src/test_utils/mock_storage.rs
- Adds DagStateSyncComputer that implements StateComputer. Dag State sync will call into state sync using this struct.
- Adds a fn to PersistenceLivenessStorage trait to expose consensusDB. Dag will take in a struct that implements DAGStorage and ConsensusDB implements DAGStorage.
=> [consensus][dag] dag integration helpers

config/src/config/mod.rs, testsuite/forge-cli/src/main.rs, testsuite/testcases/src/data/two_region_link_stats.csv, testsuite/testcases/src/multi_region_network_test.rs
Create netbench tests across a pair of nodes, one colocated and the other emulated on a high-latency (and low bandwidth) network.
For now there is no success criteria, but we should be able to add one based on throughput when needed.
Run the tests in forge.
=> [Forge] Add a netbench test

Cargo.lock, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/framework/Cargo.toml, aptos-move/framework/src/module_metadata.rs, testsuite/single_node_performance.py
3% gain for this comand (32k TPS -> 33k TPS)
```
cargo run -p aptos-executor-benchmark --profile performance -- --block-size 50000  --split-ledger-db  --skip-index-and-usage --use-sharded-state-merkle-db --execution-threads 48 --connected-tx-grps 5000 --shuffle-connected-txns --generate-then-execute run-executor  --data-dir /home/msmouse/work/data/temp/$DB --checkpoint-dir /home/msmouse/work/data/temp/ck --blocks 50 --main-signer-accounts $SIGNERS
```
=> module metadata cache

aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
To defend against an potential vulnerability (read commit for detail).
=> assert no slot allocation after epilogue

aptos-move/e2e-move-tests/src/aggregator.rs, aptos-move/e2e-move-tests/src/aggregator_v2.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/chain_id.rs, aptos-move/e2e-move-tests/src/tests/code_publishing.rs, aptos-move/e2e-move-tests/src/tests/constructor_args.rs, aptos-move/e2e-move-tests/src/tests/fee_payer.rs, aptos-move/e2e-move-tests/src/tests/infinite_loop.rs, aptos-move/e2e-move-tests/src/tests/init_module.rs, aptos-move/e2e-move-tests/src/tests/per_category_gas_limits.rs, aptos-move/e2e-move-tests/src/tests/string_args.rs
We have multiple tests using the same move code in data folders, causing them to be rebuilt over and over. Adding to harness methods that cache building, so it can be reused.
Haven't changed the default methods to do the caching, as caller can decide to modify the files, and then rebuilding is needed - so it is up to the caller to decide if it wants caching or not.
This speeds up e2e-move-tests on my machine from 80s to 50s:
RUST_BACKTRACE=1 RUST_MIN_STACK=104857600 cargo test --profile ci --package e2e-move-tests --lib
Before:
test result: ok. 113 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 79.58s
After:
test result: ok. 113 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 54.51s
=> [e2e-move-tests][harness] Cache module building across tests

aptos-move/aptos-release-builder/src/main.rs, aptos-move/framework/src/natives/code.rs
This PR adds a new subcommand `print-package-metadata` to the aptos-release-builder to print out the package metadata given the package name and the account address.
Usage: aptos-release-builder print-package-metadata --endpoint '\<URL\>' --package-address \<ADDRESS\> --package-name <PACKAGE_NAME> [--print-json]
For instance, when executing the command `aptos-release-builder print-package-metadata --endpoint 'https://mainnet.aptoslabs.com/v1' --package-address 0x1 --package-name AptosFramework`, the output looks like this:
```PackageMetadata:
Package name:AptosFramework
Upgrade policy:compatible
Upgrade number:8
Source digest:DB1749CC57545C1CF4F3099837619D27A1397E7802EF926DE6E1576BC0CC7112
Manifest:
[package]
name = "AptosFramework"
version = "1.0.0"
[addresses]
std = "0x1"
aptos_std = …
```
=> [Aptos-release-builder] Add printing package metadata to the aptos-release-builder

execution/executor-service/src/tests.rs
The test is flaky as the network controller is unreliable. This will be fixed after moving to gRPC, ignoring the test for now.
Existing UT
=> Ignore remote execution test

state-sync/aptos-data-client/src/interface.rs, state-sync/state-sync-v2/data-streaming-service/src/data_notification.rs, state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs, state-sync/state-sync-v2/data-streaming-service/src/metrics.rs, state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/missing_data.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/mod.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/stream_engine.rs, state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_service.rs
Note: (i) this PR is built on https://github.com/aptos-labs/aptos-core/pull/9934; (ii) 90% of this PR is modifications to unit/integration tests.
This PR updates the data streaming service to better tolerate missing data along each stream, by automatically filling data gaps within the stream. 
Today, when requests are sent to peers for data chunks, peers may choose to return fewer data items than requested (e.g., if the data is too large to fit into a single chunk). In this case, the data stream has "missing data" and the items in the stream are no longer contiguous. This is problematic for performance because it causes all data chunks after the missing data to be invalid, and thus the stream is terminated and a new stream has to be created. This can be expensive and wasteful.
To avoid …
=> [Data Streaming Service] Support missing data chunks in streams.

aptos-move/aptos-release-builder/data/release.yaml
Reverts aptos-labs/aptos-core#10137
We've re-evaluated the feature, and agreed that this is now ready to ship.
=> Revert "Remove Bulletproofs feature flag"

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/plugins/aptos_token.ts, ecosystem/typescript/sdk/src/tests/e2e/aptos_token.test.ts
following [AIP-45](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-45.md) adding `burnObject` transaction support
=> [TS SDK] Add `burnObject` transaction support

crates/aptos/CHANGELOG.md, crates/aptos/src/move_tool/mod.rs, crates/aptos/src/move_tool/stored_package.rs, crates/aptos/src/test/mod.rs
This PR adds an option `--print-metadata` to the command `aptos move download` to print out the metadata of the package to be downloaded. Close #10131
`aptos move download  --account 0x1 --package AptosFramework --url https://mainnet.aptoslabs.com/v1 --print-metadata`
=> [CLI] Add print-metadata to the download subcommand

third_party/move/move-model/bytecode/src/function_target_pipeline.rs, third_party/move/move-model/bytecode/src/usage_analysis.rs, third_party/move/move-prover/bytecode-pipeline/src/number_operation_analysis.rs, third_party/move/move-prover/bytecode-pipeline/src/spec_instrumentation.rs
Update dumping functions to ignore inline function environments. Close #9065
=> [move] fix dumping the bytecode for smart contracts containing inline functions (#9065)

third_party/move/move-compiler/src/expansion/translate.rs, third_party/move/move-compiler/tests/move_check/parser/aptos_stdlib_attributes.exp, third_party/move/move-compiler/tests/move_check/parser/aptos_stdlib_attributes2.exp
[PR 9229](https://github.com/aptos-labs/aptos-core/pull/9229) introduced warnings on unknown attributes, but suppressed them for aptos_stdlib to avoid user consternation about problems in the Aptos codebase.  It also removed those attributes from the codebase, so now that it is released it becomes safe to Fix i[ssue 9410](https://github.com/aptos-labs/aptos-core/issues/9410) and remove the special-case for the aptos_stdlib.
Existing test cases, new test outputs.
=> Fix issue 9410 by removing special-case hack to suppress unknown attribute warnings on aptos_stdlib

consensus/src/dag/adapter.rs, consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_state_sync.rs, consensus/src/dag/mod.rs, consensus/src/dag/order_rule.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/dag/tests/integration_tests.rs, consensus/src/dag/tests/order_rule_tests.rs, consensus/src/epoch_manager.rs, consensus/src/execution_pipeline.rs, consensus/src/experimental/ordering_state_computer.rs, consensus/src/network.rs
This PR splits the notifier into OrderedNotifier and ProofNotifier. 
- Cleans up some code to make sure ordered notifier adapter is re-instantiated after each state sync, so that the parent block info is accurate. To do so, it moves the epoch change notification logic from state sync manager to state sync notifier.
- Also, cleans up some StateSyncStatus logic and makes sure that DAG doesn't reinit when an epoch change is required.
- NetworkSender implements ProofNotifier. This makes a clean abstraction and keeps all epoch manager/buffer manager related components (including messages) outside of the DAG.
=> [dag] state sync refactor and notifier reinit

config/src/config/api_config.rs, config/src/config/base_config.rs, config/src/config/config_optimizer.rs, config/src/config/config_sanitizer.rs, config/src/config/consensus_config.rs, config/src/config/execution_config.rs, config/src/config/gas_estimation_config.rs, config/src/config/indexer_config.rs, config/src/config/indexer_grpc_config.rs, config/src/config/inspection_service_config.rs, config/src/config/logger_config.rs, config/src/config/mempool_config.rs, config/src/config/peer_monitoring_config.rs, config/src/config/quorum_store_config.rs, config/src/config/safety_rules_config.rs, config/src/config/state_sync_config.rs, config/src/config/storage_config.rs
This PR:
1. Updates the `ConfigSanitizer` to take in an immutable `NodeConfig` reference. This should help to make it obvious that the sanitizer is responsible only for sanitizing/checking configs and not modifying them. Modifications should happen in the `ConfigOptimizer` step.
2. Migrates any existing `sanitize()` methods to `optimize()` if they need to modify the configs. To avoid breaking anything, I've kept the behaviour the same and added a comment about the requirements for the optimizers to not change values if specified by the node config file. This can be dealt with in a follow-up PR.
=> [Node Configs] Update sanitizer to be read-only and migrate indexer ops.

.github/workflows/forge-pfn.yaml, .github/workflows/forge-state-sync.yaml, developer-docs-site/docs/guides/state-sync.md
This PR:
1. Avoids running the PFN and state sync performance tests on release branch pushes. These runs are not needed.
2. Replaces the continuous syncing mode for fast sync in the dev docs.
=> [GHA] Stop running unnecessary tests on release branch pushes.

Cargo.lock, state-sync/aptos-data-client/Cargo.toml, state-sync/aptos-data-client/src/client.rs, state-sync/aptos-data-client/src/latency_monitor.rs, state-sync/aptos-data-client/src/peer_states.rs, state-sync/aptos-data-client/src/poller.rs
This PR offers two small cleanups and refactors to the Aptos Data Client:
1. Replace `Arc<RwLock<T>>` with `Arc<ArcSwap<T>>` for the global summary cache. This should [reduce](https://docs.rs/arc-swap/latest/arc_swap/) lock contention.
2. Remove the global `RwLock` around `PeerStates` and use `DashMap` and `DashSet` internally, to reduce lock contention.
Nothing else should change 😄 
=> [Aptos Data Client] Small cleanups and refactors.

developer-docs-site/docs/move/book/variables.md, developer-docs-site/docs/move/book/vector.md
Seems the `copy` keyword is not needed for a copyable vector, Tried with aptos-move `2.0.3`. 
Also talked about this with Matt on Discord.
By the way, the original statement makes sense for why explicit copy is needed. Very grateful if reviewers could talk about the reason for this change.
> Copies of large vectors can be expensive, so the compiler requires explicit copy's to make it easier to see where they are happening. 
The following test passed.
```move
module 0xcafe::capy {
#[test_only]
use std::vector;
struct Book has copy, drop {}
#[test]
fun implicty_copy() {
let v0 = vector[Book {}, Book {}, Book {}];
let v1 = v0; // implicit copy. The keyword `copy` is not required.
assert!(vector::length(&v0) == 3, 0);
assert!(vector::length(&v1) == 3, 1);
let _ = vector::pop_back(&mut v1); …
```
=> Remove explicit copy statement for vector

storage/aptosdb/src/lib.rs
fixing these errors in the log
```
2023-09-23T17:49:18.148734Z WARN storage/aptosdb/src/lib.rs:295 Updating rocksdb property failed. {"error":"DB::cf_handle not found for column family name: shard_0_default"}    
```
confirmed with local benchmark run
=> trivial: fix rocksdb property reporter

storage/backup/backup-cli/src/metadata/cache.rs
It's wrong to use the same temp dir for the whole process
=> fix that db-restore can not run concurrently in tests

ecosystem/typescript/sdk_v2/src/api/account.ts, ecosystem/typescript/sdk_v2/src/api/aptos.ts, ecosystem/typescript/sdk_v2/src/api/general.ts, ecosystem/typescript/sdk_v2/src/internal/account.ts, ecosystem/typescript/sdk_v2/src/internal/general.ts, ecosystem/typescript/sdk_v2/src/types/index.ts, ecosystem/typescript/sdk_v2/tests/e2e/api/account.test.ts, ecosystem/typescript/sdk_v2/tests/e2e/api/general.test.ts
Add `General` api class that holds chain general queries.
- getLedgerInfo
- getChainId
- getBlockByVersion
- getBlockByHeight
- getTableItem
- view
note: events is missing, there is an on going discussion on what this API should look like
```
✓ it fetches ledger info (22 ms)
✓ it fetches chain id (2 ms)
✓ it fetches block data by block height (3 ms)
✓ it fetches block data by block version (2 ms)
✓ it fetches view function data (61 ms)
✓ it fetches table item data (6 ms)
```
=> [TS SDK V2] Add `General` api class

ecosystem/typescript/sdk_v2/src/utils/memoize.ts, ecosystem/typescript/sdk_v2/tests/unit/memoize.test.ts
Implementation of a `memoize` and `memoizeAsync` high order functions that later can be used to cache function response.
- `memoize` - a high order function to memoize a pure function response (for example, class methods)
```
authKey(): HexString {
const memoizedAuthKey = memoize(() => {
const pubKey = new Ed25519PublicKey(this.signingKey.publicKey);
const authKey = AuthenticationKey.fromEd25519PublicKey(pubKey);
return authKey.derivedAddress();
}, `authKey`);
return memoizedAuthKey();
}
```
- `memoizeAsync` - a high order function to memoize an async function response (for example, api calls)
```
export async function getModules(args: {
aptosConfig: AptosConfig;
accountAddress: HexInput;
}): Promise<MoveModuleBytecode[]> {
const memoizedGetModules = memoizeAsync(
async (args: { …
```
=> [SDK V2] Implement memoize and memoizeAsync high order functions

Cargo.lock, aptos-move/aptos-vm-types/src/resolver.rs, aptos-move/block-executor/Cargo.toml, aptos-move/block-executor/src/captured_reads.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/lib.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs, aptos-move/block-executor/src/view.rs, aptos-move/mvhashmap/src/unit_tests/proptest_types.rs, aptos-move/mvhashmap/src/versioned_group_data.rs, types/src/write_set.rs
Create a component that exclusively deals with capturing reads from transaction execution, and validating them
- Incorporate new functionality to distinguish between reading a full value, just metadata, or only checking for existence. For now, the callers don't take full benefit of it, but resource groups will (for metadata, and it will have its own existence check for resources in the group too - functionality also implemented in CapturedReads).
- Test the component extensively.
Besides being important for getting the performance improvements for resource groups (o.w. we would get R/W conflicts on metadata), this greatly simplifies validation and code extensibility for the future, also gives us infrastructure to avoid many R/W conflicts in the future.
CapturedReads has comprehensive unit …
=> [Executor] CapturedReads component, Metadata and exists support

developer-docs-site/docs/tutorials/build-e2e-dapp/4-fetch-data-from-chain.md, developer-docs-site/scripts/additional_dict.txt
=> [docs] fix the build

consensus/src/dag/adapter.rs, consensus/src/dag/bootstrap.rs, consensus/src/dag/dag_driver.rs, consensus/src/dag/dag_handler.rs, consensus/src/dag/dag_state_sync.rs, consensus/src/dag/dag_store.rs, consensus/src/dag/tests/dag_driver_tests.rs, consensus/src/dag/tests/dag_state_sync_tests.rs, consensus/src/dag/tests/dag_test.rs, consensus/src/dag/types.rs
This PR changes bootstrapper so that the correct latest ledger info is passed to all the DAG components. If the ledger info in storage ends the epoch, then a genesis ledger info is created and given to the different DAG components. Similarly, for the parent block info for the adapter. 
Also, extracts the highest committed round from dag store and isolates it with Arc<RwLock<>>
=> [dag] support for highest committed round and latest ledger info on bootstrap

ecosystem/typescript/sdk_v2/.npmrc
I kept getting differing lockfiles, because pnpm is configured differently for me than whoever has been submitting commits.  This fixes that issue.
Ran `pnpm install` and my lockfile didn't change format version
=> [ts-sdk-v2] Add .npmrc to ensure pnpm lockfile is consistent

.github/workflows/cli-release.yaml
I was doing a release, and realized that its not very clear to me what that checkbox does. 
This PR added the text to clarify that the checkbox is for "Dry run"
=> [CLI][Easy] Update CLI dry run text

ecosystem/typescript/sdk_v2/src/core/account.ts, ecosystem/typescript/sdk_v2/src/crypto/asymmetric_crypto.ts, ecosystem/typescript/sdk_v2/src/crypto/authentication_key.ts, ecosystem/typescript/sdk_v2/src/crypto/ed25519.ts, ecosystem/typescript/sdk_v2/src/crypto/multi_ed25519.ts, ecosystem/typescript/sdk_v2/src/utils/hd-key.ts, ecosystem/typescript/sdk_v2/tests/unit/account.test.ts, ecosystem/typescript/sdk_v2/tests/unit/authentication_key.test.ts, ecosystem/typescript/sdk_v2/tests/unit/helper.ts
Note: This is the `3rd` stack of the whole work. Previous stack here -> #10186
This PR adds the Account and AuthenticationKey classes. Most of the thing stays the same as v1, but with some modification.
1. Account now holds the actual `PublicKey` and `PrivateKey` objects
2. `Verify` and `Sign` relies on the method the corresponding key
3. Using object as param
Run all tests and make sure they all passes
=> [TSSDKv2][3/n] Account and AuthenticationKey Classes

aptos-move/framework/aptos-stdlib/doc/math128.md, aptos-move/framework/aptos-stdlib/doc/math64.md, aptos-move/framework/aptos-stdlib/sources/math128.move, aptos-move/framework/aptos-stdlib/sources/math64.move, aptos-move/move-examples/marketplace/sources/coin_listing.move, aptos-move/move-examples/marketplace/sources/collection_offer.move, aptos-move/move-examples/marketplace/sources/fee_schedule.move, aptos-move/move-examples/marketplace/sources/listing.move, aptos-move/move-examples/marketplace/sources/test_utils.move
Adds an error message for a divide by zero error in the aptos stdlib and handles divide by 0 in royalties in the example marketplace contract.
Additionally, adds checks for royalty 100% or 0 denominator in the marketplace, and ensures that listings go through rather than get stuck with insufficient balance errors.
Choices in the marketplace were:
1. Take royalty and commission from full amount, then make one taken before the other (I chose this, where commission is taken second)
2. Take the commission first, then take the royalty percentage from the remaining amount
3. Take the royalty first then take the commission percentage / amount from the remaining amount
See unit tests
=> [marketplace / framework] Fix divide by zero and marketplace royalty edge conditions

testsuite/forge-cli/src/main.rs
This is in an effort to reduce noise in the PFN tests. Epoch changes are an obvious source of noise, although it's unclear how much it contributes to noise difference between runs.
To still have coverage of epoch changes, the tests without chaos will still do 5 minute epoch changes.
Run ad-hoc forge run, observe no epoch changes.
=> [Forge][PFN] remove epoch changes from some tests

testsuite/exp
Make `exp` script work for any upstream repo, by specifying the `--repo` argument. This means you can kick off `exp` on a repo other than `aptos-labs/aptos-core`, such as a private personal fork.
Previously, we made `exp` work for personal forks of `aptos-core`, where your code changes from your forked PR are then shipped to `aptos-labs/aptos-core`, and the workflow runs from there.
Existing unit tests && Run it on my fork
=> [exp] make it work for any upstream repo

aptos-move/aptos-release-builder/src/validate.rs
Increase the lockup before executing proposals
Currently the release flow started consistently failing because we need to increase the lockup
This ensures that the lockup is sufficient before executing transactions
Test Plan: not sure how to test other than by running against testnet???
Please advise
=> [release-builder] Increase lockup before executing proposals

Cargo.lock, crates/aptos-inspection-service/src/server/peer_information.rs, network/framework/Cargo.toml, network/framework/src/application/storage.rs, network/framework/src/application/tests.rs, network/framework/src/connectivity_manager/mod.rs, network/framework/src/connectivity_manager/test.rs, network/framework/src/noise/handshake.rs, network/framework/src/noise/mod.rs, network/framework/src/peer_manager/mod.rs, network/framework/src/transport/test.rs
Note: this PR is built on: https://github.com/aptos-labs/aptos-core/pull/10217
This PR offers two modifications to the peers and metadata struct (to help reduce read lock contention). Each modification is offered in its own commit:
1. Replace `Arc<RwLock<PeerSet>>>` with `Arc<ArcSwap<PeerSet>>>` in the `trusted_peers` set. Given that the trusted peers will be read frequently, but changed infrequently (e.g., during epoch changes), it makes sense to optimize these for reads.
2. To reduce lock contention on `peers_and_metadata`, we add a cached copy of the data to service all reads. The cached copy is updated every time `peers_and_metadata` is updated (which happens semi-frequently). The benefit of this approach is that reads do not need to wait for any locks. This is crucial because we …
=> [Network] Reduce lock contention in the peers and metadata struct.

.github/workflows/replay-verify.yaml, .github/workflows/workflow-run-replay-verify.yaml
1. not reference workflows by @main
2.  not cancel other sub-jobs on first failure
manually scheduled https://github.com/aptos-labs/aptos-core/actions/runs/6341570151?pr=10281
-- sub-job failure didn't cancel other sub-jobs.
=> replay-verify workflow tunings

third_party/move/move-model/src/builder/module_builder.rs, third_party/move/move-prover/tests/sources/functional/duplicate_function_declarations.exp, third_party/move/move-prover/tests/sources/functional/duplicate_function_declarations.move
Fix failing internal assert in move-model #9064. The assert is triggered because of duplicate declarations of a function name during definition analysis. This is fixed by raising an error explaining the duplicate declaration instead of an assertion violation. Close #9064 
`move-prover/tests/sources/functional/duplicate_function_declarations.move`
=> [move-model] fix internal assertion violation in definition analysis

Cargo.lock, aptos-move/aptos-debugger/src/lib.rs, aptos-move/aptos-native-interface/Cargo.toml, aptos-move/aptos-native-interface/src/builder.rs, aptos-move/aptos-vm-profiling/src/bins/run_move.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/aptos-vm/src/move_vm_ext/warm_vm_cache.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/e2e-tests/src/executor.rs, aptos-move/framework/tests/move_unit_test.rs, aptos-move/move-examples/tests/move_unit_tests.rs, aptos-move/vm-genesis/src/lib.rs, aptos-move/writeset-transaction-generator/src/writeset_builder.rs, crates/aptos/src/move_tool/aptos_debug_natives.rs, storage/backup/backup-cli/src/backup_types/state_snapshot/restore.rs, types/Cargo.toml, types/src/on_chain_config/mod.rs, types/src/on_chain_config/timed_features.rs
to fix #10147 
Natives are stateful so must be covered by the WarmVmId.
1. add TimedFeaturesBuilder and convert TimedFeatures to an array of booleans.
2. add SafeNativeBulder::id_bytes() to fix the bug
3. rebuild vm (and hence all the natives) only when the builder id_bytes() change.
replay-verify
https://github.com/aptos-labs/aptos-core/actions/runs/6357753314
also ran single machine benchmark, didn't see it getting too much slower (loading PackageRegistry from storage still dominates the time consumption)
=> fix WarmVmCache

ecosystem/typescript/sdk_v2/src/bcs/deserializer.ts, ecosystem/typescript/sdk_v2/src/bcs/serializer.ts, ecosystem/typescript/sdk_v2/src/core/account_address.ts, ecosystem/typescript/sdk_v2/src/crypto/asymmetric_crypto.ts, ecosystem/typescript/sdk_v2/src/crypto/ed25519.ts, ecosystem/typescript/sdk_v2/src/crypto/multi_ed25519.ts, ecosystem/typescript/sdk_v2/tests/unit/account_address.test.ts, ecosystem/typescript/sdk_v2/tests/unit/deserializer.test.ts, ecosystem/typescript/sdk_v2/tests/unit/multi_ed25519.test.ts, ecosystem/typescript/sdk_v2/tests/unit/serializer.test.ts
1. I've removed the export from `Deserializable` in order to facilitate using static `deserialize` methods with Deserializable values.
Typescript doesn't let us use `abstract static` methods, nor does it let us use `static` methods with interfaces, so this is the only solution I could come up with that's simple enough. Note that `Deserializable` is really only meant to facilitate the `Deserializer` instance method `deserialize()`, so it's fine if it's purely used as an interface to describe an object as opposed to being explicitly extended.
2. I also changed `Serializable` to a class instead of an interface and added the `bcsToBytes()` function to it, that way whenever a class `extends Serializable` you can just call `classInstance.bcsToBytes()` on the instance to serialize it and get the …
=> [TS-SDK v2] Updating the `Deserializable` interface and making `Serializable` an abstract class

ecosystem/typescript/sdk_v2/src/bcs/deserializer.ts, ecosystem/typescript/sdk_v2/src/bcs/serializer.ts, ecosystem/typescript/sdk_v2/tests/unit/deserializer.test.ts, ecosystem/typescript/sdk_v2/tests/unit/serializer.test.ts
Fairly self-explanatory- adding the ability to serialize and deserialize `Serializable` and `Deserializable` values respectively, using `Serializer` and `Deserializer`.
Each new function has a corresponding unit test.
`pnpm jest serializer.test.ts --verbose`
should run both tests
=> [TS-SDK v2] Adding `serializeVector` and `deserializeVector` to SDK v2

aptos-move/aptos-aggregator/src/aggregator_change_set.rs, aptos-move/aptos-aggregator/src/aggregator_extension.rs, aptos-move/aptos-aggregator/src/bounded_math.rs, aptos-move/aptos-aggregator/src/types.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/src/captured_reads.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/view.rs, aptos-move/framework/src/natives/aggregator_natives/aggregator.rs, aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs, aptos-move/framework/src/natives/aggregator_natives/context.rs, aptos-move/mvhashmap/src/versioned_aggregators.rs
with these sequential execution works (excluding exchange/materialization)
- some changes in CapturedReads (not all, there are followup)
- introducing ReadPosition (BeforeCurrentTxn, AfterCurrentTxn) for calls that we need to distinguish whether we want including with current transaction or not), so it’s harder to have bugs
- validation/try commit logic in coordinator_commit_hook
- sequential execution update to state (no exchanges yet)
=> [aggregator_v2] Fixes found through testing

Cargo.lock, aptos-move/block-executor/src/counters.rs, aptos-move/block-executor/src/scheduler.rs, storage/schemadb/Cargo.toml, storage/schemadb/src/lib.rs, storage/schemadb/src/metrics.rs, testsuite/single_node_performance.py
From the CPU flamegraph, we could observe that these counters are consuming 5-6% of the CPU. Removing few of them and changing some to sampled counter instead. 
Ran the executor benchmark and observed around 4% TPS gain.
=> Remove expensive counters

Cargo.lock, Cargo.toml, crates/aptos/Cargo.toml, crates/aptos/e2e/cases/account.py, crates/aptos/e2e/local_testnet.py, crates/aptos/e2e/main.py, crates/aptos/src/node/local_testnet/faucet.rs, crates/aptos/src/node/local_testnet/health_checker.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/node.rs, crates/aptos/src/node/local_testnet/ready_server.rs, crates/aptos/src/node/local_testnet/traits.rs, crates/aptos/src/node/local_testnet/utils.rs
- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10214
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/10271
When the local testnet was just a node and a faucet, it was somewhat acceptable to just have everything jammed into one file. With testnets becoming more fully featured, this would've become a big mess.
In this PR I introduce the ServiceManager trait. Using this trait, I separate each service into its own file, in which have:
- Configuration necessary for that service.
- Pre-run and post-healthy steps.
- Code for running the service itself.
- Logic for structuring service startup order, leveraging HealthCheckers.
Build a tools image locally:
```
DOCKER_DEFAULT_PLATFORM=linux/amd64 docker/builder/docker-bake-rust-all.sh tools
```
I used the remote …
=> [CLI] Restructure local testnet code

Cargo.lock, aptos-move/aptos-release-builder/Cargo.toml, aptos-move/aptos-release-builder/src/validate.rs
The previous PR was converting the private key arg to string incorrectly...
ED25519 key type has a very silly to_string that returns debug output
I suppose this is to prevent dumping the key, but really i think it should just
not have a to_string and instead only have a debug method that does the same
thing, and a very explicit to hex method so that you dont accidentally dump these.
Test Plan: framework upgrade test succeeds, or at least doesnt fail on this
error (there is still some underlying flakiness in the forge test itself)
=> [release-builder] Fix increase lockup

aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/aptos_governance.move, aptos-move/framework/aptos-framework/sources/vesting.move, aptos-move/framework/aptos-token/sources/token.move, aptos-move/framework/aptos-token/sources/token_transfers.move, aptos-move/framework/tests/move_unit_test.rs
This turns on running extended checks also on test-only code in the framework unit tests. A few errors discovered this way are fixed.
Changes to function declarations in this PR do not effect compatibility because only test-only functions are effected which are stripped before deployment.
Related to #10335, but more needs to be done to make this behavior the default. This cannot happen before the next framework release.
=> [framework] Turn on test-only checking and fix errors

.github/workflows/cli-external-deps.yaml, crates/aptos/scripts/check_dynamic_deps.sh
We recently broke the OpenSSL dep and went through great pains to avoid the libpq dep. This CI stops us from inadvertently reintroducing those deps.
`cargo deny` would be good but we’re blocked on features lacking in that crate: https://github.com/EmbarkStudios/cargo-deny/issues/563. So we could just use cargo tree -i <crate> instead. Or build the CLI and use otool (but that is more expensive).
I just use the system cargo here because our rust-setup action only works on Debian systems.
https://github.com/aptos-labs/aptos-core/actions/runs/6379345050/job/17311640488?pr=10338
=> Add CI to check for banned CLI dynamic deps

testsuite/forge/src/runner.rs
Fixing a mistake made in a previous PR, that made fullnode configs not apply (and overwrite validator configs)
Ran a fullnode test and manually check the config that is logged.
=> [forge] Fix fullnode override in forge

ecosystem/indexer-grpc/indexer-grpc-data-service/src/metrics.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
* update the metrics to be on `token`, `user email` and `processor name`
* update the short connection metrics to be based on user; this is to figure out the short connection issue.
* pre-commit passed
=> [indexer grpc] update the metrics to better understand the usage.

ecosystem/python/sdk/aptos_sdk/account.py, ecosystem/python/sdk/aptos_sdk/aptos_token_client.py, ecosystem/python/sdk/examples/rotate_key.py
@xbtmatt pointed out that the token client fails to parse the account addresses in resources sometimes: https://aptos-org.slack.com/archives/C05UCAA0YKW/p1696372884560539. The reason is the node API returns addresses in a non-AIP-40-compliant manner, namely that it shortens addresses unconditionally (the standard states it should only do this for special addresses). As such, any time we parse an account address from the node API we should use `from_str_relaxed`.
I checked all other uses of AccountAddress.from_str in the SDK to make sure they're valid too.
I ran the examples like 20 times and they always passed:
```
export APTOS_NODE_URL='http://127.0.0.1:8080/v1'
export APTOS_FAUCET_URL='http://127.0.0.1:8081'
make examples
```
=> [Python SDK] Use AccountAddress.from_str_relaxed when parsing addresses from the node API

Cargo.lock, testsuite/forge-cli/src/main.rs, testsuite/testcases/Cargo.toml, testsuite/testcases/src/load_vs_perf_benchmark.rs
We have a sweep of tests, with some being in 1 phase and some in 2. Previously, each test would get ~5 minutes, giving it 2.5 minutes per phase.
With this, we make all phases equal, i.e. ~4 minutes, so we get similarly stable results for each phase, as we get for full runs, without needing to extend runtime.
(this is for workload sweep test)
=> [forge] Split duration more usefully, for more reliable stats

config/src/config/quorum_store_config.rs
The previous `backlog_txn_limit_count` was too conservative. Especially when running through PFNs, which cause duplicate txns and these are included in the backlog count. We should optimize for this case, since most txns should go through PFNs in prod.
Higher values of `backlog_txn_limit_count` actually show some VFNs lagging behind in non-PFN tests (due to VNs going full throttle). We will need to think more on what to do in this case.
Ran ad-hoc test with PFNs, see an increase in TPS (latest run 7K).
=> [Quorum Store] 33% increase in backlog_txn_limit_count

aptos-move/block-executor/src/captured_reads.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/view.rs
Replacing aggregator v2 identifiers with values before transaction commitment. Finishing some of the TODOs and PR comments on the previous PR.
=> Replacing aggregator v2 identifiers with values before transaction commitment

ecosystem/typescript/sdk/src/transactions/async_queue.ts, ecosystem/typescript/sdk/src/transactions/tests/async_queue.test.ts
The AsyncQueue is utilized by the TransactionWorker and exhibited a bug when initiated with an empty transactions queue. To address this issue, I could just increase the counter *after* setting the resolveMap. Additionally, the cancellation behavior was enhanced to throw an AsyncQueueCancelledError instead of resolving to it. Furthermore, an unusual behavior was identified where the cancellation status persisted indefinitely. In addition to these fixes, several opinionated changes have been made to enhance the overall functionality and maintainability of the code.
These implemented tests not only validate the existing functionality but also ensure that recent fixes and enhancements are working as expected.
- **Enqueue and Dequeue**: Verify that items can be enqueued and dequeued as …
=> [ts-sdk] fix async queue promise dequeue and cancellation

developer-docs-site/docs/indexer/api/self-hosted.md
To make it nice and easy for people to see the image and what tags are available.
Docs.
=> [Docs] Add link to processor image on DockerHub

Cargo.lock, aptos-move/aptos-vm-benchmarks/src/helper.rs, aptos-move/e2e-move-tests/Cargo.toml, aptos-move/e2e-move-tests/src/aptos_governance.rs, aptos-move/e2e-move-tests/src/harness.rs, aptos-move/e2e-move-tests/src/tests/access_path_test.rs, aptos-move/e2e-move-tests/src/tests/fee_payer.rs, aptos-move/e2e-move-tests/src/tests/rotate_auth_key.rs, aptos-move/e2e-move-tests/src/tests/token_objects.rs, crates/aptos/src/account/key_rotation.rs, crates/aptos/src/common/types.rs, crates/aptos/src/move_tool/mod.rs, testsuite/smoke-test/src/aptos_cli/move.rs, types/src/account_config/resources/challenge.rs, types/src/account_config/resources/mod.rs, types/src/lib.rs, types/src/move_utils/mod.rs
e2e-move-tests were depending on aptos crate, just to use two utility structs. With that it basically required everything to be built. 
moving these to aptos-types (let me know if you have a better preference), reduces number of dependencies from ~1400 to ~1000, and significantly reducing build time. 
Also when modifying some code, and re-running, much less things need to be build, and the very-time-consuming "aptos" crate is not built any more
=> [e2e-move-tests] remove aptos crate (cli tool) dependency

config/src/config/state_sync_config.rs
This PR enables subscription syncing by default (in the state sync configs).
=> [State Sync] Enable subscription syncing by default.

storage/aptosdb/src/db_debugger/truncate/mod.rs, storage/aptosdb/src/state_store/mod.rs, storage/aptosdb/src/utils/truncation_helper.rs
When usages can be skipped, we can only truncate to the version that has usage persisted to db.
=> Update truncation tool.

crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/traits.rs
- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10333
- Next in stack: N/A
Tokio already has a way to spawn a bunch of tasks and manager them together, the JoinSet. This PR makes us use that instead of a vec of JoinHandles. I also make us use task IDs, which simplify figuring out which task ended.
```
cargo run -p aptos -- node run-local-testnet --assume-yes --force-restart --with-indexer-api
```
I tested that ctrl-C and friends work as expected.
=> [CLI] Use JoinSet rather than a vec of JoinHandles

Cargo.lock, Cargo.toml, crates/aptos/Cargo.toml, crates/aptos/src/node/local_testnet/indexer_api.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/postgres.rs, crates/aptos/src/node/local_testnet/traits.rs, crates/aptos/src/node/local_testnet/utils.rs
- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10311
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/10396
As it was, the local testnet code would interact with docker via the CLI. With this PR, we now interact with the Docker API.
The main advantage of this is it allows us to talk to a Docker daemon in an environment without the Docker CLI, for example from within the tools image. It's also a more structured way to interact and requires less command boilerplate.
First, follow this guide to set up the remote builder: https://www.notion.so/aptoslabs/How-to-use-the-Remote-Ad-Hoc-Docker-Builder-637d650a380841deae68f72a35eb39b5.
Build the tools image:
```
./docker/builder/docker-bake-rust-all.sh tools
```
Run a local testnet from the tools image:
``` …
```
=> [CLI] Use the Docker API rather than the CLI for the local testnet

Cargo.lock, Cargo.toml, crates/aptos/Cargo.toml, crates/aptos/src/main.rs, crates/aptos/src/node/local_testnet/indexer_api.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/postgres.rs, crates/aptos/src/node/local_testnet/traits.rs, crates/aptos/src/node/local_testnet/utils.rs
- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10255/
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/10333
Some tokio tasks don't like to go away, e.g. if they're blocking on some synchronous code and spawn_blocking wasn't used. This is pretty common with the local testnet. Since it now intercepts ctrl+C, this phenomenon is now visible, so we need to set a timeout on the runtime.
See https://github.com/aptos-labs/aptos-core/pull/10311. All the testing on that PR was actually using this one.
=> [CLI] Set runtime timeout

.dockerignore, Cargo.lock, Cargo.toml, crates/aptos/Cargo.toml, crates/aptos/src/common/types.rs, crates/aptos/src/common/utils.rs, crates/aptos/src/main.rs, crates/aptos/src/node/local_testnet/hasura_metadata.json, crates/aptos/src/node/local_testnet/health_checker.rs, crates/aptos/src/node/local_testnet/indexer_api.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/node.rs, crates/aptos/src/node/local_testnet/postgres.rs, crates/aptos/src/node/local_testnet/processors.rs, crates/aptos/src/node/local_testnet/traits.rs, crates/aptos/src/node/local_testnet/utils.rs, crates/aptos/src/node/mod.rs
- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10271
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/10310
This PR adds support for running indexer processors to the local testnet. The processors you run is configurable with `--processors`, which uses the new `ProcessorName` enum.
Note: I will update the dependency from that branch to a specific rev later.
```
cargo run -p aptos -- node run-local-testnet --assume-yes --force-restart --with-indexer-api
```
```
Readiness endpoint: http://0.0.0.0:8070/
Postgres is starting, please wait...
Transaction stream is starting, please wait...
Node API is starting, please wait...
Faucet is starting, please wait...
Log file: "/Users/dport/.aptos/testnet/validator.log"
Test dir: …
```
=> [CLI] Add support for running standard indexer processors to the local testnet

docker/builder/debian-base.Dockerfile, docker/builder/docker-bake-rust-all.hcl, scripts/update_docker_images.py
Currently, our docker builders can only build linux/amd64 images because we hardcode base-image SHA hashes to linux/amd64 ones. But, what we really should be using are the multi-platform image hashes from the `docker buildx imagetools inspect` tool. This PR updates those hashes.
This will allow us to build images for both macos/arm and linux/amd.
Wait for CI
=> [docker] Set image hash to multiplatform ones

aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/aptos-vm/src/aptos_vm_impl.rs, aptos-move/aptos-vm/src/system_module_names.rs, aptos-move/e2e-move-tests/src/tests/fee_payer.rs, aptos-move/framework/aptos-framework/doc/account.md, aptos-move/framework/aptos-framework/doc/transaction_validation.md, aptos-move/framework/aptos-framework/sources/account.move, aptos-move/framework/aptos-framework/sources/account.spec.move, aptos-move/framework/aptos-framework/sources/transaction_validation.move, aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
This is the implementation of AIP-52:
https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-52.md
This AIP proposes to allow sponsored transactions, one in which the gas payer is not the primary signer of the transaction, to create accounts for the primary signer if it does not exist. Currently when submitting a sponsored transaction an account must first exist. This is an unnecessary friction for using gas fee payer accounts for new accounts. As it means that the gas fee payer solution must first submit an independent transaction to the blockchain.
I also cleaned up the tests for fee payer since there were a lot, and they were excessively complex.
=> [aptos-vm] enable automatic creation of sponsored accounts

api/src/tests/transactions_test.rs, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/aptos-vm/src/adapter_common.rs, aptos-move/aptos-vm/src/aptos_vm.rs, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs, types/src/transaction/authenticator.rs, types/src/transaction/mod.rs
sometimes the client would like to send a transaction to a fee paying network without knowing who will actually pay for it... this PR makes the fee payer address optional by allowing signatures on Address::ZERO
AIP forthcoming will update...
I've built this on the updated sponsored transction PR, will rebase and land as appropriate assuming sufficient approvals land.
=> [fee-payer] make fee payer address optionally set during signing

storage/aptosdb/src/state_store/buffered_state.rs, testsuite/single_node_performance.py
JMT computation and commit are parallelizable now. It's time to increase the threshold.
=> [Storage] Increase the threshold of versions between two JMT snapshots.

Cargo.lock, Cargo.toml, storage/storage-interface/Cargo.toml, storage/storage-interface/src/async_proof_fetcher.rs
Looking at the flamegraph from recent executor benchmark, we see that around 5-7% of the CPU is being spent in Rayon's task stealing. The issue is that we spawn too many task (one task per key - ~100k task for a block of size 25k) and these tasks are very small, spawning too many small tasks on rayon thread pool has a huge overhead that more the thread pool is spending most of the CPU cycles in rayon's task stealing. Changing this from Rayon to threadpool (which doesn't have any task stealing) gets rid of the rayon overhead and gives us around 3-4% TPS boost. 
Ran the executor benchmark and observed 3-4% TPS improvements.
=> [Storage] Don't use Rayon for Async Proof fetcher

docker/builder/tools.Dockerfile
Fixes this issue:
```
176.7 The following packages have unmet dependencies:
177.0  libncursesw6 : Depends: libtinfo6 (= 6.2+20201114-2+deb11u2) but 6.2+20201114-2+deb11u1 is to be installed
177.1 E: Unable to correct problems, you have held broken packages.
```
```
./docker/builder/docker-bake-rust-all.sh tools
```
=> Fix build for tools image by upgrading libtinfo6 version

.dockerignore, Cargo.lock, Cargo.toml, crates/aptos/Cargo.toml, crates/aptos/src/common/types.rs, crates/aptos/src/common/utils.rs, crates/aptos/src/main.rs, crates/aptos/src/node/local_testnet/faucet.rs, crates/aptos/src/node/local_testnet/hasura_metadata.json, crates/aptos/src/node/local_testnet/health_checker.rs, crates/aptos/src/node/local_testnet/indexer_api.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/node.rs, crates/aptos/src/node/local_testnet/postgres.rs, crates/aptos/src/node/local_testnet/processors.rs, crates/aptos/src/node/local_testnet/ready_server.rs, crates/aptos/src/node/local_testnet/traits.rs, crates/aptos/src/node/local_testnet/utils.rs, crates/aptos/src/node/mod.rs, crates/indexer/Cargo.toml, ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs, ecosystem/nft-metadata-crawler-parser/Cargo.toml, testsuite/smoke-test/Cargo.toml
- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10252
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/10254
This PR adds support for:
- Spinning up postgres in a container.
- Using postgres already running in the host system.
This is required to run indexer processors.
I still need to double check that this works on a fresh system, I have a suspicion that if postgres isn't installed things will fail with some error to the effect of "postgres shared library missing".
I also need to make sure I'm not reintroducing the OpenSSL dep.
This depends on https://github.com/aptos-labs/aptos-indexer-processors/pull/146.
Note: To avoid using undesired diesel features in the CLI I had to move the feature declarations from the workspace level to the crate level. Crate …
=> [CLI] Add support for running postgres in a container to the local testnet + rest of PRs in stack

third_party/move/move-compiler/src/expansion/translate.rs, third_party/move/move-compiler/tests/move_check/deprecated/public_script.exp, third_party/move/move-compiler/tests/move_check/deprecated/public_script.move
This PR removes an assertion in visibility translation. This assertion will cause the compiler to panic when the target move code contains `public (script)` functions and there are other errors at or above `NonblockingError` level. It is not necessary because the compiler will output these errors after compilation.
=> [Compiler] remove an unnecessary assertion in visibility translation

.github/actions/run-local-testnet/action.yaml, .github/actions/run-ts-sdk-e2e-tests/action.yaml, .github/workflows/ts-sdk-e2e-tests.yaml, ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts, ecosystem/typescript/sdk/src/tests/e2e/provider.test.ts, ecosystem/typescript/sdk/src/utils/api-endpoints.ts
Now that we have a local testnet that can run the indexer API, we should run our indexer tests against it. This makes the tests more reliable because we're no longer relying on a production network which is sometimes down due to upgrades / unreliable internet. We also don't need to deal with auth keys at all now to bypass ratelimiting.
Demonstrating that it works locally:
```
pnpm test:indexer
Indexer
✓ should throw an error when account address is not valid (23 ms)
✓ should not throw an error when account address is missing 0x
get data
✓ gets indexer ledger info (1009 ms)
✓ gets account owned objects data (1026 ms)
✓ gets token activities (1050 ms)
✓ gets token activities count (1036 ms)
✓ gets account token count (1013 ms)
✓ gets token data (1025 ms)
✓ gets token owners data (1044 ms)
✓ …
```
=> Use local testnet indexer for TS SDK tests

Cargo.lock, Cargo.toml, storage/schemadb/Cargo.toml, storage/schemadb/src/lib.rs
i.e. `//?C:\...` doesn't work
`cargo run -p aptos -- node run-local-testnet --force-restart --assume-yes` on Windows 11
=> get around that RocksDB does not take Windows UNC style paths

ecosystem/typescript/sdk/CHANGELOG.md, ecosystem/typescript/sdk/src/aptos_types/type_tag.ts, ecosystem/typescript/sdk/src/tests/unit/type_tag.test.ts
Turns out this test was being skipped, and this properly fixes the bug, which was caught while cleaning up the V2 SDK
CI and `pnpm test`
=> [ts-sdk] Fix nested type tag in object parsing

crates/aptos/CHANGELOG.md, crates/aptos/src/node/local_testnet/indexer_api.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/postgres.rs, crates/aptos/src/node/local_testnet/processors.rs, crates/aptos/src/node/local_testnet/utils.rs
The previous code was not correctly persisting postgres data between restarts without `--force-restart` when using `--with-indexer-api`. We fix this by storing the data through a bindmount in the host system, so the container lifetime doesn't matter. This simplifies `--force-restart` too, the DB state gets wiped the same as all the other state. This way we can treat the postgres container as no more special than the Hasura container, which we kill mercilessly since it is has no persistent state.
Run a fresh local testnet:
```
cargo run -p aptos -- node run-local-testnet --with-indexer-api --force-restart --assume-yes
```
Wait for it to start up happily. Run the local testnet again without wiping anything:
```
cargo run -p aptos -- node run-local-testnet --with-indexer-api
```
Wait for it …
=> [CLI] Correctly persist postgres data between restarts

aptos-move/aptos-vm-types/src/output.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/block-executor/src/executor.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/view.rs, aptos-move/mvhashmap/src/unit_tests/mod.rs, aptos-move/mvhashmap/src/unsync_map.rs
In sequential execution, replace aggregator identifiers with values in resource write set, read set and events before committing the transaction.
=> Replace aggregator identifiers with values in sequential execution

.github/workflows/docker-build-test.yaml, docker/builder/docker-bake-rust-all.sh, docker/release-images.mjs
Revert the revert, and also remove the dependencies that made it fail
lint and also dispatch shows it runs ok https://github.com/aptos-labs/aptos-core/actions/runs/6412278550
=> [gha/docker] remove deprecated indexer build

state-sync/state-sync-driver/src/driver_factory.rs, state-sync/state-sync-driver/src/metrics.rs, state-sync/state-sync-driver/src/storage_synchronizer.rs, state-sync/state-sync-driver/src/tests/mocks.rs, state-sync/state-sync-driver/src/tests/storage_synchronizer.rs
This PR updates the storage synchronizer in state sync to migrate from a 2-step synchronization pipeline (i.e., `apply/execute -> commit`), to the 3-step pipeline (i.e., `apply/execute -> ledger_update -> commit`).
=> [State Sync] Migrate to the new storage synchronizer pipeline.

.github/workflows/replay-verify.yaml, .github/workflows/workflow-run-replay-verify.yaml, Cargo.lock, Cargo.toml, storage/backup/backup-cli/Cargo.toml, storage/backup/backup-cli/src/coordinators/replay_verify.rs, storage/backup/backup-cli/src/metadata/cache.rs, storage/backup/backup-cli/src/storage/mod.rs, storage/db-tool/src/replay_verify.rs, testsuite/replay_verify.py, testsuite/replay_verify_run_local.py, testsuite/smoke-test/src/storage.rs
1. use gcs instead of s3 for replay and verify
2. add retry at partition for failed command to improve robustness 
https://github.com/aptos-labs/aptos-core/actions/runs/6471317308
=> Use gcs for replay-verify and Make Replay-verify Resumable

third_party/move/move-vm/integration-tests/src/tests/loader_tests.rs, third_party/move/move-vm/integration-tests/src/tests/loader_tests_modules.move, third_party/move/move-vm/runtime/src/loader/mod.rs, third_party/move/move-vm/runtime/src/loader/modules.rs, third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
The runtime dependency check is a bit stricter than what bytecode verifier permits. Relax the constraint so that runtime check aligns with the static behavior.
Added a test case. The test would fail without the fix.
=> [move_vm] Fix loader dependency check

state-sync/state-sync-driver/src/bootstrapper.rs, state-sync/state-sync-driver/src/tests/bootstrapper.rs
This PR adds two info logs to the state sync bootstrapper to display information related to waypoint verification.
=>  [State Sync] Add info logs for waypoint verification.

Cargo.lock, crates/aptos/CHANGELOG.md, crates/aptos/Cargo.toml
The first of many PRs in the future where all we do is update the dependency on the processor code. These changes let the CLI pick up the latest and greatest processors / core processor framework code.
```
cargo run -p aptos node run-local-testnet --force-restart --assume-yes --with-indexer-api
```
I confirmed the indexer API starts and all processors work.
=> [CLI] Update processor dep for local testnet

network/benchmark/src/lib.rs, testsuite/forge-cli/src/main.rs
This PR adds a suite of forge network benchmark tests (to help identify network bottlenecks). It also moves some match statements into grouped functions to help reduce the size/complexity of managing many different forge tests in a single function. Given that we expect to continue adding forge tests, it probably makes sense to introduce some type of refactoring now.
=> [Forge] Add forge network benchmark tests and clean up some logic.

Cargo.lock, aptos-node/Cargo.toml
This PR bumps the `aptos-node` crate version to `1.7` given that this is the latest release.
=> [Aptos Node] Bump aptos-node version.

Cargo.lock, Cargo.toml
This PR changes us from using my Bollard fork that uses an older serde_with version to using the main Bollard crate.
Recently I landed a PR to serde_with that changed the minimum required serde version from 1.0.157 to 1.0.152: https://github.com/jonasbb/serde_with/pull/653. Bollard uses serde_with, so now the transitive dependency on serde through serde_with from Bollard is no longer 1.0.157 but 1.0.152, which we can use happily without breaking the the analyze formats code (see this issue for more details: https://github.com/aptos-labs/aptos-core/issues/10424).
```
cargo run -p generate-format -- --corpus aptos
```
=> Use bollard crate directly, upgrade serde to 1.0.152

third_party/move/move-vm/integration-tests/src/tests/loader_tests.rs, third_party/move/move-vm/integration-tests/src/tests/loader_tests_modules.move, third_party/move/move-vm/types/src/loaded_data/runtime_types.rs
The compatibility rule causes the loader paranoid check to break. Fix this issue.
Added a replay.
We need to wait to see if this fix replay issues.
=> [move-vm] Fix compatibility issue

Cargo.lock, Cargo.toml, crates/aptos/Cargo.toml, crates/aptos/src/node/local_testnet/health_checker.rs, crates/aptos/src/node/local_testnet/mod.rs, crates/aptos/src/node/local_testnet/processors.rs, crates/aptos/src/node/local_testnet/utils.rs
Previously in order to check that the processors were up we would check the health check port of the processor. This has two downsides:
1. This health check port doesn't actually check health at all, it always returns 200. So all this tells us is the health check server came up.
2. This meant we had to open a port for each processor for the health check port, which leads to port exhaustion issues sometimes.
In this PR I change it so when we run the processor, we just run the processor, not the health check port. To check that the processor is up, we instead check the processor status table in the DB.
```
$ cargo run -p aptos -- node run-local-testnet --assume-yes --force-restart --with-indexer-api
Readiness endpoint: http://0.0.0.0:8070/
Indexer API is starting, please wait...
Transaction …
```
=> [CLI] Health check processors using DB for local testnet

aptos-move/aptos-native-interface/src/context.rs, aptos-move/aptos-release-builder/src/components/feature_flags.rs, aptos-move/e2e-move-tests/src/aggregator_v2.rs, aptos-move/framework/move-stdlib/doc/features.md, aptos-move/framework/move-stdlib/sources/configs/features.move, aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
taking the indices before the rest of PRs land - as multiple PRs depend on these, and there are often conflicts with other flags going in.
repurpose SNAPSHOTS API flag to cover aggregator v2 api as well (as it will not be released separately)
=> [small] Add 3 aggregator related feature flags

ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs
* Tonic implicitly limits the decoding size to 4Mbtes. Relax it to unlimited.
=> [indexer grpc] Fix the cache worker grpc client message size.

aptos-move/aptos-vm/src/data_cache.rs, aptos-move/aptos-vm/src/move_vm_ext/vm.rs, aptos-move/aptos-vm/src/natives.rs, aptos-move/aptos-vm/src/tests/mock_view.rs, aptos-move/aptos-vm/src/tests/test_resolver_with_identifier_mapping.rs, aptos-move/block-executor/src/view.rs, aptos-move/framework/table-natives/src/lib.rs, third_party/move/extensions/async/move-async-vm/tests/testsuite.rs, third_party/move/extensions/move-table-extension/src/lib.rs, third_party/move/move-core/types/src/resolver.rs, third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs, third_party/move/move-vm/runtime/src/config.rs, third_party/move/move-vm/runtime/src/data_cache.rs, third_party/move/move-vm/runtime/src/loader/mod.rs, third_party/move/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs, third_party/move/move-vm/test-utils/src/storage.rs, third_party/move/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
- why are methods with layout named with "value" and methods without named with "bytes"? that is very confusing
- where should the gating - i.e. only do exchange if AGGREGATOR_EXECUTION flag is set - be?
=> Pass layout to initiate the exchange

api/src/tests/transactions_test.rs
The original test was missing a sleep to clear the cache. It never failed in CICD; it seems the work done in between took longer in CICD than macbook.
Run unit test locally.
=> [unit tests] one line fix for test_gas_estimation_cache

Cargo.lock, crates/aptos-telemetry-service/Cargo.toml, crates/aptos-telemetry-service/src/custom_event.rs
This PR fixes PeerId check during custom event Ingestion. #8727 changed how PeerId is represented as string by default making it a backwards-incompatible change. Therefore, instead of comparing strings, this PR parses the peer ID string into a PeerId struct and compares it instead.
Added new unit tests to catch this incompatibility.
=> [telemetry-svc][bugfix] Fix PeerId check for custom event

Cargo.lock, crates/transaction-emitter-lib/Cargo.toml, crates/transaction-emitter-lib/src/emitter/transaction_executor.rs, testsuite/forge-cli/src/main.rs
failing due to lack of event indices, which resulted in inability to query `NewBlockEvent`s
The PR does these two things to avoid querying the event indices:
1. skip chain progress checking
2. submit_and_wait uses bcs version of get_txn_by_hash which doesn't query the block timestamp
https://github.com/aptos-labs/aptos-core/actions/runs/6551209062
=> realistic_network_tuned_for_throughput: try not to query the event indices

aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs, aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs, aptos-move/framework/aptos-framework/doc/aggregator_v2.md, aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.move, aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.spec.move, aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs, aptos-move/framework/src/natives/aggregator_natives/helpers_v2.rs, aptos-move/vm-genesis/src/lib.rs, types/src/on_chain_config/aptos_features.rs
Self-contained logic that can be landed on main, and so ecosystem PRs can land independently of the rest of the aggregator changes
once aggregator backend execution logic lands, this will be a fallback logic used until separate aggregator execution flag is turned on.
Copied from aggregators_v2 branch
=> [agg_v2] Adding aggregator_v2.move with sequential (fallback) logic

Cargo.lock, Cargo.toml, ecosystem/indexer-grpc/indexer-grpc-data-access/Cargo.toml, ecosystem/indexer-grpc/indexer-grpc-data-access/src/access_trait.rs, ecosystem/indexer-grpc/indexer-grpc-data-access/src/gcs.rs, ecosystem/indexer-grpc/indexer-grpc-data-access/src/in_memory.rs, ecosystem/indexer-grpc/indexer-grpc-data-access/src/in_memory_storage/mod.rs, ecosystem/indexer-grpc/indexer-grpc-data-access/src/in_memory_storage/storage.rs, ecosystem/indexer-grpc/indexer-grpc-data-access/src/lib.rs, ecosystem/indexer-grpc/indexer-grpc-data-access/src/local_file.rs, ecosystem/indexer-grpc/indexer-grpc-data-access/src/redis.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/Cargo.toml, ecosystem/indexer-grpc/indexer-grpc-data-service/src/grpc_response_stream.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/lib.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/response_dispatcher/grpc_response_dispatcher.rs, ecosystem/indexer-grpc/indexer-grpc-data-service/src/response_dispatcher/mod.rs
* Refactor the data service v2.
* Add StorageTransactionRead interface, which facilitates the reads from different storages.
* Add InMemory storage to lower the cache read overhead.
* The only change to data service is token/auth is removed now. 
* Add the unit tests.
=> [indexer grpc][1/n] data service v2

api/types/src/transaction.rs, types/src/transaction/authenticator.rs
A few small fixes for #10519:
- Make sure that when we create a multiauth address, the # of signatures required is $> 0$.
- Make sure that when we create a multiauth address, the # of PKs is $\ge$ to the # of signatures required.
- Make sure that when we verify a multiauth signature, the signature bitmap is not empty
- Make sure that when we verify a multiauth signature, the signature bitmap does not have out-of-bounds indices
=> [authenticator] add sanity checks to multiauth

consensus/src/execution_pipeline.rs, consensus/src/experimental/buffer_manager.rs, consensus/src/experimental/execution_schedule_phase.rs, consensus/src/experimental/tests/execution_phase_tests.rs, execution/executor-types/src/error.rs
When consensus switches off to state sync, currently it's not guaranteed that there's no in flight blocks in the execution pipeline. This tries to address that by utilizing the CountedRequest mechanism in place.
unit tests and forge
=> Deal with ExecutionPipeline reset

aptos-move/aptos-vm-types/src/change_set.rs, aptos-move/aptos-vm-types/src/tests/test_change_set.rs, aptos-move/aptos-vm-types/src/tests/test_output.rs, aptos-move/aptos-vm-types/src/tests/utils.rs, aptos-move/aptos-vm/src/block_executor/mod.rs, aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs, aptos-move/aptos-vm/src/move_vm_ext/session.rs, aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs, aptos-move/block-executor/src/proptest_types/types.rs, aptos-move/block-executor/src/task.rs, aptos-move/block-executor/src/txn_last_input_output.rs
Use BTreeMap which provides deterministic ordering instead of HashMap.
Cherry-pick of #10582 
Fixed tests.
=> [execution] change HashMap to BTreeMap in VMChangeSet #10582

third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs, third_party/move/move-compiler-v2/tests/file-format-generator/assign.exp, third_party/move/move-compiler-v2/tests/file-format-generator/borrow.exp, third_party/move/move-compiler-v2/tests/file-format-generator/const.exp, third_party/move/move-compiler-v2/tests/file-format-generator/const.move, third_party/move/move-compiler-v2/tests/file-format-generator/fields.exp, third_party/move/move-compiler-v2/tests/file-format-generator/globals.exp, third_party/move/move-compiler-v2/tests/file-format-generator/if_else.exp, third_party/move/move-compiler-v2/tests/file-format-generator/loop.exp, third_party/move/move-compiler-v2/tests/file-format-generator/operators.exp, third_party/move/move-compiler-v2/tests/file-format-generator/vector.exp, third_party/move/move-compiler-v2/transactional-tests/tests/control_flow/sorter.exp, third_party/move/move-compiler-v2/transactional-tests/tests/no-v1-comparison/print_bytecode.exp
Compiler v2 currently uses LdConst to load all kinds of constants. However, we should prefer specific load instructions (e.g., LdTrue) for better efficiency and gas usage.
Existing compiler v2 tests, plus a new `file-format-generator/const.exp` test showing how constants are compiled.
closes https://github.com/aptos-labs/aptos-core/issues/9614
=> [Compiler v2] Prefer specific Ld* over LdConst
