Cargo.lock
crates/aptos-crypto/src/hash.rs
storage/aptosdb/Cargo.toml
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/state_store/test.rs
storage/aptosdb/src/schema/db_metadata/mod.rs
storage/aptosdb/src/state_kv_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/aptosdb/src/test_helper.rs
storage/aptosdb/src/utils/truncation_helper.rs
types/src/state_store/state_key.rs

Shard state kv commit batch, and run in parallel.
Add recovery logic when constructing StateKvDb.

[Storage][Sharding] Shard state kv commit batch.

---

developer-docs-site/docs/guides/get-test-funds.md
developer-docs-site/docs/guides/local-testnet-dev-flow.md

Changes since [PR 6947 ](https://github.com/aptos-labs/aptos-core/pull/6947) to address concerns raised in [issue 7067](https://github.com/aptos-labs/aptos-core/issues/7067):
- Reformatted the first section to increase the visibility of the other networks and methods of interacting with them
- Mentioned local testnet and hyperlinked the relevant page for developing locally
- Rephrased the mainnet portion to more explicitly state our position on funding

Raise the visibility of other networks and methods of interaction

---

aptos-move/framework/aptos-stdlib/doc/pool_u64_unbound.md
aptos-move/framework/aptos-stdlib/sources/pool_u64_unbound.spec.move

This PR adds the spec for `transfer_shares` and data invariant for `Pool` in `pool_u64_unbound.move`
prover test on CI

[Spec] Add spec for transfer_shares and data invariant for Pool in pool_u64_unbound

---

aptos-move/move-examples/README.md

I keep forgetting how to run these & other people might stand to benefit (cc @mstraka100, for running the `veiled_coin.move` test cases).

Create README.md for `move-examples`

---

.github/workflows/run-gas-calibration.yaml

Add credential for gas calibration.

[gha] add credentials for gas calibration for 1.3

---

aptos-move/e2e-move-tests/src/tests/token_objects.rs
aptos-move/move-examples/token_objects/sources/aptos_token.move
aptos-move/move-examples/token_objects/sources/collection.move
aptos-move/move-examples/token_objects/sources/token.move

* Introduce no-code collections
* Migrate common token fields to collection (mutability, burnability, freezability)
* Added some missing property map tests to AptosToken
* Deduplicate token fields that were on the collection (collection name and creator)
* Add support to mutating royalties to AptosCollection

More improvements to no-code token and collections

---

crates/indexer/src/models/stake_models/stake_utils.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/models/stake_models/stake_utils.rs

We moved staking contract to 0x1. 
Backfilled testnet. Seems to work.

[indexer] change staking contract

---

config/src/config/quorum_store_config.rs
consensus/consensus-types/src/common.rs
consensus/consensus-types/src/proof_of_store.rs
consensus/src/payload_manager.rs
consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/counters.rs
consensus/src/quorum_store/proof_manager.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/quorum_store/quorum_store_coordinator.rs
consensus/src/quorum_store/tests/proof_manager_test.rs
consensus/src/quorum_store/utils.rs

cherry-pick before merging to main

[previewnet] a pre-merge version of PR 7315

---

storage/aptosdb/src/backup/restore_utils.rs
storage/backup/backup-cli/src/backup_types/transaction/tests.rs

update the version while saving txn ws
updated unit test and manual test with more iteration

[storage] fix the version update

---

terraform/helm/fullnode/templates/backup.yaml
terraform/helm/fullnode/templates/restore.yaml

update the command to the correct aptos-db-tool command

[storage] update image command

---

developer-docs-site/docs/tutorials/build-e2e-dapp/6-handle-tasks.md

Simple update to correct the onTaskAdded section from the last part of the E2E DApp tutorial. 
1. Updated from using .unshift() to .push() when adding new task to the ToDoList.
2. Make sure the content matches exactly of what the final solution have.
Inspected and make sure the specified document content has been updated.

[Documentation] Update onTaskAdded from E2E Dapp tutorial

---

storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/state_store/test.rs
storage/aptosdb/src/schema/db_metadata/mod.rs
storage/aptosdb/src/state_kv_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/aptosdb/src/test_helper.rs
storage/aptosdb/src/utils/truncation_helper.rs
types/src/state_store/state_key.rs

[Storage] Tiny changes.

---

developer-docs-site/docs/guides/use-aptos-explorer.md

From:
https://github.com/aptos-foundation/ecosystem-projects/pull/95

Link to list of other Aptos Explorers from Aptos Explorer page

---

terraform/aptos-node-testnet/aws/main.tf
terraform/aptos-node-testnet/aws/variables.tf
terraform/aptos-node/aws/kubernetes.tf
terraform/aptos-node/aws/security.tf
terraform/aptos-node/aws/variables.tf
terraform/aptos-node/gcp/security.tf
terraform/aptos-node/gcp/variables.tf
terraform/fullnode/aws/security.tf
terraform/fullnode/aws/variables.tf
terraform/fullnode/gcp/main.tf
terraform/fullnode/gcp/security.tf
terraform/fullnode/gcp/variables.tf
terraform/modules/eks/kubernetes.tf
terraform/scripts/migrate_cluster_psp_to_pss.sh

Move security-related resources to security.tf and add PSS labels on namespace "default".
The disabling of PSP will have to be done using the migration script, but only once.
Tested on Rustienet.

Add PSS resources

---

third_party/move/move-vm/runtime/src/loader.rs

Spell out the cases in the pattern match

Address victor's comment and add struct

---

third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
third_party/move/move-prover/tests/sources/regression/test_bitvector.move

Close #7361 
Add a new regression test

[Move-prover] Fix a bug on generating code of shift operation for the bv type

---

developer-docs-site/docs/tutorials/build-e2e-dapp/6-handle-tasks.md

Fix tiny typo

---

developer-docs-site/docs/whats-new-in-docs.md

Fix link to new delegation pool ops doc from See what's new

---

Cargo.lock
consensus/Cargo.toml
consensus/src/block_storage/block_store_test.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/consensus_provider.rs
consensus/src/epoch_manager.rs
consensus/src/experimental/tests/buffer_manager_tests.rs
consensus/src/network.rs
consensus/src/network_tests.rs
consensus/src/round_manager.rs
consensus/src/twins/twins_node.rs
crates/channel/src/aptos_channel.rs

- dispatch message verification into multiple thread executor
- increase the message channel size and fix the ordering
- increase the state sync threshold to compensate large pipeline

[cherry-pick] various improvement for consensus

---

crates/aptos/src/account/mod.rs
crates/aptos/src/genesis/mod.rs
crates/aptos/src/move_tool/mod.rs
crates/aptos/src/node/mod.rs
crates/aptos/src/stake/mod.rs

Just cleanup I originally had in a different PR.
```
cargo run -p aptos -- -h
```

[CLI] Sort items in Tool structs

---

consensus/src/pending_votes.rs

saw
Metric Family 'aptos_consensus_current_round_voted_power' over 1000 dimensions '6807' in logs

[cherry-pick]  [consensus] Fix unnecessary metric dimension #7388 

---

developer-docs-site/docs/community/contributions/index.md

[PR 7308](https://github.com/aptos-labs/aptos-core/pull/7308) lead to the table not rendering correctly.

Fix broken table in Community Highlights

---

developer-docs-site/docusaurus.config.js

Follow up on and dependent upon:
https://github.com/aptos-labs/aptos-core/pull/7346

Redirect Upgrade Move page migrated to Move Book

---

scripts/dev_setup.sh

Found while investigation issue: https://github.com/aptos-labs/aptos-core/issues/7360

[dev setup] fix typo on nextest

---

config/src/config/state_sync_config.rs

This PR updates the node configs to default to execution mode for state sync.

[Configs] Default state sync to execution mode.

---

aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
third_party/move/move-vm/runtime/src/loader.rs

There was a swap of checks creating different error codes because different error was checked first

fix replay issue

---

.github/workflows/docker-build-test.yaml
aptos-move/aptos-release-builder/src/validate.rs

Reset the base image tag for framework upgrade to a image on 1.3 branch
`framework_upgrade` forge test.

[forge] Update base image tag for framework upgrade

---

config/src/config/network_config.rs

try network configs on previewnet

---

third_party/README.md
third_party/copy.bara.sky

Updates the copybara script as needed for https://github.com/move-language/move/pull/993. Also updates the README.md documentation.

[third_party] Update copybara script and README

---

developer-docs-site/scripts/additional_dict.txt

Needed by:
https://github.com/aptos-labs/aptos-core/pull/7106

Add WELLDONE to spelling dictionary

---

api/src/context.rs
crates/aptos-rosetta/src/construction.rs
crates/indexer/src/indexer/fetcher.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
execution/executor/src/mock_vm/mock_vm_test.rs
execution/executor/src/mock_vm/mod.rs
state-sync/state-sync-v2/state-sync-driver/src/tests/utils.rs
storage/aptosdb/src/fake_aptosdb.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/transaction_store/test.rs
storage/aptosdb/src/test_helper.rs
storage/aptosdb/src/transaction_store/mod.rs
storage/aptosdb/src/transaction_store/test.rs
testsuite/smoke-test/src/rest_api.rs
types/src/transaction/mod.rs

Small refactor, in preparation for QS incentive model - #6798

Use as_signed_user_txn/as_block_metadata and change it to Option

---

testsuite/smoke-test/src/upgrade.rs

[smoke-test] Diable flaky multi step upgrade test

---

storage/aptosdb/src/metrics.rs
storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_restore/restore_test.rs
storage/jellyfish-merkle/src/lib.rs
storage/jellyfish-merkle/src/mock_tree_store.rs
storage/jellyfish-merkle/src/node_type/mod.rs
storage/jellyfish-merkle/src/node_type/node_type_test.rs
storage/jellyfish-merkle/src/restore/mod.rs

[Storage] Add a tag dimension to jmt cache metrics.

---

config/src/config/storage_config.rs
execution/executor-benchmark/src/main.rs
storage/aptosdb/src/aptosdb_test.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/state_kv_pruner_manager.rs
storage/aptosdb/src/pruner/state_kv_pruner_worker.rs
storage/aptosdb/src/pruner/state_store/test.rs
storage/aptosdb/src/state_store/mod.rs

To make sure we don't accidentally enable state_kv_pruner on those intentional "full fullnodes".

[Storage][Pruner] Use ledger pruner config for state kv pruner.

---

scripts/dev_setup.sh

Updated `dev_setup.sh` to install `graphviz` upon the option `-y`.
This resolves https://github.com/aptos-labs/aptos-core/issues/5579.

Add graphviz to dev_setup.sh

---

developer-docs-site/docs/guides/move-guides/index.md

Restoring link to Move Upgrades doc on Move index

---

crates/aptos-rosetta/src/account.rs
crates/aptos-rosetta/src/client.rs
crates/aptos-rosetta/src/construction.rs
crates/aptos-rosetta/src/types/identifiers.rs
crates/aptos-rosetta/src/types/misc.rs
crates/aptos-rosetta/src/types/move_types.rs
crates/aptos-rosetta/src/types/objects.rs
testsuite/smoke-test/src/rosetta.rs

This PR cherry-picks four `unlock_stake/distribute` related PRs.

[Rosetta] v1.3.2 staking operation supported Rosetta version

---

.github/workflows/module-verify.yaml
.github/workflows/replay-verify.yaml

Group the condition such that it checks for the `inputs.CHAIN_NAME` in a separate conditional block. Also some formatting improvements to make it more readable.

[gha] fix replay-verify and module-verify network conditional

---

developer-docs-site/docs/community/aptos-style.md

Continue building out docs best practices in Aptos Style Guide

---

developer-docs-site/docs/concepts/base-gas.md

update u16, u32, u256 and call per local for base-gas.md
N/A

[Docs] update instruction for base-gas.md

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/examples/typescript/simple_nft.ts
ecosystem/typescript/sdk/src/indexer/generated/operations.ts
ecosystem/typescript/sdk/src/indexer/generated/queries.ts
ecosystem/typescript/sdk/src/indexer/generated/types.ts
ecosystem/typescript/sdk/src/indexer/queries/getAccountCoinsData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getAccountTokensCount.graphql
ecosystem/typescript/sdk/src/indexer/queries/getAccountTransactionsCount.graphql
ecosystem/typescript/sdk/src/indexer/queries/getAccountTransactionsData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getCurrentDelegatorBalancesCount.graphql
ecosystem/typescript/sdk/src/indexer/queries/getDelegatedStakingActivities.graphql
ecosystem/typescript/sdk/src/indexer/queries/getTokenActivities.graphql
ecosystem/typescript/sdk/src/indexer/queries/getTokenActivitiesCount.graphql
ecosystem/typescript/sdk/src/indexer/queries/getTokenData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getTokenOwnersData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getTopUserTransactions.graphql
ecosystem/typescript/sdk/src/indexer/queries/getUserTransactions.graphql
ecosystem/typescript/sdk/src/providers/indexer.ts
ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts

Adding Indexer queries Explorer uses so they can stop maintaining Apollo and GQL and utilize TS SDK. 
https://github.com/aptos-labs/aptos-core/issues/7076

[TS SDK] Add Indexer GQL queries

---

state-sync/aptos-data-client/src/aptosnet/metrics.rs
state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
state-sync/state-sync-v2/data-streaming-service/src/metrics.rs

This PR improves a few of the metrics for the Aptos Data Client and the Data Streaming Service.

[State Sync] Update various counters.

---

ecosystem/indexer-grpc/indexer-grpc-parser/README.md

Change readme

---

config/src/config/storage_config.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/lru_node_cache.rs
storage/aptosdb/src/pruner/pruner_utils.rs
storage/aptosdb/src/pruner/state_merkle_pruner_manager.rs
storage/aptosdb/src/pruner/state_store/mod.rs
storage/aptosdb/src/pruner/state_store/test.rs
storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/aptosdb/src/test_helper.rs
storage/aptosdb/src/utils/truncation_helper.rs
storage/aptosdb/src/versioned_node_cache.rs
storage/backup/backup-cli/src/utils/mod.rs

No-op refactoring, wrap DBs, and pass StateMerkleDb around as parameters instead of the raw DB object.

[Storage][Sharding] Wrap DBs in StateMerkleDb.

---

aptos-node/src/storage.rs
execution/executor-benchmark/src/db_generator.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/main.rs
storage/aptosdb/src/db_debugger/checkpoint/mod.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/state_kv_db.rs
storage/aptosdb/src/state_merkle_db.rs

[Storage][Sharding] Support checkpoint on sharded DBs.

---

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md

Correct misplaced monospace

---

developer-docs-site/docs/releases/devnet-release.md
developer-docs-site/docs/releases/mainnet-release.md
developer-docs-site/docs/releases/testnet-release.md

update to latest binary releases 1.3.3 and CLI 1.0.9

---

Cargo.lock
storage/backup/backup-cli/Cargo.toml
storage/backup/backup-cli/src/backup_types/transaction/analysis.rs
storage/backup/backup-cli/src/backup_types/transaction/mod.rs
storage/backup/backup-cli/src/backup_types/transaction/restore.rs
storage/backup/backup-cli/src/backup_types/transaction/tests.rs
storage/backup/backup-cli/src/coordinators/backup.rs
storage/backup/backup-cli/src/coordinators/replay_verify.rs
storage/backup/backup-cli/src/coordinators/restore.rs
storage/backup/backup-cli/src/coordinators/verify.rs
storage/db-tool/src/backup.rs

[db-tool] ability to print out transaction output sizing info

---

aptos-move/framework/move-stdlib/doc/vector.md
aptos-move/framework/move-stdlib/sources/vector.move
third_party/move/move-prover/boogie-backend/src/prelude/native.bpl
third_party/move/move-prover/tests/sources/functional/loops_with_memory_ops.exp

This PR consists two commits:
1) Add boogie natives for newly added public APIs in the `vector` module;
2) Add intrinsics to `vector.move` in `aptos-core`
Close #7204

[Spec] Add boogie natives for newly added public methods in vector

---

.github/workflows/grafana-sync.yaml
scripts/grafana-sync.mts

update the endpoint
workflow_dispatch from this PR branch: https://github.com/aptos-labs/aptos-core/actions/runs/4622229667

[gha] update grafana sync endpoint

---

aptos-move/framework/aptos-token-objects/doc/aptos_token.md
aptos-move/framework/aptos-token-objects/sources/aptos_token.move

Corrected an error code
cargo test

Correct an error code in `aptos_token.move`

---

.github/workflows/docker-build-test.yaml

[gha] revert conditional docker and forge builds

---

consensus/src/pending_votes.rs

saw
Metric Family 'aptos_consensus_current_round_voted_power' over 1000 dimensions '6807' in logs

[consensus] Fix unnecessary metric dimension

---

testsuite/forge-test-runner-template.yaml

[forge] fix yaml quotation

---

api/src/context.rs
api/src/tests/transactions_test.rs
api/test-context/src/test_context.rs

[api] Update gas estimation

---

storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/state_store/test.rs
storage/aptosdb/src/schema/db_metadata/mod.rs
storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
storage/aptosdb/src/state_store/state_snapshot_committer.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/aptosdb/src/test_helper.rs
storage/aptosdb/src/utils/truncation_helper.rs
storage/jellyfish-merkle/src/node_type/mod.rs

[Storage][Sharding] Split tree commit into multiple batches.

---

consensus/src/quorum_store/proof_coordinator.rs

Late votes will re-init batch metadata. We assume if a batch hasn't completed and hasn't received a self vote that they are created due to late votes, and don't log their metrics.

[Quorum Store] reduce false positives of timeout and low vote count

---

.github/workflows/forge-stable.yaml
testsuite/forge-cli/src/main.rs

Remove one broken test, adjust the threshold for the other
Test Plan: running on PR

[forge] Remove broken test from stable job

---

api/src/context.rs
api/src/tests/transactions_test.rs
api/test-context/src/test_context.rs

[cherry-pick] Aptos release v1.3 cherry pick gas

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] Bump version from 1.7.2 to 1.8.2

---

api/src/context.rs
api/src/tests/transactions_test.rs
api/test-context/src/test_context.rs

[api] Fix legacy testing for gas

---

developer-docs-site/docs/concepts/coin-and-token/nft-airdrop-example.md
developer-docs-site/docs/whats-new-in-docs.md
developer-docs-site/docusaurus.config.js
developer-docs-site/sidebars.js
developer-docs-site/src/contributors.json

improve naming of example

---

testsuite/fixtures/forge-test-runner-template.fixture
testsuite/forge.py
testsuite/forge_test.py
testsuite/forge_wrapper_core/shell.py

Add logging for all output of the Forge wrapper.
Auto-detect cloud environment from the cluster name.
Successfully scheduled "land_blocking" tests on the GCP clusters.

Add logging to Forge wrapper and auto-detect cloud

---

crates/aptos-telemetry/src/core_metrics.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/metrics.rs
storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
storage/aptosdb/src/pruner/state_kv_pruner.rs
storage/aptosdb/src/pruner/state_store/mod.rs
testsuite/smoke-test/src/state_sync.rs

[Storage] Add some metrics.

---

third_party/move/tools/move-package/src/resolution/resolution_graph.rs

In order to use certain features of the Aptos CLI, such as `aptos move compile` or `aptos move publish`, you must have `git` locally to download dependencies such as the framework. If you don't have it, the command fails with this error.
Command:
```
PATH='' ~/.local/bin/aptos move compile --package-dir /tmp/ans/core/
```
Output:
```
FETCHING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
{
"Error": "Move compilation failed: Unable to resolve packages for package 'aptos_names': While resolving dependency 'AptosFramework' in package 'aptos_names': Failed to fetch latest Git state for package 'AptosFramework', to skip set --skip-fetch-latest-git-deps"
}
```
This error is a bit obscure.
Now it looks like this:
```
PATH='' target/debug/aptos move compile --package-dir …
```

[Move] Check for git explicitly in resolution graph

---

developer-docs-site/docs/releases/devnet-release.md
developer-docs-site/docs/releases/mainnet-release.md

Update release versions

---

developer-docs-site/docs/community/rust-coding-guidelines.md

Fix links to migrated Rust resources from Rust Coding Guidelines

---

developer-docs-site/docs/sdks/ts-sdk/typescript-sdk-overview.md

Fix links to TypeScript files reorganized in PR #6993

---

aptos-move/framework/aptos-token-objects/doc/token.md
aptos-move/framework/aptos-token-objects/sources/token.move

as title
per @bowenyang007 request.
ut

[token_v2] add old/new_value to mutation events and change field name

---

aptos-move/aptos-release-builder/data/example.yaml
aptos-move/aptos-release-builder/data/release.yaml
aptos-move/vm-genesis/src/lib.rs

Turn on the flags for features crypto_algebra and bls12381_structures by default.

crypto_algebra and bls12381_structures as default features

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Pending @0xjinn's changes, will release soon.

[cli] Make the 1.0.10 release

---

developer-docs-site/docs/tutorials/first-move-module.md

I have updated the terminal outputs since new versions of CLI output a different message than the one mentioned in this doc.

Updated first-move-module.md to match with the terminal outputs given by the latest version of Aptos CLI

---

developer-docs-site/docs/community/contributions/remix-ide-plugin.md
developer-docs-site/scripts/additional_dict.txt

This PR contains some improvements to the WELLDONE Remix plugin docs, such as reordering some sections to match the actual development flow and some other formatting fixes.
Docs.

Improve docs for WELLDONE Remix plugin

---

docker/compose/data-restore/gcs.yaml
docker/compose/data-restore/s3.yaml
storage/backup/backup-cli/src/metadata/cache.rs
storage/backup/backup-cli/src/storage/command_adapter/mod.rs
storage/backup/backup-cli/src/storage/command_adapter/sample_configs/azure.sample.yaml
storage/backup/backup-cli/src/storage/command_adapter/sample_configs/gcp.sample.yaml
storage/backup/backup-cli/src/storage/command_adapter/sample_configs/local_folder.sample.yaml
storage/backup/backup-cli/src/storage/command_adapter/sample_configs/s3.sample.yaml
storage/backup/backup-cli/src/storage/command_adapter/tests.rs
storage/backup/backup-cli/src/storage/local_fs/mod.rs
storage/backup/backup-cli/src/storage/mod.rs
terraform/helm/fullnode/files/backup/azure.yaml
terraform/helm/fullnode/files/backup/gcs.yaml
terraform/helm/fullnode/files/backup/oci.yaml
terraform/helm/fullnode/files/backup/s3-public.yaml
terraform/helm/fullnode/files/backup/s3.yaml
terraform/helm/fullnode/files/backup/scw_s3.yaml

Return file handle in save_xxx interfaces and update the commands
use existing tests

[storage] update the backupstorage interface

---

crates/aptos-rosetta/src/account.rs
crates/aptos-rosetta/src/types/misc.rs
crates/aptos-rosetta/src/types/requests.rs

* add lockup_expiration to balance endpoint metadata

[rosetta] Add lockup_expiration to account balance metadata (#7711)

---

aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-tests/src/executor.rs

Support view function execution in e2e test harness

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

Bump version to release 1.8.4 version
pnpm run lint

[TS SDK] Bump the TS SDK version to 1.8.4

---

developer-docs-site/docs/tutorials/build-e2e-dapp/3-add-wallet-support.md
developer-docs-site/docs/tutorials/build-e2e-dapp/index.md

[DOC] Update adapter version to use

---

aptos-move/framework/aptos-token-objects/doc/collection.md
aptos-move/framework/aptos-token-objects/sources/collection.move

0 max supply makes no sense.
ut

[tokenv2] disallow 0 max_supply

---

developer-docs-site/docs/releases/devnet-release.md
developer-docs-site/docs/releases/mainnet-release.md
developer-docs-site/docs/releases/testnet-release.md

update devnet, testnet, mainnet version

---

crates/aptos/src/move_tool/mod.rs

[CLI] Correct invalid BCS type arguments

---

state-sync/storage-service/server/src/handler.rs
state-sync/storage-service/server/src/tests.rs

This PR adds basic sanity checks to the server-side of the storage service. Specifically, we verify all requests are serviceable before handling them (i.e., the data held by the server is a superset of the data being requested).
Note:
- These checks are best-effort only. There are some request parameters that state sync cannot verify without going directly to storage (e.g., in the case of fast sync indices), so we still need to be prepared to handle bad storage requests on the database side.
- Most of this PR is just new unit tests 😄 
Existing and new tests.

[State Sync] Add sanity checks to storage requests.

---

aptos-node/src/lib.rs
aptos-node/src/tests.rs
config/src/config/node_config.rs
config/src/config/persistable_config.rs
config/src/config/safety_rules_config.rs
config/src/generator.rs
crates/aptos-genesis/src/builder.rs
crates/aptos-telemetry/src/sender.rs
crates/aptos-telemetry/src/service.rs
crates/aptos/src/node/mod.rs
mempool/src/tests/common.rs
mempool/src/tests/core_mempool_test.rs
mempool/src/tests/mocks.rs
mempool/src/tests/multi_node_test.rs
mempool/src/tests/node.rs
network/src/testutils/builder.rs
testsuite/forge/src/backend/local/mod.rs
testsuite/forge/src/backend/local/node.rs
testsuite/smoke-test/src/full_nodes.rs
testsuite/smoke-test/src/fullnode.rs
testsuite/smoke-test/src/genesis.rs
testsuite/smoke-test/src/network.rs
testsuite/smoke-test/src/state_sync.rs
testsuite/smoke-test/src/test_smoke_tests.rs
testsuite/smoke-test/src/txn_broadcast.rs

This PR makes several small refactors and cleanups to the node configs. Specifically, it:
- Removes unused parameters from methods.
- Renames a few methods for consistency and clarity.
- Adds additional comments to the code.
- Unifies a few methods to reduce code duplication and provide better consistency.
Nothing should logically change with this PR. 😄  Also, there's a bunch more cleanups to be done, but I'm delegating that to future PRs.

[Node Configs] Small refactors and clean ups.

---

.github/workflows/execution-performance.yaml

To correct the directory of the yaml file.

[Execution Benchmark] Small fix

---

Cargo.lock
crates/transaction-emitter-lib/src/args.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/lib.rs
crates/transaction-emitter-lib/src/wrappers.rs
crates/transaction-generator-lib/src/account_generator.rs
crates/transaction-generator-lib/src/accounts_pool_wrapper.rs
crates/transaction-generator-lib/src/args.rs
crates/transaction-generator-lib/src/call_custom_modules.rs
crates/transaction-generator-lib/src/lib.rs
crates/transaction-generator-lib/src/nft_mint_and_transfer.rs
crates/transaction-generator-lib/src/p2p_transaction_generator.rs
crates/transaction-generator-lib/src/publish_modules.rs
crates/transaction-generator-lib/src/transaction_mix_generator.rs
execution/executor-benchmark/Cargo.toml
execution/executor-benchmark/src/account_generator.rs
execution/executor-benchmark/src/db_access.rs
execution/executor-benchmark/src/fake_executor.rs
execution/executor-benchmark/src/gen_executor.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/main.rs
execution/executor-benchmark/src/transaction_generator.rs

enabling to test on same workloads as Forge

Use transaction-generator-lib in executor benchmark

---

aptos-move/framework/aptos-framework/doc/account.md
aptos-move/framework/aptos-framework/doc/code.md
aptos-move/framework/aptos-framework/doc/guid.md
aptos-move/framework/aptos-framework/doc/version.md
aptos-move/framework/aptos-framework/sources/account.move
aptos-move/framework/aptos-framework/sources/code.move
aptos-move/framework/aptos-framework/sources/configs/version.move
aptos-move/framework/aptos-framework/sources/guid.move
aptos-move/framework/aptos-token-objects/sources/collection.move
aptos-move/framework/aptos-token-objects/sources/token.move
aptos-move/framework/aptos-token/doc/property_map.md
aptos-move/framework/aptos-token/doc/token.md
aptos-move/framework/aptos-token/sources/property_map.move
aptos-move/framework/aptos-token/sources/token.move
aptos-move/framework/aptos-token/sources/token_transfers.move
aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move
aptos-move/move-examples/shared_account/sources/shared_account.move
aptos-move/move-examples/token_objects/sources/hero.move
third_party/move/evm/examples/sources/ERC1155.move
third_party/move/evm/examples/sources/ERC20.move
third_party/move/evm/examples/sources/ERC721.move
third_party/move/evm/move-to-yul/tests/Tables.move
third_party/move/evm/move-to-yul/tests/Vectors.move
third_party/move/evm/move-to-yul/tests/test-dispatcher/DispatcherEncodingStorage.move

*& is not necessary for copyable values.
Code compiles.

Remove unnecessary *& syntax

---

aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/execution_config.md
aptos-move/framework/aptos-framework/doc/gas_schedule.md
aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/configs/execution_config.move
aptos-move/framework/aptos-framework/sources/configs/execution_config.spec.move
aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
aptos-move/framework/aptos-framework/sources/genesis.move
aptos-move/framework/aptos-stdlib/doc/fixed_point64.md
aptos-move/framework/aptos-stdlib/sources/fixed_point64.move

As above to simplify the governance proposal. 
Existing UTs.

Remove initialize function from execution config

---

aptos-move/framework/FRAMEWORK-PROVER-GUIDE.md
developer-docs-site/docs/guides/prover-guides/index.md
developer-docs-site/docs/guides/prover-guides/spec-lang.md
developer-docs-site/docs/guides/prover-guides/supporting-resources.md
developer-docs-site/sidebars.js

Added a page for Move Prover supporting resources
Fixed the broken expression in `spec-lang.md`.
Updated `framework-prover-guide.md` for a better hyper link.
Migrated the info from https://github.com/aptos-labs/aptos-core/pull/7623
pnpm build

[Doc] Added a page for Move Prover supporting resources

---

aptos-move/aptos-release-builder/data/example.yaml
aptos-move/aptos-release-builder/data/release.yaml
aptos-move/aptos-release-builder/src/components/execution_config.rs
aptos-move/aptos-release-builder/src/components/mod.rs

Added support for changing execution config to enable transaction shuffling.
framework upgrade test.

[release-tooling] Add section for execution config

---

aptos-move/aptos-release-builder/data/release.yaml

Update proposal metadata

---

aptos-move/aptos-vm/src/aptos_vm.rs

combine with https://github.com/aptos-labs/aptos-core/pull/7716 to provide visibility of invariant violation compatible with speculative execution

[vm] log invariant violation error in adapter

---

docker/rust-all.Dockerfile

Update Docker images

---

aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/block.md
aptos-move/framework/aptos-framework/doc/consensus_config.md
aptos-move/framework/aptos-framework/doc/gas_schedule.md
aptos-move/framework/aptos-framework/doc/reconfiguration.md
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/block.spec.move
aptos-move/framework/aptos-framework/sources/configs/consensus_config.spec.move
aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move
aptos-move/framework/aptos-stdlib/doc/fixed_point64.md
aptos-move/framework/aptos-stdlib/sources/fixed_point64.move

Remove timeout pragma in framework specs

[Spec] Remove timeout pragma in framework specs

---

developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md

Move the option to publish with no artifacts to later in the page

Update move publish docs

---

testsuite/parallel_execution_performance.py
testsuite/sequential_execution_performance.py

Small changes to the execution-only benchmark to check if the TPS is within a range (10%) of the hard-coded threshold.

[Execution Benchmark] Check if TPS within range

---

Cargo.lock
Cargo.toml

Cherry-picking the recent hotfix

cherry-pick: fix cfg-bypass bug in the bytecode verifier

---

testsuite/parallel_execution_performance.py

Increase noise thresholds for parallel execution test.

[Execution Benchmark] Pump thresholds

---

aptos-move/aptos-release-builder/data/release.yaml

update aip 26 and 27

---

execution/executor-benchmark/src/fake_executor.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/main.rs
execution/executor-benchmark/src/native_executor.rs

Improve fake executor to handle coin::transfer and aptos_account::transfer as well

---

.github/workflows/forge-unstable.yaml
testsuite/forge-cli/src/main.rs

Add the tests to forge unstable. If they prove stable for a week, should be moved to stable.

[Quorum Store] Add new tests to forge-unstable

---

consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_driver_test.rs
consensus/src/dag/reliable_broadcast.rs
consensus/src/epoch_manager.rs
testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs

dag driver shutdown

---

aptos-move/move-examples/post_mint_reveal_nft/Move.toml
aptos-move/move-examples/post_mint_reveal_nft/sources/minting.move
aptos-move/move-examples/post_mint_reveal_nft/sources/whitelist.move
aptos-move/move-examples/tests/move_unit_tests.rs

1. add multi-stage whitelist support
2. switch from using a resource account to using a normal account
3. switch from re-using the same tokendata to creating a new token data for each source token 
unit tests; manually tested

[move-examples] updated post-mint tutorial

---

types/src/on_chain_config/consensus_config.rs

We should delete the related code in separate commit too.

[consensus] disable coupled execution

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

[cli] Release 1.0.12

---

storage/aptosdb/src/lib.rs

[Storage][Refactoring] Extract code in save_transactions into multiple functions.

---

ecosystem/typescript/sdk/src/account/aptos_account.ts
ecosystem/typescript/sdk/src/tests/unit/aptos_account.test.ts
ecosystem/typescript/sdk/yarn.lock

Adds a signature verification method to the TS SDKs AptosAccount. These are convenience methods around nacl.
Added test for ensuring verification passes/fails as expected

[TS-SDK] Add verification ability to AptosAccount

---

aptos-move/framework/aptos-stdlib/doc/smart_table.md
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move

Here we add specifications for smart_table. 
Use the Aptos prover.

[Spec] Specs for `smart_table` module

---

.github/actions/docker-setup/action.yaml
.github/workflows/forge-gcp.yaml
.github/workflows/workflow-run-forge.yaml
terraform/aptos-node-testnet/gcp/main.tf

Auth to GCP in Forge-GCP workflow.
Tested manually via workflow_dispatch.

Connect GH actions to GCP environment

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

[CLI] upgrade cli to 1.0.13

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

Updated the package to version 1.8.5

[TS SDK] Bump version from 1.8.4 to 1.8.5

---

Cargo.lock
aptos-move/aptos-sdk-builder/Cargo.toml
aptos-move/aptos-sdk-builder/src/golang.rs

Serialize Vectors for the aptos-sdk-builder

---

aptos-node/src/lib.rs
config/src/config/api_config.rs
config/src/config/execution_config.rs
config/src/config/logger_config.rs
config/src/config/mempool_config.rs
config/src/config/network_config.rs
config/src/config/state_sync_config.rs
config/src/config/storage_config.rs

Add documentation to the config, and tune the CLI local testnet config
I was successful at pulling CPU down to 67-72% from 126% at idle.

Config tuning for local testnet

---

aptos-move/aptos-release-builder/data/release.yaml

- Update release.yaml
- [framework] Change step names, remove quorum store for now

Turn off crypto algebra and quorum store for v1.4 for now

---

crates/transaction-generator-lib/src/args.rs
crates/transaction-generator-lib/src/batch_transfer.rs
crates/transaction-generator-lib/src/lib.rs
testsuite/single_node_performance.py

Add batch transaction and multi-collection NFT mint to single node benchmark

---

consensus/src/block_storage/block_store.rs
consensus/src/counters.rs

[simple] add failed round counter

---

aptos-move/aptos-release-builder/src/main.rs
aptos-move/aptos-release-builder/src/validate.rs

Fix the tooling such that it fetch exactly one event instead of 100 events that can lead to potential pruning issues.
Framework testing would work.

[release] Fix tooling

---

config/src/config/mempool_config.rs
docker/compose/aptos-node/fullnode.yaml
terraform/helm/aptos-node/values.yaml

To reduce duplication when going through PFNs. (VFNs have a separate override.)

[mempool] reduce default failover: 3 -> 1

---

consensus/src/block_storage/block_store.rs
consensus/src/counters.rs
mempool/src/core_mempool/mempool.rs
mempool/src/counters.rs

A companion PR to #7998 that covers metrics on the mempool side.
Noop in non-metrics behavior. Existing tests.

[mempool] better counters for duplicate txns

---

aptos-move/aptos-vm/src/aptos_vm.rs

Add logging for invariant violation.
N/A

[aptos-vm] Add additional logging

---

config/src/config/mempool_config.rs
consensus/src/block_storage/block_store.rs
consensus/src/counters.rs
docker/compose/aptos-node/fullnode.yaml
execution/executor/src/components/chunk_output.rs
mempool/src/core_mempool/mempool.rs
mempool/src/counters.rs
terraform/helm/aptos-node/values.yaml

Changes are related to PFN forwarding and duplicates
#7998 #8022 #8023

[mempool] cherry-pick reduce default failover: 3 -> 1 and related PRs

---

.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml

Follow-up to #7913 after seeing the tests are successful.

[Forge / Quorum Store] upgrade unstable tests to stable

---

storage/aptosdb/src/state_merkle_db.rs

Fix state merkle db checkpoint.

---

aptos-move/aptos-vm/src/move_vm_ext/session.rs

[log] Add more logging

---

CODEOWNERS

This PR makes several modifications to the code owners file:
1. Extend the logger config owners to the entire config directory (just to help keep things tidy).
2. Add @brianolson to the network owners 😄.
3. Add owners for the inspection service.
4. Remove errors from unknown authors in the file.

[Code owners] Update owners for configs and network.

---

aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/sources/coin.spec.move

This is a part of spec work for Aptos Framework from MoveBit. The change is:
- Completed all specs left as TODO in previous commits.
`aptos move prove -f coin.move` passes.

[Spec] Finish all TODOs in coin.spec.move

---

aptos-move/aptos-release-builder/src/main.rs
aptos-move/aptos-release-builder/src/validate.rs
aptos-move/aptos-vm/src/aptos_vm.rs

Cherrypick a few changes from our production branch.
NA

Cherrypick changes from production.

---

aptos-move/framework/aptos-framework/doc/fungible_asset.md
aptos-move/framework/aptos-framework/sources/fungible_asset.move

1. Fix merge function
2. Remove the checking of supply underflow and delegate this to aggregator to unblock paralellism.
3. **Only enable adding fungibility to non-deletable objects**.
4. Fix `ungated_balance_transfer_allowed` function that it will not return `true` if non-existent. This is the default behavior for primary_fungible_store but not any store.
5. The second commit rename `asset` to `metadata` in tests.
ut

Fix several major issues in fungible asset 

---

aptos-move/e2e-move-tests/src/tests/access_path_test.rs
third_party/move/move-vm/runtime/src/data_cache.rs
third_party/move/move-vm/runtime/src/interpreter.rs

[move] skip core dump with storage error

---

aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/scheduler.rs
aptos-move/block-executor/src/task.rs
aptos-move/mvhashmap/src/lib.rs
aptos-move/mvhashmap/src/versioned_code.rs
aptos-move/mvhashmap/src/versioned_data.rs

Fix  typos  in block-executor comment
N/A

fix typos in block-executor comment

---

developer-docs-site/docs/concepts/gas-txn-fee.md

This updates our doc so that it correctly reflects our latest design, which has introduced separate storage fees. 
Notice that we'll also need to update the How Base Gas Works doc, but that'll be a separate PR.

[gas] update doc to reflect the introduction of separate storage fees

---

consensus/src/sender_aware_shuffler.rs

Shuffling was not handling the special case of conflict window size being 0 - so one of the fuzz test was flaky. Please note that this is not a problem in production as we have a non zero conflict window size. 
Added a new test

[Execution][Shuffling] Fix the flaky test for txn shuffling

---

config/src/config/config_optimizer.rs
config/src/config/mempool_config.rs
docker/compose/aptos-node/fullnode.yaml
terraform/helm/aptos-node/values.yaml

This PR adds mempool config overrides to the config optimizer and removes the manual overrides that have been specified in the docker and terraform files. Note: the config overrides are only for VFNs (not validators or PFNs). 
Several small unit tests have also been added.

[Config Optimizer] Add mempool config optimizations.

---

Cargo.lock
Cargo.toml

This gives us the `hidden` attribute on endpoints.
See here: https://github.com/poem-web/poem/blob/master/poem-openapi/CHANGELOG.md#2011-2022-08-30.
CI.

Update poem from 2.0.10 to 2.0.11

---

crates/aptos-protos/proto/aptos/indexer/v1/raw_data.proto
crates/aptos-protos/proto/aptos/internal/fullnode/v1/fullnode_data.proto
crates/aptos-protos/proto/aptos/transaction/testing1/v1/transaction.proto

Add JS annotation for uint64. 
* `buf lint` no errors. 
* `buf breaking` seems fine
* `	buf breaking --against '../../.git#branch=main,subdir=crates/aptos-protos/proto'` 	
*

[indexer grpc] add annotation for JS uint64.

---

ecosystem/typescript/sdk/src/plugins/index.ts

[TS SDK] Export AnsClient class

---

api/doc/spec.json
api/doc/spec.yaml
api/src/lib.rs
api/src/state.rs
api/types/src/error.rs
api/types/src/lib.rs
api/types/src/state.rs
aptos-move/aptos-validator-interface/src/rest_interface.rs
crates/aptos-rest-client/src/lib.rs
crates/aptos-rosetta/src/error.rs
ecosystem/typescript/sdk/src/generated/models/AptosErrorCode.ts

To support getting resource groups and state metadata.

[api] for the debugger: get_raw_state_value

---

developer-docs-site/docs/tools/aptos-cli-tool/use-aptos-cli.md

update use-aptos-cli help usage command

---

aptos-move/aptos-release-builder/data/release.yaml
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-release-builder/src/components/framework.rs

Cleanup the release file to get ready for next release cycle.
Covered by the framework release testing.

[release] Cleanup the release config for next release

---

crates/indexer/migrations/2023-05-17-010107_activities_v2/down.sql
crates/indexer/migrations/2023-05-17-010107_activities_v2/up.sql
crates/indexer/src/models/token_models/mod.rs
crates/indexer/src/models/token_models/v2_collections.rs
crates/indexer/src/models/token_models/v2_token_activities.rs
crates/indexer/src/models/token_models/v2_token_datas.rs
crates/indexer/src/models/token_models/v2_token_ownerships.rs
crates/indexer/src/models/token_models/v2_token_utils.rs
crates/indexer/src/models/v2_objects.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/schema.rs

1. Fix nft transfer (when nft is transferred we need to soft delete previous ownership record)
2. Add token activities
3. Pad some addresses that weren't padded properly in token v2 tables

[Indexer] Token v2 part 2

---

aptos-move/aptos-aggregator/src/aggregator_extension.rs
aptos-move/framework/src/natives/aggregator_natives/context.rs

self-descriptive :-) just to not forget the comments before auto-merge

Minor comment fixes add-on

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] Bump TS SDK version to 1.9.0

---

aptos-move/framework/src/natives/cryptography/multi_ed25519.rs

Fix the linting issue in the aptos-vm.
`cargo check`

[aptos-vm] Fix linting

---

aptos-move/aptos-gas/src/gas_meter.rs
aptos-move/aptos-gas/src/lib.rs

fix  typos in aptos-gas

---

docker/builder/build-tools.sh
docker/builder/indexer-grpc.Dockerfile

* Add post processor, which is for monitoring, file store snapshot, etc, into indexer grpc image.

[indexer grpc] Add post processor to indexer grpc.

---

api/goldens/aptos_api__tests__transactions_test__test_gas_estimation_disabled.json
api/src/context.rs
api/src/tests/transactions_test.rs
config/src/config/gas_estimation_config.rs
testsuite/smoke-test/src/rest_api.rs

Gate with a regular config so change is not released accidentally. Maybe want to change this to onchain eventually.

[Gas Estimation] gate (disable) the v2 logic

---

docker/compose/indexer-grpc/cache-worker-config.yaml
docker/compose/indexer-grpc/data-service-config.yaml
docker/compose/indexer-grpc/file-store-config.yaml
docker/compose/indexer-grpc/test_indexer_grpc_docker_compose.sh
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-post-processor/src/main.rs

[indexer grpc] remove the server name from config.

---

ecosystem/typescript/sdk/SPEC.md

Aptos SDK spec for anyone who wants to create an Aptos SDK.

Aptos SDK Spec

---

crates/indexer/src/models/token_models/v2_token_ownerships.rs

[Indexer] Only include tokenstore in v1

---

config/src/config/storage_config.rs
storage/aptosdb/src/db_options.rs
storage/aptosdb/src/ledger_db.rs
storage/aptosdb/src/lib.rs
storage/backup/backup-cli/src/utils/mod.rs

[Storage][Sharding] Add a LedgerDb struct, to prepare split ledger db to multiple RocksDB instances.

---

aptos-move/framework/aptos-stdlib/doc/big_vector.md
aptos-move/framework/aptos-stdlib/doc/smart_table.md
aptos-move/framework/aptos-stdlib/doc/smart_vector.md
aptos-move/framework/aptos-stdlib/sources/data_structures/big_vector.spec.move
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.spec.move

- enhanced the data invariants
- specified the post conditions of `push_back`, `pop_back`, `swap`, and `swap_remove`
- defined several helper functions, and simplified the spec using the helper functions
cargo test -p aptos-framework

[Spec] Added more spec to `big_vector`

---

developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-gcp.md
developer-docs-site/docusaurus.config.js
ecosystem/typescript/sdk/README.md
ecosystem/typescript/sdk/examples/README.md
terraform/aptos-node/gcp/README.md

Fixes some dead links and set up redirects in the case of referring domains.
Verify redirects are working by visiting urls in the `from:` path below `@docusaurus/plugin-client-redirects` inside `docusaurus.config.js`

[docs] Setup Redirects & Fix Dead Links

---

config/src/config/peer_monitoring_config.rs

This PR enables the peer monitoring client by default (in all networks, not just devnet).

[Config] Enable peer monitoring client by default.

---

aptos-move/aptos-vm-logging/src/lib.rs

Because I can't make 1 line change before landing correctly, and because I don't know how to use static / lazy

Fixes to speculative fix

---

Cargo.lock
crates/aptos-protos/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-cache-worker/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-data-service/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-file-store/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-fullnode/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-parser/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-post-processor/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-server-framework/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-utils/Cargo.toml
ecosystem/indexer-grpc/release_notes.md

* Release indexer grpc 1.0.0. 
`./scripts/rust_lint.sh` without warnings.

[indexer grpc] release indexer grpc 1.0.0

---

storage/aptosdb/src/backup/restore_handler.rs
storage/aptosdb/src/backup/restore_utils.rs
storage/aptosdb/src/db_debugger/common/mod.rs
storage/aptosdb/src/db_debugger/examine/print_db_versions.rs
storage/aptosdb/src/db_debugger/ledger/check_range_proof.rs
storage/aptosdb/src/db_debugger/ledger/check_txn_info_hashes.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/event_store/mod.rs
storage/aptosdb/src/event_store/test.rs
storage/aptosdb/src/ledger_db.rs
storage/aptosdb/src/ledger_store/ledger_info_test_utils.rs
storage/aptosdb/src/ledger_store/mod.rs
storage/aptosdb/src/ledger_store/transaction_info_test.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/event_store/test.rs
storage/aptosdb/src/pruner/ledger_pruner_manager.rs
storage/aptosdb/src/pruner/ledger_store/ledger_store_pruner.rs
storage/aptosdb/src/pruner/pruner_utils.rs
storage/aptosdb/src/pruner/state_store/test.rs
storage/aptosdb/src/pruner/transaction_store/test.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/aptosdb/src/test_helper.rs
storage/aptosdb/src/transaction_store/mod.rs
storage/aptosdb/src/transaction_store/test.rs
storage/aptosdb/src/utils/truncation_helper.rs
storage/db-tool/src/tests.rs

[Storage][Sharding] Use the new LedgerDb struct.

---

consensus/src/block_storage/block_store.rs

Current pipeline backpressure constants need to be tuned for different networks, based on average network latency (i.e. a test network with minimal latencies needs to have a different thresholds compared to mainnet with real-world latencies)
With this change, we exclude block_creation -> block_ordered part of the latency, and only use block_ordered -> block_committed as a pipeline latency, reducing the need for tuning backpressure constants across different networks.

Change consensus pipeline backpressure to exclude consensus ordering latency

---

config/src/config/gas_estimation_config.rs

[Gas Estimation] enable v2 by default

---

Cargo.lock
Cargo.toml
testsuite/forge-cli/Cargo.toml
testsuite/forge-cli/src/main.rs
testsuite/forge/src/backend/k8s/cluster_helper.rs
testsuite/forge/src/backend/k8s/mod.rs
testsuite/forge/src/backend/k8s/prometheus.rs
testsuite/forge/src/backend/k8s/stateful_set.rs
testsuite/forge/src/backend/k8s/swarm.rs

Make --namespace optional and give the default a somewhat easy to remember name
Test Plan: unittests

[forge] Automatically generate a useful namespace

---

storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/schemadb/src/lib.rs

[Logging] Add log when RocksDB is dropped.

---

.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml

Move failing test to unstable, until it is resolved/superseeded

---

developer-docs-site/docs/community/site-updates.md
developer-docs-site/docs/guides/system-integrators-guide.md
developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-gcp.md
developer-docs-site/docusaurus.config.js
developer-docs-site/src/components/MoveReference/index.tsx

[docs] fix more bad links

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] Bump version to 1.9.1

---

aptos-move/framework/aptos-framework/doc/fungible_asset.md
aptos-move/framework/aptos-framework/sources/fungible_asset.move

fix a typo in fungible_asset.move

---

developer-docs-site/src/components/MoveReference/index.tsx

[docs] fix unnecessary grouping that was breaking regex

---

developer-docs-site/docs/move/book/modules-and-scripts.md

Change code example move/book/modules-and-scripts.md to clarify that it is not a test module that contains automated tests but an code example
book/docs changes, I assume not tests needed

Change code example move/book/modules-and-scripts.md

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/CONTRIBUTING.md
ecosystem/typescript/sdk/LICENSE
ecosystem/typescript/sdk/README.md

Some SDK files were out of date and info was missing, this PR
- adds a LICENSE file
- improves the README file
- improves the CONTRIBUTING file
- removes redundant note from the CHANGELOG file

[TS SDK] SDK doc improvements

---

aptos-move/aptos-release-builder/data/release.yaml
types/src/on_chain_config/consensus_config.rs

Test Plan: need help testing this / CI

[release] Turn of qs for release v1.5

---

aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/sources/object.move

[docs] fix object.move can_delete comments

---

aptos-move/block-executor/src/counters.rs
aptos-move/block-executor/src/executor.rs

Minor changes to metrics and logs for better observability.

[BlockSTM] Adding metric and logs

---

aptos-move/aptos-vm/src/aptos_vm.rs

The previous logging was too relaxed and logged down errors that are not intended.
N/A

[aptos-vm] Change logging

---

aptos-move/aptos-vm/src/aptos_vm.rs

Cherrypick #8378 into production branch
NA

[aptos-vm] Do not log down storage error

---

ecosystem/typescript/sdk/README.md

[TS SDK] Fix missing links on readme file

---

terraform/aptos-node/aws/kubernetes.tf
terraform/aptos-node/gcp/kubernetes.tf
terraform/fullnode/aws/kubernetes.tf
terraform/fullnode/gcp/backup.tf
terraform/fullnode/gcp/kubernetes.tf
terraform/fullnode/gcp/variables.tf

New `enable_public_backup` similar to AWS pfn setup
also fix a typo

[tf/gcp][fullnode] option to open backup to public

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/providers/aptos_client.ts
ecosystem/typescript/sdk/src/providers/indexer.ts
ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts
ecosystem/typescript/sdk/src/utils/misc.ts

Adds `x-aptos-client` header to Indexer/Hasura requests
Tested request locally

[TS SDK] add `x-aptos-client` header to indexer queries

---

terraform/aptos-node/aws/kubernetes.tf
terraform/aptos-node/gcp/kubernetes.tf

Fix issues that look like this: https://github.com/aptos-labs/aptos-core/actions/runs/5093226162/jobs/9155578185?pr=8346
terraform-lint

[tf][aptos-node] fix formatting

---

crates/aptos/CHANGELOG.md
crates/aptos/src/common/types.rs
crates/aptos/src/common/utils.rs
crates/aptos/src/node/mod.rs
storage/db-tool/src/lib.rs

[Cli] add db restore to aptos cli

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

[CLI] bump CLI version to 1.0.14 for release

---

Cargo.lock
Cargo.toml
storage/aptosdb/src/db_options.rs

[storage] update to rocksdb 21.0 due to compilation issues

---

aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/sources/object.move

[docs] fix object.move comments

---

aptos-move/framework/aptos-framework/sources/object.spec.move
aptos-move/framework/aptos-stdlib/sources/copyable_any.spec.move

Fix specs on testnet branch to pass the compiler check

[Spec] Fix spec on testnet branch

---

aptos-move/framework/aptos-framework/sources/object.spec.move
aptos-move/framework/aptos-stdlib/sources/copyable_any.spec.move

Fix spec to pass compiler check

[Spec] Fix spec on mainnet branch

---

aptos-move/aptos-aggregator/src/aggregator_extension.rs
aptos-move/aptos-aggregator/src/transaction.rs
aptos-move/framework/aptos-framework/sources/aggregator/README.md

fix some typos in aggregator
N/A

fix some typos in aggregator

---

developer-docs-site/docs/standards/aptos-token-v2.md
developer-docs-site/docs/standards/index.md
developer-docs-site/sidebars.js

Initial pass at token v2 docs on the website

[docs] Add TokenV2 page for overview of tokenv2

---

testsuite/single_node_performance.py

Single node benchmak assert no error log lines

---

storage/storage-interface/src/async_proof_fetcher.rs

[Fix] Fix flaky test.

---

scripts/devnet_message.sh

Reported by community member @urkes#1518
Test plan: Click this link it works

[devnet] Fix devnet update message link

---

developer-docs-site/src/components/MoveReference/index.tsx

[docs] add aptos-stdlib to docs site refs

---

aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/sources/coin.move
aptos-move/framework/aptos-framework/sources/coin.spec.move

This PR uses spec variables to describe high-level properties related to the supply of the coin:
- all coin functions, except for burn, mint and initialize functions, should not change the total supply of coins in circulation. 
- the existing coins on chain is equal to the total supply of coins in circulation.

[Spec] Properties related to the supply of coins

---

storage/backup/backup-cli/src/coordinators/restore.rs

If the user doesn't specify a target version or specify a target version larger than the max backup txn version, it could trigger a bug to restore more ledger ending info than required. 
manual test the command

[storage] use a valid target version in db restore

---

aptos-move/aptos-vm/src/block_executor/mod.rs

When running move e2e tests, multiple concurrent execute_blocks might happen (due to multiple executors or otherwise), having their speculative logging inits and flushes may interfere with each other.
However, during the tests it's already ensured that speculative logging doesn't actually use speculation, but init and flush didn't require logging context and so weren't affected by that fix.
The current fix just avoids init and flush if we are in the Miscellaneous context, which is what's used by testing (other modes won't be affected).
Confirmed the e2e tests no longer fails locally with out of bounds errors on flush.

[VM] fix speculative flush error when running tests concurrently

---

crates/aptos/CHANGELOG.md

[CLI] update changelog for 2.0.0 release

---

aptos-move/framework/aptos-token/doc/token.md
aptos-move/framework/aptos-token/sources/token.move

update standard link

---

developer-docs-site/docs/guides/state-sync.md

This PR updates the state sync doc guide. Specifically, it:
1. Removes old and out-of-date text.
2. Updates the text recommendations to use the new DB restore tool.

[Dev Docs] Update state sync guide.

---

.github/workflows/replay-verify.yaml

Add a txn 148358668 to skip during mainnet replay.

[replay-tool] Add txn to skip

---

.github/workflows/docker-indexer-grpc-test.yaml

So it works for all branches, even if they haven't been rebased.
CI

[gha] use install-grpcurl from main

---

aptos-move/aptos-release-builder/src/components/consensus_config.rs
aptos-move/aptos-release-builder/src/components/execution_config.rs
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-release-builder/src/components/gas.rs
aptos-move/aptos-release-builder/src/components/transaction_fee.rs
aptos-move/aptos-release-builder/src/components/version.rs
aptos-move/aptos-release-builder/src/utils.rs
aptos-move/aptos-release-builder/src/validate.rs
aptos-move/framework/aptos-framework/doc/reconfiguration.md
aptos-move/framework/aptos-framework/sources/reconfiguration.move
aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move

Forcing reconfigruation after feature flag change.
framework release testing would suffice.

[features] Force reconfigruation after feature change

---

developer-docs-site/scripts/additional_dict.txt

[docs] add words to dictionary

---

crates/aptos/e2e/cases/init.py
crates/aptos/e2e/main.py

Reverts aptos-labs/aptos-core#8460 as this broke some tests on main that are blocking other changes from merging

Revert "[CLI] Add customer header checking to e2e"

---

aptos-move/aptos-vm/src/move_vm_ext/vm.rs
aptos-move/framework/move-stdlib/tests/bcs_tests.move
third_party/move/move-stdlib/nursery/tests/event_tests.move
third_party/move/move-stdlib/tests/bcs_tests.move
third_party/move/move-vm/runtime/src/config.rs
third_party/move/move-vm/runtime/src/interpreter.rs
third_party/move/move-vm/runtime/src/loader.rs
third_party/move/move-vm/transactional-tests/tests/recursion/runtime_layout_deeply_nested.exp
third_party/move/move-vm/transactional-tests/tests/recursion/runtime_layout_deeply_nested.mvir
third_party/move/move-vm/types/src/loaded_data/runtime_types.rs

This implements an improved value depth checker in the VM.

cherry-pick: improved value depth checks in the VM 

---

aptos-move/aptos-vm/src/move_vm_ext/vm.rs
aptos-move/framework/move-stdlib/tests/bcs_tests.move
third_party/move/move-stdlib/nursery/tests/event_tests.move
third_party/move/move-stdlib/tests/bcs_tests.move
third_party/move/move-vm/runtime/src/config.rs
third_party/move/move-vm/runtime/src/interpreter.rs
third_party/move/move-vm/runtime/src/loader.rs
third_party/move/move-vm/transactional-tests/tests/recursion/runtime_layout_deeply_nested.exp
third_party/move/move-vm/transactional-tests/tests/recursion/runtime_layout_deeply_nested.mvir
third_party/move/move-vm/types/src/loaded_data/runtime_types.rs

This implements an improved value depth checker in the VM.

cherry-pick: improved value depth checks in the VM

---

aptos-move/framework/aptos-framework/sources/object.spec.move
aptos-move/framework/aptos-stdlib/sources/copyable_any.spec.move

[Spec] fix spec on mainnet

---

aptos-move/aptos-gas/src/gas_meter.rs
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/move_vm_ext/resolver.rs
aptos-move/aptos-vm/src/move_vm_ext/session.rs
third_party/move/extensions/async/move-async-vm/tests/testsuite.rs
third_party/move/move-core/types/src/resolver.rs
third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
third_party/move/move-vm/runtime/src/data_cache.rs
third_party/move/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
third_party/move/move-vm/test-utils/src/storage.rs
third_party/move/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs

Refactor the code to return actual bytes read from storage to the gas metering. Use gas version feature to enable this when the next version is bumped.

Add accurate resource group gas metering

---

aptos-move/framework/aptos-stdlib/doc/simple_map.md
aptos-move/framework/aptos-stdlib/sources/simple_map.move
aptos-move/framework/aptos-stdlib/sources/simple_map.spec.move
aptos-move/framework/aptos-token/doc/property_map.md
aptos-move/framework/aptos-token/sources/property_map.move
aptos-move/framework/aptos-token/sources/property_map.spec.move

These functions are useful to have
Unit tests

Add functions to extract all keys and values from simple_map and (token v1's property_map)

---

aptos-move/aptos-gas/src/gas_meter.rs

[aptos-gas] fix typo

---

ecosystem/python/sdk/setup.py

It looks like version was mess up on Python. We have 0.6.2 but we did not publish it to pypi. Also `setup.py` has the old version which is still on `0.6.0`
Did a publish to pypi - https://pypi.org/project/aptos-sdk/
Also checked locally on skeleton project, and make sure simple-nft example works
```
(.venv) ➜  python /Users/jinhou/Projects/sdk-testing/python/.venv/bin/python /Users/jinhou/Projects/
sdk-testing/python/test_sdk.py
=== Addresses ===
Alice: 0xac69d22afe99a003a5dd2214391f74ed02e20a8e55bf6cfa0dc5df21db5eefcc
Bob: 0x3d9a4513fea9a30dab5fda03014ffaba51172af5a75938a0b062dd48a4add375
=== Initial Coin Balances ===
Alice: 100000000
Bob: 100000000
=== Creating Collection and Token ===
Alice's collection: {
"description": "Alice's simple collection",
"maximum": "18446744073709551615", …
```

[Python SDK] update version

---

.github/workflows/replay-verify.yaml
aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
aptos-move/aptos-vm/src/verifier/view_function.rs
aptos-move/e2e-move-tests/src/tests/constructor_args.data/pack/sources/args_test.move
aptos-move/e2e-move-tests/src/tests/constructor_args.rs

Cherry-pick the fix released in v1.4.4

[Cherry pick] fix for constructor

---

aptos-move/aptos-gas-profiling/src/profiler.rs
aptos-move/aptos-gas/src/gas_meter.rs
aptos-move/aptos-gas/src/transaction/storage.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/framework/src/natives/object.rs
third_party/move/extensions/async/move-async-vm/tests/testsuite.rs
third_party/move/move-core/types/src/resolver.rs
third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
third_party/move/move-vm/runtime/src/data_cache.rs
third_party/move/move-vm/runtime/src/interpreter.rs
third_party/move/move-vm/runtime/src/native_functions.rs
third_party/move/move-vm/runtime/src/session.rs
third_party/move/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
third_party/move/move-vm/test-utils/src/gas_schedule.rs
third_party/move/move-vm/test-utils/src/storage.rs
third_party/move/move-vm/types/src/gas.rs
third_party/move/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs

This implements proper (hopefully) gas metering for resource groups so that they charged in spite of the resource existing or not.

[gas] fix gas metering for resource groups

---

.github/workflows/build-node-binaries.yaml

Stop this workflow from running on all PRs
Test Plan: execute on PR, once landed shouldnt run on PR

[gha] Filter build node on pull request

---

aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
aptos-move/aptos-vm/src/verifier/view_function.rs
aptos-move/e2e-move-tests/src/tests/constructor_args.data/pack/sources/args_test.move
aptos-move/e2e-move-tests/src/tests/constructor_args.rs

Integrate fixes back into main branch

Integrate fixes into mainnet

---

.github/workflows/forge-stable.yaml
crates/transaction-emitter-lib/src/emitter/stats.rs
testsuite/forge-cli/src/main.rs
testsuite/forge/src/interface/network.rs
testsuite/forge/src/report.rs
testsuite/forge/src/success_criteria.rs
testsuite/testcases/src/compatibility_test.rs
testsuite/testcases/src/consensus_reliability_tests.rs
testsuite/testcases/src/framework_upgrade.rs
testsuite/testcases/src/fullnode_reboot_stress_test.rs
testsuite/testcases/src/lib.rs
testsuite/testcases/src/partial_nodes_down_test.rs
testsuite/testcases/src/quorum_store_onchain_enable_test.rs
testsuite/testcases/src/two_traffics_test.rs
testsuite/testcases/src/validator_join_leave_test.rs
testsuite/testcases/src/validator_reboot_stress_test.rs

real-world network land_blocking test to replace the old one

---

aptos-move/aptos-gas/src/gas_meter.rs
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/move_vm_ext/resolver.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/move_vm_ext/session.rs
third_party/move/extensions/async/move-async-vm/tests/testsuite.rs
third_party/move/move-core/types/src/resolver.rs
third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
third_party/move/move-vm/runtime/src/data_cache.rs
third_party/move/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
third_party/move/move-vm/test-utils/src/storage.rs
third_party/move/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs

* Add accurate resource group gas metering
* Add accurate resource group gas metering
* fix
* add test
* Correct feature version
* change trait signature
* Clear any resource cache after proloque
* bump gas feature
* add comment
* fix trigger condition for build jobs
* test loadtest
* add improvement
* Fix respawn session whatever that maybe
---------

[cherry-pick] Update gas metering (#8526)

---

crates/aptos/e2e/cases/move.py
crates/aptos/e2e/main.py
crates/aptos/e2e/move/common/hero/sources/hero.move
crates/aptos/e2e/move/devnet/hero/Move.toml
crates/aptos/e2e/move/devnet/hero/sources
crates/aptos/e2e/move/mainnet/hero/Move.toml
crates/aptos/e2e/move/mainnet/hero/sources
crates/aptos/e2e/move/testnet/hero/Move.toml
crates/aptos/e2e/move/testnet/hero/sources
crates/aptos/e2e/test_helpers.py

This PR adds a test to check that `aptos move publish` works.
In addition to the test itself I make a couple of framework and CI changes to make this actually work.
Tested locally:
```
DOCKER_DEFAULT_PLATFORM=linux/amd64 poetry run python main.py -d --base-network mainnet --test-cli-tag nightly
```
I tested in CI with `pull_request` instead of `pull_request_target` and it worked too.

[CLI][E2E] Add test for aptos move publish

---

aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
aptos-move/aptos-vm/src/verifier/view_function.rs
aptos-move/e2e-move-tests/src/tests/constructor_args.data/pack/sources/args_test.move
aptos-move/e2e-move-tests/src/tests/constructor_args.rs

[cherry-pick] fix for constructor

---

aptos-move/framework/move-stdlib/doc/vector.md
aptos-move/framework/move-stdlib/sources/vector.move
aptos-move/framework/move-stdlib/tests/vector_tests.move

This is a common operations for iterating over vector inputs.
New unit tests

Add zip functions in vector module to iterate over 2 vectors concurrently

---

.github/workflows/forge-stable.yaml
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/emitter/submission_worker.rs
testsuite/forge-cli/src/main.rs
testsuite/forge/src/report.rs
testsuite/forge/src/success_criteria.rs
testsuite/testcases/src/load_vs_perf_benchmark.rs
testsuite/testcases/src/state_sync_performance.rs
testsuite/testcases/src/two_traffics_test.rs

Add realistic_env_load_sweep forge test, to check latency across TPS

---

storage/aptosdb/src/backup/restore_utils.rs
storage/aptosdb/src/ledger_store/mod.rs
storage/aptosdb/src/ledger_store/transaction_info_test.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/transaction_store/test.rs
storage/aptosdb/src/test_helper.rs

Existing UTs, and manually tested on executor benchmark.

[Storage][Sharding] Split ledger commit into multiple batches.

---

.github/workflows/docker-build-test.yaml

to fix the error
```
[Invalid workflow file: .github/workflows/docker-build-test.yaml#L210](https://github.com/aptos-labs/aptos-core/actions/runs/5269776769/workflow)
error parsing called workflow
".github/workflows/docker-build-test.yaml"
-> "./.github/workflows/docker-indexer-grpc-test.yaml"
: failed to fetch workflow: workflow was not found.
```

[Cherry-pick][GHA] Pin main branch workflow for indexer workflow (#8653)

---

execution/executor/src/components/block_tree/mod.rs
execution/executor/src/components/block_tree/test.rs

helps with performance when blocks are large.
tests (fixed)

drop pruned blocks asynchronously

---

testsuite/forge-cli/src/main.rs
testsuite/forge/src/success_criteria.rs

and add expired/failed_submission to success criteria
based on
https://github.com/aptos-labs/aptos-core/actions/runs/5253448203/jobs/9490834445

Tune run-forge-realistic-env-load-sweep forge test

---

storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_store/state_store_test.rs

[CP][Fix] Return the correct version for state snapshot when the root is not committed.

---

aptos-move/aptos-vm/src/errors.rs

[cherry-pick][aptos-vm] Skip converting storage error

---

.github/workflows/replay-verify.yaml

replay-verify once per day

---

terraform/helm/testnet-addons/templates/loadtest.yaml
terraform/helm/testnet-addons/values.yaml

* change binary name
* add required command line parameters to chart values
Test live on Devnet.

[Helm] Fix loadtest cronjob

---

.github/workflows/forge-stable.yaml
crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-emitter-lib/src/emitter/submission_worker.rs
testsuite/forge-cli/src/main.rs

Add workload_mix and realistic_env_graceful_overload, and cleanup continuous forge test

---

aptos-move/aptos-release-builder/data/release.yaml

Test plan: is valid yaml :P
```
yq aptos-move/aptos-release-builder/data/release.yaml # return success
```

[release] Fix framework release description to v1.5.0

---

aptos-move/framework/aptos-stdlib/doc/simple_map.md
aptos-move/framework/aptos-stdlib/sources/simple_map.move
aptos-move/framework/aptos-stdlib/sources/simple_map.spec.move

Add an add_all function to simple_map
Unit tests

Add a new_from and add_all functions to simple_map

---

storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_store/state_store_test.rs

[Fix] Return the correct version for state snapshot when the root is not committed.

---

aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/gas_schedule.md
aptos-move/framework/aptos-framework/doc/voting.md
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
aptos-move/framework/aptos-framework/sources/voting.spec.move

To unblock PRs that fail on the prover test.

[Spec] disable spec in aptos_governance

---

ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs

Add unit tests for cache_operator
unit tests

Add unit tests for cache_operator

---

testsuite/forge-cli/src/main.rs

forge - increase memory limit for overload

---

developer-docs-site/docs/nodes/full-node/aptos-db-restore.md

[storage] update the restore doc

---

.github/workflows/docker-build-test.yaml

[CI] Update image version.

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/indexer/generated/operations.ts
ecosystem/typescript/sdk/src/indexer/generated/queries.ts
ecosystem/typescript/sdk/src/indexer/generated/types.ts
ecosystem/typescript/sdk/src/indexer/queries/getTokenData.graphql
ecosystem/typescript/sdk/src/plugins/aptos_token.ts
ecosystem/typescript/sdk/src/providers/indexer.ts
ecosystem/typescript/sdk/src/tests/e2e/aptos_token.test.ts
ecosystem/typescript/sdk/src/tests/e2e/fungible_asset_client.test.ts
ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts

This PR adds 
1. support `transfer` a fungible token.
2. `getTokenData` to support token v2 standard

[TS SDK] Support `transfer` fungible token

---

aptos-move/aptos-release-builder/data/release.yaml

[release.yaml] AIP-37 and AIP-26

---

developer-docs-site/docs/nodes/validator-node/operator/node-requirements.md

This PR updates the port instructions for validator operators. Specifically, it calls out the ports that need to be open publicly, privately, and closed entirely.

[Docs] Update port instructions for validator operators.

---

scripts/dev_setup.sh

Related: https://github.com/rust-lang/rustup/issues/3390
This PR adds a fallback to the `dev_setup.sh` script to allow it to handle `cargo nightly` installation failures. Specifically, if nightly fails to install, we'll fallback to a specific nightly build. Note: the fallback is a bit brittle in that it won't work for non-linux machines. But, given that the fallback is primarily to help unblock CI/CD in such situations, this is okay for the time being.
Once this lands (and we get feedback on the upstream issues), we can improve this.

[Dev setup] Better handle nightly rustup command failures.

---

aptos-move/aptos-release-builder/data/release.yaml

These leftover fields breaking release builder
Test Plan: yq release.yaml to make sure yaml is valid

[release] Remove the unused urls breaking release

---

aptos-move/move-examples/cli-e2e-tests/common/sources/cli_e2e_tests_script.move
crates/aptos/e2e/README.md
crates/aptos/e2e/cases/move.py
crates/aptos/e2e/main.py
crates/aptos/e2e/test_helpers.py

```
2023-06-22 16:28:56,301 - INFO - These tests passed:
2023-06-22 16:28:56,301 - INFO - test_metrics_accessible
2023-06-22 16:28:56,301 - INFO - test_init
2023-06-22 16:28:56,301 - INFO - test_account_fund_with_faucet
2023-06-22 16:28:56,301 - INFO - test_account_create
2023-06-22 16:28:56,302 - INFO - test_account_lookup_address
2023-06-22 16:28:56,302 - INFO - test_aptos_header_included
2023-06-22 16:28:56,302 - INFO - test_move_compile
2023-06-22 16:28:56,302 - INFO - test_move_compile_script
2023-06-22 16:28:56,302 - INFO - test_move_publish
2023-06-22 16:28:56,302 - INFO - All tests passed!
```

[CLI] Add CLI e2e for move compile command

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] Bump version to 1.11.0

---

developer-docs-site/docs/nodes/validator-node/operator/node-requirements.md

This PR offers some small tweaks to the recommended port settings in node documentation.

[Dev Docs] Small tweaks to recommended port settings.

---

aptos-move/move-examples/move-tutorial/README.md

Fixes all of the broken links in the Move tutorial

---

developer-docs-site/docs/tools/install-cli/install-move-prover.md

Add Move Prover setup instructions for Windows users

---

aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
aptos-move/framework/aptos-framework/sources/primary_fungible_store.move

add a couple of mint, transfer, freeze/unfreeze function to primary_store.
ut

[FA] add utility functions in primary_fungible_store

---

consensus/consensus-types/src/proof_of_store.rs
consensus/consensus-types/src/timeout_2chain.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/mod.rs
consensus/src/dag/reliable_broadcast.rs
consensus/src/dag/tests/reliable_broadcast_tests.rs
consensus/src/dag/types.rs
types/src/aggregate_signature.rs
types/src/ledger_info.rs
types/src/validator_verifier.rs

Skeleton of supporting fetching missing dependencies based on local dag information.

[dag] basic dag fetcher

---

terraform/fullnode/gcp/cluster.tf
terraform/helm/fullnode/templates/backup-compaction.yaml
terraform/helm/fullnode/values.yaml

locally test the command successfully finished
`aptos-db-tool backup-maintenance compact --state-snapshot-file-compact-factor 100 --transaction-file-compact-factor 100 --epoch-ending-file-compact-factor 100 --command-adapter-config ~/Downloads/s3-public.yaml
`

[storage] add cron job for backup compaction

---

.github/workflows/docker-build-test.yaml
.github/workflows/forge-stable.yaml
.github/workflows/forge-unstable.yaml

and remove some stale unstable tests

Update land_blocking => realistic_env_max_load on PR

---

crates/aptos/e2e/linter.sh

Added simple script for cli e2e test
```
➜  e2e git:(main) ✗ ./linter.sh       
Start linter.sh...
Running isort...
Configuration file exists at /Users/jinhou/Library/Preferences/pypoetry, reusing this directory.
Consider moving TOML configuration files to /Users/jinhou/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Fixing /Users/jinhou/Projects/aptos-core/crates/aptos/e2e/local_testnet.py
Fixing /Users/jinhou/Projects/aptos-core/crates/aptos/e2e/test_helpers.py
Fixing /Users/jinhou/Projects/aptos-core/crates/aptos/e2e/main.py
Running black...
Configuration file exists at /Users/jinhou/Library/Preferences/pypoetry, reusing this directory.
Consider moving TOML configuration files to /Users/jinhou/Library/Application …
```

[CLI] Add linter script for cli e2e

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/indexer/generated/queries.ts
ecosystem/typescript/sdk/src/indexer/queries/getTokenOwnersData.graphql

https://aptos-org.slack.com/archives/C041GRFLRL3/p1687823425097419

[TS SDK] Use amount greater than 0 in getTokenOwnersData query

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

[CLI] Update CLI version to 2.0.2

---

aptos-move/framework/aptos-stdlib/doc/comparator.md
aptos-move/framework/aptos-stdlib/doc/debug.md
aptos-move/framework/aptos-stdlib/doc/secp256k1.md
aptos-move/framework/aptos-stdlib/doc/smart_table.md
aptos-move/framework/aptos-stdlib/doc/string_utils.md
aptos-move/framework/aptos-stdlib/sources/comparator.spec.move
aptos-move/framework/aptos-stdlib/sources/cryptography/secp256k1.spec.move
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move
aptos-move/framework/aptos-stdlib/sources/debug.spec.move
aptos-move/framework/aptos-stdlib/sources/string_utils.spec.move

Added more specs to the following modules:
* comparator
* debug
* secp256k1
* string_utils
cargo test -p aptos-framework

[Spec] Specified the aptos_std modules

---

consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_handler.rs
consensus/src/dag/dag_network.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/mod.rs
consensus/src/dag/reliable_broadcast.rs
consensus/src/dag/tests/dag_test.rs
consensus/src/dag/tests/reliable_broadcast_tests.rs
consensus/src/dag/types.rs
consensus/src/network.rs

This PR adds the trait and structs for the receiver-side of the reliable broadcast. 
added unit tests

[dag] reliable broadcast receiver

---

storage/scratchpad/Cargo.toml

Jemalloc needs to be only built on Unix
CI

[deps] Ensure that everything builds on Windows

---

aptos-move/move-examples/tic-tac-toe/Move.toml
aptos-move/move-examples/tic-tac-toe/sources/TicTacToe.move

An example of tic tac toe written in Move. 
- All entry functions
- Valid winning states
- Invalid moves (i.e., taking a player twice, illegal moves, etc.)
Contract example is deployed to [devnet](https://explorer.aptoslabs.com/account/0x2b01c4d0b3d97ca229d8da5bdc675d0a8ce48655a7f68bfcecec49510e8ca1dd/modules/code/ttt?network=devnet)

[move-example] tic tac toe contract

---

aptos-move/framework/aptos-stdlib/doc/smart_table.md
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move

- Made the spec of `smart_table` intrinsic to unblock the spec work on the delegation pool module.
cargo test -p aptos-framework

[Spec] Made the spec of `smart_table` intrinsic

---

storage/aptosdb/src/state_store/mod.rs

recreate the PR using aptos-core. previous PR was created on a forked repo and consistently have issues with github action
Existing tests

[storage] remove unecessary plus 1

---

storage/aptosdb/src/pruner/ledger_pruner/transaction_pruner.rs

[Storage][Pruner][Fix] When catch up, the db version might be larger than the start version, do not check it.

---

aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/vm-genesis/src/lib.rs
types/src/on_chain_config/aptos_features.rs

Add `APTOS_UNIQUE_IDENTIFIERS` feature flag in a couple of places.

Add AUID feature flag

---

.gitignore
Cargo.lock
aptos-move/aptos-gas-profiling/Cargo.toml
aptos-move/aptos-gas-profiling/src/aggregate.rs
aptos-move/aptos-gas-profiling/src/erased.rs
aptos-move/aptos-gas-profiling/src/flamegraph.rs
aptos-move/aptos-gas-profiling/src/lib.rs
aptos-move/aptos-gas-profiling/src/log.rs
aptos-move/aptos-gas-profiling/src/misc.rs
aptos-move/aptos-gas-profiling/src/profiler.rs
aptos-move/aptos-gas-profiling/src/render.rs
aptos-move/aptos-gas-profiling/src/textualize.rs
aptos-move/e2e-move-tests/Cargo.toml
aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-move-tests/src/tests/gas.rs
aptos-move/e2e-tests/Cargo.toml
aptos-move/e2e-tests/src/executor.rs
crates/aptos/src/common/types.rs

Our gas profiler has been able to build up a detailed gas log and visualize it in the form of a flamegraph. However, there is still need for a text-based output format, especially when doing more sophisticated analysis. This PR gets such functionality implemented.
Additionally, it also makes gas profiling available in e2e move tests. You can now generate human-readable logs by running the gas test with the environment variable `PROFILE_GAS` set.  
```
env RUST_MIN_STACK=16777216 PROFILE_GAS=1 cargo test -p e2e-move-tests test_gas -- --nocapture
```
Here is an example output:
```
execution & IO (gas unit, full trace)                                            5.012     100.00%
intrinsic                                                                    1.5       29.93% …
```

[gas] add pretty texualization for transaction gas log and make gas profiling available in e2e move tests

---

storage/aptosdb/src/utils/iterators.rs

ContinuousVersionIter: print first_version in error log

---

storage/aptosdb/src/ledger_db.rs
storage/aptosdb/src/pruner/ledger_pruner/event_store_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/mod.rs
storage/aptosdb/src/pruner/ledger_pruner/transaction_accumulator_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/transaction_info_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/transaction_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/write_set_pruner.rs
storage/aptosdb/src/pruner/state_kv_pruner/mod.rs
storage/aptosdb/src/pruner/state_kv_pruner/state_kv_shard_pruner.rs
storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs
storage/aptosdb/src/pruner/state_merkle_pruner/state_merkle_shard_pruner.rs

[Storage][Pruner] Write pruner progress for all sub pruners, and add more logs.

---

developer-docs-site/docs/move/move-on-aptos/modules-on-aptos.md

Add missing details regarding init_module and emphasize that it's only executed during the initial deployment

---

developer-docs-site/docs/guides/nfts/mint-onchain-data.md

Fix the CLI examples in the docs to use new args format
doc change

[docs] Fix the docs to use new args format

---

developer-docs-site/docs/standards/fungible-asset.md

[fa_doc] explain sedonary store and ownership

---

aptos-move/move-examples/mint_nft/README.md

Update (Mint an NFT with Aptos CLI) URL link in  README.md

---

aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-stdlib/doc/simple_map.md
aptos-move/framework/aptos-stdlib/sources/simple_map.move
third_party/move/move-vm/types/src/loaded_data/runtime_types.rs

Just fix the simple map's document typo
Documents change

[framework] fix simple map document typo

---

ecosystem/typescript/sdk/src/tests/e2e/aptos_client.test.ts

[ts-sdk] disable broken resource account test

---

Cargo.lock
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/metrics.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/processor.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
ecosystem/indexer-grpc/indexer-grpc-post-processor/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-post-processor/README.md
ecosystem/indexer-grpc/indexer-grpc-post-processor/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-post-processor/src/metrics.rs
ecosystem/indexer-grpc/indexer-grpc-post-processor/src/pfn_ledger_checker.rs

* Add PFN checker, this checks the latest indexer grpc entries with PFN timestamp.
* Use Redis ConnectionManager to retry in case redis connection is broken(i.e., maintenance) 
* Locally tested, looks good

[indexer grpc] improve the pfn checker and redis connection retry.

---

consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/types.rs

[dag] update dag fetcher to construct request inside

---

Cargo.lock
Cargo.toml
consensus/Cargo.toml
consensus/src/dag/types.rs
crates/aptos-enum-conversion-derive/Cargo.toml
crates/aptos-enum-conversion-derive/src/lib.rs
crates/aptos-enum-conversion-derive/tests/cases/multiple_fields.rs
crates/aptos-enum-conversion-derive/tests/cases/multiple_fields.stderr
crates/aptos-enum-conversion-derive/tests/cases/no_fields.rs
crates/aptos-enum-conversion-derive/tests/cases/no_fields.stderr
crates/aptos-enum-conversion-derive/tests/conversion_tests.rs

This PR adds a derive macro that implements `From` traits for converting structs in enum to enum variants and vice-versa.

[dag] derive macro for enum variant conversions 

---

crates/aptos/src/common/types.rs
sdk/src/types.rs

Update submit_transaction to allow signing txn with ledger profile
Note: This will be merging into feature branch [feature_branch/cli_ledger_integration](https://github.com/aptos-labs/aptos-core/tree/feature_branch/cli_ledger_integration)
Manual test
1. `aptos init --ledger` to init a ledger profile
2. `aptos move publish` to publish a module with your ledger profile
```
➜  hello_blockchain git:(jin/sign_with_hardware_wallet) ✗ aptos-debug move publish --profile=pledger --named-addresses hello_blockchain=pledger
BUILDING Examples
package size 1755 bytes
Do you want to submit a transaction for a range of [39400 - 59100] …
```

[CLI][1/n] Sign txn with ledger

---

consensus/src/consensusdb/consensusdb_test.rs
consensus/src/consensusdb/mod.rs
consensus/src/consensusdb/schema/block/mod.rs
consensus/src/consensusdb/schema/dag/mod.rs
consensus/src/consensusdb/schema/mod.rs
consensus/src/consensusdb/schema/quorum_certificate/mod.rs
consensus/src/consensusdb/schema/single_entry/mod.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/mod.rs
consensus/src/dag/storage.rs
consensus/src/dag/tests/dag_test.rs
consensus/src/dag/tests/reliable_broadcast_tests.rs
consensus/src/dag/types.rs

- Add node/certified node to consensus db
- Plug in basic storage into dag_store

[dag] add persisted storage

---

consensus/src/quorum_store/counters.rs

Having buckets that match well with the data allows us to have accurate histogram_quantile in grafana.
Run forge, observe the charts make sense.

[Quorum Store] metrics: give proper buckets for histogram

---

crates/aptos/CHANGELOG.md

Notice I update the date instead of new one, because that one was never released on 6/27

[CLI] release 2.0.2

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] Bump to version 1.13.1

---

aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/aptos-vm/src/sharded_block_executor/cross_shard_client.rs
aptos-move/aptos-vm/src/sharded_block_executor/tests.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/txn_commit_hook.rs

Fix the issue of cross shard client panicking when we use 1 concurrency per shard. 
Added tests

Fix sharded execution for concurrency 1

---

aptos-move/framework/aptos-framework/doc/account.md
aptos-move/framework/aptos-framework/doc/aptos_account.md
aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/block.md
aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/doc/event.md
aptos-move/framework/aptos-framework/doc/guid.md
aptos-move/framework/aptos-framework/doc/reconfiguration.md
aptos-move/framework/aptos-framework/doc/state_storage.md
aptos-move/framework/aptos-framework/doc/voting.md
aptos-move/framework/aptos-framework/sources/account.spec.move
aptos-move/framework/aptos-framework/sources/aptos_account.spec.move
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/block.spec.move
aptos-move/framework/aptos-framework/sources/coin.spec.move
aptos-move/framework/aptos-framework/sources/event.spec.move
aptos-move/framework/aptos-framework/sources/guid.spec.move
aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move
aptos-move/framework/aptos-framework/sources/state_storage.spec.move
aptos-move/framework/aptos-framework/sources/voting.spec.move

This PR adds some specs in the high-level requirements docs.

[Spec] Add high-level specs

---

consensus/src/dag/dag_handler.rs
consensus/src/dag/types.rs
consensus/src/epoch_manager.rs
consensus/src/network.rs

This PR adds the peer and author checks for the DAG message on the receiver side.

[dag] message author and epoch checks on receiver side

---

aptos-move/move-examples/marketplace/sources/coin_listing.move
aptos-move/move-examples/marketplace/sources/listing.move

If the closer of a marketplace listing is the recipient, we already have their signer, so we can direct deposit it into their account. This is purely an optimization, since it is entirely possible for other entities to close, for example, in auctions.

[marketplace] short-circuit closer is recipient for tokenv1

---

third_party/move/move-compiler/tests/move_check/typing/break_constant.exp
third_party/move/move-compiler/tests/move_check/typing/break_constant.move

Add a compiler test case for buggy code const C = break;
Ran the test, see the error is caught.

add compiler tests for const = break

---

.github/workflows/forge-specialized.yaml

This PR fixes the indentation in the specialized forge jobs GHA file. Only noticed this on the most recent job run failure 🤦 
Manual YAML verification.

[Forge] (Trivial) Fix indentation in specialized forge jobs file.

---

aptos-move/aptos-release-builder/data/release.yaml

Add fee payer enable to the release.yaml.  Also update a incorrect copied description on charge invariant violation feature.

Add fee payer to release

---

ecosystem/typescript/sdk/src/tests/unit/builder_utils.test.ts

tests are failing in CI https://aptos-org.slack.com/archives/C03PKBQM2RY/p1689098051000379
This was first introduced as part of this PR https://github.com/aptos-labs/aptos-core/pull/8907 but then was removed on this commit https://github.com/aptos-labs/aptos-core/pull/8907/commits/6dc811525404bcc5b4b537ad61d37ce0a14e65b8 but the test wasn't removed

remove unneeded test

---

.github/workflows/workflow-run-replay-verify.yaml
testsuite/replay_verify.py

Split the replay verify into multiple jobs so it can finish faster
https://github.com/aptos-labs/aptos-core/actions/runs/5491816459/jobs/10008745766

[storage] split the replay_verify to multiple jobs

---

aptos-move/aptos-release-builder/data/release.yaml

Cherry-pick the release.yaml to enable the fee payer into release v1.6.
Also at runtian request remove the already released charge_invariant_violation feature section

Gerben cherry

---

aptos-move/move-examples/fungible_asset/README.md
aptos-move/move-examples/fungible_asset/fa_coin/Move.toml
aptos-move/move-examples/fungible_asset/fa_coin/sources/FACoin.move
aptos-move/move-examples/tests/move_unit_tests.rs
developer-docs-site/docs/tutorials/first-fungible-asset.md
developer-docs-site/docs/tutorials/index.md
developer-docs-site/scripts/additional_dict.txt
developer-docs-site/sidebars.js
ecosystem/typescript/sdk/examples/typescript/package.json
ecosystem/typescript/sdk/examples/typescript/pnpm-lock.yaml
ecosystem/typescript/sdk/examples/typescript/your_coin.ts
ecosystem/typescript/sdk/examples/typescript/your_fungible_asset.ts

similar to your first coin. but with FA.
pnpm start

[tutorial] your first fungible asset

---

aptos-move/aptos-release-builder/data/release.yaml

Turn on the on-chain config for block gas limit.

[BlockSTM] update release.yaml

---

aptos-move/framework/aptos-framework/doc/resource_account.md
aptos-move/framework/aptos-framework/sources/resource_account.spec.move

High-level spec for the resource account module

[Spec] high-level spec for resource account

---

aptos-move/move-examples/fungible_asset/fa_coin/sources/FACoin.move
developer-docs-site/docs/tutorials/first-fungible-asset.md

[first_fa] fix typos not addressed in #8830

---

aptos-move/aptos-release-builder/data/release.yaml

Change release.yaml file to enable AUIDs feature flag

Enable AUIDs feature flag

---

third_party/README.md
third_party/copy.bara.sky

Discovered while working on [upstream sync PR](https://github.com/move-language/move/pull/1066)

[copy-bara] Fixing mispellings

---

crates/aptos-telemetry-service/src/prometheus_push_metrics.rs

This PR adds logging additional errors in metrics ingestion route in telemetry service. Also, fixes a metric label bug.

[telemetry-svc] additional logging metrics ingest errors

---

aptos-move/aptos-release-builder/data/release.yaml

Enable AUIDs feature flag in Aptos release v1.6.

Enable AUIDs flag

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts
ecosystem/typescript/sdk/yarn.lock

I missed the changelog in my last TS SDK change

[ts-sdk] Release 1.13.2

---

aptos-move/aptos-release-builder/data/release.yaml

Turn on the on chain config for enabling block gas limit, with limit 35000.

[Cherrypick] Update release.yaml

---

.github/workflows/execution-performance.yaml

To help catch regressions
Test Plan: actionlint / PR

[gha] Run single node perf every four hours

---

.github/workflows/ts-sdk-e2e-tests.yaml

https://aptos-org.slack.com/archives/C03PKBQM2RY/p1689100392827799?thread_ts=1689098051.000379&cid=C03PKBQM2RY

[TS SDK ] Run CI tests against the current code version

---

api/src/log.rs
api/src/metrics.rs

Seeing the size of POST body will help debug API performance.
Run e2e test, view in grafana.

[api] log POST sizes

---

crates/transaction-emitter-lib/src/wrappers.rs
crates/transaction-generator-lib/src/args.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/main.rs
testsuite/single_node_performance.py

add workload mix to executor benchmark/regression tests

---

aptos-move/framework/move-stdlib/doc/vector.md
aptos-move/framework/move-stdlib/sources/vector.move
aptos-move/framework/move-stdlib/tests/vector_tests.move

vector::find as a more useful generic version of vector::index_of
Unit tests

Add a vector::find function that returns index of element matching a predicate

---

crates/indexer/migrations/2023-07-06-042159_minor_optimizations/down.sql
crates/indexer/migrations/2023-07-06-042159_minor_optimizations/up.sql
crates/indexer/src/models/coin_models/v2_fungible_asset_utils.rs
crates/indexer/src/models/token_models/v2_collections.rs
crates/indexer/src/models/token_models/v2_token_activities.rs
crates/indexer/src/models/token_models/v2_token_datas.rs
crates/indexer/src/models/token_models/v2_token_utils.rs
crates/indexer/src/processors/token_processor.rs
crates/indexer/src/schema.rs
ecosystem/indexer-grpc/indexer-grpc-parser/README.md
ecosystem/indexer-grpc/indexer-grpc-parser/migrations/2023-07-06-042159_minor_optimizations/down.sql
ecosystem/indexer-grpc/indexer-grpc-parser/migrations/2023-07-06-042159_minor_optimizations/up.sql
ecosystem/indexer-grpc/indexer-grpc-parser/parser.yaml
ecosystem/indexer-grpc/indexer-grpc-parser/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/models/coin_models/v2_fungible_asset_utils.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/v2_collections.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/v2_token_activities.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/v2_token_datas.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/models/token_models/v2_token_utils.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/processors/token_processor.rs
ecosystem/indexer-grpc/indexer-grpc-parser/src/worker.rs
storage/indexer/src/lib.rs

Add fungible token activities when fungible token is deposit / withdrawn

Fungible token activities

---

aptos-move/move-examples/marketplace/sources/coin_listing.move
aptos-move/move-examples/marketplace/sources/collection_offer.move
aptos-move/move-examples/marketplace/sources/events.move
aptos-move/move-examples/marketplace/sources/test_utils.move
aptos-move/move-examples/marketplace/sources/token_offer.move

Adds token offers to the marketplace
Unit tests, and soon manual testing

[move-examples] Add token offers to marketplace example

---

testsuite/single_node_performance.py

Recalibrate single node perf constants

---

aptos-move/framework/aptos-framework/doc/account.md
aptos-move/framework/aptos-framework/doc/aggregator.md
aptos-move/framework/aptos-framework/doc/aptos_account.md
aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/event.md
aptos-move/framework/aptos-framework/doc/optional_aggregator.md
aptos-move/framework/aptos-framework/doc/reconfiguration.md
aptos-move/framework/aptos-framework/doc/storage_gas.md
aptos-move/framework/aptos-framework/doc/transaction_validation.md
aptos-move/framework/aptos-framework/sources/account.spec.move
aptos-move/framework/aptos-framework/sources/aggregator/aggregator.spec.move
aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.spec.move
aptos-move/framework/aptos-framework/sources/aptos_account.spec.move
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/event.spec.move
aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move
aptos-move/framework/aptos-framework/sources/storage_gas.spec.move
aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move

This PR adds more high-level specs and fixes some existing spec issues.

[Spec] Add more high-level specs

---

aptos-move/framework/aptos-framework/doc/staking_config.md
aptos-move/framework/aptos-framework/sources/configs/staking_config.move

minor refactor: simplify staking_config::get_reward_rate

---

third_party/move/move-prover/tests/sources/functional/verify_vector.move

- Added test cases for the loop unrolling feature using the vector standard.
cargo test -p move-prover

[Prover] tested the loop unrolling feature using the basic vector operations

---

aptos-move/framework/aptos-framework/doc/stake.md
aptos-move/framework/aptos-framework/sources/stake.move

fix typo in stake.move comments

---

.github/workflows/forge-pfn.yaml
.github/workflows/forge-state-sync.yaml

This PR fixes the forge schedule checks in the forge jobs to match the cron schedule (in the same file).

[Forge] (Trivial) Fix schedule check in job.

---

crates/indexer/src/models/stake_models/delegator_balances.rs
crates/indexer/src/models/token_models/collection_datas.rs
crates/indexer/src/models/token_models/v2_collections.rs
crates/indexer/src/models/token_models/v2_token_activities.rs
crates/indexer/src/models/token_models/v2_token_datas.rs
crates/indexer/src/models/token_models/v2_token_ownerships.rs

If data is not backfilled and we expect it to be, we'll still return but log error instead of panic.

[Indexer] Avoid panic if data is not backfilled

---

testsuite/forge-cli/src/main.rs

We reduced the number of nodes recently, which has caused the CPU to increase by 1-2 cores.
Run Forge

[Forge] Tune cpu metrics threshold criteria for realistic_env_max_load_test

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/providers/provider.ts
ecosystem/typescript/sdk/src/utils/api-endpoints.ts

Reverts aptos-labs/aptos-core#8850

Revert "[ts-sdk] Allow local endpoint provider"

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

Releases 1.13.3 with support for Object<Type> and null in Options

[ts-sdk] Release 1.13.3

---

consensus/src/dag/anchor_election.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/storage.rs
consensus/src/dag/tests/mod.rs
consensus/src/dag/tests/order_rule_tests.rs

Add a simple proptest for the order rule

[dag] add tests for order rule

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] bump version 1.14.0

---

config/src/config/state_sync_config.rs
state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
state-sync/state-sync-v2/state-sync-driver/src/utils.rs

This PR enables "intelligent" syncing mode for all nodes (by default). Intelligent syncing mode executes transactions or applies outputs, depending on whichever is cheaper (per chunk).

[State Sync] Enable intelligent syncing mode.

---

aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.move

first pr on aggregators_v2 branch - initial implementation of aggregator_v2/aggregator.move file (without rust code behind it). review the full file, I accidentally added part of it to branch before the PR :)

aggregator_v2/aggregator.move

---

api/src/tests/objects.rs
aptos-move/e2e-move-tests/src/tests/token_objects.rs
aptos-move/move-examples/swap/Move.toml
aptos-move/move-examples/tests/move_unit_tests.rs
aptos-move/move-examples/token_objects/ambassador/Move.toml
aptos-move/move-examples/token_objects/ambassador/sources/ambassador.move
aptos-move/move-examples/token_objects/hero/Move.toml
aptos-move/move-examples/token_objects/hero/sources/hero.move
aptos-move/move-examples/token_objects/knight/Move.toml
aptos-move/move-examples/token_objects/knight/sources/food.move
aptos-move/move-examples/token_objects/knight/sources/knight.move
aptos-move/move-examples/token_objects/token_lockup/Move.toml
aptos-move/move-examples/token_objects/token_lockup/sources/token_lockup.move
aptos-move/move-examples/token_objects/token_lockup/sources/unit_tests.move

Current code self-transfers if the creator is also the recipient which is unnecessary. Also fix some other nits (import ordering, etc.)
Unit tests

[Move examples] Ensure no self transfer in knight token module.

---

aptos-move/framework/cached-packages/src/lib.rs

Puts windows in line with the unix changes

[cached-packages] Fix windows use of framework bundle

---

developer-docs-site/docs/tools/aptos-cli/use-cli/use-aptos-ledger.md
developer-docs-site/sidebars.js

This adds the doc for how to use CLI-Ledger
NOTE: this is merging into feature branch

[CLI] add cli ledger doc

---

.github/actions/fullnode-sync/action.yaml
.github/actions/fullnode-sync/fullnode_sync.py
.github/workflows/fullnode-execute-devnet-main.yaml
.github/workflows/fullnode-execute-devnet-stable.yaml
.github/workflows/fullnode-fast-mainnet-stable.yaml
.github/workflows/fullnode-fast-testnet-main.yaml
.github/workflows/fullnode-fast-testnet-stable.yaml
.github/workflows/fullnode-intelligent-devnet-main.yaml
.github/workflows/fullnode-intelligent-mainnet-main.yaml
.github/workflows/fullnode-intelligent-mainnet-stable.yaml
.github/workflows/fullnode-intelligent-testnet-main.yaml
.github/workflows/run-fullnode-sync.yaml

This PR:
1. Adds three new fullnode sync jobs to test the "intelligent" syncing mode. Specifically, we test: (i) syncing on `mainnet` from the `main` branch; (ii) syncing on `mainnet` from the `mainnet` branch; and (iii) syncing on `testnet` from the `main` branch.
2. Add a metric dump to the end of the job, so that we can inspect the metrics after each run.
3. Reduce (and stagger) the job frequencies so that jobs run once a day, at different times.

[Fullnode GHA] Add daily jobs to test intelligent syncing mode.

---

aptos-move/aptos-aggregator/src/aggregator_extension.rs
aptos-move/aptos-debugger/src/lib.rs
aptos-move/aptos-vm/src/adapter_common.rs
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/move_vm_ext/vm.rs
aptos-move/aptos-vm/src/natives.rs
aptos-move/e2e-tests/src/executor.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator.rs
aptos-move/framework/src/natives/aggregator_natives/context.rs
aptos-move/vm-genesis/src/lib.rs
aptos-move/writeset-transaction-generator/src/writeset_builder.rs

Remove `aggregator_enabled` flag.

Remove aggregator_enabled flag

---

Cargo.lock
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs

* add chunking to grpc to avoid large response is rejected by the client.

add chunking to grpc to avoid large response is rejected by the client.

---

.github/workflows/workflow-run-replay-verify.yaml

increase runner of runner to speed up replay-verify
existing tests

Use 8 runners for replay-verify

---

Cargo.lock
consensus/Cargo.toml
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_network.rs
consensus/src/dag/reliable_broadcast.rs
consensus/src/dag/tests/dag_network_test.rs
consensus/src/dag/tests/mod.rs
consensus/src/dag/tests/reliable_broadcast_tests.rs

This PR implements the `send_rpc_with_fallback`.

[dag] rpc with fallback implementation

---

consensus/src/consensusdb/consensusdb_test.rs
consensus/src/consensusdb/mod.rs
consensus/src/consensusdb/schema/block/mod.rs
consensus/src/consensusdb/schema/dag/mod.rs
consensus/src/consensusdb/schema/mod.rs
consensus/src/consensusdb/schema/quorum_certificate/mod.rs
consensus/src/consensusdb/schema/single_entry/mod.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/storage.rs
consensus/src/dag/tests/dag_test.rs
consensus/src/dag/tests/order_rule_tests.rs
consensus/src/dag/tests/reliable_broadcast_tests.rs
consensus/src/dag/types.rs
consensus/src/experimental/buffer_item.rs
consensus/src/pending_votes.rs
consensus/src/quorum_store/proof_coordinator.rs
types/src/ledger_info.rs
types/src/validator_verifier.rs

[dag] persist ordered anchor for recovery

---

ecosystem/typescript/sdk/src/plugins/aptos_token.ts
ecosystem/typescript/sdk/src/tests/e2e/aptos_token.test.ts

[TS SDK] Set default denominator to 1

---

storage/backup/backup-cli/src/coordinators/backup.rs
storage/backup/backup-cli/src/metadata/view.rs
storage/backup/backup-cli/src/metrics/backup.rs

add monitoring on the latest compacted metadata version 
Existing test

[storage] Monitor the latest compacted version

---

crates/aptos/src/common/utils.rs
crates/aptos/src/governance/delegation_pool.rs
crates/aptos/src/governance/mod.rs
crates/aptos/src/governance/utils.rs
crates/aptos/src/test/mod.rs
crates/aptos/src/test/tests.rs

Add partial governance voting support for CLI. Behaviors are different only when `PARTIAL_GOVERNANCE_VOTING` or `DELEGATION_POOL_PARTIAL_GOVERNANCE_VOTING` feature flags are enabled.
- After `PARTIAL_GOVERNANCE_VOTING` is enabled, `aptos governance vote` can specify voting power. If not specified, use all the voting power.
- Add `aptos governance delegation-pool vote` and `aptos governance delegation-pool propose` for delegation pool stakers to vote/propose.
Tested on devnet.
The followings are commands to test `aptos governance delegation-pool vote` and `aptos governance delegation-pool propose`.
```
./aptos move run --function-id "0x1::aptos_account::transfer" --sender-account 0xa550c18 --args address:f3bf84e77cc26ced9bad5ce4b98bd0db21bb8388cd272326a7e9e65cd8518ae7 u64:100100000000000 …
```

Partial governance voting support for CLI

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] Bump version to 1.15.0

---

aptos-move/framework/move-stdlib/src/natives/bcs.rs
aptos-move/framework/src/natives/string_utils.rs
aptos-move/framework/src/natives/util.rs
aptos-move/framework/table-natives/src/lib.rs
third_party/move/extensions/move-table-extension/src/lib.rs
third_party/move/move-stdlib/src/natives/bcs.rs
third_party/move/move-stdlib/src/natives/debug.rs
third_party/move/move-vm/runtime/src/native_functions.rs

None is unnecessary and I will run replay test.
replay test and unit test

[move] kill the option in return type of type-to-layout conversion

---

ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Functionality for writing to GCS and handle errors for Postgres commits
Fixes EI-261

[NFT Metadata Crawler] GCS Write + Postgres Commit

---

aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs

fixing some gas costs that were missing the MUL = 20 multiplier

---

ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs

Logic for image optimizer module
Fixes EI-252

[NFT Metadata Crawler] Image Optimizer

---

ecosystem/nft-metadata-crawler-parser/src/utils/json_parser.rs

Logic for JSON parser implementation
Fixes EI-251

[NFT Metadata Crawler] JSON Parser

---

ecosystem/nft-metadata-crawler-parser/src/utils/uri_parser.rs

Logic for URI Parser implementation
Fixes EI-250

[NFT Metadata Crawler] URI Parser

---

ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs
ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs
ecosystem/nft-metadata-crawler-parser/src/utils/json_parser.rs
ecosystem/nft-metadata-crawler-parser/src/utils/mod.rs
ecosystem/nft-metadata-crawler-parser/src/utils/uri_parser.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Set up metadata flow (no logic besides deduplication) according to [design](https://docs.google.com/document/d/1GqRkdB0GAHYDqzmDb5Vl1Ze2aU47IIOo9d4kNQe3xxY/edit#heading=h.ai67ew5z8d1x)
Fixes EI-262

[NFT Metadata Crawler] Parser Flow

---

ecosystem/nft-metadata-crawler-parser/src/worker.rs

Integrate flow for subscribing to PubSub and parallelizing the handling of parsers
Fixes EI-263

[NFT Metadata Crawler] Parser PubSub gRPC Parallelization

---

aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move

This PR solves the timeout issue in the daily prover test being run on CI

[Spec] Fix spec for the CI

---

aptos-move/aptos-gas/src/aptos_framework.rs

cherrypick fix missing MULs in gas costs of cryptographic hash functions

---

consensus/src/epoch_manager.rs
types/src/on_chain_config/execution_config.rs

Commands (applied cleanly):
```
git revert f313b5be43d6918a5456e738d8c7f67c7e9160fa
git cherry-pick 66fe8cf56c3b1cd0f869c0160bbd42a8c93c163d
```

[Cherry pick] cherry-pick execution_config changes into v1.6 (#8459 #9391)

---

ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs
ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs
ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs
ecosystem/nft-metadata-crawler-parser/src/utils/json_parser.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Utilizes additional config field to configurably set the JPEG quality 
Fixes EI-270

[NFT Metadata Crawler] Add configurable image quality for optimizer

---

Cargo.lock
consensus/Cargo.toml
consensus/src/dag/dag_driver.rs
crates/reliable-broadcast/Cargo.toml
crates/reliable-broadcast/src/lib.rs
crates/reliable-broadcast/src/tests.rs

This PR adds backoff ability for RPC calls made for RB broadcast calls. 
Existing unit tests modified

[rb] Support for backoff based retry

---

aptos-move/framework/aptos-framework/sources/account.move
aptos-move/framework/aptos-framework/sources/event.move
aptos-move/framework/src/natives/event.rs

change the name and implementation of this test only function.
ut

refactor emitted_events to emitted_events_by_handle

---

ecosystem/nft-metadata-crawler-parser/src/utils/uri_parser.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Added unit tests for the URI Parser.
Also changed how the URI Parser accesses the prefix for the dedicated gateway and removed extraneous code for initializing the worker struct. 
Unit tests included
Fixes EI-273

[NFT Metadata Parser] URI Parser unit tests

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

Release v1.16.0
- Export all remaining types and functions in TS SDK
- Add improvements for `IndexerClient`
- Export indexer types - `export * from "/indexer/generated/types"`
- Support for token v2 activities - `getTokenActivities`, response structure has changed
- Aggregate query suports token v2 activities - `getTokenActivitiesCount`
- Support for sorting indexer queries - `orderBy` optional argument in `extraArgs` arguments
- Support for get owned tokens by token address or token data id - `getOwnedTokensByTokenData`
- Add support for local/custom networks without an indexer client

[TS SDK] bump version to 1.16.0

---

config/src/config/state_sync_config.rs

This PR increases the data prefetcher configuration value from 6 to 12 data chunks. This makes the PFNs match that of the validators and VFNs.

[Data Streaming Service] Increase data prefetcher for PFNs.

---

ecosystem/nft-metadata-crawler-parser/src/worker.rs

Add prefix to CDN that was previous left out
Tested locally

[NFT Metadata Crawler] Add CDN Prefix to CDN JSON/URI

---

Cargo.lock
Cargo.toml
ecosystem/nft-metadata-crawler-parser/Cargo.toml
ecosystem/nft-metadata-crawler-parser/src/main.rs

Rename crate from `nft-metadata-crawler-parser` to `aptos-nft-metadata-crawler-parser`

[NFT Metadata Crawler] Rename crate

---

aptos-move/framework/aptos-stdlib/doc/simple_map.md
aptos-move/framework/aptos-stdlib/doc/smart_table.md
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move
aptos-move/framework/aptos-stdlib/sources/simple_map.move

as title
to_simple_map would be used for view functions mostly to get a snapshot of this table.
Not supposed to be called for a large table.
ut

[smart_table] add add_all, to_simple_map

---

aptos-move/aptos-vm/src/sharded_block_executor/counters.rs
aptos-move/aptos-vm/src/sharded_block_executor/cross_shard_state_view.rs
aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs

[Sharding] Add some performance counters for sharded execution

---

crates/aptos-rest-client/src/faucet.rs

add authorization to faucet client

---

crates/aptos/CHANGELOG.md

update cli release 2.0.3 date

---

config/src/config/state_sync_config.rs

- This reverts commit 0f07a3083a271412544c35f30b808ca91e8ff7af.
- This PR was created using: `git revert 0f07a3083a271412544c35f30b808ca91e8ff7af `
The network stack is yet to handle the increased aggression and some test PFNs (with weak links) are seeing health check failures due to bandwidth saturation.

Revert "[Data Streaming Service] Increase data prefetcher for PFNs."

---

ecosystem/nft-metadata-crawler-parser/src/worker.rs

Only send ACK to PubSub if release flag is set
Tested locally; looks good
Fixes EI-284

[NFT Metadata Crawler] Default to no ACK after parsing

---

developer-docs-site/docs/concepts/base-gas.md

taken numbers from today transaction.rs and storage_gas.md

gas-schedule numbers updates.md

---

developer-docs-site/docs/concepts/base-gas.md

changed folder
not sure where EXECUTION_GAS_MULTIPLIER parameter is located now, that link doesn't work as well

gas-schedule folder changing.md

---

aptos-move/framework/aptos-token-objects/doc/aptos_token.md
aptos-move/framework/aptos-token-objects/sources/aptos_token.move
aptos-move/move-examples/marketplace/sources/collection_offer.move
aptos-move/move-examples/marketplace/sources/test_utils.move

Function probably needs a better name, but the long needed non-entry version of mint.
See move tests

[framework] Add Aptos-token mint function that returns object

---

aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move

Need to turn off verification of `create_stake_pool` to avoid timeout of inconsistency check in the daily prover test job.

[Spec] Fix spec for daily prover test

---

.vscode/extensions.json
.vscode/settings.json

This PR introduces some default vscode settings to make it easier to work on the aptos-core repo using vscode.
N/A

[devtools] vscode workspace settings

---

aptos-move/framework/aptos-framework/doc/aggregator_v2.md
aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.move

[aggregator_v2][move] Rename to max_value and make Aggregator template

---

ecosystem/nft-metadata-crawler-parser/diesel.toml
ecosystem/nft-metadata-crawler-parser/migrations/2023-06-27-001532_create_tables/down.sql
ecosystem/nft-metadata-crawler-parser/migrations/2023-06-27-001532_create_tables/up.sql
ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris.rs
ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris_query.rs
ecosystem/nft-metadata-crawler-parser/src/schema.rs
ecosystem/nft-metadata-crawler-parser/src/utils/database.rs

Move tables for the nft metadata crawler to its own postgres schema

[NFT Metadata Crawler] Use separate DB schema

---

config/src/config/storage_config.rs

So that a user won't be able to accidentally set it to a super large number and fail requests.
eyes.
I feel a unit test doesn't add much value.

Sanitize pruner window configs

---

ecosystem/nft-metadata-crawler-parser/migrations/2023-06-27-001532_create_tables/down.sql
ecosystem/nft-metadata-crawler-parser/migrations/2023-06-27-001532_create_tables/up.sql
ecosystem/nft-metadata-crawler-parser/src/models/ledger_info.rs
ecosystem/nft-metadata-crawler-parser/src/models/mod.rs
ecosystem/nft-metadata-crawler-parser/src/schema.rs
ecosystem/nft-metadata-crawler-parser/src/utils/database.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Adds chain id check to make sure the parser is pulling and writing data for the write chain
Tested locally, looks good. Code is also mostly copied from indexers
Fixes EI-282

[NFT Metadata Crawler] Check received chain id against existing chain id in parser db

---

storage/indexer/src/lib.rs

Cherry pick indexer fix to current mainnet version

---

Cargo.lock
Cargo.toml
crates/aptos-profiler/Cargo.toml
crates/aptos-profiler/src/cpu_profiler.rs
crates/aptos-profiler/src/jeprof.py
crates/aptos-profiler/src/lib.rs
crates/aptos-profiler/src/memory_profiler.rs
crates/aptos-profiler/src/utils.rs

Adding the aptos-profiler crate with cpu and memory profiling features.

Aptos-profiling crate

---

execution/executor/src/chunk_executor.rs

replay-verify: log skipped version when it happens

---

.github/workflows/module-verify.yaml
.github/workflows/replay-verify.yaml
.github/workflows/workflow-run-module-verify.yaml
.github/workflows/workflow-run-replay-verify.yaml
developer-docs-site/docs/nodes/full-node/aptos-db-restore.md
testsuite/module_verify_run_local.py
testsuite/replay_verify_run_local.py

install google sdk
use the gcp bucket instead
https://github.com/aptos-labs/aptos-core/actions/runs/5815172944/job/15766231496 Test replay verify successfully started

Swich to gcp for reading backup data

---

storage/indexer/src/lib.rs

internal indexer: parse tables in resource groups

Pick indexer table fix to 1.6

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/indexer/generated/operations.ts
ecosystem/typescript/sdk/src/indexer/generated/queries.ts
ecosystem/typescript/sdk/src/indexer/generated/types.ts
ecosystem/typescript/sdk/src/indexer/queries/CurrentTokenOwnershipFieldsFragment.graphql
ecosystem/typescript/sdk/src/indexer/queries/getAccountCoinsData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getAccountTransactionsData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getCollectionData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getCollectionsWithOwnedTokens.graphql
ecosystem/typescript/sdk/src/indexer/queries/getNumberOfDelegators.graphql
ecosystem/typescript/sdk/src/indexer/queries/getTokenCurrentOwnerData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getTokenData.graphql
ecosystem/typescript/sdk/src/indexer/queries/getTokenOwnersData.graphql
ecosystem/typescript/sdk/src/providers/indexer.ts
ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts

- Add a filter amount > 0 on getTokenOwnersData
- Include missing query fields

[TS SDK] filter amount > 0 on getTokenOwnersData and include all query fields

---

.github/workflows/forge-stable.yaml
testsuite/forge-cli/src/main.rs
testsuite/forge/src/success_criteria.rs
testsuite/testcases/src/load_vs_perf_benchmark.rs

[forge] Add checking latency for different workloads

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

- Fix default behavior for coin client to transfer and create account by default
- Filter amount > 0 on `getTokenOwnersData`
- Include missing fields for all Indexer queries

[TS SDK] bump version to 1.18.0

---

developer-docs-site/docs/nodes/full-node/aptos-db-restore.md

[storage] update resource requirement

---

.dockerignore
docker/builder/build-tools.sh
docker/builder/docker-bake-rust-all.hcl
docker/builder/nft-metadata-crawler.Dockerfile

Initial PR was reverted here https://github.com/aptos-labs/aptos-core/commit/aa81b95e7c4bf7abc83e28b341ae6e8fdfdf7317 due issues with the build process, which has be resolved. This brings it back. 

Revert "Revert "[NFT Metadata Crawler] Dockerize Parser (#9541)""

---

aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs

Doesn't need to be `mut` in a few places.
existing tests

trivial: fix gas meter mutability

---

developer-docs-site/docs/move/book/functions.md

typo in functions.md

---

developer-docs-site/docs/move/prover/spec-lang.md

typo spec-lang.md

---

.github/workflows/docker-build-test.yaml

update compatibility test base

---

developer-docs-site/docs/nodes/indexer-fullnode.md

This PR adds a small note to the indexer documentation about supported ways of bootstrapping an indexer fullnode.

[Dev Docs] Add note about indexer bootstrap support.

---

crates/aptos-api-tester/src/main.rs
crates/aptos-api-tester/src/strings.rs
crates/aptos-api-tester/src/tests/mod.rs
crates/aptos-api-tester/src/tests/view_function.rs
crates/aptos-api-tester/src/utils.rs

This commit adds a new test which tests a simple view function.
Can run locally to success. GCP coming soon.

[api] Add view function testing to the API tester

---

Cargo.lock
crates/aptos-profiler/src/cpu_profiler.rs
crates/aptos-profiler/src/jeprof.py
crates/aptos-profiler/src/lib.rs
crates/aptos-profiler/src/memory_profiler.rs
execution/executor-benchmark/Cargo.toml
execution/executor-benchmark/src/main.rs

Started implementation of manual cpu profiling start/stop.

Profiling exec benchmark

---

ecosystem/typescript/sdk_v2/src/core/account_address.ts

I think this was a bad merge, the above code block handles all of the stuff from this block I delete in this PR.
```
npx jest -- tests/unit/*
```

[TS SDK v2] Remove redundant code in AccountAddress.fromString

---

aptos-move/aptos-vm/src/evm/engine.rs
aptos-move/aptos-vm/src/evm/evm_backend.rs

Temp change to add change set support

---

ecosystem/nft-metadata-crawler-parser/src/utils/gcs.rs
ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs
ecosystem/nft-metadata-crawler-parser/src/utils/json_parser.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Title, add more context for logs, add more panics (failed to write to gcs, failed to commit postgres tx)
Works locally

[NFT Metadata Crawler] Stop parsing completely if token_uri has already been parsed

---

aptos-move/aptos-evm/src/engine.rs
third_party/move/extensions/move-table-extension/src/lib.rs

Add support for generating Change Set

---

consensus/src/quorum_store/batch_generator.rs
consensus/src/quorum_store/counters.rs
testsuite/forge-cli/src/main.rs

A couple metrics to observe backpressure better

[Quorum Store] A couple metrics to observe backpressure better

---

Cargo.lock
aptos-move/aptos-evm/Cargo.toml
aptos-move/aptos-evm/src/engine.rs
aptos-move/aptos-evm/src/evm_backend.rs
aptos-move/aptos-evm/src/utils.rs
third_party/move/move-core/types/Cargo.toml
third_party/move/move-core/types/src/u256.rs
third_party/move/move-core/types/src/value.rs

Add support for storage key

---

aptos-move/aptos-evm/src/engine.rs
aptos-move/aptos-evm/src/utils.rs

Test deploying smart contract

---

aptos-move/aptos-evm/src/engine.rs
aptos-move/aptos-evm/src/evm_backend.rs
aptos-move/aptos-evm/src/lib.rs

Add view function and transfer function

---

aptos-move/aptos-evm/src/engine.rs
aptos-move/aptos-evm/src/evm_backend.rs
aptos-move/aptos-evm/src/evm_io.rs
aptos-move/aptos-evm/src/lib.rs

Skedia hack evm

---

aptos-move/aptos-evm/Cargo.toml
aptos-move/aptos-evm/src/engine.rs
aptos-move/aptos-evm/src/eth_address.rs
aptos-move/aptos-evm/src/evm_backend.rs
aptos-move/aptos-evm/src/evm_io.rs
aptos-move/aptos-evm/src/lib.rs
aptos-move/aptos-evm/src/utils.rs

Some more tests and add API for contract address

---

Cargo.lock
aptos-move/aptos-evm/src/engine.rs
aptos-move/aptos-evm/src/evm_io.rs
aptos-move/aptos-evm/src/utils.rs

Fix BCS encoding mess

---

aptos-move/aptos-evm/src/engine.rs

Add code fix

---

aptos-move/aptos-gas-calibration/README.md

Improve docs based on user feedback

[gas][docs] example guides

---

consensus/src/dag/tests/integration_tests.rs
consensus/src/dag/tests/mod.rs

This PR implements an e2e integration test for the DAG modules. The test currently only asserts the good case behavior and doesn't cover all possible invocations. It uses the NetworkPlayground to simulate the network.

[dag] e2e integration test

---

aptos-move/framework/aptos-stdlib/doc/big_vector.md
aptos-move/framework/aptos-stdlib/doc/smart_vector.md
aptos-move/framework/aptos-stdlib/sources/data_structures/big_vector.move
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.move

drop/clear a smart vector if T has drop.
ut

[smart_vector] add destroy/clear functions for droppable T

---

Cargo.lock
Cargo.toml
aptos-move/aptos-vm/src/aptos_vm.rs
crates/aptos-profiler/Cargo.toml
crates/aptos-profiler/src/cpu_profiler.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/storage-interface/src/async_proof_fetcher.rs

Unify thread name, and combine all threads in the same thread pool in framegraph produced by cpu_profiler.

---

crates/aptos-crypto/src/traits.rs

Fix `Uniform` comments in `aptos-crypto/src/traits.rs`

---

ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs

* Accepts the headers to data service.
* To avoid cardinality issue, use classification + name as the fields.

add the header to data service.

---

consensus/src/quorum_store/batch_coordinator.rs

remove handle_batch which does checks that ensure_max_limits already does

[Quorum Store] remove redundant checks

---

developer-docs-site/docs/reference/glossary.md
developer-docs-site/docs/sdks/ts-sdk/sdk-plugins-layer.md
developer-docs-site/docs/standards/aptos-coin.md
developer-docs-site/docs/standards/aptos-object.md
developer-docs-site/docs/standards/aptos-token.md
developer-docs-site/docs/standards/digital-asset.md
developer-docs-site/docs/standards/fungible-asset.md
developer-docs-site/docs/standards/index.md
developer-docs-site/scripts/additional_dict.txt
developer-docs-site/sidebars.js

Rename Token V2 to Digital Asset (DA)

---

consensus/consensus-types/src/block.rs
consensus/consensus-types/src/block_data.rs
consensus/consensus-types/src/common.rs
consensus/src/dag/adapter.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/mod.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/tests/dag_driver_tests.rs
consensus/src/dag/tests/dag_test.rs
consensus/src/dag/tests/integration_tests.rs
consensus/src/dag/tests/order_rule_tests.rs
consensus/src/dag/types.rs

Add trait/impl for buffer manager adapter and implement the persist/recovery flow.

[dag] support crash recovery for order rule

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

bump CLI version to 2.1.0

---

aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
aptos-move/framework/aptos-framework/sources/object.move
aptos-move/framework/aptos-framework/sources/object.spec.move
aptos-move/framework/aptos-framework/sources/primary_fungible_store.move

Context: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-45.md
Unit tests. Manual tests in devnet/testnet/mainnet later

[Framework] AIP-45: Allow soft burning objects

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/src/indexer/generated/operations.ts
ecosystem/typescript/sdk/src/indexer/generated/queries.ts
ecosystem/typescript/sdk/src/indexer/generated/types.ts
ecosystem/typescript/sdk/src/indexer/queries/getAccountCoinDataCount.graphql
ecosystem/typescript/sdk/src/indexer/queries/getAccountCoinsData.graphql
ecosystem/typescript/sdk/src/providers/indexer.ts
ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts

Adds fungible asset queries support
- getAccountCoinsData
- getAccountCoinsDataCount

[TS SDK] Add support for fungible asset queries

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] bump version to 1.19.0

---

Cargo.lock
Cargo.toml
crates/aptos-runtimes/src/lib.rs
experimental/runtimes/Cargo.toml
experimental/runtimes/src/lib.rs
experimental/runtimes/src/thread_manager.rs

This is just a start point. We have too many threads in the system. I'm trying to come up a way to manager all threads at a common place. I'm just putting two simple strategies as an example, please just treat this as an example and playground, and implement better things on top of it.

[Experimental] Add ThreadManager.

---

developer-docs-site/docs/indexer/custom-processors/parsing-txns.md
developer-docs-site/sidebars.js

Addresses part of https://github.com/aptos-labs/aptos-core/issues/9758.

[indexer-docs] Add guide to parsing txns

---

developer-docs-site/docs/indexer/api/example-queries.md
developer-docs-site/docs/indexer/api/usage-guide.md
developer-docs-site/docs/indexer/indexer-landing.md
developer-docs-site/scripts/additional_dict.txt

Addresses part of https://github.com/aptos-labs/aptos-core/issues/9758. 
As part of this PR I include an embed for a diagram I made in Figjam that outlines the whole system at a somewhat high level of detail.
The flow here could be better but we're in a bit of a rush with this content, we can brush it up later.

[indexer-docs] Improve top level landing page

---

developer-docs-site/docs/indexer/txn-stream/local-development.md

Addresses part of https://github.com/aptos-labs/aptos-core/issues/9758.

[indexer-docs] Add local development guide for the transcation stream service

---

ecosystem/indexer-grpc/indexer-grpc-server-framework/src/lib.rs
ecosystem/nft-metadata-crawler-parser/src/models/nft_metadata_crawler_uris_query.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Fixed the closing of PubSub subscription streams and added more logs and panics
Tested with processor locally, works fine

[NFT Metadata Crawler] Fix PubSub ACKing bugs and add logs

---

aptos-move/framework/aptos-stdlib/doc/smart_table.md
aptos-move/framework/aptos-stdlib/doc/smart_vector.md
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.move

add a clear function to smart_table with droppable kv.
ut

[smart_table] add clear and some nits

---

developer-docs-site/docs/indexer/api/labs-hosted.md
developer-docs-site/docs/indexer/txn-stream/labs-hosted.md

Addresses part of https://github.com/aptos-labs/aptos-core/issues/9758.

[indexer-docs] Add information about the API Gateway

---

aptos-move/aptos-release-builder/data/release.yaml

Enable transaction shuffling in release.yaml for v1.7 release

---

aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
aptos-move/aptos-gas-schedule/src/ver.rs
aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm-types/src/storage.rs
aptos-move/e2e-move-tests/src/tests/storage_refund.data/pack/sources/main.move
aptos-move/e2e-move-tests/src/tests/storage_refund.rs

Add some safety guard, just in case.

limit max number of write ops

---

aptos-move/framework/aptos-framework/doc/event.md
aptos-move/framework/aptos-framework/sources/event.move
aptos-move/framework/aptos-framework/sources/event.spec.move
aptos-move/framework/src/natives/event.rs

make native function name consistent with move function name.
compile

[rename] rename function of event v2

---

consensus/src/consensusdb/consensusdb_test.rs
consensus/src/consensusdb/mod.rs
consensus/src/consensusdb/schema/dag/mod.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_handler.rs
consensus/src/dag/storage.rs
consensus/src/dag/tests/dag_driver_tests.rs
consensus/src/dag/tests/dag_test.rs

[dag] support crash recovery of dag driver

---

Cargo.lock
execution/executor-benchmark/Cargo.toml
execution/executor-benchmark/src/account_generator.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/main.rs
execution/executor-benchmark/src/pipeline.rs
execution/executor-benchmark/src/transaction_generator.rs

Generate transactions in multiple threads.

---

aptos-move/aptos-release-builder/data/release.yaml

Feels silly to enable a feature, then disable and then enable. let's simplify it?

update release yaml

---

aptos-move/aptos-release-builder/data/release.yaml

[Release] remove duplicated entry

---

Cargo.lock
Cargo.toml
execution/executor/Cargo.toml
execution/executor/src/block_executor.rs
execution/executor/src/components/block_tree/mod.rs
execution/executor/src/components/in_memory_state_calculator_v2.rs
experimental/runtimes/src/common.rs
experimental/runtimes/src/lib.rs
experimental/runtimes/src/strategies/default.rs
experimental/runtimes/src/strategies/mod.rs
experimental/runtimes/src/strategies/pin_exe_threads_to_cores.rs
experimental/runtimes/src/thread_manager.rs
storage/aptosdb/Cargo.toml
storage/aptosdb/src/lib.rs
storage/aptosdb/src/state_kv_db.rs
storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_restore/mod.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_snapshot_committer.rs
storage/jellyfish-merkle/Cargo.toml
storage/jellyfish-merkle/src/lib.rs
storage/scratchpad/Cargo.toml
storage/scratchpad/src/sparse_merkle/updater.rs

Default to the "default" strategy.
Adjusted the threadpool, under the default strategy, commit is slightly slower, execution is slightly faster.
This PR doesn't cover all the threadpool usages. There are some other things that may need to move to a different thread pool, but I'm not super confident that they won't affect production, need more investigations.

[Performance] Refactor ThreadManager, and use it in some places.

---

consensus/src/network.rs
consensus/src/quorum_store/batch_requester.rs
consensus/src/quorum_store/tests/types_test.rs
consensus/src/quorum_store/types.rs

[cherry-pick] [Quorum Store] check digest match, and log sender if mismatch

---

consensus/src/dag/order_rule.rs
consensus/src/dag/tests/order_rule_tests.rs

[dag] add process_all to order rule

---

Cargo.lock
consensus/Cargo.toml
consensus/src/dag/tests/types_test.rs
consensus/src/dag/types.rs

(#9872)
+ DAG Network message test
(cherry picked from commit eef00c64113f78e585ce62bfeeaaaca30fd6fad4)

[consensus][dag] Truncate bytes when debug logging network message 

---

consensus/src/experimental/buffer_manager.rs

[consensus] fix the re-broadcast condition

---

execution/executor-benchmark/src/main.rs
testsuite/single_node_performance.py

add different suites to single_node_performance.py

---

execution/executor-benchmark/src/main.rs

[Fix] Fix build error under non-linux.

---

developer-docs-site/docs/move/move-on-aptos/cryptography.md

[docs] typo in docs/move/move-on-aptos/cryptography.md

---

developer-docs-site/docs/move/move-on-aptos/cryptography.md

[docs] add SHA2-256 and SHA3-256 to "Cryptography in Move" hashing table

---

aptos-move/aptos-release-builder/data/release.yaml
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/aptos_vm_impl.rs
aptos-move/framework/src/module_metadata.rs
aptos-move/vm-genesis/src/lib.rs
types/src/on_chain_config/aptos_features.rs

[metadata] Metadata fixes

---

aptos-move/aptos-vm/src/testing.rs

trivial: fix unused variable warning

---

ecosystem/nft-metadata-crawler-parser/src/utils/counters.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Panic to restart cloud run instance when unable to get postgres connection

[NFT Metadata Crawler] Remove pool clone

---

aptos-move/aptos-release-builder/data/example.yaml
aptos-move/aptos-release-builder/src/components/mod.rs
aptos-move/aptos-release-builder/src/validate.rs

Deprecate the Single Step Governance proposal option for the release builder.
Existing test should cover this.

[aptos-release-builder] Deprecate Single Step Proposal

---

testsuite/smoke-test/src/rest_api.rs

Followup to https://github.com/aptos-labs/aptos-core/issues/7849

[smoke-test] Test API pagination works greater than 25

---

ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs
ecosystem/nft-metadata-crawler-parser/src/utils/counters.rs
ecosystem/nft-metadata-crawler-parser/src/worker.rs

Improves the metrics so there is a clearer comparison for how a parser is terminated

[NFT Metadata Crawler] Improve metrics for parser invocation and termination

---

Cargo.lock
aptos-move/aptos-aggregator/Cargo.toml
aptos-move/aptos-aggregator/src/aggregator_change_set.rs
aptos-move/aptos-aggregator/src/aggregator_extension.rs
aptos-move/aptos-aggregator/src/bounded_math.rs
aptos-move/aptos-aggregator/src/delta_change_set.rs
aptos-move/aptos-aggregator/src/lib.rs
aptos-move/block-executor/src/unit_tests/mod.rs
aptos-move/framework/aptos-framework/doc/aggregator_v2.md
aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
aptos-move/framework/src/natives/aggregator_natives/context.rs
aptos-move/mvhashmap/src/unit_tests/mod.rs
aptos-move/mvhashmap/src/versioned_aggregators.rs

bounded math utilities for simpler aggregator formulas

---

consensus/src/dag/adapter.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/storage.rs
consensus/src/dag/tests/dag_test.rs

[dag] support commit event for history anchors

---

consensus/src/counters.rs
consensus/src/experimental/execution_phase.rs
consensus/src/experimental/persisting_phase.rs
consensus/src/experimental/pipeline_phase.rs
consensus/src/experimental/signing_phase.rs

trivial: add phase timers

---

ecosystem/typescript/sdk/src/transaction_builder/index.ts

[ts-sdk] Export builder utils

---

aptos-move/aptos-vm/src/sharded_block_executor/test_utils.rs
aptos-move/aptos-vm/src/sharded_block_executor/tests.rs

Fixed a unit test setup bug which is probably responsible for the previous flakiness...

re-enable sharded executor unit tests

---

consensus/consensus-types/src/common.rs
consensus/src/block_storage/block_store.rs
consensus/src/error.rs
consensus/src/experimental/execution_phase.rs
consensus/src/experimental/ordering_state_computer.rs
consensus/src/experimental/persisting_phase.rs
consensus/src/experimental/tests/execution_phase_tests.rs
consensus/src/payload_manager.rs
consensus/src/quorum_store/batch_requester.rs
consensus/src/quorum_store/batch_store.rs
consensus/src/quorum_store/tests/proof_coordinator_test.rs
consensus/src/state_computer.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_state_computer.rs
execution/executor-types/src/error.rs
execution/executor-types/src/lib.rs
execution/executor/src/block_executor.rs
execution/executor/src/components/block_tree/mod.rs

Prepare for introduction of some more complicated types

trivial: ExecutorResult, ExecutorError 

---

storage/aptosdb/src/event_store/mod.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/utils/truncation_helper.rs

[v1.7] cherrypick #10019

---

developer-docs-site/docs/concepts/index.md

Update index.md: concepts index page lack of base-gas.md entry

---

Cargo.lock
aptos-move/aptos-aggregator/Cargo.toml
aptos-move/aptos-aggregator/src/aggregator_change_set.rs
aptos-move/aptos-aggregator/src/aggregator_extension.rs
aptos-move/aptos-aggregator/src/bounded_math.rs
aptos-move/aptos-aggregator/src/delta_change_set.rs
aptos-move/aptos-aggregator/src/delta_math.rs
aptos-move/aptos-aggregator/src/lib.rs
aptos-move/aptos-aggregator/src/resolver.rs
aptos-move/aptos-gas-schedule/src/gas_schedule/aptos_framework.rs
aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm-types/src/output.rs
aptos-move/aptos-vm-types/src/tests/test_change_set.rs
aptos-move/aptos-vm-types/src/tests/test_output.rs
aptos-move/aptos-vm-types/src/tests/utils.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/move_vm_ext/session.rs
aptos-move/block-executor/Cargo.toml
aptos-move/block-executor/src/unit_tests/mod.rs
aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/sources/aggregator_v2_test.move
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
aptos-move/framework/src/natives/aggregator_natives/context.rs
aptos-move/framework/src/natives/aggregator_natives/mod.rs
aptos-move/mvhashmap/Cargo.toml
aptos-move/mvhashmap/src/unit_tests/mod.rs
aptos-move/mvhashmap/src/versioned_aggregators.rs
third_party/move/extensions/move-table-extension/src/lib.rs

Implementing the Aggregator v2 and Snapshots feature in aggregator extension.

Aggregator v2 and Snapshots Implementation

---

api/openapi-spec-generator/Cargo.toml
aptos-move/aptos-aggregator/src/delta_change_set.rs
aptos-move/aptos-vm/Cargo.toml
aptos-move/block-executor/Cargo.toml
aptos-move/framework/Cargo.toml
aptos-move/framework/cached-packages/Cargo.toml
aptos-move/mvhashmap/Cargo.toml
aptos-node/src/lib.rs
consensus/src/state_computer.rs
execution/executor-service/Cargo.toml
third_party/move/extensions/move-table-extension/Cargo.toml
third_party/move/tools/move-cli/Cargo.toml
types/src/state_store/state_value.rs

Including features directly in dependencies will expose it unconditionally which is not what we want most of the time.

[dep] moving testing features out from dependencies

---

aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/Move.toml
aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/sources/aggregator_v2_test.move
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs

Fix aggregator v2 snapshot tests

Fixing aggregator v2 tests

---

third_party/move/move-compiler/tests/move_check/inlining/non_lambda_arg.exp
third_party/move/move-compiler/tests/move_check/inlining/non_lambda_arg.move

Adding the test case from #9694 to show that the bug mentioned is already fixed.
Manually verified the outcome of the newly added test case and added it to the baseline.

Adding a new test case to demonstrate issue #9694 has been fixed.

---

consensus/src/consensusdb/consensusdb_test.rs
consensus/src/consensusdb/mod.rs
consensus/src/consensusdb/schema/dag/mod.rs
consensus/src/consensusdb/schema/mod.rs
consensus/src/dag/adapter.rs
consensus/src/dag/anchor_election.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/storage.rs
consensus/src/dag/tests/dag_test.rs

[dag] replace the persisted anchor id with commit event

---

storage/storage-interface/src/lib.rs

Prepare for  https://github.com/aptos-labs/aptos-core/pull/8849

trivial: DbReader: ability to delegate implementation

---

execution/executor-test-helpers/src/integration_test_impl.rs
storage/aptosdb/src/db_debugger/checkpoint/mod.rs
storage/aptosdb/src/db_debugger/common/mod.rs
storage/aptosdb/src/db_debugger/examine/print_db_versions.rs
storage/aptosdb/src/db_debugger/mod.rs
storage/aptosdb/src/db_debugger/state_tree/get_path.rs
storage/aptosdb/src/db_debugger/state_tree/get_snapshots.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/ledger_db.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/state_merkle_pruner/test.rs
storage/aptosdb/src/state_merkle_db.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/test_helper.rs
storage/aptosdb/src/utils/truncation_helper.rs

manual test command with new flag works 
update the proptest to test sharded db

sharded DB truncation, cli, test

---

state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs
state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs
state-sync/state-sync-v2/data-streaming-service/src/tests/streaming_service.rs
state-sync/state-sync-v2/data-streaming-service/src/tests/utils.rs

This PR builds on https://github.com/aptos-labs/aptos-core/pull/9921 and adds additional unit and integration tests for subscription streams. Note: no other logical changes should take place.

[State Sync] Add additional tests for subscription streams.

---

Cargo.lock
Cargo.toml
crates/aptos-protos/Cargo.toml
crates/aptos-protos/src/lib.rs
crates/aptos-protos/src/pb/aptos.indexer.v1.tonic.rs
crates/aptos-protos/src/pb/aptos.internal.fullnode.v1.tonic.rs
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs

* upgrade dependencies to new versions.
`./scripts/rust_lint.rs` passed on Mac M1 and Debian platform.

[proto] Fix the proto build with newer prost plugins. 

---

.github/workflows/replay-verify.yaml

Increase timeout for mainnet replay

[replay-verify] increase timeout for mainnet replay

---

config/src/config/state_sync_config.rs
state-sync/state-sync-v2/data-streaming-service/src/metrics.rs
state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs
state-sync/storage-service/server/src/handler.rs
state-sync/storage-service/server/src/lib.rs
state-sync/storage-service/server/src/optimistic_fetch.rs
state-sync/storage-service/server/src/subscription.rs
state-sync/storage-service/server/src/tests/optimistic_fetch.rs
state-sync/storage-service/server/src/tests/subscription.rs
state-sync/storage-service/server/src/tests/utils.rs
state-sync/storage-service/server/src/utils.rs

This PR:
1. Replaces the `Mutex<HashMap<...>>` wrapped subscriptions struct with a `DashMap<...>` for improved [performance](https://docs.rs/dashmap/latest/dashmap/) and reduced lock contention.
2. Adds some missing metrics along the way.
Nothing should logically change in this PR.

[State Sync] Update metrics and optimize locks.

---

storage/aptosdb/src/aptosdb_test.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/state_merkle_pruner/test.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/aptosdb/src/test_helper.rs

trivial: AptosDB: remove unused testonly field

---

storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs
storage/aptosdb/src/state_kv_db.rs
storage/aptosdb/src/state_merkle_db.rs

trivial: panic with error msg

---

.github/workflows/replay-verify.yaml

To test this, goto https://github.com/aptos-labs/aptos-core/actions/workflows/replay-verify.yaml and trigger the workflow from this branch with `mainnet`.

[replay-verify] Fix typo 

---

testsuite/single_node_performance.py

adjust performance benchmarks

---

aptos-move/aptos-release-builder/data/release.yaml

Disable aggregator_snapshots feature flag for 1.7

---

aptos-move/aptos-aggregator/src/types.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
aptos-move/mvhashmap/src/types.rs
aptos-move/mvhashmap/src/versioned_aggregators.rs

[trivial] consolidate aggregator ids

---

aptos-move/aptos-native-interface/src/context.rs
aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move
aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
aptos-move/framework/src/natives/aggregator_natives/helpers_v1.rs
aptos-move/framework/src/natives/aggregator_natives/helpers_v2.rs
aptos-move/vm-genesis/src/lib.rs
types/src/on_chain_config/aptos_features.rs

recreating as #9996 got closed as it was against Satya's PR.

Add aggregator_execution_enabled feature flag, and fallback logic

---

aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-node/src/storage.rs

picking https://github.com/aptos-labs/aptos-core/pull/10118 to v1.7 release branch

[cherry-pick 1.7] assert no slot allocation after epilogue

---

aptos-move/e2e-move-tests/src/harness.rs

[e2e-move-tests][harness] Richer assert macros

---

config/src/config/indexer_grpc_config.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/localnet_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs

* Add external grpc to fullndoe, which supports `transactions_count`. 
Tested locally, looks good. Also the disconnection is handled gracefully. 
with `dev_mode` off:
with `dev_mode` on:

[transaction stream] add the external grpc to fullnode.

---

aptos-move/aptos-release-builder/data/release.yaml

we will hold on with enabling this feature in release v1.7

Remove Bulletproofs feature flag

---

aptos-move/framework/Cargo.toml
aptos-move/move-examples/Cargo.toml

[move-examples] fix test dependencies

---

consensus/consensus-types/src/block.rs
consensus/consensus-types/src/block_data.rs
consensus/src/dag/adapter.rs
consensus/src/dag/bootstrap.rs

[dag] fill in the previous voters bitvec in adapter

---

ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs

* This is to fix that the transaction stream on fullnode is not accepted by processors.

enable the compression for txn stream on fullnode.

---

consensus/consensus-types/src/block.rs
consensus/consensus-types/src/block_data.rs
consensus/src/dag/adapter.rs

[dag] add new block type for dag

---

consensus/src/dag/order_rule.rs
consensus/src/dag/tests/order_rule_tests.rs

[dag] apply the window to order rule

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

[TS SDK] Bump version to 1.20.0

---

state-sync/aptos-data-client/src/metrics.rs
state-sync/state-sync-driver/src/metrics.rs

This PR increases the range of various latency buckets used by state sync.

[State Sync] Increase various latency buckets.

---

aptos-move/move-examples/mint_nft/2-Using-Resource-Account/sources/create_nft_with_resource_account.move

Update create_nft_with_resource_account.move comment

---

aptos-move/block-executor/src/lib.rs

Update typos in lib.rs

---

developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/index.md

There are only nine steps in the link. Perhaps this is a mistake and was meant to be from step 1.

[typo*]Update index.md

---

developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md

[link*]Update fullnode-source-code-or-docker.md

---

testsuite/forge/src/runner.rs

forge: ability to override resource ask in Rust

---

aptos-move/framework/aptos-framework/doc/object.md
aptos-move/framework/aptos-framework/sources/object.move

[object] refactor burn/unburn

---

consensus/src/epoch_manager.rs
consensus/src/liveness/proposal_generator_test.rs
consensus/src/liveness/unequivocal_proposer_election.rs
consensus/src/liveness/unequivocal_proposer_election_test.rs
consensus/src/logging.rs
consensus/src/network.rs
consensus/src/round_manager.rs
consensus/src/round_manager_fuzzing.rs
consensus/src/round_manager_test.rs

[consensus] Dedicated channel for proposal buffering and batch process

---

aptos-move/aptos-aggregator/src/aggregator_change_set.rs
aptos-move/aptos-aggregator/src/aggregator_extension.rs
aptos-move/aptos-aggregator/src/bounded_math.rs
aptos-move/aptos-aggregator/src/delta_change_set.rs
aptos-move/aptos-aggregator/src/types.rs
aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm-types/src/tests/test_change_set.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
aptos-move/framework/src/natives/aggregator_natives/context.rs
aptos-move/mvhashmap/src/versioned_aggregators.rs

Implementing VersionedAggregators and AggregatorChange for aggregator V2

---

aptos-move/aptos-aggregator/src/aggregator_change_set.rs
aptos-move/aptos-aggregator/src/delta_change_set.rs
aptos-move/aptos-aggregator/src/resolver.rs
aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm-types/src/tests/utils.rs
aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/natives.rs
aptos-move/aptos-vm/src/storage_adapter/executor_view_base.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/task.rs
aptos-move/block-executor/src/txn_last_input_output.rs
aptos-move/block-executor/src/view.rs
aptos-move/framework/src/natives/aggregator_natives/context.rs
aptos-move/mvhashmap/src/lib.rs
aptos-move/mvhashmap/src/unit_tests/mod.rs
aptos-move/mvhashmap/src/unit_tests/proptest_types.rs
aptos-move/mvhashmap/src/unsync_map.rs
aptos-move/mvhashmap/src/versioned_aggregators.rs

connecting MVHashMap with AggregatorChange for read and write

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

CLI version bump to 2.1.1

---

ecosystem/typescript/sdk_v2/src/api/transaction.ts
ecosystem/typescript/sdk_v2/src/internal/transaction.ts
ecosystem/typescript/sdk_v2/tests/e2e/api/transaction.test.ts

Adds getTransactions to the sdk API
None - blocked on transaction submission

[ts-sdk-v2] Add getTransactions to the sdk-v2 transaction API

---

aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/stake.md
aptos-move/framework/aptos-framework/doc/staking_contract.md
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/stake.spec.move
aptos-move/framework/aptos-framework/sources/staking_contract.spec.move

Fix the spec of the governance and stake module. All high-level requirements in the stake module and the first two high-level requirements in the staking_contract module are proved.

[Spec] Fix spec

---

testsuite/forge-cli/src/main.rs

We found that the throughput for large and small messages is very different with large latencies. We update the test to run with large messages and then split out a small messages test. The large messages are useful for sanity checking the network setup, the small messages is something that we can hopefully improve upon.

[Forge][netbench] split into large and small messages for two region test

---

.github/workflows/replay-verify.yaml
.github/workflows/workflow-run-module-verify.yaml
.github/workflows/workflow-run-replay-verify.yaml
scripts/dev_setup.sh
terraform/helm/fullnode/files/backup/s5cmd-public.yaml

manual run
https://github.com/aptos-labs/aptos-core/actions/runs/6343023416?pr=10295

use s5cmd for downloading files in the restore process

---

testsuite/single_node_performance.py

recalibrate single node benchmark for perf regression

---

.github/workflows/replay-verify.yaml
.github/workflows/workflow-run-module-verify.yaml
.github/workflows/workflow-run-replay-verify.yaml
scripts/dev_setup.sh
terraform/helm/fullnode/files/backup/s5cmd-public.yaml

resend of https://github.com/aptos-labs/aptos-core/pull/10295 which landed on a non-main branch by accident.

use s5cmd for downloading files in replay-verify

---

aptos-move/e2e-tests/Cargo.toml

Fix compilation error due to feature unification.

[e2e-tests] Fix compilation error

---

execution/executor/src/components/in_memory_state_calculator_v2.rs

Drop frozen root after make checkpoint.

---

aptos-move/aptos-abstract-gas-usage/src/algebra_helpers.rs

This revises `fn aggregate_terms` so that it ignores all terms with 0 as coefficients, preventing them from causing errors in the gas calibration tool downstream.

[gas-calibration][simple] ignore terms with 0-coefficients

---

aptos-move/aptos-release-builder/data/release.yaml

[framework-release] update yaml

---

Cargo.lock
Cargo.toml
consensus/Cargo.toml
consensus/src/dag/dag_driver.rs
consensus/src/dag/mod.rs
consensus/src/dag/observability/counters.rs
consensus/src/dag/observability/mod.rs
consensus/src/dag/observability/tracing.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/types.rs
consensus/src/lib.rs

[dag] add various counters

---

Cargo.lock
aptos-move/e2e-move-tests/Cargo.toml
aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/Move.toml
aptos-move/e2e-move-tests/src/tests/aggregator_v2.data/pack/sources/aggregator_v2_test.move
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs
aptos-move/e2e-tests/src/executor.rs

with api enabled and execution disabled, all tests now pass on top of #10069

[aggregators_v2] Refactor and improve aggregator tests

---

storage/aptosdb/src/lib.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/utils/truncation_helper.rs

Successfully synced a devnet PFN from genesis.

Allow using skip_index_and_usage on state sync code path.

---

consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_state_sync.rs
consensus/src/dag/observability/logging.rs
consensus/src/dag/observability/mod.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/types.rs

[dag] add a few structured logging

---

ecosystem/typescript/sdk_v2/src/crypto/ed25519.ts

[SDKv2] ed25519 fix publicKey derive

---

ecosystem/typescript/sdk_v2/src/crypto/ed25519.ts
ecosystem/typescript/sdk_v2/tests/unit/ed25519.test.ts

[SDKv2] derive publickey unit test

---

aptos-move/framework/aptos-framework/doc/delegation_pool.md
aptos-move/framework/aptos-framework/sources/delegation_pool.move

refactor: replace multiply_then_divide using math64::mul_div

---

consensus/src/dag/dag_handler.rs
consensus/src/dag/tests/types_test.rs
consensus/src/dag/types.rs

[dag] hardening message verification

---

ecosystem/typescript/sdk_v2/src/client/get.ts
ecosystem/typescript/sdk_v2/src/client/post.ts
ecosystem/typescript/sdk_v2/src/internal/general.ts

Refactors the post request code to be consistent for indexer calls

[ts-sdk-v2] Mini get/post request refactor

---

aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm-types/src/output.rs
aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/block-executor/src/captured_reads.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/task.rs
aptos-move/block-executor/src/txn_last_input_output.rs
aptos-move/block-executor/src/view.rs
aptos-move/e2e-tests/src/executor.rs
aptos-move/mvhashmap/src/types.rs
aptos-move/mvhashmap/src/unit_tests/proptest_types.rs
types/src/write_set.rs

Replacing Aggregator V2 IDs with values when committing the transaction

[Draft] Replacing Aggregator V2 IDs with values when committing the transaction 

---

storage/aptosdb/src/pruner/ledger_pruner/ledger_pruner_manager.rs
storage/aptosdb/src/pruner/state_kv_pruner/state_kv_pruner_manager.rs
storage/aptosdb/src/pruner/state_merkle_pruner/state_merkle_pruner_manager.rs

[Storage][Pruner] Set min_readable_version and metrics.

---

aptos-node/src/storage.rs
config/src/config/storage_config.rs
execution/executor-benchmark/src/db_generator.rs
execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/main.rs
execution/executor-test-helpers/src/integration_test_impl.rs
execution/executor/tests/storage_integration_test.rs
storage/aptosdb/src/db_debugger/checkpoint/mod.rs
storage/aptosdb/src/db_debugger/common/mod.rs
storage/aptosdb/src/db_debugger/examine/print_db_versions.rs
storage/aptosdb/src/db_debugger/mod.rs
storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/ledger_db.rs
storage/aptosdb/src/lib.rs
storage/aptosdb/src/state_kv_db.rs
storage/aptosdb/src/state_merkle_db.rs
storage/backup/backup-cli/src/utils/mod.rs
storage/db-tool/src/tests.rs
testsuite/forge-cli/src/main.rs
testsuite/single_node_performance.py
testsuite/smoke-test/src/genesis.rs
testsuite/smoke-test/src/storage.rs

Use one single flag to control all storage related optimization work.

---

.github/workflows/docker-build-test.yaml
docker/builder/docker-bake-rust-all.sh
docker/release-images.mjs

Reverts aptos-labs/aptos-core#9836

Revert "[gha/docker] remove deprecated indexer build"

---

storage/aptosdb/src/db_debugger/truncate/mod.rs
storage/aptosdb/src/pruner/pruner_utils.rs

We will only have it at the end of chunk/block.

[Fix] Do not assume we have VersionData at every version.

---

execution/executor-types/src/lib.rs
execution/executor-types/src/parsed_transaction_output.rs
execution/executor-types/src/state_checkpoint_output.rs
execution/executor/src/components/apply_chunk_output.rs
execution/executor/src/components/chunk_output.rs
execution/executor/src/components/in_memory_state_calculator_v2.rs
types/src/transaction/mod.rs

Move the counter update off of critical path to newly introduced ledger update stage.
Existing UTs.

Move the transaction details counter to ledger update stage

---

ecosystem/indexer-grpc/indexer-grpc-post-processor/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-post-processor/src/pfn_ledger_checker.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs

* Now the monitoring is between indexer via api gateway and PFN.
* Add reconnection to the service. 
Locally tested against testnet; looks good.

[Indexer] Fix the PFN checker for indexer grpc.

---

testsuite/single_node_performance.py

single_node_performance.py: allow overriding data dir

---

.dockerignore
Cargo.lock
Cargo.toml
crates/aptos/Cargo.toml
crates/aptos/src/main.rs
crates/aptos/src/node/local_testnet/hasura_metadata.json
crates/aptos/src/node/local_testnet/indexer_api.rs
crates/aptos/src/node/local_testnet/mod.rs
crates/aptos/src/node/local_testnet/postgres.rs
crates/aptos/src/node/local_testnet/traits.rs
crates/aptos/src/node/local_testnet/utils.rs
crates/aptos/src/node/mod.rs

- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10310
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/10311
This adds support for attaching an indexer API (Hasura) to the DB populated by the processors (support for which is added in https://github.com/aptos-labs/aptos-core/pull/10254).
As part of this I add the notion of shutdown hooks. These are best effort attempts to clean up state that doesn't get cleaned up automatically as part of process shutdown (the perils of Docker).
```
cargo run --release -p aptos -- node run-local-testnet --assume-yes --force-restart --with-indexer-api
```
```
Readiness endpoint: http://0.0.0.0:8070/
Postgres is starting, please wait...
Faucet is starting, please wait...
Indexer API is starting, please wait...
Node API is …
```

[CLI] Add support for running an indexer API to the local testnet

---

.dockerignore
Cargo.lock
Cargo.toml
crates/aptos/Cargo.toml
crates/aptos/src/common/types.rs
crates/aptos/src/common/utils.rs
crates/aptos/src/main.rs
crates/aptos/src/node/local_testnet/hasura_metadata.json
crates/aptos/src/node/local_testnet/indexer_api.rs
crates/aptos/src/node/local_testnet/mod.rs
crates/aptos/src/node/local_testnet/postgres.rs
crates/aptos/src/node/local_testnet/traits.rs
crates/aptos/src/node/local_testnet/utils.rs
crates/aptos/src/node/mod.rs

- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10254
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/10255
For some subcommands JSONifying the error output doesn't really make sense. I make it possible to opt out.
See https://github.com/aptos-labs/aptos-core/pull/10255/.

[CLI] Add support for not JSONifying errors

---

storage/aptosdb/src/state_store/mod.rs

[Fix] Reduce logs.

---

storage/aptosdb/src/state_store/mod.rs

[Fix] Reduce logs. (Previous fix was wrong.)

---

consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_handler.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/mod.rs
consensus/src/dag/observability/tracing.rs
consensus/src/dag/round_state.rs
consensus/src/dag/tests/dag_driver_tests.rs
types/src/validator_verifier.rs

[dag] abstract round state to support different behaviors

---

ecosystem/typescript/sdk_v2/src/crypto/secp256k1.ts
ecosystem/typescript/sdk_v2/src/transactions/authenticator/account.ts
ecosystem/typescript/sdk_v2/src/types/index.ts

Adds the AccountAuthenticator for secp256k1
pnpm fmt & pnpm test

[SDKv2] Add secp256k1 account authenticator

---

aptos-move/framework/aptos-framework/doc/stake.md
aptos-move/framework/aptos-framework/sources/stake.spec.move

Comment out a spec in the stake module to let inconsistency check pass in CI. The spec itself has been proved.

[Spec] Solve timeout in prover daily test

---

testsuite/forge-cli/src/main.rs

The TPS has been consistently above 7k, after landing a series of performance improvements - tinyurl.com/ymhoo66o

[Forge] Increase the TPS threshold for land blocking

---

developer-docs-site/docs/standards/fungible-asset.md

Just a tiny formatting fix for one of the doc pages
No test needed

fix: Tiny formatting error

---

developer-docs-site/docs/guides/system-integrators-guide.md

typos and grammar fixed.
Some grammar and typos are fixed.

Update system-integrators-guide.md [typos and grammar]

---

developer-docs-site/docs/indexer/legacy/migration.md

Update indexer config in doc

---

experimental/runtimes/src/strategies/default.rs
experimental/runtimes/src/strategies/pin_exe_threads_to_cores.rs
experimental/runtimes/src/strategies/threads_priority.rs
experimental/runtimes/src/thread_manager.rs
storage/aptosdb/src/pruner/db_sub_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/event_store_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/mod.rs
storage/aptosdb/src/pruner/ledger_pruner/transaction_accumulator_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/transaction_info_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/transaction_pruner.rs
storage/aptosdb/src/pruner/ledger_pruner/write_set_pruner.rs
storage/aptosdb/src/pruner/state_kv_pruner/mod.rs
storage/aptosdb/src/pruner/state_kv_pruner/state_kv_shard_pruner.rs
storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs
storage/aptosdb/src/state_store/mod.rs

Also added a new thread pool for background tasks.

[Storage][Pruner] Make pruners run in parallel.

---

aptos-move/block-executor/src/executor.rs
aptos-move/framework/src/natives/aggregator_natives/helpers_v2.rs
aptos-move/mvhashmap/src/unit_tests/mod.rs
aptos-move/mvhashmap/src/versioned_data.rs
aptos-move/mvhashmap/src/versioned_delayed_fields.rs
aptos-move/mvhashmap/src/versioned_modules.rs

to have better enforcement (and fix the current issue)

[trivial] Separate insert from insert_final_value in versioned_aggregators

---

ecosystem/python/sdk/aptos_sdk/account.py
ecosystem/python/sdk/aptos_sdk/account_address.py
ecosystem/python/sdk/aptos_sdk/asymmetric_crypto.py
ecosystem/python/sdk/aptos_sdk/authenticator.py
ecosystem/python/sdk/aptos_sdk/bcs.py
ecosystem/python/sdk/aptos_sdk/ed25519.py
ecosystem/python/sdk/examples/integration_test.py
ecosystem/python/sdk/examples/rotate_key.py
ecosystem/python/sdk/examples/simple_aptos_token.py
ecosystem/python/sdk/pyproject.toml

* Made a common asymmetric crypto key class
* Made it possible to rotate to multi keys

[python-sdk] improving usage around keys

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Releasing all the local testnet stuff.
Version bump.

Bump CLI to version 2.2.0

---

CODEOWNERS

[aptos protos] add codeowner to protos

---

aptos-move/block-executor/src/captured_reads.rs
aptos-move/block-executor/src/view.rs
aptos-move/mvhashmap/src/types.rs
third_party/move/move-vm/runtime/src/interpreter.rs

[trivial] followup comments from refactoring agg v2 exceptions

---

Cargo.lock
aptos-move/e2e-move-tests/Cargo.toml
aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-move-tests/src/tests/aggregator.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator.rs

in addition to fixing code, tests had [should_panic] which is incorrect.
I will recheck - but I think these fail on main too, as I think [should_panic] was mistakenly added back in https://github.com/aptos-labs/aptos-core/commit/3e29accd9d9aa2ca4802bcfa35847d13c3af7ccd

[small] Fix to check overflow/underflow in V1 aggregators, and throw appropriate exceptions

---

api/src/tests/transactions_test.rs
types/src/transaction/authenticator.rs

if the fee payer doesn't sign off on the fee payer, any signature can be used, which in turn means any signature can be used as the fee payer.
tests are updated to represent the new protocol....

[types] require that fee payer acknowledge that they are fee payer

---

Cargo.lock
Cargo.toml
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-generator-lib/src/account_generator.rs
crates/transaction-generator-lib/src/accounts_pool_wrapper.rs
crates/transaction-generator-lib/src/batch_transfer.rs
crates/transaction-generator-lib/src/call_custom_modules.rs
crates/transaction-generator-lib/src/lib.rs
crates/transaction-generator-lib/src/p2p_transaction_generator.rs
crates/transaction-generator-lib/src/publish_modules.rs
crates/transaction-generator-lib/src/transaction_mix_generator.rs
execution/executor-benchmark/Cargo.toml
execution/executor-benchmark/src/metrics.rs
execution/executor-benchmark/src/pipeline.rs
execution/executor-benchmark/src/transaction_committer.rs
execution/executor-benchmark/src/transaction_generator.rs

[Benchmark] Allow parallel txn generation when transaction generator is provided.

---

Cargo.lock
Cargo.toml
crates/transaction-emitter-lib/src/emitter/mod.rs
crates/transaction-generator-lib/src/account_generator.rs
crates/transaction-generator-lib/src/accounts_pool_wrapper.rs
crates/transaction-generator-lib/src/batch_transfer.rs
crates/transaction-generator-lib/src/call_custom_modules.rs
crates/transaction-generator-lib/src/lib.rs
crates/transaction-generator-lib/src/p2p_transaction_generator.rs
crates/transaction-generator-lib/src/publish_modules.rs
crates/transaction-generator-lib/src/transaction_mix_generator.rs
execution/executor-benchmark/Cargo.toml
execution/executor-benchmark/src/metrics.rs
execution/executor-benchmark/src/pipeline.rs
execution/executor-benchmark/src/transaction_committer.rs
execution/executor-benchmark/src/transaction_generator.rs

[CP][Previewnet2] Allow parallel txn generation when transaction generator is provided.

---

.github/workflows/execution-performance.yaml
.github/workflows/workflow-run-execution-performance.yaml
testsuite/single_node_performance.py

PR on top of igor/benchmark_suites (#9854)

Full single node performance (all tests) run on continuous

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Releasing the postgres persistence fix.
Release.

Bump CLI version to 2.2.1

---

api/src/context.rs
consensus/src/transaction_shuffler.rs
testsuite/forge-cli/src/main.rs

Tunings used for getting some big TPS numbers
https://github.com/aptos-labs/aptos-core/actions/runs/6489091369

[forge] Tunings for realistic_network_tuned_for_throughput

---

aptos-move/framework/aptos-framework/sources/aggregator_v2/aggregator_v2.spec.move

Adding aggregator_v2.spec.move file

Aggregator V2 Move Prover Spec File

---

state-sync/storage-service/server/src/metrics.rs

This PR updates the metric buckets for storage service request processing.

[State Sync] Update metric buckets for storage requests.

---

developer-docs-site/docs/nodes/validator-node/operator/connect-to-aptos-network.md

This PR updates the instructions for onboarding new validators and VFNs into `testnet` and `mainnet`. Specifically, it fixes the following:
- Removes unnecessary config overrides.
- Updates the docs to specify that new nodes should join the validator set first (before syncing and connecting to others).
- Reorganizes and relocates the `Verify Node Correctness` section.

[Dev Docs] Update instructions for connecting new validators/VFNs.

---

aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/scheduler.rs
aptos-move/block-executor/src/unit_tests/mod.rs

Add re-execution during try_commit if validation fails

---

aptos-move/aptos-aggregator/src/tests/types.rs
aptos-move/aptos-vm/src/natives.rs
aptos-move/block-executor/Cargo.toml
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/view.rs

to easily detect issues with exchange

[trivial][agg_v2] Generate IDs starting with random large number

---

aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/view.rs
aptos-move/mvhashmap/src/unit_tests/mod.rs
aptos-move/mvhashmap/src/versioned_data.rs
third_party/move/move-vm/runtime/src/loader/mod.rs

[small][agg_v2] Fix identifier mapping - layout caching, and MVHashMap storing

---

aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs

and have it be larger than token name

[trivial][agg v2] Limit string length as safety for now

---

consensus/src/dag/adapter.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_handler.rs
consensus/src/dag/dag_state_sync.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/order_rule.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/tests/dag_driver_tests.rs
consensus/src/dag/tests/dag_state_sync_tests.rs
consensus/src/dag/tests/dag_test.rs
consensus/src/dag/tests/integration_tests.rs
consensus/src/dag/tests/order_rule_tests.rs
consensus/src/dag/tests/types_test.rs
consensus/src/dag/types.rs

[dag] garbage collection

---

.github/workflows/replay-verify.yaml

Same as for the mainnet verify.

Lower the timeout of testnet replay-verify 14h->5h

---

consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_state_sync.rs
consensus/src/dag/dag_store.rs

[dag] support consensusdb recovery

---

aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/task.rs
aptos-move/block-executor/src/txn_last_input_output.rs

[small][agg_v2] Fix agg v2 error handling - Success can also have failure error codes

---

aptos-move/aptos-release-builder/data/release.yaml

This PR resets the `release.yaml` for v.1.8

Reset `release.yaml` for v1.8

---

aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm-types/src/tests/test_change_set.rs
aptos-move/aptos-vm-types/src/tests/test_output.rs
aptos-move/aptos-vm-types/src/tests/utils.rs
aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/move_vm_ext/session.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/task.rs

[execution] change HashMap to BTreeMap in VMChangeSet

---

Cargo.lock
Cargo.toml
crates/aptos-drop-helper/Cargo.toml
crates/aptos-drop-helper/src/lib.rs
crates/aptos-drop-helper/src/metrics.rs
execution/executor/Cargo.toml
execution/executor/src/components/block_tree/mod.rs
execution/executor/src/components/in_memory_state_calculator_v2.rs

On a super beefy machine the SMT dropping couldn't keep up, resulting in "mem leak".
unit test

aptos-drop-helper that drops asynchronously but with a bounded backlog

---

aptos-move/aptos-aggregator/src/aggregator_v1_extension.rs
aptos-move/aptos-aggregator/src/bounded_math.rs
aptos-move/aptos-aggregator/src/delayed_change.rs
aptos-move/aptos-aggregator/src/delayed_field_extension.rs
aptos-move/aptos-aggregator/src/delta_change_set.rs
aptos-move/aptos-aggregator/src/delta_math.rs
aptos-move/aptos-aggregator/src/lib.rs
aptos-move/aptos-aggregator/src/resolver.rs
aptos-move/aptos-aggregator/src/tests/types.rs
aptos-move/aptos-aggregator/src/types.rs
aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm-types/src/tests/test_change_set.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/natives.rs
aptos-move/aptos-vm/src/storage_adapter/executor_view_base.rs
aptos-move/block-executor/src/captured_reads.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/scheduler.rs
aptos-move/block-executor/src/unit_tests/mod.rs
aptos-move/block-executor/src/view.rs
aptos-move/e2e-move-tests/proptest-regressions/tests/aggregator_v2.txt
aptos-move/e2e-move-tests/src/tests/aggregator.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator_factory.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
aptos-move/framework/src/natives/aggregator_natives/context.rs
aptos-move/framework/src/natives/aggregator_natives/helpers_v1.rs
aptos-move/mvhashmap/src/versioned_delayed_fields.rs
types/src/aggregator.rs

Move DeltaHistory to CapturedReads

---

aptos-move/aptos-vm/src/block_executor/mod.rs
aptos-move/block-executor/src/errors.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/proptest_types/baseline.rs
aptos-move/block-executor/src/proptest_types/tests.rs
aptos-move/block-executor/src/txn_last_input_output.rs

[agg_v2] Fallback To Sequential on PanicError::CodeInvariantError

---

aptos-move/aptos-aggregator/src/utils.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/view.rs
aptos-move/mvhashmap/src/unit_tests/mod.rs
aptos-move/mvhashmap/src/versioned_data.rs
aptos-move/mvhashmap/src/versioned_group_data.rs
types/src/aggregator.rs

[agg_v2] Fix mistakenly overriding on concurrent set_base_value

---

Cargo.lock
Cargo.toml
aptos-node/Cargo.toml
aptos-node/src/lib.rs
aptos-node/src/services.rs
config/src/config/admin_service_config.rs
config/src/config/config_optimizer.rs
config/src/config/config_sanitizer.rs
config/src/config/mod.rs
config/src/config/node_config.rs
crates/aptos-admin-service/Cargo.toml
crates/aptos-admin-service/src/lib.rs
crates/aptos-admin-service/src/server/mod.rs
crates/aptos-admin-service/src/server/profiling.rs
crates/aptos-admin-service/src/server/utils.rs

[AdminService] Add an admin service to support some profiling functionalities on a running node.

---

crates/aptos-admin-service/src/server/mod.rs

Fix the local rust lint for MacOS.

---

.github/workflows/docker-build-test.yaml

Test Plan: workflow on PR passes

[gha] Upgrade the upgrade test

---

aptos-move/block-executor/src/view.rs

Unit test to check aggregator v2 Id value exchange is done properly in view.rs

Aggregator v2 unit tests

---

aptos-move/aptos-vm-types/src/change_set.rs
aptos-move/aptos-vm/src/aptos_vm.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs

Add MoveTypeLayout to resource group change set in VMChangeSet.

[Agg v2] Add MoveTypeLayout to resource group change set

---

aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move

Fix framework upgrade compatibility on main

---

state-sync/state-sync-driver/src/tests/storage_synchronizer.rs

This PR adds several small unit tests to verify the correct behaviour of the 3 stage pipeline in state sync. Specifically, we verify that an error is returned if any one of the 3 stages drops their corresponding receiver channel.

[State Sync] Add basic tests for 3 stage pipeline.

---

developer-docs-site/docs/concepts/events.md

The first doc introduce module events and deprecate the old one.
Will add an example once on mainnet.
pnpm start

[event v2] first doc

---

aptos-move/aptos-aggregator/src/aggregator_v1_extension.rs
aptos-move/aptos-aggregator/src/delayed_field_extension.rs
aptos-move/aptos-aggregator/src/delta_change_set.rs
aptos-move/aptos-aggregator/src/resolver.rs
aptos-move/aptos-aggregator/src/tests/types.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
aptos-move/framework/src/natives/aggregator_natives/context.rs

[agg_v2] Fixup of agg v2 tests, so they all pass

---

README.md

Add Twitter to README

---

Cargo.lock
testsuite/fuzzer/fuzz/Cargo.toml
third_party/move/move-binary-format/Cargo.toml
third_party/move/move-bytecode-verifier/fuzz/Cargo.toml
third_party/move/move-core/types/Cargo.toml

Arbitrary has been updated, fixing an issue that created problems with a new Fuzzer.
https://github.com/rust-fuzz/arbitrary/commit/b3e8342ea8dc8437aff3d3a1f5b95b7c02bf57f5

[fuzzing] Upgrade Arbitrary Dependency

---

storage/aptosdb/src/lib.rs

[Storage] Commit transaction batches one by one to avoid gap.

---

.github/workflows/docker-build-test.yaml

This test is currently broken, remove it from adding noise

[indexer] Remove broken test

---

aptos-move/move-examples/marketplace/sources/coin_listing.move

Fixed type parameter when purchasing at auction or listing.

[Bug] Fix purchase type in marketplace contract

---

.github/workflows/docker-build-test.yaml

Previous was 1.7.2 however 1.7.3 actually has an important fix

[gha] Upgrade the framework upgrade to 1.7.3

---

api/src/tests/transactions_test.rs
api/src/transactions.rs
third_party/move/move-vm/types/src/values/values_impl.rs

This is a cherry pick version for #10675
Added a new test for the error message.

[api] Add error message to simulation failure

---

aptos-node/Cargo.toml
crates/aptos-admin-service/Cargo.toml

Only use rstack-self on Linux.

Fix build error on Mac.

---

aptos-node/src/lib.rs

Fix aptos-node on Mac.

---

storage/aptosdb/src/state_store/mod.rs
storage/backup/backup-cli/src/backup_types/transaction/tests.rs
storage/backup/backup-cli/src/coordinators/replay_verify.rs
storage/db-tool/src/replay_verify.rs
testsuite/replay_verify.py
testsuite/replay_verify_run_local.py

The problem is the txn version can be smaller than snapshot version during restore. 
The existing code doesn't correctly get the snapshot version for restore case and cause the wrong snapshot used
manual test on previous failed cases and see it succeeded

[storage] fix a issue in getting latest snapshot version

---

api/README.md

Update README.md in api/

---

scripts/dev_setup.sh

Change the way we're installing nodejs to avoid some install failures. Use up to date install instructions from https://deb.nodesource.com/. The install scripts have been deprecated 
Also lint...
dev_setup.sh runs and CI passes, incl all steps that rely on nodejs installation

[dev-setup] update nodesource install

---

aptos-move/aptos-vm/src/aptos_vm.rs

Partially revert the change in #10518

[feature flag] Bring the feature flag SPONSORED_AUTOMATIC_ACCOUNT_CREATION back

---

aptos-move/framework/aptos-stdlib/doc/big_vector.md
aptos-move/framework/aptos-stdlib/doc/fixed_point64.md
aptos-move/framework/aptos-stdlib/doc/smart_vector.md
aptos-move/framework/aptos-stdlib/doc/type_info.md
aptos-move/framework/aptos-stdlib/sources/data_structures/big_vector.spec.move
aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.spec.move
aptos-move/framework/aptos-stdlib/sources/fixed_point64.move
aptos-move/framework/aptos-stdlib/sources/type_info.spec.move
aptos-move/framework/move-stdlib/doc/bit_vector.md
aptos-move/framework/move-stdlib/sources/bit_vector.move

This PR adds a few more specs to the type_info, bit_vector, smart_vector and big_vector module.

[Spec] Add more specs

---

crates/aptos-rest-client/src/lib.rs

client api supports get table item(json or bcs) at some specific version.
No test needed.

aptos-client: support get table item at a specific version

---

.github/workflows/coverage.yaml

Increase job time out as they started to take close to 10hrs to complete 
CI
https://github.com/aptos-labs/aptos-core/actions/runs/6741400957

[gha] increase code cov job time

---

.github/workflows/replay-verify.yaml
.github/workflows/workflow-run-replay-verify.yaml

[Workflow] Remove @main.

---

aptos-move/aptos-aggregator/src/delta_change_set.rs
aptos-move/aptos-aggregator/src/resolver.rs
aptos-move/aptos-aggregator/src/tests/types.rs
aptos-move/aptos-vm/src/data_cache.rs
aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
aptos-move/aptos-vm/src/natives.rs
aptos-move/aptos-vm/src/storage_adapter/executor_view_base.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/view.rs
aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs
aptos-move/framework/src/natives/aggregator_natives/helpers_v2.rs

[agg_v2] As a precaution - verify all DelayedFieldIDs that native code was called with

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml
crates/aptos/src/node/local_testnet/hasura_metadata.json
crates/aptos/src/node/local_testnet/indexer_api.rs

This PR updates the processor version and Hasura metadata.
```
cargo run -p aptos --release -- node run-local-testnet --force-restart --assume-yes --with-indexer-api
```
See that the local testnet starts up.

[CLI] Update processor version and Hasura metadata for local testnet

---

ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs

[Indexer GRPC] Additional logging

---

config/src/config/transaction_filter_type.rs
consensus/src/state_computer.rs
consensus/src/transaction_filter/mod.rs

This will be handy to turn on/off other filters at a particular point of time without causing execution divergence. 
Added UTs.

[Execution] Add timestamp based filtering to txn filter

---

crates/aptos-rosetta/src/types/objects.rs
testsuite/smoke-test/src/rosetta.rs

In block [104019798](https://explorer.aptoslabs.com/block/104019798?network=mainnet), the [tx](https://explorer.aptoslabs.com/txn/298831206/userTxnOverview?network=mainnet) has a `FeeStatement` event which send 50,000 refunds back to the [address](https://explorer.aptoslabs.com/account/0x210b6493881698bca67b15a7777625a3bac51944d9c7e66b77aa89c846ab3e0d?network=mainnet) but Rosetta failed to detect the funds. This PR is try to catch the refunds from the `FeeStatement`. Example output:
```
curl --location 'http://localhost:8082/block' --header "Content-Type: application/json" \
--data '{
"network_identifier": {"blockchain":"aptos","network":"mainnet"}, "block_identifier":{"index":104019798}}'
{"block":{"block_identifier":{"index":104019798,"hash":"mainnet-104019798"},"parent_block_identifier" …
```

[Rosetta] Add refund from FeeStatement events

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

Bumping the version to release a new CLI.
CI

Bump CLI version to 2.3.1

---

consensus/src/dag/dag_fetcher.rs
consensus/src/dag/dag_handler.rs
consensus/src/dag/dag_network.rs
consensus/src/dag/errors.rs
consensus/src/dag/tests/dag_network_test.rs
crates/aptos-bitvec/src/lib.rs

This PR improves the debuggability of the DAG Fetcher.
- It includes the responder along with the RPC response. 
- Includes a bitvec of missing targets when returning MissingNodes error.
- Bugfix: fixes an incorrect downcast.

[dag] fetcher debugging improvements

---

config/src/config/consensus_config.rs

[Consensus] Wait for full block config

---

aptos-node/src/lib.rs
config/src/config/state_sync_config.rs

This PR manually updates various node configs and ensures that storage sharding is enabled.

[Node Configs] Hard code specific features.

---

Cargo.lock
aptos-move/aptos-debugger/Cargo.toml
aptos-move/aptos-debugger/src/aptos_debugger.rs
aptos-move/aptos-debugger/src/common.rs
aptos-move/aptos-debugger/src/execute_past_transactions.rs
aptos-move/aptos-debugger/src/execute_pending_block.rs
aptos-move/aptos-debugger/src/lib.rs
consensus/Cargo.toml
consensus/src/lib.rs
consensus/src/util/db_tool.rs
consensus/src/util/mock_time_service.rs
consensus/src/util/mod.rs
crates/aptos-admin-service/src/server/consensus/mod.rs
crates/aptos-debugger/Cargo.toml
crates/aptos-debugger/src/lib.rs

Add a tool to dump block from consensus/quorum_store DBs.
Add a tool to execute uncommitted blocks in consensus/quorum_store DBs, at a given version.

[Tooling] Refactor aptos-debugger and add two new tools.

---

aptos-move/framework/aptos-framework/doc/event.md
aptos-move/framework/aptos-framework/doc/transaction_fee.md
aptos-move/framework/aptos-framework/sources/event.move
aptos-move/framework/aptos-framework/sources/event.spec.move
aptos-move/framework/aptos-framework/sources/transaction_fee.spec.move
aptos-move/move-examples/dao/nft_dao/sources/nft_dao_events.move
aptos-move/move-examples/defi/sources/locked_coins.move
aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move
aptos-move/move-examples/marketplace/sources/events.move
aptos-move/move-examples/marketplace/sources/fee_schedule.move
aptos-move/move-examples/message_board/sources/acl_message_board.move
aptos-move/move-examples/message_board/sources/cap_message_board.move
aptos-move/move-examples/mint_nft/4-Getting-Production-Ready/sources/create_nft_getting_production_ready.move
aptos-move/move-examples/my_first_dapp/move/sources/todolist.move
aptos-move/move-examples/post_mint_reveal_nft/sources/minting.move
aptos-move/move-examples/swap/sources/liquidity_pool.move
aptos-move/move-examples/tic-tac-toe/sources/TicTacToe.move
aptos-move/move-examples/token_objects/ambassador/sources/ambassador.move
aptos-move/move-examples/token_objects/knight/sources/knight.move
aptos-move/move-examples/veiled_coin/sources/veiled_coin.move

[event_v2] migrate move-examples to events v2

---

Cargo.lock
aptos-move/aptos-debugger/Cargo.toml
aptos-move/aptos-debugger/src/execute_pending_block.rs
crates/aptos-admin-service/Cargo.toml
crates/aptos-admin-service/src/server/consensus/mod.rs

Support bcs format in AdminService for /debug/consensus/blocks
Support running pending transactions by extracting them from a debug endpoint in AdminService.

[Tooling] Support running pending transactions by extracting them from a debug endpoint in AdminService.

---

ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs

* This is to lower the cache usage.

[indexer grpc] Reduce the cache size

---

ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs

This was landed into testnet and mainnet; now we merged into main.

Fix the cache size to avoid overloading.

---

developer-docs-site/docs/indexer/custom-processors/e2e-tutorial.md

Addresses part of https://github.com/aptos-labs/aptos-core/issues/9758.

[indexer-docs] Add custom indexer processor tutorial + some minor edits

---

aptos-move/framework/aptos-stdlib/doc/bls12381.md
aptos-move/framework/aptos-stdlib/doc/crypto_algebra.md
aptos-move/framework/aptos-stdlib/doc/ed25519.md
aptos-move/framework/aptos-stdlib/doc/multi_ed25519.md
aptos-move/framework/aptos-stdlib/doc/ristretto255.md
aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381.spec.move
aptos-move/framework/aptos-stdlib/sources/cryptography/crypto_algebra.move
aptos-move/framework/aptos-stdlib/sources/cryptography/crypto_algebra.spec.move
aptos-move/framework/aptos-stdlib/sources/cryptography/ed25519.spec.move
aptos-move/framework/aptos-stdlib/sources/cryptography/multi_ed25519.spec.move
aptos-move/framework/aptos-stdlib/sources/cryptography/ristretto255.spec.move

Add some specs for the module multi_ed25519, bls12381, ristretto255 and crypto_algebra.
Note: RistrettoPoint in ristretto255 and crypto_algebra use the handle so related functions are not specified in this PR.

[Spec] add specs for cryptographic modules

---

aptos-node/src/lib.rs
config/src/config/state_sync_config.rs

[State Sync] Hard code intelligent syncing

---

aptos-node/src/lib.rs
config/src/config/state_sync_config.rs

Output syncing mode.

---

config/src/config/storage_config.rs

[Storage][Pruner] Increase pruner batch size.

---

Cargo.lock
execution/executor-types/Cargo.toml
execution/executor-types/src/executed_chunk.rs
execution/executor/src/block_executor.rs
execution/executor/src/chunk_executor.rs
execution/executor/src/metrics.rs
storage/aptosdb/src/state_kv_db.rs
types/src/transaction/mod.rs

Send some drops to background.
Parallel verification.

[Execution] Add some metrics and optimize ChunkExecutor.

---

Cargo.lock
crates/aptos-admin-service/Cargo.toml
crates/aptos-admin-service/src/server/profiling.rs
crates/aptos-admin-service/src/server/thread_dump.rs

[AdminService] Minor improvements for admin service.

---

crates/transaction-emitter-lib/src/args.rs
crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/wrappers.rs

adding flag to adjust polling

---

scripts/windows_dev_setup.ps1

* Fixed the Prover installation script for Windows (Korean language)
* Upgraded the boogie version

Fixed the Prover installation script for Windows (Korean)

---

third_party/move/move-compiler-v2/src/bytecode_generator.rs
third_party/move/move-compiler-v2/src/file_format_generator/function_generator.rs
third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs
third_party/move/move-compiler-v2/tests/bytecode-generator/fields.exp
third_party/move/move-compiler-v2/tests/bytecode-generator/fields.move
third_party/move/move-compiler-v2/tests/checking/access_specifiers/access_err.exp
third_party/move/move-model/src/builder/exp_builder.rs

There are fixes how to deal with global resources in #10544, pulling them out to unblock testing.

[compiler v2] Pulls out fixes from #10544 to unblock testing

---

aptos-move/block-executor/src/view.rs

fix double borrow in view

---

crates/aptos-compression/src/lib.rs
crates/aptos-compression/src/metrics.rs

This PR updates the compression mode for state sync messages.

[Compression] Use high compression mode for state sync messages.

---

aptos-move/framework/src/natives/aggregator_natives/aggregator_v2.rs

safety limit for agg snapshot string size

---

aptos-move/aptos-release-builder/src/components/feature_flags.rs
aptos-move/framework/aptos-framework/doc/delegation_pool.md
aptos-move/framework/aptos-framework/sources/delegation_pool.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
aptos-move/framework/move-stdlib/doc/features.md
aptos-move/framework/move-stdlib/sources/configs/features.move
types/src/on_chain_config/aptos_features.rs

This PR adds the function to allow the delegation pool owner to update the operator commission percentage.
This implements the AIP-50: https://github.com/aptos-foundation/AIPs/pull/250

[Stake] Allows the delegation pool owner to update the operator commission percentage

---

testsuite/single_node_performance.py

we need to follow up but it's blocking lands

single-node-performance: update number for coin-transfer on native vm

---

state-sync/inter-component/event-notifications/src/lib.rs
state-sync/inter-component/event-notifications/src/tests.rs
state-sync/state-sync-driver/src/tests/driver.rs
state-sync/state-sync-driver/src/tests/storage_synchronizer.rs

Enable EventV2 subscription.
new UTs.

EventV2 subscription by type tag

---

crates/transaction-emitter-lib/src/emitter/account_minter.rs
crates/transaction-emitter-lib/src/emitter/transaction_executor.rs

1. sleep between tries to make source account, because the failure is possible other instances of the emitter trying to                                                                                                                   use the same sequence number   
2. similarly, for mint_to_root
3. do not retry on SEQUENCE_NUMBER_TOO_OLD -- won't succeed
4. configurable latency-poll-interval (stolen from @igor-aptos )

when making source account, randomly sleep between tries 

---

storage/aptosdb/src/lib.rs
storage/aptosdb/src/pruner/state_merkle_pruner/test.rs
storage/aptosdb/src/state_store/mod.rs
storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
storage/aptosdb/src/state_store/state_store_test.rs
storage/aptosdb/src/test_helper.rs

When restart, the snapshot version must have usage.

[Storage] Also write usage for the last checkpoint in the chunk.

---

consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_state_sync.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/tests/dag_driver_tests.rs
consensus/src/dag/tests/dag_state_sync_tests.rs
consensus/src/dag/tests/dag_test.rs
consensus/src/dag/tests/fetcher_test.rs
consensus/src/dag/tests/helpers.rs
consensus/src/dag/tests/order_rule_tests.rs
consensus/src/dag/tests/rb_handler_tests.rs
consensus/src/epoch_manager.rs
consensus/src/network.rs
consensus/src/payload_manager.rs
consensus/src/quorum_store/proof_coordinator.rs
consensus/src/quorum_store/quorum_store_builder.rs
consensus/src/quorum_store/tests/proof_coordinator_test.rs
consensus/src/test_utils/mock_quorum_store_sender.rs

[dag] support for Quorum Store

---

Cargo.lock
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/processor.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
ecosystem/indexer-grpc/indexer-grpc-utils/Cargo.toml
ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs

Add timestamp logging and metrics

[indexer grpc] Timestamp metrics

---

consensus/consensus-types/src/block.rs
consensus/consensus-types/src/executed_block.rs
consensus/src/block_storage/block_store.rs
consensus/src/dag/adapter.rs
consensus/src/execution_pipeline.rs
consensus/src/experimental/execution_schedule_phase.rs
consensus/src/experimental/ordering_state_computer.rs
consensus/src/experimental/tests/execution_phase_tests.rs
consensus/src/experimental/tests/test_utils.rs
consensus/src/state_computer.rs
consensus/src/state_replication.rs
consensus/src/test_utils/mock_state_computer.rs

[Execution] Move the transaction shuffling and dedup to the block preparation phase

---

config/src/config/dag_consensus_config.rs
config/src/config/quorum_store_config.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_state_sync.rs
consensus/src/epoch_manager.rs
consensus/src/experimental/buffer_manager.rs
testsuite/forge-cli/src/main.rs
testsuite/testcases/src/dag_onchain_enable_test.rs
testsuite/testcases/src/lib.rs
testsuite/testcases/src/quorum_store_onchain_enable_test.rs

Adds a Forge test to test onchain config change to enable DAG and makes adds DAG-specific QS configs.

[dag][forge] dag onchain enable test

---

config/src/config/dag_consensus_config.rs
consensus/src/epoch_manager.rs
types/src/on_chain_config/consensus_config.rs

DAG Configs and debugging logs for Previewnet 2

[dag] previewnet configs

---

developer-docs-site/docs/guides/system-integrators-guide.md

[link*]Update system-integrators-guide.md

---

config/src/config/dag_consensus_config.rs
consensus/src/dag/bootstrap.rs
consensus/src/dag/dag_driver.rs
consensus/src/dag/dag_store.rs
consensus/src/dag/errors.rs
consensus/src/dag/rb_handler.rs
consensus/src/dag/round_state.rs
consensus/src/dag/tests/rb_handler_tests.rs

[dag] pipeline backpressure

---

aptos-move/e2e-testsuite/src/tests/execution_strategies.rs

Reported in https://github.com/aptos-labs/aptos-core/issues/10644, might be a less involved fix than https://github.com/aptos-labs/aptos-core/pull/10648
@so-schen : thanks for reporting! please let us know if this addresses the issue.

[e2e testsuite] Fix execution strategy test

---

Cargo.lock
config/src/config/execution_config.rs
config/src/config/mod.rs
config/src/config/transaction_filter_type.rs
consensus/Cargo.toml
consensus/src/consensus_provider.rs
consensus/src/epoch_manager.rs
consensus/src/lib.rs
consensus/src/state_computer.rs
consensus/src/transaction_filter/mod.rs

[Execution] Add support for configurable transaction filtering (#10742)

---

third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_old.exp
third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_old.move
third_party/move/move-compiler-v2/tests/checking/specs/move_function_in_spec.exp
third_party/move/move-compiler-v2/tests/checking/specs/move_function_in_spec.move
third_party/move/move-compiler-v2/tests/checking/typing/conditional_global_operations.exp
third_party/move/move-compiler-v2/tests/checking/typing/constant_folding.exp
third_party/move/move-compiler-v2/tests/checking/typing/constant_folding.move
third_party/move/move-compiler-v2/tests/checking/typing/move_from_type_argument.exp
third_party/move/move-compiler-v2/tests/checking/typing/move_from_type_argument.move
third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_unpack.exp
third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_unpack_assign.exp
third_party/move/move-compiler-v2/tests/file-format-generator/unpack_generic_struct.exp
third_party/move/move-compiler-v2/tests/file-format-generator/unpack_generic_struct.move
third_party/move/move-model/bytecode/src/lib.rs
third_party/move/move-model/src/builder/exp_builder.rs
third_party/move/move-model/src/builder/module_builder.rs

This PR 
- adds test cases for the issue #9330,  #10883, #10884, #10920 and #10960 
- add fix to close #10883, close #10920 and close #10960.

Add some unit tests and bug fixes for compiler v2

---

Cargo.lock
Cargo.toml
aptos-node/Cargo.toml
aptos-node/src/lib.rs
aptos-node/src/services.rs
config/src/config/admin_service_config.rs
config/src/config/mod.rs
config/src/config/node_config.rs
consensus/Cargo.toml
consensus/src/consensus_provider.rs
consensus/src/lib.rs
consensus/src/persistent_liveness_storage.rs
consensus/src/quorum_store/mod.rs
consensus/src/quorum_store/quorum_store_db.rs
consensus/src/quorum_store/types.rs
consensus/src/test_utils/mock_storage.rs
consensus/src/util/db_tool.rs
consensus/src/util/mod.rs
crates/aptos-admin-service/Cargo.toml
crates/aptos-admin-service/src/lib.rs
crates/aptos-admin-service/src/server/consensus/mod.rs
crates/aptos-admin-service/src/server/mod.rs
crates/aptos-admin-service/src/server/profiling.rs
crates/aptos-admin-service/src/server/thread_dump.rs
crates/aptos-admin-service/src/server/utils.rs
docker/builder/builder.Dockerfile
scripts/dev_setup.sh

[CP] AdminService.

---

aptos-move/framework/aptos-stdlib/doc/simple_map.md
aptos-move/framework/aptos-stdlib/sources/simple_map.spec.move

- Added the spec for `simple_map::new` to unblock the situation where Prover fails when the function is called

[Spec] Added the spec for `simple_map::new`

---

config/src/config/transaction_filter_type.rs
consensus/src/state_computer.rs
consensus/src/transaction_filter/mod.rs

 [Execution] Add timestamp based filtering to txn filter

---

execution/executor/src/components/chunk_output.rs
execution/executor/src/metrics.rs

Cherry-pick output size counter (from #10762 and 11023)

---

aptos-node/Cargo.toml

Fix build on Mac.

---

aptos-move/framework/aptos-token-objects/doc/token.md
aptos-move/framework/aptos-token-objects/sources/token.move

fix typo in create_numbered_token

---

aptos-move/framework/aptos-token-objects/doc/token.md
aptos-move/framework/aptos-token-objects/sources/token.move

[tentative] Cherry-pick create numbered token into v1.8

---

developer-docs-site/docs/guides/sponsored-transactions.md
developer-docs-site/docusaurus.config.js
developer-docs-site/sidebars.js

[docs] basic doc on sponsored transactions

---

execution/executor-benchmark/src/lib.rs
execution/executor-benchmark/src/pipeline.rs
execution/executor/src/components/chunk_output.rs
execution/executor/src/metrics.rs

txn output counter as historgram

---

testsuite/single_node_performance.py

recalibrating for recent perf improvements

---

third_party/move/tools/move-cli/src/base/test.rs

This PR adds support of running V2 for framework unit test.

Add support of framework unit test for compiler V2

---

Cargo.lock
crates/aptos/CHANGELOG.md
crates/aptos/Cargo.toml

[CLI] Bump version to 2.3.2

---

aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs

Change `assert_layout_matches` function to match layouts sporadically.

---

developer-docs-site/docs/indexer/legacy/index.md

updated deprecation policy for legacy indexer

[docs] Update legacy indexer index

---

config/src/config/consensus_config.rs
consensus/consensus-types/src/block_retrieval.rs
consensus/src/block_storage/sync_manager.rs
consensus/src/epoch_manager.rs
consensus/src/network.rs
consensus/src/payload_manager.rs
consensus/src/recovery_manager.rs
consensus/src/round_manager.rs
consensus/src/state_computer.rs

[consensus] override block retrieval limit with quorum store and make quorum store notify non blocking

---

consensus/src/epoch_manager.rs
consensus/src/experimental/buffer_manager.rs
consensus/src/experimental/decoupled_execution_utils.rs
consensus/src/experimental/tests/buffer_manager_tests.rs
consensus/src/recovery_manager.rs
consensus/src/round_manager.rs
consensus/src/round_manager_fuzzing.rs
consensus/src/round_manager_test.rs

[buffer mananger] move message verification to bounded executor

---

aptos-move/framework/aptos-framework/doc/staking_proxy.md
aptos-move/framework/aptos-framework/sources/staking_proxy.spec.move

Fix the prover CI timeout issue

[Prover][trivial] fix prover CI

---

developer-docs-site/docs/sdks/ts-sdk-v2/index.md
developer-docs-site/docs/sdks/ts-sdk/index.md

Remove reference to sdk v2.0.0

---

Cargo.lock
consensus/consensus-types/Cargo.toml
consensus/consensus-types/src/executed_block.rs
consensus/consensus-types/src/lib.rs
consensus/consensus-types/src/randomness.rs
consensus/src/lib.rs
consensus/src/rand/dkg/mod.rs
consensus/src/rand/mod.rs
consensus/src/rand/rand_gen/block_queue.rs
consensus/src/rand/rand_gen/mod.rs

[rand] initial commit with block queue 

---

third_party/move/move-compiler-v2/src/inliner.rs
third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_unpack.exp
third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_single_unpack_assign.exp
third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_threaded_unpack.exp
third_party/move/move-compiler-v2/tests/checking/typing/type_variable_join_threaded_unpack_assign.exp
third_party/move/move-compiler-v2/tests/file-format-generator/unpack_generic_struct.exp
third_party/move/move-compiler-v2/tests/file-format-generator/unpack_generic_struct.move
third_party/move/move-model/src/ast.rs
third_party/move/move-model/src/builder/exp_builder.rs
third_party/move/move-model/src/builder/module_builder.rs
third_party/move/move-model/src/exp_rewriter.rs

This PR: 
- Extend ExpWriter to support rewriting patterns
- Close #11099 by rewriting the block pattern with type instantiation.

[Compiler-v2] Fix issue 11099

---

consensus/src/rand/rand_gen/mod.rs
consensus/src/rand/rand_gen/network_messages.rs
consensus/src/rand/rand_gen/reliable_broadcast_state.rs
consensus/src/rand/rand_gen/types.rs

[rand_gen] add augmented data and network messages

---

developer-docs-site/docs/tutorials/first-transaction.md

This PR updates "you first transaction" example to use the new sdk
https://deploy-preview-11200--aptos-developer-docs.netlify.app/tutorials/your-first-transaction

Update you first transaction example to use the new sdk

---

developer-docs-site/docs/tutorials/your-first-nft.md
developer-docs-site/scripts/additional_dict.txt

PR to update "Your First NFT" Tutorial to use the new sdk.
https://deploy-preview-11207--aptos-developer-docs.netlify.app/tutorials/your-first-nft

Update nft example to use the new sdk

---

third_party/move/move-compiler-v2/src/inliner.rs
third_party/move/move-compiler-v2/tests/file-format-generator/unpack_generic_struct.exp
third_party/move/move-compiler-v2/tests/file-format-generator/unpack_generic_struct.move
third_party/move/move-compiler-v2/tests/file-format-generator/vector.exp
third_party/move/move-compiler-v2/tests/file-format-generator/vector.move

close #11210 by implementing a non-recursive call version of rewrite_pattern in inliner.rs.

[Compiler-v2] Fix #11210

---

consensus/src/rand/rand_gen/mod.rs
consensus/src/rand/rand_gen/storage/db.rs
consensus/src/rand/rand_gen/storage/interface.rs
consensus/src/rand/rand_gen/storage/mod.rs
consensus/src/rand/rand_gen/storage/schema.rs
consensus/src/rand/rand_gen/types.rs

[rand_gen] add storage

---

aptos-move/framework/aptos-framework/sources/multisig_account.move
aptos-move/framework/aptos-stdlib/doc/math_fixed.md
aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381_algebra.move
aptos-move/framework/aptos-stdlib/sources/math_fixed.move
aptos-move/framework/aptos-stdlib/tests/fixedpoint64_tests.move

Revert constant related changes in #11072 and #11101.
Land this after #11128.

[trivial] Add constants back in the framework code

---

storage/db-tool/src/lib.rs
storage/db-tool/src/replay_verify.rs

On my linux box,  I can see outer retry works as expected.
Need to print more info to investigate what happened

[storage] debugging no retry

---

consensus/src/rand/rand_gen/mod.rs
consensus/src/rand/rand_gen/reliable_broadcast_state.rs
consensus/src/rand/rand_gen/storage/db.rs
consensus/src/rand/rand_gen/storage/interface.rs
consensus/src/rand/rand_gen/storage/mod.rs
consensus/src/rand/rand_gen/storage/schema.rs
consensus/src/rand/rand_gen/types.rs

[rand_gen] add rb state

---

consensus/src/rand/rand_gen/network_messages.rs

[rand_gen] use EnumConversion macro

---

testsuite/replay_verify.py

[storage] try on unknown failure cases and increase retry count

---

aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
aptos-move/e2e-move-tests/src/tests/string_args.rs

This PR fixes how we validate string arguments to ensure the
length of a string is always upper-bounded.
Unit tests.

[vm] Fix string arg validation

---

aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-tests/src/executor.rs

- add support to modify_gas_scaling (to be able to assert on smaller gas differences)
- add more granular comparison of txn outputs between sequential and parallel mode ( assert_outputs_equal ) for easier debugging

MoveHarness improvements

---

consensus/consensus-types/src/randomness.rs
consensus/src/rand/rand_gen/aug_data_store.rs
consensus/src/rand/rand_gen/mod.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/storage/db.rs
consensus/src/rand/rand_gen/storage/in_memory.rs
consensus/src/rand/rand_gen/storage/interface.rs
consensus/src/rand/rand_gen/storage/mod.rs
consensus/src/rand/rand_gen/types.rs

[rand gen] add aug data store

---

consensus/consensus-types/src/randomness.rs
consensus/src/network.rs
consensus/src/rand/rand_gen/aug_data_store.rs
consensus/src/rand/rand_gen/mod.rs
consensus/src/rand/rand_gen/network_messages.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/storage/db.rs
consensus/src/rand/rand_gen/storage/in_memory.rs
consensus/src/rand/rand_gen/storage/interface.rs
consensus/src/rand/rand_gen/storage/mod.rs
consensus/src/rand/rand_gen/types.rs

[rand_gen] RandManager 2/n

---

ecosystem/typescript/sdk/README.md

Add a note indicating the ts sdk on this repo is the legacy ts sdk

---

consensus/src/pipeline/buffer_item.rs
consensus/src/pipeline/buffer_manager.rs
consensus/src/pipeline/commit_reliable_broadcast.rs
consensus/src/rand/rand_gen/block_queue.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/reliable_broadcast_state.rs
consensus/src/rand/rand_gen/storage/db.rs
consensus/src/rand/rand_gen/storage/in_memory.rs
consensus/src/rand/rand_gen/storage/interface.rs
consensus/src/rand/rand_gen/types.rs
crates/reliable-broadcast/src/lib.rs

[rand gen] refactor rand store api

---

config/src/config/indexer_grpc_config.rs
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/processor.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/localnet_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs

* Put metrics and logging in a helper function to make sure we have consistent instrumentation everywhere and make experimentation easier
* Gate logging behind feature flag so we can land this PR without worrying about perf

[indexer grpc] Logging

---

aptos-move/framework/aptos-framework/doc/managed_coin.md
aptos-move/framework/aptos-framework/sources/managed_coin.spec.move
third_party/move/move-prover/move-docgen/src/docgen.rs

Add support for generating a high level requirements table in the documentation file
the `managed_coin.spec.move` is a sample input and `managed_coin.md` is the expected output.

support high level requirements table for document generation

---

config/src/config/indexer_grpc_config.rs
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/processor.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/localnet_data_service.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs

* [indexer grpc] Add steps logging
* Create helper functions for metrics collection and logging
Set enable_verbose_logging to true and see that there are logs ([link](https://cloud.us.humio.com/k8s/search?live=false&query=k8s.namespace%20%3D%20%22indexer-grpc-devnet%22%0A%7C%20rename(%5B%5Bdata.service_type%2C%20fields.service_type%5D%2C%20%5Bdata.step%2C%20fields.step%5D%5D)%20%2F%2F%20Rename%20the%20fields%20in%20fullnode%0A%7C%20in(fields.service_type%2C%20values%3D%5B%22data_service%22%2C%20%22cache_worker%22%2C%20%22file_worker%22%2C%20%22indexer_fullnode%22%5D)%0A%7C%20fields.step%20%3D%20*%0A%7C%20format(format%3D%22service%3D%25s%2C%20step%3D%25s%22%2C%20field%3D%5Bfields.service_type%2C%20fields.step%5D%2C%20as%3D%22step%22)%0A%7C%20timeChart(series%3Dstep%2C%20function%3Dmax(fiel …

[indexer grpc] Logging (#11062)

---

consensus/src/network.rs
consensus/src/pipeline/buffer_item.rs
consensus/src/pipeline/buffer_manager.rs
consensus/src/pipeline/commit_reliable_broadcast.rs
consensus/src/rand/rand_gen/aug_data_store.rs
consensus/src/rand/rand_gen/block_queue.rs
consensus/src/rand/rand_gen/network_messages.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/reliable_broadcast_state.rs
consensus/src/rand/rand_gen/storage/db.rs
consensus/src/rand/rand_gen/storage/in_memory.rs
consensus/src/rand/rand_gen/storage/interface.rs
consensus/src/rand/rand_gen/types.rs
crates/reliable-broadcast/src/lib.rs

[rand gen] RandManager 3/n receiver part

---

consensus/src/block_storage/sync_manager.rs
consensus/src/epoch_manager.rs
consensus/src/recovery_manager.rs

[consensus] prefetch quorum store data during catch up

---

aptos-move/aptos-gas-schedule/src/ver.rs

Remove no longer necessary gas feature description

---

aptos-move/vm-genesis/src/lib.rs

enable the commission change in delegation pool in the devnet

[staking] enable the commission change in delegation pool in the devnet

---

aptos-move/block-executor/src/captured_reads.rs
aptos-move/block-executor/src/executor.rs
aptos-move/block-executor/src/limit_processor.rs
aptos-move/block-executor/src/proptest_types/types.rs
aptos-move/block-executor/src/view.rs
types/src/block_executor/config.rs
types/src/on_chain_config/execution_config.rs
types/src/transaction/mod.rs
types/src/transaction/signature_verified_transaction.rs

Account for transaction size when computing block output (for block limit purposes)

---

aptos-move/block-executor/src/limit_processor.rs

fix block output limit hit counter

---

ecosystem/typescript/sdk/CHANGELOG.md
ecosystem/typescript/sdk/package.json
ecosystem/typescript/sdk/src/version.ts

This release mainly updates dependencies to their final state, and no further updates are expected of this SDK.  All future SDK updates will be to the new TS SDK.

[ts-sdk] Release v1.21.0

---

aptos-move/block-executor/src/limit_processor.rs
types/src/block_executor/config.rs
types/src/on_chain_config/execution_config.rs

Improved block gas limit, including changes for gas recalibration

---

aptos-move/framework/aptos-framework/doc/managed_coin.md
third_party/move/move-prover/move-docgen/src/docgen.rs

1. Add support for multiple tags
2. Fix anchor issue

[docgen] Update table generation

---

aptos-move/aptos-vm/src/aptos_vm.rs

for kept aborted transaction we need to filter away the info, this was accidentally clipped in the previous pr.

[movevm] filter away abort info

---

aptos-move/aptos-release-builder/data/release.yaml
types/src/on_chain_config/execution_config.rs

release yaml for aip 57

---

aptos-move/framework/aptos-framework/doc/aptos_account.md
aptos-move/framework/aptos-framework/doc/aptos_governance.md
aptos-move/framework/aptos-framework/doc/block.md
aptos-move/framework/aptos-framework/doc/coin.md
aptos-move/framework/aptos-framework/doc/governance_proposal.md
aptos-move/framework/aptos-framework/doc/managed_coin.md
aptos-move/framework/aptos-framework/doc/staking_config.md
aptos-move/framework/aptos-framework/doc/state_storage.md
aptos-move/framework/aptos-framework/doc/transaction_fee.md
aptos-move/framework/aptos-framework/doc/transaction_validation.md
aptos-move/framework/aptos-framework/sources/aptos_account.spec.move
aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
aptos-move/framework/aptos-framework/sources/block.spec.move
aptos-move/framework/aptos-framework/sources/coin.spec.move
aptos-move/framework/aptos-framework/sources/configs/staking_config.spec.move
aptos-move/framework/aptos-framework/sources/governance_proposal.spec.move
aptos-move/framework/aptos-framework/sources/managed_coin.spec.move
aptos-move/framework/aptos-framework/sources/state_storage.spec.move
aptos-move/framework/aptos-framework/sources/transaction_fee.spec.move
aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move

Fix minor errors across 10 high level requirement tables.

Fix high level requirement tables

---

consensus/consensus-types/src/randomness.rs
consensus/src/block_storage/tracing.rs
consensus/src/epoch_manager.rs
consensus/src/pipeline/buffer_manager.rs
consensus/src/pipeline/ordering_state_computer.rs
consensus/src/pipeline/tests/buffer_manager_tests.rs
consensus/src/rand/rand_gen/block_queue.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/types.rs

[rand gen] RandManager 5/n

---

consensus/src/dag/types.rs
consensus/src/network.rs
consensus/src/pipeline/commit_reliable_broadcast.rs
consensus/src/rand/rand_gen/network_messages.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/reliable_broadcast_state.rs
consensus/src/rand/rand_gen/storage/interface.rs
consensus/src/rand/rand_gen/types.rs
crates/reliable-broadcast/src/lib.rs
crates/reliable-broadcast/src/tests.rs

[rand gen] impl pull based share aggregation

---

testsuite/forge-cli/src/main.rs

This PR makes some small tweaks to various forge-stable tests (to help address flaky test failures).

[Forge] Small tweaks to help unblock flaky tests.

---

ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/main.rs
ecosystem/indexer-grpc/indexer-grpc-file-store/src/processor.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
ecosystem/indexer-grpc/indexer-grpc-server-framework/src/lib.rs
ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs

1. Add logging for each batch processed by cache worker and file store worker
2. Refactor some logic in cache worker
3. Fix TPS metrics
4. Make duration logging mutually exclusive everywhere

Cache worker logging

---

testsuite/forge-cli/src/main.rs

This PR increases the state sync chunk sizes for the validators in the `realistic_network_tuned_for_throughput` test. I [previously](https://github.com/aptos-labs/aptos-core/pull/11406) bumped these for the fullnodes (but forgot to do so for the validators, which is required because they're currently just returning the smaller data chunks 😄). 

[Forge] Increase state sync chunk sizes for validators and fullnodes.

---

config/src/config/admin_service_config.rs

[AdminService] Use the snake_case in config to make it consistent with other configs.

---

aptos-move/e2e-move-tests/src/aggregator_v2.rs
aptos-move/e2e-move-tests/src/harness.rs
aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs

test that it is the same for cases where enabled and disabled should produce the same gas charges
for cases where gas charges should be different - assert comparison fails.

improved agg_v2 tests - add comparison between enabled and disabled

---

testsuite/forge-cli/src/main.rs

Fix workload sweep forge test

---

config/src/config/admin_service_config.rs

[CP][AdminService] Use the snake_case in config to make it consistent with other configs.

---

testsuite/forge-cli/src/main.rs

[cherry-pick] Fix workload sweep forge test (#11370)

---

types/src/on_chain_config/execution_config.rs

Tune block limits for expiration fix

---

types/src/on_chain_config/execution_config.rs

[cp for 1.9] Tune block limits for expiration fix

---

consensus/src/rand/rand_gen/aug_data_store.rs
consensus/src/rand/rand_gen/network_messages.rs
consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/types.rs

[rand gen] adjust interface and support persist/re-use aug data

---

storage/aptosdb/src/db/include/aptosdb_reader.rs
storage/aptosdb/src/db/include/aptosdb_writer.rs
storage/aptosdb/src/db/mod.rs
storage/aptosdb/src/db_options.rs
storage/aptosdb/src/schema/block_by_version/mod.rs
storage/aptosdb/src/schema/block_by_version/test.rs
storage/aptosdb/src/schema/mod.rs

Add block by version index.
Use it for some block APIs iff sharding is enabled, otherwise still use the old code path.
Will refactor and add more tests in batch for sharding in a separate PR.

[Storage] Add block_by_version index.

---

consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/types.rs
crates/reliable-broadcast/src/lib.rs

[rand gen] only request for missing shares

---

third_party/move/move-compiler-v2/src/file_format_generator/module_generator.rs

This was missing, leading to LOOKUP_FAILURE errors for friend modules.
Test plan: manually tested against unit tests in aptos-stdlib. Unfortunately the txn framework doesn't support module bundles. (Module friends need to published at once.)
Close #11485

[compiler v2] Generate friend handles in CompiledModule

---

consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs
consensus/src/rand/rand_gen/reliable_broadcast_state.rs
consensus/src/rand/rand_gen/storage/db.rs
consensus/src/rand/rand_gen/storage/in_memory.rs
consensus/src/rand/rand_gen/storage/interface.rs
consensus/src/rand/rand_gen/storage/schema.rs
consensus/src/rand/rand_gen/test_utils.rs
consensus/src/rand/rand_gen/types.rs
crates/reliable-broadcast/src/lib.rs

[rand gen] remove trait Proof and RandStorage for the new pulling model

---

consensus/src/rand/rand_gen/rand_manager.rs
consensus/src/rand/rand_gen/rand_store.rs

[rand gen] split rand store and block queue to make share aggregation async

---

aptos-move/framework/aptos-framework/doc/multisig_account.md
aptos-move/framework/aptos-framework/multisig_account.spec.move
aptos-move/framework/aptos-framework/sources/multisig_account.spec.move

- Added the specs for the view functions of the multisig_account module
- Moved the spec file to the right place

[spec] the specs of the view functions of the multisig_account module

---

aptos-move/block-executor/src/counters.rs

Adjust buckets for gas histogram counters

---

config/src/config/consensus_config.rs
consensus/src/counters.rs
consensus/src/round_manager.rs

Make pipeline backpressure more aggressive

---

aptos-move/block-executor/src/counters.rs

[cherry-pick] Adjust buckets for gas histogram counters (#11547)
